{
    "title": "CarsX: New & Used Cars",
    "description": "Get ready to rev up your car shopping experience! We\u2019ve made it super fun and easy with our Tinder-like swipe feature. Say goodbye to boring searches\u2014now you can swipe your way to your next ride with a beautiful, clean, and smooth interface.\r\n\r\nWant to know more about a car? Curious about the manufacturer or want to read some reviews? Just ASK AI! Plus, meet ROBODEAL\u2122, your new best friend that shows you how a vehicle\u2019s price stacks up against similar models within 100 miles.\r\n\r\nWith over 2 million vehicles to explore in America, finding your dream car has never been easier! Use our easy 1-tap filters and swipe right to add your favorites.\r\n\r\nThanks for letting us be a part of your exciting journey!",
    "descriptionHTML": "Get ready to rev up your car shopping experience! We\u2019ve made it super fun and easy with our Tinder-like swipe feature. Say goodbye to boring searches\u2014now you can swipe your way to your next ride with a beautiful, clean, and smooth interface.<br><br>Want to know more about a car? Curious about the manufacturer or want to read some reviews? Just ASK AI! Plus, meet ROBODEAL\u2122, your new best friend that shows you how a vehicle\u2019s price stacks up against similar models within 100 miles.<br><br>With over 2 million vehicles to explore in America, finding your dream car has never been easier! Use our easy 1-tap filters and swipe right to add your favorites.<br><br>Thanks for letting us be a part of your exciting journey!",
    "summary": "Shop Cars With AI",
    "installs": "5,000+",
    "minInstalls": 5000,
    "realInstalls": 7134,
    "score": 4.032258,
    "ratings": 31,
    "reviews": 34,
    "histogram": [
        5,
        3,
        0,
        1,
        22
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "CarsX",
    "developerId": "CarsX",
    "developerEmail": "maidenlabsllc@gmail.com",
    "developerWebsite": "https://www.carsx.ai/",
    "developerAddress": null,
    "privacyPolicy": "https://www.carsx.ai/privacy",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/g-tkUTtJ7lgdZKfvL1RjJUzvTT4XrjabFEpClnuyvpQd1-wkzwZS9PGfu_yiUpxZJhY",
    "headerImage": "https://play-lh.googleusercontent.com/i_YLyZTTDo3DH3r2wgTRQz-seYRgFebP_a9rnzcDENKK9XK7G7_EO5MBcCukIi1I7A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/baD0UutCHZEAQ-4ehYhyVzZHu3UMqCUWwprOtJ0gJzni1y4JYttrbpt-zJFfEqQkOQ",
        "https://play-lh.googleusercontent.com/2rFTBCsGgCOXK_Onjby1Y5XS7fKvuYR5GbzqBFfNkGOtIOMD3Re6hJJt5eya2Ep6qQ",
        "https://play-lh.googleusercontent.com/EhfPp_LXb9Fm6qyBnbhrmNUym0CC4HkgDkMbdoxLXCXvotuXKGy6f_jgqNW5YewRvcBP",
        "https://play-lh.googleusercontent.com/AkNBmYAMYGUmJWcYkDkMOaWHiovLZGpy4OLBJcKRkpdt_uwURT68QbVNssIW3gBLREM",
        "https://play-lh.googleusercontent.com/xyN09Pi6dzxEfH2GA2aLNpbfYqBDmIL2wFOnve0nKkjDAznNSU2qcMWFlMon4QaIFP4",
        "https://play-lh.googleusercontent.com/Bbv-1A4eCSCJtTVGRxjImH6628iZUjNzibhrGXXU0iNu8VYbUPCWE_FYO0rjzLX4bMWb",
        "https://play-lh.googleusercontent.com/RL0f9up7nefoaBu9l8VXCzmhsu2cDJrG3193PQkyAOeS_1GbUNx10EI-lEd8ORFAHOY",
        "https://play-lh.googleusercontent.com/nCsXGtwAev_LXihPm2vQYaDqrU4BFhAkHNZtepN2EHbXlLbli9upHWPzuHSiInksTwDo",
        "https://play-lh.googleusercontent.com/BB5Iypow7ZL8hDkG4M-zibFWLNSqPFqgyQIYdn6QdK247Bk23at93b74e_TmcpFbUd0",
        "https://play-lh.googleusercontent.com/oh26aaVOlMX7IHJV6_b4YmCs-317HGcfeeJp6Pnsv2b4MGSZ_DXTNntmpfJbKv_kQEw",
        "https://play-lh.googleusercontent.com/vUMV7m4M_uNCIMJvRkJxWisgoFZUdMaY6AIOr5SfKEmqHt95m4ZGBpZcENQXMdBdDV0",
        "https://play-lh.googleusercontent.com/qBNcLN3tkoCIqL4VONDRZNZ_exNKcpReOV3-70fnRMvnyf0I3-IQQ8lJLVh2IcetPHQ",
        "https://play-lh.googleusercontent.com/KIm-rxC_x4zwu_Mw0-a2x_asd94ZXTHdTD_iDlH7JAfApuTohJEBTHJa0KstyTAQ7mk",
        "https://play-lh.googleusercontent.com/gjMhJs6uljpsAJ3i-7Il17dQYuf9p_l0uIOhFeczMgJF7fRJlpcr6teqFb6k9Nnd5A",
        "https://play-lh.googleusercontent.com/OH7gEb08nKzBJe2X8OZPVziz3A1kNqQFMveWaFiSAmxDaGJAdn62ALOJ2o-Y4jYE0A",
        "https://play-lh.googleusercontent.com/vC-mCDvHDjCdgOXBfekVP7IswMaKRI7rV0m78JSqWl2GR7JKOjMnfNbyddE2_rMVLtI",
        "https://play-lh.googleusercontent.com/DSlyh2KwBMFl0BeuW6I8cmzOUr27v0-twlHXQvOcj9gFRbJmtr8i-inbJ7BjLqjokqEH",
        "https://play-lh.googleusercontent.com/_w75yZMwcvKOsPXQT1cf3jCRuTdLE-NtMtYWIKKFRKUr0E_wvwMDQud0MKeRHOZCwlo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 26, 2024",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731953592,
    "version": "1.11.0",
    "comments": [],
    "appId": "ai.carsx.app",
    "url": "https://play.google.com/store/apps/details?id=ai.carsx.app&hl=en&gl=us"
}