{
    "title": "Howbout: update your friends",
    "description": "Howbout\u2019s the social app to keep up with friends. Socials aren't for friends anymore, so we made an app for updates you actually care about - how your friends spend their time.\r\n\r\nOver 4 million people on Howbout, and they\u2019re all hot.\u2026\r\n\r\n\u2026\r\n\r\nSHARE CALENDARS\r\n- Let friends know what\u2019s going on by adding it to the calendar\r\n\r\nFRIENDS-ONLY ACTIVITY FEED\r\n- Easiest way to stalk all your friends are up to\r\n\r\nMAKE PLANS\r\n- Get plans out of the group chat\r\n\r\nSET WHO SEES WHAT\r\n- Choose to share your any event with all friends, just Close Friends, or with no one\r\n\r\nCHAT\r\n- Friends' plans are the best conversation starters, so react to events & DM friends. And there\u2019s a built-in group chat for plans & groups\r\n\r\nSEE WHEN EVERYONE\u2019S FREE\r\n- Find when everyone\u2019s free to meet up\r\n\r\nVOTE WITH POLLS\r\n- Vote on anything (what to do or when works best) with polls\r\n\r\nCOUNTDOWN TO PLANS\r\n- Pin calendar events to your home screen and countdown to their date\r\n\r\nKEEP MEMORIES\r\n- Add pictures to pinned events to keep them as memories\r\n\r\nALL YOUR PLANS TOGETHER\r\n- Forced to use a different calendar for work? Sync it all into Howbout\r\n\r\nBUCKET LISTS\r\n- Add in your bucket list to turn them into plans\r\n\r\nSHARE PICS & VIDS\r\n- Share pictures & videos directly to chats & plans\r\n\r\nSEND INVITES\r\n- Invite anyone to any plan with a link - and welcome to the 21st-century\r\n\r\nFeatured by Apple, BBC, MailOnline, TechCrunch, Business Insider and a ton of other ones we don\u2019t care about as much!\r\n\u2026\r\nBored of stalking your friends on Howbout? Stalk us instead: @howbout_app on socials, hello@howbout.app on email",
    "descriptionHTML": "Howbout\u2019s the social app to keep up with friends. Socials aren&#39;t for friends anymore, so we made an app for updates you actually care about - how your friends spend their time.<br><br>Over 4 million people on Howbout, and they\u2019re all hot.\u2026<br><br>\u2026<br><br>SHARE CALENDARS<br>- Let friends know what\u2019s going on by adding it to the calendar<br><br>FRIENDS-ONLY ACTIVITY FEED<br>- Easiest way to stalk all your friends are up to<br><br>MAKE PLANS<br>- Get plans out of the group chat<br><br>SET WHO SEES WHAT<br>- Choose to share your any event with all friends, just Close Friends, or with no one<br><br>CHAT<br>- Friends&#39; plans are the best conversation starters, so react to events &amp; DM friends. And there\u2019s a built-in group chat for plans &amp; groups<br><br>SEE WHEN EVERYONE\u2019S FREE<br>- Find when everyone\u2019s free to meet up<br><br>VOTE WITH POLLS<br>- Vote on anything (what to do or when works best) with polls<br><br>COUNTDOWN TO PLANS<br>- Pin calendar events to your home screen and countdown to their date<br><br>KEEP MEMORIES<br>- Add pictures to pinned events to keep them as memories<br><br>ALL YOUR PLANS TOGETHER<br>- Forced to use a different calendar for work? Sync it all into Howbout<br><br>BUCKET LISTS<br>- Add in your bucket list to turn them into plans<br><br>SHARE PICS &amp; VIDS<br>- Share pictures &amp; videos directly to chats &amp; plans<br><br>SEND INVITES<br>- Invite anyone to any plan with a link - and welcome to the 21st-century<br><br>Featured by Apple, BBC, MailOnline, TechCrunch, Business Insider and a ton of other ones we don\u2019t care about as much!<br>\u2026<br>Bored of stalking your friends on Howbout? Stalk us instead: @howbout_app on socials, hello@howbout.app on email",
    "summary": "Social feed for friends, shared calendar to make plans, group calendars & chat",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1018818,
    "score": 4.6504426,
    "ratings": 9058,
    "reviews": 243,
    "histogram": [
        360,
        40,
        200,
        1200,
        7253
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Howbout",
    "developerId": "Howbout",
    "developerEmail": "hello@howbout.app",
    "developerWebsite": "https://howbout.app",
    "developerAddress": null,
    "privacyPolicy": "https://howbout.app/privacy-policy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Q7jHlQMfcrsliG3JXsokGzt8zg5JQST1r0oukZSjyLhPJn1Fwt24wrUg817Ui6LaPA",
    "headerImage": "https://play-lh.googleusercontent.com/zmRLnwxr9E1zgEQXktabUGIfDcHE0K6hPuRJCsRUP2iurRGsd7cY0JqzOJ630iHM4A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/h1GOG4A_zv__WOYPXoSN1uThsA-uoFf_wlzCvFW8vsNhvDXUgKzHw3td2bSOZQWF3R5B",
        "https://play-lh.googleusercontent.com/IxcPjVE8jW2oTzj-wZTVac4gUvdwPYpkSvjm4Mp2TXGp1G3YVJAb8k1nEFXwn_k4NGA",
        "https://play-lh.googleusercontent.com/P_OE1ZCbHyPZdxb8_5V8-DAWdDS3YKi_QOsgPXmDiMaFotEdvAhruFmksddfN-dECG4",
        "https://play-lh.googleusercontent.com/uxmV-9cYt9u-a3SUakk6_4XlNZqxUjc3hyn56Y4H8vfZfaw_aUCJ_5noUDcC0exMb7Y",
        "https://play-lh.googleusercontent.com/-6F9ON6UFVwlkg1Z1A49R4KXbzvorAjcOvEPjzYCTgKPzXi8CTnzqswlIfx5LpqRmzY",
        "https://play-lh.googleusercontent.com/r9p1Xbe0CABokAvxmmCdTIuFR7cPfwY7MlKW1J-O98LjlvgW7IqtuVxYBFPQRybuhg",
        "https://play-lh.googleusercontent.com/MHn81thdXh-65K38-7OGxNldNgbIFF_FH0jReUgNwxojVSptGqXGOzuCAb_-WIVbSRs",
        "https://play-lh.googleusercontent.com/yhU_hXHCwA-O6L3MxgokgFJrrV6MHEi_qa6ZwbXEgmQqkn_3lhZrG5vCdxt6azDa-T4"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 29, 2019",
    "lastUpdatedOn": "Nov 13, 2024",
    "updated": 1731511399,
    "version": "10.1.1",
    "comments": [],
    "appId": "app.zyng.app",
    "url": "https://play.google.com/store/apps/details?id=app.zyng.app&hl=en&gl=us"
}