{
    "title": "Country Balls: World Battle",
    "description": "Prepare for a thrilling new twist in the world of strategy gaming with Country Balls: World Battle! Experience the excitement of capturing territories and expanding your empire not just through direct combat but also by inciting riots and revolts within enemy states. Transform the tides of war in this tactical adventure where you can either lead your army to a glorious victory or manipulate the unrest of your adversaries to secure your expansion!\r\n\r\n\r\nIn this dynamic strategy game, you will need to react quickly to dynamic changes on the playing field! Attack head-on or weaken your opponents from the inside. Command your unique Country Balls army as you engage in real-time battles, capture countries and overtake territories while cleverly leveraging the chaos of uprisings. It's your call\u2014will you charge into battle, or will you mastermind the dissent and seize control without firing a shot?\r\n\r\n\r\nGame Features:\r\n\r\n\r\n\r\nTerritory Capture & Riots: Use your strategic prowess to capture enemy states through direct conflict or incite riots to turn their own people against them!\r\n\r\nDynamic Gameplay: Participate in tactical, real-time strategy battles where every decision counts. Fight for every inch of land and adapt your plan based on emerging situations.\r\n\r\nResource Management: Build a robust economy, fortify your borders, and accumulate resources while keeping an eye on your enemies who may try to do the same.\r\n\r\nCustomization Options: Tailor your Country Balls avatar with a myriad of customization options to showcase your unique style while leading your troops.\r\n\r\nAdvanced Warfare: For players looking for an edge, unlock powerful game-changing options, including nuclear weapons to obliterate enemy strongholds and claim their territories effortlessly.\r\n\r\n\r\nChallenge yourself as you strategize, build your state, and establish dominion over the globe in this exhilarating simulator. Watch as the balance of power shifts with every riot and troop movement\u2014this is a world where the cunning and the courageous thrive!\r\n\r\n\r\nStep into the shoes of a wise commander or a ruthless dictator as you cultivate your territory and engage in epic confrontations. Use your tactical skill to ignite revolts in enemy cities, paving the way for a new victorious reign under your leadership. In Country Balls: World Battle, every choice you make can lead to triumph or disaster.\r\n\r\n\r\nAre you ready to rally your Country Balls warriors, initiate the riots, and capture the world? Download Country Balls: World Battle for free today and embark on your journey to conquest, strategy, and endless fun! Embrace your fate, and let the world witness your rise to power!",
    "descriptionHTML": "Prepare for a thrilling new twist in the world of strategy gaming with Country Balls: World Battle! Experience the excitement of capturing territories and expanding your empire not just through direct combat but also by inciting riots and revolts within enemy states. Transform the tides of war in this tactical adventure where you can either lead your army to a glorious victory or manipulate the unrest of your adversaries to secure your expansion!<br><br><br>In this dynamic strategy game, you will need to react quickly to dynamic changes on the playing field! Attack head-on or weaken your opponents from the inside. Command your unique Country Balls army as you engage in real-time battles, capture countries and overtake territories while cleverly leveraging the chaos of uprisings. It&#39;s your call\u2014will you charge into battle, or will you mastermind the dissent and seize control without firing a shot?<br><br><br>Game Features:<br><br><br><br>Territory Capture &amp; Riots: Use your strategic prowess to capture enemy states through direct conflict or incite riots to turn their own people against them!<br><br>Dynamic Gameplay: Participate in tactical, real-time strategy battles where every decision counts. Fight for every inch of land and adapt your plan based on emerging situations.<br><br>Resource Management: Build a robust economy, fortify your borders, and accumulate resources while keeping an eye on your enemies who may try to do the same.<br><br>Customization Options: Tailor your Country Balls avatar with a myriad of customization options to showcase your unique style while leading your troops.<br><br>Advanced Warfare: For players looking for an edge, unlock powerful game-changing options, including nuclear weapons to obliterate enemy strongholds and claim their territories effortlessly.<br><br><br>Challenge yourself as you strategize, build your state, and establish dominion over the globe in this exhilarating simulator. Watch as the balance of power shifts with every riot and troop movement\u2014this is a world where the cunning and the courageous thrive!<br><br><br>Step into the shoes of a wise commander or a ruthless dictator as you cultivate your territory and engage in epic confrontations. Use your tactical skill to ignite revolts in enemy cities, paving the way for a new victorious reign under your leadership. In Country Balls: World Battle, every choice you make can lead to triumph or disaster.<br><br><br>Are you ready to rally your Country Balls warriors, initiate the riots, and capture the world? Download Country Balls: World Battle for free today and embark on your journey to conquest, strategy, and endless fun! Embrace your fate, and let the world witness your rise to power!",
    "summary": "Command your forces, employ cunning tactics and strategy to triumph in conflicts",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 283094,
    "score": 4.8454547,
    "ratings": 4061,
    "reviews": 272,
    "histogram": [
        71,
        0,
        71,
        181,
        3724
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.49 - $15.99 per item",
    "developer": "MAD PIXEL GAMES LTD",
    "developerId": "6812510223927925130",
    "developerEmail": "info@madpixel.dev",
    "developerWebsite": "https://madpixel.dev/",
    "developerAddress": null,
    "privacyPolicy": "https://madpixel.dev/privacy.html",
    "genre": "Strategy",
    "genreId": "GAME_STRATEGY",
    "categories": [
        {
            "name": "Strategy",
            "id": "GAME_STRATEGY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/77vdDMADiiKGnNWzMqS7A5mo9S_AM90bj01C10c_fDQNkjeYO3eMFyNwMHQbQfV4zLg",
    "headerImage": "https://play-lh.googleusercontent.com/guzQwiicrvf2SnALJIyd1Pq8bHghJzGjbMJWoL6ApSypE7nezYq9WKa_gUGNx34p5Psb",
    "screenshots": [
        "https://play-lh.googleusercontent.com/r2utJTnRc7YfLtOS1N1B-S0kTO2eWopKGe6jtFe5_zKKCqyzC0zyoRtmT8U3I5jRPg",
        "https://play-lh.googleusercontent.com/g1xwKEARKg4yIJ6RAE0q7oLtXP6kyhP2vZnLEZBepUPUOXTY5fAgqrw8X3IZ5zKUSqGF",
        "https://play-lh.googleusercontent.com/hc_19XnRvI-Ev1jNgqMy58oWenXzgk91VQVyvDh7dvBhtOBiYFzZ8J0rVA5QIaOjDecg",
        "https://play-lh.googleusercontent.com/O_NVuqHwLksJrtblrtpYB8gBqi2UdIjv6e8c4gSpycZYrksCmtMjQIv1VUylIOrUYI4",
        "https://play-lh.googleusercontent.com/09_0n4FkcJebz6XSQW-dovOFGRFyGTARKZ89EkBrqAjSUJThoThyW9qOZCKjOdNvINU",
        "https://play-lh.googleusercontent.com/cCvZk_59K-orHrkIh4ZzklQIfUJ4_zIJXm44usGbtiw6mQVIOLG1Tf6S_3aMMfcT7P4",
        "https://play-lh.googleusercontent.com/q8EEYUtw9TOLIRhffg2wW5bLbWsysem5Il_pOARvKs-xjk_wW5iTNIlzhJ-VEDc5wQ",
        "https://play-lh.googleusercontent.com/acLFIO5zlJyY8GF3CjJx9p2tscYq0QS_qkg1QWUwdcAHRjyX5sVimZQt0d1pJelvhbrh"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 20, 2024",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731925732,
    "version": "1.4.5",
    "comments": [],
    "appId": "clash.war.dictators.io",
    "url": "https://play.google.com/store/apps/details?id=clash.war.dictators.io&hl=en&gl=us"
}