{
    "title": "Azuki \u2013 Manga Reader App",
    "description": "Azuki is your source for the latest manga chapters, officially licensed and in high quality.\r\n\r\nTHOUSANDS OF CHAPTERS\r\n\r\n\u2022 Weekly new chapters from exclusive series including Natsume & Natsume and Turning the Tables on the Seatmate Killer.\r\n\u2022 Read the latest volumes of The Yakuza\u2019s Guide to Babysitting, Gacha Girls Corps, BLITZ, and more, before anyone else.\r\n\u2022 Huge back catalog including hits like Attack on Titan, Fire Force, and That Time I Got Reincarnated as a Slime.\r\n\u2022 Hidden gems from indie manga publishers like Glacier Bay Books and Star Fruit Books.\r\n\r\nMULTIPLE WAYS TO READ\r\n\r\n\u2022 Access hundreds of chapters for free with ads.\r\n\u2022 Unlock thousands of chapters with a Premium Membership. Just $4.99/month (USD*). Get started with a free trial!\r\n\u2022 Read purchased volumes in the app.\r\n\r\nAVAILABLE WORLDWIDE ON ALL DEVICES\r\n\r\n\u2022 Read English-language manga anywhere in the world (except Japan).\r\n\u2022 Subscribe once, read on any device. Full iOS, Android, and Web support. Read on your phone, tablet, or computer.\r\n\u2022 Progress synced across all devices. Never lose track of where you are!\r\n\u2022 No internet? No problem. Read offline by downloading chapters in advance.\r\n\r\nSUPPORT CREATORS LEGALLY\r\n\r\n\u2022 All manga is officially licensed from publishers like Kodansha, Futabasha, ABLAZE, Kaiten Books, Star Fruit Books, Glacier Bay Books, SOZO Comics, Coamix, One Peace Books, CORK, Kaoru Tada/Mz's plan/Minato Pro, Toii Games, TORICO, and Vast Visual.\r\n\u2022 Reading on Azuki supports creators and translators. We\u2019re committed to fair pay for our localizers.\r\n\u2022 Built by a worker-owned company staffed with manga superfans.\r\n\r\nJOIN THE COMMUNITY\r\n\r\n\u2022 Have a question or just want to chat? Hit us up on our Twitter, Instagram, or Facebook at @ReadAzuki; or Mastodon at @Azuki@mstdn.social!\r\n\u2022 Join our Azuki Discord (https://www.azuki.co/discord/join) to discuss your favorite manga and give feedback!\r\n\r\n*Prices may vary to reflect your local currency.\r\n\r\nDownload Azuki on your Android phone or tablet today for a free trial. Cancel anytime.",
    "descriptionHTML": "Azuki is your source for the latest manga chapters, officially licensed and in high quality.<br><br>THOUSANDS OF CHAPTERS<br><br>\u2022 Weekly new chapters from exclusive series including Natsume &amp; Natsume and Turning the Tables on the Seatmate Killer.<br>\u2022 Read the latest volumes of The Yakuza\u2019s Guide to Babysitting, Gacha Girls Corps, BLITZ, and more, before anyone else.<br>\u2022 Huge back catalog including hits like Attack on Titan, Fire Force, and That Time I Got Reincarnated as a Slime.<br>\u2022 Hidden gems from indie manga publishers like Glacier Bay Books and Star Fruit Books.<br><br>MULTIPLE WAYS TO READ<br><br>\u2022 Access hundreds of chapters for free with ads.<br>\u2022 Unlock thousands of chapters with a Premium Membership. Just $4.99/month (USD*). Get started with a free trial!<br>\u2022 Read purchased volumes in the app.<br><br>AVAILABLE WORLDWIDE ON ALL DEVICES<br><br>\u2022 Read English-language manga anywhere in the world (except Japan).<br>\u2022 Subscribe once, read on any device. Full iOS, Android, and Web support. Read on your phone, tablet, or computer.<br>\u2022 Progress synced across all devices. Never lose track of where you are!<br>\u2022 No internet? No problem. Read offline by downloading chapters in advance.<br><br>SUPPORT CREATORS LEGALLY<br><br>\u2022 All manga is officially licensed from publishers like Kodansha, Futabasha, ABLAZE, Kaiten Books, Star Fruit Books, Glacier Bay Books, SOZO Comics, Coamix, One Peace Books, CORK, Kaoru Tada/Mz&#39;s plan/Minato Pro, Toii Games, TORICO, and Vast Visual.<br>\u2022 Reading on Azuki supports creators and translators. We\u2019re committed to fair pay for our localizers.<br>\u2022 Built by a worker-owned company staffed with manga superfans.<br><br>JOIN THE COMMUNITY<br><br>\u2022 Have a question or just want to chat? Hit us up on our Twitter, Instagram, or Facebook at @ReadAzuki; or Mastodon at @Azuki@mstdn.social!<br>\u2022 Join our Azuki Discord (https://www.azuki.co/discord/join) to discuss your favorite manga and give feedback!<br><br>*Prices may vary to reflect your local currency.<br><br>Download Azuki on your Android phone or tablet today for a free trial. Cancel anytime.",
    "summary": "One subscription. Endless manga to explore.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 120626,
    "score": 4.61,
    "ratings": 533,
    "reviews": 38,
    "histogram": [
        20,
        10,
        10,
        67,
        418
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $99.99 per item",
    "developer": "KiraKira Media Inc.",
    "developerId": "KiraKira+Media+Inc.",
    "developerEmail": "support@kirakira.io",
    "developerWebsite": "https://www.azuki.co",
    "developerAddress": null,
    "privacyPolicy": "https://www.azuki.co/privacy-policy",
    "genre": "Comics",
    "genreId": "COMICS",
    "categories": [
        {
            "name": "Comics",
            "id": "COMICS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ZZoppxKTs0MXJRKzbesIhsnfF-bcp2ldfpS_sD8tAPQWa6maNNZbGX2QerMW5B0n6vY",
    "headerImage": "https://play-lh.googleusercontent.com/SCy0q7JY9__tvMq8eGUjaco7sLOLX1c_IOUbR7ZHM5qqy5fP0_IN5LB9jz-wTyt0WcPe",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nV-S9gcjQjAIoxmfGUvCpf6ReVzNDIax4EtJx7YA9t0W7Rvmx-btF6dQOBxWuf9TCIk",
        "https://play-lh.googleusercontent.com/PG3NDlijAMqP7EWL7Bcpb9xrkDICyYJNeYb-aKRKF4lLY-6ipNhmLU5CrL6kF7ROlH0",
        "https://play-lh.googleusercontent.com/iLAmWBD9sCCEMwflDQkVnFgvp-XCytXQX3KLtOUtuwxZSekQ1VzEhP4TfWzaJUxZkX0",
        "https://play-lh.googleusercontent.com/j9Dg9EptZN96hPAz4PwXKloQ4uR-rOOAKvLCK1OOy8IsZOfeXfcmeFFuIqXY8ECMp4M",
        "https://play-lh.googleusercontent.com/jd2S3JMR9o0JLvibIIddJFjwsQUYiok57soBtoGJytgCOmHZK_SJrUoZYUCGX-I3STw",
        "https://play-lh.googleusercontent.com/WldjjZ8Ls7doAOFj1P4hXXzMyYSl2g9LEZaQ8PDIyAHBqM1_twVPmCiFQsULdRN3",
        "https://play-lh.googleusercontent.com/3WSwgu6atzv8GTjbCrWvvmQv4lN2oVcBz4Zd2RODO1_coDaiT0_czVHMj2TKQuS7sIk",
        "https://play-lh.googleusercontent.com/wObaqYaDYLPj0Zpex60RXfRgex6yIlWZdQ8HVmCNx0kwnWaus1o1GXsIuQ0ys_i19HbD",
        "https://play-lh.googleusercontent.com/ZG22KccuUgK1qka_q3Flcd6AbBpPuS9rjJNfNRObmZ9LZKXFSPd_3n1AW9mWtzJG-ol_"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Violence, Blood, Suggestive Themes",
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 17, 2021",
    "lastUpdatedOn": "Sep 16, 2024",
    "updated": 1726544813,
    "version": "3.2.0",
    "comments": [],
    "appId": "co.azuki.app",
    "url": "https://play.google.com/store/apps/details?id=co.azuki.app&hl=en&gl=us"
}