{
    "title": "Hinge Dating App: Match & Date",
    "description": "<b>HINGE, THE DATING APP DESIGNED TO BE DELETED</b>\r\nHinge is the dating app for people who want to get off of dating apps. With profiles that show your personality through text, photos, video, and voice, you have unique conversations that lead to great dates. And it\u2019s working. Currently, people on Hinge go on a date every three seconds. Additionally, in 2022, we were the fastest-growing dating app in the US, UK, and Canada.\r\n\r\n<b>HOW WE GET YOU OFF HINGE</b>\r\nWhen it comes to online dating, people are so busy matching that they\u2019re not actually connecting, in person, where it counts. Hinge is on a mission to change that. So we built a dating app that\u2019s designed to be deleted. Here\u2019s how:\r\n\r\n\ud83d\udc8c We quickly learn your type. You\u2019ll only be introduced to the best people for you.\r\n\r\n\ud83c\udf10 We give you a sense of someone\u2019s personality. You\u2019ll get to know potential dates through their unique answers to prompts, as well as information like religion, height, politics, dating intentions, relationship type, and much more.\r\n\r\n\ud83d\udde3 We make it easy to start a conversation. Every match begins by someone liking or commenting on a specific part of your profile.\r\n\r\n\u2705 We want you to feel confident about meeting people in person and going on great dates. Selfie Verification makes it easier for daters on Hinge to ensure that they are who they say they are.\r\n\r\n\ud83c\udfa4 We ask how your dates are going. After exchanging phone numbers with a Match, we\u2019ll follow up to hear how your date went so we can make better recommendations in the future.\r\n\r\n<b>PRESS</b>\r\n\u25fc \"It's the go-to dating app for many people looking for love.\" - The Daily Mail\r\n\u25fc \u201cHinge\u2019s CEO says a good dating app relies on vulnerability, not algorithms.\u201d - Washington Post\r\n\u25fc \"Hinge is the first dating app to actually measure real-world success\" - TechCrunch\r\n\r\n\r\nThe app is free to use. Members looking to see everyone who likes them or send unlimited likes can upgrade to Hinge+. To access additional features, including enhanced recommendations and priority likes, we offer HingeX.\r\n\r\n<b>SUBSCRIPTION INFO</b>\r\n\u2795 Payment will be charged to Google Account at confirmation of purchase\r\n\u2795 Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period\r\n\u2795 Account will be charged for renewal within 24-hours prior to the end of the current period\r\n\u2795 Subscriptions may be managed and auto-renewal may be turned off by going to Account Settings after purchase\r\n\r\nSupport: hello@hinge.co\r\nTerms of Service: https://hinge.co/terms.html\r\nPrivacy Policy: https://hinge.co/privacy.html\r\n\r\nAll photos are of models and used for illustrative purposes only.",
    "descriptionHTML": "<b>HINGE, THE DATING APP DESIGNED TO BE DELETED</b><br>Hinge is the dating app for people who want to get off of dating apps. With profiles that show your personality through text, photos, video, and voice, you have unique conversations that lead to great dates. And it\u2019s working. Currently, people on Hinge go on a date every three seconds. Additionally, in 2022, we were the fastest-growing dating app in the US, UK, and Canada.<br><br><b>HOW WE GET YOU OFF HINGE</b><br>When it comes to online dating, people are so busy matching that they\u2019re not actually connecting, in person, where it counts. Hinge is on a mission to change that. So we built a dating app that\u2019s designed to be deleted. Here\u2019s how:<br><br>\ud83d\udc8c We quickly learn your type. You\u2019ll only be introduced to the best people for you.<br><br>\ud83c\udf10 We give you a sense of someone\u2019s personality. You\u2019ll get to know potential dates through their unique answers to prompts, as well as information like religion, height, politics, dating intentions, relationship type, and much more.<br><br>\ud83d\udde3 We make it easy to start a conversation. Every match begins by someone liking or commenting on a specific part of your profile.<br><br>\u2705 We want you to feel confident about meeting people in person and going on great dates. Selfie Verification makes it easier for daters on Hinge to ensure that they are who they say they are.<br><br>\ud83c\udfa4 We ask how your dates are going. After exchanging phone numbers with a Match, we\u2019ll follow up to hear how your date went so we can make better recommendations in the future.<br><br><b>PRESS</b><br>\u25fc &quot;It&#39;s the go-to dating app for many people looking for love.&quot; - The Daily Mail<br>\u25fc \u201cHinge\u2019s CEO says a good dating app relies on vulnerability, not algorithms.\u201d - Washington Post<br>\u25fc &quot;Hinge is the first dating app to actually measure real-world success&quot; - TechCrunch<br><br><br>The app is free to use. Members looking to see everyone who likes them or send unlimited likes can upgrade to Hinge+. To access additional features, including enhanced recommendations and priority likes, we offer HingeX.<br><br><b>SUBSCRIPTION INFO</b><br>\u2795 Payment will be charged to Google Account at confirmation of purchase<br>\u2795 Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period<br>\u2795 Account will be charged for renewal within 24-hours prior to the end of the current period<br>\u2795 Subscriptions may be managed and auto-renewal may be turned off by going to Account Settings after purchase<br><br>Support: hello@hinge.co<br>Terms of Service: https://hinge.co/terms.html<br>Privacy Policy: https://hinge.co/privacy.html<br><br>All photos are of models and used for illustrative purposes only.",
    "summary": "Dating app designed to be deleted: Chat, Date, Meet Local Friends & Find People",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 22105369,
    "score": 3.3882124,
    "ratings": 321866,
    "reviews": 46241,
    "histogram": [
        91553,
        19691,
        27353,
        38778,
        144487
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.49 - $239.99 per item",
    "developer": "Hinge, Inc.",
    "developerId": "Hinge,+Inc.",
    "developerEmail": "hello@hinge.co",
    "developerWebsite": "https://www.hinge.co/",
    "developerAddress": "809 Washington St\nNew York, NY 10014",
    "privacyPolicy": "https://hinge.co/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/5P5svqXNCWqE0NtHSV91pl2YUGKJ2aitjaUWIVZd-65AtskDVO2o9bpYx1oAV9fr0-nt",
    "headerImage": "https://play-lh.googleusercontent.com/z8s6U3MGIwotocaU-0X5Gq_NTjh_5FR8KAgTwpi5m6ESme0YPTvitpHvQuMXW5DvmA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/AmLxe2q3ZRLbzWRLbRGkJ22f4WLtNKx3xWdSKh0Ltcizo_t18gLRPyrTF77QJF2krT8",
        "https://play-lh.googleusercontent.com/ZnyINfRKlIYIIIi8yhAyAZNwMMxAdFAJ-Qlk11YxIlfoiu0HU25vKPedQSN6ysJznPE",
        "https://play-lh.googleusercontent.com/J_UE-H7WdPnct3sC1ulgSfwRgwswa_2RZEvg0aCOUUjHU2YJR6VWY4MBb9Ol3taj5Fw",
        "https://play-lh.googleusercontent.com/WsssKOAIiIkn-1LJxsWy6CO0ysv3OsL7bw1KBmQ2Io35jrbTNgtphNFLbaGE8P75Dm4",
        "https://play-lh.googleusercontent.com/Q8beQ4VViLdN0z9q8y77pJxjflUMPu9wAMBiNtgOctuJweBlNqv0kpmSCsvGA-wjNkA",
        "https://play-lh.googleusercontent.com/-77C99cc37IYfQ8NfTKqPSRfC4mHDwrJd44bSGe2WtcDQM5N9Q_GGZfHqKQdD_4I2g",
        "https://play-lh.googleusercontent.com/NFVHsJq6RIkSMYXZn9ZHsnoDtZWrfsoudZmImFeAsPs6nFp6PnHeTvTWQEZpIXvYE1s",
        "https://play-lh.googleusercontent.com/YzjC7DF1B02j9sG1SkTTHQK3S3rtnZtwYFEBcewZBhh0VqBPCY_V44ZoD7P-ZODWlj8",
        "https://play-lh.googleusercontent.com/9hNNp0g1jfyWavMCKvNRGJs9MR6dN8SaOaIEYI7XUM1gDyioqgc5EbMrJd5BOXAKx1Wv",
        "https://play-lh.googleusercontent.com/vIlja-oer3tMGjMNLYanAa6TZCK15KawEp2dky52BLOQd5HSlXdHaotTI2N1_WcXvK4",
        "https://play-lh.googleusercontent.com/psRBLYG-MeT3wdXmbhmWhi6H7AYJ_An4KeeYfdD3wla8FqTALqm2Ue0ytJOYERNPkfM",
        "https://play-lh.googleusercontent.com/8kYw4QI5qK0n66BjbvxhWFMP7eknNFfATEGjWOMXY04296oHioLl8KabfFNwaJ1S_eQ",
        "https://play-lh.googleusercontent.com/AEPTdZxwz4zBgses7U3ydcmb3yqw3SmJLDHr--6gVzy0PnUWaUemeL9Ck3hBDWsagw",
        "https://play-lh.googleusercontent.com/sW9OoTXfVuoBmeD2KmvTOFME8ktN-jXHaiVcEgmd-8beogcCoHznNk4upRu3IylL5I8",
        "https://play-lh.googleusercontent.com/TNAONAi7mTDYakLysPzNbOekwTjsg1vNejiO8XtW1J8l7hA0reNzKZDYSQF-043bzQ",
        "https://play-lh.googleusercontent.com/bGSUKEEhfHTdseaYpqe5SJFdTXHJfUYThnO3Bj0vMo6YqLCpi4jOxNNyPjAtwPuRQvg",
        "https://play-lh.googleusercontent.com/PdGHNMIwkG-swLsWV6xeI8EuTT1SQiMVob7MITqL4HkhA4c7_X9IidHO1CXyy1aN5RM",
        "https://play-lh.googleusercontent.com/RNQDp2OdJXpbxzqj1kNLV2dJKTw4tBopLtg51JRqkONMadOksifGW2hqh8XobIagkQ",
        "https://play-lh.googleusercontent.com/MswA-PiAtlJFc0BHEj5AvUYnsYvnaHgFlMmV2BSzpkc57abE_rzXkpyW1WvwckOAjyVi",
        "https://play-lh.googleusercontent.com/MHAeLLdKqZTQBRUJ_u5baJI_15HYJX3Fwd9PdgdNFx9xT5PSi0XQ--O1bOtISDdNww",
        "https://play-lh.googleusercontent.com/Ve1wHUsox_zjTkb42DhBI6vgAON64XhoVUI4Ult1zTbLzEujJ46nlyJBqQuidKMq3HM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 10, 2017",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731705346,
    "version": "9.61.0",
    "comments": [],
    "appId": "co.hinge.app",
    "url": "https://play.google.com/store/apps/details?id=co.hinge.app&hl=en&gl=us"
}