{
    "title": "brightwheel: Childcare App",
    "description": "Brightwheel is the #1 software solution for preschools, child care, daycare, camps, and after school programs.\r\n\r\nBrightwheel is the only app that integrates everything you need: sign in/out, messaging, learning assessments, daily sheet reports, photos, videos, calendars, online bill pay for parents, and much more.\r\n\r\nBrightwheel lets you manage your center, streamline workflows, and engage with parents, so you can save time and money, make life easier for your staff, and improve satisfaction for your parents.\r\n\r\nJoin the thousands of preschools, child care, and daycare programs across the globe that have fallen in love with brightwheel!\r\n\r\nPRESCHOOLS / CHILD CARE / DAYCARE / CAMPS: Manage your students and classrooms, track attendance and room ratios, share photos and videos, assess learning milestones, communicate with parents, send paperless invoices and payments, review daily sheets, and manage staff. Brightwheel is your all-in-one child care and daycare management app!\r\n\r\nPARENTS: Engage in your child\u2019s day with a real-time feed of photos, videos, reminders, and updates. Use brightwheel\u2019s digital check-in to securely sign in and out, pay tuition online, and even invite grandparents, nannies, and friends to join in the fun!\r\n\r\nFeatures include:\r\n\u2022 Central Database: Store everything related to kids and families in one secure place.\r\n\u2022 Student Check-In: Multiple digital check-in options available including digital signatures, 4 digit check-in codes, and a kiosk mode - all aligned with child care licensing requirements.\r\n\u2022 Staff Check-In & Ratios: Make administrative tasks easier by managing staff check-in to see your ratios across all your rooms in real time.\r\n\u2022 Attendance: Easily log attendance and absences for your school-age students, infants, and toddlers. Use our attendance tracking system to keep track of your toddlers.\r\n\u2022 Photo and video sharing: Snap photos, record videos and tag students with one click. Automatically saved to your account and shared with parents (with no extra work!).\r\n\u2022 Daily Sheet Reports: Log naps, meals, bathroom, and other activities. Parents get a feed and daily summary. Daily sheet reports are a breeze with brightwheel.\r\n\u2022 Assessment & Observations: Make note of progress, achievements, and activities with pre-loaded state standards and a DRDP tool. Share with parents or privately amongst teachers.\r\n\u2022 Student Feed: Parents get a personalized feed throughout the day. Save time \u2013 no more paper tracking sheets or sending individual photos.\r\n\u2022 Parent Communication: Manage parent communication from one central hub (notices, calls, texts, etc.).\r\n\u2022 Calendar: Share events, holidays, and important dates with both families and staff.\r\n\u2022 Paperless Billing: Seamless electronic billing and payments for tuition and fees. Use brightwheel for all your child care accounting needs.\r\n\u2022 Reporting: Detailed reports of every brightwheel feature for billing and licensing requirements.\r\n\u2022 Seamless Sync: Brightwheel stays up to date across all phones and tablets \u2013 so teachers can use their own device or a school device.\r\n\u2022 Web Portal: Easy management and great functionality available on the web, too.\r\n\u2022 Affordable. Both free and premium plans available to fit your needs.\r\n\r\nAnd... much more coming! Brightwheel is the #1 early education platform for preschools, child care, and daycares, and we\u2019re always committed to innovation with frequent improvements and new features.",
    "descriptionHTML": "Brightwheel is the #1 software solution for preschools, child care, daycare, camps, and after school programs.<br><br>Brightwheel is the only app that integrates everything you need: sign in/out, messaging, learning assessments, daily sheet reports, photos, videos, calendars, online bill pay for parents, and much more.<br><br>Brightwheel lets you manage your center, streamline workflows, and engage with parents, so you can save time and money, make life easier for your staff, and improve satisfaction for your parents.<br><br>Join the thousands of preschools, child care, and daycare programs across the globe that have fallen in love with brightwheel!<br><br>PRESCHOOLS / CHILD CARE / DAYCARE / CAMPS: Manage your students and classrooms, track attendance and room ratios, share photos and videos, assess learning milestones, communicate with parents, send paperless invoices and payments, review daily sheets, and manage staff. Brightwheel is your all-in-one child care and daycare management app!<br><br>PARENTS: Engage in your child\u2019s day with a real-time feed of photos, videos, reminders, and updates. Use brightwheel\u2019s digital check-in to securely sign in and out, pay tuition online, and even invite grandparents, nannies, and friends to join in the fun!<br><br>Features include:<br>\u2022 Central Database: Store everything related to kids and families in one secure place.<br>\u2022 Student Check-In: Multiple digital check-in options available including digital signatures, 4 digit check-in codes, and a kiosk mode - all aligned with child care licensing requirements.<br>\u2022 Staff Check-In &amp; Ratios: Make administrative tasks easier by managing staff check-in to see your ratios across all your rooms in real time.<br>\u2022 Attendance: Easily log attendance and absences for your school-age students, infants, and toddlers. Use our attendance tracking system to keep track of your toddlers.<br>\u2022 Photo and video sharing: Snap photos, record videos and tag students with one click. Automatically saved to your account and shared with parents (with no extra work!).<br>\u2022 Daily Sheet Reports: Log naps, meals, bathroom, and other activities. Parents get a feed and daily summary. Daily sheet reports are a breeze with brightwheel.<br>\u2022 Assessment &amp; Observations: Make note of progress, achievements, and activities with pre-loaded state standards and a DRDP tool. Share with parents or privately amongst teachers.<br>\u2022 Student Feed: Parents get a personalized feed throughout the day. Save time \u2013 no more paper tracking sheets or sending individual photos.<br>\u2022 Parent Communication: Manage parent communication from one central hub (notices, calls, texts, etc.).<br>\u2022 Calendar: Share events, holidays, and important dates with both families and staff.<br>\u2022 Paperless Billing: Seamless electronic billing and payments for tuition and fees. Use brightwheel for all your child care accounting needs.<br>\u2022 Reporting: Detailed reports of every brightwheel feature for billing and licensing requirements.<br>\u2022 Seamless Sync: Brightwheel stays up to date across all phones and tablets \u2013 so teachers can use their own device or a school device.<br>\u2022 Web Portal: Easy management and great functionality available on the web, too.<br>\u2022 Affordable. Both free and premium plans available to fit your needs.<br><br>And... much more coming! Brightwheel is the #1 early education platform for preschools, child care, and daycares, and we\u2019re always committed to innovation with frequent improvements and new features.",
    "summary": "Daily sheets, attendance, billing & learning tools for childcare programs",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2159979,
    "score": 4.797834,
    "ratings": 8989,
    "reviews": 3079,
    "histogram": [
        129,
        108,
        172,
        627,
        7949
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "brightwheel",
    "developerId": "brightwheel",
    "developerEmail": "support@mybrightwheel.com",
    "developerWebsite": "https://mybrightwheel.com",
    "developerAddress": null,
    "privacyPolicy": "https://mybrightwheel.com/privacy",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/zBsR9wvZShmIET8R_521CCQ_cGRVX57smATQ7wNM2cxlr6UMCxSngIyNdpx8zRAnQOw",
    "headerImage": "https://play-lh.googleusercontent.com/Qb34sInB1UBfe80xLY0jR8rVG8emXl7mrcKVpD2HKw2X3eRZY47UvBZk0ka0J8bmUv0",
    "screenshots": [
        "https://play-lh.googleusercontent.com/-AmX-g4x7WktJveTVZwwpK6k34cailWwYZ_LMwkgBYeYgVd_VYC9GnldTzYHupsIVEg",
        "https://play-lh.googleusercontent.com/lZ_THmI7XOENuIUVz-ZFgKij7AIQ5BXJPqkA8EqViyVQVPnf082RB1m05oS3ezFcuvs",
        "https://play-lh.googleusercontent.com/UX9aWWhEQPvTMHiaRfgvhX6nYVoi20_ZaVTxmxCVJuOlPvpVkplQ5tkL7VoaIKW0KA",
        "https://play-lh.googleusercontent.com/2YGkNAUnAbL02eY_voSi7ESxPbyW8aB12mHv2cIeHDwS6JjaYQphdkBGr0kdV-eyshY",
        "https://play-lh.googleusercontent.com/4K7UTmFGZKyxDHWJWQ3mwbv_umOCJR8omSOpjMEJ3BCsshYipFRpxmOFBWTszaH1-9Y",
        "https://play-lh.googleusercontent.com/DwmbdBaHZZ2YLTFZAqdyGzv2pcDaBdCajAXP92BaLJWCERlN4vvSYMF_PyeMe4tyZQ",
        "https://play-lh.googleusercontent.com/Coi_OG71HRLNl05SVCy51oEV4fYE46dxt8z3WDZTjhVgSVi12-FYjBspucAFvBcg0g"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 25, 2014",
    "lastUpdatedOn": "Nov 13, 2024",
    "updated": 1731540828,
    "version": "5.34.1",
    "comments": [],
    "appId": "co.kidcasa.app",
    "url": "https://play.google.com/store/apps/details?id=co.kidcasa.app&hl=en&gl=us"
}