{
    "title": "Bright - Crush Your Card Debt",
    "description": "Get Debt in control with Bright Money.\r\nConsolidate multiple debt into one manageable Credit Line, pay down monthly, and simplify debt management(1)\r\nBuild Credit with simple secured Line of Credit starting $50(2)\r\nGet personalized money management plans designed to repay debt.\r\nAll this with the AI-powered Bright App @ <$10/month(3)\r\n\r\nWhat does the Bright App offer?\r\nPay down high-interest debt on a tap(1)\r\nThe Bright App can help you consolidate credit card balances, into a single Credit Line of up to $8,000(1). Pay it down with affordable monthly payments, and simplify your management.\r\n\r\nBright Credit Fees\r\nCredit limit -  $500 - $8,000\r\nAPR (Annual Percentage Rate -  9% \u201324.99%\r\nApplication fee - $0\r\nOrigination fees - $0\r\nLate fees - $0\r\nPrepayment fees - $0\r\nMonthly minimum payment - 3%\r\n(of the outstanding principal balance plus the accrued interest)\r\nExample:\r\nCredit limit - $5,000\r\nAPR (Annual Percentage Rate) - 12%\r\nOutstanding Principal Balance - $5,000\r\nMonthly minimum payment - $200\r\n\r\nManage all Credit Cards in one place\r\nSimplify Credit Card management with the Bright App. Organize multiple cards and bills in one place and receive payment reminders. Avoid missed bills and debt with Bright\u2019s AI-driven plan.\r\n\r\nBuild Credit with Bright\u2019s Secured Credit Line.\r\nGet a Secured Line of Credit starting at $50(2) on the Bright App. Make on-time payments(2)monthly, get your payments reported to the credit agencies, and build your credit. \r\n\r\nBuild Savings that consistently grow\r\nBright\u2019s AI-driven plan helps you pay down debt easily, creates a path to get debt under control, and builds your savings. Plan your financial future right.\r\n\r\nAI-driven Budget Plan tailored for you:\r\nThe Bright App creates personalized payoff plans to repay debt easily. Whether  you are planning a long-due trip, a favorite car, a new house, or a happy retirement, the Bright App guides you toward smart budgeting within your current income.\r\n\r\nExpert tips to manage your money the smart way.\r\nGet access to expert finance guidance on the Bright App. There are short articles, practical guides, and a comprehensive answer bank for all your money questions. A wealth of financial information to stay on top of your money.\r\n\r\nFast sign-up and 365 days Live chat support.\r\nSigning up for the Bright App takes just 2 minutes(1). Get started with your personalized debt management and credit building. 24*7 Live Customer Chat Support. \r\nFor any queries at any point, email it to us on support@brightmoney.co or call us on +1 877-274-6494 [OPERATIONAL HOURS [Mon-Fri] - 9:30 TO 6:30 PM (CST)]\r\n\r\nJoin the community of 1 million+ satisfied customers who have experienced the benefits of the Bright App. \r\n\r\n(1)Bright Credit is a line of credit that can be used to pay off your credit cards. Subject to credit approval. Variable APR ranges from 9% \u201324.99%, and Credit Limit ranges from $500 - $8,000. APR will vary based on prime rates.  Final terms may vary depending on credit review. Monthly Minimum Payments are as low as 3% of the outstanding principal balance plus the accrued interest. Also, you can choose to pay more than the minimum due if you want to pay down the loan faster. Credit line originated by Bright or CBW Bank, Member FDIC. Products and services are subject to state residency and regulatory requirements. Bright Credit is currently not available in all states.\r\n(2)Payment history has the biggest impact on credit score accounting for 40% of how score is calculated per TransUnion(https://www.transunion.com/credit-score). Bright Builder helps you build a payment history that may positively improve your credit score. A credit score increase is not guaranteed. Individual results may vary. Late payments, missed payments, or other defaults on your accounts with us or others will negatively affect your credit score. Products and services are subject to state residency and regulatory requirements. Bright Builder is currently not available in all states.\r\n(3)Applicable when a user chooses annual or semi-annual plans",
    "descriptionHTML": "Get Debt in control with Bright Money.<br>Consolidate multiple debt into one manageable Credit Line, pay down monthly, and simplify debt management(1)<br>Build Credit with simple secured Line of Credit starting $50(2)<br>Get personalized money management plans designed to repay debt.<br>All this with the AI-powered Bright App @ &lt;$10/month(3)<br><br>What does the Bright App offer?<br>Pay down high-interest debt on a tap(1)<br>The Bright App can help you consolidate credit card balances, into a single Credit Line of up to $8,000(1). Pay it down with affordable monthly payments, and simplify your management.<br><br>Bright Credit Fees<br>Credit limit -  $500 - $8,000<br>APR (Annual Percentage Rate -  9% \u201324.99%<br>Application fee - $0<br>Origination fees - $0<br>Late fees - $0<br>Prepayment fees - $0<br>Monthly minimum payment - 3%<br>(of the outstanding principal balance plus the accrued interest)<br>Example:<br>Credit limit - $5,000<br>APR (Annual Percentage Rate) - 12%<br>Outstanding Principal Balance - $5,000<br>Monthly minimum payment - $200<br><br>Manage all Credit Cards in one place<br>Simplify Credit Card management with the Bright App. Organize multiple cards and bills in one place and receive payment reminders. Avoid missed bills and debt with Bright\u2019s AI-driven plan.<br><br>Build Credit with Bright\u2019s Secured Credit Line.<br>Get a Secured Line of Credit starting at $50(2) on the Bright App. Make on-time payments(2)monthly, get your payments reported to the credit agencies, and build your credit. <br><br>Build Savings that consistently grow<br>Bright\u2019s AI-driven plan helps you pay down debt easily, creates a path to get debt under control, and builds your savings. Plan your financial future right.<br><br>AI-driven Budget Plan tailored for you:<br>The Bright App creates personalized payoff plans to repay debt easily. Whether  you are planning a long-due trip, a favorite car, a new house, or a happy retirement, the Bright App guides you toward smart budgeting within your current income.<br><br>Expert tips to manage your money the smart way.<br>Get access to expert finance guidance on the Bright App. There are short articles, practical guides, and a comprehensive answer bank for all your money questions. A wealth of financial information to stay on top of your money.<br><br>Fast sign-up and 365 days Live chat support.<br>Signing up for the Bright App takes just 2 minutes(1). Get started with your personalized debt management and credit building. 24*7 Live Customer Chat Support. <br>For any queries at any point, email it to us on support@brightmoney.co or call us on +1 877-274-6494 [OPERATIONAL HOURS [Mon-Fri] - 9:30 TO 6:30 PM (CST)]<br><br>Join the community of 1 million+ satisfied customers who have experienced the benefits of the Bright App. <br><br>(1)Bright Credit is a line of credit that can be used to pay off your credit cards. Subject to credit approval. Variable APR ranges from 9% \u201324.99%, and Credit Limit ranges from $500 - $8,000. APR will vary based on prime rates.  Final terms may vary depending on credit review. Monthly Minimum Payments are as low as 3% of the outstanding principal balance plus the accrued interest. Also, you can choose to pay more than the minimum due if you want to pay down the loan faster. Credit line originated by Bright or CBW Bank, Member FDIC. Products and services are subject to state residency and regulatory requirements. Bright Credit is currently not available in all states.<br>(2)Payment history has the biggest impact on credit score accounting for 40% of how score is calculated per TransUnion(https://www.transunion.com/credit-score). Bright Builder helps you build a payment history that may positively improve your credit score. A credit score increase is not guaranteed. Individual results may vary. Late payments, missed payments, or other defaults on your accounts with us or others will negatively affect your credit score. Products and services are subject to state residency and regulatory requirements. Bright Builder is currently not available in all states.<br>(3)Applicable when a user chooses annual or semi-annual plans",
    "summary": "Super app to manage debt in one place. Build credit. AI Budget tool",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1186047,
    "score": 4.65878,
    "ratings": 69663,
    "reviews": 6235,
    "histogram": [
        1707,
        515,
        3306,
        8776,
        55354
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Bright Money",
    "developerId": "Bright+Money",
    "developerEmail": "support@brightmoney.co",
    "developerWebsite": "https://www.brightmoney.co",
    "developerAddress": null,
    "privacyPolicy": "https://www.brightmoney.co/legal/privacy-policy/",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Rz9Bnj8Z0AIn09qIkf7sS9gvaPBdH9vSqHFP5xJMqZKSnD6OwuRXFM94wUB99dmjUxg",
    "headerImage": "https://play-lh.googleusercontent.com/iLyiv_qbXoB5uTI5LINWC8zG9wZzuKABxMkdOVugYtQIfwcH4O0fGvUnTUePOKIFfA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/cf4na4W4KNtuTO42Q1Xq5U4wAsmCvyWuUVoWygPohAB6KbLgRO8qCsMny-dMzmt35g",
        "https://play-lh.googleusercontent.com/LHHa-Jv0PtdiMidDjv6dbhbjzklQkpfathJe_7WMO0sR-CIgC4-Qp2ki725Mb5WdCQ",
        "https://play-lh.googleusercontent.com/dIBhISb1ir2OEsGdGo22ymNTl7ULInme7ZO2KLpyxLKOA4pDYwuFf501w8up0rpX16c",
        "https://play-lh.googleusercontent.com/ib7Qh1Pg-Spie2XjnDO-9SQAE9Cl0MfQxukNhTmlUCXhN9Q0D3XTreyYT8yABZ3Dy9OG",
        "https://play-lh.googleusercontent.com/z9c8TjY_Ps7UGBXpln4PC4BNrYCHxPto5GZTK89R4R0OeDThXIo_rblsAvD-HT4Weq62",
        "https://play-lh.googleusercontent.com/ZGoW4ZCwpUhN_jhogtPfHUF5lq3335SKHtL5Zc0Yyj_7qpAARwzzqw1RpCGZUD4lTl0",
        "https://play-lh.googleusercontent.com/SVXIpKAKGu4yTudHBreaEb8wgaTTxvbLPtJMtGzaARDGK_X-UgJvZvllnS7IM-1K4bY",
        "https://play-lh.googleusercontent.com/bM2AdGP4uTAhsATLqim71STXBleM6ejPswSwZ5ECOdHZyI17EZplLDr58mxO0C6FkzA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 31, 2020",
    "lastUpdatedOn": "Sep 29, 2024",
    "updated": 1727602598,
    "version": "1.49.1",
    "comments": [],
    "appId": "com.brightcapital.app",
    "url": "https://play.google.com/store/apps/details?id=com.brightcapital.app&hl=en&gl=us"
}