{
    "title": "JOB TODAY: Hire & Find Jobs",
    "description": "Find jobs & hire quality candidates for your company fast! With JOB TODAY, you can job search and get alerts for work in retail, hospitality and the service industry. Find work fast and build your career in a single click. Are you an employer hiring for your company? Interview candidates & hire staff right from the app! \r\n\r\nJOB TODAY revolutionizes the way candidates find jobs and employers hire staff. It's career recruitment without the paperwork: no lengthy CV, no cover letter and no spending tons of time on your job search. Pretty cool, right?\r\n\r\nJOB SEARCH & BUILD YOUR CAREER WITH JOB TODAY:\r\n1. Find retail jobs, part-time work in hospitality or the service industry while on the go\r\n2. Career recruitment: candidates apply for jobs & chat with employers instantly\r\n3. Get job alerts, build your career or hire staff fast!\r\n\r\nJOB SEARCHING FOR PART-TIME OR A FULL-TIME WORK?\r\nFind retail jobs, work in hospitality or the service industry in seconds!\r\n\r\nSearching for part-time work to fit around coursework or looking for your first full-time job? Find jobs in every sector including hospitality, the restaurant industry, marketing & retail jobs. \r\n\r\n+ Create a short profile and apply - no more spending time on lengthy CVs! \r\n+ Search job listings & get job alerts so you can find work fast in your chosen industry\r\n+ Chat with employers and start to build your career in seconds!\r\n\r\nHIRING FOR YOUR COMPANY?\r\nInterview candidates for part-time jobs or full-time work on JOB TODAY. Your company\u2019s career recruitment has never been faster.\r\n\r\nHiring for a part-time bartender to cover a late-night shift? Need a friendly restaurant server or reliable candidate to join your hospitality staff?\r\n\r\n+ Create your company profile in seconds\r\n+ Publish your job listing for free and find the best candidates fast\r\n+ Interview candidates and message with them via our built-in chat \r\n\r\n**********************\r\n\r\nNeed help or have a question?\r\nEmail us at support.us@jobtoday.com \r\nLove our app? Please leave a review!",
    "descriptionHTML": "Find jobs &amp; hire quality candidates for your company fast! With JOB TODAY, you can job search and get alerts for work in retail, hospitality and the service industry. Find work fast and build your career in a single click. Are you an employer hiring for your company? Interview candidates &amp; hire staff right from the app! <br><br>JOB TODAY revolutionizes the way candidates find jobs and employers hire staff. It&#39;s career recruitment without the paperwork: no lengthy CV, no cover letter and no spending tons of time on your job search. Pretty cool, right?<br><br>JOB SEARCH &amp; BUILD YOUR CAREER WITH JOB TODAY:<br>1. Find retail jobs, part-time work in hospitality or the service industry while on the go<br>2. Career recruitment: candidates apply for jobs &amp; chat with employers instantly<br>3. Get job alerts, build your career or hire staff fast!<br><br>JOB SEARCHING FOR PART-TIME OR A FULL-TIME WORK?<br>Find retail jobs, work in hospitality or the service industry in seconds!<br><br>Searching for part-time work to fit around coursework or looking for your first full-time job? Find jobs in every sector including hospitality, the restaurant industry, marketing &amp; retail jobs. <br><br>+ Create a short profile and apply - no more spending time on lengthy CVs! <br>+ Search job listings &amp; get job alerts so you can find work fast in your chosen industry<br>+ Chat with employers and start to build your career in seconds!<br><br>HIRING FOR YOUR COMPANY?<br>Interview candidates for part-time jobs or full-time work on JOB TODAY. Your company\u2019s career recruitment has never been faster.<br><br>Hiring for a part-time bartender to cover a late-night shift? Need a friendly restaurant server or reliable candidate to join your hospitality staff?<br><br>+ Create your company profile in seconds<br>+ Publish your job listing for free and find the best candidates fast<br>+ Interview candidates and message with them via our built-in chat <br><br>**********************<br><br>Need help or have a question?<br>Email us at support.us@jobtoday.com <br>Love our app? Please leave a review!",
    "summary": "Connecting Candidates with Employers Hiring Immediately.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 9656552,
    "score": 4.6179037,
    "ratings": 187725,
    "reviews": 1529,
    "histogram": [
        10244,
        1193,
        3250,
        20488,
        152467
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $799.99 per item",
    "developer": "JOB TODAY S.A.",
    "developerId": "6434219031553312265",
    "developerEmail": "info@jobtoday.com",
    "developerWebsite": "https://jobtoday.com/",
    "developerAddress": "9 rue du Laboratoire, L-1911 Luxembourg",
    "privacyPolicy": "https://jobtoday.com/gb/static/privacy",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/K0RnQ1HOn5ZZG-qEob5fsYujuGYKPeDKr-Mwhe0xAnN6MjsmTvloXKcO9NJK27HAttg",
    "headerImage": "https://play-lh.googleusercontent.com/s0Egfw7KCcWFBUpeM0jk7p4-OZvWxOi1XqEqGwrsdEyisy1sTaejrEFddX9Iq0O2TDk",
    "screenshots": [
        "https://play-lh.googleusercontent.com/81f9DTfYWEuQ1M2ZK7nOc8PBSN3SNcYFAXavuEqOjI0RA0IlooP-5EHdhxCV849E2ms",
        "https://play-lh.googleusercontent.com/Xo2QD4oMhGzhhR82Oi4E25mqxRGIN1eFRDphqKMysH8gWD6vnU_P_KpuPMfPxzS_aBA",
        "https://play-lh.googleusercontent.com/2jpgDK6SdcHGOWQszdlsBvzF_fVBUvbRpqvp5Bh29aJ3bxbJa1lGrbQnHCvXQMoC8K0",
        "https://play-lh.googleusercontent.com/ZiTXDSCbBxnQxQA07zqrhjFypjsHpJiaWzwcVmBowIEtuXPq6hKHX0XzdWGx89591nM",
        "https://play-lh.googleusercontent.com/xgFirXMmGgYDIcQDJuUcc4AH2QgQvNIbBlw8sC4qbWMS0_W6Udorf3JdLXk0_e_12l_4"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 11, 2016",
    "lastUpdatedOn": "Nov 6, 2024",
    "updated": 1730926393,
    "version": "2.89.1",
    "comments": [],
    "appId": "com.jobtoday.app",
    "url": "https://play.google.com/store/apps/details?id=com.jobtoday.app&hl=en&gl=us"
}