{
    "title": "Bumble Dating App: Meet & Date",
    "description": "<h1><b>The dating app to meet new people and build equitable relationships.</b></h1>\r\n\r\nBumble is the dating app with millions of people to meet and find dates, where women always make the first move. In a sea of dating apps, what makes us shine? \u2728 Our unwavering focus on <b>kindness, respect, and equality</b>, where individuals of all orientations - straight, gay, lesbian, and beyond - are not just welcomed but celebrated.\r\n\r\n<b>Match with the right people, date or make friends!</b>\r\n\r\nBumble is a free date app and social network for singles and people who want to make new friends; the perfect place to meet new people, in an instant. Whether you want to make genuine matches, seeking arrangements that prioritize mutual respect and understanding, chat with strangers, find friends, or even expand your professional, we\u2019ve got you covered.\r\n\r\n<b>Bumble's embrace of kindness, equality and respect</b>\r\n\ud83d\udc9b We believe healthy relationships are fundamental to living a positive life\r\n\ud83d\udc9b In the fight against old-fashioned hetero-norms, women always take the first step\r\n\ud83d\udc9b We've changed the rules of the game to switch up the dynamics of dating and make friends!\r\n\ud83d\udc9b Unlike other dating apps, kindness is at the core of everything we do\r\n\r\n<b>Changing the rules of dating</b>\r\nBumble is the best free dating app, founded on respect, equality, and kindness. You can meet new people, meet up, find dates or your best friend in the way you've always done.\r\n\ud83d\udd52 With heterosexual matches, women have 24h to start a chat, and men have 24h to respond\r\n\ud83d\udcac Other matches (LGBTQIA+) have 24h to start a chat or reply before the match expires\r\n\ud83d\udc65 Bumble has 3 modes to suit what you're looking for: Date, BFF, and Bizz\r\n\r\n<b>Discover our amazing features</b>\r\nWe\u2019ve levelled up from the days of dating sites, enjoy all these features at your fingertips:\r\n\ud83c\udf3c Craft your profile and showcase your uniqueness effortlessly\r\n\ud83d\udd0e Find your perfect match with tailored searches\r\n\u2705 Trust genuine connections with verified profiles\r\n\ud83c\udfb5 Link your Spotify and Instagram accounts to share your interests with potential dates and friends!\r\n\ud83d\udcf9 Use Video Chat to meet people IRL and get to know your matches better\r\n\ud83d\udcf7 Send your videos and favorite pictures while you are chatting with new friends!\r\n\ud83d\udca4 Hide your profile with the Snooze Mode, (you'll still keep all your matches!)\r\n\r\nStart today, meet singles, have dates or a new friendship!\r\n\r\n<b>Boost your dating life, Bumble Premium help you enhance your experience</b>\r\n\ud83d\udc9b See everyone who swiped right on you\r\n\ud83d\udd01 Rematch with expired connections for a second chance at a date\r\n\ud83d\udd04 Extend your matches by 24 hours and meet people\r\n\ud83d\udc49 Meet people by swiping as much as you like\r\n\ud83d\udcac Unlimited chat so you can find the right match\r\nand much more!\r\n\r\n<b>Inclusivity is key</b>\r\nBumble is different from other dating apps because <b>we make it easy for you to build a new relationship, meet people or make new friends</b>. We\u2019re the first app to combine dating for singles, meeting new people, and making professional connections all in one app. \r\n\r\nBumble is committed to being <b>inclusive, and supportive of our community</b> whatever their gender, sexual orientation, or religion. Whether you\u2019re looking for a place to chat and date, seeking arrangement, find friends, an LGBTQ, bisexual, lesbian or gay dating app or a Jeiwsh or Christian dating app; We\u2019ve got everything you\u2019re looking for in our lovely community to meet new people or make new friends.\r\n\r\n---\r\nBumble is a free dating app to download and use. We offer optional subscription packages (Bumble Boost & Bumble Premium) and non-subscription, single, and multi-use paid features (Bumble Spotlight & Bumble SuperSwipe).\r\nYour personal data is securely stored on Bumble - be sure to read our privacy policy and terms and conditions\r\nhttps://bumble.com/en/privacy\r\nhttps://bumble.com/en/terms\r\n\r\nBumble Inc. is the parent company of Bumble, along with Badoo, Official, Bumble for Friends and Fruitz, dating apps free to download and use.",
    "descriptionHTML": "<h1><b>The dating app to meet new people and build equitable relationships.</b></h1><br><br>Bumble is the dating app with millions of people to meet and find dates, where women always make the first move. In a sea of dating apps, what makes us shine? \u2728 Our unwavering focus on <b>kindness, respect, and equality</b>, where individuals of all orientations - straight, gay, lesbian, and beyond - are not just welcomed but celebrated.<br><br><b>Match with the right people, date or make friends!</b><br><br>Bumble is a free date app and social network for singles and people who want to make new friends; the perfect place to meet new people, in an instant. Whether you want to make genuine matches, seeking arrangements that prioritize mutual respect and understanding, chat with strangers, find friends, or even expand your professional, we\u2019ve got you covered.<br><br><b>Bumble&#39;s embrace of kindness, equality and respect</b><br>\ud83d\udc9b We believe healthy relationships are fundamental to living a positive life<br>\ud83d\udc9b In the fight against old-fashioned hetero-norms, women always take the first step<br>\ud83d\udc9b We&#39;ve changed the rules of the game to switch up the dynamics of dating and make friends!<br>\ud83d\udc9b Unlike other dating apps, kindness is at the core of everything we do<br><br><b>Changing the rules of dating</b><br>Bumble is the best free dating app, founded on respect, equality, and kindness. You can meet new people, meet up, find dates or your best friend in the way you&#39;ve always done.<br>\ud83d\udd52 With heterosexual matches, women have 24h to start a chat, and men have 24h to respond<br>\ud83d\udcac Other matches (LGBTQIA+) have 24h to start a chat or reply before the match expires<br>\ud83d\udc65 Bumble has 3 modes to suit what you&#39;re looking for: Date, BFF, and Bizz<br><br><b>Discover our amazing features</b><br>We\u2019ve levelled up from the days of dating sites, enjoy all these features at your fingertips:<br>\ud83c\udf3c Craft your profile and showcase your uniqueness effortlessly<br>\ud83d\udd0e Find your perfect match with tailored searches<br>\u2705 Trust genuine connections with verified profiles<br>\ud83c\udfb5 Link your Spotify and Instagram accounts to share your interests with potential dates and friends!<br>\ud83d\udcf9 Use Video Chat to meet people IRL and get to know your matches better<br>\ud83d\udcf7 Send your videos and favorite pictures while you are chatting with new friends!<br>\ud83d\udca4 Hide your profile with the Snooze Mode, (you&#39;ll still keep all your matches!)<br><br>Start today, meet singles, have dates or a new friendship!<br><br><b>Boost your dating life, Bumble Premium help you enhance your experience</b><br>\ud83d\udc9b See everyone who swiped right on you<br>\ud83d\udd01 Rematch with expired connections for a second chance at a date<br>\ud83d\udd04 Extend your matches by 24 hours and meet people<br>\ud83d\udc49 Meet people by swiping as much as you like<br>\ud83d\udcac Unlimited chat so you can find the right match<br>and much more!<br><br><b>Inclusivity is key</b><br>Bumble is different from other dating apps because <b>we make it easy for you to build a new relationship, meet people or make new friends</b>. We\u2019re the first app to combine dating for singles, meeting new people, and making professional connections all in one app. <br><br>Bumble is committed to being <b>inclusive, and supportive of our community</b> whatever their gender, sexual orientation, or religion. Whether you\u2019re looking for a place to chat and date, seeking arrangement, find friends, an LGBTQ, bisexual, lesbian or gay dating app or a Jeiwsh or Christian dating app; We\u2019ve got everything you\u2019re looking for in our lovely community to meet new people or make new friends.<br><br>---<br>Bumble is a free dating app to download and use. We offer optional subscription packages (Bumble Boost &amp; Bumble Premium) and non-subscription, single, and multi-use paid features (Bumble Spotlight &amp; Bumble SuperSwipe).<br>Your personal data is securely stored on Bumble - be sure to read our privacy policy and terms and conditions<br>https://bumble.com/en/privacy<br>https://bumble.com/en/terms<br><br>Bumble Inc. is the parent company of Bumble, along with Badoo, Official, Bumble for Friends and Fruitz, dating apps free to download and use.",
    "summary": "Dating app to meet new people, chat and date with singles IRL or make friends.",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 86439696,
    "score": 3.8367891,
    "ratings": 1200389,
    "reviews": 84226,
    "histogram": [
        225552,
        43450,
        99302,
        165121,
        666953
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.49 - $259.99 per item",
    "developer": "Bumble Holding Limited",
    "developerId": "6810146070790225259",
    "developerEmail": "android.support@bumble.com",
    "developerWebsite": "http://bumble.com/",
    "developerAddress": "The Broadgate Tower\nThird Floor\n20 Primrose Street\nLondon\nUnited Kingdom\nEC2A 2RS",
    "privacyPolicy": "https://bumble.com/privacy/",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/X3L93Xhvu_at9rma4VreKjjJHXJQEiYARLjF3lvqhWNsFbY6-JDrGBZQM3qiv4MwVg",
    "headerImage": "https://play-lh.googleusercontent.com/5HLmcOqGqQsw_Vql1WBXsdHORyST2rYjZlW6GbhvY99U4-Do6x--0pVHKoiDzAf6WQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/GunApbEmFpXjMjKIWuKE8eTPcXKuk6vesW_q9uLfSJn-5oArU0OOD1QWhrdFLWo5ZYU",
        "https://play-lh.googleusercontent.com/KAj_RpwgBye1BEpgIGF986Qd8fHy9EPij7JzYFceV8qN1KJJOv7IE7d1a93pSnTI1vY",
        "https://play-lh.googleusercontent.com/3Ge1fjX8pvXoqzapbchrV8gqanNEKWUG9gaL5lZw0vXklvqlD97D1ZqNoX4_BojQJwI",
        "https://play-lh.googleusercontent.com/Ve7FxPz9CXJRpGshZYzH9X_Le2idrnaucWl7E6qyRaBRQNNHkjWqfyj8cb0DHacD3w",
        "https://play-lh.googleusercontent.com/M23X1FReIqGPXcVW6tcr1jOGNkafMX7nuwikMGql_9Evz6leaxB2VqCxFn8XfEs7sSDv",
        "https://play-lh.googleusercontent.com/DoKViJVcGEfZETtJ4I4Sm98gFFcdOgtiN7v3x7xR4IvhiQNejNF_gOy2opOWL-2Y9bC5",
        "https://play-lh.googleusercontent.com/DN4orYa9gEgqhfoiANQsWcRYz7ssKusxhRkp1zCAE_jSitk-BZJkgmrPPlEzG-LhhUo",
        "https://play-lh.googleusercontent.com/Rr9CC2MeSi94Mi_-RdEeJ25qW11Ng8MHBYLytcPtR-eWBgSm_qhjqznoZdPGv9L8QQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 30, 2015",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731686135,
    "version": "5.394.0",
    "comments": [],
    "appId": "com.bumble.app",
    "url": "https://play.google.com/store/apps/details?id=com.bumble.app&hl=en&gl=us"
}