{
    "title": "BeeDee",
    "description": "BeeDee is a Dating app based around one of the most popular online personality tests in the world.\r\nBeeDee connects you to people in your area with compatible results.",
    "descriptionHTML": "BeeDee is a Dating app based around one of the most popular online personality tests in the world.<br>BeeDee connects you to people in your area with compatible results.",
    "summary": "Match your freak | Connect with compatible people",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 25319,
    "score": 3.4166667,
    "ratings": 110,
    "reviews": 48,
    "histogram": [
        33,
        3,
        7,
        16,
        49
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $59.99 per item",
    "developer": "BeeDee Dating",
    "developerId": "BeeDee+Dating",
    "developerEmail": "team@beedee.com",
    "developerWebsite": null,
    "developerAddress": "Kink in the Cable BV\nOttergemsesteenweg-Zuid 808 bus 193\n9000 Ghent\nBelgium",
    "privacyPolicy": "https://www.beedee.com/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/lwlx5UGwT1K8u6NcEsJLaKW7TKPgXy67WKDudoY39UENAdmxLpXAcpoUH60db6CVARCw",
    "headerImage": "https://play-lh.googleusercontent.com/zwk1wcBPPQzOVjrtBmi5EhNAi8ZvJ-Q5zpGP8v1sLAjCmmuhGz_ASsa-ho44Tca_2A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/PfB8Q2L_2naER9XjIzSQH23STPWEpI0TVKyK-H7Rnb7yAxfHhWjsfEd3m1yMm1GsP5Y",
        "https://play-lh.googleusercontent.com/ltUMa8AL1ftREZERS0InY_yeks4id4btfbVtWOGqjiGOJi3gGkjXK4vH8SvjcNrtgqI",
        "https://play-lh.googleusercontent.com/vYDlo2BumdiEwaE10fBxEUGQ5SG9ERlvMvhxG_N8Fa_ecJQ_ewjKu-79U0wI1jqy6Rk",
        "https://play-lh.googleusercontent.com/GUS1yIswy3e4oHQatKeXagpoVh5a6E13NALz1Z_jYJItx4RqjQnj4r_DIgCBPzWNc_Q",
        "https://play-lh.googleusercontent.com/-bltTyiPFWRG-j6PhtuwxzpPDD3u8pBu7m8ZHHfBvtPQcu-TgyiCz-VGNgoTQU354KA",
        "https://play-lh.googleusercontent.com/BztyVaqf-uRyjVP7qMS4-U3R8LjNDc6tEU41PENRtl71xplxJ82xD8BscMM5udVN9fk",
        "https://play-lh.googleusercontent.com/n8KKZja2f3adsnHrX8ud0-_Y1_Rf-X2-ly84rDKm_sXkt5_6SQf7IPV8-lKgxqTsznM",
        "https://play-lh.googleusercontent.com/NOh6XOf39xMtw2gjUelfnu2SZje02x6EsUZvhc13MvICprAKMkMEh-n4THCUApyDpAsg",
        "https://play-lh.googleusercontent.com/eJ2igKvFhcv4TJ68_7bUdAEbRNm_jQIbDI65ivz0JBRnfL9F_eXTWbg9qYvjiObUvqAE"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 12, 2024",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729600991,
    "version": "1.4.0",
    "comments": [],
    "appId": "com.beedee.app",
    "url": "https://play.google.com/store/apps/details?id=com.beedee.app&hl=en&gl=us"
}