{
    "title": "Meta Business Suite",
    "description": "Grow your business and connect with more people with Meta Business Suite.\r\n\r\nUse this app to:\r\n\u2022 Create, schedule, and manage posts and stories across your Facebook Page and Instagram account\r\n\u2022 Connect with more customers by responding to all of your messages and comments in one place\u2014you can even automate responses to save time\r\n\u2022 View insights about how people are interacting with your posts, stories and ads so you can create content that resonates with them\r\n\u2022 View your notifications and to-do list so you can stay on top of what matters most",
    "descriptionHTML": "Grow your business and connect with more people with Meta Business Suite.<br><br>Use this app to:<br>\u2022 Create, schedule, and manage posts and stories across your Facebook Page and Instagram account<br>\u2022 Connect with more customers by responding to all of your messages and comments in one place\u2014you can even automate responses to save time<br>\u2022 View insights about how people are interacting with your posts, stories and ads so you can create content that resonates with them<br>\u2022 View your notifications and to-do list so you can stay on top of what matters most",
    "summary": "Grow your business and connect with more people with Meta Business Suite.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 156522773,
    "score": 4.521113,
    "ratings": 4167780,
    "reviews": 77337,
    "histogram": [
        226845,
        84834,
        203648,
        426640,
        3225777
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Meta Platforms, Inc.",
    "developerId": "Meta+Platforms,+Inc.",
    "developerEmail": "android-support@fb.com",
    "developerWebsite": "http://www.facebook.com/FacebookPages",
    "developerAddress": "1 Hacker Way\nMenlo Park, CA 94025",
    "privacyPolicy": "https://www.facebook.com/about/privacy/",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/j1OseAaAgXiTFAMEuZcXEj6Kp9O3s0Xxr23B7znf3xJSL2i7IWPxEaAK4Fb8h4tUOJk",
    "headerImage": "https://play-lh.googleusercontent.com/rDkO_W0YLooPkw0_ZL_6EWkl0kepE9xrVePqI_Ve_iLk-J2KGN8dpNeecwYwcnyg9n8d",
    "screenshots": [
        "https://play-lh.googleusercontent.com/p_IicYXp0gyFfnpJ-Vya-xASyv90nus7rKYfLhqSQHkR34x_yhHnRY2KMb30eiXDA_4",
        "https://play-lh.googleusercontent.com/vJ4F2tJW6tDEr9nfYYKJg_OsUI8nBy-Ul0J_qEPHodRCVktAI67vBqsbgvPw8XfGPA",
        "https://play-lh.googleusercontent.com/arZtqNXuP5IGALSefUxWqh8ZNf2EpXtaxFV2CrUaQVgxx-5prRNqnbVlR_LilQ2sUQ",
        "https://play-lh.googleusercontent.com/7aFzbA3-NForr39BL5VP8wNjWIBp0uXgqRUiu_NGftcXtXZyq2BFtaC5GsM44jlk-LU",
        "https://play-lh.googleusercontent.com/kqH0Xy4SZuWT29FNNUg-AuAkRWFLHfQw63Izh6q-cxY79FcA9-Udl6_2xsvTayYN9lw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 28, 2014",
    "lastUpdatedOn": "Nov 16, 2024",
    "updated": 1731780120,
    "version": "480.0.0.58.109",
    "comments": [],
    "appId": "com.facebook.pages.app",
    "url": "https://play.google.com/store/apps/details?id=com.facebook.pages.app&hl=en&gl=us"
}