{
    "title": "Current: The Future of Banking",
    "description": "Current is the future of banking. Spend, save, and manage your money better with our mobile banking app and Visa credit and debit cards so you can make the most of what you've got.\r\n\r\nCurrent is a financial technology company, not an FDIC-insured bank. FDIC insurance up to $250,000 only covers the failure of an FDIC-insured bank. Certain conditions must be satisfied for pass-through deposit insurance coverage to apply. Banking services provided by Choice Financial Group, Member FDIC, and Cross River Bank, Member FDIC. \r\n\r\nWITH CURRENT YOU CAN\r\nBUILD CREDIT: Use your Build Card to build credit safely with every swipe, no credit checks required \r\n\r\nACCESS CASH: Qualify for up to a $500 Paycheck Advance\u2076\r\n\r\nSKIP THE FEES: Get fee-free overdraft & fee-free cash withdrawals from 40,000 Allpoint ATMs in the U.S.\u00b9\r\n\r\nGET PAID: Payday comes up to 2 days faster with direct deposit\u00b2\r\n\r\nSAVE: Earn up to 4.00% annual bonus on your savings\u00b3\r\n\r\nGET REWARDED: Get up to 7x the points and cash back on swipes\u2074\r\n\r\nGET HELP: 24/7 support in the app\r\n\r\n\u00b9 Some fees may apply, including out of network ATM fees of $2.50 per transaction, late payment fees of 3% of any total due balance outstanding and past due for two or more billing cycles, foreign transaction fees of 3% of the full transaction amount (minimum $0.50), card replacement fees per card of $5 for regular delivery and $30 for expedited delivery, cash deposit fees of $3.50 per deposit, and third party processing fees\r\n\u00b2 Faster access to funds is based on comparison of traditional banking policies and deposit of paper checks from employers and government agencies versus deposits made electronically. Direct deposit and earlier availability of funds is subject to timing of payer's submission of deposits\r\n\u00b3 Boost Bonuses are credited to your Savings Pods within 48 hours of enabling the Boost feature and on a daily basis thereafter, provided that the Savings Pod has accrued a Boost Bonus of at least $0.01. The Boost rate on Savings Pods is variable and may change at any time. The disclosed rate is effective as of August 1, 2023. Must have $0.01 in Savings Pods to earn a Boost rate of either 0.25% or 4.00% annually on the portion of balances up to $2000 per Savings Pod, up to $6000 total. The remaining balance earns 0.00%. To earn a Boost rate of 4.00%, the sum of your Eligible Payroll Deposits over a rolling 35-day period must be $500 or more, with at least one Eligible Payroll Deposit equalling a minimum of $100. No minimum balance required. See Current Boost Terms at current.com/docs\r\n\u2074 Points available at participating merchants. Teen accounts do not earn points\r\n\u2075 FDIC insurance only covers the failure of an FDIC-insured bank. FDIC insurance up to $250,000 is available on customer funds through pass-through insurance at Choice Financial Group, Member FDIC, and Cross River Bank, Member FDIC where we have a direct relationship for the placement of deposits and into which customer funds are deposited, but only if certain conditions have been met.\r\n\u2076 For eligible customers only. Your actual available Paycheck Advance amount will be displayed to you in the mobile app and may change from time to time. Conditions and eligibility may vary and are subject to change at any time, at the sole discretion of Finco Advance LLC, which offers this optional feature. Finco Advance LLC is a financial technology company, not a bank. See Paycheck Advance Terms at current.com/docs/\r\n\r\nThe Current Visa\u00ae Debit Card is issued by Choice Financial Group pursuant to a license from Visa U.S.A. Inc. and may be used everywhere Visa debit cards are accepted. The Current Visa\u00ae secured charge card is issued by Cross River Bank pursuant to a license from Visa U.S.A. Inc. and may be used everywhere Visa credit cards are accepted. See back of your Card for its issuing bank. Current Individual Account required to apply for the Current Visa\u00ae secured charge card. Independent approval required.",
    "descriptionHTML": "Current is the future of banking. Spend, save, and manage your money better with our mobile banking app and Visa credit and debit cards so you can make the most of what you&#39;ve got.<br><br>Current is a financial technology company, not an FDIC-insured bank. FDIC insurance up to $250,000 only covers the failure of an FDIC-insured bank. Certain conditions must be satisfied for pass-through deposit insurance coverage to apply. Banking services provided by Choice Financial Group, Member FDIC, and Cross River Bank, Member FDIC. <br><br>WITH CURRENT YOU CAN<br>BUILD CREDIT: Use your Build Card to build credit safely with every swipe, no credit checks required <br><br>ACCESS CASH: Qualify for up to a $500 Paycheck Advance\u2076<br><br>SKIP THE FEES: Get fee-free overdraft &amp; fee-free cash withdrawals from 40,000 Allpoint ATMs in the U.S.\u00b9<br><br>GET PAID: Payday comes up to 2 days faster with direct deposit\u00b2<br><br>SAVE: Earn up to 4.00% annual bonus on your savings\u00b3<br><br>GET REWARDED: Get up to 7x the points and cash back on swipes\u2074<br><br>GET HELP: 24/7 support in the app<br><br>\u00b9 Some fees may apply, including out of network ATM fees of $2.50 per transaction, late payment fees of 3% of any total due balance outstanding and past due for two or more billing cycles, foreign transaction fees of 3% of the full transaction amount (minimum $0.50), card replacement fees per card of $5 for regular delivery and $30 for expedited delivery, cash deposit fees of $3.50 per deposit, and third party processing fees<br>\u00b2 Faster access to funds is based on comparison of traditional banking policies and deposit of paper checks from employers and government agencies versus deposits made electronically. Direct deposit and earlier availability of funds is subject to timing of payer&#39;s submission of deposits<br>\u00b3 Boost Bonuses are credited to your Savings Pods within 48 hours of enabling the Boost feature and on a daily basis thereafter, provided that the Savings Pod has accrued a Boost Bonus of at least $0.01. The Boost rate on Savings Pods is variable and may change at any time. The disclosed rate is effective as of August 1, 2023. Must have $0.01 in Savings Pods to earn a Boost rate of either 0.25% or 4.00% annually on the portion of balances up to $2000 per Savings Pod, up to $6000 total. The remaining balance earns 0.00%. To earn a Boost rate of 4.00%, the sum of your Eligible Payroll Deposits over a rolling 35-day period must be $500 or more, with at least one Eligible Payroll Deposit equalling a minimum of $100. No minimum balance required. See Current Boost Terms at current.com/docs<br>\u2074 Points available at participating merchants. Teen accounts do not earn points<br>\u2075 FDIC insurance only covers the failure of an FDIC-insured bank. FDIC insurance up to $250,000 is available on customer funds through pass-through insurance at Choice Financial Group, Member FDIC, and Cross River Bank, Member FDIC where we have a direct relationship for the placement of deposits and into which customer funds are deposited, but only if certain conditions have been met.<br>\u2076 For eligible customers only. Your actual available Paycheck Advance amount will be displayed to you in the mobile app and may change from time to time. Conditions and eligibility may vary and are subject to change at any time, at the sole discretion of Finco Advance LLC, which offers this optional feature. Finco Advance LLC is a financial technology company, not a bank. See Paycheck Advance Terms at current.com/docs/<br><br>The Current Visa\u00ae Debit Card is issued by Choice Financial Group pursuant to a license from Visa U.S.A. Inc. and may be used everywhere Visa debit cards are accepted. The Current Visa\u00ae secured charge card is issued by Cross River Bank pursuant to a license from Visa U.S.A. Inc. and may be used everywhere Visa credit cards are accepted. See back of your Card for its issuing bank. Current Individual Account required to apply for the Current Visa\u00ae secured charge card. Independent approval required.",
    "summary": "Save, spend, and get paid faster\u00b2",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 5649407,
    "score": 4.61778,
    "ratings": 159102,
    "reviews": 42904,
    "histogram": [
        8397,
        1581,
        4093,
        14283,
        130743
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Current",
    "developerId": "Current",
    "developerEmail": "support@current.com",
    "developerWebsite": "https://current.com",
    "developerAddress": null,
    "privacyPolicy": "https://current.com/privacy_policy",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/jWZ5eL3rFrRg3YXn2KW8Crzxr9zpbtZ9d9s3AyLMfbC3rBZxsj0AiRAOhUlRZlKEgcQ",
    "headerImage": "https://play-lh.googleusercontent.com/baOvKvezt6iueuqPKLPDKLhBW-dNAXNlOV7Mf8okbM0aPQy1UyvsBSpbQm2pEABAxEn2",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nGop-vYQ9Nxv9uxXv34FpE7cbn9Ti1HcggH8tgXrMmKbGeczqzZA5DKRCxvr9znxNw",
        "https://play-lh.googleusercontent.com/bt5P_9-_pe_h84h0CV9aHb34y99jGaMa9b1E2nLzfCcvCaveVRrpYpcoNqGg0DjdufM",
        "https://play-lh.googleusercontent.com/pQDdRj7aOLz0P2aCmHbRvfnooz3rOM3Of2Dww8wyrgYz3tEcnlzYqAjP41_2YLVXnA",
        "https://play-lh.googleusercontent.com/Kw4ILxptAS_9UZ-qNPPT_CxxlEU6AJSQFB6JOYsRo2xbieKqdoFDNPcE-Vm4RnoakHY",
        "https://play-lh.googleusercontent.com/NUIQY1nNjgiGUGkBHabLGqUVd_63Sac9gSZ2j0pdYOzMLsadVEAHRLBT_GVQYu1LCpeF",
        "https://play-lh.googleusercontent.com/8xPr9IJ4AxeIRwYKlDF0v7IZoU40UqA0cRzSW_UHAx_G-co76rfAXokM8qtuN9n8kpc",
        "https://play-lh.googleusercontent.com/9PMfxiHf-y0LEGCssAL10tDjLQNqbSbqqnv12-yioC2ZWxa7Xro0KZRiU6rW6mS4QgQ",
        "https://play-lh.googleusercontent.com/I0pBSS2ZkiTvrHfq1JKxeDQKjQgsL_6KtixGyfZOGq7miTkEj5okeojfKobtb1-Mlw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 5, 2017",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731945701,
    "version": "7.16.1",
    "comments": [],
    "appId": "com.current.app",
    "url": "https://play.google.com/store/apps/details?id=com.current.app&hl=en&gl=us"
}