{
    "title": "Harbor Freight Tools",
    "description": "HARBOR FREIGHT COUPONS\r\nFind the latest coupons, instant savings, Inside Track Club member deals, and more with the Harbor Freight Tools app.\r\n\u00a0\r\nSHOP\r\nBrowse the latest tools, watch them in action with our Harbor Freight videos, check in-stock availability in your area, and create a wish list for your next in-store visit. You can also use the Barcode/QR scanner in-store to quickly learn more about our tools.\r\n\u00a0\r\nACCOUNT ACCESS\r\nSign in to your Harbor Freight Tools account and sync your product wish list across different devices.\r\n\u00a0\r\nINSIDE TRACK CLUB MEMBERS\r\nStay up to date with all the latest Inside Track Club Member deals. Save your Inside Track Club deals to your wish list for your next in-store visit.\r\n\u00a0\r\nABOUT US\r\nHarbor Freight Tools is America's leading retailer of quality tools at the lowest prices. Harbor Freight carries over 7,000 products, specializing in air compressors, automotive tools, drills, generators, hand tools, saws, tool storage, welding supplies, wrenches, and more. Most Harbor Freight products are sourced directly from manufacturers and are all tested in our own quality assurance facility in the United States. Harbor Freight is known for our compellingly low prices on quality tools, all of which meet, or beat, the quality of the brand name competitors.\r\n\u00a0\r\nHarbor Freight has over 1500+ stores nationwide. Our Harbor Freight Tools stores stock a full selection of hardware, tools, and accessories in categories including automotive, air and power tools, storage, outdoor power equipment, generators, welding supplies, shop equipment, hand tools, and more. All of Harbor Freight\u2019s hand tools come with a lifetime warranty.\r\n\u00a0\r\nWhatever you do, do it for less at Harbor Freight.\r\n\u00a0\r\nFAQ\r\nHave questions or feedback? Email us at:\u00a0appcs@harborfreight.com",
    "descriptionHTML": "HARBOR FREIGHT COUPONS<br>Find the latest coupons, instant savings, Inside Track Club member deals, and more with the Harbor Freight Tools app.<br>\u00a0<br>SHOP<br>Browse the latest tools, watch them in action with our Harbor Freight videos, check in-stock availability in your area, and create a wish list for your next in-store visit. You can also use the Barcode/QR scanner in-store to quickly learn more about our tools.<br>\u00a0<br>ACCOUNT ACCESS<br>Sign in to your Harbor Freight Tools account and sync your product wish list across different devices.<br>\u00a0<br>INSIDE TRACK CLUB MEMBERS<br>Stay up to date with all the latest Inside Track Club Member deals. Save your Inside Track Club deals to your wish list for your next in-store visit.<br>\u00a0<br>ABOUT US<br>Harbor Freight Tools is America&#39;s leading retailer of quality tools at the lowest prices. Harbor Freight carries over 7,000 products, specializing in air compressors, automotive tools, drills, generators, hand tools, saws, tool storage, welding supplies, wrenches, and more. Most Harbor Freight products are sourced directly from manufacturers and are all tested in our own quality assurance facility in the United States. Harbor Freight is known for our compellingly low prices on quality tools, all of which meet, or beat, the quality of the brand name competitors.<br>\u00a0<br>Harbor Freight has over 1500+ stores nationwide. Our Harbor Freight Tools stores stock a full selection of hardware, tools, and accessories in categories including automotive, air and power tools, storage, outdoor power equipment, generators, welding supplies, shop equipment, hand tools, and more. All of Harbor Freight\u2019s hand tools come with a lifetime warranty.<br>\u00a0<br>Whatever you do, do it for less at Harbor Freight.<br>\u00a0<br>FAQ<br>Have questions or feedback? Email us at:\u00a0appcs@harborfreight.com",
    "summary": "Harbor Freight Coupons - Generators, Air Compressors, Tool Storage, and More.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3225542,
    "score": 4.5892806,
    "ratings": 33910,
    "reviews": 10386,
    "histogram": [
        912,
        300,
        1364,
        6636,
        24691
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Harbor Freight Tools USA, Inc.",
    "developerId": "Harbor+Freight+Tools+USA,+Inc.",
    "developerEmail": "cs@harborfreight.com",
    "developerWebsite": "https://www.harborfreight.com/",
    "developerAddress": "26541 Agoura Rd.\nCalabasas, CA 91302",
    "privacyPolicy": "https://www.harborfreight.com/security-and-privacy.html",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Fj8vnJ0JGwRIFFotSR2B-gTFCNTRuPzqXYvXmrxppQcn2nPEMON5E0KYTI8fFYxj0KU",
    "headerImage": "https://play-lh.googleusercontent.com/z3YXs9BIxiqUoFxehkBRnzpOoDUbYuVnRaiNJmp6ANNlpCADUKB5l_zAcEmHhGrmKmQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/rWnWRkL2t-Jp7gKOgyIb-RAZma7O5iYspa3U3vybC3tEU-RO2qbqGsrwiIoUsFcxjpI",
        "https://play-lh.googleusercontent.com/_J_jLwJwW9qdCZbaD8a-1-gexdOdaTcgMD0yaxtbth8DxLZUXmDgOvSBl_1RqT1z_aY",
        "https://play-lh.googleusercontent.com/xEca0voHFrOtRPh5EP0V5TTROMeKPvBsfJfWtr0rKJhPGcf8mA9WTsmxAcGxPfand8E",
        "https://play-lh.googleusercontent.com/O8XnnWLmigmGFMdLS3aVuO5RtJeqw6Wkpk5HwySKJ3GJvpD14omctBCKlMpWFazJ78A",
        "https://play-lh.googleusercontent.com/6dZTjVU7TQ-lbVTRppO6F7nsrrlWAkA2Y8gWYWM9LmCpfx4xERnDvblPZ-epnZDN6Uw",
        "https://play-lh.googleusercontent.com/kLuSTJIll-KL8O1fkoo-Sx5AbOpHGzMaXmaXLM4GMMpWBHwufRO8Nab4v1ChuMejdw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 28, 2020",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729588448,
    "version": "11.9.0",
    "comments": [],
    "appId": "com.harborfreight.app",
    "url": "https://play.google.com/store/apps/details?id=com.harborfreight.app&hl=en&gl=us"
}