{
    "title": "CareCredit Mobile",
    "description": "Now there's a simple, convenient way to manage and use your CareCredit credit card. With the CareCredit Mobile App, you can access your digital card, pay your bill, find enrolled providers and retail locations that accept CareCredit, set alerts and pay bills from participating doctors and healthcare providers in the network. With a new, vibrant and simple design, the CareCredit Mobile App offers features such as:\r\n\r\nEasy Set-Up and Login Access\r\n\u2022 Securely log into your CareCredit account with your username and password then enable fingerprint login to make logging into the app more convenient. If you\u2019ve never accessed your account online; tap, \u201cI\u2019ve never logged in before\u201d to get started. \r\n\u2022 Looking for help or information about the app? Simply tap the \"?\" icon at the top right of the login screen to access contact information, login assistance, and FAQs at any time.\r\n\r\nSecure Digital Card Access\r\n\u2022 Your CareCredit credit card is preloaded when you log in. Just access the Summary and swipe down to view your digital card.\r\n\u2022 Use your CareCredit digital card for purchases within the CareCredit network of enrolled providers.\r\n\r\nConvenient Account Management\r\n\u2022 View your CareCredit statements and manage your statement delivery preferences 24/7.\r\n\u2022 Make monthly payments to your CareCredit account.\r\n\u2022 Always know where your account stands. Check your balance and credit limit anytime, anywhere.\r\n\u2022 View your promotional purchase details, transaction & payment history.\r\n\u2022 Make payments directly to your doctor or healthcare provider with CareCredit.\r\n\r\nFind a Location\r\n\u2022 Search for providers, partners, and retail locations that accept the CareCredit credit card.\r\n\u2022 Save and quickly access your favorite locations.\r\n\u2022 Use the map view, explore nearby CareCredit Network locations, and get directions.\r\n\r\nStay Informed\r\n\u2022 Set custom notifications to remind you about payments and changes to your account.\r\n\u2022 Access to helpful information, Cardholder resources, and tips for using credit wisely in the Knowledge Center.\r\n\r\nLearn More: https://www.carecredit.com/app",
    "descriptionHTML": "Now there&#39;s a simple, convenient way to manage and use your CareCredit credit card. With the CareCredit Mobile App, you can access your digital card, pay your bill, find enrolled providers and retail locations that accept CareCredit, set alerts and pay bills from participating doctors and healthcare providers in the network. With a new, vibrant and simple design, the CareCredit Mobile App offers features such as:<br><br>Easy Set-Up and Login Access<br>\u2022 Securely log into your CareCredit account with your username and password then enable fingerprint login to make logging into the app more convenient. If you\u2019ve never accessed your account online; tap, \u201cI\u2019ve never logged in before\u201d to get started. <br>\u2022 Looking for help or information about the app? Simply tap the &quot;?&quot; icon at the top right of the login screen to access contact information, login assistance, and FAQs at any time.<br><br>Secure Digital Card Access<br>\u2022 Your CareCredit credit card is preloaded when you log in. Just access the Summary and swipe down to view your digital card.<br>\u2022 Use your CareCredit digital card for purchases within the CareCredit network of enrolled providers.<br><br>Convenient Account Management<br>\u2022 View your CareCredit statements and manage your statement delivery preferences 24/7.<br>\u2022 Make monthly payments to your CareCredit account.<br>\u2022 Always know where your account stands. Check your balance and credit limit anytime, anywhere.<br>\u2022 View your promotional purchase details, transaction &amp; payment history.<br>\u2022 Make payments directly to your doctor or healthcare provider with CareCredit.<br><br>Find a Location<br>\u2022 Search for providers, partners, and retail locations that accept the CareCredit credit card.<br>\u2022 Save and quickly access your favorite locations.<br>\u2022 Use the map view, explore nearby CareCredit Network locations, and get directions.<br><br>Stay Informed<br>\u2022 Set custom notifications to remind you about payments and changes to your account.<br>\u2022 Access to helpful information, Cardholder resources, and tips for using credit wisely in the Knowledge Center.<br><br>Learn More: https://www.carecredit.com/app",
    "summary": "Manage your CareCredit account, make payments, use your digital card, and more",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3504493,
    "score": 4.599048,
    "ratings": 40176,
    "reviews": 15645,
    "histogram": [
        2354,
        382,
        533,
        4476,
        32428
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Synchrony",
    "developerId": "Synchrony",
    "developerEmail": "appsupport@synchronyfinancial.com",
    "developerWebsite": "https://www.carecredit.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.carecredit.com/privacy/",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/GZwu83BVe22R4-tQfzV7pZn8uFFeO__dvd_2LEt4THgWHkfXYSSaMe4gdAUpIZcbrw",
    "headerImage": "https://play-lh.googleusercontent.com/uoLX0Y3AnFW0RYuTThdcfeL0X3YIfR9YZZlFmIhihXyuyL1KhoYYDBLt1HDMBOdrKQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/2s1vCZOfG90RrjSwApiSaTYZxddTqsMRPOixroTJ8pvpcP2qRmyPzCp91W0Y2_4V2X9X",
        "https://play-lh.googleusercontent.com/RmWil5TovqIhuxgBPWj73FHBqsTVr95E6ezIE6fYsCEZ0UF2gUHjcKD0ZA_9TteFB0U",
        "https://play-lh.googleusercontent.com/bymHNaY5Mlqm-bj6lCxwkVYIbffS87Ef3r87tFWee_zKoJ--BEwaytKn3nXmbZsEQQ",
        "https://play-lh.googleusercontent.com/ujc2ygvo8Rup9Vn0i6W-jjE3ioq72h7UV7iC-IO-RTnVg7SxcxND1itUkXfHvK5xe70",
        "https://play-lh.googleusercontent.com/XK23XTjbBimPrr1itnI0vLD3iIEBAejuezCZNihIkQsfj2NrIdh_T4kWGxABWoAE59A",
        "https://play-lh.googleusercontent.com/XTUywiCyCxUXAg9-hDg5PUzKau0VZrulwRZOTmiSHq5Dmv6Z7vN_U1iXFPqsl__Hmu8",
        "https://play-lh.googleusercontent.com/Ku9l4FAppVV1Dswqi5iF7EzmYAZqkIyI-hamtCXmER4O9LDwytzoMRCKJ64gvx6jTww",
        "https://play-lh.googleusercontent.com/PHp_VXpY5359bDJc2nat3gfO1ytbtj_6HaiqYY8ZajwtgbZzTSD3Gj1tehpaG3WGaKpD"
    ],
    "video": "https://www.youtube.com/embed/VinT-HxZOkY?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/uoLX0Y3AnFW0RYuTThdcfeL0X3YIfR9YZZlFmIhihXyuyL1KhoYYDBLt1HDMBOdrKQ",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 27, 2015",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729529188,
    "version": "4.28.0",
    "comments": [],
    "appId": "com.syf.cc",
    "url": "https://play.google.com/store/apps/details?id=com.syf.cc&hl=en&gl=us"
}