{
    "title": "Photoroom AI Photo Editor",
    "description": "Photoroom is the all-in-one app that edits, designs and optimizes great visual content that helps you run your business from your phone. Remove or erase the background of photos, use templates and create your own content. \r\n\r\nNo need to be a photographer or design pro anymore: with Photoroom, you can turn your photos into pro-quality content in seconds.\r\nOur magic? The app crops objects and people in your picture, automatically. With one tap, remove the background and create stand-out content that showcases a product or person. Edit the image, add text or a logo, stickers, make collages.\r\nWith our Magic Retouch, now you can remove any unwanted details effortlessly (POOF!) with a swipe of your fingertip, \r\nEditing perfect product shots is a breeze (and dare we say, fun!). We mean it when we say we do visual magic so you can sell faster!\r\n\r\nMore than 6 million shop owners, resellers, and creators trust us. Join our mobile-first entrepreneur revolution and download Photoroom free today.\r\n\r\n\r\nWhat you can create:\r\n- Product content for e-commerce & marketplaces like Shopify, eBay, Etsy, Facebook marketplace, or Depop.\r\n- Portrait photography and profile pics for business or social\r\n- Instagram Stories to promote you or your business\r\n- Fun collages and stickers\r\n\r\nHow to use Photoroom:\r\n1. Take a picture or upload one from your library\r\n2. Pick from one of our 1000+ available backgrounds or templates\r\n3. Edit the image and add text. Apply filters, remove the background, play with Magic Retouch, modify the contrast, or add quotes easily with our smart photo editor.\r\n4. Add your logo (with Photoroom PRO)\r\n5. Export your content to your Library, or directly to Whatsapp, Messages, Social Media, or marketplaces like Poshmark, Depop, Vinted, etc. \r\n\r\nPhotoroom is the Photo Editor for Everyone\r\n- Use the most accurate and easy background eraser to cut out objects in images & erase their backgrounds, apply a white background, blur the background or cut the background itself\r\n- Easily crop photos\r\n- Use Magic Retouch to remove any unwanted objects \r\n- Make your own stickers in a few steps\r\n- Use our seasonal templates to create easy, dynamic seasonal content\r\n- Make photo collages\r\n\r\nPhotoroom for Resellers\r\nIf you are a reseller on marketplaces like Poshmark, Depop you can optimize your business with features like the background remover, product or person cut out, easy export directly to the marketplaces platform, or batch export mode with our PRO membership. \r\n\r\nPhotoroom for Small Business\r\nCreate professional images for your website or app in a few seconds. Use Photoroom to remove background, magic retouch pictures, or cut out a product or person perfectly. Edit to your liking and easily export. If you\u2019re looking for Pixelcut, why not try the original Photoroom.\r\n\r\nPhotoroom for Creators\r\nPromote you and your business on social by easily creating templates for Youtube or Podcast covers, and Facebook, Instagram, or Pinterest content.\r\n\r\nPhotoroom Pro: you'll have access to the following features.\r\n- Remove the Photoroom logo\r\n- Access to 3 Pro cutout options (Standard, Person, Object)\r\n- Access to the full Pro backdrop & template library\r\n- Access to Instant Backgrounds - a tool that creates perfect backgrounds for your products using artificial intelligence. \r\n- Export at higher resolutions\r\n- Edit and export in batch mode\r\n\r\nTry Photoroom Pro with a free trial. You'll be charged a subscription fee when the trial ends only, except if you cancel the subscription before. Your Pro subscription will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Manage membership and turn off auto-renew in Google Play account. Free trial is limited to one per Google Play account.\r\n\r\nFree Plan is limited to 250 exports. \r\n\r\nLove Photoroom?\r\nFollow us on Instagram @photoroom for illustrations and design tips.\r\nSend your feedback to hello@photoroom.com",
    "descriptionHTML": "Photoroom is the all-in-one app that edits, designs and optimizes great visual content that helps you run your business from your phone. Remove or erase the background of photos, use templates and create your own content. <br><br>No need to be a photographer or design pro anymore: with Photoroom, you can turn your photos into pro-quality content in seconds.<br>Our magic? The app crops objects and people in your picture, automatically. With one tap, remove the background and create stand-out content that showcases a product or person. Edit the image, add text or a logo, stickers, make collages.<br>With our Magic Retouch, now you can remove any unwanted details effortlessly (POOF!) with a swipe of your fingertip, <br>Editing perfect product shots is a breeze (and dare we say, fun!). We mean it when we say we do visual magic so you can sell faster!<br><br>More than 6 million shop owners, resellers, and creators trust us. Join our mobile-first entrepreneur revolution and download Photoroom free today.<br><br><br>What you can create:<br>- Product content for e-commerce &amp; marketplaces like Shopify, eBay, Etsy, Facebook marketplace, or Depop.<br>- Portrait photography and profile pics for business or social<br>- Instagram Stories to promote you or your business<br>- Fun collages and stickers<br><br>How to use Photoroom:<br>1. Take a picture or upload one from your library<br>2. Pick from one of our 1000+ available backgrounds or templates<br>3. Edit the image and add text. Apply filters, remove the background, play with Magic Retouch, modify the contrast, or add quotes easily with our smart photo editor.<br>4. Add your logo (with Photoroom PRO)<br>5. Export your content to your Library, or directly to Whatsapp, Messages, Social Media, or marketplaces like Poshmark, Depop, Vinted, etc. <br><br>Photoroom is the Photo Editor for Everyone<br>- Use the most accurate and easy background eraser to cut out objects in images &amp; erase their backgrounds, apply a white background, blur the background or cut the background itself<br>- Easily crop photos<br>- Use Magic Retouch to remove any unwanted objects <br>- Make your own stickers in a few steps<br>- Use our seasonal templates to create easy, dynamic seasonal content<br>- Make photo collages<br><br>Photoroom for Resellers<br>If you are a reseller on marketplaces like Poshmark, Depop you can optimize your business with features like the background remover, product or person cut out, easy export directly to the marketplaces platform, or batch export mode with our PRO membership. <br><br>Photoroom for Small Business<br>Create professional images for your website or app in a few seconds. Use Photoroom to remove background, magic retouch pictures, or cut out a product or person perfectly. Edit to your liking and easily export. If you\u2019re looking for Pixelcut, why not try the original Photoroom.<br><br>Photoroom for Creators<br>Promote you and your business on social by easily creating templates for Youtube or Podcast covers, and Facebook, Instagram, or Pinterest content.<br><br>Photoroom Pro: you&#39;ll have access to the following features.<br>- Remove the Photoroom logo<br>- Access to 3 Pro cutout options (Standard, Person, Object)<br>- Access to the full Pro backdrop &amp; template library<br>- Access to Instant Backgrounds - a tool that creates perfect backgrounds for your products using artificial intelligence. <br>- Export at higher resolutions<br>- Edit and export in batch mode<br><br>Try Photoroom Pro with a free trial. You&#39;ll be charged a subscription fee when the trial ends only, except if you cancel the subscription before. Your Pro subscription will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Manage membership and turn off auto-renew in Google Play account. Free trial is limited to one per Google Play account.<br><br>Free Plan is limited to 250 exports. <br><br>Love Photoroom?<br>Follow us on Instagram @photoroom for illustrations and design tips.<br>Send your feedback to hello@photoroom.com",
    "summary": "Automatically erase and cut background & create amazing professional images.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 120156161,
    "score": 4.711194,
    "ratings": 2711044,
    "reviews": 12649,
    "histogram": [
        73511,
        26375,
        85288,
        239135,
        2286685
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $102.99 per item",
    "developer": "Photoroom AI Photo Editor",
    "developerId": "6074336733277322018",
    "developerEmail": "help@photoroom.com",
    "developerWebsite": "http://photoroom.com",
    "developerAddress": null,
    "privacyPolicy": "https://photoroom.com/legal/privacy",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/0Zb-LP5DFkezAVnX6ez5Op-qbchLdMffqIY9ct9qmmN1cMZlWCEBwK3BLIgKdi-X0Q",
    "headerImage": "https://play-lh.googleusercontent.com/nz9kebvNMLmwkhL4nR8a-tY1Hgcr1_L7UGRjNTTXs881Xnux-ws9Ot0GXtfmfGSc2x4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/HVOvaJILrY6-76DhHdXsMaoR8A_nSFtkTsCS9g-QquE8ZiuNE3LWXgiIjIezJ9TWRgwN",
        "https://play-lh.googleusercontent.com/gr2lZ_f4Y2toE9adrzKeHGnH1mNMvntPhNRo8aq_6536zEf53XSSRZHSqeSIMjOa-FA",
        "https://play-lh.googleusercontent.com/SrV1iLer7W3t1qm8WkLhbKwjhp-o_zyue4kU78G2nWtrwTTzLMPItlhUVElyJAZhXA",
        "https://play-lh.googleusercontent.com/wv1Oq0dvaLQrrQdguJwoCqMA3v1nA1FGFcIBCcirIaotETh8CNAw96qpmD2wavPaVXqz",
        "https://play-lh.googleusercontent.com/oIHeDRhARIL3c38GOYVOhjT7DkcZdQs2V61-oNa1zpZATSZCkBXpIwwv_u3fIBhE0Q",
        "https://play-lh.googleusercontent.com/T-fgZqsixBGuYG6e3GYqj95oauaOb0a9ON4fa8xrRPR9mRQuj86wzhIkGnCT9Ue54lSU",
        "https://play-lh.googleusercontent.com/e_yjADAGmAYG15VVsgzbGXnKaOJcpreuuPXK4HzFQ5Go8lfUWGejWgaUmy2814qjtw",
        "https://play-lh.googleusercontent.com/SJvL0w4mSueEInslmWZeRXmgQ0O-h4ESurmwg54F_Txjta_2bmpWrWGwKdAwOYPcvA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 16, 2020",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731952438,
    "version": "5.6.0",
    "comments": [],
    "appId": "com.photoroom.app",
    "url": "https://play.google.com/store/apps/details?id=com.photoroom.app&hl=en&gl=us"
}