{
    "title": "Route: Package Tracker",
    "description": "Route is the premier package tracker for all of your online orders. Join over 50 Million people who have tracked their orders with Route. Route connects with millions of online stores and over 600 shipping carriers worldwide, including Amazon, FedEx, UPS, USPS, DHL, and more. Get shipping notifications that give you real-time status updates on any delivery! \r\n\r\nNEVER MISS A DELIVERY\r\nThe Route App brings package tracking and delivery to life. No more wondering where your package is\u2014has it been shipped? Is it stuck in transit? Delivered? Now you can visually track your package\u2019s journey from checkout to doorstep, review previous online orders and handle delivery issues (lost, stolen, damaged) all in one app.\r\n\r\n\u201cShopping made simpler\u201d - HYPEBEAST\r\n\r\n\u201cYour go-to package tracker\u201d - NBC News\r\n\r\nWHY YOU\u2019LL LOVE ROUTE\r\nTrack all your packages in one place - Stop searching for tracking numbers in your inbox. Track every order automatically by connecting your emails to Route. \r\n\r\nVisual Tracking\u2122- Hate searching for tracking numbers? Us too. Route seamlessly connects to every online order and makes package tracking a breeze.\r\n\r\nReal-time push notifications - Route syncs in real-time with shipping carriers like FedEx, UPS and USPS to provide shipping updates that keep you informed from the minute you checkout until your package arrives safely on your doorstep.\r\n\r\nCurated Product Discovery - Find the next brand you\u2019ll fall in love with in Route Discover. No more knock-offs. Buy direct from brands you trust.\r\nFollow Your Favorite Brands - Never miss a product drop.\r\n\r\nOne-click Order Resolution - Your package never showed up? Damaged? We got you. File a claim in one click from one of our 11,000+ merchant partners and let Route handle the rest.\r\n\r\nUniversal order history - Gone are the days of digging through emails to find old online purchases. Route automatically stores and organizes every order (including Amazon) for quick review and reorders.\r\n\r\nUnrivaled privacy - Don\u2019t worry, the Route Bot pulls only the necessary information to track your packages, and never shares it.\r\n\r\nQuestions? Contact us at feedback@route.com.",
    "descriptionHTML": "Route is the premier package tracker for all of your online orders. Join over 50 Million people who have tracked their orders with Route. Route connects with millions of online stores and over 600 shipping carriers worldwide, including Amazon, FedEx, UPS, USPS, DHL, and more. Get shipping notifications that give you real-time status updates on any delivery! <br><br>NEVER MISS A DELIVERY<br>The Route App brings package tracking and delivery to life. No more wondering where your package is\u2014has it been shipped? Is it stuck in transit? Delivered? Now you can visually track your package\u2019s journey from checkout to doorstep, review previous online orders and handle delivery issues (lost, stolen, damaged) all in one app.<br><br>\u201cShopping made simpler\u201d - HYPEBEAST<br><br>\u201cYour go-to package tracker\u201d - NBC News<br><br>WHY YOU\u2019LL LOVE ROUTE<br>Track all your packages in one place - Stop searching for tracking numbers in your inbox. Track every order automatically by connecting your emails to Route. <br><br>Visual Tracking\u2122- Hate searching for tracking numbers? Us too. Route seamlessly connects to every online order and makes package tracking a breeze.<br><br>Real-time push notifications - Route syncs in real-time with shipping carriers like FedEx, UPS and USPS to provide shipping updates that keep you informed from the minute you checkout until your package arrives safely on your doorstep.<br><br>Curated Product Discovery - Find the next brand you\u2019ll fall in love with in Route Discover. No more knock-offs. Buy direct from brands you trust.<br>Follow Your Favorite Brands - Never miss a product drop.<br><br>One-click Order Resolution - Your package never showed up? Damaged? We got you. File a claim in one click from one of our 11,000+ merchant partners and let Route handle the rest.<br><br>Universal order history - Gone are the days of digging through emails to find old online purchases. Route automatically stores and organizes every order (including Amazon) for quick review and reorders.<br><br>Unrivaled privacy - Don\u2019t worry, the Route Bot pulls only the necessary information to track your packages, and never shares it.<br><br>Questions? Contact us at feedback@route.com.",
    "summary": "Track all of your packages and online orders in one app - Amazon, FedEx, & USPS",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4290566,
    "score": 4.68747,
    "ratings": 162997,
    "reviews": 12957,
    "histogram": [
        3378,
        816,
        6120,
        22728,
        129949
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Route App Inc",
    "developerId": "8389444097266412686",
    "developerEmail": "feedback@route.com",
    "developerWebsite": "https://www.route.com/",
    "developerAddress": null,
    "privacyPolicy": "https://route.com/privacy/",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/G3AFRnV0r4rAKjVrOVX3JrimkTSGqId8BUYspcf2khFUICepa6iHGawFfK8HgPT5rU0",
    "headerImage": "https://play-lh.googleusercontent.com/5p4b9cp_tknsOwKeiL6ORJvehrwOVT1LW2sbRJu0g8HWePT6kFlpSgbEHPBBg5a7YKDG",
    "screenshots": [
        "https://play-lh.googleusercontent.com/uqPAg88pbz979Mj5uQ3On5L3K_H5sl6NE17gyI1lY3M3VTtCkgVoc2pLGtwdKuaqMiw",
        "https://play-lh.googleusercontent.com/UquvglfdHsJhHaGwvdpX81x3XKXu3eBXu_JvZit8Hla0vVfBxb1w27kxZ11dUxdziA",
        "https://play-lh.googleusercontent.com/v4p7-wyMe1eJy404N2gWz3IZm71Ks6CcfNapcpQledp3ch_O79IG2KXNSEFdD_JiEg",
        "https://play-lh.googleusercontent.com/EpCl67irwLihYLqLl1XgttzEg2y-rL6BCuS9rZcQ1odCurY-A56vwVn90G3D1OXcpRgW",
        "https://play-lh.googleusercontent.com/NzqxFhScOYJoYUw7YRNtGVKxRDNtKo3iWn47KHcHND9kQp6rOCsvDcm_vyeFlxNv9zo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 3, 2020",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731704720,
    "version": "2.162.0",
    "comments": [],
    "appId": "com.route.app",
    "url": "https://play.google.com/store/apps/details?id=com.route.app&hl=en&gl=us"
}