{
    "title": "UNATION - Discover Events",
    "description": "Let's go do stuff, IRL. Discover local guides, events, experiences, & things to do with trusted recommendations from our team.\r\n\r\nUNATION features tons of stuff to do in cities across the country. Events are not only user-generated, but also hand selected by our curators, guaranteeing we present you with the best happenings in the area. Whether you\u2019re looking for a concert, sporting event, farmers market or anything in between, you\u2019ll find it on UNATION. \r\n\r\nDISCOVER\r\nSearching for events nearby? Want to find something to do this weekend? UNATION is the go-to app for finding the best things to do. Our curated guides include everything from local events and tickets, our favorite restaurants and bars, places to stay, and so much more, all in one place. \r\n\r\nUNCOVER\r\nOur locally-curated Guides will be your go-to resource for hidden gems, beloved businesses, pro tips, and more. We write about the things we know and love, so you're always getting the latest inside scoop on the best things to do.  \r\n\r\nCUSTOMIZE\r\nWe only bring you the type of stuff you love to do. We'll get to know you and your interests within the app, so your entire Home Feed feels like a custom experience. Save your favorite UNATION content to the Collections that you create and organize just the way you like. \r\n\r\nPURCHASE\r\nWe've partnered with your favorite major ticketing platforms for all the best events! We can help you seamlessly and securely buy tickets through our app, so you can spend less time scrolling and more time enjoying your city.  \r\n\r\nPROMOTE\r\nAre you an event creator or business owner? Awesome, welcome to UNATION! Let's get your content onto our app and in front of our audiences. Want to take it a step further? You can get even more exposure by allowing our promotion experts to drive more traffic to your event than ever before. \r\n\r\nIt\u2019s time to put the screens down, grab your crew, and start exploring with UNATION!",
    "descriptionHTML": "Let&#39;s go do stuff, IRL. Discover local guides, events, experiences, &amp; things to do with trusted recommendations from our team.<br><br>UNATION features tons of stuff to do in cities across the country. Events are not only user-generated, but also hand selected by our curators, guaranteeing we present you with the best happenings in the area. Whether you\u2019re looking for a concert, sporting event, farmers market or anything in between, you\u2019ll find it on UNATION. <br><br>DISCOVER<br>Searching for events nearby? Want to find something to do this weekend? UNATION is the go-to app for finding the best things to do. Our curated guides include everything from local events and tickets, our favorite restaurants and bars, places to stay, and so much more, all in one place. <br><br>UNCOVER<br>Our locally-curated Guides will be your go-to resource for hidden gems, beloved businesses, pro tips, and more. We write about the things we know and love, so you&#39;re always getting the latest inside scoop on the best things to do.  <br><br>CUSTOMIZE<br>We only bring you the type of stuff you love to do. We&#39;ll get to know you and your interests within the app, so your entire Home Feed feels like a custom experience. Save your favorite UNATION content to the Collections that you create and organize just the way you like. <br><br>PURCHASE<br>We&#39;ve partnered with your favorite major ticketing platforms for all the best events! We can help you seamlessly and securely buy tickets through our app, so you can spend less time scrolling and more time enjoying your city.  <br><br>PROMOTE<br>Are you an event creator or business owner? Awesome, welcome to UNATION! Let&#39;s get your content onto our app and in front of our audiences. Want to take it a step further? You can get even more exposure by allowing our promotion experts to drive more traffic to your event than ever before. <br><br>It\u2019s time to put the screens down, grab your crew, and start exploring with UNATION!",
    "summary": "UNATION - Promote and Discover Events Near Me |  Buy and Sell Tickets with Ease",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 155434,
    "score": 2.99,
    "ratings": 235,
    "reviews": 91,
    "histogram": [
        97,
        17,
        6,
        6,
        102
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "UNATION, INC.",
    "developerId": "UNATION,+INC.",
    "developerEmail": "hi@unation.com",
    "developerWebsite": "https://www.unation.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.unation.com/privacy/",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/7ka4GLTAEAe9U_vbIaEDwcnR7j6nouELpiHdPLQ-ZBVnUQ8adbF_LMkKT6kqHc_zKg",
    "headerImage": "https://play-lh.googleusercontent.com/St8vLJ33QalYddd02jF_Yy8Nnxhp-_waVN5hQCnRhcqRXVHierLKILACHacrvAwBbWei",
    "screenshots": [
        "https://play-lh.googleusercontent.com/BzsVaW4oblk8Zwr90_fGxt9IVtZrgmwXtwNh3OOvhBS9DD-JRo4E-T7wN_4Rvcnk440",
        "https://play-lh.googleusercontent.com/6Rx7mVAQTOJ2Ki7sLDE5krMSvR10UZZWj5CgWDMBGt_tRyw7IXCTXAnu9_3PLrAzcA",
        "https://play-lh.googleusercontent.com/9frEN_-xzOvGP6ueQHlaKK0WIkeLXgcD6UqsaAnsL4rLguS4-Fb8x7njl2j0BKLZ6F4",
        "https://play-lh.googleusercontent.com/ft4SGpsj9Dk17lUXeE3MvMktNClxE5fZh7sYiYbYOyuMxwNNqFPl2Qf3pqenwKpZZ2A",
        "https://play-lh.googleusercontent.com/2SC2jE0axSAK2SjtAThhKitwb1jOsGdSL4zG_rIxzGoTbg4llZnNCKdelT_oc6ZRHkk"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 23, 2015",
    "lastUpdatedOn": "Nov 16, 2024",
    "updated": 1731744539,
    "version": "7.7.30",
    "comments": [],
    "appId": "com.unation.app",
    "url": "https://play.google.com/store/apps/details?id=com.unation.app&hl=en&gl=us"
}