{
    "title": "Screen hipsters:wallpaper HD",
    "description": "Enjoy using the coolest wallpapers and become a hipster in the eyes of your friends. Every day you can discover new paintings, and every day you can have a new feeling. You can experience your own mobile art anytime, anywhere. There are more 4K ultra-clear wallpapers and live wallpapers waiting for you to discover.",
    "descriptionHTML": "Enjoy using the coolest wallpapers and become a hipster in the eyes of your friends. Every day you can discover new paintings, and every day you can have a new feeling. You can experience your own mobile art anytime, anywhere. There are more 4K ultra-clear wallpapers and live wallpapers waiting for you to discover.",
    "summary": "Enjoy using the coolest wallpapers!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 203767,
    "score": 4.25,
    "ratings": 251,
    "reviews": 80,
    "histogram": [
        27,
        7,
        11,
        29,
        172
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "tarda msa",
    "developerId": "tarda+msa",
    "developerEmail": "msaadiradoine58@gmail.com",
    "developerWebsite": "http://shwphd.top",
    "developerAddress": null,
    "privacyPolicy": "https://github.com/tardamsa/ScreenhipsterswallpaperHD/wiki/PrivacyPolicyStatement",
    "genre": "Personalization",
    "genreId": "PERSONALIZATION",
    "categories": [
        {
            "name": "Personalization",
            "id": "PERSONALIZATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/4005oVkD0N0-TbWp4mTBm1E4ViPKZJqht5mpHBWCjOM5Q5Zni6tBJ-EaLRyhqIWjHA",
    "headerImage": "https://play-lh.googleusercontent.com/zTRk0CoPOMh2REdUHCCOodjAwsy2QpBrsgicqaRoKsqBCGp_V_aHNwqJPrVGtMjjNA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/QaLSN6iAyuZON76c8WQBWlefEmI_Pyb3bQlWg_oZ5i17mlnQDEO78e73uZqwXKvG4UU",
        "https://play-lh.googleusercontent.com/yS3vk6R-HFBL7UKqKzf0eBXWro1GjhlnDkYueoUDLEV4ciCMTpH7-jo0C5sr7O4b5A",
        "https://play-lh.googleusercontent.com/ldsoxlfPLWRDSKAEG_2vdZWiUrDDe0z_rVuGkSq-X4ByGsGOpTanxfq0-RfbSWrxt00",
        "https://play-lh.googleusercontent.com/DI2ZVzQ9u7Tr8kOkzSEYD_ZtfOPz9jaib1aS4dujhWtMUjWY4lQSytyzbVi5p4fuSSQ",
        "https://play-lh.googleusercontent.com/8TYmSVEnn726iik_q19He5dCkKpU2qxFHt7IMrMz59lzm9p6_VtzYhvs4uvo-Mrqnww",
        "https://play-lh.googleusercontent.com/dSqMyg1Q1CXt6aP497ttMMznYp6jA0PeWjdRi56mu7qh5cXFnHYS8TBtWjGj9A9Www",
        "https://play-lh.googleusercontent.com/aqeKTGlC6-cq0FWcCqp4Mvi_qAcB7kMqV6Vvomoaa85XfyV_rvKL1O5p5oybSLu4Sw4",
        "https://play-lh.googleusercontent.com/Ibgxhr0bySR4brlJ9ZYBYv7WoQdWg6V_BVIVXQYPFwwskCvQIF-DEGmVZT4ci9urKf0",
        "https://play-lh.googleusercontent.com/Y9A3GyyeXvN03uf7QWJxuxlpclmhlX3T09W3WshgudIY38ebk_G0S-LwDB7UlFjcwj0",
        "https://play-lh.googleusercontent.com/yoCCWPmTEJaX-qhWmDWu110suTSHSa9yNju5uwIPS85IUDM9AUAD6Px-neX4LnalGA",
        "https://play-lh.googleusercontent.com/RQ0k4_10LvGq7O-PFwy6syVypsEKE4dOKOrcP7yzAgfuVI56KiQs5LC7kBgcvxoa",
        "https://play-lh.googleusercontent.com/8Fl1qYQScaLXdh3maL1wLYSt47acwp9ngSMMpn3F_BBE2dprMLitZzx_EhPS5VKalg",
        "https://play-lh.googleusercontent.com/u4cAnhhLoHU-qrSM0FrMNspPxHGkbmIwGQdMh6BaqbUNCP_-KeoWkhx9WuO8CbPp8A",
        "https://play-lh.googleusercontent.com/sS9yjgVCN76motyVZf0hByffUfahG8cJTD0ImXwpv7A648n_g5POovqgmkPArFXXIw4",
        "https://play-lh.googleusercontent.com/QzFWdmEXPircwlUZ9UIMnhsyj2ermiyhZ1dTuVPIGg28_8lxqHNGkUGwGBig5QwcmA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "May 29, 2024",
    "lastUpdatedOn": "Jul 24, 2024",
    "updated": 1721815659,
    "version": "1.0.2",
    "comments": [],
    "appId": "com.screen.hipsters.re",
    "url": "https://play.google.com/store/apps/details?id=com.screen.hipsters.re&hl=en&gl=us"
}