{
    "title": "DeerCast: Weather, Maps, Track",
    "description": "DeerCast is the most advanced whitetail hunting app, built for deer hunters, by deer hunters.\r\n\r\nDeerCast predicts whitetail movement down to the hour based on weather variables in your area. \r\n\r\nWhitetail deer behavior is driven by their environment. Become a better whitetail hunter with the DeerCast hunting app! Get data-driven deer movement predictions, advanced weather forecasts, and mapping features all specifically formulated with the whitetail deer hunter in mind. DeerCast delivers all the information you need to get your buck! \r\n\r\nForecast\r\nDesigned by renowned whitetail experts Mark and Terry Drury of Drury Outdoors, DeerCast pulls weather and moon data for your locations and delivers a custom, deer-movement prediction, just for you. \r\n\r\nMaps\r\nPlan your whitetail hunts with multiple GPS maps and tools built specifically for the whitetail hunter! \r\n\r\nWaypoints\r\nWind Check \r\nFood Plots\r\nLive Doppler Radar\r\nVirtual Rain Gauges\r\n\r\nTrack\r\nSelect your hit on an anatomical whitetail model then get expert advice to track and recover your deer! \r\n\r\nCommunity\r\nGet thousands of hunting articles and share your successes from the field. Learn from the Drury Outdoors team and watch their hunts as they happen!\r\n\r\n\r\nMANAGE SUBSCRIPTION\r\n- Subscription automatically renews unless auto-renew is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period and identify the cost of the renewal.\r\n- Payment will be charged to Account at confirmation of Purchase.\r\n- Visit the following URL for full terms of use: https://deercast.com/public/terms-of-service\r\n-Turn off or modify your auto-renewal DeerCast subscription using these instruction https://support.google.com/googleplay/answer/7018481?hl=en&co=GENIE.Platform%3DAndroid\r\n\r\n\r\nFEEDBACK\r\nWe want to know about your experience with DeerCast! Shoot us an email at support@DeerCast.com.",
    "descriptionHTML": "DeerCast is the most advanced whitetail hunting app, built for deer hunters, by deer hunters.<br><br>DeerCast predicts whitetail movement down to the hour based on weather variables in your area. <br><br>Whitetail deer behavior is driven by their environment. Become a better whitetail hunter with the DeerCast hunting app! Get data-driven deer movement predictions, advanced weather forecasts, and mapping features all specifically formulated with the whitetail deer hunter in mind. DeerCast delivers all the information you need to get your buck! <br><br>Forecast<br>Designed by renowned whitetail experts Mark and Terry Drury of Drury Outdoors, DeerCast pulls weather and moon data for your locations and delivers a custom, deer-movement prediction, just for you. <br><br>Maps<br>Plan your whitetail hunts with multiple GPS maps and tools built specifically for the whitetail hunter! <br><br>Waypoints<br>Wind Check <br>Food Plots<br>Live Doppler Radar<br>Virtual Rain Gauges<br><br>Track<br>Select your hit on an anatomical whitetail model then get expert advice to track and recover your deer! <br><br>Community<br>Get thousands of hunting articles and share your successes from the field. Learn from the Drury Outdoors team and watch their hunts as they happen!<br><br><br>MANAGE SUBSCRIPTION<br>- Subscription automatically renews unless auto-renew is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period and identify the cost of the renewal.<br>- Payment will be charged to Account at confirmation of Purchase.<br>- Visit the following URL for full terms of use: https://deercast.com/public/terms-of-service<br>-Turn off or modify your auto-renewal DeerCast subscription using these instruction https://support.google.com/googleplay/answer/7018481?hl=en&amp;co=GENIE.Platform%3DAndroid<br><br><br>FEEDBACK<br>We want to know about your experience with DeerCast! Shoot us an email at support@DeerCast.com.",
    "summary": "Industry leading whitetail movement predictor & hunting app.",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 669134,
    "score": 4.6383495,
    "ratings": 4134,
    "reviews": 1676,
    "histogram": [
        69,
        49,
        130,
        802,
        3080
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$29.99 - $74.99 per item",
    "developer": "Drury Media - DeerCast",
    "developerId": "Drury+Media+-+DeerCast",
    "developerEmail": "support@deercast.com",
    "developerWebsite": "http://www.deercast.com/",
    "developerAddress": null,
    "privacyPolicy": "https://deercast.com/public/privacy-policy",
    "genre": "Weather",
    "genreId": "WEATHER",
    "categories": [
        {
            "name": "Weather",
            "id": "WEATHER"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/uMxwG2V0_Iwx5QL2P-7uAdntzk7fBkyPhYpaQt8Cp--WpMqnaARaIaRUlAkGQMcWX7s-",
    "headerImage": "https://play-lh.googleusercontent.com/SFJIzf2RExXnfvTION2esUhwy2JSWDt9gV3cDLq2Yz9R-GmV48ekB7QVcnp7N3LHFw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/GN0hEdjt2SUDxbvptHpAiJ3WUyRYsExDuGnbtsBkmap02ftX9FulJ1ZWUihrruDX2g",
        "https://play-lh.googleusercontent.com/WkQem8Opwm-g35HVPS0jBuCSaZTINClbCtUFTdf1Q-Kmlo_L6ai7Q7cYMQXgq4bgTo4Q",
        "https://play-lh.googleusercontent.com/sCQyhuEbqHoRlLTqMH6ok_P7CF83G-DFkAWez8T50No5b_MtLLcfD1AWekbBe01WmU4",
        "https://play-lh.googleusercontent.com/mjdBDDIfrEbZ3W58dQVctTk8i9_3Ky33D_Y2wZcm3iR5zDZV7fYJI_UV9sxO9gtRoPIZ",
        "https://play-lh.googleusercontent.com/nBUgKCxrf6IIsZvDoLxyC8jGOYx4CqouT1ir9Lts3D7TAys3vtror-7GTtla2-IE5Es",
        "https://play-lh.googleusercontent.com/bwn5_tO_17O28DVAu9AoDreCSI0b6_VEI_fkjMTty6fKEV6YiCzw0WvVI-8q_Gkt4A"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone 10+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 23, 2018",
    "lastUpdatedOn": "Oct 31, 2024",
    "updated": 1730397477,
    "version": "4.1.0",
    "comments": [],
    "appId": "com.druryoutdoors.deercast.app",
    "url": "https://play.google.com/store/apps/details?id=com.druryoutdoors.deercast.app&hl=en&gl=us"
}