{
    "title": "Strangers Dating & Chat - PicU",
    "description": "<p>Welcome to PicU, the innovative dating app that redefines how people connect online.<b><i> PicU offers an exciting way to meet new people or friends by initiating real-time random chats, breaking away from the conventional matching system</i>.</b> It\u2019s\r\n    designed for spontaneity and genuine connections, with a focus on privacy and meaningful relationships. With PicU, you can explore fun, random chats while staying in control of your social experience, making dating more personal, engaging, and secure.</p>\r\n<p>App Features :</p>\r\n<p>1. <span><span>\ud83d\udc95</span><i>\u00a0</i></span><b>Random Flash Chats</b></p>\r\n<p>PicU revolutionizes the dating experience by allowing users to connect instantly through a random message-based chat. Unlike traditional apps that require mutual swipes or likes, <b><i>PicU takes the pressure off by letting users initiate a conversation simply by sharing a text,voice or photo</i></b>.\r\n    This spontaneous interaction provides an exciting, fresh way to meet people, leading to unexpected and genuine connections. After the initial message exchange, users can dive into real-time messaging with others who are currently online, making every\r\n    conversation an adventure. </p>\r\n<p>2. \ud83e\udd29\u00a0<b>Close Friends-Only Private Story</b></p>\r\n<p>Another PicU\u2019s standout features is the ability for users to create and share posts that are only visible to their connections. Unlike traditional social media platforms where posts are public, PicU provides a more intimate space for users to share personal\r\n    moments and thoughts. <b><i>Whether it\u2019s a photo, a story, or a status update, only the people you\u2019ve added as chat mates can see what you post.</i></b> This creates a sense of exclusivity and trust within your circle, encouraging meaningful engagement\r\n    and deeper connections.</p>\r\n<p>3. \ud83c\udfaf\u00a0<b>Only Match Onine Singles</b></p>\r\n<p>Get connected instantly with singles who are online! PicU dating app eliminates the need to wait\u2014no more waiting for your matches which are offline. As soon as you log in, you'll be matched with those who are already ready to chat in real-time.<b><i>Forget endless swiping or delays\u2014just fast, fluid, and fun interactions with people who are online and ready to connect right when you are!</i></b></p>\r\n<p>4. \ud83c\udfac\u00a0<b>Multi Media Forms Social Experience</b></p>\r\n<p>PicU places snaps or reels at the heart of the social experience. From starting random chats to posting updates, everything begins with a snap. This visual-first approach adds a layer of fun and creativity to online interactions, allowing users to express\r\n    themselves in ways words alone cannot.<b><i> PicU makes visual storytelling an essential part of building connections.</i></b> With every snap, users get a glimpse into someone\u2019s world, making interactions feel more genuine and immersive.</p>\r\n<p>5. \ud83d\udd12\u00a0<b>Privacy and Security Protection</b></p>\r\n<p>At PicU, user privacy and safety are at the core of the experience. <b><i> In random chats, only when both users respond does the conversation\r\n    continue.</i></b> This feature ensures that you\u2019re always in control of your interactions, helping to foster a safe and respectful environment for everyone. Additionally, no personal information is shared until you decide to take the connection further.</p>\r\n<p>In summary, PicU offers a refreshing twist on traditional dating apps<b><i> by focusing on spontaneous, real-time chats and visual interactions</i></b>. Its emphasis on privacy, security, and personalized social sharing ensures that users can connect\r\n    with confidence and creativity.</p>\r\n<p><a href=\"http://www.google.com/url?q=http%3A%2F%2Fwww.pic-u.com%2Fprivacy-policy-PicU.html&sa=D&sntz=1&usg=AOvVaw0lUvmh-ZhwPCROd55pFZ8L\" rel=\"nofollow\">http://www.pic-u.com/privacy-policy-PicU.html</a></p>\r\n<p><a href=\"http://www.google.com/url?q=http%3A%2F%2Fwww.pic-u.com%2FTerms-and-Conditions-picu.html&sa=D&sntz=1&usg=AOvVaw0Irmniyi3cb746eo3n-tMe\" rel=\"nofollow\">http://www.pic-u.com/Terms-and-Conditions-picu.html</a></p>",
    "descriptionHTML": "<p>Welcome to PicU, the innovative dating app that redefines how people connect online.<b><i> PicU offers an exciting way to meet new people or friends by initiating real-time random chats, breaking away from the conventional matching system</i>.</b> It\u2019s<br>    designed for spontaneity and genuine connections, with a focus on privacy and meaningful relationships. With PicU, you can explore fun, random chats while staying in control of your social experience, making dating more personal, engaging, and secure.</p><br><p>App Features :</p><br><p>1. <span><span>\ud83d\udc95</span><i>\u00a0</i></span><b>Random Flash Chats</b></p><br><p>PicU revolutionizes the dating experience by allowing users to connect instantly through a random message-based chat. Unlike traditional apps that require mutual swipes or likes, <b><i>PicU takes the pressure off by letting users initiate a conversation simply by sharing a text,voice or photo</i></b>.<br>    This spontaneous interaction provides an exciting, fresh way to meet people, leading to unexpected and genuine connections. After the initial message exchange, users can dive into real-time messaging with others who are currently online, making every<br>    conversation an adventure. </p><br><p>2. \ud83e\udd29\u00a0<b>Close Friends-Only Private Story</b></p><br><p>Another PicU\u2019s standout features is the ability for users to create and share posts that are only visible to their connections. Unlike traditional social media platforms where posts are public, PicU provides a more intimate space for users to share personal<br>    moments and thoughts. <b><i>Whether it\u2019s a photo, a story, or a status update, only the people you\u2019ve added as chat mates can see what you post.</i></b> This creates a sense of exclusivity and trust within your circle, encouraging meaningful engagement<br>    and deeper connections.</p><br><p>3. \ud83c\udfaf\u00a0<b>Only Match Onine Singles</b></p><br><p>Get connected instantly with singles who are online! PicU dating app eliminates the need to wait\u2014no more waiting for your matches which are offline. As soon as you log in, you&#39;ll be matched with those who are already ready to chat in real-time.<b><i>Forget endless swiping or delays\u2014just fast, fluid, and fun interactions with people who are online and ready to connect right when you are!</i></b></p><br><p>4. \ud83c\udfac\u00a0<b>Multi Media Forms Social Experience</b></p><br><p>PicU places snaps or reels at the heart of the social experience. From starting random chats to posting updates, everything begins with a snap. This visual-first approach adds a layer of fun and creativity to online interactions, allowing users to express<br>    themselves in ways words alone cannot.<b><i> PicU makes visual storytelling an essential part of building connections.</i></b> With every snap, users get a glimpse into someone\u2019s world, making interactions feel more genuine and immersive.</p><br><p>5. \ud83d\udd12\u00a0<b>Privacy and Security Protection</b></p><br><p>At PicU, user privacy and safety are at the core of the experience. <b><i> In random chats, only when both users respond does the conversation<br>    continue.</i></b> This feature ensures that you\u2019re always in control of your interactions, helping to foster a safe and respectful environment for everyone. Additionally, no personal information is shared until you decide to take the connection further.</p><br><p>In summary, PicU offers a refreshing twist on traditional dating apps<b><i> by focusing on spontaneous, real-time chats and visual interactions</i></b>. Its emphasis on privacy, security, and personalized social sharing ensures that users can connect<br>    with confidence and creativity.</p><br><p><a href=\"http://www.google.com/url?q=http%3A%2F%2Fwww.pic-u.com%2Fprivacy-policy-PicU.html&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw0lUvmh-ZhwPCROd55pFZ8L\" rel=\"nofollow\">http://www.pic-u.com/privacy-policy-PicU.html</a></p><br><p><a href=\"http://www.google.com/url?q=http%3A%2F%2Fwww.pic-u.com%2FTerms-and-Conditions-picu.html&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw0Irmniyi3cb746eo3n-tMe\" rel=\"nofollow\">http://www.pic-u.com/Terms-and-Conditions-picu.html</a></p>",
    "summary": "No waiting! Picu brings all your soulmates online, ready to snap, chat & date.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 10021,
    "score": 4.6434784,
    "ratings": 418,
    "reviews": 64,
    "histogram": [
        18,
        7,
        18,
        18,
        356
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$6.99 - $59.99 per item",
    "developer": "Nextouch",
    "developerId": "Nextouch",
    "developerEmail": "contactus@pic-u.com",
    "developerWebsite": "https://www.pic-u.com/",
    "developerAddress": null,
    "privacyPolicy": "http://www.pic-u.com/privacy-policy-PicU.html",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/p3E9URVssGHwcq6N1Xce0D9-YCfyK6iCgVYNFDsH0YjwO7f6qG0pfcLpQdg__uvmhnkQ",
    "headerImage": "https://play-lh.googleusercontent.com/22tIPuzRcBe1NQT7TcVp1rFhh03aKGs3zsoOTG2i6_dylKN8_j_-zKhkO4UOKZRx7zs",
    "screenshots": [
        "https://play-lh.googleusercontent.com/y5QluNx-Gq1AIby-o7ARCq5ul23JaHspLE6qHg_EkNEvLXn9ZgKxRxyA6ko5e5e3lw",
        "https://play-lh.googleusercontent.com/F9CiecspvJvtNA9DgXuDNAzfPBim6nTPZnEpS_dvj1KN_FkS-EfHZKg18viANr4YMrE",
        "https://play-lh.googleusercontent.com/vJdhD8Fkpfc0fIos9w3Swf4UIls5GspOB5DoOQ7pKUCwO8wyR9jGdwF4NS89c_RfW2w",
        "https://play-lh.googleusercontent.com/1lb6yZOe4Vn_023rLiuoSV7hJcJWViBCdkWagTcwp8kG6ZK6VU4CjWDEjney3x8CJx4",
        "https://play-lh.googleusercontent.com/LFARQ4lXM670Dtn71HvQHSQq9AxR88Aopwt0I-1Iunfm71hTgclwkWAP1YE1QpyWE9w",
        "https://play-lh.googleusercontent.com/gg5HD54AMX6dmSY0f1JKccwdbdemNVcBe7BwaLnM1SW2CthOZDJHsiCPg-b8PC4tIw",
        "https://play-lh.googleusercontent.com/mP9wTQKS3ULUloWWFYDMDJsqGcOqF2s9qw2hq9FsUhWu4ikNPZwsYYov-AFGKUS1FBL7",
        "https://play-lh.googleusercontent.com/1FXXQA5gclAr8n6nYNxor6eNVH2XGKOCoIaSjlenngSAh1_dD-4QEsVHASY_mAYzSeo",
        "https://play-lh.googleusercontent.com/INuaP56joY-UN9p34oMxI-848WooAl1ak24cd6gnfl044CsrU2qep51Ncxmlzznmbnw",
        "https://play-lh.googleusercontent.com/ieU4igwCmS6w5C-rgEIlV1D2iE_ABL2q7PmAV2p-3xs4VNfoqaiA6mPqPa4ySDirmP0",
        "https://play-lh.googleusercontent.com/mzQ_LZEC5MRxaADn5pcxWvOk0DjAC8v69tHsxeOWNAcsmO9FDhFOcZV0aphe4sdmaA",
        "https://play-lh.googleusercontent.com/ejUhzh83VLMAyFjohuF6mntSkPEQIxdGfQuJmtsifzvZhMMippcaLE6blQjUhbEIRg",
        "https://play-lh.googleusercontent.com/XCH7wZVSjCRnoUVnYE86-OlesJD5G2Vlq7b_odFq87h4Mf0-qt3l2iItFXlwAa9lCA",
        "https://play-lh.googleusercontent.com/eNK20fSUDZzQPNNeWTVam9Sr3jordBi08NtlR1Ew-lczwZRpjHPJZ1AOP8hjAK5_cg",
        "https://play-lh.googleusercontent.com/ysaEGNQ1GT_fAq_R0vfqtx6zi-0fSMN6do09X8eLGon4UN2tWSQaX7f98hiAnSo9yA",
        "https://play-lh.googleusercontent.com/YFYCw0EwOZuZ_sgPISlodVhcENIVaofHbDppyp-e9tyXBniRXGjUBcQ0qAB3fDilmXkL",
        "https://play-lh.googleusercontent.com/Fc2VfAuJOjTrIIxsqI0XVrkWHr6g8xZxPmh7inzVhEZkUxt2O8xeQeB0KhGTaDl5EqhL",
        "https://play-lh.googleusercontent.com/7roq8LWd3e5tJskO_mOSjiypasKuGlCebolRufxhyBMyCrSDQN1k4j2jpScvlA40qLKU",
        "https://play-lh.googleusercontent.com/T5mq2HEbM1kav1KObV7Q6sJp0XpAaadvTwvFN2KrdNkZH2w4azmuf9ZwrTJvNViNGjw",
        "https://play-lh.googleusercontent.com/vOQbc5g_OV3qbm96TbXsQJLughVqCa9Gl0iA6yjyTBzb2Aww2ZnNTJMLupAr2DKp6Q"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 19, 2024",
    "lastUpdatedOn": "Nov 14, 2024",
    "updated": 1731644353,
    "version": "1.4.2",
    "comments": [],
    "appId": "com.picu.app",
    "url": "https://play.google.com/store/apps/details?id=com.picu.app&hl=en&gl=us"
}