{
    "title": "MeetMe: Chat & Meet New People",
    "description": "Meet, Chat, and Go Live on MeetMe!\r\n\r\nMeetMe helps you find new people nearby who share your interests and want to chat now! It\u2019s fun, friendly, and free! Connect for free with friendly nearby locals who want to chat now with fun text, video, and livestreaming features! MeetMe makes it easy to find people nearby for free!\r\n\r\nDiscover people nearby, for Free!\r\n\r\nOn MeetMe there are 100+ million people also looking to meet new people like you, and our free features make meeting new people easy and fun! Strike up a text or video chat with someone local who shares your interests. Or you can broadcast yourself out to the world and have the people come to you by streaming on Live!\r\n\r\nChat with Anyone\r\nBreak the ice with people nearby or around the world. Unlike some other apps, messaging is always free on MeetMe.\r\n\r\nBeat boredom!\r\nThere is non-stop entertainment in Live on MeetMe! Create your own Livestream and start building your following as you climb the leaderboard getting to know our passionate livestreaming community. In Live, you can give and receive gifts, battle, and even go on dates. You can also enjoy hours of entertainment from watching our featured Live shows, and maybe even start your own Live show! MeetMe empowers creators on Live!\r\n\r\nFind Friends\u2026 and more than friends\r\nIt doesn\u2019t matter if you\u2019re just looking to chat and make friends, looking for a date, or looking for your soulmate \u2013 you\u2019ll find them on MeetMe. What are you waiting for?\r\n\r\n\r\n\r\nTestimonials \r\n\r\n\r\n\u201cI\u2019m very grateful for MeetMe because I never would have thought in a million years that it would help me \u2026 have friends that I have learned to love, and people from here that I want to attend my wedding because that\u2019s how close we are, and then meeting the love of my life too, it\u2019s so crazy how it\u2019s done all these things for me.\u201d - Gabe\r\n\r\n\r\n\u201cThis has allowed me to stay home, still be social - but then I can blend it with the real world. Now I\u2019ve started meeting all these amazing people I\u2019ve met on MeetMe and they\u2019ve now become some of my great friends\u201d - Blake Premer\r\n\r\n\r\n\u201cWhen I downloaded MeetMe and got into livestreaming - I\u2019m able to hold conversations now and I feel more confident as a person\u201d - Charlie (CharmCharlie)\r\n\r\n\r\n\u201cMeetMe was the first place that I was really able to start to grow. Where on those other platforms people were into my message and my story, silliness and positivity, but MeetMe really granted me the opportunity to get directly to a lot more people and grow that family and that community on a much larger scale than I could before\u201d - Katy B.\r\n\r\n\r\n\u201cEvery corner of the world I now have friends in those places and it\u2019s because of the MeetMe platform\u201d - Choff",
    "descriptionHTML": "Meet, Chat, and Go Live on MeetMe!<br><br>MeetMe helps you find new people nearby who share your interests and want to chat now! It\u2019s fun, friendly, and free! Connect for free with friendly nearby locals who want to chat now with fun text, video, and livestreaming features! MeetMe makes it easy to find people nearby for free!<br><br>Discover people nearby, for Free!<br><br>On MeetMe there are 100+ million people also looking to meet new people like you, and our free features make meeting new people easy and fun! Strike up a text or video chat with someone local who shares your interests. Or you can broadcast yourself out to the world and have the people come to you by streaming on Live!<br><br>Chat with Anyone<br>Break the ice with people nearby or around the world. Unlike some other apps, messaging is always free on MeetMe.<br><br>Beat boredom!<br>There is non-stop entertainment in Live on MeetMe! Create your own Livestream and start building your following as you climb the leaderboard getting to know our passionate livestreaming community. In Live, you can give and receive gifts, battle, and even go on dates. You can also enjoy hours of entertainment from watching our featured Live shows, and maybe even start your own Live show! MeetMe empowers creators on Live!<br><br>Find Friends\u2026 and more than friends<br>It doesn\u2019t matter if you\u2019re just looking to chat and make friends, looking for a date, or looking for your soulmate \u2013 you\u2019ll find them on MeetMe. What are you waiting for?<br><br><br><br>Testimonials <br><br><br>\u201cI\u2019m very grateful for MeetMe because I never would have thought in a million years that it would help me \u2026 have friends that I have learned to love, and people from here that I want to attend my wedding because that\u2019s how close we are, and then meeting the love of my life too, it\u2019s so crazy how it\u2019s done all these things for me.\u201d - Gabe<br><br><br>\u201cThis has allowed me to stay home, still be social - but then I can blend it with the real world. Now I\u2019ve started meeting all these amazing people I\u2019ve met on MeetMe and they\u2019ve now become some of my great friends\u201d - Blake Premer<br><br><br>\u201cWhen I downloaded MeetMe and got into livestreaming - I\u2019m able to hold conversations now and I feel more confident as a person\u201d - Charlie (CharmCharlie)<br><br><br>\u201cMeetMe was the first place that I was really able to start to grow. Where on those other platforms people were into my message and my story, silliness and positivity, but MeetMe really granted me the opportunity to get directly to a lot more people and grow that family and that community on a much larger scale than I could before\u201d - Katy B.<br><br><br>\u201cEvery corner of the world I now have friends in those places and it\u2019s because of the MeetMe platform\u201d - Choff",
    "summary": "Go Live, Chat & Meet New People! Friends. And more than friends.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 100557655,
    "score": 3.5819328,
    "ratings": 1627045,
    "reviews": 255781,
    "histogram": [
        436096,
        69337,
        103369,
        148105,
        870128
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.00 - $99.99 per item",
    "developer": "MeetMe.com",
    "developerId": "6473407804312298372",
    "developerEmail": "support@meetme.com",
    "developerWebsite": "http://www.meetme.com/",
    "developerAddress": "100 Union Square Drive\nNew Hope, PA 18938\n",
    "privacyPolicy": "https://m.meetme.com/terms/phoenix#privacyPolicy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/iCqsm7cH0HX2rNHu298w-dGKEYY4M5krj6yuy322nvY7cC0QG-A2V8aYJ6Euod5zT30",
    "headerImage": "https://play-lh.googleusercontent.com/LLrabnV7_ZqcEWTf0Cfi07zdVyrin9hXzwNX7S4rcmBBdNntFV31aV85xoB5nme2ais",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Mwem4PmTfNThoZ0CQvhfutkbxTRYtT9z-GO7CadqCTe0xnT-jBQCuEQKvtd6641kiJ0",
        "https://play-lh.googleusercontent.com/0OwttrJrQS5FVSZ-XAJwknrYDGpekRcCToIZ7zxE-dTEfGZXEFGJQ_lJk38H3E0tHQ",
        "https://play-lh.googleusercontent.com/XqopCjy99K5OjJQl1pnG8LRrTvD_uIUYn4mJ_k_a84beiFRmCqiCmxzdahk-xK9mKA",
        "https://play-lh.googleusercontent.com/BrTRrAd9-UKYVjdUTbiWM9hVEu_GK7_iE9NsxJCRE6MBO4xJjo0kqU3KajNXaVrPAEU",
        "https://play-lh.googleusercontent.com/oNDgMO_wdQiHrl2LElOorAFg5SE0ZM1_OBQhh2pYi5V80_VahUzjOFGPS3c925Vrzow",
        "https://play-lh.googleusercontent.com/rAZBflQhh_V0eCdB2qsVO5dFG9TOpIC2KYRoZj4uHbwTg92fZYLX-gP76WDq57bQiA",
        "https://play-lh.googleusercontent.com/f54aDR0Ruf7TwX9mkgxxof_hYi04ghsG1jwa1EmLI-9M-9C2TIOHN2cMYr71QPWo-a0",
        "https://play-lh.googleusercontent.com/xV0bLHFnGZglBWmE17TOV-bY-SXXGzbHjJa7AveX_Q4SNLqUSUJ-Bqn1Awa2kZAZAxk"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 1, 2010",
    "lastUpdatedOn": "Oct 24, 2024",
    "updated": 1729801908,
    "version": "14.74.0.4303",
    "comments": [],
    "appId": "com.myyearbook.m",
    "url": "https://play.google.com/store/apps/details?id=com.myyearbook.m&hl=en&gl=us"
}