{
    "title": "Dashtoon: Comics & Manga",
    "description": "We at Dashtoon are curating the best stories across the globe and visualising them into comics and graphic novels. Discover dazzling universes, soaring beyond superheroes and clich\u00e9s! A realm awaits. It\u2019s as if Manga creators and American directors teamed up to craft spellbinding comics. Brace yourself for mind-blowing diversity!\r\n\r\nBinge-read top-trending series, each transporting you to unique realms beyond imagination. Uncover mysteries, experience wonder, and find the story you love, waiting just a click away.\r\nWhether you crave love tales, heart-pounding adventures, or the thrill of the in-between, every manga enthusiast will find their uninterrupted narrative fix, with a new episode per comic every week.\r\n\r\nVenture into the vibrant world of globalised manga and manhwa, filled with captivating plots and stunning graphics. Newbie or seasoned reader, Dashtoon satisfies your quest for adventure, curiosity, passion, and more.\r\n\r\n\r\nExperience the joy of endless binge-reading. We globalize manga and manhwa, making them fun and accessible. So, sit back, relax, and let our comics transport you to a universe of boundless discovery. \r\n\r\nYou're one click away from unearthing the next Naruto, One Piece, or Pokemon sensation! Join us on our quest to unleash the next groundbreaking Anime franchise upon the world!",
    "descriptionHTML": "We at Dashtoon are curating the best stories across the globe and visualising them into comics and graphic novels. Discover dazzling universes, soaring beyond superheroes and clich\u00e9s! A realm awaits. It\u2019s as if Manga creators and American directors teamed up to craft spellbinding comics. Brace yourself for mind-blowing diversity!<br><br>Binge-read top-trending series, each transporting you to unique realms beyond imagination. Uncover mysteries, experience wonder, and find the story you love, waiting just a click away.<br>Whether you crave love tales, heart-pounding adventures, or the thrill of the in-between, every manga enthusiast will find their uninterrupted narrative fix, with a new episode per comic every week.<br><br>Venture into the vibrant world of globalised manga and manhwa, filled with captivating plots and stunning graphics. Newbie or seasoned reader, Dashtoon satisfies your quest for adventure, curiosity, passion, and more.<br><br><br>Experience the joy of endless binge-reading. We globalize manga and manhwa, making them fun and accessible. So, sit back, relax, and let our comics transport you to a universe of boundless discovery. <br><br>You&#39;re one click away from unearthing the next Naruto, One Piece, or Pokemon sensation! Join us on our quest to unleash the next groundbreaking Anime franchise upon the world!",
    "summary": "Discover diverse genres! Manga flair, Manhwa twist, globalised for the World.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 419155,
    "score": 4.8250775,
    "ratings": 13856,
    "reviews": 744,
    "histogram": [
        127,
        105,
        213,
        1157,
        12246
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.49 - $199.00 per item",
    "developer": "Dashverse",
    "developerId": "Dashverse",
    "developerEmail": "tech@dashtoon.com",
    "developerWebsite": "https://dashtoon.com/",
    "developerAddress": null,
    "privacyPolicy": "https://dashtoon.com/privacy-policy",
    "genre": "Comics",
    "genreId": "COMICS",
    "categories": [
        {
            "name": "Comics",
            "id": "COMICS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/vmEQe0Oc4qIPHhvuHIyqqlZZBwTFz3VRiTEGmN1C2kWZDgeB-0h3eKmzQ2Xv1ZWaoWse",
    "headerImage": "https://play-lh.googleusercontent.com/f0o1i5btEjeZFEJTPyhwtGv80x6FDXrb9TKu8kbMzC7WHobGz2Lqve1Kbo4eVyIh48Y",
    "screenshots": [
        "https://play-lh.googleusercontent.com/fLUqwTMlj8GWceoWqHBrgLrQX0HM9600_xWqT9weDxqT-KSFusfuE2Ok6dldtdOzM5CN",
        "https://play-lh.googleusercontent.com/XxzDbBhUcH8I7tznkh99F6UNjAlw_I11yU0I-TAESlGTovBccjHnRJvfVYbfx1yJPQ",
        "https://play-lh.googleusercontent.com/ntNIU961HhCkGqvRqyDXXuT113hiW7RIJPWXZBLiOQUK4Tf8goEpza-_tbHYa60cYduq",
        "https://play-lh.googleusercontent.com/l6o-Or5FgkCTifU20jvNVVud1TagL6XWRjqWVXlpVDRmnhI9YgqBRTijA_NfKOp2OLA",
        "https://play-lh.googleusercontent.com/KEwmqsbJpEkrteBgPq5UhqsnKIHpVPiSuGqFFAun92CIiuulXNZej_jHuXv0bJM0PhpQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 8, 2023",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731940374,
    "version": "2.6.63",
    "comments": [],
    "appId": "com.dashtoon.app",
    "url": "https://play.google.com/store/apps/details?id=com.dashtoon.app&hl=en&gl=us"
}