{
    "title": "Paired: Couples & Relationship",
    "description": "Paired is the #1 couples app, designed by experts to help you stay in love. Together, you and your partner can learn how to communicate better, manage conflict, and feel connected on a deeper level.\r\n\r\n\u2764\ufe0f 8 million downloads\r\n\ud83c\udfc6 Google Play Awards, 2020 Winner in Personal Growth\r\n\ud83d\udc9c Scientifically proven to increase relationship satisfaction\r\n\ud83d\uddde\ufe0f Featured in BBC News, The Times, Bustle, and more\r\n\r\nMAKE CONNECTION A DAILY HABIT\r\nWith Paired\u2019s Daily Conversations, you can effortlessly dedicate time each day to build strong communication, encourage intimacy, and strengthen your relationship.\r\n\r\nJOIN PAIRED WITH YOUR PARTNER\r\nAdd your answers to our questions for couples, and then unlock your partners responses to start a discussion, discover more about them and build a deep connection.\r\n\r\nREACH YOUR RELATIONSHIP GOALS\r\nPaired\u2019s guided journeys support you in developing the skills you need to help your relationship to thrive, with activities and conversations each day to build habits.\r\n\r\nDEEPEN YOUR CONNECTION\r\nPaired is the relationship app that helps couples to dive into subjects they don\u2019t often discuss, from household finances to love language, with guidance from experts to ensure sure it\u2019s always healthy and productive.\r\n\r\nFOCUS ON THE TOPICS THAT MATTER\r\nPaired has thousands of relationship games, quizzes, and questions, suitable for all stages of your couple, whether you\u2019re married, newly dating, or in a long-distance relationship.\r\n\r\nCELEBRATE EVERY EVENT, BIG AND SMALL\r\nUse Paired to keep track of the important dates in your relationship, from the big ones like anniversaries and birthdays, to the small, significant moments, like your first kiss or your favorite date night.\r\n\r\nJoin millions around the world using the Paired, the app for couples, to build happier, lasting relationships.\r\n\r\nQuestions? Suggestions? Let us know at support@paired.com.\r\n\r\n*****\r\n\r\nPlease note that Paired and the materials and information contained herein are not intended to, and do not constitute medical, psychological, or mental health advice, or diagnosis, and may not be used for such purposes. You should always consult with a qualified physician or mental health professional about your specific circumstances.\r\n\r\nOur Privacy Policy: https://www.paired.com/privacy_policy.html\r\nOur Terms and Conditions: https://www.paired.com/terms_and_conditions.html",
    "descriptionHTML": "Paired is the #1 couples app, designed by experts to help you stay in love. Together, you and your partner can learn how to communicate better, manage conflict, and feel connected on a deeper level.<br><br>\u2764\ufe0f 8 million downloads<br>\ud83c\udfc6 Google Play Awards, 2020 Winner in Personal Growth<br>\ud83d\udc9c Scientifically proven to increase relationship satisfaction<br>\ud83d\uddde\ufe0f Featured in BBC News, The Times, Bustle, and more<br><br>MAKE CONNECTION A DAILY HABIT<br>With Paired\u2019s Daily Conversations, you can effortlessly dedicate time each day to build strong communication, encourage intimacy, and strengthen your relationship.<br><br>JOIN PAIRED WITH YOUR PARTNER<br>Add your answers to our questions for couples, and then unlock your partners responses to start a discussion, discover more about them and build a deep connection.<br><br>REACH YOUR RELATIONSHIP GOALS<br>Paired\u2019s guided journeys support you in developing the skills you need to help your relationship to thrive, with activities and conversations each day to build habits.<br><br>DEEPEN YOUR CONNECTION<br>Paired is the relationship app that helps couples to dive into subjects they don\u2019t often discuss, from household finances to love language, with guidance from experts to ensure sure it\u2019s always healthy and productive.<br><br>FOCUS ON THE TOPICS THAT MATTER<br>Paired has thousands of relationship games, quizzes, and questions, suitable for all stages of your couple, whether you\u2019re married, newly dating, or in a long-distance relationship.<br><br>CELEBRATE EVERY EVENT, BIG AND SMALL<br>Use Paired to keep track of the important dates in your relationship, from the big ones like anniversaries and birthdays, to the small, significant moments, like your first kiss or your favorite date night.<br><br>Join millions around the world using the Paired, the app for couples, to build happier, lasting relationships.<br><br>Questions? Suggestions? Let us know at support@paired.com.<br><br>*****<br><br>Please note that Paired and the materials and information contained herein are not intended to, and do not constitute medical, psychological, or mental health advice, or diagnosis, and may not be used for such purposes. You should always consult with a qualified physician or mental health professional about your specific circumstances.<br><br>Our Privacy Policy: https://www.paired.com/privacy_policy.html<br>Our Terms and Conditions: https://www.paired.com/terms_and_conditions.html",
    "summary": "Questions, quizzes, advice & games for couples to support love or marriage",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3343223,
    "score": 4.526123,
    "ratings": 38542,
    "reviews": 3769,
    "histogram": [
        1256,
        640,
        2820,
        5668,
        28152
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$12.99 - $99.99 per item",
    "developer": "Paired - Relationship Advice & Quiz for Couples",
    "developerId": "5958832408214147601",
    "developerEmail": "support@paired.com",
    "developerWebsite": "http://www.paired.com",
    "developerAddress": "Paired\n3rd Floor\n86-90 Paul Street\nLondon EC2A 4NE\nUK",
    "privacyPolicy": "https://getpaired.com/privacy_policy.html",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/61Ai0lo4hXw-onsZEApxAFOcerTaQ4sYWD7pAV9FWP2SX3KoDXTARZV62Pj85TvHmZE",
    "headerImage": "https://play-lh.googleusercontent.com/YMJvVHJ3gcZncmIDzIwXayN9Ij7suWGQNvD4FLJgVcCXwEfZmP55LJRvNxJA_SL8lg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/eVQ16u65nWVIPaTuIVxzU_EQ6H67ZGx1VTmQmt6zabP4mCgaAJWuKKu_DeiVyY0Xo1U",
        "https://play-lh.googleusercontent.com/CzD-oqD8ff8PwJVc9FdKyUT1l4qtpAW47gmXucRKD10eDH8hCmwkoLgIYgvf800RTsE",
        "https://play-lh.googleusercontent.com/3zAXN2Bq8qsWeo3xR4OelOS3HJ56Fq9dm_ix_47LGhqGVkUb3_e8erLwCFzIYjwJeF9m",
        "https://play-lh.googleusercontent.com/iW4WP2_VQ1ggiq1Oi_C6rSqQALzNsdTPpUWaUEHb6eDwBMPR5qT24ugAyDQECgkAb6tJ",
        "https://play-lh.googleusercontent.com/pgdoDqNV1SCGO81Fp06nzheXFZNAjntydNKKKxUDjcpLN-O8wh0qI9Tw7oCCwpsWAg",
        "https://play-lh.googleusercontent.com/MjYdfwP3uNIdlmP6PqGDkte08eUqx7Kd_Wyq_HaGLkiBGA0MrZJbCyNaEkZWDPX4MG8",
        "https://play-lh.googleusercontent.com/rBYYSkukqpf80FgNC8CNJ1Qjr1GlnqNWbC7rJbjAF1vC3RNsccwJ-7b1NjAocuhqDm4",
        "https://play-lh.googleusercontent.com/kVwEy2Ugu_w-8xnfk_bGabMeZWfYy44NtCOpEWu_rD6xXI3M4esK8QUjoa_wnPj0Sdk"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Sexual Themes",
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 17, 2020",
    "lastUpdatedOn": "Nov 19, 2024",
    "updated": 1732035141,
    "version": "2.11.0",
    "comments": [],
    "appId": "com.getpaired.app",
    "url": "https://play.google.com/store/apps/details?id=com.getpaired.app&hl=en&gl=us"
}