{
    "title": "Tropical Smoothie Cafe",
    "description": "Install the Tropical Smoothie Cafe\u00ae app today to make ordering delicious tropic faves easy breezy. Use the app to order delivery or order ahead* for pickup, earn points toward free sips & bites, customize menu items and more. Our better-for-you smoothies, bowls, wraps, flatbreads & more are made-to-order with quality ingredients.\r\n \r\nFree Smoothie** After First Purchase\r\nDon\u2019t forget to join the Tropic Rewards\u00ae fam when you download the app and score a FREE smoothie** after your first purchase.\r\n \r\nRewards\r\nTropic Rewards members earn 10 points for every $1 spent when signed in and ordering in the app, scanning the app at the register or scanning the receipt after purchase.. Redeem points for free menu items.\r\n \r\nCustomize Tropic Faves\r\nCustomize your favorite smoothie and food items your way when you order in the app.\r\n \r\n*Terms and conditions apply.\r\n**At participating locations.",
    "descriptionHTML": "Install the Tropical Smoothie Cafe\u00ae app today to make ordering delicious tropic faves easy breezy. Use the app to order delivery or order ahead* for pickup, earn points toward free sips &amp; bites, customize menu items and more. Our better-for-you smoothies, bowls, wraps, flatbreads &amp; more are made-to-order with quality ingredients.<br> <br>Free Smoothie** After First Purchase<br>Don\u2019t forget to join the Tropic Rewards\u00ae fam when you download the app and score a FREE smoothie** after your first purchase.<br> <br>Rewards<br>Tropic Rewards members earn 10 points for every $1 spent when signed in and ordering in the app, scanning the app at the register or scanning the receipt after purchase.. Redeem points for free menu items.<br> <br>Customize Tropic Faves<br>Customize your favorite smoothie and food items your way when you order in the app.<br> <br>*Terms and conditions apply.<br>**At participating locations.",
    "summary": "Order ahead, earn rewards, find cafes and more!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2285404,
    "score": 4.5152936,
    "ratings": 43984,
    "reviews": 5469,
    "histogram": [
        2954,
        686,
        1246,
        4938,
        34153
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Tropical Smoothie Cafe",
    "developerId": "Tropical+Smoothie+Cafe",
    "developerEmail": "tsctechnology@tropicalsmoothie.com",
    "developerWebsite": "https://www.tropicalsmoothiecafe.com/",
    "developerAddress": "1117 Perimeter Center West\nSuite W200\nAtlanta, GA 30338",
    "privacyPolicy": "https://www.tropicalsmoothiecafe.com/privacy/",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/amRtzkIqaVWx3jDrjjKrCeNOxKKFDNK4-aiskpGzf-9ON2YETN09X7JJdukXltlkHg",
    "headerImage": "https://play-lh.googleusercontent.com/FSkA5cmY67So7lGd_wdJSjMh5Z2du4jfu50OOjnLby0Ht31Defvrx99uOpVReQn8Ibg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/gp3pbtnhca76IbqfJ17zFxnTKWTJaXXnmtmCMM99FMGDfyaoG-AnVZEqgtZV0fsK7GA",
        "https://play-lh.googleusercontent.com/u8P9pVOKHd7oDz6rmj0-IE4Y9e8kPF8uHmsw37DvojCbK9HRmHCwqu9wRKoxA36PiZNi",
        "https://play-lh.googleusercontent.com/rMIyE8NOufUEiyFQlc0FEL3ycM-0DKhyo9IvYcvCwV1vXPRjx5AGV3iafkZ6vPDCmQ",
        "https://play-lh.googleusercontent.com/R0EnJIoTOWjQ2821ARDdg1BxFc_B3r6Mcaa3eP8C8rZy3yv7WNaSVP7zoIAs6vMCwuQ",
        "https://play-lh.googleusercontent.com/eWTgyNuM6eCp5hBTm5Zwsu_uer1SBcsyQYsqr3gxwztVdf-Qggufd8sV4cdplms76HNr"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 21, 2015",
    "lastUpdatedOn": "Oct 25, 2024",
    "updated": 1729861487,
    "version": "5.7.1",
    "comments": [],
    "appId": "com.tropicalsmoothie.tropicalsmoothiecafe.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.tropicalsmoothie.tropicalsmoothiecafe.android.app&hl=en&gl=us"
}