{
    "title": "IKEA",
    "description": "The IKEA mobile app is where your inspiration comes to life. Find that cute armchair you saw at your friend\u2019s place or look through thousands of products and ideas just for you - to make your space truly your own.\r\n\r\nWhether you\u2019re looking to buy online or in-store, the IKEA app is your perfect shopping companion.\r\n\r\nScan the products with Shop & Go while you walk through the store  - and skip the checkout line.\r\n\r\nAre you planning a big project or small home improvements? Save and organize your favorites in lists for later. They are ready when you are!\r\n\r\nFound the perfect IKEA furniture or home decoration? Let us do the heavy lifting. Order home delivery and be informed every step of the way, by tracking your order easily in the app.\r\n\r\nThe IKEA app is also a convenient home for your IKEA Family benefits. Access your IKEA Family card quickly and find all your past receipts conveniently in one location.\r\n\r\nIKEA values your data privacy and believes in ethical use of customer data. That\u2019s why you\u2019re in control of all your data at all times.",
    "descriptionHTML": "The IKEA mobile app is where your inspiration comes to life. Find that cute armchair you saw at your friend\u2019s place or look through thousands of products and ideas just for you - to make your space truly your own.<br><br>Whether you\u2019re looking to buy online or in-store, the IKEA app is your perfect shopping companion.<br><br>Scan the products with Shop &amp; Go while you walk through the store  - and skip the checkout line.<br><br>Are you planning a big project or small home improvements? Save and organize your favorites in lists for later. They are ready when you are!<br><br>Found the perfect IKEA furniture or home decoration? Let us do the heavy lifting. Order home delivery and be informed every step of the way, by tracking your order easily in the app.<br><br>The IKEA app is also a convenient home for your IKEA Family benefits. Access your IKEA Family card quickly and find all your past receipts conveniently in one location.<br><br>IKEA values your data privacy and believes in ethical use of customer data. That\u2019s why you\u2019re in control of all your data at all times.",
    "summary": "With the IKEA app, you can explore, shop for furniture, and check out\u2014simply.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 40891965,
    "score": 4.610185,
    "ratings": 203526,
    "reviews": 2823,
    "histogram": [
        9783,
        3562,
        4882,
        19585,
        165637
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Inter IKEA Systems B.V",
    "developerId": "Inter+IKEA+Systems+B.V",
    "developerEmail": "ikeaandroidapp@ikea.com",
    "developerWebsite": "https://www.ikea.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.ikea.com/gb/en/customer-service/privacy-policy/",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/U_hRwbvZcVxq32BmCBGRd-dH9S2PmkiFovPdEz5CPDzMzELNYP7njs44EQFqTWQJIdc",
    "headerImage": "https://play-lh.googleusercontent.com/ZeUtX5IdkunPYdX17x-Ap_xsBwboF-3Lji3_rIKOmXOUB5KYk0KBWeXQ6lV5mJo1HQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/m7cUT-a1vBQzO2eRsj2Crn4cWn9GDhjwS7meyVcUv_CqrM8PACoi_aQs8LhYASqicg",
        "https://play-lh.googleusercontent.com/jHchlBMtj2pXnqubZkPBQma1KeuvcnUzTkUigOYCGjNoU7cLLw4jfOt79476dDRa0Lt9",
        "https://play-lh.googleusercontent.com/FSrKbw0xgr4WZaogiM9YO_gc3KQUzlhmMtG3Qv4ttHMBcY0BU2ufhVJ4v4KQsZxTOFEc",
        "https://play-lh.googleusercontent.com/8dLI--VMTDFPuTnbZsL8fdvM5MQchjbF5Jyb8eeTp_T2Fa0UJ6dJEjPYq6bHnsfh6Q",
        "https://play-lh.googleusercontent.com/gbwFSKdODfSvh64ub0Mghcwk1-x4ywhngNoOAZx3xk6plZPNieCQ-VqWyddCxfONG0ai",
        "https://play-lh.googleusercontent.com/lwpAEcL9SELTOfBKZLRG9Ij2JATd1-aJWdI8ql-Qe-sMsIdUOt3nQL-8JNG2iamasIJD",
        "https://play-lh.googleusercontent.com/_ITk5OqbL_yQrhJSzBDLIBMsxbUuM0LR16DN8RN1B81TVsSTgHslPBabYV1-Hsw7cWNE",
        "https://play-lh.googleusercontent.com/onEIl7JgxljuE12ASwqre7NWkfWkdRQAI6qNhFSGEN54I_WlrYGfG1TJzUc332mNB_Q",
        "https://play-lh.googleusercontent.com/1YKHSUdguk1V58YqITpYjban8eGqkEtqGWYjMpyWOFLSrgjomTi3gAcxw9qu3k760HM",
        "https://play-lh.googleusercontent.com/uoPyXii2IsRwK1QE3ToDrYRIVGbCnOJeboQBX6WJyntJ7lX7vB6Ruj8ObUAo6iL6gQ",
        "https://play-lh.googleusercontent.com/ZPtx2YVew_Cfh37nWFL4ZuIDwOU3ZnFqRqTq39MJGJcWmI9rgw2JpecWW1q2umF-BmNX",
        "https://play-lh.googleusercontent.com/QpGIThqXfy3lEmFa5SyGh39OC_M4ifyUKiixSRWDghffTxB0TmJEceaiJVRR8PBScrI",
        "https://play-lh.googleusercontent.com/vZPKkMOfDSA27MFCY3DbSsD_VVmZf3bytKFPIRjPH_RuMbk0AfBgNZ48_3HEKHX38Q",
        "https://play-lh.googleusercontent.com/hbWn8USFg2VvHUSusR7wqywGplC7CzyjApbweL1tPWYKrGjZ3Ma_4ZpnVXgFVV5u4w",
        "https://play-lh.googleusercontent.com/GMNIdHxp-D3nfP0KNLHGVLH0Ea53eTg3OW0ZDXUwDLPQhi2qBPtCmBoKwiZKr4XaFlw",
        "https://play-lh.googleusercontent.com/4iViXTD13O4hcus6l1fommRlzDNk7FGvF_ZmHANO9IJRvOrxJl47zpHrI8WmST6SKnY",
        "https://play-lh.googleusercontent.com/4fWuB70ydjBEB7PATthJPxL2ZgiMJzIHqAbxjt76nP-V7Lkx8mgdKhfEEWLZZTsp3A",
        "https://play-lh.googleusercontent.com/tboC1MFis-mPTsPrGSV0cahwKoDVXIXWbmiiH7nDLJOPtcdHz_jFZ8eTTl88eNL1Igk",
        "https://play-lh.googleusercontent.com/81Re1Wzhok6bpqg7DhsOTC3GJFBTcFl5F0SxWURUj8frbFEJjaFN9QwiUomioY3ynw",
        "https://play-lh.googleusercontent.com/IZliB81fOO1wjHAVxte5mWCuPS8T9DwpjqB1FLYlT72zE6WrHYz8EAB-XmF0gdGWqYjr",
        "https://play-lh.googleusercontent.com/J5yZt5gC1hJ8R9XHwJoJLJb1769l3IfHzm2VJP2NiQBUXcT8j3P3Foppcqhnv8DStcI",
        "https://play-lh.googleusercontent.com/KMPwc5Prtn7Vi_qYVz9HsVItEJokpNB1d0K9C5UMIvVeaiPtiO_pvNfxH5e1GwQQAA4",
        "https://play-lh.googleusercontent.com/2TcTZ1dKS1PSaSrj46ARHZDZOZANW_h9Gjf4a-EMPgvgMqPtgKYG0mFDibxrkz-j95f2",
        "https://play-lh.googleusercontent.com/TrG1RVPz8rSLGGK6mR8oznfwb__YPsCNPeOWPXLTqWtjjtRozjQ3nLz-2IHO6TF_Ng"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 24, 2020",
    "lastUpdatedOn": "Nov 13, 2024",
    "updated": 1731485610,
    "version": "4.4.1",
    "comments": [],
    "appId": "com.ingka.ikea.app",
    "url": "https://play.google.com/store/apps/details?id=com.ingka.ikea.app&hl=en&gl=us"
}