{
    "title": "Self - Credit Builder",
    "description": "Self is your credit building toolbox. Build credit, track your credit score, unlock a credit card, and more.\r\n\r\nWith the Self credit app, you\u2019ll have everything you might need to build credit. Low credit score or no credit score \u2014 get started today. At Self, all credit scores are welcome.\r\n\r\nBUILD CREDIT BY REPORTING YOUR RENT PAYMENTS AT NO COST\r\n- Increase your credit score at no cost*\r\n- Build credit with all 3 credit bureaus \u2014 Equifax, Experian, and TransUnion\r\n- No hard pull, no credit check\r\n- No credit card required\r\n- Establish positive payment history \u2014 credit\u2019s #1 factor\u2021\r\n- Track credit score with VantageScore 3.0\u00a7\r\n\r\nGROW YOUR CREDIT & SAVINGS WITH THE CREDIT BUILDER ACCOUNT\u2016\r\n- Lift your credit score by 49 points, on average\u00b6\r\n- Plans start at $25/mo.\u00b9\r\n- Unlock your savings at the end, minus interest and fees\u00b2\r\n- No credit score required\r\n- No hard credit inquiry, no credit check\r\n\r\nUNLOCK THE CREDIT CARD FOR CREDIT BUILDERS\r\n- Work toward a secured Self Visa\u00ae Credit Card\u00b3 with a Credit Builder Account\u2016\r\n- No credit check required\r\n- Control your credit limit\r\n- Build credit with all 3 credit bureaus\r\n- Use everywhere Visa is accepted in the US\r\n\r\nREPORT MORE PAYMENTS FOR MORE CREDIT\r\n- Build credit with cell phone, water, electricity, and gas payments for $6.95/mo.\r\n- Add up to 5 payments to your TransUnion credit report each month\r\n- Credit monitoring by TransUnion\r\n- Identity theft insurance up to $1 million\r\n- Cancel any time\r\n\r\nACCESS THE SELF VISA\u00ae CREDIT CARD\r\nThe secured Self Visa\u00ae Credit Card requires an active Self Credit Builder Account and qualification based on other eligibility criteria including income & expense requirements. Criteria subject to change.\r\n\r\n* Results vary. You may not receive an improved credit score. Not all lenders use scores impacted by rent reporting. Not all bill payments may be eligible. See learn.self.inc/lpg/mpa/rent-bills-landing for details.\r\n\r\n\u2021 See https://www.ficoscore.com/education#WhatYour FICO is a registered trademark of Fair Isaac Corporation in the United States and other countries.\r\n\r\n\u00a7 Credit scores only available to customers our 3rd party vendor is able to validate.\r\n\r\n\u2016 Credit Builder Accounts & Certificates of Deposit made/held by Lead Bank, Sunrise Banks, N.A., SouthState Bank, N.A., First Century Bank, N.A., each Member FDIC. Subject to credit approval.\r\n\r\n\u00b6 Average outcome for customers who opened a 12 month Credit Builder account in Q1 2021, starting VantageScore 3.0 under 600, who made on-time payments. Other factors, including activity with other creditors, may impact results. On-time payments does not mean full program completion and past performance based on study does not guarantee future results. Credit score increase not guaranteed.\r\n\r\n\u00b9 Minimum and maximum repayment period for all loan products is 24 months. Maximum Annual Percentage Rate (APR) of all loan products is 15.92%. Sample products are $25 monthly loan payment at a $520 loan amount, 24 month term and 15.92% APR, Total Payments of $600; Check the pricing page in the Self app or Self.inc for current pricing.\r\n\r\n\u00b2 Minus fees & interest. Individual results may vary and are not guaranteed. Improvement in your credit score is dependent on your specific situation & financial behavior. Failure to make monthly minimum payments by the due date each month may result in delinquent reporting to credit bureaus which may negatively impact your credit score. This product will not remove negative credit history from your credit report.\r\n\r\n\u00b3 The Self Visa\u00ae Credit Card is issued by Lead Bank, First Century Bank, N.A., or SouthState Bank, N.A., each Member FDIC. See Self.inc for details.\r\n\r\nSelf Financial, Inc. 901 E 6th Street Suite 400, Austin, TX 78702",
    "descriptionHTML": "Self is your credit building toolbox. Build credit, track your credit score, unlock a credit card, and more.<br><br>With the Self credit app, you\u2019ll have everything you might need to build credit. Low credit score or no credit score \u2014 get started today. At Self, all credit scores are welcome.<br><br>BUILD CREDIT BY REPORTING YOUR RENT PAYMENTS AT NO COST<br>- Increase your credit score at no cost*<br>- Build credit with all 3 credit bureaus \u2014 Equifax, Experian, and TransUnion<br>- No hard pull, no credit check<br>- No credit card required<br>- Establish positive payment history \u2014 credit\u2019s #1 factor\u2021<br>- Track credit score with VantageScore 3.0\u00a7<br><br>GROW YOUR CREDIT &amp; SAVINGS WITH THE CREDIT BUILDER ACCOUNT\u2016<br>- Lift your credit score by 49 points, on average\u00b6<br>- Plans start at $25/mo.\u00b9<br>- Unlock your savings at the end, minus interest and fees\u00b2<br>- No credit score required<br>- No hard credit inquiry, no credit check<br><br>UNLOCK THE CREDIT CARD FOR CREDIT BUILDERS<br>- Work toward a secured Self Visa\u00ae Credit Card\u00b3 with a Credit Builder Account\u2016<br>- No credit check required<br>- Control your credit limit<br>- Build credit with all 3 credit bureaus<br>- Use everywhere Visa is accepted in the US<br><br>REPORT MORE PAYMENTS FOR MORE CREDIT<br>- Build credit with cell phone, water, electricity, and gas payments for $6.95/mo.<br>- Add up to 5 payments to your TransUnion credit report each month<br>- Credit monitoring by TransUnion<br>- Identity theft insurance up to $1 million<br>- Cancel any time<br><br>ACCESS THE SELF VISA\u00ae CREDIT CARD<br>The secured Self Visa\u00ae Credit Card requires an active Self Credit Builder Account and qualification based on other eligibility criteria including income &amp; expense requirements. Criteria subject to change.<br><br>* Results vary. You may not receive an improved credit score. Not all lenders use scores impacted by rent reporting. Not all bill payments may be eligible. See learn.self.inc/lpg/mpa/rent-bills-landing for details.<br><br>\u2021 See https://www.ficoscore.com/education#WhatYour FICO is a registered trademark of Fair Isaac Corporation in the United States and other countries.<br><br>\u00a7 Credit scores only available to customers our 3rd party vendor is able to validate.<br><br>\u2016 Credit Builder Accounts &amp; Certificates of Deposit made/held by Lead Bank, Sunrise Banks, N.A., SouthState Bank, N.A., First Century Bank, N.A., each Member FDIC. Subject to credit approval.<br><br>\u00b6 Average outcome for customers who opened a 12 month Credit Builder account in Q1 2021, starting VantageScore 3.0 under 600, who made on-time payments. Other factors, including activity with other creditors, may impact results. On-time payments does not mean full program completion and past performance based on study does not guarantee future results. Credit score increase not guaranteed.<br><br>\u00b9 Minimum and maximum repayment period for all loan products is 24 months. Maximum Annual Percentage Rate (APR) of all loan products is 15.92%. Sample products are $25 monthly loan payment at a $520 loan amount, 24 month term and 15.92% APR, Total Payments of $600; Check the pricing page in the Self app or Self.inc for current pricing.<br><br>\u00b2 Minus fees &amp; interest. Individual results may vary and are not guaranteed. Improvement in your credit score is dependent on your specific situation &amp; financial behavior. Failure to make monthly minimum payments by the due date each month may result in delinquent reporting to credit bureaus which may negatively impact your credit score. This product will not remove negative credit history from your credit report.<br><br>\u00b3 The Self Visa\u00ae Credit Card is issued by Lead Bank, First Century Bank, N.A., or SouthState Bank, N.A., each Member FDIC. See Self.inc for details.<br><br>Self Financial, Inc. 901 E 6th Street Suite 400, Austin, TX 78702",
    "summary": "Up your score* with rent payments fast at no cost, or build credit and savings.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3734922,
    "score": 4.524017,
    "ratings": 84911,
    "reviews": 35558,
    "histogram": [
        5957,
        1299,
        2458,
        7766,
        67426
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Self Financial, Inc.",
    "developerId": "Self+Financial,+Inc.",
    "developerEmail": "support@self.inc",
    "developerWebsite": "https://www.self.inc",
    "developerAddress": null,
    "privacyPolicy": "https://www.self.inc/privacy-policy",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ANmjDcEa8GvshZN658mUpvX0Wdz2wVXppOoiNQTXhqtdLsnjzWSkydAUpgMPoeZiqCk",
    "headerImage": "https://play-lh.googleusercontent.com/n3Y2un4TcxgsRs46-4V-oA9bLap_CWaVH1dsJjGNQT2i5E3OiawCUZHhoahZu6fLcOke",
    "screenshots": [
        "https://play-lh.googleusercontent.com/MZ5MiHYd_7Ai1XkpH1ySw5u_Iu7kjoiUieBjDwRh5STYhHi5mGBe9xZ7peboxPZ_Cjs",
        "https://play-lh.googleusercontent.com/m4HJ5ybMcBo3KsFXRcl5KvI1iaCW0eSjEeQCKGj3TZODn9HYLKeRkKdQN4qUTYKOqA",
        "https://play-lh.googleusercontent.com/pgloHQ8vbOiPhcJPzFKIjozeJkG6JfJBqiwIJ4CCz4E85GqBimXHBDbGoC4DRnzkQE0",
        "https://play-lh.googleusercontent.com/vBT7eF_nopa2P6CbO-Xed6gCxJUhbcbeRaIpygLhdXd371XpW5Q_19tY2uXVxrJrVjY",
        "https://play-lh.googleusercontent.com/A9varEhBH28p3Wh9r3oP5C5diMRBWUICgZi-YIjTWHgElnSLAc7WLUQcbQnfYeav8K8",
        "https://play-lh.googleusercontent.com/PeukDTod6Ewh71Egv4hFRd8emCTLqJczZV9fWknlRH33e_CTGTQSVCn1Fe4xsTdFlDQ",
        "https://play-lh.googleusercontent.com/X32UM3xM2UVZwBuXMlf25AMRLlRlAEGWiuqZtA3cbFNaMAd-gbsUpLOG6RQ2uKvFS4PI",
        "https://play-lh.googleusercontent.com/V9mYtzpsc71xkgeGjVLBitFHu-oTPpXrjC2GtquJ4i00InomdH_xcLvQj71VX_bEOMI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 30, 2018",
    "lastUpdatedOn": "Nov 14, 2024",
    "updated": 1731621126,
    "version": "5.10.0",
    "comments": [],
    "appId": "com.selflender.thor",
    "url": "https://play.google.com/store/apps/details?id=com.selflender.thor&hl=en&gl=us"
}