{
    "title": "POV \u2013 Disposable Camera Events",
    "description": "POV helps you capture the point of view of everyone at your event.\r\n\r\nLike a digital disposable camera \u2013\u2013 cap the number of photos that each of your guests can take and have the photos reveal the next day!\r\n\r\nNO DOWNLOAD REQUIRED FOR GUESTS\r\nGuests can scan a code or tap on a link and don't have to download this app to participate.\r\n\r\nCAMERA\r\nThe camera is completely customizable \u2013\u2013 you determine how many photos each of your guests can take.\r\n\r\nGALLERY\r\nThe gallery can reveal during the event or you can make people wait until the next day. Great for everyone to relive the next day.\r\n\r\nCUSTOMIZABILITY\r\nYou can design the screens to look and feel exactly how you want it. Stickers, text, backgrounds + more design tools at your fingertips.\r\n\r\nSHAREABILITY\r\nPurchase a QR code or some NFC tags so that friends can easily find your event.\r\n\r\nQuestions or ideas? Send us all your feedback. We're happy to help!",
    "descriptionHTML": "POV helps you capture the point of view of everyone at your event.<br><br>Like a digital disposable camera \u2013\u2013 cap the number of photos that each of your guests can take and have the photos reveal the next day!<br><br>NO DOWNLOAD REQUIRED FOR GUESTS<br>Guests can scan a code or tap on a link and don&#39;t have to download this app to participate.<br><br>CAMERA<br>The camera is completely customizable \u2013\u2013 you determine how many photos each of your guests can take.<br><br>GALLERY<br>The gallery can reveal during the event or you can make people wait until the next day. Great for everyone to relive the next day.<br><br>CUSTOMIZABILITY<br>You can design the screens to look and feel exactly how you want it. Stickers, text, backgrounds + more design tools at your fingertips.<br><br>SHAREABILITY<br>Purchase a QR code or some NFC tags so that friends can easily find your event.<br><br>Questions or ideas? Send us all your feedback. We&#39;re happy to help!",
    "summary": "For weddings, parties & events",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 593261,
    "score": 4.7,
    "ratings": 2850,
    "reviews": 73,
    "histogram": [
        84,
        56,
        112,
        112,
        2475
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $89.99 per item",
    "developer": "Untitled Tech, Inc.",
    "developerId": "Untitled+Tech,+Inc.",
    "developerEmail": "help+android@pov.camera",
    "developerWebsite": "https://pov.camera",
    "developerAddress": null,
    "privacyPolicy": "https://pov.camera/terms",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/wJ9rQd_bfyZJTNIIccgzspWpIngKrf4snZb7reLUrgWYKMJbpa4JWgWWUN_kJl8Iq1nA",
    "headerImage": "https://play-lh.googleusercontent.com/9QGLbzrKkdxcVQ1rNhNKfFnsTxZrfX_3XvtpRPi2sk5MYG56bRlmHUSTpCzTe6vg9hp6",
    "screenshots": [
        "https://play-lh.googleusercontent.com/KiVWFwPQXhYZVIXrEy9p4kyYjxkqyXEeTgFp-aOKP0xSgtX_aR9H36FsT3y--E1v",
        "https://play-lh.googleusercontent.com/1KU1buwu2RRe2WVPCSMMHHPLv7Im4plETcBxwtA3IijVblpQlcHLL1dlZ9N_gVw5uoI",
        "https://play-lh.googleusercontent.com/y7dPmyItn02MVHb6PrTlHmQMdLjQXN5mFrWT2kJaNAkeDlO7HONfpO60SRZPPK_4vWY",
        "https://play-lh.googleusercontent.com/VqIF05yR3POFPTxlxwdKcdhi4MGYNBCutVG3PGmT4e6_Sah9f99Phw2u_VvqSbxIDg",
        "https://play-lh.googleusercontent.com/MmhzoY5S26gpvmM2R5VHoK-en2iB7Jczi0MahcCVa6xf_tTmVG6DqNIWZqqfYLUhpvY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 22, 2022",
    "lastUpdatedOn": "Nov 1, 2024",
    "updated": 1730484586,
    "version": "1.28.9",
    "comments": [],
    "appId": "com.untitledshows.pov",
    "url": "https://play.google.com/store/apps/details?id=com.untitledshows.pov&hl=en&gl=us"
}