{
    "title": "Fishbrain - Fishing App",
    "description": "Fish smarter with Fishbrain! Find new fishing spots, get detailed local info, and connect with a community of 15 million anglers. Fishbrain provides you with the maps and tools you need to improve your fishing skills.\r\n\r\nFIND NEW FISHING SPOTS\r\nFishbrain is the fastest and easiest way to find places to fish. Explore thousands of fishing waters and see exactly where fish are being caught with the Fishbrain map. Take your scouting to the next level with advanced map layers and customization options. Whether you\u2019re fishing for bass, trout, catfish, redfish, or any other species, Fishbrain can help you set the hook.\r\n\r\nGET THE LATEST LOCAL INFO\r\nBe the first to know about fishing trends in your area. Get pictures and updates from local anglers. See which baits & lures are catching the most fish. Check weather conditions, tide charts, air pressure, moon phases, and advanced BiteTime forecasts. Search updated local fishing regulations in 25+ US states.\r\n\r\nTRACK YOUR FISHING ADVENTURES\r\nKeep track of your fishing trips to unlock personalized insights and tips. Log catches to remember the baits and weather patterns that led to success. Record all your favorite fishing moments, and share your catches with the community to celebrate with your fellow anglers.\r\n\r\nKEEP YOUR SPOTS SECRET\r\nYou control how much location info you share! Fishbrain\u2019s built-in privacy settings ensure you can keep info about your favorite fishing spots private.\r\n\r\nCONNECT WITH LIKE-MINDED ANGLERS\r\nFishing is better with friends, old and new. Fishbrain brings together passionate anglers from around the globe. Connect with other fishing enthusiasts, exchange tips & tricks, join fishing groups, learn new fishing techniques and so much more.\r\n\r\nFISHBRAIN APP FEATURES \r\n \u2022 Fishing maps with advanced map layers & filters\r\n \u2022 Find potential fishing access with the \"Parks & Government Land\" map layer\r\n \u2022 Detailed info on fishing waters, including recent photos & catch reports\r\n \u2022 Depth charts from Garmin Navionics (USA & Canada) and C-Map Social\r\n \u2022 \u201cTop Baits\u201d recommendations based on community reports\r\n \u2022 BiteTime fishing forecasts powered by advanced AI\r\n \u2022 Weather conditions, tide charts, air pressure, moon phases and more\r\n \u2022 Fishing logbook with personal stats & fishing insights\r\n \u2022 Private waypoints to keep track of your favorite fishing spots\r\n \u2022 Markers for boat ramps, tackle shops, and other points of interest\r\n \u2022 Social community with over 15 million members\r\n \u2022 Local fishing rules and regulations in 30+ US states\r\n\r\nGET MORE WITH FISHBRAIN PRO\r\nThe Fishbrain app is free to download and use. Upgrade to Fishbrain Pro to unlock all the most advanced features. Fishbrain Pro makes finding your next fishing spot even easier, and gives you all the data you need to make great decisions about where to go fishing.\r\n\r\nWhether you\u2019re a beginner just learning how to fish, or an experienced angler chasing your next PB, Fishbrain will help you along your journey as an angler! Download Fishbrain today and start knowing the water like never before.\r\n\r\nPrivacy policy: https://fishbrain.com/privacy\r\nTerms and conditions: https://fishbrain.com/terms-of-service\r\nLike us on Facebook: https://www.facebook.com/fishbrainapp\r\nFollow us on Instagram: https://www.instagram.com/fishbrainapp",
    "descriptionHTML": "Fish smarter with Fishbrain! Find new fishing spots, get detailed local info, and connect with a community of 15 million anglers. Fishbrain provides you with the maps and tools you need to improve your fishing skills.<br><br>FIND NEW FISHING SPOTS<br>Fishbrain is the fastest and easiest way to find places to fish. Explore thousands of fishing waters and see exactly where fish are being caught with the Fishbrain map. Take your scouting to the next level with advanced map layers and customization options. Whether you\u2019re fishing for bass, trout, catfish, redfish, or any other species, Fishbrain can help you set the hook.<br><br>GET THE LATEST LOCAL INFO<br>Be the first to know about fishing trends in your area. Get pictures and updates from local anglers. See which baits &amp; lures are catching the most fish. Check weather conditions, tide charts, air pressure, moon phases, and advanced BiteTime forecasts. Search updated local fishing regulations in 25+ US states.<br><br>TRACK YOUR FISHING ADVENTURES<br>Keep track of your fishing trips to unlock personalized insights and tips. Log catches to remember the baits and weather patterns that led to success. Record all your favorite fishing moments, and share your catches with the community to celebrate with your fellow anglers.<br><br>KEEP YOUR SPOTS SECRET<br>You control how much location info you share! Fishbrain\u2019s built-in privacy settings ensure you can keep info about your favorite fishing spots private.<br><br>CONNECT WITH LIKE-MINDED ANGLERS<br>Fishing is better with friends, old and new. Fishbrain brings together passionate anglers from around the globe. Connect with other fishing enthusiasts, exchange tips &amp; tricks, join fishing groups, learn new fishing techniques and so much more.<br><br>FISHBRAIN APP FEATURES <br> \u2022 Fishing maps with advanced map layers &amp; filters<br> \u2022 Find potential fishing access with the &quot;Parks &amp; Government Land&quot; map layer<br> \u2022 Detailed info on fishing waters, including recent photos &amp; catch reports<br> \u2022 Depth charts from Garmin Navionics (USA &amp; Canada) and C-Map Social<br> \u2022 \u201cTop Baits\u201d recommendations based on community reports<br> \u2022 BiteTime fishing forecasts powered by advanced AI<br> \u2022 Weather conditions, tide charts, air pressure, moon phases and more<br> \u2022 Fishing logbook with personal stats &amp; fishing insights<br> \u2022 Private waypoints to keep track of your favorite fishing spots<br> \u2022 Markers for boat ramps, tackle shops, and other points of interest<br> \u2022 Social community with over 15 million members<br> \u2022 Local fishing rules and regulations in 30+ US states<br><br>GET MORE WITH FISHBRAIN PRO<br>The Fishbrain app is free to download and use. Upgrade to Fishbrain Pro to unlock all the most advanced features. Fishbrain Pro makes finding your next fishing spot even easier, and gives you all the data you need to make great decisions about where to go fishing.<br><br>Whether you\u2019re a beginner just learning how to fish, or an experienced angler chasing your next PB, Fishbrain will help you along your journey as an angler! Download Fishbrain today and start knowing the water like never before.<br><br>Privacy policy: https://fishbrain.com/privacy<br>Terms and conditions: https://fishbrain.com/terms-of-service<br>Like us on Facebook: https://www.facebook.com/fishbrainapp<br>Follow us on Instagram: https://www.instagram.com/fishbrainapp",
    "summary": "Find new fishing spots, get weather forecasts and bait recommendations",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 9336403,
    "score": 4.00888,
    "ratings": 59443,
    "reviews": 15245,
    "histogram": [
        9295,
        2154,
        3767,
        7726,
        36495
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $199.99 per item",
    "developer": "Fishbrain",
    "developerId": "Fishbrain",
    "developerEmail": "support@fishbrain.com",
    "developerWebsite": "http://www.fishbrain.com",
    "developerAddress": "Fishbrain AB\nMagnus Ladul\u00e5sgatan 65\n118 27 Stockholm",
    "privacyPolicy": "http://www.fishbrain.com/privacy",
    "genre": "Sports",
    "genreId": "SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/sGMarGQKpsAJVCslzpa3rqM_0QjLQ5eWCfMLD0YFePp1rBIrhXnBW4y2UEA8dwZ57tk",
    "headerImage": "https://play-lh.googleusercontent.com/KRZaybErnKyr9ZFLmcy6NAMffVsdWDcpWi5Y6Mwc44xx7u5WctX9vy48ZaKCmwNHKQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/3IfKYkeUed_I9TBhgVpkjh17tcm1Enxzay6bsraETCwy7B3l0FmQOgzp1DYrgPXPAWs",
        "https://play-lh.googleusercontent.com/7pnxmCqYy1EwKyC-DMJQf3ydaFgGaL31GXDZBPdpp9Uv1BNqZdftI48CUqEeYqZEkt88",
        "https://play-lh.googleusercontent.com/pKmP_Ver0yDwaJJy07zSk-fokjuB7PQNeC1eV7BjYcoDJLHKyOIfKYxaI7qME_WwrA",
        "https://play-lh.googleusercontent.com/tWgjNeF3h5-tjn7Hc1I5iXbh7--aCkNavaJNx878JS5iWHIq948gexBZBhRIeX_rkZo",
        "https://play-lh.googleusercontent.com/zdKtdHfa56hZHg0e9m6MoEENmLbQscZ_csok_2bVkYUK7WF27ReixYsIzb3p1Jges66j",
        "https://play-lh.googleusercontent.com/nRdva_WrBCB6nwZfibqaY46fvwPWS6JPzM6ck26bqYZZK39LSpPoUVOCStRp3PojVQ",
        "https://play-lh.googleusercontent.com/0yCzfbQbVEqIS4boqsH7PKixmUHtil4AawWzJYYHYVn8IWbw1YAUaaIwpNo5pqYg09U",
        "https://play-lh.googleusercontent.com/FY_664DMn8FZxavHwyaTKK5xvlPCASzMraEfgm_IyK7Z_dhsJhfHhfA3XFLAXmsu2TQ",
        "https://play-lh.googleusercontent.com/tYcH0HumYxRKA5TW79g9seIn_fwoDiklfj2mcw-Jzv7f2hAYLwaCaDKJeulTo-xxIQ",
        "https://play-lh.googleusercontent.com/BsTLbQqjECQM0IE7k6pKD8S2yZc2-6eWZHTzGO9ITjUC_LTLkbhV9D77A3JHgMbs-nw",
        "https://play-lh.googleusercontent.com/sRkX8LnaUjHVoSDmSSzDVmEbkADkRjSsSxaTUOxnJqdnkLfx-xzdRdspkEsqUJfgBR4",
        "https://play-lh.googleusercontent.com/G8zehIW6ts_hdhbB1aiLVqteouKbJU2c7ewAVKVVK0N4eQSPp0TdwFaMyY-OYzsqMQ8",
        "https://play-lh.googleusercontent.com/eOF1wAvGNlb8KH5gEvs9FlqFqoUi6ehwxVAjVcJEqOT3_xFKN-s2_jx04CzwlFmt2A",
        "https://play-lh.googleusercontent.com/e_CJCseme3SFXzLCL1-1tvMepFjRZf3qAzEUQbEpXMF55oxsy3xbz8wz4A6uth_u0GU",
        "https://play-lh.googleusercontent.com/Y_413Bxt9ctQZgmW18w4Lw4O9hhWsWDdTl4ejzk6qyjBPkM_tYtizpX9PXsHr9mBTQ",
        "https://play-lh.googleusercontent.com/5ZUtOwrtjO6UnHmjl5p4Ubs8BnCNEma-EGMw0df38J69wuFE6IsMbN8AkuUMVxZw",
        "https://play-lh.googleusercontent.com/f4OMYiXZxqH79a5iLY69HqO8gSUFsxfJYQHbxqfPBe7tNvUbUELB-Ht2VCDmWMvvzJk",
        "https://play-lh.googleusercontent.com/KYfPdMau0xf3ODuAJpvj2RUqwBaYp_A4vMW1g9MoLVIF4ZIGYMPDCj0sGrzbQREmbNY",
        "https://play-lh.googleusercontent.com/Q-9raBXkyGndGOc5Rt1FtsmMvJPUISIbHepTT8bQVBrBJSbVG2DF6N6w3rXDBVM5Uw",
        "https://play-lh.googleusercontent.com/1REBnExqI_yN_sBIVfTpYKjmjopObUBA-9mEc_PlfhlLv6tN30Qov1Vaa8ZRZcH5Aw",
        "https://play-lh.googleusercontent.com/bF5IJYDctKpyevxVnLRtc_1tbh_5V5SKBykfeP4apoTvJWk2ekiJX4cadGZBFXU0ttQ",
        "https://play-lh.googleusercontent.com/8-RHA-As2ORWU9KYbpm2e3zASdKvop5KLZPTCxLGXZbqWaf2tEiATB4nJ5r4IdsQCi4",
        "https://play-lh.googleusercontent.com/04SWsE534dG1uBYcK5IQLru7MwoxGq9kPzq_j4rfdMAMyM3NOYdTze54qiDYJPm8xIkd",
        "https://play-lh.googleusercontent.com/faziyGmgfsmOPa9J1pYH1Bcj03jRKY7OkNq2WsUTmhLT51Sa38Hfiz4aDBE3vjOefQ"
    ],
    "video": "https://www.youtube.com/embed/ReaeqrA_l5c?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/KRZaybErnKyr9ZFLmcy6NAMffVsdWDcpWi5Y6Mwc44xx7u5WctX9vy48ZaKCmwNHKQ",
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 25, 2013",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731932696,
    "version": "11.16.0.(23301)",
    "comments": [],
    "appId": "com.fishbrain.app",
    "url": "https://play.google.com/store/apps/details?id=com.fishbrain.app&hl=en&gl=us"
}