{
    "title": "Winter Lord",
    "description": "Welcome, my lord! In this game, you rule over an ancient, snow-covered kingdom famous for forging legendary weapons. The frozen land harbors many dangerous creatures, but also hides rich treasures that attract adventurers. Equip these brave souls, and they will stand by your side to defend your city.\r\n\r\nDefend Your Territory\r\nDangerous creatures often threaten your city, their chilling roars echoing through the night. But fear not, adventurers are ready to fight by your side.\r\n\r\nEquip Your Heroes\r\nGive these adventurers top gear, and they will protect your city.\r\n\r\nCommand and Conquer\r\nLead your skilled blacksmiths, strategize weapon production, and lead your troops in epic battles.\r\n\r\nRelax and Reap Rewards\r\nEnjoy a relaxing game with idle rewards that keep you progressing, even when you're not playing.\r\n\r\nExpand your territory, find hidden treasures, and become the master of this icy world!",
    "descriptionHTML": "Welcome, my lord! In this game, you rule over an ancient, snow-covered kingdom famous for forging legendary weapons. The frozen land harbors many dangerous creatures, but also hides rich treasures that attract adventurers. Equip these brave souls, and they will stand by your side to defend your city.<br><br>Defend Your Territory<br>Dangerous creatures often threaten your city, their chilling roars echoing through the night. But fear not, adventurers are ready to fight by your side.<br><br>Equip Your Heroes<br>Give these adventurers top gear, and they will protect your city.<br><br>Command and Conquer<br>Lead your skilled blacksmiths, strategize weapon production, and lead your troops in epic battles.<br><br>Relax and Reap Rewards<br>Enjoy a relaxing game with idle rewards that keep you progressing, even when you&#39;re not playing.<br><br>Expand your territory, find hidden treasures, and become the master of this icy world!",
    "summary": "Relax, craft, and lead armies",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 267272,
    "score": 4.7524753,
    "ratings": 5757,
    "reviews": 95,
    "histogram": [
        109,
        54,
        54,
        681,
        4844
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "Game Lab Limited",
    "developerId": "Game+Lab+Limited",
    "developerEmail": "cyc.zuo@gmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://www.gamelablimited.com/",
    "genre": "Strategy",
    "genreId": "GAME_STRATEGY",
    "categories": [
        {
            "name": "Strategy",
            "id": "GAME_STRATEGY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/j6LCFDu6emJ__bS_4rL7gB9KQqln6blE86CeblQPIUoNq3qPcjpvC3W2NjnOEl7VgxQ",
    "headerImage": "https://play-lh.googleusercontent.com/L1BnBbz30Sakj8SM_Rt6wFuwOlnKarA1Tp4EJ-1hdZUUz4oLx2KRHMMOulWL9FodwQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/rjhRGKucMGJe8J9Sp8jWTKEXZgRo6yHc0DJ-A75DB0yg8_XFMS9Ke3OaPSAtuCRGhAg",
        "https://play-lh.googleusercontent.com/TxLTnu717VaOhljwZTPDbfYuiUaPR6DwgEyMUe4V_mLJNxTMo47h0fVzm9Nk8gxUmQ",
        "https://play-lh.googleusercontent.com/A5hPJ8qWVrxBRUzyBaKluPOmpsS2LMMjQq8aiKZtsopD3xRzoOCD5GkOmEEy8h5dic8",
        "https://play-lh.googleusercontent.com/5d9zzEc4Mf9W789WT6FxuZvgb5v_0k5YOh1MPXAukfigKfVnpvnnn_6yHb0NmDwmNg",
        "https://play-lh.googleusercontent.com/A-G-TsXNYDV7uoJI6eHxoqP201wbye67wYbeWx45I2s6AsbPiZ7kuSb6YNqt6BZP6og"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Fantasy Violence, Mild Blood, Alcohol Reference",
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 16, 2024",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731991236,
    "version": "1.0.69",
    "comments": [],
    "appId": "com.gamelab.winterlord.gp",
    "url": "https://play.google.com/store/apps/details?id=com.gamelab.winterlord.gp&hl=en&gl=us"
}