{
    "title": "Top Heroes: Kingdom Saga",
    "description": "**Log in now to get your SSR hero, 100 free summons, and an abundance of resources. This once-a-year event is the perfect time to dive in!**\r\n**Join 10 million players and counting!**\r\n**Dive into a vast world full of creative and fun gameplay!**\r\n\r\nOn this distant and mysterious continent, countless unknown miracles and challenges are hidden. Here live magical creatures of various forms, each with their unique culture and profound secrets. Their legends and stories, filled with magic and myth, ignite the curiosity of every adventurer.\r\n\r\nHowever, a powerful and terrifying dark force is spreading and threatening the peace and tranquility of this continent. Facing this dark tide, brave warriors from different races and cultures have stepped forward. They vow to unite and resist this evil force together.\r\n\r\nIn this passionate and adventurous game, you will play as a brave leader, leading these warriors through mysterious forests, ancient ruins, and dark caves to explore every corner of this continent. On the journey, you will encounter various wonderful creatures, uncover forgotten ancient secrets, discover hidden treasures, and fight against various powerful enemies.\r\n\r\nYour wisdom, courage, and strategy will be the key to defeating the dark forces and protecting the peace of the continent. Rally your team, select appropriate equipment and spells, and fight for the future of this continent! In this grand adventure, every choice and battle is of great significance. Now, it's time to embark on this journey to save the world!",
    "descriptionHTML": "**Log in now to get your SSR hero, 100 free summons, and an abundance of resources. This once-a-year event is the perfect time to dive in!**<br>**Join 10 million players and counting!**<br>**Dive into a vast world full of creative and fun gameplay!**<br><br>On this distant and mysterious continent, countless unknown miracles and challenges are hidden. Here live magical creatures of various forms, each with their unique culture and profound secrets. Their legends and stories, filled with magic and myth, ignite the curiosity of every adventurer.<br><br>However, a powerful and terrifying dark force is spreading and threatening the peace and tranquility of this continent. Facing this dark tide, brave warriors from different races and cultures have stepped forward. They vow to unite and resist this evil force together.<br><br>In this passionate and adventurous game, you will play as a brave leader, leading these warriors through mysterious forests, ancient ruins, and dark caves to explore every corner of this continent. On the journey, you will encounter various wonderful creatures, uncover forgotten ancient secrets, discover hidden treasures, and fight against various powerful enemies.<br><br>Your wisdom, courage, and strategy will be the key to defeating the dark forces and protecting the peace of the continent. Rally your team, select appropriate equipment and spells, and fight for the future of this continent! In this grand adventure, every choice and battle is of great significance. Now, it&#39;s time to embark on this journey to save the world!",
    "summary": "Download Now for SSR hero and Exclusive Once-a-Year Gifts",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4420947,
    "score": 4.1538463,
    "ratings": 26789,
    "reviews": 587,
    "histogram": [
        3881,
        799,
        683,
        3313,
        18087
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "RiverGame",
    "developerId": "RiverGame",
    "developerEmail": "support_th@rivergame.net",
    "developerWebsite": "https://www.greenmushrooms.net/",
    "developerAddress": null,
    "privacyPolicy": "https://www.greenmushrooms.net/privacy_n.html",
    "genre": "Adventure",
    "genreId": "GAME_ADVENTURE",
    "categories": [
        {
            "name": "Casual",
            "id": "GAME_CASUAL"
        },
        {
            "name": "Single player",
            "id": null
        },
        {
            "name": "Stylized",
            "id": null
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/EvGNuZnmGWDNkpK2uImB7QsI1UOZvUbMx9I5DFeIONeIwoJM4gtbXaNlCBeT0VdMA4I",
    "headerImage": "https://play-lh.googleusercontent.com/uP0W8wjrDIBDA_LPeTSAKZvWhwy1FzeiMRF6CySSI5-A1ReedpymoB73ePcsRpA8tgo",
    "screenshots": [
        "https://play-lh.googleusercontent.com/IOfk62823R1aP70x4LVSU4rljJxWY-hm4mrENzw1xnf-drI5sPoILUF5FJWK1PlnSCg",
        "https://play-lh.googleusercontent.com/C6xmATXSiU8jnVJ0tAbvZrZhPp_E9qkBe1rzXqEk7W-Cq58dsL9RdJnF-laAJsbBml5K",
        "https://play-lh.googleusercontent.com/5xYRHUMWsBCiSpzOCNQOCtSftUQ-5O9uPjtUCatnuy46XEg0TmaBxrL9fAqyT0R74g",
        "https://play-lh.googleusercontent.com/AYLpQbTn9IQhgIsC8PycPDZ_xHuAzFQND0YOyHeTQ6Y_0-wXFOrzCXK50f-IopPN1dc",
        "https://play-lh.googleusercontent.com/IbN3gQqka2GuswtDV-MUUznA5W9WhBpA0IYStcY620T53Rz2Zdj_q4gF9nBwBWKhIlE",
        "https://play-lh.googleusercontent.com/d2AMWS6Vnw0BoGbAjZqGNLKDZVXzUtestjuLDuBRm2xJliaPVUs32YYvLWbGmEPjnVM",
        "https://play-lh.googleusercontent.com/TAHMugAQJFx1oMeWoHLXx5iZbt1BLVQtzA9OhidX2SjvUJF_LwmfSYPrgr-BjGr__0c",
        "https://play-lh.googleusercontent.com/dROcXSjuCBVIHsMiHiEQE8ctazk9zHvfw5s6AvPMi6MBB1Y-G5Ijo_F2gtZiAjd3PNQ",
        "https://play-lh.googleusercontent.com/6rd2Lg9azoHzPkMGOCKC19j2F2C2w1VJNLiZWbR6ThJriqJ0G7NvgH2XRBTvlZi5Njde",
        "https://play-lh.googleusercontent.com/7mFrNrggbgauuYNb5M9fTfPoxjdOYBPQKbzTlvMRe4MGa9ig2SJPINJBdhc7m0XSpms",
        "https://play-lh.googleusercontent.com/zPNq4trteStC1fwpvCiDxV5TdhzCpygpQ-NbsmDmpH41uQ_fjuFDVCK6fq-C3wwVf8c",
        "https://play-lh.googleusercontent.com/qoArz1szoZ9MeRLTg9vMm_C6yvjWNxDGQzclH-P47V0CbQC0Wf9V2DPEa9u6rXEopA",
        "https://play-lh.googleusercontent.com/zpKRAxVERzTKn26g_KFZDd4Q-d9kPPUKO7vvLRMhqCxqE_S3xLpqfWBZpgQIRGiMuw",
        "https://play-lh.googleusercontent.com/Vog1wH8BEzemfqWdFQROdsbUMtbd2-lPa2DWorpnoMhphKz5zYoJK37bR_nms_CmOA",
        "https://play-lh.googleusercontent.com/ykItthps4chSG7Zm53mqeI2L8Fr6ycJ4rnjbIYO0KUMpVgF6JwGNzHaFZLEcGzUUQSg",
        "https://play-lh.googleusercontent.com/lYL6mmX3BfKi0P5BVNwhYi8JPZK4pNrh6biL-mguE6paXAcFUBvtC6rhcCSM_0RYmz9m",
        "https://play-lh.googleusercontent.com/g3fC_j4IqvhJKhLHVzE6p7BZaaRwcGDK6gnI5d60bNywbymHvHTSKY0qN7eizWG16U0t",
        "https://play-lh.googleusercontent.com/NKdBssYPJP7_klx1KxvDQgKt-nbIVtzxbVsuVRFVH6H0gAFw22gVxwGAGhCHSMWEzdo",
        "https://play-lh.googleusercontent.com/GoXzVPrePyl4277_TOO9hOAlYKs6P62-RXWhsygTdf9UG-ndVp-OSuBjgnFgMr0BNwI",
        "https://play-lh.googleusercontent.com/TIoppLmfzbB9Gj6zhBWUP_rl_CkPITuT5D9Oo83OaEPsu9MUYkIb493kx7Xx1nZBBA",
        "https://play-lh.googleusercontent.com/r6Bjpx_-yxR_mnstBdvHoaU9sg8XYmpcGngUo87PSM56Qs3VprkBgZKaMo-l6NPphoo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone 10+",
    "contentRatingDescription": "Fantasy Violence, Mild Language",
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 17, 2024",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731956977,
    "version": "1.33.11",
    "comments": [],
    "appId": "com.greenmushroom.boomblitz.gp",
    "url": "https://play.google.com/store/apps/details?id=com.greenmushroom.boomblitz.gp&hl=en&gl=us"
}