{
    "title": "AI Photo: Hug Video & Enhancer",
    "description": "Everything you need to create images with AI\uff01\r\n\r\nDo you want create a lifelike virtual hug? Do you want to know what your future baby will look like? Do you want to unblur, restore, and enhance any photo\uff1fWant to animate your own photos? Try this app now! AI Photo app can amazing HD art Photos using the most advanced AI photo app with just one tap!\r\n\r\nIn addition, our app offers a variety of features, including face aging, AI filter, swap face, colorize, repair, retake and more. AI Photo app uses advanced AI technology to alter your photos and quickly generate artistic images in seconds. It is the ultimate tool for creating funny and amazing photos.\r\n\r\nKey Features:\r\n\r\n\ud83c\udfad  AI Hug Video\r\nWith our advanced AI technology, you can upload two separate photos to create a realistic virtual hug video.\r\n\r\n\ud83d\udc68\ud83c\udffb\u200d\ud83e\uddb3 Aging Video\r\nHow Will You Look When You're Old? AI Photo app is powered by AI technology for the best experience and accurate face aging. It is so much fun to oldify yourself with easy-to-use amazing old face filters, perfectly predicts the future for you.\r\n\r\n\ud83d\udc76 AI Future Baby Generator\r\nFuture Baby feature uses advanced AI technology to predict your future baby's face! Simply upload a photo of you and your partner, select the gender of your baby, and let the app work its magic. This feature is meant to be fun with your significant other, whether it's your girlfriend, boyfriend, wife, or husband. Don't take it seriously.\r\n\r\n\ud83c\udf08 AI Filter\r\nAI Photo can turn your photos into stunning works of art with thousands of possible styles. Want to transform into your favorite superhero? Want your cat dressed up as an astronaut and fly to Mars? It's just one click away, create your AI filter photos instantly!\r\n\r\n\ud83d\udca1 Animate Photos\r\nBreathe life into your still images with our Animate Photo feature. Transform your precious moments into living memories with just a few taps.  \r\n\r\n\ud83d\udcf8  AI Retake Shot\r\nAI retake uses cutting-edge AI technology to help you easily fix those imperfect moments. Fix your bad photos and open your closed eyes, generating multiple perfect photos with high quality.\r\n\r\n\ud83e\uddd1\u200d\ud83d\udcbc AI Photo Generator\r\nAI Photo app quickly create images with cutting-edge artificial intelligence. Just upload your own photos to generate pictures in various artistic styles such as LinkedIn profile, business, old money, wedding, etc., your private photo gallery.\r\n\r\n\ud83d\udc69\ud83c\udffc\u200d\ud83e\uddb0 AI Face Swap\r\nAI Photo app will amaze you with the AI face changer. With advanced AI face-swapping technology, the face on your photo can be replaced on another photo and has realistic facial expressions and movements that really look like you. Paste your face onto your favorite beauties, witches and more, it must be fun to trick your friends with ultra-realistic AI face swap pictures!\r\n\r\n\ud83e\uddb9\ud83c\udffd\u200d\u2640\ufe0f AI Avatar Maker\r\nUse the artificial intelligence magic in the AI Photo app to automatically generate artistic portraits, feel the fun of magical portraits, and get them with just one touch. Turn your ordinary selfies or photos into stylish, cool, art-like paintings. AI Photo will be your best choice to generate an unique personal portrait. Experience the future of imagery as AI Photo and AI Art converge.\r\n\r\nAdvanced AI Photo app combines photos with AI Art. App transforms ordinary photos into mesmerizing works of art Experience the perfect combination of AI technology and AI Art with our AI Photo that allows you to effortlessly create captivating visuals that transcend traditional boundaries. Unleash your full creative potential with an unrivaled blend of AI photos and AI art in app. Experience the magic of AI Photo and the artistry of AI Art in tandem.\r\n\r\nIf got any questions, please email us to summerdaysc@outlook.com and we'll help you figure it out.\r\n\r\nRead more about our terms and conditions here:\r\nPrivacy Policy:https://coolsummerdev.com/artgenerator-privacy-policy\r\nTerm of Use:https://coolsummerdev.com/artgenerator-terms-of-use\r\nCommunity Guidelines: https://coolsummerdev.com/community-guidelines",
    "descriptionHTML": "Everything you need to create images with AI\uff01<br><br>Do you want create a lifelike virtual hug? Do you want to know what your future baby will look like? Do you want to unblur, restore, and enhance any photo\uff1fWant to animate your own photos? Try this app now! AI Photo app can amazing HD art Photos using the most advanced AI photo app with just one tap!<br><br>In addition, our app offers a variety of features, including face aging, AI filter, swap face, colorize, repair, retake and more. AI Photo app uses advanced AI technology to alter your photos and quickly generate artistic images in seconds. It is the ultimate tool for creating funny and amazing photos.<br><br>Key Features:<br><br>\ud83c\udfad  AI Hug Video<br>With our advanced AI technology, you can upload two separate photos to create a realistic virtual hug video.<br><br>\ud83d\udc68\ud83c\udffb\u200d\ud83e\uddb3 Aging Video<br>How Will You Look When You&#39;re Old? AI Photo app is powered by AI technology for the best experience and accurate face aging. It is so much fun to oldify yourself with easy-to-use amazing old face filters, perfectly predicts the future for you.<br><br>\ud83d\udc76 AI Future Baby Generator<br>Future Baby feature uses advanced AI technology to predict your future baby&#39;s face! Simply upload a photo of you and your partner, select the gender of your baby, and let the app work its magic. This feature is meant to be fun with your significant other, whether it&#39;s your girlfriend, boyfriend, wife, or husband. Don&#39;t take it seriously.<br><br>\ud83c\udf08 AI Filter<br>AI Photo can turn your photos into stunning works of art with thousands of possible styles. Want to transform into your favorite superhero? Want your cat dressed up as an astronaut and fly to Mars? It&#39;s just one click away, create your AI filter photos instantly!<br><br>\ud83d\udca1 Animate Photos<br>Breathe life into your still images with our Animate Photo feature. Transform your precious moments into living memories with just a few taps.  <br><br>\ud83d\udcf8  AI Retake Shot<br>AI retake uses cutting-edge AI technology to help you easily fix those imperfect moments. Fix your bad photos and open your closed eyes, generating multiple perfect photos with high quality.<br><br>\ud83e\uddd1\u200d\ud83d\udcbc AI Photo Generator<br>AI Photo app quickly create images with cutting-edge artificial intelligence. Just upload your own photos to generate pictures in various artistic styles such as LinkedIn profile, business, old money, wedding, etc., your private photo gallery.<br><br>\ud83d\udc69\ud83c\udffc\u200d\ud83e\uddb0 AI Face Swap<br>AI Photo app will amaze you with the AI face changer. With advanced AI face-swapping technology, the face on your photo can be replaced on another photo and has realistic facial expressions and movements that really look like you. Paste your face onto your favorite beauties, witches and more, it must be fun to trick your friends with ultra-realistic AI face swap pictures!<br><br>\ud83e\uddb9\ud83c\udffd\u200d\u2640\ufe0f AI Avatar Maker<br>Use the artificial intelligence magic in the AI Photo app to automatically generate artistic portraits, feel the fun of magical portraits, and get them with just one touch. Turn your ordinary selfies or photos into stylish, cool, art-like paintings. AI Photo will be your best choice to generate an unique personal portrait. Experience the future of imagery as AI Photo and AI Art converge.<br><br>Advanced AI Photo app combines photos with AI Art. App transforms ordinary photos into mesmerizing works of art Experience the perfect combination of AI technology and AI Art with our AI Photo that allows you to effortlessly create captivating visuals that transcend traditional boundaries. Unleash your full creative potential with an unrivaled blend of AI photos and AI art in app. Experience the magic of AI Photo and the artistry of AI Art in tandem.<br><br>If got any questions, please email us to summerdaysc@outlook.com and we&#39;ll help you figure it out.<br><br>Read more about our terms and conditions here:<br>Privacy Policy:https://coolsummerdev.com/artgenerator-privacy-policy<br>Term of Use:https://coolsummerdev.com/artgenerator-terms-of-use<br>Community Guidelines: https://coolsummerdev.com/community-guidelines",
    "summary": "Try AI hug Video & face aging & baby generator. Edit and enhance art photos.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 7404269,
    "score": 4.319328,
    "ratings": 42585,
    "reviews": 727,
    "histogram": [
        4827,
        702,
        1423,
        4647,
        30947
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $39.99 per item",
    "developer": "Smart AI DEV",
    "developerId": "7455516559837104567",
    "developerEmail": "summerdaysc@outlook.com",
    "developerWebsite": "https://coolsummerdev.com/",
    "developerAddress": null,
    "privacyPolicy": "https://coolsummerdev.com/avatar-privacy-policy",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Wd7tLPaVKiVSFMmLogD7mOm-BBtdV77e0Jxq7pBRMFhJpNeItfvXjybQaBG3H8aNf7Q",
    "headerImage": "https://play-lh.googleusercontent.com/ubErntfLAxsouZeV8ED1VT0drJIQJbErENMB8e8b0ayrJlQKmIATCP8EaisAb0hF3B8H",
    "screenshots": [
        "https://play-lh.googleusercontent.com/5OPJR4Mgon8HXV7A7KsiqPCbyCzn8hQ-RFpiEsc5KHyLtDQnGjrIoQr3MtcQf0JdIjk",
        "https://play-lh.googleusercontent.com/vrktgAIfzT_pJETSP5-cLjf8lE_SxuiyEPr5sVuCOn1B8zaOBkcv6qt761DB0iNiYBE",
        "https://play-lh.googleusercontent.com/jN1_8L7eAQR3n9GTjM_65g5RVaCjh6ou2kWwj7K5T-HRDUqqWkWW-W0hrV1yT_ZkXeNz",
        "https://play-lh.googleusercontent.com/GNJE8QbSZb-ezrDmn4BH0ueDFyW_xLEeuI2ASXHbiZAPJdXlnNH5cUhEQ_x_AxW4Iys",
        "https://play-lh.googleusercontent.com/wwFiWE_Q0MFNGoupMHn9Nye4XZ3uyhcprzlFs0t58lpDUJ4TA2WunWo380Octt0rlH7k",
        "https://play-lh.googleusercontent.com/wekTCGntcjYDoIk_4cjhEOGMjkSJEPVs7fREuxUNQ5i3qi8Qr0Ifzw4h-WolFaLbyFc",
        "https://play-lh.googleusercontent.com/gTx7c1laX-eYF9Ow3Yc2yigGGb6ab4IrMmuHdTu4PkkrPeN14JzK40DvwF5MghSQ7A",
        "https://play-lh.googleusercontent.com/Sm04GrienXi_QZ6PHMFdt4BiEsDGw3a6dzU5Hw3EMlsSjziwn8Dof48_wBrGvl8GNog",
        "https://play-lh.googleusercontent.com/H34GHmzokA1qu-xOHcTWisehPHPbnQdKQnpR8U-QFkrklc6kl1WiDJytBM4Ueo1DbFg",
        "https://play-lh.googleusercontent.com/Do6h73AmwSnYMiQ8QSlpPpez2uiSv50pELVFqAQ_8NwA1Wk3WWDom20DoNqJslvl5g",
        "https://play-lh.googleusercontent.com/pE6ZL2f7dG9DKf8JsjApYmj-ZNTlOmZhiGuivuPe5bkplC2roBmHrCK624UgyvYXhLs",
        "https://play-lh.googleusercontent.com/tzQbJS00hf0AMY5jz81VSQndp0UrlqTuqJDYIceAKjHLxOX6kuGbgn5W7VuvdtMe4_wn",
        "https://play-lh.googleusercontent.com/Wip5Ewgl5HuIAAn6d1Xh7KclM0SkDUMi-x6rftQcj7zDFvchjnm1A0pBJeRHTaWQDS9N",
        "https://play-lh.googleusercontent.com/y9HidD8tw6f_v9ApmD1MTVNLvnXxFtAhvJnA2PjgkCOV9Ca6MJ-FRxLXRwEHZQj7Dpk",
        "https://play-lh.googleusercontent.com/6CSfBMxLk2LzlNHkjfZ68g1wtLWu9vpfbt5uQ3h8HkYGMlmaUDUSwLMn6MIiCAYMY7k",
        "https://play-lh.googleusercontent.com/55QbYJH08tzeu3AOBU0YEPUBEXN_sM3n9fhum3WDTczxyg99yKW5E88QpIWQdP8alOQ",
        "https://play-lh.googleusercontent.com/Ei1uvwb4Kpbz7DDRWkqlhgbW8yawyK1rxebLsL7ge2AjuER6dxGQAkMschnAHGzyi04",
        "https://play-lh.googleusercontent.com/8a9JIFEJEQmos-tRZqdhE6RxVsB2HVpZP2MNKO8QBeUmJH7O7SH3CjRZu7hS5Ew0Qg",
        "https://play-lh.googleusercontent.com/fcfrkKbfqvWinSnAk-sgUkLQJUd-2c_xgTmYak_ueug3bFNb_Nn0vFmcoD-4J8SQEg",
        "https://play-lh.googleusercontent.com/Avc9cBK4mez4izplj0R9jnR1rBUEqZ5n1O3lpjOlTq7v-8HyFb8JHE-kHULz3OTALQ",
        "https://play-lh.googleusercontent.com/DblZkTpBjpxF6CCrquBHtFw7BjnYu2DuxIm4Leha3mPAaETIzxjX1LhP2sqz_fwBNaO2",
        "https://play-lh.googleusercontent.com/PnsHLlPucuhl8BUmu4QdQAW6DDaehGnn_cyCqllGUbcfEtoUpvgPEvtdf52KYMmcYD8",
        "https://play-lh.googleusercontent.com/b-kLPbIzqj0x3FUfu3F7fFomsk1gQw7zrVHSbtKfpaQYPKzo4-8GHMGG-EmSzog-vqfU",
        "https://play-lh.googleusercontent.com/q-TkPNULkI0NjK3q0cVgc1IAE5Ms-0O-P_7_2riuSbADM-Wo63JyEFTaG_VM2NrL7uVZ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 17, 2023",
    "lastUpdatedOn": "Nov 12, 2024",
    "updated": 1731402746,
    "version": "1.3.4",
    "comments": [],
    "appId": "com.ai.avatar.face.portrait.app",
    "url": "https://play.google.com/store/apps/details?id=com.ai.avatar.face.portrait.app&hl=en&gl=us"
}