{
    "title": "PUMA | Clothes & Shoes App",
    "description": "PUMA is known for iconic footwear, clothing, and beyond \u2013 all designed to make you Forever Faster. Take your shopping experience to the next level with the PUMA APP and shop faster.\r\n\r\nFind the streetwear, workout clothes, and other gear you need faster with the PUMA APP. Whether you\u2019re looking for PUMA\u2019s iconic Sportstyle footwear or sneakers, collaborations with the biggest names in fashion, or training gear built to make you Forever Faster, you\u2019ll find it on the PUMA APP. Buy sneakers and streetwear, explore new clothing collections, discover exclusive sales on your favorite products, and shop faster with one click checkout.\r\n\r\nTake your fitness and fashion to the next level with the PUMA APP. Receive elite access to the newest clothing and sneakers with timed drops and online-only exclusives in our digital store. Use the wish list feature so you\u2019ll get notified when items you love are back in stock.\r\n\r\nDownload the PUMA APP for a seamless shopping experience and reach your athletic goals with PUMA\u2019s fashion-forward gear.\r\n\r\nBUY SHOES & CLOTHING\r\n- Explore PUMA\u2019s latest drops, online exclusives, and more in our digital apparel and shoe store\r\n- Discover streetwear and workout clothes that fit your style\r\n- Shop fashion-forward collaborations with the biggest names in sports and culture\r\n- Browse streetwear inspired looks from our digital clothing shop that elevate your style\r\n- Find the latest app-only deals, flash sales, and more\r\n\r\nEASY-TO-USE SHOPPING TOOLS:\r\n- Create a wish list to save your favorite PUMA gear to buy later\r\n- Get notified when items on your wish list are back in stock\r\n- Stay up-to-date on exclusive drops and receive customized notifications on your favorite sneakers or streetwear\r\n- Receive alerts for flash sales, online/app-only deals, and early access to PUMA exclusives\r\n\r\nCUSTOMIZED FASHION FEED\r\n- See customized apparel and shoe recommendations based on your shopping history, wish list, saved items, and more\r\n- Browse the latest PUMA sneakers and streetwear by scrolling a single, customized feed\r\n- Get the inside track on our latest drops, collaborations, and new products\r\n\r\nDownload the PUMA APP today, it\u2019s like having a PUMA store in your pocket.",
    "descriptionHTML": "PUMA is known for iconic footwear, clothing, and beyond \u2013 all designed to make you Forever Faster. Take your shopping experience to the next level with the PUMA APP and shop faster.<br><br>Find the streetwear, workout clothes, and other gear you need faster with the PUMA APP. Whether you\u2019re looking for PUMA\u2019s iconic Sportstyle footwear or sneakers, collaborations with the biggest names in fashion, or training gear built to make you Forever Faster, you\u2019ll find it on the PUMA APP. Buy sneakers and streetwear, explore new clothing collections, discover exclusive sales on your favorite products, and shop faster with one click checkout.<br><br>Take your fitness and fashion to the next level with the PUMA APP. Receive elite access to the newest clothing and sneakers with timed drops and online-only exclusives in our digital store. Use the wish list feature so you\u2019ll get notified when items you love are back in stock.<br><br>Download the PUMA APP for a seamless shopping experience and reach your athletic goals with PUMA\u2019s fashion-forward gear.<br><br>BUY SHOES &amp; CLOTHING<br>- Explore PUMA\u2019s latest drops, online exclusives, and more in our digital apparel and shoe store<br>- Discover streetwear and workout clothes that fit your style<br>- Shop fashion-forward collaborations with the biggest names in sports and culture<br>- Browse streetwear inspired looks from our digital clothing shop that elevate your style<br>- Find the latest app-only deals, flash sales, and more<br><br>EASY-TO-USE SHOPPING TOOLS:<br>- Create a wish list to save your favorite PUMA gear to buy later<br>- Get notified when items on your wish list are back in stock<br>- Stay up-to-date on exclusive drops and receive customized notifications on your favorite sneakers or streetwear<br>- Receive alerts for flash sales, online/app-only deals, and early access to PUMA exclusives<br><br>CUSTOMIZED FASHION FEED<br>- See customized apparel and shoe recommendations based on your shopping history, wish list, saved items, and more<br>- Browse the latest PUMA sneakers and streetwear by scrolling a single, customized feed<br>- Get the inside track on our latest drops, collaborations, and new products<br><br>Download the PUMA APP today, it\u2019s like having a PUMA store in your pocket.",
    "summary": "Shop the latest apparel & sneakers. Deals on workout clothes, streetwear & shoes",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4713637,
    "score": 4.8551145,
    "ratings": 113159,
    "reviews": 2531,
    "histogram": [
        490,
        161,
        1505,
        10916,
        100075
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "PUMA SE",
    "developerId": "7866557077467988202",
    "developerEmail": "shopping-app@puma.com",
    "developerWebsite": "https://puma.com/",
    "developerAddress": "Puma Way 1\n91074 Herzogenaurach\nGermany",
    "privacyPolicy": "https://about.puma.com/en/shopping-app-privacy-policy",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/HbAETPY7O6QoY0Y0Zp2d6wUgtSY4L1dTyUYZB2gqLlWAcsrrdhvHjVBUDrk2Uol8SfQ",
    "headerImage": "https://play-lh.googleusercontent.com/vcamKZvxrucONnvKJQ8aqmgZ4ilsdoqCA0-_YeET8ZNyfsEImNzZOSmgR1rjgKK6itA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Gvc8jqPSMxnxbnjPG72OQyBKVRGo1aNXDfwUAkq3iQA2kvEVWR51-DTL7GaFRVNV7Wg",
        "https://play-lh.googleusercontent.com/Wj8R7yXCIzfIXiAaMNcUODDFeQ7JNmX9_qMs8GbVXVstVw0bDu5193kLtBt-Lp6LTSQ",
        "https://play-lh.googleusercontent.com/RavAZIO-W837EpDnkKuAjJ7NJWhfrYOLyBuYrDBz6OGQfI4CGh7xzkrle9drClf-hTD6",
        "https://play-lh.googleusercontent.com/rTRVVWIvZR9mnH5dL9HLThwlbQVQXy-QMVnzcNvC5KY_UUF9ZE99sdpUaGkiSGvEfNmd",
        "https://play-lh.googleusercontent.com/pfZ9DoVUO2jDwaFlXTGoRquO4qt6f71yZ1ltECIU3m379BNeoOOkJ9TL5rL31O2MQdc",
        "https://play-lh.googleusercontent.com/9IHyQgYVJOhFA0qDMdFE175V1VPhfidhnyMVFexLLPyX0ZKsHOx7z1Puwv_ux6UfRuU",
        "https://play-lh.googleusercontent.com/m-Cv244v-X9_aZw_eGsBCB5YnPToHDm9N5BjF2OsH6nIHMF63mopSVJ45kR6WktZCPM",
        "https://play-lh.googleusercontent.com/RwCSwIUbUc4Q5zQGs2z0Xb6zHDaRk-2Fa-8w5q7mvhm6RfnELHu5nitJomLYQvH3zQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 28, 2022",
    "lastUpdatedOn": "Nov 8, 2024",
    "updated": 1731072423,
    "version": "1.11.2",
    "comments": [],
    "appId": "com.puma.ecom.app",
    "url": "https://play.google.com/store/apps/details?id=com.puma.ecom.app&hl=en&gl=us"
}