{
    "title": "Rise of Kingdoms: Lost Crusade",
    "description": "<b>Conquer with Greece, Rise to Greatness</b>\r\n\u25b6Introducing a New Civilization to Rise of Kingdoms: Greece! \u25c0\r\nGreece has entered the Rise of Kingdoms arena. The bedrock of western civilization and home to legendary philosophers, warriors, and poets, the might of the Hellenistic world is now yours to wield:\r\nTHE GREEKS\u2014Brave, thoughtful, artistic, and innovative, the Ancient Greeks are known for their breathtaking architectural marvels such as the Parthenon, as well as their pioneering role in politics, arts, philosophy, and warfare. How will you leverage the wealth of resources and intellectual prowess at your disposal?\r\nWill you steer Greece like the Golden Age of Pericles, fostering democracy and constructing architectural masterpieces? Or showcase your military strength like Alexander the Great? Will you succumb to the forces of Rome, or extend the brilliant legacy of Hellenic civilization into perpetuity? \r\nIt's time for you to show your true power. \r\n\r\n\u25b6FEATURES\u25c0\r\n14 Unique Civilizations\r\nChoose one of 14 historical civilizations and guide your empire from a lone clan into a great, unstoppable force! Each civilization has its own architecture, unique units, and special advantages \u2014 how you utilize them is up to you!\r\nPut your governing skills to the test with the Greece civilization; fight together with Pyrrhus, Pericles, Alexander the Great, and other great commanders to conquer the Aegean.\r\n\r\nReal-Time Battles\r\nBattles happen in real time on the map. Anyone can join or leave a battle at any time, allowing true RTS gameplay. See an ally being attacked right in your backyard? Send some troops to help your buddy out, or launch a surprise counterattack on the attacker\u2019s city.\r\n \r\nSeamless World Map\r\nAll in-game action takes place on a single, enormous map inhabited by players and NPCs. No isolated bases or separate battle screens. Never before seen on mobile \u201cinfinite zoom\u201d allows you to transition freely between the world view and individual cities or barbarian outposts. Map features include natural obstructions such as rivers and mountain ranges and strategic passes that must be captured to gain entrance to neighboring regions.\r\n \r\nExploration & Investigation\r\nYour world is covered in thick fog. Dispatch scouts to explore this mysterious land and uncover the hidden treasure within.\r\nInvestigate lost temples, barbarian fortresses, mysterious caves, and tribal villages, gather intelligence on your enemies, and prepare yourself for the ultimate battle!\r\n \r\nUnrestricted Troop Movements\r\nNew orders can be issued to troops at any time, offering limitless strategic possibilities. Launch an attack on an enemy city, then circle back and meet up with your alliance army to capture a pass.\r\nDispatch troops to collect lumber from a nearby forest and have them pick off a few barbarian clans along the way. Forces can also be split up between multiple commanders so that you can engage in multiple actions simultaneously.\r\n \r\nAlliance System\r\nFull alliance features allow players to help one another: live chat with built-in translation, officer roles, map indicators to coordinate strategies, and more! Alliances can expand their territory to gain resources, capture mountain passes and barbarian outposts to strengthen their position, and work together to unlock group achievements.\r\n \r\nConquer the Kingdom\r\nFight alongside your alliance to take control of this vast kingdom. Clash with other players and use superior tactics to emerge victorious in a MMO strategy battle royale. Rise to the top and you and your civilization will be written down in your kingdom\u2019s history!\r\n \r\nRPG Commanders\r\nCall upon dozens of historical figures who will serve as your trustworthy commanders, from Julius Caesar and Sun Tzu to Joan of Arc and Kusunoki Masashige. Level up your commanders by defeating barbarians and sending them into battles, then upgrade their abilities using an RPG style talent tree and skill system.\r\n\r\nFacebook: https://www.facebook.com/riseofkingdomsgame/",
    "descriptionHTML": "<b>Conquer with Greece, Rise to Greatness</b><br>\u25b6Introducing a New Civilization to Rise of Kingdoms: Greece! \u25c0<br>Greece has entered the Rise of Kingdoms arena. The bedrock of western civilization and home to legendary philosophers, warriors, and poets, the might of the Hellenistic world is now yours to wield:<br>THE GREEKS\u2014Brave, thoughtful, artistic, and innovative, the Ancient Greeks are known for their breathtaking architectural marvels such as the Parthenon, as well as their pioneering role in politics, arts, philosophy, and warfare. How will you leverage the wealth of resources and intellectual prowess at your disposal?<br>Will you steer Greece like the Golden Age of Pericles, fostering democracy and constructing architectural masterpieces? Or showcase your military strength like Alexander the Great? Will you succumb to the forces of Rome, or extend the brilliant legacy of Hellenic civilization into perpetuity? <br>It&#39;s time for you to show your true power. <br><br>\u25b6FEATURES\u25c0<br>14 Unique Civilizations<br>Choose one of 14 historical civilizations and guide your empire from a lone clan into a great, unstoppable force! Each civilization has its own architecture, unique units, and special advantages \u2014 how you utilize them is up to you!<br>Put your governing skills to the test with the Greece civilization; fight together with Pyrrhus, Pericles, Alexander the Great, and other great commanders to conquer the Aegean.<br><br>Real-Time Battles<br>Battles happen in real time on the map. Anyone can join or leave a battle at any time, allowing true RTS gameplay. See an ally being attacked right in your backyard? Send some troops to help your buddy out, or launch a surprise counterattack on the attacker\u2019s city.<br> <br>Seamless World Map<br>All in-game action takes place on a single, enormous map inhabited by players and NPCs. No isolated bases or separate battle screens. Never before seen on mobile \u201cinfinite zoom\u201d allows you to transition freely between the world view and individual cities or barbarian outposts. Map features include natural obstructions such as rivers and mountain ranges and strategic passes that must be captured to gain entrance to neighboring regions.<br> <br>Exploration &amp; Investigation<br>Your world is covered in thick fog. Dispatch scouts to explore this mysterious land and uncover the hidden treasure within.<br>Investigate lost temples, barbarian fortresses, mysterious caves, and tribal villages, gather intelligence on your enemies, and prepare yourself for the ultimate battle!<br> <br>Unrestricted Troop Movements<br>New orders can be issued to troops at any time, offering limitless strategic possibilities. Launch an attack on an enemy city, then circle back and meet up with your alliance army to capture a pass.<br>Dispatch troops to collect lumber from a nearby forest and have them pick off a few barbarian clans along the way. Forces can also be split up between multiple commanders so that you can engage in multiple actions simultaneously.<br> <br>Alliance System<br>Full alliance features allow players to help one another: live chat with built-in translation, officer roles, map indicators to coordinate strategies, and more! Alliances can expand their territory to gain resources, capture mountain passes and barbarian outposts to strengthen their position, and work together to unlock group achievements.<br> <br>Conquer the Kingdom<br>Fight alongside your alliance to take control of this vast kingdom. Clash with other players and use superior tactics to emerge victorious in a MMO strategy battle royale. Rise to the top and you and your civilization will be written down in your kingdom\u2019s history!<br> <br>RPG Commanders<br>Call upon dozens of historical figures who will serve as your trustworthy commanders, from Julius Caesar and Sun Tzu to Joan of Arc and Kusunoki Masashige. Level up your commanders by defeating barbarians and sending them into battles, then upgrade their abilities using an RPG style talent tree and skill system.<br><br>Facebook: https://www.facebook.com/riseofkingdomsgame/",
    "summary": "The Best Civilization Strategy Game. Conquer with Greece, Rise to Greatnes.",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 80643986,
    "score": 4.4564676,
    "ratings": 2437339,
    "reviews": 75415,
    "histogram": [
        172773,
        40685,
        87719,
        336109,
        1800008
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $214.99 per item",
    "developer": "LilithGames",
    "developerId": "6526849192653249949",
    "developerEmail": "rok-service@lilith.com",
    "developerWebsite": "https://rok.lilith.com/en",
    "developerAddress": "Unit 417, 4/F,Lippo Centre, Tower Two, No. 89 Queensway, Admiralty,Hong Kong.",
    "privacyPolicy": "https://www.lilith.com/privacy?locale=en-US",
    "genre": "Strategy",
    "genreId": "GAME_STRATEGY",
    "categories": [
        {
            "name": "Strategy",
            "id": "GAME_STRATEGY"
        },
        {
            "name": "4X",
            "id": null
        },
        {
            "name": "Stylized",
            "id": null
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/OmRFgoSS-iZDwzkMpygYEjbBkpY-_fpE2CEiEgj2KG0yoj2DcP01fbGMutWEf8ip2tiv",
    "headerImage": "https://play-lh.googleusercontent.com/AKCqPtOLyfty0nxyW1FDD8egEgj3O_qV-MrwekriMU-w7ix_pC87SJbv-Lesaav4V8Y",
    "screenshots": [
        "https://play-lh.googleusercontent.com/0dQWzntJiDpHsfhXmxeJw7Yay60g6G5liDFL7INDR88LESmoc1tmMHgwzg-phBGxpQ",
        "https://play-lh.googleusercontent.com/ATDWIOVyIVEV5JC21nSyz5eTg-Qvn44RSS4-lMTzzH_AuG-t9MPogP4ng-8YAlm4MGg",
        "https://play-lh.googleusercontent.com/xxPna8Z4KGi3VdC-xppfNwy8yPIfIYwzI8Jqrnvt8AGtsqx6pbEJ1klbK1HHdtmFDw",
        "https://play-lh.googleusercontent.com/_QF4BrnkdN0Bu9dW4gQf1a8T99LHvRYrtznww0YElmXThLof3IJUQ9T1JhKqXjs-bDM",
        "https://play-lh.googleusercontent.com/XvLi7qaWKf05WXr2uMNPxehdLbL7kBnNOOJodlfDcdTzsvkKMQ8SO8560JDmPBvhqTA",
        "https://play-lh.googleusercontent.com/jJF-iV06zZVMTQhAcednEZiOK3t2vY-7SyF3_6xhgmJAp32J8UqwLevmjJyfeOPY4Gn5",
        "https://play-lh.googleusercontent.com/GNEu3fdP-AmfyHtb0UCyBRASPbUVaW_529jk_TI7n74R9WkApZs15V8js-T8yfF7GwCR",
        "https://play-lh.googleusercontent.com/41G4OLZQuApD95qZFwa3DODXb1zQoQf45z6MH6G4kK3Xxyr-FBDKAr7m5Ww7WebcTCc",
        "https://play-lh.googleusercontent.com/mtjcuxtd0PtImSimnML9BAib4fZnK1QH17J8YI5H7dgJ8NL91f2Hr46Hh14M7dEKKw",
        "https://play-lh.googleusercontent.com/EUtnP-FqGHCaCsTAUlsO_aTs_VcmIRHw9sJ-_JC5XxTL6PLHfpsG5ENYJqJuUlpPMgU",
        "https://play-lh.googleusercontent.com/K5PdZUw4qtBFlENqoLFr_sbRoRIlv_4HqZllKfB16oHav_-LJ_tPwnVb5NSIvZyPtcQ",
        "https://play-lh.googleusercontent.com/q-QOGUZE1ZTJOHPFjdSYueDp2-VD_ADVa3iae-sm5HtvAQrwF5JIrdrJ5bkY8KntfG4",
        "https://play-lh.googleusercontent.com/GuPtTGdmcbA15sXCmgGpLVUTWaAAGP1tHtPQSwp2L6Hbi3CNadaJ9TzAjTkexYWihq79",
        "https://play-lh.googleusercontent.com/JxZoKzrwfCn_mSYTx89gRD9JhJW4R1lXmCUxPu9KY0vD3_TVnckJiw_Pq0D3rEaGq6U",
        "https://play-lh.googleusercontent.com/fEZmewO17zWXEpwUh9YDurzk7waL1aK_mtRNtPWS8m3yMi6Eu0RoyKXfIbuts5Ir1Uk",
        "https://play-lh.googleusercontent.com/BXnU5mZyCnSTsIFNR18j6j2sjX9_jJJAa2DjpFTfvADuvbMcSBdMbG_YdcJ61gCybCk",
        "https://play-lh.googleusercontent.com/Hxf3HNKZiczcbub8WB__ItpmOejf9ecWOVLR-2EeblRX1n0Imd7bIBd9GOrvaN7BmQ",
        "https://play-lh.googleusercontent.com/dhTu7EH9PHe9pvMjxW9nqn17yAv5MYJ04vMYoGEWPIwItNcwz2gZ8xkE10wHf2FQ9w",
        "https://play-lh.googleusercontent.com/XGqCFVSltpHReC3oO2UFe_2nGmsVXqoZYbu1Dpnd90HJo4uvKd2_0SbhiOfBU91X1w",
        "https://play-lh.googleusercontent.com/z_rZA8jMApPCIk8hX9XRQXpDRn1UqUYCTqCoIactBHBFEBPnHfH8uT6N41LRjHEpYLpZ",
        "https://play-lh.googleusercontent.com/BwFy5DRsle8vMEXQTf9veZ_nEA07-SJpQwRzm7-_oLxsNHETyoGU9suDRYPDm7AVIBy3",
        "https://play-lh.googleusercontent.com/C54CK_whnwtrg_vebZx7dpniTK8-Cmi24sC306QQGJ1rvPlAOew0vI5ROVj5lX2uCA",
        "https://play-lh.googleusercontent.com/2ggSBxqCWXIHz7rEQT5G7waP87sqvYbdohmvBRyWO_EqbmQjiJ-X8ziH1Xmec9-4sBM",
        "https://play-lh.googleusercontent.com/zzXOhyxmxVY42iyalOuz7yhXO_4DUn6vYc4LGx7d9jWBbZDkiYVoclqYFy4pZuXXFw"
    ],
    "video": "https://www.youtube.com/embed/5CBdVmCuDx4?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/AKCqPtOLyfty0nxyW1FDD8egEgj3O_qV-MrwekriMU-w7ix_pC87SJbv-Lesaav4V8Y",
    "contentRating": "Everyone 10+",
    "contentRatingDescription": "Fantasy Violence",
    "adSupported": false,
    "containsAds": false,
    "released": "May 24, 2018",
    "lastUpdatedOn": "Nov 1, 2024",
    "updated": 1730454549,
    "version": "1.0.88.15",
    "comments": [],
    "appId": "com.lilithgame.roc.gp",
    "url": "https://play.google.com/store/apps/details?id=com.lilithgame.roc.gp&hl=en&gl=us"
}