{
    "title": "Cryptoscapes - Brain Word Game",
    "description": "HOW TO PLAY:\r\n1. Collect Clues: Each letter corresponds to a number, similar to Sudoku. Gather known clues to progress through levels more effectively.\r\n2. Decrypt Words: Utilize context, phrases, idioms, morphology to unveil unknown letters, advance progress, and acquire more clues.\r\n3. Finish Quotes: Each solution is a meaningful famous quote, allowing you to guess answers without completing all words. Combine your rich knowledge to decrypt effectively.\r\n\r\nHighlights:\r\n\ud83e\udde0 Engaging Challenges: Stimulate your mind with an array of innovative and thought-provoking word search puzzles, designed to captivate your attention for extended periods.\r\n\ud83d\udeab No Game Cutting ADS: You can safely focus on the enjoyment of the game.\r\n\ud83c\udf3f Immersive Landscapes: Immerse yourself in breathtaking natural scenery through captivating background visuals, enhancing your gaming immersion.\r\n\ud83c\udd93 Free of Charge: Peace Word Search offers premium entertainment at no cost, ensuring accessibility for all players without any hidden fees.\r\n\ud83e\udd1d Intuitive Interface: Seamlessly navigate through the game with a user-friendly interface designed for effortless interaction and ease of use.\r\n\ud83c\udf1f Distinctive Levels: Delve into a diverse selection of meticulously crafted levels, each presenting a unique and gratifying journey.\r\n\r\nPack your worries away and join us on a quest for brain challenge with Cryptoscapes. Start your journey today and train your brain!",
    "descriptionHTML": "HOW TO PLAY:<br>1. Collect Clues: Each letter corresponds to a number, similar to Sudoku. Gather known clues to progress through levels more effectively.<br>2. Decrypt Words: Utilize context, phrases, idioms, morphology to unveil unknown letters, advance progress, and acquire more clues.<br>3. Finish Quotes: Each solution is a meaningful famous quote, allowing you to guess answers without completing all words. Combine your rich knowledge to decrypt effectively.<br><br>Highlights:<br>\ud83e\udde0 Engaging Challenges: Stimulate your mind with an array of innovative and thought-provoking word search puzzles, designed to captivate your attention for extended periods.<br>\ud83d\udeab No Game Cutting ADS: You can safely focus on the enjoyment of the game.<br>\ud83c\udf3f Immersive Landscapes: Immerse yourself in breathtaking natural scenery through captivating background visuals, enhancing your gaming immersion.<br>\ud83c\udd93 Free of Charge: Peace Word Search offers premium entertainment at no cost, ensuring accessibility for all players without any hidden fees.<br>\ud83e\udd1d Intuitive Interface: Seamlessly navigate through the game with a user-friendly interface designed for effortless interaction and ease of use.<br>\ud83c\udf1f Distinctive Levels: Delve into a diverse selection of meticulously crafted levels, each presenting a unique and gratifying journey.<br><br>Pack your worries away and join us on a quest for brain challenge with Cryptoscapes. Start your journey today and train your brain!",
    "summary": "Decode words with numbers and naturescapes!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 223938,
    "score": 4.740741,
    "ratings": 1649,
    "reviews": 297,
    "histogram": [
        80,
        0,
        20,
        60,
        1485
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Rankhamb Venkatesh",
    "developerId": "Rankhamb+Venkatesh",
    "developerEmail": "support@yyplaygames.com",
    "developerWebsite": "https://block.yyplaygames.com",
    "developerAddress": null,
    "privacyPolicy": "https://block.yyplaygames.com/privacy-policy.html",
    "genre": "Word",
    "genreId": "GAME_WORD",
    "categories": [
        {
            "name": "Word",
            "id": "GAME_WORD"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/wcQvHYB2mRLDmvo-gjodTOZloAVNHfx9yRyUO_qFS2fM9vo0rp3C8GP_qaqnrsp8NA",
    "headerImage": "https://play-lh.googleusercontent.com/o5KndejeM_YkUbViEZ-SveseE0bhEx_Qh5JpJion7cJoxly_eBn5ftxV_UnEFMuaOCQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/c1jvKKlF6S1A3HbnaEKwXq0DJqyzxbY2wrPggeVwZ63olPjMbfI5Fjzwz2lMWd_qWbI",
        "https://play-lh.googleusercontent.com/n3h0tjIRDLJcvRJwxgOPt-M8aI1_0mCnmQXNMu3puPJ99ZEgX_DqMrUwtER9pBaE6i8",
        "https://play-lh.googleusercontent.com/p9ldG3QKQkGsIgYlKZiGVUQbvGbwHwRkSDf7NzRN10ho_ZcCcjVgzySHUEKrHZFowXJR",
        "https://play-lh.googleusercontent.com/-R9YdsMf1bJvCvyS_yUHblJGKdA-jEqure_hXKUHzvJb08feHQmOXcK1YKXxogGPbcI",
        "https://play-lh.googleusercontent.com/iGYe6WTiaMfxcyd2MMX8zBomdqr9ND6MsR8OyovdVxmkGRigNIsdKwhiTKAxT5L-IPQ",
        "https://play-lh.googleusercontent.com/XrbCteZgRI47omOM4I1aFdRsLxoeWPyb2I3Ja4KCsm5G6rcjfMXR1eWQm8lSta_eIzU",
        "https://play-lh.googleusercontent.com/4avcdmT9Yoj9fhr7shwqN5fLssT1fh408B0xg1sniZVTIE-BhSC2KZic2OsIGcgkCQ",
        "https://play-lh.googleusercontent.com/djoRokwM1igJJRQuo6BP7r-XCRdTZYn_89pDgPLz8H5Md6553Rz3jGq0fhAXj8hQxw",
        "https://play-lh.googleusercontent.com/ISJI2K7tl92snDv9BbBmkncjHxStTUKwSm5_rL6VQm6ayUeZBefJTw5bhkNn7esNDeQ3",
        "https://play-lh.googleusercontent.com/_TJ2P2qfzYB4PJPIujChdnBBvTZY_WiyZufqzore1H6Gfpgk002B-_s43SZiO-InXxD_",
        "https://play-lh.googleusercontent.com/N0aKbmLPn4WAPurBIog_NaPgU7sNsFLntWOv5eDzzetE1Y60Q8f373so9VCIsW3scg",
        "https://play-lh.googleusercontent.com/ujFMYI3HIUHOX3K_Krr_RLydLomz3JYb0yb8LSrC4Boc8K8r9MAwA1Y89n333OVQ7UE",
        "https://play-lh.googleusercontent.com/IkNkf_RQ7oHZLvspOLyqkgojor-M87uXAsUgcpb2Ei8WJ3E1RI3UQBgiBHueqldNaj0",
        "https://play-lh.googleusercontent.com/ewn8HRM_fV_qkTcg3U7lWT_q_TtmwrqmzNArMIriDVIeLoTccEew9L2sD3sJKlxSMg32",
        "https://play-lh.googleusercontent.com/3pzs5CS9pxmvWwbZmD4WidEpAVEgiHKH9IKebcynHL1aDAIPHnxItgNuekUcCNqS0o4",
        "https://play-lh.googleusercontent.com/Y5jVvm_Q7_0dvjI2lsUl-KPYQKxFRx-O3S-IkoQyB-BZrP0l7GWUwBTCEKjVk9YxfA",
        "https://play-lh.googleusercontent.com/ux_y1jfWcZSpbNfFmwPyPoT77Y-g6hyd0ryq7zmcFpK6YKYk2PzzK678VHJls-uo90w",
        "https://play-lh.googleusercontent.com/zCBzeMstqNXbFHzfmcZlAR29oiD6Nu5gukaK1QJofu3AtkPd3C3yxycuiJqm5fVaZo8g"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 28, 2024",
    "lastUpdatedOn": "Nov 4, 2024",
    "updated": 1730716334,
    "version": "1.10.1",
    "comments": [],
    "appId": "com.insbraingames.cryptoscapes.gp",
    "url": "https://play.google.com/store/apps/details?id=com.insbraingames.cryptoscapes.gp&hl=en&gl=us"
}