{
    "title": "TruckSmarter Load Board & Fuel",
    "description": "Find truck loads across the U.S. with the #1-rated free load board for truck drivers with diesel discounts and instant freight factoring.\r\n\r\nFrom higher paying truck loads to deeper fuel savings, we help truck drivers, owner-operators, truck carriers, and dispatchers earn more with every load.\r\n\r\nWe\u2019re more than a free load board. We\u2019re an all-in-one toolkit that empowers truck drivers to manage their trucking business, their way.\r\n\r\nHow the free TruckSmarter Load Board helps you find loads:\r\n- Book loads by city, region, or zone!\r\n- Minimize deadhead: Book backhauls, see deadhead predictions, and book multiple routes\r\n- 100% free\u2013no subscriptions or tiers\r\n- Unlimited free load search\r\n- See all your load boards in one place: Combine load board accounts\u2013no more app switching to see loads!\r\n- See more rates: 80% more truck loads with rates than leading load boards\r\n- Filter faster: Search loads by rpm, trailer type, location, broker, and more\r\n- Save truck loads you like\r\n- Save searches for faster booking\r\n- Load alerts: We alert you to loads you\u2019ll like\r\n- 100K+ daily truck loads: Find, bid on, and book new loads every day for free\r\n- Book loads with your favorite freight brokers, hide brokers you don't want to work with\r\n\r\nCut your #1 cost with TruckSmarter Fuel Discounts:\r\n- Save on fuel at truck stops across the U.S. including Maverik, Roady's, GrubMart, Quicklees, Davis, Taylor Quik Pik, & more\r\n- Save up to $1.50/gal  $1000s yearly \r\n- Free to use: No hidden fees or subscriptions to book fuel discounts\r\n- Pay for fuel in the app: Don't collect another fuel card! Book fuel, we provide a code, and you give the code to the cashier at the truck stop \r\n- Find truck stop amenities like showers\r\n- Earn fuel credits: Deepen fuel discounts with ways to rack up fuel credits toward future fills at truck stops\r\n- Get deals & promos: We regularly offer deals, coupons, & promos for instant fuel savings at truck stops in our network\r\n\r\nGet paid fast with TruckSmarter Freight Factoring:\r\n- We pay 50% of trucking invoices in 2 hours\r\n- Freight factoring rates as low as 2.5%\r\n- Get paid instantly: Upload load paperwork and get paid the second it\u2019s approved\r\n- No annual contracts: You\u2019re free to go if we\u2019re not the right solution for your trucking business\r\n- Get paid weekends & holidays: We pay 7 days a week\r\n- Non-recourse protection: You\u2019re paid for a load if a freight broker shutters its doors\r\n- No hidden fees: No minimums, reserves, or cancellation fees\r\n- Cash advances: Get paid up to 50% immediately after picking up a load\r\n- Work with 3.7K+ freight brokers: we run a free credit check so you\u2019re working with trusted brokers\r\n- Request a freight broker: Have a preferred broker? Request them in the app.\r\n- Simple load invoicing: Scan or upload your load ID/paperwork and the minute it\u2019s approved we deposit payment to your TruckSmarter Checking Account\r\n\r\nManage your money your way with TruckSmarter Checking:\r\n- TruckSmarter Checking Account allows you to get paid for loads instantly (no wait for holidays or weekends) plus rack up discounts on other TruckSmarter products\r\n- FDIC-insured: Your money is secure up to $250,000\r\n- Instant, wire, or ACH transfers: Want to move your money elsewhere? You have loads of options.\r\n- Earn 1% cash back: Factor with us and we provide a TruckSmarter Visa Debit Card with unlimited cash back & fee free ATM withdrawals\r\n- Earn interest: Every dollar in your TruckSmarter Checking Account earns 3.23% interest\r\n- Deepen fuel discounts: Get an extra 10\u00a2/gal off on top of the fuel discount when you pay from TruckSmarter Checking\r\n\r\nWhy choose us over other apps for truck drivers?\r\n- Our loadboard is 100% free ( DAT One, Truck Stop, 123Loadboard have subscriptions!)\r\n- Our freight factoring is 2.5% with zero annual contracts (unlike RTS, OTR & others)\r\n- Our fuel discounts are card-free and free to use \r\n\r\nQuestions? We\u2019re here.\r\nContact support@trucksmarter.com or 415-384-5018.\r\n\r\nSoporte en espa\u00f1ol disponible",
    "descriptionHTML": "Find truck loads across the U.S. with the #1-rated free load board for truck drivers with diesel discounts and instant freight factoring.<br><br>From higher paying truck loads to deeper fuel savings, we help truck drivers, owner-operators, truck carriers, and dispatchers earn more with every load.<br><br>We\u2019re more than a free load board. We\u2019re an all-in-one toolkit that empowers truck drivers to manage their trucking business, their way.<br><br>How the free TruckSmarter Load Board helps you find loads:<br>- Book loads by city, region, or zone!<br>- Minimize deadhead: Book backhauls, see deadhead predictions, and book multiple routes<br>- 100% free\u2013no subscriptions or tiers<br>- Unlimited free load search<br>- See all your load boards in one place: Combine load board accounts\u2013no more app switching to see loads!<br>- See more rates: 80% more truck loads with rates than leading load boards<br>- Filter faster: Search loads by rpm, trailer type, location, broker, and more<br>- Save truck loads you like<br>- Save searches for faster booking<br>- Load alerts: We alert you to loads you\u2019ll like<br>- 100K+ daily truck loads: Find, bid on, and book new loads every day for free<br>- Book loads with your favorite freight brokers, hide brokers you don&#39;t want to work with<br><br>Cut your #1 cost with TruckSmarter Fuel Discounts:<br>- Save on fuel at truck stops across the U.S. including Maverik, Roady&#39;s, GrubMart, Quicklees, Davis, Taylor Quik Pik, &amp; more<br>- Save up to $1.50/gal  $1000s yearly <br>- Free to use: No hidden fees or subscriptions to book fuel discounts<br>- Pay for fuel in the app: Don&#39;t collect another fuel card! Book fuel, we provide a code, and you give the code to the cashier at the truck stop <br>- Find truck stop amenities like showers<br>- Earn fuel credits: Deepen fuel discounts with ways to rack up fuel credits toward future fills at truck stops<br>- Get deals &amp; promos: We regularly offer deals, coupons, &amp; promos for instant fuel savings at truck stops in our network<br><br>Get paid fast with TruckSmarter Freight Factoring:<br>- We pay 50% of trucking invoices in 2 hours<br>- Freight factoring rates as low as 2.5%<br>- Get paid instantly: Upload load paperwork and get paid the second it\u2019s approved<br>- No annual contracts: You\u2019re free to go if we\u2019re not the right solution for your trucking business<br>- Get paid weekends &amp; holidays: We pay 7 days a week<br>- Non-recourse protection: You\u2019re paid for a load if a freight broker shutters its doors<br>- No hidden fees: No minimums, reserves, or cancellation fees<br>- Cash advances: Get paid up to 50% immediately after picking up a load<br>- Work with 3.7K+ freight brokers: we run a free credit check so you\u2019re working with trusted brokers<br>- Request a freight broker: Have a preferred broker? Request them in the app.<br>- Simple load invoicing: Scan or upload your load ID/paperwork and the minute it\u2019s approved we deposit payment to your TruckSmarter Checking Account<br><br>Manage your money your way with TruckSmarter Checking:<br>- TruckSmarter Checking Account allows you to get paid for loads instantly (no wait for holidays or weekends) plus rack up discounts on other TruckSmarter products<br>- FDIC-insured: Your money is secure up to $250,000<br>- Instant, wire, or ACH transfers: Want to move your money elsewhere? You have loads of options.<br>- Earn 1% cash back: Factor with us and we provide a TruckSmarter Visa Debit Card with unlimited cash back &amp; fee free ATM withdrawals<br>- Earn interest: Every dollar in your TruckSmarter Checking Account earns 3.23% interest<br>- Deepen fuel discounts: Get an extra 10\u00a2/gal off on top of the fuel discount when you pay from TruckSmarter Checking<br><br>Why choose us over other apps for truck drivers?<br>- Our loadboard is 100% free ( DAT One, Truck Stop, 123Loadboard have subscriptions!)<br>- Our freight factoring is 2.5% with zero annual contracts (unlike RTS, OTR &amp; others)<br>- Our fuel discounts are card-free and free to use <br><br>Questions? We\u2019re here.<br>Contact support@trucksmarter.com or 415-384-5018.<br><br>Soporte en espa\u00f1ol disponible",
    "summary": "Loadboard with 100K daily truck loads and freight for truck drivers and owners",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 155172,
    "score": 4.621212,
    "ratings": 2724,
    "reviews": 209,
    "histogram": [
        103,
        61,
        61,
        309,
        2187
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "TruckSmarter",
    "developerId": "7647380593219597011",
    "developerEmail": "support@trucksmarter.com",
    "developerWebsite": "https://trucksmarter.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.trucksmarter.com/legal/privacy-policy",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ze5FrG8xYfsD1E8_HFIMbeeCDKLuaWQD5FH4bQWw_HhwNDDUih5-zm7od79VYgSxaQI",
    "headerImage": "https://play-lh.googleusercontent.com/DKo0k4c_wT3LxgOMvBM112MUygdcF0V9LNnkMrkUP9cB9CuqXpY91J0FqqO5-1Tv7fo",
    "screenshots": [
        "https://play-lh.googleusercontent.com/upL259jm9j3WETwv8oVYQ-Mto3d9MWk0a93qQlt4-WhcbXO-LlleN90Gpo7eMCLvV4M",
        "https://play-lh.googleusercontent.com/tTHWBhEYkZhfrq2brL879YKxYdQqsAhV7VaafVM_h_AnIrCRe4mktVtFTOBy8ywJdBM",
        "https://play-lh.googleusercontent.com/4VcWA5LNWPZk5mwJUhM4QtF3pJ5IjSY0VOPFY6721_jesdfrB7jsCvB3M3Lj7O6bxyBB",
        "https://play-lh.googleusercontent.com/eb2si_F1sTxxZpfT431oFKqmi07b4mbsgXMDvSTdb1Y6A26fMu4PbtKi1lwzKjeqtcI3",
        "https://play-lh.googleusercontent.com/VoIWbB0kuXmMZ5KyFBnpumjHwjud8bDhyMGhvC0WNe5BeRW7AYymVJXbnNmGGRy6r6Y",
        "https://play-lh.googleusercontent.com/fBMvqitMhxM9X1B6KDTHVB3K-fmH7cZ4u62sZhz3wgei5jhzQ7VYVYQF5W99SlJhWAvm",
        "https://play-lh.googleusercontent.com/SUYJKzcRc5tqNKAcu-LXt19KnaMI-JFXWGpsw2JoMgL8Dan7IjpZz4GqbowrDXHBkb4",
        "https://play-lh.googleusercontent.com/zS1fezMHx6wZdFARsszmVco6Tkk8v5IItT4j-oIs6WueN__zTW0sbJjac9LAtE2SgRk",
        "https://play-lh.googleusercontent.com/jAv5Ns3Fbh3LTjPYkVSGUu3tFjWaUlI9NnBe6tirvBDLlJXUy57IenyVo534tbGzuVdC",
        "https://play-lh.googleusercontent.com/LkXOpEW1_h33KPFLH6WVukleCj3wZZBuaq3yLKjcf1jX2aXLfsWnQGdV0UxEGa07zSM",
        "https://play-lh.googleusercontent.com/kP8zjZAMhKCG4xfbeDk3vhQ1JJD6pu7WepEDMiCPZoPUpTRFgMSwRYCTHZsSzm5p5lJY",
        "https://play-lh.googleusercontent.com/6UpQbGhd-UdtF-IOsrHauVRZh9s0iIYvjzm9YoagvEJAQv6nmiXKfgUm-Msddm4snyMH",
        "https://play-lh.googleusercontent.com/JAbZu-RcTa_JAyS7cHIRJGcGVE1oi94--jyEgwkMtTuF5AAnAfFRWP4v6pfEs1J2fA",
        "https://play-lh.googleusercontent.com/KiBIp4FuL_qXrwu_SESMmZDTzt_lXpuPO-fMTSbarpmwimrI0GsfYF2DQZxGbgflhz8",
        "https://play-lh.googleusercontent.com/Q2P8xMGIAUzmW8yeQwcqAherwhl1F1VylMuXIhw73oY3V8kMdgyuFRnhzeztMDV9XA",
        "https://play-lh.googleusercontent.com/y0JU_fKv2M1arzSSqsRKTGvTXe9RiUKHzQAwjttn63f74uJx5-N74Lwnrim4Wzjv5JcM",
        "https://play-lh.googleusercontent.com/XrpeLcYDI68m09YDmaNeHIxPOOLYqM4g9-gnFbb6Ht402R1jybzXB6WrGu2qLevFFQ",
        "https://play-lh.googleusercontent.com/b6g8ILfGPjnxk4AO6MfcWKKN86yh6QXURTfSdfnysFV_cLpwps_QdjgxocWom_nBYa4",
        "https://play-lh.googleusercontent.com/r17SqECZfS1ZfIecAEWNu4vK19wtSh4F6BNCPxoLOh1-S7JBBLG7bHVdakObX5YPI3k",
        "https://play-lh.googleusercontent.com/Fs5JLa164g4syjwwGgGlA4MfRKroY94nysGUZWsPHCZ1sPatHGjGFEyzaZ03KL8AK6w",
        "https://play-lh.googleusercontent.com/6NNkz9WwXijwjmOSXtIyHHxqpMFBdBGk9a6IlXg-Jr7d8EDCCIvqVWHNoxUn6IHIK9JM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 25, 2021",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731720380,
    "version": "194.0",
    "comments": [],
    "appId": "com.trucksmarter.app",
    "url": "https://play.google.com/store/apps/details?id=com.trucksmarter.app&hl=en&gl=us"
}