{
    "title": "eventNab - Discover Events",
    "description": "Welcome to eventNab \u2013 your trusted, 24x7 event partner!\r\n\r\nAlways searching for events near me or festivals near me?  Not anymore. Get ready to know about all your favorite events or festivals from eventNab.\r\nIt\u2019s your all-in-one event BFF ready to transform your event hunt. Enjoy & chill with your favorite theater, nightclub experience! But eventNab isn\u2019t just about finding events. Having a long weekend holiday? Quickly plan your holiday experience or nightlife venue from start to finish. Planning for your forthcoming anniversary event?  Get ready to NABigate your way to unforgettable events!\r\n\r\nWHY eventNab?\r\nBecause we\u2019re the event app that leverages AI. So, we know what you like! We believe that every upcoming Events should be a party; not a chore. With our all-in-one solution, you can:\r\n\u2022 Save Time: No more juggling btw multiple apps to plan your perfect holiday out. With our planner, you get everything in one place.\r\n\u2022 Stay Informed: Real-time updates curated just for you. Means, you\u2019re always in the know about Festivals, Theaters, Sports, Live Music, Upcoming Events, concert in real-time.\r\n\u2022 Enjoy More: Want to party at a nightclub? Crave for a memorable bachelorette nightlife or bachelor nightlife or want a perfect birthday party planner? With your fingers on eventNab having fun & making memories is easy peasy! Let\u2019s take care of your party planner while you enjoy.\r\n\r\nEXPERIENCES JUST FOR YOU\r\nSay goodbye to endless scrolling. Get your personalized planner & event ideas unified in our app! From electrifying Live Music, Music Festivals, Theaters, concerts, thrilling sports, mouth-watering restaurants near me to nightclub with safe parking & charging, we\u2019ve got you covered.\r\n\r\nLET US NABigate YOUR EXPERIENCE\r\n Our planner makes it easy to plan your entire outing. \r\n\u2022 Quick event tickets: Grab concert tickets, tickets for sports, festivals near me, theater & more. Secure your spot fast for Music Festivals or Live Music.\r\n\u2022 Hungry? Book the best restaurants near me to grab a bite near your event venue with safe parking & charging your EV. From chic dining to quick snacks, book your table with just a few taps. Never go hungry at an event as our ticketmaster ensures everything for you!\r\n\u2022 Hassle-Free Parking: Say goodbye to parking nightmares! Reserve a spot nearby & roll up like a VIP. No more driving in circles!\r\n\u2022 Weather Check: Wondering if you\u2019ll need shades or an umbrella? Discover your event day weather right in the app. Be prepared for any weather, rain or shine.\r\n\u2022 EV Charging Stations: Got an EV? Discover charging stations near your venue. Keep your wheels juiced up & safe with hassle-free parking.\r\n\u2022 Uber: We\u2019ve teamed up with Uber so you can get to & from the event without a hitch. Ride in comfort & style. Reach your venue & back with zero stress.\r\n\r\nCOOL FEATURES TO AMP UP YOUR EXPERIENCE\r\n\u2022 Sleek & Easy Interface: Our app is super user-friendly & simple to use! Discover what you need fast.  \r\n\u2022 Personalized Recommendations: Sign up to better leverage our AI engine to discover events, venues tailored to your tastes. Book tickets via our Ticketmaster.\r\n \u2022 Easy Sign-In: Log in with Google, Apple, or manually\u2014whatever works for you. Simple & Secure.\r\n\r\nCURATED CITIES, CURATED FUN\r\nOur focus is on urban hot spots with many options. But we\u2019re also diligently working to continue adding new areas every week (so keep an eye out). Are you a local trying to constantly discover festivals near me or traveling for business with some leeway to book concert tickets or tickets for music festivals? Or you just visiting the city, looking for some events? Discover events near me matching your choice from anywhere. From hiring a cab to your party venue or nightclub venue to driving you to any restaurants near me we\u2019re there for you. In real-time!\r\n\r\nDownload eventNab Right Away for the ultimate event adventure. You focus on making memories!\r\n\r\nTerms & Policies: https://www.eventnab.com/terms-of-use-services\r\nPrivacy Policy: https://www.eventnab.com/privacy-policy/",
    "descriptionHTML": "Welcome to eventNab \u2013 your trusted, 24x7 event partner!<br><br>Always searching for events near me or festivals near me?  Not anymore. Get ready to know about all your favorite events or festivals from eventNab.<br>It\u2019s your all-in-one event BFF ready to transform your event hunt. Enjoy &amp; chill with your favorite theater, nightclub experience! But eventNab isn\u2019t just about finding events. Having a long weekend holiday? Quickly plan your holiday experience or nightlife venue from start to finish. Planning for your forthcoming anniversary event?  Get ready to NABigate your way to unforgettable events!<br><br>WHY eventNab?<br>Because we\u2019re the event app that leverages AI. So, we know what you like! We believe that every upcoming Events should be a party; not a chore. With our all-in-one solution, you can:<br>\u2022 Save Time: No more juggling btw multiple apps to plan your perfect holiday out. With our planner, you get everything in one place.<br>\u2022 Stay Informed: Real-time updates curated just for you. Means, you\u2019re always in the know about Festivals, Theaters, Sports, Live Music, Upcoming Events, concert in real-time.<br>\u2022 Enjoy More: Want to party at a nightclub? Crave for a memorable bachelorette nightlife or bachelor nightlife or want a perfect birthday party planner? With your fingers on eventNab having fun &amp; making memories is easy peasy! Let\u2019s take care of your party planner while you enjoy.<br><br>EXPERIENCES JUST FOR YOU<br>Say goodbye to endless scrolling. Get your personalized planner &amp; event ideas unified in our app! From electrifying Live Music, Music Festivals, Theaters, concerts, thrilling sports, mouth-watering restaurants near me to nightclub with safe parking &amp; charging, we\u2019ve got you covered.<br><br>LET US NABigate YOUR EXPERIENCE<br> Our planner makes it easy to plan your entire outing. <br>\u2022 Quick event tickets: Grab concert tickets, tickets for sports, festivals near me, theater &amp; more. Secure your spot fast for Music Festivals or Live Music.<br>\u2022 Hungry? Book the best restaurants near me to grab a bite near your event venue with safe parking &amp; charging your EV. From chic dining to quick snacks, book your table with just a few taps. Never go hungry at an event as our ticketmaster ensures everything for you!<br>\u2022 Hassle-Free Parking: Say goodbye to parking nightmares! Reserve a spot nearby &amp; roll up like a VIP. No more driving in circles!<br>\u2022 Weather Check: Wondering if you\u2019ll need shades or an umbrella? Discover your event day weather right in the app. Be prepared for any weather, rain or shine.<br>\u2022 EV Charging Stations: Got an EV? Discover charging stations near your venue. Keep your wheels juiced up &amp; safe with hassle-free parking.<br>\u2022 Uber: We\u2019ve teamed up with Uber so you can get to &amp; from the event without a hitch. Ride in comfort &amp; style. Reach your venue &amp; back with zero stress.<br><br>COOL FEATURES TO AMP UP YOUR EXPERIENCE<br>\u2022 Sleek &amp; Easy Interface: Our app is super user-friendly &amp; simple to use! Discover what you need fast.  <br>\u2022 Personalized Recommendations: Sign up to better leverage our AI engine to discover events, venues tailored to your tastes. Book tickets via our Ticketmaster.<br> \u2022 Easy Sign-In: Log in with Google, Apple, or manually\u2014whatever works for you. Simple &amp; Secure.<br><br>CURATED CITIES, CURATED FUN<br>Our focus is on urban hot spots with many options. But we\u2019re also diligently working to continue adding new areas every week (so keep an eye out). Are you a local trying to constantly discover festivals near me or traveling for business with some leeway to book concert tickets or tickets for music festivals? Or you just visiting the city, looking for some events? Discover events near me matching your choice from anywhere. From hiring a cab to your party venue or nightclub venue to driving you to any restaurants near me we\u2019re there for you. In real-time!<br><br>Download eventNab Right Away for the ultimate event adventure. You focus on making memories!<br><br>Terms &amp; Policies: https://www.eventnab.com/terms-of-use-services<br>Privacy Policy: https://www.eventnab.com/privacy-policy/",
    "summary": "Discover events, restaurants & parking with your ultimate AI event planner!",
    "installs": "1,000+",
    "minInstalls": 1000,
    "realInstalls": 1952,
    "score": 4.75,
    "ratings": 16,
    "reviews": 6,
    "histogram": [
        0,
        1,
        0,
        0,
        14
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "eventNab",
    "developerId": "eventNab",
    "developerEmail": "archie@eventnab.com",
    "developerWebsite": "https://www.eventnab.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.eventnab.com/privacy-policy/",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/QvqpzW4nDxK3ajY9o014P3o-5qSq_HLLL3ecmF-S0suDeH8QbkV-DvwCA9iV0bQnucA",
    "headerImage": "https://play-lh.googleusercontent.com/mk9tA-hajIBio8r9UOrkH9ZQXioxqd30oxjjyO5yaV6H1m7Vx86ijRkAboRfMQDw9_A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/oe8FuBSfcJgyg21Xtp_PFPKW6FBz69kiZtXt0ieJz56AWpGD0HdjGrFfu_fIjeZW6x8",
        "https://play-lh.googleusercontent.com/REfITbqlE4ouBi4BV9yQwHwzY2Lpg9EVk4jcNh-j0dmCe8hNM2Pwb2sfliQXWZifhNg",
        "https://play-lh.googleusercontent.com/bXmfbIpTuYhfdVNR6KP6RK_a06hh4Z3UeV0J9L0vSzV1c12ly3o2OvAmwMANlU6Zdoc",
        "https://play-lh.googleusercontent.com/FuypX2dzld4Wg9HV_ypi_9eeeGwR8CZ2kk9sKH-XSPum-N3fdoAgUTaAUrmiMriFqw",
        "https://play-lh.googleusercontent.com/MluUWOmjmtQiIc2GbSa6IoPdS-e-vZpq3PTBnqiw3vZvyg9ZqpSZnFsD2MXxc_zK0-Nr",
        "https://play-lh.googleusercontent.com/fjZfEZOEZhyZ4rDUqu5LeWWvZqr2RHV4fOtqfxBWkH5GlXu7UySUoSaOp1YBieAwuA",
        "https://play-lh.googleusercontent.com/t7ZFoPqZp8IMGBSTO1Wh6SUD5z4x-VR0rh12v5FZqKJDKyPX2cQvqlANpzjG9LY-HGiz"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 28, 2024",
    "lastUpdatedOn": "Nov 16, 2024",
    "updated": 1731769747,
    "version": "1.5.1",
    "comments": [],
    "appId": "com.eventnab.app",
    "url": "https://play.google.com/store/apps/details?id=com.eventnab.app&hl=en&gl=us"
}