{
    "title": "Mirror App - Makeup Mirror",
    "description": "Mirror Pro is Pocket mirror app providing you an extraordinary and unique experience with HD camera quality which changes your phone environment to Wonderfull HD mirror with extra features. These feature will changes your cell phone to compact mirror, mobile mirror hd and Pocketmirror.\r\n\r\nYou don\u2019t need to carry Makeup mirror with you anymore. Pro Mirror has a feature provides you to check your face appearance, look, face makeup, lipstick and hairstyle in just a second. You can freeze the image to check it with Zoom in and Zoom out feature. All this feature make Pocket mirror app as compact mirror. \r\n\r\nMagic Mirror can save your look for photo editing and can easily provide you service to share it with other apps or can easily share on Social media platforms. Pocket mirror has One touch lightening control feature which helps you to See your self even in darkness. Real time zoom in and zoom out feature will display better view than ordinary mirror. You can even control brightness in mobile mirror which suits you to set you lipstick and hairs. Mirror Pro provides you quick look of yourself.\r\n\r\nFeatures of Pro Mirror\r\n- Simple and Easy User interface\r\n- Control Brightness Makeup mirror\r\n- Freeze Image and Download option\r\n- View Rotation (Landscape and Portrait)\r\n- Take Selfie After completing Makeup\r\n- Mirror View, Flip Image view\r\n- Magnifying View and Magnifying mirror\r\n- Amazing tool for daily life for Makeup and Set hairstyle\r\n- Capture image to save it in gallery\r\n- See yourself even in darkness with Lighted mirror\r\n- Professional makeup tool for daily life\r\n- Mirror your makeup companion \r\n\r\nHow to use Beauty Mirror Pro\r\nAfter installing Pocket mirror Application, user can use mirror feature of this app in a first tap. User can change brightness of the mirror. You can use Lighted mirror feature in the darkness by using bulb button on screen. Camera button can capture image and save it to the gallery where as user can freeze image to examine it properly by zooming in and zooming out to experience better feature of Magnifying mirror view. Freeze image can be share to other social media platforms and can be download to gallery also. Flip button will show you real mirror view.\u2028\u2028\r\n\r\nNote: Mirror App using front camera of your device. It requires camera permissions to access camera. The result of Mirror App is totally depending on your front camera results.",
    "descriptionHTML": "Mirror Pro is Pocket mirror app providing you an extraordinary and unique experience with HD camera quality which changes your phone environment to Wonderfull HD mirror with extra features. These feature will changes your cell phone to compact mirror, mobile mirror hd and Pocketmirror.<br><br>You don\u2019t need to carry Makeup mirror with you anymore. Pro Mirror has a feature provides you to check your face appearance, look, face makeup, lipstick and hairstyle in just a second. You can freeze the image to check it with Zoom in and Zoom out feature. All this feature make Pocket mirror app as compact mirror. <br><br>Magic Mirror can save your look for photo editing and can easily provide you service to share it with other apps or can easily share on Social media platforms. Pocket mirror has One touch lightening control feature which helps you to See your self even in darkness. Real time zoom in and zoom out feature will display better view than ordinary mirror. You can even control brightness in mobile mirror which suits you to set you lipstick and hairs. Mirror Pro provides you quick look of yourself.<br><br>Features of Pro Mirror<br>- Simple and Easy User interface<br>- Control Brightness Makeup mirror<br>- Freeze Image and Download option<br>- View Rotation (Landscape and Portrait)<br>- Take Selfie After completing Makeup<br>- Mirror View, Flip Image view<br>- Magnifying View and Magnifying mirror<br>- Amazing tool for daily life for Makeup and Set hairstyle<br>- Capture image to save it in gallery<br>- See yourself even in darkness with Lighted mirror<br>- Professional makeup tool for daily life<br>- Mirror your makeup companion <br><br>How to use Beauty Mirror Pro<br>After installing Pocket mirror Application, user can use mirror feature of this app in a first tap. User can change brightness of the mirror. You can use Lighted mirror feature in the darkness by using bulb button on screen. Camera button can capture image and save it to the gallery where as user can freeze image to examine it properly by zooming in and zooming out to experience better feature of Magnifying mirror view. Freeze image can be share to other social media platforms and can be download to gallery also. Flip button will show you real mirror view.\u2028\u2028<br><br>Note: Mirror App using front camera of your device. It requires camera permissions to access camera. The result of Mirror App is totally depending on your front camera results.",
    "summary": "Beauty Mirror with capture image, brightness control & Magnifying mirror view.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1395134,
    "score": 4.7,
    "ratings": 8267,
    "reviews": 158,
    "histogram": [
        316,
        79,
        79,
        728,
        7015
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "o16i Apps",
    "developerId": "9197857236982036353",
    "developerEmail": "support.mirrorpro@zipoapps.com",
    "developerWebsite": "https://zipoapps.com/mirrorpro",
    "developerAddress": "Livnim 6\nTzur Yigal, Israel",
    "privacyPolicy": "https://zipoapps.com/mirrorpro/privacy",
    "genre": "Beauty",
    "genreId": "BEAUTY",
    "categories": [
        {
            "name": "Beauty",
            "id": "BEAUTY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/TQRyQ5LR_8X-isuJ_MjgTZsHi7Eg99AYrAUuCZc80zim43Z1k84S1xMxLOZMfWwPgI3G",
    "headerImage": "https://play-lh.googleusercontent.com/Sw_Rrhh0Dk-F1OPVe6tt_jkBOkkcKdjKbhLmRq8uOril0EEiEJQI3j5NtbsFm1lGDoQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Kp4l8np5hlPqhSYYgjrb44esWb23HelG7iFCLQ_tfgEBKFM3zQPlkfmcF8ZhfLHHzg",
        "https://play-lh.googleusercontent.com/pIXQSmwHvt0_pClwWpB_JGsEoWQYqT7FdaFIHQ6mUObareLh5WTsDF3hbV4dW_w3Y7w",
        "https://play-lh.googleusercontent.com/EUQonY3JaA7lRAYXK5ADnkEilnxc47ikmPek5-jenZlOYA4QS9V3DFQbzbQHE0mYww",
        "https://play-lh.googleusercontent.com/f7_RUXkmXwa9Or4XQv2EtDvDcbiHNgNi_DTRnu7_P96BPwa--2X_cYkmkQvjBadTDFU",
        "https://play-lh.googleusercontent.com/gNFbA2MKDq9lIou4HnW8wp_EJd_7Do7Mvs-iOmx4ynmBfBzMW9wzorg1pqqDuCujjHo",
        "https://play-lh.googleusercontent.com/tECVrIC1TN12TY1mqlSYNFdA-tH2mPLq41Mhv3zve5r3NP6QUuhbbbrAR0JhZJmhCtM",
        "https://play-lh.googleusercontent.com/q3RPf0zMKfzTJECRSd-XDa7sJ13Kcgbw9PeQNHSG08c7QeSr4t2bLOeoPzT3tLnbZ9PL",
        "https://play-lh.googleusercontent.com/5sLdWR5rv-xe7tKwwojRpOsd5F_v4S5B-AAqFBk7V-0MS3XS9Bmvg9Q80EoFUGFupdcS",
        "https://play-lh.googleusercontent.com/Kq_GCUMsPHiwIbhQOx17a4bnJ2ozW90YGzO6E9gbyGthtb28uK5fZnMby6xbpkdp1bY",
        "https://play-lh.googleusercontent.com/gFV_yYix4faKxoutJeYJzRzqDv8mS6ATVejhYWxTlO1dKM5itCY0MNnv201nEuWQIA",
        "https://play-lh.googleusercontent.com/7N-lf7u1ep6PY_NT47QP7yZ9nwTS7rURVgIClqgP9nGgWXqJIo2ZgeiHyX0XxSme-d8",
        "https://play-lh.googleusercontent.com/LgIsFzfBVBl5exx7yH_Pan39ykdQZO2xxUl5NwhSSOm4VSj-i-qIk6Jxn3OiC5acJAE",
        "https://play-lh.googleusercontent.com/_mxrolXn3cZFEVCD5yTIRaSEEtYysC7bFmI_Ha8FwcVuio_Z-l_iqQz_X0Tdr2WHdOLy",
        "https://play-lh.googleusercontent.com/Kh0hXc0vdQTCDYLv88lGMztCoveasy5S-gsdk-3_h02I_SQlq9QzC8vOUWiLHcr19WU",
        "https://play-lh.googleusercontent.com/uJ8szs0pV1TBtYYl8N7IxPPUvwF_gBUbeMoaL70s175coJYpM4bsEammpl4FPnKrsQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 2, 2019",
    "lastUpdatedOn": "Dec 17, 2023",
    "updated": 1702811013,
    "version": "1.2.1",
    "comments": [],
    "appId": "com.mw.hd.mobile.mirror.pro",
    "url": "https://play.google.com/store/apps/details?id=com.mw.hd.mobile.mirror.pro&hl=en&gl=us"
}