{
    "title": "Mammoth VPN",
    "description": "Mammoth VPN provides fast and secure access to the internet. With a wide range of servers located in different countries, you can use Mammoth VPN to bypass restrictions and access content that is not available in your region. With advanced encryption technology, your internet traffic will be protected and your online privacy will be safeguarded. Connect to Mammoth VPN today and enjoy the benefits of a fast and secure online experience.",
    "descriptionHTML": "Mammoth VPN provides fast and secure access to the internet. With a wide range of servers located in different countries, you can use Mammoth VPN to bypass restrictions and access content that is not available in your region. With advanced encryption technology, your internet traffic will be protected and your online privacy will be safeguarded. Connect to Mammoth VPN today and enjoy the benefits of a fast and secure online experience.",
    "summary": "Secured Connection",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 667534,
    "score": 4.3366337,
    "ratings": 1803,
    "reviews": 395,
    "histogram": [
        195,
        52,
        52,
        141,
        1356
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Trx Soft Bay",
    "developerId": "Trx+Soft+Bay",
    "developerEmail": "trxsoft.bay@gmail.com",
    "developerWebsite": "https://ecda446d0.app-ads-txt.com",
    "developerAddress": null,
    "privacyPolicy": "https://doc-hosting.flycricket.io/gem-vpn-privacy-policy/e62e321c-2c2a-41f9-b6cb-d9a020eb3532/privacy",
    "genre": "Productivity",
    "genreId": "PRODUCTIVITY",
    "categories": [
        {
            "name": "Productivity",
            "id": "PRODUCTIVITY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/taz_gtAI4L4SoMH9GCR8fRIE76w38QWaU8mjWhbcmsPS_kj19P_9ycR4HmrouUp979jQ",
    "headerImage": "https://play-lh.googleusercontent.com/RdBXBJz2kLAXNqMfb-DQNOyhqk-xUJawdSmt9eKAoj9DFYQAz4IQZBRn8HTqcRU6m7wu",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ivl6E-7ElGn5PYr8WG2PqYk2ICWgk3Q4mdzryq2p6ibRQx6lwAN0GpJbT8izBA9YIw",
        "https://play-lh.googleusercontent.com/bj4YYSVXdgaTBoeDMDIRwivHaEb7mro0WL6_OLXCzh6Ca6qW_Uc7hHBRz-eGk2IyotM",
        "https://play-lh.googleusercontent.com/jMX_8-Zn1VNbvGScEWzURqYcgPyXmQLcOcyW2aL74l7GQnvCFfPYcv01tvuYhLcbyBM",
        "https://play-lh.googleusercontent.com/ev-qk_3JscVpKpywZGMZbmeuLXonPlgyHwNYTzvEJdq9z09rgd33di_SY9-Hhn04w6s",
        "https://play-lh.googleusercontent.com/HfuaQuDLEQohl4yjY8TEi63UfqwaUC7SnxnV-BdYWD9fdaV9MMkRuZOVJmc8eurtcQ",
        "https://play-lh.googleusercontent.com/vUJvfTdCSmI_Vh6q6ceJDg2ULJ9GGqPTJBqytXunsmab0qkw25kbPnaYDTXnyfmw4w"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 19, 2023",
    "lastUpdatedOn": "Jun 21, 2023",
    "updated": 1687387566,
    "version": "3",
    "comments": [],
    "appId": "com.mammothvpn20023.pro",
    "url": "https://play.google.com/store/apps/details?id=com.mammothvpn20023.pro&hl=en&gl=us"
}