{
    "title": "Gluroo: Diabetes Log Tracker",
    "description": "Simplify Diabetes.  Together!\r\n\r\nWorry about diabetes less and live life more with Gluroo, a free collaborative diabetes logger that works like a chat app.\r\n\r\n\u201cThe simplest yet most comprehensive diabetes tool you may ever need\u201d \r\n- DiabetesMine\r\n\r\nCOLLABORATE: STREAMLINED FOR DIABETES MANAGEMENT\r\n\r\nWork together to manage the diabetes of your loved one by streamlining group-chat messaging, blood glucose and insulin levels, exercise, device health and more - all in one place for everyone to see.\r\n\r\nStay connected with your GluCrew, whether you\u2019re in the same room or across the globe!\r\n\r\n\r\nLOGGING: COMPREHENSIVE AND EASY!\r\n\r\nWhether with a few simple taps of the intuitive UI or text recognition (\u201ddosed 5u\u201d), Gluroo gives you a fast way to log everything you need:\r\n\r\n* Food\r\n* Insulin doses\r\n* Exercise\r\n* CGM readings and manual finger pricks\r\n* Opening a new insulin vial or pen\r\n* Adding a new pump site, CGM sensor, or transmitter\r\n* Custom hashtags that you can search for later\r\n\r\n\r\nNOTIFICATIONS: SMARTER, FEWER\r\n\r\nAlerts and notifications invade our lives and can be distracting and overwhelming.\r\n\r\nGluroo uses a new method of coordinated smart notifications which makes sure the right set of people get alerted at the right times. Every alert is actionable. For example, if the person with diabetes (PWD) has low blood sugar, Gluroo will alert them first and give them a chance to address the low.\r\n\r\nIf they don\u2019t address it within a few minutes, the alert will roll over to the rest of the GluCrew. This lets the PWD develop responsibility and confidence while always having someone else ready to back them up - and reducing alarm fatigue in the process!\r\n\r\n\r\nSEARCH:\r\n\r\nAs you log meals, doses, exercise and more, you build up a valuable data source. Look back at how you handled a tricky sushi lunch or your favorite pizza joint in the past, expand an inline chart of your blood glucose readings during that period, and use that information to help you handle it better in the future. \r\n\r\n\r\nINTEGRATIONS:\r\n\r\nContinuous Glucose Monitors (CGM) - Dexcom (G7, G6, G5), Freestyle Libre, blood glucose meters, and more planned!\r\n\r\nInsulin Delivery Types - Gluroo supports pumps like Omnipod DASH, Omnipod OP5, DIY Loop, and Nightscout instances with more planned!\r\n\r\nYou can also easily log your daily injections with SmartPens, pens, vials, syringes, and more.\r\n\r\nGluroo is also available for Wear OS (based on G-Watch Wear), and provides a watch face and several Gluroo-specific data complications (the IOB and COB data complications are shown). The data chart on the watch requires the Gluroo phone app to be installed and configured with a supported CGM.\r\n\u2014 More Information \u2014\r\n\r\nCaution: Dosing decisions should not be made based on this device. The user should follow instructions on the continuous glucose monitoring system. This device is not intended to replace self-monitoring practices as advised by a physician. Not available for patient use.\r\n\r\nGluroo is neither reviewed by nor approved by the FDA and is free to use.\r\n\r\nFor more about Gluroo, see also: https://www.gluroo.com\r\n\r\nPrivacy policy: https://www.gluroo.com/privacy.html\r\n\r\nEULA: https://www.gluroo.com/eula.html\r\n\r\nDexcom, Freestyle Libre, Omnipod, DIY Loop, and Nightscout are trademarks of their respective owners. Gluroo is not affiliated with Dexcom, Abbott, Insulet, DIY Loop, nor Nightscout.",
    "descriptionHTML": "Simplify Diabetes.  Together!<br><br>Worry about diabetes less and live life more with Gluroo, a free collaborative diabetes logger that works like a chat app.<br><br>\u201cThe simplest yet most comprehensive diabetes tool you may ever need\u201d <br>- DiabetesMine<br><br>COLLABORATE: STREAMLINED FOR DIABETES MANAGEMENT<br><br>Work together to manage the diabetes of your loved one by streamlining group-chat messaging, blood glucose and insulin levels, exercise, device health and more - all in one place for everyone to see.<br><br>Stay connected with your GluCrew, whether you\u2019re in the same room or across the globe!<br><br><br>LOGGING: COMPREHENSIVE AND EASY!<br><br>Whether with a few simple taps of the intuitive UI or text recognition (\u201ddosed 5u\u201d), Gluroo gives you a fast way to log everything you need:<br><br>* Food<br>* Insulin doses<br>* Exercise<br>* CGM readings and manual finger pricks<br>* Opening a new insulin vial or pen<br>* Adding a new pump site, CGM sensor, or transmitter<br>* Custom hashtags that you can search for later<br><br><br>NOTIFICATIONS: SMARTER, FEWER<br><br>Alerts and notifications invade our lives and can be distracting and overwhelming.<br><br>Gluroo uses a new method of coordinated smart notifications which makes sure the right set of people get alerted at the right times. Every alert is actionable. For example, if the person with diabetes (PWD) has low blood sugar, Gluroo will alert them first and give them a chance to address the low.<br><br>If they don\u2019t address it within a few minutes, the alert will roll over to the rest of the GluCrew. This lets the PWD develop responsibility and confidence while always having someone else ready to back them up - and reducing alarm fatigue in the process!<br><br><br>SEARCH:<br><br>As you log meals, doses, exercise and more, you build up a valuable data source. Look back at how you handled a tricky sushi lunch or your favorite pizza joint in the past, expand an inline chart of your blood glucose readings during that period, and use that information to help you handle it better in the future. <br><br><br>INTEGRATIONS:<br><br>Continuous Glucose Monitors (CGM) - Dexcom (G7, G6, G5), Freestyle Libre, blood glucose meters, and more planned!<br><br>Insulin Delivery Types - Gluroo supports pumps like Omnipod DASH, Omnipod OP5, DIY Loop, and Nightscout instances with more planned!<br><br>You can also easily log your daily injections with SmartPens, pens, vials, syringes, and more.<br><br>Gluroo is also available for Wear OS (based on G-Watch Wear), and provides a watch face and several Gluroo-specific data complications (the IOB and COB data complications are shown). The data chart on the watch requires the Gluroo phone app to be installed and configured with a supported CGM.<br>\u2014 More Information \u2014<br><br>Caution: Dosing decisions should not be made based on this device. The user should follow instructions on the continuous glucose monitoring system. This device is not intended to replace self-monitoring practices as advised by a physician. Not available for patient use.<br><br>Gluroo is neither reviewed by nor approved by the FDA and is free to use.<br><br>For more about Gluroo, see also: https://www.gluroo.com<br><br>Privacy policy: https://www.gluroo.com/privacy.html<br><br>EULA: https://www.gluroo.com/eula.html<br><br>Dexcom, Freestyle Libre, Omnipod, DIY Loop, and Nightscout are trademarks of their respective owners. Gluroo is not affiliated with Dexcom, Abbott, Insulet, DIY Loop, nor Nightscout.",
    "summary": "Connect your CGM, see blood sugar readings on your watch, and simplify diabetes",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 52507,
    "score": 4.39,
    "ratings": 651,
    "reviews": 157,
    "histogram": [
        45,
        32,
        19,
        77,
        473
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Gluroo Imaginations Inc.",
    "developerId": "7481526561989965896",
    "developerEmail": "info@gluroo.com",
    "developerWebsite": "https://www.gluroo.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.gluroo.com/privacy.html",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/xHwryuuKiVUYrM67j3C4WjLRK1RFruU3WXmqqBfHzLj3DyOMxX7sXUkWEmzYPCQPrOc",
    "headerImage": "https://play-lh.googleusercontent.com/mKstWZN4CYV8DIOOSBnS-WJWauaPtAqZ9RSL5RXeM69t4CkpN-_r5vzy0NzOXWsBodzX",
    "screenshots": [
        "https://play-lh.googleusercontent.com/tEoDfys_tP3b9YZ6RrGjie0lw2Ww7b7uLFqrBLnac-x9Y23Paw5k8oAUo6KkHww9xw",
        "https://play-lh.googleusercontent.com/JduLbpbKQa24W4G1WWM3A2fXOvm7ptzkuevBpkFLo2eyEkmtVR3MdKCiOHHxXeNaUXA",
        "https://play-lh.googleusercontent.com/EmEq9l5DIgHpx5tuDFgKZfEb-Yq7bwwetURRx1Ak8kh2854n9ClrOzkoRM0iF0CHTax2",
        "https://play-lh.googleusercontent.com/weQ2KZkDiwMQmdRmshvUY7TvGR9_AvruvQ4c-VMRl1C4VH019P3p5nTUnBnxEFDzLdQ",
        "https://play-lh.googleusercontent.com/TTCSZYu2XAqJ5WKSYWEpM_X-d7SLTWT3i9iTyOOaqgLAfTxrJDYG-Ym_O3U5mHgvWTA",
        "https://play-lh.googleusercontent.com/SKJzXKaS7E3m-sZmyW3ThuusiR4biYG_Mv4efzZxM8zYcSHGk4QG2NpCZns67CSaQw",
        "https://play-lh.googleusercontent.com/l7UeG6ryt8QKXEcpi2-0LOBp9aZIbjCj5BMkcH32wHoeFU6tblAxEbQeiyqDkKF2sZFc",
        "https://play-lh.googleusercontent.com/UM8Tg7NEh276Rp3NW86hbNbcwciBnRatDY_xX3WfmZv1BuTu428jaFYC6AXctGXbxA",
        "https://play-lh.googleusercontent.com/kyCKPzvsmpWHPJYYMSBRA01ap-8IQWZWgXhoBQ3ON5RzeVABKDiz7PWspUftbFjvVU05",
        "https://play-lh.googleusercontent.com/oYnOy0TcwfkYzkPFkASDvDXK3C7xD8r6WB5IFh0MTlX4YNcdfkDkOkmfvQOD1mvBHA",
        "https://play-lh.googleusercontent.com/FVvc1TIvDav_iitiiSQA2O7G6Ay7HmELWI-M98dA0jWD9QhZkQm984OJg7WDwvJa4g",
        "https://play-lh.googleusercontent.com/VN2WfyCp7J8zXSC9w6BZZGcJT8oM23YWpBLqX01IgWa3BNvQrw4BEK3VK0x4oDTcuZyW",
        "https://play-lh.googleusercontent.com/yws3B5yt958UJHdNlweVzvBgusGHvCABZvaWhU-g54qONoVXHDK2Bgh_mrHkWQHKsKQ",
        "https://play-lh.googleusercontent.com/qP1nv4Sn-3BPaXKOeWD0adxDzF0cojpwoKSi0iTVJyRgTrsFPNdJK348x4qPN5_OA8k",
        "https://play-lh.googleusercontent.com/mirTmFbu_TLAYQrHIxnIDjTZIeFQeN-oD7D8Jd7bc_gGuiaVYE94BnSW_fShdmVYlJE",
        "https://play-lh.googleusercontent.com/zIIX-U77yLz2-NVNBIF23OsbVKYRKR4aHu38JXUcyY5ms19CNdeqa-UsuTqi9jfpOEQ",
        "https://play-lh.googleusercontent.com/cyjGOtmgEKb6qFlD9BmVNdEO6PJUXb8FPX4i-AnO2yoPSZSRRrBggXP58MLaYPA3Sro",
        "https://play-lh.googleusercontent.com/csqwgEhozpgSz1Z1Hmcm8UqD1zqcxg7w49tufhoLtjweGhkofOUflaaqG-HrXiPQFA",
        "https://play-lh.googleusercontent.com/RQxJ40xCBAiO1KRs8DttOg6mxUg7ZKynBO3ndXfAtmCZ_86bMHu9B7PMKRvUTnPcbA",
        "https://play-lh.googleusercontent.com/4MBlW_R9K13XrzT_DofoBoyhzf8mZRh6OmjOGh3ESp6rlEfhjYB0yDikR0vGs7thLtE",
        "https://play-lh.googleusercontent.com/POVJTOKbBlgNeyY2mZktgQnLnVXE6o7n-CCifuQ7b-B-SJ-8SUUMaYb0TQ427Y2_dja3"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 29, 2022",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731712928,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.gluroo.app",
    "url": "https://play.google.com/store/apps/details?id=com.gluroo.app&hl=en&gl=us"
}