{
    "title": "Shanghai Mahjongg",
    "description": "Shanghai Mahjongg: Where Tradition Meets Innovation\r\nWelcome to Shanghai Mahjong, where the timeless allure of traditional Shanghai tile-matching merges with innovative gameplay. We're committed to delivering a game that's both engaging and challenging, tailored to seamlessly adapt to tablets and mobile phones of all sizes and shapes.\r\nHow to Play Mahjong Solitaire:\r\nPlaying Shanghai Mahjong Solitaire is straightforward. Your goal is to clear all tiles on the board by matching identical images. Tap or slide two matching tiles to remove them. Strategize to uncover and match tiles that aren't concealed or blocked. As you progress, puzzles become more intricate, enhancing your cognitive skills. Completing all tiles signals success in the mahjong solitaire puzzle!\r\nWhy Choose Shanghai Mahjong?\r\nShanghai Mahjong stands out with its blend of tradition and innovation:\r\n   \u2022   Classic Gameplay, Modern Flair: Immerse yourself in Shanghai mahjong with a contemporary twist, featuring intricate tile designs and engaging mechanics.\r\n   \u2022   Enhanced Visuals and Interface: Enjoy large, visually appealing tiles and a user-friendly interface designed for clear visibility and ease of use on any device.\r\n   \u2022   Challenge and Skill Development: Test your abilities through progressively challenging puzzles that stimulate strategic thinking and cognitive skills.\r\n   \u2022   Variety of Game Modes: Dive into classic modes or explore unique challenges crafted to keep gameplay fresh and exciting.\r\nUnique Features of Shanghai Mahjong:\r\n   \u2022   Innovative Tile Designs: Discover special tiles and power-ups that add depth and strategy, offering new ways to clear the board.\r\n   \u2022   Accessible Gameplay Options: Use tools like hints, undo moves, and reshuffles to conquer difficult puzzles.\r\n   \u2022   Daily and Weekly Challenges: Engage in daily tasks and weekly challenges to earn rewards, improve skills, and track progress.\r\n   \u2022   Offline Play Capability: Enjoy uninterrupted gaming sessions with full offline support, ideal for gaming on the go without internet.\r\n   \u2022   Cross-Device Compatibility: Seamlessly switch between smartphones and tablets for a consistent and enjoyable gaming experience.\r\nShanghai Mahjong sets itself apart by honoring tradition while embracing innovation, promising an immersive and satisfying mahjong experience. Embark on your Shanghai Mahjong journey today and discover the thrill of mastering tile-matching puzzles with style and sophistication!",
    "descriptionHTML": "Shanghai Mahjongg: Where Tradition Meets Innovation<br>Welcome to Shanghai Mahjong, where the timeless allure of traditional Shanghai tile-matching merges with innovative gameplay. We&#39;re committed to delivering a game that&#39;s both engaging and challenging, tailored to seamlessly adapt to tablets and mobile phones of all sizes and shapes.<br>How to Play Mahjong Solitaire:<br>Playing Shanghai Mahjong Solitaire is straightforward. Your goal is to clear all tiles on the board by matching identical images. Tap or slide two matching tiles to remove them. Strategize to uncover and match tiles that aren&#39;t concealed or blocked. As you progress, puzzles become more intricate, enhancing your cognitive skills. Completing all tiles signals success in the mahjong solitaire puzzle!<br>Why Choose Shanghai Mahjong?<br>Shanghai Mahjong stands out with its blend of tradition and innovation:<br>   \u2022   Classic Gameplay, Modern Flair: Immerse yourself in Shanghai mahjong with a contemporary twist, featuring intricate tile designs and engaging mechanics.<br>   \u2022   Enhanced Visuals and Interface: Enjoy large, visually appealing tiles and a user-friendly interface designed for clear visibility and ease of use on any device.<br>   \u2022   Challenge and Skill Development: Test your abilities through progressively challenging puzzles that stimulate strategic thinking and cognitive skills.<br>   \u2022   Variety of Game Modes: Dive into classic modes or explore unique challenges crafted to keep gameplay fresh and exciting.<br>Unique Features of Shanghai Mahjong:<br>   \u2022   Innovative Tile Designs: Discover special tiles and power-ups that add depth and strategy, offering new ways to clear the board.<br>   \u2022   Accessible Gameplay Options: Use tools like hints, undo moves, and reshuffles to conquer difficult puzzles.<br>   \u2022   Daily and Weekly Challenges: Engage in daily tasks and weekly challenges to earn rewards, improve skills, and track progress.<br>   \u2022   Offline Play Capability: Enjoy uninterrupted gaming sessions with full offline support, ideal for gaming on the go without internet.<br>   \u2022   Cross-Device Compatibility: Seamlessly switch between smartphones and tablets for a consistent and enjoyable gaming experience.<br>Shanghai Mahjong sets itself apart by honoring tradition while embracing innovation, promising an immersive and satisfying mahjong experience. Embark on your Shanghai Mahjong journey today and discover the thrill of mastering tile-matching puzzles with style and sophistication!",
    "summary": "Classic Solitaire Match Game",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 254871,
    "score": 4.7065215,
    "ratings": 3223,
    "reviews": 730,
    "histogram": [
        173,
        23,
        46,
        80,
        2895
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Rankhamb Venkatesh",
    "developerId": "Rankhamb+Venkatesh",
    "developerEmail": "support@yyplaygames.com",
    "developerWebsite": "https://block.yyplaygames.com",
    "developerAddress": null,
    "privacyPolicy": "https://block.yyplaygames.com/privacy-policy.html",
    "genre": "Board",
    "genreId": "GAME_BOARD",
    "categories": [
        {
            "name": "Board",
            "id": "GAME_BOARD"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Cctqo_5NFzf8LB9N8t6zJvRwMp4JUi07Ypk0FN5xDPBTaioQs5aAhSrRSRF21HNK5dB2",
    "headerImage": "https://play-lh.googleusercontent.com/apDizG2vUunpPWp4XfkBaRDp8ruwN0eHRHHHiUJISLW4UrJs6VQzWHPoArQgAhKg1g",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Iwe3DEmrBj-4HXBWWbfA7ZdHUu9Y_LFqtIpT9MXtMlzPXpxcxRhw6DsZJoxWASRIkpo",
        "https://play-lh.googleusercontent.com/RY4lZpSLNReKCe4GbJZqrkMTgNTcdAb_nbPMXPdPGXkPqLnqAbZI2WhFh83Iw4yLTg",
        "https://play-lh.googleusercontent.com/Ugrrpf5OJHoMDvg0-l64XR_UdUTa9DIvf0Z1CpGuVbJPeJHyBCXvDpX6FR53i6RwZJsx",
        "https://play-lh.googleusercontent.com/ixFhMOjltvsm_cnIXd0hhJnrnrDHuvL1YLbB_DDhacfmpJkvzoIwbymK7iUufbPPzBM",
        "https://play-lh.googleusercontent.com/hJoRDuW1myVJf0FOW3ts_E0nlAB0DD3ZYhh_7Gn5qsZcIT8yT8R3z67e-Wenw5hXmcg",
        "https://play-lh.googleusercontent.com/iHMFhsJ5Jf_XGKsIBYYaV5duGxfX9Q8xCHSi3OmmWQh5fz3Upyq-hN_VgNgM2hjW2g",
        "https://play-lh.googleusercontent.com/jg6Rej-NcXDMkuLmxnP5rmOO5RjZivYzWbiJkVByVy-jvXM_j8YFyn3eAlKc0XNb8sAw",
        "https://play-lh.googleusercontent.com/dxze8Y98otJiRqz6yN34cJZv-M_A32Z9P9f4rwOE4xFPsaRn1T55I8A2Kr-3l3aqojU",
        "https://play-lh.googleusercontent.com/wzqIEq6prfkHTKI1z8kofpzKJ2vfQTgOYg69x9kl3ePsLKpRo9gymoskyKbjekDhO65D",
        "https://play-lh.googleusercontent.com/B_JRI5BvBS7LZA_nMCVLBqnJc1RQkSRRGhOBhv9XVqWB1IclNsCE_t4d16TjxqCnVJQ",
        "https://play-lh.googleusercontent.com/PrIv6WDwVPINGiErXd7BKIFWsRFLKCsG9yIW5pPKTZV6E6t97iDSNjnACBR_6vJKiW8",
        "https://play-lh.googleusercontent.com/5JcyG2yVqqj2y-RPkxheCqzNBbBxqE0ImqofLo15Vx8zYT746oUKn7nMwQQ73xvqR3ZZ",
        "https://play-lh.googleusercontent.com/N_M4LrZXcu7VmXGDZP1KVpGGX1k0s8g2gVluK-V1_OiRssfolnQUGGsNbkPGRWzm5_4",
        "https://play-lh.googleusercontent.com/x9tWFDqQCMALg68EEi5AEa66Q6hgBKaYKcjVkfpoeO6ksreLRyPKh5yykqx7tEcDlmLT",
        "https://play-lh.googleusercontent.com/AokU7y5qwhpI4DrTmlMptdCoWQLTKrjulqOioLoWqKPjYdCUweyPngzlXFwWSW7Y3o94"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 5, 2024",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731683765,
    "version": "1.9.0",
    "comments": [],
    "appId": "com.mahjong.op.gp",
    "url": "https://play.google.com/store/apps/details?id=com.mahjong.op.gp&hl=en&gl=us"
}