{
    "title": "Swingers & Threesomes by SDC",
    "description": "SDC swingers for couples and threesome's helps you connect with like-minded individuals for casual encounters and group activities. Our app offers a variety of features to help you find and connect with others, including:\r\n\r\n   - A 3-day trial membership with full access to all app features.\r\n   - The ability to see who's online and nearby.\r\n   - Instant and group messaging with push notification options.\r\n   - Video messaging with push notifications.\r\n   - The ability to send pictures directly from your device.\r\n   - Forums for discussions with other members.\r\n   - Speed dating and availability features to help you find partners in real-time.\r\n   - A feature that shows you who has viewed your profile.\r\n   - A travel calendar to see who's visiting your area or to announce your own travels.\r\n   - A notification when new members join in your area.\r\n   - A directory of local parties and clubs with guest lists.\r\n   - The ability to edit your profile and upload photos directly from your device.\r\n   - Extensive search functionality to help you find members who match your interests.\r\n   - Support for multiple languages, including English, Spanish, German, French, Italian, Dutch, and Portuguese.\r\n\r\n*Please note that profile photos must comply with the mobile app provider's terms of service.",
    "descriptionHTML": "SDC swingers for couples and threesome&#39;s helps you connect with like-minded individuals for casual encounters and group activities. Our app offers a variety of features to help you find and connect with others, including:<br><br>   - A 3-day trial membership with full access to all app features.<br>   - The ability to see who&#39;s online and nearby.<br>   - Instant and group messaging with push notification options.<br>   - Video messaging with push notifications.<br>   - The ability to send pictures directly from your device.<br>   - Forums for discussions with other members.<br>   - Speed dating and availability features to help you find partners in real-time.<br>   - A feature that shows you who has viewed your profile.<br>   - A travel calendar to see who&#39;s visiting your area or to announce your own travels.<br>   - A notification when new members join in your area.<br>   - A directory of local parties and clubs with guest lists.<br>   - The ability to edit your profile and upload photos directly from your device.<br>   - Extensive search functionality to help you find members who match your interests.<br>   - Support for multiple languages, including English, Spanish, German, French, Italian, Dutch, and Portuguese.<br><br>*Please note that profile photos must comply with the mobile app provider&#39;s terms of service.",
    "summary": "Swingers App for couples & threesome's near you. 3 million members worldwide",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 342645,
    "score": 4.3,
    "ratings": 1832,
    "reviews": 547,
    "histogram": [
        218,
        35,
        17,
        254,
        1298
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$25.99 - $154.99 per item",
    "developer": "SDC Media",
    "developerId": "SDC+Media",
    "developerEmail": "support@sdcmedia.com",
    "developerWebsite": "https://www.sdcmedia.com",
    "developerAddress": "2054 Kildaire Farm road #428, Cary 27511",
    "privacyPolicy": "https://www.sdcmedia.com/privacy_policy.html",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/0gb7gE9T0IETEub3xB9hApEbViCVaBqI9tml2aE1maXB-Cz10Dq8f5ZuI1t8ZbrpK5zl",
    "headerImage": "https://play-lh.googleusercontent.com/7ppO88PCr_08dypYKR5O53CY_cq5KinkJsHZLcDAPWm8Bkn9274siIW2CvzzE6Nx1g",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Mo2Rsz3o6YUfQp9xyRGyycX3kDLrNl6sITtlEQcXmECs1Wj2goItepADyo6Rrxs5VL0",
        "https://play-lh.googleusercontent.com/PWU5cUM0FIB8yGvnAItLx4T7YzWJ1CRPXa6mqGRn8SBgI3f-_P-kLlkbdg4lXGibq_7a",
        "https://play-lh.googleusercontent.com/3eHgyzB97rviTKijG50Iq72BKl154AdaE-y5uW80qgEvNrfgG7rXbzByWM5IHOzsEs0",
        "https://play-lh.googleusercontent.com/M2_deIzVmvM7DzAU-d1mlEIvANS92-0CyWP7fYTzCCNHGxl-tFBroNAIxMBxWeE8Hw",
        "https://play-lh.googleusercontent.com/E0v1cVJcEP22g64HYj0VaFEelAKLKAZ0X4ILpkNf-sKhHeI0sU7kaJ4CQXAT1x4lqcUW",
        "https://play-lh.googleusercontent.com/L8gxLt6gNlUj0T1JAyB8SRusPHuQoIUYrIrtMYuURwm0_0XWFTLBCOgV6T6iB4azAQ",
        "https://play-lh.googleusercontent.com/e9824PPuFwL_SkJsomeyUD_xWvK9TmkUAnPTimrmfESwiHb8jjikJUG1kdW0NuetyQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 2, 2022",
    "lastUpdatedOn": "Oct 30, 2024",
    "updated": 1730308450,
    "version": "4.7.3",
    "comments": [],
    "appId": "com.sdcmedia.swingers.g4",
    "url": "https://play.google.com/store/apps/details?id=com.sdcmedia.swingers.g4&hl=en&gl=us"
}