{
    "title": "Shopkick: Cash Back Gift Cards",
    "description": "Earn money as rewards, cash back, and gift cards with Shopkick while shopping! \r\nUse our receipt scanner to earn rewards and gift cards for shopping you already do. Getting cash back rewards and earning money back, deals, coupons or discounts has never been easier! Just scan receipts, earn money, and fetch your rewards while shopping! You can also use your coupons and gift cards to save on future deals! \r\n\r\nGet Started\r\nEarn rewards shopping points (called kicks) and get cash back!\r\n\r\nJust walk into stores! Earn kicks at the entrance of select stores.\r\nScan receipts: Use the in-app receipt scanner & scan select products.\r\nFetch groceries to earn money back, cash back rewards, and redeem gift cards as you shop while using our receipt scanner. Go on normal shopping runs & scan receipts through the app.\r\nEarn kicks for every dollar you spend at select partner stores when you shop with a linked credit card. You can combine your kicks with coupons and deals to save even more money while shopping! This way you can fetch rewards and earn points for the shopping you already do! \r\nOnline shopping: Do all your shopping while staying indoors!\r\nWatch videos from the comfort of your couch.\r\nInvite friends to join the Shopkick craze!\r\n\r\nWe make sure you get cash back, gift cards, and coupons as easily as it can get. Every day millions of users use Shopkick and our receipt scanner to discover new products, scan receipts, and earn rewards & coupons. The savings you earn will help keep your shopping budget healthy & happy: no need to feel guilty when you shop. For further savings, use your coupons as well!\r\n\r\nGetting extra money while shopping is a no brainer! Fetch that Xbox controller, KitchenAid or that vanilla latte with extra cream from Starbucks that you\u2019re always eyeing, and get your money back! Start using our receipt scanner and scan receipts to earn your first free gift card (of many gift cards) today!\r\n\r\nRedeem your Rewards\r\nTo create the best shopping experience for our users, we partner with major retailers & brands including:\r\nAmazon, Pampers, Huggies, Starbucks, Walmart, eBay, Groupon, TJ Maxx, Marshalls, Lowe\u2019s, Sephora, Nike, Best Buy, GameStop & many more!\r\n\r\nThe buzz about Shopkick: \u201cThis app is addictive.\u201d \u2013 Oprah.com",
    "descriptionHTML": "Earn money as rewards, cash back, and gift cards with Shopkick while shopping! <br>Use our receipt scanner to earn rewards and gift cards for shopping you already do. Getting cash back rewards and earning money back, deals, coupons or discounts has never been easier! Just scan receipts, earn money, and fetch your rewards while shopping! You can also use your coupons and gift cards to save on future deals! <br><br>Get Started<br>Earn rewards shopping points (called kicks) and get cash back!<br><br>Just walk into stores! Earn kicks at the entrance of select stores.<br>Scan receipts: Use the in-app receipt scanner &amp; scan select products.<br>Fetch groceries to earn money back, cash back rewards, and redeem gift cards as you shop while using our receipt scanner. Go on normal shopping runs &amp; scan receipts through the app.<br>Earn kicks for every dollar you spend at select partner stores when you shop with a linked credit card. You can combine your kicks with coupons and deals to save even more money while shopping! This way you can fetch rewards and earn points for the shopping you already do! <br>Online shopping: Do all your shopping while staying indoors!<br>Watch videos from the comfort of your couch.<br>Invite friends to join the Shopkick craze!<br><br>We make sure you get cash back, gift cards, and coupons as easily as it can get. Every day millions of users use Shopkick and our receipt scanner to discover new products, scan receipts, and earn rewards &amp; coupons. The savings you earn will help keep your shopping budget healthy &amp; happy: no need to feel guilty when you shop. For further savings, use your coupons as well!<br><br>Getting extra money while shopping is a no brainer! Fetch that Xbox controller, KitchenAid or that vanilla latte with extra cream from Starbucks that you\u2019re always eyeing, and get your money back! Start using our receipt scanner and scan receipts to earn your first free gift card (of many gift cards) today!<br><br>Redeem your Rewards<br>To create the best shopping experience for our users, we partner with major retailers &amp; brands including:<br>Amazon, Pampers, Huggies, Starbucks, Walmart, eBay, Groupon, TJ Maxx, Marshalls, Lowe\u2019s, Sephora, Nike, Best Buy, GameStop &amp; many more!<br><br>The buzz about Shopkick: \u201cThis app is addictive.\u201d \u2013 Oprah.com",
    "summary": "Receipt Scanner: Earn Cash Back & Gift Cards! Scan Receipts for Money Rewards!",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 15162547,
    "score": 3.7391152,
    "ratings": 233638,
    "reviews": 74851,
    "histogram": [
        48489,
        14042,
        16818,
        24862,
        129421
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Shopkick",
    "developerId": "Shopkick",
    "developerEmail": "help@shopkick.com",
    "developerWebsite": "https://www.shopkick.com",
    "developerAddress": null,
    "privacyPolicy": "https://shopkick.com/privacy-policy",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/sMOeh0laoKhx9_OLX5q4viwfaQSQTCRRInWYlchBDU9iBZu5JPj-VamMYHfmdzOH4Dg",
    "headerImage": "https://play-lh.googleusercontent.com/9fEbhe2uqAvw5WHe2ueE06ryJgE45OnrWQqEgu_UXrfBJ9xjGZY-Fb1HcUzraV5ocTA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/B4pfVrYlel1fKCEFJM9MmrpBqEbveCJg-A7lfPwosqSn9THtY_35GUdRfKlo_m9Vjw",
        "https://play-lh.googleusercontent.com/m7SjpKQwh3zJr4gTt9pKvmj8G_GxFy-Af0VFaHSbM3AN02vvPWp-DJVXtRXUP1KyLz4",
        "https://play-lh.googleusercontent.com/DEzoG0AYNan52aaqIR4u62KhB-DiqhVDGAuhCJgr59xVrhfYuMoChnLJqlGzrRPrxHvU",
        "https://play-lh.googleusercontent.com/2v9UBxpI6ymuD-YuiQCAV2GdmXrrSMPO1FzrNGJpRzco1UDu5oCERLWfigvNf0n5FA",
        "https://play-lh.googleusercontent.com/1L3tv_W9DAFtlRXWpdo4--u4YgtBxrzeQAtHIX_5icV3P-zEJjqomNM5QvnqbNHJEw",
        "https://play-lh.googleusercontent.com/7lMIbnk9AQle68_7HFGqcM2UzjOJWW_NsZc1wfegqK8LqjmdG2aH1L3zAtb4OrFeUi_e",
        "https://play-lh.googleusercontent.com/HRghehM8SFNNfjifVxDIqFqx8HRsOQ-62qSAzYoABGq3Q2XjuU4iQP0TzoDhqFXuAEQb",
        "https://play-lh.googleusercontent.com/1R6etHNxG5-qibeVovfLo_38I5JWlIgmmQDrmUqYtHplo14NY-tFLvIJTrbiVFJxYmU",
        "https://play-lh.googleusercontent.com/ihs-nBLkBnPQZBxPkSgBi-6ApLv8GnN0VAzojjWEK_2X6sTA2rBb2fedwzEvOqE_yM8",
        "https://play-lh.googleusercontent.com/fTowoznfM3L1huAb23OQWWxX_ErC9Aw5mLuqhD_ASbJvvV9xiVlHdvhzT76Cq7-ORxCO",
        "https://play-lh.googleusercontent.com/PB2PlXJuEglxKkjtq2gtzkRg74PXfEhbAkexPkqofFRmXS2I7yZSeP9Yh9RuYeffqA",
        "https://play-lh.googleusercontent.com/opAex7aydDAD73Y3bJ2t5hQNdE6VDOPRUXdY1aOWbRw_9fXOeDCsSkNsagUK9cNORw",
        "https://play-lh.googleusercontent.com/fTQ4zDLNXA58JnsZFsMM05biUhz0rKum32Lnn_qpZozMJZqTu4N5PEvl_2O9mgnmLw",
        "https://play-lh.googleusercontent.com/GtC78dN8WwdaHAoyxaQl6RralgBOUbdtxTs2dEWoSxh0pX-VyaWP8l8KsOEhh0uR4qw",
        "https://play-lh.googleusercontent.com/qf3sL7GEw0krWE8NzJwnQmXJYo9gyu0yQ66OVa47lzKJbJtvzELlnSo-chS6qJLCfUJz",
        "https://play-lh.googleusercontent.com/VqqZcxTeJGCYyFmVID-57geh2UMZaFUxdetbF3JUijrKMh03_eNhIGWeMtV_zBq2NLc",
        "https://play-lh.googleusercontent.com/U0gPAmlaQl75_-JWG8pp8v55D5zpugm5LK_nmOPcyUF3X89zcbUAyhYSWIbvwXd_owY",
        "https://play-lh.googleusercontent.com/5VoBMO_s0JhM0f8jyz6lvBWBhCbhVyEzWmzAYq4qoKXmMbfoTLcTKPozBVR52kVVE0c",
        "https://play-lh.googleusercontent.com/iL2lTmGcV6X1GeQ0EH8_zkbfSKUO5jiqzwARyE43s2MOmY9GrfhQesJtHSDs0bzm15c",
        "https://play-lh.googleusercontent.com/gYFO-TiiPKD6-ng-nvmWNFumkP1YCPkJmGF0geLcSYdUpvxR8r-EpD7aViCB9fKLdXQ",
        "https://play-lh.googleusercontent.com/vImOgJvkptJRi7nmXRGWEURdz3Nor-xbfaUynmP78eJF6Z3cHpkojGaj72B4yBxSoIc",
        "https://play-lh.googleusercontent.com/Dy-9LQgN6Q-Ofwt1ax9FPY_TTCEG6UlBdwz4dSa3KjBzGmROxstS_Ig186JU1s2Sm5MY",
        "https://play-lh.googleusercontent.com/ypppl3-4IwhhlDXFPO8jm5JQ6FHDfpejMRV8ayRAaI_pqARDuCJ-7EDpRxnaqVlJDA",
        "https://play-lh.googleusercontent.com/Ej40rsXWto7OllC9djMSuHW1mJfpSi4gsumoS9pV3RXnVfu4wZV9VYBGpTlDQy-sDfTr"
    ],
    "video": "https://www.youtube.com/embed/7s9R_jMT6lY?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/9fEbhe2uqAvw5WHe2ueE06ryJgE45OnrWQqEgu_UXrfBJ9xjGZY-Fb1HcUzraV5ocTA",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 14, 2010",
    "lastUpdatedOn": "Sep 24, 2024",
    "updated": 1727213197,
    "version": "7.1.3",
    "comments": [],
    "appId": "com.shopkick.app",
    "url": "https://play.google.com/store/apps/details?id=com.shopkick.app&hl=en&gl=us"
}