{
    "title": "Radar Map, Radar Detector, HUD",
    "description": "Radar Map, Radar Detector, HUD is a leading police radar and speed cameras finder to save your money. Excellent and ultimate functions are following to experience a great journey...\r\n\r\nDiscover a seamless driving experience with \"Radar Map, Radar Detector, HUD,\" an innovative app designed to enhance your journey and keep you informed on the road. This app combines essential driving tools into one integrated platform, revolutionizing how you interact with your vehicle and the world around you.\r\n\r\nReal-time Radar Detector\r\nWorried about speed cameras and speed traps? Our advanced radar detector scans for both mobile and fixed radars, providing you with timely radar alerts. Unlike other driving app, our radarbot technology is engineered to differentiate between speed radar gun and other signals, ensuring that you receive only accurate and relevant alerts.\r\n\r\nHead-up Display (HUD)\r\nSay goodbye to the distraction of looking down at your phone or GPS navigation system. Our head-up display feature projects crucial driving information directly onto your windshield. Navigate with ease and keep your eyes focused on the road ahead.\r\n\r\nUp-to-date Maps\r\nNever lose your way with our meticulously updated maps. The app offers real-time GPS navigation, ensuring that you're always on the quickest and safest route. Whether it's avoiding a speed trap or finding a shortcut, the maps feature offers a dynamic look at the road ahead.\r\n\r\nFind Closest Radar\r\nUsing the cutting-edge radarbot technology, the speed-camera traffic app pinpoints the nearest speed radar or speed camera, allowing you to adjust your driving accordingly. You can also see the proximity of cop radar, enabling you to stay well within speed limits and avoid tickets.\r\n\r\nTravel History\r\nYour past routes are saved in the travel history feature, allowing you to review your drives, the alerts received, and any interactions with speed cameras and speed radars. This can be an invaluable tool for long-term road awareness and driving improvement.\r\n\r\nSpeedometer\r\nNever be caught off guard by speed limits again. Our digital speedometer display shows your current speed and compares it with local speed limits, making it easier than ever to drive responsibly.\r\n\r\nDownload \"Radar Map, Speed Camera Radar Detector, HUD\" today and experience a new dimension in driving technology. Take the stress out of your journey with radar alerts, head-up displays, and a host of other features designed to keep you safe and focused on the road.",
    "descriptionHTML": "Radar Map, Radar Detector, HUD is a leading police radar and speed cameras finder to save your money. Excellent and ultimate functions are following to experience a great journey...<br><br>Discover a seamless driving experience with &quot;Radar Map, Radar Detector, HUD,&quot; an innovative app designed to enhance your journey and keep you informed on the road. This app combines essential driving tools into one integrated platform, revolutionizing how you interact with your vehicle and the world around you.<br><br>Real-time Radar Detector<br>Worried about speed cameras and speed traps? Our advanced radar detector scans for both mobile and fixed radars, providing you with timely radar alerts. Unlike other driving app, our radarbot technology is engineered to differentiate between speed radar gun and other signals, ensuring that you receive only accurate and relevant alerts.<br><br>Head-up Display (HUD)<br>Say goodbye to the distraction of looking down at your phone or GPS navigation system. Our head-up display feature projects crucial driving information directly onto your windshield. Navigate with ease and keep your eyes focused on the road ahead.<br><br>Up-to-date Maps<br>Never lose your way with our meticulously updated maps. The app offers real-time GPS navigation, ensuring that you&#39;re always on the quickest and safest route. Whether it&#39;s avoiding a speed trap or finding a shortcut, the maps feature offers a dynamic look at the road ahead.<br><br>Find Closest Radar<br>Using the cutting-edge radarbot technology, the speed-camera traffic app pinpoints the nearest speed radar or speed camera, allowing you to adjust your driving accordingly. You can also see the proximity of cop radar, enabling you to stay well within speed limits and avoid tickets.<br><br>Travel History<br>Your past routes are saved in the travel history feature, allowing you to review your drives, the alerts received, and any interactions with speed cameras and speed radars. This can be an invaluable tool for long-term road awareness and driving improvement.<br><br>Speedometer<br>Never be caught off guard by speed limits again. Our digital speedometer display shows your current speed and compares it with local speed limits, making it easier than ever to drive responsibly.<br><br>Download &quot;Radar Map, Speed Camera Radar Detector, HUD&quot; today and experience a new dimension in driving technology. Take the stress out of your journey with radar alerts, head-up displays, and a host of other features designed to keep you safe and focused on the road.",
    "summary": "Radar Detector, Speedometer, Maps, Travel History, Speed Camera, HUD for Journey",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 11222588,
    "score": 4.35,
    "ratings": 14677,
    "reviews": 184,
    "histogram": [
        1613,
        427,
        136,
        1457,
        11002
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $29.99 per item",
    "developer": "Negroni",
    "developerId": "Negroni",
    "developerEmail": "android@negroniapplicationslimited.com",
    "developerWebsite": "http://radarmaps.negroniapplicationslimited.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.negroniapplicationslimited.com/privacy-policy/",
    "genre": "Maps & Navigation",
    "genreId": "MAPS_AND_NAVIGATION",
    "categories": [
        {
            "name": "Maps & Navigation",
            "id": "MAPS_AND_NAVIGATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/7E1a9yZqULIYxR-Lw29SDK9MedCu90PvcTn7GDGVbn_2tLYGiA44qyZUa-yNTZSRR8ee",
    "headerImage": "https://play-lh.googleusercontent.com/zEIeTg1BczWC2qD6ZWAc2vH4xOMK5M5umZBOzDhOIn1A8oAHGZ_K6XOtCaKXBE9VCR3W",
    "screenshots": [
        "https://play-lh.googleusercontent.com/dQ6p9VDDbRK6iunTKNZnYUK7UTU6qg8BRdeGEOI3J2bVIoQxMkVcyN_29QOdv3rnv9o",
        "https://play-lh.googleusercontent.com/-KuCgQe6i91vv0B8_RhKMp-wtUYnvPRcLgvXxhHp58CFsM1m_nNwj57sqKJ-ci3dgw",
        "https://play-lh.googleusercontent.com/x99aEzmx-1JBhI8RYRM4-Zs2Ej--KTYxVT-RxHaSToDlbO69RQTbBPj-YpbNT6zJyfyz",
        "https://play-lh.googleusercontent.com/t9KlvhFpCZwQJTf23mK3zHhfJ1wj76mlqdEDBciQXvgZia3h09njhXg0y9LUOn6eZKg",
        "https://play-lh.googleusercontent.com/mAMI2HIQ8fIQuLF8hSQy62XOIUKohXnb971AEqUQzJfV6QVc46MJ-PSE_c1y9CAozUg",
        "https://play-lh.googleusercontent.com/TJmK9gBMnzcdaCa4XijH5UQXFu7_ZY4Dym7_jCW_HyawBG21NpELeD-k2vSmIPuScP0",
        "https://play-lh.googleusercontent.com/ueAIsNzGok8OtY-KfF_1zu1OA3knhv-hAOYsHn_NNStEVIQYrEj-x768C2aNIpDjzkTF",
        "https://play-lh.googleusercontent.com/LGYRIw9RWvv5lTHKIhxNZvnuZV30GhR4tHKA6qF1_siHL3ve9pnnpVE6_r6wBDufr5dJ",
        "https://play-lh.googleusercontent.com/GQTBCVwB3F0R6uG9lXKMQjb_0qEenG2zXu4WpOXMa9WN0d-oaTBLmUSe1a1Btyr9gfkZ",
        "https://play-lh.googleusercontent.com/jZhJrIKpMXxIriq8RE8rJbNbSH6Di87k6nXfg23PodM7MpUETXHLAke9abcuMCoJMQw",
        "https://play-lh.googleusercontent.com/eyyu3FOrxoo4L90sO5R87u9TaGjPMv0NAVNksR0vuVUdZOiVeOlOjCwSjnsx2izsQflG",
        "https://play-lh.googleusercontent.com/WPCBNHscHsC5xAymZDiK7LnMUQyDfEAroOsbAY4ODKlkO4Q12krCvughAngc9SnQwtjT",
        "https://play-lh.googleusercontent.com/JfR4c1-KtQeiKiRJINgThACbWnbgHcBsAPCKr8yDOSJHUK5CuRZWTGKIN_jUnUY4o-k",
        "https://play-lh.googleusercontent.com/Tgens_1P83-WTD23e7UfgzBt7cPZwtlUJRbw5TOXMzd-92janqxJhGx3PfNJjKVs9D9a",
        "https://play-lh.googleusercontent.com/_4DTHRAF1tlV3zdW0AEKS655R1SK8bBZN-qnFTxdu9ZeL21Ok-79hQlV0zN_oCJDk6g",
        "https://play-lh.googleusercontent.com/OqmGSBQZ3WHDB-SDvAt2vJyR7hRXeYqMm8FqqySkZvk09KceujmoqVlUsQ_n4gwl9Ag",
        "https://play-lh.googleusercontent.com/1rcSwZqR7Ce88j9IH8Nwvur90ozHSUjrD6FkC2TyjThGvabDCH6KvfHmkl_pgq066cY",
        "https://play-lh.googleusercontent.com/w2pEusiS2AI2xmjXlpn3a7ca_6NzW_o-fuWpG2hkf1M79qyAyoKSVClDCFfDVnYJ3e0",
        "https://play-lh.googleusercontent.com/WJdKStmNFbPKGM9-yinzf88OTmUe69GN_3HVWxuFaKYyRhgpPmdLe55q7BXeKxdc5rNO",
        "https://play-lh.googleusercontent.com/KZW8D5cZZvLf0uRyzKIsmpIlemb3Bq56dB0D_lDjCFFApFiB1UFA0vyFsEMQn3Kj0Fw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 10, 2022",
    "lastUpdatedOn": "Jul 22, 2024",
    "updated": 1721638653,
    "version": "2.14",
    "comments": [],
    "appId": "com.negroni.android.radar.maps.app",
    "url": "https://play.google.com/store/apps/details?id=com.negroni.android.radar.maps.app&hl=en&gl=us"
}