{
    "title": "Bumble For Friends: Meet IRL",
    "description": "<b>Bumble For Friends</b> is the new dedicated friendship app from Bumble, made to help you create new, meaningful friendships in your city.\r\n\r\nWhat do we have special from other chat apps? \r\nWith Bumble For Friends, you can chat, meet new people, and make friends in a community focused on kindness and safety. Whether you\u2019re new to a city or just looking to expand your circle, Bumble For Friends is the easiest way to make new friends and find community.\r\n\r\n<h1><b>Who We Are</b></h1>\r\n\r\nIf you love BFF mode within the Bumble app, then Bumble For Friends is for you! Bumble For Friends is an app where people in all stages of life can intentionally make new friends and create meaningful friendships. Bumble For Friends is not just an app that provides easy ways to help people connect and make friends with people nearby, it\u2019s also an app that prioritizes:\r\n\r\n\ud83d\udc6f\u200d\u2640\ufe0f <b>Genuine connections</b>: We include app features like profile prompts and lifestyle badges, to make it easy for people to show up in a way that's true to themselves. Allowing you to find real, genuine friendships in your city. Meet people and find friends today!\r\n\r\n\u2728 <b>Kindness</b>: We want you to feel good about chatting and meeting friends locally, so we\u2019re creating a community centered around kindness. By committing to our kindness pledge, you are helping to make Bumble For Friends a welcoming and inclusive space for everyone who wants to meet new people.\r\n\r\n\u2705 <b>Trust and safety</b>: We empower our community with safety features like Photo Verification, Reporting and Blocking, and our Safety Center, so that all members can feel safe to meet people and make new friends.\r\n\r\n\r\n<b>Get it all with Premium and expand your circle quicker!</b>\r\n\r\n- Liked you: See who's already swiped right on you to make friends instantly and have more chats\r\n- Unlimited likes: More chances to find friends\r\n- Unlimited Backtrack: Swiped left accidentally? Undo it!\r\n- Unlimited Rematch: A second chance to find your best friends\r\n- Unlimited Extends: Get an extra 24 hours to more chats and meet people\r\n- Advanced filters: Find what really matters to you in a friend\r\n- 5 SuperSwipes every week: SuperSwipes says you really like their vibe\r\n- 1 Spotlight every week: Be seen by more people for 30 mins\r\n- Travel mode: Planning a trip? Have chats and find friends before you get there\r\n- Incognito mode: Only people you swipe right on can see you\r\n\r\n<b>Download Bumble For Friends</b>\r\n\r\nBumble For Friends is free to download and use. However, we also offer an optional subscription package (Bumble For Friends Premium) and single or multiple-use paid services for which no subscription is required (including Spotlights and SuperSwipes).\r\n\r\nWe offer weekly, monthly, 3-month and 6-month subscriptions, with discounts given on the weekly price. Prices may vary per country and are subject to change without notice. Prices are clearly displayed in the app.\r\n\r\n* Payment will be charged to your Google Play account at confirmation of purchase.\r\n* Your subscription will automatically renew itself, unless auto-renewal is turned off at least 24 hours before the end of the current period.\r\n* Your account will be charged for renewal within 24 hours prior to the end of the current period.\r\n* You can manage your subscriptions and turn off auto-renewal by going to your Account Settings in the Google Play Store.\r\n* If you choose to use our free trial, any unused portion of the free trial period will be forfeited when you purchase a subscription to that publication, where applicable.\r\n* If you don\u2019t choose to purchase Bumble For Friends Premium, you can simply continue using and enjoying Bumble For Friends for free.\r\n\r\nYour personal data is securely stored on Bumble For Friends\u2014be sure to read our privacy policy and terms and conditions:\r\nbumble.com/bff/privacy\r\nbumble.com/bff/terms\r\n\r\nBumble Inc. is the parent company of Bumble for Friends, along with Bumble, Badoo and Fruitz.",
    "descriptionHTML": "<b>Bumble For Friends</b> is the new dedicated friendship app from Bumble, made to help you create new, meaningful friendships in your city.<br><br>What do we have special from other chat apps? <br>With Bumble For Friends, you can chat, meet new people, and make friends in a community focused on kindness and safety. Whether you\u2019re new to a city or just looking to expand your circle, Bumble For Friends is the easiest way to make new friends and find community.<br><br><h1><b>Who We Are</b></h1><br><br>If you love BFF mode within the Bumble app, then Bumble For Friends is for you! Bumble For Friends is an app where people in all stages of life can intentionally make new friends and create meaningful friendships. Bumble For Friends is not just an app that provides easy ways to help people connect and make friends with people nearby, it\u2019s also an app that prioritizes:<br><br>\ud83d\udc6f\u200d\u2640\ufe0f <b>Genuine connections</b>: We include app features like profile prompts and lifestyle badges, to make it easy for people to show up in a way that&#39;s true to themselves. Allowing you to find real, genuine friendships in your city. Meet people and find friends today!<br><br>\u2728 <b>Kindness</b>: We want you to feel good about chatting and meeting friends locally, so we\u2019re creating a community centered around kindness. By committing to our kindness pledge, you are helping to make Bumble For Friends a welcoming and inclusive space for everyone who wants to meet new people.<br><br>\u2705 <b>Trust and safety</b>: We empower our community with safety features like Photo Verification, Reporting and Blocking, and our Safety Center, so that all members can feel safe to meet people and make new friends.<br><br><br><b>Get it all with Premium and expand your circle quicker!</b><br><br>- Liked you: See who&#39;s already swiped right on you to make friends instantly and have more chats<br>- Unlimited likes: More chances to find friends<br>- Unlimited Backtrack: Swiped left accidentally? Undo it!<br>- Unlimited Rematch: A second chance to find your best friends<br>- Unlimited Extends: Get an extra 24 hours to more chats and meet people<br>- Advanced filters: Find what really matters to you in a friend<br>- 5 SuperSwipes every week: SuperSwipes says you really like their vibe<br>- 1 Spotlight every week: Be seen by more people for 30 mins<br>- Travel mode: Planning a trip? Have chats and find friends before you get there<br>- Incognito mode: Only people you swipe right on can see you<br><br><b>Download Bumble For Friends</b><br><br>Bumble For Friends is free to download and use. However, we also offer an optional subscription package (Bumble For Friends Premium) and single or multiple-use paid services for which no subscription is required (including Spotlights and SuperSwipes).<br><br>We offer weekly, monthly, 3-month and 6-month subscriptions, with discounts given on the weekly price. Prices may vary per country and are subject to change without notice. Prices are clearly displayed in the app.<br><br>* Payment will be charged to your Google Play account at confirmation of purchase.<br>* Your subscription will automatically renew itself, unless auto-renewal is turned off at least 24 hours before the end of the current period.<br>* Your account will be charged for renewal within 24 hours prior to the end of the current period.<br>* You can manage your subscriptions and turn off auto-renewal by going to your Account Settings in the Google Play Store.<br>* If you choose to use our free trial, any unused portion of the free trial period will be forfeited when you purchase a subscription to that publication, where applicable.<br>* If you don\u2019t choose to purchase Bumble For Friends Premium, you can simply continue using and enjoying Bumble For Friends for free.<br><br>Your personal data is securely stored on Bumble For Friends\u2014be sure to read our privacy policy and terms and conditions:<br>bumble.com/bff/privacy<br>bumble.com/bff/terms<br><br>Bumble Inc. is the parent company of Bumble for Friends, along with Bumble, Badoo and Fruitz.",
    "summary": "BFF is the friendship app to chat, meet new people near you and make friends IRL",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 933263,
    "score": 3.3,
    "ratings": 3466,
    "reviews": 582,
    "histogram": [
        1085,
        207,
        276,
        368,
        1523
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $199.99 per item",
    "developer": "Bumble Holding Limited",
    "developerId": "6810146070790225259",
    "developerEmail": "android.support@bumbleforfriends.com",
    "developerWebsite": "https://bumbleforfriends.com",
    "developerAddress": "The Broadgate Tower\nThird Floor\n20 Primrose Street\nLondon\nUnited Kingdom\nEC2A 2RS",
    "privacyPolicy": "https://bumble.com/bff/privacy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/H_cQSHvCfiI5ls2LGnEVTeFcKNQ-CKRChVdKnw8JxzN2dqX7B4EDcnHeykN38JrIAAQ",
    "headerImage": "https://play-lh.googleusercontent.com/kYpgZ7hUdc2lQ1REUfuq4Xud5Q3DO981xk2CAPQu6_jok67nk0cP-4f-ocleb000eA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/HR1fk-XXBlXsRAIB5nRT68m_SCcv3DyZTzk6Ln4NdNtXVK1f47LH5HPrp_OfGH8Gxxk",
        "https://play-lh.googleusercontent.com/FopStLg-baqK1PRHjPQexdLfMbA1pY8LGA4n9daPFVBwNIhR8B_Gh0Y7GVLmBpSf2A",
        "https://play-lh.googleusercontent.com/-lizm7cLsfpahVzYxk97PXdUtz-Jn8dz59s_D7E1X-LVIs36sR03F4xt9iDtn533gw",
        "https://play-lh.googleusercontent.com/dIh-3cAhJsgsmVTYyfS0nmUnY3to_Cx4ptLwk-8xP8HZp7zgcTXLd6WJGtGgCJ9YIoU",
        "https://play-lh.googleusercontent.com/sjQeNDqc50ovZFkipdxiRAtQ7Qya8dYm1N-oAvWKN4DKiyXQiP-EciXhyj3Cdoq8-RE",
        "https://play-lh.googleusercontent.com/rvnnjBejwWO-pkmWdn5TtEfU8t5rVxLrFLI9iuo5QuKtELEYXB85Hboca4gt9ZLL3J0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 29, 2023",
    "lastUpdatedOn": "Nov 8, 2024",
    "updated": 1731084277,
    "version": "5.388.0",
    "comments": [],
    "appId": "com.bumblebff.app",
    "url": "https://play.google.com/store/apps/details?id=com.bumblebff.app&hl=en&gl=us"
}