{
    "title": "DOWN Dating App: Date Near Me",
    "description": "<b>Wanna meet people? Looking for pure love?</b>\r\nSwipe & Date On Easy Mode with DOWN Dating App! All our dating users are looking for the best and fastest way to date, chat & meet people.\r\n\r\n<b>What is DOWN Dating App?</b>\r\nDOWN is a fast-growing dating app that promotes honesty. Liberate yourself and say if you want to Get Down (casually meet people) or Get Date (find pure love). Date the way you want!\r\n\r\n<b>Meet people, find friends or pure love</b>\r\nDating is easy! With 15+ million users, you can meet people all across the world.\r\n\r\n<b>Explore your dating life in a private & safe dating space</b>\r\nYour privacy & safety comes first. From setting up a photo verification process, to proactively hunting down bad actors & scammers, we aim to create a safe, private dating place for you to swipe, chat & date.\r\n\r\n<b>Casual dating & chat app</b>\r\nSwipe & chat freely with open-minded people. DOWN Dating App includes free games like \u2018Would You Rather?\u2019 & \u2018Photo Challenge\u2019 to break the ice & chat in a fun way!\r\n\r\n<b>Swipe & chat easily</b>\r\nOnline dating with DOWN Dating App is easy \u2014 Find friends, casual dates, pure love, or anything in between to chat with.\r\n\r\n<b>Dating made easy</b>\r\n- Get attractive profiles near you to swipe, chat, and date, every day!\r\n- Dating the honest way: If you're looking for casual fun or friends, swipe Down.\r\n- If you\u2019re looking for pure love, swipe Date.\r\n- It's that easy - swipe & date your way! Swipe, chat, date for free!\r\n- Over 1/2 of all matches on DOWN APP meet & date in real life.\r\n\r\n<b>How DOWN works:</b>\r\n- Sign in once with a Phone Number, Google, or Facebook.\r\n- Swipe the singles & couples nearby: We will only tell them you're interested if it's a match!\r\n- If it's a match, we'll connect you so you can chat & enjoy meetups!\r\n\r\n<b>Wanna meet people? Looking for pure love? Join millions of users worldwide to swipe, chat, & date.</b>",
    "descriptionHTML": "<b>Wanna meet people? Looking for pure love?</b><br>Swipe &amp; Date On Easy Mode with DOWN Dating App! All our dating users are looking for the best and fastest way to date, chat &amp; meet people.<br><br><b>What is DOWN Dating App?</b><br>DOWN is a fast-growing dating app that promotes honesty. Liberate yourself and say if you want to Get Down (casually meet people) or Get Date (find pure love). Date the way you want!<br><br><b>Meet people, find friends or pure love</b><br>Dating is easy! With 15+ million users, you can meet people all across the world.<br><br><b>Explore your dating life in a private &amp; safe dating space</b><br>Your privacy &amp; safety comes first. From setting up a photo verification process, to proactively hunting down bad actors &amp; scammers, we aim to create a safe, private dating place for you to swipe, chat &amp; date.<br><br><b>Casual dating &amp; chat app</b><br>Swipe &amp; chat freely with open-minded people. DOWN Dating App includes free games like \u2018Would You Rather?\u2019 &amp; \u2018Photo Challenge\u2019 to break the ice &amp; chat in a fun way!<br><br><b>Swipe &amp; chat easily</b><br>Online dating with DOWN Dating App is easy \u2014 Find friends, casual dates, pure love, or anything in between to chat with.<br><br><b>Dating made easy</b><br>- Get attractive profiles near you to swipe, chat, and date, every day!<br>- Dating the honest way: If you&#39;re looking for casual fun or friends, swipe Down.<br>- If you\u2019re looking for pure love, swipe Date.<br>- It&#39;s that easy - swipe &amp; date your way! Swipe, chat, date for free!<br>- Over 1/2 of all matches on DOWN APP meet &amp; date in real life.<br><br><b>How DOWN works:</b><br>- Sign in once with a Phone Number, Google, or Facebook.<br>- Swipe the singles &amp; couples nearby: We will only tell them you&#39;re interested if it&#39;s a match!<br>- If it&#39;s a match, we&#39;ll connect you so you can chat &amp; enjoy meetups!<br><br><b>Wanna meet people? Looking for pure love? Join millions of users worldwide to swipe, chat, &amp; date.</b>",
    "summary": "For casual & local meetups, friends, finding a bf or gf, & anything in between.",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 506649,
    "score": 4.111111,
    "ratings": 7993,
    "reviews": 869,
    "histogram": [
        887,
        417,
        713,
        869,
        5100
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $189.99 per item",
    "developer": "DOWN Dating App",
    "developerId": "6584629324210347053",
    "developerEmail": "ops@downapp.com",
    "developerWebsite": "https://www.downapp.com",
    "developerAddress": "Down App, Inc.\n8 The Green\nSuite # 12693\nDover, DE 19901",
    "privacyPolicy": "https://downapp.com/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/SbLJx0ELxnCf2DD2aQ6TXHnPHkima5lzXvSh5BoC3blico4wLBkZfe-qQfM9RpCiQw",
    "headerImage": "https://play-lh.googleusercontent.com/_PJRQYNmpC5Bbv3KZQAt-hOpenlcZC39gxLzwamuMZP6mDI6M6X71yU9sVtqauxJO7A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/yB5kOLa4A-CHa1z3-NnN0JDhiSEqkf5Tdq92_Q3LbcWG_LKsIvfauf2os07jY2WQbsQ",
        "https://play-lh.googleusercontent.com/pD2VLyHk1249UiiN1Z5fExDQBEerVfwyOWU0IKDIXOZAX7uylInwSaKO2mLNwocCeXyg",
        "https://play-lh.googleusercontent.com/_bPndXVX-lgaxYbtFIS1yCb0nmP6oGw2fJADYQe3yiEZ_auXWPItOn__u7J1bU8_amw",
        "https://play-lh.googleusercontent.com/94vxNO_NO8tv5d9BRNsrQVDIGcKy5u1sva2M_r_4r0lfJ4E68gloeGU13FCPobjIzRQ6",
        "https://play-lh.googleusercontent.com/T5oJQfJw8cH6W-pM1pWb05ZpIUqFgdZRUQcjmjkkbyHf0relLw5ndXxjwl2mC_u4Ock",
        "https://play-lh.googleusercontent.com/aMbe4zKmI4Jemkjg6wZf21yrCvNg0w8Ff4O2UxmFRk46e0BoqX1bRl9F90UqSuOxwLo",
        "https://play-lh.googleusercontent.com/Lv7I2juhu1LY7lPIqdeOLiyUCfgdk1Pm4URk-xJ9d7E0NfwSWRkLowmxN6iivi1yYa0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 2, 2021",
    "lastUpdatedOn": "Nov 6, 2024",
    "updated": 1730949860,
    "version": "54",
    "comments": [],
    "appId": "down.date.hookup.app",
    "url": "https://play.google.com/store/apps/details?id=down.date.hookup.app&hl=en&gl=us"
}