{
    "title": "Coffee Meets Bagel: Dating App",
    "description": "\u25ba <b>JOIN COFFEE MEETS BAGEL THE DATING APP</b>\r\n\u25ba <b>CMB IS A SAFE PLACE TO MEET ONLINE</b>\r\n\u25ba <b>CMB IS FOR SERIOUS DATERS</b>\r\n(*North America & Caribbean)\r\n\r\nReady to ditch the dating games and find something serious? You'll be in good company at Coffee Meets Bagel or CMB for short, where <b>91% of our daters are looking for a serious relationship</b>. That means less swiping, and more matching, chatting, and <b>*actual* dating on Coffee Meets Bagel</b>. \r\n\r\nCoffee Meets Bagel has made <b>over 150 million matches</b> and counting. Ready to meet yours? Here\u2019s how it\u2019s done \ud83d\udc47 \r\n\r\n\ud83d\udc9c  <b>CMB HAS A CURATED COMMUNITY</b>\r\nLooking for something casual? You\u2019re welcome to join, but you won\u2019t find that here. Coffee Meets Bagel asks upfront what you\u2019re looking for and only deliver daily batches of highly curated matches \u2013 that way, everyone is actually dating with intention.\r\n\r\n\ud83d\udc9c  <b>CMB HAS DETAILED PROFILES</b>\r\nDo they want kids? What\u2019s their relationship goal? Do they share your values? Every Coffee Meets Bagel date should be relationship-potential, so we\u2019ve made sure all the important details like education, interests, and family plans are upfront.\r\n\r\n\ud83d\udc9c  <b>CMB HAS CHATS MADE FOR MEETING</b>\r\nCoffee Meets Bagel will help you get the conversation rolling with Icebreakers, then help you move the conversation to real life with Seven-Day Chat Limit. Because small talk is cool and all, but face-to-face is the real deal.\r\n\r\n\ud83d\udc9c  <b>CMB HAS MORE WAYS TO MEET</b>\r\nStick to our daily picks in Suggested, explore more in Discover, or match instantly in Likes You. Wherever you choose to start on Coffee Meets Bagel, there\u2019s always someone worth meeting.\r\n\r\n------------------------------------------------------------------------------\r\n\r\n<b>CMB UPGRADES</b>\r\nCoffee Meets Bagel is a free dating app, but you can always subscribe for special features. Go for CMB Premium to maximize your matches, or get the VIP experience with CMB Platinum\u2019s exclusive upgrades to find love faster. Subscription benefits are subject to change, but here are the current perks you can enjoy: \r\n\r\n<b>CMB Premium</b>\r\n\u2714\ufe0f Unlimited Suggested: Unlock more profiles picked just for you in Suggested\r\n\r\n\u2714\ufe0f See all your likes: Why wait? Unblur all your likes and match instantly. \r\n\r\n\u2714\ufe0f 8 flowers a month: Stand out and get seen instantly with a virtual bouquet.\r\n\r\n\u2714\ufe0f Premium Preferences: Set relationship goals, smoking habits, and more in Suggested.\r\n\r\n\u2714\ufe0f 1 Boost a month: All eyes on you! Boost your profile for up to 5x more views.\r\n\r\n\u2714\ufe0f Unlimited Rewinds: Change your mind? Undo passes on suggested profiles in History.\r\n\r\n\u2714\ufe0f Activity Reports: See who\u2019s worth your time with activity and chat statistics.\r\n\r\n\u2714\ufe0f Read Receipts: Know when your messages are read, so you\u2019re never left in the dark.\r\n\r\n<b>CMB Platinum</b>\r\n\u2714\ufe0f Infinite Boost: Just like a regular Boost, but it\u2019s always on and always working for you. \r\n\r\n\u2714\ufe0f Priority likes: All the likes you send in Suggested get shown at the top of your potential match\u2019s list. \r\n\r\n\u2714\ufe0f Incognito mode: Want to control who sees you? Flip on Incognito mode to only get shown to people you've liked first. \r\n\r\n\u2714\ufe0f Plus everything in CMB Premium!\r\n------------------------------------------------------------------------------\r\n\r\n\u25ba <b>WHAT PEOPLE ARE SAYING</b>\r\n\r\n\ud83d\udcac \u201cOne of the best dating apps for relationships, according to real people who found success\u201d - Yahoo Finance\r\n\r\n\ud83d\udcac \u201cBest for setting up real dates\u201d - Mashable\r\n\r\n\ud83d\udcac \u201cBest app if you\u2019re trying to Marie Kondo your dating life.\u201d - Women\u2019s Health\r\n\r\n\ud83d\udcac \u201cScrew endless browsing: CMB focuses on in-depth profiles and only sends curated matches.\u201d - Mashable\r\n\r\n------------------------------------------------------------------------------\r\n\r\n\u25bc Any Suggestions? \r\nContact us with issues or features suggestions on \"https://coffeemeetsbagel.zendesk.com\"\r\n\r\n\u25bc Terms of Service: https://coffeemeetsbagel.com/tos\r\n\u25bc Privacy Policy:  https://coffeemeetsbagel.com/privacy-terms/",
    "descriptionHTML": "\u25ba <b>JOIN COFFEE MEETS BAGEL THE DATING APP</b><br>\u25ba <b>CMB IS A SAFE PLACE TO MEET ONLINE</b><br>\u25ba <b>CMB IS FOR SERIOUS DATERS</b><br>(*North America &amp; Caribbean)<br><br>Ready to ditch the dating games and find something serious? You&#39;ll be in good company at Coffee Meets Bagel or CMB for short, where <b>91% of our daters are looking for a serious relationship</b>. That means less swiping, and more matching, chatting, and <b>*actual* dating on Coffee Meets Bagel</b>. <br><br>Coffee Meets Bagel has made <b>over 150 million matches</b> and counting. Ready to meet yours? Here\u2019s how it\u2019s done \ud83d\udc47 <br><br>\ud83d\udc9c  <b>CMB HAS A CURATED COMMUNITY</b><br>Looking for something casual? You\u2019re welcome to join, but you won\u2019t find that here. Coffee Meets Bagel asks upfront what you\u2019re looking for and only deliver daily batches of highly curated matches \u2013 that way, everyone is actually dating with intention.<br><br>\ud83d\udc9c  <b>CMB HAS DETAILED PROFILES</b><br>Do they want kids? What\u2019s their relationship goal? Do they share your values? Every Coffee Meets Bagel date should be relationship-potential, so we\u2019ve made sure all the important details like education, interests, and family plans are upfront.<br><br>\ud83d\udc9c  <b>CMB HAS CHATS MADE FOR MEETING</b><br>Coffee Meets Bagel will help you get the conversation rolling with Icebreakers, then help you move the conversation to real life with Seven-Day Chat Limit. Because small talk is cool and all, but face-to-face is the real deal.<br><br>\ud83d\udc9c  <b>CMB HAS MORE WAYS TO MEET</b><br>Stick to our daily picks in Suggested, explore more in Discover, or match instantly in Likes You. Wherever you choose to start on Coffee Meets Bagel, there\u2019s always someone worth meeting.<br><br>------------------------------------------------------------------------------<br><br><b>CMB UPGRADES</b><br>Coffee Meets Bagel is a free dating app, but you can always subscribe for special features. Go for CMB Premium to maximize your matches, or get the VIP experience with CMB Platinum\u2019s exclusive upgrades to find love faster. Subscription benefits are subject to change, but here are the current perks you can enjoy: <br><br><b>CMB Premium</b><br>\u2714\ufe0f Unlimited Suggested: Unlock more profiles picked just for you in Suggested<br><br>\u2714\ufe0f See all your likes: Why wait? Unblur all your likes and match instantly. <br><br>\u2714\ufe0f 8 flowers a month: Stand out and get seen instantly with a virtual bouquet.<br><br>\u2714\ufe0f Premium Preferences: Set relationship goals, smoking habits, and more in Suggested.<br><br>\u2714\ufe0f 1 Boost a month: All eyes on you! Boost your profile for up to 5x more views.<br><br>\u2714\ufe0f Unlimited Rewinds: Change your mind? Undo passes on suggested profiles in History.<br><br>\u2714\ufe0f Activity Reports: See who\u2019s worth your time with activity and chat statistics.<br><br>\u2714\ufe0f Read Receipts: Know when your messages are read, so you\u2019re never left in the dark.<br><br><b>CMB Platinum</b><br>\u2714\ufe0f Infinite Boost: Just like a regular Boost, but it\u2019s always on and always working for you. <br><br>\u2714\ufe0f Priority likes: All the likes you send in Suggested get shown at the top of your potential match\u2019s list. <br><br>\u2714\ufe0f Incognito mode: Want to control who sees you? Flip on Incognito mode to only get shown to people you&#39;ve liked first. <br><br>\u2714\ufe0f Plus everything in CMB Premium!<br>------------------------------------------------------------------------------<br><br>\u25ba <b>WHAT PEOPLE ARE SAYING</b><br><br>\ud83d\udcac \u201cOne of the best dating apps for relationships, according to real people who found success\u201d - Yahoo Finance<br><br>\ud83d\udcac \u201cBest for setting up real dates\u201d - Mashable<br><br>\ud83d\udcac \u201cBest app if you\u2019re trying to Marie Kondo your dating life.\u201d - Women\u2019s Health<br><br>\ud83d\udcac \u201cScrew endless browsing: CMB focuses on in-depth profiles and only sends curated matches.\u201d - Mashable<br><br>------------------------------------------------------------------------------<br><br>\u25bc Any Suggestions? <br>Contact us with issues or features suggestions on &quot;https://coffeemeetsbagel.zendesk.com&quot;<br><br>\u25bc Terms of Service: https://coffeemeetsbagel.com/tos<br>\u25bc Privacy Policy:  https://coffeemeetsbagel.com/privacy-terms/",
    "summary": "The dating app for serious daters - Match, meet people & date with singles",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 276651,
    "score": 3.4,
    "ratings": 1896,
    "reviews": 784,
    "histogram": [
        523,
        121,
        132,
        300,
        814
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$19.99 - $199.99 per item",
    "developer": "Coffee Meets Bagel Inc.",
    "developerId": "Coffee+Meets+Bagel+Inc.",
    "developerEmail": "contact@coffeemeetsbagel.com",
    "developerWebsite": "https://www.coffeemeetsbagel.com",
    "developerAddress": null,
    "privacyPolicy": "https://coffeemeetsbagel.com/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/SazszDfE2uoUQdAE0JlVdXzOn9E3ulrXrB8MvoaiFBlTCm1Kd8qt5pL1yNQ1awHUTg",
    "headerImage": "https://play-lh.googleusercontent.com/GK1BMwH0UYKAmaTRHi4sB4ScLlV915yvEwcM81mF9jb8BMdDjj9LlPY-SOuM_u6H6zk",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Jng7nJZp-yfrZP0dUaPOH5TzUENmu1NSpwQRATEaCMgEVIGmKWuPa1pJHmUxlJ4Ncg",
        "https://play-lh.googleusercontent.com/BJf5zL0xmNZMw-jwfYOpW9ty7XuFvL2QTTe-Y6xEiJ9PAxSXNpjDSN5Uic20ey-37w",
        "https://play-lh.googleusercontent.com/uKQy2pS-y6SXeAXAylhQfepdVH6lfmKVp-GvMPzrvz_KaGrgi338IpQvxICIh3jNvw",
        "https://play-lh.googleusercontent.com/89v4vU9d2ZN72BLavKJovOqoNcIEgt67_jAIkrP8jF8T3fFHFb7_C0C6A2jPQDVgL6w",
        "https://play-lh.googleusercontent.com/aTumSIk-oyzIUo2WotehUoJWF63exUufYOE1jzEyPThaPwC6a6uFG5FXXZl_ZzK27d89",
        "https://play-lh.googleusercontent.com/KsyPkHSQH3BhremdPHemrgc5ThGGwUKA2WfTcHygX6t7IjpKDbFgBoYQJCcG5ISC1wFH"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 21, 2024",
    "lastUpdatedOn": "Nov 18, 2024",
    "updated": 1731964417,
    "version": "9.7.1",
    "comments": [],
    "appId": "io.cmbus.app",
    "url": "https://play.google.com/store/apps/details?id=io.cmbus.app&hl=en&gl=us"
}