{
    "title": "Cheelee: Short Videos for You",
    "description": "Vibe with Cheelee \u2014 a reimagined social network for short video fun\r\n\r\nExplore engaging videos from creators worldwide. Discover catchy challenges, inspiring DIY, funny stories, crazy memes, yummy recipes, and the latest dance moves. Cheelee embraces you with the best short video feed to boost your imagination!\r\n\r\nExpress your creativity by capturing and sharing special moments in a fun and interactive way. Relax, get inspiration, and watch videos made by our community of artists, influencers, and trendsetters. \r\n\r\nDiscover others' journeys, initiate conversations, create collaborative content, and find friends within the Cheelee community!\r\n\r\nKey Features:\r\n- Explore the Ecosystem\r\nMake the most of an impressive video library with AI-driven personalized recommendations. Also, check out our extra features that make Cheelee a special social network.\r\n\r\n- Upload and Publish\r\nShare your videos and see them going viral with our algorithms. We don't hide newbies. We let them shine!\r\n\r\n- Meet Diverse Creators\r\nMeet unique creators who make top videos in different genres, from edutainment to pure entertainment.\r\n\r\n- Set Trends\r\nParticipate in challenges, react to other videos, help trends grow, and find your own way to engage millions of users. Make them fall in love with your content.\r\n\r\n- Cheelee Community\r\nComment, collaborate, make friends, and attract followers from all over the world.\r\n\r\nUnveil your creativity, share your passions, and celebrate moments that resonate with Cheelee's community. Let our platform be your canvas to express, engage, and entertain. Cheelee is the place where creativity finds its home.",
    "descriptionHTML": "Vibe with Cheelee \u2014 a reimagined social network for short video fun<br><br>Explore engaging videos from creators worldwide. Discover catchy challenges, inspiring DIY, funny stories, crazy memes, yummy recipes, and the latest dance moves. Cheelee embraces you with the best short video feed to boost your imagination!<br><br>Express your creativity by capturing and sharing special moments in a fun and interactive way. Relax, get inspiration, and watch videos made by our community of artists, influencers, and trendsetters. <br><br>Discover others&#39; journeys, initiate conversations, create collaborative content, and find friends within the Cheelee community!<br><br>Key Features:<br>- Explore the Ecosystem<br>Make the most of an impressive video library with AI-driven personalized recommendations. Also, check out our extra features that make Cheelee a special social network.<br><br>- Upload and Publish<br>Share your videos and see them going viral with our algorithms. We don&#39;t hide newbies. We let them shine!<br><br>- Meet Diverse Creators<br>Meet unique creators who make top videos in different genres, from edutainment to pure entertainment.<br><br>- Set Trends<br>Participate in challenges, react to other videos, help trends grow, and find your own way to engage millions of users. Make them fall in love with your content.<br><br>- Cheelee Community<br>Comment, collaborate, make friends, and attract followers from all over the world.<br><br>Unveil your creativity, share your passions, and celebrate moments that resonate with Cheelee&#39;s community. Let our platform be your canvas to express, engage, and entertain. Cheelee is the place where creativity finds its home.",
    "summary": "Join the short video community. Ignite creativity, connect worldwide, have fun!",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 8082349,
    "score": 4.559322,
    "ratings": 197026,
    "reviews": 2859,
    "histogram": [
        14529,
        1668,
        5006,
        13571,
        162200
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $204.99 per item",
    "developer": "Cheelee",
    "developerId": "Cheelee",
    "developerEmail": "support@cheelee.io",
    "developerWebsite": "https://cheelee.io",
    "developerAddress": null,
    "privacyPolicy": "https://static.cheeleepay.com/files/en_US/privacy-policy.html",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/KJUfjKwHYmW5XpKv48Ig9t25SecpjJE4lqrgljB-2VzmP7OJTN5rka72OPXggALeG7Q",
    "headerImage": "https://play-lh.googleusercontent.com/iSnPtSWDGSUI-vFrSTGAnGOlyC0ZikEnKyoHt9nnXalY0E1jg8zdLtxzGajKBnKNVI0",
    "screenshots": [
        "https://play-lh.googleusercontent.com/4UVCTNSDhIiAmue56IOEhA2NWUTONbgdGvUqRE848NLcWp8DRURIAe73-ZpGc_07FVA",
        "https://play-lh.googleusercontent.com/Ds8B9NM7V4b3RxLja60dqSzpoLShIRlDWrFRCaUipIz4taCty5BxLCjJ9A0p9FZCFKlv",
        "https://play-lh.googleusercontent.com/6XHqMViIxurL6gjJORI09v5b8sHiR2CEI1kwRIGhbF-X9R4TmCM9En2zxKlySys1AEnV",
        "https://play-lh.googleusercontent.com/AlRXbBGLoMyQpKTYcy7Lw_mPlXuOd9ImjzLjPe-ZHNi80JYE5kY1wwjRWcAqhfMPwQ",
        "https://play-lh.googleusercontent.com/GVwuAiWRhESUTIaC8S8OtEpg-fCVHMn8bNBHMH1uL4m--Qpw8qA9hpBVBk6NmYGzaYI",
        "https://play-lh.googleusercontent.com/wJ-a1QGIwSC7bl6PBK-PRvmZC9EG_Va-ACpKTlhOTbrb4VXef1onPAw5T1uGgyrrQPw",
        "https://play-lh.googleusercontent.com/EbZzO4KBVN8Eoe02sjXgDx9OWMrmkQyeXj7hxBHAJaCv_qtrFNTH-GDPkf0Wl4YSzQ",
        "https://play-lh.googleusercontent.com/A7MBdqEkOgTVhQGXLQFgRe_oLQ3qPRvbUcu_qa9rIX96ZFzwzwmg84XIEBfF5K5Xn0U",
        "https://play-lh.googleusercontent.com/2ViXmb4dPtXho8pAViwQDFJUZ3-UFGJkt_FcNorLBubkw4H3sswC1hol6YTpd5i7QQ5P",
        "https://play-lh.googleusercontent.com/VSnOn0R0Hh5FltR8_7Y1zWq4tZyxN32haPKkLsU41nmg2o3WJFw-CG62dT54RVp_jA",
        "https://play-lh.googleusercontent.com/rNm_JchMlIH_3K65GEMANjK7VqOXqIw_l8Kq5egIQY9gknHXDKToulIQM5cqmbuDmWM",
        "https://play-lh.googleusercontent.com/QV2ec5XUcr6QKDLt7jVgZKu51FaXj_acxe9ARZcmASZqQdFEyY2QQSm3LKIxfdbHNQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 20, 2023",
    "lastUpdatedOn": "Nov 11, 2024",
    "updated": 1731335654,
    "version": "1.49.0",
    "comments": [],
    "appId": "io.cheelee.app",
    "url": "https://play.google.com/store/apps/details?id=io.cheelee.app&hl=en&gl=us"
}