{
    "title": "JBL Headphones",
    "description": "JBL Headphones app redefines your headphones experience. Through your mobile device, you can now conveniently control the headphone settings, smart ambient, noise cancelling and many more in your JBL Headphones app. Supported models are:\r\nJBL WAVE BUDS, WAVE BEAM, WAVE FLEX, VIBE BUDS, VIBE BEAM, VIBE FLEX\r\nJBL TUNE FLEX, TUNE ANC, TUNE 130NC TWS, TUNE  230NC TWS, TUNE BEAM, TUNE BUDS, WAVE BEAM 2, WAVE BUDS 2, WAVE FLEX 2, VIBE BEAM 2, VIBE BUDS 2, VIBE FLEX 2, \r\nJBL TUNE525BT, TUNE 520BT, TUNE 720BT, TUNE 670NC, TUNE 770NC\r\nJBL LIVE FREE 2, LIVE PRO 2, LIVE FREE NC+ TWS, LIVE PRO+ TWS, LIVE300 TWS, LIVE FLEX, LIVE BEAM 3, LIVE BUD 3, LIVE FLEX 3\r\nJBL LIVE 670NC, LIVE675NC, LIVE 770NC, LIVE 460NC, LIVE 660NC, LIVE 400BT, LIVE500BT,LIVE 650BTNC, LIVE 220BT,\r\nJBL CLUB PRO+ TWS, CLUB700BT, 950NC, ONE\r\nJBL TOUR PRO+ TWS, TOUR ONE, TOUR PRO 2, TOUR ONE M2, \r\nJBL SOUNDGEAR SENSE, SOUNDGEAR FRAMES\r\nJBL QUANTUM TWS, QUANTUM TWS AIR\r\nJBL ENDURANCE PEAK 3, ENDURANCE RACE, ENDURANCE RACE 2\r\nJBL REFLECT AERO, REFLECT FLOW PRO, REFLECT MINI NC, REFLECT AWARE\r\nUA PROJECT ROCK OVER-EAR TRAINING HEADPHONES\r\nJBL EVEREST ELITE100, 150NC, 300 and 750NC\r\nJBL X TOMORROWLAND\r\nJBL QUANTUM STREM WIRELSS \r\nJBL QUANTUM 360 WIRELESS, QUANTUM 360P and QUANTUM 360X\r\n\r\nOther features include:\r\n- EQ Settings:  The App provides predefined EQ presets and allows you to create or customize EQ settings as per their personal preferences. \r\n- Customize ANC: Select different noise cancelling level to enjoy the best sound on each occasion (available only on specific models)\r\n- Smart Audio & Video: improve your audio that is adjusted to what you are doing (available only on specific models)\r\n- Application Settings:  App setting include Voice Assistant, Smart Audio & Video, Touch gesture setting, Product help, Tips, FAQ, etc, subject to different models.\r\n- Gestures: allow you to change your button configuration based on your preference (available only on specific models)\r\n- Headphone battery indicator: Displays the headphone battery level so you can quickly see how much playtime is left.\r\n- Tips: Product tutorial will be found under Product help.\r\n- FAQ: Allows you to find quick answer when using our JBL APP.\r\n- Voice assistant setup: Allows you to select Google Assistant or Amazon Alexa as your voice assistant.",
    "descriptionHTML": "JBL Headphones app redefines your headphones experience. Through your mobile device, you can now conveniently control the headphone settings, smart ambient, noise cancelling and many more in your JBL Headphones app. Supported models are:<br>JBL WAVE BUDS, WAVE BEAM, WAVE FLEX, VIBE BUDS, VIBE BEAM, VIBE FLEX<br>JBL TUNE FLEX, TUNE ANC, TUNE 130NC TWS, TUNE  230NC TWS, TUNE BEAM, TUNE BUDS, WAVE BEAM 2, WAVE BUDS 2, WAVE FLEX 2, VIBE BEAM 2, VIBE BUDS 2, VIBE FLEX 2, <br>JBL TUNE525BT, TUNE 520BT, TUNE 720BT, TUNE 670NC, TUNE 770NC<br>JBL LIVE FREE 2, LIVE PRO 2, LIVE FREE NC+ TWS, LIVE PRO+ TWS, LIVE300 TWS, LIVE FLEX, LIVE BEAM 3, LIVE BUD 3, LIVE FLEX 3<br>JBL LIVE 670NC, LIVE675NC, LIVE 770NC, LIVE 460NC, LIVE 660NC, LIVE 400BT, LIVE500BT,LIVE 650BTNC, LIVE 220BT,<br>JBL CLUB PRO+ TWS, CLUB700BT, 950NC, ONE<br>JBL TOUR PRO+ TWS, TOUR ONE, TOUR PRO 2, TOUR ONE M2, <br>JBL SOUNDGEAR SENSE, SOUNDGEAR FRAMES<br>JBL QUANTUM TWS, QUANTUM TWS AIR<br>JBL ENDURANCE PEAK 3, ENDURANCE RACE, ENDURANCE RACE 2<br>JBL REFLECT AERO, REFLECT FLOW PRO, REFLECT MINI NC, REFLECT AWARE<br>UA PROJECT ROCK OVER-EAR TRAINING HEADPHONES<br>JBL EVEREST ELITE100, 150NC, 300 and 750NC<br>JBL X TOMORROWLAND<br>JBL QUANTUM STREM WIRELSS <br>JBL QUANTUM 360 WIRELESS, QUANTUM 360P and QUANTUM 360X<br><br>Other features include:<br>- EQ Settings:  The App provides predefined EQ presets and allows you to create or customize EQ settings as per their personal preferences. <br>- Customize ANC: Select different noise cancelling level to enjoy the best sound on each occasion (available only on specific models)<br>- Smart Audio &amp; Video: improve your audio that is adjusted to what you are doing (available only on specific models)<br>- Application Settings:  App setting include Voice Assistant, Smart Audio &amp; Video, Touch gesture setting, Product help, Tips, FAQ, etc, subject to different models.<br>- Gestures: allow you to change your button configuration based on your preference (available only on specific models)<br>- Headphone battery indicator: Displays the headphone battery level so you can quickly see how much playtime is left.<br>- Tips: Product tutorial will be found under Product help.<br>- FAQ: Allows you to find quick answer when using our JBL APP.<br>- Voice assistant setup: Allows you to select Google Assistant or Amazon Alexa as your voice assistant.",
    "summary": "Redefine your music experience with JBL Headphones app.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 21952631,
    "score": 4.5741596,
    "ratings": 356949,
    "reviews": 8092,
    "histogram": [
        15592,
        6595,
        11918,
        45963,
        276857
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Harman Consumer, Inc.",
    "developerId": "Harman+Consumer,+Inc.",
    "developerEmail": "appsupport@harman.com",
    "developerWebsite": "http://www.harman.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.harman.com/privacy-policy",
    "genre": "Music & Audio",
    "genreId": "MUSIC_AND_AUDIO",
    "categories": [
        {
            "name": "Music & Audio",
            "id": "MUSIC_AND_AUDIO"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/a1fWWFSA9o11aAV6mVbaQiVWLtHn8N1GcYInNp1MSgzJhZXNuxH01TcwMGSv2NE9Qg",
    "headerImage": "https://play-lh.googleusercontent.com/U8RHQYF-bwxUTcS-jXjFx3nYyTl5l490cvd6vP2FfQZt1lTlF4QXYDEp2KsOxg6iB5o",
    "screenshots": [
        "https://play-lh.googleusercontent.com/xOHCU4dXwU8yG3ovlczlaJm5SGEmb8665CuHXmcWdp8WwMxPjZ3FLNBmYPPoG2HPNw",
        "https://play-lh.googleusercontent.com/CyYWAbS1FUa-ogmnE3PjgBcVI8mepibsvOIH8cJfvz9b8S9J7HHZ6czUTD-0s0yi",
        "https://play-lh.googleusercontent.com/HjGuqJlWYY57wmy8qMxPV-Re7eZ9w8lQAA4El_1OESH5djxjLpMFMpkDN_-OTHyadw",
        "https://play-lh.googleusercontent.com/1KK6-jaGNPA2y_cHs-vml-oJBuImRzsEhkGBD6etROrFkVzIEhSlF1NXOq5pf8i7ff0",
        "https://play-lh.googleusercontent.com/xWvkXBM6vra4ZQ70JqdVMxEdagWwU9KNwzyy0uUdZoL242N-q7fBtRMgxpaSkbgDwRE",
        "https://play-lh.googleusercontent.com/KptvkQPe4fL8Z4hxgBd7jF52BXjmNAgceUlDCYj_D61r8uozEChBubPA9ZgZdslgDLxS",
        "https://play-lh.googleusercontent.com/Nw2EaYQrfvbVA-bJSV1haFUWIcBbU_3lQXFvG9OoipecZILAy_z6UY-ZU31WoqrmPUM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 6, 2015",
    "lastUpdatedOn": "Aug 27, 2024",
    "updated": 1724819284,
    "version": "5.23.12",
    "comments": [],
    "appId": "jbl.stc.com",
    "url": "https://play.google.com/store/apps/details?id=jbl.stc.com&hl=en&gl=us"
}