{
    "title": "MLB PRO SPIRIT",
    "description": "Play in the big leagues with this brand-new, officially licensed MLB game! \r\nExperience the thrill of fast-paced baseball action on your mobile device.\r\nBuild the ultimate dream team and compete against players from all over the world. Download now and get into the spirit of the game! \r\n\r\n\u25a0REAL PLAYERS \r\nReal players from every MLB team! \r\nUse Contracts to acquire your favorite players and showcase their skills on the field.\r\nCollect players and build up your roster to create an unstoppable dream team.\r\n\r\n\u25a0AUTHENTICITY \r\nAll MLB stadiums and uniforms have been carefully crafted to match the real deal!\r\nHear the crack of the bat and roar of the crowd to immerse yourself in the MLB experience.\r\n\r\n\u25a0JAM-PACKED WITH MODES\r\n- Season -\r\nMake it to the World Series in a 52-game MLB season against CPU teams.\r\nUse players in Season mode to level them up and increase their attributes!\r\n\r\n- Online -\r\nTest your skills on the diamond against other players in real time!\r\nSet the rules and play a casual game against friends in Custom Game.\r\nRanked Games match you with like-skilled players for a chance to rank up!\r\n\r\n- Events -\r\nLog in to play limited-time events and earn awesome rewards!\r\n\r\n\u25a0IMPORTANT\r\nAn internet connection is required to play this app.\r\nWe strongly recommend playing with a stable connection to ensure you get the most out of the game.\r\nA download of approximately 2GB is required after starting the game and finishing the tutorial.\r\n\r\n\u25a0SYSTEM REQUIREMENTS\r\nAndroid 10.0 and up\r\n\r\n*This app may not function properly even if your device meets the system requirements due to device specifications, app usage, or other factors.\r\n*You may experience issues while playing if your device is not capable of handling this app's 3D graphics.\r\n*This app may not function properly if you are using a device that has two-screen display.\r\n\r\nMajor League Baseball trademarks and copyrights are used with permission of Major League Baseball. Visit MLB.com.  Officially Licensed Product of MLB Players, Inc. MLBPA trademarks, copyrighted works and other intellectual property rights are owned and/or held by MLBPA and may not be used without the written consent of MLBPA or MLB Players, Inc. Visit www.MLBPLAYERS.com the Players Choice on the web.  \"Major League Baseball\"(or \"Major League\") is a registered trademark owned by Major League Baseball Properties, Inc., used under license.  Getty Images  All other copyrights or trademarks are the property of their respective owners and are used under license.  \u00a92024 Konami Digital Entertainment",
    "descriptionHTML": "Play in the big leagues with this brand-new, officially licensed MLB game! <br>Experience the thrill of fast-paced baseball action on your mobile device.<br>Build the ultimate dream team and compete against players from all over the world. Download now and get into the spirit of the game! <br><br>\u25a0REAL PLAYERS <br>Real players from every MLB team! <br>Use Contracts to acquire your favorite players and showcase their skills on the field.<br>Collect players and build up your roster to create an unstoppable dream team.<br><br>\u25a0AUTHENTICITY <br>All MLB stadiums and uniforms have been carefully crafted to match the real deal!<br>Hear the crack of the bat and roar of the crowd to immerse yourself in the MLB experience.<br><br>\u25a0JAM-PACKED WITH MODES<br>- Season -<br>Make it to the World Series in a 52-game MLB season against CPU teams.<br>Use players in Season mode to level them up and increase their attributes!<br><br>- Online -<br>Test your skills on the diamond against other players in real time!<br>Set the rules and play a casual game against friends in Custom Game.<br>Ranked Games match you with like-skilled players for a chance to rank up!<br><br>- Events -<br>Log in to play limited-time events and earn awesome rewards!<br><br>\u25a0IMPORTANT<br>An internet connection is required to play this app.<br>We strongly recommend playing with a stable connection to ensure you get the most out of the game.<br>A download of approximately 2GB is required after starting the game and finishing the tutorial.<br><br>\u25a0SYSTEM REQUIREMENTS<br>Android 10.0 and up<br><br>*This app may not function properly even if your device meets the system requirements due to device specifications, app usage, or other factors.<br>*You may experience issues while playing if your device is not capable of handling this app&#39;s 3D graphics.<br>*This app may not function properly if you are using a device that has two-screen display.<br><br>Major League Baseball trademarks and copyrights are used with permission of Major League Baseball. Visit MLB.com.  Officially Licensed Product of MLB Players, Inc. MLBPA trademarks, copyrighted works and other intellectual property rights are owned and/or held by MLBPA and may not be used without the written consent of MLBPA or MLB Players, Inc. Visit www.MLBPLAYERS.com the Players Choice on the web.  &quot;Major League Baseball&quot;(or &quot;Major League&quot;) is a registered trademark owned by Major League Baseball Properties, Inc., used under license.  Getty Images  All other copyrights or trademarks are the property of their respective owners and are used under license.  \u00a92024 Konami Digital Entertainment",
    "summary": "Play real baseball, real fast in this officially licensed MLB game!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 337954,
    "score": 3.3465347,
    "ratings": 1724,
    "reviews": 151,
    "histogram": [
        592,
        68,
        34,
        183,
        831
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $64.99 per item",
    "developer": "KONAMI",
    "developerId": "KONAMI",
    "developerEmail": "ask-konami@faq.konami.com",
    "developerWebsite": "http://www.konami.com/games/mps/us/en-us/",
    "developerAddress": "\u6771\u4eac\u90fd\u4e2d\u592e\u533a\u9280\u5ea7\u4e00\u4e01\u76ee11\u756a1\u53f7",
    "privacyPolicy": "https://legal.konami.com/games/privacy/",
    "genre": "Sports",
    "genreId": "GAME_SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "GAME_SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/xEJgh7pdytUERn-rKgM_mX9ZKkeDYAFrDjqyxw9GfJdDaCbg3WrUypr616oUJeCTxqw",
    "headerImage": "https://play-lh.googleusercontent.com/Bk8_8d4xg-qRGrFRTPLw6KrN0lcWf6JWChGjmOd8KC_YyeLReW8lpBr6nXUuAxMcd3hc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/QvbT-YqdNPfpl53dyturjRRvQzrJ1gPFakb6lQfWo8_VFLOvJHf1EwED-on-9hPYzZY",
        "https://play-lh.googleusercontent.com/c_5uPS2mAFtJAdYi0ndC13NbxsYyjW6sP1XRJg_jsiOcMdcjBqd4QlPB4E4uMZUbbA",
        "https://play-lh.googleusercontent.com/K0WnbAxoLRvCbhy50k_j2-onjkEdhCeokjippWaMncs9qRPydkr_wjtjbHVvv6gt_Q",
        "https://play-lh.googleusercontent.com/9gdmCM69qwOoqE7zyMfAolqMBthx19lGOHCDEWSSGYnvxDfjmGTLFoK3GII1EhdbkA",
        "https://play-lh.googleusercontent.com/WUf8cb0GZe7AeSHLVZ_28OixMW5yrwbd8LGUF5j9QG-5I8u5898tVp8BpoLvWDK25eVv",
        "https://play-lh.googleusercontent.com/BScMLaEP2kL6U3exQe4fj9dNNj8cZUGPjXgOB15Rsfk04NE09PIEIqAlFrPZUqaF5MY",
        "https://play-lh.googleusercontent.com/8_f9tQMmwoTlt-_HYdizC7dNlzzZAG3QElb-4xYMPEDEhtl2Axp0DEfc9EzOUsQg8g",
        "https://play-lh.googleusercontent.com/K0z5OZUAayMyfCERtvIJiER3MbAvYUhVlqFtQeOJ615Dw-zTjg7qBgMJe0_e7K78CfQ",
        "https://play-lh.googleusercontent.com/_0x8unDmqDGWe5dUXzTZ7gftQ8LNenX4lNQ6vlQVOSIbTKzCwFjzJXAtACTCXFDjRVw",
        "https://play-lh.googleusercontent.com/BH2aJBGhjN3nZySD8BQowK8MvVrb7J-csZAh5KcEoNVCnp2peoqqqTQykMp9aD9B0NA",
        "https://play-lh.googleusercontent.com/kZ0Jv-cTWlv1kKZyf6OyzgWLmkf49jcDGWjwbHDNi4byVXVsrzUC1vaeWmeTpmLkNlc",
        "https://play-lh.googleusercontent.com/7_GwlKJPbkFHXwTSFWNkJjHMP89EGdJs5C8zxToVeoyTaCOUyEqKFj-HaWSES6mRzw",
        "https://play-lh.googleusercontent.com/cFvEIFRdo5AyoD7IBkKpDo03R-zkzd44iaFKBWVOJmwnePBm81cmN8gsR7QtoOwG040",
        "https://play-lh.googleusercontent.com/rh9hhXirK9varKAFJNy3IqR4jRUF9A3Jwf2WIYmd_Ggqlj8I2ADjyGT1_Oi4ika3MA",
        "https://play-lh.googleusercontent.com/Y4vR5Hqrv6kQzSplpTx1nWx02I7YRx37nBmwZWAKWh3vwD1puSQw_3StN-67YODzjrg"
    ],
    "video": "https://www.youtube.com/embed/3NfQdEYS5HU?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/Bk8_8d4xg-qRGrFRTPLw6KrN0lcWf6JWChGjmOd8KC_YyeLReW8lpBr6nXUuAxMcd3hc",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Oct 22, 2024",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729642555,
    "version": "1.0.0",
    "comments": [],
    "appId": "jp.konami.mps",
    "url": "https://play.google.com/store/apps/details?id=jp.konami.mps&hl=en&gl=us"
}