{
    "title": "Spam Call Blocker for Android",
    "description": "Spam Call Blocker is an effective way to end phone spams for good! It eliminates up to 98% of robocalls, spam calls, scam calls, no caller ID calls, telemarketers automatically. Spam Call Blocker is the only call filter you'll ever need to block spam calls & scam calls! The database of spam call blocker analyzes calls instantly and shows you caller ID spam alerts.\r\n\r\n*TIRED OF RECEIVING SPAM CALLS? \r\nBillions of spam calls hit people's cell phones every week. If you are tired of spam calls and unwanted calls, this spam call blocker can help you get rid of spam calls forever.\r\n\r\n*WHY CHOOSE SPAM CALL BLOCKER FOR ANDROID?\r\n\u2022 Automatically block robocalls, spam calls, scam calls, no caller ID calls, telemarketers, unwanted calls\r\n\u2022 Identify fraud, spam, and scam before you even pick up\r\n\u2022 Control who can call you - add any unwanted callers to your block list\r\n\u2022 Get revenge on robocallers with our automated response service\r\n\r\n*HOW TO BLOCK SPAM CALLS?\r\nAny robocall, spam call, telemarketer, unwanted caller, or any phone call with an unknown caller ID will be marked as spam with the help of our number blocking system. Each number that contacts you is run through our call filter's database, and if there's a match, our spam protection engine automatically blocks the spam calls.\r\nCreate a personalized blacklist of phone numbers and caller ID names that you simply don't want to hear from. Once a number is added to your block list, it will be prevented from reaching you. Manage your personal blacklist now. \r\n\r\n*REVERSE SEARCH PHONE NUMBERS\r\nLook up the phone number of an unsaved contact and determine if it is likely associated with a telemarketer. With our powerful reverse search feature, you can effortlessly identify potential telemarketers and make informed decisions on whether to answer the call.\r\n\r\n*SCAM CALL BLOCKING\r\nYou'll get full caller ID scam alerts. Stop scammers in action after a single ring. Stop scammers in their tracks after a single ring and safeguard your personal and financial security. Rest easy knowing that our app is dedicated to intercepting and blocking scam calls, ensuring the protection of your valuable assets and peace of mind.\r\n\r\n*GET REVENGE ON ROBOCALLERS\r\nAfter flagging a caller as spam, Spam Call Blocker sends the spam caller to \"Answer Bots,\" a feature that plays pre-recorded messages to trick telemarketers and other unsolicited callers into thinking they're speaking to a real person.\r\n\r\n*SAFE CALL FILTER\r\nEverything you do stays on your phone, and your phone only - your data is never shared with any 3rd parties. All reports are fully anonymous. With our safe call filter, you can enjoy peace of mind knowing that your privacy and confidentiality are always respected.\r\n\r\nIf you have any questions or suggestions, please feel free to contact us at: info@robocallblock.com\r\nPrivacy Policy: http://www.robocallblock.com/privacy\r\nTerms of Service: http://www.robocallblock.com/terms\r\n\r\nSpam Call Blocker for android is the best way to block spam calls! Download spam call filter today and experience a spam-free life.",
    "descriptionHTML": "Spam Call Blocker is an effective way to end phone spams for good! It eliminates up to 98% of robocalls, spam calls, scam calls, no caller ID calls, telemarketers automatically. Spam Call Blocker is the only call filter you&#39;ll ever need to block spam calls &amp; scam calls! The database of spam call blocker analyzes calls instantly and shows you caller ID spam alerts.<br><br>*TIRED OF RECEIVING SPAM CALLS? <br>Billions of spam calls hit people&#39;s cell phones every week. If you are tired of spam calls and unwanted calls, this spam call blocker can help you get rid of spam calls forever.<br><br>*WHY CHOOSE SPAM CALL BLOCKER FOR ANDROID?<br>\u2022 Automatically block robocalls, spam calls, scam calls, no caller ID calls, telemarketers, unwanted calls<br>\u2022 Identify fraud, spam, and scam before you even pick up<br>\u2022 Control who can call you - add any unwanted callers to your block list<br>\u2022 Get revenge on robocallers with our automated response service<br><br>*HOW TO BLOCK SPAM CALLS?<br>Any robocall, spam call, telemarketer, unwanted caller, or any phone call with an unknown caller ID will be marked as spam with the help of our number blocking system. Each number that contacts you is run through our call filter&#39;s database, and if there&#39;s a match, our spam protection engine automatically blocks the spam calls.<br>Create a personalized blacklist of phone numbers and caller ID names that you simply don&#39;t want to hear from. Once a number is added to your block list, it will be prevented from reaching you. Manage your personal blacklist now. <br><br>*REVERSE SEARCH PHONE NUMBERS<br>Look up the phone number of an unsaved contact and determine if it is likely associated with a telemarketer. With our powerful reverse search feature, you can effortlessly identify potential telemarketers and make informed decisions on whether to answer the call.<br><br>*SCAM CALL BLOCKING<br>You&#39;ll get full caller ID scam alerts. Stop scammers in action after a single ring. Stop scammers in their tracks after a single ring and safeguard your personal and financial security. Rest easy knowing that our app is dedicated to intercepting and blocking scam calls, ensuring the protection of your valuable assets and peace of mind.<br><br>*GET REVENGE ON ROBOCALLERS<br>After flagging a caller as spam, Spam Call Blocker sends the spam caller to &quot;Answer Bots,&quot; a feature that plays pre-recorded messages to trick telemarketers and other unsolicited callers into thinking they&#39;re speaking to a real person.<br><br>*SAFE CALL FILTER<br>Everything you do stays on your phone, and your phone only - your data is never shared with any 3rd parties. All reports are fully anonymous. With our safe call filter, you can enjoy peace of mind knowing that your privacy and confidentiality are always respected.<br><br>If you have any questions or suggestions, please feel free to contact us at: info@robocallblock.com<br>Privacy Policy: http://www.robocallblock.com/privacy<br>Terms of Service: http://www.robocallblock.com/terms<br><br>Spam Call Blocker for android is the best way to block spam calls! Download spam call filter today and experience a spam-free life.",
    "summary": "A fast and effective way to stop all spam & scam calls for Android devices.",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 791564,
    "score": 4.40484,
    "ratings": 15281,
    "reviews": 2638,
    "histogram": [
        858,
        378,
        1039,
        2438,
        10562
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $59.99 per item",
    "developer": "Dingtone Communications Ltd",
    "developerId": "Dingtone+Communications+Ltd",
    "developerEmail": "info@robocallblock.com",
    "developerWebsite": "https://www.robocallblock.com",
    "developerAddress": "Room 2200, Future Plaza",
    "privacyPolicy": "http://www.robocallblock.com/privacy",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/8uy5EWH8gdCVGfGxdXcrk6EGSQvN2BH-16HjYCfk9uWCvCugVihaQrYgH5kTsnwsFA",
    "headerImage": "https://play-lh.googleusercontent.com/bEXnPp5t2eeVHdzcLaXVOaIJByZ-ggg8X2Lk_VtEQoM12dRQKZvSvZrzW-s_npCbTr4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/tFhTzSuGwq3XMWh5tN1GBj3023fUQsIybwvK6PqBJgM1gNU77tiBjtTkKWl4DI3rPc35",
        "https://play-lh.googleusercontent.com/-0HqDkIRpBSi36ictwjD4QcSU_6gs5KsVHfrFUlOXWaLTOEmAk59Y7a0ZAkzs9-m3C0",
        "https://play-lh.googleusercontent.com/of_whwXs8mLrcMHBp0SMuAsPSuKnbi05ycYOWrvoNP58VFDOoD8MBZzAUyduSxniEA",
        "https://play-lh.googleusercontent.com/Fh8r1wR-l4ykl_FHjm-mTD0tpOwqjz-K5NkYDuACqYJMjEjZvFbwy9EM-Hi6TfiygA",
        "https://play-lh.googleusercontent.com/BzE7IdkH_kciNIXV6UcFYpQxl9CmKX-88MAYmSrlQBr_MU1cxFaziwTFJi63HDT8lmHK",
        "https://play-lh.googleusercontent.com/WM94slIlC5hmlGvrbk6V05VVZxERgOLRuNJZDg9uPZt_uv3ikcI56Ilr3n4Y8pQ6rQ"
    ],
    "video": "https://www.youtube.com/embed/AB6PK9-n9WQ?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/bEXnPp5t2eeVHdzcLaXVOaIJByZ-ggg8X2Lk_VtEQoM12dRQKZvSvZrzW-s_npCbTr4",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 16, 2021",
    "lastUpdatedOn": "Sep 27, 2024",
    "updated": 1727436051,
    "version": "3.8.2",
    "comments": [],
    "appId": "me.spam.robo.call.blocker.call.filter.app",
    "url": "https://play.google.com/store/apps/details?id=me.spam.robo.call.blocker.call.filter.app&hl=en&gl=us"
}