{
    "title": "Yoga For Beginners by Yoga-Go",
    "description": "Yoga For Beginners by Yoga-Go is a yoga workout app suitable for beginners and more advanced yogis. Discover 600+ workouts for any needs: Somatic Yoga Workout, Chair Yoga for Seniors, 28-day Wall Pilates Challenge, Tai Chi, and more. Learn and practice yoga poses from over 500+ asanas. \r\n\r\nWITH YOGA-GO YOU\u2019LL GET:\r\n\u2022 Personalized weight loss workouts at home with no equipment needed\r\n\u2022 Wall pilates and somatic yoga exercises based on your abilities\r\n\u2022 Quick 7-minut\u0435 yoga workouts for both beginners and advanced yogis\r\n\u2022 600+ yoga-inspired workouts from gentle Somatic Yoga and Chair Yoga Stretching to the 28-day Wall Pilates challenge\r\n\u2022 Easy-to-follow exercises for weight loss, flexibility, stretching, relaxation\r\n\u2022 All-in-one yoga studio right in your pocket\r\n \r\nADAPTED TO YOUR FITNESS NEEDS\r\nThe app offers different daily yoga workouts according to your health goals. Even the busiest person can find 7-15 minutes a day to complete one of the following workouts: Chair Yoga, Sofa Morning Yoga, Lazy Yoga for Beginners, etc. Up for a longer training session? No problem! Switch to a 30-minute Wall Pilates workout or melt away with meditation and breathing exercises. \r\n\r\nWALL PILATES WORKOUTS\r\nExperience the power of home pilates. This workout series is designed to help you strengthen your core, improve flexibility, and enhance overall fitness. The wall serves as a supportive tool, enabling you to perform a variety of exercises with precision and control. A home pilates routine is perfect for all fitness levels, offering modifications to suit your needs.\r\n\r\nCHAIR YOGA WORKOUTS\r\nWith chair yoga, you can achieve your weight loss goals without the stress of a high-intensity workout. This series offers a unique blend of gentle, yet effective yoga poses that can be done from the comfort of your chair. It's perfect for those new to yoga or anyone seeking low-impact exercises.  \r\n\r\nSOMATIC YOGA PLAN\r\nEmbark on a transformative journey with our joyful and brief somatic exercises series. Elevate your well-being, conquer stress, and say goodbye to back pain as you unlock the path to wellness with empowering somatic yoga poses. \r\n\r\nTAI CHI FOR BEGINNERS\r\nExplore our brand-new Tai Chi series featuring gentle, repetitive movements that are easy to learn. Boost your energy with the 28-Day Tai Chi Series.\r\n \r\nA PERSONALIZED WORKOUT PLANNER\r\nAccess yoga workouts that are focused on figure sculpting, mind and body health, stretching, or flexibility. Work out anytime, set your workout days and rest days. \r\n\r\nA WORKOUT BUILDER TOOL\r\nGet a customized daily yoga training program that takes your goals, problem areas, fitness level, and more into consideration. Choose between different training plans, focus on a problem body area, and train with a purpose.\r\n\r\nYoga is more than just stretching exercises. It's also about making your body stronger and healthier. As well as a 7-minute yoga workout (Morning Yoga for Beginners), introduce your body to more intensive Wall Pilates challenges aimed at building endurance and losing weight, as well as Chair Yoga and somatic exercises aimed at improving flexibility and toning up the whole body. \r\n\r\nSUBSCRIPTION INFO\r\nYou can download the app for free. Further use requires a subscription. \r\nIn addition to the purchased subscription, we may offer you add-on items (e.g. health guides) for an additional fee, either as a one-off or recurring payment. At our discretion, we may decide to offer you a free trial per the terms displayed in the app.\r\n\r\nLove Yoga-Go? Leave us your comments! Questions? Feedback? Email us at support@yoga-go.fit\r\nPrivacy Policy: https://legal.yoga-go.io/page/privacy-policy\r\nTerms of Use: https://legal.yoga-go.io/page/terms-of-use \r\n\r\nStart your daily workouts with Yoga-Go! Explore new poses of yoga for beginners, train with a 28-day Wall Pilates challenge, try stretching with Chair Yoga for Seniors, melt away with Tai Chi or Somatic Yoga Workout, and build one more good habit into your life.",
    "descriptionHTML": "Yoga For Beginners by Yoga-Go is a yoga workout app suitable for beginners and more advanced yogis. Discover 600+ workouts for any needs: Somatic Yoga Workout, Chair Yoga for Seniors, 28-day Wall Pilates Challenge, Tai Chi, and more. Learn and practice yoga poses from over 500+ asanas. <br><br>WITH YOGA-GO YOU\u2019LL GET:<br>\u2022 Personalized weight loss workouts at home with no equipment needed<br>\u2022 Wall pilates and somatic yoga exercises based on your abilities<br>\u2022 Quick 7-minut\u0435 yoga workouts for both beginners and advanced yogis<br>\u2022 600+ yoga-inspired workouts from gentle Somatic Yoga and Chair Yoga Stretching to the 28-day Wall Pilates challenge<br>\u2022 Easy-to-follow exercises for weight loss, flexibility, stretching, relaxation<br>\u2022 All-in-one yoga studio right in your pocket<br> <br>ADAPTED TO YOUR FITNESS NEEDS<br>The app offers different daily yoga workouts according to your health goals. Even the busiest person can find 7-15 minutes a day to complete one of the following workouts: Chair Yoga, Sofa Morning Yoga, Lazy Yoga for Beginners, etc. Up for a longer training session? No problem! Switch to a 30-minute Wall Pilates workout or melt away with meditation and breathing exercises. <br><br>WALL PILATES WORKOUTS<br>Experience the power of home pilates. This workout series is designed to help you strengthen your core, improve flexibility, and enhance overall fitness. The wall serves as a supportive tool, enabling you to perform a variety of exercises with precision and control. A home pilates routine is perfect for all fitness levels, offering modifications to suit your needs.<br><br>CHAIR YOGA WORKOUTS<br>With chair yoga, you can achieve your weight loss goals without the stress of a high-intensity workout. This series offers a unique blend of gentle, yet effective yoga poses that can be done from the comfort of your chair. It&#39;s perfect for those new to yoga or anyone seeking low-impact exercises.  <br><br>SOMATIC YOGA PLAN<br>Embark on a transformative journey with our joyful and brief somatic exercises series. Elevate your well-being, conquer stress, and say goodbye to back pain as you unlock the path to wellness with empowering somatic yoga poses. <br><br>TAI CHI FOR BEGINNERS<br>Explore our brand-new Tai Chi series featuring gentle, repetitive movements that are easy to learn. Boost your energy with the 28-Day Tai Chi Series.<br> <br>A PERSONALIZED WORKOUT PLANNER<br>Access yoga workouts that are focused on figure sculpting, mind and body health, stretching, or flexibility. Work out anytime, set your workout days and rest days. <br><br>A WORKOUT BUILDER TOOL<br>Get a customized daily yoga training program that takes your goals, problem areas, fitness level, and more into consideration. Choose between different training plans, focus on a problem body area, and train with a purpose.<br><br>Yoga is more than just stretching exercises. It&#39;s also about making your body stronger and healthier. As well as a 7-minute yoga workout (Morning Yoga for Beginners), introduce your body to more intensive Wall Pilates challenges aimed at building endurance and losing weight, as well as Chair Yoga and somatic exercises aimed at improving flexibility and toning up the whole body. <br><br>SUBSCRIPTION INFO<br>You can download the app for free. Further use requires a subscription. <br>In addition to the purchased subscription, we may offer you add-on items (e.g. health guides) for an additional fee, either as a one-off or recurring payment. At our discretion, we may decide to offer you a free trial per the terms displayed in the app.<br><br>Love Yoga-Go? Leave us your comments! Questions? Feedback? Email us at support@yoga-go.fit<br>Privacy Policy: https://legal.yoga-go.io/page/privacy-policy<br>Terms of Use: https://legal.yoga-go.io/page/terms-of-use <br><br>Start your daily workouts with Yoga-Go! Explore new poses of yoga for beginners, train with a 28-day Wall Pilates challenge, try stretching with Chair Yoga for Seniors, melt away with Tai Chi or Somatic Yoga Workout, and build one more good habit into your life.",
    "summary": "Pilates and yoga workout. Wall pilates, somatic yoga, chair yoga for seniors",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 25703742,
    "score": 4.397885,
    "ratings": 113548,
    "reviews": 4368,
    "histogram": [
        12588,
        1404,
        1404,
        10970,
        87166
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $139.99 per item",
    "developer": "WELLTECH APPS LIMITED",
    "developerId": "5137904782958257230",
    "developerEmail": "support-a@yoga-go.fit",
    "developerWebsite": "http://yoga-go.fit/",
    "developerAddress": "13, Karaiskaki, 3032, Limassol, Cyprus",
    "privacyPolicy": "https://legal.yoga-go.io/page/privacy-policy",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Dugiv35tKFTjgl0-VaLx5_nLudVU-gdqJka3HEa_2d1fjrRT5MvGHWHvSmRLqIDp8w",
    "headerImage": "https://play-lh.googleusercontent.com/XRxr6apyDgUKNPduxDFLFpTacOaGkQZTvpZzbrRyHBIZNA0DGif2QSqYKpZSauR1VWc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/elTU1ZBqj243LD1lFyHIW46IM3TWymZcfmEyfIAZNotCGx3PLQK5kQ6afU7xhh4tUyVM",
        "https://play-lh.googleusercontent.com/uHSDUDC5wA1oRWqE4Z4af6e-cyiz9gfoCpr0JOSyjnE8sYC6WDt3Wk96EyaSnWlxZyo5",
        "https://play-lh.googleusercontent.com/drLAV8v1etkFUYO5oKoHKQY84r34hNFHygUO9N6uPH3JzupArjcwoe_mWHBJ6XZjGnw",
        "https://play-lh.googleusercontent.com/lw1M3LY4puFtacxukuK3tYVd7gLHi4r2U7F_q6MCLbkbiLpob2gOsIn5i5UeXohv9ho",
        "https://play-lh.googleusercontent.com/62J7xi2V7ukdvsAWO-EW7pklzyEWdHDTFFVB8aGqPWpVKKnWK-EJysNsLmbJslkH6S2X",
        "https://play-lh.googleusercontent.com/hu-i8r2AM7i8tXdDT_CF8e3sxxpa8XkPu34_VSRXGS-rfDgbldXbNfJDNAZv9-ipww"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 6, 2019",
    "lastUpdatedOn": "Nov 7, 2024",
    "updated": 1730993146,
    "version": "10.33.0",
    "comments": [],
    "appId": "net.beginners.weight.loss.workout.women.yoga.go",
    "url": "https://play.google.com/store/apps/details?id=net.beginners.weight.loss.workout.women.yoga.go&hl=en&gl=us"
}