{
    "title": "ActiVote: Voting & Politics",
    "description": "<b>CONFIDENTLY VOTING IN ELECTIONS</b>\r\nActiVote is a safe environment for voter research. It empowers all Americans to be active in our democracy by helping voters create the habit of voting. No ads and we do not share your personal data.\r\n\r\nAn exciting tool that takes the guesswork out of voting and allows you to prepare to participate in elections at the local, state and federal level! You can see all your upcoming elections and candidates, participate in polls, and even figure out who to vote for by determining who shares your beliefs.\r\n\r\nReview bills and acts making their way through your state legislature and Congress, with direct links to your state legislature's official website as well as www.congress.gov for US government congressional bills.\r\n\r\nCheck out all the officials that represent you, all the way from the President down to your local school board.\r\n\r\nAnswer Daily Policy Questions, to see how the country feels about key issues. Find your place on the political spectrum and compare your position with your representatives and those running to represent you in the future.\r\n\r\nParticipate in ActiVote's polls on bills, officials and elections.\r\n\r\n<b>ACTIVOTE'S DATA</b>\r\nNote: This is <b>NOT</b> an official ballot and you <b>CANNOT</b> vote using this app. ActiVote is not a government agency, but a civic tech platform that collects and organizes politics, elections and legislative information from official federal, state and local sources.\r\n\r\nActiVote's legislative data comes from LegiScan who sources direct from government sites. Primarily https://www.congress.gov/.\r\n\r\nActiVote's elected representative data comes from the GoogleCivic API as well as VoteSmart. For reference you can find information here:\r\nhttps://developers.google.com/civic-information\r\nhttps://justfacts.votesmart.org/about/\r\n\r\nActiVote's election data comes from multiple nonprofit vendors who source their data direct from official government election sources. You can find the election officials where information is sourced here:\r\nhttps://www.usa.gov/state-election-office\r\n\r\nFor a full list of our data suppliers and links to the source content, explore the \"Our Partners\" menu option.\r\n\r\nAre you ready to make a difference by voting? ActiVote empowers you to engage in the democratic process confidently, ensuring your voice is heard.\r\n\r\nWe love to hear from you, contact us at info@activote.net\r\n\r\n<b>DOWNLOAD ACTIVOTE TODAY.</b>",
    "descriptionHTML": "<b>CONFIDENTLY VOTING IN ELECTIONS</b><br>ActiVote is a safe environment for voter research. It empowers all Americans to be active in our democracy by helping voters create the habit of voting. No ads and we do not share your personal data.<br><br>An exciting tool that takes the guesswork out of voting and allows you to prepare to participate in elections at the local, state and federal level! You can see all your upcoming elections and candidates, participate in polls, and even figure out who to vote for by determining who shares your beliefs.<br><br>Review bills and acts making their way through your state legislature and Congress, with direct links to your state legislature&#39;s official website as well as www.congress.gov for US government congressional bills.<br><br>Check out all the officials that represent you, all the way from the President down to your local school board.<br><br>Answer Daily Policy Questions, to see how the country feels about key issues. Find your place on the political spectrum and compare your position with your representatives and those running to represent you in the future.<br><br>Participate in ActiVote&#39;s polls on bills, officials and elections.<br><br><b>ACTIVOTE&#39;S DATA</b><br>Note: This is <b>NOT</b> an official ballot and you <b>CANNOT</b> vote using this app. ActiVote is not a government agency, but a civic tech platform that collects and organizes politics, elections and legislative information from official federal, state and local sources.<br><br>ActiVote&#39;s legislative data comes from LegiScan who sources direct from government sites. Primarily https://www.congress.gov/.<br><br>ActiVote&#39;s elected representative data comes from the GoogleCivic API as well as VoteSmart. For reference you can find information here:<br>https://developers.google.com/civic-information<br>https://justfacts.votesmart.org/about/<br><br>ActiVote&#39;s election data comes from multiple nonprofit vendors who source their data direct from official government election sources. You can find the election officials where information is sourced here:<br>https://www.usa.gov/state-election-office<br><br>For a full list of our data suppliers and links to the source content, explore the &quot;Our Partners&quot; menu option.<br><br>Are you ready to make a difference by voting? ActiVote empowers you to engage in the democratic process confidently, ensuring your voice is heard.<br><br>We love to hear from you, contact us at info@activote.net<br><br><b>DOWNLOAD ACTIVOTE TODAY.</b>",
    "summary": "Voting smart in elections. Get US government policy, congress, democracy & more!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 127753,
    "score": 3.85,
    "ratings": 631,
    "reviews": 243,
    "histogram": [
        132,
        12,
        44,
        69,
        372
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "ActiVote Inc",
    "developerId": "ActiVote+Inc",
    "developerEmail": "info@activote.net",
    "developerWebsite": "https://activote.net/",
    "developerAddress": null,
    "privacyPolicy": "https://activote.net/privacy-policy/",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/YjZWR0VKeobRZdayQiLvOzEyrYgz4Wtw3COI_2YS8f_o9E5lPCMXAiI0r1NqXEHI7ls",
    "headerImage": "https://play-lh.googleusercontent.com/ExBKdV67lNSu3CRJlWTyOb15m1u7ZhrEtFkyvCYejzbt3a4GngooUbdB8ybisrzLlg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/sB_an2RhuO9kMRe1m0CxQDxR-S8W8ItCogHS_SxTqwSxaPVbKPx77FOkPLuArOLwpP0",
        "https://play-lh.googleusercontent.com/pz4tv5XbNe3SIQQdiqsq3HcwNNLEP1Duq8Y7bSRV4ARn7Ep9cWiC6JlUjl0kHapi1w8",
        "https://play-lh.googleusercontent.com/mOB5ndzCMAn7sPjl3UL-A7nRvCBPmc-3SL4h9yuquhOT2ibMDx7vweL6flUcLU3wVQ",
        "https://play-lh.googleusercontent.com/Vam6F6-hI2R4-wdPDCdJdw3I1xY93eEYrBEeEOXN19LJmoDMKDk4mqN_mlKg-I7eTA",
        "https://play-lh.googleusercontent.com/IG_vbqYUe8rjl8ZQwmSBgaIrhv7cEQPrGPqcJXI3QrWUi60RTdYEFS_sC_zH3QT51JI",
        "https://play-lh.googleusercontent.com/qCdNTC9P3dbjhjowtQR4E54Sj-LqoF-dZJYQ4GqJDRDGJf2lmqJOFJ4OFu4_HN7e680"
    ],
    "video": "https://www.youtube.com/embed/Hqa7tM_12x0?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/ExBKdV67lNSu3CRJlWTyOb15m1u7ZhrEtFkyvCYejzbt3a4GngooUbdB8ybisrzLlg",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 19, 2019",
    "lastUpdatedOn": "Aug 25, 2024",
    "updated": 1724597878,
    "version": "6.4.0",
    "comments": [],
    "appId": "net.activote.app",
    "url": "https://play.google.com/store/apps/details?id=net.activote.app&hl=en&gl=us"
}