{
    "title": "Money Well - Games for rewards",
    "description": "Have you ever wanted to earn money or gift cards while playing games?\r\n\r\nIt\u2019s time to get lucky and get the money you deserve for playing! \ud83c\udf40\r\n\r\nOnce you start playing, we track your active time in the game. Throughout the games, you will collect tickets that you can <b>exchange with gift cards</b>. \ud83c\udf81\r\n\r\nAll you have to do is play one of our games and you will pick up your rewards: gift cards and discount vouchers from top brands, or money payouts! \r\n\r\nLast but not least, enjoy a smooth game experience with <b>no advertising</b> in the games.\r\n\r\n\ud83d\udc69\u200d\ud83c\udfeb Here\u2019s how it works:\r\n\r\n\ud83d\ude42 First thing, get our completely free app: no in-app purchases, no deposit and no advertising.\r\n\r\n\ud83d\ude0a Once you have opened Money Well, you can <b>select a game</b> from our offer wall: <b>arcade</b>, <b>adventure</b>, <b>casual</b>, <b>strategic games</b>, and more. New games will appear regularly in the app and give you the opportunity to discover something new every day.\r\n\r\n\ud83d\ude03 As soon as you start playing, our app tracks your time. <b>The more you play, the more money you make</b>. Check any time your score on Money Well to see your progress. To win a gift card, you will have to collect a certain amount of tickets depending on the brand.\r\n\r\n\ud83e\udd11 <b>Fetch your gift card<b></b> as soon as you have reached enough tickets. You can also <b>cash out on your Paypal account</b> and get your money in less than 2 days.\r\n\r\nSounds like an easy way to make some money, right? \ud83e\udd2f\r\n\r\nDon\u2019t miss out on our tips to win your gift card faster \ud83d\udcc8\r\n\ud83e\udd1d Invite your friends or family and get extra tickets\r\n\ud83d\udcb8 Each game gives a different amount of tickets per minute, be smart and select the games where you earn tickets faster \r\n\r\nLet\u2019s play and get lucky!\r\n\r\nOffers and rewards are subject to availability.</b>",
    "descriptionHTML": "Have you ever wanted to earn money or gift cards while playing games?<br><br>It\u2019s time to get lucky and get the money you deserve for playing! \ud83c\udf40<br><br>Once you start playing, we track your active time in the game. Throughout the games, you will collect tickets that you can <b>exchange with gift cards</b>. \ud83c\udf81<br><br>All you have to do is play one of our games and you will pick up your rewards: gift cards and discount vouchers from top brands, or money payouts! <br><br>Last but not least, enjoy a smooth game experience with <b>no advertising</b> in the games.<br><br>\ud83d\udc69\u200d\ud83c\udfeb Here\u2019s how it works:<br><br>\ud83d\ude42 First thing, get our completely free app: no in-app purchases, no deposit and no advertising.<br><br>\ud83d\ude0a Once you have opened Money Well, you can <b>select a game</b> from our offer wall: <b>arcade</b>, <b>adventure</b>, <b>casual</b>, <b>strategic games</b>, and more. New games will appear regularly in the app and give you the opportunity to discover something new every day.<br><br>\ud83d\ude03 As soon as you start playing, our app tracks your time. <b>The more you play, the more money you make</b>. Check any time your score on Money Well to see your progress. To win a gift card, you will have to collect a certain amount of tickets depending on the brand.<br><br>\ud83e\udd11 <b>Fetch your gift card<b></b> as soon as you have reached enough tickets. You can also <b>cash out on your Paypal account</b> and get your money in less than 2 days.<br><br>Sounds like an easy way to make some money, right? \ud83e\udd2f<br><br>Don\u2019t miss out on our tips to win your gift card faster \ud83d\udcc8<br>\ud83e\udd1d Invite your friends or family and get extra tickets<br>\ud83d\udcb8 Each game gives a different amount of tickets per minute, be smart and select the games where you earn tickets faster <br><br>Let\u2019s play and get lucky!<br><br>Offers and rewards are subject to availability.</b>",
    "summary": "Play and exchange your points with gift cards. Make fast money with games!",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 26816451,
    "score": 4.400399,
    "ratings": 568913,
    "reviews": 14620,
    "histogram": [
        28398,
        14172,
        49440,
        86118,
        390778
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Money Well",
    "developerId": "Money+Well",
    "developerEmail": "contact@moneywell-app.online",
    "developerWebsite": "https://moneywell-app.online",
    "developerAddress": null,
    "privacyPolicy": "http://moneywell-app.online/legal/privacy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/cmHpf17VGIu13cAhcPessCjnAMtjwtcK1Cb3AeM8gZXv3bvB-msXPRopn3jM3MsMEA",
    "headerImage": "https://play-lh.googleusercontent.com/nJKO9Gwr9xFQLJXdVTOf5CfoPdIY8QsyaJ4zAhqd5upxoDePF0TN7qADzllVpY5oWQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ZcmuKKtLhq-nVzOIuXm8JfyLigry7zzd-CWUOFEgZJM7oCIUFCrgj8v1pMXWnL_1srg",
        "https://play-lh.googleusercontent.com/awnVPCC4OFZJFpLi4mNP7GAIpGdodqSbiBGfBmvk3y5nK8oqQm8sNn1ikOeYfnfDnDs",
        "https://play-lh.googleusercontent.com/AJI0aZOXFGk_NLPmj-uFTmY22zj0uxD6-ywh8ZbNxaRpEQYrLUIRg8WUlx9MG7Rff5Y",
        "https://play-lh.googleusercontent.com/4Gg49KJcqmrBJdihNSmCJ9_9EwmScBKygBEf7ZWcpV9ThMSgw4R1EwTEJz9c_vFLv0Q",
        "https://play-lh.googleusercontent.com/q3k4iiOyKeBdfAPPPs63zrz71Fo0Jw_p-3UXidzoJqEMW5UbBuAeQeHy3aom4eb37Vs"
    ],
    "video": "https://www.youtube.com/embed/mjep_OMuiSc?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/nJKO9Gwr9xFQLJXdVTOf5CfoPdIY8QsyaJ4zAhqd5upxoDePF0TN7qADzllVpY5oWQ",
    "contentRating": "Teen",
    "contentRatingDescription": "Simulated Gambling",
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 3, 2021",
    "lastUpdatedOn": "Nov 8, 2024",
    "updated": 1731088761,
    "version": "5.1.3-MoneyWell",
    "comments": [],
    "appId": "online.moneywell.app",
    "url": "https://play.google.com/store/apps/details?id=online.moneywell.app&hl=en&gl=us"
}