{
    "title": "Find my kids: live GPS tracker",
    "description": "Find my kids is a family live GPS tracker and kid tracker for parents designed for child's safety and mental health. You can connect a kid's GPS watch or install our family tracker app for live location share. Our live location tracker is important for every family, especially for stress-free parenting. Enable live location share with one tap!\r\n\r\nIn today's world, it is very important for a child to have support and protection both in the real world and online. Bullying at school, social media influences and child neglect can affect mental health and increase a child's stress levels. Findmykids is designed specifically for children and will not only help you keep your child safe as a pedestrian and avoid dangerous situations on the road, but will also allow you to reduce anxiety for your child while they are at school. Find out how much time your child spends on apps while at school, whether they are addicted to social media and teach your child proper time management.\r\n\r\nOur key features: \r\n\u2714 <b>Family live GPS tracker</b> \u2013Worried about your child's navigation skills? Ensure your child's safety and that they aren't visiting high-risk areas with a live mobile location tracker. This aids in promoting pedestrian safety and road safety for your children.\r\n\u2714 <b>Sound Around</b> \u2013 tune in to what is happening around your child to ensure that they are staying safe and in good company: this helps in preventing child neglect and addressing issues like anxiety and school bullying.\r\n\u2714 <b>Loud signal</b> \u2013 send a loud notification and find the phone if your child lost the phone or can't hear your call. \r\n\u2714 <b>App Statistics</b> \u2013 you can see what\u2019s distracting them or preventing them from focusing in the classroom, helping with time management, effective communication, and discipline. Address issues like screen time, social media distractions, and cyberbulling. Manage screen time to prioritize child's well-being!\r\n\u2714 <b>Live Updates</b> \u2013 check that your child arrived at school on time \u2013 get notifications when they reach school; add in custom locations. Know the location of your child and get all the benefits from live location share. This feature supports road safety and pedestrian safety. \r\n\u2714 <b>Battery check</b> \u2013 Encourage self-care and staying organized: track your child's mobile device charge status, and remind your child to charge their phone in time. \r\n\u2714 <b>Family chat</b> \u2013 chat with your child in our live location app with funny stickers. Learning to communicate with your child and teaching your child effective communication skills. Family chat is private, so you can have peace of mind about your child's internet safety.\r\n\r\n\r\nWe care about your privacy and the security of your data. We align our GPS family tracker with the requirements of the COPPA, the law on children's protection on the Internet. We do not sell or share your or your child's personal data with third parties.\r\n<b>How the Find my kids GPS cell phone tracker works:</b>\r\nInstall the Find my kids live GPS tracker on your phone;\r\nChoose what device you want to connect: child\u2019s phone or GPS watch;\r\nInstall the Pingo GPS tracker app on your child\u2019s phone or enter the GPS watch SIM card number;\r\nStart using the Find my kids GPS cell phone tracker to ensure your family's safety, including preventing school bullying, managing anxiety, and improving time management.\r\nHaving technical difficulties with our geo tracker? Please contact our 24/7 chat support within the app or send an email to support@findmykids.org.\r\n\r\nThe Find my kids GPS cell phone tracker asks for the following permissions:\r\n\u2013 Access to the camera and photos \u2013 to install the child's avatar;\r\n\u2013 Access to contacts \u2013 to fill in the phone book in the GPS watch;\r\n\u2013 Access to a microphone \u2013 to send voice messages in the chat;\r\n\u2013 Accessibility services - to limit time on the smartphone screen.",
    "descriptionHTML": "Find my kids is a family live GPS tracker and kid tracker for parents designed for child&#39;s safety and mental health. You can connect a kid&#39;s GPS watch or install our family tracker app for live location share. Our live location tracker is important for every family, especially for stress-free parenting. Enable live location share with one tap!<br><br>In today&#39;s world, it is very important for a child to have support and protection both in the real world and online. Bullying at school, social media influences and child neglect can affect mental health and increase a child&#39;s stress levels. Findmykids is designed specifically for children and will not only help you keep your child safe as a pedestrian and avoid dangerous situations on the road, but will also allow you to reduce anxiety for your child while they are at school. Find out how much time your child spends on apps while at school, whether they are addicted to social media and teach your child proper time management.<br><br>Our key features: <br>\u2714 <b>Family live GPS tracker</b> \u2013Worried about your child&#39;s navigation skills? Ensure your child&#39;s safety and that they aren&#39;t visiting high-risk areas with a live mobile location tracker. This aids in promoting pedestrian safety and road safety for your children.<br>\u2714 <b>Sound Around</b> \u2013 tune in to what is happening around your child to ensure that they are staying safe and in good company: this helps in preventing child neglect and addressing issues like anxiety and school bullying.<br>\u2714 <b>Loud signal</b> \u2013 send a loud notification and find the phone if your child lost the phone or can&#39;t hear your call. <br>\u2714 <b>App Statistics</b> \u2013 you can see what\u2019s distracting them or preventing them from focusing in the classroom, helping with time management, effective communication, and discipline. Address issues like screen time, social media distractions, and cyberbulling. Manage screen time to prioritize child&#39;s well-being!<br>\u2714 <b>Live Updates</b> \u2013 check that your child arrived at school on time \u2013 get notifications when they reach school; add in custom locations. Know the location of your child and get all the benefits from live location share. This feature supports road safety and pedestrian safety. <br>\u2714 <b>Battery check</b> \u2013 Encourage self-care and staying organized: track your child&#39;s mobile device charge status, and remind your child to charge their phone in time. <br>\u2714 <b>Family chat</b> \u2013 chat with your child in our live location app with funny stickers. Learning to communicate with your child and teaching your child effective communication skills. Family chat is private, so you can have peace of mind about your child&#39;s internet safety.<br><br><br>We care about your privacy and the security of your data. We align our GPS family tracker with the requirements of the COPPA, the law on children&#39;s protection on the Internet. We do not sell or share your or your child&#39;s personal data with third parties.<br><b>How the Find my kids GPS cell phone tracker works:</b><br>Install the Find my kids live GPS tracker on your phone;<br>Choose what device you want to connect: child\u2019s phone or GPS watch;<br>Install the Pingo GPS tracker app on your child\u2019s phone or enter the GPS watch SIM card number;<br>Start using the Find my kids GPS cell phone tracker to ensure your family&#39;s safety, including preventing school bullying, managing anxiety, and improving time management.<br>Having technical difficulties with our geo tracker? Please contact our 24/7 chat support within the app or send an email to support@findmykids.org.<br><br>The Find my kids GPS cell phone tracker asks for the following permissions:<br>\u2013 Access to the camera and photos \u2013 to install the child&#39;s avatar;<br>\u2013 Access to contacts \u2013 to fill in the phone book in the GPS watch;<br>\u2013 Access to a microphone \u2013 to send voice messages in the chat;<br>\u2013 Accessibility services - to limit time on the smartphone screen.",
    "summary": "Live location app for kids and parents: Phone tracking & Live location sharing",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 62242468,
    "score": 4.60984,
    "ratings": 1637390,
    "reviews": 10860,
    "histogram": [
        55757,
        22252,
        87316,
        174351,
        1297683
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.29 - $267.99 per item",
    "developer": "LETEM LTD",
    "developerId": "7228063865851856825",
    "developerEmail": "support@findmykids.org",
    "developerWebsite": "https://findmykids.org",
    "developerAddress": null,
    "privacyPolicy": "https://findmykids.org/docs/privacy-policy/android/en",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/e8uFp9Cmt-B59MCzPhU1chnhdIhyXSpS9pfg1rcetuake-RF73vvGWSdNuwLMlXGU1A",
    "headerImage": "https://play-lh.googleusercontent.com/PsGo852RXGFOxard_sYZlIPqOu8Nch2e3t6dwompaUffAWp4sRLSOul66f4ZJfFYDw0-",
    "screenshots": [
        "https://play-lh.googleusercontent.com/NjNdJchoj0H9Wz3Mtu8ZX8nBGX4J_fzvBkI86Ev6lnbjT1CCYygJrkbeoLL5FCGQwQ",
        "https://play-lh.googleusercontent.com/6IESQBVv8QG0wrZTa4CZcs9Qhf90nG_zAO8i-5SxYAt64EO8BYYYl5ThToRCXvmlRAo",
        "https://play-lh.googleusercontent.com/jNHUxHZ4WB_gLdzCVn1PJMtKYXvyy6R8KSl2yEOWi_z0bCW1IZ5c-rezA1hMfp1V64s",
        "https://play-lh.googleusercontent.com/ka6Eh4fpZ0EgHrht0qJX9O8wqCgTA5lLx2BjjKS_1YApnKGtYabvL7l-p6O79gYpbQ",
        "https://play-lh.googleusercontent.com/URQwbB5E0RYa5tV1Inr6pTcwwENsYmFAjCul45I-6-iPBDEkSvq201CdAR9Gbi_drJbw",
        "https://play-lh.googleusercontent.com/dxnD1c86Hm8UkqsbM-__zF0Qd8xZGYx1JSJXlkUHCSM0fuZ1mn0SC3JbuXid6lfeHCI",
        "https://play-lh.googleusercontent.com/CaE6SywNHZWssvnlbmRXh8DmE9DjUNNio6_OZJiX3E8LAVMYKmcHHYZlrqwXas6mpqk"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 17, 2015",
    "lastUpdatedOn": "Nov 14, 2024",
    "updated": 1731612166,
    "version": "2.8.15-google",
    "comments": [],
    "appId": "org.findmykids.app",
    "url": "https://play.google.com/store/apps/details?id=org.findmykids.app&hl=en&gl=us"
}