{
    "title": "LovePlanet - Live video dating",
    "description": "There are so many men and women around who'd wish to meet, chat, flirt or go dating with you! Whether you want to find a friend or find love, this app will be the best tool for achieving the goal. \r\n\r\nCheck out singles in the app, leave your \"\"likes\"\" for those who spark your interest or attract you, find out if they wish to chat or go out. Meet today! It might be a perfect start for new relationships! Make HD-quality video calls over Wi-Fi or on-the-go (2.5G/3G/4G/5G).\r\n\r\nFind out how many \"\"likes\"\" your photos would receive!\r\n\r\nLovePlanet unites men and women looking for relationship and brings them love!\r\n\r\nDownload the app right now to:\r\n\r\n* to find a pal, romantic or your second half\r\n* keep in touch with men or women you like wherever you are online\r\n* be sure that your profile and conversations are absolutely secure and will only appear in your phone\r\n* join those 800 thousand attractive singles who are about to find love and start new relationship\r\n* Thousands of the app users meet online every day - they are surely much closer to new relationship than those who haven't joined \r\n\r\nThe woman or man of your dream might be joining us right now! Get the app and be ready for love!",
    "descriptionHTML": "There are so many men and women around who&#39;d wish to meet, chat, flirt or go dating with you! Whether you want to find a friend or find love, this app will be the best tool for achieving the goal. <br><br>Check out singles in the app, leave your &quot;&quot;likes&quot;&quot; for those who spark your interest or attract you, find out if they wish to chat or go out. Meet today! It might be a perfect start for new relationships! Make HD-quality video calls over Wi-Fi or on-the-go (2.5G/3G/4G/5G).<br><br>Find out how many &quot;&quot;likes&quot;&quot; your photos would receive!<br><br>LovePlanet unites men and women looking for relationship and brings them love!<br><br>Download the app right now to:<br><br>* to find a pal, romantic or your second half<br>* keep in touch with men or women you like wherever you are online<br>* be sure that your profile and conversations are absolutely secure and will only appear in your phone<br>* join those 800 thousand attractive singles who are about to find love and start new relationship<br>* Thousands of the app users meet online every day - they are surely much closer to new relationship than those who haven&#39;t joined <br><br>The woman or man of your dream might be joining us right now! Get the app and be ready for love!",
    "summary": "Meet strangers, video streaming",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 18035615,
    "score": 4.010294,
    "ratings": 227252,
    "reviews": 894,
    "histogram": [
        37759,
        7671,
        17368,
        16040,
        148379
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $49.99 per item",
    "developer": "LovePlanet LLC",
    "developerId": "5982981992845727649",
    "developerEmail": "support@loveplanet.ru",
    "developerWebsite": "http://loveplanet.ru",
    "developerAddress": "117393, \u0433.\u041c\u043e\u0441\u043a\u0432\u0430, \u0443\u043b.\u041f\u0440\u043e\u0444\u0441\u043e\u044e\u0437\u043d\u0430\u044f, \u0434.78",
    "privacyPolicy": "http://loveplanet.ru/a-conditions/en",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/qw2qJaFkjWPeeGug4ocwPAXfYJl4G-xvoBN0kM5cE36-Jj_f6jeE5ODzkpPENMvcVW8",
    "headerImage": "https://play-lh.googleusercontent.com/bGR8pZ9js5qN60SfjKYJxZhnxghHCWMqBf7B_GuGNCakZBNDf05sEUpp_lSlDyTcI_g",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Jj4ujZxq29ABrgBN4eDJkaoQy0OfvhJXAYTKU7te0ycI2dVBlF4jdTyS2TZynog7ddI",
        "https://play-lh.googleusercontent.com/gcgs9TmYg2bXjRKeGFRObSwxtA5PZhlBK5LCgwAOMm6wgF2F62V-_ZDEhtcjKuXhsg",
        "https://play-lh.googleusercontent.com/hn2Ccb7iF7VfNNFzVEI_Y4HOOtg6TV26ZNNzkbytSpDCZ15ICZe0aIhPi8LuVnZaYw",
        "https://play-lh.googleusercontent.com/ojJyAsMjd4drC-haVSCy9rEBtK7H6PDkt1zIxJaXI1hY8mPEgohKnXw-jaVy7iR95B4",
        "https://play-lh.googleusercontent.com/T8SiqhOyW89fd-CLxg5kcLAdIl_6Zpomia9S7ne925TJUwbmBlwShwyFN5qhNWX02yA",
        "https://play-lh.googleusercontent.com/kphQk_Gv3agUNR_7eT3rJZPwH-AatN50sweF2Gz4-foV9q3XoUmd0Mf5_cA6jPfAXA",
        "https://play-lh.googleusercontent.com/F8NzytvEb05ewiXQc1-Y48-3r_EgpwP3NlG3uOLQWoIvMp22OWctZjy4yqNYTUh073g",
        "https://play-lh.googleusercontent.com/7m4I-3CitnLNq8HapcjoPJZiC5ELwiWvvs-4NVZVi8VE6-IG52QwP4_JJ4Uxsx0s3lk",
        "https://play-lh.googleusercontent.com/t1UJonEOEABk0XcSxyo4aRVMjwt9gOqJSmbv9p8dK4h8zODN-W_EaMUYaFdJe8h9nsi4",
        "https://play-lh.googleusercontent.com/l8KN4KUngl1nXv6Z2dMcM3u7ZsBxnaur9MPdFj_dW9Y_SCXaUhMOkXNloCyqzxxVJcw",
        "https://play-lh.googleusercontent.com/irrSWJJX0TEQtM60v7wW9bcui7dCMFLEo2dXjOR6K7jm49kaoYgIn7hxLyobsrslgbM",
        "https://play-lh.googleusercontent.com/P3bQrV5lh45uJQpLb8CW6hETsO-6VGF8RNLFqWb4R6A7ru4uDRiWgH43e9yEFxchAfs",
        "https://play-lh.googleusercontent.com/DZ9RROGlEcyRiC1J7DIzAYfD9b20V8lzn_N3eh0d_UwPTiBnZaiIR8TUZudmqxhckKBs",
        "https://play-lh.googleusercontent.com/p5c98m7WWPabhwYoJr7tHixmP36K341jxk7VX-sdhU-Z_LRptq43GImWZ3rwb23uLFs",
        "https://play-lh.googleusercontent.com/S5ahR3O9ymDQL9UfyFudBu2bfEmU6vDBt-JFCThkxrmv61Hwic3Tr95lQ1f0mpEgXL8",
        "https://play-lh.googleusercontent.com/kU_kIO3QMXMF5QeYdiepy9pGsuCHDWlRFNI0j_6PJA_qj4sgnck_giN7T0dQoA9dPw",
        "https://play-lh.googleusercontent.com/onEGrj4RKlmqB9PxgjuI22LeqN4T1n2SA-NUEGt-WgYWd2Ovgq6WHq31lcy_dlRykuA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 5, 2014",
    "lastUpdatedOn": "Nov 19, 2024",
    "updated": 1732032356,
    "version": "2.99.280",
    "comments": [],
    "appId": "ru.loveplanet.app",
    "url": "https://play.google.com/store/apps/details?id=ru.loveplanet.app&hl=en&gl=us"
}