{
    "title": "Ruby Rewards",
    "description": "With the new Ruby Rewards App, you can receive Rubies on purchases, earn free food, get exclusive offers, AND order from your phone!\r\n\r\nFeatures:\r\nOrder from your phone for added convenience.\r\n\r\nEarn Rubies when you eat at Ruby Tuesday or order through the Ruby Rewards App or rubytuesday.com\r\n\r\nSpend your Rubies on Free Food!\r\n\r\nSet your favorite Ruby Tuesday to get all the latest information on specials and offers!\r\n\r\nFind nearby locations \u2013 Get directions, view store details, and find the nearest location to you!\r\n\r\nAnd much more!\r\n\r\nOnly available at participating locations in the continental US. Excludes Hawaii, Guam, and airport locations.",
    "descriptionHTML": "With the new Ruby Rewards App, you can receive Rubies on purchases, earn free food, get exclusive offers, AND order from your phone!<br><br>Features:<br>Order from your phone for added convenience.<br><br>Earn Rubies when you eat at Ruby Tuesday or order through the Ruby Rewards App or rubytuesday.com<br><br>Spend your Rubies on Free Food!<br><br>Set your favorite Ruby Tuesday to get all the latest information on specials and offers!<br><br>Find nearby locations \u2013 Get directions, view store details, and find the nearest location to you!<br><br>And much more!<br><br>Only available at participating locations in the continental US. Excludes Hawaii, Guam, and airport locations.",
    "summary": "Join the Ruby Rewards! Trade Rubies for Food, Order Ahead, and more!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 218063,
    "score": 4.596226,
    "ratings": 2662,
    "reviews": 1389,
    "histogram": [
        140,
        20,
        60,
        330,
        2108
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Ruby Tuesday",
    "developerId": "Ruby+Tuesday",
    "developerEmail": "itappdeveloper@rubytuesday.com",
    "developerWebsite": "https://www.rubytuesday.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.rubytuesday.com/privacy-policy/",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/VZeIfftfocoeuL6zYmRLdJXsxxhiktv_PBtZ0WIgBtmIVUy5vgx8v0sNpK5l8WRrQeI",
    "headerImage": "https://play-lh.googleusercontent.com/ybd941eZtIRNlCo1l5DUO-GTto6MjbamBjkS3YAo6XeJqawLcuy3jWmDaDpj4p6d1w",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Z5MlvpO03_0lyylqGyUF4yPUbqCqrlmYk0iN3IjWd4wMBs2mMKqbnla5SPE0NvJwOQ",
        "https://play-lh.googleusercontent.com/OSFDSKNEY5uUstbsPqxG_pwj1huodL90g-nXAMl7-icxPMe3oykBmvpyazdxkL2okrk",
        "https://play-lh.googleusercontent.com/rhI9s6KJa-cCqGNQuTUP6bdXrJ1y9x5w95L-5egp6HS35Iz_dHhmrFr45zFYM1uEOM3T",
        "https://play-lh.googleusercontent.com/hjrloTPuBmKQZ1wW81V9yPmXstcBDr4DVhrZDT_9RGwa8WfCvTVd_D-s5ltmQgp-yA",
        "https://play-lh.googleusercontent.com/3klHVnHwa-YlFslVXD00-B7vB9fXdby_nt39fdL4VccTAwv4r0KWqPcW84uT1KJE2z8",
        "https://play-lh.googleusercontent.com/hMY2oRmhwQ1y6jy1Yt--w1RagnjU2TtZ0a_s249x7wm1B_SNjcWMQlON3KtvwVYutEY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 21, 2022",
    "lastUpdatedOn": "May 12, 2023",
    "updated": 1683907525,
    "version": "1.2",
    "comments": [],
    "appId": "ruby.tuesday.app",
    "url": "https://play.google.com/store/apps/details?id=ruby.tuesday.app&hl=en&gl=us"
}