{
    "title": "Swift Alert",
    "description": "The ultimate app for Swifties! Swift Alert will keep you connected to the shows and the music with a newsfeed of key fan accounts, concert dates in your time zone, and real-time alerts so you can check out livestreams. The Surprise Song Tracker will ensure you always know the latest surprise songs, and trivia quizzes will give you a chance to test your knowledge and show off your Swiftie status to your friends. \r\n\r\nSwift Alert is THE go-to source for Swifties!",
    "descriptionHTML": "The ultimate app for Swifties! Swift Alert will keep you connected to the shows and the music with a newsfeed of key fan accounts, concert dates in your time zone, and real-time alerts so you can check out livestreams. The Surprise Song Tracker will ensure you always know the latest surprise songs, and trivia quizzes will give you a chance to test your knowledge and show off your Swiftie status to your friends. <br><br>Swift Alert is THE go-to source for Swifties!",
    "summary": "Tour notifications",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 270199,
    "score": 4.9397593,
    "ratings": 17630,
    "reviews": 260,
    "histogram": [
        38,
        0,
        166,
        552,
        16863
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $1.99 per item",
    "developer": "Swift Alert LLC",
    "developerId": "Swift+Alert+LLC",
    "developerEmail": "swiftalerts13@gmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://www.swiftalert.online/terms-of-service",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/OjVmm4IeAmCW7ncWAb3vm32ZZeWEm6O3owXpp5nQ8_U-5bccM0iRyzCv-ATNMztIWQ",
    "headerImage": "https://play-lh.googleusercontent.com/0HN3MK7v_y4EShaTvd10qso-CVVR494V9PqPlCfFIuOVj3YDOyRjMtxnmii4jEbPYRQg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/rKD5N0NyOuINmKoxtiuFWKdbTNKIsGPVvz2gWVEdBJLC2w7LA098kJD0T6gzyQNek0c",
        "https://play-lh.googleusercontent.com/gWUBcHWvc1_cCbkJL0RMITjmJFWDZsVfLOQdge56sRb_vbydtR3yz5ZrkVOCXNcNdwk",
        "https://play-lh.googleusercontent.com/WIVO0IDGT26q2ZQvJ_-wWzwD8WCz1_fdQpVznNVlchh8C8U0_s_ZtxdQugHiLwevRe0",
        "https://play-lh.googleusercontent.com/k7qQsbK79-AhPwni1aJeQLZIB99-ShhIoY99XhzPsy4EmADIgrLH2-Eh2qKUO9IRWIUC",
        "https://play-lh.googleusercontent.com/TRlV9lxnNW2sEv0P_KRZYjHCWa1_olZByAnkBw3pFn-DtmSYcjfZK73f6OMEWgn620k",
        "https://play-lh.googleusercontent.com/7OHZxkuro1bPXlTdLHDx1pw_Q7HuF822lWlOLja68q8fA5xX6iClZuhNNzMrremKZ-tp"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 23, 2023",
    "lastUpdatedOn": "Nov 1, 2024",
    "updated": 1730504033,
    "version": "2.7.25",
    "comments": [],
    "appId": "swift.alert.app",
    "url": "https://play.google.com/store/apps/details?id=swift.alert.app&hl=en&gl=us"
}