{
    "title": "Test'em All: Test & Get Paid",
    "description": "With Test'em All, you become an online tester and earn exciting rewards!\r\nDo you have a passion for trying out new games? Look no further! Test'em All is here to transform your gaming experience into a rewarding adventure.\r\n\r\nHere is how it works:\r\n\r\n\u2b50 Install Test\u2019em All\r\n\u2b50 Test games\r\n\u2b50 Get cool rewards for your efforts! \r\n\r\n\r\nHere are the rewards we offer: \r\n\ud83d\udecd\ufe0f Discounts from Top Brands: Enjoy exclusive discounts across various industries, including technology, fashion,  food, and more.\r\n\ud83d\udcb0 Gift Cards: Earn gift cards to your favorite retailers and online stores, allowing you to shop for the products you love.\r\n\ud83e\udd11 Payouts: Accumulate points for every game tested and every review submitted. Convert these points into real cash payouts directly to your Paypal account \r\n\r\nJoin the Test'em All community today and embark on a journey of exploration, testing, and rewards. Be at the forefront of the digital world, shaping the future of mobile while enjoying exclusive discounts, gift cards, and payouts. \r\n\r\nYour passion and feedback are valuable, and Test'em All is here to make sure you're recognized for it. \r\n\r\nDownload the app now and start your testing adventure!",
    "descriptionHTML": "With Test&#39;em All, you become an online tester and earn exciting rewards!<br>Do you have a passion for trying out new games? Look no further! Test&#39;em All is here to transform your gaming experience into a rewarding adventure.<br><br>Here is how it works:<br><br>\u2b50 Install Test\u2019em All<br>\u2b50 Test games<br>\u2b50 Get cool rewards for your efforts! <br><br><br>Here are the rewards we offer: <br>\ud83d\udecd\ufe0f Discounts from Top Brands: Enjoy exclusive discounts across various industries, including technology, fashion,  food, and more.<br>\ud83d\udcb0 Gift Cards: Earn gift cards to your favorite retailers and online stores, allowing you to shop for the products you love.<br>\ud83e\udd11 Payouts: Accumulate points for every game tested and every review submitted. Convert these points into real cash payouts directly to your Paypal account <br><br>Join the Test&#39;em All community today and embark on a journey of exploration, testing, and rewards. Be at the forefront of the digital world, shaping the future of mobile while enjoying exclusive discounts, gift cards, and payouts. <br><br>Your passion and feedback are valuable, and Test&#39;em All is here to make sure you&#39;re recognized for it. <br><br>Download the app now and start your testing adventure!",
    "summary": "Gift cards, coupons and more!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 228236,
    "score": 4.5256066,
    "ratings": 3974,
    "reviews": 387,
    "histogram": [
        85,
        95,
        363,
        524,
        2901
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "justDice GmbH",
    "developerId": "justDice+GmbH",
    "developerEmail": "contact@appstation.online",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://apps.justdice-product.info/legal/privacy/android.testemall.app",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/r33-d3T1hNz9pWPthN0VrIcs-GHTXnUljDjpDxPciv9yPv_5vVkSony29kmWYt5T8FE",
    "headerImage": "https://play-lh.googleusercontent.com/2sJtR5appos3-W4iU6U3hMjwDy0dEeww0OwlIYy34YqCE1SMrVLHszMa8GHpeFmXtYs",
    "screenshots": [
        "https://play-lh.googleusercontent.com/LFjs0_JCksi81veLyMRTFFFfTDf_e3YzBDMBZ5GMmkgRWgdU04ZelLNExk1h9g62-uFU",
        "https://play-lh.googleusercontent.com/Nn91wh1zZ8xP_Mtjmu5t90xwGXC4NeQdx8KLoRRRWBxkOn4-PlPXhbW-VSb3WawghXw",
        "https://play-lh.googleusercontent.com/tkQfW7nfeUPOmFjvzG7SQ5VOtDtdnM0p9rxf7ItutH75db7nRgTLlg1cDtIXyyTMLzk",
        "https://play-lh.googleusercontent.com/MttjwW3fCHtxyXrr8xdNpxcrY2Axav-KZ0aml7VTNc_XxrlYXlpKk5jCe4LTlNucxLqp",
        "https://play-lh.googleusercontent.com/JbZZzYpox2u3MD3R0Q3zFOcm4iJVf8BBOgbGhD4eAIkEET7itVVUXGTF-fskAean9xQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 20, 2024",
    "lastUpdatedOn": "Nov 8, 2024",
    "updated": 1731088595,
    "version": "5.1.3-TestEmAll",
    "comments": [],
    "appId": "thetestemall.app",
    "url": "https://play.google.com/store/apps/details?id=thetestemall.app&hl=en&gl=us"
}