{
    "title": "Twitch: Live Streaming",
    "description": "Twitch is where thousands of communities come together for our favorite streamers, for the games we love, for the lulz, for each other, for whatever. Download Twitch and join millions enjoying live games, music, sports, esports, podcasts, cooking shows, IRL streams, and whatever else crosses our community\u2019s wonderfully absurd minds. We\u2019ll see you in chat.\r\n\r\nHere\u2019s a convenient list of other awesome things about Twitch:\r\n\r\nEveryone is \u201cabout\u201d community. We actually are one: Whatever you nerd out about, you can find your people on Twitch. \r\nGive support, get support: Find new streamers and subscribe to your favorites. Plus,  unlock exclusive perks for your support. \r\nStart your own channel: The Twitch app is one of the easiest ways to start streaming. Just create an account, go live directly from the app, and bring people together around whatever you\u2019re passionate about. \r\nYou never know what you\u2019ll find: Popular games are always live, but so are music festivals, rocket launches, street tours of Tokyo, and goat yoga. Yes, really. \r\nDark mode: Y\u2019all love this one. Black and purple have never looked this good together.\r\n\r\nTwitch's Terms of Service are available at https://www.twitch.tv/p/legal/terms-of-service/\r\nFor feedback and assistance, please visit our Support Center: https://help.twitch.tv\r\n \r\nPlease note: This app features Nielsen\u2019s proprietary measurement software which contributes to market research, like Nielsen\u2019s TV Ratings. Please see http://priv-policy.imrworldwide.com/priv/mobile/us/en/optout.html for more information",
    "descriptionHTML": "Twitch is where thousands of communities come together for our favorite streamers, for the games we love, for the lulz, for each other, for whatever. Download Twitch and join millions enjoying live games, music, sports, esports, podcasts, cooking shows, IRL streams, and whatever else crosses our community\u2019s wonderfully absurd minds. We\u2019ll see you in chat.<br><br>Here\u2019s a convenient list of other awesome things about Twitch:<br><br>Everyone is \u201cabout\u201d community. We actually are one: Whatever you nerd out about, you can find your people on Twitch. <br>Give support, get support: Find new streamers and subscribe to your favorites. Plus,  unlock exclusive perks for your support. <br>Start your own channel: The Twitch app is one of the easiest ways to start streaming. Just create an account, go live directly from the app, and bring people together around whatever you\u2019re passionate about. <br>You never know what you\u2019ll find: Popular games are always live, but so are music festivals, rocket launches, street tours of Tokyo, and goat yoga. Yes, really. <br>Dark mode: Y\u2019all love this one. Black and purple have never looked this good together.<br><br>Twitch&#39;s Terms of Service are available at https://www.twitch.tv/p/legal/terms-of-service/<br>For feedback and assistance, please visit our Support Center: https://help.twitch.tv<br> <br>Please note: This app features Nielsen\u2019s proprietary measurement software which contributes to market research, like Nielsen\u2019s TV Ratings. Please see http://priv-policy.imrworldwide.com/priv/mobile/us/en/optout.html for more information",
    "summary": "Stream, Watch, Chat. Live.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 286001489,
    "score": 4.0449543,
    "ratings": 5499097,
    "reviews": 234142,
    "histogram": [
        995816,
        152497,
        169355,
        472389,
        3709022
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $799.00 per item",
    "developer": "Twitch Interactive, Inc.",
    "developerId": "Twitch+Interactive,+Inc.",
    "developerEmail": "android@twitch.tv",
    "developerWebsite": "https://www.twitch.tv",
    "developerAddress": "350 Bush St Suite 200\nSan Francisco, CA 94104",
    "privacyPolicy": "https://www.twitch.tv/p/legal/privacy-notice",
    "genre": "Entertainment",
    "genreId": "ENTERTAINMENT",
    "categories": [
        {
            "name": "Entertainment",
            "id": "ENTERTAINMENT"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/QLQzL-MXtxKEDlbhrQCDw-REiDsA9glUH4m16syfar_KVLRXlzOhN7tmAceiPerv4Jg",
    "headerImage": "https://play-lh.googleusercontent.com/bnzBREOtt_TZXcKsrtUDmbDlYdBgTEMXDSBswLAhVDO0NJ-wDGHzg8lOMTzcgUjXhpQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/286cQbDMI2uJy43itASGRJflrsO_ZrsAKDquQHff1r3EBs9g5qDhPBnE1OP80xCHVy0",
        "https://play-lh.googleusercontent.com/DnPep1DdYfsRbAomh01h-jP7nLEjo1FDATRxZyjKGNHi-LW8hNns1rb4yJmKOrvtj05E",
        "https://play-lh.googleusercontent.com/Twky7JHydRNnmsSmipLqKLnsOLPYgcEvxL_eoiPZOPEEF_iHkStWqBpyJr7vWuw1MYY",
        "https://play-lh.googleusercontent.com/5TjSG5kcBvk2V1VJRS6edlBn1usxrmp7AHWB8keSEbktuX1kllXXu0nerXTGZLEaYl9p",
        "https://play-lh.googleusercontent.com/hox9RzRFjAMpg3TrG1hsSvjhj1z2077RhDyAxCMiSO3bkawgXotm9MlbPXnxdTPLdg",
        "https://play-lh.googleusercontent.com/6prucgh7zQpLSd-nfdRlpJDb42-LwfV2zvcgkvtCT9MF9iU74l_CN8yMYNqJP5_e4xo",
        "https://play-lh.googleusercontent.com/Na5JFTWuVRLejOty92trFndWhaiMovvnaT01Eb73sBd3n4dwcWscGF5sFbjuq8DrDDk",
        "https://play-lh.googleusercontent.com/hYkjpmmaPwEPHWmov3XzHiCAbXVV9Wg_BpgAJF6yH6aomzBI0wUkd4jiYSoj7u4XDgM",
        "https://play-lh.googleusercontent.com/CHHwJz5IncMq8VD1S6EGRWLFC933Oxw6Cr8Rd8uOoOhQ46pEI7PAwf2IXFQbk8IvRA",
        "https://play-lh.googleusercontent.com/j7rmYlNidq7weLDZX7t34qhBnarubsHautyu8-kvS7l6Hgx0J058l3V-VCcn1Oz83Uk",
        "https://play-lh.googleusercontent.com/hr-H3SlDquZRAFIarw1VzqXIm5R57WPI6LYVY7gmkuI-OAzokK_ZIUmoy_zSz51ufxV_",
        "https://play-lh.googleusercontent.com/CQQVB484xWZksKrT4HDSNP_Q2VT1gmd5U2I3g0wYYQI2MHkqsnYaHnasrPO3OyATreE",
        "https://play-lh.googleusercontent.com/OisFVWvmWuk_8JvoDQgqmtvjvL_cXz67E7JXP5rQa0oG5KXzLQsymf_JNw2y0iVtvA",
        "https://play-lh.googleusercontent.com/wVLza7IbkhmSlkPp8ekRlJMBAlx9lBm-b1clupRAAMAtGtKd25rWIhVAuEIoDzlZTG52",
        "https://play-lh.googleusercontent.com/YAxD8rrBrcJvUyoOFYhVQYtKiSHE6ePNhLLrR3hu4a-NyWCSba321vQ6MBjrz1GDnA",
        "https://play-lh.googleusercontent.com/MaD8DealA6wtn0Q3LjmdchVdwEq2J77dBwb-hDM3uyZFqYiSm_jocBSgv0EarjGwiTM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "May 20, 2015",
    "lastUpdatedOn": "Nov 15, 2024",
    "updated": 1731713145,
    "version": "Varies with device",
    "comments": [],
    "appId": "tv.twitch.android.app",
    "url": "https://play.google.com/store/apps/details?id=tv.twitch.android.app&hl=en&gl=us"
}