{
    "title": "Bluesky",
    "description": "Bluesky is THE NEW SOCIAL NETWORK for people who stay online and up-to-date. News, jokes, gaming, art, hobbies, and whatever you're into is happening here. Short text posts make for a quick read during coffee, an easy way to wind down the day, or a great way to get connected to your community. Follow your favorite posters or pick from one of the 25,000 feeds to find your people. Join millions of users to be part of the moment and have some fun again.\r\n\r\nYOUR TIMELINE, YOUR CHOICE\r\nStay in touch with your friends, stay up-to-date on the latest news, or explore with an algorithm that learns what you like. On Bluesky, you choose your own feed.\r\n\r\nCONTROL YOUR SCROLL\r\nStack powerful blocks, mutes, moderation lists, and content filters. You\u2019re in control.\r\n\r\nSOME OF THE OLD, ALL OF THE NEW\r\nLet\u2019s have fun online again. Be yourself and riff with your friends, all while having the option to keep tabs on what\u2019s happening at a global scale. It all happens on Bluesky.",
    "descriptionHTML": "Bluesky is THE NEW SOCIAL NETWORK for people who stay online and up-to-date. News, jokes, gaming, art, hobbies, and whatever you&#39;re into is happening here. Short text posts make for a quick read during coffee, an easy way to wind down the day, or a great way to get connected to your community. Follow your favorite posters or pick from one of the 25,000 feeds to find your people. Join millions of users to be part of the moment and have some fun again.<br><br>YOUR TIMELINE, YOUR CHOICE<br>Stay in touch with your friends, stay up-to-date on the latest news, or explore with an algorithm that learns what you like. On Bluesky, you choose your own feed.<br><br>CONTROL YOUR SCROLL<br>Stack powerful blocks, mutes, moderation lists, and content filters. You\u2019re in control.<br><br>SOME OF THE OLD, ALL OF THE NEW<br>Let\u2019s have fun online again. Be yourself and riff with your friends, all while having the option to keep tabs on what\u2019s happening at a global scale. It all happens on Bluesky.",
    "summary": "Social media as it should be",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 7704998,
    "score": 4.113164,
    "ratings": 26955,
    "reviews": 2385,
    "histogram": [
        4664,
        492,
        992,
        1738,
        19048
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Bluesky PBLLC",
    "developerId": "Bluesky+PBLLC",
    "developerEmail": "support@bsky.app",
    "developerWebsite": "https://bsky.app",
    "developerAddress": null,
    "privacyPolicy": "https://bsky.app/support/privacy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/VsgCCgW-ct98JhgVoQzndWCAaXxlP6uMwcjzINYPmeja8cCNISsJDqDFNQrF2IRq9xM",
    "headerImage": "https://play-lh.googleusercontent.com/syV8OYsksMQwXNTDc089WXqBuPbochteGiURADXJOkbBJmy-n-nf1V18LHVZ__ouOA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/WOqVBTStmU4oiKZ6lcuZp1tCN57XUHXkm9wX3GtjIU1M4IXUJ--4sGKGXGGqfdu-RVY",
        "https://play-lh.googleusercontent.com/cyc_E_nnE0AbCy9ZiQ13Lj4-7kq2c_SMtc6R9GwEF2RVXV60Uo-w-7xYTwqeyvb2UA",
        "https://play-lh.googleusercontent.com/FGwmMFNh-4sk_rGsM11C_1xIkVTzeMqPjiIzQsen_Qpwa1IsHzZ5_uR3Ox-iWhaeWe0",
        "https://play-lh.googleusercontent.com/gdv7IH90hVDGW_Jpe7R3_UlKHs3aQ9-ZpdjGimClXOsy0or2NxnriKhjmFgbor4FRA",
        "https://play-lh.googleusercontent.com/K6ATJT8svsKfVZCvFQ7S_pnl-x7AoW-QNw0aEiRzC_K55TvIvtmbFyCfnyE79WDCvbw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 9, 2023",
    "lastUpdatedOn": "Nov 16, 2024",
    "updated": 1731805300,
    "version": "1.94.0",
    "comments": [],
    "appId": "xyz.blueskyweb.app",
    "url": "https://play.google.com/store/apps/details?id=xyz.blueskyweb.app&hl=en&gl=us"
}