apk_log_folder = "test_data/api_log"
fastbot_log_path = "test_data/ui_trace"
app_detail_path = "/Users/yorca/projects/sdk_interaction/py/apps/app_details"
click_event_log_path = "test_data/click_event"
summary_ground_truth = "../Dynamic/data/api_summary_groundtruth.json"
runtime_environment = "IP: Euro"