{
    "title": "AI Interior Design: Home Plan",
    "description": "Transform your living space with AI Interior Design, where creating your dream home is as simple as snapping a photo. \r\n\r\n\u25ba AI Interior Design & Renovation\r\nJust upload an image of your room, choose the type of space and the style you want. Our advanced AI technology will analyze your room's dimensions and characteristics, then generate a stunning interior design plan catered to your taste. From modern chic to rustic warmth, our AI interior designer presents you with a visualization of furniture arrangements, color palettes, and decorative accents that bring your personal touch to life. \r\n\r\n\u25ba AI Exterior Design & Renovation\r\nTransform your home's exterior and garden with AI-powered design tools, visualize your dream space. Get rid of design constraints with a multitude of novel ideas for your home's exterior design. Simply upload a picture of your house, choose your preferred style, and the AI will provide you with a personalized design plan.\r\n\r\n\u25ba Discover New Walls\r\nRevamp your room's look with \"New Walls.\" Swap textures and colors with ease, visualizing the perfect wall finish without lifting a paintbrush. Our AI ensures every suggestion aligns with your vision.\r\n\r\n\u25ba Preview Your Flooring Choices\r\nWhy wait for the perfect flooring when you can see it instantly? Our \"Instantly Install New Flooring\" feature lets you preview a wide selection of flooring options, from hardwood to tile, right on your device. Experience the immediate impact of new flooring on your room's overall design and make an informed decision on your next home improvement project.\r\n\r\n\u25ba Explore Room Design Ideas\r\nLooking for a little inspiration? \"AI Interior Design\" is your go-to source for a plethora of room design ideas. Whether you're starting from scratch or just looking to refresh a single room, our app provides a wealth of ideas that cater to all styles. Our AI generates design concepts that consider the latest trends, timeless classics, and everything in between. Each idea is meticulously crafted to spark your creativity and help you create a living space that feels uniquely yours.\r\n\r\n\u25ba User-Friendly Interface & Intuitive Experience\r\nNavigating through \"AI Interior Design\" is a breeze, thanks to our clean and intuitive user interface. With simple actions, you can experiment with different furniture layouts and decor elements. Our app ensures that the design process is as enjoyable as the end result, making it easy for anyone to be their own interior designer.\r\n\r\n\u25ba Save & Share\r\nWith \"AI Interior Design,\" you can share your designs with friends and family, or collaborate with them in real-time. Embrace the power of AI in your home design journey. Start turning your house into the home of your dreams.\r\n\r\nIf got any questions, please email us to summerdaysc@outlook.com and we'll help you figure it out!\r\n\r\nRead more about our terms and conditions here:\r\nPrivacy Policy:https://coolsummerdev.com/artgenerator-privacy-policy\r\nTerm of Use:https://coolsummerdev.com/artgenerator-terms-of-use\r\nCommunity Guidelines: https://coolsummerdev.com/community-guidelines",
    "descriptionHTML": "Transform your living space with AI Interior Design, where creating your dream home is as simple as snapping a photo. <br><br>\u25ba AI Interior Design &amp; Renovation<br>Just upload an image of your room, choose the type of space and the style you want. Our advanced AI technology will analyze your room&#39;s dimensions and characteristics, then generate a stunning interior design plan catered to your taste. From modern chic to rustic warmth, our AI interior designer presents you with a visualization of furniture arrangements, color palettes, and decorative accents that bring your personal touch to life. <br><br>\u25ba AI Exterior Design &amp; Renovation<br>Transform your home&#39;s exterior and garden with AI-powered design tools, visualize your dream space. Get rid of design constraints with a multitude of novel ideas for your home&#39;s exterior design. Simply upload a picture of your house, choose your preferred style, and the AI will provide you with a personalized design plan.<br><br>\u25ba Discover New Walls<br>Revamp your room&#39;s look with &quot;New Walls.&quot; Swap textures and colors with ease, visualizing the perfect wall finish without lifting a paintbrush. Our AI ensures every suggestion aligns with your vision.<br><br>\u25ba Preview Your Flooring Choices<br>Why wait for the perfect flooring when you can see it instantly? Our &quot;Instantly Install New Flooring&quot; feature lets you preview a wide selection of flooring options, from hardwood to tile, right on your device. Experience the immediate impact of new flooring on your room&#39;s overall design and make an informed decision on your next home improvement project.<br><br>\u25ba Explore Room Design Ideas<br>Looking for a little inspiration? &quot;AI Interior Design&quot; is your go-to source for a plethora of room design ideas. Whether you&#39;re starting from scratch or just looking to refresh a single room, our app provides a wealth of ideas that cater to all styles. Our AI generates design concepts that consider the latest trends, timeless classics, and everything in between. Each idea is meticulously crafted to spark your creativity and help you create a living space that feels uniquely yours.<br><br>\u25ba User-Friendly Interface &amp; Intuitive Experience<br>Navigating through &quot;AI Interior Design&quot; is a breeze, thanks to our clean and intuitive user interface. With simple actions, you can experiment with different furniture layouts and decor elements. Our app ensures that the design process is as enjoyable as the end result, making it easy for anyone to be their own interior designer.<br><br>\u25ba Save &amp; Share<br>With &quot;AI Interior Design,&quot; you can share your designs with friends and family, or collaborate with them in real-time. Embrace the power of AI in your home design journey. Start turning your house into the home of your dreams.<br><br>If got any questions, please email us to summerdaysc@outlook.com and we&#39;ll help you figure it out!<br><br>Read more about our terms and conditions here:<br>Privacy Policy:https://coolsummerdev.com/artgenerator-privacy-policy<br>Term of Use:https://coolsummerdev.com/artgenerator-terms-of-use<br>Community Guidelines: https://coolsummerdev.com/community-guidelines",
    "summary": "Powerful home decoration & house design that allows you to design dream home.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 21635,
    "score": 4.1666665,
    "ratings": 93,
    "reviews": 12,
    "histogram": [
        13,
        2,
        6,
        4,
        66
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $49.99 per item",
    "developer": "Smart AI DEV",
    "developerId": "7455516559837104567",
    "developerEmail": "summerdaysc@outlook.com",
    "developerWebsite": "https://coolsummerdev.com/",
    "developerAddress": null,
    "privacyPolicy": "https://coolsummerdev.com/artgenerator-privacy-policy",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/BjURwN3PfIGut6Qmifp3AP5AsMN6W27JMmL04O4lKwQ7WfKWT8eC_W5VEAG95HkuDrh3",
    "headerImage": "https://play-lh.googleusercontent.com/MR3tVBtceCunGMQDnc_A36actFMuoe8nP9ERwgToZvJW6LaZM7lPyvZTQnQpMR6U6sA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/J-RsddWjTKsOwi1x3KuTggds85wQzB3rIjBk7kxNFWJddtqeREgjmAn5ZCVsGC1VTZ9U",
        "https://play-lh.googleusercontent.com/iVxPOEZ3Kmf3EBaFYhr9lPIV5kLiK97AuI0eBMxZceQwZzcyvFCMedP0JvzdcVnBDlg",
        "https://play-lh.googleusercontent.com/HQtPBEvSlRrtAnExRt-POGa2GEsm0u755_uX6JovF755waDAsc5R1MW3xeOqTiBsbEWx",
        "https://play-lh.googleusercontent.com/xVaDmyXg3evjlvJaDhnQtwUQYJIk2D2tD12QiWY54ZnbKTdPUITBDcdSjxAMVzlfMIL7",
        "https://play-lh.googleusercontent.com/AtTraslOXK6Hnpywfo8TN3hFzicumxkljLxjE_p1kvfXJm92wKK3_kchqT7GAcwXkQ",
        "https://play-lh.googleusercontent.com/zRFdUErOYGCU2lvhKz-ToilUIzXI9CAeg53-4YWNGQgl96aPnqj8rbcq-xgLLNgsXTo",
        "https://play-lh.googleusercontent.com/NWncaK7Z5kzEsap708pDg0yPCIom6g_8Cmx0YSuWu_pAzPr-vUMSVioef8jXAxtKqNjK",
        "https://play-lh.googleusercontent.com/QTDbeglR6TPmfYnlmA-vVhi-VkplfeOSocgvRc_h6Q796sUVtoCN0f-2359oUmVsEQ",
        "https://play-lh.googleusercontent.com/oUzitgW7TyHPtTMj0C3Qudft7rtc2wlN1GYi0HifolX8TeKQm7IQNKw_0Ovv7okFls0",
        "https://play-lh.googleusercontent.com/a4HaviDIkr5oPG15TWl1h6TR4faf9zRQX52XU4vsSrFv1UiD5nPjcZn3yiNaC7fbpjM",
        "https://play-lh.googleusercontent.com/q06kLV9Gd8JBv_NJvdH6vxO3A_831Mf3BueVEidCOUmlmZ8QJQ3YVm8yoVEQ8L5bvvEC",
        "https://play-lh.googleusercontent.com/YAsrAZyEdRNzrxEpORtUCgMCvRQM1rz-adedlbebkhEjviEkkUmszK1HgDX5IzVeGko",
        "https://play-lh.googleusercontent.com/lywJGgbv38Z2HS64zhPYGjcrzNNNKd1sDflAe3svN1dqSe8rZlOwaVmrsqIMTQAjCXU",
        "https://play-lh.googleusercontent.com/sKN0Mrl_Nmj_9kU-USdpg0ZLPPrKO1QtI0N4edyHkhTBP1mXNuTLFKP8zvk9t7qeUMSD",
        "https://play-lh.googleusercontent.com/2YKUH-OZVE6Zo5P2Gh8xw1bCaG3zM0FEAncg5MpmmdHXLaOzUUlBWcSof2C4xKwXVQ",
        "https://play-lh.googleusercontent.com/_qTvV9tRSp5DCjtegbeMVry7pHx4uqAMtL7Exdr1dMbAb82FUg5-PV9AIz3sszVTPFk",
        "https://play-lh.googleusercontent.com/PrUGiwzfBOBippMeC7d32cpg5oWAJjXR3RQHiGzBGuO3JMX9aeZ2WjeEcTi3t03bDK4",
        "https://play-lh.googleusercontent.com/Fr9wrNKL5gx2IQW_sCYns9RwQSbGz-96OAeyhCY3F8meUR8iuPPtVeX7R6gooPkgvQ",
        "https://play-lh.googleusercontent.com/sjjBPhB_nAVYE78zxqLkUZD5ldTFd0flpjeIpZf2re_DHLjPXh9ukIc2Z46tVqQbpA",
        "https://play-lh.googleusercontent.com/2gogZU-6z90ec6Hcb0zGOkkyXvPlFLx4Kp1Ue8pcjEHtsp8Y3N4VUv42qeY9kHNnv5c",
        "https://play-lh.googleusercontent.com/U66J0SF7WspCjnwFpRKMh5vdIvTWeiVPlcC3qg2oUrBN8EiPxopc9jA74OWqAY92YzGN"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 22, 2024",
    "lastUpdatedOn": "Oct 12, 2024",
    "updated": 1728723636,
    "version": "1.0.9",
    "comments": [],
    "appId": "ai.interior.design.home.renovation.app",
    "url": "https://play.google.com/store/apps/details?id=ai.interior.design.home.renovation.app&hl=en&gl=us"
}