{
    "title": "Howbout: social calendar",
    "description": "We\u2019re Howbout, the social calendar app to share time with friends. Share calendars, see when friends are free, make plans, keep on top of everything. \r\n\r\nOver 2.5 million users on Howbout, and they\u2019re all hot. \r\n\r\n\u2026\r\n\r\nSHARE CALENDARS\r\n- Want to stalk your friend\u2019s events? Shared calendars are for you\r\n\r\nMAKE PLANS\r\n- Stop bed rot and actually get plans out of the group chat. Unless you\u2019re scheduling group bed rot time together\r\n\r\nSEE WHEN EVERYONE\u2019S FREE\r\n- Share availability to find when everyone\u2019s free without sharing every detail\r\n\r\nVOTE WITH POLLS\r\n- Vote on anything (like what to do or when works best) with polls\r\n\r\nCOUNTDOWN TO PLANS\r\n- Pin calendar events to your home and countdown to their date\r\n\r\nKEEP MEMORIES\r\n- Add pictures to pinned events to keep them as memories\r\n\r\nALL YOUR PLANS TOGETHER\r\n- Forced to use another calendar? Gross. Sync it into Howbout\r\n\r\nBUCKET LISTS\r\n- Add in your bucket list and turn them into plans\r\n\r\nCHAT ON EVERY PLAN\r\n- There\u2019s a built-in group chat for every plan and group\r\n\r\nSHARE PICS & VIDS\r\n- Share pictures & videos directly to the plan\r\n\r\nSEND INVITES\r\n- Invite anyone to any event with a link\r\n\r\nFeatured by Apple, BBC, MailOnline, TechRound and a ton of other ones we don\u2019t care about as much!\r\n\r\n\u2026\r\n\r\nBored of stalking your friend\u2019s joint calendars? Stalk us instead:\r\n@howbout_app on socials, hello@howbout.app on email",
    "descriptionHTML": "We\u2019re Howbout, the social calendar app to share time with friends. Share calendars, see when friends are free, make plans, keep on top of everything. <br><br>Over 2.5 million users on Howbout, and they\u2019re all hot. <br><br>\u2026<br><br>SHARE CALENDARS<br>- Want to stalk your friend\u2019s events? Shared calendars are for you<br><br>MAKE PLANS<br>- Stop bed rot and actually get plans out of the group chat. Unless you\u2019re scheduling group bed rot time together<br><br>SEE WHEN EVERYONE\u2019S FREE<br>- Share availability to find when everyone\u2019s free without sharing every detail<br><br>VOTE WITH POLLS<br>- Vote on anything (like what to do or when works best) with polls<br><br>COUNTDOWN TO PLANS<br>- Pin calendar events to your home and countdown to their date<br><br>KEEP MEMORIES<br>- Add pictures to pinned events to keep them as memories<br><br>ALL YOUR PLANS TOGETHER<br>- Forced to use another calendar? Gross. Sync it into Howbout<br><br>BUCKET LISTS<br>- Add in your bucket list and turn them into plans<br><br>CHAT ON EVERY PLAN<br>- There\u2019s a built-in group chat for every plan and group<br><br>SHARE PICS &amp; VIDS<br>- Share pictures &amp; videos directly to the plan<br><br>SEND INVITES<br>- Invite anyone to any event with a link<br><br>Featured by Apple, BBC, MailOnline, TechRound and a ton of other ones we don\u2019t care about as much!<br><br>\u2026<br><br>Bored of stalking your friend\u2019s joint calendars? Stalk us instead:<br>@howbout_app on socials, hello@howbout.app on email",
    "summary": "Shared calendar to make plans, group calendars, share events & chat with friends",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 987541,
    "score": 4.754902,
    "ratings": 8596,
    "reviews": 217,
    "histogram": [
        123,
        0,
        166,
        1262,
        7034
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Howbout",
    "developerId": "Howbout",
    "developerEmail": "hello@howbout.app",
    "developerWebsite": "https://howbout.app",
    "developerAddress": null,
    "privacyPolicy": "https://howbout.app/privacy-policy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Q7jHlQMfcrsliG3JXsokGzt8zg5JQST1r0oukZSjyLhPJn1Fwt24wrUg817Ui6LaPA",
    "headerImage": "https://play-lh.googleusercontent.com/zmRLnwxr9E1zgEQXktabUGIfDcHE0K6hPuRJCsRUP2iurRGsd7cY0JqzOJ630iHM4A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/xqWt-4lRCxodKZlDOKVaottvTdQDWQC-p9d2j5pE445uA0n9q63xe1eTnN7Zl-eNOLQR",
        "https://play-lh.googleusercontent.com/rykQQqQL0OcyLnpEwKc_XFgBh1ANrin5B3B3JyiGMMCjLj00Qy5Xnns4sEl6185nQrV5",
        "https://play-lh.googleusercontent.com/RteqIhogVSlQpJJ6wx_7sioF3Tgw_PUE8CWEmhbJJJGsh4QvN1CSUjMB9vuoRRqNvg",
        "https://play-lh.googleusercontent.com/iuqH_kylNHhkDHZMWwkae-ToQzpM1p36Drqoh_xGiLqiyGQQguknMmx94_ud8mlVdA",
        "https://play-lh.googleusercontent.com/oc5-CyYfoNLubqmTZCu5lEEj2PmaouNAtvXfDU5iT7dgw2ODZ5fvVTNqAx6WRvqL0q5n",
        "https://play-lh.googleusercontent.com/AsbkOld6FBWyZZ4DAQI-msci8_Tc0g8mq_X-aW2C9TlinBKFd5QjwoykbcBmyhxe7Q",
        "https://play-lh.googleusercontent.com/VT_PU4CEzHL_VMcU2wxfGNwMRrrf10Q9MAnt3Rhl-u8ETugnhYNJVsWtsYS7EXYvTE0",
        "https://play-lh.googleusercontent.com/JiQAwGuo1-ZMH5-5K56v5ItdkPFwCbljXpSkNKbGihq7WX4otSrt73vyMLwXhUbUOXI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 29, 2019",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729598363,
    "version": "9.11.5",
    "comments": [],
    "appId": "app.zyng.app",
    "url": "https://play.google.com/store/apps/details?id=app.zyng.app&hl=en&gl=us"
}