{
    "title": "Storybook: Calm Bedtime, Sleep",
    "description": "<i>Nurturing Bonds, One Story at a Time</i>\r\n\r\n<b>Transform Bedtime with Storybook</b>\r\n\r\nWelcome to Storybook, the award-winning app designed to help parents improve their children's sleep, manage anxiety, and boost self-esteem through guided relaxation techniques, narrated bedtime stories, affirmations, and soothing music. Trusted by over 3 million families worldwide, Storybook creates meaningful, screen-free bedtime routines that build a lasting bond between parents and children. \r\n\r\n<i> ***Storybook is recommended by leading psychologists, therapists, and child well-being experts.*** </i>\r\n\r\n\r\n<b>Benefits for Families:</b>\r\n\r\n\u2022 STRENGTHEN FAMILY BONDS Create special moments and deepen your connection with your children through engaging stories and relaxing massages.\r\n\u2022 PROMOTE DEEP SLEEP Encourage restful sleep and minimize nightmares with our expert-designed sessions. Develop healthy sleep habits that ensure peaceful nights.\r\n\u2022 BOOST SELF-ESTEEM Build your child's confidence and self-worth through positive affirmations and soothing bedtime routines that promote emotional well-being and resilience.\r\n\u2022 MANAGE ANXIETY Help your child navigate and reduce anxiety with calming techniques and guided meditations designed specifically for children.\r\n\u2022 HOLISTIC HEALTH BENEFITS Reduce muscle and headache pain naturally, improve mood, stimulate the digestive system, and more. Foster a positive home atmosphere with our calming routines.\r\n\r\n\r\n<b>Discover Storybook:</b>\r\n\r\nStorybook offers over 400 content tracks and more than 100 massage techniques for children 0-12 years old, with new content added weekly. Our app is easy to use \u2013 simply follow the techniques and enjoy the stories together. Or meditate together, pray, express gratitude, listen to powerful affirmations, or enjoy a white noise music session. We also feature special Catholic and Bible stories and content for children and families to enjoy and reflect on together.\r\n\r\n\r\n<b>Features:</b>\r\n\r\n\u2022 GUIDED RELAXATION & MASSAGES Easy-to-follow techniques and enjoy a unique bonding experience with your children. Designed by certified sleep experts and backed up by science!\r\n\u2022 NARRATED BEDTIME STORIES Listen to beautifully narrated stories that encourage values, captivate your children\u2019s imagination, and help them wind down for the night.\r\n\u2022 AFFIRMATIONS (DAY AND NIGHT) Boost your child\u2019s self-esteem and confidence with positive affirmations that set the tone for a positive day and peaceful night.\r\n\u2022 GUIDED MEDITATIONS Help your child relax and manage anxiety with guided meditations designed specifically for their needs.\r\n\u2022 GRATITUDES & PRAYERS Encourage a sense of gratitude and mindfulness with nightly prayers and gratitude exercises.\r\n\u2022 SONGS Listen together to powerful songs that will help your child understand key messages and values, while enjoying a screen-free experience.\r\n\u2022 SOOTHING MUSIC & SOUNDS Create a serene environment with calming music and ambient sounds that promote relaxation and deep sleep.\r\n\u2022 SCIENTIFICALLY BACKED METHODS Our techniques are supported and backed by research and scientific evidence, showing that infant massage reduces stress, increases oxytocin levels, lowers cortisol levels, and supports neurological and muscular development.\r\n\u2022 EASY-TO-USE INTERFACE \r\n\r\n\r\n<b>Certifications:</b>\r\n\r\n\u2022 FSI (Family Sleep Institute) \r\n\u2022 IMUSA (Infant Massage USA)\r\n\u2022 KidSAFE \r\n\u2022 Recommended by Harvard experts\r\n\r\n\r\n<b>Pricing:</b>\r\n\r\nStart your free trial and experience better sleep routines, a calmer home, a confident child, and a happier family. Subscription is priced at $59.99/year for United States customers. Pricing in other countries may vary, and actual charges may be converted to your local currency depending on your country of residence.\r\n\r\n<b> Join millions of families already enjoying Storybook. Download now! </b>\r\n\r\n<b>Additional Resources:</b>\r\n\r\n\u2022 Support: info@familify.com\r\n\u2022 Privacy Policy: https://www.storybook-app.com/privacy-policy\r\n\u2022 Terms of Service: https://www.storybook-app.com/user-agreement",
    "descriptionHTML": "<i>Nurturing Bonds, One Story at a Time</i><br><br><b>Transform Bedtime with Storybook</b><br><br>Welcome to Storybook, the award-winning app designed to help parents improve their children&#39;s sleep, manage anxiety, and boost self-esteem through guided relaxation techniques, narrated bedtime stories, affirmations, and soothing music. Trusted by over 3 million families worldwide, Storybook creates meaningful, screen-free bedtime routines that build a lasting bond between parents and children. <br><br><i> ***Storybook is recommended by leading psychologists, therapists, and child well-being experts.*** </i><br><br><br><b>Benefits for Families:</b><br><br>\u2022 STRENGTHEN FAMILY BONDS Create special moments and deepen your connection with your children through engaging stories and relaxing massages.<br>\u2022 PROMOTE DEEP SLEEP Encourage restful sleep and minimize nightmares with our expert-designed sessions. Develop healthy sleep habits that ensure peaceful nights.<br>\u2022 BOOST SELF-ESTEEM Build your child&#39;s confidence and self-worth through positive affirmations and soothing bedtime routines that promote emotional well-being and resilience.<br>\u2022 MANAGE ANXIETY Help your child navigate and reduce anxiety with calming techniques and guided meditations designed specifically for children.<br>\u2022 HOLISTIC HEALTH BENEFITS Reduce muscle and headache pain naturally, improve mood, stimulate the digestive system, and more. Foster a positive home atmosphere with our calming routines.<br><br><br><b>Discover Storybook:</b><br><br>Storybook offers over 400 content tracks and more than 100 massage techniques for children 0-12 years old, with new content added weekly. Our app is easy to use \u2013 simply follow the techniques and enjoy the stories together. Or meditate together, pray, express gratitude, listen to powerful affirmations, or enjoy a white noise music session. We also feature special Catholic and Bible stories and content for children and families to enjoy and reflect on together.<br><br><br><b>Features:</b><br><br>\u2022 GUIDED RELAXATION &amp; MASSAGES Easy-to-follow techniques and enjoy a unique bonding experience with your children. Designed by certified sleep experts and backed up by science!<br>\u2022 NARRATED BEDTIME STORIES Listen to beautifully narrated stories that encourage values, captivate your children\u2019s imagination, and help them wind down for the night.<br>\u2022 AFFIRMATIONS (DAY AND NIGHT) Boost your child\u2019s self-esteem and confidence with positive affirmations that set the tone for a positive day and peaceful night.<br>\u2022 GUIDED MEDITATIONS Help your child relax and manage anxiety with guided meditations designed specifically for their needs.<br>\u2022 GRATITUDES &amp; PRAYERS Encourage a sense of gratitude and mindfulness with nightly prayers and gratitude exercises.<br>\u2022 SONGS Listen together to powerful songs that will help your child understand key messages and values, while enjoying a screen-free experience.<br>\u2022 SOOTHING MUSIC &amp; SOUNDS Create a serene environment with calming music and ambient sounds that promote relaxation and deep sleep.<br>\u2022 SCIENTIFICALLY BACKED METHODS Our techniques are supported and backed by research and scientific evidence, showing that infant massage reduces stress, increases oxytocin levels, lowers cortisol levels, and supports neurological and muscular development.<br>\u2022 EASY-TO-USE INTERFACE <br><br><br><b>Certifications:</b><br><br>\u2022 FSI (Family Sleep Institute) <br>\u2022 IMUSA (Infant Massage USA)<br>\u2022 KidSAFE <br>\u2022 Recommended by Harvard experts<br><br><br><b>Pricing:</b><br><br>Start your free trial and experience better sleep routines, a calmer home, a confident child, and a happier family. Subscription is priced at $59.99/year for United States customers. Pricing in other countries may vary, and actual charges may be converted to your local currency depending on your country of residence.<br><br><b> Join millions of families already enjoying Storybook. Download now! </b><br><br><b>Additional Resources:</b><br><br>\u2022 Support: info@familify.com<br>\u2022 Privacy Policy: https://www.storybook-app.com/privacy-policy<br>\u2022 Terms of Service: https://www.storybook-app.com/user-agreement",
    "summary": "Kids' Audio Stories, Meditations, Affirmations, Prayers & Gratitude Moments",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2001190,
    "score": 3.8019803,
    "ratings": 3558,
    "reviews": 131,
    "histogram": [
        770,
        163,
        163,
        281,
        2134
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $89.99 per item",
    "developer": "Familify\u00ae - Kids Sleep Health & Early Stimulation",
    "developerId": "7039428041479392812",
    "developerEmail": "info@familify.com",
    "developerWebsite": "https://storybook-app.com",
    "developerAddress": "14900 SW 30th St, Miramar, FL, 33027",
    "privacyPolicy": "https://storybook-app.com/privacy-policy/",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/tKUulGMNZxe6NJZO3O1WaI-Ii_trPQmYCSF0AnJZOteR8boM121wTrL7Y50b5HOZrg",
    "headerImage": "https://play-lh.googleusercontent.com/onYjkxKEB26ZGJn9obV6QSMnAdvzCe2D6n_eVfN0EZGLiSDjtjfyKqN1EpciciWxJQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/5RdUw6IlW5NsByBLHvs7JAMEAifZJ3zw0cnZGviPW_E2hYi7lQaD-vgU5mpG60YRavQj",
        "https://play-lh.googleusercontent.com/fH6lDMUPD0r2_8LiipsVFt1dEaS6zALJEMDyDnhvICb-D_3YawPXidDTaP30XQiaqg",
        "https://play-lh.googleusercontent.com/CjDmKpvf2pcQtY2gDShJma3gv59M4-cMUcCLPdXH4HcybEVH7ABCZp0VhghQC0JNeXg",
        "https://play-lh.googleusercontent.com/QWef_gPh-7DpMhN_Luj1w2njisoGWhOzqAkgkFzakgfdbzDy3oE38PWsm69rXE_5B5Y",
        "https://play-lh.googleusercontent.com/xoOCa81f05IASf9cffAayKwHlxWreYp9junRs_7DRJQfMIRESIIegiYGqcsI-Hr1zGI",
        "https://play-lh.googleusercontent.com/n0a-BmFHJ6WMYxf1gTvoxty_47ZlPDMhj2DpJsME8bOvn-ybTuf32cF8Hm6eW1qHq0T9",
        "https://play-lh.googleusercontent.com/0A9yrlm7WUtXHnruhvFVCmYKjDaEHDGGKLoOrDn7PIkCqgAvllvR0_NcannzoyiAGg",
        "https://play-lh.googleusercontent.com/fy_TjIDC2yrWMIKzLNBZpAOhjzVgwhG4dimnxMZtCIxsdkDpNY2exb8zSY5TPEjsSw",
        "https://play-lh.googleusercontent.com/8rJ7NRgRofgpNzUJf9eM8mra96mf_bzJTLEGcpDcMLs40hHla7LyJ8tdqLTMdRtxmqs",
        "https://play-lh.googleusercontent.com/jq0mvPLuBvRPMceeld2X8U9H5g5NfX9HSOdmWmJo9Lx0W4Peq5upwC8MlUUnP_LRLQw",
        "https://play-lh.googleusercontent.com/XFWhEGeuEh6KNKeX8nqRzqx8vJrFvGLohn4DjGcpkl9wzULjquhNVubzTBZHAl3bpU0",
        "https://play-lh.googleusercontent.com/wBnd-TMhKzOzUeav-L7-FfNmD_b9F4K1m_7AvlUr1G_diSkm7N-3VrOUcHWS8MDIZ0JY",
        "https://play-lh.googleusercontent.com/xEj1PxgKmEK3MvJXRBUyrzBXxV2UD-w4o41DrhGKPyCJmZMa-W1WNNdmJ1xHXGmWjQ",
        "https://play-lh.googleusercontent.com/4x1VeG0SlzeckKMPHUmiZ-qJIY9U50_QHzNSZiH7rYMGUxM0s_5peV8WkO66SxZ_pVk",
        "https://play-lh.googleusercontent.com/6_cygqHcSYVAqYmYVL557jL1-4QLOXijNaJDNkAVQPxPTz8FaCNfJpkxPCbbyNzFzuQ",
        "https://play-lh.googleusercontent.com/Kw2c30bfdWAATpbZe18-FgAmmTrWDHtmpkKPjLkchdp8gNRQeqY2PSCjI04gj8Wudxo",
        "https://play-lh.googleusercontent.com/WRoVV_2RdVh-oS9b9BvEa90QWAx9pNlFx1mizB0MgOYPdQJfoaL8wy5UVcJYKYCQfw",
        "https://play-lh.googleusercontent.com/q4L38vSpn4hQZtMu5gS4mofYuIty1IhOd6ff-s7DsP8WDZfWVKSsBgnMD42_Z0eK8J4",
        "https://play-lh.googleusercontent.com/N-vM530MiNR3idxe6ddrV-1lkl5HtKIPsd_y4tiX2uVz7wvH1YP4Q9NpFtUyr7LYUw",
        "https://play-lh.googleusercontent.com/xXO9HIKSDUo_nRktzFJazwFLz19LzPa-dFGpu5zied3S5wsoIhatm_6Lu-xsJzEdpwU",
        "https://play-lh.googleusercontent.com/tKIEDizMEBBXi-ilT2Oad3ULAMwEqU2cRyoEKoHWjLUfwQO47QwmWq9eNPpKJiC4ng0",
        "https://play-lh.googleusercontent.com/9MB6T2lQGXtr9mJRL3a9Ae003U8fdv4mWSVDf14_UY450N0XRisYJTq2m6yVAMRqnA",
        "https://play-lh.googleusercontent.com/itAQsGKdS3VTNQHBSX_N4jD3h64n8w6tgLv8Gd4BNgaQ6LPWyIhjjdGyOXYinhrvfHnb",
        "https://play-lh.googleusercontent.com/TWd6i_y6dRUGH2gKbo4kp7ByCxrfUd6aGZJuOYazzcx3zTeU6e_uCbnU4V6hu7o0Ow"
    ],
    "video": "https://www.youtube.com/embed/74NfiTXALOs?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/onYjkxKEB26ZGJn9obV6QSMnAdvzCe2D6n_eVfN0EZGLiSDjtjfyKqN1EpciciWxJQ",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 22, 2018",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729038473,
    "version": "5.2.27",
    "comments": [],
    "appId": "app.storybook.story",
    "url": "https://play.google.com/store/apps/details?id=app.storybook.story&hl=en&gl=us"
}