{
    "title": "AR Drawing Paint Sketch Trace",
    "description": "AR Drawing Paint Sketch Trace, an AR art projector that can help release your trace drawing and painting talents! Wanna know how to draw anime? Try this sketch AR drawing app and make your own masterpieces!\r\n\r\nHow to do AR drawing sketch paint?\r\n-Open the tracing app, prepare a pencil, a piece of paper, canva or a sketch book.\r\n-Choose a photo to sketch from your camera / gallery or from the outline pictures of the app.\r\n-Fix your phone with a support and trace to draw on photo with the tracing projector.\r\n-Congratulations! Now you can turn pictures into drawings anytime!\r\n\r\nHere's what our AR drawing app offers:\r\nAR ART Projector: Enhance your drawing experience with cutting-edge AR technology and AI-powered sketch conversion.\r\n\r\nCamera Integration: Open your camera, trace anything and draw with ease. Create both sketches and colorful artworks.\r\n\r\nAdjustable Settings: Modify transparency, pattern size, rotation, mirroring, and even use the flashlight for better visibility.\r\n\r\nExtensive Library: Choose from a wide range of images, including anime, cute designs, cartoon, animals, festival, aesthetics to use as your pencil sketch or drawing base.\r\n\r\nPhoto to Sketch: Convert your own photos into line sketches and start drawing instantly. Easy anime drawing!\r\n\r\nVideo Recording: Record your AR drawing paint process and share your creations with friends and family.\r\n\r\nTutorial Page: Step-by-step guides to help beginners learn outline drawing and ar draw sketch art quickly and efficiently.\r\n\r\nShowcase Skills: Perfect for those with some drawing experience to showcase their talents and art trace beautiful pictures.\r\n\r\nFun and Educational: Everyone can learn to draw, develop their artistic skills, and have fun at the same time.\r\n\r\nCreate Masterpieces: Trace and paint step-by-step to create artwork you\u2019ll be proud of.\r\n\r\nIt's ''magical'' to turn pictures into drawings and draw on photo. Whether you're a beginner or an experienced artist, our app caters to all skill levels. You won't have to worry about how to draw anime again because we'll make drawing easy for you!  \r\n\r\nDownload our AR Drawing Paint Sketch Trace App now and start creating beautiful art anytime, anywhere!",
    "descriptionHTML": "AR Drawing Paint Sketch Trace, an AR art projector that can help release your trace drawing and painting talents! Wanna know how to draw anime? Try this sketch AR drawing app and make your own masterpieces!<br><br>How to do AR drawing sketch paint?<br>-Open the tracing app, prepare a pencil, a piece of paper, canva or a sketch book.<br>-Choose a photo to sketch from your camera / gallery or from the outline pictures of the app.<br>-Fix your phone with a support and trace to draw on photo with the tracing projector.<br>-Congratulations! Now you can turn pictures into drawings anytime!<br><br>Here&#39;s what our AR drawing app offers:<br>AR ART Projector: Enhance your drawing experience with cutting-edge AR technology and AI-powered sketch conversion.<br><br>Camera Integration: Open your camera, trace anything and draw with ease. Create both sketches and colorful artworks.<br><br>Adjustable Settings: Modify transparency, pattern size, rotation, mirroring, and even use the flashlight for better visibility.<br><br>Extensive Library: Choose from a wide range of images, including anime, cute designs, cartoon, animals, festival, aesthetics to use as your pencil sketch or drawing base.<br><br>Photo to Sketch: Convert your own photos into line sketches and start drawing instantly. Easy anime drawing!<br><br>Video Recording: Record your AR drawing paint process and share your creations with friends and family.<br><br>Tutorial Page: Step-by-step guides to help beginners learn outline drawing and ar draw sketch art quickly and efficiently.<br><br>Showcase Skills: Perfect for those with some drawing experience to showcase their talents and art trace beautiful pictures.<br><br>Fun and Educational: Everyone can learn to draw, develop their artistic skills, and have fun at the same time.<br><br>Create Masterpieces: Trace and paint step-by-step to create artwork you\u2019ll be proud of.<br><br>It&#39;s &#39;&#39;magical&#39;&#39; to turn pictures into drawings and draw on photo. Whether you&#39;re a beginner or an experienced artist, our app caters to all skill levels. You won&#39;t have to worry about how to draw anime again because we&#39;ll make drawing easy for you!  <br><br>Download our AR Drawing Paint Sketch Trace App now and start creating beautiful art anytime, anywhere!",
    "summary": "AR drawing app, trace to do pencil sketch or paint a photo, easy anime drawing",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 182311,
    "score": 5,
    "ratings": 1097,
    "reviews": 4,
    "histogram": [
        0,
        0,
        0,
        0,
        1097
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "ideaFun - Pixel Art Coloring Games Color by Number",
    "developerId": "7148680220855906998",
    "developerEmail": "SunTingqwe@gmail.com",
    "developerWebsite": "http://droid-fun.com",
    "developerAddress": null,
    "privacyPolicy": "https://droid-fun.com/PrivacyPolicy.html",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/fJtNapYg1qFEe3XgmLh7HCLUvrkGamt4JaRLFnTTX7WN_vuIgMfyEAUsCcpe35VewCs",
    "headerImage": "https://play-lh.googleusercontent.com/1SNjJIRZrhym7_tNptdEoMRIN86mdf_f_kGT_gAB2AZ1-l9V22qe25x0FSaIVnB7Coc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nvPuN6wPIAZ0irQgWiGiDAtzwEXhRGHi7pZ1z6qgNY-B0KTxGDmi0QKoNRQlpE2EDmgu",
        "https://play-lh.googleusercontent.com/0c815q8IkP0-iOrvf2eHY6k9qjvfj-BOdqTQn-b0iP-0M794AbQMQvzaenJwW4IZv8gI",
        "https://play-lh.googleusercontent.com/2P2UUvxcCvPju3xu50RZ5WKLp3u9vg6pT9cAazuASmQ70cnvnwrTM70fYK1wAur85Q",
        "https://play-lh.googleusercontent.com/pl1B9mXVeCrTOTbJa9IOKTL8xN5b2nUfQfeGy4I6e-DrIBuVaM_cq8910pkmyGKl5g",
        "https://play-lh.googleusercontent.com/5iV7771NxrGDhJi6LmPyks9HlZjtanK0SOxUFXN7aPMwbb3YFBaxeLXQqajBw-GGEIc",
        "https://play-lh.googleusercontent.com/IRTApCTf7RJCK55q6uGTPoh4-hl53xRU77RuQVnjJBfgPviT87VyzIdmYtKCI3Ub2WQ",
        "https://play-lh.googleusercontent.com/hKDLNIs-0LLKuPbRUVCQL_Q1DTSXg1jK6WFtYMvU58ZD-mM-N3lbKSExC7btY9sG00E",
        "https://play-lh.googleusercontent.com/qRq_QyX-OdRS1567r-q5KyYX1PbLuH3AhHi8TQf7JdEfBkEOTZsEYzL9-BmNNgx2o0I1"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 20, 2024",
    "lastUpdatedOn": "Sep 30, 2024",
    "updated": 1727684150,
    "version": "1.0.4",
    "comments": [],
    "appId": "ar.drawing.paint.draw.sketch.art.trace.drawing.app",
    "url": "https://play.google.com/store/apps/details?id=ar.drawing.paint.draw.sketch.art.trace.drawing.app&hl=en&gl=us"
}