{
    "title": "Hair Editor, AI Makeup Filters",
    "description": "Beauty editor with tools inside such as trendy make up filters, AI hairstyle filters like long hair filter, bangs filter, bald filter hair changer, reshape body editor and many more will create a magical transformation!\r\n\r\nBeauty Camera\r\n\r\n- Make up photo editor and retouch face beauty AI tools to smooth skin\r\n- You can photo edit your lips and lipstick, apply eyeliner or eyebrow filters like you have many cosmetics! Edit your eyebags for a perfect look with no eyebags! There are eye color palettes in eye filters, eyelashes filter, cheekbones filter and eye shadow makeup filters!\r\n- Try smooth skin foundation, acne remover, teeth whitener, blemish remover and add some blush for cheekbones filter for a perfect skin\r\n- Beauty AI retouch face filter enhances your natural beauty plus increases your selfie's photo quality by AI photo editor! \r\n- There are perfect beauty filters AI effects like celebrity, freckles, desire, smile, fresh!\r\n\r\nAI Hair Filters\r\n\r\n- AI hairstyle app to have fun time with ai hair changer, long hair filter, bangs filter, curly hair filter, blonde hair filter and short hair filter for your face in hair editor\r\n- Beard photo editor and hair editor that serves many hairstyles for men also! AI hairstyle changer has hair dye filters, blond and red hair color filters, AI haircut filters as: Beard app, bald filter, short hair, long hair, blonde wavy hair, curly hair, straight and bangs filter!\r\n\r\nRetouch Face & Skin Smoother\r\n- Don't forget the touch retouch face: Remove dark circles, red eye corrector, no eyebags filter and many perfect face filters!\r\n- Retouch face beauty AI for \"make me thin\" for face, photo slimmer for chin and cheek, nose and jawline shaper!\r\n\r\nReshape Body Tune by AI Body Editor\r\n\r\n- Easily reshape body with AI body editor tools that complete beauty editor app inside!\r\n- Reshape body edit for perfect body tune by one click! Reshape photo editor for a slim and skinny waist, beauty AI, thinner and longer legs\r\n- Reshape your body with funny filters as fat filter or get a body like fitness person by AI Retouch Face & Reshape Body Editor!\r\n\r\n\r\nEnhance Photo Quality \r\n\r\n- Enhance photo quality tool is for you to make photos clear by picture enhancer!\r\n- Fix blurry photo with super AI face editor, quality enhancer and increase picture res with unblur photo and pixel!\r\n- Photo enhancer is ready to make your pictures incredible with AI art generator!\r\n\r\nObject Removal & Photo Background Changer\r\n\r\n- Remove objects from photo easily and delete unwanted people with AI face editor!\r\n- If object removal and remove things from photos are not enough for you, change background or remove backgorund completely for transparent background in seconds by AI Beauty Editor\r\n- AI photo generator takes you to any place you want to go with background changer, design and cutout background, white BG changer perfectly\r\n\r\nAI Photo Editor\r\n\r\n- Follow fun trends by AI face editor with young filter, make me old age filter, time machine, \"How do I look\" for future self!\r\n- Find perfect celebrity look alike, do gender swap by AI face generator!\r\n- AI cartoon photo editor, baby generator is ready for you to design your retro or AI art version! AI face generator for your portraits to turn them in cartoon trends with your pet!\r\n- \"How will my baby look like?\" With time machine effects, use the future baby filter! You can create your future baby with your and your partner photos!\r\n\r\nOne tap: Hair Editor, AI Makeup Filters App is a beauty editor with natural face make up filters and AI hairstyle changer! AI Art Generator with beauty looks! Beautiful lips, reshaped nose and eyes for your face, fun hairstyles like bald filter, no beard filter, short & long hair filter! Don't forget to retouch face for smooth skin for face and after, edit your perfect body reshape by your Abs Body Editor! Share your makeover on Instagram, Facebook, Whatsapp, Snapchat, TikTok, VK, Tumblr, Flickr, Twitter and Pinterest!",
    "descriptionHTML": "Beauty editor with tools inside such as trendy make up filters, AI hairstyle filters like long hair filter, bangs filter, bald filter hair changer, reshape body editor and many more will create a magical transformation!<br><br>Beauty Camera<br><br>- Make up photo editor and retouch face beauty AI tools to smooth skin<br>- You can photo edit your lips and lipstick, apply eyeliner or eyebrow filters like you have many cosmetics! Edit your eyebags for a perfect look with no eyebags! There are eye color palettes in eye filters, eyelashes filter, cheekbones filter and eye shadow makeup filters!<br>- Try smooth skin foundation, acne remover, teeth whitener, blemish remover and add some blush for cheekbones filter for a perfect skin<br>- Beauty AI retouch face filter enhances your natural beauty plus increases your selfie&#39;s photo quality by AI photo editor! <br>- There are perfect beauty filters AI effects like celebrity, freckles, desire, smile, fresh!<br><br>AI Hair Filters<br><br>- AI hairstyle app to have fun time with ai hair changer, long hair filter, bangs filter, curly hair filter, blonde hair filter and short hair filter for your face in hair editor<br>- Beard photo editor and hair editor that serves many hairstyles for men also! AI hairstyle changer has hair dye filters, blond and red hair color filters, AI haircut filters as: Beard app, bald filter, short hair, long hair, blonde wavy hair, curly hair, straight and bangs filter!<br><br>Retouch Face &amp; Skin Smoother<br>- Don&#39;t forget the touch retouch face: Remove dark circles, red eye corrector, no eyebags filter and many perfect face filters!<br>- Retouch face beauty AI for &quot;make me thin&quot; for face, photo slimmer for chin and cheek, nose and jawline shaper!<br><br>Reshape Body Tune by AI Body Editor<br><br>- Easily reshape body with AI body editor tools that complete beauty editor app inside!<br>- Reshape body edit for perfect body tune by one click! Reshape photo editor for a slim and skinny waist, beauty AI, thinner and longer legs<br>- Reshape your body with funny filters as fat filter or get a body like fitness person by AI Retouch Face &amp; Reshape Body Editor!<br><br><br>Enhance Photo Quality <br><br>- Enhance photo quality tool is for you to make photos clear by picture enhancer!<br>- Fix blurry photo with super AI face editor, quality enhancer and increase picture res with unblur photo and pixel!<br>- Photo enhancer is ready to make your pictures incredible with AI art generator!<br><br>Object Removal &amp; Photo Background Changer<br><br>- Remove objects from photo easily and delete unwanted people with AI face editor!<br>- If object removal and remove things from photos are not enough for you, change background or remove backgorund completely for transparent background in seconds by AI Beauty Editor<br>- AI photo generator takes you to any place you want to go with background changer, design and cutout background, white BG changer perfectly<br><br>AI Photo Editor<br><br>- Follow fun trends by AI face editor with young filter, make me old age filter, time machine, &quot;How do I look&quot; for future self!<br>- Find perfect celebrity look alike, do gender swap by AI face generator!<br>- AI cartoon photo editor, baby generator is ready for you to design your retro or AI art version! AI face generator for your portraits to turn them in cartoon trends with your pet!<br>- &quot;How will my baby look like?&quot; With time machine effects, use the future baby filter! You can create your future baby with your and your partner photos!<br><br>One tap: Hair Editor, AI Makeup Filters App is a beauty editor with natural face make up filters and AI hairstyle changer! AI Art Generator with beauty looks! Beautiful lips, reshaped nose and eyes for your face, fun hairstyles like bald filter, no beard filter, short &amp; long hair filter! Don&#39;t forget to retouch face for smooth skin for face and after, edit your perfect body reshape by your Abs Body Editor! Share your makeover on Instagram, Facebook, Whatsapp, Snapchat, TikTok, VK, Tumblr, Flickr, Twitter and Pinterest!",
    "summary": "Beauty editor with perfect make up filter, AI hairstyle and long hair filter!",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 711843,
    "score": 4.295681,
    "ratings": 5903,
    "reviews": 832,
    "histogram": [
        843,
        117,
        78,
        274,
        4587
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.99 - $49.99 per item",
    "developer": "AI Photo Generator, AI Chat",
    "developerId": "6438245010274581761",
    "developerEmail": "support@sparkdyn.com",
    "developerWebsite": "https://sparkdyn.com",
    "developerAddress": null,
    "privacyPolicy": "https://sparkdyn.com/privacy_policy.htm",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/6zZALLOTtyW56PCCtM0k9pHwA730f9Fw9_AtLTwFYHzj5XD5FEP_59mmBmsLg2ZlNWw",
    "headerImage": "https://play-lh.googleusercontent.com/ke3N6egFQaBsipWtG7KXWHdqw1yr_wYeMYWCNLKrnf6AVcxR8ZvacHPVLkPGKdtBFEY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nYuCs07fv2BzziQbo66fZR2pzOUV1t6p21rRs5AWSt6DIWm5SPp0agvR8_32lYiCxboh",
        "https://play-lh.googleusercontent.com/GyGvUysMWyZradkLBYx8mDB90So0NESL7dBRAIZ3LPmUFhv_Uyiz6n70CEqoJLxfnSY",
        "https://play-lh.googleusercontent.com/XD-AM_lI36LG1VXzWm_rcrlaA-ISQ5sm_AMhTxVnDNXAM5J4irXN7ssY96uDdZ16lvY",
        "https://play-lh.googleusercontent.com/7EllzroP9DvSyE7qS4WXtsorTfUFJIj2b3dagBT0V0THAwowZ0N2_n3jYxbaQ6vQx2I",
        "https://play-lh.googleusercontent.com/EnqDMdfGyoOem_zkjtoZLmqfKueN86Lzd1qLQ3NU1ZWoWdf-fOIZT6p68Z03o4UyN0E",
        "https://play-lh.googleusercontent.com/sqv-b-ApkayfslexpPseczEMR1Vw4RRmfqCswaayTvfyJ4UAldGEW1mHavgiVTfuVy8",
        "https://play-lh.googleusercontent.com/nAQFG5FCU3MuYr4jjilBGR3Viw9aVMHWd1Y187iyPF7b6dKyy9-gqbd7tY3zS17DoA",
        "https://play-lh.googleusercontent.com/Gk1IO8LncCRRgG9IBdACaZg2CxY4aVSsmcGFzecLH-RrO-tQRiAStgf8oTuKsN0_yNI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jan 5, 2023",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729252177,
    "version": "2.4.7",
    "comments": [],
    "appId": "beauty.makeup.cosmo.app",
    "url": "https://play.google.com/store/apps/details?id=beauty.makeup.cosmo.app&hl=en&gl=us"
}