{
    "title": "Shokz",
    "description": "You can find the following functions in the Shokz app:\r\n\r\n1) Rich and powerful sound\r\nEnjoy built-in tuning for easy switching between sound modes, while the customizable equalizer allows you to tailor your music to your preferences.\r\n\r\n2) Programmable buttons\r\nAssign touch buttons to the functions you use the most.\r\n\r\n3) Effortless multipoint pairing\r\nThe app allows you to simultaneously connect one pair of headphones to two Bluetooth devices. Additionally, you can easily switch and manage other Shokz headphones directly from the app.\r\n\r\n4) Firmware upgrades\r\nUp-to-date firmware keeps your headphones in optimal condition, ensuring you get the best user experience.\r\n\r\n5) Playback controls\r\nAdjust the volume, pause/play music, skip songs, and choose playback modes directly through the app.\r\n\r\n6) Access information\r\n- Your headphones: Including headphone battery status, user manual, serial number, and additional details.\r\n- Shokz: Explore the brand story, service policy, and other relevant information.\r\n\r\nIf you have any feedback, please visit the \"About Us\" section and select \"Feedback\" to share your comments with us.\r\n\r\nNote\r\nThe Shokz app is compatible with OpenRun Pro, OpenFit, OpenFit Air, OpenSwim Pro, and OpenRun Pro 2 models.\r\nPlease be aware that certain features may not be accessible on all products.",
    "descriptionHTML": "You can find the following functions in the Shokz app:<br><br>1) Rich and powerful sound<br>Enjoy built-in tuning for easy switching between sound modes, while the customizable equalizer allows you to tailor your music to your preferences.<br><br>2) Programmable buttons<br>Assign touch buttons to the functions you use the most.<br><br>3) Effortless multipoint pairing<br>The app allows you to simultaneously connect one pair of headphones to two Bluetooth devices. Additionally, you can easily switch and manage other Shokz headphones directly from the app.<br><br>4) Firmware upgrades<br>Up-to-date firmware keeps your headphones in optimal condition, ensuring you get the best user experience.<br><br>5) Playback controls<br>Adjust the volume, pause/play music, skip songs, and choose playback modes directly through the app.<br><br>6) Access information<br>- Your headphones: Including headphone battery status, user manual, serial number, and additional details.<br>- Shokz: Explore the brand story, service policy, and other relevant information.<br><br>If you have any feedback, please visit the &quot;About Us&quot; section and select &quot;Feedback&quot; to share your comments with us.<br><br>Note<br>The Shokz app is compatible with OpenRun Pro, OpenFit, OpenFit Air, OpenSwim Pro, and OpenRun Pro 2 models.<br>Please be aware that certain features may not be accessible on all products.",
    "summary": "Help you quickly get started with Shokz headphones",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 721056,
    "score": 4.337278,
    "ratings": 6000,
    "reviews": 712,
    "histogram": [
        778,
        32,
        67,
        601,
        4506
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Shokz",
    "developerId": "5015386298390251536",
    "developerEmail": "customer.service@shokz.com",
    "developerWebsite": "https://shokz.com/",
    "developerAddress": null,
    "privacyPolicy": "https://policyapp.shokz.com.cn/en",
    "genre": "Music & Audio",
    "genreId": "MUSIC_AND_AUDIO",
    "categories": [
        {
            "name": "Music & Audio",
            "id": "MUSIC_AND_AUDIO"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/aZLcaQTWCctmEe3V9XLlZDqdVSnQASC2AIJ2Cr0vtdxi5VvGxRdzuvy4VlVxbDrbgAw",
    "headerImage": "https://play-lh.googleusercontent.com/hycu78zRpQa3z9T6mxRzbHmeQosax6aHYjcp1IROUchi3WGI4vtYpYTTQ776Bt-OCD-v",
    "screenshots": [
        "https://play-lh.googleusercontent.com/JbpWk_sNJUmv_0sEKmdUeFaxuGrUaX8cbC8gEm3kHDc8pxPgV8bU9T2USjTITFqL8bMz",
        "https://play-lh.googleusercontent.com/A7IoChfCqB2zkkwg9ePGny0mmzXlIN6WR1-ecvtw_n65EOPL1OpBQK1AJMNBc3_Mmoto",
        "https://play-lh.googleusercontent.com/sz1FODV_ym_F7SL0gsReOZst7VdttACHO88NZHjuxtwoBiFhta5Nzsy1lkSpZEXn4Q",
        "https://play-lh.googleusercontent.com/S6bJR185Yvp9X-DQXgqFG5XmXkZrjHZIx7igo1YaADK_HhnlEP30h25FqYgPPIULz78",
        "https://play-lh.googleusercontent.com/BELnjAQ0DYk90Hb_3mv45w-iiS626P6GPutyQ-XAhERRSrFvBdAvhpo3M3PxlLoiOJs",
        "https://play-lh.googleusercontent.com/vRbkOR1DHiMoedHthDcIZzoKmP4vg7Lyskr8FjtFz9tr1MN67Nv-_ONiZxgvqvry5A",
        "https://play-lh.googleusercontent.com/nm-MqvJZlV85nlJJaN2ly_K6gG5aG3crS6WRgI3xmCXEPwwuagOovNbmQqfHxq5QU8o",
        "https://play-lh.googleusercontent.com/RRRlOYYSEQOXkbUxcw3VwX1dX7MQNKqpkuSTSLD98jwQJQd9yR6vFb0_PVIXOmwLU2k",
        "https://play-lh.googleusercontent.com/GL2BNzZ4O4ucg1hDeWBLPJDLmFUQzBtuz_fGFKgVG_2SnqJ5xa141u9SQhchkMsE-Q",
        "https://play-lh.googleusercontent.com/6I2ahygMStbo5xptjMHQFa5SE72-ZdUVxz9o4G61HGY-nzDO9tqHzl6PYvVBd1hYFAY",
        "https://play-lh.googleusercontent.com/1kJOtWwlJldzXKU-G-BJRvX71iboCLs_GXqLR2c9HVsFPUbU0IGHrUVcBdNBxVKoNqTi",
        "https://play-lh.googleusercontent.com/UdrdfMWRFN-ZwWUDolOkYlhNEM59RFM1oFSrwtLuADhwOImHArsaM19gcrSpbxjc1CYn",
        "https://play-lh.googleusercontent.com/C2J1PTlo8MtPHORn0xmxpdfrhi39dC432jkMc5NQiYhKSf4Osr-pIx3-s1m_HLubESM",
        "https://play-lh.googleusercontent.com/-mvqod7gr2mNPxIqtMMu5bixILMCxOFMS6ZxUuKiuErMEGXpoxrWA-NFkEhFA75NiZY",
        "https://play-lh.googleusercontent.com/P8e7EXNAfIK2FaS0C3crfx_cN8P40IyUYmtcn85ufj81KGXzJZo118iQjL7SDQkvqmak"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 2, 2021",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729148068,
    "version": "4.1.3",
    "comments": [],
    "appId": "cn.com.aftershokz.app",
    "url": "https://play.google.com/store/apps/details?id=cn.com.aftershokz.app&hl=en&gl=us"
}