{
    "title": "Goodie Bag: Local Food Deals",
    "description": "Welcome to Goodie Bag - Your App for Local Food Savings, Sustainability, and Connecting to Your Community!\r\n\r\nAt Goodie Bag, we're passionate about bringing you amazing deals on quality food from your favorite local eateries, while making a positive impact on your community and the environment. With our user-friendly app, you can access irresistible food offers at up to 80% OFF for pickup from the best restaurants, bakeries, cafes, grocers, and other shops in your neighborhood.\r\n\r\nWhy Choose Goodie Bag?\r\n\r\nWe offer you the best deal on quality local food period.\r\n\r\n* Unbeatable Deals: Enjoy mouth-watering meals and treats, also known as \"goodie bags,\" at a fraction of the price. We offer our OG surplus food goodie bags and fresh deal goodie bags. From gourmet dishes to your daily bread, indulge in a variety of options without stretching your budget.\r\n\r\n* Sustainable Choices - The OG Goodie Bag: Join us in our mission to reduce food waste and contribute to a healthier planet. Our OG goodie bags save perfectly good unsold food from being wasted, making you a hero for Mother Earth.\r\n\r\n* Exclusive Local Deals - The Fresh Deal Goodie Bag: Explore a diverse selection of freshly made items available at special discounts only found in our app chosen by the shops themselves. Enjoy the assurance of knowing exactly what you're getting, savor a fresh meal, support your local gems, and benefit from great savings.\r\n\r\n* Local First: We partner exclusively with top-rated local businesses to offer you a diverse selection of ready-to-eat meal-sized portions. We are on a mission to support the businesses that are the heartbeat of your community.\r\n\r\n* Instant Notifications: Never miss out on a deal! Turn on notifications to get alerted as soon as new goodie bags become available, ensuring you always get the best picks.\r\n\r\n* Easy and Convenient: Our app is designed for ease of use, allowing you to browse, purchase, and secure your goodie bag with just a few taps. Pick up your delicious finds at a pre-set time and enjoy your foodie adventure with no hassle.\r\n\r\nJoin Our Community of Eco-Conscious and Local Food Lovers\r\n\r\nBy choosing Goodie Bag, you're not just saving money; you're also making a statement against food waste and supporting local businesses. It's a win-win-win for you, the planet, and your community. With each goodie bag, you're contributing to a movement that values sustainability, quality, and deliciousness.\r\n\r\nWhat's in a Goodie Bag?\r\n\r\nOur OG goodie bags are a surprise, filled with high-quality, unsold food\u2014from freshly baked pastries and wholesome meals to gourmet dishes and delightful snacks. Enjoy the anticipation and the satisfaction of discovering what's inside, all while doing good.\r\n\r\nOur Fresh Deal goodie bags are made to order at a discounted price for pickup helping your local restaurants bring in business  in an era where food delivery services and chain restaurants prevail.\r\n\r\nReady to Start Goodie Baggin'?\r\n\r\nDownload Goodie Bag today and turn your food purchases into meaningful actions. Save cash, savor delicious food, and take a stand for your community and the environment. Let's make a difference together\u2014one goodie bag at a time.",
    "descriptionHTML": "Welcome to Goodie Bag - Your App for Local Food Savings, Sustainability, and Connecting to Your Community!<br><br>At Goodie Bag, we&#39;re passionate about bringing you amazing deals on quality food from your favorite local eateries, while making a positive impact on your community and the environment. With our user-friendly app, you can access irresistible food offers at up to 80% OFF for pickup from the best restaurants, bakeries, cafes, grocers, and other shops in your neighborhood.<br><br>Why Choose Goodie Bag?<br><br>We offer you the best deal on quality local food period.<br><br>* Unbeatable Deals: Enjoy mouth-watering meals and treats, also known as &quot;goodie bags,&quot; at a fraction of the price. We offer our OG surplus food goodie bags and fresh deal goodie bags. From gourmet dishes to your daily bread, indulge in a variety of options without stretching your budget.<br><br>* Sustainable Choices - The OG Goodie Bag: Join us in our mission to reduce food waste and contribute to a healthier planet. Our OG goodie bags save perfectly good unsold food from being wasted, making you a hero for Mother Earth.<br><br>* Exclusive Local Deals - The Fresh Deal Goodie Bag: Explore a diverse selection of freshly made items available at special discounts only found in our app chosen by the shops themselves. Enjoy the assurance of knowing exactly what you&#39;re getting, savor a fresh meal, support your local gems, and benefit from great savings.<br><br>* Local First: We partner exclusively with top-rated local businesses to offer you a diverse selection of ready-to-eat meal-sized portions. We are on a mission to support the businesses that are the heartbeat of your community.<br><br>* Instant Notifications: Never miss out on a deal! Turn on notifications to get alerted as soon as new goodie bags become available, ensuring you always get the best picks.<br><br>* Easy and Convenient: Our app is designed for ease of use, allowing you to browse, purchase, and secure your goodie bag with just a few taps. Pick up your delicious finds at a pre-set time and enjoy your foodie adventure with no hassle.<br><br>Join Our Community of Eco-Conscious and Local Food Lovers<br><br>By choosing Goodie Bag, you&#39;re not just saving money; you&#39;re also making a statement against food waste and supporting local businesses. It&#39;s a win-win-win for you, the planet, and your community. With each goodie bag, you&#39;re contributing to a movement that values sustainability, quality, and deliciousness.<br><br>What&#39;s in a Goodie Bag?<br><br>Our OG goodie bags are a surprise, filled with high-quality, unsold food\u2014from freshly baked pastries and wholesome meals to gourmet dishes and delightful snacks. Enjoy the anticipation and the satisfaction of discovering what&#39;s inside, all while doing good.<br><br>Our Fresh Deal goodie bags are made to order at a discounted price for pickup helping your local restaurants bring in business  in an era where food delivery services and chain restaurants prevail.<br><br>Ready to Start Goodie Baggin&#39;?<br><br>Download Goodie Bag today and turn your food purchases into meaningful actions. Save cash, savor delicious food, and take a stand for your community and the environment. Let&#39;s make a difference together\u2014one goodie bag at a time.",
    "summary": "Save food & money!",
    "installs": "5,000+",
    "minInstalls": 5000,
    "realInstalls": 8026,
    "score": 3.0333333,
    "ratings": 30,
    "reviews": 22,
    "histogram": [
        7,
        6,
        5,
        3,
        9
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Goodie Bag Food Co",
    "developerId": "Goodie+Bag+Food+Co",
    "developerEmail": "info@goodiebag.co",
    "developerWebsite": "https://www.about.goodiebag.co/",
    "developerAddress": null,
    "privacyPolicy": "https://www.about.goodiebag.co/privacypolicy",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/vjvA0RO49wq9A7bITTyXBfyljvCRoof4c18uIpf_9Qbx1ghVqy68_e0eRiA6JRm7Q28",
    "headerImage": "https://play-lh.googleusercontent.com/XT8LWPAvSrY2XZk4ZNlstVIZ0v86WJRsrk1cWL09Dcxb13L9oXw8TsGwSFyv_UWZ1w",
    "screenshots": [
        "https://play-lh.googleusercontent.com/sP561G6RiE5yYQtQOectqYtXMaa39DtcPGNKH7CRkUzvbD-RobhErlajpPdBPHccBuU",
        "https://play-lh.googleusercontent.com/wUDDc2K2qDkhJ6iuRvPcE8oNFTrSw-q68kbArmIerTVYmnDQlJy25f6wX_V7N3LyK98T",
        "https://play-lh.googleusercontent.com/NniIy_5W5sEHi1Bundp17b-ZhMR0ubc2YTOaEpYZcrXaDrfza60aWIMCbtywQU5ep2s",
        "https://play-lh.googleusercontent.com/dGI8bymt3MU_MXCbpKR_R-i2zBFHhmEQo4-wYEh62qQEGullrvfgtS8w2hSrZeePDhc",
        "https://play-lh.googleusercontent.com/l_D-w8hyP2dDfxiWtu3hBi7DLusYXFUo08fCCOWUe5vxZmZRDPaWW--rsHoB3qAQo-qM",
        "https://play-lh.googleusercontent.com/V8X4LWPuWbUVWMj453044_6pDRLp9szJXPtgvH_ogSvil4QeAmFW2haPcUoOEr5hBpWx",
        "https://play-lh.googleusercontent.com/4wcsdwlzmF3ldma57BL3mkpTRdQERI4OOhw3kfE3gTpfgxGwCVUqfzttTt4kr7I47f4",
        "https://play-lh.googleusercontent.com/8llM9QRz6IjtoHMMkLpMcx3pXw3jWOJnhoaObrmbJojJS7pnpaRAK_qSuRkvmWLgV24",
        "https://play-lh.googleusercontent.com/K-UFFQSzBETntpKv_8ExkMPYpD83tSe8bgaJ9BT8fzNIk9k0noAf7jlIDahvFMiW3w",
        "https://play-lh.googleusercontent.com/csk5XS81cVYIcK--Ry-3Zit1MZhDz7CQE4nTC72GH11uhTbcBtZF9PFq5QV0eLIqsw",
        "https://play-lh.googleusercontent.com/jxuQQB4Q-teSAaCTss4RHoFjSdk6oc0i56JLPAp9h3gsXcj6czTyGk0Kr6BwNoUl868",
        "https://play-lh.googleusercontent.com/mVm2jzL7mAuYGLmrHFS-jx_GttkO7vsH37eo3SfY20iE0B78HJKOlX5aeKbZkCEmdBs",
        "https://play-lh.googleusercontent.com/q3AHGQ9gCk8U6YjMz8M_ApOfsCeIDHNW-KZy7xFCjRGe1EVUFH7VK9qjqoWuPgptfPU",
        "https://play-lh.googleusercontent.com/RNZYFLcP5CgZjsS2mqK_5VBcJ9vpFDPNNiZrxWH6OmHEXcymBahx7cQJr4cWlxaQZdyK",
        "https://play-lh.googleusercontent.com/MLVCa_5eshHbZjeBwFSxuBntH5ongKPjo4CBw17MeImIu9PiqIufPzvAPl3DaaiGTQ",
        "https://play-lh.googleusercontent.com/G5_-Ao3eL5WRSZa9Av-qvYxmyKKS5dfaQtXKF1XXqVDft4GXKLE8QQKtpBjK29lLrlI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 20, 2023",
    "lastUpdatedOn": "Sep 18, 2024",
    "updated": 1726682138,
    "version": "2.0.0",
    "comments": [],
    "appId": "co.goodiebag.app",
    "url": "https://play.google.com/store/apps/details?id=co.goodiebag.app&hl=en&gl=us"
}