{
    "title": "HUD Hookup App: Dating & Chat",
    "description": "Join the HUD\u2122 casual dating community and meet more than 17 million open-minded adult singles and couples worldwide who choose to have open relationships, local hookups NSA and more.\r\n\r\nHUD\u2122 - Revolution in Casual Dating\r\nHUD\u2122 app is a casual dating and hookups app that is honest about the realities of online dating. Authentic, transparent and safe hookups are what this open dating app aims to create. A safe space for like-minded adults to connect, explore dating freely - whether casual fun, have polyamory NSA meets, chat with local singles and couples, or anything in between.\r\n\r\nNo matter what kind of relationship you're looking for: casual hookup dating, friends with benefits dating (FWB) or romance relationships, what matters most is communication, honesty, mutual respect, and trust. Explore dating as you want with HUD's open-minded dating community.\r\n\r\nHonest Casual Hookups With Confidence\r\nHonest, upfront dating is what HUD\u2122 does best.\r\n \u2b24 Find great flings and casual relationships with like-minded individuals by using the casual dating in-app features, designed to help you show your true self and meet new people.\r\n \u2b24 Be confident in the transparent, casual dating experience your hookup app provides.\r\n \u2b24 Stay in control and feel safe with virtual dating options to flirt, chat and date, such as video chat with built-in privacy blur, private chat, and female-friendly chat features.\r\n\r\nSafe space for DTF & safe dating\r\nOur adult hookup app is popular for a reason - it works! HUD\u2122 celebrates dating in all its forms: Whether you\u2019re looking to have casual dates with men or you are looking to meet women, if you are into polyamory and couples dating or want to meet singles, casual gay local meetups, lesbian, bi curious, straight,  bisexual, pansexual, non-binary or transgender hookup, you will connect with like-minded individuals looking for casual open dating and open relationships. HUD\u2122 is an inclusive, accepting space to explore your desires freely.\r\n\r\nCasual Dating on Your Terms\r\nNot looking for anything serious? No problem! Long term relationships are great, but we get it - sometimes you just want some casual fun!  HUD\u2122 acknowledges that not every person is ready for a commitment on the first date. That's why HUD\u2122 is perfect for those looking for short-term flings, polyamory, ethical non-monogamous (ENM) dating, FWB (friends with benefits), casual sex, NSA hookup (no strings attached), a one-night stand, and sexy connections without expectations. Whether you\u2019re travelling, want to keep things light, too busy for a relationship or you\u2019re just coming out of one, HUD\u2122 is the perfect place to find someone. \r\nYou deserve a casual dating experience that is empowering, judgment-free, and all about your desires. No games, no guilt - just genuine connections with respectful, open-minded singles who embrace your sexuality and boundaries. Meet open-minded singles for safe flirting and zero-strings excitement. \r\n\r\nFlirty Flings, FWB hookups & Dates with HUD\u2122\r\n \u2b24 Safe, discreet & fully customizable\r\n \u2b24 Female-friendly chat features\r\n \u2b24 Video dating app with auto blur safety feature\r\n \u2b24 Send and receive videos, photos, and voice messages\r\n \u2b24 Photo Protection Blur\r\n \u2b24 Advanced match filters\r\n\r\nLooking for an easy way to meet up with locals for a casual hook up? Look no further than HUD\u2122 - the open dating app, for people who want to find local fun dating and excitement. Find hookups tonight!\r\n\r\n --------------------------------\r\n\r\n Subscription Service Terms & Conditions:\r\n\r\n If you choose to purchase HUD\u2122 Premium, payment will be charged to your Google Play account, and your account will be charged for renewal within 24-hours prior to the end of the current period. Your subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period. If you don\u2019t choose to purchase HUD Premium, you can simply continue using HUD for free.\r\n\r\n Privacy Policy: https://www.hudapp.com/#/privacy\r\n Terms: https://www.hudapp.com/#/terms",
    "descriptionHTML": "Join the HUD\u2122 casual dating community and meet more than 17 million open-minded adult singles and couples worldwide who choose to have open relationships, local hookups NSA and more.<br><br>HUD\u2122 - Revolution in Casual Dating<br>HUD\u2122 app is a casual dating and hookups app that is honest about the realities of online dating. Authentic, transparent and safe hookups are what this open dating app aims to create. A safe space for like-minded adults to connect, explore dating freely - whether casual fun, have polyamory NSA meets, chat with local singles and couples, or anything in between.<br><br>No matter what kind of relationship you&#39;re looking for: casual hookup dating, friends with benefits dating (FWB) or romance relationships, what matters most is communication, honesty, mutual respect, and trust. Explore dating as you want with HUD&#39;s open-minded dating community.<br><br>Honest Casual Hookups With Confidence<br>Honest, upfront dating is what HUD\u2122 does best.<br> \u2b24 Find great flings and casual relationships with like-minded individuals by using the casual dating in-app features, designed to help you show your true self and meet new people.<br> \u2b24 Be confident in the transparent, casual dating experience your hookup app provides.<br> \u2b24 Stay in control and feel safe with virtual dating options to flirt, chat and date, such as video chat with built-in privacy blur, private chat, and female-friendly chat features.<br><br>Safe space for DTF &amp; safe dating<br>Our adult hookup app is popular for a reason - it works! HUD\u2122 celebrates dating in all its forms: Whether you\u2019re looking to have casual dates with men or you are looking to meet women, if you are into polyamory and couples dating or want to meet singles, casual gay local meetups, lesbian, bi curious, straight,  bisexual, pansexual, non-binary or transgender hookup, you will connect with like-minded individuals looking for casual open dating and open relationships. HUD\u2122 is an inclusive, accepting space to explore your desires freely.<br><br>Casual Dating on Your Terms<br>Not looking for anything serious? No problem! Long term relationships are great, but we get it - sometimes you just want some casual fun!  HUD\u2122 acknowledges that not every person is ready for a commitment on the first date. That&#39;s why HUD\u2122 is perfect for those looking for short-term flings, polyamory, ethical non-monogamous (ENM) dating, FWB (friends with benefits), casual sex, NSA hookup (no strings attached), a one-night stand, and sexy connections without expectations. Whether you\u2019re travelling, want to keep things light, too busy for a relationship or you\u2019re just coming out of one, HUD\u2122 is the perfect place to find someone. <br>You deserve a casual dating experience that is empowering, judgment-free, and all about your desires. No games, no guilt - just genuine connections with respectful, open-minded singles who embrace your sexuality and boundaries. Meet open-minded singles for safe flirting and zero-strings excitement. <br><br>Flirty Flings, FWB hookups &amp; Dates with HUD\u2122<br> \u2b24 Safe, discreet &amp; fully customizable<br> \u2b24 Female-friendly chat features<br> \u2b24 Video dating app with auto blur safety feature<br> \u2b24 Send and receive videos, photos, and voice messages<br> \u2b24 Photo Protection Blur<br> \u2b24 Advanced match filters<br><br>Looking for an easy way to meet up with locals for a casual hook up? Look no further than HUD\u2122 - the open dating app, for people who want to find local fun dating and excitement. Find hookups tonight!<br><br> --------------------------------<br><br> Subscription Service Terms &amp; Conditions:<br><br> If you choose to purchase HUD\u2122 Premium, payment will be charged to your Google Play account, and your account will be charged for renewal within 24-hours prior to the end of the current period. Your subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period. If you don\u2019t choose to purchase HUD Premium, you can simply continue using HUD for free.<br><br> Privacy Policy: https://www.hudapp.com/#/privacy<br> Terms: https://www.hudapp.com/#/terms",
    "summary": "Hookups & Casual Dating. Hook up with fun adults and have NSA meets as you want",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 375088,
    "score": 3.3304348,
    "ratings": 1816,
    "reviews": 266,
    "histogram": [
        551,
        157,
        109,
        125,
        868
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$7.99 - $149.99 per item",
    "developer": "HUD Android Limited",
    "developerId": "6606706761629671677",
    "developerEmail": "support@hudapp.com",
    "developerWebsite": "https://www.hudapp.com",
    "developerAddress": "Level 11, 19 Victoria Street West, Auckland 1010, New Zealand",
    "privacyPolicy": "https://www.hudapp.com/#/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/AU6JPzFH-QCHjNafVDX-MzFgA4j5L354n3oVtEkz03-Tuob0Qz1N0YhmFyuoQCnCGw",
    "headerImage": "https://play-lh.googleusercontent.com/U2qtY6P5fTwp33ytyGpcE7C298I8IsnMVgDO1viO-oDlIFIX2O10pNXvgEL_QUTl",
    "screenshots": [
        "https://play-lh.googleusercontent.com/FZmoU9KVq7CACxcblw0NuwWqlhPsZM4RSHjxG49EmlCputJPqf2LZlv6FmOtuj2dFN4",
        "https://play-lh.googleusercontent.com/iHE8EJB09wrXyugyyIpukhKTyHMRo5EE-83Au0Yab7MdJ-42rceoFzFRUaMayok_kGc",
        "https://play-lh.googleusercontent.com/AXOIp9VythAu0p_J8EynjDcBs6Z-GlY7AMWWC_YY60BNl1HBCpBBGmIndI4knH-A2co",
        "https://play-lh.googleusercontent.com/WyffWQM1oGKs6HR5-4OHprtotgyJNKRtgs4mAaZMmricKfZkdPgIvHmHWPh7zyIk0t0",
        "https://play-lh.googleusercontent.com/37x4-P-acsjbHC0JFfFOUrnHAB_tBjxWcQe2TI_MkViNWFesYs2ibzlKoiQBwzXCVz1e",
        "https://play-lh.googleusercontent.com/1yUiQNpdoadl69Q-Tai3caNDp5wsDwtJH_arrESHvnbwPMrOyPQdgjJPfpiF1HYqoSyX",
        "https://play-lh.googleusercontent.com/wJWAfxSwmEnPMpzgvfEEc4a24SBKHWsuvS8xT3Po6pvSA_VDG9PqxOO3dv_wqjsXans",
        "https://play-lh.googleusercontent.com/Ol20sBq_Pv6DFXz6WTXoESbT_Hv3sTTpp4zcn90uEvM7NlLhILyh4wEuycI0kfiHxA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 8, 2021",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729120553,
    "version": "9.2.13",
    "comments": [],
    "appId": "co.hud.app",
    "url": "https://play.google.com/store/apps/details?id=co.hud.app&hl=en&gl=us"
}