{
    "title": "Just a Baby: Become a parent",
    "description": "Looking for a sperm donor, egg donor, embryo donor or surrogate? Perhaps someone willing to co-parent? Maybe you can help others start a family?\r\nJust a Baby is the fastest growing community connecting you with thousands of people worldwide open to discussing surrogacy, donation and co-parenting.\r\n\r\nFIND MATCHES AND CHAT\r\nWith Just a Baby, you can find matches and start chatting with potential donors, surrogates or co-parents, bringing you one step closer to achieving your dream of having a baby!\r\n\r\nJUST ONE SWIPE AWAY FROM STARTING A FAMILY\r\nFinding a match has never been easier. To like someone, swipe right, or swipe left to pass. If someone likes you back, it\u2019s a match and we connect you together through chat. Simply swipe, match, and connect until you find the right egg or sperm donor, embryo donor, surrogate or co-parent you\u2019re looking for.\r\n\r\nCONNECT LOCALLY OR GLOBALLY\r\nAdjust the distance of the people you want to match with or filter your search results to find surrogates, sperm, egg and embryo donors around the world.\r\n\r\nGROW YOUR FAMILY YOUR WAY\r\nPeople have different ways of growing and starting a family. Some want to find a donor to conceive, some want to co-parent and others don\u2019t, it\u2019s up to you. You decide how you use Jab to do so.\r\n\r\nOR MAYBE YOU CAN HELP OTHERS?\r\nThousands of couples and singles are struggling to conceive or get pregnant. With JaB, you can help others achieve their dream of having a baby by. Let them know privately and confidentially what you have to offer or let it be known on your profile so the right people can find you.\r\n\r\nUPGRADE FOR MORE!\r\nSubscribe to Just a Baby Plus+ to experience more features like:\r\n\u2022 Unlimited swipes\r\n\u2022 No Ads\r\n\u2022 See those who you liked and who likes you\r\n\u2022 Get free ChattyLikes\r\n\u2022 Put people in your \"Maybe Pile\" and reconsider later\r\n\u2022 Swap photos and files\r\n\u2022 See when your match was last active\r\n\u2022 See chat history of past matches\r\n\u2022 Backtrack to review recent dislikes\r\n\u2022 Masquerade Mode to change your name and protect your privacy\r\n\u2022 Translate profiles of other language\r\n\u2022 Have private pics, revealed only to people you like\r\n\r\nSUBSCRIPTION OPTIONS\r\nJust a Baby Plus+ subscriptions offered:\r\n\u2022 1 week (USD$9.99)\r\n\u2022 1 month (USD$19.99)\r\n\r\nYour Google account will be charged upon purchase. Within at least 24 hours before the end of your current subscription, your subscription is auto-renewed. Subscription can be managed and Auto-renewal can be turned off by going to your Account settings.\r\n\r\nIN-APP PURCHASES\r\nJust a Baby credits are available for purchase within the app. Credits are used to send direct messages to potential donors. 1 credit = 1 message.\r\n\r\n1 JAB Credit $1.99USD\r\n5 JAB Credits $6.99USD\r\n30 JAB Credits $9.99USD\r\n\r\nOTHER THINGS YOU NEED TO KNOW\r\nJust a Baby is safe and secure. You can view our Privacy Policy at https://www.justababy.io/privacy-safety/ & our Terms of Use at https://www.justababy.io/terms-of-service/\r\n\r\nYou must be at least 18 years old to download & use this app\r\n\r\nDOWNLOAD FREE TODAY\r\nBegin your baby journey FREE today and start matching and chatting with Just a Baby!\r\n\r\nWe're always excited to hear from you! If you have any feedback, please mail us at info@justababy.com",
    "descriptionHTML": "Looking for a sperm donor, egg donor, embryo donor or surrogate? Perhaps someone willing to co-parent? Maybe you can help others start a family?<br>Just a Baby is the fastest growing community connecting you with thousands of people worldwide open to discussing surrogacy, donation and co-parenting.<br><br>FIND MATCHES AND CHAT<br>With Just a Baby, you can find matches and start chatting with potential donors, surrogates or co-parents, bringing you one step closer to achieving your dream of having a baby!<br><br>JUST ONE SWIPE AWAY FROM STARTING A FAMILY<br>Finding a match has never been easier. To like someone, swipe right, or swipe left to pass. If someone likes you back, it\u2019s a match and we connect you together through chat. Simply swipe, match, and connect until you find the right egg or sperm donor, embryo donor, surrogate or co-parent you\u2019re looking for.<br><br>CONNECT LOCALLY OR GLOBALLY<br>Adjust the distance of the people you want to match with or filter your search results to find surrogates, sperm, egg and embryo donors around the world.<br><br>GROW YOUR FAMILY YOUR WAY<br>People have different ways of growing and starting a family. Some want to find a donor to conceive, some want to co-parent and others don\u2019t, it\u2019s up to you. You decide how you use Jab to do so.<br><br>OR MAYBE YOU CAN HELP OTHERS?<br>Thousands of couples and singles are struggling to conceive or get pregnant. With JaB, you can help others achieve their dream of having a baby by. Let them know privately and confidentially what you have to offer or let it be known on your profile so the right people can find you.<br><br>UPGRADE FOR MORE!<br>Subscribe to Just a Baby Plus+ to experience more features like:<br>\u2022 Unlimited swipes<br>\u2022 No Ads<br>\u2022 See those who you liked and who likes you<br>\u2022 Get free ChattyLikes<br>\u2022 Put people in your &quot;Maybe Pile&quot; and reconsider later<br>\u2022 Swap photos and files<br>\u2022 See when your match was last active<br>\u2022 See chat history of past matches<br>\u2022 Backtrack to review recent dislikes<br>\u2022 Masquerade Mode to change your name and protect your privacy<br>\u2022 Translate profiles of other language<br>\u2022 Have private pics, revealed only to people you like<br><br>SUBSCRIPTION OPTIONS<br>Just a Baby Plus+ subscriptions offered:<br>\u2022 1 week (USD$9.99)<br>\u2022 1 month (USD$19.99)<br><br>Your Google account will be charged upon purchase. Within at least 24 hours before the end of your current subscription, your subscription is auto-renewed. Subscription can be managed and Auto-renewal can be turned off by going to your Account settings.<br><br>IN-APP PURCHASES<br>Just a Baby credits are available for purchase within the app. Credits are used to send direct messages to potential donors. 1 credit = 1 message.<br><br>1 JAB Credit $1.99USD<br>5 JAB Credits $6.99USD<br>30 JAB Credits $9.99USD<br><br>OTHER THINGS YOU NEED TO KNOW<br>Just a Baby is safe and secure. You can view our Privacy Policy at https://www.justababy.io/privacy-safety/ &amp; our Terms of Use at https://www.justababy.io/terms-of-service/<br><br>You must be at least 18 years old to download &amp; use this app<br><br>DOWNLOAD FREE TODAY<br>Begin your baby journey FREE today and start matching and chatting with Just a Baby!<br><br>We&#39;re always excited to hear from you! If you have any feedback, please mail us at info@justababy.com",
    "summary": "Connecting you with egg & sperm donors, co-parents and surrogates globally",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 134246,
    "score": 4.3333335,
    "ratings": 2571,
    "reviews": 559,
    "histogram": [
        114,
        81,
        246,
        509,
        1614
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $109.99 per item",
    "developer": "Just a Baby Inc.",
    "developerId": "Just+a+Baby+Inc.",
    "developerEmail": "info@justababy.com",
    "developerWebsite": "https://www.justababy.com",
    "developerAddress": "8 The Green, Suite A, Dover, Kent County, Delaware 19901, USA",
    "privacyPolicy": "https://www.justababy.com/privacy-safety/",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/mezLpNX5oq21dGkZB-3Z-jAwbtxicEMmW6jcPGZoU2QAczn4QTsDv4KtumEw6MtQI70",
    "headerImage": "https://play-lh.googleusercontent.com/B3eB7RDW2_LPbSM586tnFE8VEXNLNvz18YxrqYg7HyM8rZ6ho2U9IcyKtRhs2CNp0rI",
    "screenshots": [
        "https://play-lh.googleusercontent.com/elb-qnGKyd7i-OJ3Xymp4daSFA-8VFWtATha-Y3DGWN9n00SB0y7zdLngO_LO7BQfGDp",
        "https://play-lh.googleusercontent.com/j8W4T-C6bkACOurk7OmkoJRLbYx-i0Ab8ZzxoTfg_iL9_vwIjq-MSQ0vOTo0iqBC3Q",
        "https://play-lh.googleusercontent.com/3Az92QyGiXIcEEdENT2ihQ1pGooWcXNonF-jFnD_suqtjNaR5xtGbfmWamJ35XfLYdg",
        "https://play-lh.googleusercontent.com/38tSQDgqtdGhAPQzfiIIEECfF5KVneAsPgsAX8FZHyaUE-whhOU4WK3UeAp0ngKbZDA",
        "https://play-lh.googleusercontent.com/ANdM5ddYyXG_K6M7jn8bKDOKSZut9zldkQzWTzyy0yv1oqihJ_bfJpbSnR-MGqBQ5Hc",
        "https://play-lh.googleusercontent.com/CmnO8LqJFOI4JaQ-wpSqWdwcFEpT_cwyAt6RQb_TT1F6-vs-VZ2Y_83R1vulk0hSPTCG",
        "https://play-lh.googleusercontent.com/iS75puqMDm0SvwWQByTu-xTvFjOcam8ZVQ77WV-lVZaz56Dfsp_oBqQKXouEdXAHEcO-",
        "https://play-lh.googleusercontent.com/5xlKRK3YpTXbEeC-VIDX81jwvLEVacmxAdMms_rITQ9YZ3GXIScjKrFmWzPue91V",
        "https://play-lh.googleusercontent.com/XGl9E_THDsU9QTwuX6Al4VKLKMra00UngntDrVSuNABsPzpGSX8BiHSxnbQGY6RbTQ",
        "https://play-lh.googleusercontent.com/swHb5ATsmO3f_hFaJ-l4Nubdd5kRgXJgYQOl-JKTacP1bBHdBNEqCh7D1BPMKy_qmw",
        "https://play-lh.googleusercontent.com/3vnxdfdA6tKim0HS4zXLWctMrq26D-kPdA5qbt3_6N7dThEWVw0LwJUnnkTBKD91aw",
        "https://play-lh.googleusercontent.com/TYeSNfUeo-t9abKHpBsmvRyb3diZMcjDjg1QKMHXXR3Lj1nywgMq90hh0l-pZJlVDp4",
        "https://play-lh.googleusercontent.com/PWtar2GVn3v77IFLbseJIyTZj_IrssEkxyLkF9y48FHqOwHTjf9VNQGR-yGCMwxZdQ",
        "https://play-lh.googleusercontent.com/kgmEeNNvfCtz1vOapNwBYohDmY7eUNLhsrzWMPabkzve7ARe1i_Wbfo35E6kMyQRsvw",
        "https://play-lh.googleusercontent.com/Ny0iTfnMX6LvGHFBT-DzIdwgXRcVdbArJMD5_g4i1EWuRwjlM7YjE3dNa9XOvHuPiig",
        "https://play-lh.googleusercontent.com/lqHw5H1g55xs1jL7IUjh-HPLGyn5hgk-tXptgEwblwtklkwyfwCexnLzLeoVQ4hnRA",
        "https://play-lh.googleusercontent.com/yymUAbC6ojdGKirdozJwHvuuW3M6nZ30v_yP5F3IKLDPzSUbReWwQwZlUJ1k5t_hOnX1",
        "https://play-lh.googleusercontent.com/-1F6o8heFufxW0H6_koPvU-86ECnU_xM8IKs8nI1P5AVLhfkju-mmF59dFeovHT85CQ",
        "https://play-lh.googleusercontent.com/qCsJxFr7LVRohdIxCcupLC-0XCuDnWPSGG-UkzYo1SCfgDoE1Zc_vaCNrq3JtJQLtvE",
        "https://play-lh.googleusercontent.com/XtsS6jw5FkAPgGknvvZQHHWsL1qaE-svABI0TZgbnGDWbBc_O_W3YIkD-gGnzZ6YsQ",
        "https://play-lh.googleusercontent.com/Iw0brnXApHMdGpO9w_TpBv1vJev2YMXWAAvIXMWwAr2aY5oV55zJXX1f2oL7elx-Jzg",
        "https://play-lh.googleusercontent.com/COresBwx2XLsd2e-k7WBfEg-XxcDHIV1yCZcIOeA9-i6VqYrzkP-IN91rWqgkUBWwQ",
        "https://play-lh.googleusercontent.com/wcxm5l8pF0wkFLCeIKWAtW_piADdRgnZwuGk9P3lnQ1ty7FR6BKKPlhiJ80EtwN9V6Na",
        "https://play-lh.googleusercontent.com/CNitDlz5idpn-kalxuDIg3GdzLCMAnzfvfMRjOEuQ2Bph3wR8oEsDw737xhZkbqKJ5Uy"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 26, 2016",
    "lastUpdatedOn": "Oct 10, 2024",
    "updated": 1728609382,
    "version": "23.10.0",
    "comments": [],
    "appId": "co.justababy.app",
    "url": "https://play.google.com/store/apps/details?id=co.justababy.app&hl=en&gl=us"
}