{
    "title": "Clarify: ADHD Organizer & help",
    "description": "Are you struggling to stay on top of tasks and appointments? Is it difficult to meet deadlines, even when you know they\u2019re important? Does a lack of organization leave you feeling overwhelmed and unaccomplished?\r\nConquer the chaos and embrace a more focused and organized life with Clarify, the ultimate time management app designed for individuals with ADHD, those who suspect they have ADHD, or anyone who wants to improve their executive functioning skills.\r\n\r\nIn a world buzzing with distractions, where time slips away like sand through your fingers, you\u2019re about to embark on the quest of a lifetime. You're setting out to conquer what many deem impossible \u2014 mastering the realms of focus and time management.\r\n\r\nDo you find you have problems with:\r\n- Focus?\r\n- Procrastination?\r\n- Starting tasks?\r\n- Follow through?\r\n- Relationships?\r\n- Organization?\r\n- Impulse control?\r\n\r\nAdults with ADHD face challenges with these and more every day.\r\nYet you hold within you a secret energy source \u2014 a strength that comes from your unique abilities. In Clarify, you will transform your life, not by working against ADHD, but through its very power.\r\n\r\nYOUR FOCUS KEEPER\r\nThrough personalized goal-setting, tailored strategies, and expert guidance, we empower you to take charge of your time and routines to create more productive days.\r\nHere's what you can expect:\r\n\ud83c\udfaf Find Focus: Work with your unique mind to develop strategies for greater productivity\r\n\ud83d\udcab Tune In: Learn how to identify and reduce distractions\r\n\u231b Overcome Procrastination: Explore ways to gamify your To-Do list to effortlessly complete tasks\r\n\ud83d\udee0\ufe0f Skills and Routines: Sculpt your daily routine to sustain long-term growth\r\n\ud83c\udf0d Big Picture: Unleash your true self, embrace your individuality, and let yourself flourish\r\n\r\nLIFE WITH ADHD MADE EASY\r\nClarify is your personal ADHD coach, guiding you through a transformative journey of self-discovery to find greater productivity and focus. Unlike other ADHD planners, it helps you create a sustainable foundation for success with just two simple routines:\r\n\ud83c\udf00 Centering: Start your day with a short centering activity. Benefit from a variety of techniques, such as reflection, planning, guided visualization, meditation, and breathing exercises. Set a positive tone for the day ahead.\r\n\ud83d\ude80 Deep Work: Step into an immersive experience tailored to your tasks. Timers keep you engaged, periodic reminders refocus your attention, and the task completion tracker motivates you to stay on course. Say goodbye to procrastination and unlock your productivity.\r\n\r\nDESIGN YOUR DAY FOR SUCCESS\r\n\u2713 POWERFUL TOOLS: Boost your productivity and enhance your time management skills with customizable To-Do lists, immersive focus mode, and progress trackers. Clarify equips you to stay on top of your busy schedule.\r\n\u2713 EXPERT GUIDANCE: Access evidence-based techniques specifically curated for individuals with ADHD. Our team, including psychologists and coaches, is dedicated to providing you with the most effective strategies for managing ADHD-related challenges and maximizing your potential.\r\n\u2713 PERSONALIZED APPROACH: We understand that everyone's ADHD experience is unique. Clarify tailors its features and recommendations to your preferences. By adapting to your needs, our app ensures a personalized experience.\r\n\u2713 SUPPORTIVE COMMUNITY: Join a vibrant community of individuals who share your struggles and triumphs. Engage in discussions, share tips and success stories, and find inspiration in the journeys of others. Together, we create a space where growth and progress thrive.\r\n\r\nWHO WE ARE\r\nClarify is brought to you by the creators of Fabulous, an award-winning app featured on Lifehacker, the New York Times, Self, Forbes, GirlBoss, and more. Through our apps, we've empowered millions of people worldwide to change their lives for the better.\r\nDare to unleash your superpower. Unlock your full potential.\r\n-------\r\nRead our full terms and conditions and our privacy policy: https://www.thefabulous.co/terms.html",
    "descriptionHTML": "Are you struggling to stay on top of tasks and appointments? Is it difficult to meet deadlines, even when you know they\u2019re important? Does a lack of organization leave you feeling overwhelmed and unaccomplished?<br>Conquer the chaos and embrace a more focused and organized life with Clarify, the ultimate time management app designed for individuals with ADHD, those who suspect they have ADHD, or anyone who wants to improve their executive functioning skills.<br><br>In a world buzzing with distractions, where time slips away like sand through your fingers, you\u2019re about to embark on the quest of a lifetime. You&#39;re setting out to conquer what many deem impossible \u2014 mastering the realms of focus and time management.<br><br>Do you find you have problems with:<br>- Focus?<br>- Procrastination?<br>- Starting tasks?<br>- Follow through?<br>- Relationships?<br>- Organization?<br>- Impulse control?<br><br>Adults with ADHD face challenges with these and more every day.<br>Yet you hold within you a secret energy source \u2014 a strength that comes from your unique abilities. In Clarify, you will transform your life, not by working against ADHD, but through its very power.<br><br>YOUR FOCUS KEEPER<br>Through personalized goal-setting, tailored strategies, and expert guidance, we empower you to take charge of your time and routines to create more productive days.<br>Here&#39;s what you can expect:<br>\ud83c\udfaf Find Focus: Work with your unique mind to develop strategies for greater productivity<br>\ud83d\udcab Tune In: Learn how to identify and reduce distractions<br>\u231b Overcome Procrastination: Explore ways to gamify your To-Do list to effortlessly complete tasks<br>\ud83d\udee0\ufe0f Skills and Routines: Sculpt your daily routine to sustain long-term growth<br>\ud83c\udf0d Big Picture: Unleash your true self, embrace your individuality, and let yourself flourish<br><br>LIFE WITH ADHD MADE EASY<br>Clarify is your personal ADHD coach, guiding you through a transformative journey of self-discovery to find greater productivity and focus. Unlike other ADHD planners, it helps you create a sustainable foundation for success with just two simple routines:<br>\ud83c\udf00 Centering: Start your day with a short centering activity. Benefit from a variety of techniques, such as reflection, planning, guided visualization, meditation, and breathing exercises. Set a positive tone for the day ahead.<br>\ud83d\ude80 Deep Work: Step into an immersive experience tailored to your tasks. Timers keep you engaged, periodic reminders refocus your attention, and the task completion tracker motivates you to stay on course. Say goodbye to procrastination and unlock your productivity.<br><br>DESIGN YOUR DAY FOR SUCCESS<br>\u2713 POWERFUL TOOLS: Boost your productivity and enhance your time management skills with customizable To-Do lists, immersive focus mode, and progress trackers. Clarify equips you to stay on top of your busy schedule.<br>\u2713 EXPERT GUIDANCE: Access evidence-based techniques specifically curated for individuals with ADHD. Our team, including psychologists and coaches, is dedicated to providing you with the most effective strategies for managing ADHD-related challenges and maximizing your potential.<br>\u2713 PERSONALIZED APPROACH: We understand that everyone&#39;s ADHD experience is unique. Clarify tailors its features and recommendations to your preferences. By adapting to your needs, our app ensures a personalized experience.<br>\u2713 SUPPORTIVE COMMUNITY: Join a vibrant community of individuals who share your struggles and triumphs. Engage in discussions, share tips and success stories, and find inspiration in the journeys of others. Together, we create a space where growth and progress thrive.<br><br>WHO WE ARE<br>Clarify is brought to you by the creators of Fabulous, an award-winning app featured on Lifehacker, the New York Times, Self, Forbes, GirlBoss, and more. Through our apps, we&#39;ve empowered millions of people worldwide to change their lives for the better.<br>Dare to unleash your superpower. Unlock your full potential.<br>-------<br>Read our full terms and conditions and our privacy policy: https://www.thefabulous.co/terms.html",
    "summary": "Manage ADHD effortlessly. Your ADHD organizer and planner. Curb procrastination.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 434424,
    "score": 4.0471206,
    "ratings": 4444,
    "reviews": 872,
    "histogram": [
        812,
        160,
        44,
        394,
        3024
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$7.99 - $89.99 per item",
    "developer": "TheFabulous",
    "developerId": "TheFabulous",
    "developerEmail": "hello@thefabulous.co",
    "developerWebsite": "https://www.thefabulous.co",
    "developerAddress": "17 Av de Villiers, 75017, Paris, France",
    "privacyPolicy": "https://www.thefabulous.co/terms.html",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/D-pgjs84StyEL8DrcEGhNiK7X_9465MJYVJ0bYyzlFQdGrmmbfN86740GFYx5m_zOfU",
    "headerImage": "https://play-lh.googleusercontent.com/RNB8TPE25f__EYKLLKvoOiMD2-jvRa-NIXwTSfIYQwm-w3Xku1lZ89e07MjjSRrQsw-o",
    "screenshots": [
        "https://play-lh.googleusercontent.com/z_UW_aY8hv3Y3kTbnOIxoRsmMX5ayaOPvwwy4LzaDLC6H7_e-cLeUm1jxN7udMkpVuM",
        "https://play-lh.googleusercontent.com/HaeDmqSPPyILhWkLOrpdFb5a_D8OMWmSKCNenVmfUp_smRTMb_rJwzITn-pebM40TUzm",
        "https://play-lh.googleusercontent.com/MlBBB1-kI74NEri3mLFBthUeCdNono2X9VVXO8qeanrw5JFJZ35PW5GhDbkyKJj2OQ",
        "https://play-lh.googleusercontent.com/AS4mC9Y8Q9eIodvKw2P4I1i-PXAnur_JK8OZdvUet50AWR9BFRhB8symuTb92igtcBIH",
        "https://play-lh.googleusercontent.com/4iYoejeDQxj58FsQkIeNsdNS6DLWXq-gMOhNE6ljrybiMLQMa0Bl9udwdZ_1PksoQUc"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 25, 2023",
    "lastUpdatedOn": "Oct 23, 2024",
    "updated": 1729678932,
    "version": "6.3",
    "comments": [],
    "appId": "co.thefab.tm",
    "url": "https://play.google.com/store/apps/details?id=co.thefab.tm&hl=en&gl=us"
}