{
    "title": "Pollo Campero, USA",
    "description": "Your life is about to become more flavorful!\r\n\r\nThe Campero app is your ticket to the most flavorful Rewards program. We\u2019ve been serving our one-of-a-kind flavors since 71\u2019 and the Campero app is your one stop shop to get your hands on the delicious golden perfection of our classic fried chicken, the zesty grilled chicken, plus any of our nine unique & savory sides. Don\u2019t forget the empanadas, bowls, sandwiches, and 100% white meat Camperitos!  Download the app, join the #CamperoFamily, and you\u2019ll receive a $10 REWARD just for signing up!\r\n\r\nSkip the line! Order ahead and choose to-go, curbside pickup, drive-thru pickup, or always FREE Delivery just for our Rewards members. Dining in with us? Head straight to your table, open your app, and try out our Digital Table Service.\r\n\r\n\r\nEarn points with every purchase, whether in store or online. Your points will get you Reward credits that can be used for ANYTHING on the menu. Plus, the more points you earn the higher your tier and the higher the Reward credit!\r\n\u2022\t$1 = 10 points\r\n\u2022\tBronze Tier: 1000 points = $10 Reward\r\n\u2022\tSilver Tier: 1000 points = $12 Reward\r\n\u2022\tGold Tier: 1000 points = $14 Reward\r\nSave up your rewards or spend just a fraction of what you've earned. Think about the app as your mobile bank account for delicious chicken!\r\n\r\n\r\nIn addition to Reward credits you\u2019ll have access to:\r\n\u2022\tExclusive offers \r\n\u2022\tSave your favorite meal \r\n\u2022\tA Birthday gift every year \r\n\u2022\tReward credit for referring your friends\r\n\u2022\tThe ability to receive, load, and reload digital gift cards\r\nDownload today and don\u2019t forget to leave us a review!",
    "descriptionHTML": "Your life is about to become more flavorful!<br><br>The Campero app is your ticket to the most flavorful Rewards program. We\u2019ve been serving our one-of-a-kind flavors since 71\u2019 and the Campero app is your one stop shop to get your hands on the delicious golden perfection of our classic fried chicken, the zesty grilled chicken, plus any of our nine unique &amp; savory sides. Don\u2019t forget the empanadas, bowls, sandwiches, and 100% white meat Camperitos!  Download the app, join the #CamperoFamily, and you\u2019ll receive a $10 REWARD just for signing up!<br><br>Skip the line! Order ahead and choose to-go, curbside pickup, drive-thru pickup, or always FREE Delivery just for our Rewards members. Dining in with us? Head straight to your table, open your app, and try out our Digital Table Service.<br><br><br>Earn points with every purchase, whether in store or online. Your points will get you Reward credits that can be used for ANYTHING on the menu. Plus, the more points you earn the higher your tier and the higher the Reward credit!<br>\u2022\t$1 = 10 points<br>\u2022\tBronze Tier: 1000 points = $10 Reward<br>\u2022\tSilver Tier: 1000 points = $12 Reward<br>\u2022\tGold Tier: 1000 points = $14 Reward<br>Save up your rewards or spend just a fraction of what you&#39;ve earned. Think about the app as your mobile bank account for delicious chicken!<br><br><br>In addition to Reward credits you\u2019ll have access to:<br>\u2022\tExclusive offers <br>\u2022\tSave your favorite meal <br>\u2022\tA Birthday gift every year <br>\u2022\tReward credit for referring your friends<br>\u2022\tThe ability to receive, load, and reload digital gift cards<br>Download today and don\u2019t forget to leave us a review!",
    "summary": "Earn points with every dollar you spend!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 162712,
    "score": 3.22,
    "ratings": 455,
    "reviews": 244,
    "histogram": [
        167,
        22,
        22,
        22,
        217
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Pollo Campero USA",
    "developerId": "Pollo+Campero+USA",
    "developerEmail": "pollocamperomobile@gmail.com",
    "developerWebsite": "http://us.campero.com",
    "developerAddress": null,
    "privacyPolicy": "https://us.campero.com/privacy-policy",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ictWxsrnvVpYlD6jUh35RCxtNJxWSMmMLDEiV56rGomy8kxYC2f7-ffRhoEeGlIIbQ",
    "headerImage": "https://play-lh.googleusercontent.com/J6JUSDEmjJa5xViHXd5oBNnokQK-sZ0h5TRSw3EGqU65vq0Wv2YrRzfl06eb6GUWks4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/r58uMlJfkW43rufWPJvG_W44_hWOFl4uizBs5Auc8rQL2q4OYlcrQ0eF6Okv8w5kS7g",
        "https://play-lh.googleusercontent.com/n9l9yQPcjVqPS26cRFxSn06yYTOz5_xxIk5LGSH2WWyEMdKH5oMg8FLui5wS97GdzME",
        "https://play-lh.googleusercontent.com/LDjQQgJhySZXqLyXupLJEKVDyjxHtOnoWSmTStK6RdcoYqO-vE4qh7v7w4sOgGCCJlqf",
        "https://play-lh.googleusercontent.com/jR1bWB1KMwYwz765UkLifzOZtyNYjT9ucFgVMGYrDmUjVg3KZArS6gn-gcPvYNc4zXA",
        "https://play-lh.googleusercontent.com/EeWoyACdJlnbobRgfbTiTGuR5tMCJZVxUCSBtYg5_o0a9W3qOQfTHHpdCJYYGA9_cWI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 4, 2018",
    "lastUpdatedOn": "Jul 26, 2024",
    "updated": 1722030869,
    "version": "2.7",
    "comments": [],
    "appId": "com.pollocampero.app",
    "url": "https://play.google.com/store/apps/details?id=com.pollocampero.app&hl=en&gl=us"
}