{
    "title": "NickWatch",
    "description": "NickWatch, the Nickelodeon smartwatch just for kids, offers trustworthy entertainment and safety features that caregivers love. Nickelodeon characters from Spongebob Squarepants, The Loud House and Teenage Mutant Ninja Turtles inspire fun, independence and creativity!\r\n\r\nThis app is your NickWatch command centre; manage your account, call and chat with devices and access all safety features.\r\n\r\nACCOUNT MANAGEMENT\r\nCreate your account and profile, link NickWatches and manage your subscriptions and billing details.\r\n\r\nFAMILY RING\r\nYour family ring is made up of your children\u2014the NickWatch users\u2014and the adults who care for them. Add and remove members of your family ring, who can then communicate with your linked NickWatches and view their locations via the NickWatch App on their phones. \r\n\r\nGPS LOCATOR\r\nView your children\u2019s locations in real time. Name commonly visited locations like school and home and be notified when your children enter or exit saved places. Adults in your family ring can also choose to share their real-time locations.\r\n\r\nCOMMUNICATION\r\nSend and receive calls and messages between your phone and linked NickWatches. A unique poll message function makes family consensus easy. Track NickWatch battery life so you know when children are out of reach. \r\n\r\nSOS ALERT\r\nReceive emergency alerts from linked NickWatches. End the alert once the emergency has been attended to. \r\n\r\nROUTINE\r\nSet alerts for daily routine activities. You can include as many or as few routine activities as you\u2019d like, including a designated wind-down sequence at the end of the day. Activate quiet mode during school and bedtime so that games and other disruptive features are unavailable. \r\n\r\nMEDIA\r\nView and manage photos taken with linked NickWatches. \r\n\r\nDownload the NickWatch for Caregivers App today to maximize your family\u2019s NickWatch experience!",
    "descriptionHTML": "NickWatch, the Nickelodeon smartwatch just for kids, offers trustworthy entertainment and safety features that caregivers love. Nickelodeon characters from Spongebob Squarepants, The Loud House and Teenage Mutant Ninja Turtles inspire fun, independence and creativity!<br><br>This app is your NickWatch command centre; manage your account, call and chat with devices and access all safety features.<br><br>ACCOUNT MANAGEMENT<br>Create your account and profile, link NickWatches and manage your subscriptions and billing details.<br><br>FAMILY RING<br>Your family ring is made up of your children\u2014the NickWatch users\u2014and the adults who care for them. Add and remove members of your family ring, who can then communicate with your linked NickWatches and view their locations via the NickWatch App on their phones. <br><br>GPS LOCATOR<br>View your children\u2019s locations in real time. Name commonly visited locations like school and home and be notified when your children enter or exit saved places. Adults in your family ring can also choose to share their real-time locations.<br><br>COMMUNICATION<br>Send and receive calls and messages between your phone and linked NickWatches. A unique poll message function makes family consensus easy. Track NickWatch battery life so you know when children are out of reach. <br><br>SOS ALERT<br>Receive emergency alerts from linked NickWatches. End the alert once the emergency has been attended to. <br><br>ROUTINE<br>Set alerts for daily routine activities. You can include as many or as few routine activities as you\u2019d like, including a designated wind-down sequence at the end of the day. Activate quiet mode during school and bedtime so that games and other disruptive features are unavailable. <br><br>MEDIA<br>View and manage photos taken with linked NickWatches. <br><br>Download the NickWatch for Caregivers App today to maximize your family\u2019s NickWatch experience!",
    "summary": "Activate and manage all Nickwatch features with this essential app.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 20783,
    "score": 3.5882354,
    "ratings": 58,
    "reviews": 8,
    "histogram": [
        13,
        0,
        10,
        6,
        27
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "WatchiNU Ltd.",
    "developerId": "WatchiNU+Ltd.",
    "developerEmail": "support@nickwatch.com",
    "developerWebsite": "https://www.nickwatch.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.nickwatch.com/caregiver-app-privacy-policy",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/9oNTcfXbFUTflq-3ZPW2gfOJqKvo153ifHVYpHX_uPIyrkzwxKA6r88R1VlZ-yxjA4Y",
    "headerImage": "https://play-lh.googleusercontent.com/S1y9WHNPMp1nk134JVoZ9YpbWQ91CKZ6364UDQJCqSBS7w19EGSA4a9G1r6cNgQBs9A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/JTaC9wrdPydLJjFK46T_Qdlg263B6MJ39CbOwGwp2pECpn8iYidF46WyS_5SbaL0KQ",
        "https://play-lh.googleusercontent.com/N8LnNq6C5dF5iz8GaxkTDem3NWKA-_4ED3OSLoH9EuonuK84epYmgmnJwfNj-VfaNgg",
        "https://play-lh.googleusercontent.com/XQeepgMDoko1Bw3EkdW-bGPE3Tyu2IgThkWM0nZKx1so5iYYteosU5ePT3GAOXSyOA",
        "https://play-lh.googleusercontent.com/0u42S3MwWw1SYtukXaqsuxuOpK-HovU_VCbu0Q41y2uoXS3YRnn8UgwE20zNM-6iBdk",
        "https://play-lh.googleusercontent.com/122ejQU9AB6skyZ9aINYk5Zv2FqbXJY9Vfinli_q9ShHqN7wB5OYGucmqZbZFQjuTAL2",
        "https://play-lh.googleusercontent.com/M4mXjX339sZX4-A7oKPfFMQFZFNVqOPl8WXk6g3ZOFRfVUPKfKtOvusrAU1umjYShPQ",
        "https://play-lh.googleusercontent.com/MQhrWoCRSCgvpZqd3VxjnkH0Wfsm7tuzt07yv-ZY4rTzW22KoWHGS3xZXYPHTO2GL1fY",
        "https://play-lh.googleusercontent.com/rQ8igtuCLt80dl-B8QQcWioCrE_1NXTcHUTea9UiUb07EPW7wljFyUEnMWBxTbgZBQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 31, 2023",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729494836,
    "version": "1.0.46",
    "comments": [],
    "appId": "com.nickwatch.app",
    "url": "https://play.google.com/store/apps/details?id=com.nickwatch.app&hl=en&gl=us"
}