{
    "title": "Highway Radar",
    "description": "Highway Radar is an application to help drivers be aware of road hazards, cameras, and speed traps. It collects traffic-related information from multiple sources and provides notices on potential risks on the road.\r\n\r\nCrowd-sourced alerts: Highway Radar can connect to a sever aggregating crowd-sourced alerts and show them on the map. It also issues audible voice warnings and optionally a beeper to grab the attention. Currently, the application supports alerting on speed traps and road hazards reports.\r\n\r\nAircraft alerts: In some countries, aircraft traffic enforcement is in use. Highway Radar collects information about air traffic around though various ADS-B exchange sites (ADSBx, OpenSky). Then it matches every aircraft to multiple registration databases and alerts drivers only on those which can potentially do traffic enforcement.\r\n\r\nHistorical data analysis: Highway Radar aggregates data about past police and speed trap reports and estimates the risk of a given area being heavily patrolled. The app also features a heat map that shows places with especially frequent speed trap reports.\r\n\r\nSpeed and red-light cameras: Highway Radar can warn the driver when approaching a traffic camera. This feature is available in the USA and Canada only.\r\n\r\nExtra features: Highway Radar can also show you traffic jams on nearby streets and a weather radar information around you.\r\n\r\nNOTE: This application can use accessibility service to launch other application on service start, including activating split-screen mode or preloading the application. The accessibility service isn't used for anything else but launching other applications upon service start, and only if Highway Radar is configured to do so. No data is accessed, collected, or shared in any way though the accessibility service.",
    "descriptionHTML": "Highway Radar is an application to help drivers be aware of road hazards, cameras, and speed traps. It collects traffic-related information from multiple sources and provides notices on potential risks on the road.<br><br>Crowd-sourced alerts: Highway Radar can connect to a sever aggregating crowd-sourced alerts and show them on the map. It also issues audible voice warnings and optionally a beeper to grab the attention. Currently, the application supports alerting on speed traps and road hazards reports.<br><br>Aircraft alerts: In some countries, aircraft traffic enforcement is in use. Highway Radar collects information about air traffic around though various ADS-B exchange sites (ADSBx, OpenSky). Then it matches every aircraft to multiple registration databases and alerts drivers only on those which can potentially do traffic enforcement.<br><br>Historical data analysis: Highway Radar aggregates data about past police and speed trap reports and estimates the risk of a given area being heavily patrolled. The app also features a heat map that shows places with especially frequent speed trap reports.<br><br>Speed and red-light cameras: Highway Radar can warn the driver when approaching a traffic camera. This feature is available in the USA and Canada only.<br><br>Extra features: Highway Radar can also show you traffic jams on nearby streets and a weather radar information around you.<br><br>NOTE: This application can use accessibility service to launch other application on service start, including activating split-screen mode or preloading the application. The accessibility service isn&#39;t used for anything else but launching other applications upon service start, and only if Highway Radar is configured to do so. No data is accessed, collected, or shared in any way though the accessibility service.",
    "summary": "Helps with spotting speed traps and road hazards early",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 96414,
    "score": 4.36,
    "ratings": 328,
    "reviews": 113,
    "histogram": [
        25,
        19,
        12,
        19,
        248
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Highway Radar",
    "developerId": "6758836631318852759",
    "developerEmail": "info@highwayradar.com",
    "developerWebsite": "https://highwayradar.com/",
    "developerAddress": "30 N Gould St Ste N\nSheridan, WY 82801",
    "privacyPolicy": "https://highwayradar.com/privacy/",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/EOPdBuu5tlWV4Z92FR-pFvcovI6Qg0xFnYp4p70Z5RnB9L7_yrTmMy6w5lStnMcLf4a6",
    "headerImage": "https://play-lh.googleusercontent.com/HkRkMxjOr_MAEnnCK1rbtlMqvbzOhlP0qgzW_5us_v_RwOje3Ffbi2pxW-uKHUZw1A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/URWILeHRw7zhOvbvFGM2ySDtX5AzcXVQY0qmiViUyilm-_LWZM0AUPkI8Ww3HSny4kJK",
        "https://play-lh.googleusercontent.com/34RzH6fnBbe6XrrkbtXwAVY26m-iIZSi29s_-Om_0M9qm7_eHN4uhzfHFRDyUncmgJn9",
        "https://play-lh.googleusercontent.com/rVHDMsh65lMhgxCjUW1-B95kIWBjwyVPf0-xGaLCU1G4NGFcF71IQHNJGmssvkesIEwE",
        "https://play-lh.googleusercontent.com/UeK9uCDsCwc_ghmIAJSGixwayj35tuxUgYjqMCJPEAAHmoKWPnXEN_pcHcdZHwotgg8",
        "https://play-lh.googleusercontent.com/0v45iA7i1i-GmI7FXBhvgr-DQJ8os1ERayrIrFmlzFAWNYNDWPbECRmrFJMCAmW6Dw",
        "https://play-lh.googleusercontent.com/QSNUw7P3BraKOM_skHusfpZD4cZFFJZiicvj1BffkozkMkkeZg4OFNLCCoahgzv8UcY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 2, 2019",
    "lastUpdatedOn": "Jun 8, 2024",
    "updated": 1717894849,
    "version": "3.1.1 (update 2)",
    "comments": [],
    "appId": "com.highwayradar.app",
    "url": "https://play.google.com/store/apps/details?id=com.highwayradar.app&hl=en&gl=us"
}