{
    "title": "Hily Dating app: Meet & Date",
    "description": "On Hily dating app, date as you are. \u0421hat with singles, flirt online, meet people and connect with local singles for real. Because dating apps work wonders when you let yourself be real.\r\n\r\nMutual connections are so easy to establish on Hily. Just make your dating profile match your personality\u2014and find a compatible date! Don't know how to start? Use our profile tips and rely on icebreakers and compatibility checks to chat and flirt. Finding love or a relationship may not be the ultimate goal. But meeting people to meet your true self surely is.\r\n\r\n<b>Check out Hily's star dating features:</b>\r\n\ud83d\udc9c Compatibility Quiz to make pure harmony chances in our app\r\n\ud83d\udc9c Fun zodiac synastry test to see if your stars align\r\n\ud83d\udc9c Safety checks before you come to meet new people\r\n\ud83d\udc9c Photo and profile tips to find a date with no stress\r\n\ud83d\udc9c Personalized icebreakers to chat and flirt like a pro\r\n\r\nWe believe that dating apps should make online dating easy and fun. Just use Hily as you like and date as you are, and you\u2019ll meet new people amid plenty of connections. Get the app, build your profile, chat with locals whom you\u2019d like to meet up in real life \u2013 and get the relationships you\u2019re looking for! You can chat for true love, enjoy short-term fun, or just network and meet up with local singles.\r\n\r\n<b>\ud83d\udc40 Stay in touch with us!</b>\r\n\u2b50\ufe0f To learn more, go to Hily website https://hily.com\r\n\u2b50\ufe0f Share your experience by leaving your feedback at apps@corp.hily.com\r\n\u2b50\ufe0f If you\u2019re worried about whether you can use dating apps safely, take a look at our Terms of Service at https://hily.com/terms and Privacy Policy at https://hily.com/privacypolicy\r\n\r\nWe want dating apps to be fun again. And we believe there is no other way to date and meet people for real than being your authentic self. So hop on real dating fun with us! Are you in the mood to chat or flirt? Get the Hily dating app to enjoy the ride on your terms!",
    "descriptionHTML": "On Hily dating app, date as you are. \u0421hat with singles, flirt online, meet people and connect with local singles for real. Because dating apps work wonders when you let yourself be real.<br><br>Mutual connections are so easy to establish on Hily. Just make your dating profile match your personality\u2014and find a compatible date! Don&#39;t know how to start? Use our profile tips and rely on icebreakers and compatibility checks to chat and flirt. Finding love or a relationship may not be the ultimate goal. But meeting people to meet your true self surely is.<br><br><b>Check out Hily&#39;s star dating features:</b><br>\ud83d\udc9c Compatibility Quiz to make pure harmony chances in our app<br>\ud83d\udc9c Fun zodiac synastry test to see if your stars align<br>\ud83d\udc9c Safety checks before you come to meet new people<br>\ud83d\udc9c Photo and profile tips to find a date with no stress<br>\ud83d\udc9c Personalized icebreakers to chat and flirt like a pro<br><br>We believe that dating apps should make online dating easy and fun. Just use Hily as you like and date as you are, and you\u2019ll meet new people amid plenty of connections. Get the app, build your profile, chat with locals whom you\u2019d like to meet up in real life \u2013 and get the relationships you\u2019re looking for! You can chat for true love, enjoy short-term fun, or just network and meet up with local singles.<br><br><b>\ud83d\udc40 Stay in touch with us!</b><br>\u2b50\ufe0f To learn more, go to Hily website https://hily.com<br>\u2b50\ufe0f Share your experience by leaving your feedback at apps@corp.hily.com<br>\u2b50\ufe0f If you\u2019re worried about whether you can use dating apps safely, take a look at our Terms of Service at https://hily.com/terms and Privacy Policy at https://hily.com/privacypolicy<br><br>We want dating apps to be fun again. And we believe there is no other way to date and meet people for real than being your authentic self. So hop on real dating fun with us! Are you in the mood to chat or flirt? Get the Hily dating app to enjoy the ride on your terms!",
    "summary": "Dating app to date as you are: meet people to chat, flirt, connect, and have fun",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 17363270,
    "score": 4.2206473,
    "ratings": 166186,
    "reviews": 24994,
    "histogram": [
        25744,
        2638,
        3125,
        12363,
        122309
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $299.99 per item",
    "developer": "Hily Corp.",
    "developerId": "8466050068348543977",
    "developerEmail": "apps@corp.hily.com",
    "developerWebsite": "http://hily.com",
    "developerAddress": "Hily Corp.\nRegistered office: Suite 1410, Farmers Bank Building, 301 North Market Street, County of New Castle, Wilmington, Delaware 19801.\nZip 19801",
    "privacyPolicy": "https://hily.com/privacypolicy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/5wMyhCW-kb9mIgMv2q7AG08FT3121_xXdlc8JPtpuUFBcOjQFMuNUFtA2UpVsTW7Eio",
    "headerImage": "https://play-lh.googleusercontent.com/ACqwoZ3SjjoTqJcPeU7fSQ-gMy7THixMnKlS8PQ3afpQr1tdHhLPpjd-bYMxRA10-6U",
    "screenshots": [
        "https://play-lh.googleusercontent.com/RWJmVoRunLtcXrrSK_FtWGLCI4gr5B68-VmGLPP_5ZY5G0grZ8JUQ-J4Q8XD3WAqPX4",
        "https://play-lh.googleusercontent.com/MEDiuLoBAfJO6kPwkeyR4MnUXuBb0TtUGvp_MeCcGRlDOSYg3o361g283CmVGvb_RU8",
        "https://play-lh.googleusercontent.com/9Lck18ZooHXEu3XaUG63DOd0-TgyhMTY5LhuDtUEmuwESvkc1Yeu8z9Dr2inRvwpIcU",
        "https://play-lh.googleusercontent.com/O5CauJqgnjkr5o0-VXyn8UA2b6sETayJeuSoGOfdIk8C8pMHSAbwY1nvgxVsFzf5IQ",
        "https://play-lh.googleusercontent.com/Uaq4x87SY8igBCOy1Ac8JWEjNkCFa1vYZgc0Hs6SnZ_BVJFT281UUULgQ5GpxFjQ964",
        "https://play-lh.googleusercontent.com/vmDsjEdcu0DlOLWEIZGIQR82Ew7OHV901tVWcd7VUrU6d1OFq_0VVwtbXS-3T-mELvw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 16, 2018",
    "lastUpdatedOn": "Oct 23, 2024",
    "updated": 1729699960,
    "version": "4.1.3.1",
    "comments": [],
    "appId": "com.hily.app",
    "url": "https://play.google.com/store/apps/details?id=com.hily.app&hl=en&gl=us"
}