{
    "title": "FanDuel Fantasy Football",
    "description": "FanDuel Fantasy Football lets you make every moment more all season long! Draft your favorite players into your lineup for a chance to win real money prizes all season long! FanDuel gets you in on the daily and nightly action for NFL, MLB, NCAAF, NBA, PGA, NHL, UFC, Soccer, and more! Want to create your own fantasy league? Build your custom contest on FanDuel, invite your friends, and play for real cash! Make sure to check out FanDuel for our latest promotions and bonuses for both new and returning fantasy players!\r\n\r\n\r\nGet full scores, news, data, and daily coverage of NFL, MLB, NBA, NCAA, NHL, Premier League Soccer and Champions League Soccer. Join the fun and start on the path to winning cash today!\r\n\r\n\r\nWhether your game is football, baseball, basketball, golf, or soccer, FanDuel has daily and weekly contests you\u2019ll love. Plus, you have your own choice of contest options, from world-famous tournaments to beginner contests \u2014 where there are no experienced players allowed.\r\n\r\nFanDuel even lets you enter free games year round featuring all your favorite sports for a chance to win big prizes!\r\n\r\nWHY YOU\u2019LL LOVE FANDUEL:\r\n\r\n\r\n- The choice is yours \u2013 Play Single Game and daily contests for NFL, MLB, NBA, PGA. NHL, EPL and UCL soccer, and many more fantasy sports you love\r\n\r\n\r\n- Cash prizes are waiting for you \u2013 Draft your fantasy lineup, track your scores and compete daily for prizes in one of our many fantasy contests\r\n\r\n\r\n- You don\u2019t have to commit to season-long play \u2013 Make last-minute changes and draft the perfect team. Our Late Swap contests let you adjust the players on your roster right until their individual games start\r\n\r\n-Live draft - every game day - with Daily Snake Drafts! Play with friends or enter a public contest for your chance to win real cash prizes. Draft the best players available with no salary caps. Available now for the NFL, NBA, MLB, NHL, and PGA.\r\n \r\n- Share the fun with your friends \u2013 Our Friends Mode is a new take on the \u201ctraditional\u201d fantasy league that lets you play FanDuel with your friends all season long. Create your league, draft teams, track live scoring, and keep track of rankings among your friends. Now is the perfect time to try daily fantasy! (For more details, see FanDuel.com)\r\n\r\n\r\nJOIN MILLIONS OF OTHER FANS ACROSS THE COUNTRY\r\n\r\n\r\nAs featured in ESPN, Sports Illustrated, The New York Times, The Wall Street Journal and Yahoo Sports.\r\n\r\n\r\nUS residents only. Users must be 18 or older (19 or older in AL, 21 or older in AZ, IA, LA, MA). Users physically located in DE, ID, HI, MT, NV, and WA are not eligible to participate in paid contests. FanDuel makes no representation that participation in paid entry fantasy sports contests is lawful under Texas state law. Additional state limitations may apply.\r\n\r\n\r\n\r\nAt FanDuel, we are committed to protecting our players and helping them manage their play in a responsible manner. We offer proactive tools, resources, and support to encourage healthy player behavior and deliver positive player experiences. For more information, visit https://www.fanduel.com/responsibleplay or the \"\"Responsible Play\"\" item in the account menu. For California privacy rights, see the Privacy link in our App Menu after Download.\r\n\r\n\r\n\r\nhttps://www.FanDuel.com/terms\r\n\r\n\r\nhttps://www.FanDuel.com/privacy",
    "descriptionHTML": "FanDuel Fantasy Football lets you make every moment more all season long! Draft your favorite players into your lineup for a chance to win real money prizes all season long! FanDuel gets you in on the daily and nightly action for NFL, MLB, NCAAF, NBA, PGA, NHL, UFC, Soccer, and more! Want to create your own fantasy league? Build your custom contest on FanDuel, invite your friends, and play for real cash! Make sure to check out FanDuel for our latest promotions and bonuses for both new and returning fantasy players!<br><br><br>Get full scores, news, data, and daily coverage of NFL, MLB, NBA, NCAA, NHL, Premier League Soccer and Champions League Soccer. Join the fun and start on the path to winning cash today!<br><br><br>Whether your game is football, baseball, basketball, golf, or soccer, FanDuel has daily and weekly contests you\u2019ll love. Plus, you have your own choice of contest options, from world-famous tournaments to beginner contests \u2014 where there are no experienced players allowed.<br><br>FanDuel even lets you enter free games year round featuring all your favorite sports for a chance to win big prizes!<br><br>WHY YOU\u2019LL LOVE FANDUEL:<br><br><br>- The choice is yours \u2013 Play Single Game and daily contests for NFL, MLB, NBA, PGA. NHL, EPL and UCL soccer, and many more fantasy sports you love<br><br><br>- Cash prizes are waiting for you \u2013 Draft your fantasy lineup, track your scores and compete daily for prizes in one of our many fantasy contests<br><br><br>- You don\u2019t have to commit to season-long play \u2013 Make last-minute changes and draft the perfect team. Our Late Swap contests let you adjust the players on your roster right until their individual games start<br><br>-Live draft - every game day - with Daily Snake Drafts! Play with friends or enter a public contest for your chance to win real cash prizes. Draft the best players available with no salary caps. Available now for the NFL, NBA, MLB, NHL, and PGA.<br> <br>- Share the fun with your friends \u2013 Our Friends Mode is a new take on the \u201ctraditional\u201d fantasy league that lets you play FanDuel with your friends all season long. Create your league, draft teams, track live scoring, and keep track of rankings among your friends. Now is the perfect time to try daily fantasy! (For more details, see FanDuel.com)<br><br><br>JOIN MILLIONS OF OTHER FANS ACROSS THE COUNTRY<br><br><br>As featured in ESPN, Sports Illustrated, The New York Times, The Wall Street Journal and Yahoo Sports.<br><br><br>US residents only. Users must be 18 or older (19 or older in AL, 21 or older in AZ, IA, LA, MA). Users physically located in DE, ID, HI, MT, NV, and WA are not eligible to participate in paid contests. FanDuel makes no representation that participation in paid entry fantasy sports contests is lawful under Texas state law. Additional state limitations may apply.<br><br><br><br>At FanDuel, we are committed to protecting our players and helping them manage their play in a responsible manner. We offer proactive tools, resources, and support to encourage healthy player behavior and deliver positive player experiences. For more information, visit https://www.fanduel.com/responsibleplay or the &quot;&quot;Responsible Play&quot;&quot; item in the account menu. For California privacy rights, see the Privacy link in our App Menu after Download.<br><br><br><br>https://www.FanDuel.com/terms<br><br><br>https://www.FanDuel.com/privacy",
    "summary": "NFL Fantasy Football is back! Draft your lineup for a chance to win cash prizes.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4049429,
    "score": 4.7234154,
    "ratings": 89916,
    "reviews": 14843,
    "histogram": [
        1930,
        456,
        1940,
        11892,
        73693
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "FanDuel",
    "developerId": "FanDuel",
    "developerEmail": "support@fanduel.com",
    "developerWebsite": "http://www.fanduel.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.fanduel.com/privacy",
    "genre": "Sports",
    "genreId": "SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/AaPWTeiINX32xe4q2zfcJbSWJU5PyCyZR2urH_EdwEkiku-pHumrx_Rx9QtIRTohfG0",
    "headerImage": "https://play-lh.googleusercontent.com/mwL8T-6ElfDFRzBvR1IC0fPajxUZ-DhMRDX2_HrNVreFCL3dyzISqT88mSRmuzP3PSMH",
    "screenshots": [
        "https://play-lh.googleusercontent.com/xYtWspsGbiTdotbUEPOIX70FLkVAr1dqA31s9kWztD0vMkaMuDVxHuRFJnCz4SzChto",
        "https://play-lh.googleusercontent.com/9xjGKap9St0q1Cuc_YpeiUNyw6UsPEdxzlSLRebjgk1hfAG6fzs8KfqhLt_fVxgqD3zv",
        "https://play-lh.googleusercontent.com/mhtds4AnWXiYhWhssPu1Bx4kSBuFE0ixARHgmOammrr0PEza6MGpffQbQIMfGLWSwn3P",
        "https://play-lh.googleusercontent.com/YHLSMZPDHBBW0ZEnfNuoX6Z5ft0xSAEO4ftJA0uZHpwhvgOnlBo0H1wt0NKsHBvHeCE",
        "https://play-lh.googleusercontent.com/Mk4HQm-KJNcqgwh57V3nkkHmrk3B7IMl1kf45UZkt187cAkcp77VlLfHbBOIFTDIzEY",
        "https://play-lh.googleusercontent.com/qIGKm3YWjECsKnxZbY92_fRfxL-01Ks3fSZ48WzyZ5RalgiLU56koAEL4ut6oi360fc",
        "https://play-lh.googleusercontent.com/6bpsBV09kymNjQuy4MxGhW8UwlOECfVQvaeQh7vK78XWMMq1oFVaiEY6eX0-HxydHA"
    ],
    "video": "https://www.youtube.com/embed/ykzpMSJYYrU?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/mwL8T-6ElfDFRzBvR1IC0fPajxUZ-DhMRDX2_HrNVreFCL3dyzISqT88mSRmuzP3PSMH",
    "contentRating": "Adults only 18+",
    "contentRatingDescription": "Cash Prizes",
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 4, 2015",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729260212,
    "version": "4.11",
    "comments": [],
    "appId": "com.fanduel.android.self",
    "url": "https://play.google.com/store/apps/details?id=com.fanduel.android.self&hl=en&gl=us"
}