{
    "title": "Asana: Work in one place",
    "description": "Asana is the easiest way to manage team projects and your individual tasks. From the small stuff to the big picture, Asana organizes work so you and your teams are clear on what to do, when to do it, and how to get it done.\r\n\r\n\u2713 USE ASANA WHEREVER YOU ARE \r\nAccess Asana on mobile or on the web. Project management doesn\u2019t stop at your desk\u2014no matter where you are, stay focused and keep your team\u2019s work on track. \r\n\r\n\u2713 GET ORGANIZED \r\nSet up different projects to bring your team\u2019s work together in one shared space.  Break the workload down into manageable tasks  and give them a clear owner and due date.  Choose a project view that suits your style\u2014lists, kanban boards, or calendar.\r\n\r\n\u2713 IMPROVE FOCUS\r\nBoost your productivity with My Tasks, where you can see all the work that\u2019s been assigned to you in one to-do list. Prioritize your work easily\u2014drag & drop tasks into Asana\u2019s built-in sections, create your own custom checklist sections, or sort by different dimensions.  \r\n\r\n\u2713 STAY CONNECTED\r\nKeep collaboration going, wherever you are. Communicate with your teammates by liking, commenting, or attaching files directly to tasks.  And get automatic updates about the projects and tasks that matter to you delivered directly to your Inbox.  \r\n\r\n\u2713 AND DO EVEN MORE\u2014 ALL WITH ONE TOOL\r\nVisit the web app to see how all of your projects are progressing with Portfolios. Personalize task management with Custom Fields to capture important information about your tasks. Choose timeline view for projects to see a Gantt chart with task dependencies. And unlock the ability to track company goals and milestones with Goals.\r\n\r\nJoin more than 100,000 organizations and millions of users worldwide who trust Asana to stay organized and in control of their work. \r\n\r\nAsana\u2019s WORK GRAPH\u2122\ufe0f represents every task, project, and goal in your organization. Which means the Work Graph\u2122\ufe0f creates integrity, visibility, and coordination between every team and every department. All in one place.\r\n\r\nDownload the Asana work management app now.  \r\n\r\nBy downloading Asana, you agree to our Terms of Service, which you can find at https://asana.com/terms.",
    "descriptionHTML": "Asana is the easiest way to manage team projects and your individual tasks. From the small stuff to the big picture, Asana organizes work so you and your teams are clear on what to do, when to do it, and how to get it done.<br><br>\u2713 USE ASANA WHEREVER YOU ARE <br>Access Asana on mobile or on the web. Project management doesn\u2019t stop at your desk\u2014no matter where you are, stay focused and keep your team\u2019s work on track. <br><br>\u2713 GET ORGANIZED <br>Set up different projects to bring your team\u2019s work together in one shared space.  Break the workload down into manageable tasks  and give them a clear owner and due date.  Choose a project view that suits your style\u2014lists, kanban boards, or calendar.<br><br>\u2713 IMPROVE FOCUS<br>Boost your productivity with My Tasks, where you can see all the work that\u2019s been assigned to you in one to-do list. Prioritize your work easily\u2014drag &amp; drop tasks into Asana\u2019s built-in sections, create your own custom checklist sections, or sort by different dimensions.  <br><br>\u2713 STAY CONNECTED<br>Keep collaboration going, wherever you are. Communicate with your teammates by liking, commenting, or attaching files directly to tasks.  And get automatic updates about the projects and tasks that matter to you delivered directly to your Inbox.  <br><br>\u2713 AND DO EVEN MORE\u2014 ALL WITH ONE TOOL<br>Visit the web app to see how all of your projects are progressing with Portfolios. Personalize task management with Custom Fields to capture important information about your tasks. Choose timeline view for projects to see a Gantt chart with task dependencies. And unlock the ability to track company goals and milestones with Goals.<br><br>Join more than 100,000 organizations and millions of users worldwide who trust Asana to stay organized and in control of their work. <br><br>Asana\u2019s WORK GRAPH\u2122\ufe0f represents every task, project, and goal in your organization. Which means the Work Graph\u2122\ufe0f creates integrity, visibility, and coordination between every team and every department. All in one place.<br><br>Download the Asana work management app now.  <br><br>By downloading Asana, you agree to our Terms of Service, which you can find at https://asana.com/terms.",
    "summary": "Get to your goals faster",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 6876774,
    "score": 4.3661766,
    "ratings": 43541,
    "reviews": 3000,
    "histogram": [
        4352,
        1406,
        1215,
        3517,
        33039
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Asana, Inc.",
    "developerId": "Asana,+Inc.",
    "developerEmail": "mobile-feedback@support.asana.com",
    "developerWebsite": "https://asana.com/product",
    "developerAddress": null,
    "privacyPolicy": "http://www.asana.com/privacy",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/SWbS8z3NqFVHCEQc_6l-ZDdDj5qPGrWSK8hEWRSPHYm9s8958y6nTnoLolVHXlgKfXw",
    "headerImage": "https://play-lh.googleusercontent.com/IHdMoqelbKranvPvQgCmKK1RD6V4e2angPBpje6wupS6-mmTkamMmOsi5cPljs-wW453",
    "screenshots": [
        "https://play-lh.googleusercontent.com/5uPvE1w-2LQEpwK90ith7MAKVCKVTMKG7hIV1bhKUtsqB6n3dMo1QIxRKrsKRFuafiA5",
        "https://play-lh.googleusercontent.com/ZSRUkx5SOsiH2dbFiKGyO-bB0QJBwBkaElESa7PXEnxF4k53L7VO8nBK2o4HZTt97w",
        "https://play-lh.googleusercontent.com/lWSlJsceo1HpJwjU-OtWWevb-sBS78m_QczP_NMPL4QSNcyhQ5bYfN7jNWv3qCQLkhc",
        "https://play-lh.googleusercontent.com/jrg-gshdCvctrvuJF7dF--bLeYsAKR6o_l15F7dfI9eKHrnn_Q3HhgHl6bF7GmB213Nk",
        "https://play-lh.googleusercontent.com/nCQOysjslWi60O9Nbn3etmUV1y_5pYcc-62LilwsiWcZc4by8mptIGlFkv5ShEArT47n",
        "https://play-lh.googleusercontent.com/yMVef4CoG4gGSSJGdQmMIFsaYlPyYHZt34HS_ji4JWqXqXDUFWDRtuhsCP--frurSg",
        "https://play-lh.googleusercontent.com/TvdbZNMLJbwaettngwQtKLd4bKOvidJ04rmsvieOUlJQy4Ol6ReQUfy8kRTkaZUoQ-xR",
        "https://play-lh.googleusercontent.com/44QkenLyFXLzOiOE6TVT3MVAeiYZbJm-ESciuuHFphzAAsfq-HKsJJbPemE6DRq_Wqw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 27, 2013",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729271175,
    "version": "8.17.2",
    "comments": [],
    "appId": "com.asana.app",
    "url": "https://play.google.com/store/apps/details?id=com.asana.app&hl=en&gl=us"
}