{
    "title": "Robokiller - Spam Call Blocker",
    "description": "Block spam calls with Robokiller, the spam call blocker that eliminates 99% of unwanted phone calls. No robocall stands a chance against Robokiller\u2019s algorithm, which protects you against over 1 billion scams in our global database. \r\n\r\nUse Robokiller as the default SMS app. Robokiller blocks 99% of spam text messages so you only receive the ones you desire.\r\n\r\nBlock telemarketers\u2019 spam with Robokiller. Any phone call with an unknown caller ID will be marked as spam - with the help of our number-blocking, audio fingerprinting technology.\r\n\r\nYou can add unwanted callers to your blocklist, customizing your level of spam blocking. Block spammers on your own terms - get good calls only\u00ae and never miss an important call with our powerful spam blocker app.\r\n\r\nRobokiller provides peace of mind, blocking annoying scam calls and preventing costly losses to fraud. The average scam costs $1,464*, but with our spam blocker you won\u2019t be the next victim. Robokiller lets you get robocall revenge:registered: on unwanted callers with answer bots, that intercept calls and play hilarious pre-recorded audio.\r\n\r\nMESSAGING:\r\n- Use Robokiller as your primary text messaging app to seamlessly send and receive messages.\r\n- Automatically block spam, scam, and telemarketing texts using our secure technology. \r\n- Customize who can and can\u2019t reach you with block & safe filters.\r\n\r\nBLOCK SPAM CALLS:\r\n- Reduce unwanted calls by 99% in your first 30 days of using our spam filter.\r\n- Our blocklist updates automatically to ensure the most up-to-date protection.\r\n- Block robocalls and phone calls you don\u2019t want, keep the number blocked for as long as you wish.\r\n\r\nCONTROL WHO CAN & CAN\u2019T REACH YOU:\r\n- Keep your contacts or any new number safe in your allow list.\r\n- View the number you\u2019ve missed in your calls list.\r\n- Pause call blocking - temporarily disable our spam blocking function if you\u2019re expecting an important call from an unknown number, then continue to block calls when you\u2019re ready.\r\n\r\nKEEP YOUR PERSONAL INFO PRIVATE:\r\n- New personal data protection feature helps you reclaim your privacy.\r\n- Scan the web to help you find and remove your private info from public search sites where it\u2019s sold and used for spam calls, identity theft and more.\r\n- Take your info off the market and use our ongoing monitoring to notify you of any new exposures.\r\n\r\nSCREEN PHONE CALLS IN REAL TIME:\r\n- Screen callers by asking them to identify themselves before your phone rings with our automatic answering service.\r\n- Get transcriptions of the caller\u2019s response in real-time: We deliver the call screening report as your device is ringing.\r\n\r\nFIGHT SPAM WITH ANSWER BOTS:\r\n- Send spammers to lengthy recordings provided by Robokiller.\r\n- Choose from a variety of Answer Bots that will give spammers a taste of their own medicine, blocking them in style.\r\n- Enjoy listening to blocked & recorded calls.\r\n\r\nREPORT SPAMMERS:\r\n- Join the fight against robocalls by reporting any specific number or unknown caller.\r\n- Check the scam activity in your state: Be aware of the top scams in your area.\r\n- Contact our dedicated customer service team 24/7 regarding any issues with our spam call blocker app.\r\n\r\nRobokiller is an award-winning spam blocker built by people who hate robocalls and respect privacy. Our mission is to stop robocalls forever.\r\n\r\nThis app has been featured by The New York Times, NBC, Wired, Engadget, Vice, and other publications.\r\n\r\nRobokiller is free to download. A subscription is required to use the service, but you can try it free for 7 days. Once your trial ends, your subscription will automatically renew. You can cancel your subscription at any time.\r\n\r\nAnswer your phone without fear thanks to Robokiller, the spam call blocker app made to give you peace of mind.\r\n\r\nTerms of Service: https://www.robokiller.com/terms.html\r\nPrivacy Policy: https://www.robokiller.com/privacy.html\r\nCalifornia Privacy Notice: https://robokiller.com/privacy.html#section-8\r\n\r\n*According to FTC estimates",
    "descriptionHTML": "Block spam calls with Robokiller, the spam call blocker that eliminates 99% of unwanted phone calls. No robocall stands a chance against Robokiller\u2019s algorithm, which protects you against over 1 billion scams in our global database. <br><br>Use Robokiller as the default SMS app. Robokiller blocks 99% of spam text messages so you only receive the ones you desire.<br><br>Block telemarketers\u2019 spam with Robokiller. Any phone call with an unknown caller ID will be marked as spam - with the help of our number-blocking, audio fingerprinting technology.<br><br>You can add unwanted callers to your blocklist, customizing your level of spam blocking. Block spammers on your own terms - get good calls only\u00ae and never miss an important call with our powerful spam blocker app.<br><br>Robokiller provides peace of mind, blocking annoying scam calls and preventing costly losses to fraud. The average scam costs $1,464*, but with our spam blocker you won\u2019t be the next victim. Robokiller lets you get robocall revenge:registered: on unwanted callers with answer bots, that intercept calls and play hilarious pre-recorded audio.<br><br>MESSAGING:<br>- Use Robokiller as your primary text messaging app to seamlessly send and receive messages.<br>- Automatically block spam, scam, and telemarketing texts using our secure technology. <br>- Customize who can and can\u2019t reach you with block &amp; safe filters.<br><br>BLOCK SPAM CALLS:<br>- Reduce unwanted calls by 99% in your first 30 days of using our spam filter.<br>- Our blocklist updates automatically to ensure the most up-to-date protection.<br>- Block robocalls and phone calls you don\u2019t want, keep the number blocked for as long as you wish.<br><br>CONTROL WHO CAN &amp; CAN\u2019T REACH YOU:<br>- Keep your contacts or any new number safe in your allow list.<br>- View the number you\u2019ve missed in your calls list.<br>- Pause call blocking - temporarily disable our spam blocking function if you\u2019re expecting an important call from an unknown number, then continue to block calls when you\u2019re ready.<br><br>KEEP YOUR PERSONAL INFO PRIVATE:<br>- New personal data protection feature helps you reclaim your privacy.<br>- Scan the web to help you find and remove your private info from public search sites where it\u2019s sold and used for spam calls, identity theft and more.<br>- Take your info off the market and use our ongoing monitoring to notify you of any new exposures.<br><br>SCREEN PHONE CALLS IN REAL TIME:<br>- Screen callers by asking them to identify themselves before your phone rings with our automatic answering service.<br>- Get transcriptions of the caller\u2019s response in real-time: We deliver the call screening report as your device is ringing.<br><br>FIGHT SPAM WITH ANSWER BOTS:<br>- Send spammers to lengthy recordings provided by Robokiller.<br>- Choose from a variety of Answer Bots that will give spammers a taste of their own medicine, blocking them in style.<br>- Enjoy listening to blocked &amp; recorded calls.<br><br>REPORT SPAMMERS:<br>- Join the fight against robocalls by reporting any specific number or unknown caller.<br>- Check the scam activity in your state: Be aware of the top scams in your area.<br>- Contact our dedicated customer service team 24/7 regarding any issues with our spam call blocker app.<br><br>Robokiller is an award-winning spam blocker built by people who hate robocalls and respect privacy. Our mission is to stop robocalls forever.<br><br>This app has been featured by The New York Times, NBC, Wired, Engadget, Vice, and other publications.<br><br>Robokiller is free to download. A subscription is required to use the service, but you can try it free for 7 days. Once your trial ends, your subscription will automatically renew. You can cancel your subscription at any time.<br><br>Answer your phone without fear thanks to Robokiller, the spam call blocker app made to give you peace of mind.<br><br>Terms of Service: https://www.robokiller.com/terms.html<br>Privacy Policy: https://www.robokiller.com/privacy.html<br>California Privacy Notice: https://robokiller.com/privacy.html#section-8<br><br>*According to FTC estimates",
    "summary": "Block 99% of spam calls and scam texts. Use Robokiller as the default SMS app.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 7921484,
    "score": 4.1391897,
    "ratings": 120925,
    "reviews": 48980,
    "histogram": [
        16214,
        3363,
        6013,
        17111,
        78218
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $129.99 per item",
    "developer": "Mobile Heroes",
    "developerId": "Mobile+Heroes",
    "developerEmail": "support@robokiller.com",
    "developerWebsite": "http://www.robokiller.com",
    "developerAddress": "Via Nino Bonnet 10\n20154 Milano",
    "privacyPolicy": "https://support.bendingspoons.com/privacy.html?app=4975918500388151620",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/oI-1_YPa2aPCdbbZ-uPhlEYGouc3Y7jXlHjcjNhMEmccAsp00_pfN7dob8Kau0LZ-U8",
    "headerImage": "https://play-lh.googleusercontent.com/fhQ-ZImg10GRRDH8KPVVRibreiPBw7BH3KfMhwy7CqjvZcPMIxk8AJINuHwONqGVxLY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Po-Pka6AomdFwgDLgHk5pddMFEYVq9UQd7SKVd4GOnG20t02zc0vHI-nkmCEXMYvjXxN",
        "https://play-lh.googleusercontent.com/FSFFn7Fb0fftBIBSJGtwEwizcaVqP55fxpwkXe8vaEANb6DMkW1cxvBdzF2JbcJGwQ",
        "https://play-lh.googleusercontent.com/RJP4jVE1Yd3iaZ2yJTRjyB2jgA0pTksrwpxmoyJgjwExDk2zZHOlxHZf3V0iMlyDbzU",
        "https://play-lh.googleusercontent.com/6mv84EndGq3X1ehRfZDOVmizfv8fKGlw7So8XS9QEnerYdK9Yk19trfXaZwsIaaF78E",
        "https://play-lh.googleusercontent.com/_JrtEH_TBb57dJEu5ozSQzDxBm0bMJ8ivctITjsM4yYKjin7EqeKV90bFccJ-B3HDCw",
        "https://play-lh.googleusercontent.com/8yqVOKv80mUBe1zrwXg82EvP0lOEDbhrQkbFatZDI0AcVvccyZiZqe5NGNvb8Z_G9W7A",
        "https://play-lh.googleusercontent.com/k-jaBqNnFeV02seSkoTa-GHqDsvIklwEmgTUze93FGfvjuuIcbpmd4-CFQxfZHg63yeO",
        "https://play-lh.googleusercontent.com/rbEN3VwKoVYTPMnOBPXhJQ-bHCzZ7r4xxImBD_RIfwTS04DD2DhZqabntGJOrBwYsmY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 21, 2018",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729087864,
    "version": "24.7.7",
    "comments": [],
    "appId": "com.robokiller.app",
    "url": "https://play.google.com/store/apps/details?id=com.robokiller.app&hl=en&gl=us"
}