{
    "title": "PREQUEL AI Filter Photo Editor",
    "description": "Create unique Avatars with AI filters, effects & presets for your photos & videos. Use AI to get a retro album from one photo!\r\n\r\nPrequel is a photo filters and video effects editing app with the most aesthetic presets. It offers a handpicked selection of foto & video filters for pictures. Edit your photos and videos to make them stand out with a variety of vintage, trendy effects like Kidcore, VHS, Dust, Indie Kid, Teal, Grain filter, Canvas, Renaissance, Fisheye, Cartoon! Now you can even create unique avatars!\r\n\r\nAesthetic AI Photo Filters & Effects\r\n\r\n\u2022 Most beloved and trendy camera effects & filters for pictures \u2013 Kidcore, VHS, Dust, Indie Kid, Teal, Grain filter, Stardust, Diamond, Sparkle. Boost your social media with eye-catching content\r\n\u2022 Wide range of advanced adjustments and editing tools for every filter and effect \u2013 make your pics & edits unique and custom!\r\n\u2022 Rich festive filter & effect collection: edit & create Christmas, Halloween and Easter content\r\n\u2022 Huge collection of filters & effects (500+) with pro-level color correction \u2013 adjust any of them according to your personal needs\r\n\u2022 D3D: create amazing 3D live moving pictures without any hassle \u2013 add volume to any 2D photo and use any trendy effect and filter you want\r\n\u2022 Create avatar in your own style: cartoon pics & vintage edits\r\n\u2022 Unique collection of Templates for fan pages\r\n\u2022 Authentic Intros for your video content for any mood\r\n\r\nVideo Editor\r\n\u2022 Importing and creating any videos\r\n\u2022 Add trendy presets & templates to any video\r\n\u2022 Transform your videos into a real movie (speed up or slow down, crop, trim). Become a director and tell your stories!\r\n\u2022 Create unique edits with a rich collection of effects & filters for videos\r\n\u2022 Stylize your films with a rich collection of retro effects \u2013 the 20s, 60s, 80s, 90s, 00s cameras\r\n\r\nMake your content stand out with Prequel Editor\r\n\r\nDo you want to make your stories & layout unique aesthetic visuals? Prequel is a tool for boundless creativity and self-expression. Our trendy presets and templates for videos will help visualize even the bravest ideas as crisp content.\r\nAlso you can make new profile pic and toon your photos using our app.\r\n\r\nWhatever your mood is today, turn it up with our camera tools and presets for your edits \u2014 all based on the biggest aesthetics: the bright Indie Kid, the haunting Dark Academia, or the cute Kawaii. Play with nostalgia using the Yearbook effect. Touch up your pictures with the tasteful Matcha and Sunkissed filters. Easily find ones that reflect your vibe!\r\nAnd don\u2019t forget to time travel! Style photos and films with retro effects and filters for pictures like Lomo, VHS, Dust, Denim, Monroe \u2014 and many more! Or throw it way back with  Renaissance effect, turning any selfie into a fine art masterpiece in our aesthetic picture editor.\r\n\r\nAdvanced Editing Tool kit\r\n\r\n\u2022 Easy and fast editing process that requires no special skills or add-ons -- everything you want in just one tap!\r\n\u2022 Intuitive interface that is easy to master\r\n\u2022 Mix unlimited number of filters and tools to edit your own unique custom presets\r\n\r\nCustom Giphy Text & Stickers\r\n\r\n\u2022 Create animated text stickers with your custom text. Say everything in style!\r\n\u2022 Choose the font that suits your own aesthetics\r\n\u2022 Add your own custom text to any photo & video\r\n\u2022 Add funny and cute animated Giphy stickers to your creatives\r\n\r\nGet PREQUEL Gold\r\n\r\n\u2022 Unlimited editing possibilities\r\n\u2022 Full effects & filters collections\r\n\u2022 Advanced creative tools\r\n\u2022 No boundaries for your creativity\r\n\u2022 Flexible subscription plans that suits your personal needs\r\n\u2022 Special offers and festive discounts\r\n\r\nTurn your most daring projects into reality and create your aesthetic world with Prequel picture editor!\r\n\r\n***\r\nAbout subscription: https://prequel.app/prequel-subscription\r\nRead our Terms of Use here: https://prequel.app/term-of-use\r\nRead our Privacy Policy here: https://prequel.app/privacy-policy",
    "descriptionHTML": "Create unique Avatars with AI filters, effects &amp; presets for your photos &amp; videos. Use AI to get a retro album from one photo!<br><br>Prequel is a photo filters and video effects editing app with the most aesthetic presets. It offers a handpicked selection of foto &amp; video filters for pictures. Edit your photos and videos to make them stand out with a variety of vintage, trendy effects like Kidcore, VHS, Dust, Indie Kid, Teal, Grain filter, Canvas, Renaissance, Fisheye, Cartoon! Now you can even create unique avatars!<br><br>Aesthetic AI Photo Filters &amp; Effects<br><br>\u2022 Most beloved and trendy camera effects &amp; filters for pictures \u2013 Kidcore, VHS, Dust, Indie Kid, Teal, Grain filter, Stardust, Diamond, Sparkle. Boost your social media with eye-catching content<br>\u2022 Wide range of advanced adjustments and editing tools for every filter and effect \u2013 make your pics &amp; edits unique and custom!<br>\u2022 Rich festive filter &amp; effect collection: edit &amp; create Christmas, Halloween and Easter content<br>\u2022 Huge collection of filters &amp; effects (500+) with pro-level color correction \u2013 adjust any of them according to your personal needs<br>\u2022 D3D: create amazing 3D live moving pictures without any hassle \u2013 add volume to any 2D photo and use any trendy effect and filter you want<br>\u2022 Create avatar in your own style: cartoon pics &amp; vintage edits<br>\u2022 Unique collection of Templates for fan pages<br>\u2022 Authentic Intros for your video content for any mood<br><br>Video Editor<br>\u2022 Importing and creating any videos<br>\u2022 Add trendy presets &amp; templates to any video<br>\u2022 Transform your videos into a real movie (speed up or slow down, crop, trim). Become a director and tell your stories!<br>\u2022 Create unique edits with a rich collection of effects &amp; filters for videos<br>\u2022 Stylize your films with a rich collection of retro effects \u2013 the 20s, 60s, 80s, 90s, 00s cameras<br><br>Make your content stand out with Prequel Editor<br><br>Do you want to make your stories &amp; layout unique aesthetic visuals? Prequel is a tool for boundless creativity and self-expression. Our trendy presets and templates for videos will help visualize even the bravest ideas as crisp content.<br>Also you can make new profile pic and toon your photos using our app.<br><br>Whatever your mood is today, turn it up with our camera tools and presets for your edits \u2014 all based on the biggest aesthetics: the bright Indie Kid, the haunting Dark Academia, or the cute Kawaii. Play with nostalgia using the Yearbook effect. Touch up your pictures with the tasteful Matcha and Sunkissed filters. Easily find ones that reflect your vibe!<br>And don\u2019t forget to time travel! Style photos and films with retro effects and filters for pictures like Lomo, VHS, Dust, Denim, Monroe \u2014 and many more! Or throw it way back with  Renaissance effect, turning any selfie into a fine art masterpiece in our aesthetic picture editor.<br><br>Advanced Editing Tool kit<br><br>\u2022 Easy and fast editing process that requires no special skills or add-ons -- everything you want in just one tap!<br>\u2022 Intuitive interface that is easy to master<br>\u2022 Mix unlimited number of filters and tools to edit your own unique custom presets<br><br>Custom Giphy Text &amp; Stickers<br><br>\u2022 Create animated text stickers with your custom text. Say everything in style!<br>\u2022 Choose the font that suits your own aesthetics<br>\u2022 Add your own custom text to any photo &amp; video<br>\u2022 Add funny and cute animated Giphy stickers to your creatives<br><br>Get PREQUEL Gold<br><br>\u2022 Unlimited editing possibilities<br>\u2022 Full effects &amp; filters collections<br>\u2022 Advanced creative tools<br>\u2022 No boundaries for your creativity<br>\u2022 Flexible subscription plans that suits your personal needs<br>\u2022 Special offers and festive discounts<br><br>Turn your most daring projects into reality and create your aesthetic world with Prequel picture editor!<br><br>***<br>About subscription: https://prequel.app/prequel-subscription<br>Read our Terms of Use here: https://prequel.app/term-of-use<br>Read our Privacy Policy here: https://prequel.app/privacy-policy",
    "summary": "Video filters & effects! Edit vintage, cartoon & anime edits with AI presets",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 49835215,
    "score": 4.261266,
    "ratings": 283719,
    "reviews": 6097,
    "histogram": [
        34544,
        5772,
        11408,
        31200,
        200762
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.49 - $39.99 per item",
    "developer": "Prequel Inc.",
    "developerId": "6562506502134777861",
    "developerEmail": "support@prequelapp.com",
    "developerWebsite": "https://prequel.app",
    "developerAddress": "15 Palm Avenue, Miami Beach, Florida, 33139, United States",
    "privacyPolicy": "https://prequel.app/privacy-policy/",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/8LJJF7EdSlpSC3JuL6z1T7pRKDesekDVcsd-2Yk6Ecza1bCaTkeMCA_3BJKmhdpbjg4",
    "headerImage": "https://play-lh.googleusercontent.com/8gKLtjemIS2B7Kx7nUPm-8Fs54UAo6srhcUcV9iH9Eey__S08LprUK9M1dI4wrV1OxY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/0zyqR7zIyUXQ5GerjPYIz3VVS3ATR6-PwJE3nypzIXQaEc5VIyRbTTQ5jHC5uWHK0w",
        "https://play-lh.googleusercontent.com/cuMwGYPKQ46w9WT6AdXYtb6YXERR9cUemplQyjsa3mKm7nkDUMJoEO7BFg040Qo3KQ",
        "https://play-lh.googleusercontent.com/ewtGje_qFdewOpKiFOK4tfhGlorrrjfLSBxv9vpFhfUBmvbl6gUFEMnX8ju9-g6QmQ",
        "https://play-lh.googleusercontent.com/o9BBL1vW8QplrnZiu2QvHTiXsSl1z7pW4vK_Ip0voeFS2R-WAS0al4GXbr7_r1xF_t8",
        "https://play-lh.googleusercontent.com/IjuhHH_K1Mb23e_1ueJxh_h7e8kMe2COpeu32JLdjy2dtqAsFM74NQmU7ipWzCuvZ6c",
        "https://play-lh.googleusercontent.com/msRlL_-9bjn14fcWX5MeTDnqF_yutbfONJI115iFcYxs0OMuk1jf4GOvcfNVoZTFnUf4"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 24, 2020",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728904722,
    "version": "1.79.0",
    "comments": [],
    "appId": "com.prequel.app",
    "url": "https://play.google.com/store/apps/details?id=com.prequel.app&hl=en&gl=us"
}