{
    "title": "Mangamo Manga & Comics",
    "description": "Mangamo is the official reading manga destination from over 20 top Japanese publishers. Buy chapters of iconic series like A Sign of Affection, Attack On Titan, Tokyo Revengers, That Time I Got Reincarnated as a Slime, Fire Force, A Silent Voice, and more! Subscribe to Plus to get access to 50+ exclusive titles such as the critically acclaimed My Love Story with Yamada-kun at Lv999, Devil-Chi, Date of Marriage, A Man with A Thousand Skills, Dropkick My Devil!, I Fell in Love So I'm Streaming It, and 400+ great manga titles. \r\n\r\n\r\nFREE READING NOW\r\n\u2022 Enjoy reading hundreds of free chapters on over 400 series!\r\n\r\n\r\nSUBSCRIBE TO PLUS\r\n\u2022 One low monthly price, cancel anytime\r\n\u2022 Access to over 50+ titles only on Mangamo such as My Love Story with Yamada-kun at Lv999, I Fell in Love So I'm Streaming It, Ultra-Fem Shishihara-kun, and Reset Game\r\n\u2022 More new release titles such as Record of Ragnarok, Date of Marriage, Devil Chi, Nanase-san's Crazy Love Obsession, and Kamisama Death Game\r\n\u2022 New chapters every day\r\n\u2022 No daily limits on reading\r\n\u2022 No ads \r\n\r\n\r\nBUY WITH COINS \r\n\u2022 Buy coins Redeem chapter access to iconic series like Attack On Titan, Tokyo Revengers, That Time I Got Reincarnated as a Slime, Fire Force, A Silent Voice, Land of the Lustrous, Your Lie in April, and more\r\n\u2022 Read them whenever you want without restrictions once purchased\r\n\u2022 More series and chapters coming soon\r\n\r\n\r\nBUILD YOUR PERSONAL LIBRARY\r\n\u2022 Add a new series you discovered to your list and view your finished collections\r\n\u2022 Automatically track your reading progress on every title\r\n\u2022 Easy one-tap bookmark for return reading\r\n\u2022 Add titles to your reading list\r\n\u2022 Reading optimized for any iOS device\r\n\r\n\r\nENJOY THE HIGHEST QUALITY READING\r\n\u2022 High quality imagery for iPhone and iPad\r\n\u2022 Professional, accurate translation on all series\r\n\u2022 Intuitive page to page navigation in gallery view\r\n\u2022 Choose between Horizontal or Vertical scrolling options (read like a webtoon/webcomic)\r\n\u2022 Three different methods for zooming--choose your favorite\r\n\r\n\r\nYour support on Mangamo helps support the manga creators that work tirelessly behind the scenes to forge your favorite stories.\r\n\r\n\r\nDownload Mangamo today and read FREE. No subscription or purchase required to start reading free.",
    "descriptionHTML": "Mangamo is the official reading manga destination from over 20 top Japanese publishers. Buy chapters of iconic series like A Sign of Affection, Attack On Titan, Tokyo Revengers, That Time I Got Reincarnated as a Slime, Fire Force, A Silent Voice, and more! Subscribe to Plus to get access to 50+ exclusive titles such as the critically acclaimed My Love Story with Yamada-kun at Lv999, Devil-Chi, Date of Marriage, A Man with A Thousand Skills, Dropkick My Devil!, I Fell in Love So I&#39;m Streaming It, and 400+ great manga titles. <br><br><br>FREE READING NOW<br>\u2022 Enjoy reading hundreds of free chapters on over 400 series!<br><br><br>SUBSCRIBE TO PLUS<br>\u2022 One low monthly price, cancel anytime<br>\u2022 Access to over 50+ titles only on Mangamo such as My Love Story with Yamada-kun at Lv999, I Fell in Love So I&#39;m Streaming It, Ultra-Fem Shishihara-kun, and Reset Game<br>\u2022 More new release titles such as Record of Ragnarok, Date of Marriage, Devil Chi, Nanase-san&#39;s Crazy Love Obsession, and Kamisama Death Game<br>\u2022 New chapters every day<br>\u2022 No daily limits on reading<br>\u2022 No ads <br><br><br>BUY WITH COINS <br>\u2022 Buy coins Redeem chapter access to iconic series like Attack On Titan, Tokyo Revengers, That Time I Got Reincarnated as a Slime, Fire Force, A Silent Voice, Land of the Lustrous, Your Lie in April, and more<br>\u2022 Read them whenever you want without restrictions once purchased<br>\u2022 More series and chapters coming soon<br><br><br>BUILD YOUR PERSONAL LIBRARY<br>\u2022 Add a new series you discovered to your list and view your finished collections<br>\u2022 Automatically track your reading progress on every title<br>\u2022 Easy one-tap bookmark for return reading<br>\u2022 Add titles to your reading list<br>\u2022 Reading optimized for any iOS device<br><br><br>ENJOY THE HIGHEST QUALITY READING<br>\u2022 High quality imagery for iPhone and iPad<br>\u2022 Professional, accurate translation on all series<br>\u2022 Intuitive page to page navigation in gallery view<br>\u2022 Choose between Horizontal or Vertical scrolling options (read like a webtoon/webcomic)<br>\u2022 Three different methods for zooming--choose your favorite<br><br><br>Your support on Mangamo helps support the manga creators that work tirelessly behind the scenes to forge your favorite stories.<br><br><br>Download Mangamo today and read FREE. No subscription or purchase required to start reading free.",
    "summary": "Read officially manga titles from Japan including Attack on Titan",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 688830,
    "score": 4.04,
    "ratings": 1332,
    "reviews": 84,
    "histogram": [
        157,
        102,
        90,
        133,
        835
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $199.99 per item",
    "developer": "Mangamo",
    "developerId": "8258654145188544799",
    "developerEmail": "contact@mangamo.com",
    "developerWebsite": "https://www.mangamo.com",
    "developerAddress": "10-4 Sakuragaoka-cho, Shibuya-ku, Tokyo 150-0031",
    "privacyPolicy": "https://www.mangamo.com/privacy-policy",
    "genre": "Comics",
    "genreId": "COMICS",
    "categories": [
        {
            "name": "Comics",
            "id": "COMICS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Lr5nvkJ3ejfYH2jSjrZ3AE7daMzsL0-Hw8Xs9ITEsmveHlt49P91YVy35-puJY4r3Q",
    "headerImage": "https://play-lh.googleusercontent.com/b9_zqdM8poGMG3EABzXbW8T3iT8r1lT9l71cVgcHuArmtPqn3ngOXGLEAl5QBSWX9Huo",
    "screenshots": [
        "https://play-lh.googleusercontent.com/gsrsltg9OMq2WMdOedohY1WeP-jUgpNlIcaXFNQ9i0pDKv2GfMYKHAgCWUz2QkFFp4Q",
        "https://play-lh.googleusercontent.com/3RB3RGxnierfT5dETr1LtXVhrM2q6gWrFirR7UcWibe7522Bp9yyHxVtxkbZaiPMLg",
        "https://play-lh.googleusercontent.com/1sk7GGjNY602aAFWJLYgBjucZ_0x92wjkezTpfWe4Sf591xKRdtuuoyA_1wAHx1qRA",
        "https://play-lh.googleusercontent.com/cRiQG4H17StVO3Wjj4Kw5U1uyijFTEcyLs1qDd6PKmJA9UcoFdxPKYgvDeHAKygkAR-Y",
        "https://play-lh.googleusercontent.com/Av-EvshKNuGokMUD6DOf3j1DpWYJzFe3REyF7jTjoDGzi1_6iWfh42KUPPTfFNocbV0",
        "https://play-lh.googleusercontent.com/N-BkyEdktVhrMRwQzzHEV-DAsIgK168nrOluZu8Gs9Srmwuxcj-yMLbNBt7GiRCZwQ",
        "https://play-lh.googleusercontent.com/G9CJpXqJlzO3Dw-TmThZkvP9z2qqz1vKKwO8yi3RBCPcOExRNGZvlLOU526PiKLxT-g",
        "https://play-lh.googleusercontent.com/YdGPPLB0cVYG3KM-8UAMt1Pz_6VTAXoVO42Woy6PQYZgaajcLwuOvBjTrVJA_cHuaw",
        "https://play-lh.googleusercontent.com/MSp3PkDcL_8dumV7eVyQ4MCBFUBXRFh8ItVHdgClmTIAlshMtXgof4NuTBbzwPk7dPsx",
        "https://play-lh.googleusercontent.com/p4qh4GBxKF8dIapZlAgnRW712b2TL1UmbKHz4Bhy2Nae7aCPke3b6N-qsfLbBDBpeQ",
        "https://play-lh.googleusercontent.com/aj2UXgIOsvo4PVTxeDGGYJBxnjkdE88PSSeqT9QGw-Q_b6eFngTsY_eYIQ7h8oMhorY",
        "https://play-lh.googleusercontent.com/AQP9H9O8bNM9d7aAWfYuH6RTpyoAurGrNFMZEK0Jjs23rOdbGIArEDY8ovHXYCoK2FQ",
        "https://play-lh.googleusercontent.com/IlJsv5o5Z485yNBWkRzTENCKvkw7Dlm4E35j7r6DvzfY-mMHGSyLoWlNLcjAMNI2eFU"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 22, 2020",
    "lastUpdatedOn": "Sep 4, 2024",
    "updated": 1725485480,
    "version": "1.226.12",
    "comments": [],
    "appId": "com.mangamo.app",
    "url": "https://play.google.com/store/apps/details?id=com.mangamo.app&hl=en&gl=us"
}