{
    "title": "SchoolCaf\u00e9",
    "description": "SchoolCaf\u00e9 is powered by PrimeroEdge, the leading school nutrition management software for K-12 school districts and food service providers in the United States.\r\n\r\nParents: Manage your child's cafeteria account. Apply for free or reduced meals. Make payments, view purchase history, receive low balance alerts, and view school menus containing nutritional and allergen information for items. For convenience, setup automatic payments to replenish your child's cafeteria funds. Know what is on the menu at the school cafeteria and provide feedback by rating and sharing items. Favorite your child's favorite items and SchoolCaf\u00e9 will send you a push notification to let you know when it's on the menu.\r\n\r\nStudents and Staff: Use SchoolCaf\u00e9 to check out what's available on the cafeteria menu each day. View nutritional and allergen information to help you make healthy decisions. Use \"Make a Tray\" to build your meal for the items available that day and see the combined nutrient information. Give your feedback to the school cafeteria by rating items. Favorite specific items on the menu so that you can know when they'll be available in the cafeteria. Connect to your cafeteria account to always know your account balance and have access to your digital ID card.\r\n\r\nDistrict Administrators: View helpful reports and useful analytics for users in your districts and help them manage their accounts.\r\n\r\nSchoolCaf\u00e9 is available for participating schools only.",
    "descriptionHTML": "SchoolCaf\u00e9 is powered by PrimeroEdge, the leading school nutrition management software for K-12 school districts and food service providers in the United States.<br><br>Parents: Manage your child&#39;s cafeteria account. Apply for free or reduced meals. Make payments, view purchase history, receive low balance alerts, and view school menus containing nutritional and allergen information for items. For convenience, setup automatic payments to replenish your child&#39;s cafeteria funds. Know what is on the menu at the school cafeteria and provide feedback by rating and sharing items. Favorite your child&#39;s favorite items and SchoolCaf\u00e9 will send you a push notification to let you know when it&#39;s on the menu.<br><br>Students and Staff: Use SchoolCaf\u00e9 to check out what&#39;s available on the cafeteria menu each day. View nutritional and allergen information to help you make healthy decisions. Use &quot;Make a Tray&quot; to build your meal for the items available that day and see the combined nutrient information. Give your feedback to the school cafeteria by rating items. Favorite specific items on the menu so that you can know when they&#39;ll be available in the cafeteria. Connect to your cafeteria account to always know your account balance and have access to your digital ID card.<br><br>District Administrators: View helpful reports and useful analytics for users in your districts and help them manage their accounts.<br><br>SchoolCaf\u00e9 is available for participating schools only.",
    "summary": "SchoolCaf\u00e9 connects families to school nutrition.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 471913,
    "score": 4.0034485,
    "ratings": 2897,
    "reviews": 1315,
    "histogram": [
        438,
        119,
        189,
        388,
        1757
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Cybersoft PrimeroEdge",
    "developerId": "Cybersoft+PrimeroEdge",
    "developerEmail": "apps@primeroedge.com",
    "developerWebsite": "https://www.schoolcafe.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.schoolcafe.com/privacy/",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ud_TCrck8pJpYDyHSN7t-dQk3b_kB8Bp81oU6kDV9mR60p4OMZ8VsGBoRisI4HfTCLc",
    "headerImage": "https://play-lh.googleusercontent.com/PTn6_DW9n9HB4xZ1kkdkOiujlQXK_gc6SMKSMPNbS9sjPtpiBgE40Qde63LaqfkahNnI",
    "screenshots": [
        "https://play-lh.googleusercontent.com/O_M7BIDoiALNSSOZhtXUXvfHf7ucXduJzuF2sIuD7eSgPfT4kKtiwmmNqmIqwdgjub4",
        "https://play-lh.googleusercontent.com/a2ppf0rrR4ePWcPyo9sOj4xDVcy-0PA-r7c5OHNyllg2qeJHD2fKrT3uUpW-6rkwdQ",
        "https://play-lh.googleusercontent.com/lkwq_aIGx96tYyGaOsA4x6pZF0BW6-8W9Zobmcd0-MZMcvcVUM594VklZ1fADYyThlFt",
        "https://play-lh.googleusercontent.com/q85-6_G9TsN04jtFlJ92fulkdWiVfmbsoZDFEHWuTDiatS0TRGpFMUQ4gntDlQwdFdNm",
        "https://play-lh.googleusercontent.com/1AqdrViUMYR3WGjopQcbFYWCC8AvGzKMpf0voblcqmhkBXwkIQ2sWQxsBbiXHnplzw",
        "https://play-lh.googleusercontent.com/YKLFpzrf9DsrWJP8E9mRHu9UzO1mxnOITmh6TgAEmT1nqMuKf01orfJe-sFjIS5GgJk",
        "https://play-lh.googleusercontent.com/WXNDaW85hrj3uWlZ7bJ-34bwgABrTN8x3zQp7QKtVwQQIzRw8gL7gxtfEa4_oINI-Do",
        "https://play-lh.googleusercontent.com/KK4rA_08zwsM2omXormDaxtfRroh2J_EkT4nOczV0KI6zyEoFkEMMx4DFil6_EMkjfs",
        "https://play-lh.googleusercontent.com/8wfZyMwpFUOgwQGoUExEvjsGK03gQmXymYXQ6BCrOL0-V3IH6eUrwTE6-9zUh0qJfw",
        "https://play-lh.googleusercontent.com/Mm8ciX5qqD6m2S75Mr5QbvL46gyUQC1eDlv950t5VvjAc7F1NconjqAsaI06YFxxZBM",
        "https://play-lh.googleusercontent.com/o8XF0yTOFObQby7L_rQSdZVFB3OUS0f_z7-vxuMDjsUwgysP2U1H4Ti_E33JnbaOi1Q",
        "https://play-lh.googleusercontent.com/0paAqE7eEA3T2OGJg-TI2lJZAt3DVGPrGK1G9qPUkojxKTjhh891Q-XiOpqjEfSzMis",
        "https://play-lh.googleusercontent.com/GXKxacRdprCufLtOBmOhGk_C5ADa07Mhu-8AkzwcGS4bdj3AkuBr0ibeg2kd4caguQ",
        "https://play-lh.googleusercontent.com/HVd0PaqZIQqla_ko7w7lVOjLF5DkXAOR6kh8_yl9ZdT0SoXlSrRPmJ2kFfgIIGrfFHA",
        "https://play-lh.googleusercontent.com/gwD45jdUpojXQdVeimsv5qDUBgYEHKSahouZjTEr0IZPxuR7xNBIB0eI39-ptHY6KlU",
        "https://play-lh.googleusercontent.com/jw4wizRoP8uSAq3N3CqRN6nDMMB_WqjAH_RHrmWu32Bz8YF_SYStfzh-q7D3_16KowDn",
        "https://play-lh.googleusercontent.com/3OXTI-Z1hAjJOrf2V4XrLk28ysXt5w7EJR_uodYXbZA99UbKqzglMxgejcGFd5nUsC0",
        "https://play-lh.googleusercontent.com/DmgBKm5FXu-esv0AAbsSDdYm9swXwRkboGaVFDWCduInWdaVEDeeMlz3yOYB-IT9Ano"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 31, 2016",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728918745,
    "version": "14.4.1",
    "comments": [],
    "appId": "com.schoolcafe.app",
    "url": "https://play.google.com/store/apps/details?id=com.schoolcafe.app&hl=en&gl=us"
}