{
    "title": "Reliant",
    "description": "The improved Reliant app delivers powerful new features along with plenty of quick and easy ways to manage your Reliant account. Track electricity usage, receive alerts, pay your bill and sync your Google Nest thermostat and Goal Zero Yeti.  \r\n\r\nKeep your home comfortable \r\n\r\nConnect and remotely adjust your Nest thermostat  \r\n\r\nTrack electricity, solar and electric vehicle usage \r\n\r\nMonitor electricity usage details by day, week, month or year. See your projected electricity bill and compare current and past usage. \r\n\r\nMonitor your solar generation and consumption and see your Energy Efficiency score. \r\n\r\nSync your EV to schedule charging, see your gas savings and environmental impact.  \r\n \r\nStay in the know \r\n\r\nSign up for Reliant Account Alerts to keep tabs on your electricity usage, bill due dates and even projected charges.* \r\n\r\nPay your bill your way \r\n\r\nUse a stored credit card or bank account to quickly and securely pay your bill.  \r\n\r\nManage prepaid funds \r\n\r\nIf you\u2019re enrolled in a Reliant prepaid electricity plan, you can use the in-app payment calculator to budget your electricity usage. \r\n \r\nAccess account essentials \r\n\r\nReview your plan details and manage account settings. Eligible customers can also renew, transfer or change their plan.  \r\n \r\nGet 24/7 help  \r\n\r\nContact customer support, report an outage, find payment locations and view FAQs. \r\n \r\n*Not available to customers enrolled in a Reliant prepaid electricity plan. \r\n\r\nVisit reliant.com/app to learn more about the Reliant app. Please note that the Reliant app is only available to residential customers at this time.  \r\n\r\nReliant is not affiliated with Google or the products and services they market. Google Nest and Google Nest thermostat are trademarks of Google LLC. \r\nYou can view our complete privacy policy at reliant.com/privacy. If you have any questions, we\u2019re available 24/7 via online chat and at 1-866-222-7100. \r\n\r\nReliant is a registered service mark of Reliant Energy Retail Holdings, LLC. Reliant Energy Retail Services, LLC (PUCT Certificate #10007). \u00a9 2023 Reliant Energy Retail Holdings, LLC. All rights reserved.  \r\n\r\nGoogle Play and Android are trademarks of Google Inc.",
    "descriptionHTML": "The improved Reliant app delivers powerful new features along with plenty of quick and easy ways to manage your Reliant account. Track electricity usage, receive alerts, pay your bill and sync your Google Nest thermostat and Goal Zero Yeti.  <br><br>Keep your home comfortable <br><br>Connect and remotely adjust your Nest thermostat  <br><br>Track electricity, solar and electric vehicle usage <br><br>Monitor electricity usage details by day, week, month or year. See your projected electricity bill and compare current and past usage. <br><br>Monitor your solar generation and consumption and see your Energy Efficiency score. <br><br>Sync your EV to schedule charging, see your gas savings and environmental impact.  <br> <br>Stay in the know <br><br>Sign up for Reliant Account Alerts to keep tabs on your electricity usage, bill due dates and even projected charges.* <br><br>Pay your bill your way <br><br>Use a stored credit card or bank account to quickly and securely pay your bill.  <br><br>Manage prepaid funds <br><br>If you\u2019re enrolled in a Reliant prepaid electricity plan, you can use the in-app payment calculator to budget your electricity usage. <br> <br>Access account essentials <br><br>Review your plan details and manage account settings. Eligible customers can also renew, transfer or change their plan.  <br> <br>Get 24/7 help  <br><br>Contact customer support, report an outage, find payment locations and view FAQs. <br> <br>*Not available to customers enrolled in a Reliant prepaid electricity plan. <br><br>Visit reliant.com/app to learn more about the Reliant app. Please note that the Reliant app is only available to residential customers at this time.  <br><br>Reliant is not affiliated with Google or the products and services they market. Google Nest and Google Nest thermostat are trademarks of Google LLC. <br>You can view our complete privacy policy at reliant.com/privacy. If you have any questions, we\u2019re available 24/7 via online chat and at 1-866-222-7100. <br><br>Reliant is a registered service mark of Reliant Energy Retail Holdings, LLC. Reliant Energy Retail Services, LLC (PUCT Certificate #10007). \u00a9 2023 Reliant Energy Retail Holdings, LLC. All rights reserved.  <br><br>Google Play and Android are trademarks of Google Inc.",
    "summary": "Power Your Way",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 520100,
    "score": 4.7329288,
    "ratings": 7291,
    "reviews": 2186,
    "histogram": [
        209,
        110,
        88,
        596,
        6283
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Reliant Energy Retail Holdings, LLC.",
    "developerId": "Reliant+Energy+Retail+Holdings,+LLC.",
    "developerEmail": "mobile@reliant.com",
    "developerWebsite": "https://www.reliant.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.reliant.com/en/about/legal/privacy-statement.jsp",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/wjM--cV_tmP256PzV_PcIpZmnPC_5ltHA21QVXFh-oYo_krAt1rc8sHhtRGGKqGrdqT6",
    "headerImage": "https://play-lh.googleusercontent.com/I9pUMIujcEPO8jYhitPBBIzs57M4z6J32ibASf0cqkwvZMbsEH4NRezXZ4et8oRJsHE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/2O3J_WsvmlQpc0z9nQoaD7j42oABKz5eIxmY71uxHdV0SD0tLV5A1V2X0mP5OdGhSjM",
        "https://play-lh.googleusercontent.com/UyUHbx4_Fv54qe5tnHpqqe7pwiDb9fmjVvm_WIHx0Fr0A0E4Jk3_JNJtt3k22ygMh3xR",
        "https://play-lh.googleusercontent.com/0xkobyk-UY08VY-ooPOR8EAhUYpErPx-4H-x7A2L28qnVZss2e--K5hDQeM9oJqHkg",
        "https://play-lh.googleusercontent.com/yia7BdKNVAbFQWukktIf2-usmo_32ngeCBYpkabVDi1GurXg5JWy0fkTFPq5RoFcFEE",
        "https://play-lh.googleusercontent.com/eblDt396PkRyGyupak5cj4I6YhjzVMHLF_kHSg1IxGTChLIbTaLCDnS3R9h60zU2Jvyc",
        "https://play-lh.googleusercontent.com/hauhYx6UCJl2ZMN8oSOHgXvGy_7X5umm5nwrxxJmSL5GELDKC_CCKnrJzy3qKOQAoGY",
        "https://play-lh.googleusercontent.com/BvazlUCR2v2XWEWrM8pibVhRfejiplensLtMX-5zyOUME-iHBwLuFFzwnV7kdhE41RKS",
        "https://play-lh.googleusercontent.com/Y1r65R18uid2crTSPuWRyhdYUz_VsohwlK4C5ZjTlml3tZgsMCqmu4DL1t2zZETkVFs",
        "https://play-lh.googleusercontent.com/iQP4mCS4ue6WDixtI1Sdbn8u0FPeEVxDLC9mjqWYm8n7KzdHX2IUjaZBIqARX8pOsNA",
        "https://play-lh.googleusercontent.com/8UqSJEj2voj-F2PotmnhrmgAUlxjB8Z5mxjE4DsThKv8FLi1eDd7smkb1dUqnxzHMUc",
        "https://play-lh.googleusercontent.com/6hvGmY35GjKK28k2kfNhAnWYsAQvUvEW0SuQcfsH5Ka41fXV16caLbkGsTHyNOOVwQ",
        "https://play-lh.googleusercontent.com/xQP98gz5kpyKjxEu_V2V3n9mHWkI4ehu46ro8ifrcfrfJfp2Uw30VZkSgt2n5Xq2oQ",
        "https://play-lh.googleusercontent.com/ByPmaQwM0bq3SCJfjCWMx1B_uXdOQ78GFDQiVGn2gBYnxln9eWaXKH77HqtkB7Hnqm8",
        "https://play-lh.googleusercontent.com/gsi7_V09Qvt3GA1pLqVXKg1kHCyff8a1vnI9ttpBp8oFkS1R4h1JP21JeXCB310aQ88",
        "https://play-lh.googleusercontent.com/cDApwnGm-rFtWBbatln5VM5dbUv6Wlokn1GkAtoX7YZqttWKaabgbZEiFTBIH0bMtYv4",
        "https://play-lh.googleusercontent.com/rTpGP7up67i7Nmb3nHooBCS5jzmiNUDKfKLLHtkXRYKGBbIEeXnRWMBujTpl4DuB9OA",
        "https://play-lh.googleusercontent.com/6qZiag6wgNkyr_R2N04qONi0RSdRsFg5CEELulqcYC2RCbGCrlIvjL28b0OjmAaiB4o",
        "https://play-lh.googleusercontent.com/36Qai5OdMnh74ZDV18jzcZafJSPcLn664WgCngymwsbH-2gbmG8bAqN0PPQcBoNsP8U",
        "https://play-lh.googleusercontent.com/b8affYsAZfzl5Np7BcHMSPrMzpAFJAgNxPzDcVNINRr7PXz0Jz7NQVEibfEbN1WBHFxX",
        "https://play-lh.googleusercontent.com/HzFyfrgF-nvpD8cPfVY8ZQf2PPngASd7dLw3MS85wZ_yi8l9RpbWGhC1HMQeYYJedA",
        "https://play-lh.googleusercontent.com/NcdpBem6dioJaQ7eNpdpbek2ommNgUmIuqkyAe90m8-90xIPmWne5h0HYJNeAJgRiVo",
        "https://play-lh.googleusercontent.com/LbEfyJxVH7viEic0rAqJ6Hh69RRFTAv0YgFGrnzzgw2Xyxs1dPbsKqNkRiIYP-m7eRNk",
        "https://play-lh.googleusercontent.com/WPXdJC699Y6NPE-wOmTvnDVeTLqRcvTaRRZ_Mu2dMfl3P9qBMAzcIymcl9oVd7GXUFA",
        "https://play-lh.googleusercontent.com/rAYdkvYF9GHYwsyBtA15mKFrfZ3Kr1DmY4hMg71IhKeL956Dp0A9QX89IrUYmIOZhMr-",
        "https://play-lh.googleusercontent.com/LczcVLqOEcRc-hgR5QeRMT6QjrwvcENEnV51d1oin5YExc7L6usY9QYENNAIZPXenAPU",
        "https://play-lh.googleusercontent.com/wXrUtJfnsnKV7qaBCB8vPjxuH6Zftb772GJHm2jwqFPRmc1wpQsh4JwIx6xeJt88fyE",
        "https://play-lh.googleusercontent.com/DzbqKceNldO0ecuxKk05MNxAL7uxxeHFxZI564Njd2rE2pyJYgyIfLvxH5HeIkNwuY7G",
        "https://play-lh.googleusercontent.com/S9QDhZ9WGeLZugrbeCG1yAl3BZIsKm2xxH2-HwRviepa78J8yEKuyRHNNsizIxCnhlE"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 12, 2013",
    "lastUpdatedOn": "Oct 11, 2024",
    "updated": 1728651844,
    "version": "9.0.0",
    "comments": [],
    "appId": "com.reliant.app",
    "url": "https://play.google.com/store/apps/details?id=com.reliant.app&hl=en&gl=us"
}