{
    "title": "TheGrint | Golf Handicap & GPS",
    "description": "Discover the top golf app for handicap, GPS, scorecard tracking & more. Link your GHIN# and enjoy intuitive tools \u2013 from a golf shot tracker and GPS rangefinder, to live stats \u2013 hit the green confidently around the world.\r\n\r\nTheGrint is the perfect golf tracker to follow your journey in one place. Connect with friends, track milestones and achievements, and use live score alerts with the perfect golfing tool. Cheer on birdies or trash talk friends in-app and check golf stat progress as you play. If it\u2019s not on TheGrint, did it really happen?\r\n\r\nGolf shot tracker with shot distances, green heatmaps, and detailed golf stats to help improve your shot and scores.\r\n\r\nFEATURES\r\n\r\nGolfing Rangefinder\r\n\u2022 Golf distance finder features compatible on nearly any course\r\n\u2022 Golf distance tracker measures the distance of the fairway\r\n\u2022 Our golf shot rangefinder lets you swing confidently knowing the distance to the green\r\n\u2022 Golf course GPS with a detailed view, heatmap of slopes and breaks\r\n\u2022 Track your golf score and get shot distances from your wrist with our watch app (Available for Wear OS running devices)\r\n\r\nOfficial Golf Handicap & Score Tracker\r\n\u2022 Track your golf scorecard free directly into USGA servers when you link your GHIN#\r\n\u2022 Scorecard tracker with golf stats like fairway accuracy, penalties and number of putts\r\n\u2022 Upload and track golf scores with our Scorecard Picture Service (SPS)\r\n\u2022 Golf stats & calculations for Skins, High & Low, Medal, Best Ball, Niners, and Stableford\r\n\r\nTee Off With Golfing Insights\r\n\u2022 Golf shot tracker, swing by swing analysis and past scores \u2013 it\u2019s all available on TheGrint\r\n\u2022 Track clubs used on the golf course\r\n\u2022 Get pro-like golf stats with a look into your scoring trends\r\n\u2022 Advanced golf stat information like 1st putt distance & drinks available\r\n\r\nShot Editing\r\n\u2022 Edit tracked shots from your phone after they're recorded\r\n\u2022 View shot distances and arcs overlaid onto GPS view\r\n\r\nLive Golf Scores\r\n\u2022 Get golf course updates with Push Notifications\r\n\u2022 Tee off & compete with others in real-time\r\n\u2022 Get a golf score tracker to use on multiple phones\r\n\u2022 Ryder Cup Format competitions\r\n\r\nGolfing Community with Friends & New Groups\r\n\u2022 Golf scores, stats and photos uploaded by golf buddies\r\n\u2022 Organize tee times with our Groups tool\r\n\u2022 Compare your golf scorecard to rank with friends and TheGrint community\r\n\r\nBest in class customer support\r\n\r\nPRO MEMBERSHIP\r\n\u2022 Advanced Stats - Dive into 14 golf stat modules to improve your swing, with dynamic targets\r\n\u2022 Golf Shot Tracker - Dial in shot distances with every club and empower additional stats modules based on tracked shot data\r\n\u2022 Games - Access Wolf, Vegas, Animals, Hot Potato, Marks, and more\r\n\u2022 Golf Scorecard Picture Service - Upload an image of your scorecard to be transcribed\r\n\u2022 Green Maps - With our golf course GPS you can plan shots with precision & confidence for over 14k courses\r\n\u2022 Insights & Targets - Improve your game with custom golf handicap benchmarks for 8 stat categories\r\n\u2022 Multigames & Presses - Run many games at once and add unlimited presses\r\n\u2022 Golf Shot Tracker from the Watch - Start and stop the shot tracker from your smartwatch\r\n\u2022 Leave your phone in the cart\r\n\u2022 Record the club you hit to collect average distance data by club\r\n\r\nIMPORTANT DISCLOSURE\r\n\u2022 Payment will be charged to your account, and the Subscription will automatically renew after 1 year unless the auto-renew is turned off at least 24 hours before the end of the current period. Renewal payment may be processed within 24-hours prior to the end of the period to ensure continuity.\r\n\u2022 Subscriptions may be managed by the user and auto-renewal may be turned off by going to the user's Account Settings after purchase\r\n\u2022 Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable.\r\n\r\nFinally, make sure to take a look at our Terms & Conditions and Privacy Policy at the following link http://thegrint.com/terms\r\n\r\nWe hope you enjoy our service!\r\n\r\nTheGrint Team",
    "descriptionHTML": "Discover the top golf app for handicap, GPS, scorecard tracking &amp; more. Link your GHIN# and enjoy intuitive tools \u2013 from a golf shot tracker and GPS rangefinder, to live stats \u2013 hit the green confidently around the world.<br><br>TheGrint is the perfect golf tracker to follow your journey in one place. Connect with friends, track milestones and achievements, and use live score alerts with the perfect golfing tool. Cheer on birdies or trash talk friends in-app and check golf stat progress as you play. If it\u2019s not on TheGrint, did it really happen?<br><br>Golf shot tracker with shot distances, green heatmaps, and detailed golf stats to help improve your shot and scores.<br><br>FEATURES<br><br>Golfing Rangefinder<br>\u2022 Golf distance finder features compatible on nearly any course<br>\u2022 Golf distance tracker measures the distance of the fairway<br>\u2022 Our golf shot rangefinder lets you swing confidently knowing the distance to the green<br>\u2022 Golf course GPS with a detailed view, heatmap of slopes and breaks<br>\u2022 Track your golf score and get shot distances from your wrist with our watch app (Available for Wear OS running devices)<br><br>Official Golf Handicap &amp; Score Tracker<br>\u2022 Track your golf scorecard free directly into USGA servers when you link your GHIN#<br>\u2022 Scorecard tracker with golf stats like fairway accuracy, penalties and number of putts<br>\u2022 Upload and track golf scores with our Scorecard Picture Service (SPS)<br>\u2022 Golf stats &amp; calculations for Skins, High &amp; Low, Medal, Best Ball, Niners, and Stableford<br><br>Tee Off With Golfing Insights<br>\u2022 Golf shot tracker, swing by swing analysis and past scores \u2013 it\u2019s all available on TheGrint<br>\u2022 Track clubs used on the golf course<br>\u2022 Get pro-like golf stats with a look into your scoring trends<br>\u2022 Advanced golf stat information like 1st putt distance &amp; drinks available<br><br>Shot Editing<br>\u2022 Edit tracked shots from your phone after they&#39;re recorded<br>\u2022 View shot distances and arcs overlaid onto GPS view<br><br>Live Golf Scores<br>\u2022 Get golf course updates with Push Notifications<br>\u2022 Tee off &amp; compete with others in real-time<br>\u2022 Get a golf score tracker to use on multiple phones<br>\u2022 Ryder Cup Format competitions<br><br>Golfing Community with Friends &amp; New Groups<br>\u2022 Golf scores, stats and photos uploaded by golf buddies<br>\u2022 Organize tee times with our Groups tool<br>\u2022 Compare your golf scorecard to rank with friends and TheGrint community<br><br>Best in class customer support<br><br>PRO MEMBERSHIP<br>\u2022 Advanced Stats - Dive into 14 golf stat modules to improve your swing, with dynamic targets<br>\u2022 Golf Shot Tracker - Dial in shot distances with every club and empower additional stats modules based on tracked shot data<br>\u2022 Games - Access Wolf, Vegas, Animals, Hot Potato, Marks, and more<br>\u2022 Golf Scorecard Picture Service - Upload an image of your scorecard to be transcribed<br>\u2022 Green Maps - With our golf course GPS you can plan shots with precision &amp; confidence for over 14k courses<br>\u2022 Insights &amp; Targets - Improve your game with custom golf handicap benchmarks for 8 stat categories<br>\u2022 Multigames &amp; Presses - Run many games at once and add unlimited presses<br>\u2022 Golf Shot Tracker from the Watch - Start and stop the shot tracker from your smartwatch<br>\u2022 Leave your phone in the cart<br>\u2022 Record the club you hit to collect average distance data by club<br><br>IMPORTANT DISCLOSURE<br>\u2022 Payment will be charged to your account, and the Subscription will automatically renew after 1 year unless the auto-renew is turned off at least 24 hours before the end of the current period. Renewal payment may be processed within 24-hours prior to the end of the period to ensure continuity.<br>\u2022 Subscriptions may be managed by the user and auto-renewal may be turned off by going to the user&#39;s Account Settings after purchase<br>\u2022 Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable.<br><br>Finally, make sure to take a look at our Terms &amp; Conditions and Privacy Policy at the following link http://thegrint.com/terms<br><br>We hope you enjoy our service!<br><br>TheGrint Team",
    "summary": "Golf score tracker, handicap, rangefinder & scorecard for your phone or watch",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 852745,
    "score": 4.094488,
    "ratings": 4138,
    "reviews": 1063,
    "histogram": [
        454,
        259,
        308,
        520,
        2589
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "Grint LLC",
    "developerId": "Grint+LLC",
    "developerEmail": "contactus@thegrint.com",
    "developerWebsite": "https://www.thegrint.com",
    "developerAddress": "2030 S Douglas Rd #209\nCoral Gables, FL 33134",
    "privacyPolicy": "http://thegrint.com/terms",
    "genre": "Sports",
    "genreId": "SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/3LxTmzoK5ZGWhoeA2I1b91kxo5z3jNWGtnvjFwXBTlXiPuOQ1ZjuC68h0mcBRkwQBt8",
    "headerImage": "https://play-lh.googleusercontent.com/YB-vbaIqFmwv_4ConnWBa8a8wMoRiBLdlVKxPCEAKhGSm0ei96sf7kff4t8FxD6V4Kc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/SyJYI1_x-disczAQDSgEYNkREbQmLeqpOzJNgDMFd5TBMQptwnV_aqSye0var6MLkw",
        "https://play-lh.googleusercontent.com/F-qb1ENOW4QtrFCU6ZZT01dE_Wn6VhUG_82PPdlveZJJGhRA6rCIs8McJVC_6C6E4JQ",
        "https://play-lh.googleusercontent.com/Uuz3yoxU2gw-fuyldV4REBY2l6cqIKH3F8PwJjUzoMouEmU1jUOY2jWJ29TmEpprhR4",
        "https://play-lh.googleusercontent.com/IwNDlI8aNw7l0FhBMN4D1a-Hv9NORbZCIH2IowHo56MVLBAbjytPyJuY3HKYQnMYFkg",
        "https://play-lh.googleusercontent.com/VoICBpXj7Eh1kRPg7LX_cHeP5Y1IbNa5OkWnqLzafsAVroPniHMCmjN9WX9Y7lLvHxQT",
        "https://play-lh.googleusercontent.com/LDDgWmVrzaZ0Sdk7XJYMv1rv7D8-YR-bT4uTPNduPnpuhFj7y7tvJYea_v6_MaGjEpg",
        "https://play-lh.googleusercontent.com/PxEgfd0qX801itfYyCGoWBY9Ab3IhC7ZFDo5W22bTE1Vbc1M1tklA2UrBXEViWVbYw",
        "https://play-lh.googleusercontent.com/OepF2WM3usObN0fDYqkAMaHm7asYUU2xSe_zW1FTGfATqpADhDUPeBsWlNlkBjMj4X4",
        "https://play-lh.googleusercontent.com/xO6t_1O3l1EbCPJD2dFmpwWeN6oIzj4E4xCdmHfawILm0UIcnGmAxIsJqqBUvxgkJn8q",
        "https://play-lh.googleusercontent.com/Dgo-JtCcdPLgnPf1JilJjOPLWPAXDQdvymaaTY4JkYlw-9BirkmKdR32SjNzLL4Q3v6c",
        "https://play-lh.googleusercontent.com/b_GVVOG_DeuIfIYbdcA0J2KUWovYW40j_bga4_7gkoCSSsUUbnI77MmW64PacfEJLVA",
        "https://play-lh.googleusercontent.com/p9f_VNupUXue9jsnljnULmdyb8mTdIVa9onCKNHGKBUU-7-vYd1Mj__iv4TPB9cA6TE",
        "https://play-lh.googleusercontent.com/kyhP20oLsBfPyfLzqM343JxSlYg5Quu9sG3m-Mprh_IcySuecq0jtZZaC3p7CsixOuc",
        "https://play-lh.googleusercontent.com/tUlzNhkdY1tJ4oy1pBP6qrnR7yMrE7M8_UfcHSbZDS2aWVQRcY4ffqrpvXGs3IL06gY9",
        "https://play-lh.googleusercontent.com/DxJrDrhqbwcN7XF-76E11eofiUITxqea3L4dVV-PN5QgK0UA-IMWqkLeDwbUG4Bigd0l",
        "https://play-lh.googleusercontent.com/FK89gGNKuZc8KE24xkKnMOw8VS4-o2diRvExJUShmP1dLPrZKnNHmilJd7GSDZWGCA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 4, 2013",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729213439,
    "version": "v15.2.9 R2D2",
    "comments": [],
    "appId": "com.grint.thegrint.pro",
    "url": "https://play.google.com/store/apps/details?id=com.grint.thegrint.pro&hl=en&gl=us"
}