{
    "title": "La Biblia en Espa\u00f1ol",
    "description": "The Holy Bible in Modern Spanish is a free application that allows you to navigate through all the wisdom of the Bible in simple and clear language, with just a few clicks and without the need for an Internet connection.\r\n\r\nThis application represents our effort to make the Bible in Modern Spanish publicly available to everyone and reach people around the world through technology.\r\n\r\nMAIN FEATURES:\r\n- Offline access: Read the Holy Bible anytime, anywhere, even without internet.\r\n- Reading Tracker: Continue your Bible reading right where you left off and keep track of completed books and chapters.\r\n- Instant Navigation: Jump directly to any book, chapter or verse in the Old or New Testament of the Bible.\r\n- Study tools: Add colorful notes and bookmarks to verses and review your reading history.\r\n- Spread the Word: Create and share beautiful images of Bible verses or build entire PDFs within the app for seamless sharing.\r\n- Powerful search tools: Locate specific content in the Bible effortlessly.\r\n- Daily inspiration: Receive an image of the Verse of the Day every day.\r\n- Home screen widget: Add a widget to view inspirational verses directly on your home screen.\r\n- Personalization: Customize your Bible reading experience with various themes and fonts.\r\n- Protect your eyes: Activate night mode for a more relaxed Bible reading experience.\r\n- Backup and Sync: Seamlessly transfer your bookmarks, notes and reading progress to another device.\r\n\r\nAPP CONTENT:\r\n- The Bible in Modern Spanish\r\n- The World Bible in Spanish\r\n- The Reina Valera Bible 1909\r\n- The Bear Bible (Cassiodoro de Reina 1569)\r\n\r\nOUR WORK\r\nThis product has been carefully and lovingly crafted, and is a testament to our belief in the transformative power of the teachings of the Holy Bible, as well as our mission to make them more accessible to all.\r\n\r\nJOIN OUR GROWING COMMUNITY\r\nBe part of the millions of believers who have chosen our Modern Spanish Bible app for their daily readings of the Holy Bible. As we continue to expand, we now offer more Spanish Bible translations.\r\n\r\nDownload the Modern Spanish Bible app and take your own digital copy of the Holy Bible with you wherever you go! Follow us on Facebook: https://www.facebook.com/LaBibliaModernaApp",
    "descriptionHTML": "The Holy Bible in Modern Spanish is a free application that allows you to navigate through all the wisdom of the Bible in simple and clear language, with just a few clicks and without the need for an Internet connection.<br><br>This application represents our effort to make the Bible in Modern Spanish publicly available to everyone and reach people around the world through technology.<br><br>MAIN FEATURES:<br>- Offline access: Read the Holy Bible anytime, anywhere, even without internet.<br>- Reading Tracker: Continue your Bible reading right where you left off and keep track of completed books and chapters.<br>- Instant Navigation: Jump directly to any book, chapter or verse in the Old or New Testament of the Bible.<br>- Study tools: Add colorful notes and bookmarks to verses and review your reading history.<br>- Spread the Word: Create and share beautiful images of Bible verses or build entire PDFs within the app for seamless sharing.<br>- Powerful search tools: Locate specific content in the Bible effortlessly.<br>- Daily inspiration: Receive an image of the Verse of the Day every day.<br>- Home screen widget: Add a widget to view inspirational verses directly on your home screen.<br>- Personalization: Customize your Bible reading experience with various themes and fonts.<br>- Protect your eyes: Activate night mode for a more relaxed Bible reading experience.<br>- Backup and Sync: Seamlessly transfer your bookmarks, notes and reading progress to another device.<br><br>APP CONTENT:<br>- The Bible in Modern Spanish<br>- The World Bible in Spanish<br>- The Reina Valera Bible 1909<br>- The Bear Bible (Cassiodoro de Reina 1569)<br><br>OUR WORK<br>This product has been carefully and lovingly crafted, and is a testament to our belief in the transformative power of the teachings of the Holy Bible, as well as our mission to make them more accessible to all.<br><br>JOIN OUR GROWING COMMUNITY<br>Be part of the millions of believers who have chosen our Modern Spanish Bible app for their daily readings of the Holy Bible. As we continue to expand, we now offer more Spanish Bible translations.<br><br>Download the Modern Spanish Bible app and take your own digital copy of the Holy Bible with you wherever you go! Follow us on Facebook: https://www.facebook.com/LaBibliaModernaApp",
    "summary": "Study the word of God and share verses with the Bible in Spanish App",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3827912,
    "score": 4.846377,
    "ratings": 52077,
    "reviews": 4393,
    "histogram": [
        449,
        247,
        550,
        4325,
        46491
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $3.49 per item",
    "developer": "Warp Studios Bibles",
    "developerId": "7359320133149714273",
    "developerEmail": "alfredo.warpstudios@gmail.com",
    "developerWebsite": "https://warpstudios.github.io",
    "developerAddress": "Luis Vivanco Castro 7029, Regi\u00f3n Metropolitana, Chile.",
    "privacyPolicy": "https://warpstudios.github.io/#/privacy_policy",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/bpsJznojBMHh1Vzl0UlBgBufLBeTX1Ns79Qo4CyLBQsF2h_l_u1BUM69iIGpUCublXM",
    "headerImage": "https://play-lh.googleusercontent.com/njzm-KwvKYNlTUX4iycT5sHgsyg-80qQXbIf81QW7r0-aQgRtOvSyfLVvoYYnyXwgvEh",
    "screenshots": [
        "https://play-lh.googleusercontent.com/__JkbBj0OvrkO9sHMunwJHUhLCoKAC4HpRUAhvAMI--6i5mTFSIFIqcoDC0N782HITH2",
        "https://play-lh.googleusercontent.com/JFeA54KYOEGOn8zVsAJVYVhVvwwumjmfznrleG6gBu-VT3i8rH9g9Kng7qI2t2SxSA",
        "https://play-lh.googleusercontent.com/PHBKyYCBHxU1Q-wCEPAJfsqEc7CX3BRfLgwL1vgP528LXT_FUQ7r_xTvc5KlXK222ng",
        "https://play-lh.googleusercontent.com/rPkf-D-3rmajvdehstiQiB8S2KP31e5CvF36cLOKplOmcONZYQcSulYUoJoEjOnItsw",
        "https://play-lh.googleusercontent.com/T9JCilFDOG4DxoLru7aYIV3T5RQoi_z3QQOX9_Q-MyPEQpZCrilVn2ChSq9-JUhhqg",
        "https://play-lh.googleusercontent.com/rRltsCRSVtWSjI3J_FgSZhelM72Makk5y4bvBoWgxPL7cKYbEmC9M73kikHlm5Xiv_I",
        "https://play-lh.googleusercontent.com/OHx3ORtYOFWsSQL-Ev13LB7vLWiDnOmdMV20VQKJvWi_BJ_dqBwjaLyEAIYfir2WtdA",
        "https://play-lh.googleusercontent.com/E5BVZ5jgVnzpEPA57YHkDazd-mCR_MzoWwwl7N0vwC0LabEaYW1Z-ftwL0PpF9_fnOen"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 9, 2013",
    "lastUpdatedOn": "Oct 13, 2024",
    "updated": 1728811719,
    "version": "3.3.4",
    "comments": [],
    "appId": "com.azwstudios.theholybible.em",
    "url": "https://play.google.com/store/apps/details?id=com.azwstudios.theholybible.em&hl=en&gl=us"
}