{
    "title": "Car Dashboard Speedometer HUD",
    "description": "This app has car dashboard speedometer that comes with amazing speedometer themes and customizable options. All you need to do is run this app and put your phone on the car dashboard, the reflection of your phone will show you the speedometer on your front car glass. Also get car speed alerts, monitor your car speed and record your vehicle mileage.\r\n\r\nApp Main Features: \r\n\r\n=> HUD (Head up Display) mode:- It supports HUD mode, which mirrors the display in either portrait mode or landscape mode.\r\n=> Orientation:- It supports both portrait and landscape mode and also supports sensor-based auto-rotate.\r\n=> Speed unit:- It supports MPH/KMH speed units.\r\n=> Speed warnings:- Set a max speed warning. It warns you if you exceeds the max speed during your journey.\r\n=> Color switch:- It allows you to switch between various display colors.\r\n=> Information display:- It displays time, battery, current/max/average speed, GPS status.\r\n=> Save your journey data in history.",
    "descriptionHTML": "This app has car dashboard speedometer that comes with amazing speedometer themes and customizable options. All you need to do is run this app and put your phone on the car dashboard, the reflection of your phone will show you the speedometer on your front car glass. Also get car speed alerts, monitor your car speed and record your vehicle mileage.<br><br>App Main Features: <br><br>=&gt; HUD (Head up Display) mode:- It supports HUD mode, which mirrors the display in either portrait mode or landscape mode.<br>=&gt; Orientation:- It supports both portrait and landscape mode and also supports sensor-based auto-rotate.<br>=&gt; Speed unit:- It supports MPH/KMH speed units.<br>=&gt; Speed warnings:- Set a max speed warning. It warns you if you exceeds the max speed during your journey.<br>=&gt; Color switch:- It allows you to switch between various display colors.<br>=&gt; Information display:- It displays time, battery, current/max/average speed, GPS status.<br>=&gt; Save your journey data in history.",
    "summary": "Monitor & record car speed data & vehicle mileage of your journey.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 105904,
    "score": 3.2666667,
    "ratings": 119,
    "reviews": 9,
    "histogram": [
        35,
        3,
        11,
        27,
        39
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$3.49 per item",
    "developer": "Stupendous Games",
    "developerId": "Stupendous+Games",
    "developerEmail": "stupendousgame@gmail.com",
    "developerWebsite": "https://stupendousgame.blogspot.com",
    "developerAddress": "Ravi Kiran Apt. Katargam, Surat, Gujarat, India.",
    "privacyPolicy": "http://adtubeservices.co.in/StupendousGames/privacy_policy.html",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/wzO4_gQLsP9CQAQRbx0EnPoDjmQyMwWBiYCIKcme9qBY0mjyQRjH8KO812LlX7LIiw",
    "headerImage": "https://play-lh.googleusercontent.com/9YrWXO_PeVfzw7thY0HlksmLJteSXd_a2QdLKcvy0bf7P_tNIl9Ty01kNKZaL1cMjYk",
    "screenshots": [
        "https://play-lh.googleusercontent.com/-4MfleXgEi1ndwX0oH9MGEat5Hi_EhP87LuwT7_zzXwiTzAwnQubhvWw5Vrmov_Om_g",
        "https://play-lh.googleusercontent.com/7R4LXbiKiodYt1PCMiUipIlhuINnRPFSfwf4p71RGLVPBwh5_A493cltwYeIrEOn2e4",
        "https://play-lh.googleusercontent.com/2cg3qngQHuHY9W2wEdCpaTSOzLIwhJ3x5ig_CCPeIZZc_PkGiboU6cqIyN8wDwCrLQ",
        "https://play-lh.googleusercontent.com/D4lVRkMCa-MA7o2rrUw6tpIY1ZhqAiSEAWDjk18-e0LFGQryPprldScgDv4YpiQlJuA",
        "https://play-lh.googleusercontent.com/HoX8V9pq81sNOMAknN7xzOCR9FYnomx9-UTYeee5Pxv6zcagxGcfKGfQnbH-XRtyzw",
        "https://play-lh.googleusercontent.com/fVjmvZMIWJO5Wxb6rdpYkcfdqg23pT09nWi3WiZexSQ_qmWHep-6ZyFCs9Qe60JaDAo",
        "https://play-lh.googleusercontent.com/m3DLtGwUloCRHkgicCfqzw2-EFjslbabsQH9xNccOfjGss-kQs9cT4OO7ms3riFehA",
        "https://play-lh.googleusercontent.com/lXVE-pgTEL3SnkDpRs4oqh95_Gv1FFt9qNBVnLCCm1nAksZFiwyPqL-XtuXIPIhPxE0",
        "https://play-lh.googleusercontent.com/cHZ-_xM_KBLWSDcI11AkGdp6eRlR_CxHeluQqQkubZeKyYTkUiyJ9PdxtV91NV399A",
        "https://play-lh.googleusercontent.com/I1kyahhUNrCJrmtk88BDyINE4_qGyFSvU_05s0J2EiskioNEdOlVA0htKOdH8EouAUg",
        "https://play-lh.googleusercontent.com/110MlrwE869Wq0D9SVX46qiTfLlV2pcAxSc5VcnEj-KnQGg8mitThBfSar7hADN0ekU",
        "https://play-lh.googleusercontent.com/WkzhBesOlSpKCam9Am-j0SmDB0mrTmwV5otzPnpIueqCga4GFyGb8TChWnTTAjAtxA",
        "https://play-lh.googleusercontent.com/QohuwfJC7lIM523f9lrQGiCOpJKd5hlqNcnkxUEhoii5jGXYjjWO_gbpdKWAvv2GWg",
        "https://play-lh.googleusercontent.com/gVLvCt97fezktKNt1VR7h1AclOtgFrXQdQ7xtKWWtJTJdzdGxxVzD3tpN9gjXLlOLn0",
        "https://play-lh.googleusercontent.com/nGWtkUOlc5KnJ8trvefwMzRIso_7wTsrrtOhEO9JHn1LYJhUfADRUr3ZAZM4_1ovHlkT",
        "https://play-lh.googleusercontent.com/XASkAsF9ZG9yiICLhY33wiIVjvaC_1nXBSzooEfnldpqziOvJlzL7UE8VBmaEH_-65Q",
        "https://play-lh.googleusercontent.com/IfVGrNG0LCHDkxF0UFQItXrwLI73oki_U4-Z6hlWVs6fFVZZd_7TJbNXT0Fk9ECZ0vo",
        "https://play-lh.googleusercontent.com/8HZnnPZ1lRw_GKOV0OzXcWRZx9XVRRR1qDqgJrdXGi4nYXKBoxGGQBVCYdjQhl55jW0",
        "https://play-lh.googleusercontent.com/Xn2e_agUKCZOrGFQzy41qHZ6QhBeJH9PfsGQQmLVfSYOf8kqey_GMpVCpZZiD10Rdgg",
        "https://play-lh.googleusercontent.com/EUIspw3ilKaVHMSvvFVHdy8V_v4QpaQU3NzY-AKBuUwpKDJjaQjmbRbBeLeUO_rsToA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 9, 2023",
    "lastUpdatedOn": "Sep 21, 2024",
    "updated": 1726908919,
    "version": "1.11",
    "comments": [],
    "appId": "com.stupendousgame.speedometer.hud.vs",
    "url": "https://play.google.com/store/apps/details?id=com.stupendousgame.speedometer.hud.vs&hl=en&gl=us"
}