{
    "title": "Mathmaji - Math Learning",
    "description": "\u25a0 What is Mathmaji?\r\n\r\nMathmaji is more than just a math app; it\u2019s an award-winning educational experience that brings the innovative Japanese method of structured problem-solving to your child's fingertips. Designed for young learners in grades K-4, Mathmaji focuses on building a strong foundation in essential math skills, boosting both confidence and comprehension. Just a few minutes of daily practice can make significant improvement to your child's math abilities. Mathmaji turns math learning into an exciting journey, making it fun and effective through gamified lessons and interactive drills. Explore over 500 engaging questions tailored to each grade level and watch your child\u2019s math skills soar!\r\n\r\n\u25a0 Why Choose Mathmaji for Your Child?\r\n\r\n1. Independent Mastery: Mathmaji empowers your child to independently master math, enhancing both academic performance and essential life skills.\r\n2. Skill Enhancement: Develops strong number sense, mental calculation, and critical problem-solving skills.\r\n3. Award-Winning Innovation: Proud Gold Prize winner at the 2023 Asia EdTech Summit for its approach to math education.\r\n4. Extensive Content: Access over 500 questions and drills, with one free lesson or drill available daily.\r\n5. Quick Comprehension: Designed for swift understanding and application of mathematical concepts.\r\n6. Structured Curriculum: Facilitates rapid learning of fundamental arithmetic through a carefully crafted curriculum.\r\n7. Simplified Methodology: Uses a unique approach to make multiplication and addition easy to understand.\r\n\r\nStart your child\u2019s math adventure with Mathmaji today!",
    "descriptionHTML": "\u25a0 What is Mathmaji?<br><br>Mathmaji is more than just a math app; it\u2019s an award-winning educational experience that brings the innovative Japanese method of structured problem-solving to your child&#39;s fingertips. Designed for young learners in grades K-4, Mathmaji focuses on building a strong foundation in essential math skills, boosting both confidence and comprehension. Just a few minutes of daily practice can make significant improvement to your child&#39;s math abilities. Mathmaji turns math learning into an exciting journey, making it fun and effective through gamified lessons and interactive drills. Explore over 500 engaging questions tailored to each grade level and watch your child\u2019s math skills soar!<br><br>\u25a0 Why Choose Mathmaji for Your Child?<br><br>1. Independent Mastery: Mathmaji empowers your child to independently master math, enhancing both academic performance and essential life skills.<br>2. Skill Enhancement: Develops strong number sense, mental calculation, and critical problem-solving skills.<br>3. Award-Winning Innovation: Proud Gold Prize winner at the 2023 Asia EdTech Summit for its approach to math education.<br>4. Extensive Content: Access over 500 questions and drills, with one free lesson or drill available daily.<br>5. Quick Comprehension: Designed for swift understanding and application of mathematical concepts.<br>6. Structured Curriculum: Facilitates rapid learning of fundamental arithmetic through a carefully crafted curriculum.<br>7. Simplified Methodology: Uses a unique approach to make multiplication and addition easy to understand.<br><br>Start your child\u2019s math adventure with Mathmaji today!",
    "summary": "Master math from the basics up, the FUN way! Start \u2018getting it\u2019 from the get-go!",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 30476,
    "score": 3.8039215,
    "ratings": 54,
    "reviews": 14,
    "histogram": [
        11,
        2,
        3,
        5,
        31
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$15.00 - $124.99 per item",
    "developer": "Mathmaji Co., Ltd.",
    "developerId": "Mathmaji+Co.,+Ltd.",
    "developerEmail": "contact-app+googleplay@mathmaji.com",
    "developerWebsite": "https://www.mathmaji.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.mathmaji.com/privacy-policy",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/RZaThrxrv9q5gCd17_G5hQV6SnRDGH0qLJmHvlWap1i8Uz3pMVu9XCtPAiHqTniWpDla",
    "headerImage": "https://play-lh.googleusercontent.com/gZTwSxTmgBvaU7Tkf50ygvxnHLcDf-1ACPhX_VGfEz_vzLfCzekwSxsqpx1_qv3U0_c",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Yy7i3DGWzcHiXLkZslWsq_U5IWXGHNAmmo7NaKzzkAT9lqNmyBTaGYZ7b_50FCS0EE4",
        "https://play-lh.googleusercontent.com/ven2vBHjkRV_DucF2NoBDS9jtLHxH9gD-lV8LDMbm8zfiL976LavyWoBHToYaWolFw",
        "https://play-lh.googleusercontent.com/xyQAnV1ZfQkW4xbGnSbWW9cLEM-2E9Vqoc_w9NpUmGP7iY2sYsD8Zekd49sogMJrODg",
        "https://play-lh.googleusercontent.com/z2d-j-Aq812Rqmd8w1WbhYUL7V4XcQnVntmE_lCuAe9hAdOnS1ovAiDHZrX4fDjVxQ",
        "https://play-lh.googleusercontent.com/Dc0h8qa1y36bKV3E-El4aAnk9lgg8BzYvypE1B2_a6MVs3Az-4rTAeGfpynZ1Kqqng",
        "https://play-lh.googleusercontent.com/UtO1nABofblmamvSqT3jqd0RJOKga0g-sQ9ZxVeulFvdSCEyY_bwrIaYx98jUy0gzg",
        "https://play-lh.googleusercontent.com/QHZwFTEqYp5q7qyxWasAxBC4ylLxO6rJlj7GIFRqwYOHwKORmpJD7Q6dTUj9ReEXwA",
        "https://play-lh.googleusercontent.com/7sXDuAhp6v5DogVvuRukR1icjj5jNglWzU2MtMhrjJLiA6DfI-Lx6KpxpuOYYZjeMNMU"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 19, 2023",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729225437,
    "version": "2410172",
    "comments": [],
    "appId": "com.mathmaji.app",
    "url": "https://play.google.com/store/apps/details?id=com.mathmaji.app&hl=en&gl=us"
}