{
    "title": "MyGenMobile App",
    "description": "Download the Gen Mobile app to manage your account with ease. You can change your plan, make payment, track your data usage, add more data or international talk credit and more!\r\n\r\nGen Mobile delivers the best value in wireless with affordable plans for every budget and free unlimited international calling to over 100 destinations on plans $20 and up.\r\n\r\nBuy a phone or bring your own and try one of our plans worry-free with a 7-day money-back guarantee.",
    "descriptionHTML": "Download the Gen Mobile app to manage your account with ease. You can change your plan, make payment, track your data usage, add more data or international talk credit and more!<br><br>Gen Mobile delivers the best value in wireless with affordable plans for every budget and free unlimited international calling to over 100 destinations on plans $20 and up.<br><br>Buy a phone or bring your own and try one of our plans worry-free with a 7-day money-back guarantee.",
    "summary": "July 2023: Great news! We've launched our new redesigned MyGenMobile App!",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 67288,
    "score": 3.24,
    "ratings": 264,
    "reviews": 117,
    "histogram": [
        100,
        10,
        7,
        15,
        128
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Gen Mobile",
    "developerId": "Gen+Mobile",
    "developerEmail": "genmobilecare@dish.com",
    "developerWebsite": "https://genmobile.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.genmobile.com/pages/privacy-policy",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/pUFwjz-vTd3dPaz8reba-HkU2ZM3Va6buoN2x3mwO-kwe5rVdWrHaKD2tt-BvyAWUg",
    "headerImage": "https://play-lh.googleusercontent.com/gji2LQaa1zULY7e47fAwNHaGuA03MQVptDm0oBRgCQkLR_ZA-IuhIhYrmLACGr4KZw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/YM6oaH3nNYhlAXgU97Ba_xq_eYtqoMnfV-R3tVZNH4Ex0SEEZbL_sjIMEltu1lRd3lU",
        "https://play-lh.googleusercontent.com/8qwVjUMSH89nsOeP7Vg8ltG0aoJpLIjC8blL6A2UuMQI8kkF9v6rE5MsUeFQGefUijU",
        "https://play-lh.googleusercontent.com/FjLoMYMLZvrnlkBL_xxHfSQTcTmCDqvXpq94jpVkimxR9TIGspE-61XvfVm2c60EcJSx",
        "https://play-lh.googleusercontent.com/j2Jmc2yKLrNLvPEZsWXdO3kx8HbmtA8dQhlH2tzacx0xj2Paj5DiFmXo3P5Gl-_4-g",
        "https://play-lh.googleusercontent.com/pk0iBlWRHit8p3CFVq2Ifh-Kpt6BIhXNPYYkE3Bd9sb8pGNioa-A_EsWsOp14Xn6BBGM",
        "https://play-lh.googleusercontent.com/HKseSZtX7V6Gn8V1JlbmEeJpwGMG4kyx444pFCKkuOjlJgm4VMJ9jbTPy2S7OorwWgcM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 7, 2023",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729623778,
    "version": "1.1.2",
    "comments": [],
    "appId": "com.genmobile.app",
    "url": "https://play.google.com/store/apps/details?id=com.genmobile.app&hl=en&gl=us"
}