{
    "title": "My Transgender Date: TS Dating",
    "description": "\u2705 OFFICIAL app of the My Transgender Date website.\r\n\r\n\ud83c\udfc6 My Transgender Date is the worldwide leader in trans dating.\r\n\r\n\ud83d\udcca My Transgender Date in numbers:\r\n\r\n\ud83d\udc49 Available in 12 languages\r\n\ud83d\udc49 With members from 190 countries\r\n\ud83d\udc49 1.8 million profiles created worldwide\r\n\ud83d\udc49 55,000 active monthly users\r\n\ud83d\udc49 210 million messages sent\r\n\ud83d\udc49 900+ new daily sign-ups\r\n\r\n\u2764\ufe0f For trans women and trans-attracted men looking for a real relationships\r\n\r\nMy Transgender Date was designed specifically for transgender women and for men who want to meet transgender women. We serve people from any race, background, age, and creed. Thousands of couples have already found each other on our app. Are you next? \r\n\r\n\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f For transgender women, by transgender women\r\n\r\nWe know what trans women need when it comes to transgender dating. Our team is essentially made of trans women. This makes us understand trans topics better than anyone else in the trans dating industry. Whether you are a trans woman looking for a serious relationship or a nice guy trying to find a lovely trans woman to date, we are here to help you in that journey.\r\n\r\n\ud83e\udd47 The best trans dating app\r\n\r\nThanks to our background, we know what we can offer you. Our website, My Transgender Date, was founded in 2013. With almost 10 years of being in the dating industry, we\u2019ve built our community and our database. In fact, our site comes before many other trans dating apps. This makes us proud and grateful for our growth in the community and the trust our clients have put in us over the last 10 years. \r\n\r\n\ud83d\udee0 A real support and tech team at your service\r\n\r\nBehind the scenes, our support team serves as the backbone of My Transgender Date. Composed entirely of transgender women, their extensive knowledge of the platform and profound personal experience within the community make them indispensable. They play a pivotal role in assisting you with any issues you may encounter, ensuring a seamless transgender dating and chat experience.\r\n\r\nOur technical team members have been with My Transgender Date since its inception a decade ago. This extensive tenure provides them with a profound understanding of the unique needs of a trans dating app. They are dedicated to keeping the technology up-to-date and ensuring a top-notch experience for you.\r\n\r\nWith our dedicated support and technical teams, you can enjoy your transgender dating journey with confidence, knowing that we've got your back every step of the way.\r\n\r\n\ud83e\udd29 A great online reputation\r\n\r\nOur 10 years of being online has garnered attention from the media. Rappler, ABS-CBN, BBC World, Refinery29, and many others have often featured us to talk about important topics regarding trans women and trans dating.\r\n\r\nBut for us, nothing is more important than our community reviews. So having a great rating on Trustpilot makes us proud of the work we have done and are still doing. No app is without negative user reviews, so we try our best to reply to those and note their feedback to improve our app.\r\n\r\n\u2699\ufe0f Features and \ud83d\udcb2Costs\r\n\r\nMy Transgender Date is 100% free for trans women, always been, always will be!\r\n\r\nTo protect our trans women members from trolls and time-wasters, men are asked to subscribe to our Premium plan in order to send messages (US$29.90 /mo).\r\n\r\nFeatures:\r\n\r\n\ud83d\udc49 Create your profile (Free)\r\n\ud83d\udc49 Browse profiles & photos (Free)\r\n\ud83d\udc49 Have access to our advanced search tool (Free)\r\n\ud83d\udc49 Be in the search results (Free)\r\n\ud83d\udc49 Full access to the favorite tool (Free)\r\n\ud83d\udc49 Check who viewed your profile (Free)\r\n\ud83d\udc49 Receive and read messages (Free)\r\n\ud83d\udc49 Send messages (Free for trans women, Premium plan for men)",
    "descriptionHTML": "\u2705 OFFICIAL app of the My Transgender Date website.<br><br>\ud83c\udfc6 My Transgender Date is the worldwide leader in trans dating.<br><br>\ud83d\udcca My Transgender Date in numbers:<br><br>\ud83d\udc49 Available in 12 languages<br>\ud83d\udc49 With members from 190 countries<br>\ud83d\udc49 1.8 million profiles created worldwide<br>\ud83d\udc49 55,000 active monthly users<br>\ud83d\udc49 210 million messages sent<br>\ud83d\udc49 900+ new daily sign-ups<br><br>\u2764\ufe0f For trans women and trans-attracted men looking for a real relationships<br><br>My Transgender Date was designed specifically for transgender women and for men who want to meet transgender women. We serve people from any race, background, age, and creed. Thousands of couples have already found each other on our app. Are you next? <br><br>\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f For transgender women, by transgender women<br><br>We know what trans women need when it comes to transgender dating. Our team is essentially made of trans women. This makes us understand trans topics better than anyone else in the trans dating industry. Whether you are a trans woman looking for a serious relationship or a nice guy trying to find a lovely trans woman to date, we are here to help you in that journey.<br><br>\ud83e\udd47 The best trans dating app<br><br>Thanks to our background, we know what we can offer you. Our website, My Transgender Date, was founded in 2013. With almost 10 years of being in the dating industry, we\u2019ve built our community and our database. In fact, our site comes before many other trans dating apps. This makes us proud and grateful for our growth in the community and the trust our clients have put in us over the last 10 years. <br><br>\ud83d\udee0 A real support and tech team at your service<br><br>Behind the scenes, our support team serves as the backbone of My Transgender Date. Composed entirely of transgender women, their extensive knowledge of the platform and profound personal experience within the community make them indispensable. They play a pivotal role in assisting you with any issues you may encounter, ensuring a seamless transgender dating and chat experience.<br><br>Our technical team members have been with My Transgender Date since its inception a decade ago. This extensive tenure provides them with a profound understanding of the unique needs of a trans dating app. They are dedicated to keeping the technology up-to-date and ensuring a top-notch experience for you.<br><br>With our dedicated support and technical teams, you can enjoy your transgender dating journey with confidence, knowing that we&#39;ve got your back every step of the way.<br><br>\ud83e\udd29 A great online reputation<br><br>Our 10 years of being online has garnered attention from the media. Rappler, ABS-CBN, BBC World, Refinery29, and many others have often featured us to talk about important topics regarding trans women and trans dating.<br><br>But for us, nothing is more important than our community reviews. So having a great rating on Trustpilot makes us proud of the work we have done and are still doing. No app is without negative user reviews, so we try our best to reply to those and note their feedback to improve our app.<br><br>\u2699\ufe0f Features and \ud83d\udcb2Costs<br><br>My Transgender Date is 100% free for trans women, always been, always will be!<br><br>To protect our trans women members from trolls and time-wasters, men are asked to subscribe to our Premium plan in order to send messages (US$29.90 /mo).<br><br>Features:<br><br>\ud83d\udc49 Create your profile (Free)<br>\ud83d\udc49 Browse profiles &amp; photos (Free)<br>\ud83d\udc49 Have access to our advanced search tool (Free)<br>\ud83d\udc49 Be in the search results (Free)<br>\ud83d\udc49 Full access to the favorite tool (Free)<br>\ud83d\udc49 Check who viewed your profile (Free)<br>\ud83d\udc49 Receive and read messages (Free)<br>\ud83d\udc49 Send messages (Free for trans women, Premium plan for men)",
    "summary": "The trans women\u2019s app to meet respectful men for authentic serious relationships",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 110358,
    "score": 3.6363637,
    "ratings": 754,
    "reviews": 30,
    "histogram": [
        194,
        22,
        57,
        68,
        411
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$29.90 per item",
    "developer": "Building Bridges Ltd",
    "developerId": "8699165340238701362",
    "developerEmail": "support@mytransgenderdate.com",
    "developerWebsite": "https://mytransgenderdate.com",
    "developerAddress": "25 Vitosha blvd, fl. 2, Sofia 1000, Bulgaria",
    "privacyPolicy": "https://mytransgenderdate.com/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/nKWPTFaiTa3LxmaBiDFpoBdBJDsq3mEEEgTa9Z389DwRlA6RySDG0HaBiy5uMjTL2RE",
    "headerImage": "https://play-lh.googleusercontent.com/gH3IF7TF_KkwnyLyy_AJCDwtBLPAFj31dAKLUnOeVZzDQzfyVZ2tifV0KOoTWo2dsw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/FMTlCNij_gpQQPFzL0b0FUKfI0wdRRdI5NGe8Uw7LUZNwRnHx593_1mcYtMgdyebCEY",
        "https://play-lh.googleusercontent.com/zbI3jBMsH0Tlvs8FY5qSwWCv0eJTKeh3p5Gefj_YBg_cjIK2SjL3nggHLS9U5uvlEOw",
        "https://play-lh.googleusercontent.com/Jus6zjtRt0N5vb1Eq7ZxnxcDJIuzM61lPQsZqDxvvTgdIPChKYCdrYn9Atq1e4Vs3_a-",
        "https://play-lh.googleusercontent.com/nBqNGExqEkx3CvIV8RFw6ADoaSPV1PA70qQbu5vOmyC3RZVBdp0TE5_HSrtDZsEGSTwn",
        "https://play-lh.googleusercontent.com/Ade8o3kCcfQgaHSKLNeI9dugYWubC_EmySJx2t4FM8_sD8f31AXMvAUwiC_tlI2xIw",
        "https://play-lh.googleusercontent.com/ZYUv3ElsCbRKnvDxb4SAU09dxt10LPqpZy1IKFjZOP6OMj1VRP8biz6LSSZCNLsioovW"
    ],
    "video": "https://www.youtube.com/embed/ByVBTWL-9H8?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/gH3IF7TF_KkwnyLyy_AJCDwtBLPAFj31dAKLUnOeVZzDQzfyVZ2tifV0KOoTWo2dsw",
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 17, 2023",
    "lastUpdatedOn": "Sep 15, 2024",
    "updated": 1726385484,
    "version": "0.14.8",
    "comments": [],
    "appId": "com.mytransgenderdate.app",
    "url": "https://play.google.com/store/apps/details?id=com.mytransgenderdate.app&hl=en&gl=us"
}