{
    "title": "GAMEE Prizes: Real Money Games",
    "description": "WIN big time real cash rewards in real money games every week playing 100% FREE games on GAMEE Prizes. 70+ different minigames, we bring new ones every month with more ways to win prizes!\r\n\r\nGAMEE PRIZES is an arcade with addictive F2P real money games where you can earn fast! Win big time on PayPal with our daily lottery and scratchers as well as by playing games. Collect n win: Earn tokens for playing games when you are bored for a weekly give away. Come back daily to spin the wheel and increase your chances of winning real money games. You get instant cash as soon as you hit 10$. \r\n\r\nGAMEE is a free-to-play (F2P) real money games arcade where users can earn real PayPal money by playing fun minigames. No in-app purchases necessary!!\r\n\r\nPlay +70 addictive real money games in one app, spin the Wheel of Fortune, compete in the daily ticket leaderboard to earn instant cash every day, or take part in the Lucky Games to win as much as $10,000 every 4 hours, FOR FREE!\r\n\r\nHow is this possible? We reward our gamers loyalty by sharing our ad revenue amongst them. The more cash in real money games we earn, the bigger the cash rewards & giveaways and the more winners we can have every day! Just play addictive real money games for when you are bored to win prizes & giveaways!\r\n\r\nEnjoy addicting F2P real money games & puzzles, quick and fun. Play 70+ different addicting arcades for when you are bored to earn prizes & giveaways!\r\n\r\nHow do I make free cash every week?\r\n\r\n\u2714 Collect n win: Collect free tickets and you will automatically participate in the giveaways of  +$5.000 given away every month in the Sunday draws!\r\n\u2714 Win big time cash prizes with hundreds of real money games winners every week! \r\n\u2714 Compete on the daily ticket leaderboard to win every 24h.\r\n\u2714 Play addicting F2P arcade to win instant prizes every 4h.\r\n\r\nHow do I get tickets?\r\n\r\n\u2714 Just play our F2P real money games in the Arcade and complete game missions \r\n\u2714 Spin the Wheel of Fortune and earn tons of tickets and free rewards including cash rewards. Each 7th consecutive login will give a chance to play Real Cash Wheel of Fortune. Start earning cash by playing today!\r\n\u2714 Invite friends to get lots of tickets and earn free cash from real money games\r\n\u2714 Level up and earn a ticket multiplier and earn up to 4x more tickets every gameplay!\r\n\r\nMore tickets = higher chance of winning free real money games prizes.\r\n\r\nPlay our F2P addicting games when you are bored and make cash in real money games, in lucky draws for free. There are no in-app purchases and no pay to win. Expect rewards, real cash prizes and opportunities to earn by playing addictive mini games! \r\n\r\nCome to GAMEE every day, bring your friends into your Prizes team and make cash together with every invite! There\u2019s no better way to play free games when you are bored than to win real money games and cash giveaways!\r\n\r\n\ud83d\udcb0 WIN REAL CASH MONEY REWARDS: every day there are opportunities to win big! Especially, Sundays!\r\n\ud83c\udf9f\ufe0f COLLECT n WIN: Just by playing F2P games and completing missions, you get rewards in tickets to win real prizes and giveaways! Invite friends to multiply tickets everyday for free.\r\n\ud83c\udfae Play to Earn: all our games are free to play (F2P), and we bring new real rewards & giveaways every month.\r\n\ud83c\udf81 DAILY REWARDS: Nnew missions and big rewards available daily to give you more chances to win lots of tickets to earn cash prizes. \r\n\ud83e\udd11 CHANCE TO WIN BIG WITH LOTTERY PRIZES: Play the daily lottery for free by choosing your lucky numbers and get the chance to make cash big time! Try to make every day your lucky day while playing games when you are bored!\r\n\r\n<b>GAMEE does not endorse or promote gambling. Absolutely no purchase or payment is required to participate in the sweepstakes or contests.</b>\r\n\r\n*Google Inc. does not sponsor, nor is any way affiliated with Gamee and/or the sweepstakes prizes.",
    "descriptionHTML": "WIN big time real cash rewards in real money games every week playing 100% FREE games on GAMEE Prizes. 70+ different minigames, we bring new ones every month with more ways to win prizes!<br><br>GAMEE PRIZES is an arcade with addictive F2P real money games where you can earn fast! Win big time on PayPal with our daily lottery and scratchers as well as by playing games. Collect n win: Earn tokens for playing games when you are bored for a weekly give away. Come back daily to spin the wheel and increase your chances of winning real money games. You get instant cash as soon as you hit 10$. <br><br>GAMEE is a free-to-play (F2P) real money games arcade where users can earn real PayPal money by playing fun minigames. No in-app purchases necessary!!<br><br>Play +70 addictive real money games in one app, spin the Wheel of Fortune, compete in the daily ticket leaderboard to earn instant cash every day, or take part in the Lucky Games to win as much as $10,000 every 4 hours, FOR FREE!<br><br>How is this possible? We reward our gamers loyalty by sharing our ad revenue amongst them. The more cash in real money games we earn, the bigger the cash rewards &amp; giveaways and the more winners we can have every day! Just play addictive real money games for when you are bored to win prizes &amp; giveaways!<br><br>Enjoy addicting F2P real money games &amp; puzzles, quick and fun. Play 70+ different addicting arcades for when you are bored to earn prizes &amp; giveaways!<br><br>How do I make free cash every week?<br><br>\u2714 Collect n win: Collect free tickets and you will automatically participate in the giveaways of  +$5.000 given away every month in the Sunday draws!<br>\u2714 Win big time cash prizes with hundreds of real money games winners every week! <br>\u2714 Compete on the daily ticket leaderboard to win every 24h.<br>\u2714 Play addicting F2P arcade to win instant prizes every 4h.<br><br>How do I get tickets?<br><br>\u2714 Just play our F2P real money games in the Arcade and complete game missions <br>\u2714 Spin the Wheel of Fortune and earn tons of tickets and free rewards including cash rewards. Each 7th consecutive login will give a chance to play Real Cash Wheel of Fortune. Start earning cash by playing today!<br>\u2714 Invite friends to get lots of tickets and earn free cash from real money games<br>\u2714 Level up and earn a ticket multiplier and earn up to 4x more tickets every gameplay!<br><br>More tickets = higher chance of winning free real money games prizes.<br><br>Play our F2P addicting games when you are bored and make cash in real money games, in lucky draws for free. There are no in-app purchases and no pay to win. Expect rewards, real cash prizes and opportunities to earn by playing addictive mini games! <br><br>Come to GAMEE every day, bring your friends into your Prizes team and make cash together with every invite! There\u2019s no better way to play free games when you are bored than to win real money games and cash giveaways!<br><br>\ud83d\udcb0 WIN REAL CASH MONEY REWARDS: every day there are opportunities to win big! Especially, Sundays!<br>\ud83c\udf9f\ufe0f COLLECT n WIN: Just by playing F2P games and completing missions, you get rewards in tickets to win real prizes and giveaways! Invite friends to multiply tickets everyday for free.<br>\ud83c\udfae Play to Earn: all our games are free to play (F2P), and we bring new real rewards &amp; giveaways every month.<br>\ud83c\udf81 DAILY REWARDS: Nnew missions and big rewards available daily to give you more chances to win lots of tickets to earn cash prizes. <br>\ud83e\udd11 CHANCE TO WIN BIG WITH LOTTERY PRIZES: Play the daily lottery for free by choosing your lucky numbers and get the chance to make cash big time! Try to make every day your lucky day while playing games when you are bored!<br><br><b>GAMEE does not endorse or promote gambling. Absolutely no purchase or payment is required to participate in the sweepstakes or contests.</b><br><br>*Google Inc. does not sponsor, nor is any way affiliated with Gamee and/or the sweepstakes prizes.",
    "summary": "Real Money Games! Play Arcade, Collect Prizes, Get Paid! Weekly Get Lucky Reward",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 26690357,
    "score": 4.4482102,
    "ratings": 748758,
    "reviews": 8670,
    "histogram": [
        37947,
        21578,
        54767,
        87028,
        547388
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $29.99 per item",
    "developer": "GAMEE",
    "developerId": "GAMEE",
    "developerEmail": "prizes@gamee.com",
    "developerWebsite": "https://prizes.gamee.com/",
    "developerAddress": "Unit 417-421, Cyberport 1, 100 Cyberport Road, Pokfulam, Hong Kong",
    "privacyPolicy": "https://prizes.gamee.com/privacy-policy",
    "genre": "Casino",
    "genreId": "GAME_CASINO",
    "categories": [
        {
            "name": "Casino",
            "id": "GAME_CASINO"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/xLHMpgYoQCj-006FoGNIArtYWf-An_xWxGC0s1sXhSR8Nhki1UHajTClxbqi8NbHdA",
    "headerImage": "https://play-lh.googleusercontent.com/hRbV1PJQDB9jkPgB8FgmWKSsr8Ml3VRQIEqXxld86ZAoz3UzU-5GiX7r4McTFV8Kqe4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nvaz-dRrMH-8I8TYq2qYMfaFxEOV7axESbN6ItEvB7aC82mWkmKxeIOO_8yL5KJutQ",
        "https://play-lh.googleusercontent.com/0WoDbPX4DZNczuMwnjXsRUcIszIj2u7JTFBlFgrt_7rRlzHbgD46BPxC2EMOwv_j9DCo",
        "https://play-lh.googleusercontent.com/Nv8gnUOzEIwLmCu4U0c9U3fj-nTdFNPQejWhLA7ebfMn32U4vlnKtnaCIRqASTZDn5g",
        "https://play-lh.googleusercontent.com/qi8kMvud7gFZtJYxxcU4FTkfRjh9rxFGPgDqIgCR3C2roOeH1ABhz9MxK7sROX1h9KI",
        "https://play-lh.googleusercontent.com/S6dOI6eQNHZAh9lR73QMc7590eyGYS7sDpmTNHA6sByTTOw26r1pvtG1eOJpCMOnuw",
        "https://play-lh.googleusercontent.com/BUDcp7yexv4R1ilSigEKiS80hQ7ebG1Hh7-r95zI7vEpQKP_pIKFEXdNaRqWLdpg7E8",
        "https://play-lh.googleusercontent.com/RqRi-1ZOjBKYXP1ZuqinbbUvQ5569oUkHfODvOWS0KzU5ChuaJP781vD_DKGrOpUvLU",
        "https://play-lh.googleusercontent.com/TDRQlWfHj72IXDXrjZ_pM3axu31Falj5TJloAfEazUo8iCrhdH5pW8aJdymcx_ilfg"
    ],
    "video": "https://www.youtube.com/embed/Qg3iT6zX15E?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/hRbV1PJQDB9jkPgB8FgmWKSsr8Ml3VRQIEqXxld86ZAoz3UzU-5GiX7r4McTFV8Kqe4",
    "contentRating": "Teen",
    "contentRatingDescription": "Simulated Gambling",
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 8, 2015",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729068777,
    "version": "5.5.2",
    "comments": [],
    "appId": "com.gameeapp.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.gameeapp.android.app&hl=en&gl=us"
}