{
    "title": "CozyRead - Explore Reading",
    "description": "Welcome to CozyRead!\r\nYou can explore a new realm of comfortable reading in CozyRead, CozyRead is just your dream reading companion.\r\n\r\n10000+ wonderful novels at your fingertips: CozyRead provides you with the latest and most popular massive wonderful stories, covering CEO, Werewolf, Romance, Urban, Suspense and other diverse themes to meet the needs of different readers. We provide the latest bestsellers as well as classic favorites, allowing you to immerse yourself in exciting stories anytime, anywhere.\r\n\r\nIntuitive and friendly design escorts your reading: CozyRead makes your reading experience more comfortable and convenient. Customized reading settings, such as font size, brightness and background color, let you adjust according to your personal preferences. Night and green modes protect your eyes from glare.\r\n\r\nIntelligent library records your reading progress: Built-in bookmarks let you easily mark content of interest and share it with other readers. At the same time, CozyRead will automatically record your progress, so that you can continue reading seamlessly next time when you open it.\r\n\r\nGet rid of novel shortages with personalized recommendations: Smart recommendations to ensure you're constantly discovering new stories and authors. Our recommendation engine will push you selected book lists based on your reading preferences and historical records to help you expand your reading field.\r\n\r\nDownload CozyRead and enjoy a feast of reading! Let fresh words and stories ignite your imagination, whether it is leisure time, commuting or the moment before bed, CozyRead will accompany you and leave precious reading traces.",
    "descriptionHTML": "Welcome to CozyRead!<br>You can explore a new realm of comfortable reading in CozyRead, CozyRead is just your dream reading companion.<br><br>10000+ wonderful novels at your fingertips: CozyRead provides you with the latest and most popular massive wonderful stories, covering CEO, Werewolf, Romance, Urban, Suspense and other diverse themes to meet the needs of different readers. We provide the latest bestsellers as well as classic favorites, allowing you to immerse yourself in exciting stories anytime, anywhere.<br><br>Intuitive and friendly design escorts your reading: CozyRead makes your reading experience more comfortable and convenient. Customized reading settings, such as font size, brightness and background color, let you adjust according to your personal preferences. Night and green modes protect your eyes from glare.<br><br>Intelligent library records your reading progress: Built-in bookmarks let you easily mark content of interest and share it with other readers. At the same time, CozyRead will automatically record your progress, so that you can continue reading seamlessly next time when you open it.<br><br>Get rid of novel shortages with personalized recommendations: Smart recommendations to ensure you&#39;re constantly discovering new stories and authors. Our recommendation engine will push you selected book lists based on your reading preferences and historical records to help you expand your reading field.<br><br>Download CozyRead and enjoy a feast of reading! Let fresh words and stories ignite your imagination, whether it is leisure time, commuting or the moment before bed, CozyRead will accompany you and leave precious reading traces.",
    "summary": "CozyRead will bring you endless pleasure and a comfortable reading experience",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 130881,
    "score": 4.8431373,
    "ratings": 903,
    "reviews": 206,
    "histogram": [
        16,
        0,
        16,
        33,
        831
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.99 - $49.99 per item",
    "developer": "Persistent Team",
    "developerId": "Persistent+Team",
    "developerEmail": "cozyread.info@wownovel.net",
    "developerWebsite": "https://cozyreadh5.wownovel.net/v1/h5/common/privacyAgreement.html",
    "developerAddress": "4th Floor, Incubation Building, Hainan Ecological Software Park, Old Town High-tech Industry Demonstration Zone, Chengmai County, Hainan Province",
    "privacyPolicy": "https://cozyreadh5.wownovel.net/v1/h5/common/privacyAgreement.html",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/kNnGobHuzxSz2eCl7lCtOuiQx-T8vTdqfvy2-vbxN_I7hOf5R65UFXtD6YD9MORyrR4",
    "headerImage": "https://play-lh.googleusercontent.com/w3XpOd27QfDlS98hMJNy51QQvT2GzzZUeJm8OdBSwT-Y47r4OqIP9e7DPzV1tRSRAx8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/nnBxj4rmBYZ7xj-QYBJvVLZZFmJWcFjgkwaQ_2BhNUVC56dJGcj47KsKIYiiOQGolrE",
        "https://play-lh.googleusercontent.com/jejr7dyfJLDfBeIfMRMwmDGXELiu4JdfKOIeEQRt4vGjWBYTzxEXY9mE6wc8YP8QIY4",
        "https://play-lh.googleusercontent.com/YUvYiE_A5JhGt5i5GaFERsUXWHLY8jAjXivohd4im7uTdtBOoMKIo2e7SQZHbctCbq4",
        "https://play-lh.googleusercontent.com/APj8quqgStn7sxM3sQ5Xlpm7y3KJ39vc-fNN49gU4MYI7MrQ9E6-KbzPMyD-FxUpZigO",
        "https://play-lh.googleusercontent.com/D95Mk_H1Uc5RL_A_m7qQa2UTkXCz5lPc1zwZ9-V11x-Rg4dj6GX0Mv_w5X_lG8716Q",
        "https://play-lh.googleusercontent.com/zktxw6YZe-ECBS3HtRo2hskTzMU3STMzUGa1zEP3FtzKKBokZwKb857SW85TVMR4Jl0",
        "https://play-lh.googleusercontent.com/zoyKBAj6dLEqyH9Alid3MvID1VHbFB5PXKuoakcmwBfaFu4GzsoQFjxsPrJX4QdYPDI",
        "https://play-lh.googleusercontent.com/Jkd8UJCVmSJWT_pxZGJqL1Knvdxpl26PfdeGi-ibgbYBZAQ_Jmz6Rsg54z7WesoM_w"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 3, 2023",
    "lastUpdatedOn": "Jan 30, 2024",
    "updated": 1706668126,
    "version": "2.4.0",
    "comments": [],
    "appId": "com.cozyread.app",
    "url": "https://play.google.com/store/apps/details?id=com.cozyread.app&hl=en&gl=us"
}