{
    "title": "SpaceWeatherLive",
    "description": "SpaceWeatherLive is the ultimate app for those who are interested in seeing the northern lights or want to know everything about the activity on our Sun. With this app you will be able to see and understand how active the aurora is right now and if there might be a good chance to spot the northern or southern lights in the coming days. You will never miss an aurora display again with this app in your pocket no matter where you go!\r\n\r\nBeginner friendly - While the SpaceWeatherLive app is filled with all the space weather information you can think of both for beginning and advanced space weather enthusiasts, every item has a pop up with additional information to help you along if something is unclear. Learn more as you go along!\r\n\r\nEverything in one app - Switch between the auroral activity and solar activity modes with just one click!\r\n\r\nDark mode - Preserve your night vision with our special dark mode! Ideal for aurora chasing out in the field!\r\n\r\nPush notifications - Free push notifications informing you of significant space weather events like solar flares, geomagnetic storms, earth-facing coronal holes and much more! You can turn any notification on or off so if you don't want to receive any notifications at all or are only interested in specific notifications: we got you covered!\r\n\r\nModern graphs - All the data that you are interested in are represented in sleek, responsive graphs. Dials don't cut it when you are out in the field, you want to know how the data looks like in the past and right now. Our graphs provide all the information you need in the blink of an eye!\r\n\r\nNews - Not only do we provide a ton of different automated alerts, we even have a dedicated team of space weather enthusiasts who write detailed hand written reports during high solar or auroral activity!\r\n\r\nExtensive help section - Are you a beginner and does our app look a bit daunting when you first open it? Fear not, we have a dedicated help section with tons of articles and a FAQ section. Give it a read and soon you will be able to make your very own aurora forecasts!\r\n\r\nHuge space weather archive - Ever looked back at your old aurora pictures and wonder what space weather was like on that specific date? We got you covered! Take a dive in our space weather archive that is filled to the brim with geomagnetic and solar data from the year 1996 until yesterday. Dig around and discover large sunspot regions, extreme geomagnetic storms and exciting data from the past!\r\n\r\nFree for all - Best of all... Our app is completely free of charge! We do have ads but those can be removed by purchasing a subscription which in turn supports us to keep our services online!\r\n\r\nPRICE AND TERMS:\r\nAlthough the app is free, it does contain advertising at the bottom of the screen which helps us to keep our services online. Don't want the ads? No problem, with a simple in-app subscription purchase you can remove them!\r\n\r\nPrices may vary in other countries respecting your local currency exchange rate. Your subscription will be charged to your Google Play account. At the end of the term, unless auto-renewable subscriptions are disabled, your subscription will automatically renew in your Google Play account. You will be charged for the regular price of your subscription within 24 hours prior to the end of the current term. You can turn off automatic renewal in your Google Play account settings at any time, but you must do so at least 24 hours before the end of the current term. Refunds will not be provided for the unused portion of any term.\r\nTerms and conditions: https://www.spaceweatherlive.com/en/app/terms-and-conditions\r\nPrivacy policy: https://www.spaceweatherlive.com/en/app/privacy-policy",
    "descriptionHTML": "SpaceWeatherLive is the ultimate app for those who are interested in seeing the northern lights or want to know everything about the activity on our Sun. With this app you will be able to see and understand how active the aurora is right now and if there might be a good chance to spot the northern or southern lights in the coming days. You will never miss an aurora display again with this app in your pocket no matter where you go!<br><br>Beginner friendly - While the SpaceWeatherLive app is filled with all the space weather information you can think of both for beginning and advanced space weather enthusiasts, every item has a pop up with additional information to help you along if something is unclear. Learn more as you go along!<br><br>Everything in one app - Switch between the auroral activity and solar activity modes with just one click!<br><br>Dark mode - Preserve your night vision with our special dark mode! Ideal for aurora chasing out in the field!<br><br>Push notifications - Free push notifications informing you of significant space weather events like solar flares, geomagnetic storms, earth-facing coronal holes and much more! You can turn any notification on or off so if you don&#39;t want to receive any notifications at all or are only interested in specific notifications: we got you covered!<br><br>Modern graphs - All the data that you are interested in are represented in sleek, responsive graphs. Dials don&#39;t cut it when you are out in the field, you want to know how the data looks like in the past and right now. Our graphs provide all the information you need in the blink of an eye!<br><br>News - Not only do we provide a ton of different automated alerts, we even have a dedicated team of space weather enthusiasts who write detailed hand written reports during high solar or auroral activity!<br><br>Extensive help section - Are you a beginner and does our app look a bit daunting when you first open it? Fear not, we have a dedicated help section with tons of articles and a FAQ section. Give it a read and soon you will be able to make your very own aurora forecasts!<br><br>Huge space weather archive - Ever looked back at your old aurora pictures and wonder what space weather was like on that specific date? We got you covered! Take a dive in our space weather archive that is filled to the brim with geomagnetic and solar data from the year 1996 until yesterday. Dig around and discover large sunspot regions, extreme geomagnetic storms and exciting data from the past!<br><br>Free for all - Best of all... Our app is completely free of charge! We do have ads but those can be removed by purchasing a subscription which in turn supports us to keep our services online!<br><br>PRICE AND TERMS:<br>Although the app is free, it does contain advertising at the bottom of the screen which helps us to keep our services online. Don&#39;t want the ads? No problem, with a simple in-app subscription purchase you can remove them!<br><br>Prices may vary in other countries respecting your local currency exchange rate. Your subscription will be charged to your Google Play account. At the end of the term, unless auto-renewable subscriptions are disabled, your subscription will automatically renew in your Google Play account. You will be charged for the regular price of your subscription within 24 hours prior to the end of the current term. You can turn off automatic renewal in your Google Play account settings at any time, but you must do so at least 24 hours before the end of the current term. Refunds will not be provided for the unused portion of any term.<br>Terms and conditions: https://www.spaceweatherlive.com/en/app/terms-and-conditions<br>Privacy policy: https://www.spaceweatherlive.com/en/app/privacy-policy",
    "summary": "The most complete aurora forecasting and solar activity app available!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 354190,
    "score": 4.17,
    "ratings": 1757,
    "reviews": 236,
    "histogram": [
        228,
        49,
        85,
        210,
        1176
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $9.99 per item",
    "developer": "Parsec vzw",
    "developerId": "Parsec+vzw",
    "developerEmail": "webmaster@spaceweatherlive.com",
    "developerWebsite": "https://www.spaceweatherlive.com",
    "developerAddress": "Cijnsstraat 9B\nB-9880 Aalter",
    "privacyPolicy": "https://www.spaceweatherlive.com/en/app/privacy-policy/",
    "genre": "Weather",
    "genreId": "WEATHER",
    "categories": [
        {
            "name": "Weather",
            "id": "WEATHER"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/BaghZXYdld5Fd5xoU0FA16S373DBroL3QAfc90xr7-OGNgoJDzCacPBb2ieHJsbwK-42",
    "headerImage": "https://play-lh.googleusercontent.com/-rhmeU9iGa2u6xxunE8eurt4aNqA1xWKt5mgfo3XLabjnFEQDN3vS4qMs60PZq-aHw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/zzAAsQKd4bSz5UrWhUCcJulBNhjPy87DyNtpcwuvrlwSP38JgBB_IH5jSWkYXCUmug",
        "https://play-lh.googleusercontent.com/RVNZWc_fZiyewmX01VV6lkUQx5OCbraFiLuvsWVMcnhYQLR9AHYHR-pNDstHAP7iDoI",
        "https://play-lh.googleusercontent.com/cP6-iOcdUblhd6eBr2AOMw0yePh6nAWZxFlSfRSclzQfxeDktztll5u0FNuA-M9bTCk",
        "https://play-lh.googleusercontent.com/tNjox8ULbw8Bpnu_rSBMZDNTuzT-xVxgAYWUUR8C6d1oN9YdewK063BwfV4QLiYwBMI",
        "https://play-lh.googleusercontent.com/zp_9J_MSRVNqOBiqkjk1AjiFGnVLh2ecl758MrUtpHoEWImXvQo_TiFjLDA-M4LRgXkV",
        "https://play-lh.googleusercontent.com/Muqmkv53vXkhV4IFGY7acrs2lGQIvEGQQtgVWnt2OxtzojmT4P0CqVsk69sYmV5B4YA",
        "https://play-lh.googleusercontent.com/hWz7yKmINw3PTyK0ozYnjG-R6lAiboPIgIJ1kn2OmGX86K8glruzheyqPZKWOV4owlw",
        "https://play-lh.googleusercontent.com/lgfE4XDsZzq0lj0y_uh7b2o76fSj2hebVff3hxWTc3nUqQKi1YbH5KbaF4QKlWvC_Yo",
        "https://play-lh.googleusercontent.com/f7lSM6kixmifpq4BefpoN-vympoYMeFsHxd_Oa3WJSyMhcm9tKnPnk6F6RHyBaKBv3aP",
        "https://play-lh.googleusercontent.com/NpBSD0LA9H9fVtRZqiBARc60euWeThcWT86p7fJxfoE3pptdlme9Bh7Cj3c-bGM8Y9o",
        "https://play-lh.googleusercontent.com/CZS7o57ox3vk9maKN8Uc3vHhvLzoo06Heu9tTE_sTvzY6L1oDeQhO2hpQYTAFDpECUM",
        "https://play-lh.googleusercontent.com/QSjfoYE-8OB0MnqFLlxVOcfIn-1Mxepv3wMDErLbJUo-Ks4MQKkGSBI8oQvQTTyJ7dm_",
        "https://play-lh.googleusercontent.com/kyvF8jE1RLktHxcE8Hw5FGacMxhN_v0AnEW7dMmXIaX3iw7973FvINdDsv3Yzadmp0gu",
        "https://play-lh.googleusercontent.com/9AfaLki3SnXeceovJJmQTQUAVhV7a4zgseZBGjdF6jKFprmb-fq-e8W61jpoGRIXeP4",
        "https://play-lh.googleusercontent.com/eF0rnnHD88YUCKP7zF4z8hYEuZoAbZNjy1F97Q9yBPlHaJkiRx2l5MbubyuEoQlgoqC1",
        "https://play-lh.googleusercontent.com/KhhQt2V_YNvoaLrEU2z1JDCXQhRGTJPrUL9LGs82k0-DTgIemnyjxqC-Kw9PV_Yro5E",
        "https://play-lh.googleusercontent.com/Nr5vIj7lM9UopyDrU7pGStU6MwQ9Y8F2snoW_sJNaAX0G9BmbW03xlipLpCeQMsMAw",
        "https://play-lh.googleusercontent.com/mIXrInlLMZ8gOeorq7Y54PCy_PggNOOecPDXvkdJ4RT3Q9QE8OsKnh_iAZA0fQQmWy4",
        "https://play-lh.googleusercontent.com/uD-pJ_iEc3D9w3OA3pnogiaHZRT4pwvwiaNVJQ8m6txRN8rYkPJaob7o2Km45mzJJMk",
        "https://play-lh.googleusercontent.com/RikCa7Ut8GvylsFLXLgIHUvBRsiqNBIjKE42zRYU4UA_APZvtCM5VyGDK5yWplfS3twd",
        "https://play-lh.googleusercontent.com/2o9jmC26Z6vwxhFLqAekVStUQSRK8v6whrfYte9o40lTpNemhe0gzUtArokb0stDuWmH"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 7, 2018",
    "lastUpdatedOn": "Mar 21, 2024",
    "updated": 1711043110,
    "version": "1.8.1",
    "comments": [],
    "appId": "com.spaceweatherlive.app",
    "url": "https://play.google.com/store/apps/details?id=com.spaceweatherlive.app&hl=en&gl=us"
}