{
    "title": "Panda Express",
    "description": "Good Fortune Awaits with Panda Rewards and the Panda Express\u00ae App. Order your Panda favorites on the fly for dine-in, take out, or delivery. And you can earn Panda Points when you satisfy your Panda cravings! \r\n\r\nFeatures:\r\n\r\n* Join Panda Rewards and earn Panda Points with qualifying purchases by ordering in the app or scanning your QR code in store or in our drive-thru!\r\n* Get surprise offers and use your Panda Points to unlock more rewards and redeem them for your Panda favorites.\r\n* Order for dine-in, take-out, or delivery and get your food whenever you want\u2014whether it's ASAP or scheduled for later.\r\n* Save and reorder your favorites with a single tap in your account!\r\n* Having a party? Our catering options are second to none. Just pick your sides + entrees and we\u2019ve got you covered!",
    "descriptionHTML": "Good Fortune Awaits with Panda Rewards and the Panda Express\u00ae App. Order your Panda favorites on the fly for dine-in, take out, or delivery. And you can earn Panda Points when you satisfy your Panda cravings! <br><br>Features:<br><br>* Join Panda Rewards and earn Panda Points with qualifying purchases by ordering in the app or scanning your QR code in store or in our drive-thru!<br>* Get surprise offers and use your Panda Points to unlock more rewards and redeem them for your Panda favorites.<br>* Order for dine-in, take-out, or delivery and get your food whenever you want\u2014whether it&#39;s ASAP or scheduled for later.<br>* Save and reorder your favorites with a single tap in your account!<br>* Having a party? Our catering options are second to none. Just pick your sides + entrees and we\u2019ve got you covered!",
    "summary": "Good Fortune Awaits with Panda Rewards and the Panda Express\u00ae App.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4734592,
    "score": 4.7480683,
    "ratings": 43422,
    "reviews": 17198,
    "histogram": [
        1036,
        365,
        792,
        4106,
        37118
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Panda Restaurant Group, Inc.",
    "developerId": "Panda+Restaurant+Group,+Inc.",
    "developerEmail": "guestrelations@pandarg.com",
    "developerWebsite": "https://www.pandaexpress.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.pandaexpress.com/legal#privacy-policy",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/yfXETQ7tmoxN9vzZegwQMosHZuRvVYRSuhFV4aV23j6vwg_9s8BPfNFqfuQpfrvB4Uk",
    "headerImage": "https://play-lh.googleusercontent.com/1kHfmEFklApMf1pm9gK4ttb_oVbzMhx53pZa-xGQv_7_W90a7JcrWNDc9SkcE7M3W-ZF",
    "screenshots": [
        "https://play-lh.googleusercontent.com/qOro6T-7xxdRb17jTe-n7RjNocfa97P4u8W5I3eWGRRUo30ljOIDbRSBtker60jyd-4",
        "https://play-lh.googleusercontent.com/_krMi4bSfAxYhFer5nTpZ9UGVTPTpnyhxZ6TeVVg5nMMbu83tivw-4VaCExKUPX2UZQ",
        "https://play-lh.googleusercontent.com/bLHgIFq0uumkjF1sJCwk8A7PDBBwx_nb5FOvqipm3AN69nXv5qeSuVFr-KA80Cjaiw",
        "https://play-lh.googleusercontent.com/gxl8vcbv6NkjPtFgasg3xN2PUT_tqn1eyks4GgKnReXnkIHRl9g7Y1BAGboiDFhrj4E",
        "https://play-lh.googleusercontent.com/BNO4H45Wx7wyryGITunqHIbHY8TkvQmr3vV6JYXId8iACERfePYY6SEfXr5Hn0hdDyc",
        "https://play-lh.googleusercontent.com/VDiuhvgBV6e2hulGPfyHB2Dos3-2MjdRju1HUtAnk_DPlgAwfgRv1RgnLN_mrwuT-3k0",
        "https://play-lh.googleusercontent.com/w-HQ4wD-oKHIOZ0xK4B0rdPMcOyARXlBVrgOgCSf6bQ93E-gR6X-SWruC2K0RmT7LQ",
        "https://play-lh.googleusercontent.com/mpMzXhamucUic9r2Dxz1uGHRX9zGEXX5cmsHROlwHcrtF2_S295bUxaijKuRIbb2qw",
        "https://play-lh.googleusercontent.com/8hSYaD9rTT0qrRiw3BW9yUQA8GIfV--rApk8RqQQ4seKtitOSLBFfYgHSlVYllWXUQ",
        "https://play-lh.googleusercontent.com/GsHTKwUbUX-fUwcB0RoXUPhd3FGrMXQT2g6h_B5oRyqI-m8BRSAosR5dG2YV2wOo9Ng",
        "https://play-lh.googleusercontent.com/TP0nJc9Urget1j6vH_r6aGZk8RCs4GP5QbMQ0xfIz2oNVVxNR1ly_138YkSooB4N0Qru",
        "https://play-lh.googleusercontent.com/Dt5ZMypMHLrjDCEFjZz3JvQANuK-fipO2yMTVPNeGHbhhtJcQ4LDO5W0dev0St_3TGU"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 20, 2014",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729093906,
    "version": "6.2.7",
    "comments": [],
    "appId": "com.pandaexpress.app",
    "url": "https://play.google.com/store/apps/details?id=com.pandaexpress.app&hl=en&gl=us"
}