{
    "title": "MedBridge GO for Patients",
    "description": "MedBridge GO gets you moving! Powered by award-winning content and technology, MedBridge GO is the premier app for you to complete exercises as prescribed by your therapist (PT, OT, AT, or SLP).\r\n\r\nTwo simple steps to get moving:\r\n1. Enter the access code from your provider to download your program\r\n2. Tap \u2018GO\u2019 to follow along with the exercise videos as they play on-screen\r\n\r\nYou can also set reminders, track overall progress, and view all of the Patient Education materials included by your therapist, from 3D models and explanatory exercise videos to clinician notes and PDF guides.",
    "descriptionHTML": "MedBridge GO gets you moving! Powered by award-winning content and technology, MedBridge GO is the premier app for you to complete exercises as prescribed by your therapist (PT, OT, AT, or SLP).<br><br>Two simple steps to get moving:<br>1. Enter the access code from your provider to download your program<br>2. Tap \u2018GO\u2019 to follow along with the exercise videos as they play on-screen<br><br>You can also set reminders, track overall progress, and view all of the Patient Education materials included by your therapist, from 3D models and explanatory exercise videos to clinician notes and PDF guides.",
    "summary": "MedBridge GO gets you moving - get back to doing what you love, faster!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1308403,
    "score": 4.9128814,
    "ratings": 30388,
    "reviews": 11051,
    "histogram": [
        226,
        102,
        164,
        1101,
        28790
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "MedBridge",
    "developerId": "MedBridge",
    "developerEmail": "patient.support@medbridge.com",
    "developerWebsite": "https://www.medbridgego.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.medbridgego.com/privacy_policy",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/7jPXd_1xf7xfE3Wzuvc5V1vc4yxfUZVhlD54Pq5Vfu7y_WEzzpF2Cz1bYfSE0YRo6Gk",
    "headerImage": "https://play-lh.googleusercontent.com/GcxEobkG-V2SzQZbstQq9-nu0I2JVoVijpuKRdS1gZnXnny6nnQtX-qZ9CcqI-eDK7U",
    "screenshots": [
        "https://play-lh.googleusercontent.com/k6127sfCwlfIG_EexHNX5v545oETvxRPE09faadRGQ4cKzU-dqrqOmNj9v59hBk8CYw",
        "https://play-lh.googleusercontent.com/YWz4eZY8ailyJHM9p67BWK-qP7vli01SKNybN3SDZop2THIaUHpuhJLOkLSD51kFEFg",
        "https://play-lh.googleusercontent.com/_deTj8vjzQ46BAUg84gutQHS-23A9S8eyRzhedo2Ij36yU_IEBgShWHAUQKNpT_3sBQ",
        "https://play-lh.googleusercontent.com/rS3QfLJ08Kn_LnOrxZIGS2ynSG-G0QkRdO-SiReWah1D-s6_V_rNlAATIlne8lI7kHQ",
        "https://play-lh.googleusercontent.com/hZREdY3KWuu5EwstY-P4uJa82J2GgmQLmRmBzUGKo8jloB_P9G2WSUu8oADoK1WYlA",
        "https://play-lh.googleusercontent.com/ZEDSbyOa8selD4jH-Jb9Axcu4PIJarygk8sHgzxjwVD92u_2EKxlUedMWo0R4sLPlWc",
        "https://play-lh.googleusercontent.com/cmHPXMSfBIiASQDmoZ91oaRy4YLXV5okm_ELRBCz4XPNcXp2UhLci8yrcgrNqV2QtSM",
        "https://play-lh.googleusercontent.com/h5rOCB4Qud_gGIQnJ2Ka4i2u0AulVvx83Xm_qOKG1C3UyUyXjBWZQLORWcgcKb-Az6I",
        "https://play-lh.googleusercontent.com/wxIb_QoSUvm1dTWyjOiirKx_X8gTOdN0FmmGKakOH7SI04GJa2SRRA8UJPE81oY1tIPd",
        "https://play-lh.googleusercontent.com/cRZ4HWdRaykxemVPrc03eGcpR-h4YWQ1Uj7MMtprgsCKqXjiEw3ytn1Cz3LDHg4Nnvi9",
        "https://play-lh.googleusercontent.com/5R6HcmEswxlrn7ppWjCtI09b-7rw8vbRTZT1ACZubMKYILB9ZCvLuBKFm20balLdhqk",
        "https://play-lh.googleusercontent.com/8zmhI0XkWAVSIPjvVYC5cZN72ehsQP33COjPuxzkf6bgOvQDCP_WbizObRER_JMl_2Y",
        "https://play-lh.googleusercontent.com/8p-Bqktk5YlrpxBqbFG57t3mDOF7WymrjqV--7uSH0wC_mGSEvbLJv7bkvLpDwwHWbYB",
        "https://play-lh.googleusercontent.com/E2a6I2tViBEz3h7584cWosbGzpqRcxR9_d82ZJtTj3udAVUChg_m8UCSwuPxDn9oVWY",
        "https://play-lh.googleusercontent.com/KG9nf-nqCIX_gWDixCTFIZDLOyj-Np4GGKYJvlB9nDJgfKlHLljxfC1_9M2Vs0vsPHo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 15, 2017",
    "lastUpdatedOn": "Apr 3, 2024",
    "updated": 1712207902,
    "version": "4.6.3",
    "comments": [],
    "appId": "com.medbridgeed.hep.go",
    "url": "https://play.google.com/store/apps/details?id=com.medbridgeed.hep.go&hl=en&gl=us"
}