{
    "title": "adidas: Shop Shoes & Clothing",
    "description": "YOUR ADIDAS - MORE THAN A SHOPPING EXPERIENCE. adidas puts you closer to the action with instant access to seasonal fashion releases, sneaker drops, and products that fit your personal style. Shop clothes, shoes, and gear for the fitness fashion you love most. Athlete inspiration, stories, and app exclusives \u2013 all available on adidas.\r\n\r\nRunning, training, basketball, baseball, soccer or golf? The adidas app has what you need and more. Whether you\u2019re putting time in time on the court, the gym, the golf course, or the track, adidas brings you the shoes and apparel to make the impossible, possible. Find motivation from collaborations with Patrick Mahomes, James Harden, Stella McCartney, and more. adidas combines sports and fashion like never before.\r\n\r\nStreetwear more your thing? The adidas app allows you to easily build your own 3-Stripes style. Discover Originals clothes and shoes that draw from adidas archives to shape the looks of today. With fitness fashion lines for men, women\u2019s clothing, and kids\u2019 apparel, adidas keeps it fresh season after season.\r\n\r\nUnlock the best of adidas and more of what you love with adiClub. Become a member and earn points you can use towards the next sneaker release, sports clothes, or fashion fit. Level up and unlock even more exclusive rewards by completing your profile, shopping, and leaving reviews. With free shipping and returns, adidas is always bringing you the best of adiClub benefits, all the time.\r\n\r\nBe the first to discover exclusive sneakers, sportswear collections, and the best in Originals streetwear. Download today and discover online shopping that\u2019s all in or nothing.\r\n\r\nADIDAS FEATURES\r\n\r\nEXCLUSIVE SHOES & SNEAKERS\r\n- Dive into collections of online shoes perfect for any sport or style\r\n- Shop shoes and sneakers from exclusive collaborations, only at adidas\r\n- Discover classic sneaker styles from adidas Originals like the iconic Samba\r\n\r\nSPORTSWEAR FOR EVERY ATHLETE\r\n- Discover clothes and gear perfect for your next workout or training session\r\n- Basketball, soccer, baseball, and more. adidas has the clothing you need to perform in style\r\n- Predator to Ultraboost, there\u2019s something for every athlete and activity\r\n\r\nADIDAS ORIGINALS & EXCLUSIVES\r\n- Shop legendary clothing from adidas with timeless pieces and styles\r\n- Discover clothes and shoes ranging from comfy lifestyle to fashionable streetwear\r\n- Enhance your 3-Stripe style with new releases and upcoming launches\r\n- Samba, Gazelle, Stan Smith, and more icons find the best of yesterday and tomorrow on adidas\r\n\r\nALL IN, ALL THE BENEFITS\r\n- Shop for online shoes and apparel with exclusive adiClub member benefits\r\n- Gain exclusive access to shop and vote on members-only sneakers, clothing and products\r\n- Unlock discounts, limited edition drops, and invitations to special events\r\n- Access free premium training apps, exclusive offers, and more great rewards\r\n\r\nCONVENIENT ONLINE SHOPPING\r\n- Get alerts when your favorite adidas sneakers and clothes go on sale\r\n- Order and buy in just a few taps\r\n- Get free standard shipping with adiClub\r\n- Track your orders and purchase history for easy returns\r\n- Gain access to special offers, rewards, gifts, and gear\r\n\r\nJoin adidas today and discover the latest in sportswear, streetwear, and fashion all in one.\r\n\r\n With adidas, \u201cYou Got This.\u201d Download today.",
    "descriptionHTML": "YOUR ADIDAS - MORE THAN A SHOPPING EXPERIENCE. adidas puts you closer to the action with instant access to seasonal fashion releases, sneaker drops, and products that fit your personal style. Shop clothes, shoes, and gear for the fitness fashion you love most. Athlete inspiration, stories, and app exclusives \u2013 all available on adidas.<br><br>Running, training, basketball, baseball, soccer or golf? The adidas app has what you need and more. Whether you\u2019re putting time in time on the court, the gym, the golf course, or the track, adidas brings you the shoes and apparel to make the impossible, possible. Find motivation from collaborations with Patrick Mahomes, James Harden, Stella McCartney, and more. adidas combines sports and fashion like never before.<br><br>Streetwear more your thing? The adidas app allows you to easily build your own 3-Stripes style. Discover Originals clothes and shoes that draw from adidas archives to shape the looks of today. With fitness fashion lines for men, women\u2019s clothing, and kids\u2019 apparel, adidas keeps it fresh season after season.<br><br>Unlock the best of adidas and more of what you love with adiClub. Become a member and earn points you can use towards the next sneaker release, sports clothes, or fashion fit. Level up and unlock even more exclusive rewards by completing your profile, shopping, and leaving reviews. With free shipping and returns, adidas is always bringing you the best of adiClub benefits, all the time.<br><br>Be the first to discover exclusive sneakers, sportswear collections, and the best in Originals streetwear. Download today and discover online shopping that\u2019s all in or nothing.<br><br>ADIDAS FEATURES<br><br>EXCLUSIVE SHOES &amp; SNEAKERS<br>- Dive into collections of online shoes perfect for any sport or style<br>- Shop shoes and sneakers from exclusive collaborations, only at adidas<br>- Discover classic sneaker styles from adidas Originals like the iconic Samba<br><br>SPORTSWEAR FOR EVERY ATHLETE<br>- Discover clothes and gear perfect for your next workout or training session<br>- Basketball, soccer, baseball, and more. adidas has the clothing you need to perform in style<br>- Predator to Ultraboost, there\u2019s something for every athlete and activity<br><br>ADIDAS ORIGINALS &amp; EXCLUSIVES<br>- Shop legendary clothing from adidas with timeless pieces and styles<br>- Discover clothes and shoes ranging from comfy lifestyle to fashionable streetwear<br>- Enhance your 3-Stripe style with new releases and upcoming launches<br>- Samba, Gazelle, Stan Smith, and more icons find the best of yesterday and tomorrow on adidas<br><br>ALL IN, ALL THE BENEFITS<br>- Shop for online shoes and apparel with exclusive adiClub member benefits<br>- Gain exclusive access to shop and vote on members-only sneakers, clothing and products<br>- Unlock discounts, limited edition drops, and invitations to special events<br>- Access free premium training apps, exclusive offers, and more great rewards<br><br>CONVENIENT ONLINE SHOPPING<br>- Get alerts when your favorite adidas sneakers and clothes go on sale<br>- Order and buy in just a few taps<br>- Get free standard shipping with adiClub<br>- Track your orders and purchase history for easy returns<br>- Gain access to special offers, rewards, gifts, and gear<br><br>Join adidas today and discover the latest in sportswear, streetwear, and fashion all in one.<br><br> With adidas, \u201cYou Got This.\u201d Download today.",
    "summary": "Shop back to school essentials all summer long - stylish sneakers, tees & more",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 66260751,
    "score": 4.791409,
    "ratings": 570087,
    "reviews": 11166,
    "histogram": [
        13384,
        3163,
        7745,
        40339,
        505427
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "adidas",
    "developerId": "8181465493603741900",
    "developerEmail": "adidas.app@adidas.com",
    "developerWebsite": "http://www.adidas.com/adidasapp",
    "developerAddress": "adi-dassler-str 1\n91074 herzogenaurach\ngermany",
    "privacyPolicy": "https://www.adidas.com/privacy_policy",
    "genre": "Sports",
    "genreId": "SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/iPzanFznFsaq0QPJ320jnt5MkFcs6katVZXW5JWTM7Mrdt9oOETeLVJBEf6Lpy52MIys",
    "headerImage": "https://play-lh.googleusercontent.com/iCBtsDalmrupuENoNHXxQn75a5bj4lR1HA0kU062wf1NmgGsscr7S_z-VenZheogiVL9",
    "screenshots": [
        "https://play-lh.googleusercontent.com/hrcHqTNmk6XNTb6SyxS_2QpeogeOLZKwm6NuBh71c7aQY29GKwL9CXfPkad1VeMuChA",
        "https://play-lh.googleusercontent.com/3qyc1EvMbdMqv0EfeNPG3IJa8o6Z2JBtpJWRsezCHIp81lPYb5EqRsHEUix8dd8vs_w",
        "https://play-lh.googleusercontent.com/viGlpP8uRYMtMIP6zWk97b6MTpxod_AZQFfI0THLEKoy3DlibvUUjlJv1CNd1I4IkQ",
        "https://play-lh.googleusercontent.com/nDkfHY8sAi-pfCjWzCQTjYldC1XtVovePe9O6u0Zpfjk0-J5-SQrQR4mcBRLTihalR4",
        "https://play-lh.googleusercontent.com/uku3FfpjWr7xi4V3osBRIRQEAVoym9jkvcbph__B3BVQi8iHUm4SjcdW3lEE8_XZvprH",
        "https://play-lh.googleusercontent.com/sM6Gvq0pto0dRdWnB4zDp8K_g1SQII87tnh24FAT1tITq0PVQWUcc_ghwPS0vY5Rqw",
        "https://play-lh.googleusercontent.com/dee-mTpTcqxRtieZxCXJ5qJDR9z_vpFxN3T-83z5FQI2iiofi8278YtmlgZkothcBO0n"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 5, 2017",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729182436,
    "version": "5.42.0",
    "comments": [],
    "appId": "com.adidas.app",
    "url": "https://play.google.com/store/apps/details?id=com.adidas.app&hl=en&gl=us"
}