{
    "title": "Google One",
    "description": "The Google One app lets you automatically back up your phone and manage your Google cloud storage.\r\n  \u2022 Automatically back up the important things on your phone, like photos, contacts and messages using your 15 GB of storage that comes with every Google account. If you break, lose or upgrade your phone, you can restore everything to your new Android device.\r\n  \u2022 Manage your existing Google account storage across Google Drive, Gmail and Google Photos.\r\n\r\n  Upgrade to a Google One membership to get even more:\r\n  \u2022 Get as much storage as you need for your important memories, projects and digital files. Choose the plan that works best for you.",
    "descriptionHTML": "The Google One app lets you automatically back up your phone and manage your Google cloud storage.<br>  \u2022 Automatically back up the important things on your phone, like photos, contacts and messages using your 15 GB of storage that comes with every Google account. If you break, lose or upgrade your phone, you can restore everything to your new Android device.<br>  \u2022 Manage your existing Google account storage across Google Drive, Gmail and Google Photos.<br><br>  Upgrade to a Google One membership to get even more:<br>  \u2022 Get as much storage as you need for your important memories, projects and digital files. Choose the plan that works best for you.",
    "summary": "Cloud storage, automatic phone backup, and more.",
    "installs": "1,000,000,000+",
    "minInstalls": 1000000000,
    "realInstalls": 2042969057,
    "score": 4.1917844,
    "ratings": 651161,
    "reviews": 39899,
    "histogram": [
        82066,
        21049,
        36600,
        61648,
        449788
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $249.99 per item",
    "developer": "Google LLC",
    "developerId": "5700313618786177705",
    "developerEmail": "apps-help@google.com",
    "developerWebsite": "http://one.google.com/",
    "developerAddress": "1600 Amphitheatre Parkway, Mountain View 94043",
    "privacyPolicy": "http://www.google.com/policies/privacy",
    "genre": "Productivity",
    "genreId": "PRODUCTIVITY",
    "categories": [
        {
            "name": "Productivity",
            "id": "PRODUCTIVITY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/B5AENJqFOd91t5cWZLTQbVUm7iDWzYVM1n0Pe2RI_46dhlWMtVAUBioUvy4YMXWdwA",
    "headerImage": "https://play-lh.googleusercontent.com/2VG6dN-J-hHps4uc5Ei0pVu6IZcMVvXKqUyEIVvCpDwjobsOmW13sClDiiMPEoQbdrL_",
    "screenshots": [
        "https://play-lh.googleusercontent.com/xcoYpL5PaW0Mu3Wye1itWvfoQHPhUZaO51t-C7_SjLlNAIc65FqnbLOiCYIyfmJbMjU",
        "https://play-lh.googleusercontent.com/HCSGxPwHeuNpZHSNn_BZQKAi4j4wGwsdFfLWMmlYJJWbXhrTT7Pz1r3wgoVCLduLQfQ",
        "https://play-lh.googleusercontent.com/apixL5Z9_rraVR9O4G0v_6ANQC57575ov-iGjvHRV5smbQbxhOAW3716mA8nAzHxHYax",
        "https://play-lh.googleusercontent.com/LQBa2_eT1aWIuF3v0nf2XGPEDsAWvpWQvreF0Lxub4zcP4xgzsIUyaameXf8B-IOag",
        "https://play-lh.googleusercontent.com/ON19Xd4I71GTht0sD591He5YJqcvrDjmWZ75cU0bRTB21rXNYdb1qBcq8aboumYqRSTh"
    ],
    "video": "https://www.youtube.com/embed/ViRM0OIJIPQ?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/2VG6dN-J-hHps4uc5Ei0pVu6IZcMVvXKqUyEIVvCpDwjobsOmW13sClDiiMPEoQbdrL_",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 24, 2018",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729539436,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.google.android.apps.subscriptions.red",
    "url": "https://play.google.com/store/apps/details?id=com.google.android.apps.subscriptions.red&hl=en&gl=us"
}