{
    "title": "CookUnity - A Chef Marketplace",
    "description": "<b>\u2022 About this app</b>\r\nExperience award-winning chefs at your table, every day. Ever-evolving menus, weekly deliveries, endless discovery. \r\n\r\n<b>\u2022 It\u2019s Chef-to-table. Your table.</b>\r\nThe best chefs in your city\u2014and in culinary cities across the country\u2014are taking care of dinner.\r\n\r\n<b>\u2022 Unmatched variety</b>\r\nWeekly-evolving menus for your ever-evolving palate. Whatever your mood, diet, or craving\u2014our chefs are making it.\r\n\r\n<b>\u2022 Effortless</b>\r\nYour meals for the week\u2014prepped and ready to go. Dinner on your table and on your fork in under 10 minutes.",
    "descriptionHTML": "<b>\u2022 About this app</b><br>Experience award-winning chefs at your table, every day. Ever-evolving menus, weekly deliveries, endless discovery. <br><br><b>\u2022 It\u2019s Chef-to-table. Your table.</b><br>The best chefs in your city\u2014and in culinary cities across the country\u2014are taking care of dinner.<br><br><b>\u2022 Unmatched variety</b><br>Weekly-evolving menus for your ever-evolving palate. Whatever your mood, diet, or craving\u2014our chefs are making it.<br><br><b>\u2022 Effortless</b><br>Your meals for the week\u2014prepped and ready to go. Dinner on your table and on your fork in under 10 minutes.",
    "summary": "Chefs create, we deliver.",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 58838,
    "score": 4.6587677,
    "ratings": 2089,
    "reviews": 711,
    "histogram": [
        69,
        9,
        39,
        326,
        1643
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "CookUnity Inc.",
    "developerId": "CookUnity+Inc.",
    "developerEmail": "support@cookunity.com",
    "developerWebsite": "https://www.cookunity.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.cookunity.com/",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/N33Lq9SyPb_gs3x--sCVG8ccFr2ocSOO-uIZUrVddoLfXmCnJW_NZmHCrND9gFf5JQw",
    "headerImage": "https://play-lh.googleusercontent.com/TZlqV73fA2M3g5tWElsHC9HZnnQp1W-lB-nd9k82FXdCAxOaIsJoxsTUFWWP0r0-SSu-",
    "screenshots": [
        "https://play-lh.googleusercontent.com/9jZ_gwbAUf5Ya0LHlhpangjra-JlR355cS1TIlXd7B3jm4Ea1Ll1QP2VktNyDp-9MJ0",
        "https://play-lh.googleusercontent.com/RojJF8KwlLGmuPCVhXs_iqDQRBtG83q9cKGyL5lyjKmxQn95zg7CZQrBh8YpsF9snfg",
        "https://play-lh.googleusercontent.com/jLqDCOBAIoFuBos9tcRWTFYr-Azj5mEMNo8lrmuNrkOpGVyQ0Gqn9iYBcfWljjVsh9k",
        "https://play-lh.googleusercontent.com/sm8Mz6zwy4HEe-nwfT5CUQniATIpzMkjaRSa_SHPx64JFxTJah_kZZhezKxdB5Kzkg",
        "https://play-lh.googleusercontent.com/TEoJIXT9-nK8bDctx3T4hAJIqtfLse-JScLvKfHQXlvvnSNugk4GJqVgpYfOkyW_I6zv",
        "https://play-lh.googleusercontent.com/uIghVhER6Htp0P2pK-vNa10zB28eGp-mWJL6NfX5O3FuWBMx1KCKQ7kiUc0y1j0t1WtA",
        "https://play-lh.googleusercontent.com/ZOdQXRs2OUsJfvmAEbHyKcdqaqljq4EGX_JuQfltYXxBcg9ViVmu1uSDlhCvNsiG4yf9",
        "https://play-lh.googleusercontent.com/urxu0doVQaXNvLkBsvhw4k13YgJealbhbxfQAb5iMKSl5CWpBAR1-J4qcBo1_o5ydye7"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 21, 2022",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729077970,
    "version": "2.23.0",
    "comments": [],
    "appId": "com.cookunity.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.cookunity.android.app&hl=en&gl=us"
}