{
    "title": "Xoom: Send Money & Transfer",
    "description": "Xoom is the fast, safe, and reliable way to send money to friends and family abroad. We have you covered with:\r\n24/7 transaction protection and fraud monitoring. Because we're a PayPal service, your transactions and financial info are secured by PayPal's trusted technology\r\nCompetitive and transparent rates for you, and no transaction fees for your contacts\r\nEasy access to your PayPal wallet, so you can use your PayPal payment methods on Xoom\r\nUpfront delivery times and real-time tracking updates, so you know when your money will be delivered\r\nMultiple ways to send, including bank deposits, cash pickup, and mobile wallet transfers\r\nQuickly reload mobile phones. Just log in to Xoom, enter your contact\u2019s number, and pay in seconds\r\nSend money directly to friends and family \u2013 they don\u2019t need a PayPal or Xoom account\r\n\r\nMexico\r\nSend money to all major banks including BBVA Bancomer, BanCoppel, Banorte, and Banamex. Money is typically available same day*. Your contacts can pick up cash from over 41,000 trusted locations like OXXO and Elektra. Money is typically available in minutes*. Reload minutes to Telcel, ATT&T, and others\r\n\r\nThe Philippines \r\nSend money to over 35 banks including Banco de Oro and Bank of the Philippine Islands. Your contacts can pick up cash from over 12,000 reliable locations like Cebuana Lhuillier and M. Lhuillier. Money is typically available in minutes* when you send to banks or for cash pickup\r\n\r\nIndia\r\nSend money to all banks in India including State Bank of India, ICICI, HDFC Bank, and Axis Bank. Send via UPI ID or with your contact\u2019s bank info. Your contacts can pick up cash from over 100,000 convenient locations like Muthoot Finance and Manappuram Finance. Money is typically ready in minutes* when you send to banks or for cash pickup\r\n\r\nDominican Republic\r\nSend money to all major banks including BanReservas, Banco BHD, and Banco Popular. Money is typically available next business day*. Your contacts can pick up cash from over 500 trusted locations like Caribe Express and Banco BHD Le\u00f3n. Money is typically available in minutes*. You can even send money to someone\u2019s doorstep via Caribe Express or Remesas Dominicanas\r\n\r\nColombia\r\nSend money to all major banks including Bancolombia and Davivienda. Your contacts can pick up cash from over 2500 locations like SuperGiros and Bancolombia.\r\n\r\nYou can even send money to friends and family who live in the United States! Send money to your contact\u2019s bank account, or their Visa or MasterCard debit card. Your contacts can pick up cash from over 5,000 locations like Ria. Money is typically ready in minutes* when you send to banks or for cash pickup\r\n\r\nYou can also send to: Albania, Algeria, Argentina, Armenia, Australia, Austria, Bahrain, Bangladesh, Belarus, Belgium, Belize, Benin, Bhutan, Bolivia, Botswana, Brazil, Bulgaria, Burkina Faso, Burundi, Cambodia, Cameroon, Canada, Cayman Islands, Chile, China, Comoros, Congo, Costa Rica, Croatia, Cyprus, Czech Republic, DR Congo, Denmark,  Djibouti, Ecuador, Egypt, El Salvador, Eritrea, Estonia, Ethiopia, Finland, France, Gabon, Gambia, Georgia, Germany, Ghana, Greece, Guatemala, Guinea, Guinea-Bissau, Guyana, Haiti, Honduras, Hong Kong, Hungary, Indonesia, Ireland, Israel, Italy, Ivory Coast, Jamaica, Japan, Jordan, Kenya, Kuwait, Kyrgyzstan, Latvia, Liberia, Lithuania, Luxembourg, Macedonia, Madagascar, Malawi, Malaysia, Mali, Malta, Moldova, Mongolia, Montenegro, Morocco, Mozambique, Myanmar, Namibia, Nepal, Netherlands, New Zealand, Nicaragua, Niger, Nigeria, Norway, Oman, Pakistan, Panama, Paraguay, Peru, Poland, Portugal, Puerto Rico, Qatar, Romania, Russia, Rwanda, Samoa, Saudi Arabia, Senegal, Serbia, Sierra Leone, Singapore, Slovakia, Slovenia, South Africa, South Korea, Spain, Sri Lanka, Suriname, Swaziland, Sweden, Switzerland, Tajikistan, Tanzania, Thailand, Togo, Tonga, Tunisia, Uganda, Ukraine, UAE, UK, Uruguay, Uzbekistan, Vietnam, Zambia, Zimbabwe\r\n*Transfers subject to review and may be delayed or stopped if an issue is identified",
    "descriptionHTML": "Xoom is the fast, safe, and reliable way to send money to friends and family abroad. We have you covered with:<br>24/7 transaction protection and fraud monitoring. Because we&#39;re a PayPal service, your transactions and financial info are secured by PayPal&#39;s trusted technology<br>Competitive and transparent rates for you, and no transaction fees for your contacts<br>Easy access to your PayPal wallet, so you can use your PayPal payment methods on Xoom<br>Upfront delivery times and real-time tracking updates, so you know when your money will be delivered<br>Multiple ways to send, including bank deposits, cash pickup, and mobile wallet transfers<br>Quickly reload mobile phones. Just log in to Xoom, enter your contact\u2019s number, and pay in seconds<br>Send money directly to friends and family \u2013 they don\u2019t need a PayPal or Xoom account<br><br>Mexico<br>Send money to all major banks including BBVA Bancomer, BanCoppel, Banorte, and Banamex. Money is typically available same day*. Your contacts can pick up cash from over 41,000 trusted locations like OXXO and Elektra. Money is typically available in minutes*. Reload minutes to Telcel, ATT&amp;T, and others<br><br>The Philippines <br>Send money to over 35 banks including Banco de Oro and Bank of the Philippine Islands. Your contacts can pick up cash from over 12,000 reliable locations like Cebuana Lhuillier and M. Lhuillier. Money is typically available in minutes* when you send to banks or for cash pickup<br><br>India<br>Send money to all banks in India including State Bank of India, ICICI, HDFC Bank, and Axis Bank. Send via UPI ID or with your contact\u2019s bank info. Your contacts can pick up cash from over 100,000 convenient locations like Muthoot Finance and Manappuram Finance. Money is typically ready in minutes* when you send to banks or for cash pickup<br><br>Dominican Republic<br>Send money to all major banks including BanReservas, Banco BHD, and Banco Popular. Money is typically available next business day*. Your contacts can pick up cash from over 500 trusted locations like Caribe Express and Banco BHD Le\u00f3n. Money is typically available in minutes*. You can even send money to someone\u2019s doorstep via Caribe Express or Remesas Dominicanas<br><br>Colombia<br>Send money to all major banks including Bancolombia and Davivienda. Your contacts can pick up cash from over 2500 locations like SuperGiros and Bancolombia.<br><br>You can even send money to friends and family who live in the United States! Send money to your contact\u2019s bank account, or their Visa or MasterCard debit card. Your contacts can pick up cash from over 5,000 locations like Ria. Money is typically ready in minutes* when you send to banks or for cash pickup<br><br>You can also send to: Albania, Algeria, Argentina, Armenia, Australia, Austria, Bahrain, Bangladesh, Belarus, Belgium, Belize, Benin, Bhutan, Bolivia, Botswana, Brazil, Bulgaria, Burkina Faso, Burundi, Cambodia, Cameroon, Canada, Cayman Islands, Chile, China, Comoros, Congo, Costa Rica, Croatia, Cyprus, Czech Republic, DR Congo, Denmark,  Djibouti, Ecuador, Egypt, El Salvador, Eritrea, Estonia, Ethiopia, Finland, France, Gabon, Gambia, Georgia, Germany, Ghana, Greece, Guatemala, Guinea, Guinea-Bissau, Guyana, Haiti, Honduras, Hong Kong, Hungary, Indonesia, Ireland, Israel, Italy, Ivory Coast, Jamaica, Japan, Jordan, Kenya, Kuwait, Kyrgyzstan, Latvia, Liberia, Lithuania, Luxembourg, Macedonia, Madagascar, Malawi, Malaysia, Mali, Malta, Moldova, Mongolia, Montenegro, Morocco, Mozambique, Myanmar, Namibia, Nepal, Netherlands, New Zealand, Nicaragua, Niger, Nigeria, Norway, Oman, Pakistan, Panama, Paraguay, Peru, Poland, Portugal, Puerto Rico, Qatar, Romania, Russia, Rwanda, Samoa, Saudi Arabia, Senegal, Serbia, Sierra Leone, Singapore, Slovakia, Slovenia, South Africa, South Korea, Spain, Sri Lanka, Suriname, Swaziland, Sweden, Switzerland, Tajikistan, Tanzania, Thailand, Togo, Tonga, Tunisia, Uganda, Ukraine, UAE, UK, Uruguay, Uzbekistan, Vietnam, Zambia, Zimbabwe<br>*Transfers subject to review and may be delayed or stopped if an issue is identified",
    "summary": "Xoom is the fast, safe, and reliable way to send money to friends and family",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 8306629,
    "score": 4.75934,
    "ratings": 328800,
    "reviews": 29008,
    "histogram": [
        7045,
        1913,
        7456,
        30286,
        282095
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Xoom, a PayPal Service",
    "developerId": "Xoom,+a+PayPal+Service",
    "developerEmail": "product.feedback@xoom.com",
    "developerWebsite": "http://www.xoom.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.xoom.com/privacy",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/CSLoeTUtNm2q9hku76D9WzpladMeljalW7iR1pOvoaMYzoyNYHIHFHbD6nn1ieoCbw",
    "headerImage": "https://play-lh.googleusercontent.com/VEzi7TLBy9n6MbVl-HJVrg2SvAogmVdbEi7Hr-_fknRF9HfFe8Yi4Io7Dblx7afvuR8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/DDNVg_0YoNWwQl5LoLq4H0xLi82JsuAMarAO3V8WaXocI243I1y1X2hatVCuhgfCoQ",
        "https://play-lh.googleusercontent.com/rDEw6EwxDEnJw1FRRzribZjpvp5HJiYUiRP7KPVPClgf5GOKDSOtMC2PNIbZB7VAXrY",
        "https://play-lh.googleusercontent.com/9TYm2dn8oH5hFhNlbiA4IjZo1kWhUYdR3ceUVa0zIayAQrf_0SZTSSngLgLUh6nyMw",
        "https://play-lh.googleusercontent.com/qngIfPJih89l3IhCKlNZpz5mKboqPPNFi2MLWMmIpTN2531skKPG_ned9ymjZ3eSQ2k",
        "https://play-lh.googleusercontent.com/TzKW22Y08gZOc0nSjSELr7A8ZFOyKXmOZlhl-saTgBUNs0KIkq6dA8IGc-3cLHU5Ig",
        "https://play-lh.googleusercontent.com/VKCBd9NtYzIgILJufFTDm3xxOs4YlsGSKhKeqzpfJtTvPpyBFPXfy7u0Yw4I0Z9p4fen",
        "https://play-lh.googleusercontent.com/0KXoeNvsoiGQUsG_YY4Z8JWu0qO1SXOGn9NZZBSaiYeWMWYvvj_YHfvBk91aWMN5zkw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 8, 2012",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729028601,
    "version": "9.18.0",
    "comments": [],
    "appId": "com.xoom.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.xoom.android.app&hl=en&gl=us"
}