{
    "title": "Fling Dating App: Meet & Play",
    "description": "Welcome to Fling, the ultimate dating playground for the curious & bold.\r\n\r\nFor 15 epic years we\u2019ve helped our like-minded community video chat with friends around the globe, set the mood with clear intentions and meet genuine people who match your energy and passion. We make dating exciting, safe, and seriously enjoyable. Because let\u2019s face it, anything less would be boring. Here\u2019s to 15 more years of uninhibited dating done your way!\r\n\r\nWhy Dive Into Fling?\r\n\r\n\u2605 Real and Verified Users: Authenticity is our mantra. With a 24/7 team dedicated to maintaining a community of real adults, you can trust Fling for genuine connections. Safety and seriously good vibes go hand-in-hand here.\r\n\r\n\u2605 Profile Quality Score: Discover the cr\u00e8me de la cr\u00e8me with our unique Profile Quality Scorecard (patent pending). We bring the best profiles right to you.\r\n\r\n\u2605 Privacy Guaranteed: Your privacy is our top priority. Explore private profiles, make easy and safe transactions. Feel confident knowing your information is secure. Fling has never and will never share your data with third parties.\r\n\r\n\u2605 Mutual Match Feature: Instantly connect and date like-minded men, women or any gender who share your interests, passions and matches your mood. Our system is all about building real compatibility for long-lasting and meaningful connections.\r\n\r\n\u2605 Enhanced Messaging: Share the moment with direct messaging and create an electrifying space with your match. Shine and stand out with our featured priority messaging to ensure you get the responses you want.\r\n\r\n\u2605 Global Community: Whether you\u2019re in the US, Canada, the UK, Australia, South America, Europe or beyond, Fling connects you with someone special no matter where you are.\r\n\r\n\u2605 Easy Signup: Joining Fling is a breeze. With a quick and secure signup process, your profile can be live in minutes. Just upload an awesome pic of YOU, add a bit about yourself and you\u2019re in. It\u2019s that simple!\r\n\r\n\u2605 Explore with Confidence: Fling offers a satisfaction guarantee for connections and the ability to search all members with zero fees. Browse freely and find potential matches without initial commitments. We\u2019re confident you\u2019ll love it here.\r\n\r\nJoin our authentic and transparent Fling Community. Find your tribe with honest people that truly get what dating freely is all about. Whether it\u2019s casual fun, only friends or something that\u2019s forever, Fling creates that moment of rush, excitement and togetherness that shapes a robust and lively dating experience.\r\n\r\nDownload Fling today to share freely, explore safely, get the community buzzing or just sit back and soak it all in. It\u2019s your space - set the perfect mood.\r\n\r\n- Contact us: https://www.fling.com/members/info/customerservice\r\n- Terms of Use: https://www.fling.com/members/info/terms\r\n- Privacy Policy: https://www.fling.com/members/info/privacy",
    "descriptionHTML": "Welcome to Fling, the ultimate dating playground for the curious &amp; bold.<br><br>For 15 epic years we\u2019ve helped our like-minded community video chat with friends around the globe, set the mood with clear intentions and meet genuine people who match your energy and passion. We make dating exciting, safe, and seriously enjoyable. Because let\u2019s face it, anything less would be boring. Here\u2019s to 15 more years of uninhibited dating done your way!<br><br>Why Dive Into Fling?<br><br>\u2605 Real and Verified Users: Authenticity is our mantra. With a 24/7 team dedicated to maintaining a community of real adults, you can trust Fling for genuine connections. Safety and seriously good vibes go hand-in-hand here.<br><br>\u2605 Profile Quality Score: Discover the cr\u00e8me de la cr\u00e8me with our unique Profile Quality Scorecard (patent pending). We bring the best profiles right to you.<br><br>\u2605 Privacy Guaranteed: Your privacy is our top priority. Explore private profiles, make easy and safe transactions. Feel confident knowing your information is secure. Fling has never and will never share your data with third parties.<br><br>\u2605 Mutual Match Feature: Instantly connect and date like-minded men, women or any gender who share your interests, passions and matches your mood. Our system is all about building real compatibility for long-lasting and meaningful connections.<br><br>\u2605 Enhanced Messaging: Share the moment with direct messaging and create an electrifying space with your match. Shine and stand out with our featured priority messaging to ensure you get the responses you want.<br><br>\u2605 Global Community: Whether you\u2019re in the US, Canada, the UK, Australia, South America, Europe or beyond, Fling connects you with someone special no matter where you are.<br><br>\u2605 Easy Signup: Joining Fling is a breeze. With a quick and secure signup process, your profile can be live in minutes. Just upload an awesome pic of YOU, add a bit about yourself and you\u2019re in. It\u2019s that simple!<br><br>\u2605 Explore with Confidence: Fling offers a satisfaction guarantee for connections and the ability to search all members with zero fees. Browse freely and find potential matches without initial commitments. We\u2019re confident you\u2019ll love it here.<br><br>Join our authentic and transparent Fling Community. Find your tribe with honest people that truly get what dating freely is all about. Whether it\u2019s casual fun, only friends or something that\u2019s forever, Fling creates that moment of rush, excitement and togetherness that shapes a robust and lively dating experience.<br><br>Download Fling today to share freely, explore safely, get the community buzzing or just sit back and soak it all in. It\u2019s your space - set the perfect mood.<br><br>- Contact us: https://www.fling.com/members/info/customerservice<br>- Terms of Use: https://www.fling.com/members/info/terms<br>- Privacy Policy: https://www.fling.com/members/info/privacy",
    "summary": "No Strings, No Judgment - All Heat!",
    "installs": "5,000+",
    "minInstalls": 5000,
    "realInstalls": 7930,
    "score": 3.7222223,
    "ratings": 18,
    "reviews": 12,
    "histogram": [
        4,
        2,
        0,
        1,
        11
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Dime Systems",
    "developerId": "Dime+Systems",
    "developerEmail": "support@fling.com",
    "developerWebsite": "https://www.fling.com",
    "developerAddress": null,
    "privacyPolicy": "https://fling.com/members/info/privacy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/J9BnMoAHrpkCLFyLTbXYFuJ7ykkthN9P1IxRggVwo8-f6t6KeFaklJYy3javueXgxB0",
    "headerImage": "https://play-lh.googleusercontent.com/h8fW3nBLmMfG23suryp7hvMrP5wWlYM1d-TM87IBNUKNvkzLNJK4kvXTQKKuRgTlvqo",
    "screenshots": [
        "https://play-lh.googleusercontent.com/4xt3mXVlQWGpNwS2P9RKFk5ClrchpJYZcYz35-5LGzBf1lhUD5W7BnxJtuY31MqwGSs",
        "https://play-lh.googleusercontent.com/eaiNNaBRzFaTdEY_YqWLYYi6YgwdU5_Q9WliKgGoUAADYdNnz597mHJPCW3QJ4Yr",
        "https://play-lh.googleusercontent.com/GLuHI21B7EHWzT7QnOXS2y-avYlj7PObZiIr_0FiM56E_0qg1pErPNvoc6E3dNNdOEI",
        "https://play-lh.googleusercontent.com/9vF33fSwmU4cXKavLwE26rFlU6YIAvzsIPCQbczr1oRdd9DsCPOJL8dZvULYbCm5lg",
        "https://play-lh.googleusercontent.com/tHMoU_yalPoO8Sio9wRvtVpl1YDwiL3ZgVAbgkXBN7KDbonfGJWYY7x-3DnRa-zDV3tT"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 24, 2024",
    "lastUpdatedOn": "Oct 7, 2024",
    "updated": 1728325619,
    "version": "1.0.5",
    "comments": [],
    "appId": "com.flingnative.app",
    "url": "https://play.google.com/store/apps/details?id=com.flingnative.app&hl=en&gl=us"
}