{
    "title": "Spellai - AI Art Maker",
    "description": "Ready to turn your text into stunning AI art in seconds? Discover Spellai, the user-friendly app that effortlessly transforms your words into captivating photos and drawings. Prepare to be awestruck by the exceptional image quality, rivaling custom wallpapers.\r\n\r\n\ud83e\udd17 Community Sharing\r\nNow, you can easily share your images rendered with other users in community. Post your amazing photos, get feedback, and inspire others with your creativity. Whether you're showcasing your unique style or building a design portfolio, the community is the perfect place to connect with text-to-image enthusiasts and designers alike.\r\n\r\n\ud83d\udcdd Text to AI Art\r\nWith our powerful AI editor, you can quickly and easily transform your text into unique photos, from anime-inspired drawings to lifelike photos. Without any experience and skill, you can paint your dream and proudly share these AI arts on social media.\r\n\r\n\u26a1 Diverse Styles, Lightning-Fast Photo Drawing\r\nSpellai provides a variety of style templates ranging from realistic to anime. With our lightning-fast photo generation, you can paint a stunning photo from your text in no time. Spellai is your best AI art editor and enhancer tool.\r\n\r\n\ud83e\udd29 Cartoon Yourself and Perfect Your Avatar World\r\nTired of the traditional social media profile? Want to create your own cartoon character and cartoon yourself? From anime to realistic style, Spellai is the best photo editor to bring your avatar world to lifelike painting! With the ability to edit detail, you can quickly draw any face and pose you want. Express yourself in avatar world with endless possibilities in more anime-style drawings! \r\n\r\nUnleash your creativity with our pre-made prompts and be amazed by the after-effects. With Spellai, you can transform your text into visually stunning photos that are perfect for social media or even as your device's wallpaper. The possibilities are endless, so join the AI revolution today and see what amazing painting you make with Spellai!\r\n\r\nOne click, all set in your customizable avatar world. Join the AI revolution and see what stunning drawings, including anime-style ones, you would be amazed by the after-effects from Spellai. Let's make your AI dream come true!\r\n\r\nAll personal data is protected in accordance with the Policy. We always welcome your thoughts and suggestions. You can contact us via spellai-support@polyversestudio.com.\r\n\r\nTerms of Service:\r\nhttps://aimirror.fun/spellai/terms_of_service\r\nPrivacy Policy:\r\nhttps://aimirror.fun/spellai/policy",
    "descriptionHTML": "Ready to turn your text into stunning AI art in seconds? Discover Spellai, the user-friendly app that effortlessly transforms your words into captivating photos and drawings. Prepare to be awestruck by the exceptional image quality, rivaling custom wallpapers.<br><br>\ud83e\udd17 Community Sharing<br>Now, you can easily share your images rendered with other users in community. Post your amazing photos, get feedback, and inspire others with your creativity. Whether you&#39;re showcasing your unique style or building a design portfolio, the community is the perfect place to connect with text-to-image enthusiasts and designers alike.<br><br>\ud83d\udcdd Text to AI Art<br>With our powerful AI editor, you can quickly and easily transform your text into unique photos, from anime-inspired drawings to lifelike photos. Without any experience and skill, you can paint your dream and proudly share these AI arts on social media.<br><br>\u26a1 Diverse Styles, Lightning-Fast Photo Drawing<br>Spellai provides a variety of style templates ranging from realistic to anime. With our lightning-fast photo generation, you can paint a stunning photo from your text in no time. Spellai is your best AI art editor and enhancer tool.<br><br>\ud83e\udd29 Cartoon Yourself and Perfect Your Avatar World<br>Tired of the traditional social media profile? Want to create your own cartoon character and cartoon yourself? From anime to realistic style, Spellai is the best photo editor to bring your avatar world to lifelike painting! With the ability to edit detail, you can quickly draw any face and pose you want. Express yourself in avatar world with endless possibilities in more anime-style drawings! <br><br>Unleash your creativity with our pre-made prompts and be amazed by the after-effects. With Spellai, you can transform your text into visually stunning photos that are perfect for social media or even as your device&#39;s wallpaper. The possibilities are endless, so join the AI revolution today and see what amazing painting you make with Spellai!<br><br>One click, all set in your customizable avatar world. Join the AI revolution and see what stunning drawings, including anime-style ones, you would be amazed by the after-effects from Spellai. Let&#39;s make your AI dream come true!<br><br>All personal data is protected in accordance with the Policy. We always welcome your thoughts and suggestions. You can contact us via spellai-support@polyversestudio.com.<br><br>Terms of Service:<br>https://aimirror.fun/spellai/terms_of_service<br>Privacy Policy:<br>https://aimirror.fun/spellai/policy",
    "summary": "Transform texts into stunning AI art and avatars with our AI photo generator!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 328991,
    "score": 3.5671642,
    "ratings": 4455,
    "reviews": 550,
    "histogram": [
        1129,
        130,
        397,
        661,
        2125
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $89.99 per item",
    "developer": "POLYVERSE INC.",
    "developerId": "6576091938559330796",
    "developerEmail": "brickscasualus@gmail.com",
    "developerWebsite": "https://polyversestudio.com/",
    "developerAddress": "228 PARK AVE S 30327 NEW YORK,NY,10003 USA.",
    "privacyPolicy": "https://aimirror.fun/spellai/policy",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/evKQrGaLfFuvT06J7dO5G9QnqC5TUnLR-fV6RswwooyOsjhFQ12GQCpHZUPvPFl_WQI",
    "headerImage": "https://play-lh.googleusercontent.com/3LoknsPYyvJlgCNNdv6oMETaXPIDn2CyVTSvOeurB8Mz6nr6asf86HYsFeSptkURXCY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/EYWfB0HSUEje3I6970mGQh09YLF6bWBMYnT4z60phb3kpB-oWmlCJiN0yqUTN6L7Q7E",
        "https://play-lh.googleusercontent.com/j1ZTuYk2FnynrR_-Hzx9hCozYE_9PjZNAZ3VqU1CwKQ0rAPDk7JX6hyz_WrvQE7ziiJF",
        "https://play-lh.googleusercontent.com/YpTS-T3nKyusD7w7iRDc6ixe0s4Ra9vLaBBZRVZy4u_IVyuE0U7vEL4blXo4zXkWCb8",
        "https://play-lh.googleusercontent.com/mKhADUgrNyK-eEPagtobRksRDshaxDR_v3gL1UCPm1sXvDzOo1G4LyuAHHR2ZOVs63Y",
        "https://play-lh.googleusercontent.com/9y9R34KpbsXg7xstG-u2RtGZTh1hEAn3MH3mTtvEswFmmLuV_4ePxjkx2WYCYeuK4F4",
        "https://play-lh.googleusercontent.com/Cp0a3Ol8bGySxDuRM-aI62NaK03nBctzVIobdCsnAYujQ8F-EpjAuiHhPy3Q2ftlHoPC",
        "https://play-lh.googleusercontent.com/KIDs6tUoQfkE73WVYHfJUTUKtKlhx01v2HuuEoRK3hX0uM4LB5rUhoY_-Kf6426M_A",
        "https://play-lh.googleusercontent.com/1FZN5jYuHicRfgjdJHNSufB02K8kfI9FlBBwcseJSYoBAhYGlK0oF0n-z-yKRkjFpaaa",
        "https://play-lh.googleusercontent.com/i8BBnr2AgeooK8naNG46pYMQVYj2ELN3-__dKa7rzwI6S6CwlcKLAka9ixxb7N_Lgv0",
        "https://play-lh.googleusercontent.com/Ys5hhq5MDbZFzkUwYU7P19v4xaAeP3zIfiQK8Bk59qg9g6RYN5LMRTzz4eRdzdsVh03E",
        "https://play-lh.googleusercontent.com/Rm4jPGa-7R5vCiAIi_kYNpLe63AZnGu3KfPrSqBysCSKS69O9hG0oVYPD4DYyMyIuU8",
        "https://play-lh.googleusercontent.com/PipKevAXsU7jorJn0yi9twjV7-5axaiM0NoO8fom4cWXCkupr4oyaMIFEbbcfzECrp4",
        "https://play-lh.googleusercontent.com/bpeEgBGKRpWnjhXt1nqL8QpQji1fe7u5y1iiSZbTZ4Vhiyb7b9yfGtciO1Va9THYF2s",
        "https://play-lh.googleusercontent.com/MsHRazHOowy51_xyBKWONUp-YHE_Amc-_xGEF0W48PBM441xQAS0AS3DLRkaPxsj2g",
        "https://play-lh.googleusercontent.com/b59ghBRcmFS5kOeLrFwEO4P4L2sBJ-zZ6-jBDybsrwaoKfG-n_875_p89lDOE-jPXLU",
        "https://play-lh.googleusercontent.com/FTHBW2GGu_TysmNmS-I-KRqFS2mttH_JRPwwa2siTFuqE_aYNMAftsoWMIE9A8ldYw",
        "https://play-lh.googleusercontent.com/8mC0G95h3pK5fJRhsGliaZbxyPIs-eaV-cbFczA3OYk12F3AH1vjSgXQ1PrHceP2hXM",
        "https://play-lh.googleusercontent.com/ujZptH56RQ7SiEWruTnpi0BfqoN5vWRA7jNh2GxtJKXL3MN5mzAh6_bRNUY2xm61kfc",
        "https://play-lh.googleusercontent.com/8oOOml-fKuQjLxY3oJjGp8qJtvV9E8q__4Lo2HbPpTtZ5S5iVuXsSznM46XvP8TQn932",
        "https://play-lh.googleusercontent.com/wOxA12Z-yNIdwx6N96Qc0GaMTWIcKn5LYXB1x3GqTqCF27UDqZ0M0e1fMt4yY44xfyw",
        "https://play-lh.googleusercontent.com/0yCPaCTxxEq-OxBAwZUiUrFTc9hSgHcZLdJ68cpsrhQ6p1eRNDGMM8-2HfwMQXargAg",
        "https://play-lh.googleusercontent.com/KBihzvJ8Ga5tBCTTWQNzOuvghAKvTRXz5ZWV7pigwrEr5In4hOhE46zxBnZU_VfOXw",
        "https://play-lh.googleusercontent.com/YtjboGbWwPgqEA1hxzXh5MkRghmy07gzGxfbwyGVn9uBUO-i_XCXJT-7kIYxTetGYRZT",
        "https://play-lh.googleusercontent.com/3Ro9gV0iMy_PLkS9bKDoCkFUdpn_rjqyExVmPJzbfIrawi8WSHxKYxwGohPmzytZBA",
        "https://play-lh.googleusercontent.com/P0wGqCyctaQcX5LL7tISUUQcFhqUeAfeF9VygAb3BHH7G9lSbPs0oqqGBPHMZPNN7hI",
        "https://play-lh.googleusercontent.com/dFmHjmP5YwmAnLGS07tSxvvDc6B4x8otxBUs1mAJV8Xi3qvXLyQO9Kuuqd9_CVBFyl8",
        "https://play-lh.googleusercontent.com/4r7vf-jw3bsAkAjeIogIAyVh421WcheGcE1gSKcbQWzAuNA-VcpStBPHbVERJWEFdxo",
        "https://play-lh.googleusercontent.com/qene_49qPcMSGP65qRUzpnrDLEspWVB4VCTUFpB0u_GM_zGLnJ6QhPdA-SG05Ys76Qw",
        "https://play-lh.googleusercontent.com/U5xTnvnRPW-LPY_abxt1UllflyiP1GYmtMGA52-2PDHEh5LunCHLMlceUBxoXiUsdnY",
        "https://play-lh.googleusercontent.com/2j73v9-mJz5EIJqyMbNe3v6Fn-eGalZkmKGyXQuEu1Vf2gydT7DWdCWAvst9qzjP4ro",
        "https://play-lh.googleusercontent.com/5mMMb8sTeHR2tRTTELOVeWEbuAfXsBXs_XpoZt-wazYUMVbkbZqzVDCBQXf2Bj-WdQ",
        "https://play-lh.googleusercontent.com/F5DCX1Gs7HYASyqNAILGDNHlS6P8-_UKlyGjhUBvqrb78YImF37wGq6d-UVOWBC4QxA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Sexual Themes",
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 8, 2024",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728975598,
    "version": "1.7.5",
    "comments": [],
    "appId": "com.ai.polyverse.spell.pro",
    "url": "https://play.google.com/store/apps/details?id=com.ai.polyverse.spell.pro&hl=en&gl=us"
}