{
    "title": "E! News",
    "description": "Pop culture. Personalized. The Emmy\u00ae-nominated E! News app has everything you need to know, right when you need to know it. \r\n \r\nHere's what you get with the E! News app:\r\n \r\n- Find a specific photo, or swipe thru them all! The choice is yours with our interactive gallery experience. \r\n- Watch the latest E! News videos and behind-the-scenes extras from your favorite E! shows including \"Keeping Up With the Kardashians,\" \u201cVery Cavallari\u201d and \u201cTotal Divas\u201d.\r\n- Be the first to know breaking news with our mobile alerts!\r\n- Access faster-loading videos, articles and full-screen photos.\r\n- Keep up with the latest style trends.  \r\n- Share everything from E! News with your friends on social media, directly from the app.\r\n \r\nConnect with us!\r\n- Website: Eonline.com\r\n- Newsletter: Eonline.com/newsletter\r\n- Twitter: Twitter.com/enews\r\n- Instagram: Instagram.com/enews\r\n- Snapchat: snapchat.com/add/e_news\r\n- Facebook: Facebook.com/enews\r\n \r\nWe're always happy to get your feedback to help us improve the app. Email us at eonline.feedback@nbcuni.com.\r\n \r\nFor full TV episodes, download the E! app, available in Google Play.\r\n               \r\nThis app features Nielsen proprietary measurement software which will allow you to contribute to market research, like Nielsen\u2019s TV Ratings.\r\n               \r\nTo learn more about our digital measurement products and your choices in regard to them, please visit http://www.nielsen.com/digitalprivacy for more information.\r\n\r\nYour Privacy Choices: https://www.nbcuniversal.com/privacy/notrtoo\r\n \r\nCA Notice: https://www.nbcuniversal.com/privacy/california-consumer-privacy-act?intake=E!_Entertainment\r\n\r\nE! Entertainment Television, Inc.",
    "descriptionHTML": "Pop culture. Personalized. The Emmy\u00ae-nominated E! News app has everything you need to know, right when you need to know it. <br> <br>Here&#39;s what you get with the E! News app:<br> <br>- Find a specific photo, or swipe thru them all! The choice is yours with our interactive gallery experience. <br>- Watch the latest E! News videos and behind-the-scenes extras from your favorite E! shows including &quot;Keeping Up With the Kardashians,&quot; \u201cVery Cavallari\u201d and \u201cTotal Divas\u201d.<br>- Be the first to know breaking news with our mobile alerts!<br>- Access faster-loading videos, articles and full-screen photos.<br>- Keep up with the latest style trends.  <br>- Share everything from E! News with your friends on social media, directly from the app.<br> <br>Connect with us!<br>- Website: Eonline.com<br>- Newsletter: Eonline.com/newsletter<br>- Twitter: Twitter.com/enews<br>- Instagram: Instagram.com/enews<br>- Snapchat: snapchat.com/add/e_news<br>- Facebook: Facebook.com/enews<br> <br>We&#39;re always happy to get your feedback to help us improve the app. Email us at eonline.feedback@nbcuni.com.<br> <br>For full TV episodes, download the E! app, available in Google Play.<br>               <br>This app features Nielsen proprietary measurement software which will allow you to contribute to market research, like Nielsen\u2019s TV Ratings.<br>               <br>To learn more about our digital measurement products and your choices in regard to them, please visit http://www.nielsen.com/digitalprivacy for more information.<br><br>Your Privacy Choices: https://www.nbcuniversal.com/privacy/notrtoo<br> <br>CA Notice: https://www.nbcuniversal.com/privacy/california-consumer-privacy-act?intake=E!_Entertainment<br><br>E! Entertainment Television, Inc.",
    "summary": "The E! News app has everything you need to know right when you need to know it.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3491334,
    "score": 4.37785,
    "ratings": 17729,
    "reviews": 4285,
    "histogram": [
        1501,
        346,
        1038,
        1904,
        12935
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Comcast Entertainment Group",
    "developerId": "Comcast+Entertainment+Group",
    "developerEmail": "eonline.feedback@nbcuni.com",
    "developerWebsite": "http://www.eonline.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.nbcuniversal.com/privacy/mobile-apps?brandA=E!_Entertainment&intake=E!_Entertainment",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/dOgIXjIU9tUlr7-85cHsROKRt48lUgAKdtO2p6JdYK8oSVi8uNsVKPYR6Cgxf6d-2KU",
    "headerImage": "https://play-lh.googleusercontent.com/OhwwC-U-FBTPiEbLGlC-2dPzK1f_niyU77r3a38NAYCJV8vajaw5dNEsYYM-CrcQphU",
    "screenshots": [
        "https://play-lh.googleusercontent.com/XXukchdDgPsLZ5oji4MJ1veUcxEHmrhcJjZ-KO_4G623fGTXLOmXJXXAg5q87W5zSBA",
        "https://play-lh.googleusercontent.com/Vi761GlasecNNYuWcMNEk2PoMaL5EaKvRRTiw0fAk0SjDbHcyhAlgDQviKAMQ9cJhrY",
        "https://play-lh.googleusercontent.com/rT0i0E-ds1A2J7g7GJd48PjV4JN767kkIooP9HYOk_Y2m0l28Jtn_TdH8C1cPcywfPGQ",
        "https://play-lh.googleusercontent.com/WfAo4G5bswm6kjhUVLr4Ykm7oAUuaDWDoCX6fbw_vvEEDmku0Htv0vYeZmvoF2W5Xg",
        "https://play-lh.googleusercontent.com/VtFaGU1eO1NpWyUALF1s3w3rZrfzcOaKcqJZZ6iuMeSlKMXYgNDBQ-o_6QrHP-TkBQ",
        "https://play-lh.googleusercontent.com/nJU_sosOqhE_GTGN2X_mDGyE600YgUBXDuVB8we09Ghnsq685dTFupZZW4NTS-eB51U-",
        "https://play-lh.googleusercontent.com/TRlimK_eOuNf4uN_TbBT0IzVRocaP5By1s8KNQMBhDFWIRHzY71PKY8zSKsj0ztwlA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Suggestive Themes, Partial Nudity, Language",
    "adSupported": true,
    "containsAds": true,
    "released": null,
    "lastUpdatedOn": "Sep 19, 2024",
    "updated": 1726765719,
    "version": "7.1.4",
    "comments": [],
    "appId": "com.rhythmnewmedia.android.e",
    "url": "https://play.google.com/store/apps/details?id=com.rhythmnewmedia.android.e&hl=en&gl=us"
}