{
    "title": "Truth Social",
    "description": "The #1 free-speech social media platform is now available as a native Android app!\r\n\r\nIn the year 2021, the media pendulum has swung dangerously far to the left. Silicon Valley, the mainstream media, and Big Tech have begun to forcibly silence voices that do not align with their woke ideology. Big Tech platforms demonetize, throttle, and cancel those who stray from the mainstream narrative. They are not just censoring content \u2013 they are determining what can and cannot be said. By controlling how information is shared, they control the narrative. They control the future. They control you.\r\n\r\nTo counter this dangerous exercise of Big Tech monopoly power, Truth Social intends to even the playing field by providing people with an open media platform where they can share and create content without fear of reputational ruin.\r\n\r\nNo political discrimination.\r\nCanceling cancel culture.\r\nStanding up to Big Tech.\r\n\r\nJoin us.\r\n\r\nKey Features\r\n\r\nProfile - Express your unique personality by setting up a profile, avatar, and background. Begin to track your personal connections through follower and following counts as well as history for your posts and likes.\r\n\r\nTruth Feed - Get the scoop on the latest thoughts and activities from the people, organizations, and news outlets that interest you. The Truth Feed contains posts from all those you follow brought to life with the help of thumbnail photos, links, and more.\r\n\r\nCompose Truths - Let your voice be heard. Sign up, join the conversation, and share your unique opinion by posting a Truth, Re-Truth, photo, news story, poll or video link to communicate with your friends, customers, and the world. Stay informed about breaking news while staying directly connected with the people who influence you \u2013 don't be shocked if they take your Truth viral!\r\n\r\nSearch - Truth Social really starts to become interesting as you connect with others. Search for a voice that you find interesting and easily follow them right from the search list or view their profile first before deciding.\r\n\r\nDirect Messages - Take your conversations private by direct messaging your followers for 1-on-1 chats! Set messages to auto-delete after 7, 14, 30, or 90 days on a per-chat basis. Silence push notifications for all chats or on a per-chat basis. You can also turn off the ability for those you follow to DM you (in your Preferences) as well as block users, copy, delete and report messages.\r\n\r\nPolls \u2013 Create polls to get feedback on a question you may have.\r\n\r\nNotifications - Stay engaged as you build a following. See who's following you and who's interacting with your Truths.",
    "descriptionHTML": "The #1 free-speech social media platform is now available as a native Android app!<br><br>In the year 2021, the media pendulum has swung dangerously far to the left. Silicon Valley, the mainstream media, and Big Tech have begun to forcibly silence voices that do not align with their woke ideology. Big Tech platforms demonetize, throttle, and cancel those who stray from the mainstream narrative. They are not just censoring content \u2013 they are determining what can and cannot be said. By controlling how information is shared, they control the narrative. They control the future. They control you.<br><br>To counter this dangerous exercise of Big Tech monopoly power, Truth Social intends to even the playing field by providing people with an open media platform where they can share and create content without fear of reputational ruin.<br><br>No political discrimination.<br>Canceling cancel culture.<br>Standing up to Big Tech.<br><br>Join us.<br><br>Key Features<br><br>Profile - Express your unique personality by setting up a profile, avatar, and background. Begin to track your personal connections through follower and following counts as well as history for your posts and likes.<br><br>Truth Feed - Get the scoop on the latest thoughts and activities from the people, organizations, and news outlets that interest you. The Truth Feed contains posts from all those you follow brought to life with the help of thumbnail photos, links, and more.<br><br>Compose Truths - Let your voice be heard. Sign up, join the conversation, and share your unique opinion by posting a Truth, Re-Truth, photo, news story, poll or video link to communicate with your friends, customers, and the world. Stay informed about breaking news while staying directly connected with the people who influence you \u2013 don&#39;t be shocked if they take your Truth viral!<br><br>Search - Truth Social really starts to become interesting as you connect with others. Search for a voice that you find interesting and easily follow them right from the search list or view their profile first before deciding.<br><br>Direct Messages - Take your conversations private by direct messaging your followers for 1-on-1 chats! Set messages to auto-delete after 7, 14, 30, or 90 days on a per-chat basis. Silence push notifications for all chats or on a per-chat basis. You can also turn off the ability for those you follow to DM you (in your Preferences) as well as block users, copy, delete and report messages.<br><br>Polls \u2013 Create polls to get feedback on a question you may have.<br><br>Notifications - Stay engaged as you build a following. See who&#39;s following you and who&#39;s interacting with your Truths.",
    "summary": "Follow the Truth! Join America's leading free-speech social platform.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3303717,
    "score": 3.781032,
    "ratings": 18465,
    "reviews": 7931,
    "histogram": [
        4712,
        475,
        617,
        991,
        11665
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "T Media Tech LLC",
    "developerId": "T+Media+Tech+LLC",
    "developerEmail": "support@truthsocial.com",
    "developerWebsite": "https://truthsocial.com",
    "developerAddress": null,
    "privacyPolicy": "https://help.truthsocial.com/legal/privacy-policy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/viE7sFTiSuKKSnbzWHPcMpIKlKbZgWMw11bTeM2pUCV4o4lbFrzXJF8WHt88kni1q1YX",
    "headerImage": "https://play-lh.googleusercontent.com/8dIjH7hqDAitjumCLds_Zo9SJlH8G9K1bfELLA-UNq6d_RxzH8urp-FErfmpBwSxRM4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/BofhXneR-AQqAocvXiLnO9Mr6MZUnAHNUko2A4mx09UtAFeYsLDILm8IJPLxN2Z1EDA",
        "https://play-lh.googleusercontent.com/6RtojegGM6JHAgvEMbCoMLuKu2vcbQOcMP6m8LHZlFN4YRPmrPYyYGt7nvRlXDoV-A",
        "https://play-lh.googleusercontent.com/_PSZo0beSAgTc9CM944cblfoU1CnI-L6Y3dit6_JvzvsmJvUUO-EPgNU3R_fF9jpx6nY",
        "https://play-lh.googleusercontent.com/PVBJnDcQV4wtT02bn4_wFqFwVvtNMyQGtSlG_FGU2RRD1vyn6OC2jdNwaWCRWv-a3SA",
        "https://play-lh.googleusercontent.com/TM3s0ppvqnyFycZ2bN56ODEpwcUfvaP4a5HdLOGhhmLiO0zy_eHDengzUHjkDEtAbQw",
        "https://play-lh.googleusercontent.com/Rf0hsTGnRKGiJSE9noTiBYtpqT4Hpwp3cpFxTqX75jsyzhPi3feWw36Q8xGbSabLEyg",
        "https://play-lh.googleusercontent.com/wyI7xreFOytJ7JLIH5jnWFEsAX95WcKw6klMPv1ZVmAtsapndjCOqM5YuFUOXyxRqFOa",
        "https://play-lh.googleusercontent.com/fk6VgihNG0MxECoenOsKTn1XMmFrrb5Dz0u8dA6wQZjX_jV0tpUGbHidWB_M4TLmxxI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Oct 12, 2022",
    "lastUpdatedOn": "Sep 24, 2024",
    "updated": 1727187939,
    "version": "1.12.5",
    "comments": [],
    "appId": "com.truthsocial.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.truthsocial.android.app&hl=en&gl=us"
}