{
    "title": "My 2nd Line Text Call Number",
    "description": "\u2605\u2605 A Second Line Phone Number \u2605\u2605 \r\n\r\nYou can purchase a second phone number with the MySecondLine app on your mobile phone. \r\n\r\nGet started for just $8.99 / month with a USA/Canada local number. The pricing is the most affordable and the best rate in the market for such a quality app. \r\n\r\nHere are the benefits:\r\n\r\n\u2605\u2605 Get a USA/Canada local number: starts at $8.99 only \u2605\u2605\r\n\r\nYou can try the app for $8.99 only to get started! Enjoy an ad-free experience after purchase. The cost is fully transparent. It is super easy to get started. \r\n\r\nYou will unblock many advanced features below in the premium version and get a dedicated phone number!\r\n\r\n\u2605\u2605 A separate second phone number \u2605\u2605\r\n\r\nYou can purchase a dedicated phone number from MySecondLine. You can choose a local area code while keeping yourself anonymous and private. You can also find the number based on letters, e.g. 213-LAX-JOHN, or 718-NYC-8888. The phone number is memorable and unique.\r\n\r\nBesides that, we also provide:\r\n- Toll-free numbers like 800, 888, and 855 in the US/Canada.\r\n- International phone numbers from 60+ countries (GB, Israel, Hong Kong, Germany, etc.)\r\n- You can import and transfer your current USA number to us\r\n\r\n\u2605\u2605 Easy texting and quality phone calls (to the US/Canada) \u2605\u2605 \r\n\r\nIt offers easy texting and quality phone calls in the premium version. \r\n\r\nYou can text your contacts. And you can receive messages from all over the world. It's also easy to make and receive calls just like your mobile phone. Our app works with your Wi-Fi or mobile data networks for high-quality VoIP calls.\r\n\r\nNote: For the US/Canada, you can upgrade with a small fee to enable international calls and messages in the settings.\r\n\r\n\u2605\u2605 Private personal communications \u2605\u2605\r\n\r\nGet a second phone number for many personal usages such as:\r\n- Stay safe and anonymous when you give out your number\r\n- A fake number to avoid unwanted spam messages and calls\r\n- A temporary number for dating, shopping, etc\r\n- Website registration to receive SMS and still keep privacy\r\n\r\n\u2605\u2605 Great features and the best texting & calling app \u2605\u2605\r\n\r\n- Customizable text tone, ringtone & vibration\r\n- Voicemail transcription: transcript of your voicemail\r\n- Caller ID: show the incoming call's phone number and contact name\r\n- Greeting: record your sounds to greet customers\r\n- Auto-reply: automatically message reply when you are busy\r\n- Great support service: contact us if you have any questions\r\n- Upgrade to send picture messages\r\n\r\n\u2605\u2605 Premium and advanced features with extra charges \u2605\u2605\r\n\r\n- Change your second phone number with a one-time fee\r\n- Upgrade to receive verification codes from major websites\r\n- Upgrade to text or call 150+ international countries\r\n- Upgrade to choose toll-free phone numbers\r\n- Team number: manage the number with your team together\r\n- Call schedule: set schedule for different time slots for different members\r\n- Call recording: record the phone call conversation for training\r\n- Call forwarding: forward incoming calls to external numbers\r\n- Virtual receptionist: automated answers for calls and press x to redirect\r\n- Get phone numbers from 60+ countries\r\n\r\n\u2605\u2605 Download the app and get started \u2605\u2605 \r\n\r\nPrivacy Policy\r\nhttps://mysecondline.com/privacy-policy/\r\n\r\nTerms of Use\r\nhttps://mysecondline.com/terms-of-use/",
    "descriptionHTML": "\u2605\u2605 A Second Line Phone Number \u2605\u2605 <br><br>You can purchase a second phone number with the MySecondLine app on your mobile phone. <br><br>Get started for just $8.99 / month with a USA/Canada local number. The pricing is the most affordable and the best rate in the market for such a quality app. <br><br>Here are the benefits:<br><br>\u2605\u2605 Get a USA/Canada local number: starts at $8.99 only \u2605\u2605<br><br>You can try the app for $8.99 only to get started! Enjoy an ad-free experience after purchase. The cost is fully transparent. It is super easy to get started. <br><br>You will unblock many advanced features below in the premium version and get a dedicated phone number!<br><br>\u2605\u2605 A separate second phone number \u2605\u2605<br><br>You can purchase a dedicated phone number from MySecondLine. You can choose a local area code while keeping yourself anonymous and private. You can also find the number based on letters, e.g. 213-LAX-JOHN, or 718-NYC-8888. The phone number is memorable and unique.<br><br>Besides that, we also provide:<br>- Toll-free numbers like 800, 888, and 855 in the US/Canada.<br>- International phone numbers from 60+ countries (GB, Israel, Hong Kong, Germany, etc.)<br>- You can import and transfer your current USA number to us<br><br>\u2605\u2605 Easy texting and quality phone calls (to the US/Canada) \u2605\u2605 <br><br>It offers easy texting and quality phone calls in the premium version. <br><br>You can text your contacts. And you can receive messages from all over the world. It&#39;s also easy to make and receive calls just like your mobile phone. Our app works with your Wi-Fi or mobile data networks for high-quality VoIP calls.<br><br>Note: For the US/Canada, you can upgrade with a small fee to enable international calls and messages in the settings.<br><br>\u2605\u2605 Private personal communications \u2605\u2605<br><br>Get a second phone number for many personal usages such as:<br>- Stay safe and anonymous when you give out your number<br>- A fake number to avoid unwanted spam messages and calls<br>- A temporary number for dating, shopping, etc<br>- Website registration to receive SMS and still keep privacy<br><br>\u2605\u2605 Great features and the best texting &amp; calling app \u2605\u2605<br><br>- Customizable text tone, ringtone &amp; vibration<br>- Voicemail transcription: transcript of your voicemail<br>- Caller ID: show the incoming call&#39;s phone number and contact name<br>- Greeting: record your sounds to greet customers<br>- Auto-reply: automatically message reply when you are busy<br>- Great support service: contact us if you have any questions<br>- Upgrade to send picture messages<br><br>\u2605\u2605 Premium and advanced features with extra charges \u2605\u2605<br><br>- Change your second phone number with a one-time fee<br>- Upgrade to receive verification codes from major websites<br>- Upgrade to text or call 150+ international countries<br>- Upgrade to choose toll-free phone numbers<br>- Team number: manage the number with your team together<br>- Call schedule: set schedule for different time slots for different members<br>- Call recording: record the phone call conversation for training<br>- Call forwarding: forward incoming calls to external numbers<br>- Virtual receptionist: automated answers for calls and press x to redirect<br>- Get phone numbers from 60+ countries<br><br>\u2605\u2605 Download the app and get started \u2605\u2605 <br><br>Privacy Policy<br>https://mysecondline.com/privacy-policy/<br><br>Terms of Use<br>https://mysecondline.com/terms-of-use/",
    "summary": "Second phone number as 2nd line: private texts and calls",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1207426,
    "score": 4.5384617,
    "ratings": 12168,
    "reviews": 515,
    "histogram": [
        796,
        135,
        603,
        796,
        9825
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $399.99 per item",
    "developer": "AutoBizLine, Inc.",
    "developerId": "AutoBizLine,+Inc.",
    "developerEmail": "support@autobizline.com",
    "developerWebsite": "https://autobizline.com/",
    "developerAddress": "325 W Washington St\nSte 2820\nSan Diego, CA 92103",
    "privacyPolicy": "https://autobizline.com/privacy-policy/",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/jLeXloSQcufxb0jGxZPap1qNVoA_cXviinm23FzmAak8kJsw9EYp7qzd3H-5Xy7Z30Q",
    "headerImage": "https://play-lh.googleusercontent.com/cPOZcU063cORsWqCnoaOQUr9Mlpo-Lb7mbTz7Z58pmW8Jvtofz_ICjrri8ZgFL6degQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/uPFKZAvsUDTauxXLoCl-q6Mx8svbkaX1Zf0z0V-aPdGDE-lQuWhXwacGjo2LWDvGV_WX",
        "https://play-lh.googleusercontent.com/rb2r97f1mKXkoqF7qIb-9042k8PF4_wB79wWXiBrMX_DSNEfaU-iD0pVzBTSx5yHcSNd",
        "https://play-lh.googleusercontent.com/2Vbetk1YxkNRN4qpnn7Ylk4lGUsfqYX1QjyHo3iZLMWVc3RnbWw-wTuyrj2GlbgatA",
        "https://play-lh.googleusercontent.com/iZFzY5RSKSPalqfBFFnjfjtGv5Jxc4_kGMp8jlm5UlUk4SH8qbLmFW0dtiX8YeOpSMSj",
        "https://play-lh.googleusercontent.com/wavYjB7xSvmikztderkkv5M94t5porQddqkgnF3BpqYhfLPx70KN3wk7GcoHVZR-SSY",
        "https://play-lh.googleusercontent.com/7Sjz9-fWvDIOm-QTWKDp1TaCFWn8s6N_F4HCGWJsRxGAVKvQVb-ZybhGQAk62Im1nG0",
        "https://play-lh.googleusercontent.com/v-nAGZR4VABnLs_x83jC8EgtKUgshOBjpeR0CrLARe555CHu89XKOvIhjonzO38iWR8",
        "https://play-lh.googleusercontent.com/CgoU6EQjZnIKatu01f228avk9Ka3iLded10uGRQKC6--FriDCgGi_DubDgRub4Jq3g",
        "https://play-lh.googleusercontent.com/uh1os0sLUyw41uVgruB_S2TQZz7Pw_1hctaN2hZsdHGRgYRxjMbK7T0zQS3c8rg-MbSE",
        "https://play-lh.googleusercontent.com/Vr884QrIkMjN_nRBcF8hz1JTitCssGabpyrZ_GyXF0SvCCCI_Ck8ZneDepS1dn-LgSo",
        "https://play-lh.googleusercontent.com/BEkmmAeGDN9V9R1auwezmlYkBGwG6GUr_ecYprwCPAHqmDn9QZ-YYNnSsSaYacBe9w",
        "https://play-lh.googleusercontent.com/d0E1kiOq6DVmuNqSfQakMFUEXH6lfDEYpbd_tSFo2U3puhM8AYn4_37W1sTo9cJmSFU",
        "https://play-lh.googleusercontent.com/otRkY1WolLK1PlFJXFAXc7NvMFM_EPUostmZx7D0FtgNVt274V-T0_2yVRBu5MYRIg",
        "https://play-lh.googleusercontent.com/0GDaLmdt1gz3Czd7hqK4C5OnvV_dK5tM5eSrHsMbdf90-WxcfmmsxFQMrQGvkKEa8w",
        "https://play-lh.googleusercontent.com/5M3vnnnHGF1TGpJysVOX3XUNHQDFE7RLB84tMGpGy6HqWsHLLXsik0jKQ82A1I8EeCU",
        "https://play-lh.googleusercontent.com/5tPRdEE9-HLZ--G3UOPLzyVihPvjtcHB6TWn5QPtQwQHUD_xCYlVX-9pihEhgRgCoQw",
        "https://play-lh.googleusercontent.com/OL_Rg2PtbfWipsYtt-brjE1I_qmaYak5o_F2Lq_txPumqctQuRn7S2ru624b8IDfrII",
        "https://play-lh.googleusercontent.com/sONw8hooZcPgzrFSP3ujOohzTlpVys5cUVn_heR80XYyMd1xKCuhSotOMzSlfg8ZbVs",
        "https://play-lh.googleusercontent.com/qSWsHfFoVJnQCsKRWguVGrBS4DAPMYzk6BHWQdaTJDNClt0utcZi6azH1IJIoOagOKk",
        "https://play-lh.googleusercontent.com/8XPxcmLKTcSV_OFwFu3YYXHP8IDQeWP810Qk5-V3z9AQ9bjaXvlw0IH00BiFw1DcnVY",
        "https://play-lh.googleusercontent.com/O3VqK-I8SmqqacGWnDNYAOZdMQc4JR886BX_Zlp8NJci2mcw8wZbYvBulDd-W22JRz52"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 10, 2020",
    "lastUpdatedOn": "Oct 6, 2024",
    "updated": 1728255851,
    "version": "1.2.78",
    "comments": [],
    "appId": "com.mysecondline.app",
    "url": "https://play.google.com/store/apps/details?id=com.mysecondline.app&hl=en&gl=us"
}