{
    "title": "SuperCook - Recipe Generator",
    "description": "How many times have you found yourself looking for that perfect recipe \u2013 only to find that you\u2019re missing one or more ingredients?\r\n\r\nHow many times have you opened the fridge and thought to yourself -- what can I make ?\r\n\r\nHow many times have you thrown away an ingredient, because you couldn't figure out how to use it before it expired ?\r\n\r\nSuperCook to the rescue!\r\n\r\nUnlike other recipe apps,  SuperCook only shows you recipes that require the ingredients you already have.  \r\n\r\nAll the recipes you see on SuperCook  are recipes you can make right now.  No more inconvenient grocery runs for a missing ingredient, at a time when you should be home, with your family and friends\r\n\r\nWhy purchase new ingredients when you can focus on what you already have?\r\n\r\nHere\u2019s how it works:\r\n\u2022 For Supercook to do its magic, it needs to know all the ingredients you have at home.\r\n\u2022 Visit the pantry page in the SuperCook app and choose from a list of 2000+ ingredients broken down into categories like fruits, vegetables, meats, and many more. \r\n\u2022 Start adding ALL the ingredients you have at home to your SuperCook pantry \u2013 including oils, spices, and yes - even that old bottle of Worcestershire sauce in the back of the fridge!\r\n\u2022 Sit back and watch SuperCook work its magic by finding recipes that match your ingredients.\r\n\r\nSuperCook\u2019s Unique App Features:\r\n \r\n--Customized Recipe Ideas--\r\nWe\u2019ve consolidated over 11 million recipes from 18,000 recipe websites, in 20 languages to create the largest recipe collection ever.   This knowledge was fed into an AI system that learnt the intricacies of all ingredients and how they can be mixed together.\r\n\r\nAll you have to do is build your pantry on the app \u2013 and you\u2019re ready to make delicious meals without ever leaving your house!\r\n\r\nSuperCook will find you any recipe you need, whether it\u2019s for breakfast, lunch, dinner, or even a midnight snack.  \r\n\r\n--Easily Add Your Ingredients--\r\nSave time and money with an intelligent pantry. SuperCook\u2019s voice dictation mode allows you to quickly add ingredients to your in-app pantry by simply saying them out loud.\r\n\r\nJust open your fridge, click the microphone button, and start listing everything inside. The app will automatically add the ingredients to your pantry for a quick and easy way to find recipes!\r\n \r\n--Automatic Recipe Recommendations--\r\nThe app will automatically find you recipes to make with what\u2019s in your fridge \u2013 so all those lost ingredients in the back of your cupboard now have a place on your table.  It\u2019s that simple!\r\n\r\nWhen you run out of an ingredient, simply open the SuperCook app and remove it from your pantry -  and all the recipe ideas will adjust accordingly.\r\n \r\n--Get Creative in the Kitchen--\r\nSuperCook inspires new ideas and activities in the kitchen for new cooks, busy parents, foodies, and pro chefs alike.\r\n\r\nWith over 11 million recipes available in 20 different languages, SuperCook promises that you\u2019ll never cook the same thing twice (unless you want to, of course!).\r\n\r\n--What's on the menu ?--\r\nThe menu page is where you'll find all your recipe ideas.  Why is it called menu?  Because just like the menu in a restaurant, everything on the menu page is available to you now.  SuperCook instantly analyzes 11 million recipes and finds the ones that match your unique ingredients.\r\n\r\nMost likely your menu page will contain thousands of recipes, but don't worry, we've broken them down into helpful categories like soups and stews, appetizers and snacks, salads, entrees, desserts and more.\r\n\r\n--Reduce food waste--\r\nMost people don't realize how much food they throw away every day \u2014 from uneaten leftovers to spoiled produce. SuperCook is one of the best ways to reduce food waste in the home.   It finds recipes that use as many of your ingredients as possible, so nothing goes to waste.    SuperCook makes food waste prevention fun and easy, just open the menu page on the app and choose a recipe.   We help you use what you have, so nothing goes to waste!",
    "descriptionHTML": "How many times have you found yourself looking for that perfect recipe \u2013 only to find that you\u2019re missing one or more ingredients?<br><br>How many times have you opened the fridge and thought to yourself -- what can I make ?<br><br>How many times have you thrown away an ingredient, because you couldn&#39;t figure out how to use it before it expired ?<br><br>SuperCook to the rescue!<br><br>Unlike other recipe apps,  SuperCook only shows you recipes that require the ingredients you already have.  <br><br>All the recipes you see on SuperCook  are recipes you can make right now.  No more inconvenient grocery runs for a missing ingredient, at a time when you should be home, with your family and friends<br><br>Why purchase new ingredients when you can focus on what you already have?<br><br>Here\u2019s how it works:<br>\u2022 For Supercook to do its magic, it needs to know all the ingredients you have at home.<br>\u2022 Visit the pantry page in the SuperCook app and choose from a list of 2000+ ingredients broken down into categories like fruits, vegetables, meats, and many more. <br>\u2022 Start adding ALL the ingredients you have at home to your SuperCook pantry \u2013 including oils, spices, and yes - even that old bottle of Worcestershire sauce in the back of the fridge!<br>\u2022 Sit back and watch SuperCook work its magic by finding recipes that match your ingredients.<br><br>SuperCook\u2019s Unique App Features:<br> <br>--Customized Recipe Ideas--<br>We\u2019ve consolidated over 11 million recipes from 18,000 recipe websites, in 20 languages to create the largest recipe collection ever.   This knowledge was fed into an AI system that learnt the intricacies of all ingredients and how they can be mixed together.<br><br>All you have to do is build your pantry on the app \u2013 and you\u2019re ready to make delicious meals without ever leaving your house!<br><br>SuperCook will find you any recipe you need, whether it\u2019s for breakfast, lunch, dinner, or even a midnight snack.  <br><br>--Easily Add Your Ingredients--<br>Save time and money with an intelligent pantry. SuperCook\u2019s voice dictation mode allows you to quickly add ingredients to your in-app pantry by simply saying them out loud.<br><br>Just open your fridge, click the microphone button, and start listing everything inside. The app will automatically add the ingredients to your pantry for a quick and easy way to find recipes!<br> <br>--Automatic Recipe Recommendations--<br>The app will automatically find you recipes to make with what\u2019s in your fridge \u2013 so all those lost ingredients in the back of your cupboard now have a place on your table.  It\u2019s that simple!<br><br>When you run out of an ingredient, simply open the SuperCook app and remove it from your pantry -  and all the recipe ideas will adjust accordingly.<br> <br>--Get Creative in the Kitchen--<br>SuperCook inspires new ideas and activities in the kitchen for new cooks, busy parents, foodies, and pro chefs alike.<br><br>With over 11 million recipes available in 20 different languages, SuperCook promises that you\u2019ll never cook the same thing twice (unless you want to, of course!).<br><br>--What&#39;s on the menu ?--<br>The menu page is where you&#39;ll find all your recipe ideas.  Why is it called menu?  Because just like the menu in a restaurant, everything on the menu page is available to you now.  SuperCook instantly analyzes 11 million recipes and finds the ones that match your unique ingredients.<br><br>Most likely your menu page will contain thousands of recipes, but don&#39;t worry, we&#39;ve broken them down into helpful categories like soups and stews, appetizers and snacks, salads, entrees, desserts and more.<br><br>--Reduce food waste--<br>Most people don&#39;t realize how much food they throw away every day \u2014 from uneaten leftovers to spoiled produce. SuperCook is one of the best ways to reduce food waste in the home.   It finds recipes that use as many of your ingredients as possible, so nothing goes to waste.    SuperCook makes food waste prevention fun and easy, just open the menu page on the app and choose a recipe.   We help you use what you have, so nothing goes to waste!",
    "summary": "Grocery to Recipe - make recipes with ingredients you already have at home.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2719081,
    "score": 4.7462277,
    "ratings": 15192,
    "reviews": 2722,
    "histogram": [
        187,
        83,
        374,
        2104,
        12440
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "SuperCook",
    "developerId": "SuperCook",
    "developerEmail": "android@supercook.com",
    "developerWebsite": "https://supercook.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.supercook.com/privacypolicy.htm",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/yoSRLlXmNslsibpFsON5SJ_4DbRgMGnJmZLt1i_7sCkUZrDHRJsqhKyZMztwUIRmKxA",
    "headerImage": "https://play-lh.googleusercontent.com/VQad0StkRXyhLthMpJEb5OuaDDtXYcgHjZ8Htvson2tGgltu-fCwcsdd_SF0cIvuWS4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Y5zVzKX-TOmcqJxQkWojis6B7STdys228hE8O3o9Rm-ZdzMVtj1osVeyBC-BcKOiw0o",
        "https://play-lh.googleusercontent.com/V_3UcyLuKJFAbbBgwm69JnWur8KEcJ5U7v58c7wcLhhjCgT5HdWbu5AaL4R9u7qPlOk",
        "https://play-lh.googleusercontent.com/4jCsEOBojN0-bbCC33go2L5hOWwhEyJ1eCo6HhdI274wEwnOy6o2t_pSSqoRoPDTQKM",
        "https://play-lh.googleusercontent.com/h4J9Rsr0x1_Y1vuQgxyUzoYoqd4zrJDwyawRNmZkqy1aJwraz6vYZb6W1at_1oWCyGw",
        "https://play-lh.googleusercontent.com/xtOXhsw6gkoNy8eFGnaurShyTSYA0Mwm_HPx3Rw6qBC7nYqoJiH4ELFrI6GlyMf2f5w",
        "https://play-lh.googleusercontent.com/OssfPKEhJU2XuzOkCz--DSLAHFQ3FGeNgex_iqUGbyH-ySwswyF6AMh17-uDIkTYRn5r",
        "https://play-lh.googleusercontent.com/nvmdd3VJhpgB-gCkGS2LCrv9ZGvQZ16S61wR-ueKwhJcHVRj0SvcSh9RE3q_1gJRurg",
        "https://play-lh.googleusercontent.com/DH8BPwH_Qgxl56vc2Nj5t2nUsAn6vuhqyaAbRmXbBOePsR6yTGnTKW_y0QmPJ6FTrD0",
        "https://play-lh.googleusercontent.com/aLertfD6d56hsbPDi9j54wcUrGfIPVtebgPzvJeqJ8IgLbJHN0KPCu6mz9F8SGwFjZ8",
        "https://play-lh.googleusercontent.com/W8A72MVKpvHPf5Ion51Cw0nw3I7qOi1-04WWRPffNStXbVXL50T07nPMWEYKaDj3jpc",
        "https://play-lh.googleusercontent.com/AQlS5BUA4_94lJ2fnPt7oRIOACpe-DMvXYvYFsdeYeCKTS6X4kdkjSDH7ym8H2wnsqY",
        "https://play-lh.googleusercontent.com/LrDDUwhsjSY5Ygn8qogALbKqqJYcMLBcqWm6u5hB7WMtCkzuBwxNKlZlhDcIqYcF_HU",
        "https://play-lh.googleusercontent.com/8PjVi0dFP2xoZhNVZpPxxxXylO6TwZq3ByxYv10uPnLlIjIBnVnnHs5b3ufCbPA9dbA",
        "https://play-lh.googleusercontent.com/IdRNf1MXkMAC7lzwQ_pjtRZjqKAkrFDOCpUXlj6sIUxs3rS7GLYVJJAbYIIJTPeBT8M",
        "https://play-lh.googleusercontent.com/rOmdN17HtGapEovZlmrWeOdfWIPhgXfuWZVm0rm6r16qjlQO4JzrVws93Nf2vC68iq4"
    ],
    "video": "https://www.youtube.com/embed/KE1e40g0WbE?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/VQad0StkRXyhLthMpJEb5OuaDDtXYcgHjZ8Htvson2tGgltu-fCwcsdd_SF0cIvuWS4",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 23, 2019",
    "lastUpdatedOn": "Jul 2, 2024",
    "updated": 1719935377,
    "version": "2.0.25",
    "comments": [],
    "appId": "com.supercook.app",
    "url": "https://play.google.com/store/apps/details?id=com.supercook.app&hl=en&gl=us"
}