{
    "title": "All-In Summit",
    "description": "Application for events hosted by All-In Summit.\r\n\r\nFeatures: the app gives attendees access to the event agenda, important information, event FAQs, attendee networking, and much more!",
    "descriptionHTML": "Application for events hosted by All-In Summit.<br><br>Features: the app gives attendees access to the event agenda, important information, event FAQs, attendee networking, and much more!",
    "summary": "Access All-In Summit event",
    "installs": "100+",
    "minInstalls": 100,
    "realInstalls": 157,
    "score": 0,
    "ratings": 0,
    "reviews": 0,
    "histogram": [
        0,
        0,
        0,
        0,
        0
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Accelevents",
    "developerId": "7137658302480090884",
    "developerEmail": "jnolt@accelevents.com",
    "developerWebsite": null,
    "developerAddress": "10 Post Office Square\nSuite 800 South\nBoston, MA 02109",
    "privacyPolicy": "https://docs.google.com/document/d/1J1dcF77-A-ChQtlS7XFoP9goo60gnm4otBNrsk9k7-U/edit",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/hcBI6rqeV2ZGDhiSzqJSCg-9aHVI1Bnk3rvfUzFFH_ceobpXc95sscd2QiMJzTYi8gc",
    "headerImage": "https://play-lh.googleusercontent.com/wy-Gnej_1rlfLCUwxpqBnaqSOyS5clZctko4i2eQc8cSQSgvbYFwv6Kv_mfpg1feDr4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/FirnUYd2nn59UjRguEFqbNlblSR-caWDUVsWfEoSjoh6FHne5CL1DUqzN-7aXLZ3WIo",
        "https://play-lh.googleusercontent.com/PWm98qZQFRm3EQxn0_dslLBPkxysYgKgq9j546kUHMqbl7Rlpf9BJMb-b4_D5fdtl6g",
        "https://play-lh.googleusercontent.com/4Jl1rEUsSDwMD6JUfK9paXgebeiVfUll6yjrF0u4vn-YXD-d7UBS4XwHTQk3V8c94v4",
        "https://play-lh.googleusercontent.com/RQG6TyxNKnQCYOYG0CKDCJ_42RPTsUa1lfQ1KkYvcWYEYdwUp_WdHNPaGL1lPgVN_Fk",
        "https://play-lh.googleusercontent.com/ypkUvz5N70VQHtBEtw4oliHVqKthbC9KIMvZqPNPUT2tW9Td8l76r8Z5yO6I3NKsy6I"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 21, 2024",
    "lastUpdatedOn": "Sep 2, 2024",
    "updated": 1725284352,
    "version": "1.3",
    "comments": [],
    "appId": "com.allinsummit.app",
    "url": "https://play.google.com/store/apps/details?id=com.allinsummit.app&hl=en&gl=us"
}