{
    "title": "Tomorrow's Affairs",
    "description": "Download the Tomorrow's Affairs app to find analysis, explanation and assessment of the most important developments in global politics and economy: expert, impartial and accurate.\r\n\r\nTomorrow's Affairs app is your digital assistant in understanding today's complex and interconnected world.\r\n\r\nThe Tomorrow\u2019s Affairs app publishes in-depth analyses of key world events and processes. Our authors are obliged not only to describe reality through argument, but also to predict future events and processes based on their findings.\r\n\r\nThe Tomorrow's Affairs app will provide you with analyses and projections in  politics, economy, energy, finance, technology, companies, in addition to events from world regions: Europe, the US, China, the Middle East, Russia, and Turkey. Tomorrow's Affairs pays particular attention to globalisation and current analyses, and predicts future trends.\r\n\r\nTomorrow's Affairs believes that today's world cannot be understood sufficiently if events and processes are viewed separately. \r\n\r\nEven if we believe we have a good understanding of today\u2019s world, it will not help us to face the future calmly if we fail to make an effective assessment of future events. We can only do this through collective knowledge, communication and openness. That is why\u00a0Tomorrow\u2019s Affairs\u00a0exists.\r\n\r\nTomorrow\u2019s Affairs app is free to download. \r\n\r\nMore information about Tomorrow\u2019s Affairs Privacy policy, Terms and Conditions and contact details can be found at www.tomorrowsaffairs.com",
    "descriptionHTML": "Download the Tomorrow&#39;s Affairs app to find analysis, explanation and assessment of the most important developments in global politics and economy: expert, impartial and accurate.<br><br>Tomorrow&#39;s Affairs app is your digital assistant in understanding today&#39;s complex and interconnected world.<br><br>The Tomorrow\u2019s Affairs app publishes in-depth analyses of key world events and processes. Our authors are obliged not only to describe reality through argument, but also to predict future events and processes based on their findings.<br><br>The Tomorrow&#39;s Affairs app will provide you with analyses and projections in  politics, economy, energy, finance, technology, companies, in addition to events from world regions: Europe, the US, China, the Middle East, Russia, and Turkey. Tomorrow&#39;s Affairs pays particular attention to globalisation and current analyses, and predicts future trends.<br><br>Tomorrow&#39;s Affairs believes that today&#39;s world cannot be understood sufficiently if events and processes are viewed separately. <br><br>Even if we believe we have a good understanding of today\u2019s world, it will not help us to face the future calmly if we fail to make an effective assessment of future events. We can only do this through collective knowledge, communication and openness. That is why\u00a0Tomorrow\u2019s Affairs\u00a0exists.<br><br>Tomorrow\u2019s Affairs app is free to download. <br><br>More information about Tomorrow\u2019s Affairs Privacy policy, Terms and Conditions and contact details can be found at www.tomorrowsaffairs.com",
    "summary": "Tomorrow\u2019s Affairs app describes reality and predicts future processes.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 5288205,
    "score": 4.285714,
    "ratings": 2029,
    "reviews": 22,
    "histogram": [
        217,
        72,
        72,
        217,
        1449
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Tomorrow\u2019s Affairs",
    "developerId": "Tomorrow%E2%80%99s+Affairs",
    "developerEmail": "info@tomorrowsaffairs.com",
    "developerWebsite": "https://www.tomorrowsaffairs.com",
    "developerAddress": null,
    "privacyPolicy": "https://tomorrowsaffairs.com/privacy-policy/",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Y6_4mlEKzWZcmzRVwRC9WIilDD2VZnyAGohd8ZVLctDg--0LBYtCJlKNXZ57GCe_jN7Z",
    "headerImage": "https://play-lh.googleusercontent.com/29pUlaefYM0jdrTk-g8LQr731iy5pxFa_XStKulsXW8xpV-x1sCD0OklW5YnrM4Ykbo",
    "screenshots": [
        "https://play-lh.googleusercontent.com/lG9w7F9If_oTbVmfmnXNmu_uarMrY1T3uLt56u62P9Xid7MtYKeV8MHiL99-1Fzvng",
        "https://play-lh.googleusercontent.com/5WknEWvOu_mpGqpdUXlLf58kyXHv5FVEURpZPcAUY9MEmE7Rr64TrovDnNdPoBgD8w",
        "https://play-lh.googleusercontent.com/zrECOVEtnMbL04mSnJxm5wXyupQov7cYY2S3Nrz_IWbqdz-KWytJwQySC8HzjjNleoM",
        "https://play-lh.googleusercontent.com/wBCmtQAqT5INlSvvLGzn1n2MQXqPJoss3woprMt0BkDazduDXOmGSmtPolwUR-qcCE-r",
        "https://play-lh.googleusercontent.com/Waz2dTUcbGNZiKF4IQ5hEZZnq9FYjIwpJouUnIKxhhW2Tvteu1jLP8v8xxBnQ-2z3PA",
        "https://play-lh.googleusercontent.com/BchvJHCn16qJnVZCw9aiSfB8oj6yrWwiZNZONr7VBmbCEeP2LfV-dKGkXaRKsedA8x4",
        "https://play-lh.googleusercontent.com/Vx_neRt9YLJGLJm5gFX_bMUwobVEV5p_F50S7YnEt5uaJPSpYtAIP8fppOxwW0F1xg",
        "https://play-lh.googleusercontent.com/IjFzDtIcFi3zji5851W-TI2s_NsfRJScXe56a0okSwpxEnkgJ6NauP6GUkkHZCGAkSQ",
        "https://play-lh.googleusercontent.com/NNWltS7CFZM7qeqIsGyoWhCvikXOp0iiF-vniYh4pUi1Y6LP2Gz4C_cpFd9QI-a5W5E"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 24, 2023",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729008660,
    "version": "1.8.1",
    "comments": [],
    "appId": "com.tomorrowsaffairs.app",
    "url": "https://play.google.com/store/apps/details?id=com.tomorrowsaffairs.app&hl=en&gl=us"
}