{
    "title": "Boot Barn",
    "description": "Boot Barn is the nation\u2019s largest retailer of western and work boots and clothing, hats, accessories, and the latest in western-inspired fashion. The new Boot Barn app brings you our full product assortment plus exclusive in-app features.\r\n\r\nExclusive App Features\r\n\r\nShop:\r\nExplore our full assortment of thousands of cowboy boots, work boots, clothing, cowboy hats, accessories, and western fashion pieces. Plus, get first access to exclusive collections and new arrivals. Easily search for items or shop by category to find products tailored to your lifestyle.\r\n\r\nIn-Store Mode:\r\nShop items available in your local store for an easy in-store shopping experience.\r\n\r\nConcerts & Events Finder:\r\nDiscover concerts, local events, and rodeos coming soon near you and get everything you need to get ready for the show.\r\n\r\nBoot Barn Radio:\r\nListen to our curated playlist including country classics, the latest hits, and new music from aspiring artists.",
    "descriptionHTML": "Boot Barn is the nation\u2019s largest retailer of western and work boots and clothing, hats, accessories, and the latest in western-inspired fashion. The new Boot Barn app brings you our full product assortment plus exclusive in-app features.<br><br>Exclusive App Features<br><br>Shop:<br>Explore our full assortment of thousands of cowboy boots, work boots, clothing, cowboy hats, accessories, and western fashion pieces. Plus, get first access to exclusive collections and new arrivals. Easily search for items or shop by category to find products tailored to your lifestyle.<br><br>In-Store Mode:<br>Shop items available in your local store for an easy in-store shopping experience.<br><br>Concerts &amp; Events Finder:<br>Discover concerts, local events, and rodeos coming soon near you and get everything you need to get ready for the show.<br><br>Boot Barn Radio:<br>Listen to our curated playlist including country classics, the latest hits, and new music from aspiring artists.",
    "summary": "Shop Cowboy Boots, Work Boots, Clothing, Hats & Western Fashion",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 227514,
    "score": 4.701613,
    "ratings": 1198,
    "reviews": 245,
    "histogram": [
        57,
        0,
        28,
        67,
        1042
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Boot Barn",
    "developerId": "Boot+Barn",
    "developerEmail": "webmaster@bootbarn.com",
    "developerWebsite": "https://www.bootbarn.com?utm_source=google-play&utm_medium=referral",
    "developerAddress": "15345 Barranca Pkwy\nIrvine, CA 92618-2216",
    "privacyPolicy": "https://www.bootbarn.com/cs-privacy-policy.html",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/9RZGsvz6tClUyzh48CvwJoXiQvzJminJHOkVfqUMTi-HsJ2W8HajcyfZLNckSCNcYIs",
    "headerImage": "https://play-lh.googleusercontent.com/8miKjq50e7ffdJJJ2eqOGAFL5NGLHdvF3ffM56-0bGgVOnaGq3c4zzb_vMtlwhvpo039",
    "screenshots": [
        "https://play-lh.googleusercontent.com/wmCk8ma5d0x1ZKK_wd18r3LqHmqwsU8h0ioT-Eoyj-4edvNqna3FSMHMPck4iMNGSVc",
        "https://play-lh.googleusercontent.com/fIojYqMKi0J2AoJWS3q4W03hAU6KI9-HC4h1KRZnNSlTH1ujJ-h01wummgyO-9J_1Bg",
        "https://play-lh.googleusercontent.com/ix0A8jrH7a74SrTQzcVWeROn1z6Pb-G4fa7mDglAbTGVzMK1ia-r0Xbl_xTUe_gViCwj",
        "https://play-lh.googleusercontent.com/V_gokwwT0yeve1_R-owyoAMpjKKC_AHQwKOkyQxPkVj5gZ89TKIx35vkgawRuXvIr7c",
        "https://play-lh.googleusercontent.com/pyQJ0rTiVnaSCGKgRV2B0UO3yin53jSGVuMh8bK-sUffa5Kw8gxO6kjYpONj4rSigc9S",
        "https://play-lh.googleusercontent.com/eQkM1Axcvj-YGZg9eV4QaQxVQlrvt1eLlFRdCSKlvG5emBGziTgRl97CELiU1uxZ8Q",
        "https://play-lh.googleusercontent.com/zAqsMgimDxGourvOgzHd-ZfENovk6migUuih2jgFE0nStbE6gMQ4geaqEDp3OldP_A",
        "https://play-lh.googleusercontent.com/BjTXb8-3_Opy-VKvYLUyVDt_xX0oLbEc0soVdefIBpOFJE62auqMRwOLVB_3FzbiYhU",
        "https://play-lh.googleusercontent.com/Axs2QHqy-sFe8V2S2Nd2Z4yHXfO1QpAAqj-Hc4SAs19kNkyKuNQI2j25IlsQ3yi3xnY",
        "https://play-lh.googleusercontent.com/oojvyfppSeSXCZhCnxbsq_2lta0Mz7KFkFJIfPO4Jocf96MvTDNPMGSc_RMxsQbjio0",
        "https://play-lh.googleusercontent.com/yLIIn_zolkTzq3dGiBOQzepnMYY6JsmNyuPBmCQA-fFuR9rIPrK3ak0CDn3INKXSOQs",
        "https://play-lh.googleusercontent.com/QC99vpSVvGXUvZoEZp-zmOaeKaGgCGsQAUgppt0yL76LbZz-0IGVY0gRm7Pq4LoV47E",
        "https://play-lh.googleusercontent.com/wP7toTV85E48N7i3TsMLlkS1U1yF0XulOVWz9QFQXzDEpF4MSvtSa40by72G7wd7sQ",
        "https://play-lh.googleusercontent.com/nhtpc0g5tKd7AuznUH_m381ajALjZS_xFa2WNt7ITN-nT8Mi9Q3ZG1c0NzUh_5xGmFc",
        "https://play-lh.googleusercontent.com/p4H6nfVHWd-b73xwAtGFapEiqozH15ebMx9Sn6W1tLRiRKZoU8LFHl2h9JyodywKtdA",
        "https://play-lh.googleusercontent.com/PiK4psD0lsKzeR-Cq2mfGrH3A7PNTamRYbLewLq0QIx5CYT2AAZWx4OSDQowhFPsejU",
        "https://play-lh.googleusercontent.com/329NB1aTfKurqAGGP4HOyNz3u8pGYFPsUECsABrJZDjytcgrO1ArLSod5uZ2jMM3uA",
        "https://play-lh.googleusercontent.com/Wx-KJyvwBQqkYDSWrmKo1qme4_XQbMI6pM-DIdBptcxI17gIlVOlXuBfjawJMIXFJIKC",
        "https://play-lh.googleusercontent.com/w6ujdkrwj77mFcpauUl02NsFFCamNYYwIESEaMMfEYuZ7B4ctaVfIxZOvfcCKYUzXCmh",
        "https://play-lh.googleusercontent.com/W3oA2YLgEVW4Fs2CJCjdiXLBoSPt7ozE0sXV3l7u42e4HFb4bpaVKAsvK3wBGoAjsio",
        "https://play-lh.googleusercontent.com/Bu42Czv7h52fG72xI2cO-uwUDpDe71lQ0v1jieS8-2BaDn1NxpaGA4aEkeoisbKjoaE",
        "https://play-lh.googleusercontent.com/TrTpnZYe9kRjPJh2IoVM-8nH4jgMEQIB9LMKpkWmtE0ZDcLUqW3c1lfyJfi8yxpMZVo",
        "https://play-lh.googleusercontent.com/IJKuFuKCtjvtQ6s3obby_AzoeVMPxqJZcwWjN8WBjvBRormC0LEO2qyoEQCAde4jjgU",
        "https://play-lh.googleusercontent.com/7cyLieSGxlLFSAYZKdkDgXYamU0fC6-fJDg6jWJ1A7NQh1u7b3bxgWop3OeJDEzyogo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 11, 2022",
    "lastUpdatedOn": "Aug 29, 2024",
    "updated": 1724957890,
    "version": "2.9.0",
    "comments": [],
    "appId": "com.bootbarn.app",
    "url": "https://play.google.com/store/apps/details?id=com.bootbarn.app&hl=en&gl=us"
}