{
    "title": "Agorify",
    "description": "Agorify enhances your online and onsite event experience to a new level. \r\n\r\nWith Agorify you can:\r\n\u2043Network with delegates, either in private or in groups.  \r\n\u2043Watch live-streamed or on-demand sessions\r\n\u2043Access the agenda, exhibitors, speakers and relevant event information\r\n\u2043Create your own digital agenda\r\n\u2043Participate in virtual round tables\r\n\r\nFind out more at https://agorify.com/",
    "descriptionHTML": "Agorify enhances your online and onsite event experience to a new level. <br><br>With Agorify you can:<br>\u2043Network with delegates, either in private or in groups.  <br>\u2043Watch live-streamed or on-demand sessions<br>\u2043Access the agenda, exhibitors, speakers and relevant event information<br>\u2043Create your own digital agenda<br>\u2043Participate in virtual round tables<br><br>Find out more at https://agorify.com/",
    "summary": "Your Event Companion",
    "installs": "5,000+",
    "minInstalls": 5000,
    "realInstalls": 9200,
    "score": 0,
    "ratings": 0,
    "reviews": 0,
    "histogram": [
        0,
        0,
        0,
        0,
        0
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Agorify",
    "developerId": "Agorify",
    "developerEmail": "hello@agorify.com",
    "developerWebsite": "https://agorify.com/",
    "developerAddress": null,
    "privacyPolicy": "https://agorify.com/privacy-policy",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/5r8c-6EVBZ0qT6K2phL8uejl5sdGisEMv2k5GCoD3ryJGz3t10HTjL__4wucGXRa0g",
    "headerImage": "https://play-lh.googleusercontent.com/WzLAoKYaidkhlFGwmReCdUaao7bbq5L_gwbMgoueoVD-KFGenW0oeI6dwSuaQiFmuQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/GXUrG-VhEmh8jBA0fw_FVYY2VZxYhzB5SEDLT9VOyD6jHow1yCeLyzwxfKUCZy7i2Q",
        "https://play-lh.googleusercontent.com/kHuymXkhPClGkPYU9hA3WUowZm-m_XPp7iNzYuda_Q2JvzGxxrFXSK7MVTN2IiG6Jzc",
        "https://play-lh.googleusercontent.com/n3ojrlIHCRk6nBlTZFQLMkunJiuMrqyxdhhJx6NxUnA4LPMaxr54VwU-vcFvL3AE3A",
        "https://play-lh.googleusercontent.com/KxBq4IwEOvQ0XlaTMEbdb6bID_emsneCajX66cd8W2NupzTlebubwzqIHzEs5gpHCG0t",
        "https://play-lh.googleusercontent.com/ceJtcZm6wgWyFP3tHAw9Xok530j2dHoaXIe_rWu3Q21cgJ5p2VRknYqD_mgix0fCN5o",
        "https://play-lh.googleusercontent.com/zp6HwtqVB8F2bddAp-jLyyKrffL40QEOPNLO05JGOtqNxXsN4O_xCbM5UEJLWMdfTUM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 9, 2018",
    "lastUpdatedOn": "Oct 1, 2024",
    "updated": 1727801357,
    "version": "1.6.11",
    "comments": [],
    "appId": "com.agorify.app",
    "url": "https://play.google.com/store/apps/details?id=com.agorify.app&hl=en&gl=us"
}