{
    "title": "Roadie Driver",
    "description": "<b>EARN CASH FOR DRIVING, YOUR WAY</b>\r\nRoadie is the easiest, most flexible way to make extra cash in the Gig economy. Drivers earn $8-$60 on local Gigs, and even more on long haul deliveries. With no interviews or vehicle requirements, it\u2019s never been easier to sign up for a new side hustle!\r\n\u2003\u2022\u2003Choose deliveries that fit your schedule\r\n\u2003\u2022\u2003See pickup and dropoff details before you offer\r\n\u2003\u2022\u2003Deliver packages, not people\r\n\u2003\u2022\u2003Enjoy direct deposit into your bank account\r\n\r\n\r\n<b>WHAT\u2019S NEW IN OUR DRIVER APP</b>\r\nRoadie puts you in the driver\u2019s seat with more control over when and where you drive. Our new Driver App takes that even further by allowing you to: \r\n\u2003\u2022\u2003See more detailed information about deliveries, so you can be prepared ahead of time\r\n\u2003\u2022\u2003Choose your own navigation app\r\n\u2003\u2022\u2003Handle common pickup and delivery issues quickly and efficiently in the app, without a call to Support\r\n\r\n\r\nDownload the Roadie Driver App today and provide your feedback at driverfeedback@roadie.com!",
    "descriptionHTML": "<b>EARN CASH FOR DRIVING, YOUR WAY</b><br>Roadie is the easiest, most flexible way to make extra cash in the Gig economy. Drivers earn $8-$60 on local Gigs, and even more on long haul deliveries. With no interviews or vehicle requirements, it\u2019s never been easier to sign up for a new side hustle!<br>\u2003\u2022\u2003Choose deliveries that fit your schedule<br>\u2003\u2022\u2003See pickup and dropoff details before you offer<br>\u2003\u2022\u2003Deliver packages, not people<br>\u2003\u2022\u2003Enjoy direct deposit into your bank account<br><br><br><b>WHAT\u2019S NEW IN OUR DRIVER APP</b><br>Roadie puts you in the driver\u2019s seat with more control over when and where you drive. Our new Driver App takes that even further by allowing you to: <br>\u2003\u2022\u2003See more detailed information about deliveries, so you can be prepared ahead of time<br>\u2003\u2022\u2003Choose your own navigation app<br>\u2003\u2022\u2003Handle common pickup and delivery issues quickly and efficiently in the app, without a call to Support<br><br><br>Download the Roadie Driver App today and provide your feedback at driverfeedback@roadie.com!",
    "summary": "Roadie connects people with stuff to send with drivers already going that way.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1151730,
    "score": 4.021011,
    "ratings": 17627,
    "reviews": 8102,
    "histogram": [
        3293,
        580,
        479,
        1380,
        11891
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Roadie, Inc.",
    "developerId": "Roadie,+Inc.",
    "developerEmail": "driverfeedback@roadie.com",
    "developerWebsite": "https://www.roadie.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.roadie.com/privacy",
    "genre": "Maps & Navigation",
    "genreId": "MAPS_AND_NAVIGATION",
    "categories": [
        {
            "name": "Maps & Navigation",
            "id": "MAPS_AND_NAVIGATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/uCpP1a7Pvy6hInBErTH_qLHdhKcBJkk0xWIT83sR-Jfly2EmC6WNVmbcrYxabBlfnrEb",
    "headerImage": "https://play-lh.googleusercontent.com/mOZvAEi0FOiZD1VJi4_whCsm0azFin4nd4qPSGC3Glm1wPhJDuBzU_hDxt2gqH0j8Q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/5LVEVNVn6xI3Xz6k4qsjTGaFmh2uEn7e1Tu_Ij3DIJz7vdd77cYejoIvIa7dxLi10Hk",
        "https://play-lh.googleusercontent.com/5_D6OU9yPX3KMa_BDVkRfWp1Of9cnzykGZD2tx307F4qqNGqFI1R7CTmdNT2HJ3_vPRS",
        "https://play-lh.googleusercontent.com/vaYsZn8eNBI66uqfoC5JGD8aMIJ83armB9VlacvuOdrSUmIbC-62a3_HPpLJZqoMMcA",
        "https://play-lh.googleusercontent.com/MYT5rNhmffiL28fjhDrCdwfkVIsdhvIhNKqSGE77UF3iVDruArsQB5XgW0uVMj3bvA",
        "https://play-lh.googleusercontent.com/fIT1ZpNKxDQfZTul4LmD-vTR0DHfW5esUL1E78dKyTZKNiq6D26I0DXPS0C9oiNPDf0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 10, 2020",
    "lastUpdatedOn": "Oct 2, 2024",
    "updated": 1727917846,
    "version": "2.100.1",
    "comments": [],
    "appId": "com.roadie.drive.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.roadie.drive.android.app&hl=en&gl=us"
}