{
    "title": "Voghion - Online shopping app",
    "description": "With Voghion, you can stay ahead of the trend and express your own style!\r\n\r\nVoghion provides amazing deals and covers a wide range of popular goods, especially fashion apparel to home, beauty, accessories, shoes and pet, plus electronics, tools, office and more, Voghion is dedicated to meet all your needs in life. With free shippings and free returns policy, hope you have a pleasant journey in Voghion!\r\n\r\n\r\nInspire yourself with Voghion right now!\r\n \r\n\r\nWide Selections\r\n\r\n- Over 300 categories, 150 million high quality products at factory prices!\r\n- Browse by Best Sellers, New Arrivals, Trends, Category and more\r\n \r\n\r\nSave a Lot!\r\n\r\n\r\n- 99\u20ac coupon bundle for  all new users\r\n- Free shipping on orders over 20\u20ac and free rerturns in 30 Days\r\n- Daily Flash Sales: Up to 90% off for countless items\r\n- Monthly big sales: Down to 0.99\u20ac\r\n \r\n\r\nConsiderate services\r\n- 24/7 customer service and live chat available\r\n- Personalized product recommendations\r\n- Accepting PayPal and major credit cards\r\n- Buy now, pay later! Choose Afterpay or Klarna to pay in 4 interest-free payments\r\n- All items are covered with buyer protection\r\n\r\nVoghion is the perfect shopping assistant for anyone who wants to save time and money. With Voghion, you can shop smarter and faster than ever before. Download Voghion today and start shopping smarter!\r\n\r\n \r\n\r\nEmail: support@voghion.com\r\nFacebook: https://www.facebook.com/voghion\r\nInstagram: https://www.instagram.com/voghion__official/\r\nTikTok: https://www.tiktok.com/@voghion_official\r\nOfficial Site: https://www.voghion.com \r\n\r\n\r\n \r\n\r\n* Brand product authorization is provided by the merchants and distributors who have joined in Voghion",
    "descriptionHTML": "With Voghion, you can stay ahead of the trend and express your own style!<br><br>Voghion provides amazing deals and covers a wide range of popular goods, especially fashion apparel to home, beauty, accessories, shoes and pet, plus electronics, tools, office and more, Voghion is dedicated to meet all your needs in life. With free shippings and free returns policy, hope you have a pleasant journey in Voghion!<br><br><br>Inspire yourself with Voghion right now!<br> <br><br>Wide Selections<br><br>- Over 300 categories, 150 million high quality products at factory prices!<br>- Browse by Best Sellers, New Arrivals, Trends, Category and more<br> <br><br>Save a Lot!<br><br><br>- 99\u20ac coupon bundle for  all new users<br>- Free shipping on orders over 20\u20ac and free rerturns in 30 Days<br>- Daily Flash Sales: Up to 90% off for countless items<br>- Monthly big sales: Down to 0.99\u20ac<br> <br><br>Considerate services<br>- 24/7 customer service and live chat available<br>- Personalized product recommendations<br>- Accepting PayPal and major credit cards<br>- Buy now, pay later! Choose Afterpay or Klarna to pay in 4 interest-free payments<br>- All items are covered with buyer protection<br><br>Voghion is the perfect shopping assistant for anyone who wants to save time and money. With Voghion, you can shop smarter and faster than ever before. Download Voghion today and start shopping smarter!<br><br> <br><br>Email: support@voghion.com<br>Facebook: https://www.facebook.com/voghion<br>Instagram: https://www.instagram.com/voghion__official/<br>TikTok: https://www.tiktok.com/@voghion_official<br>Official Site: https://www.voghion.com <br><br><br> <br><br>* Brand product authorization is provided by the merchants and distributors who have joined in Voghion",
    "summary": "A full-category platform to pick the best deals of high-quality various products",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 7351895,
    "score": 4.357143,
    "ratings": 9269,
    "reviews": 12,
    "histogram": [
        993,
        0,
        662,
        662,
        6951
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "VOGHION TECH LIMITED",
    "developerId": "VOGHION+TECH+LIMITED",
    "developerEmail": "customer@voghion.sg",
    "developerWebsite": "https://m.voghion.com",
    "developerAddress": null,
    "privacyPolicy": "https://help.voghion.com/PrivacyNotice.html",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/rawQezYahhHrTXgzy4Kt--zmasQsd_VLBhBa9DZEPQeahDZ1Zo9NhsJWku1ZLuIBuXw",
    "headerImage": "https://play-lh.googleusercontent.com/NhYQmGeHsKJGcLr8ZjMrhy2ndgT3PPgdVmWqk3aX7s1jaH6AwvMG14RtVKZaCxLVQg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/BW3oz8n28qfYJcsCE--dHBRfxO9Cx8muQp3xuR6MVWHQNp9oeS2gZug8-VKBfzBGTdDc",
        "https://play-lh.googleusercontent.com/kiNmgrPJwtSPjUEBoJu7dzV_e-AN9Qp3WVKv1SN5wYagiOg6-y6hY8UYBUygi0zqOA",
        "https://play-lh.googleusercontent.com/zPZnIgUbpNDpZKh1yR4tK59Yltle35cBy0S_YQFTI4ZyEDemNMpwqjmK94JRm8Aj6Q",
        "https://play-lh.googleusercontent.com/cF833fTbNk_-OBhUkXrs0-HFnWMi9iR2CODd-VEc-9ZuBnXQgg3BcuL7dLkzDKpq_UM",
        "https://play-lh.googleusercontent.com/o8EnzMteVBsnA6UvnpDpE3wMq-tUoKMEFqyB1p6LdM0uac8UEZMAvf2_NnoktrFkCMAb",
        "https://play-lh.googleusercontent.com/MymS4K6d-FBPxBFRIOH-5bGPqnbq0_dBR9PwkJlQLpXugABkT2c79y2abUubPoI8GuM",
        "https://play-lh.googleusercontent.com/qNi9Mkft5YCj2seU9An_uzUNp-OjEzA7RfOu1xgHmQm45IZWfbQ6CbpIK83eQG0jpX0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 29, 2021",
    "lastUpdatedOn": "Sep 26, 2024",
    "updated": 1727346922,
    "version": "2.1.8",
    "comments": [],
    "appId": "com.voghion.app",
    "url": "https://play.google.com/store/apps/details?id=com.voghion.app&hl=en&gl=us"
}