{
    "title": "GIF Maker Pro",
    "description": "Whether you want to create a sliced GIF for a movie or create your own exclusive emoji, you can't miss this app, which can help you easily complete the GIF production.\r\n\r\nFeatures:\r\n1. Browsing videos online to search for GIF materials;\r\n2. One click download of online videos;\r\n3. Convert the video to GIF with just one click;\r\n4. Support GIF creation for images or videos;\r\n5. Support adding text or stickers;\r\n6. Support setting the resolution and frame rate of GIF.",
    "descriptionHTML": "Whether you want to create a sliced GIF for a movie or create your own exclusive emoji, you can&#39;t miss this app, which can help you easily complete the GIF production.<br><br>Features:<br>1. Browsing videos online to search for GIF materials;<br>2. One click download of online videos;<br>3. Convert the video to GIF with just one click;<br>4. Support GIF creation for images or videos;<br>5. Support adding text or stickers;<br>6. Support setting the resolution and frame rate of GIF.",
    "summary": "GIF and dynamic emoji maker.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1432389,
    "score": 3.69,
    "ratings": 850,
    "reviews": 277,
    "histogram": [
        177,
        67,
        42,
        109,
        449
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Feel Good Foods Inc.",
    "developerId": "Feel+Good+Foods+Inc.",
    "developerEmail": "ashishsatishpandya2@gmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://sites.google.com/view/convert-to-gif",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/d5Xvs0FpqLqPaf5zyDNewxGgwqIOuGWyrzeD79TefI-iXtiBK2FtohghjhPaDVd2uw",
    "headerImage": "https://play-lh.googleusercontent.com/jSrN5MDzirp469qorkkzlyFmNdfE9uHKUZ9PJ4XL2A1whxoSEjdHZFJkyXW6ekUIi9g",
    "screenshots": [
        "https://play-lh.googleusercontent.com/YLYHaGf-SlCSSm8ZJusMkkxS--5pQNH6q6gNCzWYivQS1bDI3sbVrf4f2ZzVZBg7bQ",
        "https://play-lh.googleusercontent.com/vX7cCCIj7CoumzZ3XpJPdl6mBX8QkEaeWru1RqhCwYWbZda1jBa9Tz2fjFh7n1kEaXo",
        "https://play-lh.googleusercontent.com/sQxqCqYpVduHojZvqfwNgnqfg3Su2eS1J9p5KIVG49EchWlgo0Tx-nlzl3LSeacT2pE",
        "https://play-lh.googleusercontent.com/f5k3fNZODF6C7M24HkA-nwg7kAouSQpMeaf44FLdx581qm670wZBNYjw2qoPx51S9w",
        "https://play-lh.googleusercontent.com/sL3px2djHahtpUl6TITmUFVqwWTejdYdMSkIqWB9A2DYmdgks-6DkjJhQQidLe7QJtY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Dec 28, 2023",
    "lastUpdatedOn": "Jun 13, 2024",
    "updated": 1718342020,
    "version": "1.2.4",
    "comments": [],
    "appId": "com.make.gif.pro",
    "url": "https://play.google.com/store/apps/details?id=com.make.gif.pro&hl=en&gl=us"
}