{
    "title": "Air Jordan Shop Big Deels",
    "description": "The Air Jordan sneakers are popular because celebrities recognize and wear these shoes. Athletes, entertainers, and actors wear these sneakers. Thus, any shoe can become something that people will remember and seek when someone famous buys an excellent pair of sneakers. With this, Air Jordan enjoys value and desirability.",
    "descriptionHTML": "The Air Jordan sneakers are popular because celebrities recognize and wear these shoes. Athletes, entertainers, and actors wear these sneakers. Thus, any shoe can become something that people will remember and seek when someone famous buys an excellent pair of sneakers. With this, Air Jordan enjoys value and desirability.",
    "summary": "The latest activity, the minimum pair is only 59$",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1067350,
    "score": 3.9320388,
    "ratings": 1421,
    "reviews": 360,
    "histogram": [
        317,
        0,
        54,
        137,
        910
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "dayak.LTD",
    "developerId": "dayak.LTD",
    "developerEmail": "croybal168@gmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://customer-service.on-running.com/en-jp/privacy_policy",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/_Z9aIHc1ENXz4GjNNFXZSrayEYEk3h27FeinfG8wUL9AjLuLedTYFTX13Pyib3dX428",
    "headerImage": "https://play-lh.googleusercontent.com/Yrfz_hX5XeaXkXWH0s34o5N2xbDvFLeSiltXnFsTPmllDxSYKaAUTw-f2WAKFB3VjIg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/6L7LWs0fENUC50DTYlyLxkTAhJZKIkCHFJOZuKqOQFwNkbAlJz4ddvCKf-mSbuCG1A",
        "https://play-lh.googleusercontent.com/3IdCZnwMry4UYeJRiHP0sOE4r3tevxgrKTu8Z-nX29e-Zy2rbkTTDk-zC690b9VJU7k",
        "https://play-lh.googleusercontent.com/hSvH6l5ikyAMVsjVf5CGCPK3GR85x8IyPacilAlaBSgRqeBOG1eNqLRgJTP8l8XwAV4",
        "https://play-lh.googleusercontent.com/clP0qfXYTVnJiC2879Ol--DEx5EDjKD_wsijWf8wfHODJIdRXPneXR9XTnLMzVs2sQ",
        "https://play-lh.googleusercontent.com/3WsVDaLvWM7J1hSm7LA6LMeXS_HRgxWROwEDb373XloZpBCmukvhAA8m4jTXAaI9T3o",
        "https://play-lh.googleusercontent.com/XhfEpS4x2ez72QIfhJ9vc2HSzCDVRSk-_t09sxh7COHljNfnmP0JUkymMu1lVfWCWuo",
        "https://play-lh.googleusercontent.com/_ISg3aE6tOgLxzx4QC3dQI2UrQJSNgz9Z0YR_1hVYtBeDRx7dyw4KcGOdxSZTHXTbN4",
        "https://play-lh.googleusercontent.com/EH5TZGK9R7scVJ7oo3MXoxUsQjdXK6Mqlvb6iTt5VTfgsKdVf6n9GYSaATPyuhXb6zQ",
        "https://play-lh.googleusercontent.com/rJIXJxPlhm1bW6wchiIcmz5q2Nr6VMx33jk5eazoOf32-6tlIGUkdBXQ2l_5foyvukc",
        "https://play-lh.googleusercontent.com/-lKsdODavMYLKhltXOq4qzzeI7_n_vuiJs6TG-ZJ88MvygOYpH3jREUefESM4aU3Ujg",
        "https://play-lh.googleusercontent.com/2WFKQ9A_A3x7dnix7lGeV6LEzZmrNbl4VD1N-66c57rZy8_vwJOq9zwGeZayKgAPN_E",
        "https://play-lh.googleusercontent.com/OMbUFYRcoQH1t9FJUW7eXUNWK8D5uKnLS6qMEoTq90DMcW6aSJZeu0awPKgLcnJOpg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 20, 2022",
    "lastUpdatedOn": "Aug 26, 2024",
    "updated": 1724662969,
    "version": "1.0.6",
    "comments": [],
    "appId": "com.airjordanshopbigdeels.app",
    "url": "https://play.google.com/store/apps/details?id=com.airjordanshopbigdeels.app&hl=en&gl=us"
}