{
    "title": "Police Scanner X",
    "description": "With Police Scanner X you can listen to Police/Fire/Radio Scanners from around the world.\r\nX as in eXperimental means this is the cutting edge police scanner version.  With the latest features added before other apps get to try them on for size!\r\n\r\n\r\nPolice Scanner X includes a custom stream player for faster playback and battery savings.\r\nRadio streams can be resumed at startup so you can quickly listen to your favorite police radio bands.\r\nPolice Radio 10-codes are included for quick reference so you can understand the chatter on the police radio.\r\nAuto resume last police scanner radio station. Now with more scanner stations.\r\n\r\nTop 50 Feeds (1000s more available!)\r\nChicago Police\r\nLAPD - Code 3/Hot Shots, Air/K9 and Van Nuys/Valley Traffic\r\nSan Diego Police Dispatch\r\nBayamon and San Juan Police\r\nPhoenix Police\r\nDenver Police, Fire and EMS\r\nCity of Tulsa and Rural Police, and Fire, Tulsa County Sheriff\r\nIngham County Public Safety\r\nMultnomah County Sheriff and Portland Police\r\nMemphis Police and Shelby County Sheriff\r\nWaterloo Regional Police\r\nNewark Police\r\nAmateur Repeater Los Angeles Area 147.435mhz\r\nCincinnati Police\r\nHouston Police\r\nNorthwest Ohio Digital and MARCS\r\nFort Worth Police Dispatch\r\nSacramento County Sheriff and Sacramento City Police\r\nDes Moines Metro Police\r\nSedgwick County Law Enforcement\r\nCleveland Police\r\nCity of Buffalo Police and Fire\r\nMadison Police \r\nAllen County Public Safety\r\nTucson Police and EMS\r\nMinot Police, Sheriff, Fire, and EMS\r\nStockton Police\r\nModesto Police Dispatch channel 1\r\nSan Juan and Ponce Police, Fire and EMS\r\nBlack Hawk County Police, Fire, and EMS\r\nAlbuquerque Police and Bernalillo County Sheriff\r\nAurora Police and Fire\r\nCity of Pittsburgh Police, Fire, and EMS\r\nAnne Arundel County Police, Fire, and EMS\r\nAkron Police Department\r\nAmarillo Police and Fire, Randall and Potter Counties Sheriff and Fire\r\nHunter Valley, Port Macquarie and Coffs Harbour Police\r\nNYPD Special Operations Division and Traffic\r\nLogan Police\r\nEvansville Police and Fire Dispatch\r\nPhiladelphia Police - Citywide\r\nFlint Police and Fire, Genesee County Fire Dispatch\r\nWestmoreland County Public Safety\r\nOxnard Police\r\nSan Bernardino County Fire and Sheriff System 1\r\nOmaha Police\r\nDetroit Fire Department\r\nLittle Rock Police Dispatch\r\nAllen County Public Safety\r\nButler County Sheriff, Police, Fire, and EMS",
    "descriptionHTML": "With Police Scanner X you can listen to Police/Fire/Radio Scanners from around the world.<br>X as in eXperimental means this is the cutting edge police scanner version.  With the latest features added before other apps get to try them on for size!<br><br><br>Police Scanner X includes a custom stream player for faster playback and battery savings.<br>Radio streams can be resumed at startup so you can quickly listen to your favorite police radio bands.<br>Police Radio 10-codes are included for quick reference so you can understand the chatter on the police radio.<br>Auto resume last police scanner radio station. Now with more scanner stations.<br><br>Top 50 Feeds (1000s more available!)<br>Chicago Police<br>LAPD - Code 3/Hot Shots, Air/K9 and Van Nuys/Valley Traffic<br>San Diego Police Dispatch<br>Bayamon and San Juan Police<br>Phoenix Police<br>Denver Police, Fire and EMS<br>City of Tulsa and Rural Police, and Fire, Tulsa County Sheriff<br>Ingham County Public Safety<br>Multnomah County Sheriff and Portland Police<br>Memphis Police and Shelby County Sheriff<br>Waterloo Regional Police<br>Newark Police<br>Amateur Repeater Los Angeles Area 147.435mhz<br>Cincinnati Police<br>Houston Police<br>Northwest Ohio Digital and MARCS<br>Fort Worth Police Dispatch<br>Sacramento County Sheriff and Sacramento City Police<br>Des Moines Metro Police<br>Sedgwick County Law Enforcement<br>Cleveland Police<br>City of Buffalo Police and Fire<br>Madison Police <br>Allen County Public Safety<br>Tucson Police and EMS<br>Minot Police, Sheriff, Fire, and EMS<br>Stockton Police<br>Modesto Police Dispatch channel 1<br>San Juan and Ponce Police, Fire and EMS<br>Black Hawk County Police, Fire, and EMS<br>Albuquerque Police and Bernalillo County Sheriff<br>Aurora Police and Fire<br>City of Pittsburgh Police, Fire, and EMS<br>Anne Arundel County Police, Fire, and EMS<br>Akron Police Department<br>Amarillo Police and Fire, Randall and Potter Counties Sheriff and Fire<br>Hunter Valley, Port Macquarie and Coffs Harbour Police<br>NYPD Special Operations Division and Traffic<br>Logan Police<br>Evansville Police and Fire Dispatch<br>Philadelphia Police - Citywide<br>Flint Police and Fire, Genesee County Fire Dispatch<br>Westmoreland County Public Safety<br>Oxnard Police<br>San Bernardino County Fire and Sheriff System 1<br>Omaha Police<br>Detroit Fire Department<br>Little Rock Police Dispatch<br>Allen County Public Safety<br>Butler County Sheriff, Police, Fire, and EMS",
    "summary": "Police Scanner X (eXperimental) is the latest Police Scanner from BEROBO Inc.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3793079,
    "score": 4.297831,
    "ratings": 39905,
    "reviews": 10690,
    "histogram": [
        2962,
        1176,
        2940,
        6757,
        26066
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "BEROBO (Police Scanner Radio)",
    "developerId": "BEROBO+(Police+Scanner+Radio)",
    "developerEmail": "policescannerx@berobo.com",
    "developerWebsite": "http://berobo.com",
    "developerAddress": "18 Romfield drive toronto ontario m3j1k1",
    "privacyPolicy": "http://berobo.com/privacy",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/2e2AE0Nq5LBK9_r2tW5IHcGebNxsjt6VFPzPG7wIoN3vBLyi3V9ij4xpQP5JuCCFuJY",
    "headerImage": "https://play-lh.googleusercontent.com/67jW6VT1Sa455YrZw_8Pki_61-0mibNozrD-FpAEoa4YOvUaWD0rMQgx6m3ZRAmySig",
    "screenshots": [
        "https://play-lh.googleusercontent.com/zgZU1Eu95zGRQrlqJQ0_S9W8pu3j8-KB5VnSwzWyiXozKZWqEmOIVHThk9-N468bJg",
        "https://play-lh.googleusercontent.com/9DGP0ucT931e7dpYmqwhLdh1j20qCtaofyapJNxaZRiHoEdfrZ9lFHMQ8cRht43xHRBu",
        "https://play-lh.googleusercontent.com/nrmMs3gW7163Yor2lZ9B5Xn4DjbuDsMpgoM1G7vYjmSUKeRtyrwC4dWk4clpfHF5HA",
        "https://play-lh.googleusercontent.com/FumBbOwB1VYFtXuHt55j9PhzgFJpLfv8LtQitPGN8ZlULzjQRuECYV9JTSOnc_DMNyc",
        "https://play-lh.googleusercontent.com/i40VoawiKZKjNN0KAW2T_1XDNSLPUGGVtu43JJY6TeR4pERBMIBos2V0XJX3KUN0uaTv",
        "https://play-lh.googleusercontent.com/mcMd1Vjq-0RcO0gWo5zjDflPqbBT_KcYDBL-xHHvWieqLgx1UeZeEs7IBnjx06oqVHQ",
        "https://play-lh.googleusercontent.com/v4UDcGIFf7E39IiFsiM6EE8H2FuYLJ5RcZE2u7FwjfB1rya_KvqHotqFfPvAnSzZMDQZ",
        "https://play-lh.googleusercontent.com/NB1_vt4YuPeoP40IgX-FVPmc59tarCuIoAGYeVWVGETezbhZQgMOMmFS-5I-84qJ6Q",
        "https://play-lh.googleusercontent.com/in7Cjnt6l4t_aSYjHB8f-Wv7q-zg9zLHkpBubzKBaij1ZFpL1N8St8g3Bo4DOIAk8w",
        "https://play-lh.googleusercontent.com/XtHQTaBRdH8eS6C1pjlVlHfOZR0HvQXRckU2KPRxvuE9Shg7ECUrwhqBRS65LZKGTzY",
        "https://play-lh.googleusercontent.com/3lrv1AI-jn62x9vvngccV0qRXkKhavRpWyH_lyrp41co_6_FnclXDKufJfAM2S3O5aHA",
        "https://play-lh.googleusercontent.com/1ZS7YR3SbgsFQYADdGcqDoqWr_SROxkYMwS7zqdebSMxZZPsTDTejI8lY4Yp8pY3gQ",
        "https://play-lh.googleusercontent.com/Lf-KnZxDG2Bj2-kRESepq-9R6VVJsw8Nw8Aik7WqQHU4cI6Zi9Kdm3t1HbiFrVW-xw",
        "https://play-lh.googleusercontent.com/hEjILIt0U8G6B4C5it02p95YAgIaRoP3-H1oISgTzvuP7UaWm5AcqLnRJ82mM8FUfZ8"
    ],
    "video": "https://www.youtube.com/embed/nH7UkZFoYEs?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/67jW6VT1Sa455YrZw_8Pki_61-0mibNozrD-FpAEoa4YOvUaWD0rMQgx6m3ZRAmySig",
    "contentRating": "Everyone 10+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jan 19, 2017",
    "lastUpdatedOn": "Aug 16, 2023",
    "updated": 1692252517,
    "version": "2.8",
    "comments": [],
    "appId": "com.berobo.police.scanner.x",
    "url": "https://play.google.com/store/apps/details?id=com.berobo.police.scanner.x&hl=en&gl=us"
}