{
    "title": "Dr. Prius / Dr. Hybrid",
    "description": "--- Important note: Please send any question to support@PriusApp.com and we will help you figuring out the issue right away, leaving one star isn't nice and really isn't a good way to communicate ---\r\n\r\nDr. Prius is an app developed to help professional Toyota/Lexus hybrid repair shop or owners to examine the health of the High Voltage battery. It turns your mobile device into a professional diagnostic equipment that usually cost thousand of dollars, it is being trusted by 439+ professional repair shops around the world.\r\n\r\nDr. Prius perform test and provides access to all the relevant battery information to quickly help identify problems with a simple touch on the screen of a smartphone, do not fall victim to bad battery, test the battery and print the certificate to prove the health of the battery system.\r\n\r\nThis app requires a ELM327 Bluetooth OBD interface to communicate with your hybrid vehicle, most of the cheap clone ELM327 will not work due to inability to switch between ECUs in your vehicle. Please visit http://PriusApp.com/obd.html for more detail or feel free to email us for any adapter compatibility question. It is generally NOT a good idea to use WiFi OBD2 adapter due to the interruption of the internet during the connection.\r\n\r\nSome useful features: \r\n\r\n1. Real-time battery monitor with clever charts and numbers.\r\n2. Life expectancy test with proprietary algorithm to find out battery remaining life.\r\n3. Full battery test to run diagnostic on battery system.\r\n4. Print or share test certificate with customer.\r\n5. Read error codes, reset error codes in a breeze.\r\n6. Disable or enable the reverse beep, seat belt beep, adjust battery fan speed and more.\r\n7. Maintenance mode to help with car diagnostic and maintenance\r\n8. Traction control on/off\r\n9. Find nearby reputable hybrid repair shop.\r\n\r\nCurrent supported model:\r\n\t1. 2020+ Prius all lineup except 4WD version\r\n\t2. 2020+ Highlander hybrid\r\n\t3. 2017-2019 Prius Prime Plug-In\r\n\t4. 2016-2019 Prius Gen4 One, Two, Two Eco, Three(Lithium) and Four(Lithium)\r\n\t5. 2012-2015 Prius Plug-In\r\n\t6. 2009-2015 Prius Gen3\r\n\t7. 2003-2009 Prius Gen2\r\n\t8. 1997-2003 Prius Gen1 (partial support)\r\n\t9. Prius V\t\r\n\t10. Auris\r\n\t11. Aqua\r\n\t12. Prius C\r\n\t13. Feilder hybrid\r\n\t14. Axio hybrid\r\n\t15. Camry Hybrid\r\n\t16. Avalon Hybrid\r\n\t17. Highlander Hybrid\r\n\t18. Lexus CT200h\r\n\t19. Lexus ES300h\r\n\t20. Lexus HS250h\r\n\t21. Lexus RX400h\r\n\t22. Lexus RX450h\r\n\t23. Lexus GS450h\r\n\t24. Lexus LS600h\r\n\t25. Lexus UX250h\r\n\t26. CHR Hybrid\r\n\t27. 2006 Estima Hybrid (partial support on Android and Amazon Fire)\r\n\t28. 2006+ Estima Hybrid (full support on Android and Amazon Fire)\t\r\n\r\nTutorial videos: https://www.youtube.com/channel/UCO7Wd_asG790GmeJdakUkjg/feed\r\n\r\nNote: Most features are free but test features require in-app purchase. Any feedback or feature request please reach out to support@PriusApp.com\r\n\r\nHow-to videos:\r\nFind the trouble battery:\r\nhttps://youtu.be/Vu0D-ImqMgo\r\n\r\nFind out remaining life of the battery - Android:\r\nhttps://youtu.be/J5sjeMnwSFw\r\n\r\nFind out remaining life of the battery - iOS:\r\nhttps://youtu.be/AhfIbLkEq8w\r\n\r\nPrivacy policy:\r\nDr. Prius App does not collect any personal information, a full privacy policy can be found here: https://priusapp.com/privacypolicy.html",
    "descriptionHTML": "--- Important note: Please send any question to support@PriusApp.com and we will help you figuring out the issue right away, leaving one star isn&#39;t nice and really isn&#39;t a good way to communicate ---<br><br>Dr. Prius is an app developed to help professional Toyota/Lexus hybrid repair shop or owners to examine the health of the High Voltage battery. It turns your mobile device into a professional diagnostic equipment that usually cost thousand of dollars, it is being trusted by 439+ professional repair shops around the world.<br><br>Dr. Prius perform test and provides access to all the relevant battery information to quickly help identify problems with a simple touch on the screen of a smartphone, do not fall victim to bad battery, test the battery and print the certificate to prove the health of the battery system.<br><br>This app requires a ELM327 Bluetooth OBD interface to communicate with your hybrid vehicle, most of the cheap clone ELM327 will not work due to inability to switch between ECUs in your vehicle. Please visit http://PriusApp.com/obd.html for more detail or feel free to email us for any adapter compatibility question. It is generally NOT a good idea to use WiFi OBD2 adapter due to the interruption of the internet during the connection.<br><br>Some useful features: <br><br>1. Real-time battery monitor with clever charts and numbers.<br>2. Life expectancy test with proprietary algorithm to find out battery remaining life.<br>3. Full battery test to run diagnostic on battery system.<br>4. Print or share test certificate with customer.<br>5. Read error codes, reset error codes in a breeze.<br>6. Disable or enable the reverse beep, seat belt beep, adjust battery fan speed and more.<br>7. Maintenance mode to help with car diagnostic and maintenance<br>8. Traction control on/off<br>9. Find nearby reputable hybrid repair shop.<br><br>Current supported model:<br>\t1. 2020+ Prius all lineup except 4WD version<br>\t2. 2020+ Highlander hybrid<br>\t3. 2017-2019 Prius Prime Plug-In<br>\t4. 2016-2019 Prius Gen4 One, Two, Two Eco, Three(Lithium) and Four(Lithium)<br>\t5. 2012-2015 Prius Plug-In<br>\t6. 2009-2015 Prius Gen3<br>\t7. 2003-2009 Prius Gen2<br>\t8. 1997-2003 Prius Gen1 (partial support)<br>\t9. Prius V\t<br>\t10. Auris<br>\t11. Aqua<br>\t12. Prius C<br>\t13. Feilder hybrid<br>\t14. Axio hybrid<br>\t15. Camry Hybrid<br>\t16. Avalon Hybrid<br>\t17. Highlander Hybrid<br>\t18. Lexus CT200h<br>\t19. Lexus ES300h<br>\t20. Lexus HS250h<br>\t21. Lexus RX400h<br>\t22. Lexus RX450h<br>\t23. Lexus GS450h<br>\t24. Lexus LS600h<br>\t25. Lexus UX250h<br>\t26. CHR Hybrid<br>\t27. 2006 Estima Hybrid (partial support on Android and Amazon Fire)<br>\t28. 2006+ Estima Hybrid (full support on Android and Amazon Fire)\t<br><br>Tutorial videos: https://www.youtube.com/channel/UCO7Wd_asG790GmeJdakUkjg/feed<br><br>Note: Most features are free but test features require in-app purchase. Any feedback or feature request please reach out to support@PriusApp.com<br><br>How-to videos:<br>Find the trouble battery:<br>https://youtu.be/Vu0D-ImqMgo<br><br>Find out remaining life of the battery - Android:<br>https://youtu.be/J5sjeMnwSFw<br><br>Find out remaining life of the battery - iOS:<br>https://youtu.be/AhfIbLkEq8w<br><br>Privacy policy:<br>Dr. Prius App does not collect any personal information, a full privacy policy can be found here: https://priusapp.com/privacypolicy.html",
    "summary": "Dr. Prius monitor and test the remaining life of your Toyota/Lexus HV battery",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 221337,
    "score": 3.03,
    "ratings": 1086,
    "reviews": 198,
    "histogram": [
        421,
        54,
        108,
        62,
        434
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$11.99 - $31.99 per item",
    "developer": "Pika Tech LLC",
    "developerId": "8556230248986697295",
    "developerEmail": "support@PriusApp.com",
    "developerWebsite": "http://PriusApp.com",
    "developerAddress": "123 N. Magnolia Ave. Monrovia, CA, 91106",
    "privacyPolicy": "https://priusapp.com/privacyPolicy.html",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/S_vHd1-_DfzgGfEP1zwHHxh0BPHHFDuDMfqCwk654w47miYyLSFn2LD3BabVzN_YbQ9v",
    "headerImage": "https://play-lh.googleusercontent.com/OxPDf0DdbM4aclJ4g4XTXIconrLjNsPotlfTUGyl8ChcpXn3jCj0aDwX7J9Btmod--4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/CkfFnkkHF3e0m9FKzdbgWXyH9dgVZ4IChBY3jbFhOku5sm4Pq7EH1iXudeLHxzPr_pA",
        "https://play-lh.googleusercontent.com/W-6k2n09qkBOWduMeS8k_n6dek_pNPd-cxOC-__bPcYHoH1JqArobogvmmlXst0-hg",
        "https://play-lh.googleusercontent.com/AmjSSYLwUrSOEPaf6dzVskpJmQTpxyfTdf3i_duLrbB7eRhFdpJJMaGW06ntW-SOqpo",
        "https://play-lh.googleusercontent.com/MzhYMcJYBBMb2BASAcBehnM4W6ob7KIUFeBXmQyakJ0yVUCgdFnDfD91TqV6TY7Ih6Q",
        "https://play-lh.googleusercontent.com/0mMn1pVzsgeWvbn1UZbkTl2W5yMiw-a_SfTx_vG1nee4Z0XCk8EmD7sftdfO62N_kMNZ",
        "https://play-lh.googleusercontent.com/9XywZW_Fh8ISXL02_jvtnubV1qqBikdD64lSJ5rMEZKu41cymVXEZFKSS1onUTT_L1s",
        "https://play-lh.googleusercontent.com/PSD--Oa1nyZKknjvoLKISBdNeez23aq7N53NudKmO9tYeKLvRTWaffzVz1s5h3l5WyE",
        "https://play-lh.googleusercontent.com/BwHhBthCpNohhLyPQR6CDNHLmxa_KypmzndjwUuttJYPcf2gzGTv3c5YO2bCKR2PiVA",
        "https://play-lh.googleusercontent.com/8P_WBccK4y_cwrUVtkVqYqloVx6O_cir2nXe5q6U9RNLR8BdyLcIR0wMTrxDZBrzgog",
        "https://play-lh.googleusercontent.com/SUggJE-95OUr7YUxHfBGZAfqsGeJ-hXT8hDwxv4CLcK7ZyQO_u2G9EDcvcKvzvUeJ2k2",
        "https://play-lh.googleusercontent.com/f4jUZdtHiHkOI4OSf2IshRsOw4JUO0EQ2C_Cthe3T8ISUul6WL5GnGDYFq72qcVnWuU",
        "https://play-lh.googleusercontent.com/iqVzidQx_LKCYIgUcmuxJFQIhw_Z7FJleg4etHIbSMZRGnraJEFeBhIGVOBWrCMami0V",
        "https://play-lh.googleusercontent.com/GgB8vP2-KSBYmIxWXVqsoLAXe-uCTV5KjZV6CFgY1Td__7O8Gmh5Xl88CTVTXuNohJs",
        "https://play-lh.googleusercontent.com/H4I-Pucg-qBqO87-orzGzkvt2MpHRwDWJR_N8GTG8BfQr2B8KJ-6SEsz_xMkVO72DG0",
        "https://play-lh.googleusercontent.com/qKXl-HNN2P9UTILEF6vvhR67f6-lcmaNTVlqw2bUZLmzvOGehE2R5aa2HHiEA5cZBrbK",
        "https://play-lh.googleusercontent.com/5HA3kFfI1MfeTtfmdVzfMuz4YAXe5oPG2XoXR11YU1jPjJoYgjfE1r1z5TBE2DG3boA",
        "https://play-lh.googleusercontent.com/i1PwkP2pGBd7RJGrGrXKF1wzkyr8RhEbq2ycaONGUrVhbjyrdt-2vlBUXD8ygewexV8",
        "https://play-lh.googleusercontent.com/fqwx-gvSTk3xzEt3jghwuWnKlOwUXO3RNbfDURHLomQMp4qmlh9Ia2RVyfAMBNUeIc14",
        "https://play-lh.googleusercontent.com/G4bhQX2isfOi9gYZyxF-1afcKlo1dYg7kUe4WbggHpUk-tDelAOsjuVHY5K8CZ644-U",
        "https://play-lh.googleusercontent.com/we_c5z88yAjUIZ2MxiBY3mKeSjGXRKQHiQYFi2sNXtUtRoyjnD1n0iyWwCwDQcqGM7L9",
        "https://play-lh.googleusercontent.com/vgbcQ07qR0_f3kpOoNmXaDlQv6kPp4gFiw4uOOJilQ8uldqtTeI11huvNjHA08RC-A",
        "https://play-lh.googleusercontent.com/9sY-NlVgCNOPy_Z_P47EcM3WahR_XPCyT59bNpVSbSopG7iP3shEVq6TxkI0LdzFWA",
        "https://play-lh.googleusercontent.com/SojnMYcjHxqOAQU6kAz3ya_BZt4pHKU3pB92wFqGzdknFa-iJWKva7mGojqaeAX220Q",
        "https://play-lh.googleusercontent.com/iytpFcgqV136u_Eud_TaP4p3GFhfQ97BK3DsL5CNTldulXyJE7Pf0PcMewyxpCx7dQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 10, 2017",
    "lastUpdatedOn": "Oct 13, 2024",
    "updated": 1728873970,
    "version": "6.45",
    "comments": [],
    "appId": "com.nexcell.app",
    "url": "https://play.google.com/store/apps/details?id=com.nexcell.app&hl=en&gl=us"
}