{
    "title": "PrettyLittleThing",
    "description": "Need your fashion fix on the move? Shop on the PrettyLittleThing app for the latest in affordable women\u2019s fashion looks that are sure to have you racking up all the likes on the \u2018Gram.\r\nWhen it comes to women\u2019s clothing, we\u2019ve got you covered with the latest on-trend styles hitting the site daily. Shop the Summer styles you need from the jumpsuits and rompers you can dress up or down, the two piece sets you can mix and match or add to bag your fave pair of jeans for those easy weekend wins.Inclusivity is our thing which is why our ranges PLT Plus, Shape, Tall, Petite, Premium and Maternity have your back to cater to #EveryBodyInPLT. \u2018Cos we know style has no limits. Simply download and start shopping for your 'drobe of dreams with affordable women\u2019s fashion at your fingertips.\r\nWish List - Don\u2019t have time to shop right now? Use our Wish List feature to add save those PLT pieces you\u2019ve been going heart-eyed over for later.\r\n- Exclusive offers \u2013 As an app member you\u2019ll be the first to know about our exclusive offers.\r\n- Fast and secure checkout \u2013 Looking to update your style? Get your Pretty Little Thing clothing fast with express shipping.\r\n- Track your order \u2013 Global delivery tracked straight from checkout to your door.\r\n- Easy returns \u2013 Shopping made easy with fuss-free returns, no questions asked.\r\n- Try Before You Pay - Our Buy Now Pay Later partners allow you to shop on your own terms.\r\n- New styles added daily \u2013 Need a new dress for the weekend? We have hundreds of new women\u2019s clothes landing on site daily.\r\n- Stay in the know \u2013 As an app member you'll get notifications on our latest collections before anyone else.\r\n- Pay easily, safely and securely with Apple Pay.\r\n\r\nWhatever your shopping needs, we\u2019ve got you covered 24/7 with the affordable women\u2019s fashion you need.",
    "descriptionHTML": "Need your fashion fix on the move? Shop on the PrettyLittleThing app for the latest in affordable women\u2019s fashion looks that are sure to have you racking up all the likes on the \u2018Gram.<br>When it comes to women\u2019s clothing, we\u2019ve got you covered with the latest on-trend styles hitting the site daily. Shop the Summer styles you need from the jumpsuits and rompers you can dress up or down, the two piece sets you can mix and match or add to bag your fave pair of jeans for those easy weekend wins.Inclusivity is our thing which is why our ranges PLT Plus, Shape, Tall, Petite, Premium and Maternity have your back to cater to #EveryBodyInPLT. \u2018Cos we know style has no limits. Simply download and start shopping for your &#39;drobe of dreams with affordable women\u2019s fashion at your fingertips.<br>Wish List - Don\u2019t have time to shop right now? Use our Wish List feature to add save those PLT pieces you\u2019ve been going heart-eyed over for later.<br>- Exclusive offers \u2013 As an app member you\u2019ll be the first to know about our exclusive offers.<br>- Fast and secure checkout \u2013 Looking to update your style? Get your Pretty Little Thing clothing fast with express shipping.<br>- Track your order \u2013 Global delivery tracked straight from checkout to your door.<br>- Easy returns \u2013 Shopping made easy with fuss-free returns, no questions asked.<br>- Try Before You Pay - Our Buy Now Pay Later partners allow you to shop on your own terms.<br>- New styles added daily \u2013 Need a new dress for the weekend? We have hundreds of new women\u2019s clothes landing on site daily.<br>- Stay in the know \u2013 As an app member you&#39;ll get notifications on our latest collections before anyone else.<br>- Pay easily, safely and securely with Apple Pay.<br><br>Whatever your shopping needs, we\u2019ve got you covered 24/7 with the affordable women\u2019s fashion you need.",
    "summary": "Shop this season's latest fashion & women's clothes online at PrettyLittleThing.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4859348,
    "score": 3.8741722,
    "ratings": 6909,
    "reviews": 469,
    "histogram": [
        1097,
        685,
        365,
        594,
        4160
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "PrettyLittleThing.com Limited",
    "developerId": "PrettyLittleThing.com+Limited",
    "developerEmail": "AndroidApp@Prettylittlething.com",
    "developerWebsite": "https://www.prettylittlething.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.prettylittlething.com/privacy-policy",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/rYDXECQcgQKr8FrmCWsSqb-n_d8Fcgn8i5E07HoqlR1NoHlAlH5sDOrKYMzwKcSfpw",
    "headerImage": "https://play-lh.googleusercontent.com/rT4UsBbhpk4k9W7dOb31oaY7mcb2BdjK8JF9PM3ad6A_XfzO-Ts8zcK2tWaKzvvD5ZQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/87AWLUd2kZu6KPTek4m792Oi33R6VesFfXDkOn1LVJOpltL5T1cV7l5GyDY3poKq0ZY",
        "https://play-lh.googleusercontent.com/DcvaJC5Ak6-arOrx2RSGrq-hFmstwCDEjJ3qWh0-qcVmExywOJYqNOiAXrHmLWumVw",
        "https://play-lh.googleusercontent.com/0P-apIRjLq4nKC2xCYn3oWhXsb5-DB5ASrXvAtL061k_Bz5LW86R2TY77gZdzNBAH7A",
        "https://play-lh.googleusercontent.com/kGH4sYKxzbBWEUMV5FIhEDkOWiq8K5A4X9-HMge6TQba3Rv5BOZZGmdUmEQViKnzV4I",
        "https://play-lh.googleusercontent.com/bLv1g62ZhjpKn94j6ql0ETb2D9YlJk_EJ8hDaPQd3REa1TguwaAUidJ6czDtuYxMQPQ",
        "https://play-lh.googleusercontent.com/CPo9ZK8CtTJdLF4fil2R69lmqozZpCDxtvz5ZE1MF_tEGthry6VTXuBWHTm8excbIP4",
        "https://play-lh.googleusercontent.com/r0RtR0K_uj6IPWpAOuzdxQEsQFOqMnzL0eNj5sismrJa6zPLrlMEkRLAOu9oEyfLMA",
        "https://play-lh.googleusercontent.com/NprITGHaxDRi7O4dRL-YnSFbIdimFAPSH3M8HfCHDnRHrl7ixfpjmdjQrtSmD7LijmwB",
        "https://play-lh.googleusercontent.com/LQbnm4jtTuM1Vv0pCj55LIFPj2jjsRFlb40FFRGMyU0k8X_HLGWmYGC0QZZwUBIeTgU",
        "https://play-lh.googleusercontent.com/vedxm7u3-eAD-ZtsdR_1R6DzjL7JE_NzRSKGlTLvNexveuNu49kI9QMsyPe-GmrvVt-k",
        "https://play-lh.googleusercontent.com/UypSZfdrYo08cdq46Wi1C_wcK5gnyObPWcps-RpTgQSuZgAoMB5Dll70AbH3KLgKCbk",
        "https://play-lh.googleusercontent.com/gwgeKdIzJfIZsSwDoqHRoKZgh55MP_Zll9Mc1zDtKnmO1tmEHdIrYMTu4l90ZoYQeDo",
        "https://play-lh.googleusercontent.com/OoCNM47fVR6RAAT0PPuYnWO_7xXLcVG6oADC_zINtpUX2NrBzSvOlgwJZSmUOEj_feYs",
        "https://play-lh.googleusercontent.com/47LtA_TQRhl6e0L-k_5CZsE1Z62A40xr5Uhq-pmK6ZW7dE8YaJBvZ1L6djODct87Yb4",
        "https://play-lh.googleusercontent.com/7ejVellZAj2x1DZesc1CfkQ52UVzlIjH9MFKqrb-BBxTkkAo-BnbnVXYo_j206Wfvgs",
        "https://play-lh.googleusercontent.com/9KryVH0ppMl7MYcpLRXumHdG018xJGJSW5a8A_kGCsG62WfIWWK6FqyCVn3WKe26Zkgu",
        "https://play-lh.googleusercontent.com/ySxFz085ikaJBENASZ6_LwiOyAqFgdH-biWrszyVlWxrPGm8dRR67s_KBnwhV_YUVlM",
        "https://play-lh.googleusercontent.com/HGPOE9F4KvV-FxMFkXlH7tAnibYj9jaZEWoMefYHUKKisgc_CShW6B3BdYvZPesySvk"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 23, 2017",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729532586,
    "version": "72.3.0",
    "comments": [],
    "appId": "com.poqstudio.app.platform.plt",
    "url": "https://play.google.com/store/apps/details?id=com.poqstudio.app.platform.plt&hl=en&gl=us"
}