{
    "title": "Litmatch\u2014Make new friends",
    "description": "Litmatch is all about meeting new friends and beyond. \r\n\r\nLitmatch is a safe and warm community to share your honest thoughts and feelings. You can always encounter cool and caring people in Litmatch. People here can experience emotional communication comfortably through different online interactive features. Most of our users have become friends by taking the first moves inspired by Litmatch's impressive features.\r\n\r\n\ud83d\udcac  Meet New Friends in 1 Click\r\nLitmatch empowers your encounter with a new friend. Whatever it is about 1-to-1 talk or group chatting, you can always find a place that suits you.\r\n\r\n\ud83d\udcf7  Feel Comfortable to Share All Your Emotions\r\nJoin the conversations and share your honest thoughts and feelings. Whether they are ups or downs, there are always Litmatch pals who can deeply relate to your stories.\r\n\r\n\ud83c\udf08 Litmatch Community- We respect diversity and appreciate differences.\r\nLitmatch cherishes warm, safe, and good vibes. And that's why we always promise you a community where people respect love, embrace differences, and communicate with no pressure. We do not tolerate any inappropriate behaviors or rudeness. \r\n\r\n\r\n\u2728\u2728 \u2728   DISCOVER OUR AMAZING FEATURES \u2728 \u2728 \u2728 \r\n\r\n\r\n\ud83d\udcac  SOUL GAME- TEXT, LIKE, CONNECT!\r\nKnow your new friends with text conversation in real-time.\r\nCreate a new connection once both of you have liked each other.\r\n\r\n\ud83c\udf99 VOICE GAME- STAND OUT BY YOUR VOICE!\r\nHave a brief voice call to know each other better.\r\n\r\n \ud83e\udd73  PARTY CHAT- GROUP CHATTING & GIFTS!\r\nShare your talents and thoughts on the mic in a party room.\r\nReceive warm support and interesting gifts from other people.\r\n\r\n \ud83d\udc40  FEED -  EXPLORE LIVES AROUND THE WORLD!\r\nExplore people's lives from their texts, visuals, or even voice!\r\nShare everything from your daily moments to life's highlights. \r\n\r\n\ud83d\udc36  AVATAR- CREATIVITY & IDENTITY\r\nCustomize a cool or cute avatar to stand out from the crowds, to show your personality or taste or even, to present the connection between you and others!\r\n\r\n\r\n\u2728 \u2728 \u2728 JOIN Litmatch NOW TO EXPLORE MORE SURPRISES \u2728 \u2728 \u2728 \r\n\r\n\r\nLitmatch is free to download and use. However, we also offer an optional subscription package ( \ud83d\udc51Litmatch VIP Membership \ud83d\udc51 ) and non-subscription, single and multi-use Litmatch-currency: DIAMOND. The price varies by country and may change without notice, but you can always see the exact price in the app. \r\n\r\nWe appreciate your feedback and suggestions, please contact us if you have any thoughts: lit@litatom.com",
    "descriptionHTML": "Litmatch is all about meeting new friends and beyond. <br><br>Litmatch is a safe and warm community to share your honest thoughts and feelings. You can always encounter cool and caring people in Litmatch. People here can experience emotional communication comfortably through different online interactive features. Most of our users have become friends by taking the first moves inspired by Litmatch&#39;s impressive features.<br><br>\ud83d\udcac  Meet New Friends in 1 Click<br>Litmatch empowers your encounter with a new friend. Whatever it is about 1-to-1 talk or group chatting, you can always find a place that suits you.<br><br>\ud83d\udcf7  Feel Comfortable to Share All Your Emotions<br>Join the conversations and share your honest thoughts and feelings. Whether they are ups or downs, there are always Litmatch pals who can deeply relate to your stories.<br><br>\ud83c\udf08 Litmatch Community- We respect diversity and appreciate differences.<br>Litmatch cherishes warm, safe, and good vibes. And that&#39;s why we always promise you a community where people respect love, embrace differences, and communicate with no pressure. We do not tolerate any inappropriate behaviors or rudeness. <br><br><br>\u2728\u2728 \u2728   DISCOVER OUR AMAZING FEATURES \u2728 \u2728 \u2728 <br><br><br>\ud83d\udcac  SOUL GAME- TEXT, LIKE, CONNECT!<br>Know your new friends with text conversation in real-time.<br>Create a new connection once both of you have liked each other.<br><br>\ud83c\udf99 VOICE GAME- STAND OUT BY YOUR VOICE!<br>Have a brief voice call to know each other better.<br><br> \ud83e\udd73  PARTY CHAT- GROUP CHATTING &amp; GIFTS!<br>Share your talents and thoughts on the mic in a party room.<br>Receive warm support and interesting gifts from other people.<br><br> \ud83d\udc40  FEED -  EXPLORE LIVES AROUND THE WORLD!<br>Explore people&#39;s lives from their texts, visuals, or even voice!<br>Share everything from your daily moments to life&#39;s highlights. <br><br>\ud83d\udc36  AVATAR- CREATIVITY &amp; IDENTITY<br>Customize a cool or cute avatar to stand out from the crowds, to show your personality or taste or even, to present the connection between you and others!<br><br><br>\u2728 \u2728 \u2728 JOIN Litmatch NOW TO EXPLORE MORE SURPRISES \u2728 \u2728 \u2728 <br><br><br>Litmatch is free to download and use. However, we also offer an optional subscription package ( \ud83d\udc51Litmatch VIP Membership \ud83d\udc51 ) and non-subscription, single and multi-use Litmatch-currency: DIAMOND. The price varies by country and may change without notice, but you can always see the exact price in the app. <br><br>We appreciate your feedback and suggestions, please contact us if you have any thoughts: lit@litatom.com",
    "summary": "Join the Community & Go Fun with Cool Generation!",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 127694499,
    "score": 3.9054728,
    "ratings": 1034945,
    "reviews": 1552,
    "histogram": [
        213433,
        33252,
        46140,
        84806,
        656281
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.13 - $254.99 per item",
    "developer": "CONSTRUCT TECHNOLOGY",
    "developerId": "CONSTRUCT+TECHNOLOGY",
    "developerEmail": "lit@litatom.com",
    "developerWebsite": "https://www.litmatchapp.com/#/",
    "developerAddress": null,
    "privacyPolicy": "https://www.litmatchapp.com/#/privacy-policy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/a2HLOHpXniFGGEOxr6fcAkhmjQTT_r9IK2p23c9RDdvJAioZrSsyIwBdaxqRF7qScW0",
    "headerImage": "https://play-lh.googleusercontent.com/FYsuqYhR79liHKiEGCO41iGiXkSUkI7XeAL7GUC080_TYjJSmObjrz2_s7CpgMkHuAg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ztkGCactin2LT21iR9yPrxtwvqAdZ_62UUf9mGgIVMvNmKdsP_TIdno1nw34F7wM9w",
        "https://play-lh.googleusercontent.com/sj_x2ZdWDaMbCb8rq1yATAlTSFNzvLiJAoV2v4ATslrhW0jjVdBGOsgxcZQe37e-xw",
        "https://play-lh.googleusercontent.com/TsLXPbQOwJtA0QldNMNPKsuVxu_ZoFt6wnsnAsKhv8uersbzakcmPwlWcNoMEi_ZoWc",
        "https://play-lh.googleusercontent.com/fI0bCJi55Co75fUoQeBAzbPRivSU09jF-XzYnvWbekG4qxRlZVdDIdoiRlPdiy-943E",
        "https://play-lh.googleusercontent.com/swmWL0AnmcuMWEGiQUAGUSDMzZbJ9dz4DB4hcwAyd6rtZ3624U4kURtTszZI43y4NfI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 29, 2019",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729497230,
    "version": "6.88.5",
    "comments": [],
    "appId": "com.litatom.app",
    "url": "https://play.google.com/store/apps/details?id=com.litatom.app&hl=en&gl=us"
}