{
    "title": "BLW Meals: How to Start Solids",
    "description": "What parents are saying:\r\n\r\nBikabeau - \u2b50\u2b50\u2b50\u2b50\u2b50\r\nThe MOST complete BLW guide!\r\nI found this app amazing! I'm a FTM and confused about how to start BLW. What I love about this app is the approach and the clear guide inside. It gives you TONS of guides, tips, how to serve, great recipes, and useful info that another BLW app didn't give. I am super confident now practicing BLW with my baby!\r\n\r\nTrinaC123 - \u2b50\u2b50\u2b50\u2b50\u2b50\r\nAmazing and helpful app\r\nI just have to say how much I love and appreciate this app! Starting solids with my first baby was so overwhelming and I found this app when he was about 7.5 months old (he\u2019s almost 9 months now). And I am so much more confident feeding him now and love all the meal ideas and recipes and suggestions for food preparations. I have recommended the app to all my mommy friends!\r\n\r\nRjccg - \u2b50\u2b50\u2b50\u2b50\u2b50 \r\nYou need this app! \r\n\u201cFirst time parent here- I find that figuring out what to feed my daughter has been one of the most challenging parts of parenthood!! But this app is super simple as a resource for food ideas or to help guide you through the whole process of introducing solids. Literally anytime I have a question about food and my baby- I turn to this app! Well done :)\u201d\r\n\r\nTamara Katic - \u2b50\u2b50\u2b50\u2b50\u2b50 \r\n\u201cThis app is a huge help when starting solids with your baby! Amazing recipes, easy ideas that save you lots of time. I was having so much anxiety for months, going back to BLW and then giving up again, but the app is a lifesaver, especially combined with Instagram accounts (both for babies and toddlers). The team is amazing, always ready to reply to any questions, no judging and showing that their kids can be difficult as ours \ud83d\ude02 Thank you Leah, Bri and Emma (and the little ones) \u2764\ufe0f\u201d\r\n\r\n\r\n\u2014--\r\n\r\n\ud83d\udca1 Don't forget to follow us on Instagram @BLWMealsApp \r\n\r\n\u2014--\r\n\r\n\ud83c\udf53 This is your chance to confidently start solids with your baby. Learn how to safely prepare and offer a variety of foods to your baby.\r\n\r\n\ud83d\udeab Our app is entirely ad-free with no random product promotions. Download it for free!\r\n\r\nIn this app you will find:\r\n\r\n\u27a1 A detailed weaning guide for each age with how to start and navigate Baby-led Weaning from 6 to 24 months along with guidance for allergen introduction.\r\n\r\n\u27a1 A baby food library with photos, videos, and tips on how to cut and prepare food safely for your baby to offer as finger foods or with responsive spoon-feeding. Integrated note feature for recording baby\u2019s favorite foods, making shopping lists, jotting questions for your pediatrician and much more\u2026\r\n\r\n\u27a1 Baby Cookbook: delicious, quick, and easy to make recipes\r\n\r\n\u2022 550+ recipes made by nutritionists and board-certified dietitians\r\n\u2022 450+ Vegetarian and 200+ vegan recipes\r\n\u2022 Use our filters to find exactly what you\u2019re looking for\r\n\u2022 Search for specific ingredients, save your favorites, put them in folders and make notes!\r\n\r\n\u27a1 Baby Meals: Monthly meal plans (with  a vegetarian option) for all ages (6 months and up), made by board-certified dietitians\r\n\r\n\u27a1 Foods Checklist (Tracker): baby's first foods checklist\r\n\u2022 Track your baby\u2019s first foods and take notes\r\n\u2022 Ideal for keeping track of the top allergens introduced\r\n\r\n\u27a1 Quiz\r\n\r\n\u2022 Fun quizzes you can find in the Guides by Age to test your knowledge and keep you learning about feeding your baby\r\n\r\nFor any questions, message us on Instagram @BlwMealsApp or send an e-mail to hi@kidsmealsapp.com.\r\n\r\n\u00bfHablas espa\u00f1ol? \u00a1Prueba nuestra aplicaci\u00f3n BLW Ideas con men\u00fas y recetas locales!\r\n\r\nTerms of Use and Privacy Policy: https://learn.appdocumentation.com/en/collections/1618556-terms-conditions-and-privacy-policy",
    "descriptionHTML": "What parents are saying:<br><br>Bikabeau - \u2b50\u2b50\u2b50\u2b50\u2b50<br>The MOST complete BLW guide!<br>I found this app amazing! I&#39;m a FTM and confused about how to start BLW. What I love about this app is the approach and the clear guide inside. It gives you TONS of guides, tips, how to serve, great recipes, and useful info that another BLW app didn&#39;t give. I am super confident now practicing BLW with my baby!<br><br>TrinaC123 - \u2b50\u2b50\u2b50\u2b50\u2b50<br>Amazing and helpful app<br>I just have to say how much I love and appreciate this app! Starting solids with my first baby was so overwhelming and I found this app when he was about 7.5 months old (he\u2019s almost 9 months now). And I am so much more confident feeding him now and love all the meal ideas and recipes and suggestions for food preparations. I have recommended the app to all my mommy friends!<br><br>Rjccg - \u2b50\u2b50\u2b50\u2b50\u2b50 <br>You need this app! <br>\u201cFirst time parent here- I find that figuring out what to feed my daughter has been one of the most challenging parts of parenthood!! But this app is super simple as a resource for food ideas or to help guide you through the whole process of introducing solids. Literally anytime I have a question about food and my baby- I turn to this app! Well done :)\u201d<br><br>Tamara Katic - \u2b50\u2b50\u2b50\u2b50\u2b50 <br>\u201cThis app is a huge help when starting solids with your baby! Amazing recipes, easy ideas that save you lots of time. I was having so much anxiety for months, going back to BLW and then giving up again, but the app is a lifesaver, especially combined with Instagram accounts (both for babies and toddlers). The team is amazing, always ready to reply to any questions, no judging and showing that their kids can be difficult as ours \ud83d\ude02 Thank you Leah, Bri and Emma (and the little ones) \u2764\ufe0f\u201d<br><br><br>\u2014--<br><br>\ud83d\udca1 Don&#39;t forget to follow us on Instagram @BLWMealsApp <br><br>\u2014--<br><br>\ud83c\udf53 This is your chance to confidently start solids with your baby. Learn how to safely prepare and offer a variety of foods to your baby.<br><br>\ud83d\udeab Our app is entirely ad-free with no random product promotions. Download it for free!<br><br>In this app you will find:<br><br>\u27a1 A detailed weaning guide for each age with how to start and navigate Baby-led Weaning from 6 to 24 months along with guidance for allergen introduction.<br><br>\u27a1 A baby food library with photos, videos, and tips on how to cut and prepare food safely for your baby to offer as finger foods or with responsive spoon-feeding. Integrated note feature for recording baby\u2019s favorite foods, making shopping lists, jotting questions for your pediatrician and much more\u2026<br><br>\u27a1 Baby Cookbook: delicious, quick, and easy to make recipes<br><br>\u2022 550+ recipes made by nutritionists and board-certified dietitians<br>\u2022 450+ Vegetarian and 200+ vegan recipes<br>\u2022 Use our filters to find exactly what you\u2019re looking for<br>\u2022 Search for specific ingredients, save your favorites, put them in folders and make notes!<br><br>\u27a1 Baby Meals: Monthly meal plans (with  a vegetarian option) for all ages (6 months and up), made by board-certified dietitians<br><br>\u27a1 Foods Checklist (Tracker): baby&#39;s first foods checklist<br>\u2022 Track your baby\u2019s first foods and take notes<br>\u2022 Ideal for keeping track of the top allergens introduced<br><br>\u27a1 Quiz<br><br>\u2022 Fun quizzes you can find in the Guides by Age to test your knowledge and keep you learning about feeding your baby<br><br>For any questions, message us on Instagram @BlwMealsApp or send an e-mail to hi@kidsmealsapp.com.<br><br>\u00bfHablas espa\u00f1ol? \u00a1Prueba nuestra aplicaci\u00f3n BLW Ideas con men\u00fas y recetas locales!<br><br>Terms of Use and Privacy Policy: https://learn.appdocumentation.com/en/collections/1618556-terms-conditions-and-privacy-policy",
    "summary": "The ultimate guide to help you wean baby with 550+ recipes, meals & more.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 160261,
    "score": 3.2857144,
    "ratings": 333,
    "reviews": 55,
    "histogram": [
        113,
        21,
        14,
        21,
        161
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $34.99 per item",
    "developer": "BLW SOCIAL",
    "developerId": "BLW+SOCIAL",
    "developerEmail": "leah@blwmeals.com",
    "developerWebsite": "https://www.blwmeals.com/",
    "developerAddress": "112 Kim Seng Road, #22-01\nSingapore, 239432",
    "privacyPolicy": "https://drive.google.com/drive/folders/1ChNLYv7QMIujc8Q2FYFy51YS1iJy9RPY?usp=sharing",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/SxkE1nUAVdgTauI1TjqlPxtUbAY3POub_3mE-Wl7gEMLHMhlTpHUEt4rxUiHZdz3tBA",
    "headerImage": "https://play-lh.googleusercontent.com/XNuGjKhHhQbSRyHYNct9MJbjM85Z-egOqwMHRQlX9yd-sTbR9sZVvpUTSwlMle4HYQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/0_ZhKy1HZ1Voz1OGfHX6ZPPJS2I3p63Rt7mn3xEFeEoZG03Yd49uOqRkCM2hYXpKLg",
        "https://play-lh.googleusercontent.com/U3sgNXMlONVUxwPhvnY0rAxBkIL5JhXI80P_a1pglAnqiw2hqinl04kpefxUD1hdTA",
        "https://play-lh.googleusercontent.com/pM3WyhOiFhKvgfRvUSjSyFaRW_9otZXrLvN0Raeo8v4KyL1Q4Ri0RbPt33dHdwv3OA",
        "https://play-lh.googleusercontent.com/IY95RclY8yOpCqx9CTbF0NO-WZSvLVwycBEE0mks0OQS8QhWnZjIpX7wOJuDWz6TRyA",
        "https://play-lh.googleusercontent.com/pG8MHr3kNbKJBRvYKOJFVYK-Lg5ANjeZ2jgX2xyaEP-5V-IVh3hveG1mkmvfljSEj_oH",
        "https://play-lh.googleusercontent.com/juMHio_vIrcAHBCne9lPuHD3D8WVVmcitaxqh8YVWw3jiVmqsREjtoZGhCINBERCTQ",
        "https://play-lh.googleusercontent.com/3k1DpVrpBZeNqvsAlhDp8hMtpY4QYN4gXAebnTHmsBj3r0IaBSDZwioSBPycbbdvggw",
        "https://play-lh.googleusercontent.com/UTvz37KDok_AdRHND_WR5HJBni2eoJZbXXpe5Zy4iZrT7JbuI6fo6UcLUwSY_q1Z8pMj",
        "https://play-lh.googleusercontent.com/VM2fPuIyrAKLiR04nl3vFG6ZSXqAF5mcMJCtRBhoF3ERwfw2xk3Bkpo-kfy4-Iov28U",
        "https://play-lh.googleusercontent.com/XFm72P3NJQ12RsUMv0wtnvM1nAIvXfHsZPpXeIXh0FxXKK2vjUlAp592BPRoeoEfmDQ",
        "https://play-lh.googleusercontent.com/k1ZwcAp0JhzyUlA-b0TELdvufycB55zYDCM6r8ZZRMLcrN30CQzdhPY-Mw36gGrcshY",
        "https://play-lh.googleusercontent.com/ahjMsL01L173dv3p4KLHIhGhV4qXBQbW3hyQxX9IthP8tWK-pu0PA6Zkv40kyp9urMs",
        "https://play-lh.googleusercontent.com/dcNxIgxoZpTepriSJ9P3_qXhi5b2wLO7K20kjn4mureIf4PFet6_ulEdcrd_uyPN5nM",
        "https://play-lh.googleusercontent.com/JGk1zAbYCXuD3Q8CzKAB4kr37dOHAR3GDNdg5yxwhHJQnER6olZ-SBKps1wb6wc-V_U",
        "https://play-lh.googleusercontent.com/JVuiPvc5mhH3XA5vNrJOTacod0oR7lEHNQMy4G51q-49wycKp4p7uF0qEF-73jOIta0",
        "https://play-lh.googleusercontent.com/_PeQaKlyh1sIXlBK8feNT8eOYzdLUXD3qxFRhBRUyAgZ_wrs-AY-aZtHzwyGdNZY7jk",
        "https://play-lh.googleusercontent.com/WvAgH7y0fr5Tq5Oc7S4vXDhFqPDPG6GDIcLfn771LSv-P7q1Rh-NSTvPYAAWobi44WY",
        "https://play-lh.googleusercontent.com/VIe4xUeOQB30xWalYXDNl-PE3f8lSnSYlegmgseO9EPV0lSUb-Iq3xsreXLCVFB9fzQ",
        "https://play-lh.googleusercontent.com/uvJgJlP3c4wsNuJ-oacgM13bkg8bO0-7XMVOVxa6fyIWK1S4ghjQjjiPnnVtD3K0FxM",
        "https://play-lh.googleusercontent.com/Sg2azPtEeB81OoT2TrnWYPv2IaNngNBo4Eo5lpE21_s6hmOj-LVoTF_fJhzGcAhYwo02",
        "https://play-lh.googleusercontent.com/kI4GPDheXJwiDzx6xXSr6z7iH7q_fXZq0BKykHZKY5J5p6Wv_m09PZNtJHl9LaTbMLg",
        "https://play-lh.googleusercontent.com/8FYuvqXUuWrywhj__M0lzNGqiIytfUX2tstR_jO055brDS3O5HxCS3hYoY90XE1Nkzz0",
        "https://play-lh.googleusercontent.com/dXnVJvzF8mqfy_O35yVoFdp2s1j8yVhsWcYowYujIsXlYjtNxYhS_P05vCMZgYT31A",
        "https://play-lh.googleusercontent.com/jL3Q8rF_SiKdppDkgbiriPgYXK9SM_6zN1fYlp8Fbkj9zKTXOihIxB_RGW2NooYld_0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 16, 2020",
    "lastUpdatedOn": "Aug 6, 2024",
    "updated": 1722962278,
    "version": "1.0.151",
    "comments": [],
    "appId": "com.n51951dd8177.app",
    "url": "https://play.google.com/store/apps/details?id=com.n51951dd8177.app&hl=en&gl=us"
}