{
    "title": "Kido Protect Parental Control",
    "description": "Kido parental control and screen time tracker is a secure parental control app that makes it easy for parents to control screen time, track their child's location, block apps, and monitor app usage.\r\nKido Protect is an app to keep your <b>kids safe</b> and healthy in physical and online world.\r\n\r\n<b>Best Parental Control App</b> for all families. Monitor screen time on your child\u2019s device. Address digital wellbeing, monitor app, web activities & lock apps with ease.\r\nOur Kido Parental Control app includes a range of tools for monitoring and regulating screen time to help parents manage their kids and teens phone use in line with their desired parenting style:\r\nThis is recommended for people worried about things such as:\r\n\u2022 Is my child spending too much time playing games?\r\n\u2022 What kind of games is my child playing?\r\n\u2022 Are the games my child is playing age-appropriate?\r\n\u2022 Is my child is at safe place? SOS alerts provide a quick alert system in case of an emergency!\r\n\r\nSuper exciting\ud83d\udca5 features of Kido Parental Control App:\r\n\r\n<b>\u2714 Screen Time Monitoring</b>\r\nSet a play-time limit and the console will notify users that the time limit has been reached.\r\nParents and guardians can check the Kido Protect Parental Controls app to see if the time limit has been followed. It is also possible to suspend gameplay automatically when the play-time limit is reached.\r\n\r\n<b>\u2714 Apps and Games Monitoring</b>\r\nBlock or restrict specific inappropriate installed apps and other apps. Set a schedule for the time your children can access certain apps. You can also set exactly how much screen time they use on certain apps every day. Send an instant alert when your children try to open blocked apps or games. Some common examples of monitoring e.g. YouTube monitoring, social media app monitoring.\r\n\r\n<b>\u2714 Web Monitoring</b>\r\nHave complete control over the internet activities of your kids. We offer full parental tracking system that allows you to see apps usage web surfing and sites visited and much more. This can help you to make their choices better and safer.\r\nTo ensure the filtering and blocking of undesirable browser content on your child's device, the App utilizes a VPN service. This service enables the app to monitor and manage the online activities on the device\r\n\r\n<b>\u2714 Social Media Monitoring</b>\r\nDeep and comprehensive monitoring social app activities allows you to monitor kid\u2019s online activities. Monitor social media apps notifications, such as WhatsApp, Line, and Facebook Messenger, to stop cyberbullying and online fraud timely\r\n\r\n<b>\u2714 Location and Geo Fencing</b>\r\nWorried about your children location? Now get your child location via family GPS tracking. Get notifications when your child enters or leaves geo-fenced zones you set. See location history and find your kids. Kido free Parental Control app 2023 gives you full variety of family safe tools you can use to safe your family or kids from any uncertain situations. This way your family link with you all the time. This is kind of family locator tool to assure safety of your family.\r\n\r\n<b>\u2714 Nudity Monitoring or Content Blocking</b>\r\nKeep your children away from age-restricted games and content. Lock safe search on search engine for more filtered content.\r\nReal time reporting, rich list of useful features (screen time, apps monitoring, social media monitoring, internet and web filtering, location and geofencing, SOS, task management, YouTube monitoring, and more...), with a full control of your child's devices.\r\n\r\nThe Accessibility API will allow the Kido Protect app to view and control the screens of your child's devices. It helps to parent, that can detect what child is doing the activity on his/her devices.\r\n\r\nBe more assured about your child's safety and well-being on the internet.\r\nTheir safety and well-being is our goal. So why not Kido Protect Parental Control App?\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66\r\n\r\nRead our full Terms of Service\r\nhttps://www.kidoprotect.com/terms-and-conditions/\r\nand our Privacy Policy at\r\nhttps://www.kidoprotect.com/privacy-policy/",
    "descriptionHTML": "Kido parental control and screen time tracker is a secure parental control app that makes it easy for parents to control screen time, track their child&#39;s location, block apps, and monitor app usage.<br>Kido Protect is an app to keep your <b>kids safe</b> and healthy in physical and online world.<br><br><b>Best Parental Control App</b> for all families. Monitor screen time on your child\u2019s device. Address digital wellbeing, monitor app, web activities &amp; lock apps with ease.<br>Our Kido Parental Control app includes a range of tools for monitoring and regulating screen time to help parents manage their kids and teens phone use in line with their desired parenting style:<br>This is recommended for people worried about things such as:<br>\u2022 Is my child spending too much time playing games?<br>\u2022 What kind of games is my child playing?<br>\u2022 Are the games my child is playing age-appropriate?<br>\u2022 Is my child is at safe place? SOS alerts provide a quick alert system in case of an emergency!<br><br>Super exciting\ud83d\udca5 features of Kido Parental Control App:<br><br><b>\u2714 Screen Time Monitoring</b><br>Set a play-time limit and the console will notify users that the time limit has been reached.<br>Parents and guardians can check the Kido Protect Parental Controls app to see if the time limit has been followed. It is also possible to suspend gameplay automatically when the play-time limit is reached.<br><br><b>\u2714 Apps and Games Monitoring</b><br>Block or restrict specific inappropriate installed apps and other apps. Set a schedule for the time your children can access certain apps. You can also set exactly how much screen time they use on certain apps every day. Send an instant alert when your children try to open blocked apps or games. Some common examples of monitoring e.g. YouTube monitoring, social media app monitoring.<br><br><b>\u2714 Web Monitoring</b><br>Have complete control over the internet activities of your kids. We offer full parental tracking system that allows you to see apps usage web surfing and sites visited and much more. This can help you to make their choices better and safer.<br>To ensure the filtering and blocking of undesirable browser content on your child&#39;s device, the App utilizes a VPN service. This service enables the app to monitor and manage the online activities on the device<br><br><b>\u2714 Social Media Monitoring</b><br>Deep and comprehensive monitoring social app activities allows you to monitor kid\u2019s online activities. Monitor social media apps notifications, such as WhatsApp, Line, and Facebook Messenger, to stop cyberbullying and online fraud timely<br><br><b>\u2714 Location and Geo Fencing</b><br>Worried about your children location? Now get your child location via family GPS tracking. Get notifications when your child enters or leaves geo-fenced zones you set. See location history and find your kids. Kido free Parental Control app 2023 gives you full variety of family safe tools you can use to safe your family or kids from any uncertain situations. This way your family link with you all the time. This is kind of family locator tool to assure safety of your family.<br><br><b>\u2714 Nudity Monitoring or Content Blocking</b><br>Keep your children away from age-restricted games and content. Lock safe search on search engine for more filtered content.<br>Real time reporting, rich list of useful features (screen time, apps monitoring, social media monitoring, internet and web filtering, location and geofencing, SOS, task management, YouTube monitoring, and more...), with a full control of your child&#39;s devices.<br><br>The Accessibility API will allow the Kido Protect app to view and control the screens of your child&#39;s devices. It helps to parent, that can detect what child is doing the activity on his/her devices.<br><br>Be more assured about your child&#39;s safety and well-being on the internet.<br>Their safety and well-being is our goal. So why not Kido Protect Parental Control App?\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66<br><br>Read our full Terms of Service<br>https://www.kidoprotect.com/terms-and-conditions/<br>and our Privacy Policy at<br>https://www.kidoprotect.com/privacy-policy/",
    "summary": "Kids Safety App offers block apps, screen time limit and kids tracker tools",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 124247,
    "score": 4.2608695,
    "ratings": 190,
    "reviews": 28,
    "histogram": [
        8,
        12,
        16,
        37,
        115
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$6.99 - $49.99 per item",
    "developer": "TECHNOSOFT FZCO",
    "developerId": "7602334847414558939",
    "developerEmail": "kidoprotect@gmail.com",
    "developerWebsite": "https://www.kidoprotect.com",
    "developerAddress": "Silicon Oasis, Building A2, 101",
    "privacyPolicy": "https://www.kidoprotect.com/privacy-policy/",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/WvSBczEh0kbq9EEpzt6BGF-NmKFNswm0Vqayp7jSxRGrlL5Mgx498B2YsnR0Q582nmI",
    "headerImage": "https://play-lh.googleusercontent.com/e0fqkYzWzI5uwdAp_urDNvsfybfBCEbeu1kK7Wzerc1G5tXSqnQZXhyJbKmIcYz2Yi_q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/a0Zv8gDKC40p32H9psIFPNFkwBvoiCR3uFIMg2FvOYt0tVWmxYI7UOnJCQdehr11V8k",
        "https://play-lh.googleusercontent.com/lAL9BbKUOssVUKPOBjhyJWu0B2Rc60A88qUi8ioFhwJo-2W_Kgmpgcg1SR7XrcXnzlw",
        "https://play-lh.googleusercontent.com/tfsgdl2JrCJapTGbl890BHcuRSobI4jdsYUD6lQuwvuuyQOA3mjAJjQ_78q7f4qPjg",
        "https://play-lh.googleusercontent.com/mrveSbBsV9X_PTT-lB1PGW_9YM5W41mx7Z01Yepx2glY3ZNbQxfPMI0F6wDT6cxXYg",
        "https://play-lh.googleusercontent.com/fTbjuqmOhJWyIFJ32_kzI_MWLEf8N-s1sfJ_roYgb-Shwo_bNIxlQTHRapPfXDLC6Ks",
        "https://play-lh.googleusercontent.com/3eCt85JyO0wF5ALUChq4nLYxcP2HHZoQy3kQ6iKdhhWV5zdl8INJ28h0idncVRzqlw",
        "https://play-lh.googleusercontent.com/bjC2Gj9ZRA4iEhw6_F7Jta6qve2EOIAo9Z9K7pGKoGcGKRbtuAJEWIcwFc4yXyWH6eE",
        "https://play-lh.googleusercontent.com/_6kcWDhf2oAcVrAtki59NdFDe1wlyKemUvlorro_Y4C8I2ByOCJSc1-w1_QgKazCDJWD"
    ],
    "video": "https://www.youtube.com/embed/W6bJ-eh8TUc?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/e0fqkYzWzI5uwdAp_urDNvsfybfBCEbeu1kK7Wzerc1G5tXSqnQZXhyJbKmIcYz2Yi_q",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 21, 2022",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729098369,
    "version": "6.9",
    "comments": [],
    "appId": "com.kidoprotect.app",
    "url": "https://play.google.com/store/apps/details?id=com.kidoprotect.app&hl=en&gl=us"
}