{
    "title": "CUE Live",
    "description": "CUE Live utilizes inaudible, ultrasonic sound waves to relay data and synchronize devices at CUE technology enabled events, allowing users in attendance or at home to activate their phones and help create and become a part of the show. View a live demo and make the website trigger various colors and looks with the click of a button. UPN and DJ mode can be used to take the event to the next level.",
    "descriptionHTML": "CUE Live utilizes inaudible, ultrasonic sound waves to relay data and synchronize devices at CUE technology enabled events, allowing users in attendance or at home to activate their phones and help create and become a part of the show. View a live demo and make the website trigger various colors and looks with the click of a button. UPN and DJ mode can be used to take the event to the next level.",
    "summary": "CUE Live utilizes ultrasonic sound waves to sync devices at CUE enabled events",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 50132,
    "score": 4.51,
    "ratings": 528,
    "reviews": 43,
    "histogram": [
        41,
        4,
        14,
        41,
        421
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "CUE Audio",
    "developerId": "CUE+Audio",
    "developerEmail": "jameson@cueaudio.com",
    "developerWebsite": "http://cueaudio.com",
    "developerAddress": null,
    "privacyPolicy": "https://cueaudio.com/privacy-policy/",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/iFSN9CI2B0R_tITie-eWMbu_1W4f31jxkkbhDdUE5bw0ZNtKDlFS4M22qSug6hTAfw",
    "headerImage": "https://play-lh.googleusercontent.com/TPKFAmt7VZcolTZ7fvyfT7ZYJ_BfvXusG9BikwEmrPLE_vVvfyAudgbbSwjipCv0aa8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/uEHO08TpzUlnLGm3v6nEYd5zKouIhtEEN2i8-Xtf1Wj7hEx5_1xBPIKPybGgfQ2gXUU",
        "https://play-lh.googleusercontent.com/cr1PwaxTyHOkfEOC5OFEJqAiRfIDg8_NyDutgqNHbpRaEi9Z6_f98tyym-NFnPBpS6iv",
        "https://play-lh.googleusercontent.com/eB97tKkf0rqPlbJ2ntw2eroqh5qge9j7gDeb9WUIuWJXA_ZXlGclFdlRahgMcY_vsw",
        "https://play-lh.googleusercontent.com/D3QQuhef7ttO5WeY3EqJqgb_xupAtamfn_RsyCNOJs5Dc9iz4XeYFbpSehtb07WB2j4",
        "https://play-lh.googleusercontent.com/TEavANKBwbiCCnwl-9NvUtLPWZTX6dJljzBI7cvXX1KnO6_a07XTCTUIpB3GqUWMS5I",
        "https://play-lh.googleusercontent.com/atlT81xzz--e3rUTmWc9USzTA2fgbvhAM6n-64RiTkJk30msbEvJUFgBNxpOtBZAyg",
        "https://play-lh.googleusercontent.com/jdIwL50MvyrEIILvVrl6Qokzxl9_0Q0RWh4LRCslsOZt0z1OqrQnuPfjubE0WOVJdsA"
    ],
    "video": "https://www.youtube.com/embed/ork4Q4eoUg4?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/TPKFAmt7VZcolTZ7fvyfT7ZYJ_BfvXusG9BikwEmrPLE_vVvfyAudgbbSwjipCv0aa8",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 20, 2017",
    "lastUpdatedOn": "Jun 21, 2024",
    "updated": 1718984406,
    "version": "3.14.3",
    "comments": [],
    "appId": "com.cueaudio.cue",
    "url": "https://play.google.com/store/apps/details?id=com.cueaudio.cue&hl=en&gl=us"
}