{
    "title": "Substack",
    "description": "Discover and discuss great writing on Substack.\r\n\r\nWorld-class writing: The best stories, ideas, and culture right at your fingertips.\r\n\r\nGreat discussions: Join conversations with the most interesting readers.\r\n\r\nAll your subscriptions in one place: Find what you want to read quickly and easily.\r\n\r\nSubscriber-only chats: Join private chats hosted by the writers you love.\r\n\r\nThe Substack app is home to thousands of independent writers, creators, and journalists; including George Saunders, Matt Taibbi, Heather Cox Richardson, Elizabeth Gilbert, Nate Silver, Kareem Abdul-Jabbar, Dan Carlin, Matthew Yglesias, Richard Dawkins, Seymour Hersh, Joyce Vance, Jonathan Haidt, and Roxane Gay.\r\n\r\nExplore expansive coverage and conversations about news, politics, arts, AI, finance, history, culture, business, tech, health & wellness, comics, climate, parenting, crypto, travel, philosophy, music, recipes & cooking, humor, sports, fiction, literature, design, and much more.\r\n\r\nIn the Substack app, you can:\r\n\r\n+ Discover new writers, creators, and journalists\r\n\r\n+ Read the latest posts from your subscriptions in a simple and elegant view\r\n\r\n+ Listen to posts on the go\r\n\r\n+ Join your favorite writers in their subscriber chats\r\n\r\n+ See what your friends are reading\r\n\r\n+ Share notes with your thoughts and commentary\r\n\r\n+ Save posts from the explore feed to read later\r\n\r\n+ Access subscriber-only podcast episodes",
    "descriptionHTML": "Discover and discuss great writing on Substack.<br><br>World-class writing: The best stories, ideas, and culture right at your fingertips.<br><br>Great discussions: Join conversations with the most interesting readers.<br><br>All your subscriptions in one place: Find what you want to read quickly and easily.<br><br>Subscriber-only chats: Join private chats hosted by the writers you love.<br><br>The Substack app is home to thousands of independent writers, creators, and journalists; including George Saunders, Matt Taibbi, Heather Cox Richardson, Elizabeth Gilbert, Nate Silver, Kareem Abdul-Jabbar, Dan Carlin, Matthew Yglesias, Richard Dawkins, Seymour Hersh, Joyce Vance, Jonathan Haidt, and Roxane Gay.<br><br>Explore expansive coverage and conversations about news, politics, arts, AI, finance, history, culture, business, tech, health &amp; wellness, comics, climate, parenting, crypto, travel, philosophy, music, recipes &amp; cooking, humor, sports, fiction, literature, design, and much more.<br><br>In the Substack app, you can:<br><br>+ Discover new writers, creators, and journalists<br><br>+ Read the latest posts from your subscriptions in a simple and elegant view<br><br>+ Listen to posts on the go<br><br>+ Join your favorite writers in their subscriber chats<br><br>+ See what your friends are reading<br><br>+ Share notes with your thoughts and commentary<br><br>+ Save posts from the explore feed to read later<br><br>+ Access subscriber-only podcast episodes",
    "summary": "A home for readers",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2235715,
    "score": 4.7905073,
    "ratings": 57523,
    "reviews": 3900,
    "histogram": [
        1199,
        280,
        847,
        4706,
        50484
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Substack Inc.",
    "developerId": "Substack+Inc.",
    "developerEmail": "support@substackinc.com",
    "developerWebsite": "http://substack.com/",
    "developerAddress": null,
    "privacyPolicy": "https://substack.com/privacy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/RoI_bifQ0eWgWqOg4cpbx7Bm8eFkBEml42htao3-_3aZb7xWFhZPbImflNT5bV3Kfnk",
    "headerImage": "https://play-lh.googleusercontent.com/j2Tqq3Ss6WpwiStdQe4ugBIS0WZyPOYzcq_fjFSItEYkEtkDo37s2fqL71OtCE7jkKw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/8V4cnZYzQ_crBCuNdR3caEZ8Vl7onOynXO6QnVFbY1G-RUIQrUDe2Zt3Jz9f9MnY6i0",
        "https://play-lh.googleusercontent.com/900iy8FlZ65qZ4s67l8VC-qXhzAo6d2O5DJhBZ2MOEMevlKm5DRDlUMkgcNEMdfuBVE",
        "https://play-lh.googleusercontent.com/XfyIMlH7xJoav5gKqhi7CvoGCQOk2nfWcB_1YsIZceWwip23Wsf7owf8XhNPy-Li-gm2",
        "https://play-lh.googleusercontent.com/VG1KdI2iFVN_0irnpWT2j9OCl1kIftRB9oKnhjtoG_qywuByy7xGIROBmqRc-KVHGrIf",
        "https://play-lh.googleusercontent.com/e3AyRUCAXnObWVaidkQF_QaAYJvKF_o5NB5oKa59kk9kjr5rw8VAjUSUBIeT4eR1qQ",
        "https://play-lh.googleusercontent.com/HQZ13CTUfp8sEVeGQPrv1NsbeesE5bVzVV3cdCk0NGfMyWMxnV8OqwC5yFoMfKnbjQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 3, 2022",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729014541,
    "version": "2.20.1",
    "comments": [],
    "appId": "com.substack.app",
    "url": "https://play.google.com/store/apps/details?id=com.substack.app&hl=en&gl=us"
}