{
    "title": "Nautide",
    "description": "<b>All the information you need to know to plan activities at sea in a simple and practical app.</b>\r\n\r\nMore than 15,000 coastal stations around the world.\r\n\r\n<b>TIDES</b>\r\nDaily tide charts and tidal coefficient. High tides and low tides. Tides height. Monthly tide table. Tides for fishing.\r\n\r\n<b>SURF</b>\r\nHeight and direction of the swell, wave period, hourly surf table.\r\n\r\n<b>FISH ACTIVITY</b>\r\nHourly activity chart and solunar periods with the best fishing moments of every day. Tides4fishing. Monthly activity table with daily fish activity and major and minor fishing periods. \r\n\r\n<b>SUN AND MOON</b>\r\nSunrise, sunset, moonrise, moonset, azimut, moon phases, eclipses, transits and other astronomical data.\r\n\r\n<b>BAROMETER</b>\r\nFishing barometer, pressure graph and hourly pressure table with trend indicator.\r\n\r\n<b>WIND</b>\r\nWind at land and wind at sea: wind speed, wind gust, wind force, land and sea conditions and hourly wind table.\r\n\r\n<b>WEATHER</b>\r\nWeather conditions at coast: Cloud cover, visibility, temperature, precipitation, wind chill, humidity, dew point and hourly weather table.\r\n\r\n<b>MARINE</b>\r\nOpen water forecast for marine/sailing. Includes all weather indicators and also the water temp. Hourly marine table.\r\n\r\ntides4fishing official app",
    "descriptionHTML": "<b>All the information you need to know to plan activities at sea in a simple and practical app.</b><br><br>More than 15,000 coastal stations around the world.<br><br><b>TIDES</b><br>Daily tide charts and tidal coefficient. High tides and low tides. Tides height. Monthly tide table. Tides for fishing.<br><br><b>SURF</b><br>Height and direction of the swell, wave period, hourly surf table.<br><br><b>FISH ACTIVITY</b><br>Hourly activity chart and solunar periods with the best fishing moments of every day. Tides4fishing. Monthly activity table with daily fish activity and major and minor fishing periods. <br><br><b>SUN AND MOON</b><br>Sunrise, sunset, moonrise, moonset, azimut, moon phases, eclipses, transits and other astronomical data.<br><br><b>BAROMETER</b><br>Fishing barometer, pressure graph and hourly pressure table with trend indicator.<br><br><b>WIND</b><br>Wind at land and wind at sea: wind speed, wind gust, wind force, land and sea conditions and hourly wind table.<br><br><b>WEATHER</b><br>Weather conditions at coast: Cloud cover, visibility, temperature, precipitation, wind chill, humidity, dew point and hourly weather table.<br><br><b>MARINE</b><br>Open water forecast for marine/sailing. Includes all weather indicators and also the water temp. Hourly marine table.<br><br>tides4fishing official app",
    "summary": "Plan and enjoy the activities at sea: surf, fishing, sailing, diving, kayak ...",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1914204,
    "score": 4.848214,
    "ratings": 12137,
    "reviews": 434,
    "histogram": [
        325,
        0,
        0,
        541,
        11270
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$3.49 - $19.99 per item",
    "developer": "Igoox",
    "developerId": "6480399203472843094",
    "developerEmail": "support@nautide.com",
    "developerWebsite": "https://nautide.com",
    "developerAddress": "Carmen Conde, 11\n21007 Huelva\nSpain",
    "privacyPolicy": "https://nautide.com/privacy",
    "genre": "Weather",
    "genreId": "WEATHER",
    "categories": [
        {
            "name": "Weather",
            "id": "WEATHER"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/FcW6gqmaez5k2uMtrL216jSa31rOYhd9QaRznVBwu3ccwQrdlTvzGpqfeB6-7wF_ew",
    "headerImage": "https://play-lh.googleusercontent.com/AP_mPw0NDsmcxo_xsJP8jNH3wZM43RpBAWnsakulOulzmlXoZdta00Z7w3wKgxBMQ18",
    "screenshots": [
        "https://play-lh.googleusercontent.com/xA7hpM5geAoChdHXlfC4NIVq0R3eNngD1Kd_obB9mjLXYiHEea1XPqbXHzRSuZpj_V0",
        "https://play-lh.googleusercontent.com/pmPVuX-mFlCWPyrvQhz6XA5uhJsgB4cMuo6FRJzTZrx5644AATOxrvOOf9lssUHP_l8",
        "https://play-lh.googleusercontent.com/JeiGwpwXZE1GMo-HlICDQ2T-m_bhuefRWkoNQMIUw63uPVPcKNkGM7uxoSztvrt3qg",
        "https://play-lh.googleusercontent.com/pBK0fkFi3DhnZj9FDkc9nZ4ZKuurBq9SvO15GsJPwkvO10JAjgwyPXKwa4fzTWQj4jbM",
        "https://play-lh.googleusercontent.com/wXTWbXVs1q8x1831g_77cEjjOU3vt7yESu0hkjCDsFtNR-_8X7sEhmMezwGXSfJU8QKn",
        "https://play-lh.googleusercontent.com/iSAwAq85CS2T8nfTieGuFqC0dmYB3etGukPHXUD0tgq-JG_r5CrZ8j2nwzYP0kpifPu3",
        "https://play-lh.googleusercontent.com/5R2O9l3F0HEm86XWUenXebftet6kPPLwrYHzbbIXd21_kaaENy7auygG6_8McBRpN9cc",
        "https://play-lh.googleusercontent.com/SBnNet7xtGAej4gAYE94d6JEXAWCCkNXJhxfMXmCnEqIu1NRHC-XwWmFSky7J0B58bUR",
        "https://play-lh.googleusercontent.com/GS14jhPmzTwKXdlcpuXga8czt6FCgZGm-QTcZvbLsPEehaKTtE_VMOKonjccndkVaIwd",
        "https://play-lh.googleusercontent.com/Luux9TvsgMvb2IMKoUjHvrcaJkYKvdTEAYVpnNqrRCntYf7TSKNe3bat5EL4QLQIwg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 23, 2018",
    "lastUpdatedOn": "Aug 23, 2023",
    "updated": 1692781040,
    "version": "4.2.3",
    "comments": [],
    "appId": "com.nautide.app",
    "url": "https://play.google.com/store/apps/details?id=com.nautide.app&hl=en&gl=us"
}