{
    "title": "Piano fun - Magic Music",
    "description": "Let's show your musical talent with Piano Fun\ud83c\udfbc\r\n\r\nEven you don't have any basic knowledge in piano, you still can play piano with note tiles in the game!\ud83d\ude31\r\n\r\nBeethoven or Chopin, Mozart or Schubert. Popular song, Dance, Romantic or Folk\r\n\r\n\ud83e\udd17You could choose any music you like! You just need to enjoy the piano fun game!\r\n\r\nEnjoy the classic songs and beautiful melody, relax your soul with the piano game!\r\n\r\n\u2b50\ufe0fHOW TO PLAY\u2b50\ufe0f\r\n\r\n\u2b55\ufe0fSelect your favorite song in song list book\r\n\r\n\u2b55\ufe0fPress the correct keys of piano keyboard when note tiles fall\r\n\r\n\u2b55\ufe0fPlay a music, and relax yourself!\r\n\r\n\u2b50\ufe0fGAME FEATURE\u2b50\ufe0f\r\n\r\n\ud83d\udc9cVarious Music Songs, various styles for all game player\r\n\r\n\ud83d\udc99Easy to play, from piano beginner to hardcore player. The game suits for everyone!\r\n\r\n\ud83d\udc9aSmooth gaming experience, beautiful game interface\r\n\r\nFeel the beautiful piano music melodies !\r\n\r\nDOWNLOAD NOW! \ud83c\udf89",
    "descriptionHTML": "Let&#39;s show your musical talent with Piano Fun\ud83c\udfbc<br><br>Even you don&#39;t have any basic knowledge in piano, you still can play piano with note tiles in the game!\ud83d\ude31<br><br>Beethoven or Chopin, Mozart or Schubert. Popular song, Dance, Romantic or Folk<br><br>\ud83e\udd17You could choose any music you like! You just need to enjoy the piano fun game!<br><br>Enjoy the classic songs and beautiful melody, relax your soul with the piano game!<br><br>\u2b50\ufe0fHOW TO PLAY\u2b50\ufe0f<br><br>\u2b55\ufe0fSelect your favorite song in song list book<br><br>\u2b55\ufe0fPress the correct keys of piano keyboard when note tiles fall<br><br>\u2b55\ufe0fPlay a music, and relax yourself!<br><br>\u2b50\ufe0fGAME FEATURE\u2b50\ufe0f<br><br>\ud83d\udc9cVarious Music Songs, various styles for all game player<br><br>\ud83d\udc99Easy to play, from piano beginner to hardcore player. The game suits for everyone!<br><br>\ud83d\udc9aSmooth gaming experience, beautiful game interface<br><br>Feel the beautiful piano music melodies !<br><br>DOWNLOAD NOW! \ud83c\udf89",
    "summary": "Fun musical game for you to play piano like a pro!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4683245,
    "score": 4.2993197,
    "ratings": 10193,
    "reviews": 466,
    "histogram": [
        899,
        345,
        691,
        1107,
        7141
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $46.99 per item",
    "developer": "DrawAPP",
    "developerId": "DrawAPP",
    "developerEmail": "eyewind.draw@hotmail.com",
    "developerWebsite": "http://drawapp.cc/",
    "developerAddress": "room2305,Chun Fu House,Tin Fu Court\nTin Shui Wai,NT,Hong kong\nTin Shui Wai New Territories HK",
    "privacyPolicy": "http://drawapp.cc/privacy.html",
    "genre": "Music & Audio",
    "genreId": "MUSIC_AND_AUDIO",
    "categories": [
        {
            "name": "Music & Audio",
            "id": "MUSIC_AND_AUDIO"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/vCRrzkulssLE7LPqagFBEtLbjv-0DDJR10zGaBpSE1PGcnOJsldyV7ZLV5-nHD750ZI",
    "headerImage": "https://play-lh.googleusercontent.com/C8lbS5vVwzdxyGjdzzpx1314iJOgY9AikvwaBWL_Own5CGYp3SDjapGG2PO_3dxRzDwi",
    "screenshots": [
        "https://play-lh.googleusercontent.com/0McikISh6-3-w_ro1bGR1Ci7qe0GcWX3svPmIvxtgxFyQnJ_w8Zl_zJ7_W_28sWA2l_b",
        "https://play-lh.googleusercontent.com/7xn_ZiAVmQKPaqyn6Gx_MrV8c79G_hjuI0iQDHysGSjZAA50tHzrn1ytMkeb9b71LdTP",
        "https://play-lh.googleusercontent.com/GrtPNY-ky70_St2FphLaowq8J84XAiGUvyd1NB6JKugMUvhcdMFeaR4knH9zYlliDlE",
        "https://play-lh.googleusercontent.com/zgb4uABTJX8f9ZGi7GXtC0rro0HstNP0FqEoG0lkA5-2u6N_LeSlXyErh1fEFu-RZ_BD",
        "https://play-lh.googleusercontent.com/cThNFxoX4KsRMHGfnsrxOdMD3GD5ARlGtXjJ8tdB8dboPQaujcwMSurgcCEuM1CPwQ",
        "https://play-lh.googleusercontent.com/uWdhSMxw81dc1PslbEDG_S6lPro-bKzMNSfUUFFCa5A0lSdRCCgii1gV-SnAJCcNtw",
        "https://play-lh.googleusercontent.com/4YryY1CkvHAHB2i69EVbaK3PrwalzOwT0TghcJlg41NMzO1EjIUzAnBv-vMXmeTUpL8",
        "https://play-lh.googleusercontent.com/XF5ML7AinX5rlaDt7-FmzIRzc1L1G3mpOr3izxxntxj5GrLIGizfuWnH3kwebOF-CyQ",
        "https://play-lh.googleusercontent.com/M495didnbQ-maxoXWFRrfrPXt3QqnCEpMUwF2svt07oa1I5vO6sOkjKgx_wp9zGRX2cm",
        "https://play-lh.googleusercontent.com/--9DQSjM6ZISD-s9Ovq42UZn6j_1mLuZSV6HIIJ35zL_AQZC8SZhvrxbVhFCPNMF5JM",
        "https://play-lh.googleusercontent.com/uKFrJSOWMQtGcxYijg_-uVaYmZhQtOcustx1J7RsUu4r0000uljwmPh2_CeeHyAG62Q",
        "https://play-lh.googleusercontent.com/LnoVF5AQ8I_u1ANLXVkU79qe9Efeyvc1M5a4D5b4N641kz0AQlKxr_V1SRLNZJCO5A",
        "https://play-lh.googleusercontent.com/G0CgMfDXypRz79Wt2xTujqJFBV22IkgdXrhJ6LRbev4HCaMTUOglU5j646k4motoBQ",
        "https://play-lh.googleusercontent.com/Z6Ngsf5prsqIJMcXsvXkRSlmDLeARi9iHMOjJHb9uYIayCRJ-4fg7Vs7Sc01jbDmDw",
        "https://play-lh.googleusercontent.com/7ShV7e8go-aFLnyJluVZyB4DtSL-agq2u4we6kykRnN7yfLVpnyMZaEcGrH-lOR3UDDr",
        "https://play-lh.googleusercontent.com/vWQ4De0_eZ_msIfK9LoUz5fub4GHMIrpTRZX2gCSjX-AAGyZtSRYBHD8T020XNES2eo",
        "https://play-lh.googleusercontent.com/zLpP-ebY5cmLDSs9JYMhQrvgitFyCzdgCQq9MOUIGzOPJR7jFJVgKTVyr_r4ekkaMA",
        "https://play-lh.googleusercontent.com/bL8mzwbRT-Xn6LDlo-SWhkTf3sJid-2Pe_X-3SOJvkS0u3F_URbj61CYboXMWXoKgns"
    ],
    "video": "https://www.youtube.com/embed/qW-XILqG47U?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/C8lbS5vVwzdxyGjdzzpx1314iJOgY9AikvwaBWL_Own5CGYp3SDjapGG2PO_3dxRzDwi",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 13, 2020",
    "lastUpdatedOn": "Mar 18, 2024",
    "updated": 1710816150,
    "version": "1.3.1",
    "comments": [],
    "appId": "com.tap.music.piano.fun",
    "url": "https://play.google.com/store/apps/details?id=com.tap.music.piano.fun&hl=en&gl=us"
}