{
    "title": "Houzz - Home Design & Remodel",
    "description": "Whether you\u2019re building, remodeling or decorating, Houzz has you covered.\r\n\r\n<b>Get the Best Design Ideas for Your Home</b>\r\n- Browse more than 25 million high-resolution photos of home interiors and exteriors. Choose by style, location or room, such as kitchen or bathroom.\r\n- Save and share home design photos with friends, family and home professionals.\r\n- Use the Sketch feature to annotate and draw directly on photos from Houzz.\r\n\r\n<b>Find, View and Buy Products for Your Home</b>\r\n- Shop from more than 5 million products and materials, including vanities, cabinets, lighting, furniture, tile and more for interior and exterior design.\r\n- Read verified product reviews.\r\n- Save up to 75% off during featured sales.\r\n- Use Visual Match, our visual recognition technology, to discover and buy products and materials directly from home design photos on Houzz.\r\n- Wondering what that sofa would look like in your living room? Select the View in My Room 3D feature and use the camera on your Android device to see how products would look in your space.\r\n\r\n<b>Find, Hire and Collaborate with the Best Home Professional for Your Home Renovation Project</b>\r\n- Connect with over 3 million home improvement professionals, including architects, general contractors, interior decorators, repair professionals and more.\r\n\r\n<b>Read Articles From Our Editorial Staff and Design Experts</b>\r\n- Check out our biweekly Houzz Newsletter for engaging and informative articles, including home tours, full kitchen and bathroom remodeling guides, home renovation news, decorating tricks, organizing guides, designing for pets, gardening advice, interior design and decor, humor and everything in between.\r\n- Watch Houzz TV to see original videos of inspiring homes, how-tos and more.\r\n\r\n<b>Get Advice On Your Home Remodel Project</b>\r\n- Discuss home design and renovation topics in our Advice section and get feedback from the Houzz community on your home renovation projects and design ideas.\r\n\r\nThe Houzz app topped The New York Times list of \u201cbest apps for home improvement.\u201d The Washington Post called Houzz the \u201csingle best source\" for finding inspiration. CNN named it the \u201cWikipedia of interior and exterior design.\u201d\r\n\r\nUse of the Houzz Android App and the the services provided through the Apps are subject to Houzz.com's terms of use: http://www.houzz.com/termsOfUse\r\n\r\nTo learn more about the permissions required to install the Houzz app, please visit Houzz support: https://support.houzz.com/entries/38179588-What-permissions-does-the-Houzz-app-require-",
    "descriptionHTML": "Whether you\u2019re building, remodeling or decorating, Houzz has you covered.<br><br><b>Get the Best Design Ideas for Your Home</b><br>- Browse more than 25 million high-resolution photos of home interiors and exteriors. Choose by style, location or room, such as kitchen or bathroom.<br>- Save and share home design photos with friends, family and home professionals.<br>- Use the Sketch feature to annotate and draw directly on photos from Houzz.<br><br><b>Find, View and Buy Products for Your Home</b><br>- Shop from more than 5 million products and materials, including vanities, cabinets, lighting, furniture, tile and more for interior and exterior design.<br>- Read verified product reviews.<br>- Save up to 75% off during featured sales.<br>- Use Visual Match, our visual recognition technology, to discover and buy products and materials directly from home design photos on Houzz.<br>- Wondering what that sofa would look like in your living room? Select the View in My Room 3D feature and use the camera on your Android device to see how products would look in your space.<br><br><b>Find, Hire and Collaborate with the Best Home Professional for Your Home Renovation Project</b><br>- Connect with over 3 million home improvement professionals, including architects, general contractors, interior decorators, repair professionals and more.<br><br><b>Read Articles From Our Editorial Staff and Design Experts</b><br>- Check out our biweekly Houzz Newsletter for engaging and informative articles, including home tours, full kitchen and bathroom remodeling guides, home renovation news, decorating tricks, organizing guides, designing for pets, gardening advice, interior design and decor, humor and everything in between.<br>- Watch Houzz TV to see original videos of inspiring homes, how-tos and more.<br><br><b>Get Advice On Your Home Remodel Project</b><br>- Discuss home design and renovation topics in our Advice section and get feedback from the Houzz community on your home renovation projects and design ideas.<br><br>The Houzz app topped The New York Times list of \u201cbest apps for home improvement.\u201d The Washington Post called Houzz the \u201csingle best source&quot; for finding inspiration. CNN named it the \u201cWikipedia of interior and exterior design.\u201d<br><br>Use of the Houzz Android App and the the services provided through the Apps are subject to Houzz.com&#39;s terms of use: http://www.houzz.com/termsOfUse<br><br>To learn more about the permissions required to install the Houzz app, please visit Houzz support: https://support.houzz.com/entries/38179588-What-permissions-does-the-Houzz-app-require-",
    "summary": "Home Ideas | Renovation Advice | Local Pros. Go From Dream to Home with Houzz.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 20504472,
    "score": 4.608098,
    "ratings": 405863,
    "reviews": 39636,
    "histogram": [
        19352,
        3878,
        9239,
        51522,
        321864
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Houzz Inc.",
    "developerId": "Houzz+Inc.",
    "developerEmail": "android@houzz.com",
    "developerWebsite": "http://www.houzz.com",
    "developerAddress": "8605 Santa Monica Blvd., #90918, West Hollywood, California 90069-4109 United states",
    "privacyPolicy": "http://www.houzz.com/privacyPolicy",
    "genre": "House & Home",
    "genreId": "HOUSE_AND_HOME",
    "categories": [
        {
            "name": "House & Home",
            "id": "HOUSE_AND_HOME"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/NJgFjc5QalIzaAzYPAfc93A1j0U9JOBfjHtattMoFA2D8JgzS0JYut63zzFfMpTFodA",
    "headerImage": "https://play-lh.googleusercontent.com/mRETrjEcMsR93aW9qsULyJCRDU0BlET5CmJuFs_o5u67CW3hW5QdxebwFlWRJQoJDdKf",
    "screenshots": [
        "https://play-lh.googleusercontent.com/7XD7fZggDU3TjYyCvq7dH5u7iXNbL5DhJOLAId4rfL2WbYjOtRUUKX7DLiHcbF0lN1zg",
        "https://play-lh.googleusercontent.com/KB4kocJBagqnfDWSFhDye_KbbeyyfWzt_4FKPbXdW6LYqu1ivqNJwij0hMFPSC6Awg",
        "https://play-lh.googleusercontent.com/CiXjj26TuO5dEKoLUKvYQf-7UChq7mFup1iITsiXifRq9aTZRn3PGDdOsOqSuRbJS8E",
        "https://play-lh.googleusercontent.com/630UoZi74SmP1wDrhE5BshXwckB71uqnjyKiRrf3M4hy6-ftsQhS5bXPGGAZbp9f_vk",
        "https://play-lh.googleusercontent.com/GH2ahohl1Rz1oZasjoca0qxgJDX0kUcLwAzQKMSo8Pho7SOkg0K8vHogy-Apdnm6YDU",
        "https://play-lh.googleusercontent.com/r5xk-6462eKHSYsgDX732rKnkfq5pARpnxMUpOUwFjeWJIdLIHCa_oOPKnnJFwrUgw",
        "https://play-lh.googleusercontent.com/6GbkwZ-wgDNFbv_iYqcuhD-qhryincCujthsOnGKv0176ZZCHtu_ItZu44HKXSgMOmnX",
        "https://play-lh.googleusercontent.com/jk3U34oJ-rOX2oln6hx1Hlb5NTkcrdOHVatkUuaVgK9kRhnu8mKZoXU2A34-9cQ66Q",
        "https://play-lh.googleusercontent.com/0NCtOF2k79KnRj6BPaJ3_wCd__2EEA4RZdE-A2tt5k05lr8VpKMymLS7LQRTc-sAbE0",
        "https://play-lh.googleusercontent.com/Iifbn5vP8_SM_5heL0v5hNKvx_2Vmqdg8dIEMbazi7Xw8eVtmlMjzC40UmUQdfVKAiU",
        "https://play-lh.googleusercontent.com/Kd-AuKA-cVC5untlwJlcrWvELQrC3RYBZXYioRzg6sP8fL-A0gUpmI1OUgbfisuDBwo",
        "https://play-lh.googleusercontent.com/Q5me1MbNfNzgjrK2cePOzZSoIzmTOWuwcJBfSUXzJM_0eieV2b9WKg8b4cbc1ZOb",
        "https://play-lh.googleusercontent.com/zCbfyjR74pWjIOq9uLqGuNqv88n29A1az_H9-AqO3fD9GaPIcHy249kh-6AJ05fdhuY",
        "https://play-lh.googleusercontent.com/0TRTJtS8PB1dabKHpUJGXToq7IshXqTQs33zXfssvUJ-4Jq_t83CcC6lBRgAlIjt22A",
        "https://play-lh.googleusercontent.com/t9R7LzVZj9UkeU7nxk976cfvz1GDzEKPd_9TMvvgb1UU3qJquv6ntmXQj1nb9vlJUuo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Dec 18, 2012",
    "lastUpdatedOn": "Sep 12, 2024",
    "updated": 1726132435,
    "version": "24.9.10",
    "comments": [],
    "appId": "com.houzz.app",
    "url": "https://play.google.com/store/apps/details?id=com.houzz.app&hl=en&gl=us"
}