{
    "title": "Nordstrom Rack",
    "description": "GREAT BRANDS. GREAT PRICES.\r\nIt\u2019s super-easy to find the brands you love with the Nordstrom Rack app. Use it to shop up to 70% off clothing, shoes, accessories and beauty for the whole family. \r\n\r\nAPP FEATURES\r\n\r\nGet alerts that give you the first word on sales, new markdowns, new arrivals, brands, events & more.\r\n\r\nLove flash events? They\u2019re launching daily right here, with limited-time deals on amazing brands and styles. \r\n\r\nBecome a Nordy Club member and unlock perks you\u2019ll love. It\u2019s easy\u2014and free!\r\n\r\nCreate a Wish List that lets you save your faves and share with family and friends.\r\n\r\nDid you know you can pay with your Nordstrom card in store using a QR code?\r\n\r\nABOUT NORDSTROM RACK\r\n\r\nHi! We\u2019re Nordstrom Rack, part of the Nordstrom family since 1973 and 100% committed to delivering great brands at great prices. Shop in store, online or on our app for all the looks you love\u2014and all the deals you deserve. Every day\u2019s an opportunity to save big on hundreds of brands and thousands of styles. And you can score even more when you shop our awesome sales and flash events. It\u2019s all here, all new, all for you.",
    "descriptionHTML": "GREAT BRANDS. GREAT PRICES.<br>It\u2019s super-easy to find the brands you love with the Nordstrom Rack app. Use it to shop up to 70% off clothing, shoes, accessories and beauty for the whole family. <br><br>APP FEATURES<br><br>Get alerts that give you the first word on sales, new markdowns, new arrivals, brands, events &amp; more.<br><br>Love flash events? They\u2019re launching daily right here, with limited-time deals on amazing brands and styles. <br><br>Become a Nordy Club member and unlock perks you\u2019ll love. It\u2019s easy\u2014and free!<br><br>Create a Wish List that lets you save your faves and share with family and friends.<br><br>Did you know you can pay with your Nordstrom card in store using a QR code?<br><br>ABOUT NORDSTROM RACK<br><br>Hi! We\u2019re Nordstrom Rack, part of the Nordstrom family since 1973 and 100% committed to delivering great brands at great prices. Shop in store, online or on our app for all the looks you love\u2014and all the deals you deserve. Every day\u2019s an opportunity to save big on hundreds of brands and thousands of styles. And you can score even more when you shop our awesome sales and flash events. It\u2019s all here, all new, all for you.",
    "summary": "Nordstrom Rack App for Android: Instant access to great brands at great prices.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2034380,
    "score": 4.8039646,
    "ratings": 9209,
    "reviews": 2416,
    "histogram": [
        201,
        19,
        201,
        526,
        8255
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Nordstrom, Inc.",
    "developerId": "Nordstrom,+Inc.",
    "developerEmail": "android@nordstrom.com",
    "developerWebsite": "https://www.nordstromrack.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.nordstromrack.com/privacy",
    "genre": "Shopping",
    "genreId": "SHOPPING",
    "categories": [
        {
            "name": "Shopping",
            "id": "SHOPPING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/_EeD6qk2sUcvcQ7iTffFLEd1zIGArbuCqR_7-8wP4MT3NrvPqXH-6ndAoyikctP2n_SH",
    "headerImage": "https://play-lh.googleusercontent.com/HZiHx3prRwyHF2uKI3PUe5uQmvSvAz4pkrgzWcfKNHe97XY0MorcE5zOIfc9jZ2lS5M",
    "screenshots": [
        "https://play-lh.googleusercontent.com/q6IitzpzrfOn5T5lBhHMpuP6uJIZXd0Ep5E9vIF6fAugKkdwlRQZFM2Qke5hEQ4kVA",
        "https://play-lh.googleusercontent.com/haNczBsSz1zn5_e0ZTeE2l7KfXQIXEvyndz9xNCS8K4YlopH1EWmHDr8kbWNyvciCg",
        "https://play-lh.googleusercontent.com/_YbQlJTOCWZQ8-bQxF0VnQA9e-bCCnccjM-ygRWDVRKjKK8AIQ-cHOweQmypoqDvYLk",
        "https://play-lh.googleusercontent.com/C3fMtVyqae444QJ3h4ECrWRfv9TqY9PUQ9AVyt-BGdi0PZL6wtREUaKcPHGLC5iIt-0",
        "https://play-lh.googleusercontent.com/OiKrQ-sf2QyMqGxc0ddze92d6pL-Qdse8ogcwdVIWYon5147XbiaIoo5Vxeunm7p5ps",
        "https://play-lh.googleusercontent.com/ikLE-66ktUwK0iXR5_0UlfCBblYfg8IPVeLkg0Eut87xsZ7WNSJ4Ggz27opB1EvY27w"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 16, 2015",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729608653,
    "version": "10.20.0.7291414",
    "comments": [],
    "appId": "com.nordstrom.rack.app",
    "url": "https://play.google.com/store/apps/details?id=com.nordstrom.rack.app&hl=en&gl=us"
}