{
    "title": "Speak English with Loora AI",
    "description": "Loora is your personal AI English coach. \r\nIt is always available for you to practice \"as real as it gets\" English conversations.\r\nLoora makes speaking English easy with conversation based sessions, available 24-hours a day, every day.\r\nThe lessons are personalized with real-time feedback on grammar, pronunciation, and fluency. \r\n\r\n============================\r\n\r\nBenefits of learning with Loora:\r\n* Available 24/7, Loora never sleeps.\r\n* Loora works on your schedule. Chat for just 5-minutes a day or an all-out midnight monolog.\r\n* Non-judgmental and friendly environment is always guaranteed, because the biggest mistake you could ever make, is being afraid to make one.\r\n* Real-time translation and speech recognition, to enhance your learning experience. Get immediate feedback on your pronunciation and grammar.\r\n* Track your learning trends to top your daily English fluency score. Perfect your pronunciation and accent by beating your weekly goals.\r\n* Personalized conversations at your speaking level, relevant topics that focus on your life.\r\n\r\n============================\r\n\r\nAbout the team:\r\nWe believe everyone deserves the opportunity to speak English fluently and today it is possible with the help of AI.\r\nThat's why we have gathered a team of leading conversational AI researchers and language-learning enthusiasts,  to worked together on creating Loora. Their goal was to bring you the most dynamic AI English-Coach.\r\n\r\n=====================================\r\n\r\nHave questions or need assistance? Reach out to us at support@loora.ai.\r\n\r\nRead more about our terms and conditions here:\r\n\r\nTerms of Use: https://loora.ai/Terms-and-Conditions\r\n\r\nPrivacy Policy: https://loora.ai/Privacy-Policy\r\n\r\n==============================\r\n\r\nFollow us on Social Media for English tips:\r\n\r\n* Instagram: https://www.instagram.com/loora.ai/?hl=en\r\n\r\n* Facebook: https://www.facebook.com/LooraA.I/\r\n\r\n===============================\r\n\r\nCome meet the future of English Learning!",
    "descriptionHTML": "Loora is your personal AI English coach. <br>It is always available for you to practice &quot;as real as it gets&quot; English conversations.<br>Loora makes speaking English easy with conversation based sessions, available 24-hours a day, every day.<br>The lessons are personalized with real-time feedback on grammar, pronunciation, and fluency. <br><br>============================<br><br>Benefits of learning with Loora:<br>* Available 24/7, Loora never sleeps.<br>* Loora works on your schedule. Chat for just 5-minutes a day or an all-out midnight monolog.<br>* Non-judgmental and friendly environment is always guaranteed, because the biggest mistake you could ever make, is being afraid to make one.<br>* Real-time translation and speech recognition, to enhance your learning experience. Get immediate feedback on your pronunciation and grammar.<br>* Track your learning trends to top your daily English fluency score. Perfect your pronunciation and accent by beating your weekly goals.<br>* Personalized conversations at your speaking level, relevant topics that focus on your life.<br><br>============================<br><br>About the team:<br>We believe everyone deserves the opportunity to speak English fluently and today it is possible with the help of AI.<br>That&#39;s why we have gathered a team of leading conversational AI researchers and language-learning enthusiasts,  to worked together on creating Loora. Their goal was to bring you the most dynamic AI English-Coach.<br><br>=====================================<br><br>Have questions or need assistance? Reach out to us at support@loora.ai.<br><br>Read more about our terms and conditions here:<br><br>Terms of Use: https://loora.ai/Terms-and-Conditions<br><br>Privacy Policy: https://loora.ai/Privacy-Policy<br><br>==============================<br><br>Follow us on Social Media for English tips:<br><br>* Instagram: https://www.instagram.com/loora.ai/?hl=en<br><br>* Facebook: https://www.facebook.com/LooraA.I/<br><br>===============================<br><br>Come meet the future of English Learning!",
    "summary": "Practice English speaking daily with AI to reach fluency and build confidence.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 361527,
    "score": 4.9583335,
    "ratings": 13177,
    "reviews": 227,
    "histogram": [
        0,
        0,
        74,
        390,
        12703
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$14.99 - $119.99 per item",
    "developer": "Loora AI",
    "developerId": "Loora+AI",
    "developerEmail": "contact.us@loora.ai",
    "developerWebsite": "https://loora.ai",
    "developerAddress": null,
    "privacyPolicy": "https://loora.ai/Privacy-Policy",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/PgmLtwW1UHNscMiM0nxp7lZ-D2hNtHZFRObOM739TnFO9hQezcms5WpPQzsPCMYtN7c",
    "headerImage": "https://play-lh.googleusercontent.com/A4AVh2mUfL1scnrcptHP3dM0M2CPBTKhMmx-QG_pf5qpnvERKHI8ZJKnV86xBsorPvU",
    "screenshots": [
        "https://play-lh.googleusercontent.com/s3G0rNuuNufjVSkOL6Ie34aCRHfHEdgfQUQP7PboY3RebGkuypBuxNS00PSN1NJv8O8",
        "https://play-lh.googleusercontent.com/enM-Ok4h-zi1iNyEtZo0CHaGqK8SbodwNTuWi8MNslQUyVuGWnurKIHAfw_lXT8gGmDg",
        "https://play-lh.googleusercontent.com/-ou2eW5KgnHGgwoqmcxHfRIaZmWqrIWCo9oXPDK45hrmX9RnxB5HtlxqyXMChMooB-4l",
        "https://play-lh.googleusercontent.com/iX6y0hAMygdczCCHXr3yDJAi8EJ-65Sdp6ZkI0a7uAV3TgxI66LFAGHTBjgMzOOj9aFp",
        "https://play-lh.googleusercontent.com/adCsPZX94Yr1aLabrRy63ji9yNJThFIVU6IDSp5gDPLLdGh_UBoXdzL-ZhSpG-zxAA",
        "https://play-lh.googleusercontent.com/KVeXkayhkvpOrtUXzS3KF9D8gbd8XztXk556je-EE0mxQOXYUTBdDVTwZEgH9Vw3Jrsg",
        "https://play-lh.googleusercontent.com/zSp3dJMmcg4INDzTSI_DGokGxeDlfCH1YvmO_DFdaI1dYlMj7qEekCmLA9YouiHqRZY",
        "https://play-lh.googleusercontent.com/wu0M_Bd-VZUT1F9mcz-yjD4FsFD_KZeiETAxW1oF8GcasHRcRg57K1DThciE4DLELeZj",
        "https://play-lh.googleusercontent.com/wLCwph7xAv-Guxh0DdybY8jHjyJjaCR8RS6U9nr2xti2gd3d-Jv8_u-65lI7FxgG6g",
        "https://play-lh.googleusercontent.com/7H6J7XYNYud_BSBM7sXs3QSVdnHQHCbjzxJR48dGzIPC0tqG9Nf9y3OgtvHpZagLm0m3",
        "https://play-lh.googleusercontent.com/RdWKXaCbeUG-ql3NqqVYHFCCqEVFXQd9mI-kS-en1j9W5uvIS0rrFsXbhsua6MuWHijF",
        "https://play-lh.googleusercontent.com/zncY1B9MDB8K6rHrZO2upHLRkPDviC7cOBgaSahE0tqaVHkEN_4jaEj-27ceGkdgmzY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 24, 2024",
    "lastUpdatedOn": "Oct 7, 2024",
    "updated": 1728333616,
    "version": "1.7.0",
    "comments": [],
    "appId": "com.loora.app",
    "url": "https://play.google.com/store/apps/details?id=com.loora.app&hl=en&gl=us"
}