{
    "title": "PrePass",
    "description": "The PrePass app gives drivers the option to bypass weigh stations using a mobile device. PrePass is the most reliable, widely utilized weigh station bypass system in North America. With PrePass, pre-cleared vehicles can continue at highway speeds without having to stop. PrePass not only saves fleets time, fuel, and money, but it helps create greater efficiencies for shippers and supports improved safety for all highway users.\r\n\r\nWith PrePass, customers select whether to use the PrePass app, the transponder or BOTH. The PrePass app provides coverage to an expanded number of weigh station sites while the transponder provides greater bypass reliability and integration with NORPASS and Oregon Green Light weigh station locations. The transponder also provides the option of adding toll payment services through PrePass Plus.\r\n\r\nPrePass is an endorsed featured product of the American Trucking Associations ATA) and is also endorsed by the Owner Operator Independent Drivers Association (OOIDA), Truckers Service Association (TSA), National Association of Small Trucking Companies (NASTC) and state trucking associations across the country.\r\n\r\n- The most bypassing options with a mobile app and a transponder\r\n- Works at fixed and mobile weigh stations\r\n- Includes roadway safety ALERTS\u2122\r\n- Transponder can also be used for nationwide toll payment processing\r\n- Includes Florida agriculture inspection facilities upon request\r\n- Access to PrePass industry-leading customer support\r\n- Last recall feature provides last bypass confirmation\r\n\r\nFor more information log on to the PrePass website at:\r\nhttps://prepass.com/services/weigh-station-bypass-service/\r\n\r\nFacebook: https://www.facebook.com/PrePassForum/\r\n\r\nTwitter: https://twitter.com/PrePass\r\n\r\nInstagram: https://www.instagram.com/prepass/",
    "descriptionHTML": "The PrePass app gives drivers the option to bypass weigh stations using a mobile device. PrePass is the most reliable, widely utilized weigh station bypass system in North America. With PrePass, pre-cleared vehicles can continue at highway speeds without having to stop. PrePass not only saves fleets time, fuel, and money, but it helps create greater efficiencies for shippers and supports improved safety for all highway users.<br><br>With PrePass, customers select whether to use the PrePass app, the transponder or BOTH. The PrePass app provides coverage to an expanded number of weigh station sites while the transponder provides greater bypass reliability and integration with NORPASS and Oregon Green Light weigh station locations. The transponder also provides the option of adding toll payment services through PrePass Plus.<br><br>PrePass is an endorsed featured product of the American Trucking Associations ATA) and is also endorsed by the Owner Operator Independent Drivers Association (OOIDA), Truckers Service Association (TSA), National Association of Small Trucking Companies (NASTC) and state trucking associations across the country.<br><br>- The most bypassing options with a mobile app and a transponder<br>- Works at fixed and mobile weigh stations<br>- Includes roadway safety ALERTS\u2122<br>- Transponder can also be used for nationwide toll payment processing<br>- Includes Florida agriculture inspection facilities upon request<br>- Access to PrePass industry-leading customer support<br>- Last recall feature provides last bypass confirmation<br><br>For more information log on to the PrePass website at:<br>https://prepass.com/services/weigh-station-bypass-service/<br><br>Facebook: https://www.facebook.com/PrePassForum/<br><br>Twitter: https://twitter.com/PrePass<br><br>Instagram: https://www.instagram.com/prepass/",
    "summary": "Weigh Station Bypass & Alerts",
    "installs": "5,000+",
    "minInstalls": 5000,
    "realInstalls": 9624,
    "score": 3.2105262,
    "ratings": 19,
    "reviews": 13,
    "histogram": [
        7,
        1,
        1,
        1,
        9
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "PrePass Safety Alliance",
    "developerId": "PrePass+Safety+Alliance",
    "developerEmail": "DL-PrepassMobileAppAdmin@cvo.com",
    "developerWebsite": "http://prepass.com",
    "developerAddress": null,
    "privacyPolicy": "https://secure.prepass.com/Static/PrivacyPolicy.aspx",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/YNmXyYGwFc0ENWpbs77lnQ4FVo1khOkdwZVXsZgwyXg1oz6dnUh7oOsHJjrcGhXATyWI",
    "headerImage": "https://play-lh.googleusercontent.com/juOY5-TXVOqnhPYtOojFmnryBPLF-WlbzIomW-VsHbp1L8XutX5hkp_hR0yeEDifSQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/5WQpGRcLSu4zi2JJsQHFak7B2oQBCnniXStE2Tt25iOoKdDld-mSRl4m2OD52z9itA",
        "https://play-lh.googleusercontent.com/Br_XVqIe9j8AO2W4kXSUMOoYjQjyGHotOYRNltqNj9IyxGAJ7MwBZe2sJyYiHOKzK84",
        "https://play-lh.googleusercontent.com/t6q30kox3GoT6-GYYer5SwPQgRmr0AZcKjBpsMBSsrXTLtQaKNfyAkByaPIHMoEaWrg",
        "https://play-lh.googleusercontent.com/WFarVbB3c7xcJG8S7C0ZNDuwYQXyajs0cczS8RuRZ-LYV9b5YNd2PAfQbhYeF18VUw",
        "https://play-lh.googleusercontent.com/hgZu81hUKl6GcsiTs4xOlT2asiZo4jaMxk8_3x89JPlsiEKz368Sr1laSdpvumSaxxsU",
        "https://play-lh.googleusercontent.com/um1AO53A2VHeOEco2_eeKS-n8WyBGLxKi7xu8Y-pamXosmtIS8ZHQQsQpCAjJo62wg",
        "https://play-lh.googleusercontent.com/a1d3DV_w2Dix4XsZB9dKsU-JY-qFswtsmJbUoY0CCmny695UwJPbkk2nYJMy1NQmeEc",
        "https://play-lh.googleusercontent.com/2IeKU1diNnzwBGerNZ7OHGKv3iMEezaJWiTBTG2GvH1w5PVd6Ovul2hoY-EjlbmdGCs",
        "https://play-lh.googleusercontent.com/O5Cd2WreP1oP1XKWizvT2PV5yGEDSAWR04m5n0qFFlt7cdJcNxlF_j4sV-FcBYMPuA",
        "https://play-lh.googleusercontent.com/NwspKLwZ0PYfrm-jYG0Cp1IhIY8WJE1YUER5KrYVdSlQzGZAC-IejQb6poarP83vbvCH",
        "https://play-lh.googleusercontent.com/wu3swTDnQ6BeZVC494V_mDLzNlM-KuH4wPAQNa2OVI9rV7d7dWi4QJGHUtgwpOeaet0",
        "https://play-lh.googleusercontent.com/RaGIKMn0QGNBPiGnxOecM8rJhM13zURdvPIBB2Zj-s9EYNGlOHJAgwbj80UH_XKrng",
        "https://play-lh.googleusercontent.com/0QGjDR2LQT0xZNdnhbvHAN23NGmmSeDx-jgqpPWcYgXLFRu4ASWxQLV2zXl7XlcyS34"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 12, 2023",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729020269,
    "version": "3.9.1",
    "comments": [],
    "appId": "com.prepass.mobile.app",
    "url": "https://play.google.com/store/apps/details?id=com.prepass.mobile.app&hl=en&gl=us"
}