{
    "title": "CorrectPay",
    "description": "JailFunds by VendEngine allows users to make commissary, phone, bonding, and monitoring deposits instantly for incarcerated loved ones.\r\n\r\nUsers can deposit funds in less than 30 seconds from anywhere in the world.  Users can also schedule and join video visitations and send gifts to incarcerated loved ones from within the app.\r\n\r\nThe app also provides community, health and re-entry resources for families and incarcerated loved ones.",
    "descriptionHTML": "JailFunds by VendEngine allows users to make commissary, phone, bonding, and monitoring deposits instantly for incarcerated loved ones.<br><br>Users can deposit funds in less than 30 seconds from anywhere in the world.  Users can also schedule and join video visitations and send gifts to incarcerated loved ones from within the app.<br><br>The app also provides community, health and re-entry resources for families and incarcerated loved ones.",
    "summary": "Make commissary deposits and join video visits with your loved ones in jail",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 285177,
    "score": 3.02,
    "ratings": 899,
    "reviews": 321,
    "histogram": [
        341,
        62,
        89,
        44,
        358
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Tyler Technologies, Inc",
    "developerId": "Tyler+Technologies,+Inc",
    "developerEmail": "jailfundshelp@gmail.com",
    "developerWebsite": "http://www.jailfunds.com",
    "developerAddress": "Tyler Technologies\nOne Tyler Drive\nYarmouth, ME 04096",
    "privacyPolicy": "http://vendengine.com/privacy/",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/_d6qewn1w4GL340QHVi4DxeoPHQ3amNVb1L2sRbjLZUiQaYjsLm9fJDIxC-9O4JqewxB",
    "headerImage": "https://play-lh.googleusercontent.com/SUo4NZkeAGHQ6O2pb8yl157auUEQi4flatC0ZX071YsFwYZwLViWVlWtIuHr1mCfBUs",
    "screenshots": [
        "https://play-lh.googleusercontent.com/TbbwPrkScAFGheZXgFz_qaLN8-mGhFLsndaBFQ41luNuxsct101_NOdil7bi0qOOvg",
        "https://play-lh.googleusercontent.com/2odpZX6zzI5WkJxh4HGFHpUDBwfpvLoZ9JnbWmQjKtm-dDakb9aQALGgwLfzlQpRO-k",
        "https://play-lh.googleusercontent.com/RKsqlf-hbovmpkUNuTpnCwBgFA4ODgf7yFzLhA7rMeflOevz6XnP0uC-ZjezMcs4PH8",
        "https://play-lh.googleusercontent.com/29sjnlOU_b-8n5-PChVHQWtmlOF-50GceetQteSYvuUQedKosOxWTMJCU_f6O87600I",
        "https://play-lh.googleusercontent.com/hgUg861xSFQJ4TzXDlDOS5ykt9noYcMivXKHoCQVhg-RuO2gjZdzKSzubGI-o4LZtDk",
        "https://play-lh.googleusercontent.com/sgrY3ub6EHg15pspOFPIaFU5WFctPEwdAv4Kjfyq3h0kJ5bBn-AQ4SsMUKZ8YybkrLA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 8, 2021",
    "lastUpdatedOn": "Oct 4, 2024",
    "updated": 1728067770,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.mwp.vendengineapp.cp",
    "url": "https://play.google.com/store/apps/details?id=com.mwp.vendengineapp.cp&hl=en&gl=us"
}