{
    "title": "Google Home",
    "description": "Create a more organized and personalized smart home with Google Home. Set up, manage, and control your Google Nest, Wifi, and Chromecast devices, plus thousands of compatible smart home products like lights, cameras, thermostats, and more \u2013 all from the Google Home app.\r\n\r\n Personalize your home view.\r\nPin your most-used devices, automations, and actions to the Favorites tab for easy access right when you open the app. View your Nest cameras and doorbell live feeds, and easily scan through event history. Set up and manage Routines in the Automations tab. And quickly edit any permissions in the consolidated Settings tab.\r\n\r\nUnderstand what\u2019s going on at home with a glance.\r\nThe Google Home app is designed to show you the status of your home and keep you up to date with what you may have missed. Check in on your home anytime and see a recap of recent events.\r\n\r\nControl your home from anywhere.\r\nGoogle Home for Wear OS allows you to control compatible smart home devices from your watch. Turn on the lights, adjust the thermostat, or get an alert when there\u2019s a person or package at your front door. Use the favorites tile or add a device to your watch face to make managing your home as easy as a tap on the wrist.\r\n\r\nA helpful home is a private home.\r\nProtecting your privacy starts with one of the world\u2019s most advanced security infrastructures, which we build directly into Google products so they\u2019re secure by default. And Google uses your compatible devices and data to make your home helpful, but only in the ways you allow. Visit the Google Nest Safety Center at safety.google/nest to learn more about how we protect your information and respect your privacy.\r\n\r\n* Some products and features may not be available in all regions. Compatible devices required.",
    "descriptionHTML": "Create a more organized and personalized smart home with Google Home. Set up, manage, and control your Google Nest, Wifi, and Chromecast devices, plus thousands of compatible smart home products like lights, cameras, thermostats, and more \u2013 all from the Google Home app.<br><br> Personalize your home view.<br>Pin your most-used devices, automations, and actions to the Favorites tab for easy access right when you open the app. View your Nest cameras and doorbell live feeds, and easily scan through event history. Set up and manage Routines in the Automations tab. And quickly edit any permissions in the consolidated Settings tab.<br><br>Understand what\u2019s going on at home with a glance.<br>The Google Home app is designed to show you the status of your home and keep you up to date with what you may have missed. Check in on your home anytime and see a recap of recent events.<br><br>Control your home from anywhere.<br>Google Home for Wear OS allows you to control compatible smart home devices from your watch. Turn on the lights, adjust the thermostat, or get an alert when there\u2019s a person or package at your front door. Use the favorites tile or add a device to your watch face to make managing your home as easy as a tap on the wrist.<br><br>A helpful home is a private home.<br>Protecting your privacy starts with one of the world\u2019s most advanced security infrastructures, which we build directly into Google products so they\u2019re secure by default. And Google uses your compatible devices and data to make your home helpful, but only in the ways you allow. Visit the Google Nest Safety Center at safety.google/nest to learn more about how we protect your information and respect your privacy.<br><br>* Some products and features may not be available in all regions. Compatible devices required.",
    "summary": "Set up and control your compatible Nest, Chromecast, and Google Home devices.",
    "installs": "500,000,000+",
    "minInstalls": 500000000,
    "realInstalls": 851111595,
    "score": 4.196917,
    "ratings": 2955449,
    "reviews": 160729,
    "histogram": [
        362102,
        97306,
        158835,
        315461,
        2021734
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Google LLC",
    "developerId": "5700313618786177705",
    "developerEmail": "apps-help@google.com",
    "developerWebsite": "http://cast.google.com/chromecast/",
    "developerAddress": "1600 Amphitheatre Parkway, Mountain View 94043",
    "privacyPolicy": "https://policies.google.com/privacy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/vr1isZKzTtlok9P81H6cR98iqpPhkuQHJp19Z5kPej3QlhNTnLohXpqcgMqrQpyegA",
    "headerImage": "https://play-lh.googleusercontent.com/3ASOKG4Qo3UlOpX2wR13H_H5kSRKdTfN3HtESdZGYv81d4OAiUASothf_0ChesmcU0AZ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/bQM4ljoeyoEci2C4VrVNdZVdpIcjgdERh310JNRke9F5Oc5YcNX-GrpmHkC57kZacok",
        "https://play-lh.googleusercontent.com/TPVQ0vVgH4Oc-69sPdj_0HKnG0JHF-9qDOeWrQnumPlD8kwL7a8YXNN2u1ensigRQyo",
        "https://play-lh.googleusercontent.com/ALPx7Mx2ZEXnsBrDo5SnoGNlY1gBN9r_Da4ThhTEOpKJnenVBjDy47U0fy84WL2F5hiI",
        "https://play-lh.googleusercontent.com/gvURHPwLWI9lbObR5WQsf_Etm0wFWT2N3FWB6lSFxrA2FUs7Ys7SyCfCF4b6sMd1pP-c",
        "https://play-lh.googleusercontent.com/-Ezf57c0J04e0CAWVL-KnpL33iQkZUY_tcMzyzwkcxtoq9XXBe-REL57G06K_XZQMQ",
        "https://play-lh.googleusercontent.com/UjfikktKKjXKwTQypMw8LiUGu0wnL1HYhM1ECeQwzUB2xAxiGS8I3SkA0kNbyvp76u4",
        "https://play-lh.googleusercontent.com/IXkB1dn4CMRANaHB7aSUim9cqXizLDAEP6AJiYdsoODWHlmecLxOAVLru-9qqzj5DE2F",
        "https://play-lh.googleusercontent.com/3RAxj-UA0xqhoJx2LSUYIIU6ZT2WPSmI8AKMxtULQy9nWmiew-xYoupUK7m7zBVJDKY",
        "https://play-lh.googleusercontent.com/B11sfELk2Sj43yghyUyVi9hWcMeVnXLOaDknfFhzFTzoInhvHQJIdtTjbqecuuEwBn1z",
        "https://play-lh.googleusercontent.com/pKf3JBz2lUQEhN3RROcsF8ava-SDvj1ectVG2h1X4nd7I5XmE7tNEApOWg_Ayg5ZW-Y",
        "https://play-lh.googleusercontent.com/bsbiOoIKqQfm9ULaHC9HWZmRvOQ4wPpBEohqUs_JuaLtzJ5gcbbTdwUSe0pwoyjADw",
        "https://play-lh.googleusercontent.com/Fx58HAYp_kAChowce4rb-FQGR9_Y96KW6OivWINfPDR8S83LXQcA93ddYD3yUrZk7xY",
        "https://play-lh.googleusercontent.com/v4dtVnFC_KP1c80UtAoEuxjnZqYYzGjponAGUiD-Uyo6e860kgPFwCi7XtMoweh8lg",
        "https://play-lh.googleusercontent.com/rr_5o8MdLCDviMWJQZAuMiuX6VubCIMXhdgp-OZUHVQ_RYsIHoSV6ETUdo-5gAxSfus"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 18, 2013",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729612282,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.google.android.apps.chromecast.app",
    "url": "https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app&hl=en&gl=us"
}