{
    "title": "Listenary-Enjoy AudioBooks",
    "description": "Discover a new era of entertainment with Listenary, the platform for audiobook and story series enthusiasts worldwide. From romance and mystery to fantasy and suspense thriller, our extensive library is curated to bring you a wealth of genres and storytelling formats, making every listening experience unique and immersive.\r\n\r\nUnlimited Entertainment Choices:\r\nPeruse our vast library and find new stories constantly being added. Whether you're a fan of gripping thrillers or heartwarming romances, Listenary has something for all tastes.\r\n\r\nFlexible Listening Options:\r\nEnjoy your favorite audiobooks seamlessly across multiple devices. With our intuitive interface, you can easily navigate between chapters and skip back with a simple tap.\r\n\r\nTailored Listening Experience:\r\nOur built-in player offers customizable features, including adjustable playback speed and a convenient sleep timer, providing a comfortable and personalized listening adventure.\r\n\r\nOffline Access:\r\nDownload episodes for offline enjoyment and take your stories with you everywhere, whether you're commuting, working out, or relaxing at home.\r\n\r\nPremium Listening Experience:\r\nPremium service without interruption or delay, making your listening journey uninterrupted. Experience audiobooks the way they were meant to be enjoyed.\r\n\r\nSay goodbye to repetitive music and conventional books; step into the future of storytelling with Listenary. Enrich your listening habits and dive into our universe of audio stories whenever your ears are free.\r\n\r\nJoin Listenary today and lay back as immersive, high-quality storytelling transports you to another world.\r\n\r\nLove Listenary?\r\nContact us with email: listenary.service@hotmail.com",
    "descriptionHTML": "Discover a new era of entertainment with Listenary, the platform for audiobook and story series enthusiasts worldwide. From romance and mystery to fantasy and suspense thriller, our extensive library is curated to bring you a wealth of genres and storytelling formats, making every listening experience unique and immersive.<br><br>Unlimited Entertainment Choices:<br>Peruse our vast library and find new stories constantly being added. Whether you&#39;re a fan of gripping thrillers or heartwarming romances, Listenary has something for all tastes.<br><br>Flexible Listening Options:<br>Enjoy your favorite audiobooks seamlessly across multiple devices. With our intuitive interface, you can easily navigate between chapters and skip back with a simple tap.<br><br>Tailored Listening Experience:<br>Our built-in player offers customizable features, including adjustable playback speed and a convenient sleep timer, providing a comfortable and personalized listening adventure.<br><br>Offline Access:<br>Download episodes for offline enjoyment and take your stories with you everywhere, whether you&#39;re commuting, working out, or relaxing at home.<br><br>Premium Listening Experience:<br>Premium service without interruption or delay, making your listening journey uninterrupted. Experience audiobooks the way they were meant to be enjoyed.<br><br>Say goodbye to repetitive music and conventional books; step into the future of storytelling with Listenary. Enrich your listening habits and dive into our universe of audio stories whenever your ears are free.<br><br>Join Listenary today and lay back as immersive, high-quality storytelling transports you to another world.<br><br>Love Listenary?<br>Contact us with email: listenary.service@hotmail.com",
    "summary": "Your Destination for Audiobook and Story Entertainment",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 33558,
    "score": 4.6890244,
    "ratings": 372,
    "reviews": 119,
    "histogram": [
        15,
        6,
        10,
        8,
        328
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "fancyLab",
    "developerId": "fancyLab",
    "developerEmail": "listenary.service@hotmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://listenaries.com/privacy",
    "genre": "Trivia",
    "genreId": "GAME_TRIVIA",
    "categories": [
        {
            "name": "Trivia",
            "id": "GAME_TRIVIA"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/1FiTU5lsSaJIMQKbnKfjJ5sjv8UH611VdK2GJsO56O-2as3tqc48C9LTaM93ALXAsjEb",
    "headerImage": "https://play-lh.googleusercontent.com/Wazpt7DyfZquO-UGV8zZbz_v49y5W_NPpPhFx1tKuyyJDDOJ_AMIutvtGBe4h_rKBBY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/acs-iKNCvJLTfhKB4_kFMV54lGdYBRBFZD8CSd4e4Sv10DQcJCS-D-16_bZraETQd2Nn",
        "https://play-lh.googleusercontent.com/2dCMhGBJHr0eTea5lAupcb7Ie6cy6kioQiLNLmwv3TG_plNYwg2dtGhEn996q7gdtMU",
        "https://play-lh.googleusercontent.com/bzj22c1hJ6Q5DXwE7sGh9HWt_yss7m4vg8yLgMr07ZKkeuSn_ivEtgF9iKZkk276tAFE",
        "https://play-lh.googleusercontent.com/cytpqtShx3gCWN9Ndb88GD0spWPACz2rhLqIlYn7XpfISTBF2kEGXFHvio82xoXhPo8",
        "https://play-lh.googleusercontent.com/1JOoNvZ1T0SobgyBv61gGXxyBVObBGnKasOVF-WuTK_IswtfQkyxUAQ277OEjCLq-2c"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Sexual Themes",
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 24, 2023",
    "lastUpdatedOn": "Oct 10, 2024",
    "updated": 1728558615,
    "version": "1.0.5",
    "comments": [],
    "appId": "com.wallpaper4d.parallax4d.pixel3d.topwallpapers.best.live.wallpaper.video.clock.camera.hdwallpapers.free.pro",
    "url": "https://play.google.com/store/apps/details?id=com.wallpaper4d.parallax4d.pixel3d.topwallpapers.best.live.wallpaper.video.clock.camera.hdwallpapers.free.pro&hl=en&gl=us"
}