{
    "title": "Quranly",
    "description": "WHAT IS QURANLY?\r\nA habit-building Quran app that brings a habit-centered, routine-driven approach to Quran reading.\r\nUnlike traditional Quran apps, this is a habit-building Quran app that works. It gives you a visual representation of your progress. Daily.\r\n\r\nHow Quranly can benefit you?\r\n1. Habit streaks\r\n2. Balanced design\r\n3. Reminders\r\n4. Tracker\r\n5. Challenges\r\n6. Progress",
    "descriptionHTML": "WHAT IS QURANLY?<br>A habit-building Quran app that brings a habit-centered, routine-driven approach to Quran reading.<br>Unlike traditional Quran apps, this is a habit-building Quran app that works. It gives you a visual representation of your progress. Daily.<br><br>How Quranly can benefit you?<br>1. Habit streaks<br>2. Balanced design<br>3. Reminders<br>4. Tracker<br>5. Challenges<br>6. Progress",
    "summary": "The smartest way to develop the habit of reading the Quran.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1882737,
    "score": 4.5825243,
    "ratings": 10101,
    "reviews": 254,
    "histogram": [
        583,
        89,
        381,
        763,
        8215
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $194.99 per item",
    "developer": "Quranly",
    "developerId": "Quranly",
    "developerEmail": "salam@quranly.app",
    "developerWebsite": "https://quranly.app",
    "developerAddress": null,
    "privacyPolicy": "https://www.quranly.app/privacy-policy",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/jn1PXBYcLxoVgGweuFhxnGIteJK7ZDdBt4X23IDQCy3KcVPowfg8PJYbXU_ZWVpQx-c",
    "headerImage": "https://play-lh.googleusercontent.com/kLXzonAljz3GPtyMp5mw0z6629IXcyDXf8-05cjJBqGxCOvZonyXvh3icmyFul9n8Q4q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/kHS1VUUIRCf1hi4q2LxegDOU8AfnPUgxUHrj5ebyzLWxN-Lb6CVQOt9S5l5yeL94n7k",
        "https://play-lh.googleusercontent.com/9zqoR42RRdkUeVl7VBm_IJQ9eBDl-SGeDO_1sFCXNOK1yFfOdlq6fVo3KLp5jAnJ3oo",
        "https://play-lh.googleusercontent.com/vR8_n55YjAx_mXmSS_B7HpXS_qyHqc2dHbCzChafNhhStban43SP9cjw1PukwArbTXyE",
        "https://play-lh.googleusercontent.com/lssKA2nJMZnFQHMJuK_kaXakGZo5BZZrfF1vsBjOz13sjRFQ3cQPTE2_k7NvxsMoIA",
        "https://play-lh.googleusercontent.com/WhLmlCXQE4mk1Eq0wHtPXQGh7z8M2nUdcWuWSX8GdPmoPEaUK93IzQVc_SJ9qzMwCko",
        "https://play-lh.googleusercontent.com/B-klJoIYviZ6fWOh3Hz81owMiQsicBzMooPPs9JtUeXCOmu4N78eXGhrtiSbd-dcQMIe",
        "https://play-lh.googleusercontent.com/pXkhA7DgJ-kBT84lzoJfC8C2y-awr82nxdlcSRUIrJYiPwyyM3QM3KtKf2sGcdEaHuGQ",
        "https://play-lh.googleusercontent.com/nTKNEbn8D9khz0DsAqXvzRSCuX3GDN2LV_GPRxpQWcJnyTBFXnVoPNj9b3tFe81kr1Q",
        "https://play-lh.googleusercontent.com/LSsFgiGufYqayCElCYuvQJFUuxXlW3B9CSUSkvCSYo1vROVFIp4iIHsxZGcf1gbUEXo",
        "https://play-lh.googleusercontent.com/Qwi0hMtrpndtdf_l7_iphI5_QBvs_9m0oqBpMZ6K58gkM-j6RaWhpYBV1hUORH7Hxw",
        "https://play-lh.googleusercontent.com/Tl2qXehYNhkbvlzyg6AA9E_OpO2Wb4hQtnO0HZeMqHMbpReO7WE9UBnGnYXo_gQN2iHf",
        "https://play-lh.googleusercontent.com/o30ZdM48T2m6ZZFg0D38MOH1_onVYM3zV5JTXIFCobTQVJeGMK4z3iyhN_Mz1-O7kOQ",
        "https://play-lh.googleusercontent.com/izGjblswf92Sp7jkOo-bqHAMmxAfJfEp7oTZwkkHW7vHsjhXmQjlO70wAk1KiIS4U-w",
        "https://play-lh.googleusercontent.com/htAk6CuJSlhVpfm7obae72bZg2grAIUtZCaIar9flEXcJ8Rj0szXJPPuDsbhNrXc_9C3",
        "https://play-lh.googleusercontent.com/wkYql87bi_Z_20iJjlOqZjUQ2HluHTgknO9bmLoNV-97Vq4DKUvo1Twhli3prL7ctg",
        "https://play-lh.googleusercontent.com/nVQm6dFNb16WsnzXVWg88GMsIzSeEV-A-1BrgsLqnWAGGq-b7N6l8jstNEIJUZ565JY",
        "https://play-lh.googleusercontent.com/RWZlkrVwFZUCzLzK-iAOuhrZzBk87OJMrEVA2TCiJTGETqsvtg4BGG0PS_CqiVLfS6Yv",
        "https://play-lh.googleusercontent.com/lT-BFh_6EPUbS963JXDFMxIGuHiX7QeZGFKBnixGXFi4M-76ISY63cxRBlHZs_Lsghu_",
        "https://play-lh.googleusercontent.com/3IurbLEVGJEkoWw-RQn0yYeiq3mwAL3Eu8RAXMRC2Qix3JNM5XbZgDT7YlKJzPyfIQ",
        "https://play-lh.googleusercontent.com/Wb_0zQfxMvDDBf-Ux_DOKYX6U5xNNtvcmPo0KYLR51kCkvRvT7gmbwvhg7y0J4TmMyGz",
        "https://play-lh.googleusercontent.com/NUi022GtpK0okMIyKKHbBmazcRsLGrkE-pIJyGEa_HWNP27I_5C0zntUI3Ouv_Ix8qU"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 6, 2021",
    "lastUpdatedOn": "Sep 13, 2024",
    "updated": 1726229719,
    "version": "2.0.42",
    "comments": [],
    "appId": "com.quranly.app",
    "url": "https://play.google.com/store/apps/details?id=com.quranly.app&hl=en&gl=us"
}