{
    "title": "vidIQ for YouTube",
    "description": "vidIQ is the #1 app for YouTube channel management including Video SEO, and real-time YouTube Analytics.\r\n\r\nJoin the million+ YouTube Creators who rely on vidIQ to research, plan, optimize, and publish amazing video content that generates significant views and subscribers. \r\n\r\nvidIQ is used by some of the top YouTube Creators in all niches and categories like gaming, food, beauty, tech, business, education, finance, health & fitness, productivity, sports, travel, lifestyle, vlogging, and many more. \r\n\r\nvidIQ is the perfect app for beginners with zero subscribers, and also includes a suite of easy to use tools that larger creators, brands, agencies, and publishers leverage to identify what content to rank for and how to unlock next level YouTube Channel analytics.\r\n\r\nDiscover new content ideas in seconds with the Keyword Tool. You\u2019ll quickly identify new keyword opportunities, vidIQ suggests a wealth of related keywords and trending videos to help you understand what your audience is really searching for. These Video SEO tools provide actionable analytics and insights that no other app offers. \r\n\r\nDownload the vidIQ app today and unlock:\r\n\r\n* Real-time insights into your most popular videos\r\n* The top search terms that drive traffic and views to your channel so you can instantly see which content to double down on\r\n* Insights into the most viewed videos published by other channels in your niche\r\n* A comprehensive dive into your channel performance compared to others \r\n* And more\r\n\r\nVideo SEO Tools & Keyword Research includes:\r\n\r\n* The ability to Identify what content you could rank for with real-time keyword search volume \r\n* Insights into how many other channels are publishing content around those same keywords\r\n* The top videos around a particular keyword by highest views, and also average views and subscribers\r\n* Access to vidIQ's machine learning to easily find new ideas around related keywords which have higher search volumes but less competition from other creators\r\n* Confirmation of the top channels ranking for the search term you\u2019re interested in, and all their trending videos to inspire your next video\r\n* The ability to subscribe to any search term to get alerted instantly about any trending topics in any language or country\r\n* Discovering what similar channels to you are doing to get views & subscribers \r\n* Understanding what videos are trending for similar channels and catch the trend before it's too late\r\n* Uncovering the best times and days to post which creates a higher probability of being recommended by YouTube\r\n* Finding the top channels your subscribers are watching and using the insights from the tools to understand what they're doing to attract similar subscribers\r\n* Discover the videos your subscribers are watching on other channels, and start implementing what they're doing in your own content\r\n\r\nThe vidIQ app syncs across all devices so you'll be able to continue where you left off and store your trend alerts, channel followings, and more in your free vidIQ account. \r\n\r\nRead more about our terms and conditions here:\r\n\r\nTerms of service: https://vidiq.com/terms/\r\nPrivacy policy: https://vidiq.com/privacy/",
    "descriptionHTML": "vidIQ is the #1 app for YouTube channel management including Video SEO, and real-time YouTube Analytics.<br><br>Join the million+ YouTube Creators who rely on vidIQ to research, plan, optimize, and publish amazing video content that generates significant views and subscribers. <br><br>vidIQ is used by some of the top YouTube Creators in all niches and categories like gaming, food, beauty, tech, business, education, finance, health &amp; fitness, productivity, sports, travel, lifestyle, vlogging, and many more. <br><br>vidIQ is the perfect app for beginners with zero subscribers, and also includes a suite of easy to use tools that larger creators, brands, agencies, and publishers leverage to identify what content to rank for and how to unlock next level YouTube Channel analytics.<br><br>Discover new content ideas in seconds with the Keyword Tool. You\u2019ll quickly identify new keyword opportunities, vidIQ suggests a wealth of related keywords and trending videos to help you understand what your audience is really searching for. These Video SEO tools provide actionable analytics and insights that no other app offers. <br><br>Download the vidIQ app today and unlock:<br><br>* Real-time insights into your most popular videos<br>* The top search terms that drive traffic and views to your channel so you can instantly see which content to double down on<br>* Insights into the most viewed videos published by other channels in your niche<br>* A comprehensive dive into your channel performance compared to others <br>* And more<br><br>Video SEO Tools &amp; Keyword Research includes:<br><br>* The ability to Identify what content you could rank for with real-time keyword search volume <br>* Insights into how many other channels are publishing content around those same keywords<br>* The top videos around a particular keyword by highest views, and also average views and subscribers<br>* Access to vidIQ&#39;s machine learning to easily find new ideas around related keywords which have higher search volumes but less competition from other creators<br>* Confirmation of the top channels ranking for the search term you\u2019re interested in, and all their trending videos to inspire your next video<br>* The ability to subscribe to any search term to get alerted instantly about any trending topics in any language or country<br>* Discovering what similar channels to you are doing to get views &amp; subscribers <br>* Understanding what videos are trending for similar channels and catch the trend before it&#39;s too late<br>* Uncovering the best times and days to post which creates a higher probability of being recommended by YouTube<br>* Finding the top channels your subscribers are watching and using the insights from the tools to understand what they&#39;re doing to attract similar subscribers<br>* Discover the videos your subscribers are watching on other channels, and start implementing what they&#39;re doing in your own content<br><br>The vidIQ app syncs across all devices so you&#39;ll be able to continue where you left off and store your trend alerts, channel followings, and more in your free vidIQ account. <br><br>Read more about our terms and conditions here:<br><br>Terms of service: https://vidiq.com/terms/<br>Privacy policy: https://vidiq.com/privacy/",
    "summary": "Boost your YouTube channel with vidIQ: AI-powered tools for titles, tags, ideas.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 5605036,
    "score": 4.642743,
    "ratings": 259492,
    "reviews": 1511,
    "histogram": [
        6597,
        4118,
        11556,
        30592,
        206501
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$9.99 - $199.99 per item",
    "developer": "vidIQ",
    "developerId": "vidIQ",
    "developerEmail": "googleplay@vidiq.com",
    "developerWebsite": "http://vidiq.com",
    "developerAddress": "548 Market St #70172, San Francisco, CA 94104, USA",
    "privacyPolicy": "https://vidiq.com/privacy/",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/dK_aPCxnVWxv1agmDGUsPCP4ClImkoFcWpequyJewqudNkgqLlpc3B21aEtQhstriA",
    "headerImage": "https://play-lh.googleusercontent.com/1U1P-kOQuR1F1sV17VL9uTLYxPdGZs2aTmT7_zPwrX5qgR0wW3IS3P4UQa9Vs89XJFq3",
    "screenshots": [
        "https://play-lh.googleusercontent.com/haymHGFIY_A6Uhd3VjlYBj-_Ye2AnmGb8WB0VBrLrICYGBvuOsRLzx_gdykr-Qb1ys4",
        "https://play-lh.googleusercontent.com/_VSQ8qHNnpkWVMMcvFoggIFdtahtBqzLkoq47oEhC7ruX3yUUg_-hxjRi25MxQMssN4",
        "https://play-lh.googleusercontent.com/G5XGsx3MnOOioBNna5aLUCKsSxll-ywn_dYr2a326svOfhdBo56Ww6-2aLNGHgBQrw",
        "https://play-lh.googleusercontent.com/MzBwsCt8hOjB_8k5P0edb5pqg063nXfd5CgHeQthCb8ZJUi08bRl8OrIEMGIGm0wDPU",
        "https://play-lh.googleusercontent.com/CbrNJiaVLoAc4qTinoGbi9ZvHgiPqIQ2SeLuM2TXoy1MBhegVTyuIs6BBMEP55ylYw",
        "https://play-lh.googleusercontent.com/9L538lWwnGX6yHNrqWIFnPJZX8uDqEkoUdumGNCGAkAzN_xATm7cl-zx5U9mPqpP9tA",
        "https://play-lh.googleusercontent.com/Fw7IPkbq25oGbppTMdNIUoLdulC5JjPXKOlbnSsL_kELkJ3GkjbzaRKt3TIFPurAwP1O"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 3, 2020",
    "lastUpdatedOn": "Oct 23, 2024",
    "updated": 1729707336,
    "version": "2.2.58",
    "comments": [],
    "appId": "com.vidiq.app",
    "url": "https://play.google.com/store/apps/details?id=com.vidiq.app&hl=en&gl=us"
}