{
    "title": "File Cleaner & Antivirus",
    "description": "Main Function\r\n1)Antivirus,virus remover\r\n2)Big File Scan and clean\r\n3)Photo Compress&Video Compress\r\n4)Find out hidden images\r\n5)similar photo cleanup\r\n6)find out hidden videos\r\n7)blurry photo cleanup\r\n8)Non-photo Cleanup,Screenshot Cleanup",
    "descriptionHTML": "Main Function<br>1)Antivirus,virus remover<br>2)Big File Scan and clean<br>3)Photo Compress&amp;Video Compress<br>4)Find out hidden images<br>5)similar photo cleanup<br>6)find out hidden videos<br>7)blurry photo cleanup<br>8)Non-photo Cleanup,Screenshot Cleanup",
    "summary": "Virus remover, File Cleaner and Antivirus",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4649678,
    "score": 4.144231,
    "ratings": 5280,
    "reviews": 98,
    "histogram": [
        506,
        200,
        602,
        654,
        3298
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Gallery Work",
    "developerId": "Gallery+Work",
    "developerEmail": "gallerywork123@gmail.com",
    "developerWebsite": "https://f797240e5.app-ads-txt.com",
    "developerAddress": null,
    "privacyPolicy": "https://sites.google.com/view/fileantivirus/home",
    "genre": "Productivity",
    "genreId": "PRODUCTIVITY",
    "categories": [
        {
            "name": "Productivity",
            "id": "PRODUCTIVITY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/n8pgoKO6ajatwn4GMsMSGC_uJZzQLJ7s_aN-EaNy59XhzhyXknRQrvbAIATm7QlhPH1g",
    "headerImage": "https://play-lh.googleusercontent.com/8YGF-UT7mJIGvYVyUPmFEI8QlaTdabylVxg8gpN_982s2naIGj3aquu0Zai6Wk__zGQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ThGXq9P4xwcDQm8l83ci3-KFjRfpJxaxdbsxZn8xEr6hPwOQObms4-0QxPcyn1k_dsM",
        "https://play-lh.googleusercontent.com/yP2Ha6TReoeRBi9cyAAE0WE1sVWzsQO7AumznkzIjL-S4PZdLUyDNRhIJDEehMuaBA",
        "https://play-lh.googleusercontent.com/op6NETf-C8PGucpMGnQB4JBBFkT0KFEQ6YTPYq9WfhaXgfiI_QUiFYM8ioXBNwiszJE",
        "https://play-lh.googleusercontent.com/a_4PNXGEZ_gOa9Nc51JTWO5JqfoDZkKp3U4mVrNSaAvRJXTx2XAP_coSFBVMZn73qvw",
        "https://play-lh.googleusercontent.com/YuM6tKZJZR-BeB-nkK0H4Xc88sggl82oKtwE1-19OxXQhQPsJ9wheTMHSezhgMmO2-h5",
        "https://play-lh.googleusercontent.com/ZSl5g76UgNV7tEh2gCTrwxqnvfGwTrDYw07bstDESxIzxkAi4Xyy42Pkdt_utkN04mk3"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 15, 2023",
    "lastUpdatedOn": "Sep 29, 2024",
    "updated": 1727610659,
    "version": "1.1.9",
    "comments": [],
    "appId": "com.app.security.antivirus.gp",
    "url": "https://play.google.com/store/apps/details?id=com.app.security.antivirus.gp&hl=en&gl=us"
}