{
    "title": "Amazon Alexa",
    "description": "Use the Amazon Alexa App to set up your Alexa-enabled devices, listen to music, create shopping lists, get news updates, and much more. The more you use Alexa, the more she adapts to your voice, vocabulary, and personal preferences.\r\n\r\nDISCOVER MORE\r\n\u2022 Get more out of your Echo device through personalized feature recommendations from Alexa\r\n\u2022 Discover and enable recommended Alexa skills\r\n\u2022 Pick up where you left off directly from the home feed with lists, shopping, or recently played Music and Books\r\n\r\nMANAGE YOUR DEVICES\r\n\u2022 Set up your Alexa-enabled devices, control or check status of your compatible smart lights, locks and thermostats at home or on the go\r\n\u2022 Create routines to automate your smart home devices\r\n\r\nMUSIC & BOOKS\r\n\u2022 Connect to music services like Amazon Music, Pandora, Spotify, TuneIn, and iHeartRadio. Choose a song or playlist and listen on your Alexa-enabled devices\r\n\u2022 Create speaker groups to play music across your compatible Echo devices for multi-room music\r\n\r\nORGANIZE YOUR DAY\r\n\u2022 View and edit shopping and to-do lists on the go, get weather and news updates, manage timers and alarms, and more\r\n\r\nSTAY CONNECTED\r\n\u2022 Use Drop In from your app to connect instantly with your compatible Echo devices, like a two-way intercom \r\n\u2022 Call or message supported Alexa-enabled devices, at no additional cost",
    "descriptionHTML": "Use the Amazon Alexa App to set up your Alexa-enabled devices, listen to music, create shopping lists, get news updates, and much more. The more you use Alexa, the more she adapts to your voice, vocabulary, and personal preferences.<br><br>DISCOVER MORE<br>\u2022 Get more out of your Echo device through personalized feature recommendations from Alexa<br>\u2022 Discover and enable recommended Alexa skills<br>\u2022 Pick up where you left off directly from the home feed with lists, shopping, or recently played Music and Books<br><br>MANAGE YOUR DEVICES<br>\u2022 Set up your Alexa-enabled devices, control or check status of your compatible smart lights, locks and thermostats at home or on the go<br>\u2022 Create routines to automate your smart home devices<br><br>MUSIC &amp; BOOKS<br>\u2022 Connect to music services like Amazon Music, Pandora, Spotify, TuneIn, and iHeartRadio. Choose a song or playlist and listen on your Alexa-enabled devices<br>\u2022 Create speaker groups to play music across your compatible Echo devices for multi-room music<br><br>ORGANIZE YOUR DAY<br>\u2022 View and edit shopping and to-do lists on the go, get weather and news updates, manage timers and alarms, and more<br><br>STAY CONNECTED<br>\u2022 Use Drop In from your app to connect instantly with your compatible Echo devices, like a two-way intercom <br>\u2022 Call or message supported Alexa-enabled devices, at no additional cost",
    "summary": "ALWAYS READY, CONNECTED, AND FAST. Just ask.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 158144563,
    "score": 4.2631483,
    "ratings": 4263146,
    "reviews": 132420,
    "histogram": [
        461171,
        128906,
        211511,
        486857,
        2974688
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "Amazon Mobile LLC",
    "developerId": "Amazon+Mobile+LLC",
    "developerEmail": "echo-support@amazon.com",
    "developerWebsite": "http://www.amazon.com/",
    "developerAddress": "AMZN Mobile LLC\n410 Terry Ave N\nSeattle, WA 98109",
    "privacyPolicy": "https://www.amazon.com/gp/help/customer/display.html?nodeId=201909010",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/X24ol80nJS3F_nUg3HlqWWzSxEnDHeAI34quN8rTjILQOoebd0Be3ZFBQrKAtMX2XyE",
    "headerImage": "https://play-lh.googleusercontent.com/few2-5Trc-zLyTxtE7nn5dns85hG2bU0kemAddz3-Vkmfd3fwWy9iYhA5SDaARm1LgM",
    "screenshots": [
        "https://play-lh.googleusercontent.com/QDFNlMjQlHeOfCfpKPh24T318uG0TnYrheaKYie2PnglDyucy424ZJDCFKmLOuVysFhe",
        "https://play-lh.googleusercontent.com/TE-L02w1aFZzVTq_58QDo2xcJLgqcwtvon7sAYTKaDPqPUXQ5cAQXlCTtXebDVW8Euo",
        "https://play-lh.googleusercontent.com/B8fPAOzLJ_SMi5-3f8SO_hOLgcgVVAOvKGG9vgdvw51YsIgmXW3pUuPp4XKLcOVVyA",
        "https://play-lh.googleusercontent.com/iSr6HvNE7nO04kmgBdB-DLACnOVL03kQPQC3XMuhdL7Seo4h8ZMFFsdUag1uoU5eZ4Y",
        "https://play-lh.googleusercontent.com/3naK9L-NxNDDSyRpfugTbEUwYJfddda0vidU33d4O-kkc0TGeOb06aYR9VfKaXCZ-Ao",
        "https://play-lh.googleusercontent.com/2gU4Ai3ZCDVMz0NfaGxUvNV_Ln2KyttMfQ3PHB78z-pPDjQBwxatMG9nc6Eg9WukbaI",
        "https://play-lh.googleusercontent.com/gpcsAZdd2CsLo1piudUxr3Lo_slfYjqJQyrRv6l78ytFAtIUiwI5rs57E2PRBdYmKQ",
        "https://play-lh.googleusercontent.com/SwoB8LhEYHsx780U07yfFsJA7Q2fevus0x6XeUSMJLGBm5pTn9erV9Nyb6aAQRzenQ",
        "https://play-lh.googleusercontent.com/c4sRsNw76uoqcZfetPVENPTHQF46iFQveEHo2_pXBfhV269zJGYP_tOtqFYBvLOwNpA",
        "https://play-lh.googleusercontent.com/AKjk2kp1DHrNBivDLst4z7Mrt2MUtOhewITXnnQKXN-rX1_OEVaiRR2EJGDbIbN2zrk",
        "https://play-lh.googleusercontent.com/5ET9noggzcxwEHZ2uVh1kkkR_jT1WWeVDVR5BRzxEKTKVr7Zsi7CV5djnDSaRejjo9E",
        "https://play-lh.googleusercontent.com/kQUOepkfU7ag95bfaEqH4ZEH6F4lowymjbPZUgm6_x1WhWxkhHY3z2WvUE5Vz1SBB-fr",
        "https://play-lh.googleusercontent.com/ch-KxWQhGTQ1PQftBrPKrkIwsp44ZTkt3TeQV_h_hQhBlq9pzVCXK_bcpCn_tIQ4j9cf",
        "https://play-lh.googleusercontent.com/-pBusyWoKvTMf650q0YVB-6XUuA1R2AqLSmveue_I2CE4Py-62W_cpn9lMdXC_PDMFDG",
        "https://play-lh.googleusercontent.com/lqg6MuwzpV-NKOXhj1jjj3AmZABDgqhcxFO6_qTo6UYZC45T_nFYqbUnFxPVR6VzjsI",
        "https://play-lh.googleusercontent.com/vF2B0o1utJejvhF-8NPAMEdectcwEJN2i5yC_7ciaTK7geulFVVDh1Xlisg4beLRYg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 17, 2014",
    "lastUpdatedOn": "Oct 9, 2024",
    "updated": 1728507782,
    "version": "2.2.594818.0",
    "comments": [],
    "appId": "com.amazon.dee.app",
    "url": "https://play.google.com/store/apps/details?id=com.amazon.dee.app&hl=en&gl=us"
}