{
    "title": "Harrah\u2019s Online Casino NJ",
    "description": "Harrah\u2019s Casino Online - Official New Jersey Online Casino Real Money App\r\n\r\nYou can now bring the excitement of Atlantic City and Las Vegas straight to you! With the Harrah's Casino NJ mobile app, you can play slots, video poker, roulette, and blackjack anytime, anywhere in New Jersey! You'll never miss out on a spin on the slot machines again or an online blackjack hand just because you're on the go!\r\n\r\nDownload & play for cash payouts with our exciting casino slot machines and blackjack games. Real Money games are available to players 21+ who are approved for online casino play and within the State of New Jersey.\r\n\r\nFeatures:\r\n\r\n- Safe and Secure \u2013 Harrah\u2019s has been a trusted name in casino gaming since 1937\r\n- Fully licensed in New Jersey, our casino games are audited and in compliance with the New Jersey Division of Gaming Enforcement\r\n- Secure deposit options: PayPal, Visa, Mastercard, Discover, ACH & Online banking transfer\r\n- Progressive jackpots: Ultimate Universe, Casino Reels and The Royals Go Camping!\r\n- Popular slot games: 88 Fortunes, Bonanza Megaways and Jin Jin Bao XI Hail King Of Fortune\r\n- Popular table games: Blackjack, video poker and Roulette \r\n- Regular player promotions, bonuses, and Caesars Rewards online reward credit multipliers\r\n\r\nFind out more about Harrah\u2019s Online Casino by visiting our site:\r\n\r\nhttps://www.harrahscasino.com\r\nhttps://www.harrahscasino.com/promotions/\r\nShare your feedback with us at\r\nhttps://www.facebook.com/HarrahsOnline\r\nhttps://twitter.com/harrahsonline\r\n\r\nTerms and conditions apply. Must be 21+ and present in NJ to play.  We are committed to responsible gaming, and are dedicated to an enjoyable and positive gaming experience. Visit https://www.harrahscasino.com/policies/patronprotection/ for more information. Gambling Problem? Call 1-800-GAMBLER.\r\n\r\nThis is a real-money gambling app. Please gamble responsibly and only bet what you can afford. For gambling addiction help and support, please contact National Problem Gambling Helpline at 1-800-522-4700, or visit https://www.ncpgambling.org/.",
    "descriptionHTML": "Harrah\u2019s Casino Online - Official New Jersey Online Casino Real Money App<br><br>You can now bring the excitement of Atlantic City and Las Vegas straight to you! With the Harrah&#39;s Casino NJ mobile app, you can play slots, video poker, roulette, and blackjack anytime, anywhere in New Jersey! You&#39;ll never miss out on a spin on the slot machines again or an online blackjack hand just because you&#39;re on the go!<br><br>Download &amp; play for cash payouts with our exciting casino slot machines and blackjack games. Real Money games are available to players 21+ who are approved for online casino play and within the State of New Jersey.<br><br>Features:<br><br>- Safe and Secure \u2013 Harrah\u2019s has been a trusted name in casino gaming since 1937<br>- Fully licensed in New Jersey, our casino games are audited and in compliance with the New Jersey Division of Gaming Enforcement<br>- Secure deposit options: PayPal, Visa, Mastercard, Discover, ACH &amp; Online banking transfer<br>- Progressive jackpots: Ultimate Universe, Casino Reels and The Royals Go Camping!<br>- Popular slot games: 88 Fortunes, Bonanza Megaways and Jin Jin Bao XI Hail King Of Fortune<br>- Popular table games: Blackjack, video poker and Roulette <br>- Regular player promotions, bonuses, and Caesars Rewards online reward credit multipliers<br><br>Find out more about Harrah\u2019s Online Casino by visiting our site:<br><br>https://www.harrahscasino.com<br>https://www.harrahscasino.com/promotions/<br>Share your feedback with us at<br>https://www.facebook.com/HarrahsOnline<br>https://twitter.com/harrahsonline<br><br>Terms and conditions apply. Must be 21+ and present in NJ to play.  We are committed to responsible gaming, and are dedicated to an enjoyable and positive gaming experience. Visit https://www.harrahscasino.com/policies/patronprotection/ for more information. Gambling Problem? Call 1-800-GAMBLER.<br><br>This is a real-money gambling app. Please gamble responsibly and only bet what you can afford. For gambling addiction help and support, please contact National Problem Gambling Helpline at 1-800-522-4700, or visit https://www.ncpgambling.org/.",
    "summary": "Harrah\u2019s Casino Now Available for All NJ Online Casino Real Money Players",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 53108,
    "score": 4.133333,
    "ratings": 602,
    "reviews": 113,
    "histogram": [
        108,
        0,
        11,
        63,
        418
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Caesars Interactive Entertainment Inc.",
    "developerId": "Caesars+Interactive+Entertainment+Inc.",
    "developerEmail": "njsupport@harrahscasino.com",
    "developerWebsite": "https://www.harrahscasino.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.harrahscasino.com/policies/privacypolicy/",
    "genre": "Casino",
    "genreId": "GAME_CASINO",
    "categories": [
        {
            "name": "Casino",
            "id": "GAME_CASINO"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/fKdujZb4oVNjjyzbSF6REasv8IOJeryQywREY90xsjYxTQqfzp-hBEpxU1aMHmwvzwY",
    "headerImage": "https://play-lh.googleusercontent.com/GowrrgG-DhHFzehPCvBrSaJhXQAdejytsnRciNW7vnR_8Hh9cX7Q65i0BxG6BnhDmrc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/APiiHEfX9OSuO1WHo4suwlHtG4X4Fb8aLQOvKLqWH_2UaNERqHm1UsdV16ah5p4t-Qc",
        "https://play-lh.googleusercontent.com/dj5sBTKwo0p1oFiF5iqtnYdaz_fji5A2GsFJMlhFfSIz4q5O9aIAR6WwK4Yg_aAIII3w",
        "https://play-lh.googleusercontent.com/HWU19tuunmQhtLEQtFnp-54jRGeYXwJQf0CQOfwpsSgmCNtc7x4WHkT2hR_8Qaf_bwZF",
        "https://play-lh.googleusercontent.com/O1lrObzySRUraUAZK16kcoDaNYxga66wz8pLBXwlztBTUg6Mv14Jhf8yktWZil03wfs",
        "https://play-lh.googleusercontent.com/CFhVEiF47IuChliLE2ELK0uYOstsiXrmw8rLFu1X5o5byio8nFbOyL8Ham2y3boAQw",
        "https://play-lh.googleusercontent.com/vPsslcrw_7AZGn2XKGDMatDvfDDptgnRHCh0baSiRM9Gw0PHyXdn6q7cOMOQ5JqLpAo",
        "https://play-lh.googleusercontent.com/MFcMSf8-pd1EwBXo2xysHP2LXYzyZIXthzjSIpScgEHaT7iJ4NxGAkKR0tZZaa_5Xgpc",
        "https://play-lh.googleusercontent.com/iHhWfiNhnCFDi9fnXWNV7ASalKGMC5RRO6AYLiwoOHoxGoQQnBK1tLufHySZ6n9DdEQ",
        "https://play-lh.googleusercontent.com/3LR7FEMsr12wyjNAV7Y41Arjp4BNjq8gsluQGWxhjHF42Qf69IBP2RQbB6eJbUVDUWQ",
        "https://play-lh.googleusercontent.com/sot9xBCLfOrHKoufRfJSRTVncyoccMFZxnq5IBdCYsx23amA6CbcjxX1q3nxC3g-9g",
        "https://play-lh.googleusercontent.com/8nGIg7f1HlRZKHyKP3IT30vYZpkDwbBcENE1srK1KQhAENApalf2uiUxrbzVUfLyiFI",
        "https://play-lh.googleusercontent.com/MyUUUqC9bT22BzjuBDRpA43UEBx4jiHU_8_M79SZe8bXUbOZ3k-Sen1cOgn5wQ7asHM",
        "https://play-lh.googleusercontent.com/iGm21pIx7veV_03SxSfD9Flpfe4LO7HWcaLKWoIDSAS1LynROpjwCSkHlE7katKsTk4",
        "https://play-lh.googleusercontent.com/rhL197oCGBwd5HSB_FA7-aEkpy4UdMs0jbefIsd1z-ZwmTXZdxgnEXnT8GhZWs1vnCd0",
        "https://play-lh.googleusercontent.com/R1J0IagBqi6QOpGSMPkCZsJgMNN-6pDs0Bd9gEqIV4e7XytBJes8UdggnQydQZ6aYw",
        "https://play-lh.googleusercontent.com/g5p1gOcU3Z2_4qItL9t810rDf1IsG7S2JUO6Pwehjcc7tdqn734-UODCgZbIlDsm5w",
        "https://play-lh.googleusercontent.com/lVP3gQ50D9igq53PIMQfNpyoP18-q4GQGnWirEubJehKPi2TLIw7iQn1HIvoXLMX6feT",
        "https://play-lh.googleusercontent.com/dpvI0TxuHdX0rmOEX9kVynU3ks1L5MToELq_sIRwFO8mO8jfBCKg42SrE0wteyZTh_4",
        "https://play-lh.googleusercontent.com/K0Z8-Ahmv5K7vzLtM3URsYOv9UXK3cniJCN7SjDXEcsWy-7d6_WM-8ft3lfs50gGdRE",
        "https://play-lh.googleusercontent.com/7JpX17-PL3OojOvC6kR0h803ujHxqbmCgeJ8uXpKk9deP8Vn-aZNPlA3c_yK3Yw1HA",
        "https://play-lh.googleusercontent.com/S4gMeFVcr22DhAOVgodjwGTUU8PLzUc5iFAQvKVPlvesaf_dhyRqNdR8dlxP3_K0AT6A",
        "https://play-lh.googleusercontent.com/OL3FLNQAe_KajyhOedrls31xL9rcQ66Gw5cTfoQwAWnUoVtOETvKivch2At9g6T8",
        "https://play-lh.googleusercontent.com/eujIqXyLPHztaNxA-YYLIcWALPy94Ci0x5lycZOGKjh9tkkEHxCD3h4EUCV_BK0r2CE",
        "https://play-lh.googleusercontent.com/fiU4kOA46qUCX46rpNnvvK0lxxI7SkKEHr8EqDeSsaYdOXMzC4arKmwQoG2mygtB5gg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Adults only 18+",
    "contentRatingDescription": "Real Gambling/Paid Contests",
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 23, 2021",
    "lastUpdatedOn": "Aug 7, 2024",
    "updated": 1723042017,
    "version": "3.113.386",
    "comments": [],
    "appId": "com.harrahs.rl",
    "url": "https://play.google.com/store/apps/details?id=com.harrahs.rl&hl=en&gl=us"
}