{
    "title": "Parcel Pending",
    "description": "Parcel Pending makes it simple to receive your packages and online orders! With our easy-to-use mobile app, you can manage your account, retrieve your packages, set up vacation mode, and more!\r\n\r\n Use the Parcel Pending mobile app to:\r\n- Register for Parcel Pending.\r\n- View your pending packages and package history.\r\n- Manage your notification preferences.\r\n- Get real-time alerts when your packages are delivered.\r\n- Open the locker doors with the push of a button (when Bluetooth is enabled).\r\n- Setup vacation mode to avoid storage fees.\r\n- Add people in your residence to your account to ensure they receive their packages in the locker.\r\n- Manage your personal data and your payment information.\r\n\r\n \r\nHave questions about how to use the lockers, the mobile app or about how to make updates to your profile? Visit parcelpending.com/residents to access the FAQ library and much more.\r\n\r\n   We are always looking to improve our app and services. Please let us know if there is anything we can do to make our app better.",
    "descriptionHTML": "Parcel Pending makes it simple to receive your packages and online orders! With our easy-to-use mobile app, you can manage your account, retrieve your packages, set up vacation mode, and more!<br><br> Use the Parcel Pending mobile app to:<br>- Register for Parcel Pending.<br>- View your pending packages and package history.<br>- Manage your notification preferences.<br>- Get real-time alerts when your packages are delivered.<br>- Open the locker doors with the push of a button (when Bluetooth is enabled).<br>- Setup vacation mode to avoid storage fees.<br>- Add people in your residence to your account to ensure they receive their packages in the locker.<br>- Manage your personal data and your payment information.<br><br> <br>Have questions about how to use the lockers, the mobile app or about how to make updates to your profile? Visit parcelpending.com/residents to access the FAQ library and much more.<br><br>   We are always looking to improve our app and services. Please let us know if there is anything we can do to make our app better.",
    "summary": "Parcel Pending Resident App",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 344223,
    "score": 4.015345,
    "ratings": 4115,
    "reviews": 1858,
    "histogram": [
        736,
        126,
        168,
        389,
        2693
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Parcel Pending",
    "developerId": "Parcel+Pending",
    "developerEmail": "mobile@parcelpending.com",
    "developerWebsite": "https://www.parcelpending.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.parcelpending.com/mobile-privacy-policy/",
    "genre": "House & Home",
    "genreId": "HOUSE_AND_HOME",
    "categories": [
        {
            "name": "House & Home",
            "id": "HOUSE_AND_HOME"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/G0n1hI33G_Nc7emnM18KOuzAZa-nta9LNt_agI05I3mInlCKeV55_4cfN8J5TAN204_U",
    "headerImage": "https://play-lh.googleusercontent.com/HgGMGqb_yYgmxWFlOJ58coIYvmeYIIq1us4O7Gr43SA7e1wXC941jUYeOJCyjHhFEqU",
    "screenshots": [
        "https://play-lh.googleusercontent.com/3BWsEEYvF7YycTQWj5SHuAz-fsUWawOADLjjOo0AypxKWVBeUitSrWY-mggip0F9hrUz",
        "https://play-lh.googleusercontent.com/4bWPEH6R2EKvF1jhxjmCb8a7FBdnNl2rG5agdNoik-t4GQ6v7CHd3yHxr7t87pPegA",
        "https://play-lh.googleusercontent.com/CmdFaMc4IJVrpSZW_m1VAvkIa8h3AEaQbxzm93Wj0iJzsh-ln7SSU7J-traLgKcCJFM",
        "https://play-lh.googleusercontent.com/7559QR8VpEFpUNvXnEJOwQkYHf-D-vF8DVvhps48EPcrH5-1tCWPzFx2FZtyz4NXruzr",
        "https://play-lh.googleusercontent.com/XcvHr5UUZ2orJFPWYUQW8hEYhsJswosnuQYm-qcmoFj3QoHiliwQmiIP64bZ68y-prs_",
        "https://play-lh.googleusercontent.com/JZbr1sa_fl8sIPUBKw5pXFLvDdFh_p7o6-LZk225jt0wEyqGnmmt_Xir2ZAJgLdMKhY",
        "https://play-lh.googleusercontent.com/8W0DMqiyaJrSgAkidx8WKmkpUo_hqiVtkAYB9vd-uvVw0JqoWsVbEKGqwBd--z8xDQ",
        "https://play-lh.googleusercontent.com/BYTkpk0g7dsmpfLNaRv-ue30vt3G8AH53Nml8e31wLYFblNlnRMsVIrn8F8eMx1MZQ",
        "https://play-lh.googleusercontent.com/CUc249X53SuLCBW-dxpL-nf64yqANE06no3iziW-pPUvHXknFFfGhKzcadBzLrm9Pw8",
        "https://play-lh.googleusercontent.com/lTkHLdlAAme4PWMf_xkj27w9wSRk0LjSRsRNWnE8KP4KkPFI-kpqFAodTiOC9KPhIOo",
        "https://play-lh.googleusercontent.com/XM7UMCt8t_yYFCsBOIzgA8Q9YNtAlXTtbDXsGch4tM5ZyaM6Lp13rThWGrY42ITema0",
        "https://play-lh.googleusercontent.com/uFtRmtsoF3rZcF_bfQTYGQpQcG_Zlzl38YwQljA1bwxSWwJP19GlU8ZIffRZf882by5u",
        "https://play-lh.googleusercontent.com/h_7fPRU95QNno6AMBh7zfhoOi36uRkUrOZtSKEXAyrYV13X3gxGjNoKVlLEoG9m1wQ",
        "https://play-lh.googleusercontent.com/tlzSZE-kuf9yjBKMf5mzXiesdva9f222vZWBfHaAlMGUC_vQFy2TGpUk7DiSNnmmT3k",
        "https://play-lh.googleusercontent.com/lxhA6628Lh_tUi98fzyHdx_Ca9ND7ZFtmHIAFSvuUSJYUfTACjG-NrFpyC5_nEOGHgg",
        "https://play-lh.googleusercontent.com/I3M_Yg5KVmt0A_1p3aP2hsKj6_a4p_MYN8WJpa69eO4EvLVU57-veDaVShMaIRbERQ",
        "https://play-lh.googleusercontent.com/kMJEaBlcQjZRvLc-IFozsnwPLrN7ltI181sle0YohZmhYL5kZnRSs28uyg2Ozab6jg",
        "https://play-lh.googleusercontent.com/Aeggp7DHHadica1Tz9UGvkwkzDa-cI1-WRVEqT8Wzcf8gb5RsbJ7nnplNLUAS2NfEoE"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 7, 2018",
    "lastUpdatedOn": "May 17, 2024",
    "updated": 1715958497,
    "version": "1.33.6",
    "comments": [],
    "appId": "com.parcelpendingmobile.app",
    "url": "https://play.google.com/store/apps/details?id=com.parcelpendingmobile.app&hl=en&gl=us"
}