{
    "title": "Paysign\u00ae",
    "description": "View your balance, your recent transaction history, receive account alerts, and find nearby surcharge-free ATM all from the Paysign app. It\u2019s free, secure and makes it easy to manage your funds on the go.\r\n\r\nUse your card everywhere Visa Debit cards are accepted \u2013 in stores, online or over the phone.\r\n\r\nIf you have questions regarding your Paysign card call us using the 24/7 customer service number located on the back of your card.",
    "descriptionHTML": "View your balance, your recent transaction history, receive account alerts, and find nearby surcharge-free ATM all from the Paysign app. It\u2019s free, secure and makes it easy to manage your funds on the go.<br><br>Use your card everywhere Visa Debit cards are accepted \u2013 in stores, online or over the phone.<br><br>If you have questions regarding your Paysign card call us using the 24/7 customer service number located on the back of your card.",
    "summary": "Manage your money and transactions on your Paysign\u00ae card wherever you go.",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 624128,
    "score": 2.8695652,
    "ratings": 1471,
    "reviews": 622,
    "histogram": [
        638,
        84,
        116,
        84,
        543
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Paysign, Inc",
    "developerId": "Paysign,+Inc",
    "developerEmail": "mobilesupport@paysign.com",
    "developerWebsite": "http://online.paysign.com",
    "developerAddress": null,
    "privacyPolicy": "https://paysign.com/privacy-policy/",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/OJI1kGUwV-2xNd4CEQI4UQZkK4QDJeRzPzpsYCSL0JpNiQ6YdBWylhCgPswfdjGAGA",
    "headerImage": "https://play-lh.googleusercontent.com/debfaLBrMvD42NG7sDm2d1wyBOHltwmLzME2WKpcHf2mJDRuwfv3zNzxmVcbT90fMJLg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/JG0CeKdAXCojZOWqRhrrf-tfMt9P2dekWvAauwpNtYT5MThYRTCi_hdzdimMiq1y488",
        "https://play-lh.googleusercontent.com/81GcoUJA3CFDkYnuhUaZAyuprI_aHSnCuJu3rL_-40Z92l5Ee2ZPNLvyddYuuehmbKY",
        "https://play-lh.googleusercontent.com/gyclzyY9PXTnqna1boGAKSQeaxo07O2FkpFFxTUaB_VslQP_KEFYKRgDLxDV7defh6M",
        "https://play-lh.googleusercontent.com/EOkBiMc7ts1y3cAGSsPj1sg8gkx2onv0546lpzxRqVjq9-TeeWrwBckZScRJ3DElmc4",
        "https://play-lh.googleusercontent.com/1N_cC11Y38zHDYKXXYNOPquMgCwq_QkKDboDARhZ1hiZdEPylF3te02Ui0eJDOq3b_M",
        "https://play-lh.googleusercontent.com/n6ZPHENEUKjqQ38S4nbESvBzyVv-ALk3aRWH_x9KbPXqRRtn9TCYsIeTrztWtrBBBQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 25, 2018",
    "lastUpdatedOn": "Sep 25, 2024",
    "updated": 1727322736,
    "version": "3.0.80",
    "comments": [],
    "appId": "com.paysign.app",
    "url": "https://play.google.com/store/apps/details?id=com.paysign.app&hl=en&gl=us"
}