{
    "title": "AI Tattoo Maker - Ink",
    "description": "If you have a tattoo idea but can\u2019t find the perfect design, let Ink AI generate one in seconds. Download Ink AI today and start designing your next masterpiece.\r\n\r\nSay goodbye to searching for tattoo ideas on social media. Ink AI Tattoo Generator revolutionizes your tattoo experience, allowing you to create personalized designs with ease. Input your ideas, and Ink will produce professional-grade sketches. Plus, with our virtual try-on feature, you can see exactly how the design will look on your body.\r\n\r\nHow to use?\r\nGot a tattoo idea but can\u2019t find the right design? Ink AI is here to help. Start by choosing your preferred style\u2014realistic, minimalistic, surrealistic, or anything unique. Describe your idea, and our AI will craft a custom sketch.\r\n\r\nWhat Makes Ink Special:\r\n\r\nPersonalized Designs: Create unique tattoos that reflect your individuality.\r\nDiscover Styles: Find the perfect tattoo style that matches your personality.\r\nOrganize and Compare: Save and compare designs to make the best decision.\r\nFeedback Sharing: Share your designs with friends or your tattoo artist for their input.\r\n\r\nWhether you\u2019re new to tattoos or a veteran enthusiast, Ink is your go-to app. Download Ink today and start your tattoo journey with confidence.\r\n\r\nPayment & Cancellation:\r\nSubscriptions are billed at the selected rate and charged to your iTunes account upon purchase confirmation. Subscriptions auto-renew at the chosen package cost unless canceled 24 hours before the end of the current period. Manage your subscription and disable auto-renewal in your Account Settings after purchase. Refunds are not provided for unused portions of the term.\r\n\r\nPrivacy Policy: https://www.feraset.co/privacy.html\r\nTerms of Use: https://www.feraset.co/terms.html",
    "descriptionHTML": "If you have a tattoo idea but can\u2019t find the perfect design, let Ink AI generate one in seconds. Download Ink AI today and start designing your next masterpiece.<br><br>Say goodbye to searching for tattoo ideas on social media. Ink AI Tattoo Generator revolutionizes your tattoo experience, allowing you to create personalized designs with ease. Input your ideas, and Ink will produce professional-grade sketches. Plus, with our virtual try-on feature, you can see exactly how the design will look on your body.<br><br>How to use?<br>Got a tattoo idea but can\u2019t find the right design? Ink AI is here to help. Start by choosing your preferred style\u2014realistic, minimalistic, surrealistic, or anything unique. Describe your idea, and our AI will craft a custom sketch.<br><br>What Makes Ink Special:<br><br>Personalized Designs: Create unique tattoos that reflect your individuality.<br>Discover Styles: Find the perfect tattoo style that matches your personality.<br>Organize and Compare: Save and compare designs to make the best decision.<br>Feedback Sharing: Share your designs with friends or your tattoo artist for their input.<br><br>Whether you\u2019re new to tattoos or a veteran enthusiast, Ink is your go-to app. Download Ink today and start your tattoo journey with confidence.<br><br>Payment &amp; Cancellation:<br>Subscriptions are billed at the selected rate and charged to your iTunes account upon purchase confirmation. Subscriptions auto-renew at the chosen package cost unless canceled 24 hours before the end of the current period. Manage your subscription and disable auto-renewal in your Account Settings after purchase. Refunds are not provided for unused portions of the term.<br><br>Privacy Policy: https://www.feraset.co/privacy.html<br>Terms of Use: https://www.feraset.co/terms.html",
    "summary": "Stencil Designer & Creator",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 167621,
    "score": 4.2156863,
    "ratings": 4031,
    "reviews": 47,
    "histogram": [
        468,
        74,
        196,
        631,
        2646
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $39.99 per item",
    "developer": "FERASET",
    "developerId": "FERASET",
    "developerEmail": "info@feraset.co",
    "developerWebsite": "https://www.feraset.co/",
    "developerAddress": "Ye\u015filk\u00f6y Mahallesi, Atat\u00fcrk Caddesi ,EGS Business Park, No: 12, Ic Kap\u0131 No: 251 , Bak\u0131rk\u00f6y, \u0130stanbul, 34149, T\u00fcrkiye",
    "privacyPolicy": "https://www.feraset.co/privacy.html",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/AySupYNmyFUzSa-67glixL4gr1qesmCIQMHxv7LpdCarVqY-UM-pJxqhBm_lu6HL8wc",
    "headerImage": "https://play-lh.googleusercontent.com/pU5529fgBmjwE1Y8P14ns_6aBFtZWhXkd8JYLmRQNDWKeE1NayntGBjvVWr_RngG_Q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/x8ekrfkn1np64wBIakc6f76F22a_BAkzRo0cxuSnaIh51I1ZXK5Z_cRQTQ6B4ETFBA",
        "https://play-lh.googleusercontent.com/jzNlTcYO4-iwwj-fQ1JTceGFez6BYl5JnigTk-so6BOwBy1-1YEsmVs55OZTW-JYoUs",
        "https://play-lh.googleusercontent.com/J0dE625SQ8ngoP3Rarlvz8ojqcKXXAAWQRgwMOY7OAYEZCeQT5UGINR927887xCpjQ",
        "https://play-lh.googleusercontent.com/HzEFZGiRdx1D5vIBwzIKZbf8vAWH8OZLChbQf_65q1_0Wla32nus3nce1PTDWSlauw",
        "https://play-lh.googleusercontent.com/fiU0ZwXBJ-ihr5ksxDR7DtQIo2ixMEvkbg2WJiGi04rwpvbETm1GQDk1RiY3EzvAyw",
        "https://play-lh.googleusercontent.com/Iyy61DEYIbrt-VLQa3z1t39Xu4-E8UPKszIBM_gUK5gcX_OEHCvVmfZL9IShKQMcm7qH",
        "https://play-lh.googleusercontent.com/ahwNa-NGU5a8IwyjDYTw9S9VlyNjbRDwkAsSq2D3KDXTaxSTNubdSvug6k4R_c3Ir38",
        "https://play-lh.googleusercontent.com/lvlyb7tIhkyIQU2bKldFziX-_mO1GJwfbrG13nRtYxaAUqMDfefxyJ6HDh8cyQu0EhA",
        "https://play-lh.googleusercontent.com/kisPyAXUECK8fhoNK_nZKrSEfwZ5pTMkfwFCza1BvSkEcsITD6tK7GTmUc7WiHup4TA",
        "https://play-lh.googleusercontent.com/iCy2ETsyOkG-tgPwVXcj-O82XHmAi5l3fpzqNDBDWBwWuv5eUuA_Zw8gt8SApsZXUA",
        "https://play-lh.googleusercontent.com/pMl9W6vtV7BZMhAKVn6t_-lKbu7X-cIZ6vxRXDjUgGAzqoDLsRc-bTptSCEpP2DzrA",
        "https://play-lh.googleusercontent.com/2JnfDaq8aRZBM9ZBL1syA5Je-G7CmRMDDfFYqYLSdTGMJlNvlCawIw5z8IRmsMxnSQA",
        "https://play-lh.googleusercontent.com/INnAT-_LqhCAZG9Qrp6H6R9OYX-s3lLsKUR_fdQpI6YY7QP3tucxayv4VgtsbDXTEnM",
        "https://play-lh.googleusercontent.com/86cFPQTzxMW3FmOqxHxrHuoO5Ipomin15_rGVU02LBDGCZ_iQYkHCNt7j7WTcEipFhDI",
        "https://play-lh.googleusercontent.com/OIGyK7PO_-nWWmYxHysnu69IKJoglRqh7yUcY27QdjjnorXesnPYXk1JhZqSbhVq77ds",
        "https://play-lh.googleusercontent.com/uK7VtAiHkC4pTkeg9wh4kK8rjnZK9Etw0VjdFFjIAFvc9nmp3hf4UNrG41a3OFoFzTE"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 15, 2024",
    "lastUpdatedOn": "Oct 11, 2024",
    "updated": 1728664756,
    "version": "1.3.14",
    "comments": [],
    "appId": "com.feraset.ink",
    "url": "https://play.google.com/store/apps/details?id=com.feraset.ink&hl=en&gl=us"
}