{
    "title": "Weather XL PRO",
    "description": "Welcome to one of the best weather apps on the Play Store, recognized as one of the best for its accuracy, widget flexibility, and ease-of-use. \r\n\r\nOur intuitively designed interface provides you with informative, useful, and precise weather updates for your local area and around the globe, all accompanied by stunningly detailed animations. \r\n\r\nMain App Features:\r\n\r\n\u2022 Accurate and comprehensive weather forecasts for the next 10 days\r\n\u2022 Hour-by-hour weather updates to help you plan your activities with precision\r\n\u2022 Fast, beautiful, and simple-to-use interface\r\n\u2022 Detailed forecasts for rain, snow, wind, storms and many other useful information - stay prepared for all weather conditions\r\n\u2022 Daily updates on humidity, dew, UV index, and air pressure \r\n\u2022 Data on highest and lowest historical weather values \r\n\u2022 Dynamic animations of satellite and weather radar maps\r\n\u2022 Weather also available in the notification area with the temperature display in your status bar\r\n\u2022 Optimized for both phones and tablets, and fully compatible with your favorite Wear OS smartwatch\r\n\r\nCustomizable Home Screen Widgets:\r\n\r\n\u2022 Highly configurable widgets with extensive customization options available to adjust the look, ensuring seamless integration with your home screen\r\n\u2022 Choose the size, layout, and appearance of your widget, select what weather information to display, and even adjust text size and colors\r\n\u2022 Get quick weather snapshots without even opening the app, right from your home screen\r\n\u2022 Convenience at its best, with visually pleasing designs to suit your style and preference\r\n\r\nLive Wallpaper Feature:\r\n\r\n\u2022 Experience our Live Wallpaper feature, displaying mesmerizing weather animations right on your device screen (subject to device compatibility)\r\n\u2022 Enjoy real-time weather updates in the most visually engaging way\r\n\r\nSevere Weather Alerts:\r\n\r\n\u2022 Stay safe and informed with critical information about severe weather warnings \r\n\u2022 Alerts issued by official national weather services from around the globe, ensuring comprehensive coverage\r\n\r\nSevere weather alerts availability: https://exovoid.ch/alerts\r\n\r\nAir Quality Information:\r\n\r\n\u2022 Detailed air quality information sourced from official stations to keep you healthy \r\n\u2022 Track key pollutants including ground-level ozone, particle pollution (PM2.5 and PM10), carbon monoxide, sulfur dioxide, and nitrogen dioxide\r\n\r\nAir quality Information availability: https://exovoid.ch/aqi\r\n\r\nPollen\r\n\r\nThe concentration of different pollen are displayed.\r\nPollen forecasts are available in these regions: https://exovoid.ch/aqi\r\n\r\nWe continue to actively work to add new regions to provide information on air quality and pollen.\r\n\r\nWear OS Support:\r\n\r\n\u2022 Bringing forecasts right to your wrist with full support for Wear OS\r\n\u2022 Stay updated with accurate weather information anytime, anywhere\r\n\r\nTry the best weather app now \u2013 experience simplicity, usefulness, and informative power like never before, all for free!\r\n\r\n--\r\n\r\nPrivacy Policy & Terms of use : \r\nWe do not collect any personal information. In order to use our apps, please accept our privacy policy and review conditions for third-parties such as advertising partners. \r\n\r\nhttps://www.exovoid.ch/privacy-policy",
    "descriptionHTML": "Welcome to one of the best weather apps on the Play Store, recognized as one of the best for its accuracy, widget flexibility, and ease-of-use. <br><br>Our intuitively designed interface provides you with informative, useful, and precise weather updates for your local area and around the globe, all accompanied by stunningly detailed animations. <br><br>Main App Features:<br><br>\u2022 Accurate and comprehensive weather forecasts for the next 10 days<br>\u2022 Hour-by-hour weather updates to help you plan your activities with precision<br>\u2022 Fast, beautiful, and simple-to-use interface<br>\u2022 Detailed forecasts for rain, snow, wind, storms and many other useful information - stay prepared for all weather conditions<br>\u2022 Daily updates on humidity, dew, UV index, and air pressure <br>\u2022 Data on highest and lowest historical weather values <br>\u2022 Dynamic animations of satellite and weather radar maps<br>\u2022 Weather also available in the notification area with the temperature display in your status bar<br>\u2022 Optimized for both phones and tablets, and fully compatible with your favorite Wear OS smartwatch<br><br>Customizable Home Screen Widgets:<br><br>\u2022 Highly configurable widgets with extensive customization options available to adjust the look, ensuring seamless integration with your home screen<br>\u2022 Choose the size, layout, and appearance of your widget, select what weather information to display, and even adjust text size and colors<br>\u2022 Get quick weather snapshots without even opening the app, right from your home screen<br>\u2022 Convenience at its best, with visually pleasing designs to suit your style and preference<br><br>Live Wallpaper Feature:<br><br>\u2022 Experience our Live Wallpaper feature, displaying mesmerizing weather animations right on your device screen (subject to device compatibility)<br>\u2022 Enjoy real-time weather updates in the most visually engaging way<br><br>Severe Weather Alerts:<br><br>\u2022 Stay safe and informed with critical information about severe weather warnings <br>\u2022 Alerts issued by official national weather services from around the globe, ensuring comprehensive coverage<br><br>Severe weather alerts availability: https://exovoid.ch/alerts<br><br>Air Quality Information:<br><br>\u2022 Detailed air quality information sourced from official stations to keep you healthy <br>\u2022 Track key pollutants including ground-level ozone, particle pollution (PM2.5 and PM10), carbon monoxide, sulfur dioxide, and nitrogen dioxide<br><br>Air quality Information availability: https://exovoid.ch/aqi<br><br>Pollen<br><br>The concentration of different pollen are displayed.<br>Pollen forecasts are available in these regions: https://exovoid.ch/aqi<br><br>We continue to actively work to add new regions to provide information on air quality and pollen.<br><br>Wear OS Support:<br><br>\u2022 Bringing forecasts right to your wrist with full support for Wear OS<br>\u2022 Stay updated with accurate weather information anytime, anywhere<br><br>Try the best weather app now \u2013 experience simplicity, usefulness, and informative power like never before, all for free!<br><br>--<br><br>Privacy Policy &amp; Terms of use : <br>We do not collect any personal information. In order to use our apps, please accept our privacy policy and review conditions for third-parties such as advertising partners. <br><br>https://www.exovoid.ch/privacy-policy",
    "summary": "Accurate weather forecasts & stunning animations",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 28252298,
    "score": 4.4437146,
    "ratings": 494163,
    "reviews": 4354,
    "histogram": [
        31508,
        13429,
        24078,
        60235,
        364791
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.49 per item",
    "developer": "Exovoid S\u00e0rl",
    "developerId": "6534515373655701527",
    "developerEmail": "support@exovoid.ch",
    "developerWebsite": "http://www.exovoid.ch",
    "developerAddress": "Route de Lentine 14\n1950 Sion\nSwitzerland",
    "privacyPolicy": "http://www.exovoid.ch/privacy-policy",
    "genre": "Weather",
    "genreId": "WEATHER",
    "categories": [
        {
            "name": "Weather",
            "id": "WEATHER"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/MFMPQ9CI0em-4AuBsiEZ4qiTBBCZ9ThmijX8YA9WD3fv5RhtLyXcpc8qdZhSq1d6XTc",
    "headerImage": "https://play-lh.googleusercontent.com/WYAsr3m03L3Oq5i5MRZVzdBdPHL0347IeQmQbJe7mSGZbdVGjyVi-5x3dvV2zAqv__0",
    "screenshots": [
        "https://play-lh.googleusercontent.com/_VonngpwPbae87bwMStwZLm1WMhA1sEKol53u4O2uymnQ5LgbOl653itCpUJftI7X5nv",
        "https://play-lh.googleusercontent.com/2iHdUM4yXFTTn4P-uKicCF8R7rTa1FBlRYMXfr8mehvgPEURXp42LuzmRifNb1bhMA",
        "https://play-lh.googleusercontent.com/0kbUs56fhDnJatckmAg95tpENABiStXPyNnhTOOOR3oiJ9haTcBme7t0kR-DmlIYVECT",
        "https://play-lh.googleusercontent.com/pVWOUHmSbF8Wd_RZXOOqJpJwd9-V2C2PcjsgrSI2PWLIpCaGuRvHjap3W9mreOeSyIg",
        "https://play-lh.googleusercontent.com/DHs9mUkfbIVYb3Wgp-kXcEtkLPdApdYRHhYanna1gIHqoKt-zYmIaO8hoFlrEPEjqVc",
        "https://play-lh.googleusercontent.com/ttMxkT-4ysqU4n07VTcKTbE8BYQWL1TnT6W4lUvAfHXqCGQ30uW0qcgP5gUmuOMvavY",
        "https://play-lh.googleusercontent.com/NtSosJ4F6vlKt_PJHDL3Q_Geqqcal_9yYer2idd00q5wOfQkfSWMtXD9WVWccg68NBc",
        "https://play-lh.googleusercontent.com/9DEhJms8xeDjSYiKo_enVk0VKvRh90MaIuKhf5m-BD4sOARKWZbzG794DmTNpR_aMuU",
        "https://play-lh.googleusercontent.com/WI83xJP3fDswM97KftTPQ1hmZZAT7xdxkMJ8BetREW82VLVmqVhAgMUWmH7bE1nF9Eg",
        "https://play-lh.googleusercontent.com/dcKi8ykgz_Sa7TwHaYu9o3E-folOl2te1U7Atp6gk3DMCv03kVfSo3SEStSOxdY5eg",
        "https://play-lh.googleusercontent.com/RqlpXDGuyuJCaIlX-SI8WcZ0FNu2KkbNo_MEMngWNrzUhunwb2CKymaYIBGwvlO2R58",
        "https://play-lh.googleusercontent.com/wzgFcW7_Hm03IN_hAQSGZGEcss6ii2xKFL3zOIr9zsoQf1LeKbVRh42cHR6-aax0TqMo",
        "https://play-lh.googleusercontent.com/Ooacd5vz08KM8bCOtsURi7XAlTP9h2ZBYwb7WyY-BdYvsJ461bx9ncMwWADdvi81994",
        "https://play-lh.googleusercontent.com/LbeELCQKoGniy-pByh5WBdEl76p3NdTV7q_szxX7a80RmDk-k795if9F1t5eQv2gIIbM",
        "https://play-lh.googleusercontent.com/j89TWBRG2dGQlRZsdB1smHKb7EgReqZXMc5rDePaoguKadgZbif7FfGUznZhpir7O5kx",
        "https://play-lh.googleusercontent.com/YB7TEGglgPQ-mslgaxO-8C-U90xaN3yxaEqEiX4Rr1YHe_8mFL1pi5VHfMOoJ47qRuI",
        "https://play-lh.googleusercontent.com/4cjXwVPqCy8B146QA-JY83KLoGMGCIt3f6TFVv16AFLECI0mD_24V0exyaU0jo2e7uoC",
        "https://play-lh.googleusercontent.com/RhRxP0GmooEEHJ8kHGRKCC8e0gSq_FM2xxODhH6yKrKXnVYI3NZ6trE_Fotlbu7Qgl0",
        "https://play-lh.googleusercontent.com/A1O3Lhl9N2FVyoxNEyYqgnmqYrUHiD2WtJXmIYZQbdXBAtAw6OHK8ITTH36Wi1yA3bw",
        "https://play-lh.googleusercontent.com/IKmQ0O_Wr_yShzpX-rjsrP120Q-7L-l98nZBs50QFr-Mzp0TM_A7OsZPpZp8qA4Dr70"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 15, 2014",
    "lastUpdatedOn": "Sep 24, 2024",
    "updated": 1727165572,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.exovoid.weather.app",
    "url": "https://play.google.com/store/apps/details?id=com.exovoid.weather.app&hl=en&gl=us"
}