{
    "title": "MiniNovel-Find Short Novels",
    "description": "MiniNovel: Your Personal Library of Short Stories\r\nDiscover the joy of reading with MiniNovel, the ultimate App for short story enthusiasts!\r\nWhy Choose Us?\r\n[Featured Genres]\r\nExplore a wide range of genres, from Romance and Werewolf to Fantasy. Each one is carefully selected to meet diverse interests and preferences.\r\n[Exclusive Membership Privileges]\r\nUnlock the full potential of MiniNovel by joining our Vip Premium. You have unlimited access to more premium content and enjoy uninterrupted immersive reading.\r\n[Personalized Recommendations]\r\nOur smart system learns from your reading habits and preferences, delivering tailored story suggestions that keep you hooked.\r\n[Comfortable Reading Time] \r\nMore seamless reading experience with features designed for your convenience. Clean interface, customizable fonts, day & night modes for comfortable reading any time.\r\n[Interactive Reading Community]\r\nEngage with stories like never before! Like, comment, connect with fellow book lovers and share your thoughts on the latest reads.\r\nCome to Us!\r\nJoin millions of satisfied readers who have discovered the joy of MiniNovel. Install now and embark on your personalized journey through numerous short novels!",
    "descriptionHTML": "MiniNovel: Your Personal Library of Short Stories<br>Discover the joy of reading with MiniNovel, the ultimate App for short story enthusiasts!<br>Why Choose Us?<br>[Featured Genres]<br>Explore a wide range of genres, from Romance and Werewolf to Fantasy. Each one is carefully selected to meet diverse interests and preferences.<br>[Exclusive Membership Privileges]<br>Unlock the full potential of MiniNovel by joining our Vip Premium. You have unlimited access to more premium content and enjoy uninterrupted immersive reading.<br>[Personalized Recommendations]<br>Our smart system learns from your reading habits and preferences, delivering tailored story suggestions that keep you hooked.<br>[Comfortable Reading Time] <br>More seamless reading experience with features designed for your convenience. Clean interface, customizable fonts, day &amp; night modes for comfortable reading any time.<br>[Interactive Reading Community]<br>Engage with stories like never before! Like, comment, connect with fellow book lovers and share your thoughts on the latest reads.<br>Come to Us!<br>Join millions of satisfied readers who have discovered the joy of MiniNovel. Install now and embark on your personalized journey through numerous short novels!",
    "summary": "Dive into a World of Mini-size Literature",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 101986,
    "score": 3.2608695,
    "ratings": 281,
    "reviews": 26,
    "histogram": [
        103,
        18,
        6,
        6,
        146
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $269.99 per item",
    "developer": "Novel Studio",
    "developerId": "Novel+Studio",
    "developerEmail": "mini.info@wownovel.net",
    "developerWebsite": "https://tibokh5.wownovel.net/v1/main/privacy_agreement",
    "developerAddress": "9/F MlV TOWER NO 111 BONHAM STRAND SHEUNG lvAN HONG KONG",
    "privacyPolicy": "https://tibokh5.wownovel.net/v1/main/privacy_agreement",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/zN18T7vAOqBuG5zLfPHPpUi4teuBBlx3D43EuWQDsVgj1pXr-DXOT3CV2I-oAX2R0t2a",
    "headerImage": "https://play-lh.googleusercontent.com/pfgDJwGiX7L-ZI5qhTL3GMXm8x6BhhrBjajuVZNCBLKVomDWQiQTnHIW7zaM-8vP9LE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/-ybgGxQBtaYcW3KLdEel0HqaWXX-jrczs86OoY_-ncRK23ye_W4WeEAJc3TGdxegRw",
        "https://play-lh.googleusercontent.com/EaaV_29wQHzw3qj2bjIlgAnOgRSEAI8Bt2up8Py42z_IG50MwlRGmoP1bn_RDr3zz24a",
        "https://play-lh.googleusercontent.com/cxt5fB0qfDP4nIEfYdEnnCPvQvt5YvAdlSayR4qjZeH-Sgw_qEw9Cs4II0lAJRjXIaBc",
        "https://play-lh.googleusercontent.com/aXv1D698Y7XVXBuT2yYGn9hvL_krqHlncdf0rxlkppipXlb7LfqaioPPgSLOdUVWaMY",
        "https://play-lh.googleusercontent.com/_G7EAh3ZmJAHzh8khwl-fxziPSX9Ftc8aVlIu0ups49BazD4lUZFTewBJVRTcP2LMvll",
        "https://play-lh.googleusercontent.com/ewbcfGDnR3ou7Ab8IghItVZrhF3Jy5qOA9TbKEfvTll31kkt03ilTdWnYFOwcM4f6Q",
        "https://play-lh.googleusercontent.com/UemnCBW3juBmdILODEePdSQLahgT8hSxhSKNGfT85KGHwCEinsgqjyqyrB2sfZZ0RQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "May 16, 2022",
    "lastUpdatedOn": "Oct 11, 2024",
    "updated": 1728640337,
    "version": "2.0.3",
    "comments": [],
    "appId": "com.tibok.app",
    "url": "https://play.google.com/store/apps/details?id=com.tibok.app&hl=en&gl=us"
}