{
    "title": "Viva Aerobus",
    "description": "With the new Viva App discover how easy it is to fly with Viva Aerobus. With a new and improved user experience with a friendlier design, you have everything you need from wherever you are. Our Viva flight app will become your favorite travel companion. \r\n\r\n- View your itinerary in one place and manage multiple reservations. \r\n\r\n- Customize your app. Set up your profile and add your travel documents, payment methods, and companion details to speed up your check-in and future bookings. \r\n\r\n- Check your flight status and updates in real-time. \r\n\r\n-Avoid lines at the airport and check-in directly on our app quickly and easily with just one click. \r\n\r\n- Access your boarding pass where and when you need it, without having to print it. Just save it and view it at the airport, even without an internet connection. \r\n\r\n- Discover the best promos and start enjoying your favorite destinations. \r\n\r\nDownload the app now and start enjoying the benefits!",
    "descriptionHTML": "With the new Viva App discover how easy it is to fly with Viva Aerobus. With a new and improved user experience with a friendlier design, you have everything you need from wherever you are. Our Viva flight app will become your favorite travel companion. <br><br>- View your itinerary in one place and manage multiple reservations. <br><br>- Customize your app. Set up your profile and add your travel documents, payment methods, and companion details to speed up your check-in and future bookings. <br><br>- Check your flight status and updates in real-time. <br><br>-Avoid lines at the airport and check-in directly on our app quickly and easily with just one click. <br><br>- Access your boarding pass where and when you need it, without having to print it. Just save it and view it at the airport, even without an internet connection. <br><br>- Discover the best promos and start enjoying your favorite destinations. <br><br>Download the app now and start enjoying the benefits!",
    "summary": "Check-in, access your reservation, travel documents, boarding pass, and more.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3242431,
    "score": 4.6463413,
    "ratings": 39961,
    "reviews": 888,
    "histogram": [
        2108,
        637,
        473,
        2745,
        33946
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Viva Aerobus",
    "developerId": "Viva+Aerobus",
    "developerEmail": "soportevivaapp@vivaaerobus.com",
    "developerWebsite": "https://www.vivaaerobus.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.vivaaerobus.com/es-mx/legal/politica-privacidad-aplicacion",
    "genre": "Travel & Local",
    "genreId": "TRAVEL_AND_LOCAL",
    "categories": [
        {
            "name": "Travel & Local",
            "id": "TRAVEL_AND_LOCAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/FTs9RR4CtNFyYMuILYHZORNRahNE4JiWd_psd8tUO6Gneu1A_u39O_lRaviO4UxMK6L-",
    "headerImage": "https://play-lh.googleusercontent.com/Ja0cu3XObXH3xbOS8Gn61g3NkTV90PPsz8uYkfRXQtNHLOw4e-B5-LjXk4cpYpje7Q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/a0DN-K9deVkgtF-MOiohUP7B5EqFbptCpJEev6vAX6QAptMX4izufOJGcWLXLqjaiiA",
        "https://play-lh.googleusercontent.com/epngUsg5yvm_TYqOdH3aX6WejLOoOjjY1v1EKJGFAMamrb6WTrf_DPvhknfpng5DOaQ",
        "https://play-lh.googleusercontent.com/0mv-1majuemnxdmIdfeoh3jw-jeP2jwfrsMLns7lnu-nk0AkR-xxxqDhYPYjPvt7Wg",
        "https://play-lh.googleusercontent.com/mXzofwKjl8EIzxYUMVS2G7jmxJsj_grLowy-SgWs9gBfLluc6zF_R_BpODfA19uKhbE",
        "https://play-lh.googleusercontent.com/Gc9m29z2HGfVeouqDO2PXiub9AHyUEbyI-IXQvVTuEt3vscDYdJSaPS-76T7T9wMiF8",
        "https://play-lh.googleusercontent.com/2hgDK--47QdtjWeK08KFW6aMKF9de9VtfJdP-gfImV36bo2Qe1J5gnXYjIrgT8Yc6ak"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 21, 2022",
    "lastUpdatedOn": "Oct 4, 2024",
    "updated": 1728064489,
    "version": "2.18.1",
    "comments": [],
    "appId": "com.vivaaerobus.app",
    "url": "https://play.google.com/store/apps/details?id=com.vivaaerobus.app&hl=en&gl=us"
}