{
    "title": "Jeremiah\u2019s Ice J-List Rewards",
    "description": "Earn reward points with every purchase with the J-List Rewards App. Find the closest location and start earning rewards today!\r\n\r\n- Earn your way to cool treats! 1 reward point for every $1 purchase, earn a free medium treat at 50 points! \r\n- Receive special gifts, offers, invitations and inside news. \r\n- Invite your friends and reap the sweet rewards! \r\n- Map view- Uses your phones GPS to find the closest Jeremiah\u2019s Italian ice store location.\r\n- Stay up to date on the coolest news & offers!",
    "descriptionHTML": "Earn reward points with every purchase with the J-List Rewards App. Find the closest location and start earning rewards today!<br><br>- Earn your way to cool treats! 1 reward point for every $1 purchase, earn a free medium treat at 50 points! <br>- Receive special gifts, offers, invitations and inside news. <br>- Invite your friends and reap the sweet rewards! <br>- Map view- Uses your phones GPS to find the closest Jeremiah\u2019s Italian ice store location.<br>- Stay up to date on the coolest news &amp; offers!",
    "summary": "Introducing Jeremiah\u2019s Italian ice J-List Rewards!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 211598,
    "score": 4.9617486,
    "ratings": 1721,
    "reviews": 359,
    "histogram": [
        0,
        9,
        0,
        37,
        1673
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Jeremiah's Italian Ice",
    "developerId": "Jeremiah's+Italian+Ice",
    "developerEmail": "devin@jeremiahsice.com",
    "developerWebsite": "https://jeremiahsice.com",
    "developerAddress": null,
    "privacyPolicy": "https://punchh.com/privacy_policy",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/2-G407idPTPdediFuwhvveNspaA_9D7QNtFFy_3-MlcmYjRIEDoJlK1GhwIl5bxqWg",
    "headerImage": "https://play-lh.googleusercontent.com/0s6fcjlYlscLO9epbtTT9hGqZkJ1LI9VF3jeKjQTuMaY9p1s3QtwdIen1_FWBfHUAYc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/i8Xb3i1yKmMQGeGEeBlAbXCoqlJTHJym6QIpgB87-R3zgUcUIiTMmsJn8lK07zxbqqA",
        "https://play-lh.googleusercontent.com/Ky_A0GI3LOr8NeOVWiK76r0qUFWYSrCCGUFhqeVgtIarfdfTK8z-Zj3aJyJG2crCasw",
        "https://play-lh.googleusercontent.com/37xnWCMZxr3BPAj-fIl80olagdd0S4oAQx_2m_b1HhBgGadE6DdBiZYb3_pM6A7-WkA",
        "https://play-lh.googleusercontent.com/nVBUfHy8SdxXgsE__1tyw9arLn9qaipZameqpGEyfini6ohQifr6onu6zFWvMHogpfA",
        "https://play-lh.googleusercontent.com/LEjZ3_pAl2ISpq4S39oCeRGFHRPQJN38fAwTfqnhq6qMKdnU2ZRLqrDoLc2RK4UZHnbb"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 17, 2018",
    "lastUpdatedOn": "Jul 17, 2024",
    "updated": 1721213024,
    "version": "1.6",
    "comments": [],
    "appId": "com.jeremiahsice.app",
    "url": "https://play.google.com/store/apps/details?id=com.jeremiahsice.app&hl=en&gl=us"
}