{
    "title": "PhotoShare Frame v2",
    "description": "Companion App for the PhotoShare Smart Frame. Simply select your favorite photos & videos, select one or more PhotoShare Frames as the destination and Send. Your memories will arrive in seconds, ready to be enjoyed by family & friends! With newer frames, you can now enhance your photos with fun Digital Effects like cameos and borders. You can even add filters, crop photos for the perfect fit, and personalize them with captions. Use the App to send multiple photos and video clips to up to 10 PhotoShare Frames at once.\r\n\r\nThe Disney PhotoShare Frame is published by Switchmate Home LLC under license from Disney.",
    "descriptionHTML": "Companion App for the PhotoShare Smart Frame. Simply select your favorite photos &amp; videos, select one or more PhotoShare Frames as the destination and Send. Your memories will arrive in seconds, ready to be enjoyed by family &amp; friends! With newer frames, you can now enhance your photos with fun Digital Effects like cameos and borders. You can even add filters, crop photos for the perfect fit, and personalize them with captions. Use the App to send multiple photos and video clips to up to 10 PhotoShare Frames at once.<br><br>The Disney PhotoShare Frame is published by Switchmate Home LLC under license from Disney.",
    "summary": "Send photos to your PhotoShare Frame",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 86493,
    "score": 4.740113,
    "ratings": 1883,
    "reviews": 790,
    "histogram": [
        21,
        0,
        31,
        340,
        1488
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "SimplySmart Home by Switchmate",
    "developerId": "6864370004380546670",
    "developerEmail": "support@photoshareframe.com",
    "developerWebsite": "https://www.photoshareframe.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.mysimplysmarthome.com/privacy-policy-and-terms-of-service/",
    "genre": "House & Home",
    "genreId": "HOUSE_AND_HOME",
    "categories": [
        {
            "name": "House & Home",
            "id": "HOUSE_AND_HOME"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/DJ7JB6LBobNeWq8FAEG0vFi_FqzcAmLniKf-bOrIF-pH5yUKEuvuNHTcSGGVTu-bQKc",
    "headerImage": "https://play-lh.googleusercontent.com/cMKjbmsrktDhx8ufer7VZ8e1mkSWvdMD_Wammf8bxoZ3FdGBv70dqxODjiJT2sXZZ_I",
    "screenshots": [
        "https://play-lh.googleusercontent.com/FPUKumx1ZHiYe4PmyOD2eES5mQVIa5_bM-fM9pBAW4grnOqg5mkxhxhZrtfYwQCYRA",
        "https://play-lh.googleusercontent.com/Owq98FosvNYO6GYZ2piTtDrTDPvlAZveo1Awnku9IIxqjz5P947bfeoKY-3-RGFBx-Q",
        "https://play-lh.googleusercontent.com/PVF9dlBT2GNUW6YNt0obKv6GOAeiXXFuz8CzSdbKqiiqEAOj7I1xP_rrd07eCkix3Dc",
        "https://play-lh.googleusercontent.com/-cTMxvd45B-Kj-UGoD9wp3nLAu99wDgbHYW3WMDmregKXLkGnVY6sqrTWBeZGbBGg46h",
        "https://play-lh.googleusercontent.com/snSPHQh4hDW8Sxm_K6BjBrSabDBebkYlbg4BKcQcW9uPq4c-XAPnTLAQnCfnQ-gEOF5T"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 13, 2022",
    "lastUpdatedOn": "Aug 14, 2024",
    "updated": 1723681103,
    "version": "4.0.11",
    "comments": [],
    "appId": "com.photoshareframe.app",
    "url": "https://play.google.com/store/apps/details?id=com.photoshareframe.app&hl=en&gl=us"
}