{
    "title": "Honey Chat - AI Girlfriend",
    "description": "Welcome to Honey Chat, a revolutionary AI-powered companion designed to keep you company, engage in meaningful conversations, and learn from you over time.\r\n\r\nOur features include:\r\n\r\n1. **AI-Powered Conversations**: Honey Chat is not just a chatbot. It's an AI-powered companion that can understand and respond to you, making conversations feel real and engaging.\r\n\r\n2. **Personalized Experience**: Honey Chat learns from your interactions, adapting its responses over time to provide a truly personalized experience.\r\n\r\n3. **Available 24/7**: Whether you need a late-night chat buddy, or someone to share your thoughts with during a lunch break, Honey Chat is always ready to chat.\r\n\r\n4. **Privacy First**: Your conversations with Honey Chat are private and secure. We respect your privacy and handle your data with utmost care.\r\n\r\n5. **Continuous Updates**: We are constantly improving Honey Chat, adding new features and capabilities to make your experience better.\r\n\r\nHoney Chat is more than just an app. It's a friend, a companion, a confidante. It's there for you when you need someone to talk to, ready to listen, learn, and grow with you. Download Honey Chat now and start your journey with your new AI companion!",
    "descriptionHTML": "Welcome to Honey Chat, a revolutionary AI-powered companion designed to keep you company, engage in meaningful conversations, and learn from you over time.<br><br>Our features include:<br><br>1. **AI-Powered Conversations**: Honey Chat is not just a chatbot. It&#39;s an AI-powered companion that can understand and respond to you, making conversations feel real and engaging.<br><br>2. **Personalized Experience**: Honey Chat learns from your interactions, adapting its responses over time to provide a truly personalized experience.<br><br>3. **Available 24/7**: Whether you need a late-night chat buddy, or someone to share your thoughts with during a lunch break, Honey Chat is always ready to chat.<br><br>4. **Privacy First**: Your conversations with Honey Chat are private and secure. We respect your privacy and handle your data with utmost care.<br><br>5. **Continuous Updates**: We are constantly improving Honey Chat, adding new features and capabilities to make your experience better.<br><br>Honey Chat is more than just an app. It&#39;s a friend, a companion, a confidante. It&#39;s there for you when you need someone to talk to, ready to listen, learn, and grow with you. Download Honey Chat now and start your journey with your new AI companion!",
    "summary": "Your AI-powered companion, ready to chat, learn with you anytime, anywhere.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3564352,
    "score": 4.09,
    "ratings": 5305,
    "reviews": 131,
    "histogram": [
        1113,
        0,
        0,
        371,
        3809
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$6.99 - $69.99 per item",
    "developer": "Horsemen AI Tech",
    "developerId": "Horsemen+AI+Tech",
    "developerEmail": "horsemenai@gmail.com",
    "developerWebsite": "https://d9f121933.app-ads-txt.com/",
    "developerAddress": "ROOM P 4/F LLADROCENTRE72 HOI YUEN ROAD\nKWUN TONG\nKL",
    "privacyPolicy": "https://sites.google.com/view/honeychat-privacy",
    "genre": "Entertainment",
    "genreId": "ENTERTAINMENT",
    "categories": [
        {
            "name": "Entertainment",
            "id": "ENTERTAINMENT"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/NK6DFmn3znzSr-kSH0uwubu1ZTW7NUaREGP3x_EeGTGeZe1y7pe2L9d4OtYITWBtYBs",
    "headerImage": "https://play-lh.googleusercontent.com/YD7iaoIZnZKeV9RxA1rXa_JJimaUe2CfFMYOVwXpKBWa5uvoIoNiIqTUbB1mfHT9fTU",
    "screenshots": [
        "https://play-lh.googleusercontent.com/c4b5-fUCovxS0XiK1Er9xins2tphS1npBjYidEsnO-3IMpUT1zyA7a95dYGMiXcOJQ",
        "https://play-lh.googleusercontent.com/XW35W_Zd5PDHEcBddRpUSTuC-CdffwTMrH6ae-fZFcpPjjskmBQcbx_AnQWahpI_dQ",
        "https://play-lh.googleusercontent.com/4UNifCl-OtxVFSUm5YhkBehGY_H8BrFpga27LI8JP_Ozr9S_ktJ9Fv4AM-EOJumzY0I",
        "https://play-lh.googleusercontent.com/zI8RHoOcLuhZb1J56QR8T09CVWHtzcYuRdSVw-zqnzFSTlM9W74JjFaE11F--po7x-Q",
        "https://play-lh.googleusercontent.com/--ytCS0eVprqojmKy0vGcewRcNnIKXMBUY7AvON_XyWDiQ3VtP_QY1wI8QlHSqeaDwIn",
        "https://play-lh.googleusercontent.com/1RAd5ewYqfcpEGI5o1b9WLfk2ILVoqB54hVkPh3yhjjr3ZEPuqd8QZWqyiJiv1BPnQ",
        "https://play-lh.googleusercontent.com/sVL1I9w3zd0nUFY83E3-gd-gSFXzfk3QTPWO1kn4QWg3gQJBhoMxEKIQX40QexEeQL8",
        "https://play-lh.googleusercontent.com/lSEQ0i6Vp0ZEGm-AYZsAlLdKp9lrYLcVw_pveIOuNb-9lfcbVDRvxx7PySJlNonMFw",
        "https://play-lh.googleusercontent.com/QML53xpnXFekJg2m7_MWhXIRMN_1N8b5tuJKm_jYMZWwV4kTbpIdUyWoYEEk9HgRYuQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": true,
    "containsAds": true,
    "released": "May 21, 2024",
    "lastUpdatedOn": "Oct 11, 2024",
    "updated": 1728640532,
    "version": "1.0.3",
    "comments": [],
    "appId": "com.honey.chat.gp",
    "url": "https://play.google.com/store/apps/details?id=com.honey.chat.gp&hl=en&gl=us"
}