{
    "title": "99acres Buy/Rent/Sell Property",
    "description": "Offices, Shops, Showrooms for Buy, Sell, Rent in one App. \r\n\r\nWelcome to 99acres.com, India\u2019s highest-rated property app for buying, selling and renting real estate. This is the only property app you require for all your real estate needs for searching, shortlisting and finalizing property of your choice. Be it a ready-to-move flat in a new project, investment in shops, offices or showrooms, or girls PG or boys PG in your city, app has listings from qualified property agents & top builders as well as no brokerage properties.\r\n\r\nOne stop solution for all your housing needs. Search for residential and commercial property options from owners, brokers and top builders on this user-friendly app that has helped millions of users to start their real estate journey with us.\r\n\r\nCheck key features of 99acres.com real estate app, India\u2019s best and most trusted property search app:\r\n\r\n\u2713<b>Browse multiple property options across categories</b> in 600+ cities. You can buy or rent flats, houses, plots, farmhouses, service apartments through 99acres property app. In the commercial category, explore office spaces, shops, showrooms, land and plots for buying and leasing.\r\n\r\n\u2713Explore <b>no broker</b> property options with 99acres where millions of genuine property owners list their 100% brokerage free flats, houses, offices, shops for renting, leasing, selling.\r\n\r\n\u2713<b>Personalize your search results</b> as per your requirements and save relevant property options for later. Whether you are looking to buy a flat, rent a flat, rent/lease a shop or buy a plot, you can use our smart filters to customize your results.\r\n\r\n\u2713Research any neighborhood using our <b>Real Estate Intelligence</b> platform on 99acres real estate app where you get detailed, unbiased information about the positives & negatives of localities across the country, based on realistic data points..\r\n\r\n\u2713To bring genuine information about your preferred society/locality, 99acres house search app has a <b>Ratings & Reviews</b> feature where existing and past residents rate and review their society/locality and give their honest opinion to help you make an informed decision.\r\n\r\n\u2713Fast-forward your property house hunt using our <b>landmark search on 99acres  app</b> to explore houses, flats, shops, offices in and around your preferred localities.\r\n\r\n\u2713Track price trends in your locality, city with 99acres property app. Access property transaction prices, locality insights and latest real estate trends with interactive graphs and charts.\r\n\r\n\u2713<b>Create a rental agreement online</b> on 99acres mobile app and get it delivered to your doorstep. Now you can rent a house on the go. It is not just easy but quick and convenient too. Choose a customizable template and leave the rest on 99acres.\r\n\r\n\u271399acres housing app also connects homeowners to homebuyers and tenants. This property selling app for homeowners helps with services like dedicated relationship manager, posting through WhatsApp, etc.\r\n\r\nHere is why 99acres is the <b>best real estate app</b>:\r\n\r\n\u2714\ufe0f 4M+ properties to search from\r\n\u2714\ufe0f Backed by AI for faster and efficient property search\r\n\u2714\ufe0f Each listing with detailed information and genuine photos & videos. \r\n\u2714\ufe0f Similar Localities to search better options in a locality similar to ones you are searching for\r\n\u2714\ufe0f Advance Filter Search with simple steps through India\u2019s No.1 housing app\r\n\r\nSo, download our app now and start your property search with us right away! \r\nLet us know what you think! Rate our app, or send feedback to feedback@99acres.com",
    "descriptionHTML": "Offices, Shops, Showrooms for Buy, Sell, Rent in one App. <br><br>Welcome to 99acres.com, India\u2019s highest-rated property app for buying, selling and renting real estate. This is the only property app you require for all your real estate needs for searching, shortlisting and finalizing property of your choice. Be it a ready-to-move flat in a new project, investment in shops, offices or showrooms, or girls PG or boys PG in your city, app has listings from qualified property agents &amp; top builders as well as no brokerage properties.<br><br>One stop solution for all your housing needs. Search for residential and commercial property options from owners, brokers and top builders on this user-friendly app that has helped millions of users to start their real estate journey with us.<br><br>Check key features of 99acres.com real estate app, India\u2019s best and most trusted property search app:<br><br>\u2713<b>Browse multiple property options across categories</b> in 600+ cities. You can buy or rent flats, houses, plots, farmhouses, service apartments through 99acres property app. In the commercial category, explore office spaces, shops, showrooms, land and plots for buying and leasing.<br><br>\u2713Explore <b>no broker</b> property options with 99acres where millions of genuine property owners list their 100% brokerage free flats, houses, offices, shops for renting, leasing, selling.<br><br>\u2713<b>Personalize your search results</b> as per your requirements and save relevant property options for later. Whether you are looking to buy a flat, rent a flat, rent/lease a shop or buy a plot, you can use our smart filters to customize your results.<br><br>\u2713Research any neighborhood using our <b>Real Estate Intelligence</b> platform on 99acres real estate app where you get detailed, unbiased information about the positives &amp; negatives of localities across the country, based on realistic data points..<br><br>\u2713To bring genuine information about your preferred society/locality, 99acres house search app has a <b>Ratings &amp; Reviews</b> feature where existing and past residents rate and review their society/locality and give their honest opinion to help you make an informed decision.<br><br>\u2713Fast-forward your property house hunt using our <b>landmark search on 99acres  app</b> to explore houses, flats, shops, offices in and around your preferred localities.<br><br>\u2713Track price trends in your locality, city with 99acres property app. Access property transaction prices, locality insights and latest real estate trends with interactive graphs and charts.<br><br>\u2713<b>Create a rental agreement online</b> on 99acres mobile app and get it delivered to your doorstep. Now you can rent a house on the go. It is not just easy but quick and convenient too. Choose a customizable template and leave the rest on 99acres.<br><br>\u271399acres housing app also connects homeowners to homebuyers and tenants. This property selling app for homeowners helps with services like dedicated relationship manager, posting through WhatsApp, etc.<br><br>Here is why 99acres is the <b>best real estate app</b>:<br><br>\u2714\ufe0f 4M+ properties to search from<br>\u2714\ufe0f Backed by AI for faster and efficient property search<br>\u2714\ufe0f Each listing with detailed information and genuine photos &amp; videos. <br>\u2714\ufe0f Similar Localities to search better options in a locality similar to ones you are searching for<br>\u2714\ufe0f Advance Filter Search with simple steps through India\u2019s No.1 housing app<br><br>So, download our app now and start your property search with us right away! <br>Let us know what you think! Rate our app, or send feedback to feedback@99acres.com",
    "summary": "Buy, Rent, Sell : App for Flats, Apartments, Homes or No Broker Property options",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 24592446,
    "score": 3.8660715,
    "ratings": 168799,
    "reviews": 643,
    "histogram": [
        34657,
        2978,
        12041,
        19551,
        99440
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "infoedge.com",
    "developerId": "infoedge.com",
    "developerEmail": "feedback@99acres.com",
    "developerWebsite": "https://www.99acres.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.99acres.com/load/Company/privacy",
    "genre": "House & Home",
    "genreId": "HOUSE_AND_HOME",
    "categories": [
        {
            "name": "House & Home",
            "id": "HOUSE_AND_HOME"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/0c3VhbTRqGPb9AH_rhScqpfXTcSk9KZRlgf9dveHVITv-AWmv7Rok88qGyHuLas2lA",
    "headerImage": "https://play-lh.googleusercontent.com/l5sCKIvymA3dOJfF1HMdXUAhau6ghSmUyK-NDhr1HPwFN4TvnNRKdXxgjgh5vBC9R0U",
    "screenshots": [
        "https://play-lh.googleusercontent.com/63_m1T1fZHQn4OULTTcvtVeyk2G_8ZAXrSrCIUfy-cRUCvnG6dY729Plh90POUddm_g",
        "https://play-lh.googleusercontent.com/auvpUg7QWoExzrkB5cW88zrlR0oLXUq9292FtB3rjS3c04QalsVl5xNW6U48kvzw4m8",
        "https://play-lh.googleusercontent.com/gcCMhblgwv7qWkTSpN4uhfqQwGJOCYsjTJeqlzSuLdbnaQdMwxR179xKtKcIO6v2WPg",
        "https://play-lh.googleusercontent.com/yXG44sPc0_JDcTX2UqsQC_Ztm6DUgkd7mmCucfkWfTyzWlXcQ58nZxgzgwt45QwlxA",
        "https://play-lh.googleusercontent.com/7VEyrcroyfwRlTeIqOdLyoNkpmU6TT9ipDkkftU11aUxfHV2PFnH4viJ54pcFbYJC2U",
        "https://play-lh.googleusercontent.com/yNpW0vUgxNJDllFHTZxS47H7YTJoFwCkJIFomP1hxLaKQK2arSFOrv28BfpotOGAoWsz",
        "https://play-lh.googleusercontent.com/4p--M5XP6qujgRa4Jy0tepxwrOp4NX3uLBxcn829NAyjzpeRgNWKvmY_grNS2QjWHb0",
        "https://play-lh.googleusercontent.com/HnP98vt7mFil0d4uBxVDmS8NoQEkT5C9slRRcaIdNeh3CRT7UdNcZe0NlZscnZtA0bU3"
    ],
    "video": "https://www.youtube.com/embed/y6aku6qjno4?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/l5sCKIvymA3dOJfF1HMdXUAhau6ghSmUyK-NDhr1HPwFN4TvnNRKdXxgjgh5vBC9R0U",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 17, 2013",
    "lastUpdatedOn": "Oct 10, 2024",
    "updated": 1728621553,
    "version": "15.0.7",
    "comments": [],
    "appId": "com.nnacres.app",
    "url": "https://play.google.com/store/apps/details?id=com.nnacres.app&hl=en&gl=us"
}