{
    "title": "Untappd: Find Beer You'll Love",
    "description": "Discover and share great beers, breweries, and venues with your friends, while earning badges for exploring beers of different styles and countries.\r\n\r\nDiscover nearby venues, events, and beers that you'll love\r\nKeep track of the beers you like and create lists for later\r\nGet alerts when your favorite verified venues add new beers\r\nFind new venues with great beers, anywhere in the world\r\nFollow your friends and see what beers they're enjoying\r\nFor help and support, visit http://help.untappd.com\r\n\r\nTwitter: http://twitter.com/untappd\r\nFacebook: http://facebook.com/untappd\r\nInstagram: http://instagram.com/untappd\r\n\r\nUntappd reminds you to please drink responsibly.",
    "descriptionHTML": "Discover and share great beers, breweries, and venues with your friends, while earning badges for exploring beers of different styles and countries.<br><br>Discover nearby venues, events, and beers that you&#39;ll love<br>Keep track of the beers you like and create lists for later<br>Get alerts when your favorite verified venues add new beers<br>Find new venues with great beers, anywhere in the world<br>Follow your friends and see what beers they&#39;re enjoying<br>For help and support, visit http://help.untappd.com<br><br>Twitter: http://twitter.com/untappd<br>Facebook: http://facebook.com/untappd<br>Instagram: http://instagram.com/untappd<br><br>Untappd reminds you to please drink responsibly.",
    "summary": "Drink Socially! Discover, buy, and share beers, breweries, and bars near you!",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 5451436,
    "score": 4.759693,
    "ratings": 267606,
    "reviews": 15994,
    "histogram": [
        1173,
        426,
        3467,
        51396,
        211140
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $54.99 per item",
    "developer": "Untappd",
    "developerId": "Untappd",
    "developerEmail": "help@untappd.com",
    "developerWebsite": "https://untappd.com",
    "developerAddress": "1213 W Morehead Street, Suite 220\nCharlotte NC 28208-5576\nUnited States",
    "privacyPolicy": "https://untappd.com/privacy",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/e1f4pqu_nn0p6MgMI0YW3vBWy9GLlim_8ln_9xe1fLcq91Xi8X7r9BeqDy5kMoKDuTM",
    "headerImage": "https://play-lh.googleusercontent.com/XHlhO9oYBInsDKcl-mox1UvYlxUe1Edd0UpWVOTavu0oQjFzHympQIrRLt6zw4ZoZes",
    "screenshots": [
        "https://play-lh.googleusercontent.com/d8AnO2PnztHwqE-MX7B-6x20LEhVcDF6pgb3h-75iTVarFk-RNwujD08-3-0HSc4qGjx",
        "https://play-lh.googleusercontent.com/6hcfDVn1_FWLsrSPzYYGIgwvhH3DgfMLtUf_N2oxRyf5CB5pQ5zWhD6VoWkphpP2bQ",
        "https://play-lh.googleusercontent.com/O3lyv3ew6FFP7YUbC6z0ia0QLViUeR4J-CPQ5YTj5wGyJuP_ZAexIy8rno0rLYmvU1c",
        "https://play-lh.googleusercontent.com/SrMM_DkOfo_bQhXBaNQDBeayBOZEjBY2eX0dElLH50926Zws_KOXcnnn94exMe8Icw",
        "https://play-lh.googleusercontent.com/EnK28eUH-3ybmHnlhR3J_NwhmfAHYOtyyxPbIUPj7KTRKWo5ckrZGukBxYHOwVjcMpE",
        "https://play-lh.googleusercontent.com/Y-jN4OBySkk24cLlxRLAKcuh9D4GpllLw09E6cNsqBlgpkU6N9VlQoaZCgGLJHFDfao",
        "https://play-lh.googleusercontent.com/m5G3c4wkZRnww9wGcW6lwCDK0yeorhNb6AUv8Lv_vjatfVf0wTWIe7dJWCNDtL6V71lX"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 29, 2011",
    "lastUpdatedOn": "Oct 7, 2024",
    "updated": 1728317569,
    "version": "4.4.12",
    "comments": [],
    "appId": "com.untappdllc.app",
    "url": "https://play.google.com/store/apps/details?id=com.untappdllc.app&hl=en&gl=us"
}