{
    "title": "AARP Now",
    "description": "Access your digital membership card from day one by downloading AARP Now. As a member, you can access your digital card anytime from the My Account tab and join AARP or renew your membership with a tap. The app also gives you access to relevant news stories, local and online events, and nearby member benefits including limited time member offers. Also, join AARP Rewards and sync to the Health app or your favorite fitness tracker and start earning points today.\r\n\r\nMake the most of your membership by downloading AARP Now today!\r\n\r\nDIGITAL CARD/MEMBERSHIP\r\n\r\nGet instant access to your digital membership card, add your card to your Apple Wallet, join AARP, or renew your membership in seconds. Plus, manage your account on the go!\r\n\r\nNEWS\r\n\r\nCatch up on the latest news in just a few minutes; the AARP Now App features daily stories written with you and your mobile lifestyle in mind. Share news articles with your friends and join the conversation!\r\n\r\nEVENTS\r\n\r\nExplore hundreds of local events and online virtual events, from career workshops and movie showings to kid-friendly events, and quickly register for them right from the app.\r\n\r\nMEMBER DISCOUNTS\r\n\r\nSearch for benefits and discounts in your neighborhood. Offers are added monthly.\r\n\r\nGAMES\r\n\r\nAccess AARP Games, wherever you are! From Word & Trivia Games to Arcade Games to Solitaire & Mahjongg, there's something for everyone.\r\n\r\nNOTIFICATIONS\r\n\r\nReceive news alerts, reminders for upcoming events or when benefits you have saved are nearby. You can easily manage your notifications in My Account > Notifications.\r\n\r\nAARP REWARDS\r\n\r\nGet more from AARP Now with the AARP Rewards program! Earn Rewards points for downloading the app and visiting the app each day, plus synchronize your favorite fitness tracker or the Health app to get even more points for steps, swimming, and cycling.\r\n\r\nNOT AN AARP MEMBER?\r\n\r\nNo problem! Non-members are welcome to download the app, join AARP Rewards, and learn more about how AARP is protecting and improving the lives of people 50-plus.\r\n\r\nIf there are AARP services or information you are unable to find in the app, we encourage you to visit aarp.org on your mobile phone to access them on the go!",
    "descriptionHTML": "Access your digital membership card from day one by downloading AARP Now. As a member, you can access your digital card anytime from the My Account tab and join AARP or renew your membership with a tap. The app also gives you access to relevant news stories, local and online events, and nearby member benefits including limited time member offers. Also, join AARP Rewards and sync to the Health app or your favorite fitness tracker and start earning points today.<br><br>Make the most of your membership by downloading AARP Now today!<br><br>DIGITAL CARD/MEMBERSHIP<br><br>Get instant access to your digital membership card, add your card to your Apple Wallet, join AARP, or renew your membership in seconds. Plus, manage your account on the go!<br><br>NEWS<br><br>Catch up on the latest news in just a few minutes; the AARP Now App features daily stories written with you and your mobile lifestyle in mind. Share news articles with your friends and join the conversation!<br><br>EVENTS<br><br>Explore hundreds of local events and online virtual events, from career workshops and movie showings to kid-friendly events, and quickly register for them right from the app.<br><br>MEMBER DISCOUNTS<br><br>Search for benefits and discounts in your neighborhood. Offers are added monthly.<br><br>GAMES<br><br>Access AARP Games, wherever you are! From Word &amp; Trivia Games to Arcade Games to Solitaire &amp; Mahjongg, there&#39;s something for everyone.<br><br>NOTIFICATIONS<br><br>Receive news alerts, reminders for upcoming events or when benefits you have saved are nearby. You can easily manage your notifications in My Account &gt; Notifications.<br><br>AARP REWARDS<br><br>Get more from AARP Now with the AARP Rewards program! Earn Rewards points for downloading the app and visiting the app each day, plus synchronize your favorite fitness tracker or the Health app to get even more points for steps, swimming, and cycling.<br><br>NOT AN AARP MEMBER?<br><br>No problem! Non-members are welcome to download the app, join AARP Rewards, and learn more about how AARP is protecting and improving the lives of people 50-plus.<br><br>If there are AARP services or information you are unable to find in the app, we encourage you to visit aarp.org on your mobile phone to access them on the go!",
    "summary": "Get the news, events and savings that matter to you with AARP Now.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4225185,
    "score": 4.6519895,
    "ratings": 46084,
    "reviews": 5670,
    "histogram": [
        1245,
        751,
        1626,
        5541,
        36916
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "AARP",
    "developerId": "AARP",
    "developerEmail": "appfeedback@aarp.org",
    "developerWebsite": "https://now.aarp.org",
    "developerAddress": null,
    "privacyPolicy": "http://www.aarp.org/about-aarp/info-05-2010/privacypolicy.html",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/w8GQ_RfzbA0chifW96F0ETZHC6XA2Hot2Fr-eHDbSSK5htpjl_VBHpqVX5aGQ5cJfaY",
    "headerImage": "https://play-lh.googleusercontent.com/FDEfkVF_iPCtHz0Ln9Rw1BM1ybGQT-YdQ8nd_2LMNOnqPZuCssZk2tCLRVGVJRKyGCE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/7a9KBldepmJ-XkFge6XJPnZBFHlo6c7dL8G5LzAbKbYvMyO7d6iRges0i1SgO5JgvhM",
        "https://play-lh.googleusercontent.com/N5fq8lJSdU77HoQYRCIP90TZa7waoCZZjlXaYkUnR4sZJn8E9wp1y7aGOK4hmwxp2Wo",
        "https://play-lh.googleusercontent.com/VBHSUW-SwYuBlhTG20XvYoV-YKz1GQbToAhAM9DDW0xhMFRxCVS3JL5zKf_R5uW4PfD6",
        "https://play-lh.googleusercontent.com/AhYR0m16Dgn4kAau9Gc-TK3eZjHgEduzadC8oBpMYk-C2eE4gCCrYANSFKMfl57-lqLP",
        "https://play-lh.googleusercontent.com/C6OzK4W6ncp_P3qOiM6-bhIajKivWwy7sgC8UHTudZcNFnLv_vhAFBk2kKTpmp_kWTnW",
        "https://play-lh.googleusercontent.com/RrIwGXtDkWtvL491w94b1lR-DqRlL790jL9BoSL_po9aq5Bmg4jiktADJfLVB0Pvy7w",
        "https://play-lh.googleusercontent.com/Z85P3gviOHFeDaCMAdgG3Dthmk771ftwEyZ8D5xFsWjvnkm_w_18uMdVTecgSIwngqrp",
        "https://play-lh.googleusercontent.com/NJKBK-lhahYiM3hlmDUB0koeBwEHEppblxfRJChfWrTLb_dglPVvjOCx-3uQPUZQSCb6"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 29, 2011",
    "lastUpdatedOn": "Jul 4, 2024",
    "updated": 1720103401,
    "version": "3.37.2",
    "comments": [],
    "appId": "com.aarp.app",
    "url": "https://play.google.com/store/apps/details?id=com.aarp.app&hl=en&gl=us"
}