{
    "title": "Idol Prank Video Call & Chat",
    "description": "Are you a fan of K-pop and US-UK idols? If yes, then Idol Prank Video Call & Chat is a cool prank app for you! This app lets you make fake video calls and chat with your favorite idols from various celebrities.\r\n\r\nHow to play:\r\n\ud83e\udd21 Choose your favorite idol.\r\n\ud83e\udd21 Prank video call or chat with your idol.\r\n\ud83e\udd21 Talk to your idol as a good friend.\r\n\ud83e\udd21 Flex with your friends.\r\n\r\nFeature:\r\n\ud83d\udc49 Realistic fake calls and chats.\r\n\ud83d\udc49 Variety of celebrities.\r\n\ud83d\udc49 100% FREE high-quality video calling.\r\n\ud83d\udc49 Easy and simple to use.\r\n\r\nDownload Idol Prank Video Call & Chat now and let's prank your friends!",
    "descriptionHTML": "Are you a fan of K-pop and US-UK idols? If yes, then Idol Prank Video Call &amp; Chat is a cool prank app for you! This app lets you make fake video calls and chat with your favorite idols from various celebrities.<br><br>How to play:<br>\ud83e\udd21 Choose your favorite idol.<br>\ud83e\udd21 Prank video call or chat with your idol.<br>\ud83e\udd21 Talk to your idol as a good friend.<br>\ud83e\udd21 Flex with your friends.<br><br>Feature:<br>\ud83d\udc49 Realistic fake calls and chats.<br>\ud83d\udc49 Variety of celebrities.<br>\ud83d\udc49 100% FREE high-quality video calling.<br>\ud83d\udc49 Easy and simple to use.<br><br>Download Idol Prank Video Call &amp; Chat now and let&#39;s prank your friends!",
    "summary": "Be the coolest person when prank video call and chat with idols.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 8835295,
    "score": 4.565445,
    "ratings": 25315,
    "reviews": 76,
    "histogram": [
        1582,
        518,
        917,
        1183,
        21073
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "HIGAME GLOBAL",
    "developerId": "7611998915687133068",
    "developerEmail": "Store@higame.com.vn",
    "developerWebsite": "https://higame.com.vn/",
    "developerAddress": null,
    "privacyPolicy": "https://higame.com.vn/privacy",
    "genre": "Casual",
    "genreId": "GAME_CASUAL",
    "categories": [
        {
            "name": "Casual",
            "id": "GAME_CASUAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/cL3GB_HaoNIPd80s5E-NWWk8L5Mh42g62IUjTp7ctAnLyhw0uxPUOxxZFpRL4o2-uA5q",
    "headerImage": "https://play-lh.googleusercontent.com/F3_9xcrO-RGRSpayMzE8Or2lJ-ufXNDcEDdshmiKtLkt8pDtg-G6cBkK4GJVi2_VdjQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ig3LShcyfcQcIezfFxDVvFCDIDl6iF-pSWoxSD5SL5eAueJvhVT3DfydmZ1LBB55PaU",
        "https://play-lh.googleusercontent.com/bqoFMG7tbNVpv274OR0mdfz-dHD9oK87TWXI0jPmYlb9aMCuez72GWvtWwYBaAjUFPU",
        "https://play-lh.googleusercontent.com/1FXsLp5wgItbE1Ad8gAX-JTAZkq_pzO0_Ya0jZZ609bP1jHnRntaJauzOVfh4YBrzJQ",
        "https://play-lh.googleusercontent.com/Pg0zZJg-UMjMdJFbKESzjLpIDdgRbLIrfVoF1hRpXoL28MheViP6Mv96z4V6FkKsOfUX",
        "https://play-lh.googleusercontent.com/P4KRwM81zjz0-KVj6IVPSMd7EJtDWqgtscjGsDjQoLvEvkrpC02pmvVxS845Iu3FaEsC",
        "https://play-lh.googleusercontent.com/KytoOfJV_lHSrDfjmVsIopBCtg2aFFe5wWqkTTAzgBzsVHVMB-tgxt0Bh2DNaY_dCDI",
        "https://play-lh.googleusercontent.com/f5pqz6ReLci-7fg4jVljyn4wDgeBLIElLkwnvnKWctqtERIZmn2lb1StGBZuSGqUo0zD",
        "https://play-lh.googleusercontent.com/yoPls1j8Spj_TG3rcvk4QxmpRE2ZEdMte13H83oNw4nhKOj9bAfNyW5M9n3g5qm9zC4",
        "https://play-lh.googleusercontent.com/ztpOLiDGwF-YFqb7pOJCdWjJ-vCEM-wWkpwv4-k_93hPaLsi78Y2khJE_M2xGOGcNc-5",
        "https://play-lh.googleusercontent.com/Ubqol3mx4pndzJAidACqBkq0FeiE_zRzzh2It8TmMfn8z_pwUPlMUf_PLN80R79XeXw",
        "https://play-lh.googleusercontent.com/ehWOgZfKj08FVUdDgzqWpJxvFLodCegTwvsq7-HVmwNIRR_LyH6Hh67i_HblgWRkdg",
        "https://play-lh.googleusercontent.com/34RgtU06VERp3co6IUGKFyf9P0ZM0nuPpDKtzxpwJKGlwaJH8g6LP2RqzvH1_0iGBZg",
        "https://play-lh.googleusercontent.com/lW243OmCarA00Q_WRBLx-zH5ndjZkpEuIJqd8q2YUkdrDtt04vEIJaYioZUpf4VS07U",
        "https://play-lh.googleusercontent.com/mnJmtFDCq29jwWZEtXZfbza_ed2A7kBoKn-mIejguPEPr9giLN3RMLwXhXWSaKIg7z0",
        "https://play-lh.googleusercontent.com/F5O9VtwgLDTdpBYN0ap1Gc1WVNMa6G7UEQhckvOMmtiIX07PGK6p3zKi9e7_zCiMmkus"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jan 24, 2024",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729507600,
    "version": "0.19",
    "comments": [],
    "appId": "com.higame.par.idol.prank.video.call.chat.phone.fun",
    "url": "https://play.google.com/store/apps/details?id=com.higame.par.idol.prank.video.call.chat.phone.fun&hl=en&gl=us"
}