{
    "title": "Last Z: Survival Shooter",
    "description": "In an apocalyptic world overrun by the undead, where the fate of humanity hangs in the balance amid diminishing living spaces, will you rise as the hero we need to reshape the destiny of humankind? Uncover the adventure of Last Z: Survival Shooter \u2013 your destiny awaits!\r\n\r\nDodge & Shoot\r\nIn the heart of the zombie-infested apocalypse, survival is not just a choice but an exhilarating stage, challenging the prowess of dodging and shooting skills. Navigate through waves of relentless undead, strategically evading their onslaught while honing your precision shooting. Each dodge and shoot propel you closer to victory, earning you abundant rewards in this thrilling game of wits and reflexes. \r\n\r\nExplore & Expand\r\nBrace yourself for an adrenaline-fueled journey where the apocalypse is your playground for exploration and expansion. Explore abandoned areas, uncover hidden treasures, grow from epic battles, and forge bonds with reliable companions who accompany you through thick and thin. Every step of the way brings you closer to establishing your own doomsday shelter. \r\n\r\n\r\nSurvive & Thrive\r\nIn Last Z: Survival Shooter, survival marks merely the starting point as you endeavor not just to survive but to thrive amid impending annihilation. Through exploration, expansion, and evolution, the world transforms into a vast canvas of growth and opportunity. Your prowess ascends across economic, technological, and military realms, unlocking boundless potential. And your burgeoning shelter will ultimately emerge as a beacon of hope for human civilization. \r\n\r\nExplore, thrive, and redefine the meaning of survival in this gripping saga. Download Last Z: Survival Shooter now, plunge into the ultimate test of survival, and unveil the depths of your courage to conquer the apocalypse!",
    "descriptionHTML": "In an apocalyptic world overrun by the undead, where the fate of humanity hangs in the balance amid diminishing living spaces, will you rise as the hero we need to reshape the destiny of humankind? Uncover the adventure of Last Z: Survival Shooter \u2013 your destiny awaits!<br><br>Dodge &amp; Shoot<br>In the heart of the zombie-infested apocalypse, survival is not just a choice but an exhilarating stage, challenging the prowess of dodging and shooting skills. Navigate through waves of relentless undead, strategically evading their onslaught while honing your precision shooting. Each dodge and shoot propel you closer to victory, earning you abundant rewards in this thrilling game of wits and reflexes. <br><br>Explore &amp; Expand<br>Brace yourself for an adrenaline-fueled journey where the apocalypse is your playground for exploration and expansion. Explore abandoned areas, uncover hidden treasures, grow from epic battles, and forge bonds with reliable companions who accompany you through thick and thin. Every step of the way brings you closer to establishing your own doomsday shelter. <br><br><br>Survive &amp; Thrive<br>In Last Z: Survival Shooter, survival marks merely the starting point as you endeavor not just to survive but to thrive amid impending annihilation. Through exploration, expansion, and evolution, the world transforms into a vast canvas of growth and opportunity. Your prowess ascends across economic, technological, and military realms, unlocking boundless potential. And your burgeoning shelter will ultimately emerge as a beacon of hope for human civilization. <br><br>Explore, thrive, and redefine the meaning of survival in this gripping saga. Download Last Z: Survival Shooter now, plunge into the ultimate test of survival, and unveil the depths of your courage to conquer the apocalypse!",
    "summary": "Plunge into the ultimate test of survival and conquer the apocalypse!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 457219,
    "score": 4.7371793,
    "ratings": 5821,
    "reviews": 753,
    "histogram": [
        72,
        16,
        242,
        689,
        4794
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "SILKWORLD GAME LIMITED",
    "developerId": "SILKWORLD+GAME+LIMITED",
    "developerEmail": "support-all@readygo.tech",
    "developerWebsite": "https://metapoint.club/apps/barrel/",
    "developerAddress": "Rm 603 6/F Laws Coml Plz\n788 Cheung Sha Wan Rd\nLai Chi Kok\nHong Kong",
    "privacyPolicy": "https://metapoint.club/privacy.htm",
    "genre": "Strategy",
    "genreId": "GAME_STRATEGY",
    "categories": [
        {
            "name": "Strategy",
            "id": "GAME_STRATEGY"
        },
        {
            "name": "4X",
            "id": null
        },
        {
            "name": "Stylized",
            "id": null
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ZpJDsF0VNWEUgvi6JWlyP5UYS-HyggcVtcSzwPI53BmaYzyimcfQD4daIharZLY1qHM",
    "headerImage": "https://play-lh.googleusercontent.com/FTIjtXUHYWAEasipSj18gvfF_ZfIM8t2ziFYADJBSkOm52z8qJozWuqb5DNYA49Vdz4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/rXWte-nbpQD-eB0Q4xY_i7UhZC7AdRgDDQlo3bwUGVe069ggx15QZBBUU6Ac4tjZuv4",
        "https://play-lh.googleusercontent.com/IyQL7pFs2WZ5v-2LbKYTqALdeFRjVBwH8HeKLZ5HBqr_GueQeOTIKcMTcUsmW_tmOeo",
        "https://play-lh.googleusercontent.com/RjaRx3uwS7y2KQN3TrMxoU6i-fRpUWptxLmgk0riFi7ugAnWquTzchxSmfY-9B-KWB4",
        "https://play-lh.googleusercontent.com/q49hr8FJ3W-NX7M8gFu9zDTz-8MyAY6mOifFHHRGO90uLdTa7g9yV4rm6T2lQJfQ0To",
        "https://play-lh.googleusercontent.com/rN7o8lXjvCD6Ut8fP9Ti1MIXb0EDoCXFxZt1YmdZcek4z-gAIp_mQ7DvN4Wy7-IlInzx",
        "https://play-lh.googleusercontent.com/UQna9bphxqbohKXN9FffZZkgF2kSC66GHw6tFQTTcabCuk1KPq97QGHRLMsUcX_S8di8",
        "https://play-lh.googleusercontent.com/XALpReEYqNOFFFMMXA9jKC0al8yDqmOAXj_spZwRSBZcXsSvOs8wnbgIL6DhKZ3AFVI",
        "https://play-lh.googleusercontent.com/Cmzd5tbESrNx6WoUJxlzHIXf8VbC8nMud6j3S1qx9Sq0Y8-Bq8RAumZ501pyQ53w7A",
        "https://play-lh.googleusercontent.com/cHO38Mnpiqta5GKiC1khwTuLdcgMbbqbQSmYOIeVoiA1sXTQOaGip42J_Uc-HX8tA1m9",
        "https://play-lh.googleusercontent.com/2RYle-KNaCriGpRRU2Dahgz5Onw1d_BAV0q0yEpgTU5hC9m1ipcoRJX2-Q1TrgWeITU",
        "https://play-lh.googleusercontent.com/tX6QIphd_zGwqTxoxOdliaZEOynJYpt3gSDUrIu81U4nVfLo4H0rix9325m0oxRLj5g",
        "https://play-lh.googleusercontent.com/S97fPi1U2MeyT4dS5BjbYZWD9z5kxuToGEOKaa1pcTOtmKaw2ookEqeO32Cx8bQ6FOY",
        "https://play-lh.googleusercontent.com/XIrcOg7MchCJbHPWxtZCDkOsNcC2i-1h9IdwC9Z_FV1ar4JJulFjamgqt9n577Ayvw",
        "https://play-lh.googleusercontent.com/YKaSGEGc8ABANCRNLnv2YA5YW6KIuMByiX7pqMq0hwlg7AqULe11vStiOb9ysfp2HKc",
        "https://play-lh.googleusercontent.com/bblp2nTKUGkJkEhEJxkhdxbQTp5S1L2fKlAljIcT-keYaNLTXh1wu4DmY09m1cbxJA",
        "https://play-lh.googleusercontent.com/VybmP6ZN_HI8zT6UprE_NcJ4s0Pxiw6FSgVSTvth43yyowwrrnnVGfeXxHPhvY5YCumJ",
        "https://play-lh.googleusercontent.com/F-vYhvLVunOrG9Ao0kOmzo8u65klmmRZ3kAKMttuDUiUQ76dGZOoRafmOt7IJGTKgzY",
        "https://play-lh.googleusercontent.com/e1va0gav0TE-UXWb-IZjL6jcHqWZ2CexzY-L0aCPnwp7mx9rmn9vuSSnEJRxgCpV-exb",
        "https://play-lh.googleusercontent.com/k-ZgZpQn6dc_BhQv5vr-xbaaNZ2HQAUgTszLOklNk1xAlOeNSTOJBjUjkyY-eLd84w",
        "https://play-lh.googleusercontent.com/xgUlXursv3P41L2iUWhYoBWjaZvyYL5a68HGI47TCuDmuTJDQVk3WwDO8v5m_-Nq_g",
        "https://play-lh.googleusercontent.com/dznIzRM94wdrcpGyKYSg2H5t7wBLdm_HHhZ7mPMMoY6t5GPiaT2Y0lW6QgruDImxNP8"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Fantasy Violence, Mild Blood, Suggestive Themes, Use of Drugs",
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 7, 2024",
    "lastUpdatedOn": "Oct 23, 2024",
    "updated": 1729685700,
    "version": "1.250.632",
    "comments": [],
    "appId": "com.readygo.barrel.gp",
    "url": "https://play.google.com/store/apps/details?id=com.readygo.barrel.gp&hl=en&gl=us"
}