{
    "title": "Romantic Stickers WASticker.ly",
    "description": "Love and Romantic Stickers for WhatsApp WAStickerapp\r\n\r\nAre you looking for the perfect way to express your love. We have a romantic stickers app for you. With this WA Romantic Stickers App you can send love, kiss , hug,forehead kissing stickers with your love. You can also share your romantic feelings with your loved ones through these beautiful stickers.\r\n\r\nLooking for some new stickers for your WhatsApp app ? Here's a list of all the best stickers!\r\n\r\n1. Kisses   2.Romantic  3.Forehead Kissing  4.Loving  5.Hug Stickers  6.Sleeping With Partner  7.Cute Love  8.Romantic Couples  9.Cute loved Couple  10.Caring Love  11.Romantic Moments   12.Girlfriend Love\r\n\r\nRomantic stickers  are a popular way to express  your love. Romantic stickers for WhatsApp are the beautiful sticker conveying a different message of love and romance. Want to show your love with a romantic Stickers? This collection of romantic stickers features everything from heartfelt hugs and kisses to sweet embraces and loving touches. These stickers are perfect for letting your partner know just how much you care.\r\nThe most popular romantic stickers for WhatsApp are kiss stickers. Kiss stickers are usually used to show some love and romance with your partner. Romantic sticker is the kiss sticker. Kiss stickers are used to convey love and affection between two people. \r\n\r\nThrough this WA Romantic stickers app you can impress your love by sending him/her most beautiful romantic and caring stickers. When your love see these stickers in chat she/he fall in love with you and enjoy the feelings of love . These Stickers pack for WhatsApp can be used to express a variety of emotions such as, love , romance  and caring. lyStickers WA romantic Stickers with wings stickers are a popular choice for those looking to express their love in a unique and creative way.\r\n\r\nThere are also a variety of more modern options available in this romantic stickers app. These include stickers featuring popular love stickers, such as the heart eyes stickers or the kissing stickers.\r\n\r\nWhen your love sad or angry with you then make your love happiest and cool by sending these beautiful  WA romantic love stickers. Celebrate the feelings of love and share these romantic stickers for whatsapp with your girlfriend through chating.\r\n\r\nOverall, romantic stickers are a best way to express your love and someone special. There is sure to be a romantic sticker that perfectly conveys your feelings and emotions.\r\n\r\nHow to add Stickers for WhatsApp?\r\n\r\nInstall this 'WAStickers' app.\r\nTap on ADD BUTTON.\r\nClick on confirm dialog.\r\nYou have added stickers successfully for whatsapp.\r\nNow open whatsapp App and send stickers with your love.\r\nCheck in your WA Stickers\r\n\r\nIMPORTANT NOTE:\r\nDon't uninstall this romantic stickers WAStickersly App. Otherwise WA  will remove all the stickers from it.",
    "descriptionHTML": "Love and Romantic Stickers for WhatsApp WAStickerapp<br><br>Are you looking for the perfect way to express your love. We have a romantic stickers app for you. With this WA Romantic Stickers App you can send love, kiss , hug,forehead kissing stickers with your love. You can also share your romantic feelings with your loved ones through these beautiful stickers.<br><br>Looking for some new stickers for your WhatsApp app ? Here&#39;s a list of all the best stickers!<br><br>1. Kisses   2.Romantic  3.Forehead Kissing  4.Loving  5.Hug Stickers  6.Sleeping With Partner  7.Cute Love  8.Romantic Couples  9.Cute loved Couple  10.Caring Love  11.Romantic Moments   12.Girlfriend Love<br><br>Romantic stickers  are a popular way to express  your love. Romantic stickers for WhatsApp are the beautiful sticker conveying a different message of love and romance. Want to show your love with a romantic Stickers? This collection of romantic stickers features everything from heartfelt hugs and kisses to sweet embraces and loving touches. These stickers are perfect for letting your partner know just how much you care.<br>The most popular romantic stickers for WhatsApp are kiss stickers. Kiss stickers are usually used to show some love and romance with your partner. Romantic sticker is the kiss sticker. Kiss stickers are used to convey love and affection between two people. <br><br>Through this WA Romantic stickers app you can impress your love by sending him/her most beautiful romantic and caring stickers. When your love see these stickers in chat she/he fall in love with you and enjoy the feelings of love . These Stickers pack for WhatsApp can be used to express a variety of emotions such as, love , romance  and caring. lyStickers WA romantic Stickers with wings stickers are a popular choice for those looking to express their love in a unique and creative way.<br><br>There are also a variety of more modern options available in this romantic stickers app. These include stickers featuring popular love stickers, such as the heart eyes stickers or the kissing stickers.<br><br>When your love sad or angry with you then make your love happiest and cool by sending these beautiful  WA romantic love stickers. Celebrate the feelings of love and share these romantic stickers for whatsapp with your girlfriend through chating.<br><br>Overall, romantic stickers are a best way to express your love and someone special. There is sure to be a romantic sticker that perfectly conveys your feelings and emotions.<br><br>How to add Stickers for WhatsApp?<br><br>Install this &#39;WAStickers&#39; app.<br>Tap on ADD BUTTON.<br>Click on confirm dialog.<br>You have added stickers successfully for whatsapp.<br>Now open whatsapp App and send stickers with your love.<br>Check in your WA Stickers<br><br>IMPORTANT NOTE:<br>Don&#39;t uninstall this romantic stickers WAStickersly App. Otherwise WA  will remove all the stickers from it.",
    "summary": "Unlimited WAStickers Romantic stickers ,love ,kiss stickers to express your love",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4445314,
    "score": 4.3366337,
    "ratings": 4395,
    "reviews": 21,
    "histogram": [
        510,
        117,
        78,
        235,
        3374
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Future-Apps",
    "developerId": "6514929758715263413",
    "developerEmail": "digiappsofficial@gmail.com",
    "developerWebsite": "https://kaleemkhansial2233.blogspot.com/",
    "developerAddress": null,
    "privacyPolicy": "https://sites.google.com/view/romanticstickerswastickersly",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/f77_CTUkTRC58iK1al_DjD4gukOSIggET0JDdauGdONkqGjFDzeRkh7CW3Xfdgr3aBI",
    "headerImage": "https://play-lh.googleusercontent.com/Y7qehGGj4pe6tyOKXa2rS7UPgwSp9-nX1p-WS3-PlICXrYUCShPQEPHGEKKsoaNfct0W",
    "screenshots": [
        "https://play-lh.googleusercontent.com/OESwWeJ5PRNJ6UFEPNjI_T6fYZX1q96IFDXRJBqEUk7kyA-3jIfrvOjXuoajofLRXg",
        "https://play-lh.googleusercontent.com/q2hLfPoLnlIP73s9KYFTsa3FQqgV9746dEY4IlacXcspADQhqREi8gaNUKWmdi-oTQ",
        "https://play-lh.googleusercontent.com/PogOrLSEGyVg-5zo-lFNla5FeZ2V9FN_Cro26b8Dp4U2dYqLApUu5mSvI20i0HE_MA",
        "https://play-lh.googleusercontent.com/ZoD6SPrZuSJJr2aIAZeiPNaBeNShfdg-aB-Iw0pkNdcZPhAZMQLUD2SfQUM2Rau1SQE",
        "https://play-lh.googleusercontent.com/vO459rfAHCFICPVv4ebr_UZ78hppICvOJVcAxURR_YAZQ0tTmrJTFwBknbvz3l5nZZi1",
        "https://play-lh.googleusercontent.com/ucHb4Mqs-jjEolpVhZDSEW1SOGkieYW6ylSkGVbz-jPx0Oy2px8qgT4ufIGhb2tOLPSh",
        "https://play-lh.googleusercontent.com/Ob0NzPqtxUh38ngA9zgTe8XsxIOrQUrk_U1_5XsQWjns3Vkzx5r7XCGQTcA5ZMEr4Zs",
        "https://play-lh.googleusercontent.com/7zEru5iIAcqsHlYAoj-Tulz8RCrDeqXShTmrPPMluDgmMY8Xi7cVmrlGByNyGuzOytk",
        "https://play-lh.googleusercontent.com/q70yYO7-kFsplEojKRdM3CA69B7J2_ycvDLQJTCHDyYBt3m-01K9eMb_D_UfuYu9UGAw",
        "https://play-lh.googleusercontent.com/xyF70FzxFFAQRhSuJBFsDNOQs6x1opEGk8ietWrtK38u98lrYsVrpCvCe0rBMdcKEjg",
        "https://play-lh.googleusercontent.com/mGMkOvf8V2HTyuT2aEVr5Cik67kdCfdN777dJXhVv-wpmdFWtMmhn-er02ZiZvPW9fVI",
        "https://play-lh.googleusercontent.com/HWC5qHfo-cWiQwmbqGEzGX8QRl1XaETS2AO27LywpORtKjNcK8fq8I9qlZG1bpIrlpw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Sexual Content",
    "adSupported": true,
    "containsAds": true,
    "released": "May 7, 2023",
    "lastUpdatedOn": "Aug 14, 2024",
    "updated": 1723698996,
    "version": "1.3.7",
    "comments": [],
    "appId": "com.romanticstickers.lovestickers.wastickers.ly",
    "url": "https://play.google.com/store/apps/details?id=com.romanticstickers.lovestickers.wastickers.ly&hl=en&gl=us"
}