{
    "title": "Credit Genie: Get Cash Advance",
    "description": "Improve your financial health with breakthrough financial tools and services from Credit Genie, and find better ways to budget your spending.\r\n\r\nGET A CASH BOOST UP TO $100\u2020: We all can use a little boost from time to time. With Credit Genie, get a cash advance up to $100 with no interest, and no credit check & no mandatory repayment timeframe. Just repay us back when you can afford it.\r\n\r\nOVERDRAFT ALERTS: Get alerts when your account is at risk of being over-drafted, so you can avoid expensive spending like overdraft fees.\r\n\r\nTRACK YOUR SPENDING: Use the Credit Genie app to understand how you spend your money, so you can take control of your budget and finances.\r\n\r\nManage Your Budget and Expense: Manage your spending, bills, and expenses; we've partnered with the nation's largest and most trusted providers to help manage your bills and expenses.\r\n\r\nGet Real Support from Real People\r\nHave a question about your advance? Have trouble using the app? We are here and we care! Email us at support@creditgenie.zendesk.com to speak with our customer care team. We are open Monday through Friday between 9:00 AM and 5:00 PM EST.\r\n\r\nCredit Genie Cash Advances are not available to Connecticut, Nevada & Missouri residents.\r\n\r\n\u2020Credit Genie Cash Advance is not a payday loan, personal loan, or a loan of any kind.\r\n- There is no mandatory minimum or maximum payback period for your Cash Advance.\r\n- There is no mandatory repayment time frames or interest rates or obligation to repay, customers can set a repayment date that works for them by contacting us at support@creditgenie.com. Customers typically choose to repay their cash boost between 3 days and 90 days. \r\n- It is not mandatory to pay back the full amount of your Cash Boost in less than 60 days. Customers can take as much time as they require to pay back the Cash Boost and can even pay it back in multiple smaller amounts.\r\n- Zero APR, no APR, no interest rate, zero interest.\r\n- Example Scenario: If you instantly transfer a $100 Cash Boost to your connected bank account for an optional $5.99 express delivery fee and add an optional $2 tip, then your total will be $107.99.\r\n\r\nhttps://creditgenie.com/privacy-policy\r\nhttps://creditgenie.com/terms-and-conditions",
    "descriptionHTML": "Improve your financial health with breakthrough financial tools and services from Credit Genie, and find better ways to budget your spending.<br><br>GET A CASH BOOST UP TO $100\u2020: We all can use a little boost from time to time. With Credit Genie, get a cash advance up to $100 with no interest, and no credit check &amp; no mandatory repayment timeframe. Just repay us back when you can afford it.<br><br>OVERDRAFT ALERTS: Get alerts when your account is at risk of being over-drafted, so you can avoid expensive spending like overdraft fees.<br><br>TRACK YOUR SPENDING: Use the Credit Genie app to understand how you spend your money, so you can take control of your budget and finances.<br><br>Manage Your Budget and Expense: Manage your spending, bills, and expenses; we&#39;ve partnered with the nation&#39;s largest and most trusted providers to help manage your bills and expenses.<br><br>Get Real Support from Real People<br>Have a question about your advance? Have trouble using the app? We are here and we care! Email us at support@creditgenie.zendesk.com to speak with our customer care team. We are open Monday through Friday between 9:00 AM and 5:00 PM EST.<br><br>Credit Genie Cash Advances are not available to Connecticut, Nevada &amp; Missouri residents.<br><br>\u2020Credit Genie Cash Advance is not a payday loan, personal loan, or a loan of any kind.<br>- There is no mandatory minimum or maximum payback period for your Cash Advance.<br>- There is no mandatory repayment time frames or interest rates or obligation to repay, customers can set a repayment date that works for them by contacting us at support@creditgenie.com. Customers typically choose to repay their cash boost between 3 days and 90 days. <br>- It is not mandatory to pay back the full amount of your Cash Boost in less than 60 days. Customers can take as much time as they require to pay back the Cash Boost and can even pay it back in multiple smaller amounts.<br>- Zero APR, no APR, no interest rate, zero interest.<br>- Example Scenario: If you instantly transfer a $100 Cash Boost to your connected bank account for an optional $5.99 express delivery fee and add an optional $2 tip, then your total will be $107.99.<br><br>https://creditgenie.com/privacy-policy<br>https://creditgenie.com/terms-and-conditions",
    "summary": "Same-day Cash Advance. Budgeting & Expense Manager.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1134373,
    "score": 4.513365,
    "ratings": 25341,
    "reviews": 3399,
    "histogram": [
        1842,
        308,
        796,
        2439,
        19951
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Creditly Corp",
    "developerId": "Creditly+Corp",
    "developerEmail": "support@creditgenie.zendesk.com",
    "developerWebsite": "https://creditgenie.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.creditgenie.com/privacy-policy",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Oq6CUs3oll_g7YzPwiNfL9R7A_qYYawWLrJUVd6t-byL3qyIn5cQr79YNMbWVAxXGHQ",
    "headerImage": "https://play-lh.googleusercontent.com/h5ZHOQAEqz4F-HxVkLZIXsG5BsQ1slucQmL05xsyyaaHlpBxMPEOeHI5e5rX_tSQ1x8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Gpguywy0RRfxnFPcjHUnTc_eWzKYfWOua15TeKHZWRLFYhTQLG5HwUXXBbDLbiK6PQ",
        "https://play-lh.googleusercontent.com/dIRI8p0J6N_NPqLPkQOP_O7_b0j4z_UKN4gnLyR0kMkZK6mYmCLltjt5lUIaLTCZtFl1",
        "https://play-lh.googleusercontent.com/sXCzXfw_ZkqYtJJSv4yVFelZgl0ag3t9RwBgUwSWvGrZxI7Bi_MEWAhKKIUrNteYzBY",
        "https://play-lh.googleusercontent.com/mPwi1eKMuqTpmAKQ8DUO0gC_fUXvrdq0SDaWVXfs-XczR4TbfTBokiV-U5d4T3utqw",
        "https://play-lh.googleusercontent.com/1GKBMvMfK2bzGvYBmYZuN6UUnYMrec5CMJ7E2nDUNp4EgInGUIA-zOSPjEmS45i7JKc",
        "https://play-lh.googleusercontent.com/N69C2HDqoRnKqA5s-007EPv6-pKZ_mYl0TZNp66PbUCH6OCmcd63p_R7ygkvNFTV1A",
        "https://play-lh.googleusercontent.com/6OH4QlbCrEU6_8XcFL_JuEJuk6NIxLj0dku2Cee2o3KGPTi0Tr-G6dlaxDAAX9YKIHU",
        "https://play-lh.googleusercontent.com/5aZbmZOGbl0svUpRtWdlJXA2vQHlk_kqPzbCZg_iYarT8iWof8QmT6bRj-3C7K5u9Mhq",
        "https://play-lh.googleusercontent.com/0RnZS_MlFFww16hCG2D_5xM31BRj-FR5D75ackPRL6G27-_c1NkKVdvYkVbR84LIcTo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 18, 2021",
    "lastUpdatedOn": "Jul 1, 2024",
    "updated": 1719893352,
    "version": "2.3.3",
    "comments": [],
    "appId": "com.creditgenie.app",
    "url": "https://play.google.com/store/apps/details?id=com.creditgenie.app&hl=en&gl=us"
}