{
    "title": "Pocket: Save. Read. Grow.",
    "description": "THE PLACE TO ABSORB GREAT CONTENT.\r\nUse Pocket to capture the content that comes at you all day long, and curate your own space filled with only the topics you care about. Save the latest stories, articles, news, sports and videos from any device, and any publisher or app. Then fuel your mind with a reading, watching, and listening experience designed for calm eyes, free hands, and fresh focus.\r\n\r\nSAVE FROM ANYWHERE.\r\nSave the latest news, magazine articles, stories, videos, recipes, web pages, how-to information \u2013 anything you discover online or subscribe to, from any publisher. User favorites include: New York Times, The Guardian, Washington Post, Flipboard, The Atlantic, New Yorker, Lifehacker, Business Insider, The Verge, BBC News, Google News, Buzzfeed, Vox, engadget, Medium, Newsweek, Twitter, Youtube. \r\n\r\nREST YOUR EYES. FIND YOUR FOCUS.\r\nPocket\u2019s clean layout and customizable display make for a relaxing reading experience that clears out the visual clutter, gives your eyes a rest, and lets your mind focus on the information at hand. Love long reads? Pocket\u2019s typography and layout keep reading comfortable for longer stretches. Love to read before bed? Try our new dark and sepia themes to reduce visual stimulation before you sleep.\r\n\r\nLISTEN TO ARTICLES.\r\nPocket\u2019s listen feature turns any news story, article, or blog post into a hands-free, eyes-free learning experience. Now you can turn content into knowledge while you cook, commute, work out, walk, or just relax and listen. \r\n\r\nREAD EVERYWHERE.\r\nIf it\u2019s in your Pocket, it\u2019s on your phone, tablet and computer \u2013 even when you\u2019re offline. Whether you\u2019re taking a news break, reading from bed, or breezing through articles on your commute, Pocket makes the most of your time by getting you straight to the news feeds, magazine articles, stories, information, news, and sports that are compelling to you. And estimated reading times help you turn any time into quality time.\r\n\r\nDISCOVER MORE OF WHAT YOU LOVE.\r\nFind more of what you love but might otherwise have missed. Pocket surfaces \u2018best of web\u2019 content discovered by our users, verified by our curators, and approved by our editors. Find all kinds of topics from all kinds of publishers, including quality magazines and news sources like Fast Company, The Verge, Medium, Quartz, Harvard Business Review and more.\r\n\r\nMAKE IT PREMIUM. AND PERMANENT.\r\nPower users can upgrade anytime to Pocket Premium for features like advanced search, unlimited highlights and automatic article backups.\r\n\r\nYou can also save to Pocket with our browser extensions for Chrome, Firefox, or Safari\r\nLearn more at https://getpocket.com/.",
    "descriptionHTML": "THE PLACE TO ABSORB GREAT CONTENT.<br>Use Pocket to capture the content that comes at you all day long, and curate your own space filled with only the topics you care about. Save the latest stories, articles, news, sports and videos from any device, and any publisher or app. Then fuel your mind with a reading, watching, and listening experience designed for calm eyes, free hands, and fresh focus.<br><br>SAVE FROM ANYWHERE.<br>Save the latest news, magazine articles, stories, videos, recipes, web pages, how-to information \u2013 anything you discover online or subscribe to, from any publisher. User favorites include: New York Times, The Guardian, Washington Post, Flipboard, The Atlantic, New Yorker, Lifehacker, Business Insider, The Verge, BBC News, Google News, Buzzfeed, Vox, engadget, Medium, Newsweek, Twitter, Youtube. <br><br>REST YOUR EYES. FIND YOUR FOCUS.<br>Pocket\u2019s clean layout and customizable display make for a relaxing reading experience that clears out the visual clutter, gives your eyes a rest, and lets your mind focus on the information at hand. Love long reads? Pocket\u2019s typography and layout keep reading comfortable for longer stretches. Love to read before bed? Try our new dark and sepia themes to reduce visual stimulation before you sleep.<br><br>LISTEN TO ARTICLES.<br>Pocket\u2019s listen feature turns any news story, article, or blog post into a hands-free, eyes-free learning experience. Now you can turn content into knowledge while you cook, commute, work out, walk, or just relax and listen. <br><br>READ EVERYWHERE.<br>If it\u2019s in your Pocket, it\u2019s on your phone, tablet and computer \u2013 even when you\u2019re offline. Whether you\u2019re taking a news break, reading from bed, or breezing through articles on your commute, Pocket makes the most of your time by getting you straight to the news feeds, magazine articles, stories, information, news, and sports that are compelling to you. And estimated reading times help you turn any time into quality time.<br><br>DISCOVER MORE OF WHAT YOU LOVE.<br>Find more of what you love but might otherwise have missed. Pocket surfaces \u2018best of web\u2019 content discovered by our users, verified by our curators, and approved by our editors. Find all kinds of topics from all kinds of publishers, including quality magazines and news sources like Fast Company, The Verge, Medium, Quartz, Harvard Business Review and more.<br><br>MAKE IT PREMIUM. AND PERMANENT.<br>Power users can upgrade anytime to Pocket Premium for features like advanced search, unlimited highlights and automatic article backups.<br><br>You can also save to Pocket with our browser extensions for Chrome, Firefox, or Safari<br>Learn more at https://getpocket.com/.",
    "summary": "Save, read & listen to your favorite news, stories & videos from across the web.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 18222093,
    "score": 4.1881,
    "ratings": 308718,
    "reviews": 23489,
    "histogram": [
        39549,
        9478,
        14810,
        34367,
        210500
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $44.99 per item",
    "developer": "Mozilla Corporation",
    "developerId": "5995605107085635372",
    "developerEmail": "support@getpocket.com",
    "developerWebsite": "http://help.getpocket.com",
    "developerAddress": "Mozilla Corporation\nATTN: Pocket Business Unit\n2 Harrison Street, Suite 175\nSan Francisco, CA 94105",
    "privacyPolicy": "http://getpocket.com/privacy",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/6kJhEyx-77gDf4e1xwgrODJCOhMq2E0XA-jApu7McdYJjJ_M8lRti0lrn5InAIebP0g",
    "headerImage": "https://play-lh.googleusercontent.com/ZAXioLvrGwQkQyYX4b7KnHfNcc0f7BAjb3IEbOvlB6mdHKRVboN0_y9v-x5xDEQwZWdf",
    "screenshots": [
        "https://play-lh.googleusercontent.com/e-WVNApgIWTqQn3bGo1k9B2V9gJCq_WjbX2FJuTUDvz18nvVW30o7r5dk1Wpn5ibuN0",
        "https://play-lh.googleusercontent.com/Ma4BYP9wrEfZkn9x-swCjw1ej6NocIbW78WSz-LCMf-j4_t4x7nKFFQvTdScS4dzqKEA",
        "https://play-lh.googleusercontent.com/4UEyWGKRzSUnA9yW3dA3k-8glMRqppixcLcSIbCMlcktfJrr_7KKouXI5lJoei1ppqg",
        "https://play-lh.googleusercontent.com/lQPLHnxPAApCl8i8AERFL-syNefspxNpohX28JCjzJ6lG4R2Y5PDAaBjIAxuz3STDqys",
        "https://play-lh.googleusercontent.com/lPX1eodN1neAzs-VKiM2dBHuiSkI8AbTt7yn46DhLGZrUaQGmMLuW9QO0HgCzdztFw",
        "https://play-lh.googleusercontent.com/sW65sYAIlOt9oTBI4mJ0f75kwGvkcNly8AOwu_3c9pw-Mgj1meAjm7d-iNXPOmBgkzKy",
        "https://play-lh.googleusercontent.com/shBH2sa997jAL27dGKUhxqBRgHmsyYRapj8O6q-QWMi--0MPSAPZZRNWnt3txbRfqyA",
        "https://play-lh.googleusercontent.com/6ZhCBzGQlJyI0fInuqKx1CaFeTvmGJ9EmjTCpcWJwb90KjVxCbdwS2C2clDX_nRXH_M",
        "https://play-lh.googleusercontent.com/Xq0GY8OwWL7LExVKULYQjZbdPN1kArhogspvAIGmgK9QT4Qs2-ZH0z7tgLiqmo-ymA",
        "https://play-lh.googleusercontent.com/ThsVQIeI1X_zzC_eUgecCqNkmdDYhqUQ8aBoF3lX-9GN9eA2n3J5ygSpqyhBoUxmxN4",
        "https://play-lh.googleusercontent.com/33xNAlLFaRBml7GqRxPG6aoQGN_XQNqawdQyBjLhtaoIuX9Npnu8ziD8eMVV8s6I",
        "https://play-lh.googleusercontent.com/VjL3DMbQZPCy7aUxhx0dZPHAyrqoFpfg5cHp7Y_B1w55iuhU5i2SQsGNwCPK80NRjA",
        "https://play-lh.googleusercontent.com/34qB_iY0gB-GbBn652hRwcfk0zmDj1ybzx_fDcnNiEOHyW3sY7S2AuIa2jQIAQSCn7DH",
        "https://play-lh.googleusercontent.com/xo4BSpTJHcmOOp--iXl_ZgEjKm2QtkrnemeFILuciUcJzCUObtMnuKyRbPXYrClRkw",
        "https://play-lh.googleusercontent.com/VpNfZWmJPpZGobbtLyLsb4pKmbshsLePIqeNEs3zQzUnEzXbV7_nofLV8i6I-6sw1g",
        "https://play-lh.googleusercontent.com/iA3Q3I9EJoXSZJUJJaozoBduiwjyG03poo9bJCPsXfMCmmXE4KW2dzMGUKdmvPZ5EeU",
        "https://play-lh.googleusercontent.com/xzXbVvLI7YvrMUnHGu056DC4WSzsguQqExbVWtP99z6cYxdcqHi5jdcJWWSKCAU0ZME",
        "https://play-lh.googleusercontent.com/Oo59-lf-g8d5OzKvJozeB5F8JRbWrSa3KiZAhV_BRmv4k57Gnayrv32Bxtcrh9gyz6s"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 9, 2011",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1728980092,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.ideashower.readitlater.pro",
    "url": "https://play.google.com/store/apps/details?id=com.ideashower.readitlater.pro&hl=en&gl=us"
}