{
    "title": "Jack's",
    "description": "It\u2019s more app-etizing than ever! Turn your Southern food cravings into delicious rewards when you earn points with every order on the Jack\u2019s app.\r\n\r\nWhat\u2019s for dinner? Find a Jack\u2019s near you and order all your faves for pickup or delivery right in the app. Plus, get exclusive access to online-only deals and tons of limited-time offers \u2013 like double point days and BOGO deals \u2013 right at your fingertips.\r\n\r\nA few rewards that\u2019ll have ya askin\u2019 for seconds:\r\n\r\n\u2022 Signup reward \u2013 Grab some free Big Jack just for signing up.\r\n\u2022 Birthday reward \u2013 You say it\u2019s your birthday? Well, that calls for a free shake.\r\n\u2022 Anniversary reward \u2013 Let Jack\u2019s buy you a drink on your app anniversary.\r\n\u2022 Spread the Love reward \u2013 Call your friends and fam and tell \u2019em about the app for a free reward.\r\n\r\nThe new and improved Jack\u2019s app is all you need to put a down-home Southern meal on the table tonight. Download today and start getting fresh deals and hot rewards!",
    "descriptionHTML": "It\u2019s more app-etizing than ever! Turn your Southern food cravings into delicious rewards when you earn points with every order on the Jack\u2019s app.<br><br>What\u2019s for dinner? Find a Jack\u2019s near you and order all your faves for pickup or delivery right in the app. Plus, get exclusive access to online-only deals and tons of limited-time offers \u2013 like double point days and BOGO deals \u2013 right at your fingertips.<br><br>A few rewards that\u2019ll have ya askin\u2019 for seconds:<br><br>\u2022 Signup reward \u2013 Grab some free Big Jack just for signing up.<br>\u2022 Birthday reward \u2013 You say it\u2019s your birthday? Well, that calls for a free shake.<br>\u2022 Anniversary reward \u2013 Let Jack\u2019s buy you a drink on your app anniversary.<br>\u2022 Spread the Love reward \u2013 Call your friends and fam and tell \u2019em about the app for a free reward.<br><br>The new and improved Jack\u2019s app is all you need to put a down-home Southern meal on the table tonight. Download today and start getting fresh deals and hot rewards!",
    "summary": "Join the Jack\u2019s family and download the app that loves ya back.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 249450,
    "score": 3.8923078,
    "ratings": 2576,
    "reviews": 1049,
    "histogram": [
        494,
        138,
        138,
        178,
        1624
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Jack's Family Restaurants",
    "developerId": "Jack's+Family+Restaurants",
    "developerEmail": "marketing@eatatjacks.com",
    "developerWebsite": "https://www.eatatjacks.com/",
    "developerAddress": "124 W. Oxmoor Road\nBirmingham, AL 35209",
    "privacyPolicy": "https://www.eatatjacks.com/privacy-policy",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/uvRojV8wKEY88O6tWaSSuN9D7tgeMQbg8ORYXduVbLUrM6I7qEw6IE3j5xAglZPjEXw",
    "headerImage": "https://play-lh.googleusercontent.com/HD5srvTEd0jyoCeCZvMG1eS8QywGVLLAzkd96sXMgwYjKO9gapKzUh9dBN9G4hUitg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/R9E_TCOq07Inwai70lRKNnHKgGdy22otm7iFb5NrQdqNi23kle3bl4CLLSgdaXyZPYc",
        "https://play-lh.googleusercontent.com/sHqTh6I9nrA9Z3M5jTfs1W-Q9QzKp-EktVnj6OiCLALnAQ2tYG3AVZ6oN6trC31uii6J",
        "https://play-lh.googleusercontent.com/ni2rMg1hd53oD3jLtJ5QY_Hzves36QcUnaL0f9u8kuE6bJAD6CSWMbzVS0s33-CFskU",
        "https://play-lh.googleusercontent.com/GpGPNmjKXps_oBKAlDPEJY8xXd8R08VfJ8dg7siX7H5u7pUaECiH-PPEe1_igT5Fnfcn",
        "https://play-lh.googleusercontent.com/9Q45EaA1d6HJ4Q6bAw9LX6wqbQQ2R-uDdfW9aQo30otmGLe-DKIGZ5JExTgCqNYiRA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 27, 2020",
    "lastUpdatedOn": "Aug 21, 2024",
    "updated": 1724256070,
    "version": "2.2",
    "comments": [],
    "appId": "com.jacks.app",
    "url": "https://play.google.com/store/apps/details?id=com.jacks.app&hl=en&gl=us"
}