{
    "title": "20 Minutes Till Dawn",
    "description": "Upgrade, Build and Survive! Defend hordes of vampires now!\r\n\r\n20 Minutes Till Dawn is a roguelike, shoot'em up game where you mow down endless hordes of lovecraftian monsters and survive the night!\r\n\r\n\u3010Unique Builds Every Run\u3011\r\nIn this roguelite survival game, select from a variety of upgrades to create a unique and overpowered builds every run. You can be a fire wizard, for example, and ignite monsters with every pump of your shotgun, or an agile ninja who controls magic knives to pierce your vampire enemies.\r\n\r\n\u3010Select Your Hero\u3011\r\nChoose from a diverse selection of characters and weapons that offer a variety of gameplay experiences during your survival adventure!\r\n\r\n\u3010Features\u3011\r\n*Over 80 different upgrades to choose from for a unique experience every run!\r\n*Wide cast of characters, weapons, runes, maps and vampire monsters.\r\n*Casual quick 10-20 minutes play sessions, for busy gamers.\r\n*Rune System helps you become stronger\r\n\r\n\u3010Contact Us\u3011\r\nDiscord: https://discord.gg/efTYchSsHZ\r\nFacebook: https://www.facebook.com/Erabitstudios\r\nTwitter: https://twitter.com/erabit_studios\r\nEmail\uff1a20minutestilldawn@erabitstudios.com",
    "descriptionHTML": "Upgrade, Build and Survive! Defend hordes of vampires now!<br><br>20 Minutes Till Dawn is a roguelike, shoot&#39;em up game where you mow down endless hordes of lovecraftian monsters and survive the night!<br><br>\u3010Unique Builds Every Run\u3011<br>In this roguelite survival game, select from a variety of upgrades to create a unique and overpowered builds every run. You can be a fire wizard, for example, and ignite monsters with every pump of your shotgun, or an agile ninja who controls magic knives to pierce your vampire enemies.<br><br>\u3010Select Your Hero\u3011<br>Choose from a diverse selection of characters and weapons that offer a variety of gameplay experiences during your survival adventure!<br><br>\u3010Features\u3011<br>*Over 80 different upgrades to choose from for a unique experience every run!<br>*Wide cast of characters, weapons, runes, maps and vampire monsters.<br>*Casual quick 10-20 minutes play sessions, for busy gamers.<br>*Rune System helps you become stronger<br><br>\u3010Contact Us\u3011<br>Discord: https://discord.gg/efTYchSsHZ<br>Facebook: https://www.facebook.com/Erabitstudios<br>Twitter: https://twitter.com/erabit_studios<br>Email\uff1a20minutestilldawn@erabitstudios.com",
    "summary": "Dive into intense Roguelike challenges, survive, and reach Bullet Heaven!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3728417,
    "score": 4.630342,
    "ratings": 128335,
    "reviews": 3598,
    "histogram": [
        4655,
        2098,
        5205,
        12060,
        104286
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $149.99 per item",
    "developer": "Erabit Studios",
    "developerId": "6054052760752083656",
    "developerEmail": "support@erabitstudios.com",
    "developerWebsite": "https://www.erabitstudios.com/",
    "developerAddress": "18 Howard Road, #06-01 Novelty Bizcentre, Singapore (369585)",
    "privacyPolicy": "https://erabitstudios.com/privacy_policy.html",
    "genre": "Role Playing",
    "genreId": "GAME_ROLE_PLAYING",
    "categories": [
        {
            "name": "Role Playing",
            "id": "GAME_ROLE_PLAYING"
        },
        {
            "name": "Roguelike",
            "id": null
        },
        {
            "name": "Single player",
            "id": null
        },
        {
            "name": "Stylized",
            "id": null
        },
        {
            "name": "Vampire",
            "id": null
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/gfVdMSENjgNh1QZ2RBB8MQKhNwcVxokAu2n1Ns_7TTgaLeiW926o568Q6yLoNbHHow",
    "headerImage": "https://play-lh.googleusercontent.com/kVvptQTtktkw8TNqJ_GR66R5y-QvQJHGQfVqPBT7bGXtzWRXGrrkO_Bcgq9PrJLVsw8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/xafiifsgPk9-TZVP5JE4u9K_ASOvyyumrqhzeXQe-xj_BjjPHmwBeMaTN380uTkUn4w",
        "https://play-lh.googleusercontent.com/H511H-PZFU01N7-dYSAeKKGfQqrPvJHNnsdBPELJr7MpZzuE-9gg1Be7cGz8GjXhDw",
        "https://play-lh.googleusercontent.com/M0JFuX-q7-me9_DYcUTu3MotZTGUwz0Ooe40bx097taQS2ub75NeLbbaXWGk2oBpOg",
        "https://play-lh.googleusercontent.com/v-BSyY9vIfD_xnsqAr1fAyzhFrtprfnJSxde8EDG8dqFRVMMDKcyy1Pvy2DDpLaIuac",
        "https://play-lh.googleusercontent.com/dCDfshl8hyWwBu9baaNfR7rwgyh9goBHNDH6-eiIc87CZZ8Uq6UYxCf54Lm4y-0UCj3d",
        "https://play-lh.googleusercontent.com/F2WPNwj0HcctZMbXzqTCpAgOy8KmKNUnC_Q04CJqvkWMjpDajawZJ51FFfgw8cfTb_Sm",
        "https://play-lh.googleusercontent.com/f62787vj3syNCWs0A4_QekOyt0Jy-FSXsGQ8J3X5gQ_k91Jx50yLCWvc-2JMxMHNf58",
        "https://play-lh.googleusercontent.com/BGt6XBKs64ZPuperBunTlyNm6ZZkX7NpiJjwtSZunmmKzVdBf6L460wncxCCIEkJhA",
        "https://play-lh.googleusercontent.com/JNxaKEEItuz_L5z8t0jjTlRdSUnZZACn9CkgU3EX0Eu09UXoFYR-W8K_jaaFcTPGE7g",
        "https://play-lh.googleusercontent.com/-rhar8phtpO5VU8LPnOFHGsaDZyFclVTfk1gMXtlvG8IV1KdGsuoE51scHh6O9-SzQM6",
        "https://play-lh.googleusercontent.com/ZFStvXtIKXCQ6obBiO089DQXjlp9LZBlw5-Zm2EPma_qRYULW-JMCNukg_Www5hmKpAz",
        "https://play-lh.googleusercontent.com/JG0qv7hziS2kxuNJiv5FK4wobz--sAT3LYwGBjxQWRweaukEQww11kOFN9RV8htMyHw",
        "https://play-lh.googleusercontent.com/rmtippuQz7LVb0tyeOQzNSWs4fwU9F78nYWcnY9tJY1zdqLjwYIQhY7xYB6_5vullBA",
        "https://play-lh.googleusercontent.com/pbS9P2rr8dwwoDYxeHqU3RfmnrMxHn3ErfEomrr-wEZu9NMt8semrJ5FTHFtkMXVvZU",
        "https://play-lh.googleusercontent.com/fUxD148JNgEI92UBf-tBXnDhiZ-wzvmJ96mamIFqIQAv3NpSCTfC4mYFWjPUEzPjMmU",
        "https://play-lh.googleusercontent.com/SRt0AxM_Kx487VtyHqcCBZV-BCOj_K13xBUL3EkMZEnbSpUP3ZkmM-GdHAfKZhv0gPo",
        "https://play-lh.googleusercontent.com/mul6aYuY8DRQg5OgjGXgmVMvfjAS_ybM7r3r-Xvgcs_a3v4h0QbotlfgvQOHDWlLNw",
        "https://play-lh.googleusercontent.com/YpxVAnW4EmdQmGGZiqE4faK8mgL40nGCuMvmivuadMjrU5oZn_EnW527otvFnRxUrA",
        "https://play-lh.googleusercontent.com/JWc33L-OjLK-bgo1fyvVeuh5nkqserkL_fCfwHb5jZoinxHUBZ3P6nnblKFRGEmTsU4",
        "https://play-lh.googleusercontent.com/PSt9mAs4hEczo8111-A56sSoubHf2Tlv3dQfLbblNku3ojj-3tXYiQWbmU3SLbr_Pw",
        "https://play-lh.googleusercontent.com/4P-ANzHKKGuYpdYn0oZD38aBwX6JxPMkXH6J2OSH6AAc4iby7NLlCv65icR2n4ojGQ",
        "https://play-lh.googleusercontent.com/C6GP7k_X7wjvCJMD9S_FJCn8UgKYrE6HuYNBg4Dtm9bll8W3Gm3OgToced5reKhJnv0",
        "https://play-lh.googleusercontent.com/zFpVjdvT75OXj52XtngRemjhENa9tMhPTmxBubznt2LU1AeaqzJZxBSqiaOChKc7Yn0i",
        "https://play-lh.googleusercontent.com/BHHwBbL9Evg4v8L3zv4skNReklTHr29xyt2MK75JvRVVTRUCZM8ZjwobF5FAo1WUvpQ",
        "https://play-lh.googleusercontent.com/80uk0IQDEcMoj9Dtk11j9_9HgsOJ_57PmQigyX_3lfLktpxISy5h3oemplqdfODJ7xM",
        "https://play-lh.googleusercontent.com/G4iP8tTBa7Rx-AZUcVoIfuOzZnuqSwR5Rtz1QhiJHlIGr2O8udM91AtFzUIRPZWUr79F",
        "https://play-lh.googleusercontent.com/SMvthHIP-YmoRADOCKTuK2Ab4leoJR64BEIzjq54JNQFqHhMHzp4YD4fwSUkI4ERi8w",
        "https://play-lh.googleusercontent.com/AZCkaWipCndkD5muKhSmELov8LwezD2yAOlowFayAMFCczMHsCmArbMTv3yttj17GEU",
        "https://play-lh.googleusercontent.com/biAf5j3CKfoFrEzcyyvbMn7H1YLFJnLWEMZQbSfJZedU0f2a3_dFQ9TaRKFJBFFW-kSd",
        "https://play-lh.googleusercontent.com/chSvJbNI47f_YFAFw6GDmWTp6_wnLsXWXsC2fco7OfUajmu6nHt7VFus7eK7NRvLW5w",
        "https://play-lh.googleusercontent.com/ZDLh-aYMt4uFJTNwFZkQLPiMVPft1kwzvosPDCjPysbJY1MMUeD5cOEOu62v2IVYsok"
    ],
    "video": "https://www.youtube.com/embed/SeangAC4iYk?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/kVvptQTtktkw8TNqJ_GR66R5y-QvQJHGQfVqPBT7bGXtzWRXGrrkO_Bcgq9PrJLVsw8",
    "contentRating": "Everyone 10+",
    "contentRatingDescription": "Fantasy Violence, Mild Blood",
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 6, 2022",
    "lastUpdatedOn": "Sep 18, 2024",
    "updated": 1726725993,
    "version": "5.0",
    "comments": [],
    "appId": "com.Flanne.MinutesTillDawn.roguelike.shooting.fr.gp",
    "url": "https://play.google.com/store/apps/details?id=com.Flanne.MinutesTillDawn.roguelike.shooting.fr.gp&hl=en&gl=us"
}