{
    "title": "Retro 8Bit Pixel Castle - F03",
    "description": "Introducing the Retro 8Bit Pixel Castle Watch Face for Wear OS \ud83c\udff0\ud83c\udfae\r\n\r\nGet ready to journey back in time with the Retro 8Bit Pixel Castle Watch Face, bringing that classic video game nostalgia right to your wrist. Here's how to get started:\r\n\r\nQuick Setup Guide: Experience a blast from the past with these simple steps: Watch Setup Video \ud83c\udfac.\r\n\r\nDive into the pixelated adventure with our energy-efficient Always On Display, perfect for keeping the retro charm alive without draining your battery. Please consider that continuous use may affect battery life. \ud83d\udd0b\r\n\r\nFor Manual Installation: If the magic doesn't happen automatically, cast these spells:\r\n\r\nConnect your smartwatch to Wi-Fi. \ud83d\udcf6\r\nOpen the Play Store on your watch. \ud83c\udfae\r\nSelect \"Apps on your phone\" (if available). \ud83d\udcf1\r\nHit \"Install\" by your watch in the list to transfer the watch face. \ud83d\udd79\ufe0f\r\nIf a glitch occurs, give it up to an hour for the \"Install\" option to appear again. \u231b",
    "descriptionHTML": "Introducing the Retro 8Bit Pixel Castle Watch Face for Wear OS \ud83c\udff0\ud83c\udfae<br><br>Get ready to journey back in time with the Retro 8Bit Pixel Castle Watch Face, bringing that classic video game nostalgia right to your wrist. Here&#39;s how to get started:<br><br>Quick Setup Guide: Experience a blast from the past with these simple steps: Watch Setup Video \ud83c\udfac.<br><br>Dive into the pixelated adventure with our energy-efficient Always On Display, perfect for keeping the retro charm alive without draining your battery. Please consider that continuous use may affect battery life. \ud83d\udd0b<br><br>For Manual Installation: If the magic doesn&#39;t happen automatically, cast these spells:<br><br>Connect your smartwatch to Wi-Fi. \ud83d\udcf6<br>Open the Play Store on your watch. \ud83c\udfae<br>Select &quot;Apps on your phone&quot; (if available). \ud83d\udcf1<br>Hit &quot;Install&quot; by your watch in the list to transfer the watch face. \ud83d\udd79\ufe0f<br>If a glitch occurs, give it up to an hour for the &quot;Install&quot; option to appear again. \u231b",
    "summary": "Retro Castle Face: Pixel Art Nostalgia for Wear OS",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 16434,
    "score": 4.714286,
    "ratings": 43,
    "reviews": 1,
    "histogram": [
        0,
        0,
        0,
        12,
        30
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Artistry Time Studios",
    "developerId": "4887226526184134400",
    "developerEmail": "artistrytimestudios@gmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://docs.google.com/document/u/3/d/e/2PACX-1vTkCBcJiyqch4cMESJblgeD70jRjNcDRXGgkWROzOr0JfxhzOaZpKz7B67K6dQJADqG6CcqGGGoGezx/pub",
    "genre": "Personalization",
    "genreId": "PERSONALIZATION",
    "categories": [
        {
            "name": "Personalization",
            "id": "PERSONALIZATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/IksCUy1jxarQJenrpJ0GzlL_7kuSqCUP_n-crcz0_CbnMs516EtLtx39cVmSjX477Q",
    "headerImage": "https://play-lh.googleusercontent.com/N-aIzpuI_DH1nHoZcK9gZLeypEG3DR-ZKkLbBxtG4SibHgcWCkj4z0426fzPwnHxXLs",
    "screenshots": [
        "https://play-lh.googleusercontent.com/JBPxlB7fkZ33Q2fp_Cadif66MND-jmtswFofYmESis0WywhrPdBDAXAojuH51nrrs_k",
        "https://play-lh.googleusercontent.com/d48idwMcw0_rLOflNN1m5BziesBl8Zx7m3TmCQrT4FbKRnDhWTSxAdjXNU1VpO2ts3o",
        "https://play-lh.googleusercontent.com/B9cdjiwfx2VTekRVuLUtgTN7AAjpmB8WC4ocnzfX7wNHH5wvN6_ZNN3B6ubYOUPW7w4",
        "https://play-lh.googleusercontent.com/P-sIJOp1g2W7f_2lhi1bgDWD20qisDIE-t0DG0FomLZT3PfE58wxgciD-qaemzhJ2w",
        "https://play-lh.googleusercontent.com/eNxKTqDJACHkvGQBEX1sRqWP35Q5tP4iWGT8iyKY3UhOXJCoCNxg8JhE69YZLYREN34",
        "https://play-lh.googleusercontent.com/yekr3VzCxjVLomqyLto2PBOkmrayMhw-NLboPljUyt6De3GL20Ql3xdGIMT0Xhwv8pw",
        "https://play-lh.googleusercontent.com/uWbx1MHQ6vQnF8XB82qSR8zcRdGp1YiIREFjQazoLVWu9m3unFLuXBGaHqwDEbqPo4M",
        "https://play-lh.googleusercontent.com/Gym90C3Ns59H0qygg-3-AxBRCBKSG2P2z48lyrsXJvxiJnBHl2RLLyr0-J3mBDtttw",
        "https://play-lh.googleusercontent.com/AWvv1tEpz8iloRInVc5ExO1nV-OVPEOmjKmmeOiQXPvpHugZMRb8_aXUqHD_8gwC3goR"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 7, 2023",
    "lastUpdatedOn": "Oct 20, 2024",
    "updated": 1729418508,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.artistrytimestudios.f03",
    "url": "https://play.google.com/store/apps/details?id=com.artistrytimestudios.f03&hl=en&gl=us"
}