{
    "title": "Graphionica: insta story maker",
    "description": "Graphionica is a stylish free photo editor, where you can create awesome beautiful Instagram stories and make designs for any social network. Create beautiful collages, combine several photos and videos at the same time, add drawings, stickers, and textures for backgrounds. You can add text on photo or video, add stickers on photo or video, add lettering on photo or video, add inscription on photo or video and plan social network feed. You can erase the background from any photo and save the result as your own sticker. You can erase video! Surprise your Instagram followers! Add awesome fonts to your Instagram stories! You'll also find unique editable templates for Instagram (stories).\r\n\r\n\u2714 Add free ready letterings from regularly replenished sticker packs or write your own text with one of many fonts available in the application, as some fonts support Cyrillic.\r\n\r\n\u2714 Use ready templates.\r\nStart your project in a second: just use a ready template! Templates are fully editable, like your own projects! Create project from a template, add stickers, add photos and videos, change some layers and you are ready!\r\n\r\n\u2714 Create your own templates.\r\nFind your unique style, save collages and plan social feeds. Now creating beautiful Instagram stories has become even faster! Templates can be deleted, swapped and duplicated! Create one template and reuse it many times.\r\n\r\n\u2714 Graphionica supports all popular resolutions for stories and Instagram feeds. Export your story in high resolution and without quality loss.\r\n\r\n\u2714 Add anything: drawings, calligraphy and inscriptions in png format.\r\n\r\n\u2714 Erase photos, stickers and your custom texts, work with layers: change order. Objects can be duplicated and reflected horizontally and vertically, as you create collages even faster!\r\n\r\n\u2714 Graphionica supports video. You can create collages, erase the background, and even add stickers, custom texts and inscriptions on your video!\r\n\r\n\u2714 History.\r\nWe have implemented history in the photo editor - you can undo any action: changing the position, changing the size, changing the transparency, changing the color or eraser. You can use up to 50 history states!\r\n\r\n\u2764\ufe0f Premium.\r\nSubscribe to premium and receive full unlimited access to all fonts and stickers.\r\n\r\n\ud83d\udccc To find ideas, tutorials and inspiration, subscribe to our @graphionica Instagram and also share photos with the hashtag #graphionica",
    "descriptionHTML": "Graphionica is a stylish free photo editor, where you can create awesome beautiful Instagram stories and make designs for any social network. Create beautiful collages, combine several photos and videos at the same time, add drawings, stickers, and textures for backgrounds. You can add text on photo or video, add stickers on photo or video, add lettering on photo or video, add inscription on photo or video and plan social network feed. You can erase the background from any photo and save the result as your own sticker. You can erase video! Surprise your Instagram followers! Add awesome fonts to your Instagram stories! You&#39;ll also find unique editable templates for Instagram (stories).<br><br>\u2714 Add free ready letterings from regularly replenished sticker packs or write your own text with one of many fonts available in the application, as some fonts support Cyrillic.<br><br>\u2714 Use ready templates.<br>Start your project in a second: just use a ready template! Templates are fully editable, like your own projects! Create project from a template, add stickers, add photos and videos, change some layers and you are ready!<br><br>\u2714 Create your own templates.<br>Find your unique style, save collages and plan social feeds. Now creating beautiful Instagram stories has become even faster! Templates can be deleted, swapped and duplicated! Create one template and reuse it many times.<br><br>\u2714 Graphionica supports all popular resolutions for stories and Instagram feeds. Export your story in high resolution and without quality loss.<br><br>\u2714 Add anything: drawings, calligraphy and inscriptions in png format.<br><br>\u2714 Erase photos, stickers and your custom texts, work with layers: change order. Objects can be duplicated and reflected horizontally and vertically, as you create collages even faster!<br><br>\u2714 Graphionica supports video. You can create collages, erase the background, and even add stickers, custom texts and inscriptions on your video!<br><br>\u2714 History.<br>We have implemented history in the photo editor - you can undo any action: changing the position, changing the size, changing the transparency, changing the color or eraser. You can use up to 50 history states!<br><br>\u2764\ufe0f Premium.<br>Subscribe to premium and receive full unlimited access to all fonts and stickers.<br><br>\ud83d\udccc To find ideas, tutorials and inspiration, subscribe to our @graphionica Instagram and also share photos with the hashtag #graphionica",
    "summary": "Story maker: instagram story templates. Animated templates, instagram collages.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 13275819,
    "score": 4.08,
    "ratings": 29499,
    "reviews": 166,
    "histogram": [
        4097,
        1170,
        2048,
        2926,
        19139
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.69 - $23.49 per item",
    "developer": "Aleksei Baskakov",
    "developerId": "7002833408324803901",
    "developerEmail": "graphionica@gmail.com",
    "developerWebsite": "https://graphionica.com",
    "developerAddress": "Russia, Saint-Petersburg, Bely Kuna 1/2, 197\n192242",
    "privacyPolicy": "https://graphionica-app.firebaseapp.com/privacy_policy.html",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/1b7OwombjNcQhazHtdESMsBqHfVaB0ZsiiQBbF91VX4WQT3CeoxHnd-KBrx3inxUCw",
    "headerImage": "https://play-lh.googleusercontent.com/vRoakZSFUPEbP_n4z0suAc8A6udJhzym_8QfoE8WSl9vaQhXbyC2Vf8wLxCHGuTZxUY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/k_kXcc1acKzFB31SdSn6hUh5aoywYW-BTTLLPICsCoP2GSrJcw7r8ldTzHiDSaQTTA",
        "https://play-lh.googleusercontent.com/JaiX5BWZWzq0GQO7sXjEdiUo4HoDNMDThDyykW1Z1CpLZLbHmefafe2BHIOWJ48A7Q1a",
        "https://play-lh.googleusercontent.com/16yZrEQqHZ7vMEm1a1A9VocGeNaTLpo79LbgYm-uYN3AsU2lCEjehysex9tg3GIvKeWF",
        "https://play-lh.googleusercontent.com/CZhqTvw9HA4Ai77BL1CljF7N-AZ5-70DO5dfd4eb0UnzosWpeFIF3fQyds5uYDP8qTg",
        "https://play-lh.googleusercontent.com/g17uCYQcXvuyg-3EQRXRnb4K_Xv-DMU_BLpa1LRwbIcTv66eeFuLoulJbvkefgc0tvh7",
        "https://play-lh.googleusercontent.com/SuI6iRLzHWDLR78e3Vhy64iEYl301CJv2crSU5Q1UZ2b5zvE7ibeSFPKl2t12hd3l4c",
        "https://play-lh.googleusercontent.com/Nf4DFbj0Q5otSX_o3bH27X4Z6kEXiNPxZwa2a_1SxoJK5umxcnx80ToyCogaQThXFGU",
        "https://play-lh.googleusercontent.com/IcL5REmMMlHBa4QS2S5MYfO4ySu1rXnYpDrX5B1oc5A8xrhtdCmCqmX6-KTw5rhUDU-S",
        "https://play-lh.googleusercontent.com/7RYlG6IEvnn3T7IxyTb15pCrrINyT6JlL4cZ2BQ7y5szV0HXtFn6hOwTEEYdVNUwOzQx",
        "https://play-lh.googleusercontent.com/CtewylrP-3WlVSUsbUyPqehNH2JXcG1QaBku8iufW6YO9WdWoViA6IakySpylVCSi2k",
        "https://play-lh.googleusercontent.com/nbHRmTb8pPYAszZkvX1EcBY4rHAFDf4zABEmBa5YkmCrJYWGBk9P7l5BbXcluIdLl8M",
        "https://play-lh.googleusercontent.com/EErX5eYfOwbUvj5G6bAtfalJSYX6Xa5bdl7wqapdYljvEkndjPHHrVsFziikx_X3M9k8",
        "https://play-lh.googleusercontent.com/N52MrHP9_VXRpzVDL56vDazYnJss9n4OJqSsIVCKXvDGHVTyFHuNaUStkpu2Awl0aFfq",
        "https://play-lh.googleusercontent.com/y1yvCCA2y1FvejP5LtkeK2dsd0pZgR5S7PweJgojKwVxkX7vCBw3zL2ePABX08CToWCC"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 11, 2019",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729538005,
    "version": "4.2.1",
    "comments": [],
    "appId": "com.graphionica.app",
    "url": "https://play.google.com/store/apps/details?id=com.graphionica.app&hl=en&gl=us"
}