{
    "title": "Huntington Mobile",
    "description": "With the Huntington Mobile app it is easier than ever to bank on the go, right from your phone.\r\n\r\nDownload and you\u2019ll be able to view account balances and history, deposit checks, transfer funds, pay bills, locate office branches, find ATMs, and contact a representative.  That\u2019s not all \u2013 as new features are rolled out, you\u2019ll be able to update the app so you always have the latest-and-greatest online banking tools right at your fingertips.\r\n\r\nGet started with our app today. Like the best things in life, we\u2019ve made it free! Although message and data rates from your carrier may apply.\r\n\r\nFeatures:\r\n\r\nHUNTINGTON HEADS UP (SM) - Set up alerts to get a heads up on important moments for your money, on the device you choose.\r\nHUNTINGTON QUICK BALANCE - A fast and simple way to view account balances on the login page at the touch of a button, without logging in\r\nFINGERPRINT LOGIN - Quickly and easily access your account information by verifying your fingerprint.\r\nACCOUNT INFORMATION - View up-to-date information about your Huntington accounts, including pending transactions. Search for transactions within account history.\r\nTRANSFER MONEY - Transfer money between accounts. Select the date you\u2019d like the transfer to occur and get a receipt for the transaction.\r\nPAY BILLS - Pay a person or company. You\u2019ll receive a summary that describes the amount and payment date, and get a receipt for the transaction.  You can also manage your payees by adding, editing, or deleting a payee. \r\nDEPOSIT CHECKS \u2013 Deposit checks by simply snapping a picture. It can save you time and help reduce trips to the branch or ATM.\r\nMANAGE YOUR DEBIT CARD \u2013 Activate and change your personal ATM/Debit Card PIN.\r\nUPDATE YOUR CONTACT INFO \u2013 Maintain your address, email and phone number information.\r\nMANAGE YOUR OVERDRAFT OPTIONS \u2013 Manage your overdraft options on eligible accounts to avoid overdraft fees.\r\nFIND LOCATIONS - Find ATMs and branches near your current location or by entering a street address.\r\nCONTACT US - Quick dialing for most of your customer service needs.\r\n\r\nSome features are only available to customers who have registered for Online Banking at Huntington.com.\r\nThe Huntington Mobile app is free, but message and data rates from your mobile carrier will still apply.\r\nSystem availability and response time are subject to market conditions.\r\n\r\nThe Huntington National Bank is Member FDIC.",
    "descriptionHTML": "With the Huntington Mobile app it is easier than ever to bank on the go, right from your phone.<br><br>Download and you\u2019ll be able to view account balances and history, deposit checks, transfer funds, pay bills, locate office branches, find ATMs, and contact a representative.  That\u2019s not all \u2013 as new features are rolled out, you\u2019ll be able to update the app so you always have the latest-and-greatest online banking tools right at your fingertips.<br><br>Get started with our app today. Like the best things in life, we\u2019ve made it free! Although message and data rates from your carrier may apply.<br><br>Features:<br><br>HUNTINGTON HEADS UP (SM) - Set up alerts to get a heads up on important moments for your money, on the device you choose.<br>HUNTINGTON QUICK BALANCE - A fast and simple way to view account balances on the login page at the touch of a button, without logging in<br>FINGERPRINT LOGIN - Quickly and easily access your account information by verifying your fingerprint.<br>ACCOUNT INFORMATION - View up-to-date information about your Huntington accounts, including pending transactions. Search for transactions within account history.<br>TRANSFER MONEY - Transfer money between accounts. Select the date you\u2019d like the transfer to occur and get a receipt for the transaction.<br>PAY BILLS - Pay a person or company. You\u2019ll receive a summary that describes the amount and payment date, and get a receipt for the transaction.  You can also manage your payees by adding, editing, or deleting a payee. <br>DEPOSIT CHECKS \u2013 Deposit checks by simply snapping a picture. It can save you time and help reduce trips to the branch or ATM.<br>MANAGE YOUR DEBIT CARD \u2013 Activate and change your personal ATM/Debit Card PIN.<br>UPDATE YOUR CONTACT INFO \u2013 Maintain your address, email and phone number information.<br>MANAGE YOUR OVERDRAFT OPTIONS \u2013 Manage your overdraft options on eligible accounts to avoid overdraft fees.<br>FIND LOCATIONS - Find ATMs and branches near your current location or by entering a street address.<br>CONTACT US - Quick dialing for most of your customer service needs.<br><br>Some features are only available to customers who have registered for Online Banking at Huntington.com.<br>The Huntington Mobile app is free, but message and data rates from your mobile carrier will still apply.<br>System availability and response time are subject to market conditions.<br><br>The Huntington National Bank is Member FDIC.",
    "summary": "Huntington Mobile app for Android",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3727673,
    "score": 4.812578,
    "ratings": 65060,
    "reviews": 16851,
    "histogram": [
        425,
        101,
        933,
        8314,
        55282
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Huntington National Bank",
    "developerId": "Huntington+National+Bank",
    "developerEmail": "mobile.developer@huntington.com",
    "developerWebsite": "http://www.huntington.com/mobile",
    "developerAddress": null,
    "privacyPolicy": "https://www.huntington.com/footer/HNB3800.htm",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/FF79aBu8MIex_DRRzrqWxhOiexH5AVTbwF1monIv5riJZ1V5IwyLGjvBk-oqQsQ0i8Qp",
    "headerImage": "https://play-lh.googleusercontent.com/5TXzhhML2Cg4WQeB5WYPrCSaUrso1RG2MCeUofsb4unKmXTwAIahjB7Ile9ByNWTQIE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/qZjPS8tRjByRHG4Tku7SO7qchUuUYpDTvOsiTfL9Y7KkHvGT0oMIx5KckiAtxTdBjSQj",
        "https://play-lh.googleusercontent.com/KNfOWzaWIU5u7NAel0fSYRXo_BEB3x_gazRVWA-y7w-LPnB9usdDF_MRsZPiZfdcv38",
        "https://play-lh.googleusercontent.com/N7iUuCK8ewbzYQFH5Xm0QICHBMMBYHwDY6qO62GOCZFN5AWudYCG6-qyEd4_W602LQ",
        "https://play-lh.googleusercontent.com/9z3Z8EXU64edym1cpbYwKx60hQ_-ejuxjOHCMMLOw3pfOYOUIU5IVWN2EnU5cB58ewxX",
        "https://play-lh.googleusercontent.com/yPQN-h5kDP8p18yn98pWVUXU_iIGvQuy0ZYHztUz8P9hq1TMKnshMThssHPzDcljpGk",
        "https://play-lh.googleusercontent.com/M9bmC6lB9RsTQzVchDMVptwb-s1kWH1WQOyanbmYxqjAq10wy_ENl4SjYGX6OmSXoLov",
        "https://play-lh.googleusercontent.com/EsTEGJelNY0Or2hJG4VZasJNtHUnlbtZ-kL-NDRTN0HErlHm6Ph5hp6pYyvgezHF3ijj",
        "https://play-lh.googleusercontent.com/LwCs69QRWI-FsIJvuVnbpbP6OleaqT7wp5Rw0JUBGu67z5jn6DZ2mJcR2LMlUMZ8qow"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 6, 2011",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729608420,
    "version": "6.56.156",
    "comments": [],
    "appId": "com.huntington.m",
    "url": "https://play.google.com/store/apps/details?id=com.huntington.m&hl=en&gl=us"
}