{
    "title": "Aeromexico",
    "description": "Our new app has your travel needs covered\r\nDownload and check out all the new features!\r\n\r\nBook\r\nWe\u2019ve updated our design with you in mind. Book your flights faster and easier using your Aeromexico profile.\r\n\r\nHome Screen\r\nFind everything for your next adventure: great deals for the best destinations.\r\n\r\nCheck-in\r\nFlight departing soon? Check-in and grab your digital boarding pass to skip the line.\r\n\r\nMy Trips\r\nTake control of your traveling! Review your itinerary and personalize your booking with additional services.\r\n\r\nStatus\r\nCheck flight status in real time.\r\n\r\nProfile\r\nYour Aeromexico profile keeps important information for personalizing your travel experience.\r\n\r\nNotifications\r\nTurn on notifications to receive regular promotions and updates on your flight status.",
    "descriptionHTML": "Our new app has your travel needs covered<br>Download and check out all the new features!<br><br>Book<br>We\u2019ve updated our design with you in mind. Book your flights faster and easier using your Aeromexico profile.<br><br>Home Screen<br>Find everything for your next adventure: great deals for the best destinations.<br><br>Check-in<br>Flight departing soon? Check-in and grab your digital boarding pass to skip the line.<br><br>My Trips<br>Take control of your traveling! Review your itinerary and personalize your booking with additional services.<br><br>Status<br>Check flight status in real time.<br><br>Profile<br>Your Aeromexico profile keeps important information for personalizing your travel experience.<br><br>Notifications<br>Turn on notifications to receive regular promotions and updates on your flight status.",
    "summary": "Buying tickets, Check-in with seat selection, search and track flights.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 5181663,
    "score": 3.875957,
    "ratings": 81707,
    "reviews": 1003,
    "histogram": [
        17761,
        2114,
        3247,
        7879,
        50665
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Aerov\u00edas de M\u00e9xico S.A. de C.V",
    "developerId": "Aerov%C3%ADas+de+M%C3%A9xico+S.A.+de+C.V",
    "developerEmail": "dpedraza@aeromexico.com",
    "developerWebsite": "https://www.aeromexico.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.aeromexico.com/es-mx/informacion-legal",
    "genre": "Travel & Local",
    "genreId": "TRAVEL_AND_LOCAL",
    "categories": [
        {
            "name": "Travel & Local",
            "id": "TRAVEL_AND_LOCAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/O_oPV18kAqj2B1Ld49VZT4LJWuOSUzP8hMvk-BL762DtQHh9Gb-gF4YNiIdIO4e7qzE",
    "headerImage": "https://play-lh.googleusercontent.com/FA2PxwcslIr1_habO4oWVAo_vLQnlYsscV6HkFloeDLGpM7SkXmt0XiBdC9l132mgUg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/DedqcygTWL1YlWLTaq3V5w21XhPXvagFgZoPD5auv2R7F9jMxbwXtrZRuyDHF7l1IOc",
        "https://play-lh.googleusercontent.com/7ubGRnJ3tWE7DIyTg8OYuTu_maXVG4L8QoaKTBbHGiHvVLmiT6RdVGDhYnJeo7AvEQ",
        "https://play-lh.googleusercontent.com/jJp_S2fMfM1SU9-h_jaUP1GzCtNMk7vXC4vFKvYVzhIv_Kq-wDZPC1xWwdo_aWlwZg",
        "https://play-lh.googleusercontent.com/CnWA8hYy5EPju9_R4h9qgEdYHn6AL6thKdaW6lzfGuboYRPEEhLJxIR7u9fo4Q-VE7A",
        "https://play-lh.googleusercontent.com/UAOEhCRZcQnpAixod9Jnb3rMR_WVJQ0eoqBdHwR4KHAVffwe6P9Cil1-9VOK_Ckj44Y",
        "https://play-lh.googleusercontent.com/X728Tdmjp3qAaIE3QgCy7bheOWD2UtOOb1-unHhMhOoZprgknOB2vkUtkEZrrVKn2w",
        "https://play-lh.googleusercontent.com/G2tFI177qwgwzL-0Ury91P9AVPdpl9i9VsEoODbAvh20_iWkVO4zvihiszM4y05V2Ks"
    ],
    "video": "https://www.youtube.com/embed/RrosHEgrTVg?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/FA2PxwcslIr1_habO4oWVAo_vLQnlYsscV6HkFloeDLGpM7SkXmt0XiBdC9l132mgUg",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 22, 2017",
    "lastUpdatedOn": "Sep 7, 2024",
    "updated": 1725747153,
    "version": "1.27.0",
    "comments": [],
    "appId": "com.aeromexico.app",
    "url": "https://play.google.com/store/apps/details?id=com.aeromexico.app&hl=en&gl=us"
}