{
    "title": "Pixilart - Make Pixel Art",
    "description": "Create pixel art on the go. Pixilart is a community of passionate art enthusiasts who enjoy pixels. Easily make pixel art, and then share your art and even follow others who have created their own pixel art creations. \r\n\r\nBecome part of the largest pixel art community and understand why Pixilart is a growing community for feedback, sharing, art and more! It's fun and easy to create pixel art on the go with Pixilart. Simply move your finder across the screen to move the cursor and click on draw to lay pixels. Use blank canvases or choose from a variety of bases created by other users. \r\n\r\nKEY FEATURES\r\n\u2022 Create pixel art on the go with our easy-to-use drawing feature\r\n\u2022 Create from bases or blank canvases\r\n\u2022 Create profiles to upload drawings in the cloud for easier access on different devices\r\n\u2022 Upload drawings in private, or in public so others can see\r\n\u2022 Share drawings with others for feedback or simply to show off!\r\n\u2022 Receive notifications from likes, comments, mentions, and new followers\r\n\u2022 Follow your favorite artists on activity feeds\r\n\r\nPARENT INFORMATION\r\nPixilart is a social platform for all ages. There is no private messaging system. All conversations are public. Swearing filters are enabled by default. Spam filters are enabled by default. Users can easily block/un-follow others. All drawings are monitored.\r\n\r\nSUBSCRIPTIONS\r\nThere are no subscriptions",
    "descriptionHTML": "Create pixel art on the go. Pixilart is a community of passionate art enthusiasts who enjoy pixels. Easily make pixel art, and then share your art and even follow others who have created their own pixel art creations. <br><br>Become part of the largest pixel art community and understand why Pixilart is a growing community for feedback, sharing, art and more! It&#39;s fun and easy to create pixel art on the go with Pixilart. Simply move your finder across the screen to move the cursor and click on draw to lay pixels. Use blank canvases or choose from a variety of bases created by other users. <br><br>KEY FEATURES<br>\u2022 Create pixel art on the go with our easy-to-use drawing feature<br>\u2022 Create from bases or blank canvases<br>\u2022 Create profiles to upload drawings in the cloud for easier access on different devices<br>\u2022 Upload drawings in private, or in public so others can see<br>\u2022 Share drawings with others for feedback or simply to show off!<br>\u2022 Receive notifications from likes, comments, mentions, and new followers<br>\u2022 Follow your favorite artists on activity feeds<br><br>PARENT INFORMATION<br>Pixilart is a social platform for all ages. There is no private messaging system. All conversations are public. Swearing filters are enabled by default. Spam filters are enabled by default. Users can easily block/un-follow others. All drawings are monitored.<br><br>SUBSCRIPTIONS<br>There are no subscriptions",
    "summary": "Pixel drawing & social platform for everyone",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1309409,
    "score": 4.4076085,
    "ratings": 6629,
    "reviews": 1045,
    "histogram": [
        502,
        143,
        215,
        1041,
        4718
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Pixilart",
    "developerId": "Pixilart",
    "developerEmail": "support@pixilart.com",
    "developerWebsite": "https://www.pixilart.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.pixilart.com/privacy",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/r3TfuTEkPgg0jv5tVse5SqseSN31-yOhKGdBshdxNbdlvt0_bTC2QAKaxfcnj4_8gg",
    "headerImage": "https://play-lh.googleusercontent.com/wy2icjSrWUjpxydwqQFk9dl5aUruzpBpr9_GUQdPs4l0na5WVLXP-a_O1zx3qJBdg3Q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/qLky86FqOQEWtuHYZb32fWeAhjD3gurir378NR7XM4s8on8gvn_OhZjrHGi-nseBSh2G",
        "https://play-lh.googleusercontent.com/9_2sbMN1PZFAnnE9NYf02ykzzX5O6S6wY5Bq99eDyJOE60TJ4qR0t0zCumbccTroAkfE",
        "https://play-lh.googleusercontent.com/tPZqY-XX5MxZNLQu3u8Ep0Xp2Jm7il7zbVZuaHZMyjrLLDLGKr7CbA82v79X73ek1no",
        "https://play-lh.googleusercontent.com/wbZDuA-znMzqnf_ncEA46OD_W17QlEfB5IwcnHHn9Djr-gIwpcEFFGRc1H1_JC9DlCc",
        "https://play-lh.googleusercontent.com/wWYnecDIu1C5U8A3SiQnahqDIQOl7C6nLOWleiqMqhta4JOSUxBiRZKY6IJlf-rC4AgW",
        "https://play-lh.googleusercontent.com/y5R19WaNfxCM4lpcVnCxeirVZHkulTM7cdqM6mbgdXNDwzbmjPZ7FjXse36IiZB5kQ8"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 5, 2018",
    "lastUpdatedOn": "Aug 30, 2024",
    "updated": 1725007627,
    "version": "1.7.0",
    "comments": [],
    "appId": "com.pixilart.app",
    "url": "https://play.google.com/store/apps/details?id=com.pixilart.app&hl=en&gl=us"
}