{
    "title": "Our Days Co-Parenting Calendar",
    "description": "Our Days Co-parenting Calendar is an intuitive, easy-to-use app designed to simplify and streamline shared schedules. Whether you are co-parents, couples, family members, guardians, relatives, childcare providers, or even lawyers, Our Days makes it effortless to manage and share calendars.\r\n\r\nFounded by a dedicated parent who understands the co-parenting journey, this app is crafted with empathy and practicality to support shared responsibilities transparently.\r\n\r\nHIGHLIGHTS:\r\n\r\n\u00b7 Affordable\r\nNo parent should have to worry about the cost of managing their child's schedules. That's our motto.\r\n\r\n\u00b7 Easy Calendar Sharing\r\nKeep everyone on the same page.\r\n\r\n\u00b7 Simplified Schedules:\r\n2-2-3, alternating weeks, and more.\r\n\r\n\u00b7 Customizable Options:\r\nPersonalized schedules and day swaps.\r\n\r\n\u00b7 Location Check-Ins:\r\nSave important locations.\r\n\r\n\u00b7 Google Calendar Integration\r\n\r\nThe Our Days user-friendly interface allows for notifications, and seamless swap requests, ensuring that all parties are on the same page. It is the tool you need to stay organized and focused on what truly matters\u2014providing the best for your children.\r\n\r\nJoin now thousands of families who have transformed their co-parenting journey with the Our Days Calendar.\r\n\r\nWelcome!",
    "descriptionHTML": "Our Days Co-parenting Calendar is an intuitive, easy-to-use app designed to simplify and streamline shared schedules. Whether you are co-parents, couples, family members, guardians, relatives, childcare providers, or even lawyers, Our Days makes it effortless to manage and share calendars.<br><br>Founded by a dedicated parent who understands the co-parenting journey, this app is crafted with empathy and practicality to support shared responsibilities transparently.<br><br>HIGHLIGHTS:<br><br>\u00b7 Affordable<br>No parent should have to worry about the cost of managing their child&#39;s schedules. That&#39;s our motto.<br><br>\u00b7 Easy Calendar Sharing<br>Keep everyone on the same page.<br><br>\u00b7 Simplified Schedules:<br>2-2-3, alternating weeks, and more.<br><br>\u00b7 Customizable Options:<br>Personalized schedules and day swaps.<br><br>\u00b7 Location Check-Ins:<br>Save important locations.<br><br>\u00b7 Google Calendar Integration<br><br>The Our Days user-friendly interface allows for notifications, and seamless swap requests, ensuring that all parties are on the same page. It is the tool you need to stay organized and focused on what truly matters\u2014providing the best for your children.<br><br>Join now thousands of families who have transformed their co-parenting journey with the Our Days Calendar.<br><br>Welcome!",
    "summary": "Create Your Co-Parenting Calendar in Less Than a Minute.",
    "installs": "5,000+",
    "minInstalls": 5000,
    "realInstalls": 7277,
    "score": 4.418919,
    "ratings": 85,
    "reviews": 64,
    "histogram": [
        8,
        2,
        1,
        8,
        65
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.49 - $47.99 per item",
    "developer": "Our Days, LLC",
    "developerId": "4952212952216126922",
    "developerEmail": "support@ourdayscalendar.com",
    "developerWebsite": "https://www.ourdayscalendar.com",
    "developerAddress": null,
    "privacyPolicy": "https://ourdayscalendar.com/privacy-policy-2/",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/qtYtYVt1xvOy8lEoApt-nSm6tau_CykAXtsFr8jofeDM-ZL58SLDCnK3N9CTLtszKRI",
    "headerImage": "https://play-lh.googleusercontent.com/EY9IUDGH8Asg8MyBmQZ52q9e5b6vcfI2cmui3UhaL01L2BB7lpwxY1kRNumcmniaiTJX",
    "screenshots": [
        "https://play-lh.googleusercontent.com/wbym0X8vmlzrTdaCSbJolJUT-OVZ3k1IV10j_JkYZTVhk_G_0piDrK-O1XnunnNYTA",
        "https://play-lh.googleusercontent.com/O13Bqnbvusu-BijShOJNDHWNTpU3ODWlt1g_Y70XXSDHDKBTbwYew-HP47SJ1sXrBOY",
        "https://play-lh.googleusercontent.com/NnV5wYYWtXzPJeHDVln6IYRsIUmlxLKr2UuTC_mxQ-zvJEnaUxV6hQmdjrgQmLBsBpzb",
        "https://play-lh.googleusercontent.com/4xJ31_5N8qtKd97zOyLkssnByXhF9ISqVE3N5MobzWVRN1-tThmKCADNbd9yWYo6qg",
        "https://play-lh.googleusercontent.com/DimsV0Zq97gFkviP16kuqUp19W9LP6pspRAa4NQDzVnETVP5JxXrj9M2jDTxojnazAUX",
        "https://play-lh.googleusercontent.com/kLxm4sX5UYk8nxhdcjpqKKjO3rmfdE7CL3dfSPhtYo654qo5caSdx6rh1JJcvto4JA",
        "https://play-lh.googleusercontent.com/SaQyAwoO-HiYJ-2U2t2Kk8RFgT0l9ZvQ4MozNcFbBLbNi4XxkhZgqOvC3r19JgO5R1Y",
        "https://play-lh.googleusercontent.com/tbe2M-_UFPpRmnj90XwhPCUkgqYYWXLWSIyfRO-Iuj0e25c2xXtusJKQHPWx9SHK_Zc",
        "https://play-lh.googleusercontent.com/7nvZuewAZztry0UT37NLwyHM8zXc8Fw5CIrzQo6tm6I6tM3WpepTEXugIf6fQlfA4ks",
        "https://play-lh.googleusercontent.com/wP6hmvFI-tHF4XBAIv8SGsdkhftKq44r0eNVj70_7ZJDbAw8ujywYp-Yu8NUCFy5UA",
        "https://play-lh.googleusercontent.com/FwIvW7NQXINdf7CXQhVmPd3fI58ZkOUmP4wtAVBWxzhbkMi-yuV5Y3YQ11J_KhAPTKxx",
        "https://play-lh.googleusercontent.com/JKoa9lKUHZ8uuPHrDdCeXLLrkmPkLbpmYKLerJ73sIzN3daO_RF35rHmbpCpfme7RKD0",
        "https://play-lh.googleusercontent.com/Mwa2UrO34yRiMCeF2s3RnJsH_yfccuUcW3KQXNM5JUeNT_vePIG81CuUYm0izkxhlg",
        "https://play-lh.googleusercontent.com/hbDyPwFqtyuiG2dE_XZyB4zZ6K7BZti_WMqk4K9US5G82rIBGvP8R8TbGAIT7KrF0g",
        "https://play-lh.googleusercontent.com/5yRk-bAHYl1-7nWwCWGnwdg-bVT37jiwfGf2QXMsfYc8OcHyWDkG-E1glRnJqOI_7JU",
        "https://play-lh.googleusercontent.com/-PMqOaObX8BzkVQ_jB6PYRywhrrl_Imj1XY3DR0-k_hN3xisxBvObjRMMT-VDXO7tts",
        "https://play-lh.googleusercontent.com/l0z9xgm-sti071q4QfeIWp8KNnYAueyJpAmQUx9xnXKDtY8ppcLNVLGIyWy3u3H9cds",
        "https://play-lh.googleusercontent.com/75U1cWKui2FNZ_FP680cfF8MOHjD0SwsYY_B2JuTMMCCON4kgDyvXoTUEMSjjB6ybew"
    ],
    "video": "https://www.youtube.com/embed/OSp5Y0J47c4?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/EY9IUDGH8Asg8MyBmQZ52q9e5b6vcfI2cmui3UhaL01L2BB7lpwxY1kRNumcmniaiTJX",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 18, 2020",
    "lastUpdatedOn": "Sep 11, 2024",
    "updated": 1726054476,
    "version": "3.0.21",
    "comments": [],
    "appId": "com.ourdayscalendar.android.app",
    "url": "https://play.google.com/store/apps/details?id=com.ourdayscalendar.android.app&hl=en&gl=us"
}