{
    "title": "Mortgage News Daily",
    "description": "Mortgage Calculators \r\n- Basic mortgage payment calculator with charts\r\n- Full amortization table\r\n- Total cost of loan\r\n- Compare your loan against another\r\n- Early payoff scenarios\r\n\r\nMortgage Rates\r\n- Real-time mortgage rates\r\n- Instant alert when rates update (one per day)\r\n- Intraday rate trend, tracking MBS markets\r\n- Daily commentary with Mortgage Rate Watch\r\n- Historic rate charts\r\n- Track other rate surveys, Freddie Mac and MBA\r\n- Learn how mortgage rates work\r\n\r\nMBS Prices\r\n- Track MBS prices, 30 and 15 year\r\n- Track the 10 year treasury\r\n- Follow the markets with daily MBS Commentary\r\n- Learn about MBS markets and how they affect mortgage rates\r\n\r\nNews\r\n- Mortgage and Housing News\r\n- Mortgage Rate Watch\r\n- Daily MBS Market Commentary\r\n- Rob Chrisman's Daily Post\r\n- Video News \r\n- Around the Web \r\n\r\nOptional Instant Alerts\r\n- When mortgage rates change\r\n- When Mortgage Rate Watch is published\r\n- For any Housing News \r\n- When daily MBS Commentary is released\r\n- When Rob Chrisman's daily commentary is released",
    "descriptionHTML": "Mortgage Calculators <br>- Basic mortgage payment calculator with charts<br>- Full amortization table<br>- Total cost of loan<br>- Compare your loan against another<br>- Early payoff scenarios<br><br>Mortgage Rates<br>- Real-time mortgage rates<br>- Instant alert when rates update (one per day)<br>- Intraday rate trend, tracking MBS markets<br>- Daily commentary with Mortgage Rate Watch<br>- Historic rate charts<br>- Track other rate surveys, Freddie Mac and MBA<br>- Learn how mortgage rates work<br><br>MBS Prices<br>- Track MBS prices, 30 and 15 year<br>- Track the 10 year treasury<br>- Follow the markets with daily MBS Commentary<br>- Learn about MBS markets and how they affect mortgage rates<br><br>News<br>- Mortgage and Housing News<br>- Mortgage Rate Watch<br>- Daily MBS Market Commentary<br>- Rob Chrisman&#39;s Daily Post<br>- Video News <br>- Around the Web <br><br>Optional Instant Alerts<br>- When mortgage rates change<br>- When Mortgage Rate Watch is published<br>- For any Housing News <br>- When daily MBS Commentary is released<br>- When Rob Chrisman&#39;s daily commentary is released",
    "summary": "Real-time mortgage rates, mortgage calculators and find a local lender",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 35952,
    "score": 3.29,
    "ratings": 110,
    "reviews": 57,
    "histogram": [
        38,
        5,
        5,
        6,
        53
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Mortgage News Daily, LLC",
    "developerId": "7964031724252523818",
    "developerEmail": "support-mobile@mortgagenewsdaily.com",
    "developerWebsite": "https://www.mortgagenewsdaily.com",
    "developerAddress": null,
    "privacyPolicy": "https://mobile.mortgagenewsdaily.com/privacy",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/N9wmXOyhv5w2Jl0b7OOvarnw3f5iDWPhHiw4pVBoEPUEl-4UU_WwAo7YPm73SEVvPkQ",
    "headerImage": "https://play-lh.googleusercontent.com/bpi3uqT0GLPPJBVfQZI8bjaxOYmtIDkwwwpPOy3hGE5lpul7WgV90a7LIjtCbpZywA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/kmGR8qn3RKn3j3O25LKz1KNoaipeaVLDAI3DHMB91gKYxf7OX1JzwSUjvD9uByYgSnfy",
        "https://play-lh.googleusercontent.com/W0fFE3-2f87E_7tFmMBd5eFBvHxX6iRjDrIebryGHlNrG6r0UnZtqdBLv9QkD5on3A",
        "https://play-lh.googleusercontent.com/k-uGDPYCCH7u0WDsKVDZt3IqVQqIR6HOzDO6TlSJ_W5c4eoFLvQMhxTYLoxUg_IyyKHo",
        "https://play-lh.googleusercontent.com/_cUO1RqwgGmVwc6YdDvlr1tOgB8Ov7uKrISjx3T56wsbwb8nLs9i1ZxRgDduAn2ae_w",
        "https://play-lh.googleusercontent.com/A9qywvDpYvS27pCcm0SKXFxGjXrnhnYVz7ZQBgYT1VfC7YbwbgYdDIU7hUMbUULivqsH",
        "https://play-lh.googleusercontent.com/0zAznX2I3SqoHKad7VVGDxwGThHDqdDMrsdRmGIdGHcZLOv0goO-YQlatiplXHH3pfg",
        "https://play-lh.googleusercontent.com/qoIRX_gpi8H_NK10vFpx0t1ev8iIRasppXutJ9BdFPvpxhJdyWwVxu37icVeVTUmPwrV",
        "https://play-lh.googleusercontent.com/WtmrsXOegqTYM64YH4yqnXhGYqQO81XnJyZGDJ-GVjNRqP8iu2u0QHRpWOEZgWiNlw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 2, 2021",
    "lastUpdatedOn": "Apr 26, 2024",
    "updated": 1714135606,
    "version": "1.0.30",
    "comments": [],
    "appId": "com.mortgagenewsdaily.rates.app",
    "url": "https://play.google.com/store/apps/details?id=com.mortgagenewsdaily.rates.app&hl=en&gl=us"
}