{
    "title": "Satellite Tracker: Dish Finder",
    "description": "Satellite Tracker - Satellite Locator\r\nSatellite Finder is the ultimate app for satellite enthusiasts, space explorers, and satellite dish owners alike. With three powerful features - Satellite Finder, Satellite Map, and Compass of Satellite Tracker - Satellite Locator, satellite tracker revolutionizes your satellite tracking experience like never before while using Satellite Tracker - Satellite Locator and dish finder app.\r\n\r\nSatellite Map - Satellite Locator\r\nEffortlessly locate and track satellites in real-time with the Satellite Finder and Dish Finder features. Discover detailed information about each satellite, including its position, altitude, velocity, and upcoming passes over your location while using Satellite Map - Satellite Locator. Whether you're interested in communication, weather, or scientific satellites, Satellite Finder - Dish Finder has you covered with satellite ma, Satellite Finder: GPS Detector.\r\n\r\nSatellite Finder: GPS Detector\r\nSatellite Compass - Satellite Map: Immerse yourself in the world of satellites with the interactive Satellite Map. Explore the current positions of all tracked satellites worldwide while using Satellite Finder: GPS Detector. Zoom in, tap on individual satellites and visualize their orbital paths. It's a captivating way to witness the vast network of satellites encompassing our planet with a dish finder.\r\n\r\nSatellite Locator - Satellite Map\r\nAligning your satellite compass with Satellite Finder: GPS Detector has never been easier. The Compass feature provides precise azimuth and elevation angles, guiding you to accurately position your dish for optimal signal reception. Say goodbye to signal disruptions and hello to a seamless viewing experience with Dish Finder!\r\n\r\nSatellite Tracker - Satellite Compass\r\nUser-Friendly Interface: Our app boasts an intuitive and user-friendly interface with Satellite Finder: GPS Detector, making satellite tracking and alignment a breeze for users of all levels. Whether you're a novice or an expert, Satellite Finder ensures a smooth and enjoyable experience.\r\n\r\nSatellite Finder: GPS Detector\r\nOffline Mode: Don't let a lack of internet connectivity hinder your satellite tracking adventure. Satellite Finder's offline mode allows you to access saved data and continue using the app in remote locations or areas with limited network coverage.\r\n\r\nSatellite Compass - GPS Detector\r\nEmbark on an incredible journey of satellite tracker - satellite compass through the cosmos with Satellite Finder - your essential satellite tracking and alignment companion. Download the app now and get ready to explore the wonders of space!",
    "descriptionHTML": "Satellite Tracker - Satellite Locator<br>Satellite Finder is the ultimate app for satellite enthusiasts, space explorers, and satellite dish owners alike. With three powerful features - Satellite Finder, Satellite Map, and Compass of Satellite Tracker - Satellite Locator, satellite tracker revolutionizes your satellite tracking experience like never before while using Satellite Tracker - Satellite Locator and dish finder app.<br><br>Satellite Map - Satellite Locator<br>Effortlessly locate and track satellites in real-time with the Satellite Finder and Dish Finder features. Discover detailed information about each satellite, including its position, altitude, velocity, and upcoming passes over your location while using Satellite Map - Satellite Locator. Whether you&#39;re interested in communication, weather, or scientific satellites, Satellite Finder - Dish Finder has you covered with satellite ma, Satellite Finder: GPS Detector.<br><br>Satellite Finder: GPS Detector<br>Satellite Compass - Satellite Map: Immerse yourself in the world of satellites with the interactive Satellite Map. Explore the current positions of all tracked satellites worldwide while using Satellite Finder: GPS Detector. Zoom in, tap on individual satellites and visualize their orbital paths. It&#39;s a captivating way to witness the vast network of satellites encompassing our planet with a dish finder.<br><br>Satellite Locator - Satellite Map<br>Aligning your satellite compass with Satellite Finder: GPS Detector has never been easier. The Compass feature provides precise azimuth and elevation angles, guiding you to accurately position your dish for optimal signal reception. Say goodbye to signal disruptions and hello to a seamless viewing experience with Dish Finder!<br><br>Satellite Tracker - Satellite Compass<br>User-Friendly Interface: Our app boasts an intuitive and user-friendly interface with Satellite Finder: GPS Detector, making satellite tracking and alignment a breeze for users of all levels. Whether you&#39;re a novice or an expert, Satellite Finder ensures a smooth and enjoyable experience.<br><br>Satellite Finder: GPS Detector<br>Offline Mode: Don&#39;t let a lack of internet connectivity hinder your satellite tracking adventure. Satellite Finder&#39;s offline mode allows you to access saved data and continue using the app in remote locations or areas with limited network coverage.<br><br>Satellite Compass - GPS Detector<br>Embark on an incredible journey of satellite tracker - satellite compass through the cosmos with Satellite Finder - your essential satellite tracking and alignment companion. Download the app now and get ready to explore the wonders of space!",
    "summary": "Effortlessly locate satellites with our satellite tracker - dish finder app",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1655853,
    "score": 4.29,
    "ratings": 3454,
    "reviews": 59,
    "histogram": [
        442,
        88,
        53,
        194,
        2621
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$3.49 - $8.99 per item",
    "developer": "InfinitumSoft",
    "developerId": "InfinitumSoft",
    "developerEmail": "infinitumSoft.technologies@gmail.com",
    "developerWebsite": "https://e418c15ed.app-ads-txt.com",
    "developerAddress": "73 calverton road luton lu3 2sy",
    "privacyPolicy": "https://sites.google.com/view/satellite-finder-app/satellite-finder",
    "genre": "Maps & Navigation",
    "genreId": "MAPS_AND_NAVIGATION",
    "categories": [
        {
            "name": "Maps & Navigation",
            "id": "MAPS_AND_NAVIGATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/SxEmLbwT5nhkmTvgdkED5GzCebLYe15pJXoKN7flKuicwUlA6SWjV-R46ool0XaZpw",
    "headerImage": "https://play-lh.googleusercontent.com/_LqrSB0iDipe2iDVG6UzlOYRLr-249No4qJ99hBaCZXXhg58kfpbCgDfUzD-YIGh4Dk",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Q_ygFvWOy2ErC7skpiuJ54nynrBoUrq52vH4EoLAjXaaJVZeZu3HuUFfn1vo_WrXPOQ",
        "https://play-lh.googleusercontent.com/v7DM_h8TJyw5YVQ6ajre-e5H6dWvtVgVpVjkI-q-mGohcGOkiYYkksSagopMwUVXFw",
        "https://play-lh.googleusercontent.com/qUt53PuvDOyBQKK0JizccOf5tzB8ynrzvgVWpSim5prMi8bcg8kiB1R0TWe_vyry-DU",
        "https://play-lh.googleusercontent.com/ZlysivXO5IqbJ6XE8ZW8yETa19AP0K7GmUnCWLDzUrbkBx3tiKz0LocRFlAt2n4Lldo",
        "https://play-lh.googleusercontent.com/aQVoKUCOO1YkRcDfiyY7caZu6U51YuctQDJ38HOskgi_1l1JHpKNnlAWGjauP3YLbWVe",
        "https://play-lh.googleusercontent.com/y2JxK0zTWNdlJvMZqMVp0m88SjZaQbsfVheIJxc5-czfrH7VpX4WpX75HHXI3UDuHQ",
        "https://play-lh.googleusercontent.com/ZjKefPBwAO8ytuvL1nxoYM2yHUblU3a-qn1r1Dfvj_N9JuUq-8xSbKtMb4a4vGgmTVA",
        "https://play-lh.googleusercontent.com/XQXoj9_PPc7JRw-Bis3wz8pSjaEZtYIb7VbL8HQnjyR-WOOGRiF8RreOxUK-b5VKakZk",
        "https://play-lh.googleusercontent.com/G6vE2tMNshKNualncfTVRvsCouap9UaVWemVJ25HvoQAwOCZ0GMsgJbdiO_j8UIFblse",
        "https://play-lh.googleusercontent.com/44iaY_rw-44mWtQEPnkDZpO0qfM-L3Iohym47H2yDCIX6TAemgfcTh6AYr8IrAx2DiQ"
    ],
    "video": "https://www.youtube.com/embed/AgQGOj_s8HI?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/_LqrSB0iDipe2iDVG6UzlOYRLr-249No4qJ99hBaCZXXhg58kfpbCgDfUzD-YIGh4Dk",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 3, 2023",
    "lastUpdatedOn": "Oct 9, 2024",
    "updated": 1728492603,
    "version": "1.4.3",
    "comments": [],
    "appId": "com.is.satellite.finder.gps.detector.app",
    "url": "https://play.google.com/store/apps/details?id=com.is.satellite.finder.gps.detector.app&hl=en&gl=us"
}