{
    "title": "The Pattern Astrology",
    "description": "Created to help you feel seen and understood. A homegrown labor of love, The Pattern was born out of our founder\u2019s personal journey of self-discovery. While trying to make sense of a challenging time, she recognized what an incredibly empowering tool our birth charts can be and sought to develop an application that could offer this information in a way that was easily digestible for all. Offering a psychological blueprint of one\u2019s self and insight into the unique things they may be experiencing during a period of time, The Pattern acts as a mirror, helping you to better understand yourself and others, enabling connections to be made on a much deeper level. As featured in Vanity Fair, Time, TechCrunch, Vogue, Bustle, Mashable, Harper\u2019s Bazaar, among others. For answers to commonly asked questions, please visit: https://thepattern.zendesk.com/hc/\r\n\r\nFor additional customer support, please email us: contact@thepattern.com\r\n\r\nWe are excited to bring The Pattern community a brand-new design and updated user experience. Things have changed in Version 5! This massive upgrade features access to brand-new content, including our classic reminders.\r\n\r\nEnjoy even more personalized audios (now easier to find in your Vault!), as well as all new romantic relationship and timing insights. We are sending out monthly moon journeys, 360 immersive audios, astrology classes that help you go deeper into what's behind your chart and bonds, and so much more!\r\n\r\nWhat everyone gets for free:\r\n\r\n-Daily personalized updates about you and your romantic partner or friends\r\n\r\n-Bonds that you can view to explore your compatibility with anyone\r\n\r\n-Access to some of our content library, including chapters of Cosmic Climate\r\n\r\n-Manage your Friends and Custom Friends directly from their profile\r\n\r\nWhat our Go Deeper+ subscribers enjoy:\r\n\r\n-ALL NEW Romantic timing cycles in Bond Impacts\r\n\r\n-Unlimited access to the entire content library in Discover\r\n\r\n-Unlimited access to audios, conversations, and 360 immersive sound meditations\r\n\r\n-Traveling through time, which allows you to see how your life has been impacted during key moments in your life, both in the past and future\r\n\r\n-View unlimited bonds with anyone in your friends list or in our extensive public figures database\r\n\r\n-Classes in Astrology 101, to master all things astro in understandable terms\r\n\r\n-Full access to our Connect dating feature to find and chat with your perfect match\r\n\r\nJoin our community today!\r\n\r\n\r\nFollow @ThePattern on Instagram, TikTok and X. Share your favorite insights from The Pattern using #ThePattern. The Pattern offers in-app purchases that enhance the user experience. Auto-renewing \"Go Deeper+\" subscriptions may be purchased to unlock additional content starting at $29.99 for 3 months. Subscriptions are entirely optional and may be canceled at any time. Details are available in the Terms of Service, available here: https://www.thepattern.com/terms.html",
    "descriptionHTML": "Created to help you feel seen and understood. A homegrown labor of love, The Pattern was born out of our founder\u2019s personal journey of self-discovery. While trying to make sense of a challenging time, she recognized what an incredibly empowering tool our birth charts can be and sought to develop an application that could offer this information in a way that was easily digestible for all. Offering a psychological blueprint of one\u2019s self and insight into the unique things they may be experiencing during a period of time, The Pattern acts as a mirror, helping you to better understand yourself and others, enabling connections to be made on a much deeper level. As featured in Vanity Fair, Time, TechCrunch, Vogue, Bustle, Mashable, Harper\u2019s Bazaar, among others. For answers to commonly asked questions, please visit: https://thepattern.zendesk.com/hc/<br><br>For additional customer support, please email us: contact@thepattern.com<br><br>We are excited to bring The Pattern community a brand-new design and updated user experience. Things have changed in Version 5! This massive upgrade features access to brand-new content, including our classic reminders.<br><br>Enjoy even more personalized audios (now easier to find in your Vault!), as well as all new romantic relationship and timing insights. We are sending out monthly moon journeys, 360 immersive audios, astrology classes that help you go deeper into what&#39;s behind your chart and bonds, and so much more!<br><br>What everyone gets for free:<br><br>-Daily personalized updates about you and your romantic partner or friends<br><br>-Bonds that you can view to explore your compatibility with anyone<br><br>-Access to some of our content library, including chapters of Cosmic Climate<br><br>-Manage your Friends and Custom Friends directly from their profile<br><br>What our Go Deeper+ subscribers enjoy:<br><br>-ALL NEW Romantic timing cycles in Bond Impacts<br><br>-Unlimited access to the entire content library in Discover<br><br>-Unlimited access to audios, conversations, and 360 immersive sound meditations<br><br>-Traveling through time, which allows you to see how your life has been impacted during key moments in your life, both in the past and future<br><br>-View unlimited bonds with anyone in your friends list or in our extensive public figures database<br><br>-Classes in Astrology 101, to master all things astro in understandable terms<br><br>-Full access to our Connect dating feature to find and chat with your perfect match<br><br>Join our community today!<br><br><br>Follow @ThePattern on Instagram, TikTok and X. Share your favorite insights from The Pattern using #ThePattern. The Pattern offers in-app purchases that enhance the user experience. Auto-renewing &quot;Go Deeper+&quot; subscriptions may be purchased to unlock additional content starting at $29.99 for 3 months. Subscriptions are entirely optional and may be canceled at any time. Details are available in the Terms of Service, available here: https://www.thepattern.com/terms.html",
    "summary": "The most accurate, personalized astrological insight into yourself and others.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3548757,
    "score": 3.891575,
    "ratings": 23906,
    "reviews": 6526,
    "histogram": [
        3291,
        2521,
        1750,
        2258,
        14079
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$8.99 - $83.99 per item",
    "developer": "Pattern Home, Inc.",
    "developerId": "Pattern+Home,+Inc.",
    "developerEmail": "contact@thepattern.com",
    "developerWebsite": "https://thepattern.com",
    "developerAddress": "1083 N Collier Blvd #415\nMarco Island, FL 34145",
    "privacyPolicy": "https://www.thepattern.com/privacy-policy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Al6CA4smc7joCyX7veO5ZlwFt-7alBAEAayFpaDOGk78BTpSF1kmYtuNn5DzTJDkMts",
    "headerImage": "https://play-lh.googleusercontent.com/2Q85nokm-33Ba_UamFDOtMxnf1i_EWB1e-A8PWvgMeJkie06-8o7r5yDgw5fy1t2Mmt7",
    "screenshots": [
        "https://play-lh.googleusercontent.com/DBAYlbSaVVc10iVVkPjBGUO7ItuToWA9GC-uYP1udFVFUI50b4ESB9Ns22VXeLN0BoI",
        "https://play-lh.googleusercontent.com/0-IB5DGBMOeAe8bpi3Ig3mctzHsDCpc3hVomXMkWOq4V3tC5Gk1L4GyoC2RxcSGAnp0",
        "https://play-lh.googleusercontent.com/mhwYnmqkkBFOQwQGjXEvvdz83tkjj23iRM2Y6pUhbLtjuKFXrx5cZnBuWb8Jret9uLc",
        "https://play-lh.googleusercontent.com/dmZcy9SSNrAZj-9ldVvuo-jo-rlSjKsYGZ5AA-h3IlfUUMf_auNXf2Rc_gJx_cIErLs",
        "https://play-lh.googleusercontent.com/XWmu6rKAE2VcsU0nhYczWoXFNyVsfPuJK98xMRe72Xr7xgFsYG7qXmgtkR22b6N2fw",
        "https://play-lh.googleusercontent.com/v23berBLS1J3K63Vl9BdvvbU2xjedhQOXKakZrHXkep8eoCrPJrziaOUOh23S2WUbg",
        "https://play-lh.googleusercontent.com/LhxHfQ2YiYD2i0_fxQ58qeZBwZGtxJOD64qAKfXXBCP38k0wSsq3Dv31nM84u4EMXN4",
        "https://play-lh.googleusercontent.com/Gd5VsdD5pGV1L0Q_xSnx6r72t2y09zz-B6s9sFmvwRBNrd-XJO6N7Vd7etBnJtIAmAI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Oct 17, 2019",
    "lastUpdatedOn": "Oct 9, 2024",
    "updated": 1728502650,
    "version": "5.0.6",
    "comments": [],
    "appId": "com.thepattern.app",
    "url": "https://play.google.com/store/apps/details?id=com.thepattern.app&hl=en&gl=us"
}