{
    "title": "Face Me - AI Art Photo Editor",
    "description": "<b>Use interesting photo editing tools and powerful AI technology to edit photos easily and have fun.</b>\r\n\r\n<b>What AI photo tools are available on Face Me?</b>\r\nTry the popular AI effects in 2024, like\r\n- AI Dress Up\r\n- AI hairstyles\r\n- Couple photos & Bestie photos\r\n- AI Yearbook Photo Trends\r\n- AI Art Generator\r\n- Cartoonify\r\n- Vintage Photo\r\n- Face filters\r\n- Artistic background\r\n\r\n<b>Couple photos & Bestie photos</b>\r\nCreate your own couple photos or bestie photos by face swap with just one click. There are a variety of settings and themes to choose from to create exclusive memories.\r\nIt can be a fun and creative way to have fun with photos or videos, creating interesting and memorable content to share with each other or on social media.\r\n\r\n<b>AI Yearbook Photo Trends</b>\r\nGenerate AI YearBook photos, share your high school graduation photos on social media, and let your followers know a different you.\r\n\r\n<b>Aging Time Machine</b>\r\nEver wondered how you'd look in a different age? Image processing apps now grant you the power to visualize these transformations in a fun and engaging way. Witness yourself as a child, a wise elder, or explore a whole new identity.\r\n\r\n<b>Image Quality Enhancement</b>\r\nElevate your picture by enhancing image quality, making ordinary snapshots burst with vividness and clarity. Create high-quality photos!\r\n\r\n<b>Smart AI Cutout & Background Removal</b>\r\nCarefully separate figures, objects, and even animals with just one click. Use the Background Eraser to erase and replace backgrounds. Unleash your creativity and create photos unique to you.\r\n\r\n<b>Face editing tools</b>\r\n- One-click Beauty: Skin retouch, face toner, erase wrinkles and face filters\r\n- Old pictures coloring: Add new colors to your old memories\r\n- Hair Color, Hairstyle: Transform with different hairstyles\r\n- AI Collage: Create unique collages with different photos\r\n- Custom stickers, Text: Make your photos more unique\r\n\r\n<b>Just take or upload a selfie and get ready to meet your different self.</b> \r\nMore features are in development! If you have any problems or suggestions, please contact us at any time. E-mail: fillogfeedback@outlook.com",
    "descriptionHTML": "<b>Use interesting photo editing tools and powerful AI technology to edit photos easily and have fun.</b><br><br><b>What AI photo tools are available on Face Me?</b><br>Try the popular AI effects in 2024, like<br>- AI Dress Up<br>- AI hairstyles<br>- Couple photos &amp; Bestie photos<br>- AI Yearbook Photo Trends<br>- AI Art Generator<br>- Cartoonify<br>- Vintage Photo<br>- Face filters<br>- Artistic background<br><br><b>Couple photos &amp; Bestie photos</b><br>Create your own couple photos or bestie photos by face swap with just one click. There are a variety of settings and themes to choose from to create exclusive memories.<br>It can be a fun and creative way to have fun with photos or videos, creating interesting and memorable content to share with each other or on social media.<br><br><b>AI Yearbook Photo Trends</b><br>Generate AI YearBook photos, share your high school graduation photos on social media, and let your followers know a different you.<br><br><b>Aging Time Machine</b><br>Ever wondered how you&#39;d look in a different age? Image processing apps now grant you the power to visualize these transformations in a fun and engaging way. Witness yourself as a child, a wise elder, or explore a whole new identity.<br><br><b>Image Quality Enhancement</b><br>Elevate your picture by enhancing image quality, making ordinary snapshots burst with vividness and clarity. Create high-quality photos!<br><br><b>Smart AI Cutout &amp; Background Removal</b><br>Carefully separate figures, objects, and even animals with just one click. Use the Background Eraser to erase and replace backgrounds. Unleash your creativity and create photos unique to you.<br><br><b>Face editing tools</b><br>- One-click Beauty: Skin retouch, face toner, erase wrinkles and face filters<br>- Old pictures coloring: Add new colors to your old memories<br>- Hair Color, Hairstyle: Transform with different hairstyles<br>- AI Collage: Create unique collages with different photos<br>- Custom stickers, Text: Make your photos more unique<br><br><b>Just take or upload a selfie and get ready to meet your different self.</b> <br>More features are in development! If you have any problems or suggestions, please contact us at any time. E-mail: fillogfeedback@outlook.com",
    "summary": "One-stop AI Photo Editor: Face Swap, Change Age, Photo Enhance, Face Animation",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 8828577,
    "score": 4.3322034,
    "ratings": 46507,
    "reviews": 1261,
    "histogram": [
        6137,
        629,
        1259,
        2045,
        36402
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.99 - $199.99 per item",
    "developer": "Fillog Studio",
    "developerId": "8100907766243743423",
    "developerEmail": "fillogfeedback@outlook.com",
    "developerWebsite": "https://zhuilai.com.cn",
    "developerAddress": "SHEN ZHEN, CHINA",
    "privacyPolicy": "https://sites.google.com/view/vegoo-privacy-policy",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/rUnlvIhVItU-jP-H23GoUtKDSyQD-VbctNjoxCqkhysHHk9WOHO23_XKtfnhK86mwIlI",
    "headerImage": "https://play-lh.googleusercontent.com/XE_UW8Cmo8Ts0VRRT1J64ZCLRQvGfoGH91RjNX11TYNS0F8hiBsEL0tcEUD9gx_CJ-8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Oi_qu2fvxhR6G5gZTN-5zKk828zt9TXAO9e57FUSBFIP8fNcrceEk0EBiFi4mZKlJ5JN",
        "https://play-lh.googleusercontent.com/EDz08nOwppjH1wtm28F_ZhxRWEy3KRM0u7ofneb3_x7QWSwfnCcFiT5i_AwgCtYmm-Q",
        "https://play-lh.googleusercontent.com/oMrwsx6a884yjOc2htE3IyLyOrwkqfFaJHDsj5VzagwF7PDujII0qDvFUOwJrVW8oEmU",
        "https://play-lh.googleusercontent.com/gaoNFP2AlFe-ut31LllYukx-GXXVR_VEiHYEoArFJbTYARjm6NXl6BaOzN3ectuGoA",
        "https://play-lh.googleusercontent.com/8FVG7xosmhTfQGIcsQbXJw8mmOrUNnhLpNjH1gUkDGQ7JsYxk6P62KcvvqvdpnDOIxaB",
        "https://play-lh.googleusercontent.com/Xp_N-i5yo0R3_ZVwS6t3JAavgEHOUzZ0lM4JO0B-G02a4qegvKIwoxJU4LhnlZvISbZm",
        "https://play-lh.googleusercontent.com/CxaLb4W78tZlTFIge_nn5PWKZy3wE_etW4_5LwuypcS0G-FaW_Ukg4XJD_Lr6p3WqA",
        "https://play-lh.googleusercontent.com/AAzaApxzaTVdxujQmbKAsoFcX-ar2aH4njKLnitBk25FDjcUgyOSq0QbTJRG9PE4uw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 20, 2023",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729570562,
    "version": "1.9.1",
    "comments": [],
    "appId": "com.ai.photoeditor.fx",
    "url": "https://play.google.com/store/apps/details?id=com.ai.photoeditor.fx&hl=en&gl=us"
}