{
    "title": "Max Hurricane Tracker",
    "description": "The Max Tracker Hurricane app is powered by WPLG\u2019s Chief Certified Meteorologist Betty Davis, Hurricane and Storm Surge Specialist Michael Lowry, and a team of certified meteorologists bringing you the latest and most accurate information on developing tropical systems.\r\n\r\nKeep your family safe, download the free app today.\r\n\r\n\u2022 Projected Hurricane Paths\r\n\u2022 Interactive Live Storm Tracker\r\n\u2022 Local Radar\r\n\u2022 Live Local 10 news storm coverage\r\n\u2022 Severe Weather Alerts\r\n\u2022 Tropical Weather Outlooks\r\n\u2022 Watches and Warnings",
    "descriptionHTML": "The Max Tracker Hurricane app is powered by WPLG\u2019s Chief Certified Meteorologist Betty Davis, Hurricane and Storm Surge Specialist Michael Lowry, and a team of certified meteorologists bringing you the latest and most accurate information on developing tropical systems.<br><br>Keep your family safe, download the free app today.<br><br>\u2022 Projected Hurricane Paths<br>\u2022 Interactive Live Storm Tracker<br>\u2022 Local Radar<br>\u2022 Live Local 10 news storm coverage<br>\u2022 Severe Weather Alerts<br>\u2022 Tropical Weather Outlooks<br>\u2022 Watches and Warnings",
    "summary": "Helping to keep your family safe by providing the latest hurricane updates..",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 325892,
    "score": 4.6132684,
    "ratings": 7410,
    "reviews": 2628,
    "histogram": [
        215,
        251,
        274,
        694,
        5970
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Graham Media Group",
    "developerId": "Graham+Media+Group",
    "developerEmail": "android-support+WPLGhurricane@grahamdigital.com",
    "developerWebsite": "https://www.local10.com",
    "developerAddress": "550 W Lafayette Blvd\nDetroit Mi., 48230",
    "privacyPolicy": "https://www.local10.com/privacy",
    "genre": "Weather",
    "genreId": "WEATHER",
    "categories": [
        {
            "name": "Weather",
            "id": "WEATHER"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/HY3jhdtYXryU0THN3qhxHSVzXZyPZcHYBTYsPObRCt4kN24MbY75jCwqlEkKb-ovNIM",
    "headerImage": "https://play-lh.googleusercontent.com/ZHgEckOVTtDa3gqwp7pUfHSsqiHpKDohF5Ka1tvzOzxXdggDZCatc935o5LE97CO2_s",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Exa8FNJ1KLppk1QLh_GdXd2m1hldNJLnelVlfoxDZaeNmbQCJkYbzShKDumG1-PW2BrD",
        "https://play-lh.googleusercontent.com/fbOcNdRybdAAVl01YTpGDhMmKdyhaOZ6L_cObepMSBUszZFJdaeezsCV9MEJIQM4aw",
        "https://play-lh.googleusercontent.com/pK6BhfY9jHAY0azWy6WkK8qZz6h8xkh9sMRQok2lgO6Rshw2ffplMnnjagO5p_Z7ryQ",
        "https://play-lh.googleusercontent.com/qTEcowW19_bGnQQ9h5RoKB--DZFW2a0ws51-zWAUYozj8HnHqvSIjJ1_aBlSTCJGkLc",
        "https://play-lh.googleusercontent.com/cCVcBm53QfO-nrcWEC4OqOC84SeLJAHUdbXuj7u2jztBQfwczpsjguQNY_Hq4zGBiw",
        "https://play-lh.googleusercontent.com/qpf6gzUZnaCJsc0ANUPt68lK8Ffyfv7TSA6Z4_c4h5H1BXnqmKespp38GTA99qioAn8",
        "https://play-lh.googleusercontent.com/pGgU_r80nxiyk__6DbwL6NN6-wGEJFLsRNLzhbaevqe8MJ2r9cv4dovfK1qoG-k-Kjw",
        "https://play-lh.googleusercontent.com/TyzO6z5HG8AjFXFwt37-usa6gaQOFdsqTnRBPDLguNxRgp12-CqZGuQ5qqaIGPrSdy8",
        "https://play-lh.googleusercontent.com/EQos60Ldwhny0ouwpy0pwyPxkn_y2z4sR7a-hWVmgCR7GjK9Xvy7Lc_Dl57-VzuGgQ",
        "https://play-lh.googleusercontent.com/6G_4KeokkSpeKkqbKbIAuU95vF2FZUQ-_CJ_QfpDq1EY7K13sEA_62YkgC0ZUECr5Q"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 1, 2012",
    "lastUpdatedOn": "Jun 21, 2024",
    "updated": 1718962149,
    "version": "5.15",
    "comments": [],
    "appId": "com.justhurricanes.mia.app",
    "url": "https://play.google.com/store/apps/details?id=com.justhurricanes.mia.app&hl=en&gl=us"
}