{
    "title": "Dice War",
    "description": "Welcome to Dice War!\r\nStep into the world of Dice War, where your dreams of becoming a tycoon come true! In this immersive Monopoly-style game, you\u2019ll roll the dice, build magnificent structures, and trade your way to the top.\r\nKey Features:\r\n\u2022\tMonopoly Gameplay: Experience the classic board game with a modern twist. Roll the dice, move around the board, and acquire properties to build your empire.\r\n\u2022\tCity Building: Design and construct unique buildings to enhance your city's skyline. From quaint houses to towering skyscrapers, the choice is yours!\r\n\u2022\tAchievement Collection: Unlock and collect achievements as you progress. Show off your accomplishments and strive for perfection.\r\n\u2022\tStrategic Trading: Engage in dynamic trading with other players. Buy, sell, and negotiate to get the best deals and maximize your wealth.\r\n\u2022\tEvent Challenges: Participate in special events and challenges to earn exclusive rewards. Keep the excitement going with new content regularly.\r\nAre you ready to become the ultimate tycoon? Roll the dice and start your journey in Dice War today!",
    "descriptionHTML": "Welcome to Dice War!<br>Step into the world of Dice War, where your dreams of becoming a tycoon come true! In this immersive Monopoly-style game, you\u2019ll roll the dice, build magnificent structures, and trade your way to the top.<br>Key Features:<br>\u2022\tMonopoly Gameplay: Experience the classic board game with a modern twist. Roll the dice, move around the board, and acquire properties to build your empire.<br>\u2022\tCity Building: Design and construct unique buildings to enhance your city&#39;s skyline. From quaint houses to towering skyscrapers, the choice is yours!<br>\u2022\tAchievement Collection: Unlock and collect achievements as you progress. Show off your accomplishments and strive for perfection.<br>\u2022\tStrategic Trading: Engage in dynamic trading with other players. Buy, sell, and negotiate to get the best deals and maximize your wealth.<br>\u2022\tEvent Challenges: Participate in special events and challenges to earn exclusive rewards. Keep the excitement going with new content regularly.<br>Are you ready to become the ultimate tycoon? Roll the dice and start your journey in Dice War today!",
    "summary": "Roll the dice and start your journey in Dice War today!",
    "installs": "1,000+",
    "minInstalls": 1000,
    "realInstalls": 4164,
    "score": 2.8235295,
    "ratings": 40,
    "reviews": 10,
    "histogram": [
        18,
        2,
        2,
        0,
        16
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "Jiaze",
    "developerId": "Jiaze",
    "developerEmail": "xl1030520@gmail.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://metapoint.club/jiaze/privacy.htm",
    "genre": "Strategy",
    "genreId": "GAME_STRATEGY",
    "categories": [
        {
            "name": "Strategy",
            "id": "GAME_STRATEGY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/HGeVUn5FrGTTFcVykgUUuFeGjBo683JxRSRK90zuh4xAGm5Bqg0RPZHSsdm4oB5S_A",
    "headerImage": "https://play-lh.googleusercontent.com/3tSLAokV6LjXugZBl-zwZTJl8IWrefPDXWp5zNFJEKrKnBOurSTVb06pY-Pi4WYsJcE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/CriC1CWxmkxt9o7zrFQf4J1JSyu_8UNOUKlW9QGdw3xTuf01fxTXANCUMSW7rUyPWA",
        "https://play-lh.googleusercontent.com/89wJ7Fj-FmjeHRb0-MR-oYmL_4sUKgWsTjjMCkVCi751-7LzLGspdjUgn9Qq9yzDGQ",
        "https://play-lh.googleusercontent.com/Rr6m3c3ZWUtSYgV4FVVoaNN1wrX_j4a4hVa8ochoDZSNtJDSV2kV4SQU3TThQOQKwrE",
        "https://play-lh.googleusercontent.com/d_MvC8vWWFxDMI5ZriqzKnn3zwb5h5hmhxFF5boI-oxNXkRwCcunE2TtgjABggEPg6Wg",
        "https://play-lh.googleusercontent.com/-3laFMk6xLbrs1tMf87IMLe5TeZJuMC7UWzfgnmPH03JUoVCVPkLlc31uPFSrbS9Tg",
        "https://play-lh.googleusercontent.com/GuxsgTtITBPz6slQUcchs8RFxQocGxWUXkv99ullx_gVUOfaux1SDYM-1DmaObP7EOdY",
        "https://play-lh.googleusercontent.com/7fq-uBxCE8iSUhj7BBA-1FpMEzOdPS_JgcVK0HXqs543oyHcmrmXQGxr50X38k7_sQ",
        "https://play-lh.googleusercontent.com/k_Rl0dH9bTYqEcVtS90aItzahwCtgh-mM3dPu_QP1NqRxTBLlCbY06D_Zbw56nX3pOTU",
        "https://play-lh.googleusercontent.com/G1UNiZo_IfDL58XbepJ3S6UgwX-cM4bnUCsqwMdZ-9hAqS7qlP_wwqodTi0REU_i3Z0",
        "https://play-lh.googleusercontent.com/vytjGknRQoPjS8WWv_wJtExZcqwEKxzzmZwSG8h0Vy0S1pJ05TOZi35UqOqOR-W3OUmw",
        "https://play-lh.googleusercontent.com/XJVBjlqRVwzKvuw8APvhjFNMel9lQG_uG_xK368c64nal-o47ATQb0qgjfTv22R5J-Q",
        "https://play-lh.googleusercontent.com/lBhEO2RRvoO4IvXZg8zG-tKydVgOuYAJP_n36pOD2xpUE9ETZbUhvWjGtWy9hvKdCIs",
        "https://play-lh.googleusercontent.com/O86J6u9dg177bMlc4cew7nTGfPa1qN_kOT5UMWg9T0LY-ZNf5eIpy0FgSQVQAsPLrX4",
        "https://play-lh.googleusercontent.com/tsiz5NKEicwFodwxPS2V8aabhicZ2724VanRz93zMnOWIl9gCrQUGGdzR4Z73We62Gs"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 16, 2024",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729581862,
    "version": "1.250.577",
    "comments": [],
    "appId": "com.readygo.luck.gp",
    "url": "https://play.google.com/store/apps/details?id=com.readygo.luck.gp&hl=en&gl=us"
}