{
    "title": "Sereal+ - Stream Short Dramas",
    "description": "<b>Hottest K-Dramas, J-Dramas, and South Asian Dramas on the Go: Enjoy Captivating Short Dramas Anytime, Anywhere.</b>\r\n\r\n<b>Sereal+ is your ultimate hub for exclusive, dramatic ultra-short dramas, all lasting just a few minutes.</b> Addictive, short reels on demand from Korea to Japan, Indonesia, Spain, and beyond, all in one place. Whether you love pocket romance stories, Hollywood stories, AI stories, or intricate plot films, Sereal+ has got you covered!\r\n\r\nSereal+ lets you explore a world of romantic, hilarious, thrilling, heartwarming, and inspiring short stories during meals, while commuting, or even in between chores - all in minutes!\r\n\r\n \u2728 \u2728 Here's why Sereal+ is different: \u2728 \u2728\r\n\r\n\u2705<b>\u3010Diverse Drama Shorts\u3011</b>\r\n\u2022 Enjoy a wide range of high-quality & original short videos across various genres, including comedy, drama, romance, thriller, and more, and there's always something new to watch.\r\n\u2022 Storylines typically revolve around themes like romance and revenge, and each clip - usually just a minute long - ends in a cliffhanger. Get ready to be hooked by fast-paced storylines and unpredictable twists!\r\n\r\n\u2705<b>\u3010Discover English Dramas & Global Gems\u3011</b>\r\n\u2022 Korean &Japanese drama cravings? Or want to watch free movies from South Asia? Sereal+ has all your drama flix, in every language.\r\n\u2022 Dive into unique English-language dramas, free Kdramas with subtitles, and hidden short TV gems from Indonesia, Spanish-speaking countries, and beyond.\r\n\r\n\u2705<b>\u3010Trending, New & High-Quality Content\u3011</b>\r\n\u2022 Experience quality in every second with Sereal+!\r\n\u2022 Discover trending mini-shorts and fresh uploads from talented creators around the world.\r\n\u2022 Whether you're looking for laughs, thrills, inspiration, or love stories, Sereal+ has it all. Join the community and start watching today!\r\n\r\n\u2705<b>\u3010Personalized Recommendations\u3011</b>\r\n\u2022 Sereal+'s AI recommendation algorithms help you get video suggestions tailored to your viewing history and preferences, ensuring you always find new sweet short films you love.\r\n\r\n\u2705<b>\u3010High-Quality Online Series Streaming\u3011</b>\r\n\u2022 Sereal+ is one of the most incredible reelshorts & drama shorts streaming platforms to watch free short movies and TV shows, where you can immerse yourself in stunning short HD movies & videos with crystal-clear visuals and flawless streaming.\r\n\r\n<b>\u3010User-Friendly Interface\u3011</b>\r\n\u2022 Navigate the app effortlessly with an intuitive and user-friendly design.\r\n\r\n\r\n\ud83d\udccd <b>Good Short Reels, Big-Time Fun!</b> \ud83d\udccd \r\n\r\nExplore the World of Top-Notch Reels of Tiny Shows in Minutes: Sereal+!\r\n\r\nSereal+ lets you experience the best streaming, HD quality, ad-free viewing, and personalized recommendations. You can create playlists, save favorites, and dive into a world of captivating short stories. Sereal+ also breaks down language and location barriers, bringing you good short TV shows from around the globe! Perfect for any moment, whether you're at home or on the go.\r\n\r\n<b>Download Sereal+ today and unlock a world of short dramas waiting to be discovered!</b>\r\n\r\n\ud83d\udc40 Stay in touch with us!\r\n\r\n\u25ba For more information, visit the Sereal+ website at https://sereal.com/.\r\n\u25ba Share your Sereal+ app experience by providing feedback at Contact@serealplus.com.\r\n\u25ba Concerned about using the app safely? Review our Terms of Service at https://sereal.com/TermsOfUse and Privacy Policy at https://sereal.com/PrivacyPolicy.",
    "descriptionHTML": "<b>Hottest K-Dramas, J-Dramas, and South Asian Dramas on the Go: Enjoy Captivating Short Dramas Anytime, Anywhere.</b><br><br><b>Sereal+ is your ultimate hub for exclusive, dramatic ultra-short dramas, all lasting just a few minutes.</b> Addictive, short reels on demand from Korea to Japan, Indonesia, Spain, and beyond, all in one place. Whether you love pocket romance stories, Hollywood stories, AI stories, or intricate plot films, Sereal+ has got you covered!<br><br>Sereal+ lets you explore a world of romantic, hilarious, thrilling, heartwarming, and inspiring short stories during meals, while commuting, or even in between chores - all in minutes!<br><br> \u2728 \u2728 Here&#39;s why Sereal+ is different: \u2728 \u2728<br><br>\u2705<b>\u3010Diverse Drama Shorts\u3011</b><br>\u2022 Enjoy a wide range of high-quality &amp; original short videos across various genres, including comedy, drama, romance, thriller, and more, and there&#39;s always something new to watch.<br>\u2022 Storylines typically revolve around themes like romance and revenge, and each clip - usually just a minute long - ends in a cliffhanger. Get ready to be hooked by fast-paced storylines and unpredictable twists!<br><br>\u2705<b>\u3010Discover English Dramas &amp; Global Gems\u3011</b><br>\u2022 Korean &amp;Japanese drama cravings? Or want to watch free movies from South Asia? Sereal+ has all your drama flix, in every language.<br>\u2022 Dive into unique English-language dramas, free Kdramas with subtitles, and hidden short TV gems from Indonesia, Spanish-speaking countries, and beyond.<br><br>\u2705<b>\u3010Trending, New &amp; High-Quality Content\u3011</b><br>\u2022 Experience quality in every second with Sereal+!<br>\u2022 Discover trending mini-shorts and fresh uploads from talented creators around the world.<br>\u2022 Whether you&#39;re looking for laughs, thrills, inspiration, or love stories, Sereal+ has it all. Join the community and start watching today!<br><br>\u2705<b>\u3010Personalized Recommendations\u3011</b><br>\u2022 Sereal+&#39;s AI recommendation algorithms help you get video suggestions tailored to your viewing history and preferences, ensuring you always find new sweet short films you love.<br><br>\u2705<b>\u3010High-Quality Online Series Streaming\u3011</b><br>\u2022 Sereal+ is one of the most incredible reelshorts &amp; drama shorts streaming platforms to watch free short movies and TV shows, where you can immerse yourself in stunning short HD movies &amp; videos with crystal-clear visuals and flawless streaming.<br><br><b>\u3010User-Friendly Interface\u3011</b><br>\u2022 Navigate the app effortlessly with an intuitive and user-friendly design.<br><br><br>\ud83d\udccd <b>Good Short Reels, Big-Time Fun!</b> \ud83d\udccd <br><br>Explore the World of Top-Notch Reels of Tiny Shows in Minutes: Sereal+!<br><br>Sereal+ lets you experience the best streaming, HD quality, ad-free viewing, and personalized recommendations. You can create playlists, save favorites, and dive into a world of captivating short stories. Sereal+ also breaks down language and location barriers, bringing you good short TV shows from around the globe! Perfect for any moment, whether you&#39;re at home or on the go.<br><br><b>Download Sereal+ today and unlock a world of short dramas waiting to be discovered!</b><br><br>\ud83d\udc40 Stay in touch with us!<br><br>\u25ba For more information, visit the Sereal+ website at https://sereal.com/.<br>\u25ba Share your Sereal+ app experience by providing feedback at Contact@serealplus.com.<br>\u25ba Concerned about using the app safely? Review our Terms of Service at https://sereal.com/TermsOfUse and Privacy Policy at https://sereal.com/PrivacyPolicy.",
    "summary": "Watch Hit Reel Shorts: KDrama, South Asian Drama, Japanese Mini Series & Episode",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2101848,
    "score": 3.7620192,
    "ratings": 29188,
    "reviews": 2994,
    "histogram": [
        5047,
        2735,
        2383,
        2944,
        16062
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $259.99 per item",
    "developer": "Sereal",
    "developerId": "Sereal",
    "developerEmail": "contact@serealplus.com",
    "developerWebsite": "https://serealplus.com/",
    "developerAddress": null,
    "privacyPolicy": "https://serealplus.com/secret/",
    "genre": "Entertainment",
    "genreId": "ENTERTAINMENT",
    "categories": [
        {
            "name": "Entertainment",
            "id": "ENTERTAINMENT"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/IGS4Z-byoC7dr-939hkAKRBK-5K2g5czfnnxx-O-orJc_WU-wfjPFpFshWg52_QwfAI",
    "headerImage": "https://play-lh.googleusercontent.com/JDW1_1_tzMOpcGZwtybWVrBEdap5EI7LI_6Sp1_wMQaIUAwYZevdtL41VHalWhDTKQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/n9bOrbuR6p2tglPSvhVurfZK9U3Sk68KJUM9V5yi5hDWiX5BBO2DUq-_MvcnbPty4Ow",
        "https://play-lh.googleusercontent.com/fH_4EGMm5xOGVnXJ9w9hGsCh0v6wmK31tf2G6reg_q7-oSwOPt0g6RIe81JMmt4xuA",
        "https://play-lh.googleusercontent.com/u2vHme1VRrh6YlsylQqr74M_97blNxCk5MVgfQCb3eZeFx55mTfzsd9ApI1nIPKruw",
        "https://play-lh.googleusercontent.com/aYK92L0DQPqqvKt5pYoIcM1jX13DFZyipXdeM3rfGBXvtI3eeq_WCac5YTfvLefGtQ",
        "https://play-lh.googleusercontent.com/OCOSJB0-6PZd4XqDqJPQpdLZzuP5cxTyw3cLcpl_Ppeutwogxy9rV2fhYbJnxPg2qg",
        "https://play-lh.googleusercontent.com/V0nSoUsJlacNVyfKxxfXRkdL2Ek8c9SHgvlMgSi_BJWBoCYQe7FByfpAEO3mRHkbHHY",
        "https://play-lh.googleusercontent.com/_GfdyHXAOQCrzBG_eUlWBPqcPNz5M6-JGxGPtrReVpk3n9Ybh8Hg97pPqXEzrWCK3A",
        "https://play-lh.googleusercontent.com/K6Bo63JvZZGfAPvg7TvMmTdllcuWum4V29YlZO_MW7L77j5J2XYIfJZF86TW9YvrPQ",
        "https://play-lh.googleusercontent.com/OHLd2vTJn7_HBnvtwsy9oih9U8eibuwxjYa11dQhO9cwbBlbZtZbhq-eNLz5LIAYOPg",
        "https://play-lh.googleusercontent.com/8E7Dii6hYjWFi7ncgUWCVilcTKzZjp6_TGRPeQDXpT7VSJVMdcdSlh7CszjOfB5AOlI",
        "https://play-lh.googleusercontent.com/mYgbnfaCoPojoNMNe3xKLoKQYmAAn8-lF8fzR8Fldq6oX9XMw0b1T9PHYh6qQxDae_KO",
        "https://play-lh.googleusercontent.com/m85Sa4iAs8P9mcJNOumh4eAft3FipzcqspUG9e9_YNbKVS5qeWPlkqJ9qQsdhZPbo2M",
        "https://play-lh.googleusercontent.com/of-pwzIy8bhngybjb0j4Jlf_n-LpvjS4vEUp5EaXkF193AeTn8nJTti5REdkwgnAQGCx",
        "https://play-lh.googleusercontent.com/4TXVhozlydM2tnJrpxK4ijPAq7MaI0f2015AUWxrqt0S40O_1kTjrLK35VSzOZca4Q",
        "https://play-lh.googleusercontent.com/gi_efLQUno2IZSUXyK5BvfZFrF5ifqZdlCdRpYkgyhC2qUCulDDFyXROHuIPM8HiDA",
        "https://play-lh.googleusercontent.com/XF6_pi5FWZOLEs83FtMBlj0Hatlj-zZFAturm9kcfkeRG8i_QpelhqK35k_7XWkgiQ",
        "https://play-lh.googleusercontent.com/JYohzYlG_KS87BeG3rjBj3nzun_z3YhV2u6XUwRIfPJzSD5KusVVohzZOJkRkqZmQDg6",
        "https://play-lh.googleusercontent.com/2_WvyurcRM0EaKtB9T2rwVUSjt2RPzbPZxpaoHdc2Ab0YfrTGpWtd56IfeNJjY4GNsA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 16, 2024",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729243738,
    "version": "1.36.5",
    "comments": [],
    "appId": "com.sereal.short.app",
    "url": "https://play.google.com/store/apps/details?id=com.sereal.short.app&hl=en&gl=us"
}