{
    "title": "Lashify",
    "description": "Shop Lashify\u2019s cult lash system on our brand new app! Find your perfect lash looks with our curated Lash Maps. Customize your Lashify Membership and explore content that gives a deeper look into Lashify - plus exclusive behind the scenes content.",
    "descriptionHTML": "Shop Lashify\u2019s cult lash system on our brand new app! Find your perfect lash looks with our curated Lash Maps. Customize your Lashify Membership and explore content that gives a deeper look into Lashify - plus exclusive behind the scenes content.",
    "summary": "DIY Luxury Lash Extensions",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 24793,
    "score": 4.841584,
    "ratings": 782,
    "reviews": 173,
    "histogram": [
        23,
        0,
        6,
        15,
        734
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Lashify Inc.",
    "developerId": "Lashify+Inc.",
    "developerEmail": "app@lashify.com",
    "developerWebsite": "https://lashify.com",
    "developerAddress": null,
    "privacyPolicy": "https://lashify.com/pages/privacy",
    "genre": "Beauty",
    "genreId": "BEAUTY",
    "categories": [
        {
            "name": "Beauty",
            "id": "BEAUTY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Qvh2g7gaJ_vHqeBlQARILHUDmuHGW2dC_3Cn-Cx0CZ30joiuVdIuqfrW21bMUejxl80",
    "headerImage": "https://play-lh.googleusercontent.com/bRGzXQomDCkLgxhSwutSpL7eJ_52DK-YzOaY0wKplGcZt4Jm1hHN2dBJzAWX5Rm5Ig_l",
    "screenshots": [
        "https://play-lh.googleusercontent.com/uDeGqwmz8sd8AUxOtLsBKtObbHv-SP5TeILkb0tFCiDB4D7Er_CmIqwTuYHx7qryfWjX",
        "https://play-lh.googleusercontent.com/EJ0ZqwpJbDJ5ONqJp2Io1FwI7KKHEUgQ1wOPvBoL2_TZ895pZ_AHezPEntQGKQkcVcE",
        "https://play-lh.googleusercontent.com/4gcDufhu7eX32gWN5vpm3tKhWmvxTEYmhFa2U8PsZ0KdtoLw8q-3iTH9nUZfIWQ85Q",
        "https://play-lh.googleusercontent.com/qHZo_PV65B7scX5KWYYj_JLJ1XBxJhokRqFRf31zJvlUMpFuoQJxKAri3edc8XTlFSc",
        "https://play-lh.googleusercontent.com/RMhkcWusGcpkzbYWZR9n2RgwHpFsvzM-u3CKP26-AOrzGQw1qzfT1GnZfoh2UqgQfADd"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 2, 2020",
    "lastUpdatedOn": "Aug 9, 2024",
    "updated": 1723187869,
    "version": "2.0.48",
    "comments": [],
    "appId": "com.lashify.app",
    "url": "https://play.google.com/store/apps/details?id=com.lashify.app&hl=en&gl=us"
}