{
    "title": "Buzztime Trivia",
    "description": "Get the Buzztime Trivia app to play Buzztime at your favorite location as well as play \u201cCountdown GO\u201d and \u201cBuzztime Dash\u201d on the go. Challenge your smarts by answering questions provided by the nation\u2019s leading trivia company. Once you download Buzztime Trivia, simply login or register as a new player to unlock these buzzworthy features!\r\n\r\nBuzztime Trivia Features:\r\n\r\n\u2022 Play all the exclusive Buzztime trivia network games that you know and love to earn Players Plus Points!\r\n\u2022 Just head into your favorite Buzztime location and select the Play at a Buzztime Location button on the home screen to play using your mobile device.\r\n\u2022 Claim your spot at the top of local and network leaderboards so you can brag about it to your bar buddies.\r\n\r\nOR \r\n\r\n\u2022 Play single-player trivia games while out of Buzztime venues to top the daily leaderboards.\r\n\u2022 Find your favorite trivia topics from categories like sports, pop culture, music, movies, and more in Countdown GO! Grab a beverage and get ready to trivia and chill.\r\n\u2022 Want to play faster? Buzztime Dash will test your quickness in 10-second questions with NO HINTS! We can't look away either!\r\n\r\n\r\nWith Buzztime Trivia, you get your daily trivia fix. Choose your favorite game here https://www.buzztime.com/app/schedule and head into a Buzztime location to play: http://www.buzztime.com/site-finder \r\n\r\nKnow a business that is perfect for Buzztime? Earn cash for referrals! https://www.buzztime.com/business/referral \r\n\r\nGet Buzztime for your business! https://www.buzztime.com/business/pricing/",
    "descriptionHTML": "Get the Buzztime Trivia app to play Buzztime at your favorite location as well as play \u201cCountdown GO\u201d and \u201cBuzztime Dash\u201d on the go. Challenge your smarts by answering questions provided by the nation\u2019s leading trivia company. Once you download Buzztime Trivia, simply login or register as a new player to unlock these buzzworthy features!<br><br>Buzztime Trivia Features:<br><br>\u2022 Play all the exclusive Buzztime trivia network games that you know and love to earn Players Plus Points!<br>\u2022 Just head into your favorite Buzztime location and select the Play at a Buzztime Location button on the home screen to play using your mobile device.<br>\u2022 Claim your spot at the top of local and network leaderboards so you can brag about it to your bar buddies.<br><br>OR <br><br>\u2022 Play single-player trivia games while out of Buzztime venues to top the daily leaderboards.<br>\u2022 Find your favorite trivia topics from categories like sports, pop culture, music, movies, and more in Countdown GO! Grab a beverage and get ready to trivia and chill.<br>\u2022 Want to play faster? Buzztime Dash will test your quickness in 10-second questions with NO HINTS! We can&#39;t look away either!<br><br><br>With Buzztime Trivia, you get your daily trivia fix. Choose your favorite game here https://www.buzztime.com/app/schedule and head into a Buzztime location to play: http://www.buzztime.com/site-finder <br><br>Know a business that is perfect for Buzztime? Earn cash for referrals! https://www.buzztime.com/business/referral <br><br>Get Buzztime for your business! https://www.buzztime.com/business/pricing/",
    "summary": "Play Buzztime trivia games that you know and love.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 15704,
    "score": 3.2564104,
    "ratings": 85,
    "reviews": 50,
    "histogram": [
        25,
        3,
        10,
        16,
        29
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Buzztime",
    "developerId": "Buzztime",
    "developerEmail": "bztsupport@buzztime.com",
    "developerWebsite": "https://www.buzztime.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.buzztime.com/business/privacy-policy/",
    "genre": "Trivia",
    "genreId": "GAME_TRIVIA",
    "categories": [
        {
            "name": "Trivia",
            "id": "GAME_TRIVIA"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/xOQ5ZU39FgjT9Vn8_SCtAft0zd9f6BXFA-m-YvyFBsTTyi4tBM0t-mDw7IrtJIv3-Fo",
    "headerImage": "https://play-lh.googleusercontent.com/60trXg_89Y5KCXRqnThXmSnffrahAnlCSBj2fp75al9FV5W3pvTOO1mRyBBhU_GQipE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Yzdxui8c7usCfeAPggdtKt-VOm23AKtboHmG5SWJQGaWsyEeAJDg4yi4Gfi7RJ_YfK4",
        "https://play-lh.googleusercontent.com/Sir-b1HWBrxfw93oHwMQWNint5CXLsyZwqliAWWHfuruMpi33VeU5pcDBX7K7pArK3A",
        "https://play-lh.googleusercontent.com/FmW3Vsf5YRjNSBQ5mT4scR6iyvxyFUwtWif7Wr7CrfxCiyq5dnlOEA4g6sEbc5IRxm4",
        "https://play-lh.googleusercontent.com/YmUbuIt2Q8RRzJN43KV5eXIF1JDE9LcyNGUpt2FJTs6_AfnQiMuk0wviMSIG9oltnos",
        "https://play-lh.googleusercontent.com/oICHSTz_-EEOr6Gedm_hfJrYiijO5wt8PVlBz2GYGqWMRQGtCbVdP2MWGoLGaSee67PN",
        "https://play-lh.googleusercontent.com/HhuLv8NGRlT2jPxjksL-cm5_OSWBNO1jUH4Yo4nAFL98OZcvgesMaCExBt94x32J6dk",
        "https://play-lh.googleusercontent.com/R8gJ3HuDFvHB9TSVRSCfROWyEQhk-Ln8gY8UO70SX_ZhBo3G57n7HT-D7IeCq7LB9Y4",
        "https://play-lh.googleusercontent.com/bRm5zTBCREEQ1Alx317JwU9NojUIXLw-Frup0HgJCPGX3Vw1hdVIxK6kMMoT_RPD2Q",
        "https://play-lh.googleusercontent.com/WsDcbYAAGKegb7AIOMKZqhD5IshW71ttRTUrxDFuVraCanjTyBXC-DM0YhG6vz6NatIU",
        "https://play-lh.googleusercontent.com/zlyNiG0_MR5ffcy-OM26C2ldCtwwzf7ok1iwWo158rSl_1fDl4V0gniLoxIXsgee56I",
        "https://play-lh.googleusercontent.com/2lL-rP8QaCAccaM7KdJrkf1DmdphmcxmkFg20Th4HPZOJJdhXkHL46AVvxyueHm3Vh8",
        "https://play-lh.googleusercontent.com/CI4YredeXwZbT-dXwMuEZpciI0O1D38qVk0wGRuE7zmIPpi2J-X7yXGhjPhto39QxeI",
        "https://play-lh.googleusercontent.com/P4UJ3LpmB8e9_okGoUDWFCvPyoiNZDQh1xlX-oV3wYC0ECTky4BCYjpTCtWgV7oNgSE",
        "https://play-lh.googleusercontent.com/xnjGGdtseSlndo6yO9wLozT_YYQ5bhCcjMjw7ptjmFjctxnb50O6YrrjaOPtdyiDWUw",
        "https://play-lh.googleusercontent.com/VgQX5rTS22nQNgx5ix7h0BGZF9NWIyh07ebgy1uI_foPh69h7R1nKUmo076bNfRpHg1O",
        "https://play-lh.googleusercontent.com/fVoxg8wnoZn-t6MOnDyeLzBQ-vs2PkwFjFo4slP9XGmhF9beWLyAkqf2Mx4AZEyT1-s",
        "https://play-lh.googleusercontent.com/GL_eW0PA48bfjv4frIy3HzUbxRa9Flg_2Phyh2nyxMyxIHjrLm2bw9Ag0vqcz21_oQ",
        "https://play-lh.googleusercontent.com/x_gJgtTVENPsmqRzyjJ9taz9vmb5l68AQMx3jXQWqwQttGlDg2-V_TQzQXme0tWQqcC0",
        "https://play-lh.googleusercontent.com/mFYfMA3JNTkc7WISM4ftWcAozwaIyTveiSKJuaKr1mY6jQWCksHhXo4ErjH8DYItKaw",
        "https://play-lh.googleusercontent.com/1jwQC73s8AUuHow2ZVneuuVuTEjb21HY1blbhG5l2JciYTK6qqChwrZ5b7-lpV-bbzs",
        "https://play-lh.googleusercontent.com/j3KIYleknutb8CKVOyyXbu7-lAjjnGVI2RDEzC6W4yliqkRtOps-eY4VGaW8BNiBVqs",
        "https://play-lh.googleusercontent.com/hmWd1n9Dfx-wYJ7DQ0nxUb_9M5icq6bmOrrhDK-gn841ZECIYeliHuKVhd-SgkmLTKD6",
        "https://play-lh.googleusercontent.com/Vg-EXJns7Vt8iqLrDICTOxuhCeksQTrtFF3eC9QLn3baSBeSWS-5BKpQjjgC9tVWN7Ds"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Dec 28, 2020",
    "lastUpdatedOn": "Aug 30, 2024",
    "updated": 1725081338,
    "version": "1.0.19",
    "comments": [],
    "appId": "com.buzztime.go",
    "url": "https://play.google.com/store/apps/details?id=com.buzztime.go&hl=en&gl=us"
}