{
    "title": "Wear OS by Google Smartwatch",
    "description": "The Wear OS by Google app, previously Android Wear, syncs your smartwatch and phone so you can get more out of your watch. Get proactive help from your Google Assistant, see important messages, track health and fitness, and more, all from your wrist:\r\n\r\n\u2022 GET PROACTIVE HELP FROM YOUR GOOGLE ASSISTANT: Stay on top of your day with proactive, personalized help and useful shortcuts from your Google Assistant. Get commute times, see upcoming reservations, check your flight status and more.\r\n\u2022 TAKE YOUR HEALTH AND FITNESS FURTHER: Get healthier and more active by tracking your progress towards your Heart Points and Steps goal\r\n\u2022 ROCK OUT WHILE YOU WORK OUT: Control your favorite music right from your wrist and stay motivated through the last mile\r\n\u2022 STAY CONNECTED AT A GLANCE: Check important notifications, texts, emails, and calls at a glance\r\n\u2022 GET MORE DONE: See your next meeting, add items to your grocery list, set reminders, pay on the go and more\r\n\u2022 EXPRESS YOURSELF: Wear OS by Google lets you be you with hundreds of styles\u2014from fashion to fitness to fun and thousands of watch faces you can customize\r\n\r\nLearn more http://google.com/WearOS\r\n\r\nSupported features may vary across watches, phones, and countries. The Google Assistant is not available in certain countries and languages.",
    "descriptionHTML": "The Wear OS by Google app, previously Android Wear, syncs your smartwatch and phone so you can get more out of your watch. Get proactive help from your Google Assistant, see important messages, track health and fitness, and more, all from your wrist:<br><br>\u2022 GET PROACTIVE HELP FROM YOUR GOOGLE ASSISTANT: Stay on top of your day with proactive, personalized help and useful shortcuts from your Google Assistant. Get commute times, see upcoming reservations, check your flight status and more.<br>\u2022 TAKE YOUR HEALTH AND FITNESS FURTHER: Get healthier and more active by tracking your progress towards your Heart Points and Steps goal<br>\u2022 ROCK OUT WHILE YOU WORK OUT: Control your favorite music right from your wrist and stay motivated through the last mile<br>\u2022 STAY CONNECTED AT A GLANCE: Check important notifications, texts, emails, and calls at a glance<br>\u2022 GET MORE DONE: See your next meeting, add items to your grocery list, set reminders, pay on the go and more<br>\u2022 EXPRESS YOURSELF: Wear OS by Google lets you be you with hundreds of styles\u2014from fashion to fitness to fun and thousands of watch faces you can customize<br><br>Learn more http://google.com/WearOS<br><br>Supported features may vary across watches, phones, and countries. The Google Assistant is not available in certain countries and languages.",
    "summary": "Wear OS by Google app, previously Android Wear, syncs your smartwatch and phone",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 85759010,
    "score": 3.5330894,
    "ratings": 282412,
    "reviews": 15262,
    "histogram": [
        76476,
        14357,
        19033,
        27194,
        145337
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Google LLC",
    "developerId": "5700313618786177705",
    "developerEmail": "apps-help@google.com",
    "developerWebsite": "http://support.google.com/wearos",
    "developerAddress": "1600 Amphitheatre Parkway, Mountain View 94043",
    "privacyPolicy": "http://www.google.com/policies/privacy",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/WmoV-m8b6x16sDRfzebu5b2vstcyBHRrpzCj6ODoh6hGuMa9Gg39EvnOk7z3qMa0_WM",
    "headerImage": "https://play-lh.googleusercontent.com/NgCCxBEBydNcr7MHnxiOBC_BYfd8zVfVcgqJmvPSWPBPkb_nXWfErRyyDab_7B4H51CM",
    "screenshots": [
        "https://play-lh.googleusercontent.com/B7VE4Am0WbwadPNJIi6nxtJ9meGWm2LsT_2uyJssZ7Wk9-EQWH9Oz2IFo1knjIiLrh8",
        "https://play-lh.googleusercontent.com/8jmYa2szbgJ6gc7tNyQcb0JVP46VGjzUN7Lcxu81N7ighEobJADFBs-zzpAgplfJxt8",
        "https://play-lh.googleusercontent.com/Hzpwa1sU0UPFu49g3vQO1VFSX07Q_t7yBfJzJg1MqpXOTMB-HbgWMP6iuXbwmYnjtDA",
        "https://play-lh.googleusercontent.com/vvlutrf7CacJ8Z63njWLN_bhM0Jq0aCBJsnTibdlTa0louw-Md8yijG8Iq9I1u2Y7v0g",
        "https://play-lh.googleusercontent.com/ny6jQbEhoC5z6hlRgiuAVxbC3VHAzjgHdp77CsmgbqdVBKrHFnMwojmQrVyYsGxiQGVR",
        "https://play-lh.googleusercontent.com/C6AYsUz_lk_zSt6vlmTGpxFW_bJ2XMtRXQ-nclEi4r8RWr6ToUa5CvdiePJkz6YhPng",
        "https://play-lh.googleusercontent.com/WrTderi5yQYNkE3C3nWXJ5VZLDJc0epatd8P-EOdy_NqAyuomOCe4FIiM3za7RBz6zc",
        "https://play-lh.googleusercontent.com/CLah251Od1F8cezB9qDfsHca8I_53uOJvF6gkPBnCV8KZoLwBTt0X0Efcgy46mVXiw",
        "https://play-lh.googleusercontent.com/kFjN0Ke0lQEnOaYRgyb0bcpxWTr9EvVaWvNpK4GagRPBaX5BE3EDjZoJaYV2xuOQ7IY",
        "https://play-lh.googleusercontent.com/9pe3iMsa-_N6_hwjf1bFeWUv7W_0YbSjOK7qgO4xb5ttby-75gdEZ4i-UJr9-Kuiy6qo",
        "https://play-lh.googleusercontent.com/HPZ4sdMKLSEaMWuorrS-_9nOT03vsqG2CKzAo4nSe02F_VeFgs6l1aNP-uJT1tMdmPdx",
        "https://play-lh.googleusercontent.com/gw9-k7iJiD0ukeQC2-zrpQq0-93QKGe09UY7HzmF2QZ_L93LVsANo6SyTjfAjkshYI8",
        "https://play-lh.googleusercontent.com/gG3rRKpco-HpAgMw4LdZsR-oD3fhgOjjjJ6BX7DhGbkfz1Fk8BDdcOMXxj9volTs1zg",
        "https://play-lh.googleusercontent.com/UJvcstl2ckv4J2_nYIDe0byWFpsba_NduJ13cr9TMp3joypdBezZeyP7XqceRMi1zRCd",
        "https://play-lh.googleusercontent.com/Z-DG8zwertbPsvZxoG1uT7uFe4co5hEV5Spy3dwT0v8NN7Ly1X63fJav2qDLHFj5CIQ",
        "https://play-lh.googleusercontent.com/DgOu9rMnNBnZMuvhLEwVgvcamT5-g4WGsI71tW-RRS_cMwktHC9gGvK-kSsObV9AiA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 2, 2014",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728912056,
    "version": "Varies with device",
    "comments": [],
    "appId": "com.google.android.wearable.app",
    "url": "https://play.google.com/store/apps/details?id=com.google.android.wearable.app&hl=en&gl=us"
}