{
    "title": "Clubhouse",
    "description": "Clubhouse is where people come together to hang out, talk about anything, and make new friends from all walks of life.\r\n\r\n* explore thousands of live conversations\u2014go deep on the big topics happening today or just chill out and hang with friends\r\n\r\n* share your thoughts, or just listen in\u2014raise your hand to speak up or lean back and break out the popcorn\r\n\r\n* vibe with your people\u2014curate a personalized hallway just \u201cfor you,\u201d where every room is filled with people that love what you love\r\n\r\n* host a room\u2014be the one to bring people together and lead the conversation\r\n\r\n* sidebar with friends\u2014talk privately during and after live rooms, even when you\u2019re not online at the same time\r\n\r\n* drop in to rooms throughout the day\u2014when your commuting, running errands, or out for a run, you never know who you might bump into",
    "descriptionHTML": "Clubhouse is where people come together to hang out, talk about anything, and make new friends from all walks of life.<br><br>* explore thousands of live conversations\u2014go deep on the big topics happening today or just chill out and hang with friends<br><br>* share your thoughts, or just listen in\u2014raise your hand to speak up or lean back and break out the popcorn<br><br>* vibe with your people\u2014curate a personalized hallway just \u201cfor you,\u201d where every room is filled with people that love what you love<br><br>* host a room\u2014be the one to bring people together and lead the conversation<br><br>* sidebar with friends\u2014talk privately during and after live rooms, even when you\u2019re not online at the same time<br><br>* drop in to rooms throughout the day\u2014when your commuting, running errands, or out for a run, you never know who you might bump into",
    "summary": "talk, listen, hang out",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 21794554,
    "score": 4.030832,
    "ratings": 571322,
    "reviews": 3917,
    "histogram": [
        102520,
        15947,
        25243,
        45198,
        382361
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Alpha Exploration Co.",
    "developerId": "Alpha+Exploration+Co.",
    "developerEmail": "support@clubhouse.com",
    "developerWebsite": "https://www.clubhouse.com/",
    "developerAddress": null,
    "privacyPolicy": "https://privacy.clubhouse.com/",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/AQa5kjFAEk7uyYWhDmLzjuz3zMAVhF3853CRr0vmAboeA7KE4-HAWKZdx9OCmswz7Sir",
    "headerImage": "https://play-lh.googleusercontent.com/ws06ggtHcT-IUUp92yxKp2QbT0RF2k5qnPHIM36oSiLZV-8VcDWrMQSJ0XpdK_rx3yQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/wvksylu3SNnbOwXPVcBv8wEqGe0bhvVnxvysKmAsFtruH9APPnbP2Vz9CKCQWWlZ4A",
        "https://play-lh.googleusercontent.com/ee6H1DY7l5RTq3ilI1RHu_lYiX4gAFqWq7YL7ZdQlcopstp9dwUJLOBZzRRibPZng9vx",
        "https://play-lh.googleusercontent.com/gKFAKZr23arUjEmWRviPgL-gc8h0LAvJ7Qpou77ZrY0aPObeYhdGimJTJ6fYccTzwGZ9",
        "https://play-lh.googleusercontent.com/WW5hJdQ8ySn9q3QPOnZYdswakdh3yn-_WRr8ja9XyqG7GD7x1vxHuhdNZKHXyKH1OA",
        "https://play-lh.googleusercontent.com/8qI6UVqLrAftkl9rKVPqlNp7QKbtcLBdqpyou9TxA6fW_vIgpEXC9a1eiyXm8L5oPXQ",
        "https://play-lh.googleusercontent.com/jWHMjVY4a6JxW1LOnYQEi6HnYEYVAd_sPbuvqAHhMIzo2SLsmKiqrNgn-8bAimJxKTya",
        "https://play-lh.googleusercontent.com/B0S0Oykxp5SjxchoAn_xvTwbGnU3qw_jf9d4Jwfh79WFofXarXffPSfnu5gvTObJQJBf",
        "https://play-lh.googleusercontent.com/puOP_gDu1ePzXfWdJmgy04_zF0cwH_-FYAbnclGx1Phzrmvj-JVNH5oqkDs46RNSokE",
        "https://play-lh.googleusercontent.com/iLiFDj1SF1GjPbLYHCuafYm73kfh_-1XUngjkgfw1_qqAAc5jNWB5SjmKV8LYo-a6co",
        "https://play-lh.googleusercontent.com/1cHeggIBAqlO-djvqsRPPmoUqQCx5AHTpX0-L90rjAIrcJQ2AUyE7hkawNuoLvLcRA",
        "https://play-lh.googleusercontent.com/MVJaF5b_etAyKlGND-ETHP7VbN1MiU46Q-jGAtNjYwetqojppZvHVhaYD6fes499Oh8",
        "https://play-lh.googleusercontent.com/FJ-gGGQ02cnNPz2qCmqjNbZK-UyS9ETkPQDIAEo79vUJdr0o6cPdhatVh0sp9EFvjg",
        "https://play-lh.googleusercontent.com/p2EIdSVHQlDHlE2yTWfBWSIYEQ329Y-uWCFZemFLPHPrr6FMqpHji8izdw8FfvsnaQ",
        "https://play-lh.googleusercontent.com/rqlozoWoj3QIjglJX9p7u4i8_92b6F-TGyPfp8vB0wKjirXUwjbkQNJrCHOY4HjGyw",
        "https://play-lh.googleusercontent.com/-T-jKV7CWZ36hClmMJtZqpl19MzX1UvhpF-PsXKQXEhXvJlicOXwsV5Ae_HuCtqS0cvg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 20, 2021",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729283958,
    "version": "24.10.15",
    "comments": [],
    "appId": "com.clubhouse.app",
    "url": "https://play.google.com/store/apps/details?id=com.clubhouse.app&hl=en&gl=us"
}