{
    "title": "Fifth Third: 53 Mobile Banking",
    "description": "Securely access your accounts, deposit checks\u00b2, view recent transactions, pay bills, transfer money\u00b9, and find ATMs and branches.\r\n\r\nSee over six months of account history and account details. Plus you can view total pending credit card transactions, and 24 months of statements. If you\u2019re a first time user, just follow the link on the login page to get started.*\r\n\r\n\r\nDEPOSIT CHECKS\r\n\r\nSave a trip to the bank and deposit checks with your phone - as late as 8 PM ET to process your deposit the same business day.\u00b2,\u00b3 And Mobile Deposit with Immediate Funds can get you access to the full amount of your check right away.\u2074\r\n\r\n\r\n\r\nTRANSFER MONEY & PAY BILLS\r\n\r\nGet in. Get out. Transfer funds quickly. Add new payees and make payments right from the app.\u00b9\r\n\r\n\r\nSEND MONEY with ZELLE\u00ae PERSON-TO-PERSON PAYMENTS\r\n\r\nIt\u2019s Easy. It\u2019s Fast. It\u2019s Secure. Send money to virtually anyone with no added fees, all they need is a U.S. bank account. Money moves directly from account to account and is typically available within minutes.\u2075 Use an email address or mobile phone number to send and receive payments, account information is not exposed to users.\r\n\r\n\r\n\r\nFIFTH THIRD INSTANT ALERTS\u00ae\r\n\r\nTrack your debit, credit, and ATM transactions with a message directly to your phone or your email. Take quick action just by swiping or clicking on the mobile app alert when you receive it, and conveniently view and manage your alert preferences right within the app. New to alerts? Login and click on the Alerts menu under your profile and we\u2019ll recommend the right ones for you.\r\n\r\n\r\nHELP YOURSELF\r\n\r\nUpdate your account information and preferences. No need to call - activate cards, change card PINs, update your user ID, choose electronic statement delivery, and manage your alerts in the app.\r\n\r\n\r\nLOCATIONS & HOURS\r\n\r\nStop in and see us. Find Branches & ATMs by mapping directly to one of our locations. Get the branch hours or call us with just one click.\r\n\r\n\r\nSECURITY\r\n\r\nWe are committed to protecting the privacy of your financial information. When you use the Fifth Third Mobile Banking app, all of your information is encrypted to help prevent unauthorized access. See our Online Privacy Policy at 53.com/privacy-security for more information.\r\n\r\n\r\n\r\n\r\nDisclosures\r\n\r\n\r\n*Subject to Digital Services User Agreement. Mobile Internet data and text message charges may apply. Please contact your mobile service provider for details.\r\n\r\n\r\n\r\n\u00b9 Transfers from a credit card will be treated as a cash advance. Please review the terms and conditions of your credit card for additional details. Transfer limitations may apply refer to the Rules and Regulations.\r\n\r\n\r\n\r\n\u00b2 Access 360 and Basic Checking accounts are not eligible for mobile deposit. Fees may apply to mobile deposit with immediate funds, and the service is not available to business accounts.\r\n\r\n\r\n\u00b3 Checks are subject to an additional review by Fifth Third, and the availability of funds from your deposit may be delayed in some instances. You will be mailed notification if the availability of funds from your deposit is delayed.\r\n\r\n\r\n\r\n\u2074 Subject to transaction fee based upon deposit amount. Terms and Conditions apply. Transactions subject to applicable cutoff times. Please see Digital Services User Agreement for details regarding cutoff times. All checks subject to approval by a third-party vendor.\r\n\r\n\r\n\u2075 Transactions between enrolled Zelle users typically occur in minutes. If your recipient is not yet enrolled with Zelle, it may take between 1 and 3 business days after they enroll. Availability may be limited based on your account type and the date of account opening. Zelle is a registered trademark of Early Warning Services, LLC.\r\n\r\n\r\nFifth Third Bank, National Association. Member FDIC.",
    "descriptionHTML": "Securely access your accounts, deposit checks\u00b2, view recent transactions, pay bills, transfer money\u00b9, and find ATMs and branches.<br><br>See over six months of account history and account details. Plus you can view total pending credit card transactions, and 24 months of statements. If you\u2019re a first time user, just follow the link on the login page to get started.*<br><br><br>DEPOSIT CHECKS<br><br>Save a trip to the bank and deposit checks with your phone - as late as 8 PM ET to process your deposit the same business day.\u00b2,\u00b3 And Mobile Deposit with Immediate Funds can get you access to the full amount of your check right away.\u2074<br><br><br><br>TRANSFER MONEY &amp; PAY BILLS<br><br>Get in. Get out. Transfer funds quickly. Add new payees and make payments right from the app.\u00b9<br><br><br>SEND MONEY with ZELLE\u00ae PERSON-TO-PERSON PAYMENTS<br><br>It\u2019s Easy. It\u2019s Fast. It\u2019s Secure. Send money to virtually anyone with no added fees, all they need is a U.S. bank account. Money moves directly from account to account and is typically available within minutes.\u2075 Use an email address or mobile phone number to send and receive payments, account information is not exposed to users.<br><br><br><br>FIFTH THIRD INSTANT ALERTS\u00ae<br><br>Track your debit, credit, and ATM transactions with a message directly to your phone or your email. Take quick action just by swiping or clicking on the mobile app alert when you receive it, and conveniently view and manage your alert preferences right within the app. New to alerts? Login and click on the Alerts menu under your profile and we\u2019ll recommend the right ones for you.<br><br><br>HELP YOURSELF<br><br>Update your account information and preferences. No need to call - activate cards, change card PINs, update your user ID, choose electronic statement delivery, and manage your alerts in the app.<br><br><br>LOCATIONS &amp; HOURS<br><br>Stop in and see us. Find Branches &amp; ATMs by mapping directly to one of our locations. Get the branch hours or call us with just one click.<br><br><br>SECURITY<br><br>We are committed to protecting the privacy of your financial information. When you use the Fifth Third Mobile Banking app, all of your information is encrypted to help prevent unauthorized access. See our Online Privacy Policy at 53.com/privacy-security for more information.<br><br><br><br><br>Disclosures<br><br><br>*Subject to Digital Services User Agreement. Mobile Internet data and text message charges may apply. Please contact your mobile service provider for details.<br><br><br><br>\u00b9 Transfers from a credit card will be treated as a cash advance. Please review the terms and conditions of your credit card for additional details. Transfer limitations may apply refer to the Rules and Regulations.<br><br><br><br>\u00b2 Access 360 and Basic Checking accounts are not eligible for mobile deposit. Fees may apply to mobile deposit with immediate funds, and the service is not available to business accounts.<br><br><br>\u00b3 Checks are subject to an additional review by Fifth Third, and the availability of funds from your deposit may be delayed in some instances. You will be mailed notification if the availability of funds from your deposit is delayed.<br><br><br><br>\u2074 Subject to transaction fee based upon deposit amount. Terms and Conditions apply. Transactions subject to applicable cutoff times. Please see Digital Services User Agreement for details regarding cutoff times. All checks subject to approval by a third-party vendor.<br><br><br>\u2075 Transactions between enrolled Zelle users typically occur in minutes. If your recipient is not yet enrolled with Zelle, it may take between 1 and 3 business days after they enroll. Availability may be limited based on your account type and the date of account opening. Zelle is a registered trademark of Early Warning Services, LLC.<br><br><br>Fifth Third Bank, National Association. Member FDIC.",
    "summary": "If your phone is on, your bank is open.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3972905,
    "score": 4.678351,
    "ratings": 169386,
    "reviews": 30926,
    "histogram": [
        5667,
        1905,
        4579,
        16930,
        140299
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Fifth Third Bank",
    "developerId": "Fifth+Third+Bank",
    "developerEmail": "53_EmailMessages@53.com",
    "developerWebsite": "https://www.53.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.53.com/site/global/privacy-security/consumer/pp-online-privacy-policy.html",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/XgUSJia0wZ_rmKCDowtQmTyM-5EXRI2HpRX2hB-LeEhnEvxQSvV0VkXUTCxSf4sMqQ",
    "headerImage": "https://play-lh.googleusercontent.com/MDJynO2K0Y--9BvOU_g3dNhSVEVYDaqto0-E1dGI3cfG-wWmo3zhsfScb0zhyHUo1Q",
    "screenshots": [
        "https://play-lh.googleusercontent.com/bXB_wn3AUOfD-5FmMYkKk3j8svGgne0Br14ND6tOHjN9_yDen7EN5jgJUThMySna8oU",
        "https://play-lh.googleusercontent.com/5q8Il5On-A3lPAjKQflPOCMWySWnniz4h9dP7lY8OaIwu1EDkc8wlP_0HCmUnqkQarg",
        "https://play-lh.googleusercontent.com/OWAeebbC1rEHTvwQV1404U8Nv-cBf9KoodM7n03ZWMxV1epQWJ3ZEU2yuiH5QSsMFMtS",
        "https://play-lh.googleusercontent.com/ZRrIMrjQRoZ1NV1Q-Ojsm6OoNTmkg4LqpK3Utlottm484m8vW9fuJinhBYt5eCEzIQ",
        "https://play-lh.googleusercontent.com/t_U5a2ArL2xeV1AhNowDckcqgQBS7Xx3xSyYGYbU3PBq9mHmlh3mC2hwYg6-U4hr3U0",
        "https://play-lh.googleusercontent.com/7bmzIfDUFbpgy6-oY9AvpGzTILytCMcYvor08edrHkh0rzQloFpz3I7w3Tv_ZmbvG2eo",
        "https://play-lh.googleusercontent.com/ii5oENCIvi-WzPG0O7UOeCtV1H2VFOVJI8ZFRMAuvRv9nyHryOG2hZCrhrVdcVyNwQ",
        "https://play-lh.googleusercontent.com/i3cuc8MDvA8N5jz_BSpnpwuCfu-aYYqzmNAy-rEumMG9TT1qgLvEl__PSyzi2FpMtKc",
        "https://play-lh.googleusercontent.com/KJaaAPCn23XeHqneUfuE1dTlEDd3lRVfS-tub6e_3dc5N_U0xk4O-Ilse7LjLTfzcEA",
        "https://play-lh.googleusercontent.com/d7r5FH56YLIwDyoxnS4Fqap5lh1Anr6RswwDXC1H4psIVZw3iV9ELdfc6dyXDWcA6vY",
        "https://play-lh.googleusercontent.com/MnvWtLEbHMk0nqha3t6zh8ghwtuSVC80KdRuSCosuSdg5q7PNy2IVE-C1nYiUmq_B5to",
        "https://play-lh.googleusercontent.com/Omrk0sRsmDXdo7jRBAXRbeHsVKveVvr44inCtyMGTk8DKl6a_AL4kQPakMM8HpdtkMI",
        "https://play-lh.googleusercontent.com/wevMA3pTsNYgzU08-NztCqSg4FE56Ljf7FH1SF-8aw8EkwSwWGX9L8XJ3PyP4vNj_eM",
        "https://play-lh.googleusercontent.com/XWjaoKYA7Vwe1X_T8PcF8Z5gOX9V2aTDk55gHLq91orTMwczLR94iN-JCwq8uqtU7b0",
        "https://play-lh.googleusercontent.com/uAAlA6qwvR41_3CDPDMn9EN_NsW_2FYkQYxu9fBKVOa8PMtojBpsK9OdBUtMEpjcZBc",
        "https://play-lh.googleusercontent.com/-cSCq9l11Pr7ZdQHwb0lksOUkuQTHP_o_BO1GzbUOgfGmjhnpR_zM-RPR9nXd1eJKQ",
        "https://play-lh.googleusercontent.com/PCvFIcIVX37mQdvQWT1eyQhYdwd9poxz-Ij72EwAAiLIJrirpZlnbrNSrlUAEL-MA8A",
        "https://play-lh.googleusercontent.com/0jPyC_xMDaaC9PVjEiGQLtF6ppI-1pIi25EV0itSEXwaEMnYV5hcHt6F3u350gKw63k",
        "https://play-lh.googleusercontent.com/EoocTCdedHTJABFNTh7m0PC5brRH2nu2qnTuMYgV3mWWVBhipxDoibHA-lU1ATrf8eg",
        "https://play-lh.googleusercontent.com/JPx4_t04jp-8I0P5g3aYNwF3_Hj79GfqWVoJEDMl8Fk5ov3fDZxXUV7SFrY13hyfHIE",
        "https://play-lh.googleusercontent.com/RxpbJplG1bpTRyOcQzRioG-xWdJ_QsOzb4QWVmldMStCTyFlT41NJc57Qkzlqgc4KR8",
        "https://play-lh.googleusercontent.com/9PkzDWmpuX4kwjs_8VlBd5GHyos3O0t3-qSXyqZmjgmXxIazGHBdXdklLyd0spNiQSea",
        "https://play-lh.googleusercontent.com/xywkxjaD4MDRE5zYgBPUJRqr6iQkgJkX4Uudfd1eW1_6zke8WmYP1XxtlRYFfUkAuC73",
        "https://play-lh.googleusercontent.com/qI9XY4Ss51scykfqqYPUfBjI8ju2ynKNDDVOLZsX4wK8lbKcdgZxahrnblcTLrk_2tg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Nov 16, 2011",
    "lastUpdatedOn": "Oct 9, 2024",
    "updated": 1728497958,
    "version": "4.38.0",
    "comments": [],
    "appId": "com.clairmail.fth",
    "url": "https://play.google.com/store/apps/details?id=com.clairmail.fth&hl=en&gl=us"
}