{
    "title": "Manualslib - User Guides & Own",
    "description": "Find, view and read manual or user guide you need without creating an account.\r\n\r\nWith ManualsLib app, you can find any Owner's Manual or User's Guide you need, add it to \u201cMy Manuals\u201d list, and view it on your mobile device anytime.   \r\n\r\n\ud83d\udd0e Search manuals and guides by device/product name.\r\nTo find the right manual or user guide, you just need to know the name of your device.\r\nFor example, to find a guide for Fitbit Alta, you need type \u201cFitbit Alta\u201d into the search bar and tap on \u201cSearch.\u201d In the search results, you\u2019ll see all documents available for this device.\r\n\r\n\ud83c\udf9b Use search filters by type of document, manufacturer of device, and type of device. \r\nManualsLib is a major platform to search manuals and user guides. For many devices, ManualsLib offers different types of documents (user guides, installation instructions, fast start guides, spec lists, maintenance manuals, etc.). Use filters to search guides by type of document, manufacturer, and type of device. \r\n\r\n\ud83d\udcc3 View manuals and guides without adding it to \u201cMy Manuals\u201d list \r\nAll manuals and guides are available for FREE and limitless viewing and reading. You can search and open any number of manuals.\r\n\r\n\ud83d\udcc1 Add manuals and guides to \u201cMy Manuals\u201d list to view them offline\r\nTo be able to access manuals and user guides offline, you need to add them to your \u201cMy Manuals\u201d list. You\u2019ll be able to access your added files in the ManualsLib app even when you\u2019re not connected to the Internet.\r\n\r\n\ud83d\uddc2 Create folders for easier access and storage \r\nFor easier access to your manuals, you can sort your documents by location and type of device. For example, you can create a \u201cSummer house manuals\u201d folder to store guides on all devices in your summer house. \r\nFurthermore, you can create folders to store user manuals for certain devices, e.g. \u201ccars guides\u201d, \u201ccamera guides\u201d, \u201cappliance guides\u201d, etc. \r\n\r\n\ud83d\udd0d Search inside a document\r\nYou can search inside the document for the information you need. Use simple key phrases, e.g. \u201cbattery charge\u201d instead of \u201chow to charge the battery.\u201d You need to be connected to the Internet to use the document search option.\r\n\r\n\ud83d\udcc4 View Table of Contents for each document\r\nAlmost every manual available in ManualsLib contains a Table of Contents for easier navigation within the document.\r\n\r\n\ud83d\udccc Create and name bookmarks \r\nBookmarks are the fastest way to access the page you need. When creating a bookmark, give it a short, descriptive name. \r\nFor example, the page that tells how to change oil in your quad bike can be named \u201cOil change.\u201d Avoid using long names, e.g. \u201cQuad oil change manual\u201d, as you\u2019ll be able to see the name of the manual in the bookmarks menu. \r\n\r\n\u2709\ufe0f Share links to an entire document or its specific page\r\nTo your friends who haven\u2019t installed the ManualsLib app (or don\u2019t know the ManualsLib.com website), you can send a link to the entire manual or a single page.\r\nSuppose, you gave your mom a new GoPro to record your dad\u2019s adventures. But your mom doesn\u2019t know how to insert an SD card into the camera. Meanwhile, your dad is ready to dive into the swimming pool from the house roof. Your mom is calling you for help. All you need to do is to open the ManualsLib app, find the right manual and the page describing how to insert an SD card, and send the link to your mom. Don\u2019t forget to tell your mom to install the ManualsLib app. Now you\u2019ll have the unforgettable video of your dad jumping into the swimming pool!\r\n\r\n\ud83d\udda8 Print out pages  \r\nYou can print out any page of any manual and hang it anywhere, e.g. on the wall above the coffee machine in your office.\r\n\r\nManualsLib App is 100% synchronized with ManualsLib.com website profile",
    "descriptionHTML": "Find, view and read manual or user guide you need without creating an account.<br><br>With ManualsLib app, you can find any Owner&#39;s Manual or User&#39;s Guide you need, add it to \u201cMy Manuals\u201d list, and view it on your mobile device anytime.   <br><br>\ud83d\udd0e Search manuals and guides by device/product name.<br>To find the right manual or user guide, you just need to know the name of your device.<br>For example, to find a guide for Fitbit Alta, you need type \u201cFitbit Alta\u201d into the search bar and tap on \u201cSearch.\u201d In the search results, you\u2019ll see all documents available for this device.<br><br>\ud83c\udf9b Use search filters by type of document, manufacturer of device, and type of device. <br>ManualsLib is a major platform to search manuals and user guides. For many devices, ManualsLib offers different types of documents (user guides, installation instructions, fast start guides, spec lists, maintenance manuals, etc.). Use filters to search guides by type of document, manufacturer, and type of device. <br><br>\ud83d\udcc3 View manuals and guides without adding it to \u201cMy Manuals\u201d list <br>All manuals and guides are available for FREE and limitless viewing and reading. You can search and open any number of manuals.<br><br>\ud83d\udcc1 Add manuals and guides to \u201cMy Manuals\u201d list to view them offline<br>To be able to access manuals and user guides offline, you need to add them to your \u201cMy Manuals\u201d list. You\u2019ll be able to access your added files in the ManualsLib app even when you\u2019re not connected to the Internet.<br><br>\ud83d\uddc2 Create folders for easier access and storage <br>For easier access to your manuals, you can sort your documents by location and type of device. For example, you can create a \u201cSummer house manuals\u201d folder to store guides on all devices in your summer house. <br>Furthermore, you can create folders to store user manuals for certain devices, e.g. \u201ccars guides\u201d, \u201ccamera guides\u201d, \u201cappliance guides\u201d, etc. <br><br>\ud83d\udd0d Search inside a document<br>You can search inside the document for the information you need. Use simple key phrases, e.g. \u201cbattery charge\u201d instead of \u201chow to charge the battery.\u201d You need to be connected to the Internet to use the document search option.<br><br>\ud83d\udcc4 View Table of Contents for each document<br>Almost every manual available in ManualsLib contains a Table of Contents for easier navigation within the document.<br><br>\ud83d\udccc Create and name bookmarks <br>Bookmarks are the fastest way to access the page you need. When creating a bookmark, give it a short, descriptive name. <br>For example, the page that tells how to change oil in your quad bike can be named \u201cOil change.\u201d Avoid using long names, e.g. \u201cQuad oil change manual\u201d, as you\u2019ll be able to see the name of the manual in the bookmarks menu. <br><br>\u2709\ufe0f Share links to an entire document or its specific page<br>To your friends who haven\u2019t installed the ManualsLib app (or don\u2019t know the ManualsLib.com website), you can send a link to the entire manual or a single page.<br>Suppose, you gave your mom a new GoPro to record your dad\u2019s adventures. But your mom doesn\u2019t know how to insert an SD card into the camera. Meanwhile, your dad is ready to dive into the swimming pool from the house roof. Your mom is calling you for help. All you need to do is to open the ManualsLib app, find the right manual and the page describing how to insert an SD card, and send the link to your mom. Don\u2019t forget to tell your mom to install the ManualsLib app. Now you\u2019ll have the unforgettable video of your dad jumping into the swimming pool!<br><br>\ud83d\udda8 Print out pages  <br>You can print out any page of any manual and hang it anywhere, e.g. on the wall above the coffee machine in your office.<br><br>ManualsLib App is 100% synchronized with ManualsLib.com website profile",
    "summary": "2,700,000+ Owner's Manuals and Guides in one place, create your own collection",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1514644,
    "score": 4.5591397,
    "ratings": 11573,
    "reviews": 2651,
    "histogram": [
        559,
        226,
        372,
        1429,
        8979
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $4.49 per item",
    "developer": "ManualsLib.com",
    "developerId": "ManualsLib.com",
    "developerEmail": "feedback@manualslib.com",
    "developerWebsite": "https://www.manualslib.com/",
    "developerAddress": "Room 2303, New Tech Plaza, 34 Tai Yau Street, San Po Kong, Kowloon, Hong Kong",
    "privacyPolicy": "https://www.manualslib.com/app/pp.pdf",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/olmMAuXUw6tSX5jXqokua7DuZEVm97Sg6KcraOA44QO18z7LhNA0-_UtjkKl-iy7FQ4",
    "headerImage": "https://play-lh.googleusercontent.com/UteY6EPuvuWRU4IFLEHIx2UPYZbiDkfjewGSQvarYSkN5Uy9LTXu66lbxGf4q7VJdhf6",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Hgq2lk3LZPjcTN8up67f5FqBM-MHFWFJjWf5LG2HMg2fceJnePRqTAG7bwaYiNC9f7Q",
        "https://play-lh.googleusercontent.com/MF2CiYUCqBnEvNYr4nrvMWuyXXYv1tZXhcFnHGMzEwfK2NVNZmlHCa5VVlvngP5IP_FS",
        "https://play-lh.googleusercontent.com/BlBZkKdcnzOezoOQbiL0cmJVc46we4Xp2XOpEsM7hoYOgXykQS-i--TWEyQ_pW0o0E1w",
        "https://play-lh.googleusercontent.com/BnSk63C_C5VGCTY-UJeyyRr9nbdKhNtwinVZAjJqv_cLlPY2YtYXgRgrao5vYn0Yh0A",
        "https://play-lh.googleusercontent.com/5IlpwXAp1-qC6j-0eqknW46XR0jicPqjMxqUFVx1gk-Bgc_WLeJpS7RRWDkusLTmLldu",
        "https://play-lh.googleusercontent.com/UPNeotURl4BaQcc9r9LQCsJIlyCZtkcSpS3XSMFex1zbgCeUiZyCtIZxOJALxMO5dmo",
        "https://play-lh.googleusercontent.com/GowQ4MzeuikZy0IoJZahKuu8gGurKvaCS80oHHnJ3olPX_Pbh0m--7mqbnlLde4r4_k",
        "https://play-lh.googleusercontent.com/82azrk_ywc6_sJFtIY1ycoQd4YS09ffgcNVJ68W7bd8J7AsEauEzTb-kDHOdi_W6fw",
        "https://play-lh.googleusercontent.com/7HLQ2SfOjbZriO9RZWzQlMfS2uLPjndz3T0wBfS2IVcSvLC0Vn9_SWEXA2OdhgNcaQ",
        "https://play-lh.googleusercontent.com/Vw-6nIWFwSTxYOOskyzNmgAMi4F97PwnVuyq1MOWiutCH9LgnFJMt6PqH1N1zIYnD8o",
        "https://play-lh.googleusercontent.com/bnQo63KEQFklM0EtBqURgwkQ8GeTJOyYMrVmrzDkM15MWrUn8_t9HkjU93cfCgpbvMjs",
        "https://play-lh.googleusercontent.com/UXs1u8RjUaJBAz99Z8oLcqLchOR4IIOzyCtdfs2pdDFYVBa4TxWuPR63E6-d_diNQok",
        "https://play-lh.googleusercontent.com/oXIE9qD9s1DV7Ipvc-YhTN0dbAqeofh3etq8xfsH-MBUCxfpuW1NnRd-FmTn8nDYYDY",
        "https://play-lh.googleusercontent.com/bSoINyqlgotZ_ll-hZWISvO5dJZV7UuXg4oEshaCF6z-wwXVLt-YYPr6QErIhzI5PQ",
        "https://play-lh.googleusercontent.com/lRIXFHibqdl2nhKdSUpvl3_vxvvHEGm0cJxGhRMsgjHXvmsNxIc5xLA9-mzrMc3aXkQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 5, 2018",
    "lastUpdatedOn": "Jun 28, 2022",
    "updated": 1656414069,
    "version": "1.6.1",
    "comments": [],
    "appId": "com.manualslib.app",
    "url": "https://play.google.com/store/apps/details?id=com.manualslib.app&hl=en&gl=us"
}