{
    "title": "Huckleberry: Baby & Child",
    "description": "A one-stop baby & parenting app for all things baby and toddler. Need a newborn tracker or need to keep track of your child's activities, sleep & feeding? Our comprehensive solution provides you with a baby tracker, baby sleep guidance, and expert advice to help you navigate parenthood.\r\n\r\nSEE WHY OVER 3 MILLION PARENTS LOVE THE HUCKLEBERRY: BABY AND CHILD APP \r\n\r\nFREE CHILD & BABY TRACKER APP\r\n-Pumping tracker, with reminders, to track total amount and log output from each side.\r\n\r\n-Track bottle feeds or breastfeeding time , amounts and the last side you breast fed on.\r\n\r\n-Add notes to our solids tracker (baby food tracker) of all solids your baby has tried and their reactions to the foods.\r\n\r\n-Track potty activities (pee, poo, mixed or accidents) with our potty tracker.\r\n\r\n-Track medication, temperature, and growth.\r\n\r\n-Other features include: one-hand tracking, summary charts, cross-device syncing for multiple users, multiple child profiles, reminders, dark mode, and data export.\r\n\r\nHUCKLEBERRY PLUS\r\n-Make nap and bedtimes easier with the SweetSpot\u24c7 feature that predicts your child\u2019s next nap time like magic. No more wake window math. No more overtired babies: just better sleep.\r\n\r\n-Schedule Creator allows you to visualize your day by creating age-appropriate sleep schedules tailored for your child. Share your custom-made sleep schedules with other caregivers.\r\n\r\n-Enhanced reports for sleep (Wake Windows vs. SweetSpot, Rise and Bedtime) and solids (Allergens and Sensitivities).\r\n\r\nUNLOCK ALL FEATURES WITH HUCKLEBERRY PREMIUM\r\nHuckleberry Premium is like a sleep consultant in your pocket! Get everything in Huckleberry Plus, along with customized sleep plans created for you by one of our sleep consultants. Get personalized help on all sleep challenges, such as newborn day/night confusion, the dreaded four-month sleep regression, nap transitions and night wakings.\r\n\r\nHuckleberry blends the step-by-step guidance and advice of a traditional sleep consultant with the convenience of an app: no crying it out required. We\u2019ll give you easy-to-follow actionable guidance to get better sleep for the whole family. \r\n\r\nAWARDS\r\nOur Huckleberry parenting and baby tracker app has served 2MM+ families across 179 countries. Up to 93% of families who use Huckleberry baby tracker report improvement to their child's sleep.\r\n\r\nFinally - sleep guidance from baby sleep experts, expert advice, and an easy baby tracker, all in one app. No matter your sleep situation, Huckleberry can help.\r\n\r\nRead our outstanding reviews from thousands of parents, or visit our website to learn more: www.huckleberrycare.com \r\n\r\nHuckleberry Plus: $9.99/mo or $58.99/yr\r\nHuckleberry Premium: $14.99/mo or $119.99/yr. Includes one child\u2019s assessment per month.\r\n\r\nNote: All subscriptions auto-renew & can be canceled anytime with no penalty.\r\nPrices are in USD; pricing may vary in other countries, & actual charges may be converted to your local currency depending on the country of residence. Payment will be charged at confirmation of purchase. Subscription automatically renews unless canceled at least 24-hours before the end of the current period. Account will be charged for renewal within 24-hours prior to the end of the current period with the same term (monthly or annual) & same price. Subscriptions may be canceled in the Settings -> Huckleberry Memberships page in the app.\r\n\r\nTerms of Use: https://www.huckleberrycare.com/terms-of-use \r\nPrivacy Policy: https://www.huckleberrycare.com/privacy-policy",
    "descriptionHTML": "A one-stop baby &amp; parenting app for all things baby and toddler. Need a newborn tracker or need to keep track of your child&#39;s activities, sleep &amp; feeding? Our comprehensive solution provides you with a baby tracker, baby sleep guidance, and expert advice to help you navigate parenthood.<br><br>SEE WHY OVER 3 MILLION PARENTS LOVE THE HUCKLEBERRY: BABY AND CHILD APP <br><br>FREE CHILD &amp; BABY TRACKER APP<br>-Pumping tracker, with reminders, to track total amount and log output from each side.<br><br>-Track bottle feeds or breastfeeding time , amounts and the last side you breast fed on.<br><br>-Add notes to our solids tracker (baby food tracker) of all solids your baby has tried and their reactions to the foods.<br><br>-Track potty activities (pee, poo, mixed or accidents) with our potty tracker.<br><br>-Track medication, temperature, and growth.<br><br>-Other features include: one-hand tracking, summary charts, cross-device syncing for multiple users, multiple child profiles, reminders, dark mode, and data export.<br><br>HUCKLEBERRY PLUS<br>-Make nap and bedtimes easier with the SweetSpot\u24c7 feature that predicts your child\u2019s next nap time like magic. No more wake window math. No more overtired babies: just better sleep.<br><br>-Schedule Creator allows you to visualize your day by creating age-appropriate sleep schedules tailored for your child. Share your custom-made sleep schedules with other caregivers.<br><br>-Enhanced reports for sleep (Wake Windows vs. SweetSpot, Rise and Bedtime) and solids (Allergens and Sensitivities).<br><br>UNLOCK ALL FEATURES WITH HUCKLEBERRY PREMIUM<br>Huckleberry Premium is like a sleep consultant in your pocket! Get everything in Huckleberry Plus, along with customized sleep plans created for you by one of our sleep consultants. Get personalized help on all sleep challenges, such as newborn day/night confusion, the dreaded four-month sleep regression, nap transitions and night wakings.<br><br>Huckleberry blends the step-by-step guidance and advice of a traditional sleep consultant with the convenience of an app: no crying it out required. We\u2019ll give you easy-to-follow actionable guidance to get better sleep for the whole family. <br><br>AWARDS<br>Our Huckleberry parenting and baby tracker app has served 2MM+ families across 179 countries. Up to 93% of families who use Huckleberry baby tracker report improvement to their child&#39;s sleep.<br><br>Finally - sleep guidance from baby sleep experts, expert advice, and an easy baby tracker, all in one app. No matter your sleep situation, Huckleberry can help.<br><br>Read our outstanding reviews from thousands of parents, or visit our website to learn more: www.huckleberrycare.com <br><br>Huckleberry Plus: $9.99/mo or $58.99/yr<br>Huckleberry Premium: $14.99/mo or $119.99/yr. Includes one child\u2019s assessment per month.<br><br>Note: All subscriptions auto-renew &amp; can be canceled anytime with no penalty.<br>Prices are in USD; pricing may vary in other countries, &amp; actual charges may be converted to your local currency depending on the country of residence. Payment will be charged at confirmation of purchase. Subscription automatically renews unless canceled at least 24-hours before the end of the current period. Account will be charged for renewal within 24-hours prior to the end of the current period with the same term (monthly or annual) &amp; same price. Subscriptions may be canceled in the Settings -&gt; Huckleberry Memberships page in the app.<br><br>Terms of Use: https://www.huckleberrycare.com/terms-of-use <br>Privacy Policy: https://www.huckleberrycare.com/privacy-policy",
    "summary": "Smart Tracker & Sleep Experts. Improve your child & baby's sleep patterns!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1419769,
    "score": 4.8946137,
    "ratings": 22829,
    "reviews": 2938,
    "histogram": [
        131,
        131,
        264,
        933,
        21358
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$9.99 - $119.99 per item",
    "developer": "Huckleberry Labs",
    "developerId": "Huckleberry+Labs",
    "developerEmail": "support@huckleberry-labs.com",
    "developerWebsite": "http://www.huckleberrycare.com",
    "developerAddress": "15615 Alton Parkway, Suite 450, Irvine, CA 92618, USA",
    "privacyPolicy": "https://www.huckleberrycare.com/privacy-policy",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/9Au3cHvuVyNSGzikuifsilv4K3SZLH-OK7vU__LrK33aYCSnhRDk7lc2fXjGBBJaag",
    "headerImage": "https://play-lh.googleusercontent.com/gBPqvuyqSad29G4Dx-h60Pnft_IDv7YOCixRRfU7SgO9ufBPiNi-OtK7sW1HwhqFXIE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/g5dYmfqOL4dMXN6GlMDZxL92cmAbmk1dJBrAhoe0Fmxz0pGDjkcLLd_05txV4d6qdJ29",
        "https://play-lh.googleusercontent.com/BRVxTOOTWkgSDcaQ2ov3j8B4gMGkMjt0OiUsBVZdUgNQwIfPs5e_o17j43puxSzvhWrd",
        "https://play-lh.googleusercontent.com/UTZ6JyUgr2XFcpHMVGhZOWd3eGR0hvsvpJWlNZ2xOhHDEkJn54sBMoHculy6fSqOLxo",
        "https://play-lh.googleusercontent.com/nrCxywp4Z8uxr_NXLmQ-hwAcL1h7pJadBwNzl2-NNhDXHbRvBPJnlW8F9QkOg0cX5oXJ",
        "https://play-lh.googleusercontent.com/QltiARsiX1_ipdMZ1eCCru_7ro2a04VmjJrtM_XLGoE-26nLzXUKmJ4Pitj8PUfv8Q",
        "https://play-lh.googleusercontent.com/WLhnROlEx_0MuvQkiuzOPXCwennhYZ7JiqkLI0tVb4Dm2RIG3f_HX9YCfqx_RgUGbI0",
        "https://play-lh.googleusercontent.com/wzaouES6bfOoIcNvCT0o4CQvC58QPZB1pOyxu22Etu8qFmW57VmBwn0kLodLxHQSwjM",
        "https://play-lh.googleusercontent.com/VmpYxJ57fmmOY2eGIvnmmgHeZqXsh8sQmSUuUyydxaE3to88uK90wYWA4WIRjXedrnI",
        "https://play-lh.googleusercontent.com/H1oOkfb7fsIAQs8iTu0GYiLbDiVXKDIGXzOrAH6j3oGhG58ptdhu15yyZe8hU8e_iQ",
        "https://play-lh.googleusercontent.com/OlLz_wsckVp8KNICo7s24_sb45taBxZNMoRkh4VJ0edC7EbalnksbP05fvpFD4epyw",
        "https://play-lh.googleusercontent.com/0xRCwuDU5SX9wRmr2xqFlYsCoFq-Lc9dHBUpY0xQ6qH080hkqdeWhCgScGHeF7iw6Q",
        "https://play-lh.googleusercontent.com/nQkwyrsd77Hdo9uI_RP53_98Z6Wu0cIRBCLxBmn9-AvQJMKg8sr1M388XbtakyYm19o",
        "https://play-lh.googleusercontent.com/Pl7X2Z8W82OwCvROtjp_gqDiHArvS-KYI-NE7D-posti1JSKiJG94ZUpmV4NfsQBsw",
        "https://play-lh.googleusercontent.com/TajyRi-Nkrd-6XC7GU26HUglfSW9LcKZDnBh-quNsHbs3WiaZJeFys-J1Jcw9cekTEw",
        "https://play-lh.googleusercontent.com/D3wQ9vaWnEF7giJpyyNcuQZjL1UmZzvcp1K8gl5itn3JElLBbNVSoiXh5jWm-dOmxIzj",
        "https://play-lh.googleusercontent.com/x2l1_pAUQoIxHlVD0RS-M9Bs94vEZtapDYTqEwwhyIyYJAO7MMFpVO5L4Wyf7UR46fs",
        "https://play-lh.googleusercontent.com/o9D-e5SC8LfCtDcxr_rkcs4_OB62eFao99cdWf1aR6WdfU33WTTaNdPrEC83JJZ0XOY",
        "https://play-lh.googleusercontent.com/OzP_1efmvDI3Atah7n1OWmPzBwfgwhmof9sGB9-KZPDUiSfc_shvSkr3uG9jWY8BNNM",
        "https://play-lh.googleusercontent.com/9dwUucjrj2gsebj3QBYFYw50saSRaeyzspNU5oOx8ofz-FMUgi9fo-wRqMikJA_uzQ",
        "https://play-lh.googleusercontent.com/y7TO_R52i9uotozVSliA761B1nagKJA8yHXyaEIFzKkUcnZkKu04Hen-meBenkzfqfA",
        "https://play-lh.googleusercontent.com/NWbk7_emTbGv-iQMeWvffML9HNF_dSbmPAqtfMSdoIUnNi90lL1hTcLL_ba7LAk8qYA",
        "https://play-lh.googleusercontent.com/TIliWAhKt6do78LbDPE9HL-Eo2HHfdm6lYnJF68CpAwGI9LL93FxdAodldZkYiVH4cI",
        "https://play-lh.googleusercontent.com/TdOML81TLhcZj1IJRVhNF4zmPM2t0mBpybbSy5PFIcDl-keze0uewcj4gvNiC2-jmJ8",
        "https://play-lh.googleusercontent.com/Q6LITmWdGgqwZVehDKNVSo9Hb35Cb4zF4hEa4zfNiATkajgJ1Eu1fNKfFG1yIZ5YNGzR"
    ],
    "video": "https://www.youtube.com/embed/JG3BzUSbU1w?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/gBPqvuyqSad29G4Dx-h60Pnft_IDv7YOCixRRfU7SgO9ufBPiNi-OtK7sW1HwhqFXIE",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 30, 2017",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729519314,
    "version": "0.9.243",
    "comments": [],
    "appId": "com.huckleberry_labs.app",
    "url": "https://play.google.com/store/apps/details?id=com.huckleberry_labs.app&hl=en&gl=us"
}