{
    "title": "Paris Baguette",
    "description": "The Paris Baguette Rewards App makes ordering our delicious pastries, warm breads, stunning cakes, and expertly brewed beverages a joyful experience all while earning points on your purchases with PB Rewards. \r\n\r\nFeatures of the new app:\r\n-\tEnjoy a free pastry with your first purchase when you sign up for PB Rewards \r\n-\tFind a caf\u00e9 nearest you\r\n-\tOrder pick up or delivery\r\n-\tSchedule orders in the future\r\n-\tEarn 1 point for every $1 spent\r\n-\tBank your points toward free pastries, beverages, cake, and more\r\n-\tEnjoy monthly PB Rewards exclusive offers\r\n-\tComplete challenges for bonus points \r\n-\tLoad and store gift cards for easy payment\r\n-\tEmail e-gift cards to friends or family\r\n-\tBe first to know what\u2019s new and upcoming at PB\r\n-\tView purchase and earning history\r\n-\tQuickly reorder from past or favorited orders",
    "descriptionHTML": "The Paris Baguette Rewards App makes ordering our delicious pastries, warm breads, stunning cakes, and expertly brewed beverages a joyful experience all while earning points on your purchases with PB Rewards. <br><br>Features of the new app:<br>-\tEnjoy a free pastry with your first purchase when you sign up for PB Rewards <br>-\tFind a caf\u00e9 nearest you<br>-\tOrder pick up or delivery<br>-\tSchedule orders in the future<br>-\tEarn 1 point for every $1 spent<br>-\tBank your points toward free pastries, beverages, cake, and more<br>-\tEnjoy monthly PB Rewards exclusive offers<br>-\tComplete challenges for bonus points <br>-\tLoad and store gift cards for easy payment<br>-\tEmail e-gift cards to friends or family<br>-\tBe first to know what\u2019s new and upcoming at PB<br>-\tView purchase and earning history<br>-\tQuickly reorder from past or favorited orders",
    "summary": "Welcome to the NEW PB Rewards and Mobile App Experience!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 128744,
    "score": 4.7828283,
    "ratings": 1968,
    "reviews": 333,
    "histogram": [
        29,
        19,
        49,
        148,
        1719
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Paris Baguette America",
    "developerId": "Paris+Baguette+America",
    "developerEmail": "davelazaro@parisbaguette.com",
    "developerWebsite": "http://www.parisbaguette.com",
    "developerAddress": null,
    "privacyPolicy": "https://parisbaguette.com/privacy-policy/",
    "genre": "Food & Drink",
    "genreId": "FOOD_AND_DRINK",
    "categories": [
        {
            "name": "Food & Drink",
            "id": "FOOD_AND_DRINK"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Ez8j5tCLk79fMorlbz_66g9w5j51ySaRJgm1w8g_8dDn_0fKL_1dYuZKkxK-eAsFetA",
    "headerImage": "https://play-lh.googleusercontent.com/VBicuD23JEjRdD5GYIamkJvSs-_nZs-McoZ9WzKAKzgFcaU0SyUxhvoSGQDgxPCwOg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/60vHoW7eka7lr_fHhv6BMtsA9h73zZDBOFpv4G_Z8Q2t1XfgA-NE9qvt_Bba-YNQras",
        "https://play-lh.googleusercontent.com/NKj8mefoJ-x_ieq0rYxcx6y5DLjpmPn0try1E5P54Gb1n4r6x41m3cljNdOZvp-euQKe",
        "https://play-lh.googleusercontent.com/gwstX0SgyCAZdpwiGiegfArXZNIHBb6keZJZBDvyIxiEIuqAdFegtq_Ae6fanrnlVp0",
        "https://play-lh.googleusercontent.com/SJQ9TW0J8jxnCov2G6GUQMU8GhTu0uJFiIhNPml-tMWBuwCjE97fvWQ4yWVJTy8iaJw",
        "https://play-lh.googleusercontent.com/Pojk0-vPIx_JdupXnJ73xb9CxIoMvhwC7Ao4o_KFvebusyEG4AmsHC67FoPPh30tMg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 7, 2019",
    "lastUpdatedOn": "Oct 7, 2024",
    "updated": 1728297060,
    "version": "3.2",
    "comments": [],
    "appId": "com.parisbaguette.app",
    "url": "https://play.google.com/store/apps/details?id=com.parisbaguette.app&hl=en&gl=us"
}