{
    "title": "Lingvano: Sign Language - ASL",
    "description": "Join 1.5 million people and learn ASL with the most popular ASL learning app in the world!\r\n\r\nLingvano teaches sign language for beginners through video lessons made by deaf teachers that can be done anywhere, anytime. You'll have fun learning the basics and start signing from your very first lesson. With just 10 minutes/day of practice, you'll be conversational in no time at all!\r\n\r\n<b>ASL learning made easy:</b>\r\n<b>\u2713 <font color=\"#F9B233\">Practical conversation skills</font></b>\r\nImmerse yourself in American Sign Language learning hands-on through interactive and useful dialogs that get you conversational fast.\r\n<b>\u2713 <font color=\"#F18736\">Remember what you've learned</font></b>\r\nUse our vocabulary trainer to reinforce your memory and retain your learnings for the long term.\r\n<b>\u2713 <font color=\"#EA4F3A\">ASL Dictionary</font></b>\r\nWant to look up a specific sign or sentence? No problem - our ASL dictionary for American Sign Language learning for beginners has got you covered.\r\n<b>\u2713 <font color=\"#F9B233\">Sign with confidence</font></b>\r\nUnsure whether you are signing the right way? Refine your execution with the Lingvano Sign Language learning mirror and gain the confidence to sign! Learn sign language fast and easy!\r\n\r\n<b>All of the ASL learning teachers</b> at Lingvano <b>are Deaf</b> and share a strong passion for teaching American Sign Language (ASL) for beginners.\r\n\r\n<b><font color=\"#F9B233\">Our mission</font> is to <font color=\"#F18736\">help you connect with</font> <font color=\"#EA4F3A\">Deaf family members, friends, colleagues, and neighbors</font></b>. Help to build bridges with American Sign Language (ASL) and start learning! Learn sign language fast and easy!\r\n\r\n------------------------------\r\n\r\nIf you enjoy sign language learning with the Lingvano ASL learning app for beginners, you can purchase a <b>premium subscription</b> to unlock all learning content and features.\r\n\r\nYour subscription will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current payment period. Your account will be automatically charged at the same price for renewal within the 24-hour-hour period prior to the end of the current payment period unless you change your subscription preferences.\r\n\r\n<b>Subscription options:</b>\r\n- 1 month\r\n- 3 months\r\n- 12 months",
    "descriptionHTML": "Join 1.5 million people and learn ASL with the most popular ASL learning app in the world!<br><br>Lingvano teaches sign language for beginners through video lessons made by deaf teachers that can be done anywhere, anytime. You&#39;ll have fun learning the basics and start signing from your very first lesson. With just 10 minutes/day of practice, you&#39;ll be conversational in no time at all!<br><br><b>ASL learning made easy:</b><br><b>\u2713 <font color=\"#F9B233\">Practical conversation skills</font></b><br>Immerse yourself in American Sign Language learning hands-on through interactive and useful dialogs that get you conversational fast.<br><b>\u2713 <font color=\"#F18736\">Remember what you&#39;ve learned</font></b><br>Use our vocabulary trainer to reinforce your memory and retain your learnings for the long term.<br><b>\u2713 <font color=\"#EA4F3A\">ASL Dictionary</font></b><br>Want to look up a specific sign or sentence? No problem - our ASL dictionary for American Sign Language learning for beginners has got you covered.<br><b>\u2713 <font color=\"#F9B233\">Sign with confidence</font></b><br>Unsure whether you are signing the right way? Refine your execution with the Lingvano Sign Language learning mirror and gain the confidence to sign! Learn sign language fast and easy!<br><br><b>All of the ASL learning teachers</b> at Lingvano <b>are Deaf</b> and share a strong passion for teaching American Sign Language (ASL) for beginners.<br><br><b><font color=\"#F9B233\">Our mission</font> is to <font color=\"#F18736\">help you connect with</font> <font color=\"#EA4F3A\">Deaf family members, friends, colleagues, and neighbors</font></b>. Help to build bridges with American Sign Language (ASL) and start learning! Learn sign language fast and easy!<br><br>------------------------------<br><br>If you enjoy sign language learning with the Lingvano ASL learning app for beginners, you can purchase a <b>premium subscription</b> to unlock all learning content and features.<br><br>Your subscription will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current payment period. Your account will be automatically charged at the same price for renewal within the 24-hour-hour period prior to the end of the current payment period unless you change your subscription preferences.<br><br><b>Subscription options:</b><br>- 1 month<br>- 3 months<br>- 12 months",
    "summary": "Sign language for beginners. Learn ASL in just 10 minutes/day of practice!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1437505,
    "score": 4.7564487,
    "ratings": 47656,
    "reviews": 4566,
    "histogram": [
        801,
        542,
        1189,
        4386,
        40733
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$17.99 - $134.99 per item",
    "developer": "Lingvano",
    "developerId": "7199715300225587527",
    "developerEmail": "support@lingvano.com",
    "developerWebsite": "https://www.lingvano.com/",
    "developerAddress": "Lingvano GmbH\nSieveringer Stra\u00dfe 72\n1190 Wien",
    "privacyPolicy": "https://www.lingvano.com/asl/privacy-policy/",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/JAWwZjG3pkVzTbR_MImfP1hJ65UDZTbvRlo7dm85tQWzbpNuL9z0LgXTBjEvkdTlTpw",
    "headerImage": "https://play-lh.googleusercontent.com/ndZ3m5j7mvpauxR100O37ZeFk82GwM3g0T7zC6jAK2QScXA7B8UlrLRdBpSFllXU74w",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Wg4ecU5IAlGVli3TO3f7A0_4hU1Q-6lOhxm0Fubt6L7ihC1dl6ZOuU2IbDa38n03aj8",
        "https://play-lh.googleusercontent.com/2BpLs9rqnTmyTaN7-7_xB03EPP-rE6EyarZc_kYOV0ye-rLOyvfw70K0b5oyvWIKSoa1",
        "https://play-lh.googleusercontent.com/ukV7JnfmZYh7izXBwZvL3rQqqbnwuCusFbr-oWGyWaVrDHUG0NK4gLWURqhPe8taqixQ",
        "https://play-lh.googleusercontent.com/OG-q06veftkim5X5UcCVHbA_Ks6IRcZWLfN9D0e3edFAffuexjXOFiSnf3YHyvEhpQ",
        "https://play-lh.googleusercontent.com/vyf9W5BcRzJSIZKCELwJP7CJD2XWAcQYlJdJhlY1GepIYYxTENij86iybJbDVKj7j1o_",
        "https://play-lh.googleusercontent.com/snuD5NPEszgQlsaWPLA4K8o6oizBpgjBpLJR-clp5UqzvEgmjd-d5Sp8d8ETGsAf4ug",
        "https://play-lh.googleusercontent.com/KAWuzRowNRlmwTc01omviTvQAjpunScd3gwuUKyNxFzZ8jmX4peGJvqyqt3u1dyz1lQ",
        "https://play-lh.googleusercontent.com/DwuyL0Zp2H4-zLsfBEOfrFt4JsTl81DBwmigY87l2Rd5GErTUpbuPNMfBQJJwsfm-w",
        "https://play-lh.googleusercontent.com/6bggc-JA2Z7TRRthFsFeQYZT1mrzWB50IIQHQ2Fkrl14rnPn03SDZ_GcpYEw06Gl0z-L",
        "https://play-lh.googleusercontent.com/Mmb65nSSrGm7NS5Deyg4nN11wgjRGUSp14JXDcqh6pxwBG5ZuG5xQqhfET6ND6BTI34",
        "https://play-lh.googleusercontent.com/pIshu665Jbz1F5CJmJPXOEFM6q_bEwoEZjquCAyh8hqzpTrVOzg5afWkTnWukS1TN20",
        "https://play-lh.googleusercontent.com/pKCk9vqWQvJMakh583jxg1haaOISrItZ8sYsOSpvo5CUBrnQEtY3J61Gfw7LmhOgCw",
        "https://play-lh.googleusercontent.com/CHYd1Qg2J_ltiERR3w49ad69xK67gZDDllkmYA4p0Ul6TYZbYeSVCFX74Tk0R823z3ZZ",
        "https://play-lh.googleusercontent.com/4cA4iMWkOdz65JOQhSIgEXnxGaDukKWnUZQYJ7SG5NCtavbnNTbzbD-1IkAy9EckMkpM",
        "https://play-lh.googleusercontent.com/XpGqgiaohs4BRQWBHyeygKYc-Q0mFJW2CjgVSknQNjeAV-xxEf5dEc2nVL1XwPB5f9Rh",
        "https://play-lh.googleusercontent.com/weQHBn8x5C1liq7pmwYhY6ONLLj5tz7H2reqiqb0LsGTrpl2u1wuNE5hLyp6ub1K9g",
        "https://play-lh.googleusercontent.com/2Wzsg6lrxDEwsY4DvaP8TLUxQeoqyX0WHYXw0TzbrzYWkaX7W8NcNGRrdjxuIr0nYA",
        "https://play-lh.googleusercontent.com/8iY_VZNscvQ461V4I3NatuZm0IgHp1xiIX7XKQQPPzGArxsLm_wLzRKcTWNiEmtvVA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 11, 2021",
    "lastUpdatedOn": "Sep 30, 2024",
    "updated": 1727700917,
    "version": "3.2.1",
    "comments": [],
    "appId": "com.lingvano.app",
    "url": "https://play.google.com/store/apps/details?id=com.lingvano.app&hl=en&gl=us"
}