{
    "title": "PepTalk: Daily Motivation App",
    "description": "Use PepTalk for your daily motivational videos, quotes, and positive affirmations to start your day right. With over 5000+ videos & playlists, along with daily quotes and widgets, PepTalk gives you a daily boost of inspiration and motivation allowing you to stay focused and perform at your best.\r\n\r\nSTRONG MOTIVATION AND A POSITIVE MINDSET BRING FOCUS & PRODUCTIVITY TO DAILY LIFE\r\n\r\nIt\u2019s no secret that watching daily motivational videos, practicing daily affirmations, and reading motivating quotes can help you develop a better mindset to help overcome hardships in life and work.\r\n\r\nWith PepTalk, get your pep talks and:\r\n\u25c8 Improve focus and productivity\r\n\u25c8 Boost your mindset and discipline\r\n\u25c8 Accomplish personal or business goals\r\n\u25c8 Learn and manifest your intelligence\r\n\u25c8 Combat fear and anxiety\r\n\u25c8 Motivate, encourage & support yourself\r\n\u25c8 Overcome temptations, depression, and addictions\r\n\u25c8 Crush fitness & workout challenges\r\nAnd more!\r\n\r\nWE GIVE PEP TALKS, YOU GET THINGS DONE\r\n\r\nOur goal is to help motivate, guide and inspire you in different ways with a simple app, PepTalk. Through curated lists of motivational videos, audio, podcasts, and inspirational quotes, PepTalk motivates your mind to get through all obstacles throughout the day.\r\n\r\nWith PepTalk, you can develop a positive mindset, and feel inspiration and motivation to pursue your dreams.\r\n\r\nGet life-changing pep talks with PepTalk on the following topics:\r\n\u00a7 Motivation\r\n\u00a7 Daily Affirmations\r\n\u00a7 Inspirational quotes\r\n\u00a7 Happiness / Gratitude\r\n\u00a7 Fitness / Workout\r\n\u00a7 Overcoming challenges / Goals\r\n\u00a7 Self-improvement\r\n\u00a7 Intelligence / Reflection\r\n\u00a7 Productivity / Self-improvement\r\n\u00a7 Self-care\r\n\u00a7 Self-talks\r\n\u00a7 Mental health\r\nPlus many more for you to explore!\r\n\r\nEASY TO USE, QUICK TO BENEFIT\r\n\r\nSometimes hard decisions can be made and great achievements can be unlocked with just the right mindset. Here\u2019s how to start:\r\n\u25ba Download PepTalk\r\n\u25ba Open it, and choose a topic\r\n\u25ba Select motivational videos & playlists to give you a mental boost or emotional support\r\n\u25ba Start watching or listening to your daily pep talk\r\n\u25ba Get motivated with daily quotes and affirmations\r\n\u25ba You can listen on the go as well!\r\n\r\nPepTalk is your daily guide to self-improvement and self-care, offering curated lists of inspirational videos, quotes & positive affirmations, audio, podcasts, and speeches that will motivate you and inspire your mind every day of your life.\r\nIt's like having Tony Robbins and David Goggins in your pocket, guiding you with their life advice on self-improvement.\r\n\r\nWHAT\u2019S BETTER THAN PEPTALK? ANSWER: PEPTALK PREMIUM SUBSCRIPTION!\r\n\r\nSubscribe today to PepTalk Elite to get the following perks and benefits:\r\n\u25ac Unlimited access to original videos\r\n\u25ac Unlimited access to thousands of motivational audio & podcasts\r\n\u25ac Thousands of quotes with original themes & curated categories\r\n\u25ac Daily reminders to start your day with positive affirmations\r\n\u25ac Daily alarm to wake up inspired\r\n\u25ac Offline Listening\r\n\r\nSubscription pricing and terms:\r\nTo access the Peptalk Elite content and features, you can choose between a monthly ($5.99/mo) or yearly ($35.99/y with a 3-day free trial) auto-renewable subscription. Payment will be charged to your iTunes Account at confirmation of purchase. Monthly and yearly subscriptions will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Account will be charged for renewal within 24 hours before the end of the current period. Subscriptions can be managed and auto-renewal can be turned off by going to your iTunes Account Settings after purchase. Any unused portion of the free trial will be forfeited if you purchase a subscription.\r\n\r\nFEEDBACK & SUPPORT\r\n\u2295 If you like PepTalk, don\u2019t hesitate to rate us on the App Store!\r\n\u2295 If you have any questions, feedback, suggestions, or simply want to say \u201cHi!\u201d, feel free to contact us at hi@peptalkapp.com\r\n\r\nLEGAL\r\nTerms of Use: https://peptalkapp.com/terms\r\nPrivacy Policy: https://peptalkapp.com/privacypolicy",
    "descriptionHTML": "Use PepTalk for your daily motivational videos, quotes, and positive affirmations to start your day right. With over 5000+ videos &amp; playlists, along with daily quotes and widgets, PepTalk gives you a daily boost of inspiration and motivation allowing you to stay focused and perform at your best.<br><br>STRONG MOTIVATION AND A POSITIVE MINDSET BRING FOCUS &amp; PRODUCTIVITY TO DAILY LIFE<br><br>It\u2019s no secret that watching daily motivational videos, practicing daily affirmations, and reading motivating quotes can help you develop a better mindset to help overcome hardships in life and work.<br><br>With PepTalk, get your pep talks and:<br>\u25c8 Improve focus and productivity<br>\u25c8 Boost your mindset and discipline<br>\u25c8 Accomplish personal or business goals<br>\u25c8 Learn and manifest your intelligence<br>\u25c8 Combat fear and anxiety<br>\u25c8 Motivate, encourage &amp; support yourself<br>\u25c8 Overcome temptations, depression, and addictions<br>\u25c8 Crush fitness &amp; workout challenges<br>And more!<br><br>WE GIVE PEP TALKS, YOU GET THINGS DONE<br><br>Our goal is to help motivate, guide and inspire you in different ways with a simple app, PepTalk. Through curated lists of motivational videos, audio, podcasts, and inspirational quotes, PepTalk motivates your mind to get through all obstacles throughout the day.<br><br>With PepTalk, you can develop a positive mindset, and feel inspiration and motivation to pursue your dreams.<br><br>Get life-changing pep talks with PepTalk on the following topics:<br>\u00a7 Motivation<br>\u00a7 Daily Affirmations<br>\u00a7 Inspirational quotes<br>\u00a7 Happiness / Gratitude<br>\u00a7 Fitness / Workout<br>\u00a7 Overcoming challenges / Goals<br>\u00a7 Self-improvement<br>\u00a7 Intelligence / Reflection<br>\u00a7 Productivity / Self-improvement<br>\u00a7 Self-care<br>\u00a7 Self-talks<br>\u00a7 Mental health<br>Plus many more for you to explore!<br><br>EASY TO USE, QUICK TO BENEFIT<br><br>Sometimes hard decisions can be made and great achievements can be unlocked with just the right mindset. Here\u2019s how to start:<br>\u25ba Download PepTalk<br>\u25ba Open it, and choose a topic<br>\u25ba Select motivational videos &amp; playlists to give you a mental boost or emotional support<br>\u25ba Start watching or listening to your daily pep talk<br>\u25ba Get motivated with daily quotes and affirmations<br>\u25ba You can listen on the go as well!<br><br>PepTalk is your daily guide to self-improvement and self-care, offering curated lists of inspirational videos, quotes &amp; positive affirmations, audio, podcasts, and speeches that will motivate you and inspire your mind every day of your life.<br>It&#39;s like having Tony Robbins and David Goggins in your pocket, guiding you with their life advice on self-improvement.<br><br>WHAT\u2019S BETTER THAN PEPTALK? ANSWER: PEPTALK PREMIUM SUBSCRIPTION!<br><br>Subscribe today to PepTalk Elite to get the following perks and benefits:<br>\u25ac Unlimited access to original videos<br>\u25ac Unlimited access to thousands of motivational audio &amp; podcasts<br>\u25ac Thousands of quotes with original themes &amp; curated categories<br>\u25ac Daily reminders to start your day with positive affirmations<br>\u25ac Daily alarm to wake up inspired<br>\u25ac Offline Listening<br><br>Subscription pricing and terms:<br>To access the Peptalk Elite content and features, you can choose between a monthly ($5.99/mo) or yearly ($35.99/y with a 3-day free trial) auto-renewable subscription. Payment will be charged to your iTunes Account at confirmation of purchase. Monthly and yearly subscriptions will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Account will be charged for renewal within 24 hours before the end of the current period. Subscriptions can be managed and auto-renewal can be turned off by going to your iTunes Account Settings after purchase. Any unused portion of the free trial will be forfeited if you purchase a subscription.<br><br>FEEDBACK &amp; SUPPORT<br>\u2295 If you like PepTalk, don\u2019t hesitate to rate us on the App Store!<br>\u2295 If you have any questions, feedback, suggestions, or simply want to say \u201cHi!\u201d, feel free to contact us at hi@peptalkapp.com<br><br>LEGAL<br>Terms of Use: https://peptalkapp.com/terms<br>Privacy Policy: https://peptalkapp.com/privacypolicy",
    "summary": "Inspirational & Motivational Videos, Daily Quotes, and Positive Affirmations!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 288424,
    "score": 4.7120824,
    "ratings": 8453,
    "reviews": 239,
    "histogram": [
        281,
        21,
        260,
        715,
        7169
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $299.99 per item",
    "developer": "Dark Knight Inc.",
    "developerId": "Dark+Knight+Inc.",
    "developerEmail": "info@peptalkapp.com",
    "developerWebsite": "https://peptalkapp.com",
    "developerAddress": "1065 SW 8th St, Unit 288\nMiami, FL 33130",
    "privacyPolicy": "https://peptalkapp.com/privacypolicy",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/CDJa6YMzxjzXqM8_Sd1JaTLFDaEBf1K4uEhxs0Heavs9iDDp3ueu8nIsczQH216jMlzc",
    "headerImage": "https://play-lh.googleusercontent.com/aZL2f2U8YCstvf9_GLaRSQUaEptAIXVJURPeYJNnCcTJT4eSqoPP3kN6XXLppHGzq1c",
    "screenshots": [
        "https://play-lh.googleusercontent.com/-m09PCH3limQflHAETb1Hch6JytB4oez4M96H2NCisTXOU4UDI_WRyeLNy5w_eJHTII",
        "https://play-lh.googleusercontent.com/uHxCzsdtklZdGkC3zw00ZVPU-c9_ZD3rMB4wCRfAv9NpAr3ELzx3tUC5stLxY3zXqfc",
        "https://play-lh.googleusercontent.com/EnGFsudxfR4_EJHS0f-Qd0gLm7edhsPXXj7-C4OkhM2yXDRUUoExNCvUThNC4JCj3Cg",
        "https://play-lh.googleusercontent.com/If8TDfDkHjoDb4phR2cyTKbmAHxEU2bkx9KWhiTKZMRRdkocy3-9hhSHib3dZqrfZ6A",
        "https://play-lh.googleusercontent.com/iTM5wkITYOQ1bBlWu8Yfi2eiP0nYkWxk2G2NVn820MxiG7XddBOGh1RYUcRjIx29x8c",
        "https://play-lh.googleusercontent.com/EVBvB_dTA5Fh1abXOmLaMVig6_R3znt-pMAqQmlwWlnmGkHR23L0Pq4UHW3tQxNJpmcT",
        "https://play-lh.googleusercontent.com/bQ7TSs0wRipSqEio_UUcgRj0IRtmPQg_ncw-MxKR7TuZLfabVDlsk6DquUDcClxr",
        "https://play-lh.googleusercontent.com/QOyXMeA_TJUbfMYhFV_06nd1fh9wXCDBSlNEr_bTEmDdderVSx4NLwDpuDoQIWe1Vj8"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 16, 2021",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729078318,
    "version": "2.19.19",
    "comments": [],
    "appId": "com.peptalk.app",
    "url": "https://play.google.com/store/apps/details?id=com.peptalk.app&hl=en&gl=us"
}