{
    "title": "Arlo Secure: Home Security",
    "description": "Protect your everything with Arlo\u2019s award-winning smart home security system, video doorbells, cameras, and floodlight. Control your home security from anywhere with one, easy-to-use app to protect your home, inside and out.\r\n\r\nPersonalize your entire home security camera system with the Arlo Secure App. Control multiple locations at once and quickly arm or disarm your system with one tap in modes.  \r\n\r\nGet round-the-clock protection with 24/7 Live Security Experts that will monitor your home, so you don\u2019t have to or use one tap Emergency Response to quickly get police, fire, or medical help to your home.* Easily customize your security by creating activity zones to reduce unwanted notifications** and set schedules to arm or disarm your system. \r\n\r\nWith an Arlo Secure plan and Arlo camera, doorbell or floodlight camera, you can also view 30 days of video and missed event details so you can review past activity. Receive notifications that tell you when a person, package, vehicle, or animal has been spotted with advanced AI Object Detection.* \r\n\r\n--Smart Home Security \r\nBring your home security to the next level with new tools and features in our security camera app. Personalize your home security system with the Arlo Secure App - control multiple locations at once, arm and disarm your system based on schedules you create, review missed event details with Feeds, and control your entire smart home security system with one app. \r\n\r\n--Manage Your Home Security in one Place \r\nInstantly know the status of your home and manage your home security in one place with a customizable Dashboard. See video from recorded events, arm or disarm your security system, and access Emergency Response, right from your phone. \r\n\r\n--Disclaimers:  \r\n* Emergency Response (available in the United States only), Object Detection and Video History require an Arlo Secure paid plan after trial period. \r\n** Activity Zones feature varies by camera model and requires an Arlo Secure paid plan after trial period..",
    "descriptionHTML": "Protect your everything with Arlo\u2019s award-winning smart home security system, video doorbells, cameras, and floodlight. Control your home security from anywhere with one, easy-to-use app to protect your home, inside and out.<br><br>Personalize your entire home security camera system with the Arlo Secure App. Control multiple locations at once and quickly arm or disarm your system with one tap in modes.  <br><br>Get round-the-clock protection with 24/7 Live Security Experts that will monitor your home, so you don\u2019t have to or use one tap Emergency Response to quickly get police, fire, or medical help to your home.* Easily customize your security by creating activity zones to reduce unwanted notifications** and set schedules to arm or disarm your system. <br><br>With an Arlo Secure plan and Arlo camera, doorbell or floodlight camera, you can also view 30 days of video and missed event details so you can review past activity. Receive notifications that tell you when a person, package, vehicle, or animal has been spotted with advanced AI Object Detection.* <br><br>--Smart Home Security <br>Bring your home security to the next level with new tools and features in our security camera app. Personalize your home security system with the Arlo Secure App - control multiple locations at once, arm and disarm your system based on schedules you create, review missed event details with Feeds, and control your entire smart home security system with one app. <br><br>--Manage Your Home Security in one Place <br>Instantly know the status of your home and manage your home security in one place with a customizable Dashboard. See video from recorded events, arm or disarm your security system, and access Emergency Response, right from your phone. <br><br>--Disclaimers:  <br>* Emergency Response (available in the United States only), Object Detection and Video History require an Arlo Secure paid plan after trial period. <br>** Activity Zones feature varies by camera model and requires an Arlo Secure paid plan after trial period..",
    "summary": "Smart home security protection",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 5710130,
    "score": 3.1914546,
    "ratings": 158756,
    "reviews": 53937,
    "histogram": [
        45680,
        17736,
        15951,
        19277,
        60106
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$9.99 - $299.99 per item",
    "developer": "Arlo Technologies, Inc",
    "developerId": "Arlo+Technologies,+Inc",
    "developerEmail": "appsupport@arlo.com",
    "developerWebsite": "http://support.arlo.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.arlo.com/en-us/about/privacy-policy/",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/4BIUELdP80ereYzRJh0s1QrmLksL35zNbAVDXkXp5C915MRq3rUxie84EAx7F0a6djXQ",
    "headerImage": "https://play-lh.googleusercontent.com/dK75x-7uL4PvvzI2mJOZGRa5ukn96_lxORb-gvVZDqCleqrjnX-6_raEpq-E5OiGz5A",
    "screenshots": [
        "https://play-lh.googleusercontent.com/l2EkzpAnN0W5NYAA36PpRLplwDjxagdY2a-XVLU3p7J4f7gU7h8gydQcBKg_NQKeFJc",
        "https://play-lh.googleusercontent.com/5UlH5aZBQflV7g9Lvoar4hDajadK_iv0-fSahy2AeQN6HPu2CbYqLTlBGQegKmv_lg",
        "https://play-lh.googleusercontent.com/pRFyhcHj6otMpiIu4CwX9eWkvmfeLWCBAta2nwWM-q5NxGXhqSN3J6Ns1eGtrB7WSg",
        "https://play-lh.googleusercontent.com/YaKqC-bQeAeUrtjcOy9tCSobo_bcuVSk-oYYGllQxS9yaVyO4NweIaq5eHaZk1nf_m4",
        "https://play-lh.googleusercontent.com/BLR-rvL1AGfd0Bcf9UdOOqbn_yiZABFVQjCzmwjAe0dKOSSr9z3MY2mY2fNEPLP_Gzst",
        "https://play-lh.googleusercontent.com/DLZE3lwmvkOkcclI4ccWgQzs8_dNSF29wDDeg3VyknCrEJbqtdBqQXeEKEZiynAVS5s",
        "https://play-lh.googleusercontent.com/TLLmcuQ6cVfEeYen2NuGgblGq3Dtr2oSc7CVZePgQ86mIQridaluzUvqGW45bqEFWw",
        "https://play-lh.googleusercontent.com/Eq4QEPlcJF0AERziEBuOuzHOvLsyPPzkkUO9ZucrRD-ADREi1n5uPNrZdqGOyFZGc2g"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 4, 2019",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729528132,
    "version": "5.0.3_28739",
    "comments": [],
    "appId": "com.arlo.app",
    "url": "https://play.google.com/store/apps/details?id=com.arlo.app&hl=en&gl=us"
}