{
    "title": "Gridwise: Gig-Driver Assistant",
    "description": "Take your Gig work to the next level by using Gridwise, the #1 business app for gig drivers.\r\n\r\nDriving for Uber, Lyft, Doordash, Walmart Spark or Instacart? Get the all-in-one app uniquely built for rideshare and delivery drivers to track mileage, boost earnings, and get control of your expenses across all rideshare and delivery apps. Plus users get automatic earnings download for Uber, Lyft, Wingz, Uber Eats, DoorDash, Caviar, Instacart, Cornershop, Grubhub, Gopuff, Amazon Flex, Alto, Walmart Spark Driver, Shipt, Roadie, Point Pickup, Curb, Waitr, Favor Delivery, and more.\r\n\r\nNew to Gig work or already a Pro, looking to tune your work to the next level? Come join the growing community of 650,000+ gig drivers using Gridwise as their one-stop shop to earn and keep more. Get even more tips in our Facebook group or on Reddit today!\r\n\r\n<b>Why Gridwise?</b>\r\n\r\n<b>Earn more</b>\r\nGet valuable insights to find where and when to work to maximize your hourly or per-mile rate. Organize all your earnings in one place so you can compare them to other drivers in your area, monitor which services are most profitable, and find opportunities to earn more efficiently.\r\n\r\n<b>Keep more</b>\r\nLooking to keep more money with the best, most accurate deductions on your taxes? Or keep more of your personal time by hitting your daily/weekly goals faster? Gridwise can help you with both! Automatically log all your rideshare and delivery activities so you can easily monitor all your expenses and mileage with an all-in-one view.\r\n\r\n<b>Plan better</b>\r\nTap into local event schedules, airport insights or neighborhood hourly wage data so you can focus on the most profitable gigs during peak times and in the busiest places, or see what places/times you should avoid if you hate sitting in traffic!\r\n\r\n<b>View and benchmark your performance</b>\r\nRun your business like a pro by getting the data you need in easy to read and interpret graphs. Gridwise goes deep and is built by gig workers for gig workers to deliver unique insights, unlike other trackers on the market like MileIQ, Hurdlr, Everlance, Stoovo, Mystro, Rydar, Sherpashare, Solo, Stride and Para.\r\n\r\n<b>Wait less and stay in the know</b>\r\nOn the airport run? Our \u201cjust in time\u201d airport arrival and departure insights have flight updates, plane sizes, weather info and customizable alerts so you know when to show up to the airport to spend the least amount of time in a queue.\r\n\r\n<b>Simplify your tax prep</b>\r\nConsolidate your business driving mileage expenses to make for an easy tax deduction. And, our Plus members save 50% on Keeper tax preparation services! \r\n\r\n<b>Enjoy perks</b>\r\nGet exclusive benefits just for being a Gridwise user to help you both on and off the road \u2014 from insurance to healthcare and more. Plus users get even higher discounts and offers.\r\n\r\n<b>Unlock even more perks!</b>\r\nGet the most out of Gridwise with a Gridwise Plus subscription. Join Plus for just $9.99/month or $71.99/year (or just $6/mo.) for our annual subscription. Since Gridwise is a business expense it\u2019s completely tax deductible. Your payment will be charged to your iTunes account at the time of purchase. Your subscription will automatically renew unless auto-renew is turned off at least 24 hours prior to the end of the current subscription period. You can manage your subscriptions and turn off auto-renewal at any time from your iTunes account settings. Please see our terms of service and privacy policy for more information.\r\n\r\nTerms of Service: gridwise.io/termsofservice\r\nPrivacy Policy: gridwise.io/privacypolicy\r\n\r\nTo reach the Gridwise team, you can find us at\r\nsupport: support@gridwise.io\r\nwebsite: https://gridwise.io/\r\n\r\nGridwise is not a financial advisor. All information provided by the app is for informational purposes only. Please seek advice from qualified tax professionals.",
    "descriptionHTML": "Take your Gig work to the next level by using Gridwise, the #1 business app for gig drivers.<br><br>Driving for Uber, Lyft, Doordash, Walmart Spark or Instacart? Get the all-in-one app uniquely built for rideshare and delivery drivers to track mileage, boost earnings, and get control of your expenses across all rideshare and delivery apps. Plus users get automatic earnings download for Uber, Lyft, Wingz, Uber Eats, DoorDash, Caviar, Instacart, Cornershop, Grubhub, Gopuff, Amazon Flex, Alto, Walmart Spark Driver, Shipt, Roadie, Point Pickup, Curb, Waitr, Favor Delivery, and more.<br><br>New to Gig work or already a Pro, looking to tune your work to the next level? Come join the growing community of 650,000+ gig drivers using Gridwise as their one-stop shop to earn and keep more. Get even more tips in our Facebook group or on Reddit today!<br><br><b>Why Gridwise?</b><br><br><b>Earn more</b><br>Get valuable insights to find where and when to work to maximize your hourly or per-mile rate. Organize all your earnings in one place so you can compare them to other drivers in your area, monitor which services are most profitable, and find opportunities to earn more efficiently.<br><br><b>Keep more</b><br>Looking to keep more money with the best, most accurate deductions on your taxes? Or keep more of your personal time by hitting your daily/weekly goals faster? Gridwise can help you with both! Automatically log all your rideshare and delivery activities so you can easily monitor all your expenses and mileage with an all-in-one view.<br><br><b>Plan better</b><br>Tap into local event schedules, airport insights or neighborhood hourly wage data so you can focus on the most profitable gigs during peak times and in the busiest places, or see what places/times you should avoid if you hate sitting in traffic!<br><br><b>View and benchmark your performance</b><br>Run your business like a pro by getting the data you need in easy to read and interpret graphs. Gridwise goes deep and is built by gig workers for gig workers to deliver unique insights, unlike other trackers on the market like MileIQ, Hurdlr, Everlance, Stoovo, Mystro, Rydar, Sherpashare, Solo, Stride and Para.<br><br><b>Wait less and stay in the know</b><br>On the airport run? Our \u201cjust in time\u201d airport arrival and departure insights have flight updates, plane sizes, weather info and customizable alerts so you know when to show up to the airport to spend the least amount of time in a queue.<br><br><b>Simplify your tax prep</b><br>Consolidate your business driving mileage expenses to make for an easy tax deduction. And, our Plus members save 50% on Keeper tax preparation services! <br><br><b>Enjoy perks</b><br>Get exclusive benefits just for being a Gridwise user to help you both on and off the road \u2014 from insurance to healthcare and more. Plus users get even higher discounts and offers.<br><br><b>Unlock even more perks!</b><br>Get the most out of Gridwise with a Gridwise Plus subscription. Join Plus for just $9.99/month or $71.99/year (or just $6/mo.) for our annual subscription. Since Gridwise is a business expense it\u2019s completely tax deductible. Your payment will be charged to your iTunes account at the time of purchase. Your subscription will automatically renew unless auto-renew is turned off at least 24 hours prior to the end of the current subscription period. You can manage your subscriptions and turn off auto-renewal at any time from your iTunes account settings. Please see our terms of service and privacy policy for more information.<br><br>Terms of Service: gridwise.io/termsofservice<br>Privacy Policy: gridwise.io/privacypolicy<br><br>To reach the Gridwise team, you can find us at<br>support: support@gridwise.io<br>website: https://gridwise.io/<br><br>Gridwise is not a financial advisor. All information provided by the app is for informational purposes only. Please seek advice from qualified tax professionals.",
    "summary": "Boost Rideshare & Delivery Pay",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 810740,
    "score": 4.4297676,
    "ratings": 10756,
    "reviews": 2660,
    "histogram": [
        880,
        259,
        399,
        1030,
        8184
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $69.99 per item",
    "developer": "Gridwise",
    "developerId": "Gridwise",
    "developerEmail": "support@gridwise.io",
    "developerWebsite": "https://gridwise.io",
    "developerAddress": "2545 Railroad St.\nPittsburgh, PA 15222",
    "privacyPolicy": "https://gridwise.io/privacypolicy",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/yEikQYgM-_TnUPDO2Db9C1hGNiWAp1lYgwDAvJbHN8zF7i-AhrPjt1y4caxaMPtlG98",
    "headerImage": "https://play-lh.googleusercontent.com/6V_kfYj0uNZrgjWB2i9mVqY4_NmyEhsOQIdUbX0Nkumlkp3ofZv1F3dC_CBdzw14_w",
    "screenshots": [
        "https://play-lh.googleusercontent.com/3aPv_kdakPEeH3C0VU8fFNEC4VtJkg6ZxtuaiwucFBpVz2m8YxenakfgD5fsjZYmhHU",
        "https://play-lh.googleusercontent.com/SHPqTCDGzALpoBcFOt3cZKM_-dvYnIIDfDOG338sQp1imBx_ccCLUSfLXQJLTFYyVy4",
        "https://play-lh.googleusercontent.com/aLujG6G8UPpeOfEGbcov1psvVg08-g7UcvPZ-2SFb7BS7a5avsTHHOS_xTnA-hLq7A",
        "https://play-lh.googleusercontent.com/jlk7MHm7zdYLfPUop_PVRksH4Hn2FyJ7oUkQx_R-S9yRzL037XpsA2tvlIF_A-DdKEbz",
        "https://play-lh.googleusercontent.com/w8aVr2Op97gmIVX778kbaK0ZkT5Iih0bh7raKyMMnd-Ei4vuvoTYQGWpR6xub2om2QY",
        "https://play-lh.googleusercontent.com/dWM0bx0V4hjJIJY_vnhHdqSt0HB0pktghCfeFXDE556L0d1auEbHwBJgjmcCa4UuBg",
        "https://play-lh.googleusercontent.com/IaNQc75MeSHvM1FvW-MT_r1-5r4eIZFSTR8TUPkVJi2t5E1nvrUO-sYbhAaWOdPCTaE",
        "https://play-lh.googleusercontent.com/IIX-NXVT1f4pnRS9wpHBlpQFTPp1dti8GLyoIivGZIhJqkRdkS5mI48DoEVBSehNJT9T"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Dec 3, 2016",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728941343,
    "version": "3.60.0",
    "comments": [],
    "appId": "com.gridwise.app",
    "url": "https://play.google.com/store/apps/details?id=com.gridwise.app&hl=en&gl=us"
}