{
    "title": "Soltera - Latino Dating App",
    "description": "Soltera is a dating app designed for the Latino community. Soltera is dedicated to single men and women who identify as Latino, Hispanic, Chicano, or Spanish. It is built around the mission of making connections and creating a community where users can take pride in their culture and country of origin. We want you to celebrate the things that make you the person you are and we also want you to easily find others that share the same interests as you and appreciate you. Download the app now and start meeting other Latino singles. \r\n\r\nSoltera has MORE features than other apps and is the best at connecting singles:\r\n\r\nFREE TO MATCH AND FREE TO CHAT\r\nSoltera users can match and send messages for free. \r\n\r\nDIRECT MESSAGES = CONNECT FASTER\r\nWe all know that great feeling when you find a profile that you really like. Well now you can send them a direct message and they will see it right away. No need to wait for them to match with you. We are all about connecting faster on Soltera! \r\n\r\nSEARCH & USE FILTERS\r\nSwiping can get tiring and maybe even boring sometime. So, when you just want to find your true match, then use the search feature and find your perfect match. \r\n\r\nCONNECT WITH PEOPLE NEARBY & WORLDWIDE\r\nDon\u2019t let geography stop you from finding the right person. Change your location and find your connection anywhere in the world. \r\n\r\nSoltera Premium is an Auto-renewable subscription service provided within the app. Activate Soltera Premium and you will get to send unlimited likes and direct messages, rewind profiles, change locations, see who likes you. \r\n\r\nAuto-renewable subscriptions for Soltera Premium\r\n\r\n\u2022 1-month ($19.99), 3 months ($39.99), 6-months $59.99, 12-months ($89.99) durations\r\n\r\n\u2022 Your subscription will be charged to your Play Store account at confirmation of purchase and will automatically renew (at the duration selected) unless auto-renew is turned off at least 24 hours before the end of the current period.\r\n\r\n\u2022 Current subscription may not be cancelled during the active subscription period; however, you can manage your subscription to a higher plan and/or turn off auto-renewal by visiting your iTunes Account Settings after purchase.\r\n\r\n\u2022Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable. Subscriptions & purchases are also forfeited if you delete your account. All prices are in U.S Dollars and may vary in other countries other than the U.S. Prices are subject to change without notice.\r\n\u2022Subscriptions are tied to only one Soltera account and cannot be transferred to new accounts.\r\n\r\n\u2022 Privacy policy and terms\r\nTerms: https://soltera.app/terms/\r\nPrivacy Policy: https://soltera.app/privacy/\r\nWe will be glad to see all your feedback at contact@soltera.app",
    "descriptionHTML": "Soltera is a dating app designed for the Latino community. Soltera is dedicated to single men and women who identify as Latino, Hispanic, Chicano, or Spanish. It is built around the mission of making connections and creating a community where users can take pride in their culture and country of origin. We want you to celebrate the things that make you the person you are and we also want you to easily find others that share the same interests as you and appreciate you. Download the app now and start meeting other Latino singles. <br><br>Soltera has MORE features than other apps and is the best at connecting singles:<br><br>FREE TO MATCH AND FREE TO CHAT<br>Soltera users can match and send messages for free. <br><br>DIRECT MESSAGES = CONNECT FASTER<br>We all know that great feeling when you find a profile that you really like. Well now you can send them a direct message and they will see it right away. No need to wait for them to match with you. We are all about connecting faster on Soltera! <br><br>SEARCH &amp; USE FILTERS<br>Swiping can get tiring and maybe even boring sometime. So, when you just want to find your true match, then use the search feature and find your perfect match. <br><br>CONNECT WITH PEOPLE NEARBY &amp; WORLDWIDE<br>Don\u2019t let geography stop you from finding the right person. Change your location and find your connection anywhere in the world. <br><br>Soltera Premium is an Auto-renewable subscription service provided within the app. Activate Soltera Premium and you will get to send unlimited likes and direct messages, rewind profiles, change locations, see who likes you. <br><br>Auto-renewable subscriptions for Soltera Premium<br><br>\u2022 1-month ($19.99), 3 months ($39.99), 6-months $59.99, 12-months ($89.99) durations<br><br>\u2022 Your subscription will be charged to your Play Store account at confirmation of purchase and will automatically renew (at the duration selected) unless auto-renew is turned off at least 24 hours before the end of the current period.<br><br>\u2022 Current subscription may not be cancelled during the active subscription period; however, you can manage your subscription to a higher plan and/or turn off auto-renewal by visiting your iTunes Account Settings after purchase.<br><br>\u2022Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable. Subscriptions &amp; purchases are also forfeited if you delete your account. All prices are in U.S Dollars and may vary in other countries other than the U.S. Prices are subject to change without notice.<br>\u2022Subscriptions are tied to only one Soltera account and cannot be transferred to new accounts.<br><br>\u2022 Privacy policy and terms<br>Terms: https://soltera.app/terms/<br>Privacy Policy: https://soltera.app/privacy/<br>We will be glad to see all your feedback at contact@soltera.app",
    "summary": "Meet & Connect with Latino Singles Nearby. Designed for Relationships.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 43498,
    "score": 4.7722774,
    "ratings": 407,
    "reviews": 49,
    "histogram": [
        3,
        0,
        15,
        44,
        341
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $99.99 per item",
    "developer": "Swift Tech, LLC",
    "developerId": "Swift+Tech,+LLC",
    "developerEmail": "contact@soltera.app",
    "developerWebsite": "https://soltera.app",
    "developerAddress": "1445 Woodmont LN NW,\nAtlanta, GA, 30318, USA",
    "privacyPolicy": "https://amaredatingapp.com/privacy/",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/x2dDzHoUW4hMd4AyZXteV7cSSNBNYezZ1uzyKiaND-TqP6eI5cXlMog3Y293S8QX3g",
    "headerImage": "https://play-lh.googleusercontent.com/9klt1aFMeiKi5ExQqNcgClj37lKNtZ3Qge3qJ2ZO22w0BN9_rL0yAValAZipVnK1ZME",
    "screenshots": [
        "https://play-lh.googleusercontent.com/gonZNHuc1FMRUnFb85stzF5eJD4esjo0rNmqmgcXAkX9N4TrM4UzCsi3IjCUO6jmmu6b",
        "https://play-lh.googleusercontent.com/rMu0iPNKzEjCTgDFyiGmqqTlQ-cl7Vd3GmLvgulw2MyfY5Gc2vGrk0WDLeXvDHzxURA",
        "https://play-lh.googleusercontent.com/AQ3nXJ7uMnDhB99ZVl8z9gC7qSm913aCDc3PIbXgZop6NQeJHflZNjvOli7vPsxFjoA",
        "https://play-lh.googleusercontent.com/RqM1eyOWT42XZUJDlatvwl6Q0Yql5ZFDSv6dLP0wE8tEtVMI_rTmVjTdFWAa0NN6nQ",
        "https://play-lh.googleusercontent.com/NJQFPwu25WA6XNI3vPc1uU6Fey__J3Ej0oY5KAMy7_s_GAbsy3feClW3kEpGNbxGXMQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 1, 2021",
    "lastUpdatedOn": "Sep 25, 2024",
    "updated": 1727273630,
    "version": "2.0.20",
    "comments": [],
    "appId": "com.swiftdating.app",
    "url": "https://play.google.com/store/apps/details?id=com.swiftdating.app&hl=en&gl=us"
}