{
    "title": "Roll by ADP \u2013 Easy Payroll App",
    "description": "Pay yourself and your employees with Roll \u2014 a chat-based payroll app for small businesses. \ud83d\ude4c\r\n\r\nTry Roll FREE for 3 months! \ud83d\ude0d If you know how to chat \ud83d\udcac , you know how to run payroll with Roll! Plus, Roll brings decades of expertise from ADP, the biggest name in payroll. With Roll, running your small business payroll really is as easy as Download. Chat. Pay.\r\n\r\nPRAISE FOR ROLL BY ADP\r\n\r\nNerdwallet: \u201cIf you\u2019re looking for solid payroll features that can be initiated from your phone, you\u2019ll find them with Roll by ADP.\u201d\r\n\r\nBusiness Insider: \u201cBacked by the long-standing payroll expertise and data security of ADP, Roll offers small business owners the ability to run payroll anywhere, anytime with no experience needed.\u201d\r\n\r\nTechRadar: \u201cThe app walks the user through the process while removing more labor-intensive aspects of the payroll run.\u201d\r\n\r\nTHE BEST PAYROLL APP FOR SMALL BUSINESSES\r\n\u25cf 2-10 employees\r\n\u25cf Solopreneurs running food trucks, catering services, construction companies, home services, advisory services, and more!\r\n\u25cf Mobile payroll management: Pay quickly and easily from your phone\r\n\u25cf Give bonuses, off-cycle raises, and run payroll anytime, anywhere\r\n\r\n\u201cHonestly, setting up ROLL was the easiest process I\u2019ve ever done, and I\u2019ve worked with a lot of payroll companies over the past 20 years. I even told my friend who owns a business that he should switch over because it was the easiest thing in the world, and the price is great. [Intuit] QuickBooks was easy, but ROLL is far easier.\u201d\r\n\u2014 Kimberly and Ken Anaya, owners Anaya Treasures Corporation\r\n\r\nSAVE TIME\r\n\u25cf No training necessary! Set up your account directly within the Roll app in minutes with a personalized, step-by-step guide\r\n\u25cf Run payroll and pay your entire team in under a minute\r\n\u25cf Easily make changes and updates: add new employees, change salaries, give promotions, send bonuses, and more \u2014 all in a chat\r\n\r\nSAVE MONEY\r\n\u25cf More affordable than other easy payroll providers\r\n\u25cf No long-term contracts\r\n\r\nKEY FEATURES\r\n\u25cf Run unlimited payroll\r\n\u25cf Integrate with QuickBooks\u00ae Online\r\n\u25cf Pay workers whenever, however you want\r\n\u25cf Personalized reminders: Get proactive reminders and alerts to help you stay on top of important tasks and deadlines\r\n\u25cfTo-do list: See everything you need to do in an intuitive timeline-based view\r\n\u25cf Automated reports: Get payroll reports sent to you and payroll registers sent to your accountant\r\n\u25cf 24/7 support: Simply chat with Roll whenever you need support\r\n\r\nFree for Employees:\r\nRoll is the same easy mobile payroll app for employees, too! With Roll, your employees can:\r\n\u25cf Easily update personal information\r\n\u25cf Get proactive notifications, task, and deadline reminders\r\n\u25cf View and print pay stubs anytime\r\n\u25cf Receive payday notifications\r\n\u25cf Visit their profile for at-a-glance job, pay and benefits info\r\n\r\nRoll by ADP is an automatic small business payroll calculator and reminder system in your pocket that makes running payroll incredibly easy. Roll by ADP not only runs payroll in under a minute \u2014 it also calculates tax and withholdings for each employee.\r\n\r\nRoll by ADP is an easy payroll management app for small businesses that does only what you need it to \u2013 nothing more, nothing less. Easy and cheap (inexpensive cheap, not cheap quality!) Now you can have easy, mobile payroll management at your fingertips.",
    "descriptionHTML": "Pay yourself and your employees with Roll \u2014 a chat-based payroll app for small businesses. \ud83d\ude4c<br><br>Try Roll FREE for 3 months! \ud83d\ude0d If you know how to chat \ud83d\udcac , you know how to run payroll with Roll! Plus, Roll brings decades of expertise from ADP, the biggest name in payroll. With Roll, running your small business payroll really is as easy as Download. Chat. Pay.<br><br>PRAISE FOR ROLL BY ADP<br><br>Nerdwallet: \u201cIf you\u2019re looking for solid payroll features that can be initiated from your phone, you\u2019ll find them with Roll by ADP.\u201d<br><br>Business Insider: \u201cBacked by the long-standing payroll expertise and data security of ADP, Roll offers small business owners the ability to run payroll anywhere, anytime with no experience needed.\u201d<br><br>TechRadar: \u201cThe app walks the user through the process while removing more labor-intensive aspects of the payroll run.\u201d<br><br>THE BEST PAYROLL APP FOR SMALL BUSINESSES<br>\u25cf 2-10 employees<br>\u25cf Solopreneurs running food trucks, catering services, construction companies, home services, advisory services, and more!<br>\u25cf Mobile payroll management: Pay quickly and easily from your phone<br>\u25cf Give bonuses, off-cycle raises, and run payroll anytime, anywhere<br><br>\u201cHonestly, setting up ROLL was the easiest process I\u2019ve ever done, and I\u2019ve worked with a lot of payroll companies over the past 20 years. I even told my friend who owns a business that he should switch over because it was the easiest thing in the world, and the price is great. [Intuit] QuickBooks was easy, but ROLL is far easier.\u201d<br>\u2014 Kimberly and Ken Anaya, owners Anaya Treasures Corporation<br><br>SAVE TIME<br>\u25cf No training necessary! Set up your account directly within the Roll app in minutes with a personalized, step-by-step guide<br>\u25cf Run payroll and pay your entire team in under a minute<br>\u25cf Easily make changes and updates: add new employees, change salaries, give promotions, send bonuses, and more \u2014 all in a chat<br><br>SAVE MONEY<br>\u25cf More affordable than other easy payroll providers<br>\u25cf No long-term contracts<br><br>KEY FEATURES<br>\u25cf Run unlimited payroll<br>\u25cf Integrate with QuickBooks\u00ae Online<br>\u25cf Pay workers whenever, however you want<br>\u25cf Personalized reminders: Get proactive reminders and alerts to help you stay on top of important tasks and deadlines<br>\u25cfTo-do list: See everything you need to do in an intuitive timeline-based view<br>\u25cf Automated reports: Get payroll reports sent to you and payroll registers sent to your accountant<br>\u25cf 24/7 support: Simply chat with Roll whenever you need support<br><br>Free for Employees:<br>Roll is the same easy mobile payroll app for employees, too! With Roll, your employees can:<br>\u25cf Easily update personal information<br>\u25cf Get proactive notifications, task, and deadline reminders<br>\u25cf View and print pay stubs anytime<br>\u25cf Receive payday notifications<br>\u25cf Visit their profile for at-a-glance job, pay and benefits info<br><br>Roll by ADP is an automatic small business payroll calculator and reminder system in your pocket that makes running payroll incredibly easy. Roll by ADP not only runs payroll in under a minute \u2014 it also calculates tax and withholdings for each employee.<br><br>Roll by ADP is an easy payroll management app for small businesses that does only what you need it to \u2013 nothing more, nothing less. Easy and cheap (inexpensive cheap, not cheap quality!) Now you can have easy, mobile payroll management at your fingertips.",
    "summary": "Roll by ADP is easy, mobile payroll for small businesses owners on the go!",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 620296,
    "score": 4.33121,
    "ratings": 1573,
    "reviews": 299,
    "histogram": [
        150,
        29,
        99,
        160,
        1131
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "ADP, INC.",
    "developerId": "ADP,+INC.",
    "developerEmail": "team.roll@adp.com",
    "developerWebsite": "https://rollbyadp.com",
    "developerAddress": null,
    "privacyPolicy": "https://e.adp.ai/privacy",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/SzaXtX96Sm6ywn0yKMRFvfBrQU0VHKkHhn9HynPMSigcqEduw4ohKTAfsfZ0tD0ly13F",
    "headerImage": "https://play-lh.googleusercontent.com/4D7V_WB8_W9htavwhV3s1jb4a8Z648tz8sPZCx_u3QiNyJzA90GbnYF8WYIwmSC3r68",
    "screenshots": [
        "https://play-lh.googleusercontent.com/0g1Wt8RPCnKIbwbjJ3EPqcjuSs1thVJZsTKp4HrisTLAUMVxLV6IHfqDaOnPChELJ4o",
        "https://play-lh.googleusercontent.com/vygWwBNOfooKp52TUhP86KsekldVlJCxpJv5Gn59-V2LqfLdqPmMNq9e7uA62YXnY0E",
        "https://play-lh.googleusercontent.com/NPrdlyErd-mNeQRr0bovE9-y6zLE8T5BCnV2BUQaw501dHUFhcBpnrlRfxWUR52w5TVH",
        "https://play-lh.googleusercontent.com/QkhNRrqLuV265O6hWasgcJMy6HCTUoGv-H15Q1SScR6_s7MUpNDYDnXSnGsV8NI-LUY",
        "https://play-lh.googleusercontent.com/Ril_wXZsemeLAbbZB1wd-x66m1q4D1DGaVp_Z1R_54OQsd7tlbzQ272JUVpXiUMaQjw",
        "https://play-lh.googleusercontent.com/jh9O0fQiBe4gdKkw8Na__ZVs9EhNf9gBLGn1VlBp3OjyN7KOx-YVMnSxtMMkArZtTA",
        "https://play-lh.googleusercontent.com/hHAOWpyLBR8hQkS9ZbnZ6IKpzs3ET4kUMasZvJ91oC2yqKToQQ35tPwHjfO8ng2KUJI",
        "https://play-lh.googleusercontent.com/YGlJ6jU_znM0wi4IyFmglPlMAd4EiEp_eIxxDWntz7crMHJpIb7f0Q-nP8SOesfRrvc",
        "https://play-lh.googleusercontent.com/mhkbT5fsuMhBaIYIfGLr6wfhueUTXUUA7IrL8qp3ETeb5n7bIPMFqxEdaEks4dDvLuOa",
        "https://play-lh.googleusercontent.com/hOLqGHauu93tNnETYKetZKNO6mOvYSmngEkiTI7RhItmVNm2PsLIBmxgjnnQtjBDzbE",
        "https://play-lh.googleusercontent.com/G4q1sxSFxdvI9LT4swDHCuK_zR06Qgb0QetTUnefNlIn6FME102MjHCUBRqwgaMA3Fo",
        "https://play-lh.googleusercontent.com/RRyMPlCi7NZJNdcOuXwcX7a_n3ESW64ZQPzUtkzcgXEemS0aKhAHhKXaJq5D47dKHQVC",
        "https://play-lh.googleusercontent.com/fdo1iFFq8Aa-Qyi79z-sG_vY9NulonAeCHaHCuSOWzTKgbpOIF5341bXUStBz8Sy-Jxa",
        "https://play-lh.googleusercontent.com/xdDlI1qLPujrKOpHsEN2fo7Un0JEymZZqenpxNPtox_VLG7bltM5UhwXWRIZR3GJdGo",
        "https://play-lh.googleusercontent.com/IN6rjVxlGZ2udsaNY4AZASjQinATWAoTjvARi_vVqo3htd-qJyzFQjosOSBcasf9iPA",
        "https://play-lh.googleusercontent.com/usxl24RtXDNmn-bQNG_ajqVIAwtc8MaRtR9BddDbnvbpiz1NONEwqnOOah3_rIsbl8M",
        "https://play-lh.googleusercontent.com/wPkrVnE541fUapzEwu45ToZY4DHrbz8hebcEN3lMJMVNWcJQzESo_V2davTEzR8Z40E",
        "https://play-lh.googleusercontent.com/nZv3kvb_dIavH7NfGC-M0aeWIRwksxGqdjIq4hEu1ULWJN5jJVaFNMxE1lvnHltym8sI",
        "https://play-lh.googleusercontent.com/ILs1I_J3P-cv727EJacsuMJ311RilfbaEiIvJlNAe3wtMdZf_dAf9pYNh1DKYwcdXLQ"
    ],
    "video": "https://www.youtube.com/embed/arhItFyqxbQ?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/4D7V_WB8_W9htavwhV3s1jb4a8Z648tz8sPZCx_u3QiNyJzA90GbnYF8WYIwmSC3r68",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 12, 2020",
    "lastUpdatedOn": "Sep 6, 2024",
    "updated": 1725651930,
    "version": "3.2.77",
    "comments": [],
    "appId": "com.adp.e",
    "url": "https://play.google.com/store/apps/details?id=com.adp.e&hl=en&gl=us"
}