{
    "title": "Color Analysis AI",
    "description": "Discover your color season and find your perfect colors with Color Analysis AI\r\n\r\n\r\n\u25c6 HOW IT WORKS \u25c6\r\n\r\n1) Upload your photos\r\n2) Glowup AI will analyze your facial features\r\n3) Learn about insights your most attractive traits and get personalized tips to highlight your beauty\r\n\r\n\r\n\u25c6 DISCOVER YOUR COLOR SEASON \u25c6\r\n\r\n- Choose from an effortless automatic color analysis or dive deep with a manual color quiz designed for the pros.\r\n- Embark on a journey through our seasonal color quiz, rooted in the timeless four seasons color theory. \r\n- Find your match among 12 dazzling season colors: from the airy hues of Light - Summer to the rich tones of Deep Autumn, and the vibrant vibes of Bright Spring to the icy shades of Cold Winter.\r\n- Let our personal color analysis reveal the clothing and makeup shades that naturally accentuate your beauty, blending seamlessly with your skin tone, eye color, and hair shade.\r\n\r\n\r\n\u25c6 CRAFT YOUR PERFECT PALETTE \u25c6 \r\n\r\n- Explore over 120 pantone colors from our seasonal palettes to craft looks that speak your style language, from chic and trendy to timeless and elegant.\r\n- Elevate your palette by adding beloved colors through an intuitive color wheel.\r\n- Experiment with fashion and accessories by mixing and matching from an extra palette of complementary color combinations.\r\n\r\n\r\n\u25c6 MAKEUP, ACCESSORIES & WARDROBE \u25c6 \r\n\r\n- Dive into a selection of 70 makeup shades tailored for each color type, including lipsticks, eyeshadows, eyeliners, and blushes.\r\n- Experience a digital transformation with our virtual makeover feature, showcasing your complete look.\r\n\r\n\r\nColor Analysis AI is here to empower you with the confidence to express your authentic self through colors that resonate with your natural beauty. Get ready to meet the most radiant you. Discover your best colors with Color Analysis AI, your personal AI color analysis guide. Our app unveils the secret to your perfect colors through an innovative personal color analysis. Simply snap a selfie, and instantly learn about your unique season color, along with the best color palettes for your clothes and makeup.\r\n\r\n\r\nPrivacy Policy: https://coloranalysisapp.com/privacy\r\nTerms of Service: https://coloranalysisapp.com/terms",
    "descriptionHTML": "Discover your color season and find your perfect colors with Color Analysis AI<br><br><br>\u25c6 HOW IT WORKS \u25c6<br><br>1) Upload your photos<br>2) Glowup AI will analyze your facial features<br>3) Learn about insights your most attractive traits and get personalized tips to highlight your beauty<br><br><br>\u25c6 DISCOVER YOUR COLOR SEASON \u25c6<br><br>- Choose from an effortless automatic color analysis or dive deep with a manual color quiz designed for the pros.<br>- Embark on a journey through our seasonal color quiz, rooted in the timeless four seasons color theory. <br>- Find your match among 12 dazzling season colors: from the airy hues of Light - Summer to the rich tones of Deep Autumn, and the vibrant vibes of Bright Spring to the icy shades of Cold Winter.<br>- Let our personal color analysis reveal the clothing and makeup shades that naturally accentuate your beauty, blending seamlessly with your skin tone, eye color, and hair shade.<br><br><br>\u25c6 CRAFT YOUR PERFECT PALETTE \u25c6 <br><br>- Explore over 120 pantone colors from our seasonal palettes to craft looks that speak your style language, from chic and trendy to timeless and elegant.<br>- Elevate your palette by adding beloved colors through an intuitive color wheel.<br>- Experiment with fashion and accessories by mixing and matching from an extra palette of complementary color combinations.<br><br><br>\u25c6 MAKEUP, ACCESSORIES &amp; WARDROBE \u25c6 <br><br>- Dive into a selection of 70 makeup shades tailored for each color type, including lipsticks, eyeshadows, eyeliners, and blushes.<br>- Experience a digital transformation with our virtual makeover feature, showcasing your complete look.<br><br><br>Color Analysis AI is here to empower you with the confidence to express your authentic self through colors that resonate with your natural beauty. Get ready to meet the most radiant you. Discover your best colors with Color Analysis AI, your personal AI color analysis guide. Our app unveils the secret to your perfect colors through an innovative personal color analysis. Simply snap a selfie, and instantly learn about your unique season color, along with the best color palettes for your clothes and makeup.<br><br><br>Privacy Policy: https://coloranalysisapp.com/privacy<br>Terms of Service: https://coloranalysisapp.com/terms",
    "summary": "Find your color season",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 155571,
    "score": 3.56,
    "ratings": 13799,
    "reviews": 50,
    "histogram": [
        2868,
        271,
        2325,
        2752,
        5504
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $12.99 per item",
    "developer": "Drawanyone",
    "developerId": "8366241453961987403",
    "developerEmail": "team@coloranalysisapp.com",
    "developerWebsite": "https://coloranalysisapp.com",
    "developerAddress": "251 Little Falls Dr\nWilmington, DE 19808",
    "privacyPolicy": "https://coloranalysisapp.com/privacy",
    "genre": "Beauty",
    "genreId": "BEAUTY",
    "categories": [
        {
            "name": "Beauty",
            "id": "BEAUTY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/6lMBR8zYLn3Wq5klILDgu1k9XbSDRhVnGJuhIYLEV-5t5b2VXNtjOPjNcqg4A6erYA",
    "headerImage": "https://play-lh.googleusercontent.com/fRVZGttZlh16rJ4NA2J91ifQd0-nzvClZTc0kuB00WSA8leYStNuzxfX44OJq1U6OQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/o8y3JJj_bxu1PTY34ScaIsS8InTDPAF1MIHVSzapMzRWq-RzvGtmrrd3nF7-OAzmkyA",
        "https://play-lh.googleusercontent.com/9rFYQCe-84jEY1Q07-sJPd3qALF_9J3zQ5ZiVthlDgaZHkw8TnRDryZ0PKykHyJhCg",
        "https://play-lh.googleusercontent.com/mLHzSJf3kknkuU1vutUL5UFewvKWml6NIBDq8huV9rX0HVvvYEaIt3H29dMwjQOi-T4",
        "https://play-lh.googleusercontent.com/kXzLDrue2y6Pynw1aEphXTC9isWV8I1InJPle_mlsEpjUqFZwJukgMfgNsgJQjcx2HA",
        "https://play-lh.googleusercontent.com/v4Q6NtWj3HggrVBuvzyxBSf8MYNWHuujrQzYe20aMQu8GX9GlPgVT0P_XX_B74UE0SPP",
        "https://play-lh.googleusercontent.com/hJr__669amYPVyzLkdJu5IpQ9V0OMcVvtKFciRs2w_Cci1NIXd4-mLjpi20FWlCcTH8",
        "https://play-lh.googleusercontent.com/oddQVIodbiLwt3fsi5Qq4fyWPOF1aoFNGuDS4L6hTX4FB5kwXjYt9H5-vk_SmPZCJgs",
        "https://play-lh.googleusercontent.com/gLuTKCKxQ7D9TBU8I0RFMI6zfZ9SrGsXAAdC04qHEnssvZ4LSQ2iMMrJG3UNz1EoIw",
        "https://play-lh.googleusercontent.com/pTypy4LkAYiOg5mKn3GharqGdJd6p13VoNTwOxRF1mBSFSekaz2PXZhZovlzXZBVS-s",
        "https://play-lh.googleusercontent.com/N89XyI48CnXz2ZNRcktC8a7q74uxUUQ81GQxwCi6Cp1ftmmySxqWhtGnIYeDoh0yGgp6",
        "https://play-lh.googleusercontent.com/OBd2NHHT6BlQQzKevVSb_nVzXfmp_xklS494Mt9unKWOFq9KQTjCe6CCQOrVOyOliA",
        "https://play-lh.googleusercontent.com/VwMn_U16o9rf60L_b9obPhfSUbWPlU3gX-REML_iYUxiZkoaFwgI0uB5_kmJ3sQo1qZJ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 8, 2024",
    "lastUpdatedOn": "Apr 12, 2024",
    "updated": 1712933247,
    "version": "1.0.1",
    "comments": [],
    "appId": "com.colorscan.app",
    "url": "https://play.google.com/store/apps/details?id=com.colorscan.app&hl=en&gl=us"
}