{
    "title": "I'm Lonely - My Community",
    "description": "I'm Lonely, Inc. is a trailblazing company dedicated to addressing the growing issue of loneliness in modern society. Founded in early 2024 by a team of individuals who personally experienced the struggles of forming meaningful connections, I'm Lonely, Inc. is committed to fostering authentic, in-person interactions within local communities. Frustrated by the shortcomings of traditional dating apps, which are often costly and plagued by fake profiles, the founders sought to create a genuine social platform for dating that everyone can use, including couples.\r\n\r\nThe app facilitates group hangouts, events, and dates, allowing users to form meaningful connections and engage in offline social activities. We firmly believe that personal relationships have a profound impact on an individual's happiness and mental health, which, in turn, can influence job satisfaction and productivity in your community. In an effort to improve the lives of our users and contribute to their overall well-being, we are committed to disrupting the dating industry and reshaping the narrative surrounding dating as an experience that is inclusive and beneficial for everyone.\r\n\r\nRemember, to maintain a healthy relationship you must date your significant other!\r\n\r\nSAFETY FEATURES\r\nWe provide the opportunity for all users to purchase a background pre-check which checks your information against the national criminal database to help protect the safety of our users. In addition, we do an identity check with your drivers license and a selfie to verify you are who you say you are and not a bot. Please take advantage of these features as this is how we keep our I'm Lonely user community safe and thriving.\r\n\r\nFOR COUPLES\r\n* Users can find and search over 1000 events and activities for an awesome date night in your city, the most on any platform.\r\n* Users can find and create new Hangouts with 3 or more users that share the same interests such as a book club, birthday party, or for a new band launch.\r\n* Won\u2019t see any dating features\r\n\r\nFOR SINGLES\r\n* Your 30 sec introduction video is vital to allowing potential daters to connect and see your vibe and personality along with matching interests you both have in common\r\n* Users are required to show their seriousness by asking and accepting a Date Night request before communicating with video calling to set up the time and place.\r\n* In person dates are within your community only so that you can get back to using your instincts and getting to know your date in a familiar setting.\r\n* Users can enjoy and attend over 1000 events and activities listed in the platform to sweep your date off their feet.\r\n\r\nUpcoming features and benefits\r\n* In person Pop Ups hosted by I\u2019m Lonely at great local venues for couples and singles.\r\n* User suggested new functionality features for implementation\r\n* Pre-matched Local Business listings for date night suggestions\r\n\r\nIn the coming months, we will be asking you to vote on new enhancements and functionality to the platform that we believe will benefit your user experience. We want and need your opinion to make this platform one we can both be proud of and enjoy.\r\n \r\nIn the meantime, if you have any suggestions or issues you can contact us at https://imlonely.live/contact-us/ or via the app's feedback form as well. \r\n\r\nHappy Dating!\r\n\r\nBy downloading I\u2019m Lonely - My Community you agree to our terms of services which can be found at https://app.termly.io/policy-viewer/policy.html?policyUUID=fdf7b486-77da-4199-b062-e02c81a4f0d9\r\n\r\nLearn how I\u2019m Lonely - My Community does not sell your data to 3rd Party Companies and how your data is used at https://app.termly.io/policy-viewer/policy.html?policyUUID=2ebbcc13-8f44-43de-bd1a-dee8ba2a7cb1",
    "descriptionHTML": "I&#39;m Lonely, Inc. is a trailblazing company dedicated to addressing the growing issue of loneliness in modern society. Founded in early 2024 by a team of individuals who personally experienced the struggles of forming meaningful connections, I&#39;m Lonely, Inc. is committed to fostering authentic, in-person interactions within local communities. Frustrated by the shortcomings of traditional dating apps, which are often costly and plagued by fake profiles, the founders sought to create a genuine social platform for dating that everyone can use, including couples.<br><br>The app facilitates group hangouts, events, and dates, allowing users to form meaningful connections and engage in offline social activities. We firmly believe that personal relationships have a profound impact on an individual&#39;s happiness and mental health, which, in turn, can influence job satisfaction and productivity in your community. In an effort to improve the lives of our users and contribute to their overall well-being, we are committed to disrupting the dating industry and reshaping the narrative surrounding dating as an experience that is inclusive and beneficial for everyone.<br><br>Remember, to maintain a healthy relationship you must date your significant other!<br><br>SAFETY FEATURES<br>We provide the opportunity for all users to purchase a background pre-check which checks your information against the national criminal database to help protect the safety of our users. In addition, we do an identity check with your drivers license and a selfie to verify you are who you say you are and not a bot. Please take advantage of these features as this is how we keep our I&#39;m Lonely user community safe and thriving.<br><br>FOR COUPLES<br>* Users can find and search over 1000 events and activities for an awesome date night in your city, the most on any platform.<br>* Users can find and create new Hangouts with 3 or more users that share the same interests such as a book club, birthday party, or for a new band launch.<br>* Won\u2019t see any dating features<br><br>FOR SINGLES<br>* Your 30 sec introduction video is vital to allowing potential daters to connect and see your vibe and personality along with matching interests you both have in common<br>* Users are required to show their seriousness by asking and accepting a Date Night request before communicating with video calling to set up the time and place.<br>* In person dates are within your community only so that you can get back to using your instincts and getting to know your date in a familiar setting.<br>* Users can enjoy and attend over 1000 events and activities listed in the platform to sweep your date off their feet.<br><br>Upcoming features and benefits<br>* In person Pop Ups hosted by I\u2019m Lonely at great local venues for couples and singles.<br>* User suggested new functionality features for implementation<br>* Pre-matched Local Business listings for date night suggestions<br><br>In the coming months, we will be asking you to vote on new enhancements and functionality to the platform that we believe will benefit your user experience. We want and need your opinion to make this platform one we can both be proud of and enjoy.<br> <br>In the meantime, if you have any suggestions or issues you can contact us at https://imlonely.live/contact-us/ or via the app&#39;s feedback form as well. <br><br>Happy Dating!<br><br>By downloading I\u2019m Lonely - My Community you agree to our terms of services which can be found at https://app.termly.io/policy-viewer/policy.html?policyUUID=fdf7b486-77da-4199-b062-e02c81a4f0d9<br><br>Learn how I\u2019m Lonely - My Community does not sell your data to 3rd Party Companies and how your data is used at https://app.termly.io/policy-viewer/policy.html?policyUUID=2ebbcc13-8f44-43de-bd1a-dee8ba2a7cb1",
    "summary": "In person community based platform with local hangouts, events, and dating.",
    "installs": "1,000+",
    "minInstalls": 1000,
    "realInstalls": 1241,
    "score": 3.1,
    "ratings": 10,
    "reviews": 4,
    "histogram": [
        4,
        1,
        0,
        0,
        5
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$19.99 - $76.99 per item",
    "developer": "I'm Lonely, Inc",
    "developerId": "I'm+Lonely,+Inc",
    "developerEmail": "info@imlonely.live",
    "developerWebsite": "https://imlonely.live/contact-us/",
    "developerAddress": null,
    "privacyPolicy": "https://app.termly.io/policy-viewer/policy.html?policyUUID=2ebbcc13-8f44-43de-bd1a-dee8ba2a7cb1",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/8hS6Ag-5OveQANaJ-yvyxLqowc_Jf5Rax8IK62aIoa_T8huz3qt4jpoKcRCr2DYVoWM",
    "headerImage": "https://play-lh.googleusercontent.com/PzHBHEwx5tojcgwlps1MxclLOj4xxuIs6IJaEblO5zTAwdLN8wH9xDBmaK0siZoeCGw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/tQT_KZ49nJoDQBp2v7DDFvW7alkdb5hayIDmaXr2Clm8IP3bw_4q20gUItQiDNPqog",
        "https://play-lh.googleusercontent.com/2gWNI5dEBVZr-NEIvrMBk47dalL_GuYWV3dS5msuXVV7BPJf6TN8AqbXL2phE0oqmw",
        "https://play-lh.googleusercontent.com/YJpnATPRfb0gzmKuoSUmkLcPXxKa73LO7jpcq8KhJCtnLpyS3DM0fBJ1cgGDkkUUVh4",
        "https://play-lh.googleusercontent.com/hFVNJTCMzhQ_PXmeLkmh0keFpSToQ1kAjBAYhglpPDiesKSF6b0HcfA5VPtpQv2CyHdr",
        "https://play-lh.googleusercontent.com/7TAVVV-4sIJ1MeLUhlUxqglQsmlvg9T7d4SShNDm06U4C8fWNxSOAdHWVavqT37xXw",
        "https://play-lh.googleusercontent.com/G4tUcQL6RmxI9JwV8LMnFSdEXdwDsqnx0Ipxm0xEmrzhMk3XEzBtbQ0jWhrLIClIpA",
        "https://play-lh.googleusercontent.com/DgHfAfBvF2yjZtHjofTm4VL_M2matGOaZYyhJRkWDrQT_6USX__wkfYbY5GH2J9bD40"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 1, 2024",
    "lastUpdatedOn": "Oct 4, 2024",
    "updated": 1728041782,
    "version": "1.3.1",
    "comments": [],
    "appId": "com.imlonely.app",
    "url": "https://play.google.com/store/apps/details?id=com.imlonely.app&hl=en&gl=us"
}