{
    "title": "Glassdoor | Jobs & Community",
    "description": "Work meets life on the new Glassdoor app. Search jobs, company reviews, and salaries, and join real, anonymous talk with professionals like you. Ask the tough questions, and get career insights, answers, and more through candid conversations in Bowls \u2014 now featuring video, images, and polls. Stay linked in with coworkers and industry insiders, trade resume and interview tips, and engage with new Worklife Pros for expert takes on everyday topics in your work and life.\r\n\r\nThe new Glassdoor offers:\r\n\r\nWORKPLACE CONVERSATIONS\r\nFind your work people in Glassdoor communities. Talk anonymously about employers, industries, and interests, and follow new Worklife Pros for advice and inspiration backed by personal experience.\r\n\r\nSALARY TRANSPARENCY\r\nMake sure you\u2019re getting the salary you deserve. Glassdoor can help you discover what others in your position are making\u2014from entry-level to C-suite\u2014so you can negotiate with confidence.\r\n\r\nCOMPANY REVIEWS & RATINGS\r\nGet insights on everything from culture and compensation to leadership and work-life balance from employees who\u2019ve been there, done that.\r\n\r\nSIMPLIFIED JOB SEARCH & EASY APPLY\r\nAutomate your search and get job alerts for new postings that could be a good fit for you. Then, apply with a few quick taps.\r\n\r\nDIVERSITY & INCLUSION INSIGHTS\r\nFind a workplace that lets you be you. Filter company ratings by gender, race/ethnicity, sexual orientation, and more to find the most diverse and inclusive employers. Then, get a first-person perspective from your new professional community on Glassdoor.\r\n\r\nYour work people are here. Download the new Glassdoor app now. \r\nDo not sell my personal information: https://www.glassdoor.com/about/doNotSell.htm",
    "descriptionHTML": "Work meets life on the new Glassdoor app. Search jobs, company reviews, and salaries, and join real, anonymous talk with professionals like you. Ask the tough questions, and get career insights, answers, and more through candid conversations in Bowls \u2014 now featuring video, images, and polls. Stay linked in with coworkers and industry insiders, trade resume and interview tips, and engage with new Worklife Pros for expert takes on everyday topics in your work and life.<br><br>The new Glassdoor offers:<br><br>WORKPLACE CONVERSATIONS<br>Find your work people in Glassdoor communities. Talk anonymously about employers, industries, and interests, and follow new Worklife Pros for advice and inspiration backed by personal experience.<br><br>SALARY TRANSPARENCY<br>Make sure you\u2019re getting the salary you deserve. Glassdoor can help you discover what others in your position are making\u2014from entry-level to C-suite\u2014so you can negotiate with confidence.<br><br>COMPANY REVIEWS &amp; RATINGS<br>Get insights on everything from culture and compensation to leadership and work-life balance from employees who\u2019ve been there, done that.<br><br>SIMPLIFIED JOB SEARCH &amp; EASY APPLY<br>Automate your search and get job alerts for new postings that could be a good fit for you. Then, apply with a few quick taps.<br><br>DIVERSITY &amp; INCLUSION INSIGHTS<br>Find a workplace that lets you be you. Filter company ratings by gender, race/ethnicity, sexual orientation, and more to find the most diverse and inclusive employers. Then, get a first-person perspective from your new professional community on Glassdoor.<br><br>Your work people are here. Download the new Glassdoor app now. <br>Do not sell my personal information: https://www.glassdoor.com/about/doNotSell.htm",
    "summary": "Find jobs and talk careers",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 22163018,
    "score": 4.628846,
    "ratings": 348020,
    "reviews": 25176,
    "histogram": [
        8320,
        4043,
        16807,
        50126,
        268712
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Glassdoor LLC",
    "developerId": "Glassdoor+LLC",
    "developerEmail": "appfeedback@glassdoor.com",
    "developerWebsite": "https://www.glassdoor.com",
    "developerAddress": null,
    "privacyPolicy": "https://hrtechprivacy.com/brands/glassdoor#privacypolicy",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/FNk92EvS6pp9vcBKdEQFVxVuA7g5vXocGWS4zz1uVFkdBUYPExDbnw1Tet3jZA_kAg",
    "headerImage": "https://play-lh.googleusercontent.com/ufYF88HdGoilJ3i9vkxxXTcXTrcTfqZwPqtOlekqcZ2ZKmmSjoi9IKOoIT2uWkIXweR3",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Z7m9oPK_R56r8-MHygDsBI0eQRfwq3YKaRY4Xran-2QjUfykdy7sl372CcIVM3xlOg",
        "https://play-lh.googleusercontent.com/4KQDKSb9SciAJElha_IxM9WaYbYTGv9hawYUt5mTV3qWesCdM8PnpQPRwucXWjN5e-I",
        "https://play-lh.googleusercontent.com/ui8g8x0qVOQ9KNrFzjtUenMOj_A5uSrW1i0nh-YESXUgivOOsdANqRquvbzBA9f2bw",
        "https://play-lh.googleusercontent.com/Q93O--lI88FlGtJUT2Cr2v3HAekAxXZUwysvXBzbowyrT6Qf6KiuxQJi8_ub5bqOo6us",
        "https://play-lh.googleusercontent.com/OyGuqn33gsx5qOH7mrJ76EPnVMmGG-EWXc2dtiFxa-lCXvg1pSrTFfSzQkvLHMdPwOMt"
    ],
    "video": "https://www.youtube.com/embed/48z3SQwryx8?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/ufYF88HdGoilJ3i9vkxxXTcXTrcTfqZwPqtOlekqcZ2ZKmmSjoi9IKOoIT2uWkIXweR3",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 13, 2013",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729515562,
    "version": "11.14.0",
    "comments": [],
    "appId": "com.glassdoor.app",
    "url": "https://play.google.com/store/apps/details?id=com.glassdoor.app&hl=en&gl=us"
}