{
    "title": "Wonder Beauties",
    "description": "Treat your skin and hair with free consultations from our team of pharmacists and doctors! The first online store in Iraq that provides original products with a full medical staff ready to help you choose the right products for you after evaluating your skin, choosing the right products, and providing a unique experience designed specifically for you.\r\nWe provide original and reliable products and provide a warranty with all products in your order\r\nNo more fear of counterfeit products, Wonder offers you a guarantee!\r\nSince 2022, more than 66 thousand consultations and 118 thousand requests have been provided\r\nWe were rated by 4233 reviewers at 4.8/5\r\n3 reasons why you should join us\r\n1- We will provide products carefully selected for you by female specialists\r\n2- You will be reassured of the widespread counterfeit products\r\n3-You will get all of this online from the comfort of your home!\r\n\r\nDownload the application and start your journey now and shop in our store, which provides you with all types of products, including skin, hair, perfumes, personal care products, tools and devices for hair and skin.",
    "descriptionHTML": "Treat your skin and hair with free consultations from our team of pharmacists and doctors! The first online store in Iraq that provides original products with a full medical staff ready to help you choose the right products for you after evaluating your skin, choosing the right products, and providing a unique experience designed specifically for you.<br>We provide original and reliable products and provide a warranty with all products in your order<br>No more fear of counterfeit products, Wonder offers you a guarantee!<br>Since 2022, more than 66 thousand consultations and 118 thousand requests have been provided<br>We were rated by 4233 reviewers at 4.8/5<br>3 reasons why you should join us<br>1- We will provide products carefully selected for you by female specialists<br>2- You will be reassured of the widespread counterfeit products<br>3-You will get all of this online from the comfort of your home!<br><br>Download the application and start your journey now and shop in our store, which provides you with all types of products, including skin, hair, perfumes, personal care products, tools and devices for hair and skin.",
    "summary": "Treat your skin and hair with free consultations from our team of pharmacists and doctors!",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 152832,
    "score": 4.428571,
    "ratings": 240,
    "reviews": 7,
    "histogram": [
        11,
        0,
        34,
        22,
        171
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "WonderBeautiesIRQ",
    "developerId": "WonderBeautiesIRQ",
    "developerEmail": "mouayad@wonderbeauties.com",
    "developerWebsite": null,
    "developerAddress": null,
    "privacyPolicy": "https://wonderbeauties.love/policies/privacy-policy",
    "genre": "Beauty",
    "genreId": "BEAUTY",
    "categories": [
        {
            "name": "Beauty",
            "id": "BEAUTY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/pJSSh5cnNngXia4mQhz8HdovKHVYxiRSysh5yRSjVLpFgSv8ikkXwqWpKXagKpRh6Mw",
    "headerImage": "https://play-lh.googleusercontent.com/K8L9MMGLe0KuN9diHbaYyRt_YmZTZegPdbL9CTL5Dff2V9oWHPR85vjCyp3mqKcpGUzr",
    "screenshots": [
        "https://play-lh.googleusercontent.com/F3AJJnD01TfwSjdg-Al8b9Vd6yqhFJmtorchC6Ip9krvPuY8X9Sib5dWBZxQiSwUTeHu",
        "https://play-lh.googleusercontent.com/7l2Mn1xjo4jx8aDr64BO03tPnWbVft2MwyYmwd3s6uYT42BrSkROGsFUqjOgrj3BdnY",
        "https://play-lh.googleusercontent.com/z_qXSIyddrtlM1cBAyChrK-puSyHC5iiH4uDnAsczI6tTSfADNQkb_TUPP02Mp2aEzs",
        "https://play-lh.googleusercontent.com/6D55xo8nlY41o-3DhY9OKNjauEuCqM6PgkOejU2LvVBu7M8tw45qvFLDcUxKSWX4YaE",
        "https://play-lh.googleusercontent.com/uKyItsnYTZCa3AoBq-uiJGdSxqRP1w9QD6m3q3c1EQEvNTdsptnD5TqlxIkM80FjiN-w",
        "https://play-lh.googleusercontent.com/DUAQpA5vRP7_zlXTJec-_yxRmeQwoHm5LWnb2cQRDAzwON8sAV4UgYfxhR-VdUjHjt4",
        "https://play-lh.googleusercontent.com/w5OcFvT2HMgoXJdbE4pUbAj7zmUt2SY-oGIm8nO1tYD2ivW7WFMWARMwLwtGHC0Khg0k",
        "https://play-lh.googleusercontent.com/SY8S_73KwfYTMT5FPlPP8x2j8iBfqp03pWy-z3tOOOiy-bvC2siwXnbeH8znhkxcVg",
        "https://play-lh.googleusercontent.com/l4yGXyl4euDI_w4u4g9VTnbNJwg3ZU9x6MRUZ2m--o70Y_poebocgzuHNquIzcTjXFo_",
        "https://play-lh.googleusercontent.com/8BYpsCda7bg91IDEJ4MfMg-KZbtPLIY8Q_qlEM8ATiVo4wOrwhmt5ADF1RGnJwv3hdQ",
        "https://play-lh.googleusercontent.com/q-_UOFf9CqwCzbCjWeUSLbOFmU8LNimqz9gdOUNmc01ZgTp60E137k2UPyZ_gZe-ams",
        "https://play-lh.googleusercontent.com/oG-retLBlv03AOU8o2rHtajEzQKGFwUEUeOVYzRYy1yrTioen3_rndOaE1cvWeIh1w",
        "https://play-lh.googleusercontent.com/TgMzvVeYizh8Hu4PWWxSG-zuN_ZLeWH4lM3mIVY4QGwdJnuj42GsV4pPdxXZGyAGjFs",
        "https://play-lh.googleusercontent.com/AsKSHRu7UbZipyWSJYZAgh_sKGe2JfL3k3aXgEZkQatWCp3Eh9TCpNoQd2NZj8zxeKI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 9, 2024",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729000687,
    "version": "1.5.6",
    "comments": [],
    "appId": "com.wonderbeauties.app",
    "url": "https://play.google.com/store/apps/details?id=com.wonderbeauties.app&hl=en&gl=us"
}