{
    "title": "FANFUT",
    "description": "FANFUT is a sports application that will keep you up to date on everything that happens in football, minute by minute. We offer you an easy-to-use interface that allows you to navigate through various sections, you can access all the latest news, statistics and match reports. Do not wait more! DOWNLOAD FANFUT!",
    "descriptionHTML": "FANFUT is a sports application that will keep you up to date on everything that happens in football, minute by minute. We offer you an easy-to-use interface that allows you to navigate through various sections, you can access all the latest news, statistics and match reports. Do not wait more! DOWNLOAD FANFUT!",
    "summary": "Sports application that informs you about everything about football minute by minute.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 119972,
    "score": 4.9772725,
    "ratings": 265,
    "reviews": 18,
    "histogram": [
        0,
        0,
        0,
        6,
        258
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "WSports",
    "developerId": "WSports",
    "developerEmail": "contacto@fanfut.com",
    "developerWebsite": "https://fanfutv.blogspot.com/",
    "developerAddress": null,
    "privacyPolicy": "https://www.app-privacy-policy.com/live.php?token=gV0yklDvgJVVpMdlqkrF09tbka26iPZw",
    "genre": "Sports",
    "genreId": "SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Yacn2fkye6UM_FmM3S7S92bqkGTH7z5cazeCro0VcdM4O6Z5s06oF4Wuner2M8A1VLY",
    "headerImage": "https://play-lh.googleusercontent.com/SykzMhwnMLVYdd7bocd1mjtSDmW6BznpLNZceB71RVp1fxHGgHkcFL8mmC-4LZ7wYTYS",
    "screenshots": [
        "https://play-lh.googleusercontent.com/QzZ8pmn5NS5ZqO7uudroTiSHNnRCSujRCcIcWxUdddo2ndrvQ-SBdEu7Mq7fu-pugD4",
        "https://play-lh.googleusercontent.com/k1dwdfNY8298VuuCDwX8JowkhA0BQWKN4hx8s_1JkpebWmAOcfD8m0Q5IFgunInBVw",
        "https://play-lh.googleusercontent.com/1bCuPK5gAlwKJkNEenGV4acDW3zE9VYlfLep9_BVDMujisiFjXv-5T8OtyIkxpACp3M",
        "https://play-lh.googleusercontent.com/LZsvr0g38yfZwAyv_YcpCxn23xbCrb0NNJW5lYXQf8bBEu-ksP5HMAqJsRlIQjpGyg",
        "https://play-lh.googleusercontent.com/ygZV_fF2Ma5VXZR8e02D6a4TPaSv8W7P7W2EygZYp2l_Osbz-RZVENNI8JVHJeizEw",
        "https://play-lh.googleusercontent.com/rYrMEBul7TLNecdVTOppoBHqLNH10ipbC5NQY83l33Em0SSySBeBRO2p7jNxKz9G2rQ",
        "https://play-lh.googleusercontent.com/HA6-TAuysM_-9frozUrCm7XRhh5qqHhJ1CCXSTznWCDeq7N-fwQ3Cq6P-R0b49zy_aw",
        "https://play-lh.googleusercontent.com/vwLUfL96RypQf4VQFIlJFDGIRf6fwAj4kwxwMZM65qhTPe59jmu_NLVZuPbzZVzpCDM",
        "https://play-lh.googleusercontent.com/opJ4jb4HuA6f5TZPAr8Fzjz2DicFjiUxMKbOB4G5c0rV0CfiiOq6EPUIdmwpBtle8yk_",
        "https://play-lh.googleusercontent.com/gAgomFRI06qNmz39dwA_PCfvlSJvRRrJ2KKU34o7MXisou3tGUa4GGaZuTp2I9TNlgVc"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 1, 2024",
    "lastUpdatedOn": "Sep 6, 2024",
    "updated": 1725683342,
    "version": "1.0.3",
    "comments": [],
    "appId": "com.fanfut.app",
    "url": "https://play.google.com/store/apps/details?id=com.fanfut.app&hl=en&gl=us"
}