{
    "title": "BTCC - Trade Bitcoin & Crypto",
    "description": "Welcome to BTCC! Our app provides you with a safe and secure environment to trade crypto with the lowest fees in town and up to 250x leverage. Get started today!\r\n\r\nIn addition to the major digital currencies like BTC, ETH, BCH, LINK, LTC, ADA, DOT, EOS, XRP, and UNI, you can also trade DOGE, SHIB, FIL, XLM, XMR, GRT, RNDR, EGLD, and KLAY on our platform. We offer flexible leverage up to 250x across daily and perpetual contract types, allowing you to adjust your positions to meet your trading needs and goals.\r\n\r\n*************************\r\nFEATURE HIGHLIGHTS\r\n*************************\r\nEASY THIRD-PARTY LOGIN: Register and log in to your BTCC account with ease using third-party login options such as Facebook and Google.\r\n\r\nLOW-COST TRADING: BTCC probably offers one of the lowest transaction fees in the industry\u2014only 0.045% per trade! What\u2019s more, you can earn coupons from campaigns to cover the trading fees.\r\n\r\nTRADE CRYPTO WITH LEVERAGE: Use our flexible leverage to your advantage and trade with up to 250x leverage on BTC, XRP, ETH, ARB, DOGE, SOL, ACH, XMR, GRT, RNDR, EGLD, KLAY and other popular cryptocurrencies. We offer both USDT-margined and coin-margined futures.\r\n\r\nTRADE COMMODITIES & STOCKS WITH USDT: BTCC offers tokenized futures on traditional commodities like gold and silver and stocks like Apple, Google, Meta, Microsoft, Netflix, and Tesla. With BTCC, it\u2019s time to say goodbye to multiple accounts on different exchanges and manage your portfolios all in one place.\r\n\r\nDEPOSIT WITH CREDIT CARDS: Making a deposit is easy on BTCC - we accept both Visa & Mastercard for payments. You can also fund your account through third-party payment gateways such as Simplex and MoonPay.   \r\n\r\nSPEEDY CRYPTO DEPOSITS & WITHDRAWALS: BTCC supports a wide range of cryptos for deposits and withdrawals. Aside from popular options like BTC, USDT, and ETH, we also accept deposits and withdrawals in AAVE, DOGE, SOL, BNB, ETC, GMT, MANA,, MASK, and many other popular cryptos.\r\n\r\nEXCITING VIP PROGRAMME: Get discounts on trading fees, withdrawal and conversion fees as you level up through the VIP tiers. Enjoy exclusive perks such as birthday gifts and branded merchandise when you become a VIP4 user or above!\r\n\r\nDEMO TRADING: New to crypto? We\u2019ve got you covered. Our non-expiring demo trading function allows you to practise trading the real market with 100,000 USDT virtual funds.\r\n\r\n*****************************\r\nPROMOTIONS & REWARDS\r\n*****************************\r\nWELCOME BONUS: Get a 10 USDT coupon when you register on our platform. \r\n\r\nREFER A FRIEND: Invite friends to BTCC to trade and get up to 530 USDT for each referral. When your friends trade, you can get a 25% rebate on their trading fees as a reward. Another plus point\u2014your friends can get rewarded too.\r\n\r\n***************\r\nWHY BTCC?\r\n***************\r\n13 years of trust & reliability: BTCC is the world's longest-running digital currency exchange, providing safe and secure trading services for crypto enthusiasts all around the globe. \r\n\r\nA platform built for everyone: We offer demo trading, which allows beginners to familiarise themselves with the crypto market. On the other hand, our high levels of market liquidity, instant trade execution, as well as VIP trader programme satisfy the needs of seasoned traders.\r\n\r\n*************\r\nAbout BTCC\r\n*************\r\nBTCC currently offers over 300 cryptocurrency pairs, including Bitcoin, Litecoin, Ethereum, and more. With an intuitive app interface and high levels of liquidity on our platform, BTCC is trusted by millions of crypto enthusiasts from around the world.\r\n*************************************\r\nFollow us for the latest crypto news!\r\n*************************************\r\nOfficial website: https://www.btcc.com/ \r\nEmail: support@btcc.com  \r\nTwitter: @YourBTCC\r\nInstagram: @btccbitcoin\r\nYouTube: https://www.youtube.com/c/BTCCOfficial2011 \r\nBusiness Address: Vilnius, Giruli\u0173 str. 10-201, Lithuania, LT-12112",
    "descriptionHTML": "Welcome to BTCC! Our app provides you with a safe and secure environment to trade crypto with the lowest fees in town and up to 250x leverage. Get started today!<br><br>In addition to the major digital currencies like BTC, ETH, BCH, LINK, LTC, ADA, DOT, EOS, XRP, and UNI, you can also trade DOGE, SHIB, FIL, XLM, XMR, GRT, RNDR, EGLD, and KLAY on our platform. We offer flexible leverage up to 250x across daily and perpetual contract types, allowing you to adjust your positions to meet your trading needs and goals.<br><br>*************************<br>FEATURE HIGHLIGHTS<br>*************************<br>EASY THIRD-PARTY LOGIN: Register and log in to your BTCC account with ease using third-party login options such as Facebook and Google.<br><br>LOW-COST TRADING: BTCC probably offers one of the lowest transaction fees in the industry\u2014only 0.045% per trade! What\u2019s more, you can earn coupons from campaigns to cover the trading fees.<br><br>TRADE CRYPTO WITH LEVERAGE: Use our flexible leverage to your advantage and trade with up to 250x leverage on BTC, XRP, ETH, ARB, DOGE, SOL, ACH, XMR, GRT, RNDR, EGLD, KLAY and other popular cryptocurrencies. We offer both USDT-margined and coin-margined futures.<br><br>TRADE COMMODITIES &amp; STOCKS WITH USDT: BTCC offers tokenized futures on traditional commodities like gold and silver and stocks like Apple, Google, Meta, Microsoft, Netflix, and Tesla. With BTCC, it\u2019s time to say goodbye to multiple accounts on different exchanges and manage your portfolios all in one place.<br><br>DEPOSIT WITH CREDIT CARDS: Making a deposit is easy on BTCC - we accept both Visa &amp; Mastercard for payments. You can also fund your account through third-party payment gateways such as Simplex and MoonPay.   <br><br>SPEEDY CRYPTO DEPOSITS &amp; WITHDRAWALS: BTCC supports a wide range of cryptos for deposits and withdrawals. Aside from popular options like BTC, USDT, and ETH, we also accept deposits and withdrawals in AAVE, DOGE, SOL, BNB, ETC, GMT, MANA,, MASK, and many other popular cryptos.<br><br>EXCITING VIP PROGRAMME: Get discounts on trading fees, withdrawal and conversion fees as you level up through the VIP tiers. Enjoy exclusive perks such as birthday gifts and branded merchandise when you become a VIP4 user or above!<br><br>DEMO TRADING: New to crypto? We\u2019ve got you covered. Our non-expiring demo trading function allows you to practise trading the real market with 100,000 USDT virtual funds.<br><br>*****************************<br>PROMOTIONS &amp; REWARDS<br>*****************************<br>WELCOME BONUS: Get a 10 USDT coupon when you register on our platform. <br><br>REFER A FRIEND: Invite friends to BTCC to trade and get up to 530 USDT for each referral. When your friends trade, you can get a 25% rebate on their trading fees as a reward. Another plus point\u2014your friends can get rewarded too.<br><br>***************<br>WHY BTCC?<br>***************<br>13 years of trust &amp; reliability: BTCC is the world&#39;s longest-running digital currency exchange, providing safe and secure trading services for crypto enthusiasts all around the globe. <br><br>A platform built for everyone: We offer demo trading, which allows beginners to familiarise themselves with the crypto market. On the other hand, our high levels of market liquidity, instant trade execution, as well as VIP trader programme satisfy the needs of seasoned traders.<br><br>*************<br>About BTCC<br>*************<br>BTCC currently offers over 300 cryptocurrency pairs, including Bitcoin, Litecoin, Ethereum, and more. With an intuitive app interface and high levels of liquidity on our platform, BTCC is trusted by millions of crypto enthusiasts from around the world.<br>*************************************<br>Follow us for the latest crypto news!<br>*************************************<br>Official website: https://www.btcc.com/ <br>Email: support@btcc.com  <br>Twitter: @YourBTCC<br>Instagram: @btccbitcoin<br>YouTube: https://www.youtube.com/c/BTCCOfficial2011 <br>Business Address: Vilnius, Giruli\u0173 str. 10-201, Lithuania, LT-12112",
    "summary": "Cryptocurrency Futures and Perpetual Trading Platform",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1600725,
    "score": 4.658754,
    "ratings": 8522,
    "reviews": 1090,
    "histogram": [
        504,
        75,
        75,
        504,
        7356
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "BTCC.COM",
    "developerId": "BTCC.COM",
    "developerEmail": "support@btcc.com",
    "developerWebsite": "https://www.btcc.com/en-US",
    "developerAddress": null,
    "privacyPolicy": "https://www.btcc.com/en-US/detail/142638",
    "genre": "Finance",
    "genreId": "FINANCE",
    "categories": [
        {
            "name": "Finance",
            "id": "FINANCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/TQ6AHm38YF_7o_oK03OBKIEdW-YFbUna53cj0v23I9hsI5HNioF-Ubg1K3v0QOiHiM90",
    "headerImage": "https://play-lh.googleusercontent.com/Vi_Kbl6zuTfqh0laYIQCrDmgRvw3QSgBTZUwwtil9-X7dSKnOjIrzuSj8t__wooaoio",
    "screenshots": [
        "https://play-lh.googleusercontent.com/QXW6ZvVdz6vcqlCuNC2h3Ba_GUnc7n7Swv6TYpzX6khSY2-MtDMfuryJ7DMDlOvzkls",
        "https://play-lh.googleusercontent.com/VnWHytGyNu9Kh1M_X6knxEbNV6r3Qm9h2eG1L0Y1dSmxw-5HdTZHz1oTH5t5SDjwwUU",
        "https://play-lh.googleusercontent.com/gdwHROO9DM5vB2lECyfXVT0GLx-4t8yNz4RmzwmH1A_feftumy864A0A_rxPHpMJCA",
        "https://play-lh.googleusercontent.com/iDeLsBha8z02-6WKpgo_VUSyJFDxDRplOUxGxA8pZBwZflMLWNOCpE4-yo5OLUpFA08",
        "https://play-lh.googleusercontent.com/cUN5b4LS_tl4jipQsIqM4fcCM0kopz6c6lGm-9ztJMz00khyqv4wYxp4loimdc6IxEs",
        "https://play-lh.googleusercontent.com/U-V4gj42nHNjayvPFQCJrSx9StrSDlUuc58guhHKD4_9tR6Ajh3Kje8WehWGOoV29w"
    ],
    "video": "https://www.youtube.com/embed/NbSnemPp-NQ?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/Vi_Kbl6zuTfqh0laYIQCrDmgRvw3QSgBTZUwwtil9-X7dSKnOjIrzuSj8t__wooaoio",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 4, 2020",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729157570,
    "version": "8.7.5",
    "comments": [],
    "appId": "com.btcc.hy",
    "url": "https://play.google.com/store/apps/details?id=com.btcc.hy&hl=en&gl=us"
}