{
    "title": "First Priority of South FL",
    "description": "View meeting details, weekly devotionals, and connect and get reminders when your First Priority Club meets.",
    "descriptionHTML": "View meeting details, weekly devotionals, and connect and get reminders when your First Priority Club meets.",
    "summary": "Stay connected to First Priority",
    "installs": "500+",
    "minInstalls": 500,
    "realInstalls": 916,
    "score": 5,
    "ratings": 7,
    "reviews": 0,
    "histogram": [
        0,
        0,
        0,
        0,
        7
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Digital Church Limited",
    "developerId": "Digital+Church+Limited",
    "developerEmail": "contact@firstpriority.cc",
    "developerWebsite": "https://firstpriority.cc",
    "developerAddress": null,
    "privacyPolicy": "https://firstpriority.app/privacy/",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/FL_107FQnjyU9WTZG18KyT_eYZDMrxwJvtf5233scN2AIXPmLGghQ65I4F3WYoONvQ",
    "headerImage": "https://play-lh.googleusercontent.com/ojtx0fhisazeQ8niPC_CB8vgw34oHcldsis3hRhPVDetui8teaOyFObV8zFuCiLS3dw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/2_-krbs7qV1nVg0Gx2aYe96EO28vZex27EDzszMKxFiX3R2YwwkckxUenfMwET7B1i0",
        "https://play-lh.googleusercontent.com/SH5Z9H6t9MoNeC9xWX0VN-YpWW7aIa8GDLIrShPqwoyjSEHaWm4Gw49HV8ApzD0tHU8o",
        "https://play-lh.googleusercontent.com/HIMrREKeovjs_iLRNzs5cNxBAioo4mT7V60fMnR1n9z-eHTb7vqW1MPVHu37SIe6Ftk",
        "https://play-lh.googleusercontent.com/owXLAOU5jTH5R1xj-L1xLRDjL9M7iqtRtRemSTRpZFmWv_GZgLK7sGNG__OR_-pLtCW8",
        "https://play-lh.googleusercontent.com/wxXxV0O7_V-NbkzUOrDqYbWZgDQcXMAxJYTpLCzrsXa3GXUk5HMKkRPnpmUOKoQzEA",
        "https://play-lh.googleusercontent.com/4BiYYhfTL_mAOBhaUHxs5LBXF2dC-iwLqZpJdQKYBMejSWc4czvzXjSmt0L9ExDj7CYb",
        "https://play-lh.googleusercontent.com/81SfytqriBwb1r53H74GNw6Dhsj-H9rqydEkHC3Z26_xVW27j1rmGquuoUnHSgtRPT8",
        "https://play-lh.googleusercontent.com/OGYGqx4Cmth_R0g5ImB9tPc7axJw9CPcJxc1fi-A9crWoEhdScSZBL1V8PZJrWjjiMI",
        "https://play-lh.googleusercontent.com/KVXekBEiauXyihkxbFeyxBNF5Y0EpaU3n7xxPCNG1Wi8lNZv5EkGNEa3mtXhhkV_6Q8"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 2, 2021",
    "lastUpdatedOn": "Sep 23, 2023",
    "updated": 1695508417,
    "version": "1.0.9",
    "comments": [],
    "appId": "com.firstpriority.core.app",
    "url": "https://play.google.com/store/apps/details?id=com.firstpriority.core.app&hl=en&gl=us"
}