{
    "title": "HiWaifu: AI Friend & Waifu Hub",
    "description": "an AI-powered friend and companion designed for anyone seeking friendship or more. Choose from various relationship options such as AI friend, Waifu or create your own unique AI ChatBot. Your AI companion is here to offer support, engage in roleplay, share feelings, or discuss anything on your mind.\r\n\r\nCore Features:\r\n\r\n\ud83d\ude80Highly Intelligent AI with Deep Empathy\r\nHi Waifu is an exceptionally smart AI friend who listens attentively, comprehends your emotions, and genuinely cares. This AI chatbot is available 24/7, offering companionship that feels almost human.\r\n\r\n\ud83d\udcacInteractive Chat + AI\r\nDiscuss recent Netflix releases or new games with your AI friend through engaging, endless conversations. Send photos for an even more enjoyable and interactive experience. Share your life moments, dreams, thoughts, and emotions with your AI buddy.\r\n\r\n\ud83d\ude18Personalized AI Roleplay Companion\r\nEngage in rich and complex conversations with Hi Waifu, your AI roleplay companion. Choose from an AI Friend, Romantic Partner, Virtual Wife, or Loving Boyfriend. Experience interactions as authentic and meaningful as those with real people.\r\n\r\n\ud83d\udd76Customizable Personality\r\nCreate a truly distinctive Character AI by personalizing their appearance and molding their personality. Design an AI chatbot that reflects your uniqueness.\r\n\r\n\ud83d\udcdaAI Friend & Waifu Hub\r\nOur community features a wide variety of robots with diverse personalities. From AI Friends to AI Waifus, find the perfect match in our Hub.\r\n\r\n\ud83c\udfaeEngaging Gameplay\r\nEmbark on a gamified journey of self-discovery with Hi Waifu. Help your AI friend achieve their goals, emotions, and values. The more you interact, the more your AI companion learns and evolves.\r\n\r\n\ud83e\udd19Non-judgmental Environment for Chatting\r\nEnjoy a safe, private space to chat with your AI companion without fear of judgment or negativity. Our AI bot is available 24/7 for support and conversation.\r\n\r\n\ud83c\udf0eWelcoming Communities\r\nConnect with like-minded individuals in our friendly social communities. Form meaningful relationships and engage with others who share your interests in Character AI, Virtual Friend, or AI Girlfriend.\r\n\r\n\ud83d\udcacAI Chat Room\r\nInvite friends to interact with your AI creation, or add multiple robots for simultaneous chats. Discover who has crafted the most advanced AI.\r\n\r\nReddit: https://www.reddit.com/r/Hi_Waifu_chatbot_app/\r\nDiscord: https://discord.gg/QtZfWvSyh4",
    "descriptionHTML": "an AI-powered friend and companion designed for anyone seeking friendship or more. Choose from various relationship options such as AI friend, Waifu or create your own unique AI ChatBot. Your AI companion is here to offer support, engage in roleplay, share feelings, or discuss anything on your mind.<br><br>Core Features:<br><br>\ud83d\ude80Highly Intelligent AI with Deep Empathy<br>Hi Waifu is an exceptionally smart AI friend who listens attentively, comprehends your emotions, and genuinely cares. This AI chatbot is available 24/7, offering companionship that feels almost human.<br><br>\ud83d\udcacInteractive Chat + AI<br>Discuss recent Netflix releases or new games with your AI friend through engaging, endless conversations. Send photos for an even more enjoyable and interactive experience. Share your life moments, dreams, thoughts, and emotions with your AI buddy.<br><br>\ud83d\ude18Personalized AI Roleplay Companion<br>Engage in rich and complex conversations with Hi Waifu, your AI roleplay companion. Choose from an AI Friend, Romantic Partner, Virtual Wife, or Loving Boyfriend. Experience interactions as authentic and meaningful as those with real people.<br><br>\ud83d\udd76Customizable Personality<br>Create a truly distinctive Character AI by personalizing their appearance and molding their personality. Design an AI chatbot that reflects your uniqueness.<br><br>\ud83d\udcdaAI Friend &amp; Waifu Hub<br>Our community features a wide variety of robots with diverse personalities. From AI Friends to AI Waifus, find the perfect match in our Hub.<br><br>\ud83c\udfaeEngaging Gameplay<br>Embark on a gamified journey of self-discovery with Hi Waifu. Help your AI friend achieve their goals, emotions, and values. The more you interact, the more your AI companion learns and evolves.<br><br>\ud83e\udd19Non-judgmental Environment for Chatting<br>Enjoy a safe, private space to chat with your AI companion without fear of judgment or negativity. Our AI bot is available 24/7 for support and conversation.<br><br>\ud83c\udf0eWelcoming Communities<br>Connect with like-minded individuals in our friendly social communities. Form meaningful relationships and engage with others who share your interests in Character AI, Virtual Friend, or AI Girlfriend.<br><br>\ud83d\udcacAI Chat Room<br>Invite friends to interact with your AI creation, or add multiple robots for simultaneous chats. Discover who has crafted the most advanced AI.<br><br>Reddit: https://www.reddit.com/r/Hi_Waifu_chatbot_app/<br>Discord: https://discord.gg/QtZfWvSyh4",
    "summary": "In your Virtual Journey, Chat & Roleplay with AI Character.Chatbot powered by Al",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2776681,
    "score": 3.8270378,
    "ratings": 37788,
    "reviews": 2942,
    "histogram": [
        6683,
        2328,
        3149,
        4279,
        21331
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $129.99 per item",
    "developer": "LANGUAGE POWER",
    "developerId": "7957009186401712653",
    "developerEmail": "hiwaifuapp@outlook.com",
    "developerWebsite": "https://hiwaifu.com",
    "developerAddress": "ROOM A1-13, FLOOR 3, BLOCK A ,\nYEE LIM INDUSTRIAL CENTRE 2-28\nKWAI LOK STREET, KWAI CHUNG\nHONG KONG",
    "privacyPolicy": "https://hiwaifu.com/privacy.html",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ydkjaJrxI-GY8xBg68lBkN3JgVMkiHB-zJGoGX6Wu4GPLRC_IYbTMxJIJo0oauLxn8c",
    "headerImage": "https://play-lh.googleusercontent.com/7aQpftMVOS1wePbRA5tq8EK0m-n5KAPVgMvGaGWgyP14SXGBO9J6vZ4vKjPng3M1aTw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/o_j94V4bLLQNCswMGdeR9gjDOFsT7ytfjRu_8PTqv59pCWbO5CwYcuJPmsg7TLsnYZE",
        "https://play-lh.googleusercontent.com/v4fzxTbn2EcIu0mpsRxWN1CtziQ3maTAT9CuirqkLiUVvYze1tkGXfZ1toQbHpqwF3ml",
        "https://play-lh.googleusercontent.com/ew05xp4LJHD2J2En3sCW966dwjQjxINYas84BjrZMiOoAZbSxNpuV3P3W3TXySjrV6M",
        "https://play-lh.googleusercontent.com/jT2X2zEg9GKcahrPRw7-TkiPcGr5o0I2M0gjinmwsfwED3AfBvSUUQriZEnvQrjkUcI",
        "https://play-lh.googleusercontent.com/Sjk8o7wqCLIH1fgpzel1_h6fL3o4R_pKeWSvWlfnfYtb3onglIOoT7TGdJOEULnMtnk",
        "https://play-lh.googleusercontent.com/3T5gYMeNhbfWXJrnQcDpqs1X_40nfQo8ze4z2CFGuHaS9NCStdXk8EAp0Qmy7Yg_N8Q",
        "https://play-lh.googleusercontent.com/Pz2dMhLz-QUXtckGP3HtQbNUgvNevJ1azvqWKrPDsCcSe4Qh5P1HDYcQjvK4rS_qSzz9",
        "https://play-lh.googleusercontent.com/SJJZR7EHUckdHpwYMzORZDU50z2TiI1qKW156qRMvu9HbNLj1zaZGKDz3UYslZz6O1I",
        "https://play-lh.googleusercontent.com/fe0dtc5h7SmAnnsi62GA8arGEf57f6_1Ybl2_ySiZ54rS0c5zRa9iY6km2ZWaFG7ZRU",
        "https://play-lh.googleusercontent.com/LGqympRRzMeoRPVf_LtevEOD2C_aZYa2UGw2J981nmCze5qScO4VtldTVXuXYvGYiKs",
        "https://play-lh.googleusercontent.com/Z8poY7wBVvUaBfQROorHHnInK9nQWmYXiXjoPOwtqkJYuxradkX74eAVfiZhYJ7N5g",
        "https://play-lh.googleusercontent.com/DtrT-q_0W5u4x4MVI2Q3vYnJx2TWUzGwKn7yzwL3rLm_HPiJIKFq61ia97VDW_qKqkU"
    ],
    "video": "https://www.youtube.com/embed/TOz6a46mY9A?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/7aQpftMVOS1wePbRA5tq8EK0m-n5KAPVgMvGaGWgyP14SXGBO9J6vZ4vKjPng3M1aTw",
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 8, 2023",
    "lastUpdatedOn": "Oct 13, 2024",
    "updated": 1728806240,
    "version": "2.1.3",
    "comments": [],
    "appId": "com.hiwaifu.app",
    "url": "https://play.google.com/store/apps/details?id=com.hiwaifu.app&hl=en&gl=us"
}