{
    "title": "Idle Island Builder",
    "description": "Dive into the ultimate relaxation of island building in this captivating casual game! Start by reclaiming the sea and crafting your own paradise from scratch. Transform the watery expanse into lush green landscapes adorned with trees, and construct magnificent buildings to create a bustling island full of life. With simple and intuitive gameplay, immerse yourself in the tranquil beauty of the ocean as you shape and expand your dream island. Unleash your creativity and build the perfect haven in this delightful and addictive idle game!",
    "descriptionHTML": "Dive into the ultimate relaxation of island building in this captivating casual game! Start by reclaiming the sea and crafting your own paradise from scratch. Transform the watery expanse into lush green landscapes adorned with trees, and construct magnificent buildings to create a bustling island full of life. With simple and intuitive gameplay, immerse yourself in the tranquil beauty of the ocean as you shape and expand your dream island. Unleash your creativity and build the perfect haven in this delightful and addictive idle game!",
    "summary": "Build Your Dream Island!",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 656796,
    "score": 4.3235292,
    "ratings": 3508,
    "reviews": 114,
    "histogram": [
        205,
        31,
        410,
        616,
        2233
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $99.99 per item",
    "developer": "Solid Games",
    "developerId": "Solid+Games",
    "developerEmail": "linluolan66@gmail.com",
    "developerWebsite": "https://www.solidgameinc.com/",
    "developerAddress": "11/F,WANG FAI INDUSTRIAL BUILDING,29 LUK HOP STREET,HONG KONG",
    "privacyPolicy": "https://solidgameinc.com/privacy.html",
    "genre": "Casual",
    "genreId": "GAME_CASUAL",
    "categories": [
        {
            "name": "Casual",
            "id": "GAME_CASUAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/r-utXPVfryVlDJXcHyiFyjZnxFBRpavUHS7ecECygDcObhsVZtaJx6JGvdPDudWYZw",
    "headerImage": "https://play-lh.googleusercontent.com/UG1VVdEJvRGwUQRGL8p2Tk-DficZbHyfHRRP_Z_3j9Q4KVLTQOlei9cvbpXZI2wyIjnC",
    "screenshots": [
        "https://play-lh.googleusercontent.com/YIJAgKM4tjnn4iWHdidgaYnsiIapZiZJbERJAp1ZL_Nh94UrnKQ2sn-NUJ7l0ESEWBk",
        "https://play-lh.googleusercontent.com/xW7WVviElx7IAu4Rv5HDauXJo5u7ybkY6ZqKbeCrJNWZ5xRep-Vl89SaCwx7QTgWBzI",
        "https://play-lh.googleusercontent.com/U9NNhNjeGNiPhjsUks4QiFqgGF1W5UDASsN2Bv5CdzkYuVa2MbMFBTqHOgQAnpDJzPSi",
        "https://play-lh.googleusercontent.com/8oHG_B2zLTwwgo3pnDzpiMx-3DZC6DyvMjWhvypViH71eQxDrwjulN8MfslznKIIlHM",
        "https://play-lh.googleusercontent.com/z7k5rVc4CXen9XGIXYIQx_6achVW1ZW9aMDhhIIcAU8Xz91fB1xqjTVFDU-cTmupGf4",
        "https://play-lh.googleusercontent.com/UR7EPhSFeidb2QxWh9sf198RuITze1kyxUMEPm_iAPn_qAYIjGHevwWYjkGUIMSMdec",
        "https://play-lh.googleusercontent.com/EQ8ZpUJ9MX7H9bsWwM1Wa4wU_7WgkN-0HlkIXzo1KkFjSnFZQ2KV49fZcst0vWJDmw",
        "https://play-lh.googleusercontent.com/Rj4hxHUdL-bZIrH6ZKz7thIEJ8s0FzAoxZEgU9f8qLJTt3gEX2UOnDtATKoqMCXy4w",
        "https://play-lh.googleusercontent.com/NAm6C03FmJtYOSYEpk4lmliZabBtLLPfY7aOS9aFq8zcxCONCZjk2nZ65op4dI7d8ReO",
        "https://play-lh.googleusercontent.com/2tisjs7i01rTWBHk0ulArznIIIAuZmUrSwf_pPfuTdOXWl5BY5-BzV4jgN92p_uoWw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 29, 2024",
    "lastUpdatedOn": "Oct 11, 2024",
    "updated": 1728630196,
    "version": "0.0.9",
    "comments": [],
    "appId": "com.idle.island.builder",
    "url": "https://play.google.com/store/apps/details?id=com.idle.island.builder&hl=en&gl=us"
}