{
    "title": "Miles - Travel, Shop, Get Cash",
    "description": "Miles is a universal rewards app that gives anyone the ability to earn miles automatically for all modes of transportation. The Miles app goes beyond airline miles, credit card points, or regular reward programs. We reward you with miles, our version of points, for any way you get from point A to point B. Whether you drive, walk, bike, or ride the train, we'll reward you miles for each mile traveled. For greener forms of travel, or healthier forms. you will be rewarded even further. \r\n\r\nYou have the flexibility to redeem the miles you've earned for exclusive rewards, gift cards, top deals, credit, discounts, and savings from amazing brands such as HP, Garmin, Pandora, Chewy, Home Chef, Buffalo Wild Wings, Wayfair, Sam's Club, Booking.com, and many more. Get rewarded with the best deals and savings from our popular brand partners that can't be found anywhere else.\r\n\r\nAdditionally, your miles can be used to enter gift card and product raffles from exciting brands, or you can donate them to charities to help feed the hungry, contribute to cancer foundations, and more.\r\n\r\nWe've created a frequent flyer program for all transportation encompassing your daily commute and travel. Miles delivers value and savings for every mile traveled, across every mode of travel, anywhere in the world. Whether by car (as a driver or passenger), train, subway, bus, boat, bicycle, or by walking, the Miles app effortlessly rewards your travel - regardless of where your journey takes you.\r\n\r\nMiles rewards you for your daily travel by offering various activity challenges that include walking, running, or biking to earn special Amazon.com gift cards. Make every mile traveled count and get rewarded for taking more sustainable modes of transportation. Download Miles today to start getting rewarded and save money!\r\n\r\nHere's how it works:\r\n\r\n1. Download the app\r\n2. Register an account\r\n3. Set Location Services to Always\r\n\r\nAfter that, just log in occasionally to claim your miles. \r\n\r\nThere are also plenty of ways to earn bonus miles in the app!\r\n2x miles for greener travel\r\n3x miles for healthier travel\r\nSpecial promo codes\r\n\r\nRedeem your miles for rewards, gift cards, raffles:\r\nThe Miles app will keep track of all your miles and you can redeem exclusive rewards using those miles in the app. You can use the rewards instantly or at a later date. You will find rewards that can be used online or at a physical location from merchants using exclusive promo codes, coupon codes, links, QR codes, or barcodes across the following categories:\r\n\r\n\u2022 Retail\r\n\u2022 Shopping\r\n\u2022 Dining\r\n\u2022 Groceries\r\n\u2022 Household\r\n\u2022 Health and Beauty\r\n\u2022 Electronics\r\n\u2022 Travel\r\n\u2022 Kids\r\n\u2022 Auto\r\n\u2022 Other\r\n\r\nBuzz about Miles:\r\n\"Finally there's a way to get recognized for all the travel you do \u2014 even if it's just a walk around the corner. It adds up.\" - Mashable\r\n\r\n\"Miles gives you reward miles for almost everything\" - TechCrunch\r\n\r\n\"It's a great way of adding value to the travel you otherwise wouldn't be rewarded for.\" - The Points Guy\r\n\r\nWhy users love the Miles app:\r\n\"I spend nothing to earn miles and redeem them for products I love. Simple and easy to use.\" - Paula T.\r\n\r\n\"Miles is for everyone - doesn't matter if you take a transit, drive, use rideshare, bike or simply walk.\" - Bank P.\r\n\r\nThanks for being a Miles user! Need help? Reach us at support@getmiles.com.\r\n\r\nApp Privacy Policy:\r\nhttps://www.getmiles.com/mobile-privacy\r\n\r\nApp Terms of Use: \r\nhttps://www.getmiles.com/mobile-tos",
    "descriptionHTML": "Miles is a universal rewards app that gives anyone the ability to earn miles automatically for all modes of transportation. The Miles app goes beyond airline miles, credit card points, or regular reward programs. We reward you with miles, our version of points, for any way you get from point A to point B. Whether you drive, walk, bike, or ride the train, we&#39;ll reward you miles for each mile traveled. For greener forms of travel, or healthier forms. you will be rewarded even further. <br><br>You have the flexibility to redeem the miles you&#39;ve earned for exclusive rewards, gift cards, top deals, credit, discounts, and savings from amazing brands such as HP, Garmin, Pandora, Chewy, Home Chef, Buffalo Wild Wings, Wayfair, Sam&#39;s Club, Booking.com, and many more. Get rewarded with the best deals and savings from our popular brand partners that can&#39;t be found anywhere else.<br><br>Additionally, your miles can be used to enter gift card and product raffles from exciting brands, or you can donate them to charities to help feed the hungry, contribute to cancer foundations, and more.<br><br>We&#39;ve created a frequent flyer program for all transportation encompassing your daily commute and travel. Miles delivers value and savings for every mile traveled, across every mode of travel, anywhere in the world. Whether by car (as a driver or passenger), train, subway, bus, boat, bicycle, or by walking, the Miles app effortlessly rewards your travel - regardless of where your journey takes you.<br><br>Miles rewards you for your daily travel by offering various activity challenges that include walking, running, or biking to earn special Amazon.com gift cards. Make every mile traveled count and get rewarded for taking more sustainable modes of transportation. Download Miles today to start getting rewarded and save money!<br><br>Here&#39;s how it works:<br><br>1. Download the app<br>2. Register an account<br>3. Set Location Services to Always<br><br>After that, just log in occasionally to claim your miles. <br><br>There are also plenty of ways to earn bonus miles in the app!<br>2x miles for greener travel<br>3x miles for healthier travel<br>Special promo codes<br><br>Redeem your miles for rewards, gift cards, raffles:<br>The Miles app will keep track of all your miles and you can redeem exclusive rewards using those miles in the app. You can use the rewards instantly or at a later date. You will find rewards that can be used online or at a physical location from merchants using exclusive promo codes, coupon codes, links, QR codes, or barcodes across the following categories:<br><br>\u2022 Retail<br>\u2022 Shopping<br>\u2022 Dining<br>\u2022 Groceries<br>\u2022 Household<br>\u2022 Health and Beauty<br>\u2022 Electronics<br>\u2022 Travel<br>\u2022 Kids<br>\u2022 Auto<br>\u2022 Other<br><br>Buzz about Miles:<br>&quot;Finally there&#39;s a way to get recognized for all the travel you do \u2014 even if it&#39;s just a walk around the corner. It adds up.&quot; - Mashable<br><br>&quot;Miles gives you reward miles for almost everything&quot; - TechCrunch<br><br>&quot;It&#39;s a great way of adding value to the travel you otherwise wouldn&#39;t be rewarded for.&quot; - The Points Guy<br><br>Why users love the Miles app:<br>&quot;I spend nothing to earn miles and redeem them for products I love. Simple and easy to use.&quot; - Paula T.<br><br>&quot;Miles is for everyone - doesn&#39;t matter if you take a transit, drive, use rideshare, bike or simply walk.&quot; - Bank P.<br><br>Thanks for being a Miles user! Need help? Reach us at support@getmiles.com.<br><br>App Privacy Policy:<br>https://www.getmiles.com/mobile-privacy<br><br>App Terms of Use: <br>https://www.getmiles.com/mobile-tos",
    "summary": "Earn gift cards and save money when you drive, walk, and run in your daily life",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2944030,
    "score": 3.6114414,
    "ratings": 65422,
    "reviews": 14914,
    "histogram": [
        16999,
        3146,
        3705,
        5989,
        35578
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $49.99 per item",
    "developer": "ConnectIQ Labs Inc.",
    "developerId": "4717247060744423069",
    "developerEmail": "support@getmiles.com",
    "developerWebsite": "https://www.getmiles.com/",
    "developerAddress": "255 Shoreline Drive, Suite 600, Redwood City, CA 94065",
    "privacyPolicy": "https://www.getmiles.com/privacy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/2RxONmnvBbOwssTNMHEaOi5PACKKbR0tuCBxX1fbbXptSC7syp0Df60-jz_GoPHMPgcQ",
    "headerImage": "https://play-lh.googleusercontent.com/qrOxMhd5xYvzxtDjoCNSIgJlswMOwdExz9pursrKqyaTrYJf_VLdZ3r2kPsSV-unBA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/iIT03LA_o5BEAS0HNuOMcN18-qCeb-EoOFR4LaEaSowpCZFa5p4LRFW_UASSXOAu56c",
        "https://play-lh.googleusercontent.com/FUzugeU1oiCuxow6GUc1PJtryh9TSclfEt3ggf6X6XJpxxDVU6yulzmIXz9XFMoWSA",
        "https://play-lh.googleusercontent.com/IoyA5BMoUcblgwzjHxZKvla7mMKXvFKaHeZL7-fpJHkdtIpVSxe3VFkTg7xw9SK48kpl",
        "https://play-lh.googleusercontent.com/uaJMwboMBKceRnMOm4TM2Zk0YGxpRkbLPLrL69NhhnepPLp3TTrAwVpDPF2-f2Sd_M1Y",
        "https://play-lh.googleusercontent.com/wHOdONLIV8oF-JTSdHIpkYMuOCQ8v3nIMjNvuxgaIn0UcfiQB5MOvkHHpODHriY15A",
        "https://play-lh.googleusercontent.com/bUkoaB3miu3qo7KPPu7xb7jja6DuRG62arKlXkF_nS-jfjYw0a8O__cf3Q22zUwSviU",
        "https://play-lh.googleusercontent.com/jEnAH2zLR_XIjewNtuBHuxU-elDUQDMct4hUUHYjSEB0OoGxDD_Bj3n3SGMDj-S8Q9-U",
        "https://play-lh.googleusercontent.com/VaE2KyRJ2fCTN1Durx5Yg56wfQ74vHD_gA2GyiESiGOqwqcp35N65XTbKPhil0ksHtQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Mar 22, 2019",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729150112,
    "version": "2.4.49(1)",
    "comments": [],
    "appId": "connectiq.miles.app",
    "url": "https://play.google.com/store/apps/details?id=connectiq.miles.app&hl=en&gl=us"
}