{
    "title": "FlixBus: Book Bus Tickets",
    "description": "With FlixBus, you can travel throughout Europe at affordable prices and are ensured a safe journey. Discover new cities, visit your friends and family as often as you want, and go on relaxing holidays. Simply book your tickets in the app, jump on the bus, and enjoy your trip!\r\n\r\nTraveling with FlixBus is so easy, there's not much to explain. Just download the free app and try it. For bookworms that need more details, here are some tips to get you started \ud83d\ude09\r\n\r\nBOOKING\r\nChoose your desired connection, enter your passenger information, choose your preferred payment method, and pay for your ticket. The advantages of booking through the app:\r\n- Your app is your ticket; you don't need to print anything\r\n- Access exclusive offers available only on the app\r\n- Easily manage and modify your booking anytime \r\n\r\nTRAVEL INSPIRATIONS \r\nAre you looking forward to your next trip? Find your next dream destination with the exploration map and get inspired!\r\n\r\nINFORMATION ON YOUR TRIP\r\nYou can access your trip information and ticket anytime via your phone and can follow your bus\u2019s location. Let the app guide you to your bus stop. Important information, such as delays or changes concerning the bus stop, will be shared with you via push notification or a text message, so you won't miss any information. Very important: don't forget to allow push notifications!\r\n\r\nBAGGAGE\r\nEvery ticket includes 1 free carry-on bag on board and 1 free suitcase or travel bag. Unlike flights or others means of transportation, you can easily and affordably bring more baggage with you on the bus. Bicycle spaces are also available \u2013 just choose the option you need during the booking process. Our bus drivers are happy to help you stow them away. You can find more information concerning rules and costs in our FAQs.\r\n\r\nCOMFORT ON BOARD\r\nWith FlixBus, you are guaranteed a seat with a comfortable and adjustable backrest, extra legroom, private power outlets, and we have toilets on board. During the trip, you can use our free Wi-Fi and buy some snacks and drinks from our drivers. Time will fly by with our great selection of movies, e-books, games, and audiobooks in the FlixBus Onboard Entertainment Portal. Onboard services are subject to availability: more information about our services on the bus can be found in our FAQs.\r\n\r\nGREEN TRAVEL\r\nFlixBus is working to make the entire bus fleet 100% carbon-neutral. You can offset your carbon footprint with a donation when purchasing your ticket.\r\n\r\nDoesn't it sound Flix-tastic? See you on board!\r\n\r\nTo ensure you have the best travel experience possible, we will request your permission to access the following functions:\r\n\u2713 Calendar: So your trip will be saved in your calendar\r\n\u2713 Location: So we can show you to your nearest bus stop\r\n\u2713 Camera: So you can scan the QR code on your booking confirmation (from PC or print) and upload your tickets directly to the app\r\nMore information can be found in \"Permissions\" at the bottom of this page.",
    "descriptionHTML": "With FlixBus, you can travel throughout Europe at affordable prices and are ensured a safe journey. Discover new cities, visit your friends and family as often as you want, and go on relaxing holidays. Simply book your tickets in the app, jump on the bus, and enjoy your trip!<br><br>Traveling with FlixBus is so easy, there&#39;s not much to explain. Just download the free app and try it. For bookworms that need more details, here are some tips to get you started \ud83d\ude09<br><br>BOOKING<br>Choose your desired connection, enter your passenger information, choose your preferred payment method, and pay for your ticket. The advantages of booking through the app:<br>- Your app is your ticket; you don&#39;t need to print anything<br>- Access exclusive offers available only on the app<br>- Easily manage and modify your booking anytime <br><br>TRAVEL INSPIRATIONS <br>Are you looking forward to your next trip? Find your next dream destination with the exploration map and get inspired!<br><br>INFORMATION ON YOUR TRIP<br>You can access your trip information and ticket anytime via your phone and can follow your bus\u2019s location. Let the app guide you to your bus stop. Important information, such as delays or changes concerning the bus stop, will be shared with you via push notification or a text message, so you won&#39;t miss any information. Very important: don&#39;t forget to allow push notifications!<br><br>BAGGAGE<br>Every ticket includes 1 free carry-on bag on board and 1 free suitcase or travel bag. Unlike flights or others means of transportation, you can easily and affordably bring more baggage with you on the bus. Bicycle spaces are also available \u2013 just choose the option you need during the booking process. Our bus drivers are happy to help you stow them away. You can find more information concerning rules and costs in our FAQs.<br><br>COMFORT ON BOARD<br>With FlixBus, you are guaranteed a seat with a comfortable and adjustable backrest, extra legroom, private power outlets, and we have toilets on board. During the trip, you can use our free Wi-Fi and buy some snacks and drinks from our drivers. Time will fly by with our great selection of movies, e-books, games, and audiobooks in the FlixBus Onboard Entertainment Portal. Onboard services are subject to availability: more information about our services on the bus can be found in our FAQs.<br><br>GREEN TRAVEL<br>FlixBus is working to make the entire bus fleet 100% carbon-neutral. You can offset your carbon footprint with a donation when purchasing your ticket.<br><br>Doesn&#39;t it sound Flix-tastic? See you on board!<br><br>To ensure you have the best travel experience possible, we will request your permission to access the following functions:<br>\u2713 Calendar: So your trip will be saved in your calendar<br>\u2713 Location: So we can show you to your nearest bus stop<br>\u2713 Camera: So you can scan the QR code on your booking confirmation (from PC or print) and upload your tickets directly to the app<br>More information can be found in &quot;Permissions&quot; at the bottom of this page.",
    "summary": "Bus tickets at unbeatable prices with routes across the US. All aboard FlixBus!",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 34901954,
    "score": 4.7181025,
    "ratings": 621105,
    "reviews": 5170,
    "histogram": [
        21439,
        3535,
        14723,
        49220,
        532148
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Flix SE",
    "developerId": "Flix+SE",
    "developerEmail": "app@flixbus.com",
    "developerWebsite": "https://www.flixbus.de",
    "developerAddress": null,
    "privacyPolicy": "https://global.flixbus.com/privacy-policy/app",
    "genre": "Travel & Local",
    "genreId": "TRAVEL_AND_LOCAL",
    "categories": [
        {
            "name": "Travel & Local",
            "id": "TRAVEL_AND_LOCAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/QqJ4jHU5FHRvqp5lWJVQPShGKI9wqZy4ph0SYousFr7Guvk3mOZPvYxbgbMuSdD1dQI",
    "headerImage": "https://play-lh.googleusercontent.com/3mv_TQTZl-7LObkwID1JxVg_kd_ZnkI6GSZq0pTnnF2HNyUFnXcuPl8cDDYQ3Up92M2N",
    "screenshots": [
        "https://play-lh.googleusercontent.com/VY7rKM9g8fXvPkq_w_OXeGWzgmgDIWm1P9UbxL-FP7Y2cBQ7VD0NCGoyWxYxRCuBv8nP",
        "https://play-lh.googleusercontent.com/l5XKcfn6fpV2wxasv3eQGXLpKwESET8Yuxl31qTd9T0WUVzCgjnxnYfYNMTZ6gjyCQ",
        "https://play-lh.googleusercontent.com/F-BtKJxNg_iBac54AzWgQ_IzfS7MBMdOldaFOzvFBQHcZLHp3tO8yFJiaubHXLp74Nk",
        "https://play-lh.googleusercontent.com/Q3g-ljhyTklaP3d6ct44ScG2-z51e9wygnUTfQzSJSuk4gDfiRXDBtWj3qFEmjwEE60",
        "https://play-lh.googleusercontent.com/VcGhHGlW7oTxzu18cyOyYvln2H29hE0URZIS4f0yJoHlJADMDTsHNkfVTcndyi1XYKo"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 3, 2014",
    "lastUpdatedOn": "Oct 23, 2024",
    "updated": 1729674827,
    "version": "9.43.0",
    "comments": [],
    "appId": "de.flixbus.app",
    "url": "https://play.google.com/store/apps/details?id=de.flixbus.app&hl=en&gl=us"
}