{
    "title": "mobile.de - car market",
    "description": "The mobile.de app\r\n\r\nThe mobile.de app helps you keep track of everything. Conveniently browse for bargains on the go, save your search(es), mark your favourites in your personal car park and receive notifications about new listings. If you're logged in, your saved vehicles and searches will be automatically synchronised across all devices. And it's all simple, secure and free!\r\n\r\n\r\nHow you benefit with mobile.de: \r\n\u2713  Buy or sell your desired vehicle quickly and conveniently\r\n\u2713  Find your desired vehicle quickly using precise search criteria\r\n\u2713  Save time and effort by saving your searches\r\n\u2713  Sort leasing and financing offers by monthly rates\r\n\u2713  Buy your next vehicle completely online\r\n\u2713  Use Safe Pay, the secure and cashless payment method for private sales/purchases\r\n\u2713  Don't miss any offers and receive notifications for new listings\r\n\u2713  Save your favourites in your personal parking area\r\n\u2713  Follow trusted dealers and receive personalised direct offers\r\n\u2713  Share great offers easily with your friends\r\n\u2713  Spot great offers immediately with the transparent price rating\r\n\u2713  Compare financing from dealers with the best offers online\r\n\u2713  Synchronise your searches & listings across all devices\r\n\u2713  Create your listing in just a few minutes\r\n\u2713  Optimise your listing with eye-catching features\r\n\u2713  Save time by selling directly to a buying station\r\n\u2713  Get an offer from verified dealers in your area\r\n\r\nAre you looking for a BMW 3 Series, F30 or SportLine? Or perhaps a VW ID.4, with a convenience package and maximum mileage of 10,000 km, within your city? Or do you want a holiday vehicle, like a VW Bus T6 California with automatic transmission, all-wheel drive and pop-up roof? No problem.\r\nmobile.de is Germany's biggest vehicle market, with over 1.4 million cars, including some 80,000 electric cars, plus almost 100,000 motorbikes, scooters and mopeds, more than 100,000 commercial vehicles and buses, and over 65,000 caravans and motorhomes. And as of 2024, also e-bikes.\r\nYour dream vehicle is sure to be among them!\r\n\r\n\r\nFinancing, leasing or buying online?\r\n\r\nWant to finance or lease your new car? You can search specifically for leasing offers, filter by monthly rates or use a finance calculator to find the right offer for you.\r\nAnd that's not all: you can also buy your new car completely online, from the comfort of your sofa, and get it delivered to your doorstep with a 14-day right of return.\r\n\r\n\r\nPrice rating and dealer rating\r\n\r\nOur price rating helps you to compare the vehicle price against the market price, while the dealer rating helps you to navigate between the many dealerships. For added practicality, if you've already found one or more trustworthy dealers, you can follow them on the platform. Going to 'My searches' allows you to view any new listings from these dealers quickly and without spam.\r\n\r\nThe only trouble is, there are so many to choose from!. Fortunately, thanks to smart search criteria and lots of filter options, you'll find exactly the vehicle for you quickly and easily.\r\n\r\n\r\nSelling\r\n\r\nWhether you want to sell an old Astra, a KTM 390 Duke that's almost as good as new, a well-travelled camper van or the semi-trailer truck you inherited from your grandma, you'll find the biggest pool of potential buyers for your used vehicle at mobile.de. And best of all, private listings are free of charge up to a sales price of 30,000 euros. Advertising on mobile.de is worthwhile for commercial sellers, too.\r\n\r\n\r\nDirect car sales\r\n\r\nIn a hurry? If you can't spare the time to negotiate with strangers or offer test drives, or if you're not entirely comfortable with the whole sales process, you can sell your car quickly and directly to a certified dealer via a buying station. Simply get a free, no-obligation estimate for the value of your used car from an expert. If you're happy with the price, you can sell your vehicle directly. The buying station will take care of deregistration process and you'll have your money in no time.",
    "descriptionHTML": "The mobile.de app<br><br>The mobile.de app helps you keep track of everything. Conveniently browse for bargains on the go, save your search(es), mark your favourites in your personal car park and receive notifications about new listings. If you&#39;re logged in, your saved vehicles and searches will be automatically synchronised across all devices. And it&#39;s all simple, secure and free!<br><br><br>How you benefit with mobile.de: <br>\u2713  Buy or sell your desired vehicle quickly and conveniently<br>\u2713  Find your desired vehicle quickly using precise search criteria<br>\u2713  Save time and effort by saving your searches<br>\u2713  Sort leasing and financing offers by monthly rates<br>\u2713  Buy your next vehicle completely online<br>\u2713  Use Safe Pay, the secure and cashless payment method for private sales/purchases<br>\u2713  Don&#39;t miss any offers and receive notifications for new listings<br>\u2713  Save your favourites in your personal parking area<br>\u2713  Follow trusted dealers and receive personalised direct offers<br>\u2713  Share great offers easily with your friends<br>\u2713  Spot great offers immediately with the transparent price rating<br>\u2713  Compare financing from dealers with the best offers online<br>\u2713  Synchronise your searches &amp; listings across all devices<br>\u2713  Create your listing in just a few minutes<br>\u2713  Optimise your listing with eye-catching features<br>\u2713  Save time by selling directly to a buying station<br>\u2713  Get an offer from verified dealers in your area<br><br>Are you looking for a BMW 3 Series, F30 or SportLine? Or perhaps a VW ID.4, with a convenience package and maximum mileage of 10,000 km, within your city? Or do you want a holiday vehicle, like a VW Bus T6 California with automatic transmission, all-wheel drive and pop-up roof? No problem.<br>mobile.de is Germany&#39;s biggest vehicle market, with over 1.4 million cars, including some 80,000 electric cars, plus almost 100,000 motorbikes, scooters and mopeds, more than 100,000 commercial vehicles and buses, and over 65,000 caravans and motorhomes. And as of 2024, also e-bikes.<br>Your dream vehicle is sure to be among them!<br><br><br>Financing, leasing or buying online?<br><br>Want to finance or lease your new car? You can search specifically for leasing offers, filter by monthly rates or use a finance calculator to find the right offer for you.<br>And that&#39;s not all: you can also buy your new car completely online, from the comfort of your sofa, and get it delivered to your doorstep with a 14-day right of return.<br><br><br>Price rating and dealer rating<br><br>Our price rating helps you to compare the vehicle price against the market price, while the dealer rating helps you to navigate between the many dealerships. For added practicality, if you&#39;ve already found one or more trustworthy dealers, you can follow them on the platform. Going to &#39;My searches&#39; allows you to view any new listings from these dealers quickly and without spam.<br><br>The only trouble is, there are so many to choose from!. Fortunately, thanks to smart search criteria and lots of filter options, you&#39;ll find exactly the vehicle for you quickly and easily.<br><br><br>Selling<br><br>Whether you want to sell an old Astra, a KTM 390 Duke that&#39;s almost as good as new, a well-travelled camper van or the semi-trailer truck you inherited from your grandma, you&#39;ll find the biggest pool of potential buyers for your used vehicle at mobile.de. And best of all, private listings are free of charge up to a sales price of 30,000 euros. Advertising on mobile.de is worthwhile for commercial sellers, too.<br><br><br>Direct car sales<br><br>In a hurry? If you can&#39;t spare the time to negotiate with strangers or offer test drives, or if you&#39;re not entirely comfortable with the whole sales process, you can sell your car quickly and directly to a certified dealer via a buying station. Simply get a free, no-obligation estimate for the value of your used car from an expert. If you&#39;re happy with the price, you can sell your vehicle directly. The buying station will take care of deregistration process and you&#39;ll have your money in no time.",
    "summary": "Buy and sell vehicles - at Germany's largest vehicle market",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 30176076,
    "score": 4.753012,
    "ratings": 618110,
    "reviews": 173,
    "histogram": [
        3666,
        10998,
        3666,
        96785,
        502504
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "mobile.de GmbH",
    "developerId": "mobile.de+GmbH",
    "developerEmail": "service@team.mobile.de",
    "developerWebsite": "https://www.mobile.de",
    "developerAddress": "mobile.de GmbH\nAlbert-Einstein-Ring 26\nD-14532 Kleinmachnow-Dreilinden",
    "privacyPolicy": "https://www.mobile.de/service/privacyPolicy",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ZtSaR6lqWaz_pzujp64myd3shYRgbLCHFzBM-vOqB2XB3Ri0Z5BIj3ThuuEbdismJJbw",
    "headerImage": "https://play-lh.googleusercontent.com/d47DZBfZx1-y2FqraIYM1R6asYAGEuzwQwGp8SyrfrB7Uq1FPcjxBcasopVJvXaA3Tg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Et-t1CgcOTkbY8-0MSVEcaho0cLD-hdDgL81d8VcCt47Lao8C7ZneZPuUBrWmUBP9MI",
        "https://play-lh.googleusercontent.com/hK9mE2l26GRcxDNe6jrQ80G8dxn4KQNTZreCgSpNKLUVVr1UssYrLtDz9Cy5raGrkwog",
        "https://play-lh.googleusercontent.com/-FAiMaMPNilpdQrRtYThsgX_HohgWG1zepDJoP5ntFL64p7p7bVjakxaAGoB-YJMwGsj",
        "https://play-lh.googleusercontent.com/MfNOMapFidT2_39u6YYo2BA9qw92Hd6nRJPYEp8IemU-S4Af1uLUQslYvMgWIzVik2I",
        "https://play-lh.googleusercontent.com/K4ehEa5egE98R9AhAAS5FE_RzLCr1g-7hCWfn0_hQz9M8YQnGbmFug_2Ko6yXAbHLtg",
        "https://play-lh.googleusercontent.com/Y5ddif66K2s44GhCEv2xg9xFagll6cOHwpJqNn9ARPo6pbszid9Hnda5j0ityyFAHgcz",
        "https://play-lh.googleusercontent.com/KOtZSq3JB-N7lsnP3BIBD2XK6BvxZFrhejoF6H8vdqvzxijRkzFH29b_ylVX6rCzpVRm",
        "https://play-lh.googleusercontent.com/-BhCSh8s8MjVXWybJBjujEINYK0_RZUVW4FAGvVYb7FZWDULdB0LYMRUskStbks4mfxG",
        "https://play-lh.googleusercontent.com/ug7D4umbp-3JySnRtl0oherq1gtsepe7O_tXQBQ3nBK8SHo2t3oLemQ4DQTadkKogKI",
        "https://play-lh.googleusercontent.com/8UiDnppD3AXbeQcGf523sjbbvjC5DfjA33F6CLmyAwVu1Wim1NeafG4YeomfBSbzS7E1",
        "https://play-lh.googleusercontent.com/Z0W4hf1DSa0geP-XplLmysU7iAvODB7uSuaWHcsmpKzNGQNtf76CXqMV2gcS2Lwj-hg",
        "https://play-lh.googleusercontent.com/FLvpiC54vnW8jUIrP1it2dTTiAclvxorHab19UMHDXygnmfUjHjLIZGqyv55AQlor5Mx",
        "https://play-lh.googleusercontent.com/RBE9dnJWryszoZg1F2_3BZLlaRxKiRq2JG6fvpUDBwkpS9tkxbtFH8Ft5fcyhf6RT5py",
        "https://play-lh.googleusercontent.com/DXFsiqDNbLG4_WdM9wZBkflRaDsxv1jzoE9V861S1maqtYTghPP06tuF-fc4jG-LGKA",
        "https://play-lh.googleusercontent.com/XtwME8lvqXzKOXpKoP4BKTb0Iua3rfm9yhS_ezIKEUkZjuaW9_VTUHG-yzvHlh_ciQ",
        "https://play-lh.googleusercontent.com/RGOqC20l7CMz33D5b5yiqH_e0vDdOxN7anNDjKRVHbEGUMcoLyjXW6gMQFKcqvf4Xus",
        "https://play-lh.googleusercontent.com/AIC2ccIkZu1H1iHsAjdaD-MEpc2Ghp3UtLLcvd_nyyz8qvkSZ4vQArp7ShAmmAF1UJo",
        "https://play-lh.googleusercontent.com/HiuWP8yhS8HgoO9nKtW0wO3zSWt07cUSyVX-gyfd2_2k8j3W7TOhNeCkjRBJKOaEvw",
        "https://play-lh.googleusercontent.com/Z9ID2Z9I1odxv-jZmSoyiv37E5l6PxJ3apjwSkGBGFg8OOizEg5Uv1khXAuI5BQtzA",
        "https://play-lh.googleusercontent.com/p--JR30b-fSDbuZcrEm-w3G6TnWvhE_QZ_uJ2gnMudiGOAzGVF7AD10_TkGZJu27ng",
        "https://play-lh.googleusercontent.com/kX2Oo-K9d2Jg2eckbM_CoXLbAyeDcEOvhOxEnmNmyn9ihtQ-qJJ7JJ14DtEB62_BpXY2"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 14, 2020",
    "lastUpdatedOn": "Sep 30, 2024",
    "updated": 1727699166,
    "version": "9.63.1",
    "comments": [],
    "appId": "de.mobile.android.app",
    "url": "https://play.google.com/store/apps/details?id=de.mobile.android.app&hl=en&gl=us"
}