{
    "title": "Tellonym: anonymous questions",
    "description": "Tellonym is a simple way to feel closer to your friends: ask anything, answer anonymous questions, receive honest feedback, and get to know yourself and your friends better!\r\n\r\nHow does it work? \r\n\r\n- Share your Tellonym link with friends\r\n- Get hundreds of anonymous messages (Tells) on Instagram & Snapchat\r\n- Answer questions and share on your profile\r\n- Share anonymous Q&A's to Snapchat and Instagram\r\n- Follow friends, join conversations, receive honest feedback & random confessions\r\n\r\nFeatures:\r\n\r\n<h3>LINK FOR ANONYMOUS MESSAGES</h3>\r\nShare your <b>Tellonym Link</b> and receive anonymous questions, feedback or random confessions at any time.\r\n\r\n<h3>SHARE Q&A\u2019s</h3>\r\nAsk me anything: Share questions and answers as Q&A\u2019s on <b>Snapchat & Instagram</b>.\r\n\r\n<h3>FIND FRIENDS</h3>\r\nFind friends and follow them to see when they <b>answer new questions</b>.\r\n\r\n<h3>MEET PEOPLE</h3>\r\nMeet people your age with the same interests as you, write <b>anonymous messages</b>, ask anything and get to know each other.\r\n\r\n<h3>PRIVATE CHATS</h3>\r\nSend a DM and start private chats with people.",
    "descriptionHTML": "Tellonym is a simple way to feel closer to your friends: ask anything, answer anonymous questions, receive honest feedback, and get to know yourself and your friends better!<br><br>How does it work? <br><br>- Share your Tellonym link with friends<br>- Get hundreds of anonymous messages (Tells) on Instagram &amp; Snapchat<br>- Answer questions and share on your profile<br>- Share anonymous Q&amp;A&#39;s to Snapchat and Instagram<br>- Follow friends, join conversations, receive honest feedback &amp; random confessions<br><br>Features:<br><br><h3>LINK FOR ANONYMOUS MESSAGES</h3><br>Share your <b>Tellonym Link</b> and receive anonymous questions, feedback or random confessions at any time.<br><br><h3>SHARE Q&amp;A\u2019s</h3><br>Ask me anything: Share questions and answers as Q&amp;A\u2019s on <b>Snapchat &amp; Instagram</b>.<br><br><h3>FIND FRIENDS</h3><br>Find friends and follow them to see when they <b>answer new questions</b>.<br><br><h3>MEET PEOPLE</h3><br>Meet people your age with the same interests as you, write <b>anonymous messages</b>, ask anything and get to know each other.<br><br><h3>PRIVATE CHATS</h3><br>Send a DM and start private chats with people.",
    "summary": "Get your Tellonym Link for Q&A and anonymous messages on Instagram und Snapchat!",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 28197506,
    "score": 4.258039,
    "ratings": 313672,
    "reviews": 2999,
    "histogram": [
        30250,
        10083,
        24343,
        32696,
        216248
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $74.99 per item",
    "developer": "Callosum Software",
    "developerId": "Callosum+Software",
    "developerEmail": "support@tellonym.me",
    "developerWebsite": "http://tellonym.me",
    "developerAddress": "Romy-Schneider-Strasse 1\n13599 Berlin\nGermany",
    "privacyPolicy": "https://tellonym.me/privacy",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/m-9v6JD0UawLVs_5tzjJ3Tgfv0kSSx-3uE9IBDcdz2rJ4FNvHSl8bx-GFQp1U9luBQ",
    "headerImage": "https://play-lh.googleusercontent.com/-_APZMh6IEWJQ83G9oRdWin0zHCbaUwh87DgESdPvtGKh-WFiBpS4mDgd0CuR3b8jA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/fxRpcCihgi_cPQwKBwbDk3xVe87VbrDb05F0fP9EympHcxGNUfXo5ajTkJEPcxlOfWw",
        "https://play-lh.googleusercontent.com/uK7mLxhvUJi4WqAVvn7lMKn3QkZdXWLvh8ZnTn0CMoNmBlGti0bSSefC6e7oFPAiQ8gT",
        "https://play-lh.googleusercontent.com/65ndQYDM40CTOriSVXiNt1uCVBK5a26ngCJQGiSBq5cMO_RHSrJ8ZYw63o8ivCyGf9k",
        "https://play-lh.googleusercontent.com/HviD0gSTT2RwoBW88v6FHMSMUxNWtGctEgkIwyRTjDRl8AhBw9vcpbtJpexoN_RFO4yN",
        "https://play-lh.googleusercontent.com/55xLM4P_ecYd5rFWtcEGxf34HUUBnAlmhNIXDYh8vyg6tZyN-1QOaDuDql5c-Vjq2GU",
        "https://play-lh.googleusercontent.com/2U6MGHDl45zvl7REZsDy5uFa2R8lrZquA3UtD63HToYj7v3JQGcHB8JkzkAhUm2ch7VN"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Aug 19, 2017",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729237893,
    "version": "3.123.3",
    "comments": [],
    "appId": "de.tellonym.app",
    "url": "https://play.google.com/store/apps/details?id=de.tellonym.app&hl=en&gl=us"
}