{
    "title": "Disposable Camera App",
    "description": "The Original Free Disposable Camera App\r\n\r\nBrought to you by www.disposable.app, the original disposable camera app for events, weddings, parties and more allows you to capture all your guests' photos in 3 simple steps:\r\n\r\n(1) Scan QR\r\nYour event guests simply scan a QR code to instantly load your event camera.\r\n \u2022 No App Downloads Required\r\n\r\n(2) Snap Photos\r\nAll guest photos are automatically captured in your event album.\r\n \u2022 Supports Android & iOS\r\n\r\n(3) Dispose.\r\nYour guests simply close the camera app to dispose of it.\r\n \u2022 Environmentally Friendly\r\n\r\nThe Result?\r\nAn event photo album with all photos captured by your guests. The album is private by default, but shareable if you choose!\r\n\r\nApp Features:\r\n \u2022 Unlimited Guest Cameras\r\n \u2022 Free QR Print Designs\r\n \u2022 Control Guest Camera Features\r\n \u2022 Shareable Event Album\r\n \u2022 Supports 15+ Global Languages\r\n \u2022 Stress-Free Event Setup Task List\r\n \u2022 Brandable Camera & Album\r\n\r\nOur team cares about capturing beautiful memories just as much as you do, and we've put our hearts and souls into designing this simple but powerful product. We sincerely hope you enjoy it.\r\n\r\n-\r\n\r\nNote: This app allows you to create disposable camera apps which are separate from this app, running as mobile web apps on www.disposable.app, meaning guests do not need to download or install any apps to use your event camera, nor are they required to create accounts to use your event camera apps. Ease of use for event guests is our first priority.\r\n\r\n-\r\n\r\nAvailable on desktop at: www.disposable.app",
    "descriptionHTML": "The Original Free Disposable Camera App<br><br>Brought to you by www.disposable.app, the original disposable camera app for events, weddings, parties and more allows you to capture all your guests&#39; photos in 3 simple steps:<br><br>(1) Scan QR<br>Your event guests simply scan a QR code to instantly load your event camera.<br> \u2022 No App Downloads Required<br><br>(2) Snap Photos<br>All guest photos are automatically captured in your event album.<br> \u2022 Supports Android &amp; iOS<br><br>(3) Dispose.<br>Your guests simply close the camera app to dispose of it.<br> \u2022 Environmentally Friendly<br><br>The Result?<br>An event photo album with all photos captured by your guests. The album is private by default, but shareable if you choose!<br><br>App Features:<br> \u2022 Unlimited Guest Cameras<br> \u2022 Free QR Print Designs<br> \u2022 Control Guest Camera Features<br> \u2022 Shareable Event Album<br> \u2022 Supports 15+ Global Languages<br> \u2022 Stress-Free Event Setup Task List<br> \u2022 Brandable Camera &amp; Album<br><br>Our team cares about capturing beautiful memories just as much as you do, and we&#39;ve put our hearts and souls into designing this simple but powerful product. We sincerely hope you enjoy it.<br><br>-<br><br>Note: This app allows you to create disposable camera apps which are separate from this app, running as mobile web apps on www.disposable.app, meaning guests do not need to download or install any apps to use your event camera, nor are they required to create accounts to use your event camera apps. Ease of use for event guests is our first priority.<br><br>-<br><br>Available on desktop at: www.disposable.app",
    "summary": "Disposable Camera App for Events, Weddings, Parties",
    "installs": "1,000+",
    "minInstalls": 1000,
    "realInstalls": 3608,
    "score": null,
    "ratings": null,
    "reviews": null,
    "histogram": [
        0,
        0,
        0,
        0,
        0
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "hakJav Studios",
    "developerId": "8290190508655209343",
    "developerEmail": "team@disposable.app",
    "developerWebsite": "https://disposable.app",
    "developerAddress": null,
    "privacyPolicy": "https://disposable.app/policies/privacy",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/5CxZ0ejR-kvf51t9a_WeQqQWBXhHUbduu_mwKK4KeIe2qEvlycESRk_AEf83kcrIiSB3",
    "headerImage": "https://play-lh.googleusercontent.com/HJn1Yhq7vp3xt_6Xig5fR9k6IwCf4nAgIT0A5V4jnmN4AppWMPJ5XBoR2fcL6dZTlmvC",
    "screenshots": [
        "https://play-lh.googleusercontent.com/l_DWuGjrYZb5DWVtSeZiO-LezGluo6sp_Kyjsau1lJolcTXgwA2jIDyjjm0aQdC5TfQ",
        "https://play-lh.googleusercontent.com/zxwaPpFuxC_xkRZc5HiEEH4J2OpQCW37v2GenEiPZZCWWXHq9ISZcsIDGpLfJEkS7l8",
        "https://play-lh.googleusercontent.com/s22B4eAnGIjMns0gDM-fLTGvHR3aHv47cSdBBfrgBpEHAWdD3k_v5NDb0CVfjFdk-bk",
        "https://play-lh.googleusercontent.com/dMp-jFOfCJvpMiiGBRtA8j0_8Kt8XGtBeg2CbMH4PkDS_lmriMu8Dy0CkI63fQ_o8qA",
        "https://play-lh.googleusercontent.com/oEYiSN3UAMM33T_zOHrGcS79Oixil1puYfrR3luNMcChoqLdtl5om5WRd7mIj6VBl4A",
        "https://play-lh.googleusercontent.com/wzccB1DgoIy5Ak-BCuiJZ1ukMFuOSgjmId9a6-MJlntP-QJvU1e2v4c4SaDq5LjBPg",
        "https://play-lh.googleusercontent.com/29TmlimgxkQcRyF0TOMJlBpQVIzXW_1coJxEdvwx9FFAJIynbxKYchsduqKFNJWlW14",
        "https://play-lh.googleusercontent.com/j9BSssdHLCCV-9Dpmrxa4Ldc42m52UCoED8Ik4kqqrw7uFB5GC4pkzOLv-jWpnRppsk",
        "https://play-lh.googleusercontent.com/d2-liSU8qQBuHzGKjkb3KuC3fRR-eUaGsk5qkIOmCFqMd1lGq0yaxVUDVNJk6OStmE8",
        "https://play-lh.googleusercontent.com/b-dcETDAVD1NCSUeMGr1fKkbdUCGk9rbCIVoAoZeX4vd7j0iUEZQ5s_tgHsMvwe8XxQ",
        "https://play-lh.googleusercontent.com/73-yIy9qz74NknrODQn3lC1LNfLd2g83DvGMJyMdm4d9Q-ZbQW2cbneaNZvQy0FOv3w",
        "https://play-lh.googleusercontent.com/POAeLrc0l1W8_M4vsx2lofdLaQAAdXOCPiDCFZEfQTVAUlfySp4FnndClq2dPudcng"
    ],
    "video": "https://www.youtube.com/embed/bQ67yDjGgPk?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/HJn1Yhq7vp3xt_6Xig5fR9k6IwCf4nAgIT0A5V4jnmN4AppWMPJ5XBoR2fcL6dZTlmvC",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 6, 2024",
    "lastUpdatedOn": "Sep 1, 2024",
    "updated": 1725215315,
    "version": "1.1",
    "comments": [],
    "appId": "disposable.camera.app",
    "url": "https://play.google.com/store/apps/details?id=disposable.camera.app&hl=en&gl=us"
}