{
    "title": "Ficbook: Read Fictions Anytime",
    "description": "MULTIPLE BENEFITS\r\n- Surprising gifts for new members only.\r\n- Complete small tasks such as \"\"Reading challenge\"\", \"\"Daily check-in\"\", \"\"Share comments\"\", etc. Get vouchers as reward!\r\n\r\nPERSONALIZED FEED\r\n- Ficbook updates new selection of novels weekly, and recommend great novels based on your interest.  \r\n\r\nSMART LISTS\r\n- Don't feel like searching for stories? Ficbook can auto-generate book lists on the basis of your clicks and reads! An easy than ever reading!\r\n\r\nPOPULAR GENRES\r\n- Ficbook covers various hot genres. You may use the filters and tags to locate novels you love!\r\n\r\nCOMFORTABLE READ\r\n- Find your way of reading by changing text size, font type, background and scrolling mode. Read comfortably on Ficbook!\r\n\r\nCOMMENTS SHARING\r\n- Read alone but not lonely on Ficbook. You may share your thoughts on paragraphs/chapters you like or dislike, and read interesting comments from other readers!\r\n\r\nOFFLINE READ\r\n- Quickly download the subsequent chapters, and read novels anytime and anywhere!\"",
    "descriptionHTML": "MULTIPLE BENEFITS<br>- Surprising gifts for new members only.<br>- Complete small tasks such as &quot;&quot;Reading challenge&quot;&quot;, &quot;&quot;Daily check-in&quot;&quot;, &quot;&quot;Share comments&quot;&quot;, etc. Get vouchers as reward!<br><br>PERSONALIZED FEED<br>- Ficbook updates new selection of novels weekly, and recommend great novels based on your interest.  <br><br>SMART LISTS<br>- Don&#39;t feel like searching for stories? Ficbook can auto-generate book lists on the basis of your clicks and reads! An easy than ever reading!<br><br>POPULAR GENRES<br>- Ficbook covers various hot genres. You may use the filters and tags to locate novels you love!<br><br>COMFORTABLE READ<br>- Find your way of reading by changing text size, font type, background and scrolling mode. Read comfortably on Ficbook!<br><br>COMMENTS SHARING<br>- Read alone but not lonely on Ficbook. You may share your thoughts on paragraphs/chapters you like or dislike, and read interesting comments from other readers!<br><br>OFFLINE READ<br>- Quickly download the subsequent chapters, and read novels anytime and anywhere!&quot;",
    "summary": "Ficbook gives you countless novels, fast updates and fantastic reading!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1076469,
    "score": 4.21,
    "ratings": 3191,
    "reviews": 309,
    "histogram": [
        317,
        125,
        281,
        281,
        2165
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $49.99 per item",
    "developer": "Infinite Stories",
    "developerId": "Infinite+Stories",
    "developerEmail": "qingmo2008@gmail.com",
    "developerWebsite": "https://mhsjh5.dmw11.com/v1/main/term?lang=en-US",
    "developerAddress": "\u9999\u6e2f\u4e5d\u9f99\u65fa\u89d2\u5f25\u6566\u9053610\u53f7\u8377\u674e\u6d3b\u5546\u4e1a\u4e2d\u5fc3",
    "privacyPolicy": "https://mhsjh5.dmw11.com/v1/main/privacy_agreement",
    "genre": "Comics",
    "genreId": "COMICS",
    "categories": [
        {
            "name": "Comics",
            "id": "COMICS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/p_5vFjmWOC6BqdlWimohC0-SaYmIMl1-XzSSpbIhkBKMDgwO74SNf0qchq5wnbZeRq8",
    "headerImage": "https://play-lh.googleusercontent.com/Wp37e7Or7vTSw8kn3DPOWMqvG2FOxJq1MuyjmXwVNOew_tppLQ0lsInLYASSjGu16RQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/9ggs8aeUe0OMC0IBI5JqfITBaKoCC5vfpUNxQb-aHTidfSyEZqMLcB_k06jjRFUEoA",
        "https://play-lh.googleusercontent.com/3Fv9oz6Mqj_mkFX849NsntgSjOAngMx3-INDKMxqrOy50RuvotH3MB519RlfX39XxQ",
        "https://play-lh.googleusercontent.com/Um0N0VMYEIk_r6TUmsiqK6_J0NkkWYfGo4bD_gnr9ugnCqvrCSyeTNaPmKE_RPuHZqoo",
        "https://play-lh.googleusercontent.com/iOf4W87WmhXaof95j0uyz3ucMG9HDbkM7RLxLp4DyQa96uJJ09eKPI6NVVSvUVI6pG30",
        "https://play-lh.googleusercontent.com/Xj1lTbNqh2AuoIqNB3Fg-dSFnZW72IKv2oKDsN3IqR0UVrEMjlglb0oDssOAh-_Uig"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Diverse Content: Discretion Advised",
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 4, 2018",
    "lastUpdatedOn": "Jan 3, 2023",
    "updated": 1672813025,
    "version": "1.4.0",
    "comments": [],
    "appId": "dmw.comicworld.app",
    "url": "https://play.google.com/store/apps/details?id=dmw.comicworld.app&hl=en&gl=us"
}