{
    "title": "eGovPH",
    "description": "The eGovPH App serve as the single operating system unifying all government services in a single application. This one-stop-shop platform provides convenience to the public and facilitates effective transactions.\r\n\r\nThis app is supported by several Republic Acts and simplifies government procedures, enhances transparency, reduces corruption and bureaucratic red tape, and promotes ease of doing business.\r\n\r\nAn innovative solution that revolutionizes government services, promoting a more efficient transparent, and responsive government that benefits all Filipinos.",
    "descriptionHTML": "The eGovPH App serve as the single operating system unifying all government services in a single application. This one-stop-shop platform provides convenience to the public and facilitates effective transactions.<br><br>This app is supported by several Republic Acts and simplifies government procedures, enhances transparency, reduces corruption and bureaucratic red tape, and promotes ease of doing business.<br><br>An innovative solution that revolutionizes government services, promoting a more efficient transparent, and responsive government that benefits all Filipinos.",
    "summary": "Get fast and easy access to Philippine government services with eGovPH!",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 6080001,
    "score": 4.7884617,
    "ratings": 143085,
    "reviews": 163,
    "histogram": [
        1367,
        2734,
        1367,
        13670,
        123718
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "DICT eGovernment",
    "developerId": "DICT+eGovernment",
    "developerEmail": "support@e.gov.ph",
    "developerWebsite": "https://e.gov.ph/",
    "developerAddress": null,
    "privacyPolicy": "https://e.gov.ph/privacy-policy",
    "genre": "Business",
    "genreId": "BUSINESS",
    "categories": [
        {
            "name": "Business",
            "id": "BUSINESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/hOMSf0qHKew894rWalyZw1Y-RCB_ShH-UcwgUZApkVQ2eV0j0CXzM7g0qen-Z5L0wEAx",
    "headerImage": "https://play-lh.googleusercontent.com/J1vgbjw_vB8R_bZ-P8UYbwroRC7DSqUXWb62s4ZK6V11AlLknrk8HAt656Vgjo9lil8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/8zvLvrAdAxntW5AWEWug1S5ZbZU03mUmSwL-c8CZVtu4xmIDE0hSyT0sKMxpUva06KiX",
        "https://play-lh.googleusercontent.com/5-OzsIiSQiRcRJ10pyGdxRhtzNyoZfyESxCnc5Bppp_2-SPugz-FsdgBKLDUU3fiL7Y",
        "https://play-lh.googleusercontent.com/B8aO0gkcRlxEAy5RjUZYe_mkvgDnkgB56zdf1B7ueO_bLuOPAUNJahkOp1C1wQzYG1U",
        "https://play-lh.googleusercontent.com/FY5p65P4h4ioEXAaSsVoBPrlrN5cEmprsmyX3okT91mHQkhXpON8u7uzBRVJ8gPdnTY",
        "https://play-lh.googleusercontent.com/t00ahLmIdJH7Zd4KuBLvkyi14giTB0rXjX5bfxZkeeya_r810Wstkge7pYaf1F46Jg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 3, 2023",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729507207,
    "version": "2.4.1",
    "comments": [],
    "appId": "egov.app",
    "url": "https://play.google.com/store/apps/details?id=egov.app&hl=en&gl=us"
}