{
    "title": "Boo: Dating. Friends. Chat.",
    "description": "Boo is for connecting with compatible and like-minded souls. Date, chat, match, make friends and meet new people by personality.\r\n\r\nJoin millions of souls on Boo and find your best match faster, for dating or friendship. \r\n\r\nWe\u2019re your tour guide through the strange landscape of another\u2019s heart and mind. We use personality psychology to help you find dates and friends that'll effortlessly love, appreciate, and understand you for who you naturally are.\r\n\r\nFind your soulmate or your best friend.\r\n\r\nOUR FEATURES\r\n\r\n1. SOCIAL DATING + FRIEND-FINDING\r\nPost in interest communities and meet new people by shared values and interests. Chat casually with people on funny, interesting, and insightful topics.\r\n\r\n2. FLIRTING TIPS\r\nGet in-depth dating tips and personality analysis with cutting-edge personality psychology. \r\n\r\nUnderstand anyone\u2019s\r\n1. Compatibility\r\n2. Strengths\r\n3. Weaknesses\r\n4. Attracted By\r\n5. Pet Peeves\r\n6. Likely Interests\r\n7. Love Languages\r\n8. What You'll Love\r\n9. Potential Conflicts\r\n10. Love Philosophy\r\n11. Mating Call\r\n12. Ideal Date\r\n13. Flirting Tips\r\n14. Relationship Material\r\n15. Relationship Fear\r\n16. Secret Desire\r\n17. Enneagram\r\n18. Zodiac\r\n\r\n3. VERIFIED PROFILES\r\nGet verified and meet other verified users using the verified filter. No more catfishes and bots.\r\n\r\n4. PRACTICE LANGUAGES\r\nMake new friends and meet new people around the world. Translate profiles and messages, and send messages in any language with cutting-edge translation.\r\n\r\nOUR VALUES\r\n\r\n1. LOVE, KINDNESS, EMPATHY\r\nBoo is an accepting, tolerant, and judgment-free space for everyone. Unlock functionalities by being a good person and earning love, our social credit system.\r\n\r\n2. AUTHENTICITY\r\nBe yourself. That\u2019s the only way you\u2019ll attract the right people. Embracing your authentic self starts when you realize that every personality has its flaws, that there are others who share your same personality, and that you are not alone. \r\n\r\n3. TRANSPARENCY\r\nUnderstand yourself and others like never before in human history. Understand anyone deeply instantly, not 3 weeks, months, or years into a failed relationship. \r\n\r\n4. EMPOWERMENT\r\nAttraction, compatibility, and succeeding in dating and making friends have always been a black box. With personality insight, you are empowered to understand how it all works for yourself, make the right decisions, and set yourself up for success.\r\n\r\nWe were using all the dating apps. It was always the same result\u2013going on dates with people we had no chemistry with. We were exhausted from all the wasted time and effort. We made Boo because we knew there was a better way.\r\n\r\nOur mission is to create a future in which personality enables our greatest potential, starting with our relationships.\r\n\r\nWe hope you like it,\r\nThe souls at Boo\r\n\r\nhttps://boo.world/terms-and-conditions",
    "descriptionHTML": "Boo is for connecting with compatible and like-minded souls. Date, chat, match, make friends and meet new people by personality.<br><br>Join millions of souls on Boo and find your best match faster, for dating or friendship. <br><br>We\u2019re your tour guide through the strange landscape of another\u2019s heart and mind. We use personality psychology to help you find dates and friends that&#39;ll effortlessly love, appreciate, and understand you for who you naturally are.<br><br>Find your soulmate or your best friend.<br><br>OUR FEATURES<br><br>1. SOCIAL DATING + FRIEND-FINDING<br>Post in interest communities and meet new people by shared values and interests. Chat casually with people on funny, interesting, and insightful topics.<br><br>2. FLIRTING TIPS<br>Get in-depth dating tips and personality analysis with cutting-edge personality psychology. <br><br>Understand anyone\u2019s<br>1. Compatibility<br>2. Strengths<br>3. Weaknesses<br>4. Attracted By<br>5. Pet Peeves<br>6. Likely Interests<br>7. Love Languages<br>8. What You&#39;ll Love<br>9. Potential Conflicts<br>10. Love Philosophy<br>11. Mating Call<br>12. Ideal Date<br>13. Flirting Tips<br>14. Relationship Material<br>15. Relationship Fear<br>16. Secret Desire<br>17. Enneagram<br>18. Zodiac<br><br>3. VERIFIED PROFILES<br>Get verified and meet other verified users using the verified filter. No more catfishes and bots.<br><br>4. PRACTICE LANGUAGES<br>Make new friends and meet new people around the world. Translate profiles and messages, and send messages in any language with cutting-edge translation.<br><br>OUR VALUES<br><br>1. LOVE, KINDNESS, EMPATHY<br>Boo is an accepting, tolerant, and judgment-free space for everyone. Unlock functionalities by being a good person and earning love, our social credit system.<br><br>2. AUTHENTICITY<br>Be yourself. That\u2019s the only way you\u2019ll attract the right people. Embracing your authentic self starts when you realize that every personality has its flaws, that there are others who share your same personality, and that you are not alone. <br><br>3. TRANSPARENCY<br>Understand yourself and others like never before in human history. Understand anyone deeply instantly, not 3 weeks, months, or years into a failed relationship. <br><br>4. EMPOWERMENT<br>Attraction, compatibility, and succeeding in dating and making friends have always been a black box. With personality insight, you are empowered to understand how it all works for yourself, make the right decisions, and set yourself up for success.<br><br>We were using all the dating apps. It was always the same result\u2013going on dates with people we had no chemistry with. We were exhausted from all the wasted time and effort. We made Boo because we knew there was a better way.<br><br>Our mission is to create a future in which personality enables our greatest potential, starting with our relationships.<br><br>We hope you like it,<br>The souls at Boo<br><br>https://boo.world/terms-and-conditions",
    "summary": "The dating app to match, chat, make friends, and meet people by personality.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 21159846,
    "score": 3.987348,
    "ratings": 2106765,
    "reviews": 57591,
    "histogram": [
        126073,
        92810,
        395211,
        560218,
        932421
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.00 - $269.99 per item",
    "developer": "Boo Enterprises, Inc.",
    "developerId": "8817941093994408218",
    "developerEmail": "hello@boo.world",
    "developerWebsite": "https://boo.world",
    "developerAddress": "525 3rd Street\nLake Oswego, Oregon 97034\nUSA",
    "privacyPolicy": "https://boo.world/privacy-policy",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/7odIr8zuMI5ddrSG6KtefaVNEvKBoiGzo6Q96lowbP5tLFhqiqUl3Mc16PMk2E1m9g",
    "headerImage": "https://play-lh.googleusercontent.com/a4MnPGXRaw3zNQsBSnXn-Sok7hxMMC17pvSrilndOBI1_Dtd42YPk_JAI9HXNvmxTZ4",
    "screenshots": [
        "https://play-lh.googleusercontent.com/_syJvVWtqFIxvQhilr2b36c3Mk-yyNkyzZNi56XPYkyhRUqxwOSh44GoFZFxPwharA",
        "https://play-lh.googleusercontent.com/H-Psmq7Vu37qpAg9FbMBIdSPS69U7_oW80ibswsXAaUqEUKTqsd-m7n7i2XC30gj-Mc",
        "https://play-lh.googleusercontent.com/gakun3jnKWXcDX7kHHIa-HEyQYRiE0XhWR4R2siBk8nitKhhXrmX0mel_pGVygSA9eA",
        "https://play-lh.googleusercontent.com/CEjvdwNJzuh3u-twksg4o0JayUjmGguhaR7qh7db5HIfBjPUhi1BnZ59bnUdt5D7MhUn",
        "https://play-lh.googleusercontent.com/H3Ew550wgN7piei4L147xlo79EQb7rqxRSZjrYAEzBwUP7UIAwvwWf39vyACYfdIeRs",
        "https://play-lh.googleusercontent.com/_VaLM2OglYmvzi_Wb0jlgKwMKAmbZsHNSZhk2I-45QMt3_PwbJ8NlVVUAs66k5cfw_4",
        "https://play-lh.googleusercontent.com/YeHIZu11-73o_HtGq13mk-x1qaErGM6-vCMKlmLjOaz70iOp2MFe9zv9coJKst6AY0Y",
        "https://play-lh.googleusercontent.com/z8X7jHlWUHBBgkCJ5_2X7HGe2u4jF9DWZyGcXZE8tgPU_j2CDosERGS9UUEzbGIRKg",
        "https://play-lh.googleusercontent.com/gCvUhpzWc3kheJJH5x-dMYkQM9zMLLarVT05R7fDEemTL-wSXq5M40md06DSyg5rcw",
        "https://play-lh.googleusercontent.com/tYcbLKtJM0LG7IKdPGIaR6eJN_QW9XQPw8g5v7Cre8wB1Hb5pNy4yDhPoxKUGCNES-Yz",
        "https://play-lh.googleusercontent.com/NtNJxRNDIWKJ54BnBl_ZvnE4hDTHd2jod8ORF6thYSCy-Wy6WrehZR2Rc_b_SmBBp2nN",
        "https://play-lh.googleusercontent.com/srJpT1d3Eidu4v6SyhB5AB0yhHPfa1MXsZ83NkGxSMJfbB9sNuDXe49z6w3JjfOH6Q",
        "https://play-lh.googleusercontent.com/20CNEQxA5lpQCLqcLLD8zoEh45ZxVVCMg0oTqxsm2AVnEyE5xoveNyMkGLy7_7X20FE",
        "https://play-lh.googleusercontent.com/BrPYmO9RKMviuUeRk0e0HfTdpMhBdmyWhlhLohxlWSrrP_MjOqvDpCAJstwx9JdYMw",
        "https://play-lh.googleusercontent.com/-onKC62Br2WAk012Iaf1Z08ljnincpWPsds6Ll8bWs0zfX62Aw0Ab2smcFQq7xSCqTIq",
        "https://play-lh.googleusercontent.com/GY_DL40PABEotpcK9wjZdoRadl45x9GHUjUAY9qJFcnyVpkR3xZcXGopNA9UwOb-MQ",
        "https://play-lh.googleusercontent.com/zICOVFpOekr6DfepVhyu3rhgzMhEPAK2e89f69pugTh44TYFspTC1c5j20_qCzms48I",
        "https://play-lh.googleusercontent.com/5MYNDMfwfMgnStriZJPwBiwSQIqn0rK_ythhcZKO3Z0HrOWzEqBfcnqZf4_nOOOUtg",
        "https://play-lh.googleusercontent.com/xmGTcqdgL6WJuZptoWlHBCiUqAXHA_mMUjogsHJwuPd8T9y7GGvZBeAdmCBFoCxCfg",
        "https://play-lh.googleusercontent.com/vq5wFOMG6OkWtfLfJazAbbxXIkW7fYwBvgbcUDFdU0YgoNE1zszKNRj9Gl_iwORbjic",
        "https://play-lh.googleusercontent.com/39MS4YO-rlUZGeIVJ5B8bkUyrXAsIaiXCzh9Ym-U1HFUBQcp07TJuBqhy82q2Nd6UoZf"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 22, 2020",
    "lastUpdatedOn": "Oct 20, 2024",
    "updated": 1729440001,
    "version": "1.13.66",
    "comments": [],
    "appId": "enterprises.dating.boo",
    "url": "https://play.google.com/store/apps/details?id=enterprises.dating.boo&hl=en&gl=us"
}