{
    "title": "Faceoff - Song Quiz",
    "description": "Play the #1 song quiz game completely hands-free - all you need is your voice! Compete against your friends or the globe in music trivia events.\r\n\r\nJump into daily song trivia challenges and guess as many song titles and artists as you can within the time limit! Can you top the leaderboards and prove your music mastery?\r\n\r\nWant to take the competition to the next level? Create live video challenges together with your friends and rivals!",
    "descriptionHTML": "Play the #1 song quiz game completely hands-free - all you need is your voice! Compete against your friends or the globe in music trivia events.<br><br>Jump into daily song trivia challenges and guess as many song titles and artists as you can within the time limit! Can you top the leaderboards and prove your music mastery?<br><br>Want to take the competition to the next level? Create live video challenges together with your friends and rivals!",
    "summary": "Hang out & play games with your voice!",
    "installs": "1,000+",
    "minInstalls": 1000,
    "realInstalls": 1545,
    "score": 3,
    "ratings": 14,
    "reviews": 9,
    "histogram": [
        7,
        0,
        0,
        0,
        7
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Volley Inc.",
    "developerId": "Volley+Inc.",
    "developerEmail": "hello@volleygames.com",
    "developerWebsite": "https://www.volleygames.com/",
    "developerAddress": "523 Octavia St\nSan Francisco, CA 94102",
    "privacyPolicy": "https://www.volleythat.com/terms-of-service",
    "genre": "Trivia",
    "genreId": "GAME_TRIVIA",
    "categories": [
        {
            "name": "Trivia",
            "id": "GAME_TRIVIA"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/VC32tQa4CxSARy4rz0rWmJf0d2X9YkgMJtHTeQ0QY1ExwEwFAI2LF36aaq5szJfL5Q",
    "headerImage": "https://play-lh.googleusercontent.com/tigmnfhpGfS2wzxxKEQ_SXtMyie_4oKP6zxVKpMCxwOozbIB2P37HQSWrmdSycwn10ak",
    "screenshots": [
        "https://play-lh.googleusercontent.com/CHoCBd61nFapE9T7Z8nGGolNMDkz-Yr4EMQvO-c7QtegUzrcXbuoqxRjVm0JkZSwSQ",
        "https://play-lh.googleusercontent.com/Us8NLdOufcjyNowlw9OxXO8eDSrZ-usdjS0m4o-pb80JND75gbvpKs6tngdGVeuu2Q",
        "https://play-lh.googleusercontent.com/-8_bfQCSRlSRGghIZTkXG5-tO07D3DlBBAdS5lrsU4YiZN4tSgItzL1y3wDu5nsvAZj-",
        "https://play-lh.googleusercontent.com/8FD-oH8pYLf3ZQDs9icGIdVrROcXOUW_2kRGxZckvvcP7TLvaqoGKUrEpmZvYRQuCntt",
        "https://play-lh.googleusercontent.com/0QZl87JC95u6NscqEcjZHJla7o_XodUM8JeiRlSs5P61Gq1Ku190Ehs20fMXDP_xnM3x",
        "https://play-lh.googleusercontent.com/CxeU1uZyvpOh13L2IbEdIIMIDh4nnYMC2bTh4gFszFUlLDyQUTzlQes_aAmLGNJDkTY",
        "https://play-lh.googleusercontent.com/fm7cnf46PZIa4Cfdff3Dd4ZdkdPUms9IVzmhmnY7yY78Ywrh9lprbj_qiivU1__RynY"
    ],
    "video": "https://www.youtube.com/embed/cYO-h47NJbQ?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/tigmnfhpGfS2wzxxKEQ_SXtMyie_4oKP6zxVKpMCxwOozbIB2P37HQSWrmdSycwn10ak",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 6, 2023",
    "lastUpdatedOn": "Aug 16, 2024",
    "updated": 1723827976,
    "version": "2024.08.02",
    "comments": [],
    "appId": "faceoff.app",
    "url": "https://play.google.com/store/apps/details?id=faceoff.app&hl=en&gl=us"
}