{
    "title": "Flipboard:Your Social Magazine",
    "description": "Get all the headlines and dive deep into the stories that matter to you with the award-winning Flipboard app. Flipboard is filled with the latest articles, videos and insights, curated by experts, on thousands of topics like business, health, sports, tech and travel. \r\n\r\nPersonalize Flipboard by selecting topics or following people on federated social networks like Threads and Mastodon to get just the content you care about. You can even follow local news and events. Just enable location services to get a list of towns and cities near you.\r\n\r\nCollect stories you like into your own Flipboard Magazine. Use the + (plus) button on any story in Flipboard to add it to your own Magazine. Make your Magazine public to share ideas and insights with an ever-growing community of enthusiasts curating on Flipboard.\r\n\r\nUSE FLIPBOARD TO:\r\n\r\n<b>\u2022</b> Keep up on all your interests with the latest stories from leading national publishers including Associate Press, The Washington Post, ESPN, National Geographic, NPR, TIME, The Atlantic, BBC, CBS, NBC and thousands more.\r\n<b>\u2022</b> Follow your city for local updates on COVID-19 as well as other regional news, weather, commute, sports, and dining.\r\n<b>\u2022</b> Curate stories you find informative or inspiring and share with others: Use the + (plus) button on any article to save it to your own Flipboard Magazine.\r\n<b>\u2022</b> Follow other experts and enthusiasts who are curating about topics you love.\r\n<b>\u2022</b> Turn on notifications and use the Flipboard widget to get stories delivered to you everyday.\r\n\r\nGET FLIPBOARD IN YOUR INBOX:\r\n\r\nGet the amazing content and curation on Flipboard delivered to your Inbox. There\u2019s a Flipboard Newsletter for all of our most popular topics. Sign up for The Tastiest for foodies, the Tech Briefing for tech enthusiasts, the Climate Briefing for environmental news, Wanderlust for travelers, The Shot for photographers and many more. \r\nVisit flipboard.com/newsletters to view and subscribe to all of the Flipboard Newsletters.\r\n\r\nKEEP UP WITH FLIPBOARD:\r\n\r\nFor product updates, the latest from our blog, and tips on how to use Flipboard, follow us on Flipboard and other social platforms:\r\nhttps://flipboard.com/@flipboard\r\nwww.twitter.com/@flipboard\r\nwww.facebook.com/Flipboard\r\nhttps://www.instagram.com/flipboard/\r\n\r\nWe\u2019d love to hear what you think! Reach out to our support team under Settings > Help & Feedback. For any other technical issues or questions, contact us at http://flip.it/help .",
    "descriptionHTML": "Get all the headlines and dive deep into the stories that matter to you with the award-winning Flipboard app. Flipboard is filled with the latest articles, videos and insights, curated by experts, on thousands of topics like business, health, sports, tech and travel. <br><br>Personalize Flipboard by selecting topics or following people on federated social networks like Threads and Mastodon to get just the content you care about. You can even follow local news and events. Just enable location services to get a list of towns and cities near you.<br><br>Collect stories you like into your own Flipboard Magazine. Use the + (plus) button on any story in Flipboard to add it to your own Magazine. Make your Magazine public to share ideas and insights with an ever-growing community of enthusiasts curating on Flipboard.<br><br>USE FLIPBOARD TO:<br><br><b>\u2022</b> Keep up on all your interests with the latest stories from leading national publishers including Associate Press, The Washington Post, ESPN, National Geographic, NPR, TIME, The Atlantic, BBC, CBS, NBC and thousands more.<br><b>\u2022</b> Follow your city for local updates on COVID-19 as well as other regional news, weather, commute, sports, and dining.<br><b>\u2022</b> Curate stories you find informative or inspiring and share with others: Use the + (plus) button on any article to save it to your own Flipboard Magazine.<br><b>\u2022</b> Follow other experts and enthusiasts who are curating about topics you love.<br><b>\u2022</b> Turn on notifications and use the Flipboard widget to get stories delivered to you everyday.<br><br>GET FLIPBOARD IN YOUR INBOX:<br><br>Get the amazing content and curation on Flipboard delivered to your Inbox. There\u2019s a Flipboard Newsletter for all of our most popular topics. Sign up for The Tastiest for foodies, the Tech Briefing for tech enthusiasts, the Climate Briefing for environmental news, Wanderlust for travelers, The Shot for photographers and many more. <br>Visit flipboard.com/newsletters to view and subscribe to all of the Flipboard Newsletters.<br><br>KEEP UP WITH FLIPBOARD:<br><br>For product updates, the latest from our blog, and tips on how to use Flipboard, follow us on Flipboard and other social platforms:<br>https://flipboard.com/@flipboard<br>www.twitter.com/@flipboard<br>www.facebook.com/Flipboard<br>https://www.instagram.com/flipboard/<br><br>We\u2019d love to hear what you think! Reach out to our support team under Settings &gt; Help &amp; Feedback. For any other technical issues or questions, contact us at http://flip.it/help .",
    "summary": "Award winning app for latest news and informative stories you want every day.",
    "installs": "500,000,000+",
    "minInstalls": 500000000,
    "realInstalls": 843756137,
    "score": 3.5329745,
    "ratings": 1421110,
    "reviews": 135518,
    "histogram": [
        333411,
        109570,
        113533,
        195365,
        669222
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Flipboard",
    "developerId": "7019463006329470284",
    "developerEmail": "play-store-support@flipboard.com",
    "developerWebsite": "https://about.flipboard.com/help-center/",
    "developerAddress": null,
    "privacyPolicy": "https://about.flipboard.com/privacy-policy/",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Z5WroTW4KmTB3mvUhZMLwgFD2VymNypnEVVxoueXPPCKEFrnUAiZVl0684t1RFEOPqzB",
    "headerImage": "https://play-lh.googleusercontent.com/idMTJUsR0YU3qummE_jbyVhWYOMaWpzWTIWjfOXFgK0o5A1PV0icB0YfqQ61KbiuBA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ZSIc_5Vpdr-aKMTkzS1eCzPmOTbLujxlKTprnUkaZIVCIwAkpdQJn9orFvlv8zdSeyg",
        "https://play-lh.googleusercontent.com/Oal7RDC6N0P34OI0Qvqn4Qv_jlEwDMonVOABQ6LEHaxuNmyXXhLLOAyu0FNgmESHbQ",
        "https://play-lh.googleusercontent.com/mJ8i7L272zxYU46YiqYmBo8MC1k_RrR39G_tsrd7ZVBqeGaDNqXws_9cj1KL3gDzEM0",
        "https://play-lh.googleusercontent.com/BxFOiE5JgOIeuIiSFL8uNouOEQjCtk09G1n8bNN9OIxJmOtwzen3mADuP_Jz2YcGjvs",
        "https://play-lh.googleusercontent.com/AGsMvnoswDM_hXCdCwv2Hp6Vq9bps0pzTx1PLgeGYL8qNUyQ5JWMQXRkbCzQOLjHWLY",
        "https://play-lh.googleusercontent.com/n-CrRAB25SyN0THenhv2xjZff5zRh8op9L5Ri_EFF08B7_jPlcqDyoAqek-DTEkUJQ",
        "https://play-lh.googleusercontent.com/mh9DKHLk-j0qEpi4C5mfGlBZEuCDrXNGhx9v3w1uLOQ3RhozZ_gN43aHvU3MabT6kA",
        "https://play-lh.googleusercontent.com/R15TBYHuUwtZWcvBLpVwVCkrUORAIi7sQEnjNwM0wGbfFyqKemQsxfrlj3nGs9X_R8A",
        "https://play-lh.googleusercontent.com/3Ybo9EnCKjWGASVefLZO2p2uwhMGZgsFNq45ckNj4tMM61f4iypHNKn_-ly7l1gPrCSb",
        "https://play-lh.googleusercontent.com/1ZZXe-wybTyOI_wVTLEThVrP-GtzbLk3zarn9BsmxRae950o0M7sRxM5ioHbbl46GTQ",
        "https://play-lh.googleusercontent.com/7ngbsdh4UVQoE4YgBSMTmou3F7FGq7No58eRY8YYs-LYiVDU9pGYERBe8wAiJWuIBSgB",
        "https://play-lh.googleusercontent.com/vQaqU50vBfnKQ_St9-jO6U0kHLaIvsFMAXddWfQzTjo9nvZbBZbHjvdBIobzUCPGAA",
        "https://play-lh.googleusercontent.com/UgaPDW-ZAlt2TIqVX9reir-GYkmP3KuMVFY2df4aILcq4tAOdO-VCtpPQQa_CujhaA",
        "https://play-lh.googleusercontent.com/yrHbKUui8kR_mQS3DQCr696ZCpgEwI0G9_DGgWTnZ5J5zaYggEGztd2DW5iiFHxsb3SY",
        "https://play-lh.googleusercontent.com/zli-mWwHqAWsa_hVlwLoftrontZfiqXmrc6qEO7jpY87syneEFMExvl40vxMJkiM6A"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone 10+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 21, 2012",
    "lastUpdatedOn": "Sep 30, 2024",
    "updated": 1727685833,
    "version": "4.3.31",
    "comments": [],
    "appId": "flipboard.app",
    "url": "https://play.google.com/store/apps/details?id=flipboard.app&hl=en&gl=us"
}