{
    "title": "Swift Watch Face",
    "description": "Swift Watch Face for Wear OS!\r\n\r\nDon't have a Wear OS watch? You can still use this watch face as a clock widget on your mobile!\r\n\r\n<font color=\"#ff0000\"><b>\u26d4\ufe0fNOT FOR SAMSUNG GEAR S2 / GEAR S3 !! (running Tizen OS)\u26d4\ufe0f\r\nIf you have one, do not install this application.\r\nTo find support and compatible applications with your watch, please go to <u>http://www.themaapps.com/watch_on_tizen_os</u></b></font>\r\n\r\n<b>\u2605 Features of Swift Watch Face \u2605</b>\r\n\r\n- Clock Widget (No second hand due to battery consumption)\r\n- Choose design colors\r\n- Day & Month\r\n- Watch battery\r\n- Mobile battery (requires phone app)\r\n- Weather (requires phone app)\r\n\r\n\r\nThe settings of the watch face are located in the \"Wear OS\" app of your mobile.\r\nJust hit the gear icon over the watch face preview and the settings screen will show up!\r\n\r\n\r\n<b>\u2605 FREE Settings \u2605</b>\r\n- Choose design colors on watch & mobile\r\n- Define heartbeat frequency refresh rate\r\n- Define weather refresh rate\r\n- Weather unit\r\n- 12 / 24 hours mode\r\n- Define interactive mode duration\r\n- Choose the ambient mode b&w and eco luminosity\r\n- Choose to display a leading zero on hours\r\n- Display brand name or not\r\n- Choose to display or not the seconds dots\r\n\r\n\r\n<b>\u2605 PREMIUM Settings \u2605</b>\r\n- Choose your own title in place of \"SWIFT\"\r\n- Switch between \u00e9co / simple b&w / full ambient mode\r\n- Choose background among different styles\r\n- Blend background with colors\r\n- Define a secondary timezone for digital display\r\n- Data:\r\n    + Change the indicator to display on the 3 positions\r\n    + Choose between up to 8 indicators (Daily step count, Heartbeat frequency, Unread Email from Gmail, etc...)\r\n    + Complication (wear 2.0 & 3.0)\r\n- Interactivity\r\n    + Access to detailed data by touching a widget\r\n    + Switch the displayed data by touching a widget\r\n    + Change the shortcut to execute on the 4 positions\r\n    + Choose your shortcut among all applications installed on your watch!\r\n    + Choose to display the interactive areas\r\n\r\n\r\n<b>\u2605 Additional settings on phone \u2605</b>\r\nThe optional phone app is an easiest way to customize the watch face. It provides additional settings and data.\r\n- Choose to switch between small/big/translucent/opaque cards (Wear 1.5x only)\r\n- Choose between 2 weather providers (Yr & OpenWeatherMap)\r\n- Define manual or automatic location\r\n- Notifications for new designs\r\n- Presets manager:\r\n    + Save your preset with all its options (colors, backgrounds, data, features. EVERYTHING is saved!)\r\n    + Load / delete one of your previously saved preset\r\n    + Share / Import presets\r\n\r\n\r\n<b>\u2605 Installation \u2605</b>\r\n<u>Watch Face</u>\r\nWear OS 1.X\r\nThis watch face will be installed automatically from your phone paired.\r\nIf it doesn't show up please go to the Wear OS App > Settings and Resync all apps.\r\nWear OS 2.X\r\nA notification will be displayed on your watch, right after your mobile installation. You just have to hit it to start the installation process of the watch face.\r\nIf the notification did not display for some reason, you can still install the watch face by using the Google Play Store available on your watch: just search the watch face by its name.\r\n\r\n<u>Mobile clock widget</u>\r\nJust long press on your launcher, then select the application widget to drop it on your home screen of your mobile.\r\nCustomize the widget settings with the application.\r\n\r\n<b>\u2605 More watch faces</b>\r\n\r\nVisit my watch faces collection for Wear OS on the Play Store at https://goo.gl/CRzXbS\r\n\r\n\r\n** If you have any issues or questions, fill free to contact me by email (English or French language) before giving a bad rating. Thanks!\r\n\r\n\r\nWebsite: https://www.themaapps.com/\r\nYoutube: https://youtube.com/ThomasHemetri\r\nTwitter: https://x.com/ThomasHemetri\r\nInstagram: https://www.instagram.com/thema_watchfaces",
    "descriptionHTML": "Swift Watch Face for Wear OS!<br><br>Don&#39;t have a Wear OS watch? You can still use this watch face as a clock widget on your mobile!<br><br><font color=\"#ff0000\"><b>\u26d4\ufe0fNOT FOR SAMSUNG GEAR S2 / GEAR S3 !! (running Tizen OS)\u26d4\ufe0f<br>If you have one, do not install this application.<br>To find support and compatible applications with your watch, please go to <u>http://www.themaapps.com/watch_on_tizen_os</u></b></font><br><br><b>\u2605 Features of Swift Watch Face \u2605</b><br><br>- Clock Widget (No second hand due to battery consumption)<br>- Choose design colors<br>- Day &amp; Month<br>- Watch battery<br>- Mobile battery (requires phone app)<br>- Weather (requires phone app)<br><br><br>The settings of the watch face are located in the &quot;Wear OS&quot; app of your mobile.<br>Just hit the gear icon over the watch face preview and the settings screen will show up!<br><br><br><b>\u2605 FREE Settings \u2605</b><br>- Choose design colors on watch &amp; mobile<br>- Define heartbeat frequency refresh rate<br>- Define weather refresh rate<br>- Weather unit<br>- 12 / 24 hours mode<br>- Define interactive mode duration<br>- Choose the ambient mode b&amp;w and eco luminosity<br>- Choose to display a leading zero on hours<br>- Display brand name or not<br>- Choose to display or not the seconds dots<br><br><br><b>\u2605 PREMIUM Settings \u2605</b><br>- Choose your own title in place of &quot;SWIFT&quot;<br>- Switch between \u00e9co / simple b&amp;w / full ambient mode<br>- Choose background among different styles<br>- Blend background with colors<br>- Define a secondary timezone for digital display<br>- Data:<br>    + Change the indicator to display on the 3 positions<br>    + Choose between up to 8 indicators (Daily step count, Heartbeat frequency, Unread Email from Gmail, etc...)<br>    + Complication (wear 2.0 &amp; 3.0)<br>- Interactivity<br>    + Access to detailed data by touching a widget<br>    + Switch the displayed data by touching a widget<br>    + Change the shortcut to execute on the 4 positions<br>    + Choose your shortcut among all applications installed on your watch!<br>    + Choose to display the interactive areas<br><br><br><b>\u2605 Additional settings on phone \u2605</b><br>The optional phone app is an easiest way to customize the watch face. It provides additional settings and data.<br>- Choose to switch between small/big/translucent/opaque cards (Wear 1.5x only)<br>- Choose between 2 weather providers (Yr &amp; OpenWeatherMap)<br>- Define manual or automatic location<br>- Notifications for new designs<br>- Presets manager:<br>    + Save your preset with all its options (colors, backgrounds, data, features. EVERYTHING is saved!)<br>    + Load / delete one of your previously saved preset<br>    + Share / Import presets<br><br><br><b>\u2605 Installation \u2605</b><br><u>Watch Face</u><br>Wear OS 1.X<br>This watch face will be installed automatically from your phone paired.<br>If it doesn&#39;t show up please go to the Wear OS App &gt; Settings and Resync all apps.<br>Wear OS 2.X<br>A notification will be displayed on your watch, right after your mobile installation. You just have to hit it to start the installation process of the watch face.<br>If the notification did not display for some reason, you can still install the watch face by using the Google Play Store available on your watch: just search the watch face by its name.<br><br><u>Mobile clock widget</u><br>Just long press on your launcher, then select the application widget to drop it on your home screen of your mobile.<br>Customize the widget settings with the application.<br><br><b>\u2605 More watch faces</b><br><br>Visit my watch faces collection for Wear OS on the Play Store at https://goo.gl/CRzXbS<br><br><br>** If you have any issues or questions, fill free to contact me by email (English or French language) before giving a bad rating. Thanks!<br><br><br>Website: https://www.themaapps.com/<br>Youtube: https://youtube.com/ThomasHemetri<br>Twitter: https://x.com/ThomasHemetri<br>Instagram: https://www.instagram.com/thema_watchfaces",
    "summary": "Swift Watch Face is an interactive digital watch face with 8 data to display",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 982292,
    "score": 4.5222673,
    "ratings": 10353,
    "reviews": 740,
    "histogram": [
        292,
        376,
        502,
        1632,
        7540
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.19 - $11.99 per item",
    "developer": "thema",
    "developerId": "8924399009186125086",
    "developerEmail": "thema.apps@gmail.com",
    "developerWebsite": "http://www.themaapps.com/",
    "developerAddress": "Plaisir\nFRANCE",
    "privacyPolicy": "http://www.themaapps.com/privacy-policy/",
    "genre": "Personalization",
    "genreId": "PERSONALIZATION",
    "categories": [
        {
            "name": "Personalization",
            "id": "PERSONALIZATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/xo2rNcwdq-szOdmRgd7wz98krEyx5_IQugN39yy6LJkBUKh6lR8jSNXBRru28AY0SPo",
    "headerImage": "https://play-lh.googleusercontent.com/Z2xeJZHvnEzEWGJZgik9PclJ3ABZQs68jYSmLxgj23Jyt4HtGvUdlHYST2JKLuc4sg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/3DHS3kbtgnP4EmorB6iux9VwU7hnMVUcgcT2o3mpFa_iM4fu0kNi488K1A1FqoX5xg",
        "https://play-lh.googleusercontent.com/30-zVPt2Lz1ZbBCJq9o-36pv-ONPBLwjStQvw4SX8VUc0wGyxFDNf3BzSRcNlp5LE4iz",
        "https://play-lh.googleusercontent.com/bc7k9zxU9oaVLp6JdHI3uA3Lg084p5K63Yi3uHm32z5AK5cdesZrrwrsDFPcBaG_fPs",
        "https://play-lh.googleusercontent.com/7HN32vLol_fZFdMWLDkh1rO5shvnzl2fGmpcoj7wPo_SZEeLcgoEJXIGCokjgiqGZg",
        "https://play-lh.googleusercontent.com/R0-ncTiWObbr8nQ9O0HCPX4TaG4vWE-JReW50WbwJkpmqfIKDROzZbrQGNAVY6e1Dik",
        "https://play-lh.googleusercontent.com/SQu6SqR1fathCmzYdodhYjnFkwiNZkvU0zQOwesSEkxr1aRXuwV3wK9vH82dcPoNtuk",
        "https://play-lh.googleusercontent.com/9rQaf_1avwbpDOadXD1TFpXuP5ApcDsuAxwawHNDyILisrxP7hoyGvSRKDmX8yKgsaQ",
        "https://play-lh.googleusercontent.com/5guF_QusP88PLQzB6OmB2ptVwf89rJey6R1v7-cZvYzFjY5iCrUNX4yYwukhA0T4Tps",
        "https://play-lh.googleusercontent.com/9DBe5nfpZZMqwZxhvTqZ3oTKRqqKhwJ5DwYDkeJ6B-zsu9mErNoKZSc3EqqT1kUMkg",
        "https://play-lh.googleusercontent.com/BlHyvfwJzfWj0P1pLVecmYYDYXpFCPtEgThEsbn1IvXgEWRaJAEDExK6LU9yjLBOZnHr",
        "https://play-lh.googleusercontent.com/PDKBOfTXNJU1w3uV0lAk7za9xVvFIB2NWhdXV0nQmHIfE-udHXWxOpkmPzcmWoBOo2Y",
        "https://play-lh.googleusercontent.com/tlQ-c5Y0TmVpKSpyeCQUhHO2KUUQUZSb0z9rGQkOLHaqQRiuX_WWLwsiLhiqdhp61YqB",
        "https://play-lh.googleusercontent.com/HfQN8-WMIuI6YrStOOn2H2cbRcd58k0kGuQYllJVfUrXn8KwKCCjETIfBkfeFA9Cquk",
        "https://play-lh.googleusercontent.com/EboC-F0hkkf3BbRupAgjLINoXKoczRLiv1hzvrRjGiSONuRjbB-aTyxvy4SxnUxxvA",
        "https://play-lh.googleusercontent.com/8GKOsLYcoc1lPxZYlxOzkl4BxG4Ig0lYrxcqTJmY6R0GO_FYgna_i9BUK-OAndQeLl_O",
        "https://play-lh.googleusercontent.com/ssY0I76sh0FLXDBflb3r62yNNb2RwGuqiCZpXTTUh6OGDz60LpSs49DJSP4xKS0_teM"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 4, 2017",
    "lastUpdatedOn": "Jul 18, 2024",
    "updated": 1721333192,
    "version": "Varies with device",
    "comments": [],
    "appId": "fr.thema.wear.watch.swift",
    "url": "https://play.google.com/store/apps/details?id=fr.thema.wear.watch.swift&hl=en&gl=us"
}