{
    "title": "Storytel - Audiobooks & Books",
    "description": "Welcome to a wide world of wonderful audiobooks, ebooks, and things that aren\u2019t books but are still pretty great.\r\n\r\nStorytel is home to beloved stories, in-depth podcasts, and exclusive Storytel Originals.\r\n\r\nWhether you listen or read, you\u2019ll find the right story for any moment.\r\n\r\n\u2022 Explore a massive library of stories in English and other languages\r\n\u2022 Jump freely from story to story until you find one you love\r\n\u2022 Build your bookshelf and get personalized recommendations\r\n\u2022 Find what fits your mood, like crime, feel-good, or self-development\r\n\u2022 Follow your favorite authors and series\r\n\u2022 Browse and share reviews and reactions\r\n\u2022 Try out that book your friend keeps talking about\r\n\u2022 Discover what\u2019s trending in the culture\r\n\r\n<b>LISTEN AND READ YOUR WAY</b>\r\n\r\n\u2022 Listen to audio stories on your mobile, tablet, Chromecast, and Wear OS watch, as well as in your car (Android Auto, Android Automotive)\r\n\u2022 Stream stories or download them for later\r\n\u2022 Switch between listening and reading anywhere in a book\r\n\u2022 Listen at your own pace: regular, sped up, or slowed down\r\n\u2022 Set bookmarks and attach your thoughts as notes\r\n\u2022 Drift off to dreamland with the sleep timer\r\n\u2022 Spare those pretty eyes with Dark Mode\r\n\u2022 See your stats and set a Listening Goal\r\n\r\n<b>KIDS MODE INCLUDED</b>\r\n\r\n\u2022 Let your kid find adventure in a space with just children\u2019s stories\r\n\u2022 Show or hide children\u2019s books in your bookshelf\r\n\u2022 Set your own pin code for parental control\r\n\r\n<b>HOW IT WORKS</b>\r\n\r\nStorytel is available in 25+ countries, including both local and international story treasures in different languages. A subscription gives you access to our ever-growing library of audiobooks, ebooks, and other stories.\r\n\r\nWhen a free trial is offered, we will ask you to add a payment method when starting the trial. But don't worry \u2013 if you cancel before the last day of the trial you won't be charged.\r\n\r\nThe content, languages and subscriptions available may vary by region. Some titles and offers shown above may not be available in your country or selected subscription plan.\r\n\r\nTerms and conditions: https://www.storytel.com/documents/terms-and-conditions\r\n\r\nPrivacy policy: https://www.storytel.com/documents/privacy-policy\r\n\r\nQuestions? Feedback? Speak to a real person! Reach us at support@storytel.com",
    "descriptionHTML": "Welcome to a wide world of wonderful audiobooks, ebooks, and things that aren\u2019t books but are still pretty great.<br><br>Storytel is home to beloved stories, in-depth podcasts, and exclusive Storytel Originals.<br><br>Whether you listen or read, you\u2019ll find the right story for any moment.<br><br>\u2022 Explore a massive library of stories in English and other languages<br>\u2022 Jump freely from story to story until you find one you love<br>\u2022 Build your bookshelf and get personalized recommendations<br>\u2022 Find what fits your mood, like crime, feel-good, or self-development<br>\u2022 Follow your favorite authors and series<br>\u2022 Browse and share reviews and reactions<br>\u2022 Try out that book your friend keeps talking about<br>\u2022 Discover what\u2019s trending in the culture<br><br><b>LISTEN AND READ YOUR WAY</b><br><br>\u2022 Listen to audio stories on your mobile, tablet, Chromecast, and Wear OS watch, as well as in your car (Android Auto, Android Automotive)<br>\u2022 Stream stories or download them for later<br>\u2022 Switch between listening and reading anywhere in a book<br>\u2022 Listen at your own pace: regular, sped up, or slowed down<br>\u2022 Set bookmarks and attach your thoughts as notes<br>\u2022 Drift off to dreamland with the sleep timer<br>\u2022 Spare those pretty eyes with Dark Mode<br>\u2022 See your stats and set a Listening Goal<br><br><b>KIDS MODE INCLUDED</b><br><br>\u2022 Let your kid find adventure in a space with just children\u2019s stories<br>\u2022 Show or hide children\u2019s books in your bookshelf<br>\u2022 Set your own pin code for parental control<br><br><b>HOW IT WORKS</b><br><br>Storytel is available in 25+ countries, including both local and international story treasures in different languages. A subscription gives you access to our ever-growing library of audiobooks, ebooks, and other stories.<br><br>When a free trial is offered, we will ask you to add a payment method when starting the trial. But don&#39;t worry \u2013 if you cancel before the last day of the trial you won&#39;t be charged.<br><br>The content, languages and subscriptions available may vary by region. Some titles and offers shown above may not be available in your country or selected subscription plan.<br><br>Terms and conditions: https://www.storytel.com/documents/terms-and-conditions<br><br>Privacy policy: https://www.storytel.com/documents/privacy-policy<br><br>Questions? Feedback? Speak to a real person! Reach us at support@storytel.com",
    "summary": "Big name books and exclusive stories you'll love to listen to.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 36203027,
    "score": 4.1392756,
    "ratings": 456897,
    "reviews": 1037,
    "histogram": [
        69995,
        10070,
        22875,
        36800,
        316781
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.49 - $179.99 per item",
    "developer": "Storytel Sweden AB",
    "developerId": "Storytel+Sweden+AB",
    "developerEmail": "support@storytel.com",
    "developerWebsite": "https://www.storytel.com",
    "developerAddress": "Tryckerigatan 4\n111 28 Stockholm\nSweden",
    "privacyPolicy": "https://www.storytel.com/sg/en/documents/privacy-policy",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ufvs48ZAzaZLOsW5l3Rw3xrSwKtkt0FEGfLWYd8Dmmw2bJJP_faRr0WesNq_rCqGCg",
    "headerImage": "https://play-lh.googleusercontent.com/9tbTieCdvX80PDGVzZ-ZqxnQ5PiUR1R5e0BxJ4ZeOlRdRMKVTImlRExCtW3reH-P2Yc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/5JgI-2UEMUdhKx77VXxheOOTWIvU-b7mNy4O8_8HPJz4qHXKp8i4HmU5M2aXJvj5iKA",
        "https://play-lh.googleusercontent.com/FQ3k4ZP9K1QLFmASQG9icYUGozexJluzH1VUCoZ_ZiMhIrDrgZnisxudEoGJ7PehjCc",
        "https://play-lh.googleusercontent.com/pX2nyz4yCrfJVkOY1qCMswSlNmpnR8DQPAihsuJ5zS8aIt9O0FOAkUNeQSVO_M64EWw1",
        "https://play-lh.googleusercontent.com/mfnkubqDSfdtSz34N7LPlyNr2WrxYJW_3AFYtnsUoDGwhuzbxpODh_1FaPViPhhe9kU",
        "https://play-lh.googleusercontent.com/Angu55Ig_HRryVqpkPRY3ywsegxCeYmU1TOn0mTN4XV9z0_R1qpG2KduXYsWh4L1GXfA",
        "https://play-lh.googleusercontent.com/5-RweG1S2fhRpKC2Jb6idOV97cT7E4CxGL3tIzIFGulOlQR_1hdrn8nq33BJKroTfwE",
        "https://play-lh.googleusercontent.com/3IPgOAQ8ec7BbXTcHPuQRDC8_3chqe5DBNmmynFfVlQCIjhvbHsnA0DzsylBuKH8e6f9",
        "https://play-lh.googleusercontent.com/EoNnLwSuRPwDQwpXvOA1hbpmqlZmTET1CVNYvjOz-Ayob2tL7ovt3X-FKOclDOpp3w",
        "https://play-lh.googleusercontent.com/Uls3H5KqjnLcfPasaABdh0e3NEqD1i-v3NDHf4Ti4braPBNgYs7VY3i7ImqYyXmMqQ",
        "https://play-lh.googleusercontent.com/YtbW862FIE64ViHSpRSeQKRXLA2m1I8H5xzEHVszumAt787-oZp1JGIjFFVPcJKvXw",
        "https://play-lh.googleusercontent.com/Ve95Djb4sD1soFMh-_M6WJ5nQ2jtiyMDsvjpG3BiJEi_Ts-ItQ7gXVpcbgVtC9XRBNM",
        "https://play-lh.googleusercontent.com/PfWBXtsuqWTcF-4HGOdZ0LC06SVu1SBF0tpKWfUSlWoDWTqH9Ba5l-zAidVHccusrdie",
        "https://play-lh.googleusercontent.com/uX7npSjGgQ3EPzxMrZZKcQIaZqdWaUsNnV71BzyVXFw3vcMT9XL2p0rg0M8-Hdh5rQ",
        "https://play-lh.googleusercontent.com/EmkwLo24Mp-_8CLCObHRpazwl0OJcsMz8_QkmTv-5SDlN6GjKGLCYgqJQ3qzJoWPTg",
        "https://play-lh.googleusercontent.com/iJY2t5jtc5RxnqlYuckOXVpMI_IgHXFmauO8Ca_YeUc0smWtmcChDEZ6-OSk7e77ut4",
        "https://play-lh.googleusercontent.com/-MNKVpiB5jgzbdroUYLlglpdNwIti62YCHiwyTIb33L3Jn8o95XzfMm_CUvApJFX8cEF",
        "https://play-lh.googleusercontent.com/CCEjU9F0zihwkUgJPI6rPY9RMMsjFhNcWHAApv4k-17Qe1-xIjiAq-XEs5GgbWAafb20",
        "https://play-lh.googleusercontent.com/n-Ms6EV2QY22ry98APRdlw50SncuCMabbNHXs7J1V-X6zCr1j-eb1uy-dHdGxid8aA",
        "https://play-lh.googleusercontent.com/zqN_V53k2b3ezpDUJ8T5tjLcy7J92Cy-SLPSFYe7BDe3YZdwuG2BSg6O1EjnZsPUXiU",
        "https://play-lh.googleusercontent.com/d9shPTnHX8pIbT5dsvtyeNSjnlF9toq31P0Hw56TJgXIVd_j4fbfPyep0f9uQkv0V4GY",
        "https://play-lh.googleusercontent.com/PQQtgsvkTvr43nuuAamif2o_QRFO2PwZFy0xKcR3OOvR8vsOyFBA9yOc1fMpuXEOljY",
        "https://play-lh.googleusercontent.com/K2sxhmke4Magqz4Hj8RaSlwGAK5TLvCt4fiHAsi4WCGx2FH0JbF31CY4rz5OBsxpVzCD",
        "https://play-lh.googleusercontent.com/zjmAToUZsMugkW6oiblzkED4H0A4D5Enlmq2_SwgR_EJ6QtHequmw_NUVFx-94-Mf4g_",
        "https://play-lh.googleusercontent.com/193qTBzocNiZ7d2FJJkWAnuPh1fwnKVIYq7DSEJPV87sUwQvnFlmbw--xLL6bIUXmiXB",
        "https://play-lh.googleusercontent.com/WA1W5hL2NQqy0yLBFvEykfQ4BGmh-UzmQYQX64EPIBm4bOSkT_X9_jmfE7BW7LkOG_Y",
        "https://play-lh.googleusercontent.com/pERD4qvT8kgUx1RoviPuVmTNcZ_m2OBanGPRSsDgk1JSEdar8cm7dCcZhkJkxalI24M",
        "https://play-lh.googleusercontent.com/wYNmDI8wNepuFW9HFxPxBr2hsd6e04-SUUohZdaCH_L4p3Yuvh0CZujFKr2VJqOaRg",
        "https://play-lh.googleusercontent.com/wSk8UB5XC_elJXrlXPkqs0EqAkPpltDIX2lD_Uh2VOM1t9C2MIQDpCgUtzSepq2GQEM",
        "https://play-lh.googleusercontent.com/AMhSthzePN7cIOcdqS5mNQAKUNLxvitDjKkNiA0uDiVgDP3VYPQN7OsDt7rE3ZbM2D8",
        "https://play-lh.googleusercontent.com/jcXV69jwtvuAD1j3D8ZrubAakxTf6ffkoxWLFGp1NQ4oWwQqBUpGyiMmO1rLYlP-6A",
        "https://play-lh.googleusercontent.com/LAgRH2LGs_rp6gFmiZaOuZNHdWTIr67WhWwusDaB2NNwQa35d_Qenw4AdZzjxogavA",
        "https://play-lh.googleusercontent.com/tEw4H7QsmdNT1gALpehGd2SpT1snA0xCndYemgU648ToR3g1T1RVN9HJxep1SRh7C0k",
        "https://play-lh.googleusercontent.com/GGLgtgf-flWBJQRDbW7vglfAAS-nwxSyIs8PCCndcGzg3WMz9t_HnkHKeCzSp8An1iCT",
        "https://play-lh.googleusercontent.com/rqrUkeIwY4FkP8e1kkUs0HkdE0N_Mfa4J-jthAZ82IJmiusDW1vBUKTwwIAc1pWwRfOh",
        "https://play-lh.googleusercontent.com/DRGSgUMTspKvFBUtmXWgh05NBB-I_FJQLqJzEpy65xG556s4MpvPVZ7j0wYR2N7wv9M",
        "https://play-lh.googleusercontent.com/aNGbCNi6bkl188hCwy145rXuoj1nvF7T2yEQAacRvr3oevZVnnVdHMxsGXX8uxRIE60"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 16, 2016",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729512384,
    "version": "Varies with device",
    "comments": [],
    "appId": "grit.storytel.app",
    "url": "https://play.google.com/store/apps/details?id=grit.storytel.app&hl=en&gl=us"
}