{
    "title": "Human Health Tracker",
    "description": "\ud83d\udc97\u00a0Human Health: Your chronic & mental health symptom tracker & treatments Reminder\r\n\r\n\ud83d\uddd2\ufe0f\u00a0Track Symptoms, Medications & Treatments Easily \r\nHuman Health is the ultimate app for tracking symptoms, medications, & treatments to better understand how yours, or a loved one\u2019s health is changing over time. Designed with input from patients, parents, & medical experts from top US universities, Human Health helps manage everyday health concerns & complex chronic health issues, including mental health, neurological, pain, & autoimmune issues.\r\n\r\nKey Features:\r\n\ud83e\udd12 SYMPTOM TRACKER \r\nUse our symptom tracker to monitor & understand the impact of your symptoms. Add your conditions & receive symptom-tracking recommendations from our database of over 1,000 symptoms.\r\n\r\n\ud83d\udcd9 SYMPTOM TRACKER JOURNAL \r\nKeep a detailed symptom diary as you track your symptoms, so you never miss important details about your symptoms or any other health details you want to remember.\r\n\r\n\ud83d\udc8a TREATMENTS TRACKER & MEDICATIONS REMINDER \r\nLog all types of treatments & set custom medication reminders. Our database includes over 100,000 treatments from medications & supplements to lifestyle changes & devices.\r\n\r\n\ud83d\udcc8\u00a0PERSONALIZED HEALTH INSIGHTS \r\nGain insights into trends & patterns in your symptoms & treatments. Explore common symptoms , treatments & medications experienced by people similar to you.\r\n\r\n\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc66\u200d\ud83d\udc66 FOR PARENTS & CARERS \r\nCreate multiple profiles so you can track symptoms,  medications & treatments for yourself & those you care for.\r\n\r\n\ud83c\udfe5\u00a0EXPORT A PDF REPORT OF YOUR SYMPTOMS & TREATMENTS \r\nExport the information you\u2019ve collected in your symptom tracker & treatments reminder into a report to give to your medical team, so you can better advocate in your next appointment. \r\n\r\n\ud83c\udf3f\u00a0COMING SOON \r\nUpload medical records to your health timeline\r\nAdd test results, vaccinations, & surgeries.\r\n\r\n\ud83d\udd12\u00a0OUR PRIVACY PROMISE \r\n- Control who can view your data. \r\n- Data encryption & secure storage. \r\n- Your personal data will never be sold. Delete your data anytime.\r\nFor more information: https://humanhealth.zendesk.com/hc/en-us\r\nPrivacy policy: https://humanhealth.zendesk.com/hc/en-us/articles/17643897206681-Our-Privacy-Policy\r\n\r\nFor more support: support@human.health\r\n\r\nAny insights provided by Human Health do not constitute medical advice. Remember to always consult your doctor before making any medical decisions.",
    "descriptionHTML": "\ud83d\udc97\u00a0Human Health: Your chronic &amp; mental health symptom tracker &amp; treatments Reminder<br><br>\ud83d\uddd2\ufe0f\u00a0Track Symptoms, Medications &amp; Treatments Easily <br>Human Health is the ultimate app for tracking symptoms, medications, &amp; treatments to better understand how yours, or a loved one\u2019s health is changing over time. Designed with input from patients, parents, &amp; medical experts from top US universities, Human Health helps manage everyday health concerns &amp; complex chronic health issues, including mental health, neurological, pain, &amp; autoimmune issues.<br><br>Key Features:<br>\ud83e\udd12 SYMPTOM TRACKER <br>Use our symptom tracker to monitor &amp; understand the impact of your symptoms. Add your conditions &amp; receive symptom-tracking recommendations from our database of over 1,000 symptoms.<br><br>\ud83d\udcd9 SYMPTOM TRACKER JOURNAL <br>Keep a detailed symptom diary as you track your symptoms, so you never miss important details about your symptoms or any other health details you want to remember.<br><br>\ud83d\udc8a TREATMENTS TRACKER &amp; MEDICATIONS REMINDER <br>Log all types of treatments &amp; set custom medication reminders. Our database includes over 100,000 treatments from medications &amp; supplements to lifestyle changes &amp; devices.<br><br>\ud83d\udcc8\u00a0PERSONALIZED HEALTH INSIGHTS <br>Gain insights into trends &amp; patterns in your symptoms &amp; treatments. Explore common symptoms , treatments &amp; medications experienced by people similar to you.<br><br>\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc66\u200d\ud83d\udc66 FOR PARENTS &amp; CARERS <br>Create multiple profiles so you can track symptoms,  medications &amp; treatments for yourself &amp; those you care for.<br><br>\ud83c\udfe5\u00a0EXPORT A PDF REPORT OF YOUR SYMPTOMS &amp; TREATMENTS <br>Export the information you\u2019ve collected in your symptom tracker &amp; treatments reminder into a report to give to your medical team, so you can better advocate in your next appointment. <br><br>\ud83c\udf3f\u00a0COMING SOON <br>Upload medical records to your health timeline<br>Add test results, vaccinations, &amp; surgeries.<br><br>\ud83d\udd12\u00a0OUR PRIVACY PROMISE <br>- Control who can view your data. <br>- Data encryption &amp; secure storage. <br>- Your personal data will never be sold. Delete your data anytime.<br>For more information: https://humanhealth.zendesk.com/hc/en-us<br>Privacy policy: https://humanhealth.zendesk.com/hc/en-us/articles/17643897206681-Our-Privacy-Policy<br><br>For more support: support@human.health<br><br>Any insights provided by Human Health do not constitute medical advice. Remember to always consult your doctor before making any medical decisions.",
    "summary": "Chronic condition and mental health copilot, track symptoms and medications.",
    "installs": "50,000+",
    "minInstalls": 50000,
    "realInstalls": 60383,
    "score": 3.7604167,
    "ratings": 120,
    "reviews": 48,
    "histogram": [
        21,
        7,
        12,
        16,
        62
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $39.99 per item",
    "developer": "Human Operations Pty Ltd",
    "developerId": "Human+Operations+Pty+Ltd",
    "developerEmail": "support@human.health",
    "developerWebsite": "https://human.health",
    "developerAddress": "91 Reservoir St\nSurry Hills NSW 2010\nAustralia",
    "privacyPolicy": "https://humanhealth.zendesk.com/hc/en-us/articles/17643897206681-Our-Privacy-Policy",
    "genre": "Medical",
    "genreId": "MEDICAL",
    "categories": [
        {
            "name": "Medical",
            "id": "MEDICAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/DJ9MnHKIMP6CeznCZmukcOwkem82jSjXjB8BVAn8HAif1QQvuZviGhs5Buurxz5dgy8",
    "headerImage": "https://play-lh.googleusercontent.com/fOTJDcEJp1G1pGcJ3IhybjPLZ7DVHxwAq-7zyP3xVsFKrnucLJ5PyoEQJYQwSaUppg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/WpBGWE_hoBCApcIfReh5woGm8IyG2FtN0cUDJaIq1nco2XIts0EVVlRytP7b6qL5_lrB",
        "https://play-lh.googleusercontent.com/eA5w_RwCzrUfzKTfew4gKP4KueHSKsaONgzjfcq3TH0d5_6eoR_ya1LH7Es2-DRhHIM",
        "https://play-lh.googleusercontent.com/NIr939xPjIQiIcitv10V8miMwx6v31nV5VK6ENtlzOIuzJmgWgyZPTi6d1mFk1vh1A",
        "https://play-lh.googleusercontent.com/fHEqrA9WDeOP1ZrowvCsBfAZTBPS5P8bAdBPGIO71LQ-q3eo47NMp1pFw-FgGiKzaB-z",
        "https://play-lh.googleusercontent.com/nxNjxBDvNOhcRXIHkfVefamOThq2uqn_5MMVxI9d3DHL8hoqibk7oWcv4-kRcfU85w",
        "https://play-lh.googleusercontent.com/V344hsqDulYpjuqY2x6rLwfK2uukzoGd-uAkO3SILmI7UZBdZvjZiLZyFARdNZ-yTlE",
        "https://play-lh.googleusercontent.com/uMAzA_W2aZbglJDERFh8sGhOYqjtJOPcsLn3mFFmhem9_KAFqXUqLkhlDFcSo-BX6Xc",
        "https://play-lh.googleusercontent.com/rnku4lFJj_Ds4kYrdXcpb51K7g2wL019ANbUlSavKrYM-EYyirVjvMYqk-3ZdPwMbQ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Apr 20, 2023",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729048868,
    "version": "4.6.4",
    "comments": [],
    "appId": "health.human.app",
    "url": "https://play.google.com/store/apps/details?id=health.human.app&hl=en&gl=us"
}