{
    "title": "Sweatcoin\u30fbWalking Step Counter",
    "description": "Step up your fitness game with Sweatcoin!\r\n\r\nLooking for a fun way to boost your fitness & get rewarded? Sweatcoin, the viral walking app is here to transform your steps into real-world rewards! Earn Sweatcoins with every step you take and redeem them for exclusive gadgets, sports gear, and amazing experiences in our marketplace! You can even donate your sweatcoin to good cause and make a difference.\r\n\r\nThe more you walk, the more earn! And the more you earn, the more you walk! \r\n\r\n\r\nDiscover the benefits:\r\n\r\n- Effortless step tracking: Sweatcoin\u2019s pedometer runs smoothly in the background, tracking your steps accurately without draining your battery. It\u2019s your perfect fitness companion, whether you\u2019re walking, running, or working out at home.\r\n\r\n- Unlock rewards: Use your sweatcoins to access incredible offers and discounts that you won\u2019t find anywhere else. Your fitness journey has never been so rewarding!\r\n\r\n- Get moving, get badges: Hit your daily step goals and collect unique badges for each milestone achieved.\r\n\r\n- Calling all streak masters: Compete with friends to see who can maintain the longest step streak. Fitness is more fun with a little friendly competition!\r\n\r\n\r\nFeatures\r\n\r\nPrivacy first: We use a secure, proprietary algorithm to count your steps. Your location and personal data stay private\u2014only you have access to your information.\r\nPedometer: Accurate step tracking with minimal battery usage.\r\nDevice compatibility: Available on Android and iOS devices. Apple Watch users can also enjoy Sweatcoin. Android Wear compatibility is on the way!",
    "descriptionHTML": "Step up your fitness game with Sweatcoin!<br><br>Looking for a fun way to boost your fitness &amp; get rewarded? Sweatcoin, the viral walking app is here to transform your steps into real-world rewards! Earn Sweatcoins with every step you take and redeem them for exclusive gadgets, sports gear, and amazing experiences in our marketplace! You can even donate your sweatcoin to good cause and make a difference.<br><br>The more you walk, the more earn! And the more you earn, the more you walk! <br><br><br>Discover the benefits:<br><br>- Effortless step tracking: Sweatcoin\u2019s pedometer runs smoothly in the background, tracking your steps accurately without draining your battery. It\u2019s your perfect fitness companion, whether you\u2019re walking, running, or working out at home.<br><br>- Unlock rewards: Use your sweatcoins to access incredible offers and discounts that you won\u2019t find anywhere else. Your fitness journey has never been so rewarding!<br><br>- Get moving, get badges: Hit your daily step goals and collect unique badges for each milestone achieved.<br><br>- Calling all streak masters: Compete with friends to see who can maintain the longest step streak. Fitness is more fun with a little friendly competition!<br><br><br>Features<br><br>Privacy first: We use a secure, proprietary algorithm to count your steps. Your location and personal data stay private\u2014only you have access to your information.<br>Pedometer: Accurate step tracking with minimal battery usage.<br>Device compatibility: Available on Android and iOS devices. Apple Watch users can also enjoy Sweatcoin. Android Wear compatibility is on the way!",
    "summary": "Pedometer that gives you sweatcoins for steps. It pays to walk!",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 117349994,
    "score": 4.265704,
    "ratings": 2405745,
    "reviews": 60582,
    "histogram": [
        261143,
        69604,
        137463,
        238167,
        1699339
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.49 - $24.99 per item",
    "developer": "Sweatco Ltd",
    "developerId": "Sweatco+Ltd",
    "developerEmail": "support@sweatco.in",
    "developerWebsite": "https://sweatco.in",
    "developerAddress": "OHS Secretaries Limited, 9th Floor, 107 Cheapside, London, EC2V 6DN, United Kingdom",
    "privacyPolicy": "https://sweatco.in/privacy",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/ilCzgxgHDfjc89NiP2znisFCIOWi9TsDlBzzKGZNP_zynsveO1YsjDTphhdIbKWd5c5Z",
    "headerImage": "https://play-lh.googleusercontent.com/e2qX0whLz1oT5i-mtKHcNPIrjIEFFPv0paRFCCyL0DCJm4VXxaeMu_yHYrAD5960ClOE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/n7ySuJoy61T1bMpzqL-isoK5QKgtZ3zQAcpmWcAd1OWPRw7Rl5yLksW8uH5j2mXNzhDC",
        "https://play-lh.googleusercontent.com/t49O0npGQEJYEVw1eYq-u4r9U8Ew3XvVxgpLpaMdE5AaYfmOlcVZoBGM1GjfPSY8F5vb",
        "https://play-lh.googleusercontent.com/bqGJHZXoIFYzReVhZa39DihOSMHQ1MLUhxpRv0FOOh0vKNXTItwJ2EiuPxYhkmDgFgs",
        "https://play-lh.googleusercontent.com/07VuduiulWsxfr-rzQ6_v_Ms16f6njZif15JrXxg1gay3r3F6DcqVt9SdNH9txXN2A",
        "https://play-lh.googleusercontent.com/SY964OdCw8ZXNBZ8KDrZIoObLu48GYPysrWd9T1jTGp5f1kp0AIoJPJ0wjJ_Mq6U3ouT",
        "https://play-lh.googleusercontent.com/C-GNRfyt9oAJObkz8sCo_sTYVHpesQ26k73t2UmHxQqakX1W75Xp0KrO9C84kkSeAg",
        "https://play-lh.googleusercontent.com/oa-3wAzdCLCL85dRpYrfHikSQJWcVIehwHDaDCuWfda1g2CgxV6t_q_p3kNco6RaDfbv"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 9, 2017",
    "lastUpdatedOn": "Oct 18, 2024",
    "updated": 1729250674,
    "version": "184.0.0",
    "comments": [],
    "appId": "in.sweatco.app",
    "url": "https://play.google.com/store/apps/details?id=in.sweatco.app&hl=en&gl=us"
}