{
    "title": "Cheelee: watch and get money",
    "description": "Cheelee is a social network and short video platform where users get money for watching and creating video content.\r\n\r\n- Make the Most of the Feed\r\nCheelee users receive money for scrolling the feed. In other words, they literally exchange the time spent watching vids for money. The smart feed offers exciting content only. Also, all the publications are personalized for you.\r\n\r\n- Try for Free\r\nEach registered user gets free Digital glasses. With them, you can check the app\u2019s mechanics without any risks, watch videos, and get money that can be easily withdrawn from Cheelee.\r\n\r\n- Get More Money for Watching Videos\r\nGet money without extra efforts: watch vids and receive LEE coins from special boxes and for watching the feed. LEE can be converted into any convenient currency and withdrawn to a regular bank card.\r\n\r\n- How to Get Money as a Blogger\r\nCheelee is more than an app for watching short videos. This is a social network for popular and new bloggers. Here you can create viral videos without spending money on promotion. Cheelee\u2019 algorithms will help you find your audience, even if you have no followers.\r\nCheelee's global video community is constantly growing. You can join it and become a popular blogger and ambassador of the platform.\r\n\r\n- How to Start Getting money?\r\nYou can receive coins for watching the feed and from special boxes you get while watching videos.\r\n\r\nAfter purchasing Digital glasses, a user can choose a strategy:\r\n*Stability\r\n*Mix\r\n*Lucky\r\nWarning: a strategy for particular glasses can be selected once only.\r\n\r\n- Strategies\u2019 Advantages and Features\r\n*Stability enables you to receive more LEE for watching the feed. However, you will get fewer and smaller boxes.\r\nPossible profitability: x1.5 - x2.2 times more than the price of the acquired glasses.\r\n\r\n* Mix lets you receive more LEE for scrolling and slightly increases the number of boxes.\r\nPossible profitability: x1.4 - x2.6 times more than the price of the acquired glasses.\r\n\r\n* Lucky increases your chances to receive boxes with more coins. However, your revenues for watching the feed will be minimal.\r\nPossible profitability: x1.2 - x3.3 times more than the price of the acquired glasses.\r\n\r\nThe profitability of the chosen strategy is affected by:\r\n* The rarity of glasses\r\nFor example, Starting glasses are more suitable for one strategy, and Simple for another.\r\n* The level of glasses\r\nIt must be efficient, i.e. generating more income.\r\nThe \"efficient\" level is not always the highest.\r\n\r\n* Attention\r\nThis parameter determines the paid time of watching the feed. When Attention goes to 0, a user gets no coins for watching the feed. Attention is restored automatically over time.",
    "descriptionHTML": "Cheelee is a social network and short video platform where users get money for watching and creating video content.<br><br>- Make the Most of the Feed<br>Cheelee users receive money for scrolling the feed. In other words, they literally exchange the time spent watching vids for money. The smart feed offers exciting content only. Also, all the publications are personalized for you.<br><br>- Try for Free<br>Each registered user gets free Digital glasses. With them, you can check the app\u2019s mechanics without any risks, watch videos, and get money that can be easily withdrawn from Cheelee.<br><br>- Get More Money for Watching Videos<br>Get money without extra efforts: watch vids and receive LEE coins from special boxes and for watching the feed. LEE can be converted into any convenient currency and withdrawn to a regular bank card.<br><br>- How to Get Money as a Blogger<br>Cheelee is more than an app for watching short videos. This is a social network for popular and new bloggers. Here you can create viral videos without spending money on promotion. Cheelee\u2019 algorithms will help you find your audience, even if you have no followers.<br>Cheelee&#39;s global video community is constantly growing. You can join it and become a popular blogger and ambassador of the platform.<br><br>- How to Start Getting money?<br>You can receive coins for watching the feed and from special boxes you get while watching videos.<br><br>After purchasing Digital glasses, a user can choose a strategy:<br>*Stability<br>*Mix<br>*Lucky<br>Warning: a strategy for particular glasses can be selected once only.<br><br>- Strategies\u2019 Advantages and Features<br>*Stability enables you to receive more LEE for watching the feed. However, you will get fewer and smaller boxes.<br>Possible profitability: x1.5 - x2.2 times more than the price of the acquired glasses.<br><br>* Mix lets you receive more LEE for scrolling and slightly increases the number of boxes.<br>Possible profitability: x1.4 - x2.6 times more than the price of the acquired glasses.<br><br>* Lucky increases your chances to receive boxes with more coins. However, your revenues for watching the feed will be minimal.<br>Possible profitability: x1.2 - x3.3 times more than the price of the acquired glasses.<br><br>The profitability of the chosen strategy is affected by:<br>* The rarity of glasses<br>For example, Starting glasses are more suitable for one strategy, and Simple for another.<br>* The level of glasses<br>It must be efficient, i.e. generating more income.<br>The &quot;efficient&quot; level is not always the highest.<br><br>* Attention<br>This parameter determines the paid time of watching the feed. When Attention goes to 0, a user gets no coins for watching the feed. Attention is restored automatically over time.",
    "summary": "Have fun and get money for watching and creating videos.",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 7210709,
    "score": 4.539704,
    "ratings": 174100,
    "reviews": 2632,
    "histogram": [
        14758,
        1404,
        3261,
        10306,
        144321
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.99 - $204.99 per item",
    "developer": "Cheelee",
    "developerId": "Cheelee",
    "developerEmail": "support@cheelee.io",
    "developerWebsite": "https://cheelee.io",
    "developerAddress": null,
    "privacyPolicy": "https://static.cheeleepay.com/files/en_US/privacy-policy.html",
    "genre": "Social",
    "genreId": "SOCIAL",
    "categories": [
        {
            "name": "Social",
            "id": "SOCIAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/KJUfjKwHYmW5XpKv48Ig9t25SecpjJE4lqrgljB-2VzmP7OJTN5rka72OPXggALeG7Q",
    "headerImage": "https://play-lh.googleusercontent.com/JItDbEXaOkLuN-TXUeivuE0gxVpQ8jA2-l-91dC2az1ofBKr8V-hvF2z1iSJ4_3yC1nK",
    "screenshots": [
        "https://play-lh.googleusercontent.com/pjY1engay3PenOy-ybSODLaQskfPOiu18z4R52_fB9DH-qeIcSP0G9PI9CjmQrf9n_Q",
        "https://play-lh.googleusercontent.com/4aYTe5PYhZ5OWgcPHZE6KGh2dx41YzLhB2odoOVfcnhWg0DaqrMBlFWpT0XWH2QMO_FO",
        "https://play-lh.googleusercontent.com/NlDy-RtaoEsSTpRFmu20eudXUTsZcYhWc_VetY2SsVVhsWLK6vE8f4cY1Y0_SFtQv0zn",
        "https://play-lh.googleusercontent.com/xQv5zlGkCwnotUau59mqSJvnY5kN16cXx4NOfqQD2rTcjAhWpN9kt3aBHaKuRNNi_pU",
        "https://play-lh.googleusercontent.com/yQGa6Vz4oQtLhZVogw2W3VbDzbXePnjAeUM32gWu1SAMU346y2POiSstnu_xyrm9zw",
        "https://play-lh.googleusercontent.com/RSK6Ik12n0QxWy0qUPr3f6i3Pk4nvBp-VhN7W-sbuLoTqFX596YJ8BWBWV4X7AS8rKg",
        "https://play-lh.googleusercontent.com/abIyLlfHArNjU0QjVzE6zfZ5KntZLkQQtKxR08FHeOVbDi54u0NfALBCcZov9RghmWE",
        "https://play-lh.googleusercontent.com/T5_Q64lU9OEwEgwb7O_w3JXlhB8GXDiOhf194SFFBmhwMQaEDoDAp5DdJfuYElI0htgj",
        "https://play-lh.googleusercontent.com/-JXMyumv-8DPY7s7K_lpBneUefG9OUVmjMmxSxn1kYprzb4Ez998iJcS8btFyselo_k",
        "https://play-lh.googleusercontent.com/p0fHc4KRk9QrHsKGzkotHIZzm2wFa8gHWMsiY19Vy9xTlc6JuaTaV6l85exNKHJzB8g",
        "https://play-lh.googleusercontent.com/TSC1dtyASHcU2m91uR9xM46KTodS1AA_K1qNFL8zBnKj4c-KWIcu_U0voZ9sxGVRZ8Br",
        "https://play-lh.googleusercontent.com/SUFWaGrvREQPf5mz39ItO4SWPJlDHeoMd3h4R7SerG1oE5TBEeNRtipkGijEypfnR0VQ",
        "https://play-lh.googleusercontent.com/cFz0V9l4fBbGc7klsBtUTOLItZxuQBDE3HKOD_XHHVPoDBSchUQ2Wfxdb2BRIP0OYhg",
        "https://play-lh.googleusercontent.com/WPeqH1lsgvtVKO4JrKQuFWXuWQcSgxtjBI639_eoOE0hq9X7FmcICeImxK3vvNzovwM",
        "https://play-lh.googleusercontent.com/_R4Xr0JEoQQMFkLUiXEnw4Q-IcTmIRjE_CnCyZ1AllPkruj--sH_tAY5ToaCYqBvybA"
    ],
    "video": "https://www.youtube.com/embed/DOhhrPZAll8?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/JItDbEXaOkLuN-TXUeivuE0gxVpQ8jA2-l-91dC2az1ofBKr8V-hvF2z1iSJ4_3yC1nK",
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 20, 2023",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728973505,
    "version": "1.46.0",
    "comments": [],
    "appId": "io.cheelee.app",
    "url": "https://play.google.com/store/apps/details?id=io.cheelee.app&hl=en&gl=us"
}