{
    "title": "Readsy: Books and Stories",
    "description": "Readsy: the best place to read romance novels! Dive into a world of captivating stories and unforgettable characters with Readsy, the premier app for reading books. Whether you're a fan of passionate billionaire romance books or thrilling werewolf romance novels, Readsy offers a vast selection that caters to every taste. Our app is designed to provide an unparalleled reading experience, making it easier than ever to immerse yourself in the genres you love.\r\n\r\nWith Readsy, you can explore an extensive library of romance novels, including billionaire romance stories that will sweep you off your feet, and werewolf romance stories that will keep you on the edge of your seat. From heartwarming LGBTQ+ tales to enchanting fantasy and paranormal love stories, Readsy has something for everyone. Our collection is carefully curated to ensure that you always have access to the best and most popular books available.\r\n\r\nOne of the standout features of Readsy is our unlimited access subscription. By purchasing a subscription, you can read novels without any restrictions, unlocking a treasure trove of stories at your fingertips. No more worrying about running out of books to read or waiting for new releases \u2013 with Readsy, you can indulge in your passion for reading as much as you like.\r\n\r\n- Hundreds of books available with one subscription\r\n- Bestsellers loved by thousands of readers\r\n- Novels of various genres: billionaire/ceo, werewolf, romance, paranormal, fantasy, lgbtq+\r\n- Collections tab where you can find your next great read\r\n- Library with your saved favourite books\r\n\r\nAre you a fan of billionaire romance novels? Readsy has you covered with a wide range of titles that delve into the glamorous and often tumultuous lives of the wealthy and powerful. These stories are filled with intrigue, passion, and drama, offering a thrilling escape from the everyday.\r\n\r\nIf werewolf romance books are more your style, you'll be thrilled with our selection of werewolf romance novels. These stories combine the allure of romance with the excitement of the supernatural, creating a unique reading experience that is both thrilling and heartwarming. Follow the adventures of werewolves and their destined mates as they navigate love, danger, and the unknown.\r\n\r\nAt Readsy, we believe that everyone should have access to great stories. That's why our app is designed to be user-friendly and accessible, allowing you to easily browse, discover, and read books. Whether you're looking for a quick escape during your lunch break or a long read to unwind at the end of the day, Readsy is the perfect companion.\r\n\r\nJoin the Readsy community today and unlock a world of romance novels. Your next great read is just a tap away!",
    "descriptionHTML": "Readsy: the best place to read romance novels! Dive into a world of captivating stories and unforgettable characters with Readsy, the premier app for reading books. Whether you&#39;re a fan of passionate billionaire romance books or thrilling werewolf romance novels, Readsy offers a vast selection that caters to every taste. Our app is designed to provide an unparalleled reading experience, making it easier than ever to immerse yourself in the genres you love.<br><br>With Readsy, you can explore an extensive library of romance novels, including billionaire romance stories that will sweep you off your feet, and werewolf romance stories that will keep you on the edge of your seat. From heartwarming LGBTQ+ tales to enchanting fantasy and paranormal love stories, Readsy has something for everyone. Our collection is carefully curated to ensure that you always have access to the best and most popular books available.<br><br>One of the standout features of Readsy is our unlimited access subscription. By purchasing a subscription, you can read novels without any restrictions, unlocking a treasure trove of stories at your fingertips. No more worrying about running out of books to read or waiting for new releases \u2013 with Readsy, you can indulge in your passion for reading as much as you like.<br><br>- Hundreds of books available with one subscription<br>- Bestsellers loved by thousands of readers<br>- Novels of various genres: billionaire/ceo, werewolf, romance, paranormal, fantasy, lgbtq+<br>- Collections tab where you can find your next great read<br>- Library with your saved favourite books<br><br>Are you a fan of billionaire romance novels? Readsy has you covered with a wide range of titles that delve into the glamorous and often tumultuous lives of the wealthy and powerful. These stories are filled with intrigue, passion, and drama, offering a thrilling escape from the everyday.<br><br>If werewolf romance books are more your style, you&#39;ll be thrilled with our selection of werewolf romance novels. These stories combine the allure of romance with the excitement of the supernatural, creating a unique reading experience that is both thrilling and heartwarming. Follow the adventures of werewolves and their destined mates as they navigate love, danger, and the unknown.<br><br>At Readsy, we believe that everyone should have access to great stories. That&#39;s why our app is designed to be user-friendly and accessible, allowing you to easily browse, discover, and read books. Whether you&#39;re looking for a quick escape during your lunch break or a long read to unwind at the end of the day, Readsy is the perfect companion.<br><br>Join the Readsy community today and unlock a world of romance novels. Your next great read is just a tap away!",
    "summary": "Romance eBooks & novels",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 21488,
    "score": 4.4851484,
    "ratings": 216,
    "reviews": 20,
    "histogram": [
        14,
        8,
        5,
        11,
        173
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$6.99 - $89.99 per item",
    "developer": "Brailion Ventures Limited",
    "developerId": "6318965543037426361",
    "developerEmail": "support@readsy.io",
    "developerWebsite": "https://readsy.io/",
    "developerAddress": "Spyrou Kyprianou, 79, Protopapas bldg, 2nd floor, Flat/Office 201, Limassol, 3076, Cyprus",
    "privacyPolicy": "https://readsy.io/privacy-policy",
    "genre": "Books & Reference",
    "genreId": "BOOKS_AND_REFERENCE",
    "categories": [
        {
            "name": "Books & Reference",
            "id": "BOOKS_AND_REFERENCE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/5KNG7Vq-2Xq61Qxrm0-8YKUjcSqZWgISIi2km9HO3BwotXco5nbdvNENLvchhvSGYmw",
    "headerImage": "https://play-lh.googleusercontent.com/z-k4V2BbkIjSho8cjD9OMXwYdZvdyuFhONTEMWvMf4m0F4SoSKbOBRja2XPmuFgXUuA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/7z0n5OfVO5tqA4GVBmI8wHBlZSLlx6VoroiPAbUgRfhvoD4MEtilr7Vd9GXIOb5T4_Iq",
        "https://play-lh.googleusercontent.com/-i1G1RDUjiLuXUmINsoK-EVF4LN8G8--FRuse2fTiUN_yuAnydBatgY5bSjN8M039scg",
        "https://play-lh.googleusercontent.com/TeU3YxyT59KjLgStEhCQiq2B4P8snv1rvorILgZOfea3pUP_tdAUcOfjyBMgP13VYg",
        "https://play-lh.googleusercontent.com/HX5AglTWiQcviepQOqbGwbOlgzNuyCxnMOBU_TCxRe6oUnukRAnm_6Xsx-VgERmYHCUu",
        "https://play-lh.googleusercontent.com/K_HSuOI47_ssuOWcJ1_R6DKk2kILXf9as16pG7yzYahDJPCugEPRa9sl6GCYNfbSMlA",
        "https://play-lh.googleusercontent.com/3vOD6xp_8A_hMf9GhIgzJwBNyteVLnzoDJhe4gZz_kDU91y12nYU2UixGooM859zDYJq",
        "https://play-lh.googleusercontent.com/bKTAdsBW-2g9rY8p_qiVSIJCg0ClcqPas2mPoJZwAkpLck0PjqZpGv-kyw6DOVH0zbs",
        "https://play-lh.googleusercontent.com/NiKob1rmhmfffx9VghGeB3ujf85pGLxgheWhNOdjvGmU4N-vVUFUbpEqRaqRzHLoj2FK",
        "https://play-lh.googleusercontent.com/lFfI_1Dw7RRFY9hxQR9HQZ2RLvGhYSqW_cngN5VXOyC3_VXAQZ3zUkUfoAPU4Az4nwc",
        "https://play-lh.googleusercontent.com/8kvdA6fMaA2ZNUtTA09BcMoKIlAkjLGFo-OdqY57uTSM6KjI6GpgVFYWUZgtccAwiBdf"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Sexual Themes, Partial Nudity, Strong Language",
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 29, 2024",
    "lastUpdatedOn": "Sep 30, 2024",
    "updated": 1727706541,
    "version": "1.3.0",
    "comments": [],
    "appId": "io.readsy.app",
    "url": "https://play.google.com/store/apps/details?id=io.readsy.app&hl=en&gl=us"
}