{
    "title": "ibis Paint X",
    "description": "ibis Paint X is a popular and versatile drawing app downloaded more than 400 million times in total as a series, which provides over 47000 brushes, over 21000 materials, over 2100 fonts, 84 filters, 46 screentones, 27 blending modes, recording drawing processes, stroke stabilization feature, various ruler features such as radial line rulers or symmetry rulers, and clipping mask features.\r\n\r\n*YouTube channel\r\nMany tutorial videos on ibis Paint are uploaded to our YouTube channel.\r\nSubscribe it!\r\nhttps://youtube.com/ibisPaint\r\n\r\n*Concept/Features\r\n- A Highly functional and professional features surpassing that of desktop drawing apps.\r\n- Smooth and comfortable drawing experience realized by OpenGL technology.\r\n- Recording your drawing process as a video.\r\n- SNS feature where you can learn drawing techniques from other users' drawing process videos.\r\n\r\n*Features\r\nibis Paint has high functionality as a drawing app along with features of sharing drawing processes with other users.\r\n\r\n[Brush Features]\r\n- Smooth drawing at up to 60 fps.\r\n- Over 47000 kinds of brushes including dip pens, felt tip pens, digital pens, air brushes, fan brushes, flat brushes, pencils, oil brushes, charcoal brushes, crayons and stamps.\r\n\r\n[Layer Features]\r\n- You can add layers as many as you need with no limit.\r\n- Layer parameters that can be set to each layers individually such as layer opacity, alpha blending, adding, subtracting, and multiplying.\r\n- A handy clipping feature for clipping images, etc.\r\n- Various layer commands such as layer duplication, import from the photo library, horizontal inversion, vertical inversion, layer rotation, layer moving, and zooming in/out.\r\n- A feature for setting layer names to distinguish different layers.\r\n\r\n*About ibis Paint purchase plan\r\nThe following purchase plans are available for ibis Paint:\r\n- ibis Paint X (free version)\r\n- ibis Paint (paid version)\r\n- Remove Ads Add-on\r\n- Prime Membership (Monthly plan / Yearly plan)\r\nThere is no difference in features other than the presence or absence of advertisements for the paid version and the free version.\r\nIf you purchase the Remove Ads Add-on, the ads will not be displayed and there will be no difference from the paid version of ibis Paint.\r\nIn order to use more advanced functions, the following Prime Membership (Monthly plan / Yearly plan) contracts are required.\r\n\r\n[Prime Membership]\r\nA prime member can use the prime features. Only for the initial time you can use the 7 days or the 30 days free trial. If you become a Prime Membership, you can use the following features and services.\r\n- 20GB of Cloud Storage capacity\r\n- No advertisements\r\n- Hiding Watermarks on the Video\r\n- Unlimited use of Vector tool(*1)\r\n- Moving and scaling on Vector Layers\r\n- Prime Filters\r\n- Prime Adjustment Layer\r\n- Reordering artworks in My Gallery\r\n- Customizing background color of Canvas screen\r\n- Creating Animation works of any size\r\n- Prime materials\r\n- Prime fonts\r\n- Prime Canvas papers\r\n(*1) You can try it for free for up to 1 hour per day.\r\n* After you become a Prime Membership with a free trial, renewal fee will be charged automatically unless you cancel your Prime Membership at least 24 hours before the end of the free trial period.\r\n* We will add premium features in future, please look out for them.\r\n\r\n*On Data Collection\r\n- Only when you are using or going to use SonarPen, the app collects audio signal from microphone. The collected data is only used for communication with SonarPen, and is never saved nor sent to anywhere.\r\n\r\n*Questions and support\r\nQuestions and bug reports in reviews will not be responded to, so please contact ibis Paint support.\r\nhttps://ssl.ibis.ne.jp/en/support/Entry?svid=25\r\n\r\n*ibisPaint's terms of service\r\nhttps://ibispaint.com/agreement.jsp",
    "descriptionHTML": "ibis Paint X is a popular and versatile drawing app downloaded more than 400 million times in total as a series, which provides over 47000 brushes, over 21000 materials, over 2100 fonts, 84 filters, 46 screentones, 27 blending modes, recording drawing processes, stroke stabilization feature, various ruler features such as radial line rulers or symmetry rulers, and clipping mask features.<br><br>*YouTube channel<br>Many tutorial videos on ibis Paint are uploaded to our YouTube channel.<br>Subscribe it!<br>https://youtube.com/ibisPaint<br><br>*Concept/Features<br>- A Highly functional and professional features surpassing that of desktop drawing apps.<br>- Smooth and comfortable drawing experience realized by OpenGL technology.<br>- Recording your drawing process as a video.<br>- SNS feature where you can learn drawing techniques from other users&#39; drawing process videos.<br><br>*Features<br>ibis Paint has high functionality as a drawing app along with features of sharing drawing processes with other users.<br><br>[Brush Features]<br>- Smooth drawing at up to 60 fps.<br>- Over 47000 kinds of brushes including dip pens, felt tip pens, digital pens, air brushes, fan brushes, flat brushes, pencils, oil brushes, charcoal brushes, crayons and stamps.<br><br>[Layer Features]<br>- You can add layers as many as you need with no limit.<br>- Layer parameters that can be set to each layers individually such as layer opacity, alpha blending, adding, subtracting, and multiplying.<br>- A handy clipping feature for clipping images, etc.<br>- Various layer commands such as layer duplication, import from the photo library, horizontal inversion, vertical inversion, layer rotation, layer moving, and zooming in/out.<br>- A feature for setting layer names to distinguish different layers.<br><br>*About ibis Paint purchase plan<br>The following purchase plans are available for ibis Paint:<br>- ibis Paint X (free version)<br>- ibis Paint (paid version)<br>- Remove Ads Add-on<br>- Prime Membership (Monthly plan / Yearly plan)<br>There is no difference in features other than the presence or absence of advertisements for the paid version and the free version.<br>If you purchase the Remove Ads Add-on, the ads will not be displayed and there will be no difference from the paid version of ibis Paint.<br>In order to use more advanced functions, the following Prime Membership (Monthly plan / Yearly plan) contracts are required.<br><br>[Prime Membership]<br>A prime member can use the prime features. Only for the initial time you can use the 7 days or the 30 days free trial. If you become a Prime Membership, you can use the following features and services.<br>- 20GB of Cloud Storage capacity<br>- No advertisements<br>- Hiding Watermarks on the Video<br>- Unlimited use of Vector tool(*1)<br>- Moving and scaling on Vector Layers<br>- Prime Filters<br>- Prime Adjustment Layer<br>- Reordering artworks in My Gallery<br>- Customizing background color of Canvas screen<br>- Creating Animation works of any size<br>- Prime materials<br>- Prime fonts<br>- Prime Canvas papers<br>(*1) You can try it for free for up to 1 hour per day.<br>* After you become a Prime Membership with a free trial, renewal fee will be charged automatically unless you cancel your Prime Membership at least 24 hours before the end of the free trial period.<br>* We will add premium features in future, please look out for them.<br><br>*On Data Collection<br>- Only when you are using or going to use SonarPen, the app collects audio signal from microphone. The collected data is only used for communication with SonarPen, and is never saved nor sent to anywhere.<br><br>*Questions and support<br>Questions and bug reports in reviews will not be responded to, so please contact ibis Paint support.<br>https://ssl.ibis.ne.jp/en/support/Entry?svid=25<br><br>*ibisPaint&#39;s terms of service<br>https://ibispaint.com/agreement.jsp",
    "summary": "Share the joy of painting with ibis Paint X! Drawing anime and manga art.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 244811707,
    "score": 4.3994493,
    "ratings": 2604578,
    "reviews": 115180,
    "histogram": [
        190420,
        73571,
        116219,
        349313,
        1875028
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.99 - $27.99 per item",
    "developer": "ibis inc.",
    "developerId": "ibis+inc.",
    "developerEmail": "mob-paint-support@ibis.ne.jp",
    "developerWebsite": "https://ibispaint.com/",
    "developerAddress": "Nakamo bldg.4F 3-17-34 Meieki, Nakamura-ku, Nagoya, Aichi 450-0002, Japan\n\u3012450 \u2013 0002 \u540d\u53e4\u5c4b\u5e02\u4e2d\u6751\u533a\u540d\u99c53\u4e01\u76ee17\u756a34\u53f7\u3000\u30ca\u30ab\u30e2\u30d3\u30eb4\u968e",
    "privacyPolicy": "https://ibispaint.com/privacy.jsp#policy",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/QcfhlXm32JDnj3WM2-TSL78ad99x4slovX4OzCSLSPU3uRN-mGXpKyM_yeXiewhz0Lk",
    "headerImage": "https://play-lh.googleusercontent.com/o76kpGp3zD9Q1-fFR6TTf6Q63fzzKY5R49uin2Y1zD8WRSrqeBuir6-oJxNcaTLZCQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/_G5O-PWaKtmnMCy0ZV0f7gCp2fVyAHtPZv58V65UdajHZax156T_iOeJS1OngWROCkXo",
        "https://play-lh.googleusercontent.com/4sy_7NHiehZh7itoeLm5D5KdQRlwVpBF-Fav5scPySucCY6qcLiK8OuNbGjQt9TKMfwT",
        "https://play-lh.googleusercontent.com/_YKDx6n7ptSO2hWKlxpX7SA3WB4DjVj39KjSt-LNPMA8WWTR-QIed8z2B_o_JFKuVcvE",
        "https://play-lh.googleusercontent.com/ky9PXYrcrujy6BNNv9m1I1qkJ46Y564kB83vyxCcipb_HDs0pk839TklWu1JzgEXvKh4",
        "https://play-lh.googleusercontent.com/62iFI3RsC4-Y-qVEtvJEO-jRm1lhHnzYUW1BQNvKaMcHMOuWni4lmphUsXq2dhMFRs84",
        "https://play-lh.googleusercontent.com/yyDdTR6o3qRxN8hXP1axBSn4lJyDomfXUlmJPYW3CvbmSp7jgHrwXwz4LRGykTZleA",
        "https://play-lh.googleusercontent.com/OSh21fIjL4DhUQJuFI3AHTQS05LBMYJ08YfkdrlbtIEOo2P-cj3N4x6DSQ-fyZGgnzI",
        "https://play-lh.googleusercontent.com/v3Qz321Yza3dugWqWJkM20bz8zm_awct8V37pc7FB-8dHo0Bb4pzVNTOG0kbIgK0ag",
        "https://play-lh.googleusercontent.com/cEfn-FBmgUgEp8pG3N27nwZdjLAARg-D9V-6wokJDNhWvGXItlmDO2FocTLDkLrhcw",
        "https://play-lh.googleusercontent.com/wqThXBr0dENpPbfIVy_xtn9oExQo0azoxysCijcEzMpkeeoBt7t1145oslR92W-XGQ",
        "https://play-lh.googleusercontent.com/aDWiUlIAxjh0doIlTGtU40UJD0CxAbk-tKd-58BNRbr9jbo7irylM6ULzZq9L8zli88",
        "https://play-lh.googleusercontent.com/SFpjtmCSHBadQg-k1vPhJiRzd7gGU5jOBGSOI0lIei7XdHxl8bYrBn8bMlV9BbGDX2Q",
        "https://play-lh.googleusercontent.com/xfHuD4ugOMH9nrdrr4FpzkYzLLklzaKiRTfWFpHvP10Os8p20a-esEPhKuJ7AeIhMFZl",
        "https://play-lh.googleusercontent.com/WauJQchcNhTEeGL1SzAhBtQDbvT4ttWaeqzDZYqZleIrmA5Pf1h0-iXQeuxstt_rMw",
        "https://play-lh.googleusercontent.com/106A7miAFrnOiCv9EoQ5GKcnIHjUpqOJeHBlGFTcoOx4IEPJP91hnyFSgsLZh3jRuIA",
        "https://play-lh.googleusercontent.com/WL8DEtU0gEu08SQw7cVbTyFaTtgdUCNydkKQ7cieLRJ-RFcB3z39aERMoKfhKdXpYiwn",
        "https://play-lh.googleusercontent.com/5FKuCWugCpATl9if8dQB53YOBhku3MXQvpwt1OdYogUxhfe_KpKrl9Z0lpIyuxL2oAk",
        "https://play-lh.googleusercontent.com/yR88zA0Xrdra-hG8mgR4cj-wtkFXurCaoMsv55NTN1D_wV3TYUDVTUcgiIIwB9boTQKE"
    ],
    "video": "https://www.youtube.com/embed/8IMaUlV39sA?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/o76kpGp3zD9Q1-fFR6TTf6Q63fzzKY5R49uin2Y1zD8WRSrqeBuir6-oJxNcaTLZCQ",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 27, 2014",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729499048,
    "version": "12.2.7",
    "comments": [],
    "appId": "jp.ne.ibis.ibispaintx.app",
    "url": "https://play.google.com/store/apps/details?id=jp.ne.ibis.ibispaintx.app&hl=en&gl=us"
}