{
    "title": "Pool League",
    "description": "The official app of the American Poolplayers Association (APA) and Canadian Poolplayers Association (CPA) Pool Leagues, the World's Largest Pool League!\r\n\r\nMembers of our Pool League can use this app to enjoy:\r\n\r\n- See theirs and other player's personal and team stats\r\n- Personal match schedule to see when you need to play next\r\n- Add your schedule to your device's calendar\r\n- See your next matchup details and directions to the host location\r\n- See division standings, schedules, and rosters\r\n- Download the scoresheets for their matches\r\n- News and Events from your local League\r\n- Manage their contact information\r\n- Notifications to help you have the best League experience\r\n- Easily pay for your weekly team fees (not available in all League areas)\r\n- Download the rules to your device\r\n\r\nUPDATED: Your membership, team, and tournament history is now available for you. Search results now have Host location pages in the results.",
    "descriptionHTML": "The official app of the American Poolplayers Association (APA) and Canadian Poolplayers Association (CPA) Pool Leagues, the World&#39;s Largest Pool League!<br><br>Members of our Pool League can use this app to enjoy:<br><br>- See theirs and other player&#39;s personal and team stats<br>- Personal match schedule to see when you need to play next<br>- Add your schedule to your device&#39;s calendar<br>- See your next matchup details and directions to the host location<br>- See division standings, schedules, and rosters<br>- Download the scoresheets for their matches<br>- News and Events from your local League<br>- Manage their contact information<br>- Notifications to help you have the best League experience<br>- Easily pay for your weekly team fees (not available in all League areas)<br>- Download the rules to your device<br><br>UPDATED: Your membership, team, and tournament history is now available for you. Search results now have Host location pages in the results.",
    "summary": "The official app of the APA and CPA Pool Leagues.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 255873,
    "score": 4.5121484,
    "ratings": 15905,
    "reviews": 5060,
    "histogram": [
        660,
        233,
        812,
        2785,
        11409
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "American Poolplayers Assoc",
    "developerId": "American+Poolplayers+Assoc",
    "developerEmail": "feedback-3453-RbMBJAmMNNyCTrOXVoshinKJl5Mp4q4S@feedback.doorbell.io",
    "developerWebsite": "https://poolplayers.com/contact/",
    "developerAddress": null,
    "privacyPolicy": "http://poolplayers.com/legal/privacy-policy/",
    "genre": "Sports",
    "genreId": "SPORTS",
    "categories": [
        {
            "name": "Sports",
            "id": "SPORTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/9-7paB--foNTySMGLKW3finkT2FxcIKLMIS2KE8gbOWX_nglVJyXHZ-EPRJ4nSKAGso",
    "headerImage": "https://play-lh.googleusercontent.com/U8d7vCxc7TGVTExlkU2BL4ub_56-fA5pBXM9K2c4Uo0yCKRUdiOG99VJSumYGXy0ew8",
    "screenshots": [
        "https://play-lh.googleusercontent.com/rIHRXOaD7QMBHXdWCAWymrOcTYAUqIGMfg2uJzNnNif-CTLCWfoftBl-Y2ghzOiojg",
        "https://play-lh.googleusercontent.com/BinuZN6UN1ZAbcigurQEpwbbY0HzboEOtporhTkdFh3OPcKdfcQF-fVMQmMbYo_sEA",
        "https://play-lh.googleusercontent.com/zx0nc_AeyHqbt6dWd61VkCHv5LIn1OxQrfDf6XK92A-RNejPhaATFzM4p0vpy9-0yEI",
        "https://play-lh.googleusercontent.com/zJTCpNKbORAZHZDt8m3T1oe0TLkbO1zukF8_sSr-tcBN9jeYFPYGKmAwx47YaunakUQ",
        "https://play-lh.googleusercontent.com/tdf6rFpdPcMN0FVTkftJ0O4NCVWUvNxSdarZzebwwFrXg0POHRMnV73HV5Jh1Jefmp4",
        "https://play-lh.googleusercontent.com/aB8dsHca5q8CGOtBZBwmTrTEc5YRvG6kJi1rHjKVaWwYPM2R3V2XhGuNOtS4w6pgCf8",
        "https://play-lh.googleusercontent.com/FsDOOmOuw2vvrDHyBgWIf-k9CXRNCntufZpQvVCwQ-yqYqh27QlTfd4N7lcukd07jA",
        "https://play-lh.googleusercontent.com/i2VVfzWnz2Oyqe6f9ltAKP3vZrqqKGF15by3cEZMF1TkXB0LDBF4ILCybUodRALDfwE",
        "https://play-lh.googleusercontent.com/-zfUgMj3D7l3QKBCM515xgXTJWQ_COWotbjpidJ8nrZVP0Cuz5I9N0CEOHcdCeI274k",
        "https://play-lh.googleusercontent.com/ZFN5F_ya_8yqTKWmTuMKxzl93qzRHAlEUPbHzAV-0GES08DBmxZJL7QHXPI1aKzA_5oV",
        "https://play-lh.googleusercontent.com/T_nfVRiEWhWBbDtShkrnluRwgX3xaBSisfBGuSEHkdOb8mPrny-TDprl_uPkcn8Uot94",
        "https://play-lh.googleusercontent.com/IMfLf89V3ORHlw1R8J7nW_7AbpPMPRHmrkERhICyOOhHc7dZDQtJtVYd5fbxF-gCW68",
        "https://play-lh.googleusercontent.com/ugeRoAWxoL5seSuv2GJNf3CjIeveov0X668SeHd3W7egMwkvnjiQC5eeXU_z4-n78bw"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 25, 2017",
    "lastUpdatedOn": "Sep 20, 2024",
    "updated": 1726849417,
    "version": "3.18.29",
    "comments": [],
    "appId": "league.poolplayers.com",
    "url": "https://play.google.com/store/apps/details?id=league.poolplayers.com&hl=en&gl=us"
}