{
    "title": "Crochet row counter & patterns",
    "description": "\ud83e\uddf6 Simple crochet app with row counter. PDF upload and stuffed amigurumi animals.\r\n\r\nPreview and store PDF files, count rows, track progress, upload patterns from other apps or marketplaces like Etsy, ravelry app, etc. Use row counters with + and -, check timer and track your progress on DIY handcrafts\r\n\r\n\ud83d\udcf1 Items crafted specially for mobile view\r\n\r\nLowers the bar on users who can craft projects. We find best amigurumi patterns to make crafts with the best crocheters.\r\n\r\n\u2705 Stash manager & shopping list\r\n\r\nGathered best yarn collections from best manufacturers: YarnArt, Drops, Alize, Schachenmayr, DMC, etc.\r\n\r\nAllows to control stock of items for crocheting, yarn stash, crochet hooks and other tools. Helps creators to make sure stash and yarns are always full and ready.\r\n\r\n\u2601\ufe0f New standards for easy crochet life\r\n\r\nPDF\u2019s that are currently published by creators are not optimised for mobile devices. Our new format expands the possibilities for crocheters on what they can create. Easy crafts and amigurumi, clothes and accessories, master classes that are bought from other stores, like etsy. Shopping list & uploaded PDFs and stitches counter are synchronised with cloud and will be present on the account with premium features.\r\n\r\nFeatures & Tools:\r\n\r\n- Project preview & easy steps to follow\r\n- Row counter\r\n- Crafting shopping list\r\n- Rows, project & part timer\r\n- Modern amigurumi recipes\r\n- Project completion time planner\r\n- Basic Crochet & knitting tutorials\r\n- Hook size chart\r\n- Knitting needles size charts\r\n- Completed projects\r\n- Yarn and tools shopping list\r\n- PDF import & notes\r\n- Free multiple row counter\r\n- Yarn marketplace\r\n\r\n\ud83c\udd93 Easy to get pattern\r\n\r\nGuarantee of a premium purchase, refund and quality assurance from the Crochetapp. There are more than 15 free crochet & knitting projects in the app already available, for the apps craft.\r\n\r\n\ud83d\udd04 PDF Instructions in cloud\r\n\r\nMany instructions are stored in different places, devices and ways. With our solution you can keep everything in one mobile application from any sources and creators, it allows to keep instructions forever.\r\n\r\n\ud83d\ude4bSingle format for crafted projects\r\n\r\nEvery creator has their own style and format of crafted toys or items, product is built to give the best possible experience and format for the end user. It is a completely new approach to visual information, abbreviations and style of description. Explanations, tips and instructions available, as well as needed materials and knowledge database.",
    "descriptionHTML": "\ud83e\uddf6 Simple crochet app with row counter. PDF upload and stuffed amigurumi animals.<br><br>Preview and store PDF files, count rows, track progress, upload patterns from other apps or marketplaces like Etsy, ravelry app, etc. Use row counters with + and -, check timer and track your progress on DIY handcrafts<br><br>\ud83d\udcf1 Items crafted specially for mobile view<br><br>Lowers the bar on users who can craft projects. We find best amigurumi patterns to make crafts with the best crocheters.<br><br>\u2705 Stash manager &amp; shopping list<br><br>Gathered best yarn collections from best manufacturers: YarnArt, Drops, Alize, Schachenmayr, DMC, etc.<br><br>Allows to control stock of items for crocheting, yarn stash, crochet hooks and other tools. Helps creators to make sure stash and yarns are always full and ready.<br><br>\u2601\ufe0f New standards for easy crochet life<br><br>PDF\u2019s that are currently published by creators are not optimised for mobile devices. Our new format expands the possibilities for crocheters on what they can create. Easy crafts and amigurumi, clothes and accessories, master classes that are bought from other stores, like etsy. Shopping list &amp; uploaded PDFs and stitches counter are synchronised with cloud and will be present on the account with premium features.<br><br>Features &amp; Tools:<br><br>- Project preview &amp; easy steps to follow<br>- Row counter<br>- Crafting shopping list<br>- Rows, project &amp; part timer<br>- Modern amigurumi recipes<br>- Project completion time planner<br>- Basic Crochet &amp; knitting tutorials<br>- Hook size chart<br>- Knitting needles size charts<br>- Completed projects<br>- Yarn and tools shopping list<br>- PDF import &amp; notes<br>- Free multiple row counter<br>- Yarn marketplace<br><br>\ud83c\udd93 Easy to get pattern<br><br>Guarantee of a premium purchase, refund and quality assurance from the Crochetapp. There are more than 15 free crochet &amp; knitting projects in the app already available, for the apps craft.<br><br>\ud83d\udd04 PDF Instructions in cloud<br><br>Many instructions are stored in different places, devices and ways. With our solution you can keep everything in one mobile application from any sources and creators, it allows to keep instructions forever.<br><br>\ud83d\ude4bSingle format for crafted projects<br><br>Every creator has their own style and format of crafted toys or items, product is built to give the best possible experience and format for the end user. It is a completely new approach to visual information, abbreviations and style of description. Explanations, tips and instructions available, as well as needed materials and knowledge database.",
    "summary": "Crochet row counter, knitting patterns. Easy yarn stash manager, pdf notes, list",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 300393,
    "score": 4.5,
    "ratings": 1957,
    "reviews": 72,
    "histogram": [
        116,
        0,
        56,
        387,
        1387
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.49 - $29.99 per item",
    "developer": "Crochet App - row counter, easy PDFs and patterns",
    "developerId": "Crochet+App+-+row+counter,+easy+PDFs+and+patterns",
    "developerEmail": "newcrochetapp@gmail.com",
    "developerWebsite": "https://crochetapp.web.app",
    "developerAddress": null,
    "privacyPolicy": "https://docs.google.com/document/d/1Mdur0FAqc6bwBo3m3pmJelQ_8TCxqoMc0Wgy5D-4y4s/edit",
    "genre": "Art & Design",
    "genreId": "ART_AND_DESIGN",
    "categories": [
        {
            "name": "Art & Design",
            "id": "ART_AND_DESIGN"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/bKAU3CzJk-GBOUmhlUzUxapTaUDhe3lUuA22C4CfZ4w5X31xoh3ASWKJZtInyUm52Eo",
    "headerImage": "https://play-lh.googleusercontent.com/2DZD92VW4FbGRKviqmK_dV485iX5iKPPcO4jkDfx51IySTPBOfY8H-eRWKFRNZISJjs",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Onxm2b-JWQE8Ng6-LpUZKENS2lKqXlNbwqlNwlPd8eGOz9aKgNO0UbNFcIWx7k0pQwDI",
        "https://play-lh.googleusercontent.com/0EWOEWgZcapK-FP8sjhGkZfLCvMA-UHF2gMBIfBbl5WnOjvGlLHc6HY_Fbn6UpwJl0g",
        "https://play-lh.googleusercontent.com/Dceq2tL6x1hDtp54ypm6aNqxgLvFQBwPBHAQL5HOqUu5CxerWKaEDJjlnDWuV4mPTQ",
        "https://play-lh.googleusercontent.com/Bz1pNvPKHLLrkEfF7yyiKKhF3UIDLQdgnps0yixDuP_53uaC_4ePlTLP9xge__ZVFxg5",
        "https://play-lh.googleusercontent.com/s_pwAAJsKHqwcCFETn3ny09aJFiJk9C3z7H9mdCHDqsTs46fLZQWOC9dEX_X9gpZYA",
        "https://play-lh.googleusercontent.com/DgCUPym1e1H4WW01C2ouoxO-Q6h_FDVgPElc_6VcTYPC9hhbR7JWvZ7dLDiXbjl1irY",
        "https://play-lh.googleusercontent.com/NbLAuiROtVy-_daGeEDUEBPW14SoMEmD26keo16V78eZc2zg2vhPQneLcyLdqXrPNnue"
    ],
    "video": "https://www.youtube.com/embed/moeH9fm4_Cg?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/2DZD92VW4FbGRKviqmK_dV485iX5iKPPcO4jkDfx51IySTPBOfY8H-eRWKFRNZISJjs",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 25, 2020",
    "lastUpdatedOn": "Aug 18, 2024",
    "updated": 1724003185,
    "version": "1.43.0",
    "comments": [],
    "appId": "lv.crochet.app",
    "url": "https://play.google.com/store/apps/details?id=lv.crochet.app&hl=en&gl=us"
}