{
    "title": "Hullo - Matchmaking & Dating",
    "description": "MATCHMAKING, CHAT & DATING \u2013 THAT'S HULLO'S MISSION\r\n\r\nWith over 100,000 matchmakings every day, Hullo serves as the bridge between you and other singles, providing opportunities to meet and connect with compatible individuals. Whether you're seeking true love, a memorable relationship, exciting dates, or simply looking to expand your social circle, Hullo is here to fulfill all your needs! Meeting, connecting, and chatting online with like-minded people has never been easier.\r\n\r\nHULLO MATCHMAKING\r\nEvery day, you'll receive 1 free matchmaking. This is a feature you won't find on other apps. With just one tap, Hullo pairs you with the most suitable person, allowing you to start chatting immediately. Isn't that fantastic? We've done our part, now it's up to you. Remember to create an impressive profile with your best photos, a fun and witty description, and engaging conversation starters.\r\n\r\nHULLO VERIFIED GUARANTEE\r\nWe always strive to provide the best and safest user experience possible. Choose to interact with users who have been Hullo Verified to avoid scams and ensure your safety.\r\n\r\nEASY TO USE HULLO\r\n\"Like\" (Swipe right) if you're interested in someone. If both parties agree, you can start chatting with each other.\r\n\"Nope\" (Swipe left) if you don't feel compatible.\r\n\r\nPREMIUM USER EXPERIENCE\r\nPremium user features help you find compatible matches faster. Hullo is rated as the \"best free dating app\" and the \"most affordable dating app,\" which will save you a lot of money.\r\n\r\nPremium user package includes:\r\n- Ad removal.\r\n- See who likes you.\r\n- Unlimited swipes.\r\n- Choose your desired location.\r\n- Receive 7 priority direct message per week: use to instantly message anyone you like, without waiting for them to match with you.\r\n- Receive 3 Profile Boosts per week: boost your profile to the top of the Discovery page for 30 minutes in your area.\r\n- 70% off Match Coins.\r\n\r\nWHY CHOOSE HULLO?\r\nUnlimited interactions: Hullo doesn't limit the number of people you can connect with.\r\nCompletely free: Sending and receiving \"likes\" is completely free.\r\nMeet new people: You can connect with as many new people as you want without any cost.\r\nEasily find people near you: See who's online near you to start chatting immediately.\r\n\r\n***All images are for illustrative purposes only and feature models.\r\n\r\nPAYMENT TERMS\r\nPayment will be charged to your Apple ID account upon confirmation of purchase. Your subscription will automatically renew unless canceled at least 24 hours prior to the end of the current period. You can manage and cancel your subscription by going to your App Store account settings after purchase. Any unused portion of a free trial period, if offered, will be forfeited when you purchase a subscription.\r\n\r\n\u2022 Privacy Policy: https://hullo.dating/privacy-policy/\r\n\u2022 Terms of Use: https://hullo.dating/terms-of-use/\r\n\r\nLet Hullo be your reliable companion in finding your other half waiting for you in the world. Download Hullo now and start your dating adventure today!\r\n\r\nWishing you love and happiness in life!\r\n\r\nThe Hullo Team",
    "descriptionHTML": "MATCHMAKING, CHAT &amp; DATING \u2013 THAT&#39;S HULLO&#39;S MISSION<br><br>With over 100,000 matchmakings every day, Hullo serves as the bridge between you and other singles, providing opportunities to meet and connect with compatible individuals. Whether you&#39;re seeking true love, a memorable relationship, exciting dates, or simply looking to expand your social circle, Hullo is here to fulfill all your needs! Meeting, connecting, and chatting online with like-minded people has never been easier.<br><br>HULLO MATCHMAKING<br>Every day, you&#39;ll receive 1 free matchmaking. This is a feature you won&#39;t find on other apps. With just one tap, Hullo pairs you with the most suitable person, allowing you to start chatting immediately. Isn&#39;t that fantastic? We&#39;ve done our part, now it&#39;s up to you. Remember to create an impressive profile with your best photos, a fun and witty description, and engaging conversation starters.<br><br>HULLO VERIFIED GUARANTEE<br>We always strive to provide the best and safest user experience possible. Choose to interact with users who have been Hullo Verified to avoid scams and ensure your safety.<br><br>EASY TO USE HULLO<br>&quot;Like&quot; (Swipe right) if you&#39;re interested in someone. If both parties agree, you can start chatting with each other.<br>&quot;Nope&quot; (Swipe left) if you don&#39;t feel compatible.<br><br>PREMIUM USER EXPERIENCE<br>Premium user features help you find compatible matches faster. Hullo is rated as the &quot;best free dating app&quot; and the &quot;most affordable dating app,&quot; which will save you a lot of money.<br><br>Premium user package includes:<br>- Ad removal.<br>- See who likes you.<br>- Unlimited swipes.<br>- Choose your desired location.<br>- Receive 7 priority direct message per week: use to instantly message anyone you like, without waiting for them to match with you.<br>- Receive 3 Profile Boosts per week: boost your profile to the top of the Discovery page for 30 minutes in your area.<br>- 70% off Match Coins.<br><br>WHY CHOOSE HULLO?<br>Unlimited interactions: Hullo doesn&#39;t limit the number of people you can connect with.<br>Completely free: Sending and receiving &quot;likes&quot; is completely free.<br>Meet new people: You can connect with as many new people as you want without any cost.<br>Easily find people near you: See who&#39;s online near you to start chatting immediately.<br><br>***All images are for illustrative purposes only and feature models.<br><br>PAYMENT TERMS<br>Payment will be charged to your Apple ID account upon confirmation of purchase. Your subscription will automatically renew unless canceled at least 24 hours prior to the end of the current period. You can manage and cancel your subscription by going to your App Store account settings after purchase. Any unused portion of a free trial period, if offered, will be forfeited when you purchase a subscription.<br><br>\u2022 Privacy Policy: https://hullo.dating/privacy-policy/<br>\u2022 Terms of Use: https://hullo.dating/terms-of-use/<br><br>Let Hullo be your reliable companion in finding your other half waiting for you in the world. Download Hullo now and start your dating adventure today!<br><br>Wishing you love and happiness in life!<br><br>The Hullo Team",
    "summary": "Matchmaking the ideal person for you. Find friends near you, Meet Singles Chat",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 242147,
    "score": null,
    "ratings": null,
    "reviews": null,
    "histogram": [
        0,
        0,
        0,
        0,
        0
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $20.99 per item",
    "developer": "Hullo Dating Ltd",
    "developerId": "Hullo+Dating+Ltd",
    "developerEmail": "support@hullo.dating",
    "developerWebsite": "https://hullo.dating/",
    "developerAddress": null,
    "privacyPolicy": "https://hullo.dating/en/privacy-policy/",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/GH_38m4wo4HyQyue6CGrViAvC8CgQQaizTcAiGQWHrVu6sSuKUNp2Y39QUrg33hdjw_C",
    "headerImage": "https://play-lh.googleusercontent.com/RmMLU5PQvK_tBDTR4QcbgS1LUWUs1WtmL9iifxD__lZvZK5pmFTXAs-BhiqFseoWBA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/THZmOKP6VXp04uHV9QTYEQhtatcK0qU9Sbyy2ZTnP_Uv1oGsyTmV5uIgszFSQ40DQlk",
        "https://play-lh.googleusercontent.com/90aRD1m71EGvFdHTSvUH8IJiMqAN8MlW7N5YIqjgI2wH4D83rmHcWrJI9-NSeVLY8zE",
        "https://play-lh.googleusercontent.com/dNfR6nW7-Apk3fSD5sCv7RutXZfRUrOgTwvvPUOMHladU55ou7ONNIO4ayxU2ooxbjk",
        "https://play-lh.googleusercontent.com/Mcy10CZE1bdhNsFvXmgDWPCIGIIPpHeomvpGIQiUFBG8DafTOBQJgA1jS3L9qXYPpw",
        "https://play-lh.googleusercontent.com/RJrudq17QYKymWEceuEfqIwc8j6G-ZA4HGZXxoZCNmGh5QaLfEbFttrI4gb-A_WF8Kc",
        "https://play-lh.googleusercontent.com/hQv5iTP6aVuZo2_d7iZJHcPKykNKKES0kQywLR12eAM6_ENk1sax9vzqnF7ER370EAk",
        "https://play-lh.googleusercontent.com/HMZKVmXzoXXIJhIDbIovSaf4Ntag_whNssF_wY2k8t7BcbuYXca_pSbTH_vS-nEP0T83",
        "https://play-lh.googleusercontent.com/v3W_Ej6WG2vDxsPgtfU2uZksjoKhmLEUo9zPZlBBOKIxjiZXc4r7O0VxHZNXo0FRzQ",
        "https://play-lh.googleusercontent.com/FU42HCopNhBN2MdlOE2RZFngTtnjdDc-E9EFc4FLX4wL9Rf6whXjGmFh6uK2YQ5_1N0",
        "https://play-lh.googleusercontent.com/IOlj0oq1Kp_TuGI8cZ_Ovv8b26-EqKfRY2NG78tEDCI_dgggn_CpTz1Sw7QhyXEgVdk"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 22, 2023",
    "lastUpdatedOn": "Oct 15, 2024",
    "updated": 1729046970,
    "version": "1.3.0",
    "comments": [],
    "appId": "me.olachat.app",
    "url": "https://play.google.com/store/apps/details?id=me.olachat.app&hl=en&gl=us"
}