{
    "title": "MEGA",
    "description": "MEGA provides user-controlled encrypted cloud storage that\u2019s accessed with web browsers and dedicated apps for mobile devices. Unlike other cloud storage providers, your data is encrypted and decrypted by your client devices only and never by us.\r\n\r\nUpload files from your smartphone or tablet, then search, download, stream, view, share, rename or delete them from any device, anywhere. Share folders with your contacts and see their updates in real time.\r\n\r\nYou can also automatically connect your local data to sync to the Cloud drive, ensuring your important files are always safe and accessible across all your devices.\r\n\r\nMEGA\u2019s strong and secure end-to-end encryption means we cannot access or reset your password. You MUST remember the password and make sure to back up your account recovery key. Losing your password and the account recovery key will result in lost access to your files.\r\n\r\nUse the included MEGA secure chat for end-to-end-encrypted communications, including video and audio calls, with total privacy. Chat history synchronises automatically across multiple devices and you can also easily add files to, and from the MEGA Cloud drive.\r\n\r\nMEGA offers generous free storage for all registered users. You can get even more free storage in 5\u00a0GB increments through our MEGA Achievements Programme.\r\n\r\nNeed more storage? Check out our affordable MEGA Pro subscription plans that offer plenty more space:\r\nPro\u00a0Lite: \u20ac4.99 (US$4.99) per month or \u20ac49.99 (US$49.99) per year gives you 400\u00a0GB of storage space and 1\u00a0TB of transfer quota per month.\r\nPro\u00a0I: \u20ac9.99 (US$9.99) per month or \u20ac99.99 (US$99.99) per year gives you 2\u00a0TB storage space and 2\u00a0TB of transfer quota per month.\r\nPro\u00a0II: \u20ac19.99 (US$19.99) per month or \u20ac199.99 (US$199.99) per year gives you 8\u00a0TB storage space and 8\u00a0TB of transfer quota per month.\r\nPro\u00a0III: \u20ac29.99 (US$29.99) per month or \u20ac299.99 (US$299.99) per year gives you 16\u00a0TB storage space and 16\u00a0TB of transfer quota per month.\r\n\r\nAll MEGA client-side application code is published on GitHub, for transparency. The code of our Android mobile app is located at: https://github.com/meganz/android\r\n\r\nSubscriptions renew automatically for successive periods of the same duration at the same price as the initial period chosen. To manage your subscriptions, simply tap on the Play Store icon on your device, sign in with your Google ID (if you haven\u2019t already done so), then tap on the MEGA app.\r\n\r\nApp permissions (optional):\r\nContacts: MEGA accesses your contacts so you can add them from your device.\r\nMicrophone: MEGA accesses your microphone when you capture a video, make a call or record voice messages in the app.\r\nCamera: MEGA accesses your camera when you capture a video or photo, or make a call in the app.\r\nNearby devices: MEGA accesses nearby devices so you can use Bluetooth devices to join calls in the app.\r\nNotifications: MEGA sends notifications about chat messages, calls, transfer progress, contact requests, or incoming shares from other users.\r\nMedia (photos, videos, music and audio): MEGA accesses your media files when you upload, share through chat and when camera uploads is enabled.\r\nLocation: MEGA accesses your location when you share it with your contacts in chat.\r\n\r\nMEGA\u2019s Terms of Service: https://mega.io/terms\r\nPrivacy Policy: https://mega.io/privacy",
    "descriptionHTML": "MEGA provides user-controlled encrypted cloud storage that\u2019s accessed with web browsers and dedicated apps for mobile devices. Unlike other cloud storage providers, your data is encrypted and decrypted by your client devices only and never by us.<br><br>Upload files from your smartphone or tablet, then search, download, stream, view, share, rename or delete them from any device, anywhere. Share folders with your contacts and see their updates in real time.<br><br>You can also automatically connect your local data to sync to the Cloud drive, ensuring your important files are always safe and accessible across all your devices.<br><br>MEGA\u2019s strong and secure end-to-end encryption means we cannot access or reset your password. You MUST remember the password and make sure to back up your account recovery key. Losing your password and the account recovery key will result in lost access to your files.<br><br>Use the included MEGA secure chat for end-to-end-encrypted communications, including video and audio calls, with total privacy. Chat history synchronises automatically across multiple devices and you can also easily add files to, and from the MEGA Cloud drive.<br><br>MEGA offers generous free storage for all registered users. You can get even more free storage in 5\u00a0GB increments through our MEGA Achievements Programme.<br><br>Need more storage? Check out our affordable MEGA Pro subscription plans that offer plenty more space:<br>Pro\u00a0Lite: \u20ac4.99 (US$4.99) per month or \u20ac49.99 (US$49.99) per year gives you 400\u00a0GB of storage space and 1\u00a0TB of transfer quota per month.<br>Pro\u00a0I: \u20ac9.99 (US$9.99) per month or \u20ac99.99 (US$99.99) per year gives you 2\u00a0TB storage space and 2\u00a0TB of transfer quota per month.<br>Pro\u00a0II: \u20ac19.99 (US$19.99) per month or \u20ac199.99 (US$199.99) per year gives you 8\u00a0TB storage space and 8\u00a0TB of transfer quota per month.<br>Pro\u00a0III: \u20ac29.99 (US$29.99) per month or \u20ac299.99 (US$299.99) per year gives you 16\u00a0TB storage space and 16\u00a0TB of transfer quota per month.<br><br>All MEGA client-side application code is published on GitHub, for transparency. The code of our Android mobile app is located at: https://github.com/meganz/android<br><br>Subscriptions renew automatically for successive periods of the same duration at the same price as the initial period chosen. To manage your subscriptions, simply tap on the Play Store icon on your device, sign in with your Google ID (if you haven\u2019t already done so), then tap on the MEGA app.<br><br>App permissions (optional):<br>Contacts: MEGA accesses your contacts so you can add them from your device.<br>Microphone: MEGA accesses your microphone when you capture a video, make a call or record voice messages in the app.<br>Camera: MEGA accesses your camera when you capture a video or photo, or make a call in the app.<br>Nearby devices: MEGA accesses nearby devices so you can use Bluetooth devices to join calls in the app.<br>Notifications: MEGA sends notifications about chat messages, calls, transfer progress, contact requests, or incoming shares from other users.<br>Media (photos, videos, music and audio): MEGA accesses your media files when you upload, share through chat and when camera uploads is enabled.<br>Location: MEGA accesses your location when you share it with your contacts in chat.<br><br>MEGA\u2019s Terms of Service: https://mega.io/terms<br>Privacy Policy: https://mega.io/privacy",
    "summary": "MEGA is Cloud Storage with secure always-on privacy.",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 163502304,
    "score": 4.4887705,
    "ratings": 1446813,
    "reviews": 15475,
    "histogram": [
        103969,
        23151,
        54611,
        144998,
        1120041
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$5.30 - $320.00 per item",
    "developer": "Mega Ltd",
    "developerId": "5566309428969472081",
    "developerEmail": "android@mega.nz",
    "developerWebsite": "https://mega.io",
    "developerAddress": "Physical Address: Level 21 Huawei Centre, 120 Albert St\nAuckland 1010\nNew Zealand\n\nMail Address: Private Bag 92 533\nVictoria St West\nAuckland 1142\nNew Zealand",
    "privacyPolicy": "https://mega.nz/privacy",
    "genre": "Productivity",
    "genreId": "PRODUCTIVITY",
    "categories": [
        {
            "name": "Productivity",
            "id": "PRODUCTIVITY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/LPje8jSAa7MHJt4xaJUXn-aYy7LfFyKbc0HJuuf3c5__k7_9DbOJkwlVHvrdQ--kDvYp",
    "headerImage": "https://play-lh.googleusercontent.com/CYmIyrDj_7nia_ojZygGQZlAUCv5HXuUoYfnU9ozr9vmzzLI-sIW5dHTHkKjzcJO4gY",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Ypdt0B3zkDNO-JXYX20peZgnqvKItd13M1ueY_KI-NSpRwue2BBO-7XMbmyIE8_UcZo",
        "https://play-lh.googleusercontent.com/PJ_CwLf9z8JU3dbrPEzw2nGzugqqzWpxqMQ6hbucm0Pzwo99C06ME4ExIiLrZdfUgfMc",
        "https://play-lh.googleusercontent.com/RAba1tPrfxBHLinklfgKI9k98BUXpCvsivWY4YihVNMO0C-5Ha5l3tejBFkWg-aEeH2b",
        "https://play-lh.googleusercontent.com/LtWcPRjhwKDhZRv0n1jvnkU332XXddPPN5I_d7ND5mVVZaXTYr7in5pSAz4_zhGFqcw",
        "https://play-lh.googleusercontent.com/Oi69zlCfzUaZoK45VdYTldrciRXc8U2jKu9ZyIy9h_5zMyqSL-jyFJfl_L-0X34McA",
        "https://play-lh.googleusercontent.com/XMy400klxBcL3WsMJNVKsnxQZVxQgXpgFgfI2DQaCfuIuC9QxqtjA02vgVfSyU1LxBbf",
        "https://play-lh.googleusercontent.com/-sjctA7Qyu9I-w_tfOZukiVG1jyEcybwr7jgJ89azfrUeGcaYE9ZlNannU53onMfrA",
        "https://play-lh.googleusercontent.com/wQBpdzcLUOfX4EWvPU0Lj2cS_8bRGXcqdByNdSYZeR3_VLrSuyDshNup6K1WE_fxPg",
        "https://play-lh.googleusercontent.com/PDyM9MLyO9aOHScsl8SlvaDoPmdWapQGcjo0Be1VpNHP-FPwAaEQCbPXIS5uyZINpQ",
        "https://play-lh.googleusercontent.com/DK1cvkA9RqThC82VtLycLqD6xanl4FgXwHwzggz2NsVR1JXJZ7VkSalcMPUvkh9QkMg",
        "https://play-lh.googleusercontent.com/kqyST0o5Htnb4tRe3phpureMwroK8JS5__2KePxBo58TJ4n149ENBuzQ2ndVBSDxLcE2",
        "https://play-lh.googleusercontent.com/epzlhSnGcUrFJPeSsSi9U_0eWGWZbZDfocBtSOk1JCxVEd92iYKBXf2z5GXtn2WF6ns",
        "https://play-lh.googleusercontent.com/RVgO9ZD4ioApyhJp6IDRyPdTB0FG4eSfRkzdez7CKpI7N963R2p2DuCjy1ddPpDY1A",
        "https://play-lh.googleusercontent.com/-r1DICAC3WP2eBTubdBvmHVKVfQzeNVbMsvlyfWx-I0iOI8nvAkXWNc4yK3kd4ZCww",
        "https://play-lh.googleusercontent.com/SJdWsXveP04jknLaECCCnjzRnWp5kvswDk5DxJPXBKRenedk_4t_8WOMyiuKPFNxooE",
        "https://play-lh.googleusercontent.com/X7WvTjhHW03tuVP6fJudFA49WHm4IqOB0h2YEZK0e0kCVP8I46iPrq0SHQWj5QpH2Of-",
        "https://play-lh.googleusercontent.com/Uehl_v6cvF5rY28BEnXqfK_KUQGIs6qiujuU8j1ffHK-4W2Y9w9t_Akm42uWIxGcN-A",
        "https://play-lh.googleusercontent.com/dBYVyr0Tbgh8sFTkydYhWI6yq5pPAFJHXYP7ivAhYcC-ghBgjqDv5G9CrF1eNTO-BZeg"
    ],
    "video": "https://www.youtube.com/embed/KHVRb_kCpDo?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/CYmIyrDj_7nia_ojZygGQZlAUCv5HXuUoYfnU9ozr9vmzzLI-sIW5dHTHkKjzcJO4gY",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Feb 8, 2016",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729152207,
    "version": "Varies with device",
    "comments": [],
    "appId": "mega.privacy.android.app",
    "url": "https://play.google.com/store/apps/details?id=mega.privacy.android.app&hl=en&gl=us"
}