{
    "title": "BackPack Mod for Minecraft PE ",
    "description": "This is the first add-on for Minecraft: Bedrock Edition to implement fully working backpacks to the game. They are essentially a mobile chest which you can wear on your back while traveling around in your world. It\u2019s great if you are out on an adventure and need somewhere to offload your blocks and items. It\u2019s easy to wear and also easy to take off in case you need to access the storage space easily. It\u2019s definitely a must have for all the survivors out there!\r\n\r\nTo get a backpack you\u2019ll need to craft one. You can also dye them.Crafting recipes are listed below. To spawn a backpack long tap on the ground with the item.\r\n\r\nDisclaimer: This is an unofficial app for Minecraft Pocket Edition. This app is not affiliated in any way with Mojang AB. The name, brand and assets are the property of Mojang AB or its respectful owner.",
    "descriptionHTML": "This is the first add-on for Minecraft: Bedrock Edition to implement fully working backpacks to the game. They are essentially a mobile chest which you can wear on your back while traveling around in your world. It\u2019s great if you are out on an adventure and need somewhere to offload your blocks and items. It\u2019s easy to wear and also easy to take off in case you need to access the storage space easily. It\u2019s definitely a must have for all the survivors out there!<br><br>To get a backpack you\u2019ll need to craft one. You can also dye them.Crafting recipes are listed below. To spawn a backpack long tap on the ground with the item.<br><br>Disclaimer: This is an unofficial app for Minecraft Pocket Edition. This app is not affiliated in any way with Mojang AB. The name, brand and assets are the property of Mojang AB or its respectful owner.",
    "summary": "They are a mobile chest which you can wear on your back while traveling.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3635388,
    "score": 4.181818,
    "ratings": 54398,
    "reviews": 583,
    "histogram": [
        6577,
        785,
        4095,
        7404,
        35410
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Master Mod Minecraft",
    "developerId": "Master+Mod+Minecraft",
    "developerEmail": "mkappsupp@gmail.com",
    "developerWebsite": "https://mastermodweb.blogspot.com",
    "developerAddress": null,
    "privacyPolicy": "https://sites.google.com/view/9c2346",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/efoxiEY_DER4yONP7oN-n7C-g_OqbcIAlWjNF8cIz2nWToWJB-Gmkc2WfBypM9JaOA8",
    "headerImage": "https://play-lh.googleusercontent.com/gJT7LZvUQ5pN9Xjku4NhZ-gsNiwypNESkZq4Eb5WoYT_XWLMZohyAacPpYaHyTvI7wI",
    "screenshots": [
        "https://play-lh.googleusercontent.com/jhwgGVliasKkTfkvJAY7nCnHIe-NqeATNprE_LNpXzqwG4veAyFRPAQTScfarkyFFZJA",
        "https://play-lh.googleusercontent.com/jz3tHm8zmfxT8XjYRrc4EF_RAWaSkr9mMBgw74AZZo3eGas4m1YX6YYtIsMU_fe3zjBC",
        "https://play-lh.googleusercontent.com/7Euv22tLv7sFlok9HGk--xbsr-fXU-Uoy_nb5am6EnHr255BRf-Ct7k6plvwIQrgrw",
        "https://play-lh.googleusercontent.com/_mTWMJJ1LvXrv4No_oMah0ZEuN98Gsz7aOmqOgco2w1dj0WI_bj7WLF9xx1ldIrY-Aw",
        "https://play-lh.googleusercontent.com/EA00RzQpJxfNxkkUm7GC7M0FYgegK18GD1HpfmkW_zfSp4YHN8rzwNPBXwaK-mu9ZgRD",
        "https://play-lh.googleusercontent.com/aCjsi6b5NGsTf6BDoIOmg7lSIf8MiB7UYlt2tVZInTA6N2WXhy6df4fqjKevSrMF4fY",
        "https://play-lh.googleusercontent.com/b4ib1mCmKvDD6GBuIkkrkpPV_FfOESVODKRPmT-toj-79aEdAF1LjOdqy_X4SFlkrcc",
        "https://play-lh.googleusercontent.com/zAbKLpcoaK6PMJUCgSozt3bFQ_-eEawhp_QuvjUcNp8b1WHgumq8MdXd98oXRVaYgCU",
        "https://play-lh.googleusercontent.com/GbsP0ywVPkgdS9JUoSqZ6Yxz-2FvgmJqNINfSuDNlEK4r8ccxcbe8Qon7arYvHU2PZY"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 12, 2020",
    "lastUpdatedOn": "Aug 8, 2023",
    "updated": 1691490635,
    "version": "2.3.44",
    "comments": [],
    "appId": "minecraft.mk.mods.h",
    "url": "https://play.google.com/store/apps/details?id=minecraft.mk.mods.h&hl=en&gl=us"
}