{
    "title": "Superheroes Mod for Minecraft ",
    "description": "The main idea of the add-on is to add most things from the movie into your Minecraft world, including the six Infinity Stones. The Infinity Stones have no function, but the Infinity Gaunlet definitely has as sit can save you from death. There is also a Thanos Boss, who has 1000 health and can teleport using the Space Stone. So suit up and save the world!\r\n\r\nDisclaimer: This is an unofficial app for Minecraft Pocket Edition. This app is not affiliated in any way with Mojang AB. The name, brand and assets are the property of Mojang AB or its respectful owner.",
    "descriptionHTML": "The main idea of the add-on is to add most things from the movie into your Minecraft world, including the six Infinity Stones. The Infinity Stones have no function, but the Infinity Gaunlet definitely has as sit can save you from death. There is also a Thanos Boss, who has 1000 health and can teleport using the Space Stone. So suit up and save the world!<br><br>Disclaimer: This is an unofficial app for Minecraft Pocket Edition. This app is not affiliated in any way with Mojang AB. The name, brand and assets are the property of Mojang AB or its respectful owner.",
    "summary": "This mod is based off the Superheroes and Superpowers.",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4839065,
    "score": 4.3,
    "ratings": 24840,
    "reviews": 313,
    "histogram": [
        2966,
        719,
        988,
        1228,
        18877
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Master Mod Minecraft",
    "developerId": "Master+Mod+Minecraft",
    "developerEmail": "mkappsupp@gmail.com",
    "developerWebsite": "https://mastermodweb.blogspot.com",
    "developerAddress": null,
    "privacyPolicy": "https://sites.google.com/view/9c2346",
    "genre": "Events",
    "genreId": "EVENTS",
    "categories": [
        {
            "name": "Events",
            "id": "EVENTS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/bK3U7770MclHcZiUAw_DKwaDalxi_5_nYBoxFkbzMq_Cm4sgz9hpiPH_4Kkx3LV9CWc",
    "headerImage": "https://play-lh.googleusercontent.com/KZAuzAfwfPPSNTd5VFnbOhWZh2ItQyrtbGRXrIsQjCBOT0-tKOb_SN8M8Pf2uWJMiWVu",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Pf3sahlREJ82jt7NpEjpvd-8uPdSjwZtuHBEzQpyTWWWjuiylW0fdAgfFZclEgWPv0mU",
        "https://play-lh.googleusercontent.com/achpb7f0e7fVIvVDdWouvwHaKxDHYq_oMW1iO8H-XvZyhHxivAEQYQSMy5unTgTNpQ",
        "https://play-lh.googleusercontent.com/cDioiscTwn3ttQxmLWKLONCDqZZOwmWzf9eU0mpPVPwDdKYO4UH-oAeMeJgEMf2W9hbm",
        "https://play-lh.googleusercontent.com/QbfZLEyM_vlMIXz1pOPBaE3NwQnjbwK4dbVMV0jMo9Dj0K_T0vbLX863nKCyK-FVa0E",
        "https://play-lh.googleusercontent.com/t74jnFClYNNFO0Z4wx3s_v77ShZkvCNP2oaCZ03x8cZrFwr9Ty1bhOEEdrVkVy6jpj0",
        "https://play-lh.googleusercontent.com/JISyjmoJLRYwXIdgSJn-PnAi-sVMIW_SK6W1rPDYlp-tgJd3Q8t51P4hNaYC4lez2A",
        "https://play-lh.googleusercontent.com/zUAmPr4oSRhCfaPL36ocnpTW1Cr9rZh3ucgGrji3qiGdWJRUxEWOhOJYuQEcgsXZwTo",
        "https://play-lh.googleusercontent.com/ZSBDPVKjXPs-SzzUc-3xFc1UodZ34ZF0Vk8bZZejCCn-imaokhFqernC3lc1QhilIH0t",
        "https://play-lh.googleusercontent.com/F6qAvtfQhYy1Tbfo6liYyweN-xlvR5BUqIsWKL-7IFh09bWsfGBZc6ZtoCxYa44wcw",
        "https://play-lh.googleusercontent.com/bogIbxovR6QySYuu8FJuW14UiRHdYDfa3pouaqEQ2BZQUkuhCas-pyJtL7QXkdZ-d9TR",
        "https://play-lh.googleusercontent.com/9W-lDNOAsqToIVy61Vl8fPPfp5d9f4WJW-5SOznO5sul8_m98yVfMLGVKu9q2_mVyFo",
        "https://play-lh.googleusercontent.com/89RxpMdqWXw0rcSWn5DyG_Cm_ozLpMAqpKOC0lUuRI-gWIbOgwTuys68ptmgUV6K_Q"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone 10+",
    "contentRatingDescription": "Fantasy Violence",
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 12, 2020",
    "lastUpdatedOn": "Aug 8, 2023",
    "updated": 1691490647,
    "version": "2.3.44",
    "comments": [],
    "appId": "minecraft.mk.mods.j",
    "url": "https://play.google.com/store/apps/details?id=minecraft.mk.mods.j&hl=en&gl=us"
}