{
    "title": "Local News - Latest & Breaking",
    "description": "Local News - Latest & Breaking is a <b>comprehensive news platform</b> that provides the latest local news and breaking events in your community, county, city, and state. It helps you learn about your neighborhoods and the US with real-time news updates. Never miss any local trending headlines!\r\n\r\nLocal News focuses on local news stories that may affect you and your neighborhoods. All the news is handpicked from <b>trusted sources</b>, covering a wide range of topics, such as neighborhood anecdotes, traffic and weather alerts, sports events, and more. It delivers news based on your preference and location, making it easy for you to stay up-to-date on your concerned local events, weather, and traffic conditions.\r\n\r\nNow, experience the thrill of knowing everything in your area without leaving home! Local News has your back!\r\n\r\n\r\n\ud83e\uddd0 <b>Why choose Local News?</b>\r\n\u2726 Live local & breaking news updates\r\n\u2726 Headlines curated for you\r\n\u2726 Trusted news sources\r\n\u2726 Real-time weather forecast\r\n\u2726 User-friendly Interface\r\n\r\n\r\n\ud83d\udce3 <b>Personalized News Feed</b>\r\nIts personalized news feed perfectly satisfies your curiosity and interests, allowing you to easily access the news that you really care about or are interested in. Stay up-to-date with local news on politics, business, sports, entertainment and more\u2026\r\n\r\n\ud83c\udf0e <b>Rich and Reliable News Sources</b> \r\nWe provide portals to a variety of local news sources, ensuring that all current events are at your fingertips. Keep you updated with the most authentic events from trusted sources. Get the latest news stories with just one refresh!\r\n\r\n\ud83d\udcf1 <b>Concise Interface Design</b>\r\nWe've designed an intuitive user interface and an easy-to-read format. This guarantees you a seamless experience as you dive into the latest news articles and trending topics. You can also check history and bookmarks at any time to revisit the news you care about.\r\n\r\n\u26c5 <b>Real-time Weather Conditions</b>\r\nStay informed with live weather updates and plan your activities with confidence. With 24-hour and 7-day forecasts, you'll have all the information you need to stay ahead of changing weather conditions.\r\n\r\n\r\n\ud83c\udf89 More exciting features, waiting for you to discover\u2026\r\n\r\n\r\nEmbrace the ever-changing world, stay informed with up-to-date information, follow live local news updates and find out about local news near you. Based on trusted sources, we provide you with rich and comprehensive content and customizable feed to suit your needs. Don't miss out - download now and stay seamlessly connected to what's going on around you!\r\n\r\nIf you have any thoughts or concerns while using our app, please don't hesitate to contact us at localnews.feedbacks@gmail.com.\r\n\r\n\r\nDisclaimer:\r\n- Local News is only an RSS feeds aggregator and is not affiliated with any news media site. \r\n- Local News aims to enhance the accessibility of news content and facilitate the dissemination of information. Any news content does not represent the position of our app.\r\n- Any unauthorized actions and violations of intellectual property rights are the sole responsibility of the user (e.g. share/comment on news).\r\n- Local News adheres to the principles of fair use, if you would like us to remove your site from our platform, please feel free to contact us at support@zankhana.ltd.",
    "descriptionHTML": "Local News - Latest &amp; Breaking is a <b>comprehensive news platform</b> that provides the latest local news and breaking events in your community, county, city, and state. It helps you learn about your neighborhoods and the US with real-time news updates. Never miss any local trending headlines!<br><br>Local News focuses on local news stories that may affect you and your neighborhoods. All the news is handpicked from <b>trusted sources</b>, covering a wide range of topics, such as neighborhood anecdotes, traffic and weather alerts, sports events, and more. It delivers news based on your preference and location, making it easy for you to stay up-to-date on your concerned local events, weather, and traffic conditions.<br><br>Now, experience the thrill of knowing everything in your area without leaving home! Local News has your back!<br><br><br>\ud83e\uddd0 <b>Why choose Local News?</b><br>\u2726 Live local &amp; breaking news updates<br>\u2726 Headlines curated for you<br>\u2726 Trusted news sources<br>\u2726 Real-time weather forecast<br>\u2726 User-friendly Interface<br><br><br>\ud83d\udce3 <b>Personalized News Feed</b><br>Its personalized news feed perfectly satisfies your curiosity and interests, allowing you to easily access the news that you really care about or are interested in. Stay up-to-date with local news on politics, business, sports, entertainment and more\u2026<br><br>\ud83c\udf0e <b>Rich and Reliable News Sources</b> <br>We provide portals to a variety of local news sources, ensuring that all current events are at your fingertips. Keep you updated with the most authentic events from trusted sources. Get the latest news stories with just one refresh!<br><br>\ud83d\udcf1 <b>Concise Interface Design</b><br>We&#39;ve designed an intuitive user interface and an easy-to-read format. This guarantees you a seamless experience as you dive into the latest news articles and trending topics. You can also check history and bookmarks at any time to revisit the news you care about.<br><br>\u26c5 <b>Real-time Weather Conditions</b><br>Stay informed with live weather updates and plan your activities with confidence. With 24-hour and 7-day forecasts, you&#39;ll have all the information you need to stay ahead of changing weather conditions.<br><br><br>\ud83c\udf89 More exciting features, waiting for you to discover\u2026<br><br><br>Embrace the ever-changing world, stay informed with up-to-date information, follow live local news updates and find out about local news near you. Based on trusted sources, we provide you with rich and comprehensive content and customizable feed to suit your needs. Don&#39;t miss out - download now and stay seamlessly connected to what&#39;s going on around you!<br><br>If you have any thoughts or concerns while using our app, please don&#39;t hesitate to contact us at localnews.feedbacks@gmail.com.<br><br><br>Disclaimer:<br>- Local News is only an RSS feeds aggregator and is not affiliated with any news media site. <br>- Local News aims to enhance the accessibility of news content and facilitate the dissemination of information. Any news content does not represent the position of our app.<br>- Any unauthorized actions and violations of intellectual property rights are the sole responsibility of the user (e.g. share/comment on news).<br>- Local News adheres to the principles of fair use, if you would like us to remove your site from our platform, please feel free to contact us at support@zankhana.ltd.",
    "summary": "The latest local & breaking news app. Stay informed about all events around you!",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 17613,
    "score": 4.361446,
    "ratings": 95,
    "reviews": 24,
    "histogram": [
        8,
        0,
        8,
        12,
        66
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "ZANKHANA PTE LTD",
    "developerId": "ZANKHANA+PTE+LTD",
    "developerEmail": "support@zankhana.ltd",
    "developerWebsite": "https://zankhana.ltd",
    "developerAddress": null,
    "privacyPolicy": "https://zankhana.ltd/privacypolicy.html?pkg=news.local.latest.newsbreak.free.app",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/LvNdxrUNMlZKmZC-fZMXiICxKbLCGTscIAyKNR_AnMXIskgHZjeP1RTf61LHhaAE_cB8",
    "headerImage": "https://play-lh.googleusercontent.com/zqKKjsbmFgG6ppVf8u9hs57JSJIHPPhzyleFI3zkh-wGpiWNvynxztBQYpl8DahNGn0",
    "screenshots": [
        "https://play-lh.googleusercontent.com/9giOX_gxCcEneFtErPjZXjq-ahHhzGSd-pOq2013klPEHxmBhpQVpKAydaCkBErI9HM",
        "https://play-lh.googleusercontent.com/d0YQhjtUcGjf7_h1rTXL_YoAq-Pqdo1ENWn-XSN12-ZmeQYNrTEKljNiOXyX3gAqik0",
        "https://play-lh.googleusercontent.com/843LC-0xdv9Xscfo66k2cqspqQGx5vdSu7CDw66MY7jolFNpkSvy8Tps1lywa0ssEzaA",
        "https://play-lh.googleusercontent.com/70GSf407iBCGhumm-BYyxZFq6nIR_qDGcC4SzsXvfqPnENXzsFLbAlgv1T83oU0pesHI",
        "https://play-lh.googleusercontent.com/64LOXEmtM56Z01aZ08ekm2AxnVHx9XxKfTwulM3SFgGX3ZmMT8QH9AZKRmfMNl8HBPY",
        "https://play-lh.googleusercontent.com/CjOX4JGLAWA8qvn1sPf56ZaVlUOQjs_p7lLr59Cem_jcw7LcOYBMFFdWJdjrjKa5Xl4"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 12, 2023",
    "lastUpdatedOn": "Sep 4, 2024",
    "updated": 1725449030,
    "version": "1.1.8",
    "comments": [],
    "appId": "news.local.latest.newsbreak.free.app",
    "url": "https://play.google.com/store/apps/details?id=news.local.latest.newsbreak.free.app&hl=en&gl=us"
}