{
    "title": "Passport Size Photo Maker",
    "description": "Passport Photo Maker offers a quick and easy solution for creating official passport photos from the comfort of your home. With our user-friendly app, you can take and edit photos to meet international passport standards within minutes.\r\n\r\nThis app guides you through the photo-taking process, ensuring that your photos meet the size and background requirements for various countries. Features include an automatic background remover, size adjustments, and a comprehensive guide on passport photo specifications worldwide.\r\n\r\n\ud83d\udcf8 Features Include:\r\n\u221a Auto background removal for a clean, compliant photo.\r\n\u221a Auto photo cropper/resizer to get the correct 2x2 size photo. \r\n\u221a A library of photo-size templates for different countries.\r\n\u221a Save or print photos directly from your phone.\r\n\u221a Guidance for acceptable photo standards globally.\r\n\r\nPhoto Editing App\r\nNot just a passport photo maker, our app doubles as a versatile photo editing tool. Edit any photo with tools like crop, adjust, and retouch to achieve the perfect look.\r\n\r\nID Photos Made Easy\r\nWhether you need a photo for a passport, visa, or other official documentation, our app makes it simple and quick. Follow step-by-step instructions to capture the perfect ID photo.\r\n\r\nProfessional Photos at Home\r\nNo need to visit a photo booth or professional photographer. Our app provides all the tools you need to create professional-quality photos with your smartphone.\r\n\r\nMake Passport Photo Maker your go-to app for all official photo needs. It's like having a photo booth in your pocket! \ud83d\udcaa \ud83d\udcaa \ud83d\udcaa",
    "descriptionHTML": "Passport Photo Maker offers a quick and easy solution for creating official passport photos from the comfort of your home. With our user-friendly app, you can take and edit photos to meet international passport standards within minutes.<br><br>This app guides you through the photo-taking process, ensuring that your photos meet the size and background requirements for various countries. Features include an automatic background remover, size adjustments, and a comprehensive guide on passport photo specifications worldwide.<br><br>\ud83d\udcf8 Features Include:<br>\u221a Auto background removal for a clean, compliant photo.<br>\u221a Auto photo cropper/resizer to get the correct 2x2 size photo. <br>\u221a A library of photo-size templates for different countries.<br>\u221a Save or print photos directly from your phone.<br>\u221a Guidance for acceptable photo standards globally.<br><br>Photo Editing App<br>Not just a passport photo maker, our app doubles as a versatile photo editing tool. Edit any photo with tools like crop, adjust, and retouch to achieve the perfect look.<br><br>ID Photos Made Easy<br>Whether you need a photo for a passport, visa, or other official documentation, our app makes it simple and quick. Follow step-by-step instructions to capture the perfect ID photo.<br><br>Professional Photos at Home<br>No need to visit a photo booth or professional photographer. Our app provides all the tools you need to create professional-quality photos with your smartphone.<br><br>Make Passport Photo Maker your go-to app for all official photo needs. It&#39;s like having a photo booth in your pocket! \ud83d\udcaa \ud83d\udcaa \ud83d\udcaa",
    "summary": "Create official passport photos with our easy-to-use tool\u2014no professional needed",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 7015390,
    "score": 4.272517,
    "ratings": 48311,
    "reviews": 1416,
    "histogram": [
        7140,
        557,
        669,
        3570,
        36372
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Passport Photo Online",
    "developerId": "Passport+Photo+Online",
    "developerEmail": "help@passport-photo.online",
    "developerWebsite": "https://passport-photo.online",
    "developerAddress": "ul. Mielczarskiego 8/58\n02-798 Warszawa\nPolska",
    "privacyPolicy": "https://passport-photo.online/privacy-policy",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/noeQdI9c1qz7_VQkMTBqkSwYgDDR18j3E_Xy6FO2vEvjZDbCmUx1R2mQP-uv1Ap36YU",
    "headerImage": "https://play-lh.googleusercontent.com/n9hs9G3mn-s1p54j4BsNcsGZotkjnXEurWdaoUYUK1Ja_i2bEhJ11PIkvtZvoGn7Iw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/krVte8b0QvmMii1jOru-j-Bwu7NCV-sgz5Tw9-cTrY7bymbpYMQJXeR_wp3ncktpzrs",
        "https://play-lh.googleusercontent.com/1rr4HdbWpN8RIZlUDPsFgPhF5ppGP80ggAGm7RRo1jNhA3ddVKj5tndpCOY0c_ADKEk",
        "https://play-lh.googleusercontent.com/GopPHr47TlJncentWpHt_mzBeOIo4DMswzizaVbywFjOTlttfCkNcOTKzEjkxUpI1E4",
        "https://play-lh.googleusercontent.com/qncYjz627jmloZFBHq0WgGMZDOiw20mU-61HPh0oSSyKLj8t91n5KNnM_hbdqVYG_Lo",
        "https://play-lh.googleusercontent.com/Pu6uzSPbmc6UAsbs9teE-wQMnQnBIGfQVpgr5sNmApfpOERwzwKuPZipQnVuT7DlpOM",
        "https://play-lh.googleusercontent.com/qtfRe99izF7F-9JlsZvDsvNaREvfEwX2jd6VZy1BARyJ2oc-TxMY4-5uXCN1QKTmCA",
        "https://play-lh.googleusercontent.com/sGs2XnQEYJndUBiNKGDatxfEsDWRLgBoKy1AoiN7GD8sewQjYfrjtTwJhToMWL0stPzG",
        "https://play-lh.googleusercontent.com/lj1Z0oxil1jatRJjVW1MA2DkRJP4Du4UBuYqRRLOggJvNxEHbtNsZqcOh9c1rS8zKyRY",
        "https://play-lh.googleusercontent.com/DpYskDB1h5H1CyiB8fs4vkHyM5qzRR1gBUksgXSUDfBZFGMldyKiIfGScM6wPn6W5g",
        "https://play-lh.googleusercontent.com/1pr85tWpCuKnV8tQEq8l8Ykdb3fchTeO3N49OZbqs6TMOumc8Tl6xc282Vws7G-nJUU",
        "https://play-lh.googleusercontent.com/TQMJqRNeJk-g-eENof_1M59srjqzY7xlX8C9STfsPNS05x57I6ELDJ7cUaHXHu39rJI",
        "https://play-lh.googleusercontent.com/EvA4VDTpy3s2Z1xggZHK9GEYEFgPqkMhVU1WJW58U1TpRIqW-TdjtGW_09E4Me6daQ",
        "https://play-lh.googleusercontent.com/T1H_yL2Yahj_GFdOm6DbsVgzLnP-vv5i4HRj5WpAR5EtO3YcxV7oGH1A2p0tMkJgfg",
        "https://play-lh.googleusercontent.com/0vm7aYFwpiyjS8djlntcswdzBHelDPWuiRnBH6T9iBeT-wyazN3_eUGWwKOlSD5cM-s",
        "https://play-lh.googleusercontent.com/2ROjaNjlUSspCCwJ3ogyiMKAux8QbxO_-S85fHZl-7odCfgrH9CLmqzZzKcGLLPG7ww",
        "https://play-lh.googleusercontent.com/LfMbAiejdP4eJeb0LMd-dIkq41m0oZE7rE7fU5qk5ksFn7i2VDpJiiIQNrVUaBRFfws",
        "https://play-lh.googleusercontent.com/zvMLRfX_Z3TiURHKxie2lHPr-CAhnTvIPfxQX50v0SyFuyX99F_4W7k-gW9w5m6XPg",
        "https://play-lh.googleusercontent.com/F9nWXuJMaMQvIPWj1VOORkVVRvU-4HxI1fiQF0EdqMj7yimQ-XVKHNGOTAQEgrOADX0",
        "https://play-lh.googleusercontent.com/42E0mpmQGyqoQAeL9lTvPRI11jN457drPLxuvJPxFtOjkglm0k08Brx5M_92dHjcZHI8",
        "https://play-lh.googleusercontent.com/8bVixTkajmOE6v65pUxkQ-YxBE2c5KtYVfQ5X0C8cgFgd_ZelpzUS-zD841ai6nu5472",
        "https://play-lh.googleusercontent.com/LXHSg6ZEedS0-VUI2mzPk1hDM5tjjElGPHq3zH8QGhTJDn4LFb0Xjr_grhmvtn5M7w",
        "https://play-lh.googleusercontent.com/dOr-M8JLK9QBVj52MtYAaNWdYE3VIj7mFJ4euQjS5WGG1cLd0IVko6dWF6sdN5INVDI",
        "https://play-lh.googleusercontent.com/bhtVjHhbP3IJzHj5HWRxidK_VPgfwUPwrA4sMU90fdXPnKHm1Ch60wC8xh6f_dPYlAg",
        "https://play-lh.googleusercontent.com/4h5JtMfRuQqwM010i4QKhRMI4g-473s6X3WlK7AlbEni1dGlKj877rqL7ssgsvIoqg",
        "https://play-lh.googleusercontent.com/7wdVWmXkL5C30WxSE78EutPqpZVDKAHKs-vPRWY6L5Q7hKeAsSZJV-I2EyW_1seg3UlS",
        "https://play-lh.googleusercontent.com/cLJw94WA9wBGk7qFAO1e0htBXVkkGRqy3HJ9XNNWETRBeBG5YtldJ4esOWgeRzZMXM0",
        "https://play-lh.googleusercontent.com/4pfCiJPwiLubrDwzg8V7cIBWYHJiyy7U22LrH4Pq2gpXyV_BkkpZ_QZuMh2pYk3Y4d4",
        "https://play-lh.googleusercontent.com/Rq9HqgUZQOwk0220lL3xUOcpGesYgYjDXXL67j9Czb7rAFLMpTR9ITdcWmH5wXPPQ1dZ"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Nov 23, 2019",
    "lastUpdatedOn": "Sep 18, 2024",
    "updated": 1726727016,
    "version": "1.12.0",
    "comments": [],
    "appId": "online.passportphoto.visa.id.app",
    "url": "https://play.google.com/store/apps/details?id=online.passportphoto.visa.id.app&hl=en&gl=us"
}