{
    "title": "Cash\u2019em All: Play & Win",
    "description": "<b>Earn free gift cards and money by playing free games. It\u2019s time you grow and become your own boss. Don\u2019t miss this lucky day!</b>\r\n\r\nAll you have to do is play and you will be rewarded for your time.\r\n\r\nGet Cash'em All for free (no deposits, no in-app purchases, and, no ads at all) \u2705\r\nChoose and play your favorite game from our list \ud83c\udfae\r\nGet rewards for every minute you spend playing free games \ud83c\udf81\ud83c\udf89\ud83c\udfc6\r\n\r\nAre you looking for a cash app that pays you for real?\r\n\u2192 Start playing games that give you free money!\r\n\r\nCash'em All is a <b>completely free app</b>, offering you the opportunity to earn real money by playing free games on your mobile phone. \r\n\r\nDiscover and play new and popular games every day from our list \u27a1 spend time playing free games, collect coins \u27a1 <b>exchange coins and win gift cards and discounts from top brands as well as  cash prizes\r\n\r\nPlaying free games and making money sounds exciting, right? Now, let\u2019s get to the point.\r\n\r\n<b>How to start making money with our reward app?</b>\r\n\r\nCash'em All is so easy to use:\r\n\r\n\u2713\ud83d\udcf1 Get Cash'em All now for FREE\r\n\u2713\ud83c\udfae Play any of our FREE partner games\r\n\u2713\ud83d\udc8e Earn coins for every second you play\r\n\u2713\u23f0 The more you play the more money you\u2019ll make\r\n\u2713\ud83d\udcb2 Trade your coins for ANY gift card or real money rewards\r\n\r\nThat\u2019s it \ud83d\ude0a \r\n\r\n<b>Why Cash'em All?</b>\r\n\r\n\u2714\ufe0fCompletely free cash app (\u26d4no deposits, \u26d4no in-app purchases, \u26d4 no ads)!\r\n\u2714\ufe0fEasy to use!\r\n\u2714\ufe0fFast and guaranteed payouts!\r\n\u2714\ufe0fHuge variety of available payout options\r\n\u2714\ufe0fHuge selection of different game types to fit any preference!\r\n\u2714\ufe0fInvite your friends to Cash'em All and you both get extra cash prizes!\r\n\r\nIf you\u2019re reading this, you shouldn\u2019t waste this lucky day! <b>Free games and free money in one app, without any ads. </b>\r\n\r\nThe exciting thing about our app is that you can earn your first gift card or get your paypal money reward after just a few hours you spent playing any game you choose! \r\nCurrently, our offer wall contains <b>various game types</b> such as Casual, Strategy, Action, Puzzle, Adventure, Arcade, and many more. You can play ANY game you like and start earning cash!\r\n\r\nIf you already like playing mobile games, Cash'em All is the app for you as you will earn money playing games! \r\n\r\nWith Cash'em All you will never have to worry about your pocket money again! \r\n\r\nSo, what keeps you waiting on trying and earning your free money! \ud83c\udfc6\r\n\r\nOffers and rewards are subject to availability.</b>",
    "descriptionHTML": "<b>Earn free gift cards and money by playing free games. It\u2019s time you grow and become your own boss. Don\u2019t miss this lucky day!</b><br><br>All you have to do is play and you will be rewarded for your time.<br><br>Get Cash&#39;em All for free (no deposits, no in-app purchases, and, no ads at all) \u2705<br>Choose and play your favorite game from our list \ud83c\udfae<br>Get rewards for every minute you spend playing free games \ud83c\udf81\ud83c\udf89\ud83c\udfc6<br><br>Are you looking for a cash app that pays you for real?<br>\u2192 Start playing games that give you free money!<br><br>Cash&#39;em All is a <b>completely free app</b>, offering you the opportunity to earn real money by playing free games on your mobile phone. <br><br>Discover and play new and popular games every day from our list \u27a1 spend time playing free games, collect coins \u27a1 <b>exchange coins and win gift cards and discounts from top brands as well as  cash prizes<br><br>Playing free games and making money sounds exciting, right? Now, let\u2019s get to the point.<br><br><b>How to start making money with our reward app?</b><br><br>Cash&#39;em All is so easy to use:<br><br>\u2713\ud83d\udcf1 Get Cash&#39;em All now for FREE<br>\u2713\ud83c\udfae Play any of our FREE partner games<br>\u2713\ud83d\udc8e Earn coins for every second you play<br>\u2713\u23f0 The more you play the more money you\u2019ll make<br>\u2713\ud83d\udcb2 Trade your coins for ANY gift card or real money rewards<br><br>That\u2019s it \ud83d\ude0a <br><br><b>Why Cash&#39;em All?</b><br><br>\u2714\ufe0fCompletely free cash app (\u26d4no deposits, \u26d4no in-app purchases, \u26d4 no ads)!<br>\u2714\ufe0fEasy to use!<br>\u2714\ufe0fFast and guaranteed payouts!<br>\u2714\ufe0fHuge variety of available payout options<br>\u2714\ufe0fHuge selection of different game types to fit any preference!<br>\u2714\ufe0fInvite your friends to Cash&#39;em All and you both get extra cash prizes!<br><br>If you\u2019re reading this, you shouldn\u2019t waste this lucky day! <b>Free games and free money in one app, without any ads. </b><br><br>The exciting thing about our app is that you can earn your first gift card or get your paypal money reward after just a few hours you spent playing any game you choose! <br>Currently, our offer wall contains <b>various game types</b> such as Casual, Strategy, Action, Puzzle, Adventure, Arcade, and many more. You can play ANY game you like and start earning cash!<br><br>If you already like playing mobile games, Cash&#39;em All is the app for you as you will earn money playing games! <br><br>With Cash&#39;em All you will never have to worry about your pocket money again! <br><br>So, what keeps you waiting on trying and earning your free money! \ud83c\udfc6<br><br>Offers and rewards are subject to availability.</b>",
    "summary": "Play games and earn money on your Paypal account or win gift cards.",
    "installs": "50,000,000+",
    "minInstalls": 50000000,
    "realInstalls": 67557256,
    "score": 4.3268957,
    "ratings": 1326920,
    "reviews": 26604,
    "histogram": [
        93360,
        33778,
        114147,
        190042,
        895572
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Cash'em All",
    "developerId": "Cash'em+All",
    "developerEmail": "support@cashemall.online",
    "developerWebsite": "https://cashemall.online/",
    "developerAddress": null,
    "privacyPolicy": "https://cashemall.online/legal/privacy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/8wqkWGNUrTczAVIb0k-5Es6QXThOHdO81zJhySA13eaR6r9lGzcHRHcAp9-0TOJopw",
    "headerImage": "https://play-lh.googleusercontent.com/DUAQFgiJsm-P9UgpZ1EDuGTujHcq7jF3fr1aez3sgb5tXz9d_rhag7KrGKUSGYKcK8ls",
    "screenshots": [
        "https://play-lh.googleusercontent.com/QpXwCAOqNfzQCwJx5IaBbT2VEqRecMSN7DRF5sEvkWoMcfvcYebiErq5xgLfkBreKQ",
        "https://play-lh.googleusercontent.com/9qpczIGw7giJW1MM5_Ce3ERXUgvBhE7VFg4SD9eH3J83-3Ov8abr_GV7MwvBnw_Ncw",
        "https://play-lh.googleusercontent.com/umFksXtxWaIG5H_vStCN9Li_mEvLLuodgQ3xqVk0YRHQ6XqWoSB_XadN-6ZClOXn6Q",
        "https://play-lh.googleusercontent.com/CdPWcepJuqfoWro_nvug-9sivsoFqbHmhQYQTSdnxeqfQ4yjC3rSiVE3pEpggdfnwuaF",
        "https://play-lh.googleusercontent.com/o-TPqrzdJ7hRW0-svO4O8lfC1MCcfe-TwcMymNhAAz_tplxALoS6LrdZ_rHipmMFX_Gn"
    ],
    "video": "https://www.youtube.com/embed/j9VKXWsuHpo?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/DUAQFgiJsm-P9UgpZ1EDuGTujHcq7jF3fr1aez3sgb5tXz9d_rhag7KrGKUSGYKcK8ls",
    "contentRating": "Teen",
    "contentRatingDescription": "Simulated Gambling",
    "adSupported": true,
    "containsAds": true,
    "released": "Jun 25, 2020",
    "lastUpdatedOn": "Oct 16, 2024",
    "updated": 1729091822,
    "version": "5.1.0-CashemAll",
    "comments": [],
    "appId": "online.cashemall.app",
    "url": "https://play.google.com/store/apps/details?id=online.cashemall.app&hl=en&gl=us"
}