{
    "title": "AA Grapevine",
    "description": "The Grapevine app is all things Grapevine right on your smartphone. The monthly magazine, the articles archives, the podcast, the daily quote, an enhanced sobriety calculator, and the AA events calendar. App-exclusive features include a spiritual maintenance checklist and the ability to share articles, and your own experience, strength, and hope with other Grapevine app users. The app allows for more content each month too. Service-oriented members will find easy ways to be a part of the AA Grapevine Community in our Get Involved section. You\u2019ll be able to read Grapevine anonymously wherever you go. You can also listen to each month\u2019s articles on a playlist, and listen to the podcast playlist right on the app.",
    "descriptionHTML": "The Grapevine app is all things Grapevine right on your smartphone. The monthly magazine, the articles archives, the podcast, the daily quote, an enhanced sobriety calculator, and the AA events calendar. App-exclusive features include a spiritual maintenance checklist and the ability to share articles, and your own experience, strength, and hope with other Grapevine app users. The app allows for more content each month too. Service-oriented members will find easy ways to be a part of the AA Grapevine Community in our Get Involved section. You\u2019ll be able to read Grapevine anonymously wherever you go. You can also listen to each month\u2019s articles on a playlist, and listen to the podcast playlist right on the app.",
    "summary": "Carry everything Grapevine on your smartphone \u2014 everywhere you go.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 19742,
    "score": 4.6153846,
    "ratings": 57,
    "reviews": 25,
    "histogram": [
        4,
        0,
        0,
        4,
        48
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.99 - $29.99 per item",
    "developer": "Grapevine and La Vi\u00f1a Apps",
    "developerId": "Grapevine+and+La+Vi%C3%B1a+Apps",
    "developerEmail": "webcoord@aagrapevine.org",
    "developerWebsite": "https://aagrapevine.org",
    "developerAddress": null,
    "privacyPolicy": "https://www.aagrapevine.org/website-policy",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/s6y8L_G0a3jZ_ZZpP1028htUNn8ciDp3vLN5EsRsqb6Ht3hZFy8nXQug6sor6eGTH5k",
    "headerImage": "https://play-lh.googleusercontent.com/LlhrXb96fkxbR-TMXMQhc3ZdKwCkN2HfcntzcNjjP6VFoURi-_UCK4YU2dGfyZ52",
    "screenshots": [
        "https://play-lh.googleusercontent.com/w1RIlasdW7yPnMZu9FVkZ1FPeFY-aWM8EZkZArLfRQZaap5BgABzHA-BayvHqxNBgCg",
        "https://play-lh.googleusercontent.com/SvPn19Rr2dBA6q-Vn8gDmX-uAWbPGXndFm7c_ZMKeWPMrW_FAMqrU1IamDvH61M-ipc",
        "https://play-lh.googleusercontent.com/u4vg3qVddrCdHwu4KObsiCgW2H1Cyw9XrJ2cb9seTwonTp54TV0QKDmld8Cmtj3ubUSc",
        "https://play-lh.googleusercontent.com/Q1aOe3DA0BshxBAA_EN_pE6ebfqhiGk9yyblqeXdYVznWjMWR-Ub2slhdnq5gG7Qx-0J",
        "https://play-lh.googleusercontent.com/VeUysCVZ6rcG5sdSM5xInld0LFbABNq3IH-CsHXPubzt1jNtdfLMUqJeZkhbxrNRGJw",
        "https://play-lh.googleusercontent.com/LfHSnWmQV8Dw5irhdfQWhX2vkmG3ioX79WCntXPSJi6vmUPWwjVB4nw_ocsjhVncTmU",
        "https://play-lh.googleusercontent.com/Rmt-O5EwJ7VNq1VTpISi7HLt9WWyAy2J9YQj8y6a2H58100uaG4KRi-4tQwgP7vWoI8",
        "https://play-lh.googleusercontent.com/hvl7gfq2lwPOWZs3bB4vYKgwMuWrJnKt7Zu46nZfEQnk5uFcbhlue10fDsnkURgHMD8",
        "https://play-lh.googleusercontent.com/bSvq-K5Wc3sjVrNBV3AV6WXncjwO5scmeZk2ZYuxDsByQsgU8BF5TYTJCz33roWIkQA",
        "https://play-lh.googleusercontent.com/sCM8z6sW55FYF1eGb5wVLjXlnJoxmG-Czu8u6nAtiq0BxTkNbpVGbpiirAndvofSnBc",
        "https://play-lh.googleusercontent.com/tJRa1cPfCdDFMZyrr7Ab_hSxATdY8tOUH4EyYtb4plakgMp4bcjyfgBtnoJtm1Ifu8Kq",
        "https://play-lh.googleusercontent.com/L4zpq8W2GYM0CDNVPXp-TudFGx1TpGlnk_9Zpe7UYkxUi4aKKD96d9sbyTXufVF6WC1H",
        "https://play-lh.googleusercontent.com/BHOme-AytzwvM6I-kxRJx235cCiJL1uGgBt6mNMCIOJiI4r6mTv45xuT_3dictrFlTI",
        "https://play-lh.googleusercontent.com/ML0WVmWdyLKr97zLrK2taMWqpwEA_V2-tlX8ZQF2NaBB4a85YDZ49BDjvlG9EQ-aB6o",
        "https://play-lh.googleusercontent.com/6Eb5ELRkjNQdn4kCg9wi3nPDB_YC7Oz5mGsmoSoP7d5csIoxzMx1EV8YXTO4rkKaig",
        "https://play-lh.googleusercontent.com/wIegskTArbgbZGoi6ZMWvssn0E4BSl4-0z65TdBXWn-kzrqTry_YM3hLWKJk5Jm1SQY",
        "https://play-lh.googleusercontent.com/Vkw1gHhwnGFL5H36u_3UIBQn2FXouKHWmgnALXQ8g6etvBfyVikVE_-_AwikPkEf-t6C",
        "https://play-lh.googleusercontent.com/4vZoYirAJ3jPrUjRfd211Shp9yOfzCN-XuQBNBzIFJfDGYUfbMwkrCd1yKOa4DilTeE",
        "https://play-lh.googleusercontent.com/HW2FteSn4PHBVPPXuj-vxBtPbEHbBRH04KbNBzTq19-QkfSbZe5T_qCoGyVO1uw6ZQ",
        "https://play-lh.googleusercontent.com/4nYniDKgDaGNQzQ7PrJN9krY_Zps04SG41TSM0ypoMu7zY5Ypp_19ZAVj3sNVuDF5MDw",
        "https://play-lh.googleusercontent.com/LfbbPhwYWdzrdi120ABIgEA5nE2z0qwIV2twJBz6NaLFnyVeqHyQujqUQ1U10QWvSg",
        "https://play-lh.googleusercontent.com/j9UrDuWDzafnMCCKtJYTP_AHRkctsZETbyiW5VZkr2mqGlf_MQwZVotv0V2zrBKBR0Y",
        "https://play-lh.googleusercontent.com/i648IYYcF5agRX2dMon-EnnJwP4t7OpGSvZPKeBjJ3RQQ5Tw5fJl13iNARnFG8ByXN_y"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 20, 2023",
    "lastUpdatedOn": "Oct 10, 2024",
    "updated": 1728570943,
    "version": "1.10.1",
    "comments": [],
    "appId": "org.aagrapevine.app",
    "url": "https://play.google.com/store/apps/details?id=org.aagrapevine.app&hl=en&gl=us"
}