{
    "title": "Kaiser Permanente",
    "description": "Whether you're at home or on the go, the Kaiser Permanente app gives you a simple, secure way to manage your health \u2014 all in one place.\r\n \r\nLive in Washington (outside of Vancouver/Longview)? Download the Kaiser Permanente Washington app instead. \r\n \r\nWith the Kaiser Permanente app, you can easily:\r\n\u2022 Email your doctor\u2019s office or Member Services with nonurgent questions\r\n\u2022 Schedule, view, and cancel routine appointments and see information about past visits\r\n\u2022 Fill or refill most prescriptions, check the status of a prescription order, and see a list of all your medications\r\n\u2022 View your medical history, including allergies and immunizations, ongoing health conditions, and most lab test results\r\n\u2022 Choose a doctor by browsing our online doctor profiles\r\n\u2022 Find facilities and pharmacies near you\r\n\u2022 Get care in a way that works for you \u2014 online, by phone, or in person\r\n\u2022 Access your digital membership card to check in for appointments, pick up prescriptions, and more\r\n\u2022 Get personalized reminders and health information as soon as they\u2019re available\r\n \r\nTo get started, download the app and sign in with your kp.org account. If you haven\u2019t registered yet, you can also create your online account in the app.",
    "descriptionHTML": "Whether you&#39;re at home or on the go, the Kaiser Permanente app gives you a simple, secure way to manage your health \u2014 all in one place.<br> <br>Live in Washington (outside of Vancouver/Longview)? Download the Kaiser Permanente Washington app instead. <br> <br>With the Kaiser Permanente app, you can easily:<br>\u2022 Email your doctor\u2019s office or Member Services with nonurgent questions<br>\u2022 Schedule, view, and cancel routine appointments and see information about past visits<br>\u2022 Fill or refill most prescriptions, check the status of a prescription order, and see a list of all your medications<br>\u2022 View your medical history, including allergies and immunizations, ongoing health conditions, and most lab test results<br>\u2022 Choose a doctor by browsing our online doctor profiles<br>\u2022 Find facilities and pharmacies near you<br>\u2022 Get care in a way that works for you \u2014 online, by phone, or in person<br>\u2022 Access your digital membership card to check in for appointments, pick up prescriptions, and more<br>\u2022 Get personalized reminders and health information as soon as they\u2019re available<br> <br>To get started, download the app and sign in with your kp.org account. If you haven\u2019t registered yet, you can also create your online account in the app.",
    "summary": "Managing your health made easy",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 4043191,
    "score": 4.667484,
    "ratings": 90387,
    "reviews": 15460,
    "histogram": [
        3111,
        1117,
        2647,
        8955,
        74552
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Kaiser Permanente",
    "developerId": "5463839529367662786",
    "developerEmail": "kpmobile@kp.org",
    "developerWebsite": "http://kp.org/thrive",
    "developerAddress": null,
    "privacyPolicy": "https://healthy.kaiserpermanente.org/privacy.html",
    "genre": "Health & Fitness",
    "genreId": "HEALTH_AND_FITNESS",
    "categories": [
        {
            "name": "Health & Fitness",
            "id": "HEALTH_AND_FITNESS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/51P1NROzZjnKU6sNuZGxmsjeKNzOdIFjuir82uGKCL3YCU8sK2_LCi6tWQNYy71czME",
    "headerImage": "https://play-lh.googleusercontent.com/wLb50oHrEPDCLuwpjodT6-56YYKpC1uYCVBpXaMDMX9Vtj-Nuo_Lb5LMHUjyMR7BNOFa",
    "screenshots": [
        "https://play-lh.googleusercontent.com/g0BauBdR2eYthT90FlUaVFUtNQhotR7Sq4kXEz0wNaSu963qM60wFSB0tJ4O5HdvQw",
        "https://play-lh.googleusercontent.com/uvMbHZsoWo9Da8SWxUwoN2UyHNSGVkVD9VEHUT28O1sWlSMNjtsnvsoRrW50pwhdUuA",
        "https://play-lh.googleusercontent.com/CNJT-zDOIjyzl54ck6-qOUiku7vCL48Z9ZMLRLFUdlS8EpO-ZBbATE4lpD57Bu8Bp5kl",
        "https://play-lh.googleusercontent.com/jn_jYaHVNVbGKZRmW1yWmzesNKIXmmNtqvsz-evd2cWrsjtzYubWtseocoSCP_f43k9G",
        "https://play-lh.googleusercontent.com/g1lOWOqBQDDUoruHM1wxLPHQiNDwWZqnc8DtKi83DmxCfhmlz4Lkr05BlO7suLyf4g",
        "https://play-lh.googleusercontent.com/0qOdcOelBjnplLVf9-inHF-LXaFgz0-O1MQCADBAz2Qn_VZyFt51qTiGGTyTLGszKA",
        "https://play-lh.googleusercontent.com/xPG1OJhpfvj1D5RGfMcB9Wub2gWj175DoI_aHzzs7wEUg9-KMilsnIiYWCc-yQrD-hE"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 23, 2012",
    "lastUpdatedOn": "Sep 26, 2024",
    "updated": 1727390487,
    "version": "6.6.0",
    "comments": [],
    "appId": "org.kp.m",
    "url": "https://play.google.com/store/apps/details?id=org.kp.m&hl=en&gl=us"
}