{
    "title": "Valley Metro",
    "description": "The Valley Metro app is your tool for taking transit in the metro Phoenix area. \r\n\r\nSmart Fare makes taking transit even easier \u2013 load your account, scan every time you ride and the more you ride, the more you save! You\u2019ll never pay more than the Smart Fare daily, weekly and monthly fare. \r\n\r\nTrip planning helps you get where you want to go with step-by-step navigation and real-time location for bus and light rail.  \r\n\r\nFeatures:\r\n\u2022 Load your account and scan the QR code at the purple fare reader\r\n\u2022 View your transaction history \r\n\u2022 Set up autoload or load your account with cash at select retail locations \r\n\u2022 Plan your trip with step-by-step navigation \r\n\u2022 Locate your bus or train in real time\r\n\u2022 Save your favorite stops and routes \r\n\u2022 Get service alerts and account notifications",
    "descriptionHTML": "The Valley Metro app is your tool for taking transit in the metro Phoenix area. <br><br>Smart Fare makes taking transit even easier \u2013 load your account, scan every time you ride and the more you ride, the more you save! You\u2019ll never pay more than the Smart Fare daily, weekly and monthly fare. <br><br>Trip planning helps you get where you want to go with step-by-step navigation and real-time location for bus and light rail.  <br><br>Features:<br>\u2022 Load your account and scan the QR code at the purple fare reader<br>\u2022 View your transaction history <br>\u2022 Set up autoload or load your account with cash at select retail locations <br>\u2022 Plan your trip with step-by-step navigation <br>\u2022 Locate your bus or train in real time<br>\u2022 Save your favorite stops and routes <br>\u2022 Get service alerts and account notifications",
    "summary": "The official tool for transit trips in the metro Phoenix area.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 210882,
    "score": 4.3958335,
    "ratings": 8861,
    "reviews": 900,
    "histogram": [
        778,
        204,
        409,
        799,
        6665
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "ValleyMetro",
    "developerId": "ValleyMetro",
    "developerEmail": "csr@valleymetro.org",
    "developerWebsite": "https://www.valleymetro.org/",
    "developerAddress": "101 N. 1st Avenue\nSuite 1400\nPhoenix, AZ 85003",
    "privacyPolicy": "https://www.valleymetro.org/privacy-notice",
    "genre": "Maps & Navigation",
    "genreId": "MAPS_AND_NAVIGATION",
    "categories": [
        {
            "name": "Maps & Navigation",
            "id": "MAPS_AND_NAVIGATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/prOiGlMptHbfDMRa-AJlhx8MgQL6ZEWd3fRkYsvDGjnWVhyAjFChLuV7TFRp4rHcmLE",
    "headerImage": "https://play-lh.googleusercontent.com/OR7Uo_-uSWN_5XTATnqqabM72s7_K4EeHQlc1MdgtXnAx7_jfmxDrhESdCgmAPnrO-E",
    "screenshots": [
        "https://play-lh.googleusercontent.com/2IbYhpMJGwuqLsgivJccOes3qlwYYj9wRxx_Le2PWKPBXTlX9tsJAb8O0nWpdZnMk08v",
        "https://play-lh.googleusercontent.com/981JlKW6UK-ln4sCZmHYEoawT8zsB0mPfltpcu99Br9xg2hJOzhWBSGxBxc6-H0i9YI",
        "https://play-lh.googleusercontent.com/7Lnl-HXYLdmR6PdI_lQU61hEFg4NZ7BTOwi3NzLmMe-3Ejdiyq0_jT0PCERlBuv2wZY",
        "https://play-lh.googleusercontent.com/pDb9Qwam_uGGw_4nOSNZoU3c6Q0lzogiNL_Qkf8YatBVnn1I9M5aQVI9GlPMtIaZQg",
        "https://play-lh.googleusercontent.com/dDCL-BInhKRjcvwHRJx2I0gAOChPFdfl3OvUDNSvNhia96_y949VhylJUExP6-zNdg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jun 29, 2021",
    "lastUpdatedOn": "Aug 5, 2024",
    "updated": 1722865327,
    "version": "3.0.2",
    "comments": [],
    "appId": "org.valleymetro.app",
    "url": "https://play.google.com/store/apps/details?id=org.valleymetro.app&hl=en&gl=us"
}