{
    "title": "SEPTA",
    "description": "The official SEPTA app brings our entire transit network directly to you with convenient access to schedule information, real-time updates, trip planning, fare options, social media connections, and Customer Service. This new app is perfect for customers on the go with your best SEPTA travel options right at your fingertips. We\u2019ve made some our most popular website features mobile including:\r\n\r\n*Manage your SEPTA key card(s) directly in the app.\r\n*Purchase weekly, Monthly Passes,Travel Wallet \r\n*Next to Arrive: Point to point train schedules and real-time information for trips between any two stations on our Regional Rail system\r\n* TransitView: Locate your bus, trolley, or trackless trolley and see approximately how close it is to your stop\r\n* TrainView: Your personal status report for all Regional Rail trains on the system\r\n* Schedules: Find a timetable for every bus, trolley, trackless trolley, high speed line, and regional rail line\r\n* Fares: Find the right fare option to suit your travel needs\r\n* SEPTA Connect: Link to us on Facebook, Twitter, contact Customer Service or share your feedback",
    "descriptionHTML": "The official SEPTA app brings our entire transit network directly to you with convenient access to schedule information, real-time updates, trip planning, fare options, social media connections, and Customer Service. This new app is perfect for customers on the go with your best SEPTA travel options right at your fingertips. We\u2019ve made some our most popular website features mobile including:<br><br>*Manage your SEPTA key card(s) directly in the app.<br>*Purchase weekly, Monthly Passes,Travel Wallet <br>*Next to Arrive: Point to point train schedules and real-time information for trips between any two stations on our Regional Rail system<br>* TransitView: Locate your bus, trolley, or trackless trolley and see approximately how close it is to your stop<br>* TrainView: Your personal status report for all Regional Rail trains on the system<br>* Schedules: Find a timetable for every bus, trolley, trackless trolley, high speed line, and regional rail line<br>* Fares: Find the right fare option to suit your travel needs<br>* SEPTA Connect: Link to us on Facebook, Twitter, contact Customer Service or share your feedback",
    "summary": "The SEPTA Android app.",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 571259,
    "score": 3.1835017,
    "ratings": 6307,
    "reviews": 2578,
    "histogram": [
        1751,
        711,
        689,
        933,
        2218
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Southeastern Pennsylvania Transportation Authority",
    "developerId": "Southeastern+Pennsylvania+Transportation+Authority",
    "developerEmail": "septadev@gmail.com",
    "developerWebsite": "http://www.septa.org",
    "developerAddress": null,
    "privacyPolicy": "https://www5.septa.org/privacy/",
    "genre": "Maps & Navigation",
    "genreId": "MAPS_AND_NAVIGATION",
    "categories": [
        {
            "name": "Maps & Navigation",
            "id": "MAPS_AND_NAVIGATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/lneHaMng1iDYldpbKvzRZXUfnsK1tGSOjd7DWobQgGYt18IILaGSAcCyY9AH_a3v7XU",
    "headerImage": "https://play-lh.googleusercontent.com/SGO0h-Bxuhh8dj19ljPaX1hOyWig972gWxA-IHDY3q5kxSOfcMdt5r45sXV002SJk1zA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/OWPGwgIHaXZrDHtSbFrvKIGLXB6_XgK73tmj1NwIW17w2k1h36yVoWwhMSDdfET2nQZ1",
        "https://play-lh.googleusercontent.com/wQX0kx9K59wgErQdLkv2oaGzHULvGgr6SOwy1yggc--JVDam_6KiBFGr4mc9JEqOqqw",
        "https://play-lh.googleusercontent.com/WHNrQHcJXm83KFoZCwYNGMeZ_rE4Ay7h1VS3AZjYMbAmPF8EcuQmjBD-SMk1vmtPcw",
        "https://play-lh.googleusercontent.com/CsHR5vUo6FcS7jwktAgPmKE8CVZvxat4Gl1BF4zR4LR3uJc_6FbvHMwyWZtSsKftgiQ",
        "https://play-lh.googleusercontent.com/SjbirzD08T5SHAu62uVrVDhB85mNNujLDrDoOla9DG_xbdSCLlrDVixA_8DplFHpKQ",
        "https://play-lh.googleusercontent.com/STcxl0-sE8ThNmDzg7SgrA3vIwMs9NKtXdXNSqu8BZXQYVMehqCxSwcVByM4gUbRqA",
        "https://play-lh.googleusercontent.com/-a14FwQBH3fMnNJvtn07rUS8Vmpc3bV6t3YW-uH16YThK_SpHSVIb12dolI4ga_KJhJh",
        "https://play-lh.googleusercontent.com/E1m9uEEXZIf-AJ2rvKo4Gqf61Q2AwZepQ2pr-w01E60Skreb7oLPrnLHx0ljE1ceXYI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 15, 2014",
    "lastUpdatedOn": "Oct 2, 2023",
    "updated": 1696265038,
    "version": "2.2.410-284",
    "comments": [],
    "appId": "org.septa.android.app",
    "url": "https://play.google.com/store/apps/details?id=org.septa.android.app&hl=en&gl=us"
}