{
    "title": "C-SPAN Now",
    "description": "Watch live and on demand C-SPAN's complete coverage of the House and Senate, congressional hearings, White House events, the courts, the campaigns and more from the world of politics. Listen to C-SPAN Radio and discover a variety of informative podcasts. Watch the three C-SPAN TV networks* and the latest episodes of \"Washington Journal\" and \"Q&A\". Find current schedule information for C-SPAN\u2019s TV networks and C-SPAN Radio.\r\n\r\nFrom your mobile device, on C-SPAN Now you'll find anywhere, anytime access to:\r\n\r\n\u2022\tLive streams of U.S. Congress floor proceedings\r\n\u2022\tLive streams of each day's key congressional hearings and other top political events\r\n\u2022\tOn-demand access to the latest events\r\n\u2022\tFeatured clips driving the news\r\n\u2022\tC-SPAN Radio\r\n\u2022\tPodcasts on politics, history and nonfiction books\r\n\u2022\tC-SPAN, C-SPAN2 and C-SPAN3*\r\n\u2022\tLatest episodes of \"Washington Journal\" and \"Q&A\"\r\n\u2022\tUp-to-date schedule information for C-SPAN TV networks and C-SPAN Radio\r\n\r\n*Access to the livestreams of C-SPAN's three television networks is reserved for authenticated cable and satellite TV customers.\r\n \r\nC-SPAN Now...Washington Unfiltered.",
    "descriptionHTML": "Watch live and on demand C-SPAN&#39;s complete coverage of the House and Senate, congressional hearings, White House events, the courts, the campaigns and more from the world of politics. Listen to C-SPAN Radio and discover a variety of informative podcasts. Watch the three C-SPAN TV networks* and the latest episodes of &quot;Washington Journal&quot; and &quot;Q&amp;A&quot;. Find current schedule information for C-SPAN\u2019s TV networks and C-SPAN Radio.<br><br>From your mobile device, on C-SPAN Now you&#39;ll find anywhere, anytime access to:<br><br>\u2022\tLive streams of U.S. Congress floor proceedings<br>\u2022\tLive streams of each day&#39;s key congressional hearings and other top political events<br>\u2022\tOn-demand access to the latest events<br>\u2022\tFeatured clips driving the news<br>\u2022\tC-SPAN Radio<br>\u2022\tPodcasts on politics, history and nonfiction books<br>\u2022\tC-SPAN, C-SPAN2 and C-SPAN3*<br>\u2022\tLatest episodes of &quot;Washington Journal&quot; and &quot;Q&amp;A&quot;<br>\u2022\tUp-to-date schedule information for C-SPAN TV networks and C-SPAN Radio<br><br>*Access to the livestreams of C-SPAN&#39;s three television networks is reserved for authenticated cable and satellite TV customers.<br> <br>C-SPAN Now...Washington Unfiltered.",
    "summary": "Your front row seat at the day's biggest political events & policy discussions.",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 140800,
    "score": 3.88,
    "ratings": 829,
    "reviews": 350,
    "histogram": [
        131,
        74,
        57,
        57,
        504
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "National Cable Satellite Corporation",
    "developerId": "National+Cable+Satellite+Corporation",
    "developerEmail": "online@c-span.org",
    "developerWebsite": "https://www.c-span.org",
    "developerAddress": null,
    "privacyPolicy": "https://www.c-span.org/about/privacy/",
    "genre": "News & Magazines",
    "genreId": "NEWS_AND_MAGAZINES",
    "categories": [
        {
            "name": "News & Magazines",
            "id": "NEWS_AND_MAGAZINES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/AbjjLNzNbOf7utXurW6_u0uPe_FDNPKI2Un4RaIYZrsTDSXz6pzIZGUS7mdq2iD1dk-e",
    "headerImage": "https://play-lh.googleusercontent.com/J3xxj5zMWKuqSvaHbIRYlLPGU5QWM05w9frxeIAwOfJfEFY2XGzx20VP3gT3fvwTjuA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/0KvpbDwyOKDX80nGN5Eu-K2dLMpiA4hhKg7A1D8-dfya0I5RGDDbfPcozU38Iou-tm0",
        "https://play-lh.googleusercontent.com/ppfd_1R5MMRLlL1hvUOJTfupLc75jKoTU_t5V0YNzf7O7N-IrpnHnN-j7lM-ii6q8g",
        "https://play-lh.googleusercontent.com/uhRelpWxi8oWO6OJ2oUr_oM0Ocn4X2ryVhHvWlrTVFpWF8oewxFejQKU-UnzWV78M6s",
        "https://play-lh.googleusercontent.com/4NwQ863BhyggkitEUkdS4oHBLYOLPfsYx0rxFGBmIX6VdRjShR5C0LN97mYxZk7M-rdI",
        "https://play-lh.googleusercontent.com/kWnErUUgw0oue_ubLGav8PXavWFUUiYIuSHKPZxc8dIoF_lI7mT1XUf7Bl6Ml2B70Dx7"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Sep 24, 2021",
    "lastUpdatedOn": "Sep 27, 2024",
    "updated": 1727492110,
    "version": "1.23.2",
    "comments": [],
    "appId": "org.cspan.app",
    "url": "https://play.google.com/store/apps/details?id=org.cspan.app&hl=en&gl=us"
}