{
    "title": "Watch Duty (Wildfire)",
    "description": "Watch Duty is the only wildfire mapping and alert app powered by real people giving you real-time information vetted by trained professionals, not robots. While many other apps rely solely on government alerts, which can often be delayed, Watch Duty provides up-to-the-minute, life-saving information through a dedicated team of active and retired firefighters, dispatchers, first responders, and reporters who monitor radio scanners around the clock. We aim to keep you informed and safe with real-time updates and alerts.\r\n\r\nWildfire Tracking Features:\r\n\r\n- Push notifications about nearby wildfires and firefighting efforts\r\n- Real-time updates as conditions change\r\n- Active fire perimeters and progress\r\n- Infrared satellite hotspots from VIIRS and MODIS\r\n- Wind speed and direction\r\n- Evacuation orders & shelter information\r\n- Historical wildfire perimeters\r\n- Street and satellite maps\r\n- Air attack and air tanker flight tracker\r\n- Save locations for quick access on the map\r\n\r\nWatch Duty is a 501(c)(3) non-profit organization. Our service will always remain free of charge and free of advertising or sponsorship. You can support our mission with a $25/year membership, which grants access to special features as a token of our appreciation.\r\n\r\nDisclaimer: Watch Duty is not affiliated with any government agency. The information provided in this app is sourced from publicly available and trusted sources, including but not limited to government agencies, radio transmissions, and satellite data. Specific government sources include:\r\n\r\n- National Oceanic and Atmospheric Administration (VIIRS, MODIS)\r\n- National Interagency Fire Center (NIFC) \r\n- California Department of Forestry and Fire Protection (CAL FIRE)\r\n- California Governor's Office of Emergency Services (Cal OES)\r\n\r\nFor more information or support, feel free to contact us at support.watchduty.org.\r\n\r\nPrivacy Policy: https://www.watchduty.org/legal/privacy-policy",
    "descriptionHTML": "Watch Duty is the only wildfire mapping and alert app powered by real people giving you real-time information vetted by trained professionals, not robots. While many other apps rely solely on government alerts, which can often be delayed, Watch Duty provides up-to-the-minute, life-saving information through a dedicated team of active and retired firefighters, dispatchers, first responders, and reporters who monitor radio scanners around the clock. We aim to keep you informed and safe with real-time updates and alerts.<br><br>Wildfire Tracking Features:<br><br>- Push notifications about nearby wildfires and firefighting efforts<br>- Real-time updates as conditions change<br>- Active fire perimeters and progress<br>- Infrared satellite hotspots from VIIRS and MODIS<br>- Wind speed and direction<br>- Evacuation orders &amp; shelter information<br>- Historical wildfire perimeters<br>- Street and satellite maps<br>- Air attack and air tanker flight tracker<br>- Save locations for quick access on the map<br><br>Watch Duty is a 501(c)(3) non-profit organization. Our service will always remain free of charge and free of advertising or sponsorship. You can support our mission with a $25/year membership, which grants access to special features as a token of our appreciation.<br><br>Disclaimer: Watch Duty is not affiliated with any government agency. The information provided in this app is sourced from publicly available and trusted sources, including but not limited to government agencies, radio transmissions, and satellite data. Specific government sources include:<br><br>- National Oceanic and Atmospheric Administration (VIIRS, MODIS)<br>- National Interagency Fire Center (NIFC) <br>- California Department of Forestry and Fire Protection (CAL FIRE)<br>- California Governor&#39;s Office of Emergency Services (Cal OES)<br><br>For more information or support, feel free to contact us at support.watchduty.org.<br><br>Privacy Policy: https://www.watchduty.org/legal/privacy-policy",
    "summary": "Wildfire Maps & Alerts",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 831447,
    "score": 4.7915196,
    "ratings": 5594,
    "reviews": 1944,
    "histogram": [
        88,
        39,
        88,
        513,
        4862
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Watch Duty",
    "developerId": "Watch+Duty",
    "developerEmail": "feedback@watchduty.org",
    "developerWebsite": "https://www.watchduty.org",
    "developerAddress": null,
    "privacyPolicy": "https://www.watchduty.org/legal/privacy-policy",
    "genre": "Communication",
    "genreId": "COMMUNICATION",
    "categories": [
        {
            "name": "Communication",
            "id": "COMMUNICATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/pOv2fLe_FQmWgtLFz_XuhIfLf4DzlhR7a9X1aRcTeAtv3e7VKAONNyvpOUN65n4o_w",
    "headerImage": "https://play-lh.googleusercontent.com/XR3ZLo-QrYo7hMCvibPPIyvzSYjx8ObyMDf7_irjYBo4C_v03K_qyuRaDc2eVMHQLys",
    "screenshots": [
        "https://play-lh.googleusercontent.com/YK5x6B5beeP5VA7H42F6ikAIVkWMlCTKOWWhz2ahPOioxz1scTZ9Qs_NAGuaVkm-v0c",
        "https://play-lh.googleusercontent.com/viIc3H2Yl8v-eKSocNsvCiL9vdfdyzPI-iLxqbq6BK9beC1rBp8XsMv_9uO6i6adQQ",
        "https://play-lh.googleusercontent.com/z8x-rM7nDkd0aiuz8883M8cn_clrhfoO4wA9tn2mD0xuI00e9I6CscU9E1yFDM-F6B8b",
        "https://play-lh.googleusercontent.com/_YVN4SemujSOxXqftJAvFShKBnx2BNdSlJ1Lto7Z6CThAfkNC7hjugV1MsrqExQa1g0",
        "https://play-lh.googleusercontent.com/vAxaDG8Zcfe6Fvw-f7ZeAbb8YCgHNg0MQK49jFGJ5Y7KriXTDeL9gmk5MVBxGkyIRg",
        "https://play-lh.googleusercontent.com/ThQbUh6uiBvo1aKmt_aXeXrph-AyjspQ2fh3JbaHVgaFViZCmyOHhADoJdjL6xtQRL8",
        "https://play-lh.googleusercontent.com/PIs7rIbUPgCSKl_gzZ3d4r57LdO2yjsTkUyE5CTd_B5P6by3-IZxyX37dXNRMMqeCg",
        "https://play-lh.googleusercontent.com/T0xgbym8NyNybUseS-q1XkcZ_7X2eFhX_xzPLhtKcsyBPzML8xX9D5F7GPBCZHey2HQ",
        "https://play-lh.googleusercontent.com/ZQDyY4HoVn9OY2_N6C27wG57wxW7TmuwkKNGRFIAYvbtJFENX_mruaVZbVqUubUFInkm",
        "https://play-lh.googleusercontent.com/1V4KBGoDpk9MMw54_RPTG2bZt8Gw5F0Sfp8zpRAKbPt64DlPPPzg2eyITZzMf5lWShs",
        "https://play-lh.googleusercontent.com/zMB7ywYkkjmr3-2S-bC2v71FYO7Jdv1EGvnPo0ckgBR6ax8pZAZTqCliKImUE0tcHbg",
        "https://play-lh.googleusercontent.com/cegaPlb_RNt1hw9X0-Os4c07-kFlgfSX7iX1lYDTicZl-16IBTLtl-QFB8N5_Q05nG0",
        "https://play-lh.googleusercontent.com/Okv8Pjb_gHpAa-b25dyshHgM5v86JcTVUpMoHDemRQdYyTzCWGJOBTnNRwa2I5R3o5s"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Aug 3, 2021",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729639848,
    "version": "2024.10.22",
    "comments": [],
    "appId": "org.watchduty.app",
    "url": "https://play.google.com/store/apps/details?id=org.watchduty.app&hl=en&gl=us"
}