{
    "title": "The Wonder Weeks - Leaps",
    "description": "The world\u2019s No. 1 baby app! Understand why your baby cries more at certain times, isn't himself or herself and... what you can do to help.\r\n\r\nDuring our research, which began in 1971 with Jane Goodall and the chimpanzees in Tanzania, we discovered that babies are more prone to cry and to be clingy or cranky from time to time. This behavior was shown to be related to a leap in the baby's mental development. More specifically, babies go through 10 mental leaps in the first 20 months of their life. A leap may be tough, but it's a positive thing: it gives your baby the opportunity to learn something new.\r\n\r\nUse The Wonder Weeks app to:\r\n- See when a leap starts and ends thanks to a personalized leap schedule\r\n- Be automatically notified when a leap is about to start\r\n- Learn to recognize the leaps based on the various signals your baby gives \r\n- Discover the new skills your baby develops with each leap\r\n- Stimulate your baby's new skills with 77 playtime games\r\n- Keep track of your baby's development in your personal diary\r\n- Link the app to your partner's app to keep track of your baby's developments together\r\n- Share your experiences and ask questions in the forum\r\n- Watch fun and interesting videos about parenting\r\n- Complete fun polls and find out what other parents think about certain topics\r\n- Benefit from a baby monitor with 4G wireless connectivity, including interesting information about sleeping patterns.\r\n\r\nOur mission is to help parents gain confidence in the face of the greatest leap in life: having a baby. We take a candid look at parenting, shed light on all sides and are there for all parents. We can all help each other and learn from each other.\r\n\r\nMillions of parents before you have already followed, supported and stimulated the 10 leaps in the mental development of their babies. It's not a coincidence that we have been one of the best-selling baby apps worldwide for many years!\r\n\r\nDisclaimer: This app has been developed with utmost care. Neither the developer nor the author is liable for any damage resulting from inaccuracies or omissions in this app.",
    "descriptionHTML": "The world\u2019s No. 1 baby app! Understand why your baby cries more at certain times, isn&#39;t himself or herself and... what you can do to help.<br><br>During our research, which began in 1971 with Jane Goodall and the chimpanzees in Tanzania, we discovered that babies are more prone to cry and to be clingy or cranky from time to time. This behavior was shown to be related to a leap in the baby&#39;s mental development. More specifically, babies go through 10 mental leaps in the first 20 months of their life. A leap may be tough, but it&#39;s a positive thing: it gives your baby the opportunity to learn something new.<br><br>Use The Wonder Weeks app to:<br>- See when a leap starts and ends thanks to a personalized leap schedule<br>- Be automatically notified when a leap is about to start<br>- Learn to recognize the leaps based on the various signals your baby gives <br>- Discover the new skills your baby develops with each leap<br>- Stimulate your baby&#39;s new skills with 77 playtime games<br>- Keep track of your baby&#39;s development in your personal diary<br>- Link the app to your partner&#39;s app to keep track of your baby&#39;s developments together<br>- Share your experiences and ask questions in the forum<br>- Watch fun and interesting videos about parenting<br>- Complete fun polls and find out what other parents think about certain topics<br>- Benefit from a baby monitor with 4G wireless connectivity, including interesting information about sleeping patterns.<br><br>Our mission is to help parents gain confidence in the face of the greatest leap in life: having a baby. We take a candid look at parenting, shed light on all sides and are there for all parents. We can all help each other and learn from each other.<br><br>Millions of parents before you have already followed, supported and stimulated the 10 leaps in the mental development of their babies. It&#39;s not a coincidence that we have been one of the best-selling baby apps worldwide for many years!<br><br>Disclaimer: This app has been developed with utmost care. Neither the developer nor the author is liable for any damage resulting from inaccuracies or omissions in this app.",
    "summary": "The 10 leaps in the mental development of your baby",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 124535,
    "score": 3.0285714,
    "ratings": 702,
    "reviews": 40,
    "histogram": [
        300,
        40,
        20,
        20,
        320
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $34.99 per item",
    "developer": "The Wonder Weeks",
    "developerId": "The+Wonder+Weeks",
    "developerEmail": "support.android@thewonderweeks.com",
    "developerWebsite": "https://support.thewonderweeks.com",
    "developerAddress": "Sint Walburgisplein 45\n6811 BZ Arnhem\nThe Netherlands",
    "privacyPolicy": "https://www.thewonderweeks.com/privacy-statement-customers-and-website-visitors-2/",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/Tpudi9GADeoasPdyJb6KVYPxKrErPaz9Cn-bc2AkyJvv_l01eih_HgABmwJXYUv2OmLb",
    "headerImage": "https://play-lh.googleusercontent.com/ZowGuIlK6xGIWbUzMAXyieHZqD64GU9EKVC9lD607XDgOOBo3dNVAGkOxvMWKxZcKik",
    "screenshots": [
        "https://play-lh.googleusercontent.com/SZ6HEBKjm2FkO4ehURRPxnQnFlra6snnxVL9NvT0_pFSkoVIdsVHdxBSergS0tRcJg",
        "https://play-lh.googleusercontent.com/lLqkLBDty5jn-GoXPOrGQYPGT9W68beeOx13B2wb7T8itLJVJbjaIVlqFZYQII2e5g",
        "https://play-lh.googleusercontent.com/ByxILAK_DQyh3ikw9hLdQ5n3edYfFpN3wBa3wHjMh7I6Jg0tt594lxA7_n4QeuXvTg",
        "https://play-lh.googleusercontent.com/aT7SpGKgeF1IewzXHbkpAwqTOjlheLqAXngzoYx2mecV5wV-s6qpBacT6o9fTkH4LiM",
        "https://play-lh.googleusercontent.com/eyE_NECV1OnlyR3_iGBmk5ZHRrCvxrnlUkWdR28diI7-cVOg06yNcVb8n_eExt0GO2P6",
        "https://play-lh.googleusercontent.com/nobmDJp8KieS15paWjkYoad7Gde3aSfmFtSSidGWSZ78F6Q7t7ipsY0awebVuBbfjD0",
        "https://play-lh.googleusercontent.com/bkXEJ6JcYMcl04hlOJCYzGR3fDi9r2WA37-WZSdzweSBc0_VSN3t4SC76XwqnnRbnQ",
        "https://play-lh.googleusercontent.com/4QbRWOaE8WTZbmXoTaWNBNpujaO6Q9ppmkaW5Re-Fx5pERQ-Gp92X8Yylq0ZUpjgWqE",
        "https://play-lh.googleusercontent.com/6QhAWGUkWuPngtlf0xklFWDjZcMlYXys5bqcL6ThiQ6Qn2WdmWeTSL_qpZlMHDS4waB_",
        "https://play-lh.googleusercontent.com/B0TTdbFtRpgI_oxjKn6neDIIrS8KtBmiQ8wFh7pSpNnA1XjsQYdJxnrbtSjaGEB9UxTl",
        "https://play-lh.googleusercontent.com/WjLx28HT3ARyM4FMUH-vrhltxXvzrPdvW41LKyXUUCwqKQOlxJ9boA140eo1TN5qLFY",
        "https://play-lh.googleusercontent.com/Y8V2tdDIhCU05x-k8-TESdByEuYldiT_oImSCWlTYuCTejB60BpvmJWGbIkIySGuERk",
        "https://play-lh.googleusercontent.com/Zfr4ivfLrW3x7NaDRmnrqmotxFUU3F54RE7snkxTK_oZi7LfRDZEGXW1WCy4ral6sk0",
        "https://play-lh.googleusercontent.com/bhJXQulsOT0ZudTteNVxTDZvv3wZy6S6BBfcOYO4aWgIjZDRMdEkGjXgx5De9re7uJCh",
        "https://play-lh.googleusercontent.com/DdD7QkBWRCNMxNOqeMEN5VZyaUf8St0mtxgxjv-VCu0p6KlPWy3yU9R7UHbU4Jyse8o",
        "https://play-lh.googleusercontent.com/ugnIyL2YjVKtdCm593xLV3wQF68YJFUGhorzQat2kdq3oCrhBjmm5df5xHeQg8M5pA",
        "https://play-lh.googleusercontent.com/J2CXchlgS1vU7f3upufLOXKM50pC8A-HnRrUuGJ6a5I96Z38RbpICA-voimRB6hyAv8",
        "https://play-lh.googleusercontent.com/27g3GAn29APPSxMSgd31KNGl7usjFR96x5fnr-TXp7XgetOTcf2TvEZ7OyXe7BAiegQ",
        "https://play-lh.googleusercontent.com/-_5ueAgVFen-V0V7XgNSyCqsep-maUG7uvRtHgfbL9InM8Z27Ukj4DckHAnrgYYiGr0",
        "https://play-lh.googleusercontent.com/PlPeVCrRuGbWiiegxO-k8X-hA-URIYM1FhVXqXYZ6HwF4LE-POklKOI1CsVlDQQHnPw3",
        "https://play-lh.googleusercontent.com/VZCsfR1IQCx2Fu14IhGv1BtCpGeB7TTjP_ki-qBUopL76YD0kYIB0Jlni8Y6xFG31ag",
        "https://play-lh.googleusercontent.com/FyDOAqBtO33nDXcYEX3bYjheNHPKY1o-d8cMMJQYpN0zekC8XcMIlP7rgYHG-_6A_w",
        "https://play-lh.googleusercontent.com/57FUwfLEdqkyDCXH5ND_p4emOKwd84QPJY_mgqGNd1FODNtJ4BD78fDkY0i0d-z1pns",
        "https://play-lh.googleusercontent.com/7VHVu4S56A_maCJiM2UbXGIGmHBuztCzu207_OB1BQrmEFC43BFzMYaCaeIb4ZtNqaI"
    ],
    "video": "https://www.youtube.com/embed/IrOntiD6SIo?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/ZowGuIlK6xGIWbUzMAXyieHZqD64GU9EKVC9lD607XDgOOBo3dNVAGkOxvMWKxZcKik",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jul 4, 2024",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729153108,
    "version": "1529 (12.1.7)",
    "comments": [],
    "appId": "org.twisevictory.apps.ex",
    "url": "https://play.google.com/store/apps/details?id=org.twisevictory.apps.ex&hl=en&gl=us"
}