{
    "title": "Spin - Electric Scooters",
    "description": "Spin is reimagining the way people and cities flow by offering shared electric micro-mobility options as an alternative to traditional forms of urban transport. We are committed to being the best possible partner for cities while building the safest, most equitable, and most sustainable mobility solution for the communities we serve. Just download our easy-to-use, reliable app for access to thousands of shared scooters and bikes across the country. Spin scooters and bikes are emissions-free, so you\u2019ll also help keep the air fresh every time you ride.\r\n\r\nHow to Take a Spin:\r\n\r\n- Open the app to find the nearest Spin scooter or bike.\r\n- Unlock your Spin by scanning the QR code or by entering its ID.\r\n- Ride safely to your destination, using bike lanes where available.\r\n- Park responsibly, avoiding pedestrian right of ways, building entrances, and wheelchair ramps.\r\n- Provide Bluetooth permissions to connect to vehicles to capture location data in the background to send to our servers for city compliance requirements\r\n\r\nWant Spin scooter or bike-sharing where you live for your commute? Have feedback on your ride? Contact support@spin.pm, or find more info at www.spin.app\r\n\r\nCalifornia Privacy Notice: https://www.spin.app/policies/ca-privacy-policy\r\nTerms of Use: https://www.spin.app/policies/terms-us",
    "descriptionHTML": "Spin is reimagining the way people and cities flow by offering shared electric micro-mobility options as an alternative to traditional forms of urban transport. We are committed to being the best possible partner for cities while building the safest, most equitable, and most sustainable mobility solution for the communities we serve. Just download our easy-to-use, reliable app for access to thousands of shared scooters and bikes across the country. Spin scooters and bikes are emissions-free, so you\u2019ll also help keep the air fresh every time you ride.<br><br>How to Take a Spin:<br><br>- Open the app to find the nearest Spin scooter or bike.<br>- Unlock your Spin by scanning the QR code or by entering its ID.<br>- Ride safely to your destination, using bike lanes where available.<br>- Park responsibly, avoiding pedestrian right of ways, building entrances, and wheelchair ramps.<br>- Provide Bluetooth permissions to connect to vehicles to capture location data in the background to send to our servers for city compliance requirements<br><br>Want Spin scooter or bike-sharing where you live for your commute? Have feedback on your ride? Contact support@spin.pm, or find more info at www.spin.app<br><br>California Privacy Notice: https://www.spin.app/policies/ca-privacy-policy<br>Terms of Use: https://www.spin.app/policies/terms-us",
    "summary": "Shared electric scooters",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2473796,
    "score": 4.795138,
    "ratings": 40264,
    "reviews": 14766,
    "histogram": [
        1121,
        142,
        538,
        2253,
        36204
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "Spin Inc.",
    "developerId": "Spin+Inc.",
    "developerEmail": "support@spin.pm",
    "developerWebsite": "https://spin.pm",
    "developerAddress": null,
    "privacyPolicy": "https://www.spin.app/policies/ca-privacy-policy",
    "genre": "Travel & Local",
    "genreId": "TRAVEL_AND_LOCAL",
    "categories": [
        {
            "name": "Travel & Local",
            "id": "TRAVEL_AND_LOCAL"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/qnT-ePbdRQhAdpesDDKtwQM8wwA3S_yeOQ7wcITWBxrDLD67NR_114rhYssbs3Uo5rW0",
    "headerImage": "https://play-lh.googleusercontent.com/mO8fTQ9EzWgNPNKVy5ciHEiUXUEIoKELvkFAYtzSQKmKD7y9UEmf4sIZcf0rg9n_XRk",
    "screenshots": [
        "https://play-lh.googleusercontent.com/J_LhS-NL1hxk1gU-Dqhp9CSewWUJXaflMk0jE1lMRxSVePvSSPwgQJrrZ_mWymRIFyI",
        "https://play-lh.googleusercontent.com/cMyM__e7CIStyBrjS8_uqLEgfDwOvCKWGfOsg_T4oPScfahPzUJDF_fkoV-S_ZPXJ5Y",
        "https://play-lh.googleusercontent.com/FGk8q2IUPOew9wIcz7BYTnKzN8oEM82XWRJE1jjSMzabu1BZksNWhx9Hl8WofPtmcVQ",
        "https://play-lh.googleusercontent.com/RsLSywaIIkYGrzhLaBCLjSMr_cxZqlGR-DRVP2wqEmaMHgjyCnZdgcvCebot2-MSJQk",
        "https://play-lh.googleusercontent.com/fTF4OnsXW91dWZNSzngKmo8WZRdD7XRaru7JGveWJ7-DMhFamjkUYK6DJdUgCZS_2k8",
        "https://play-lh.googleusercontent.com/l-7MuOf9mJNG-rltCVvKU7n1iI8WEk-xY-ITae25GXjXnnBKo8agiqGpjfP2ZWRdVUXe"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "May 28, 2017",
    "lastUpdatedOn": "Oct 21, 2024",
    "updated": 1729522144,
    "version": "4.315.1.10",
    "comments": [],
    "appId": "pm.spin",
    "url": "https://play.google.com/store/apps/details?id=pm.spin&hl=en&gl=us"
}