{
    "title": "Pixel Coloring-Color by number",
    "description": "Pixel Coloring is a good way to relax! Happy sandbox pixel art games.\r\n\r\nOur coloring book is a great art therapy sandbox to use when you feel anxious and stressed. You are in total control: you choose what to color by number, where to do it, and when to start or finish. There\u2019s no time limit or competition breathing down your neck. Just take your phone and enjoy coloring games. Play paint by number games and relax anywhere, anytime!\r\n\r\nDesigned by gaming experts and loved by players worldwide, Pixel Art coloring games help you dive into a world of coloring meditation. Choose from a wide range of fascinating artworks and paint by number while having fun!\r\n\r\nWhy play this game?\r\n\r\n\u2714 Coloring by number is simple. Browse pictures, then just tap a color number, and start painting the image. You will always know what color to use and where while playing Pixe coloring games.\r\n\r\n\u2714 More than 1000 images to choose from. Color by number mandala pictures, flowers, and tons of other topics. Our coloring pages range from easy to very detailed and suit any taste and mood.\r\n\r\n\u2714 New pictures to paint by number every day. Discover new number coloring images on a daily basis, and you\u2019ll never run out of free pictures to color!\r\n\r\n\u2714 Paint by number unique images during Seasonal Events! Color by number thematic pictures and get unique bonuses. Our images are specially crafted for major seasons, holidays and festivals. Build your own collection of images from popular coloring topics, such as Christmas, Halloween, Thanksgiving, and many more.\r\n\r\n\u2714 import or shoot your own pictures to create your pixel masterpieces! Color by number all your photos for free with our pixel art maker!\r\n\r\n\u2714 Share time-lapse videos with just one tap. Show everyone you\u2019re into painting games!\r\n\r\nWhenever you want to relax, just open Paint by Number - Pixel Art.         You will find so many fascinating pictures like ice creams, unicorns, flowers\r\n\r\nIf you want to find a pixel-style coloring game to kill time and relax, Paint by Number - Pixel Art serves as a good choice!\r\n\r\nDownload and draw your pixel coloring art right now!",
    "descriptionHTML": "Pixel Coloring is a good way to relax! Happy sandbox pixel art games.<br><br>Our coloring book is a great art therapy sandbox to use when you feel anxious and stressed. You are in total control: you choose what to color by number, where to do it, and when to start or finish. There\u2019s no time limit or competition breathing down your neck. Just take your phone and enjoy coloring games. Play paint by number games and relax anywhere, anytime!<br><br>Designed by gaming experts and loved by players worldwide, Pixel Art coloring games help you dive into a world of coloring meditation. Choose from a wide range of fascinating artworks and paint by number while having fun!<br><br>Why play this game?<br><br>\u2714 Coloring by number is simple. Browse pictures, then just tap a color number, and start painting the image. You will always know what color to use and where while playing Pixe coloring games.<br><br>\u2714 More than 1000 images to choose from. Color by number mandala pictures, flowers, and tons of other topics. Our coloring pages range from easy to very detailed and suit any taste and mood.<br><br>\u2714 New pictures to paint by number every day. Discover new number coloring images on a daily basis, and you\u2019ll never run out of free pictures to color!<br><br>\u2714 Paint by number unique images during Seasonal Events! Color by number thematic pictures and get unique bonuses. Our images are specially crafted for major seasons, holidays and festivals. Build your own collection of images from popular coloring topics, such as Christmas, Halloween, Thanksgiving, and many more.<br><br>\u2714 import or shoot your own pictures to create your pixel masterpieces! Color by number all your photos for free with our pixel art maker!<br><br>\u2714 Share time-lapse videos with just one tap. Show everyone you\u2019re into painting games!<br><br>Whenever you want to relax, just open Paint by Number - Pixel Art.         You will find so many fascinating pictures like ice creams, unicorns, flowers<br><br>If you want to find a pixel-style coloring game to kill time and relax, Paint by Number - Pixel Art serves as a good choice!<br><br>Download and draw your pixel coloring art right now!",
    "summary": "Color by number, pixel art game and relaxing sandbox pixel art coloring book",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1096281,
    "score": 4.622807,
    "ratings": 2566,
    "reviews": 151,
    "histogram": [
        133,
        65,
        42,
        133,
        2182
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $69.99 per item",
    "developer": "Coloring Game Studio@RabiGame",
    "developerId": "6020844897578981302",
    "developerEmail": "support@rabigame.com",
    "developerWebsite": "https://pixel.rabigame.com",
    "developerAddress": "RabiGame Studio, Wang Fai Industrial Building, 29 LUK HOP Street, SAN PO KONG, KOWLOON, HONG KONG",
    "privacyPolicy": "https://pixel.rabigame.com/privacy.html",
    "genre": "Board",
    "genreId": "GAME_BOARD",
    "categories": [
        {
            "name": "Board",
            "id": "GAME_BOARD"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/HcJeqdSzR9nDwiO2oCDN1ZhW1Ix3c4l4BH7fbBNKPU2dUZwo4879LpAeL6J4oZqQB1E",
    "headerImage": "https://play-lh.googleusercontent.com/5IQahMi0muNG5EuXAk-sbmFLIcvx-k-tqyZ_WFYJpj5Asu7BaQXpH4Kh6sr-1C15oBTw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/8pu6qb_U-eI0ECJvZ0uRQSshxu4eGNrJ8A_2yv7g8cRYStLxKpIID0CnStJ6my614yQ",
        "https://play-lh.googleusercontent.com/PJObN9Dc-WUSX5_q8iGlviP0fnqtWBSmrwQgLHDPIukhqkA14PAqbS2VFQzoAfIhHus",
        "https://play-lh.googleusercontent.com/OHo1h4Sk8t5RjLTOVcl1jLPHcdfvKsKrLVOiqRrHFORH5y3dj4jw-PKA9D2BvATtMA",
        "https://play-lh.googleusercontent.com/J3Ll6Q7I6KM2QqOE0PL11Up6YDfH2uGFLmnP1x6xh6S8fVlcEGQfMUahf1Wh_t55Zg",
        "https://play-lh.googleusercontent.com/PDxPkwbux7uO5nLXkEaLeepBZgastTUv75cjQXmWLBVGM_RdE1eVCDcKgmjyq9lfBKy5",
        "https://play-lh.googleusercontent.com/MvI-Y4VHvv8Q2Mfx85q9ySwP19iu-Joem1H-7jTIQ539thg0EZAqR0RLW0NrgZeECE-R",
        "https://play-lh.googleusercontent.com/8mRDqQS2rF_-Hlm1XTuPZp8TaKBLBC9CcV-K9e5omynufWYZhx6QYP5TzK0McxZjfKQh",
        "https://play-lh.googleusercontent.com/XjAVLNiWaM-oU4ciRq7lEdQr_H9obknS8clrmncanGRnW9An_RSZiKqQO2EUhqMlhg",
        "https://play-lh.googleusercontent.com/CO9iNcpzUWUyHXl67TeqqM7wRlJF7ai8chpeOSRlkas-RA-hrqf8Tk1ZWQ9WRqji7Kg",
        "https://play-lh.googleusercontent.com/EcE4hSvTr9tfTQdgSY0PDi5hezsAKNfQxx5wyX_6bsdsacdYaNmsXgnDrpscYSVysg",
        "https://play-lh.googleusercontent.com/99QNfl8wmSjgHj9pIocv_qdNqyc2WuVrxmpsZDKyqQ1-9O2vqH35kzCeRz-vtOiReA",
        "https://play-lh.googleusercontent.com/ySFMyxFukMtoghzAJ3wMHASxB_o0IKvIoXG9U4g32tTbjoaPkhZHf3dnnrR7mjsRLec",
        "https://play-lh.googleusercontent.com/CUuwGZ-Sah5ligKJYmgCXdRm3SIuogOxzNUk2hCWXuCScXsSyfuqpQMXT6N2biebXws",
        "https://play-lh.googleusercontent.com/RdyBx0n32SpEsCgHQKzO6qDCXHXfdbJOLXwvoBAr7-e61HJTdNuyj9d23nsBi5Dml2Q",
        "https://play-lh.googleusercontent.com/OfWV68qJe-yNd6gTTEx2X7EEw38omsOzUCSHN8jNqOcxCPkHSxXx_vXRklWhm1EhOBc",
        "https://play-lh.googleusercontent.com/Pp5m6Vk7lrZHo1_rJToaPXH6nKGw34GCs6YAL7C7qu3LRT29NxijvV-VxrPWbJbUnng",
        "https://play-lh.googleusercontent.com/_sOGPLn7zEFCy8my_upgnRHV4w7dDibqN06seicPJxq4HVLBp5c8p3s_JnRMVYh37Q",
        "https://play-lh.googleusercontent.com/CZ9PcRwlX_IoY8KguWGkaF7IHb05tN047f9nckhk80UanbNZUoclxHkTFOGmzRezAQ",
        "https://play-lh.googleusercontent.com/dkY3bux_ElL8z612Ud_3JbwSvKaaN0ZpK8pGm4aAW_NGU6GUG7hzN5YDa51MdrCNtpo",
        "https://play-lh.googleusercontent.com/FsyajR0bTAfx0C_vNCbMCTj7pJaPstSM7gSIrmZT_jTQDJEDykT4BCZYtxefYzWIqw",
        "https://play-lh.googleusercontent.com/kHoyckm6sfGDPPKG_QxByBd0PlHIfvs_iwRcWN4S7S4OfuSFsjealW80wtHIMCjiD7yy",
        "https://play-lh.googleusercontent.com/i2aDrKy1rxA0BybCiWOfxz2gcIrpsbFUFs1v_EUfySa3OMLjkrG7Av5NMSbp0z34OQ",
        "https://play-lh.googleusercontent.com/OjfBilGU5IIZwrSydR8iBrQ2hHLSgPotKnvXi1Yla2F0hmApwow4nqPyJ94J5n8qwQPs",
        "https://play-lh.googleusercontent.com/g3-94EZ8213YF1oZUp3r36nDVwpw9JA4cB4e6KJa2yytvINM0C35Xvvz3FnqJ6La7sY"
    ],
    "video": "https://www.youtube.com/embed/vGoV6tBgeYI?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/5IQahMi0muNG5EuXAk-sbmFLIcvx-k-tqyZ_WFYJpj5Asu7BaQXpH4Kh6sr-1C15oBTw",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 24, 2023",
    "lastUpdatedOn": "Oct 17, 2024",
    "updated": 1729148692,
    "version": "1.35.3",
    "comments": [],
    "appId": "puzzle.pixel.art.coloring.drawing.sandbox.free.painting.games.kids.adults.fun",
    "url": "https://play.google.com/store/apps/details?id=puzzle.pixel.art.coloring.drawing.sandbox.free.painting.games.kids.adults.fun&hl=en&gl=us"
}