{
    "title": "ReelSage",
    "description": "Become a true film connoisseur with ReelSage. Dive into a vast collection of cinematic masterpieces, curated by our experts. Discover hidden gems, indulge in classics, and let your film knowledge soar.\r\n\r\nThis APP only provides video introduction and trailer, does not provide playback function, and has no copyright risk.\r\nAll data comes from the open API of TMDB.",
    "descriptionHTML": "Become a true film connoisseur with ReelSage. Dive into a vast collection of cinematic masterpieces, curated by our experts. Discover hidden gems, indulge in classics, and let your film knowledge soar.<br><br>This APP only provides video introduction and trailer, does not provide playback function, and has no copyright risk.<br>All data comes from the open API of TMDB.",
    "summary": "Unleash Your Inner Film Guru",
    "installs": "100,000+",
    "minInstalls": 100000,
    "realInstalls": 203312,
    "score": 4.4257426,
    "ratings": 624,
    "reviews": 221,
    "histogram": [
        55,
        6,
        30,
        55,
        475
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $49.99 per item",
    "developer": "GANG122",
    "developerId": "GANG122",
    "developerEmail": "fufuzuo22@gmail.com",
    "developerWebsite": "https://lb6981688.app-ads-txt.com",
    "developerAddress": null,
    "privacyPolicy": "https://sites.google.com/view/privacypolicyofreelsage",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/bPbhscaZwnufunCnGSrKXwkLX1sRQmkDZfcfKe43WkJHBvdXytJLO7px0kpY-qq2X6s",
    "headerImage": "https://play-lh.googleusercontent.com/_a61u6AmHHSyralbz_m_MqGdqcMcFv75jefVEHFFZSkarAZU7-9DoNlNA64T8ecKyFw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/hiJe_0Ec-iZYJi70JG18Bl0939bte981huGnSEZukwr3ApOIr8gvzvpYe9ax2skLq6Y",
        "https://play-lh.googleusercontent.com/45zacxZG1itnE0K8216naMqOGfhcLoiIDsCG5X384vqTG1MvXxt1UELtlVBsuABrbV8",
        "https://play-lh.googleusercontent.com/l5AFeuuPXU8UCXEqQPAIDramJa3fqII05FMDHQTpEy-MLODfG-Ag_jzd8NlPya_zNgY",
        "https://play-lh.googleusercontent.com/xkqLODHF_cMs_fVo0rbnAMXbYcfvSKHFktMyMEVmrAddLkPODivgOAFXI4VIyG2ruQ",
        "https://play-lh.googleusercontent.com/Q0HG2eZzeM1FdbAqlTrRIAiygBoMk6MFne1fQ6JfCCnVrp6d_ON_gEpGu_IaQP6X7Hk",
        "https://play-lh.googleusercontent.com/uM2iOmdksJWRn0ga86Tm44x801Dln2cOOlVZ6WOWe--SF5Y3gU6-sXydiDwLjyo-sw",
        "https://play-lh.googleusercontent.com/mg449HwOFWgDKLpot9iVIBqvqdYqJZ3RtPe-OAnv84lsCH1DfsaVjQPVsoKCgUJqag",
        "https://play-lh.googleusercontent.com/LEJWWZeBy70-OrNyeB5OCl65cnARiNIP0OHSlER8cQmZa921fRZGSJE5s3h7dnRn43Q",
        "https://play-lh.googleusercontent.com/VFXRhVRlMscNYYHrD9dPN71rca9KpdXGQQv386jA_WBLpe8WCG4zmYZZYp5PM9wck-o",
        "https://play-lh.googleusercontent.com/GnLDC1P5Vkkg-HixjOY9SByb6d2004KtuIZqKlDtqFZT0hbHRJbzzTE9zMHy-GgzUSY",
        "https://play-lh.googleusercontent.com/-pJiaNnEQ7eN8QtMr0iGrYbbH53Go-TlT6crCMwmi708br4BiPej87v8IffnfIvb0jXq"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Teen",
    "contentRatingDescription": "Mild Violence",
    "adSupported": true,
    "containsAds": true,
    "released": "Jul 28, 2023",
    "lastUpdatedOn": "Mar 21, 2024",
    "updated": 1711087473,
    "version": "1.0.6",
    "comments": [],
    "appId": "reel.reelsage.sage",
    "url": "https://play.google.com/store/apps/details?id=reel.reelsage.sage&hl=en&gl=us"
}