{
    "title": "Revive: Animation & AI Photos",
    "description": "<b>Create face animation with Revive's AI photo generator. Try face filters for photos & create funny videos with our face app.</b>\r\n\r\nRevive is an animation creator. Using this photo animator you can easily make your face dance. It offers a handpicked selection of animation & funny video for pictures. Animate pictures to funny videos and make them stand out with a variety of trendy effects and sing like Monroe, Queen, Rihanna etc. You can also create cartoon animation with the meme maker option! Bring to live your boring avatars using AI video Generator!\r\n\r\n<b>Animation & funny videos</b>\r\n\r\n\u2022 Most beloved and trendy funny videos, memes & animations for pictures \u2013 CJ, Fifty Fifty, Jake Sully, Muppet Show, The sorting Hat. Boost your social media with eye-catching content\r\n\u2022 Wide range of functions for animate pictures using our face app \u2013 make your face dance in funny videos\r\n\u2022 Rich festive collection & animation effects: create Christmas, Halloween and Easter content using this photo animator\r\n\u2022 In our face app is huge collection of collages & mood categories - try any animation according to your personal mood\r\n\u2022 Animate your pet - bring your pet\u2019s face dance \r\n\u2022 AI photo generator can revive any avatar with your own mimic\r\n\u2022 Unique collection of fun Templates & AI filters\r\n\u2022 Become a meme maker with our photo animator. Share your funny videos with your friends\r\n\r\n<b>AI video generator</b>\r\n\u2022 Upload and animate pictures\r\n\u2022 Edit trendy memes, AI filters\r\n\u2022 Transform your photos into real animations (add mimic or sing songs, dance, move). Become an animator and create your stories!\r\n\u2022 Create unique face dance edits with a rich collection of effects & filters for animation.\r\n\u2022 Stylize your content with a rich collection of retro celebrities \u2013 the 20s, 60s, 80s, 90s, 00s phrases.\r\n\r\n<b>Make your content stand out with our face app photo animator!</b>\r\n\r\nRevive makes any boring pictures weird and funny with the lip sync.\r\nStart a conversation in a messenger, get comments on social media with your animated photos, or singing face, cool animation or AI video generator.\r\n\r\nDiscover the world of animation and AI filters with our advanced AI editing app that transforms your photos or cartoons into funny videos. Create animated AI avatars, artistic live portraits and dancing cartoons by turning your images into vibrant, lifelike animations. Experience the seamless blend of technology and creativity, as our AI effortlessly works its magic to enhance your photo & video editing process, helping you craft visually live AI avatars and portraits that stand out.\r\n\r\nCreate live portraits with a face animation in it for an instant effect.\r\nEdit pictures, selfies, a meme with the animation creator. Make your photos sing & face app.\r\n \r\n<b>The best things you can do with the app</b>\r\n\r\n\u2022 Face filters & editor\r\n\u2022 AI photo generator & meme maker\r\n\u2022 Top phrases and songs from your favorite celebrities or actors, memes every day\r\n\u2022 Tons of different animations that you can apply on your or friend\u2019s pictures\r\n\u2022 You can organize your challenges or even fun games in social networks with your audience in the entertainment world.\r\n\u2022 Create funny videos or live photos\r\n\u2022 Prank your family with animation face app\r\n\r\n<b>Get AI Video Generator</b>\r\n\r\n\u2022 Unlimited meme maker\r\n\u2022 Animate Pictures to funny videos\r\n\u2022 AI Art Generator & face app\r\n\u2022 Special offers and festive discounts\r\n\r\nCreate funny Face Animation with AI Photo Generator. Try face filters for photos & videos!\r\n----\r\nIn case of any questions, issues, or collaboration requests, contact us at hi@reviveapp.net\r\n\r\nTerms and Conditions: https://reviveapp.net/terms/\r\nPrivacy Policy: https://reviveapp.net/privacy-policy/",
    "descriptionHTML": "<b>Create face animation with Revive&#39;s AI photo generator. Try face filters for photos &amp; create funny videos with our face app.</b><br><br>Revive is an animation creator. Using this photo animator you can easily make your face dance. It offers a handpicked selection of animation &amp; funny video for pictures. Animate pictures to funny videos and make them stand out with a variety of trendy effects and sing like Monroe, Queen, Rihanna etc. You can also create cartoon animation with the meme maker option! Bring to live your boring avatars using AI video Generator!<br><br><b>Animation &amp; funny videos</b><br><br>\u2022 Most beloved and trendy funny videos, memes &amp; animations for pictures \u2013 CJ, Fifty Fifty, Jake Sully, Muppet Show, The sorting Hat. Boost your social media with eye-catching content<br>\u2022 Wide range of functions for animate pictures using our face app \u2013 make your face dance in funny videos<br>\u2022 Rich festive collection &amp; animation effects: create Christmas, Halloween and Easter content using this photo animator<br>\u2022 In our face app is huge collection of collages &amp; mood categories - try any animation according to your personal mood<br>\u2022 Animate your pet - bring your pet\u2019s face dance <br>\u2022 AI photo generator can revive any avatar with your own mimic<br>\u2022 Unique collection of fun Templates &amp; AI filters<br>\u2022 Become a meme maker with our photo animator. Share your funny videos with your friends<br><br><b>AI video generator</b><br>\u2022 Upload and animate pictures<br>\u2022 Edit trendy memes, AI filters<br>\u2022 Transform your photos into real animations (add mimic or sing songs, dance, move). Become an animator and create your stories!<br>\u2022 Create unique face dance edits with a rich collection of effects &amp; filters for animation.<br>\u2022 Stylize your content with a rich collection of retro celebrities \u2013 the 20s, 60s, 80s, 90s, 00s phrases.<br><br><b>Make your content stand out with our face app photo animator!</b><br><br>Revive makes any boring pictures weird and funny with the lip sync.<br>Start a conversation in a messenger, get comments on social media with your animated photos, or singing face, cool animation or AI video generator.<br><br>Discover the world of animation and AI filters with our advanced AI editing app that transforms your photos or cartoons into funny videos. Create animated AI avatars, artistic live portraits and dancing cartoons by turning your images into vibrant, lifelike animations. Experience the seamless blend of technology and creativity, as our AI effortlessly works its magic to enhance your photo &amp; video editing process, helping you craft visually live AI avatars and portraits that stand out.<br><br>Create live portraits with a face animation in it for an instant effect.<br>Edit pictures, selfies, a meme with the animation creator. Make your photos sing &amp; face app.<br> <br><b>The best things you can do with the app</b><br><br>\u2022 Face filters &amp; editor<br>\u2022 AI photo generator &amp; meme maker<br>\u2022 Top phrases and songs from your favorite celebrities or actors, memes every day<br>\u2022 Tons of different animations that you can apply on your or friend\u2019s pictures<br>\u2022 You can organize your challenges or even fun games in social networks with your audience in the entertainment world.<br>\u2022 Create funny videos or live photos<br>\u2022 Prank your family with animation face app<br><br><b>Get AI Video Generator</b><br><br>\u2022 Unlimited meme maker<br>\u2022 Animate Pictures to funny videos<br>\u2022 AI Art Generator &amp; face app<br>\u2022 Special offers and festive discounts<br><br>Create funny Face Animation with AI Photo Generator. Try face filters for photos &amp; videos!<br>----<br>In case of any questions, issues, or collaboration requests, contact us at hi@reviveapp.net<br><br>Terms and Conditions: https://reviveapp.net/terms/<br>Privacy Policy: https://reviveapp.net/privacy-policy/",
    "summary": "Explore meme maker & AI generator. Try funny face filters and animation creator!",
    "installs": "5,000,000+",
    "minInstalls": 5000000,
    "realInstalls": 9912030,
    "score": 4.2865853,
    "ratings": 61316,
    "reviews": 5024,
    "histogram": [
        6821,
        1679,
        1632,
        8131,
        43041
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $74.99 per item",
    "developer": "REFACEAI LIMITED",
    "developerId": "6511558516362064209",
    "developerEmail": "hi@reviveapp.net",
    "developerWebsite": "https://reviveapp.net/",
    "developerAddress": "Ground Floor Flat, 19 Elgin Crescent, London, W11 2JD, United Kingdom",
    "privacyPolicy": "https://reface.ai/revive/privacy",
    "genre": "Entertainment",
    "genreId": "ENTERTAINMENT",
    "categories": [
        {
            "name": "Entertainment",
            "id": "ENTERTAINMENT"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/oxKE85ZOG9xe-NnIs8_864eOp_jgC-HxLvhJpzVYUrfdMO1Px3Baaq4iNzyMHcwN3U4",
    "headerImage": "https://play-lh.googleusercontent.com/w1bbYHpd1f-PoCeGoyjr78JxOPamPOqN_T0cdcyCJXJp_FKeC4XP9Sakm0Lt2FmcemtE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/GcGhK6bbpeAOKyqrBhPMezWdQ4qVYrg3CcclsMv4TIt8RF6Xj0axt483cfHCN4YSaWc",
        "https://play-lh.googleusercontent.com/kYVWC0jyWOj-KuBuOv3FR-NvCZYi8gshkHGWuk3c-96LNzON_eM271FggQGXZhZh1LY",
        "https://play-lh.googleusercontent.com/sbzIagaM9uaYOdCeTpdowlNCoM6vEznabJMvEFkWPDDn5tjhmuEAKZS0Wk4IOEPiPcI",
        "https://play-lh.googleusercontent.com/mCDg1mWa9wVoj6nVVc7ecY6dxNixHh-2HKAsD14tCAqJSoyF4zdj_tM8XFDPjq_8ULs",
        "https://play-lh.googleusercontent.com/acTeRkBkiMfHKh4j57wG85wWzPbShbzWdR1K4hQK0knmX-Ioxi2YnNPC7viS243ozHh7",
        "https://play-lh.googleusercontent.com/x5ZEFy63r7IgaCtBxc-5CmzVce5J-hK_Aota7Vo2KbSjBJHrUM56h2S216PzJZ_nPzc",
        "https://play-lh.googleusercontent.com/ow6weixs_hb6H_cLXFkpA672r1-EPH08mNt4M_Fn0LN1KsBzPGxcTzN0Rpnbg5bZDAM",
        "https://play-lh.googleusercontent.com/OeVQFUsS02TiAZgfBi8QZ16I0AnKeibFAeTALvL6mwl4ZOULY3vDxVYbOTFcoA3z5zM",
        "https://play-lh.googleusercontent.com/yEQlADDaWfFQKn2fp3kJb1RaU8NGvt_7275DWSAhZxkvil4uX8G2ChcpHii21WnxHMc",
        "https://play-lh.googleusercontent.com/cGbSjazndqzpwU9GerTL3m4v4IVWf-it0BLW277Xn7pv4aMWZ4kTcp-lIR0at6-wW3c",
        "https://play-lh.googleusercontent.com/3WmJ0WmztWpAmqzNSvo3Ab3HlTSzimmblWbbtWnPSYlHuN1c7dYvCORHDaagoFpiWQ",
        "https://play-lh.googleusercontent.com/xenV8_MHQ9wUMZVufYppcoO1WVkiYyD9-JK9dB6wjkjl_FoFLBagAfTQMU0JL1yHTw"
    ],
    "video": "https://www.youtube.com/embed/2KJ6hBXaII8?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/w1bbYHpd1f-PoCeGoyjr78JxOPamPOqN_T0cdcyCJXJp_FKeC4XP9Sakm0Lt2FmcemtE",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "May 20, 2022",
    "lastUpdatedOn": "Oct 4, 2024",
    "updated": 1728071755,
    "version": "3.12.2",
    "comments": [],
    "appId": "revive.app",
    "url": "https://play.google.com/store/apps/details?id=revive.app&hl=en&gl=us"
}