{
    "title": "Bedtime Stories - HeyKids",
    "description": "<b>Enjoy an amazing collection of bedtimes stories for children!</b>\r\n\r\nOur app is designed for curious little babies, toddlers, and preschoolers! Your child will enjoy lovely 3D animated fairy tales videos that will help them unleash their imagination and learn valuable moral lessons.\r\n\r\nCarefully designed for children of all ages this application is ideal for an engaging, educational, visually and audibly exciting experience.\r\n\r\nWhat you\u2019ll love about HeyKids:\r\n\u2022\tNO ADS, ensuring a safe environment for your children\r\n\u2022\tOFFLINE VIDEO PLAYBACK.  Watch the videos anywhere you go, no internet connection required \r\n\u2022\tThe most popular fairy tales with 3D animated videos\r\n\u2022\tNew stories for kids and cartoons added every month\r\n\u2022\tDesigned for kids - no unnecessary buttons, easy scrolling, and screen lock\r\n\u2022\tMultiple settings available for parents\r\n\u2022\tPreschool short stories that will make your child smile\r\n\r\n<b>Which is your favorite fairy tale?</b> Here are just a few of the short stories and fairytales for children you can find in our app:\r\n\r\n\u2022 Little Red Riding Hood\r\n\u2022 Three Little Pigs\r\n\u2022 The Ugly Duckling\r\n\u2022 Wolf And The Seven Little Goats\r\n\u2022 The Sleeping Beauty \r\n\u2022 and many more\r\n\r\nFor customer support, comments, or suggestion please contact us at contact@heykids.com\r\n\r\nDo you like our app? Please rate us or write a review to tell us what you think.",
    "descriptionHTML": "<b>Enjoy an amazing collection of bedtimes stories for children!</b><br><br>Our app is designed for curious little babies, toddlers, and preschoolers! Your child will enjoy lovely 3D animated fairy tales videos that will help them unleash their imagination and learn valuable moral lessons.<br><br>Carefully designed for children of all ages this application is ideal for an engaging, educational, visually and audibly exciting experience.<br><br>What you\u2019ll love about HeyKids:<br>\u2022\tNO ADS, ensuring a safe environment for your children<br>\u2022\tOFFLINE VIDEO PLAYBACK.  Watch the videos anywhere you go, no internet connection required <br>\u2022\tThe most popular fairy tales with 3D animated videos<br>\u2022\tNew stories for kids and cartoons added every month<br>\u2022\tDesigned for kids - no unnecessary buttons, easy scrolling, and screen lock<br>\u2022\tMultiple settings available for parents<br>\u2022\tPreschool short stories that will make your child smile<br><br><b>Which is your favorite fairy tale?</b> Here are just a few of the short stories and fairytales for children you can find in our app:<br><br>\u2022 Little Red Riding Hood<br>\u2022 Three Little Pigs<br>\u2022 The Ugly Duckling<br>\u2022 Wolf And The Seven Little Goats<br>\u2022 The Sleeping Beauty <br>\u2022 and many more<br><br>For customer support, comments, or suggestion please contact us at contact@heykids.com<br><br>Do you like our app? Please rate us or write a review to tell us what you think.",
    "summary": "Download and watch the most popular fairy tales and short stories for kids",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1839863,
    "score": 3.8888888,
    "ratings": 903,
    "reviews": 5,
    "histogram": [
        100,
        100,
        150,
        0,
        551
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $9.99 per item",
    "developer": "Animaj",
    "developerId": "Animaj",
    "developerEmail": "contact@vveee.com",
    "developerWebsite": "http://www.vveee.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.animaj.com/privacy-policy",
    "genre": "Parenting",
    "genreId": "PARENTING",
    "categories": [
        {
            "name": "Parenting",
            "id": "PARENTING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/UbqJJIdj95IPch5q60yXDgI74_OCoytV1R_2dbu6yKZ4XRH3GgCukfUNJVgtuMsWfQ",
    "headerImage": "https://play-lh.googleusercontent.com/mD0BrkTLF9dmu6pvdf_o1y-ViUv-uZi9-_DSPqFmv59IQfjIr-IbHTE0KyHF_84Iqw",
    "screenshots": [
        "https://play-lh.googleusercontent.com/n0bFuphR-NnzqopKQbKbdYYUwbZVq8xhAxNJAQUatxF8yjuiLhdFcDee83kYylsp4DQ",
        "https://play-lh.googleusercontent.com/_Dimu0nzHOTr1kMmgaZ2mm1SBrhLAd-DMIJuw9IWfuYDI-MYwtlP_3txqjMe433LnhQ",
        "https://play-lh.googleusercontent.com/MPE-zyiDxUVrAIZsqTprXz9hKE3pK2aoYraaxbPVtAfli8MYXfuBcubFDtprqjO60d8",
        "https://play-lh.googleusercontent.com/-9dI5iTJ_S3ak4s81-LqUmuk_uc-KvsCNezjMqFUHd4hix6V3EK6_Uo1PWbRNDVtV3M",
        "https://play-lh.googleusercontent.com/1sHSHMdQsIRjBomutZj6ktuKrGkolIuhODt6_yTM4uDSQjrGTHpAu48KdJgYpop5Sg",
        "https://play-lh.googleusercontent.com/ssmc2DzmWYqUYo9v_N_FUaS7ytX0-LWSKp5nk0JmT9sqT8tF-OjFRR6ohgdIDPUQrQ",
        "https://play-lh.googleusercontent.com/lhRqLvRTECmCxzUe2naalT7YzVKjPKo0qCpgO_u2P1hWg2axYixmo2R1Dw-qo6OOPsc",
        "https://play-lh.googleusercontent.com/hYxCCa7lir6tjywZMQ5asiGEFKB3bgIYWStwdIQm6i7-rba6v_TPJEFiypzX6SmVLg",
        "https://play-lh.googleusercontent.com/EskJZfMYiG1IfPC328Z_8K0MBFP6Be705HrEzqdOfqQWessNVgsOp2NkpbZrqlvD-UcD",
        "https://play-lh.googleusercontent.com/aXjCiIp2dBjsu75E2zgW6W-ecwanOByHyTCoUUA3zpHU3n3tIjZbrvHZWCbSAJ4k7JTZ",
        "https://play-lh.googleusercontent.com/36oTmvP715X5hyYkXhSHQQLv2mwg056sLOjSYAE_cjoyRd3utAxHYyR0YYS1w78Y4os",
        "https://play-lh.googleusercontent.com/-84qqTBdnX48aLSTfxMwcVNwd8jJxCp4mXceOIjzwcyes51TK1cD7S--QYLh9kmdSFI",
        "https://play-lh.googleusercontent.com/-P58HM4QTlSp8d5hxwI9fZgkrLPgRiEuy7znUXyESwrYRw3yykpIo4xUCPxWJuruKvnh",
        "https://play-lh.googleusercontent.com/OH0PNa1bG0UatQtpx5ubmIkY6NVlSOy2E1Ae7-tiG5j2d3XF0RL4Tx6w-KXCRTAUqbg",
        "https://play-lh.googleusercontent.com/_wHza1VrXTlDCzT6mGnWa1YZOy3u8JZb9IDajnYo2RHqAXenfjUFtaGJQK0JW2jDuQ",
        "https://play-lh.googleusercontent.com/IwqcgO2wQhuCVJHKcFkRx_desj5vMxFeStzUFgGAUqukX5YSiaMFiI_HF0CuTPR8hDk",
        "https://play-lh.googleusercontent.com/7QczZCT4ZoZWcxjAPjvsbyXlZxYWXXeBwdCnJ-eK_CluTChIluAoUKZgk4H588VcDM67",
        "https://play-lh.googleusercontent.com/mz4XrNd2dFBy9iQsdR965iWJdT1qqliiWyACtL2LGTEVGf-vXPOwClIi8aH5YQjdEv3t",
        "https://play-lh.googleusercontent.com/lfNuwGWaz0hqTIHEoVgaHLKpx3wzLFQXqQHs1BMfV6G2pcoLjTKOjYrU5SDrkcZLfA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 20, 2019",
    "lastUpdatedOn": "Sep 18, 2023",
    "updated": 1695032574,
    "version": "2.2.2",
    "comments": [],
    "appId": "ro.heykids.povesti.desene.app",
    "url": "https://play.google.com/store/apps/details?id=ro.heykids.povesti.desene.app&hl=en&gl=us"
}