{
    "title": "\u0411\u0438\u043b\u0435\u0442\u044b \u041f\u0414\u0414 2024 \u0438 \u042d\u043a\u0437\u0430\u043c\u0435\u043d \u041f\u0414\u0414",
    "description": "<b>Tickets for passing the traffic rules exam at the State Traffic Safety Inspectorate 2023/2024</b> * Free without advertising * Categories <b>AB</b> and <b>CD</b> * Drom Traffic Regulations - application from Droma. Exam tickets were taken from the official website of the State Traffic Safety Inspectorate of the Ministry of Internal Affairs of the Russian Federation https://gibdd.rf/mens/avtovladeltsam/abm. It is not an official application of the State Traffic Safety Inspectorate of the Ministry of Internal Affairs of the Russian Federation.\r\n\r\nWe are monitoring how <b>traffic rules 2024</b> tickets from the State Traffic Safety Inspectorate are changing for categories AB and sharing all the new rules for passing the exam. We help you pass the traffic police exam and avoid making a single mistake when solving traffic rules 2024 exam tickets.\r\nIn the official application you can easily prepare and pass the theoretical traffic rules exam 2024 in the traffic police All Categories AB (AB) / CD (SD) and subcategories A1, B1, C1, D1. We cooperate with Russian Driving Schools\r\n\r\n\r\n<b>Unique in the application:</b>\r\n\u2014 All 40 tickets are available free of charge and without advertising.\r\n\u2014 Current Traffic Rules from the State Traffic Safety Inspectorate AB for 2024\r\n\r\n<b>Available in the application:</b>\r\n\u2014 The exam mode is the same as in the traffic police.\r\n\u2014 Complete and up-to-date database of traffic rules tickets.\r\n\u2014 Statistics of academic performance and progress.\r\n\u2014 Comments from a specialist on all issues.\r\n- Live chat.\r\n- Reminders motivate you to learn more.\r\n\u2014 Marathon mode, all 800 questions in a row.\r\n\u2014 Working on ticket errors.\r\n\u2014 Our traffic rules simulator works completely without the Internet\r\n\u2014 The app truly teaches the rules and how to pass the exam.\r\n\r\nThe Droma team wishes you success in passing the exam and obtaining the coveted driver's license!\r\n\r\nTraffic rules 2024 \ud83d\ude97",
    "descriptionHTML": "<b>Tickets for passing the traffic rules exam at the State Traffic Safety Inspectorate 2023/2024</b> * Free without advertising * Categories <b>AB</b> and <b>CD</b> * Drom Traffic Regulations - application from Droma. Exam tickets were taken from the official website of the State Traffic Safety Inspectorate of the Ministry of Internal Affairs of the Russian Federation https://gibdd.rf/mens/avtovladeltsam/abm. It is not an official application of the State Traffic Safety Inspectorate of the Ministry of Internal Affairs of the Russian Federation.<br><br>We are monitoring how <b>traffic rules 2024</b> tickets from the State Traffic Safety Inspectorate are changing for categories AB and sharing all the new rules for passing the exam. We help you pass the traffic police exam and avoid making a single mistake when solving traffic rules 2024 exam tickets.<br>In the official application you can easily prepare and pass the theoretical traffic rules exam 2024 in the traffic police All Categories AB (AB) / CD (SD) and subcategories A1, B1, C1, D1. We cooperate with Russian Driving Schools<br><br><br><b>Unique in the application:</b><br>\u2014 All 40 tickets are available free of charge and without advertising.<br>\u2014 Current Traffic Rules from the State Traffic Safety Inspectorate AB for 2024<br><br><b>Available in the application:</b><br>\u2014 The exam mode is the same as in the traffic police.<br>\u2014 Complete and up-to-date database of traffic rules tickets.<br>\u2014 Statistics of academic performance and progress.<br>\u2014 Comments from a specialist on all issues.<br>- Live chat.<br>- Reminders motivate you to learn more.<br>\u2014 Marathon mode, all 800 questions in a row.<br>\u2014 Working on ticket errors.<br>\u2014 Our traffic rules simulator works completely without the Internet<br>\u2014 The app truly teaches the rules and how to pass the exam.<br><br>The Droma team wishes you success in passing the exam and obtaining the coveted driver&#39;s license!<br><br>Traffic rules 2024 \ud83d\ude97",
    "summary": "Traffic rules tickets 2024 from the traffic police (State Traffic Safety Inspectorate) Traffic rules exam 2024 with changes Categories ABM/CD",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 16113339,
    "score": 4.9545455,
    "ratings": 876128,
    "reviews": 84,
    "histogram": [
        0,
        0,
        6033,
        26143,
        842611
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "\u0414\u0440\u043e\u043c",
    "developerId": "%D0%94%D1%80%D0%BE%D0%BC",
    "developerEmail": "mobile@drom.ru",
    "developerWebsite": "https://www.drom.ru/pdd/",
    "developerAddress": null,
    "privacyPolicy": "https://www.drom.ru/misc/pdd-agreement/",
    "genre": "Auto & Vehicles",
    "genreId": "AUTO_AND_VEHICLES",
    "categories": [
        {
            "name": "Auto & Vehicles",
            "id": "AUTO_AND_VEHICLES"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/M05AfPVBYlU1_1jUhvjscKbTJ1cJzcsbM3rx5TQxBKma_GtAE71VH5VakYkIyHK8Qg",
    "headerImage": "https://play-lh.googleusercontent.com/EdOABp8CVmZc22gh-Ta0tLmV4TTTv1xudft46FXKO5iyrqHFwtMogL-V6XDlqbGKOg",
    "screenshots": [
        "https://play-lh.googleusercontent.com/Q-Ils6F7h_F3rwRmgs-5NidkKHDdkuRx8GjS2oVj1T9MmkgZKGvwYuNujCJ64gGM39w",
        "https://play-lh.googleusercontent.com/ip7It1A7T6U_Jy1Q3dyMw6X9CaHAWrYpt4ydOITLuwEcyY4Tq9wImFbyfTzhly8XVrfS",
        "https://play-lh.googleusercontent.com/il8Askbizh766pONpbGtx5_nVHKgWw0ShxskQ-rzcc0pmorEGtr0NuCqHRkuChoqVsk",
        "https://play-lh.googleusercontent.com/oVvk0muRT5BDGuFb1Nx_wpRN20g1CmmGM4Uiibv6ljLqjZZSSpzWKDMNPezZHvaaZu0W",
        "https://play-lh.googleusercontent.com/eLGUQxxUbumqPIwtRfm0YN4EVeQqiCxP8fiqLnX1PISudKY1Fkd7VdzOjRrCKMp1F24",
        "https://play-lh.googleusercontent.com/Xo-6oqWT0llvlAyeuaZaV2zsfX_zClkyyDbCm-wwN5WZ5XFHN5Bu-Et8hTXNwlS2Pw",
        "https://play-lh.googleusercontent.com/5_nFcQv0p7Lw2zgiLV99ForQV8hRRkJqN5gt9wwB9fwYOWsxqjZbZvuB15wjkrguc2Q",
        "https://play-lh.googleusercontent.com/3ZSWRc3aK5owjVuC43iun1tqnq5RZ3G9a4lxxX31yMZPfnzfbE6u1QltgjxIG-7-HRPB",
        "https://play-lh.googleusercontent.com/xMMkQI4UuFzOz4gABPnm8ejAG8FK3IWrRyqjGqyAnxrO_ezfsOG2P7fLVtk2s7YSGQI",
        "https://play-lh.googleusercontent.com/sX4sdBavHuENk3dMeg4dJ1unXdlYpJmdym-i7w_kzRYV_q09-LPAKP7WtDS3W2pGqaE",
        "https://play-lh.googleusercontent.com/rYAlgkcHsW8I2z8-tjNLQODGyZ6ck0nARY6nZeitpG9vfvacdyqUwJQXwXY11GDSQDs",
        "https://play-lh.googleusercontent.com/Himj2n_ez7TnBOJy1aAXdmacEPu4duXWGkQ7qHO7s9zS4oohHcyOwgpU9TvE_8rxToU",
        "https://play-lh.googleusercontent.com/eSY8fm9cbm49AkmoSDh2al-_el-6tKwLemK0kKHhmCypGgMBF5eMRU1cM9WEMo_1P8U",
        "https://play-lh.googleusercontent.com/fN6i1_L4FOTriBSaN9T9bB9-DuG46xD6e4bVwk_DzldMST46O-6f7sRPBDeuWa1O",
        "https://play-lh.googleusercontent.com/5IBiu8--reNfoMykfzgm6gGTm0GfkFeJl9WoltoXZ5rT79fRU1yx2nCqlIJk6uC2LQ",
        "https://play-lh.googleusercontent.com/HcjjqEU6Dv3F22lvtMCPwCCaVMsa0eLVxqBPOvKg9tB4vEte6Cy8vix92Z5DO33nytY",
        "https://play-lh.googleusercontent.com/B69jnCjWFP9EhyuoFuCXdtqNCWEHbQlyYen82gvLtum0nuxJyfzJ-uVssA2UGMzGJEs",
        "https://play-lh.googleusercontent.com/VrxyCGlBkC9uuZfrzNePhUx1ptOveohdNsYrT5reBWDduQL2Pn_LWKrsKBWJoD7eF60"
    ],
    "video": "https://www.youtube.com/embed/ayyaDOFOvjU?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/EdOABp8CVmZc22gh-Ta0tLmV4TTTv1xudft46FXKO5iyrqHFwtMogL-V6XDlqbGKOg",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 21, 2017",
    "lastUpdatedOn": "Sep 30, 2024",
    "updated": 1727686241,
    "version": "3.26",
    "comments": [],
    "appId": "ru.drom.pdd.android.app",
    "url": "https://play.google.com/store/apps/details?id=ru.drom.pdd.android.app&hl=en&gl=us"
}