{
    "title": "Secret - Dating Nearby Casual",
    "description": "Are you experienced dating apps user or a newcomer to online dating, we have something to surprise you! We change the game: meeting, dating, flirting, chatting online and developing love relationship is as easy as pie! \r\n\r\nSecret dating is taking the world as more and more single girls and guys hang out to find someone for casual dating, hang out meet, tango dancing etc. \r\n\r\nWe took the most difficult part upon ourselves: \r\n\r\n\u2022 picked up over 10 million audience of real people willing to date, \r\n\u2022 added a feature of geolocation search - Singles around me,\r\n\u2022 created a user-friendly system for flirt and dating only in case of mutual affinity,\r\n\u2022 added a feature of easy choice of a partner by photo, and \r\n\u2022 found you to change your view of dating once and for all!\r\n\r\nIt is a taboo-free zone: privacy makes you feel free and give way to your secret thoughts and desires. Here you can find any desired relationship style: monogamous or polyamorous, for long-term commitment or one night stand. \r\n\r\nDo you want a date? Just choose the place and time, and Secret will find a partner for you. A cherry on top of our application is a feature which allows the users to specify the way they want to spend their date, and finds a right partner for it.\r\n\r\n\u2022 A huge audience of more than 10+ mln users worldwide\r\n\u2022 Active users\r\n\u2022 Simple registration\r\n\r\nJoin us! Right now, while you have been reading this text, plenty of fish got acquainted and start communicating in our application.\r\n\r\nRemember to follow certain rules:\r\n\u2022 For adults ONLY\r\n\u2022 No hate, violence, and offensive content\r\n\u2022 No nudity or explicit sexual content",
    "descriptionHTML": "Are you experienced dating apps user or a newcomer to online dating, we have something to surprise you! We change the game: meeting, dating, flirting, chatting online and developing love relationship is as easy as pie! <br><br>Secret dating is taking the world as more and more single girls and guys hang out to find someone for casual dating, hang out meet, tango dancing etc. <br><br>We took the most difficult part upon ourselves: <br><br>\u2022 picked up over 10 million audience of real people willing to date, <br>\u2022 added a feature of geolocation search - Singles around me,<br>\u2022 created a user-friendly system for flirt and dating only in case of mutual affinity,<br>\u2022 added a feature of easy choice of a partner by photo, and <br>\u2022 found you to change your view of dating once and for all!<br><br>It is a taboo-free zone: privacy makes you feel free and give way to your secret thoughts and desires. Here you can find any desired relationship style: monogamous or polyamorous, for long-term commitment or one night stand. <br><br>Do you want a date? Just choose the place and time, and Secret will find a partner for you. A cherry on top of our application is a feature which allows the users to specify the way they want to spend their date, and finds a right partner for it.<br><br>\u2022 A huge audience of more than 10+ mln users worldwide<br>\u2022 Active users<br>\u2022 Simple registration<br><br>Join us! Right now, while you have been reading this text, plenty of fish got acquainted and start communicating in our application.<br><br>Remember to follow certain rules:<br>\u2022 For adults ONLY<br>\u2022 No hate, violence, and offensive content<br>\u2022 No nudity or explicit sexual content",
    "summary": "Dating app - Meet strangers, flirt & chat online",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 3119313,
    "score": 4.783582,
    "ratings": 46355,
    "reviews": 4444,
    "histogram": [
        1210,
        257,
        834,
        2738,
        41308
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $25.99 per item",
    "developer": "New Technologies LLC",
    "developerId": "New+Technologies+LLC",
    "developerEmail": "support@chocoapp.ru",
    "developerWebsite": "https://chocoapp.ru/secret-mobile",
    "developerAddress": "CHERNOMORSKII B-R, D. DOM 17, C. 1, MOSCOW, RUSSIA",
    "privacyPolicy": "https://chocoapp.ru/terms",
    "genre": "Dating",
    "genreId": "DATING",
    "categories": [
        {
            "name": "Dating",
            "id": "DATING"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/7jHXcp8jWWhlXlmdlV7LrpxX-0opXHqrIni2omh0pw_dMzPCGzvGX3-KVNVnSIFcZspg",
    "headerImage": "https://play-lh.googleusercontent.com/BzXzKKFe_5cQcdzw6rFqVFSq_XQtDIi9wD0Q5T9b55EoVg88UkIUzOkLk-_kbMgOMhM",
    "screenshots": [
        "https://play-lh.googleusercontent.com/DmwX1kms5-1gbH_qyQi52A1m2IV8Qi1ZwiKUakFEbVVmQ3Q9M1wKjOA9UIU7HcOkig",
        "https://play-lh.googleusercontent.com/vtCdw6MKOOYlAnmwXmGUc7XwjvKozkugzyCZvCSFhchj1um20q5TmgZJF-8nqe9mNP0",
        "https://play-lh.googleusercontent.com/8ozc21BUCnWiR6ksnzi-cSzfee8lPF9c-vgPUh2Ql1zcw62io0xuEULGNUs5uDZENg",
        "https://play-lh.googleusercontent.com/8UUeEXl3OSshNUROdBI0DomxCFsHh_x4vAHfLS8AZrs2tA0HkHw9erW1-sFatiBCydU",
        "https://play-lh.googleusercontent.com/5WwwVaudMJRk0GTW5Njd_4F252EQfQ6dTDOhE_SLEw8q_i5YUWx0uoBBlICnxAIAGOc",
        "https://play-lh.googleusercontent.com/fct34n8sxypvvDiOkZq8hQCA_0lvLrN5dXQJvjQdt4VGIehT4wRd0mLQi-0ReggV8Oiu",
        "https://play-lh.googleusercontent.com/Gefflf1zZET9sufh0l6zSEqDkHhWh8t0HKLpAcNV2MVEl1dgoQSFSxydocfPJHJjjejL",
        "https://play-lh.googleusercontent.com/dD5ovawrgNOPov9n9opx2EUPRHXakXcWFlOFtQbDgpR2h_EpfOsH6exGxI3TacZdXnUf",
        "https://play-lh.googleusercontent.com/UHQapScaze-mtbs2jKtSPx209EbkmbMIfaDv3Q5aCgsgWVqRv-rzLm9Oaaktx9CPvQrH",
        "https://play-lh.googleusercontent.com/Jpzn5QqExC2Orbc1_ugc7vz7HN9LGpm83qWh-37180A0r5mfQG4dEwNq9jOVzcpOu1Zl",
        "https://play-lh.googleusercontent.com/FjIALA0xK8gtirsIIytp92Vo7OAInBxKCzNEdK64iuGrBKnKLav6uPRsRHJf3UgDXH8N",
        "https://play-lh.googleusercontent.com/rp92TWupuR-nMoA__qCMOdrD5LqReArusYM7TBuKmcFRTx8zooR0Hm6jFjLT_3a-Aao",
        "https://play-lh.googleusercontent.com/bukT3Ll54oGZfbEb26Yi8hW4ww-oM6LMwGHjigZLhD3O3PvI08Fcl1L_GrOjTwoM47g",
        "https://play-lh.googleusercontent.com/ilFsHqxXCnlhqOscW3wARP3gAQ0C7YVjhPtAGT9PyPK85rD69l_g0CGERBIHLkjmHfd5",
        "https://play-lh.googleusercontent.com/AGLMyYmHDJKQ9FoOYP_Oy6l8rv6tGDMwAA_4VrM5aMSM1TBsYfa9eSVsNFN1HwwuzA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 16, 2017",
    "lastUpdatedOn": "Jul 26, 2024",
    "updated": 1722053957,
    "version": "1.0.68",
    "comments": [],
    "appId": "ru.taboo.app",
    "url": "https://play.google.com/store/apps/details?id=ru.taboo.app&hl=en&gl=us"
}