{
    "title": "Style DNA: Fashion AI Stylist",
    "description": "Want to dress with confidence, style outfits, and look amazing? It\u2019s time to get your AI personal stylist & outfit creator.\r\n\r\nTapping into your appearance DNA is the key to your style formula. Unlock yours with our personal styling and image consulting App!\r\n\r\nOur AI personal stylist combines the expertise of world-renowned image consultants with cutting-edge styling technology to analyze your unique features and complexion. It reveals the best colors, cuts, fabrics, and fashionable prints that flatter your body type to help you choose the right clothes and  daily outfits.\r\n\r\nUsing a simple selfie, your style profile is created in 35 seconds, showing you the right clothing to become stylish forever:\r\n\r\n\u2022 Explore your personal catalog for clothes shopping with different outfit ideas. From business casual outfits to wedding dresses and everyday styling, you\u2019ll see thousands of filtered options from fashion brands to suit your color type and body type.\r\n\u2022 Discover items from your favorite stores and brands with your personal shopper. \r\n\u2022 No matter your figure: hourglass, triangle, inverted triangle, rectangle, thin or plus size. Our online stylist shows you how to makeover your style and comfortable wear clothes. \r\n\u2022 Shop by personal color palette, thanks to digital color analysis, to see items that will perfectly complement your skin undertone, thanks to your style profile.\r\n\u2022 Manage your individual color palette if you really like a specific color. Get your own style guide.\r\n\u2022 Favorite items in your smart wardrobe to get style advice on how to combine them with your existing clothes into new outfits.\r\n\u2022 Get 5 daily, ready-to-wear outfit suggestions from your AI Stylist, all in your personal style, and budget, and organized by occasion: from office looks and gym wear to party dresses and beyond\u2026\r\n\u2022 Elevate your wardrobe using a virtual closet organizer. Take a photo of any item from your current wardrobe and see trendy ready-to-wear outfits styled for you. Combine all stylish items in your digital wardrobe, becoming your digital dressing room, virtual outfit finder, clothing generator, and professional wardrobe assistant. Save your favorite clothing and never lose track of your virtual closet.\r\n\u2022 Buy clothes and shop smart anywhere, anytime with your personal shopping assistant using your color palette, personal style book, and guide from Style DNA.\r\n\u2022 Get styling and fashion tips from your own individual stylist, tailored to what is most flattering for your body and style type.\r\n\u2022 Read more about your color type, including seasonal color typing, individual color pallets, and the prints and fabrics that suit you best.\r\n\r\n\r\nStyle DNA is like having a style book, fashion adviser, personal stylist, and personal shopper right at your fingertips. \r\n\r\nYou have just found the most fashionable and trendy outfit maker! Enjoy making and creating your own outfits with ease.\r\n\r\nSave time, shop smart and manage your styling and wardrobe with our outfit creator.\r\n\r\nSounds like magic? Not at all. Style DNA is fashion powered by technology.\r\n\r\nKeep the app updated and visit your virtual stylist regularly to get fresh new updates in the catalog, outfits, and new amazing features coming very soon.",
    "descriptionHTML": "Want to dress with confidence, style outfits, and look amazing? It\u2019s time to get your AI personal stylist &amp; outfit creator.<br><br>Tapping into your appearance DNA is the key to your style formula. Unlock yours with our personal styling and image consulting App!<br><br>Our AI personal stylist combines the expertise of world-renowned image consultants with cutting-edge styling technology to analyze your unique features and complexion. It reveals the best colors, cuts, fabrics, and fashionable prints that flatter your body type to help you choose the right clothes and  daily outfits.<br><br>Using a simple selfie, your style profile is created in 35 seconds, showing you the right clothing to become stylish forever:<br><br>\u2022 Explore your personal catalog for clothes shopping with different outfit ideas. From business casual outfits to wedding dresses and everyday styling, you\u2019ll see thousands of filtered options from fashion brands to suit your color type and body type.<br>\u2022 Discover items from your favorite stores and brands with your personal shopper. <br>\u2022 No matter your figure: hourglass, triangle, inverted triangle, rectangle, thin or plus size. Our online stylist shows you how to makeover your style and comfortable wear clothes. <br>\u2022 Shop by personal color palette, thanks to digital color analysis, to see items that will perfectly complement your skin undertone, thanks to your style profile.<br>\u2022 Manage your individual color palette if you really like a specific color. Get your own style guide.<br>\u2022 Favorite items in your smart wardrobe to get style advice on how to combine them with your existing clothes into new outfits.<br>\u2022 Get 5 daily, ready-to-wear outfit suggestions from your AI Stylist, all in your personal style, and budget, and organized by occasion: from office looks and gym wear to party dresses and beyond\u2026<br>\u2022 Elevate your wardrobe using a virtual closet organizer. Take a photo of any item from your current wardrobe and see trendy ready-to-wear outfits styled for you. Combine all stylish items in your digital wardrobe, becoming your digital dressing room, virtual outfit finder, clothing generator, and professional wardrobe assistant. Save your favorite clothing and never lose track of your virtual closet.<br>\u2022 Buy clothes and shop smart anywhere, anytime with your personal shopping assistant using your color palette, personal style book, and guide from Style DNA.<br>\u2022 Get styling and fashion tips from your own individual stylist, tailored to what is most flattering for your body and style type.<br>\u2022 Read more about your color type, including seasonal color typing, individual color pallets, and the prints and fabrics that suit you best.<br><br><br>Style DNA is like having a style book, fashion adviser, personal stylist, and personal shopper right at your fingertips. <br><br>You have just found the most fashionable and trendy outfit maker! Enjoy making and creating your own outfits with ease.<br><br>Save time, shop smart and manage your styling and wardrobe with our outfit creator.<br><br>Sounds like magic? Not at all. Style DNA is fashion powered by technology.<br><br>Keep the app updated and visit your virtual stylist regularly to get fresh new updates in the catalog, outfits, and new amazing features coming very soon.",
    "summary": "Color Analysis, Outfit Maker, Closet Planner & Organizer App",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 994303,
    "score": 3.61,
    "ratings": 4550,
    "reviews": 216,
    "histogram": [
        1227,
        84,
        130,
        859,
        2225
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.49 - $49.99 per item",
    "developer": "Style DNA",
    "developerId": "6126579406370668364",
    "developerEmail": "info@styledna.ai",
    "developerWebsite": "https://styledna.ai/",
    "developerAddress": "Paseo Ferrocarril 337,Castelldefels, Barcelona, Spain, 08860",
    "privacyPolicy": "https://styledna.ai/privacy-policy",
    "genre": "Lifestyle",
    "genreId": "LIFESTYLE",
    "categories": [
        {
            "name": "Lifestyle",
            "id": "LIFESTYLE"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/4fEgjTBK7YLV386ACJTr2kSOjqcCh3C9SG8_9i9pyTHraBNh3arLOE9bgXOSUMMY",
    "headerImage": "https://play-lh.googleusercontent.com/Rb08Z-3OToBa_Z0YoiE_U1DbYtQir1or4B-dtLYMgGiIPyisQ08KbNyqYf_t2dZVnEc",
    "screenshots": [
        "https://play-lh.googleusercontent.com/ddhCeMRTJvnxDTBfioPALGCW4cBreDSHIQFr57Rw6bPA9Z2k584ihZzI9H_ND_JU03Eq",
        "https://play-lh.googleusercontent.com/M5T0VVOUgoIrVtWhSSdviGxrDxvdRPEr9Byf27dHRHnWG7n0alE1a6NxhLBKQm867g",
        "https://play-lh.googleusercontent.com/AvDvgI-o9lYYpKY0_Z2y5aER1PFZYInKa1xu1V7mDQmd3alK8xzol3TELwHZGT12420",
        "https://play-lh.googleusercontent.com/FvnuGs8EUSMgKWbJxAirDAUUYLrSYHiHdm3xLPsTxTZsI-xDDjjmfCGcAb6A9uL2VQ",
        "https://play-lh.googleusercontent.com/f3chOjyh3zahu5y4mvd9NVVKeyJMnguGLF-anKiqXgLOp7Nmr_GryOp_mICDlnnaHs5L",
        "https://play-lh.googleusercontent.com/jdgZ-J0NjzmO_rsTtv4cVAguh0RR60Y6Tz71Qnar38z_uA02olotP4onJV1i4gRbYpE"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 6, 2022",
    "lastUpdatedOn": "Sep 16, 2024",
    "updated": 1726518536,
    "version": "1.9.191",
    "comments": [],
    "appId": "style.dna.app",
    "url": "https://play.google.com/store/apps/details?id=style.dna.app&hl=en&gl=us"
}