{
    "title": "\u0633\u0648\u0628\u0631\u0627",
    "description": "A collection of dozens of online intellectual games, including Mafia, Uno, Mench, Domino, and various board and card games.\r\n\r\nWith the ability to chat during the game, friend list and private chat, exclusive profile, ranking and weekly league and many different features",
    "descriptionHTML": "A collection of dozens of online intellectual games, including Mafia, Uno, Mench, Domino, and various board and card games.<br><br>With the ability to chat during the game, friend list and private chat, exclusive profile, ranking and weekly league and many different features",
    "summary": "Online intellectual games",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 1773981,
    "score": 3.8988094,
    "ratings": 41835,
    "reviews": 870,
    "histogram": [
        9211,
        1489,
        1737,
        1241,
        28130
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $7.99 per item",
    "developer": "Subra Games",
    "developerId": "Subra+Games",
    "developerEmail": "info@subra.games",
    "developerWebsite": "http://subra.games",
    "developerAddress": "9 Belvedere Road, Johannesburg",
    "privacyPolicy": "http://subra.studio/policy.htm",
    "genre": "Board",
    "genreId": "GAME_BOARD",
    "categories": [
        {
            "name": "Board",
            "id": "GAME_BOARD"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/7KQQe7P8HckAE5uM10GXKP-5QlvzV3EVZ_xw71ZoItqYTkhlSrVZyN5vFV8RbsPvcdo",
    "headerImage": "https://play-lh.googleusercontent.com/8GJKCiob4Y6M036DANe2XQIh9NOsPv3CT-tRvsH43FVoure85GIVZ5POo30UtOlCdgM",
    "screenshots": [
        "https://play-lh.googleusercontent.com/XgXfbcqxaa6damOKHA0FQ0eh1q-wWOR4P-O24mOuv8kNnFqOAaB5l8AhSHMXy2_o3XOA",
        "https://play-lh.googleusercontent.com/qTvo7irrEmmQDBrA87Vx2SFPo4f6qRen5BCoeOalUpuGQgezKcsC5zToyUwNDGOYig",
        "https://play-lh.googleusercontent.com/rpw-DfQI0_zvoZXzK9-C2H-8A_Y2HlIZU0HjFrNV2ZLrFs3dEwqgxLU0vheWUav3rtki",
        "https://play-lh.googleusercontent.com/4g9LdiutBnjh5NJ2fNO4jHeUce0agynwGTDePGmvP4gCvLEElzWXnmFv1vMnW9ypHIBX",
        "https://play-lh.googleusercontent.com/VZEWwH9Osgg0TiqR_xssda9FUE5tAQINrywqyTC_TgL1ku7CDRrXHyJ6sSOv6Zp6nLs",
        "https://play-lh.googleusercontent.com/Z6x89e6BhdczqXaBB_Dpsp4ShqWspE2HwZPPt7meDQkJnDdHy-600kH3ADSFhVshBjU5",
        "https://play-lh.googleusercontent.com/9H9iDL3ssAWnsotC5yZPdAhSVxpqfNeroQYBHFBU_RTaSTeeJpB3svb2VTB7vVPbXY_X",
        "https://play-lh.googleusercontent.com/LYen7wGz6wy_iB99nHAFeLojw2iPhAZPBL4wBfqf-ELtmG-1-HdQa-RoxJDn-MwdmxY",
        "https://play-lh.googleusercontent.com/DFdgRaoOXMnp1POTf5rEvpC3j66HDaEq7tquJcYXJ2YndO2u4M91uB4m2AzBP4LnIZl8",
        "https://play-lh.googleusercontent.com/_kT1tUIJkjHWAmWQPS6Pbzw8T1u72rEExEzLrH1h6H9FDedlgIwtJgUkUeVoM54xwA"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Mar 5, 2018",
    "lastUpdatedOn": "Mar 17, 2024",
    "updated": 1710744983,
    "version": "2.16.77",
    "comments": [],
    "appId": "subra.v2.app",
    "url": "https://play.google.com/store/apps/details?id=subra.v2.app&hl=en&gl=us"
}