{
    "title": "Hover - measure, design, quote",
    "description": "The one app to scope and sell every construction project. All your trades. All your people. All in one place. Contractors, adjusters, and homeowners trust Hover to get the job done.\r\n\r\nFor Construction Pros:\r\nMeasure everything. Get detailed, to-the-inch accurate exterior and interior home measurements from just 8 smartphone photos or by uploading a blueprint plan. No measuring tape or tracing required. For roof area, roof pitch, roof area, siding, soffits, eaves, fascia, trim, gutters, windows, doors, and more.\r\n\r\nDocument anything. Easily and consistently capture project notes, annotations, and photos at any point during the job. Leverage detailed templates covering inspections, liability, punchlists, team hand-offs, and more\u2014or create your own custom templates.\r\n\r\nDesign to sell. From inspiration tools powered by AI to interactive 3D home models, all from photos or a blueprint upload. Visualize your projects, the products you sell, share it with anyone, or export it as a BIM file for other applications. And when you\u2019re ready, add all the final touches like landscaping with photo-realistic rendered home designs.\r\n\r\nTakeoffs in two clicks. Generate ready-to-order Material Lists directly from Hover's measurements. Access over a hundred customizable building material templates, built by industry experts and from the most trusted brands, to generate complete Material Lists\u2014without number crunching or manual data entry. You can mix materials, trades, and even submit building material orders digitally to your local supplier.\r\n\r\nFor Homeowners:\r\nWorking with an insurance company? Hover helps streamline your underwriting or claims process.\r\n\r\nWant to remodel or redesign your home? Find inspiration with Hover\u2019s free home design tools to see what your potential project will look like ahead of time. Works for both exterior and interior remodeling projects. Hover can help you design and build your dream home.\r\n\r\nQuestions? Get in touch anytime: support@hover.to",
    "descriptionHTML": "The one app to scope and sell every construction project. All your trades. All your people. All in one place. Contractors, adjusters, and homeowners trust Hover to get the job done.<br><br>For Construction Pros:<br>Measure everything. Get detailed, to-the-inch accurate exterior and interior home measurements from just 8 smartphone photos or by uploading a blueprint plan. No measuring tape or tracing required. For roof area, roof pitch, roof area, siding, soffits, eaves, fascia, trim, gutters, windows, doors, and more.<br><br>Document anything. Easily and consistently capture project notes, annotations, and photos at any point during the job. Leverage detailed templates covering inspections, liability, punchlists, team hand-offs, and more\u2014or create your own custom templates.<br><br>Design to sell. From inspiration tools powered by AI to interactive 3D home models, all from photos or a blueprint upload. Visualize your projects, the products you sell, share it with anyone, or export it as a BIM file for other applications. And when you\u2019re ready, add all the final touches like landscaping with photo-realistic rendered home designs.<br><br>Takeoffs in two clicks. Generate ready-to-order Material Lists directly from Hover&#39;s measurements. Access over a hundred customizable building material templates, built by industry experts and from the most trusted brands, to generate complete Material Lists\u2014without number crunching or manual data entry. You can mix materials, trades, and even submit building material orders digitally to your local supplier.<br><br>For Homeowners:<br>Working with an insurance company? Hover helps streamline your underwriting or claims process.<br><br>Want to remodel or redesign your home? Find inspiration with Hover\u2019s free home design tools to see what your potential project will look like ahead of time. Works for both exterior and interior remodeling projects. Hover can help you design and build your dream home.<br><br>Questions? Get in touch anytime: support@hover.to",
    "summary": "Scope and sell every project. For contractors, adjusters, and homeowners.",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 833628,
    "score": 3.2913387,
    "ratings": 1469,
    "reviews": 787,
    "histogram": [
        450,
        103,
        137,
        114,
        658
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "HOVER",
    "developerId": "HOVER",
    "developerEmail": "support@hover.to",
    "developerWebsite": "http://www.hover.to",
    "developerAddress": null,
    "privacyPolicy": "https://hover.to/privacy",
    "genre": "Productivity",
    "genreId": "PRODUCTIVITY",
    "categories": [
        {
            "name": "Productivity",
            "id": "PRODUCTIVITY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/-GxTPngfc-YGMV7Ns1YJ16SEiZPe_g9WK_fC3b9Hk3Lnzl-bRAmNFlX4cZb1iyqk80o",
    "headerImage": "https://play-lh.googleusercontent.com/Fh7Yf8ouU1Q0vCtgqEM-plRSB9-yw4txMTJjqsjED_vqqcnvArHF0Eof8dVqa2yTSA",
    "screenshots": [
        "https://play-lh.googleusercontent.com/f7qacvVPxqouESBr5TAE4o7zcMD_ntUUn_6ZpPNZrYmPzbiF_G20_lzYD_axKjyOnVA",
        "https://play-lh.googleusercontent.com/a3zzJKzeGuNGQY8rEOQNHLWqfSkTHj5l6nlw9DSlT4emfXNYDkfEErhT5dOMOI8FMGR6",
        "https://play-lh.googleusercontent.com/eERdEINQTMXVgySccuQJjY_c2vhs_79OZqI31ATMDt3xT5Cfj6ca3a6UpizXuAthw4Y",
        "https://play-lh.googleusercontent.com/vB1Usob_bRImBs5kK_cGbQFQmlyPQ7L5U4aAg0LaDn6wH9y7KiV_OmH_sDHntpoyCv4",
        "https://play-lh.googleusercontent.com/-1u0cx4JUFbGudOSf5M9WCAWUn0l25dBCTJyGNCpX5ZFLIsim_SBvx8vZaZikzERUW0",
        "https://play-lh.googleusercontent.com/oGDVFHB-GgJhbZOdX0DZVzjzUg6WiIxJt99A21zpHHV7wYtze3w8-acEIHn2JJOWMnc",
        "https://play-lh.googleusercontent.com/S6acbOv1H5rLq8o7bPjCcQPAhIC4si4r1E3gZkBK_bS_pJktFWvqYyrobaHBoviIFss",
        "https://play-lh.googleusercontent.com/8ExNI9PDdY6e-M3wo0wCNQcMk_DP6E2LAa4EHaIc0xEQLGhJDWV3cX3z_i-ZApXP5ps",
        "https://play-lh.googleusercontent.com/UdiIn6gXM4I4cTNnMEeCWnygfg42POqfq3lTlCP2QwSmZDmTb78sCBKXkdb1upidCy0",
        "https://play-lh.googleusercontent.com/gKQoS_SGu2eMm31t1Bj5_LCm09IHHwMNuUfNEtP1Ery_tT2HLm6TXuRZejuMFr-IJw",
        "https://play-lh.googleusercontent.com/3Z3jO1Hr9d36Ron3Cr-G-DBgUWJ_VsWqs8ufNQRDLnVNNcyFWXMC_vdBSq2fF5jcOQ",
        "https://play-lh.googleusercontent.com/j88JKKJ8p9dhSzdRYVMdek5JFmRaO2qJn1hPGApq8ItN939JGO-f10CijObcVYHFLBE",
        "https://play-lh.googleusercontent.com/Kigj-pJYENqVfrYEdrBVIIA_dA4rCO0sJ4Xc8Wrm2AzMwpdMqzkFP67zB86Ht9Kj3a4",
        "https://play-lh.googleusercontent.com/-tpBjT0RhrYV0gs9LlQI-Aj36lvrggCVTi6_9hMQx7GEGRV0vjlmXDsavm8KpXntkYE",
        "https://play-lh.googleusercontent.com/mz8m2chsEp8gS853DfOgnErTQngOpBsSu1pPOT80KOfF1I7xCpVVsRxXgB8kB2aAsAg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Jan 18, 2016",
    "lastUpdatedOn": "Oct 8, 2024",
    "updated": 1728417664,
    "version": "5.0.0",
    "comments": [],
    "appId": "to.hover.android.app",
    "url": "https://play.google.com/store/apps/details?id=to.hover.android.app&hl=en&gl=us"
}