{
    "title": "The Weather Channel Auto App",
    "description": "The Weather Channel Auto App provides accurate weather information for drivers and passengers and translates weather data into guidance about driving and road conditions. \r\n\r\n- Driving and safety alerts from the world's most accurate forecaster**\r\n\r\n- A home page that provides current conditions and how they impact driving. \r\n\r\n- Hourly and daily forecasts, and the radar view shows the vehicle's location as well as a stored location, such as a destination. \r\n\r\n- Follow me alerts provide location-based government alerts about severe weather.\r\n---------------------------------\r\n\r\n**The Weather Channel is the World's Most Accurate Forecaster.\r\n\r\nForecastWatch, Global and Regional Weather Forecast Accuracy Overview, 2017-2022, https://forecastwatch.com/AccuracyOverview2017-2022.",
    "descriptionHTML": "The Weather Channel Auto App provides accurate weather information for drivers and passengers and translates weather data into guidance about driving and road conditions. <br><br>- Driving and safety alerts from the world&#39;s most accurate forecaster**<br><br>- A home page that provides current conditions and how they impact driving. <br><br>- Hourly and daily forecasts, and the radar view shows the vehicle&#39;s location as well as a stored location, such as a destination. <br><br>- Follow me alerts provide location-based government alerts about severe weather.<br>---------------------------------<br><br>**The Weather Channel is the World&#39;s Most Accurate Forecaster.<br><br>ForecastWatch, Global and Regional Weather Forecast Accuracy Overview, 2017-2022, https://forecastwatch.com/AccuracyOverview2017-2022.",
    "summary": "Bring the power of The Weather Channel with you on the road.",
    "installs": "10,000+",
    "minInstalls": 10000,
    "realInstalls": 39050,
    "score": 2,
    "ratings": 14,
    "reviews": 1,
    "histogram": [
        8,
        2,
        0,
        0,
        2
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": false,
    "inAppProductPrice": null,
    "developer": "The Weather Channel",
    "developerId": "5938833519207566184",
    "developerEmail": "twc-auto-support@weather.com",
    "developerWebsite": "http://www.weather.com",
    "developerAddress": "1001 Summit Blvd\nBrookhaven, GA 30319",
    "privacyPolicy": "https://weather.com/en-US/twc/privacy-policy",
    "genre": "Weather",
    "genreId": "WEATHER",
    "categories": [
        {
            "name": "Weather",
            "id": "WEATHER"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/JugLjQB3Tp_dEeK0rPhVevI1tw42bKopUgtdvqz3Sf27YTCak0s1EcsYcgEnIXNbtg",
    "headerImage": "https://play-lh.googleusercontent.com/mlBNy_iDtg-1hj4XGJORoJLuoI7h1xC7d71IP8SONgkHdtevV0EiNLWpIX_ul4IKSHQ",
    "screenshots": [
        "https://play-lh.googleusercontent.com/aTFUk7GqKvnBIzWIlzwQ8yHsCODsVoZvhJHYg_DqRZb7hZk0QZJXdaMWShOVBzb9jYw",
        "https://play-lh.googleusercontent.com/aTd4k8q7EV95_qlP_iWfyNrxZaoQ3TyM2lPoqlU8TNmnihMJSjUUOqMy5w1JTLaqEx4",
        "https://play-lh.googleusercontent.com/fLGS3MR0Q5V-KC1VHGg3EoDAS9pWBdt0s9YiSUrKmlfa3LQCsaLWHYRQDOijhbGFzTM",
        "https://play-lh.googleusercontent.com/Tq8YaL_1DqF_q2ibyDxq15tHEqVzW3PEkQbWQ9ldr2DqIeax4jHVVgQMYB22Wig_G34",
        "https://play-lh.googleusercontent.com/m5w93frYVIra9Zjm3_xjrfc8n-iMSk9sT22ZOCCsmJy7Ov854QgnTuZPnhw2ZMMcI3w",
        "https://play-lh.googleusercontent.com/bJ4OJfcp8e15FQg8zuhwZdIIfm1-peOEMm6D6NmnCvB3lQFmLLpPQBnJsQ1OLiWD9lg",
        "https://play-lh.googleusercontent.com/qQlk4hSXZiTzcwhVkgZyyfe3eEz1n5UYDT10pQmewcxEP6JtwikN4HwUAT5MjtkCam1j",
        "https://play-lh.googleusercontent.com/QZiQVIIRsaqE_kfxs-fBY55l3D4REzWNfFTNq-iHuBLm_cS1WkUxiY1RhElRxAGtvg",
        "https://play-lh.googleusercontent.com/sPqmV6FBzQXe8ls4X_RsQPcA2TH4xB81AciizvpXcsL9bIP23uTFPNCgDiOE8ZF7_wE",
        "https://play-lh.googleusercontent.com/voGnj2ZrcbdfaR-NiEn24g_Wi8kdx-5zSulJvfs1Z2fQvE1o7lilDMLoGN36qUHWTQ",
        "https://play-lh.googleusercontent.com/1VZbGL4Og_nAkgavu5wRpnxwI0_bEWoSVbyJh_apdkAwhFI0eQU-x-oCYlEGqKMVTQ",
        "https://play-lh.googleusercontent.com/3z2lhPFJeLR_kfz3hf_caT6SOzBr-m8PK3xb3qLTVPcAF_tmWjiJuE69cxpfElcf7vJR",
        "https://play-lh.googleusercontent.com/ULhyBwdcUbHU0y1oBUvSUUgI9_GUAGTFSsNI-svusEUdd4XBjWXMTc8vCbBWOY_bnOCq",
        "https://play-lh.googleusercontent.com/ktNRifPQdkpgzRltiOODiRPUEwx7_Pw8sBQ4jPN448Oa7dvLBY4ZrK6b7DzZrmFN-Q",
        "https://play-lh.googleusercontent.com/E7o-CTW0hHGYc1yiAxjHJb4CthKWiUP5uP-I4vOz-ULFMJBhQfe2kJ-XYZxhQeXg2qU",
        "https://play-lh.googleusercontent.com/vIUYwBCn-03mkz6qyxIDYA-3m32rc6x_qI7HP0qPgoIW8NWZV0ia48FkTHX2CqDKpXg",
        "https://play-lh.googleusercontent.com/QO4xLx_Q7ZwSIuVnIxoLM0Pdw-io6MdpOv-7dZ3QD_HflNp6nbcRLoFS_K5bWiiRbMs",
        "https://play-lh.googleusercontent.com/9Gqh50wON62E9g8o1xPuAQCFTo59AAmrnZUsVjExZFHNmKJrBeGU1VFl0C8zY1RrZ4Q",
        "https://play-lh.googleusercontent.com/wNUzbpWmjDJtYCU_OR34-dlzzbFnRF_zWGmoeQMJfR1AmtgP3JqsNCwKhGoAh0z1FHo",
        "https://play-lh.googleusercontent.com/8VeVyZt5TFmDRFVPQLbugKlWrTq_PHI-Gxw0y1R080TzADS0xGaBsVEGxeW298sWye0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Dec 13, 2023",
    "lastUpdatedOn": "Aug 29, 2024",
    "updated": 1724929605,
    "version": "1.8.39-go",
    "comments": [],
    "appId": "twc.car.tmpl.go",
    "url": "https://play.google.com/store/apps/details?id=twc.car.tmpl.go&hl=en&gl=us"
}