{
    "title": "AI Video Editor: ShotCut AI",
    "description": "ShotCut - a pro <b>AI video editor</b>, offers intuitive AI tools and the most trending content to cater to diverse user needs. Whether a seasoned creator or a novice editor, you can use shotcut to craft unique works.\r\n\r\n\u2605 <b>AI Video Editor Tool</b>\r\n\r\n- <b>AI Captions</b>\r\nFree trial for transcribing your videos to text is now live! Experience our latest ai technology, smarter sentence segmentation, precise word segmentations, and full support across all major languages!\r\n- <b>AI Automusic</b>\r\nPost your videos to shotcut and enrich them with auto-generated music. We'll match a music set suitable for your video's style.\r\n- <b>Ai Text Generation</b>\r\n Simply upload your video, specify the platform, and our Ai crafts powerful titles, hashtags, and descriptions for maximum engagement.\r\n\r\n\u2605 <b>Basic Video Editing</b>\r\n\r\n- <b>Video reverser</b>\r\nReverse/rewind vid and play video backwards in seconds.\r\n- <b>Video cropper</b>\r\nCrop your video for free. Easily crop your video to any aspect ratios.\r\n- <b>Video cutter & splitter</b>\r\nCut and split larger video into clips. \r\n- <b>Video merger & combiner</b>\r\nA free merge tool to combine video clips together.\r\n- <b>Video converter</b>\r\nConvert video to HD quality or MP3  audio. Export video without watermark.\r\n- <b>Video eraser</b>\r\nVideo editor no watermark. Remove watermark from video.\r\n- <b>Video sound/audio editor</b>\r\nExtract audio from video and edit audio track of your video. \r\n\r\n\u2605 <b>Pro Video Editing</b>\r\n\r\n- <b>Add music to video</b>\r\nAdd audio, songs, voice over, and sound effects to video for free. The best video maker with music.\r\n- <b>Stop motion</b>\r\nCreate easy stop motion video animations with just your phone! \r\n- <b>Slow motion</b>\r\nSlow down your videos and create cool slo mo effects online. \r\n- <b>Blur video</b>\r\nAdd blur/mosaic to video. Pixelate videos.\r\n- <b>PIP</b>\r\nCreate a Picture in Picture and overlay video like a pro.\r\n- <b>Video effects & filters</b>\r\nTransition effects for videos, slow mo fx, bold glamour filter, hyperlapse, and etc. ShotCut is loaded with reel templates for Instagram & effect house templates for TikTok. \r\n- <b>Video stabilizer</b>\r\nStabilize shaky footage for free. Remove the effect of camera shake from captured videos.\r\n- <b>Green screen editor</b>\r\nRemove a selected color from video with the chroma key tehnique.\r\n- <b>Video background remover</b>\r\nVideo cutout. Remove background from video without green screen.\r\n\r\nAs a full-featured editing app for videos, ShotCut can be used for multi purposes:\r\n\r\n<b>Free video editor, maker, and creator</b>\r\nA free video maker to generate slideshows, movies, vlogs for TikTok, YouTube, and Instagram platforms.\r\n\r\n<b>Movie maker & editor</b>\r\nMake a movie for free with a standard 24 fps frame rate. Edit films or movies like a pro.\r\n\r\n<b>Slideshow maker</b>\r\nFree photo video slideshow maker with music and voice over. Picture video maker: convert live photo to video.\r\n\r\n<b>Free collage maker</b>\r\nMake video collage for free, layout video and photo collage as you want.\r\n\r\n<b>Slow motion video editor</b>\r\nMake slow and fast motion video from normal frame rate footage. \r\n\r\n<b>Video speed editor</b>\r\nAdjust video velocity with fast & slow motion fx. Speed up or slow down video without losing video quality.\r\n\r\n<b>Reels maker & editor</b>\r\nInstagram reel maker, Instagram editor, free reel maker, instagram video editor.\r\n\r\n<b>YouTube editor</b>\r\nThe best editing app for YouTube. Easily create vlogs and music videos.\r\n\r\n<b>TikTok editor</b>\r\nEdit videos for TikTok without CapCut video editor and Effect House.\r\n\r\n<b>Instagram post maker</b>\r\nCreate Instagram posts with a plethora of reel templates.\r\n\r\nMake the most of ShotCut as a <b>video editor</b>, <b>movie maker</b>, <b>slideshow maker</b>, or whatever you need it for!\r\n\r\n<b> Disclaimer: </b>\r\nShotCut is not affiliated, associated, sponsored, endorsed by, or in any way officially connected with YouTube, Instagram, TikTok, WhatsApp, Facebook, Twitter.\r\n \r\nStay connected with us on: https://discord.gg/DYHA9W7Xaa",
    "descriptionHTML": "ShotCut - a pro <b>AI video editor</b>, offers intuitive AI tools and the most trending content to cater to diverse user needs. Whether a seasoned creator or a novice editor, you can use shotcut to craft unique works.<br><br>\u2605 <b>AI Video Editor Tool</b><br><br>- <b>AI Captions</b><br>Free trial for transcribing your videos to text is now live! Experience our latest ai technology, smarter sentence segmentation, precise word segmentations, and full support across all major languages!<br>- <b>AI Automusic</b><br>Post your videos to shotcut and enrich them with auto-generated music. We&#39;ll match a music set suitable for your video&#39;s style.<br>- <b>Ai Text Generation</b><br> Simply upload your video, specify the platform, and our Ai crafts powerful titles, hashtags, and descriptions for maximum engagement.<br><br>\u2605 <b>Basic Video Editing</b><br><br>- <b>Video reverser</b><br>Reverse/rewind vid and play video backwards in seconds.<br>- <b>Video cropper</b><br>Crop your video for free. Easily crop your video to any aspect ratios.<br>- <b>Video cutter &amp; splitter</b><br>Cut and split larger video into clips. <br>- <b>Video merger &amp; combiner</b><br>A free merge tool to combine video clips together.<br>- <b>Video converter</b><br>Convert video to HD quality or MP3  audio. Export video without watermark.<br>- <b>Video eraser</b><br>Video editor no watermark. Remove watermark from video.<br>- <b>Video sound/audio editor</b><br>Extract audio from video and edit audio track of your video. <br><br>\u2605 <b>Pro Video Editing</b><br><br>- <b>Add music to video</b><br>Add audio, songs, voice over, and sound effects to video for free. The best video maker with music.<br>- <b>Stop motion</b><br>Create easy stop motion video animations with just your phone! <br>- <b>Slow motion</b><br>Slow down your videos and create cool slo mo effects online. <br>- <b>Blur video</b><br>Add blur/mosaic to video. Pixelate videos.<br>- <b>PIP</b><br>Create a Picture in Picture and overlay video like a pro.<br>- <b>Video effects &amp; filters</b><br>Transition effects for videos, slow mo fx, bold glamour filter, hyperlapse, and etc. ShotCut is loaded with reel templates for Instagram &amp; effect house templates for TikTok. <br>- <b>Video stabilizer</b><br>Stabilize shaky footage for free. Remove the effect of camera shake from captured videos.<br>- <b>Green screen editor</b><br>Remove a selected color from video with the chroma key tehnique.<br>- <b>Video background remover</b><br>Video cutout. Remove background from video without green screen.<br><br>As a full-featured editing app for videos, ShotCut can be used for multi purposes:<br><br><b>Free video editor, maker, and creator</b><br>A free video maker to generate slideshows, movies, vlogs for TikTok, YouTube, and Instagram platforms.<br><br><b>Movie maker &amp; editor</b><br>Make a movie for free with a standard 24 fps frame rate. Edit films or movies like a pro.<br><br><b>Slideshow maker</b><br>Free photo video slideshow maker with music and voice over. Picture video maker: convert live photo to video.<br><br><b>Free collage maker</b><br>Make video collage for free, layout video and photo collage as you want.<br><br><b>Slow motion video editor</b><br>Make slow and fast motion video from normal frame rate footage. <br><br><b>Video speed editor</b><br>Adjust video velocity with fast &amp; slow motion fx. Speed up or slow down video without losing video quality.<br><br><b>Reels maker &amp; editor</b><br>Instagram reel maker, Instagram editor, free reel maker, instagram video editor.<br><br><b>YouTube editor</b><br>The best editing app for YouTube. Easily create vlogs and music videos.<br><br><b>TikTok editor</b><br>Edit videos for TikTok without CapCut video editor and Effect House.<br><br><b>Instagram post maker</b><br>Create Instagram posts with a plethora of reel templates.<br><br>Make the most of ShotCut as a <b>video editor</b>, <b>movie maker</b>, <b>slideshow maker</b>, or whatever you need it for!<br><br><b> Disclaimer: </b><br>ShotCut is not affiliated, associated, sponsored, endorsed by, or in any way officially connected with YouTube, Instagram, TikTok, WhatsApp, Facebook, Twitter.<br> <br>Stay connected with us on: https://discord.gg/DYHA9W7Xaa",
    "summary": "AI editing app for videos, slideshows, and movies.Pro video editor & maker.",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 27654220,
    "score": 4.5187907,
    "ratings": 267814,
    "reviews": 4161,
    "histogram": [
        22959,
        5668,
        5028,
        9836,
        224255
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$4.99 - $99.99 per item",
    "developer": "Shotcut Video Workshop",
    "developerId": "8339405244398676704",
    "developerEmail": "support-shotcut-android@shotcut.app",
    "developerWebsite": "https://shotcut.app",
    "developerAddress": null,
    "privacyPolicy": "https://shotcut.app/privacy-policy/",
    "genre": "Video Players & Editors",
    "genreId": "VIDEO_PLAYERS",
    "categories": [
        {
            "name": "Video Players & Editors",
            "id": "VIDEO_PLAYERS"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/zlbmkLIdtFB5zvs-JagpcBzkXw-veFD2tILWqwqkuzkodeNY1RcpgYjN9H7DwOxglw0",
    "headerImage": "https://play-lh.googleusercontent.com/QPe_M7MpskpihK1qWkVq02Zbd8BS0xlxq62x2x24UGd1orDHVJVrGDhiNUOKDFf8mBM",
    "screenshots": [
        "https://play-lh.googleusercontent.com/GBt8_UNoAPeEai7Fm30KJfYSlKYsS-8oRPAeY6Q-KUHdD4maBOiF1Fm31FN2XVNrjA",
        "https://play-lh.googleusercontent.com/OIrbaxPCWXxaQ2Z8pUBYyXVdlaQPTRgRqgmshB1jHzAa7fqDrMUkIpkjB5bjatS7Mfg",
        "https://play-lh.googleusercontent.com/2ApEsXngbVBxsHxDu-EZXkrW-sumSmNIVH053L8HIW50T6zJFLizz4JJYDtvx07XNQXJ",
        "https://play-lh.googleusercontent.com/yydEPNYLshqO7k4VUL7pVCcoFSwit-o57uaSkG0A_K8mElUauohaNPqy4QsaaZoV7eI",
        "https://play-lh.googleusercontent.com/P9mVOk7R1Ho5wGtNfIbJJpYg-Kik-zU8gm-VK6I6GP4Kr7GnGUgxg9J76lskYjyvAt8",
        "https://play-lh.googleusercontent.com/y9eDzEjI4CY1tIW4s4uWdTbzzuy84X_z4dUp9jzNZAVzCq7zXywScP9Qlx8we96CWQ",
        "https://play-lh.googleusercontent.com/uaxcLak6CMoI1wLSLh78ed0sY3Z8cjJEMdNeYay90tlMW3r1x8IWdwLs2O66W2s_3JE",
        "https://play-lh.googleusercontent.com/qo3TkL8n63ZRMkF9P7tlUVLsUQ46wK3hw6QDGRQYlhp6CAyl0MvbhPnbRB0fkJyfg0w"
    ],
    "video": "https://www.youtube.com/embed/2_lQMGwtqf8?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/QPe_M7MpskpihK1qWkVq02Zbd8BS0xlxq62x2x24UGd1orDHVJVrGDhiNUOKDFf8mBM",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Apr 28, 2021",
    "lastUpdatedOn": "Oct 22, 2024",
    "updated": 1729587930,
    "version": "1.80.2",
    "comments": [],
    "appId": "video.editor.videomaker.effects.fx",
    "url": "https://play.google.com/store/apps/details?id=video.editor.videomaker.effects.fx&hl=en&gl=us"
}