{
    "title": "Reface: Face Swap AI Photo App",
    "description": "<b>Reface: The Ultimate AI-Powered Face Swap & Photo Generator!</b>\r\nUnlock a world of creativity and fun with our app, the most advanced face swap app and AI photo generator! Whether you want to swap faces, generate AI pictures and headshots, create future baby images, or edit your photos and videos with funny filters, Reface has everything you need to make your life easier.\r\n\r\n\ud83c\udf1f <b>Transform Your Photos & Videos Instantly!</b>\r\n- Use Reface as a face swap app to change faces on photos and videos with a single tap. \r\n- Faceswap into friends, characters on any picture.\r\n- Generate professional headshots with our AI photo editor.\r\n- Discover our future baby generator to see what will your baby look like!\r\n- Apply fun and funny face filters, or change your hairstyle, hair color, and more.\r\n- Try gender swaps, face morphing, and create hilarious memes using our face app.\r\n\r\n\ud83d\uddbc\ufe0f <b>Advanced AI Photo Generator Features</b>:\r\n- Customize every detail of your photos with our AI photo editor\u2014change hair color, smooth skin, or enhance facial features.\r\n- Create stunning AI images and headshots with our AI headshot generator.\r\n- Make your photos unique with effects like age change, gender swap, and more.\r\n- Perfect your selfies with advanced tools like teeth retouching, blemish remover. \r\n- Animate your pictures: Bring them to life with AI-powered animations that make them talk, sing, or laugh!\r\n\r\n\ud83c\udfa5 <b>AI Video Generator</b>:\r\n- Edit and enhance your videos with face swaps, funny effects, and filters.\r\n- Apply changes to a single frame or the entire video in one go. Create Pro headshots, swap backgrounds, or add funny epik effects instantly!\r\n- Make your videos stand out with AI-powered enhancements and creative tools.\r\n\r\n\ud83d\udc84<b>Makeover Your Selfies</b>:\r\n- Try face retouch effects, change hair color, and reshape facial features with a few taps.\r\n- Highlight your cheekbones, reshape your jawline, or add a tan for a sun-kissed look.\r\n- Use our AI photo editor to add glamor to your photos, create professional headshots, or simply retouch your selfies.\r\n\r\n\ud83d\udd04 <b>Explore Unique Tools</b>:\r\n- Hairstyle Try On: Change your hairstyle in any photo with just one tap!\r\n- AI Headshot Generator: Transform selfies into professional headshots or fun, creative avatars.\r\n- AI Future Baby Generator: Imagine your future baby\u2019s face with our AI generator tool.\r\n- Video Face Editor: Animate photos, make them talk, sing, or dance with advanced faceswap effects.\r\n\r\n\ud83d\udc65<b>Connect with the World</b>:\r\n- Share your face swaps, AI avatars, memes, and funny videos directly on social media.\r\n- Enjoy daily updates with new filters, effects, and creative tools to keep your content fresh and engaging.\r\n\r\n\u2728<b>Additional Features</b>:\r\n- Create AI avatars and headshots from any photo.\r\n- Perform gender swaps, pet swaps, or try out new hair colors and styles.\r\n- Use photo retouching tools to enhance your natural beauty and correct imperfections.\r\n- Get creative with meme creators, GIF makers, and more!\r\n\r\n\ud83c\udf0d Join Millions of Users Worldwide! Reface is loved by millions in over 100 countries for its unique AI technology and creative features. Join our community and see why it\u2019s the best face swap and AI photo editor app on the market!\r\n\r\n--\r\nIn case of any questions, issues, or collaboration requests, contact us at hi@Reface.app\r\n\r\nTerms and Conditions: https://Reface.app/terms/\r\nPrivacy Policy: https://Reface.app/privacy-policy/",
    "descriptionHTML": "<b>Reface: The Ultimate AI-Powered Face Swap &amp; Photo Generator!</b><br>Unlock a world of creativity and fun with our app, the most advanced face swap app and AI photo generator! Whether you want to swap faces, generate AI pictures and headshots, create future baby images, or edit your photos and videos with funny filters, Reface has everything you need to make your life easier.<br><br>\ud83c\udf1f <b>Transform Your Photos &amp; Videos Instantly!</b><br>- Use Reface as a face swap app to change faces on photos and videos with a single tap. <br>- Faceswap into friends, characters on any picture.<br>- Generate professional headshots with our AI photo editor.<br>- Discover our future baby generator to see what will your baby look like!<br>- Apply fun and funny face filters, or change your hairstyle, hair color, and more.<br>- Try gender swaps, face morphing, and create hilarious memes using our face app.<br><br>\ud83d\uddbc\ufe0f <b>Advanced AI Photo Generator Features</b>:<br>- Customize every detail of your photos with our AI photo editor\u2014change hair color, smooth skin, or enhance facial features.<br>- Create stunning AI images and headshots with our AI headshot generator.<br>- Make your photos unique with effects like age change, gender swap, and more.<br>- Perfect your selfies with advanced tools like teeth retouching, blemish remover. <br>- Animate your pictures: Bring them to life with AI-powered animations that make them talk, sing, or laugh!<br><br>\ud83c\udfa5 <b>AI Video Generator</b>:<br>- Edit and enhance your videos with face swaps, funny effects, and filters.<br>- Apply changes to a single frame or the entire video in one go. Create Pro headshots, swap backgrounds, or add funny epik effects instantly!<br>- Make your videos stand out with AI-powered enhancements and creative tools.<br><br>\ud83d\udc84<b>Makeover Your Selfies</b>:<br>- Try face retouch effects, change hair color, and reshape facial features with a few taps.<br>- Highlight your cheekbones, reshape your jawline, or add a tan for a sun-kissed look.<br>- Use our AI photo editor to add glamor to your photos, create professional headshots, or simply retouch your selfies.<br><br>\ud83d\udd04 <b>Explore Unique Tools</b>:<br>- Hairstyle Try On: Change your hairstyle in any photo with just one tap!<br>- AI Headshot Generator: Transform selfies into professional headshots or fun, creative avatars.<br>- AI Future Baby Generator: Imagine your future baby\u2019s face with our AI generator tool.<br>- Video Face Editor: Animate photos, make them talk, sing, or dance with advanced faceswap effects.<br><br>\ud83d\udc65<b>Connect with the World</b>:<br>- Share your face swaps, AI avatars, memes, and funny videos directly on social media.<br>- Enjoy daily updates with new filters, effects, and creative tools to keep your content fresh and engaging.<br><br>\u2728<b>Additional Features</b>:<br>- Create AI avatars and headshots from any photo.<br>- Perform gender swaps, pet swaps, or try out new hair colors and styles.<br>- Use photo retouching tools to enhance your natural beauty and correct imperfections.<br>- Get creative with meme creators, GIF makers, and more!<br><br>\ud83c\udf0d Join Millions of Users Worldwide! Reface is loved by millions in over 100 countries for its unique AI technology and creative features. Join our community and see why it\u2019s the best face swap and AI photo editor app on the market!<br><br>--<br>In case of any questions, issues, or collaboration requests, contact us at hi@Reface.app<br><br>Terms and Conditions: https://Reface.app/terms/<br>Privacy Policy: https://Reface.app/privacy-policy/",
    "summary": "Photo Retouch & Enhancer: Funny Videos, AI Headshot Generator and Hair Filters",
    "installs": "100,000,000+",
    "minInstalls": 100000000,
    "realInstalls": 142223555,
    "score": 3.7370365,
    "ratings": 1675593,
    "reviews": 53905,
    "histogram": [
        416309,
        59139,
        65327,
        142822,
        991959
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$0.99 - $79.99 per item",
    "developer": "NEOCORTEXT, INC.",
    "developerId": "5227104178004548866",
    "developerEmail": "hi@reface.ai",
    "developerWebsite": "https://reface.ai/",
    "developerAddress": "251 Little Falls Drive, Wilmington, New Castle County, Delaware, 19808, USA",
    "privacyPolicy": "https://hey.reface.ai/privacy/",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/_ha0T5FBMi0gu2zfALowJsgBHIvCVm6rHxNwBdqNs2bOm1FXKSX7NqSHP_YC6VTnbHU",
    "headerImage": "https://play-lh.googleusercontent.com/W-EMt3QH-N5TdB-iBhbP-mo_K6w-LKMP7oSTlKrzX1KKsWgi9mngky3Xx3U77TA9lJmF",
    "screenshots": [
        "https://play-lh.googleusercontent.com/YGhkeq2Bl-mgnumH0sZrJOiBz78fuPihIs5c-PrHYn5cwTSxpyyNZOha4B2G60qv6GQ",
        "https://play-lh.googleusercontent.com/In6XOSEuBBKhFGY-92jyNYNV-k28HoTvS6Ri-Gi-u2iUE0wm1Yn9GmWx99x4ZP4f0Do",
        "https://play-lh.googleusercontent.com/Z7hQB_k05g6IOg4glISqjvK-MAhpGw1AzTo4PJxqSxkT4HV-8ep_jDfVUh1ZsZt-xmw",
        "https://play-lh.googleusercontent.com/OWY6arxfChvzwx88DPZu6YSrFZRYsolDtX_IaPqJXl_yzclNskVZ9zfLMuaOvqrtB5E",
        "https://play-lh.googleusercontent.com/p0vHSu_L7VAPBw85OmMlO0mYYvWf_wb6sWtjftli3jRLwalHNxtUGkfiMhMzMekjl8Jn",
        "https://play-lh.googleusercontent.com/I7xSc-rTd0MF9U28U5vmdJPk0QSIdJNMeNdTf0SKtEiDTUDk5AiNmJNBEvzRPdpE-q4",
        "https://play-lh.googleusercontent.com/fT04RXZ-5c1OguODndRZPJjAI0CPugBprAfpyWeLVDNOSV19fZVGpNsLncyxXLKtcQ",
        "https://play-lh.googleusercontent.com/S1dM5IWEB-AB_bctuLT_thEj-TNl3JhDqzUVt94ojbqkWvzktQuhLjqmuoGOHfAg46A",
        "https://play-lh.googleusercontent.com/ZftDd2FGQyjZffl_fD8lw4PXWAd0H4KeyHQLrg7KeSDDO7FcHlykqTPkmdVObc57gWs",
        "https://play-lh.googleusercontent.com/1v5GygS_-L5AqT4Fatd-pLyZONhIIu050zzicq21EjmlYP-Pwgz_JotAu_y9odzTbw",
        "https://play-lh.googleusercontent.com/3NwM6FNYzAAj5awgRRbH4l_euG6mBPKqDHXJzmV93l4nHigF7OnkP489MnwffkgUWEE",
        "https://play-lh.googleusercontent.com/oGMpWvBYbaf-N0zZxyB0nAPFWXjb70YzhE2IVxjKLx94DKUNCJVCYfdVacrmMSaGOspg",
        "https://play-lh.googleusercontent.com/yAazPiPq2RcNSjVgFqs3rDCpHQJ4Jbo8N1nXYpTPblLBZf89NrOuQ7s8ht6qGsR_1V4",
        "https://play-lh.googleusercontent.com/ybG2OVRJKP3sklDLrYT_arbsQoi1II3W4MPUX3sNy5ZytzFhDguYUNa7KMxSyOPk8wjV",
        "https://play-lh.googleusercontent.com/TbnzXhi6XMjeNXHs0oTqrYfyfZviYX0iPWN5uxu3tc_7b7EBu0wWlyuXSM2tquJBA9E",
        "https://play-lh.googleusercontent.com/WB2BUqU9JOqMS56Lu-a2EVdPfoz7zOl_EE4jFyS1TkIbcKIf48j4lGA05EbuQOCqeZjE",
        "https://play-lh.googleusercontent.com/4oOl8apOy_x_EcrykfNddyZ3wGEwPAFIXuvTxtpsfl7kprF_QgmobKGEhk32oACL8vY_",
        "https://play-lh.googleusercontent.com/derBXEmMMf89jf79P0zbZr29MlaO82G0ceSjthXzxQNXU4URTe2fAZ6727sC-0jb_Mg"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Mature 17+",
    "contentRatingDescription": "Violence, Blood, Sexual Content, Use of Drugs, Strong Language, Crude Humor",
    "adSupported": true,
    "containsAds": true,
    "released": "Dec 23, 2019",
    "lastUpdatedOn": "Oct 20, 2024",
    "updated": 1729442268,
    "version": "4.22.2",
    "comments": [],
    "appId": "video.reface.app",
    "url": "https://play.google.com/store/apps/details?id=video.reface.app&hl=en&gl=us"
}