{
    "title": "Mojo: Reels and Video Captions",
    "description": "Creating trending social content has never been simpler. Mojo is an app designed to help you make amazing video content for Instagram and TikTok and more. Mojo is made in Paris and has already been downloaded by over 40 million people worldwide.\r\n\r\nTo use Mojo, simply download the app and start exploring one of our 700+ unique templates. After selecting the template you\u2019d like to edit, choose from a number of our editing features to create the perfect video. You can then easily resize and share your content to any social platform with the touch of a button.\r\n\r\nWhile editing, you can choose from a number of our top features like adding auto-captions, text effects, filters, and creating a grid. You can also select one of our trending templates which is already paired perfectly with a trending sound from Instagram and TikTok!\r\n\r\nMojo is an inclusive app made for everyone. Whether you\u2019re a creator, small business owner, photographer, or a first-time social user - there will be something for you! \r\n\r\nTake a look at our top features and why our users love them:\r\n\r\nTrending sounds templates\r\n\r\n- Choose from our unique trending sounds templates that connect directly to trending sounds on Instagram and TikTok\r\n- Get inspired in our trending sounds collection and create videos with already identified trends\r\n\r\nAuto captions\r\n\r\n- Add auto-captions to maximize your views\r\n- Select from a variety of auto-caption styles to stand out on social\r\n- Translate your captions into a different language than the one you\u2019re speaking\r\n\r\nText effects\r\n\r\n- Easily add aesthetic text effects to your videos\r\n- Select from a variety of styles like modern, retro, speech bubbles, and calls to action\r\n\r\nAll-in-one video editor\r\n\r\n- Edit all of your videos on one platform\r\n- Trim your clips, add transitions, music, text, and animated elements on Mojo\r\n\r\nBackground removal\r\n\r\n- Remove the background from any image in one tap\r\n- The perfect tool for business owners to showcase their products\r\n\r\nBrand kit\r\n\r\n- Save your brand fonts, colors, and logos to the brand kit tool\r\n- Easily stay on brand while creating your content on Mojo\r\n\r\nAI tools\r\n\r\n- Select any photo from your camera roll and watch Mojo turn it into a meme\r\n\r\nRoyalty free music\r\n\r\n- Choose from our royalty-free tracks that can be used for commercial purposes\r\n- Upload your own music and add it to any of our templates\r\n\r\nTransitions\r\n\r\n- Seamlessly add transitions to your videos to elevate visual appeal\r\n- Elevate professionalism with a variety of available transitions like zoom in, fisheye, ripped paper, camera slides in different directions, and so many more\r\n- Apply your transitions to your whole video in just one tap\r\n\r\nShare across all social platforms\r\n\r\n- Share to Instagram, TikTok, YouTube, and other social platforms in just one tap\r\n- Mojo easily resizes your content depending on the platform you\u2019re sharing to\r\n\r\nEdit the animations of all elements\r\n\r\n- Animate any element of your video and capture your viewers attention\r\n\r\nAnimated stickers and graphics\r\n\r\n- Incorporate animated stickers and graphics into your videos\r\n- Add GIFs directly in the app\r\n\r\nTerms of Use: https://www.mojo-app.com/terms-of-use\r\n\r\nWe're always open to feedback, email us yours at feedback@mojo.video.\r\n\r\nFrom Paris with love,\r\n\r\nThe Mojo Team",
    "descriptionHTML": "Creating trending social content has never been simpler. Mojo is an app designed to help you make amazing video content for Instagram and TikTok and more. Mojo is made in Paris and has already been downloaded by over 40 million people worldwide.<br><br>To use Mojo, simply download the app and start exploring one of our 700+ unique templates. After selecting the template you\u2019d like to edit, choose from a number of our editing features to create the perfect video. You can then easily resize and share your content to any social platform with the touch of a button.<br><br>While editing, you can choose from a number of our top features like adding auto-captions, text effects, filters, and creating a grid. You can also select one of our trending templates which is already paired perfectly with a trending sound from Instagram and TikTok!<br><br>Mojo is an inclusive app made for everyone. Whether you\u2019re a creator, small business owner, photographer, or a first-time social user - there will be something for you! <br><br>Take a look at our top features and why our users love them:<br><br>Trending sounds templates<br><br>- Choose from our unique trending sounds templates that connect directly to trending sounds on Instagram and TikTok<br>- Get inspired in our trending sounds collection and create videos with already identified trends<br><br>Auto captions<br><br>- Add auto-captions to maximize your views<br>- Select from a variety of auto-caption styles to stand out on social<br>- Translate your captions into a different language than the one you\u2019re speaking<br><br>Text effects<br><br>- Easily add aesthetic text effects to your videos<br>- Select from a variety of styles like modern, retro, speech bubbles, and calls to action<br><br>All-in-one video editor<br><br>- Edit all of your videos on one platform<br>- Trim your clips, add transitions, music, text, and animated elements on Mojo<br><br>Background removal<br><br>- Remove the background from any image in one tap<br>- The perfect tool for business owners to showcase their products<br><br>Brand kit<br><br>- Save your brand fonts, colors, and logos to the brand kit tool<br>- Easily stay on brand while creating your content on Mojo<br><br>AI tools<br><br>- Select any photo from your camera roll and watch Mojo turn it into a meme<br><br>Royalty free music<br><br>- Choose from our royalty-free tracks that can be used for commercial purposes<br>- Upload your own music and add it to any of our templates<br><br>Transitions<br><br>- Seamlessly add transitions to your videos to elevate visual appeal<br>- Elevate professionalism with a variety of available transitions like zoom in, fisheye, ripped paper, camera slides in different directions, and so many more<br>- Apply your transitions to your whole video in just one tap<br><br>Share across all social platforms<br><br>- Share to Instagram, TikTok, YouTube, and other social platforms in just one tap<br>- Mojo easily resizes your content depending on the platform you\u2019re sharing to<br><br>Edit the animations of all elements<br><br>- Animate any element of your video and capture your viewers attention<br><br>Animated stickers and graphics<br><br>- Incorporate animated stickers and graphics into your videos<br>- Add GIFs directly in the app<br><br>Terms of Use: https://www.mojo-app.com/terms-of-use<br><br>We&#39;re always open to feedback, email us yours at feedback@mojo.video.<br><br>From Paris with love,<br><br>The Mojo Team",
    "summary": "All-in-one social content maker: Auto subtitles, video editor, story & collages",
    "installs": "10,000,000+",
    "minInstalls": 10000000,
    "realInstalls": 16063019,
    "score": 4.4755244,
    "ratings": 224283,
    "reviews": 1492,
    "histogram": [
        14496,
        5067,
        8603,
        27028,
        168968
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$9.99 - $39.99 per item",
    "developer": "Archery Inc.",
    "developerId": "6305710061287744043",
    "developerEmail": "feedback@mojo.video",
    "developerWebsite": "https://www.mojo-app.com/",
    "developerAddress": "Archery Inc.\n86 Bd de S\u00e9bastopol\n75003 Paris\nFrance",
    "privacyPolicy": "https://www.mojo-app.com/privacy-policy",
    "genre": "Photography",
    "genreId": "PHOTOGRAPHY",
    "categories": [
        {
            "name": "Photography",
            "id": "PHOTOGRAPHY"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/wH06fKLDUv4u8EcIdkFHZaihw2VgCMTwF9WCRAQgP1QByCd_ahRFmFToyRtVv7etKAg",
    "headerImage": "https://play-lh.googleusercontent.com/1NMnnf7buPuty9AUjpVEyyWv2GwKqRZGXpx4032Azj1Ql0UXK2Njkfju5iEyx5v96pv-",
    "screenshots": [
        "https://play-lh.googleusercontent.com/7JZmPV_nKi7z45udkcVEulUzjZm1Vn5Iat1TfY2DU35hhbfrM5_0-y3y1WTY3RoGn3Y",
        "https://play-lh.googleusercontent.com/drofD6Fj_XxQpG5ju7hnVgSh0EooxfxH4vp4Fr7E5VSRYCzQT7T1psXTGm5K4GqWIHI",
        "https://play-lh.googleusercontent.com/P9JlCl73iCLfUVNWJwjvS0ifGxm3up49lrr8STf4tV9dnuVNEtn_WiAM82aZsKJedtI",
        "https://play-lh.googleusercontent.com/m2TBUuoE_MrHxmAGYu_jUGzS2HkRaDo5pOTD52XeBQzav6MnjrCOe1riUCUi1IhmEg",
        "https://play-lh.googleusercontent.com/DJKJvtF-Ro4rJVVkTnZr261O1VGGNF3PrMkLzLy7N3AgWYexX-vmgOEQWyqcWpEKkA",
        "https://play-lh.googleusercontent.com/rj5tET8Em56CbFK22U54qeUZFLf5WN0x6cLyPiiXDBfX77SvkcHh-djum8oRXcHJuqo",
        "https://play-lh.googleusercontent.com/cuLw9geiKTDyYDqdgp9obcmZmrtIHdZgyZG30yg7TPrccIHSwKnAffeBv3ztyLtNRy8",
        "https://play-lh.googleusercontent.com/UngkLiFHOxTuv5X6pOu-cLcIy2BkHvHTchCVXXXLGRvcu1hiaKTpP2XFNybeLb45mgk"
    ],
    "video": "https://www.youtube.com/embed/nj0qLRF8N6k?ps=play&vq=large&rel=0&autohide=1&showinfo=0",
    "videoImage": "https://play-lh.googleusercontent.com/1NMnnf7buPuty9AUjpVEyyWv2GwKqRZGXpx4032Azj1Ql0UXK2Njkfju5iEyx5v96pv-",
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": false,
    "containsAds": false,
    "released": "Sep 16, 2019",
    "lastUpdatedOn": "Oct 14, 2024",
    "updated": 1728924235,
    "version": "2.67.2",
    "comments": [],
    "appId": "video.mojo",
    "url": "https://play.google.com/store/apps/details?id=video.mojo&hl=en&gl=us"
}