{
    "title": "Web Scan - Dual Accounts",
    "description": "<b>WELCOME TO web Scan Dual Accounts Qr Code Scanner App</b>\r\nWeb Scan Dual Accounts Qr Code Scanner App is world top rated app in the world. Web Scanner Dual Accounts Qr Code Scanner App is the fastest and efficient tool that makes it easy to run single web Scan - Dual Accounts web account on multiple android devices. web Scan Dual Accounts Qr Code Scanner App web scanner accounts also work as clone application to clone multiple web Scan - web Scan Dual Accounts Qr Code Scanner App on one device without downloading multi accounts web Scan - Dual Accounts web apps. With web Scan Dual Accounts Qr Code Scanner App amazing features, you can also browse multi account chats and send direct messages to other without adding number in contact list. \r\n\r\nWeb Scan Dual Accounts Qr Code Scanner App also allow its users to download and save images and video files from statuses to their devices. Web Scan Dual Accounts Qr Code Scanner app also work as dual accounts.\r\n\r\nFeatures of WEB Scan - Dual Accounts Qr Code Scanner App\r\n\r\n\t\u2022\tRun single WEB Scan Dual Accounts Qr Code Scanner account on multiple devices.\r\n\r\n\t\u2022\tClone multiple WEB Scan Dual Accounts Qr Code Scanner App web accounts to run or create parallel space in a single device.\r\n\r\n\t\u2022\twith the WEB Scan Dual Accounts Qr Code Scanner App you can download images, text and videos from others \r\n\r\n\t\u2022\tWEB Scan Dual Accounts Qr Code Scanner App you can direct chat send and receive messages from other without saving numbers to contact list.\r\n\r\n\t\u2022\tWEB Scan Dual Accounts Qr Code Scanner App cleaner to remove all of the junk or spam files from the WEB Scan Dual Accounts Qr Code Scanner App web accounts\r\n\r\n\t\u2022\tWeb Scan Dual Accounts Qr Code Scanner App also works as dual accounts.\r\n\r\nwith this web Scan Dual Accounts Qr Code Scanner App you can use multiple web accounts.\r\n\r\n\r\nWEB Scan Dual Accounts Qr Code Scanner App\r\n\r\nWEB Scan Dual Accounts Qr Code Scanner App has the fastest scanning function to scan QR code Scanner from WEB Scan Dual Accounts Qr Code Scanner App web account to run multiple accounts parallel accounts in one device. With this efficient QR Web scanner tool user can also use one WEB Scan Dual Accounts Qr Code Scanner App account in different devices. \r\n\r\nDirect Chat\r\n\r\nWEB Scan Dual Accounts Qr Code Scanner App has made chatting very easy and simple. Now WEB Scan Dual Accounts Qr Code Scanner App users are not required to save contact numbers in list to chat with them. Users can send direct messages to others by just entering their numbers there.\r\n\r\nStatus Downloader\r\n\r\nWEB Scan Dual Accounts Qr Code Scanner App also help its users in downloading images and videos from any status one liked. WEB Scan Dual Accounts Qr Code Scanner App feature add the downloaded media directly to phone gallery which users can also share with friends and family.\r\n\r\nWEB Scan Dual Accounts Qr Code Scanner App Cleaner\r\n\r\nWEB Scan Dual Accounts Qr Code Scanner App also helps in optimising device storage. With this amazing WEB Scan Dual Accounts Qr Code Scanner App cleaner feature, users can clean up device memory by removing all of the selected junk files including images, videos, and gifs from accounts to free up some space from device.\r\n\r\nWeb Scan Dual Accounts Qr Code Scanner App \r\n\r\n With the help of web Scan Dual Accounts Qr Code Scanner App you can use multiple web accounts on single device.\r\n\r\nWeb Scanner Dual Accounts Qr Code Scanner App you can scan any type of qr code scanner and barcode scanner codes.\r\n\r\nWeb Scan Dual Accounts Qr Code Scanner App you can scan any type of qr code scanner and barcode scanner and check the prices of the products.",
    "descriptionHTML": "<b>WELCOME TO web Scan Dual Accounts Qr Code Scanner App</b><br>Web Scan Dual Accounts Qr Code Scanner App is world top rated app in the world. Web Scanner Dual Accounts Qr Code Scanner App is the fastest and efficient tool that makes it easy to run single web Scan - Dual Accounts web account on multiple android devices. web Scan Dual Accounts Qr Code Scanner App web scanner accounts also work as clone application to clone multiple web Scan - web Scan Dual Accounts Qr Code Scanner App on one device without downloading multi accounts web Scan - Dual Accounts web apps. With web Scan Dual Accounts Qr Code Scanner App amazing features, you can also browse multi account chats and send direct messages to other without adding number in contact list. <br><br>Web Scan Dual Accounts Qr Code Scanner App also allow its users to download and save images and video files from statuses to their devices. Web Scan Dual Accounts Qr Code Scanner app also work as dual accounts.<br><br>Features of WEB Scan - Dual Accounts Qr Code Scanner App<br><br>\t\u2022\tRun single WEB Scan Dual Accounts Qr Code Scanner account on multiple devices.<br><br>\t\u2022\tClone multiple WEB Scan Dual Accounts Qr Code Scanner App web accounts to run or create parallel space in a single device.<br><br>\t\u2022\twith the WEB Scan Dual Accounts Qr Code Scanner App you can download images, text and videos from others <br><br>\t\u2022\tWEB Scan Dual Accounts Qr Code Scanner App you can direct chat send and receive messages from other without saving numbers to contact list.<br><br>\t\u2022\tWEB Scan Dual Accounts Qr Code Scanner App cleaner to remove all of the junk or spam files from the WEB Scan Dual Accounts Qr Code Scanner App web accounts<br><br>\t\u2022\tWeb Scan Dual Accounts Qr Code Scanner App also works as dual accounts.<br><br>with this web Scan Dual Accounts Qr Code Scanner App you can use multiple web accounts.<br><br><br>WEB Scan Dual Accounts Qr Code Scanner App<br><br>WEB Scan Dual Accounts Qr Code Scanner App has the fastest scanning function to scan QR code Scanner from WEB Scan Dual Accounts Qr Code Scanner App web account to run multiple accounts parallel accounts in one device. With this efficient QR Web scanner tool user can also use one WEB Scan Dual Accounts Qr Code Scanner App account in different devices. <br><br>Direct Chat<br><br>WEB Scan Dual Accounts Qr Code Scanner App has made chatting very easy and simple. Now WEB Scan Dual Accounts Qr Code Scanner App users are not required to save contact numbers in list to chat with them. Users can send direct messages to others by just entering their numbers there.<br><br>Status Downloader<br><br>WEB Scan Dual Accounts Qr Code Scanner App also help its users in downloading images and videos from any status one liked. WEB Scan Dual Accounts Qr Code Scanner App feature add the downloaded media directly to phone gallery which users can also share with friends and family.<br><br>WEB Scan Dual Accounts Qr Code Scanner App Cleaner<br><br>WEB Scan Dual Accounts Qr Code Scanner App also helps in optimising device storage. With this amazing WEB Scan Dual Accounts Qr Code Scanner App cleaner feature, users can clean up device memory by removing all of the selected junk files including images, videos, and gifs from accounts to free up some space from device.<br><br>Web Scan Dual Accounts Qr Code Scanner App <br><br> With the help of web Scan Dual Accounts Qr Code Scanner App you can use multiple web accounts on single device.<br><br>Web Scanner Dual Accounts Qr Code Scanner App you can scan any type of qr code scanner and barcode scanner codes.<br><br>Web Scan Dual Accounts Qr Code Scanner App you can scan any type of qr code scanner and barcode scanner and check the prices of the products.",
    "summary": "Web Scan - Dual Accounts & Chats - QR Code Scanner - QR Scanner - Direct Chat",
    "installs": "500,000+",
    "minInstalls": 500000,
    "realInstalls": 588883,
    "score": 4.4444447,
    "ratings": 1599,
    "reviews": 2,
    "histogram": [
        177,
        0,
        0,
        177,
        1243
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$1.99 - $19.99 per item",
    "developer": "WHAT'S WEB",
    "developerId": "7425311508451500983",
    "developerEmail": "proparallelspace@gmail.com",
    "developerWebsite": "https://proparallelspace.blogspot.com/",
    "developerAddress": null,
    "privacyPolicy": "https://proparallelspace.blogspot.com/2021/10/policy-this-page-is-used-to-inform.html",
    "genre": "Libraries & Demo",
    "genreId": "LIBRARIES_AND_DEMO",
    "categories": [
        {
            "name": "Libraries & Demo",
            "id": "LIBRARIES_AND_DEMO"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/XGAp3Egh3VaH1tTnxGbjuMrKQFxA89kunKXiBz_9XYlYovpVS7InUl57sH2E1Ti94A",
    "headerImage": "https://play-lh.googleusercontent.com/dRzTrD92Y_8LnMau_yGieVjz0wiueD0ok_H5WJeKIP4wLbDSTQPCkAiLTiyRNzHspPs",
    "screenshots": [
        "https://play-lh.googleusercontent.com/qMFQ83E57AESGWeeJgCCZXpTdVQJJVwibpJQ_oD3o8_U_z-JdlCgNt61VkIsPluKU9I",
        "https://play-lh.googleusercontent.com/cKXnTyV4lvQ47E6-V_Wg_DzmM6S2j8kGx4zW9-pX3huy11Xo9k5zfKu4WN1h7WPPRN4",
        "https://play-lh.googleusercontent.com/gd51ZSSYiSgtFFccIIb2rgIAT4swAPrzsC-txT2oRvEhocQwSKVjRL7hjWVNREy_Hkk",
        "https://play-lh.googleusercontent.com/wBcUfUQh-2taBspPW45Bc022irFrjNtSIR6G61qspXkqrG8PH_DfMr-gotMBenJSyg",
        "https://play-lh.googleusercontent.com/ndsMhxIWFeU0iQunpPAjqg0g-nyDlW1lpKB7nG2Qe4dAIkMjbUgl5Cejsp5OLpA7PIAR",
        "https://play-lh.googleusercontent.com/fH1UfNaDKnCBKXGWjtXHQxIKbYwiiM2h08rIylqOQfOPaM_h_B3TWZMysdlXkfSC9w",
        "https://play-lh.googleusercontent.com/FAC2uxjM3MQ94p_VXz3Eoh1Fk0Zayqte236sdDpqQ2vTJyS-mOycLD6NiEKabBheu38",
        "https://play-lh.googleusercontent.com/2d_yT9uwkw1vnve2lPeTsoBUAPamHhT2W-mGY1V8-9JUjFbptP5KVxpets7VFbKNgyQ",
        "https://play-lh.googleusercontent.com/ENlr-xNS75iW6uX7HCMbLonEAiVcHnpB04GZpzpB0iCGQAriT3O1ce3IgEE6cT_CiahF",
        "https://play-lh.googleusercontent.com/2BQ17E4stgmc6ICkr7b3zTWOP8_hjPvNs4M061sa60fSRSq6TU65gTn0NsiOcAv4cKY",
        "https://play-lh.googleusercontent.com/fLsax6BnMA5PK70Ss-s-uO7yGnQU2yGrMeoHO4XqSDTjrFUkcmnQpHTvYDhrYnE31Q",
        "https://play-lh.googleusercontent.com/74mh6HxOhHuAhYwZ39PdZdcuE_GQbPcZNMVVwJ4DVJJKSc9TUB0VDixZ9nXqTaSKztKV",
        "https://play-lh.googleusercontent.com/R2s3ETKzNuqsT8LD0w-m_1Z9wsytmb1VAe_91O4p1g943lKCUCUsNDe5E7jnnzmcJXI"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Feb 4, 2022",
    "lastUpdatedOn": "Aug 30, 2024",
    "updated": 1725015260,
    "version": "5.7",
    "comments": [],
    "appId": "whats.web.app",
    "url": "https://play.google.com/store/apps/details?id=whats.web.app&hl=en&gl=us"
}