{
    "title": "Woofz - Puppy and Dog Training",
    "description": "Welcome to Woofz\u2014our handy, all-inclusive dog training app for you and your fluffy friend!\r\n\r\nEver wondered what makes your dog tick? What do those barks really mean? Or how to help your dog get rid of bad habits and form good ones instead?\r\n\r\nLook no further! Woofz will answer all your questions to help you create a more harmonious pet-person relationship.\r\n\r\nSo, what\u2019s packed inside our puppy and dog training app?\r\n\r\n- Dog training activities \u2014 Learn tonnes of easy dog commands with step-by-step video and audio lessons.\r\n\r\n- Problem Behaviors Program - Say goodbye to barking, chewing, biting, etc.\r\n\r\n- Course Completion Certificates \u2014 Inspire yourself and your pet to new levels of dog training with course completion certificates. \r\n\r\n- Tricks and tips \u2014 Train your dog and help them learn new tricks by following simple commands\u2014sit, give paw, and more.\r\n\r\n- Profiles for each dog \u2014 Keep track of each of your pets with individual profiles, where you can monitor their health and check their dog training stats.\r\n\r\n- Doggy calendar \u2014 In this handy puppy training app, you can keep track of your dog\u2019s schedule\u2014 walks, trick lessons, dog health, vet visits, and get reminders of coming events.\r\n\r\n- Precious moments gallery \u2014 Woofz isn\u2019t just a dog training app. It\u2019s a place where you can store all your precious fluffy friend moments and accomplishments.\r\n\r\n- Helpful puppy trainer tools \u2014 Armed with the in-app dog clicker, you make training even more easier.\r\n\r\n- Walking tracker \u2014 Who said training dogs didn\u2019t involve any effort or energy? But with Woofz, you can take the guesswork out of how much your pet has walked with our built-in puppy tracker that will track those puppy-paw steps.\r\n\r\nAnd much more for training your dogs and puppies!\r\n\r\nGrab a treat and set off on an exciting journey in the dog world! You will both love it!\r\n\r\nOfficial Website - www.woofz.com",
    "descriptionHTML": "Welcome to Woofz\u2014our handy, all-inclusive dog training app for you and your fluffy friend!<br><br>Ever wondered what makes your dog tick? What do those barks really mean? Or how to help your dog get rid of bad habits and form good ones instead?<br><br>Look no further! Woofz will answer all your questions to help you create a more harmonious pet-person relationship.<br><br>So, what\u2019s packed inside our puppy and dog training app?<br><br>- Dog training activities \u2014 Learn tonnes of easy dog commands with step-by-step video and audio lessons.<br><br>- Problem Behaviors Program - Say goodbye to barking, chewing, biting, etc.<br><br>- Course Completion Certificates \u2014 Inspire yourself and your pet to new levels of dog training with course completion certificates. <br><br>- Tricks and tips \u2014 Train your dog and help them learn new tricks by following simple commands\u2014sit, give paw, and more.<br><br>- Profiles for each dog \u2014 Keep track of each of your pets with individual profiles, where you can monitor their health and check their dog training stats.<br><br>- Doggy calendar \u2014 In this handy puppy training app, you can keep track of your dog\u2019s schedule\u2014 walks, trick lessons, dog health, vet visits, and get reminders of coming events.<br><br>- Precious moments gallery \u2014 Woofz isn\u2019t just a dog training app. It\u2019s a place where you can store all your precious fluffy friend moments and accomplishments.<br><br>- Helpful puppy trainer tools \u2014 Armed with the in-app dog clicker, you make training even more easier.<br><br>- Walking tracker \u2014 Who said training dogs didn\u2019t involve any effort or energy? But with Woofz, you can take the guesswork out of how much your pet has walked with our built-in puppy tracker that will track those puppy-paw steps.<br><br>And much more for training your dogs and puppies!<br><br>Grab a treat and set off on an exciting journey in the dog world! You will both love it!<br><br>Official Website - www.woofz.com",
    "summary": "Dog training app to teach your pet! Puppy tracker and easy dog tricks trainer!",
    "installs": "1,000,000+",
    "minInstalls": 1000000,
    "realInstalls": 2200863,
    "score": 4.5238094,
    "ratings": 28141,
    "reviews": 621,
    "histogram": [
        1001,
        415,
        1672,
        4770,
        20263
    ],
    "price": 0,
    "free": true,
    "currency": "USD",
    "sale": false,
    "saleTime": null,
    "originalPrice": null,
    "saleText": null,
    "offersIAP": true,
    "inAppProductPrice": "$2.99 - $99.99 per item",
    "developer": "nove8",
    "developerId": "6483557793320664874",
    "developerEmail": "support@woofz.com",
    "developerWebsite": "https://www.woofz.com",
    "developerAddress": null,
    "privacyPolicy": "https://www.woofz.com/privacy-policy/",
    "genre": "Education",
    "genreId": "EDUCATION",
    "categories": [
        {
            "name": "Education",
            "id": "EDUCATION"
        }
    ],
    "icon": "https://play-lh.googleusercontent.com/EclKluCsMroNatS7XKf-TYIM8S0XSKyENKS8TjkY9K6U7auizIGPN46GmojnURCKUTI",
    "headerImage": "https://play-lh.googleusercontent.com/uDorwrD1Pz6ghKdPAQ9OsXu022s0aYHPrQGx1YHOdGRiz9tijIO5MsXyMfYaIuk9NZE",
    "screenshots": [
        "https://play-lh.googleusercontent.com/sANL0Txxrz-Ggiq77YEYrNYgH8pPfDgibsXl-eRl5qHvzERq7eer3OuNIPGUuImRxWc",
        "https://play-lh.googleusercontent.com/B0QF7FH6HPC_hAXSiJ66Ss5Nxh68o80CWOmhpbGGu4Bh1V-QRfX-JBL5qoK-IptAGEg",
        "https://play-lh.googleusercontent.com/BYAe9f1W-OzOLHsxfxEh4cmnKswr48aqMsxyPoXCapKKtcV4Mv1a72gOYuRcTgFYT8lN",
        "https://play-lh.googleusercontent.com/qRuXGNxnV6TvarWkw-FSI9ktfg2k51i_4zE6IGYi9Z-k4CsUaK6hQupokJzKF_urSQ",
        "https://play-lh.googleusercontent.com/mFeOQ9_7skMmaYcOUIa2QSiHZhOHb9XbE6kCyend5EEuzgh453lxge_F5POnauXDU_E",
        "https://play-lh.googleusercontent.com/dsTyrIcj-LPKFhMlfmHfZld5ROBQtF923bJYBRYP1lHbILw5Gf4WxHITcBRo3gLAdg",
        "https://play-lh.googleusercontent.com/1d--KjzH8_UTyDlD0zBW_P61UhljWYGIqcds_FQfPGSN-u59oNbPOz7imdJcyndg7AE",
        "https://play-lh.googleusercontent.com/gi1z9hSi2fKIcoTxJ7wfhNi3DRpc1tP6B1nmKzSFWR_FwXtd4u2WwIjvnpuxc1AIZK0"
    ],
    "video": null,
    "videoImage": null,
    "contentRating": "Everyone",
    "contentRatingDescription": null,
    "adSupported": true,
    "containsAds": true,
    "released": "Dec 11, 2020",
    "lastUpdatedOn": "Oct 23, 2024",
    "updated": 1729673029,
    "version": "1.49.2",
    "comments": [],
    "appId": "woofz.dog.training.app",
    "url": "https://play.google.com/store/apps/details?id=woofz.dog.training.app&hl=en&gl=us"
}